### ISSUE TITLE
Copy as To-Do has wrong URLs for messages copied from Party and Tavern

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10016]
When you use Copy as To-Do on a message from your Party or the Tavern, the URLs in the To-Do are wrong.

Currently the links are:
* `[Party name goes here](https://habitica.com/groups/guild/12345678-8050-4253-1234567890abc)`
* `[Tavern](https://habitica.com/groups/guild/00000000-0000-4000-A000-000000000000)`

They should be:
* `[Party name goes here](https://habitica.com/party)`
* `[Tavern](https://habitica.com/groups/tavern)`

**Comment by Feywood** [comment]
I'll pick this up if that's okay

**Comment by Alys** [comment]
@Feywood Thanks! Go ahead.

**Comment by Feywood** [comment]
Okay, from what I've seen so far, it seems that the copyastodomodal is used for parties, tavern and guilds and applies the same logic for each of these with the group ID. 
So that gives two options, as far as I see it:
- create a separate modal for each location you can copy from
- add in an if structure that differentiates based on the group you're copying from with guilds retaining the current structure, tavern being hardcoded with its fixed ID and parties... well I'm sure there's some form of user.party variable? 
The second seems to me the more flexible solution or at least more practical in case of future changes, but I await feedback before hopping along :rabbit:

**Comment by TheHollidayInn** [comment]
I can't remember, but if we aren't already, you can just pass the full group object to the component. Then create a factory function called `generateUrl` does:
1. if group.type === guild, return guild url
2. if group.type === party, return party url
3. if group._id === TAVERN_ID (a constant you can import) return tavern url.

**Comment by FergusonSean** [comment]
I'll give this a shot if that's cool with people :)

**Comment by paglias** [comment]
sure @FergusonSean :)
