### ISSUE TITLE
Avatars transformed into flowers don't appear next to messages in chats

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#10015]
![image of four messages by avatars with transformation buffs, all of which look fine except the flower, which doesn't show](https://user-images.githubusercontent.com/14182450/36338122-c9ac0482-1374-11e8-82d8-f4b1a492a91d.png)

Avatars transformed into flowers (with the shiny seed) don't display next to messages in chats. If they're wearing a hair flower, that flower will be visible, but the transformation itself won't.

**Comment by Alys** [comment]
Good bug report, thanks!

I think it must be because the Flower is the only one that needs to know the user's class (different flowers for different classes):
https://github.com/HabitRPG/habitica/blob/b4cbcb172b32d1a24674004367807ece90fdacbd/website/client/components/avatar.vue#L160-L166

and `stats.class` is not included in the `userStyles` that are saved to each chat message. That's an easy fix.

**Comment by dmitrytorba** [comment]
Hi, I can reproduce this locally. 
If its OK, Id like to try fixing this bug

**Comment by paglias** [comment]
Sure @dmitrytorba !

**Comment by beffymaroo** [comment]
I'm still seeing this on the production site with Shiny Seeds.
