### ISSUE TITLE
decorations cover Featured Items label in Shops > Market when zoomed in

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10037]
In Shops > Market, if you have your browser zoomed in a couple of levels, (e.g., for people with poor eyesight), one of the Valentine heart decorations covers part of the "Featured Items" label.

![screenshot_2018-02-22_20-16-11](https://user-images.githubusercontent.com/1495809/36532712-39d1c2dc-180d-11e8-8cc3-1530100a9f9f.png)

I imagine we won't get a fix made fast enough to fix it for this years Valentine period, but we could prevent this for any future decorations by giving the "Featured Items" label a z-index value great enough to ensure it's in front of all other items.

**Comment by probaton** [comment]
This has been bugging me too so I wanna fix it! If I understand correctly I'm supposed to leave a comment here before doing so? Which I'm doing. Because this is a comment. And I'm leaving it here. 

Also, I secretly already have a fix for this (it's only one line of css), so say the word and I'll create a PR.

**Comment by probaton** [comment]
Ok, so maybe I was impatient and already pushed the request. My most sincere apologies for scoffing at your eminently sensible guidelines. 

If the timing is inopportune feel free to scrap the request; it was only a small fix anyway and I can always re-implement it if it's conflicting with more important work.
