### ISSUE TITLE
tried to use chat for the first time but it said chat privelages had been revoked 

### ISSUE THREAD

**Issue by danwulf** [HabitRPG/habitica#10101]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by citrusella** [comment]
Did somebody ask you to report this here instead of on the website or by email?

You may want to email admin@habitica.com to discuss that if it wasn't a temporary thing (or even if it was), just in case there was a moderation related reason. I know they can't check your account without your user ID, anyway, so this blank issue probably can't help them without more information if there's somehow a non-moderation related actual-bug reason. (User IDs look like this: 2d6ef231-50b4-4a22-90e7-45eb97147a2c and they're visible on the API settings page or on your profile screen, if you're on the website.)
