### ISSUE TITLE
Notifications are covered by resting in the inn status banner

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10169]
As reported by citrusella:

> The inn banner forces the navbar down but doesn't push down the notifications for gold and such, which places the navbar over top of the notifications (presumably because of its z-index? I think?).

I've confirmed this behaviour on production and staging. Here's a screenshot. 
![image](https://user-images.githubusercontent.com/8144640/37828143-04b85b2e-2e92-11e8-8822-56c59dc187ce.png)

**Comment by Alys** [comment]
As a note to anyone who works on this, the desired fix is to move those notifications down when the banner is in place, not to change any z-index values.

citrusella is correct that it's the navbar's z-index that places it over the top of the notifications and we want to keep doing that so that when the user opens a drop-down menu from the navbar, it opens over the top of any remaining notifications.

**Comment by Alys** [comment]
I'm reopening this because the fix was reverted in https://github.com/HabitRPG/habitica/pull/10203 but I'm setting it to in progress while we investigate what went wrong with the fix.
