### ISSUE TITLE
Rewards substract life

### ISSUE THREAD

**Issue by JesperDramsch** [HabitRPG/habitica#102]
Hi,

I just wanted to show someone how this app works and clicked on a reward.
What happened is that I lost 17 HP and 3 gold on "nothing". I don't think it's a good idea to substract all those HP without warning, I would've thought you just don't get the reward.

Oh yeah and could I get those HP and gold back?

Cheers,
Jesper

**Comment by antistic** [comment]
I agree - there should be a warning like "Are you sure you want to buy this reward? You will lose [number] HP and [number] coins if you do"

**Comment by racuna** [comment]
Not bad, or just undo the last bought.

**Comment by The-Bard** [comment]
Maybe have an optional "Oops" button for when you accidently click on something. The oops button could even keep track of how often you use it, or could cost a small amount like 5 silver. Even so, a prompt for the rewards would be handy.

**Comment by BenMilford** [comment]
I do agree there should be some type of warning.

**Comment by horusofoz** [comment]
@ApplePi314 Can you advise if you are still able to reproduce this unusual behaviour?

Also a request for an Undo button has been logged under #158

**Comment by horusofoz** [comment]
@ApplePi314 Apologies. I wrongly cited you in my previous comment.

@Jesper1337 Can you advise if you are still able to reproduce this unusual behaviour?

**Comment by wc8** [comment]
Does this relate to #158 Feature Request: Confirmation Dialog before Spending Gold?
I think HP loss for spending more gold than you have is expected behavior, to make you think twice before you watch Sesame Street ;-) for an hour when all your dailies and todos are incomplete.

**Comment by StanLindsey** [comment]
@wc8 is correct, if you didn't have enough gold then by indulging yourself without due cause your character loses HP. As previously stated there will be an undo button as well as a confirmation if HP loss is to happen. 

(Just noticed that this original post was two weeks ago so Trello wouldn't of been set up and these suggestions formalised) 

I'm going to close this as it is not only old but is currently expected behavior. (Any other admins can open if you deem it so)
