### ISSUE TITLE
Tooltip may not update right away when you purchase equipment

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1020]
The information tooltip that previews the stats you'll enjoy when purchasing a new weapon or armor piece doesn't appear to update upon purchase. For instance, when I bought my very first Sword, the Axe tooltip continued to say it would grant a 3% experience gain, leading me to believe there was only an aesthetic difference between the two. It wasn't until later (after a refresh or logout/return maybe) that the tooltip updated to show the correct 6% value.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by SabreCat** [comment]
Actually, it turns out this is still the case--and in fact has gotten worse. When you purchase a gear reward, _nothing_ changes in the shop: you still see the item you just bought, same price, same tooltip. The avatar updates correctly, but it takes a refresh to see the next tier of item.

**Comment by lefnire** [comment]
can you open the no-update bit on a separate ticket, i wanna track these differently since the tooltip is minor but the update thing sounds major. This tooltip bit is still happening though eh? I'll look into it, may require updating angular-ui-bootstrap (i need to do that anyway to remove all the components we aren't using)

**Comment by paglias** [comment]
Fixed
