### ISSUE TITLE
Flagging multiple messages include the same message in the new flags

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10214]
When you flag multiple messages on the same page, after you have flagged the first message, subsequent flags automatically include the previous text. You can delete this text and flag without including text, and going to a different guild clears the box, but the persistence of the text might still be confusing ("am I flagging the right thing? Did my last flag go through?").

**Comment by allie5** [comment]
I can take a look at this? 
@Alys

**Comment by Alys** [comment]
@alliemoon Please do, thanks! Post here if you have questions.

**Comment by allie5** [comment]
@Alys 

I've been looking though the code, I've found the groups.json that contains the placeholder text (the "Please help our moderators by letting us know why you are reporting this post for a violation..." bit) and I've found the reportFlagModal.vue stuff. 

And I realized I misunderstood the bug as well, I thought the text of the message you're flagging is persisting but it's the "Why are you reporting?" text that is maintained instead of it being the placeholder text again. 

I was wondering if you had any insight into where I should be looking?

**Comment by Alys** [comment]
@alliemoon I'm not especially experienced with vue myself, so all I really know is that website/client/components/chat/reportFlagModal.vue creates the form for adding the report comment, and there must be something that causes the value of the `reportComment` field to remain in the form after it's closed.

@TheHollidayInn what's the best way of clearing `reportComment` after the form is submitted?

**Comment by TheHollidayInn** [comment]
You would need to reset the `Component's data`. 

So here is the data: https://github.com/HabitRPG/habitica/blob/21954647725ebd28bd56484ef52f1f0b08438e3f/website/client/components/chat/reportFlagModal.vue#L91

To reset reportComment, you would need to add `this.reportComment = ''` at this line: https://github.com/HabitRPG/habitica/blob/21954647725ebd28bd56484ef52f1f0b08438e3f/website/client/components/chat/reportFlagModal.vue#L121

You might want to look at the other data items to see if we should reset them as well.

**Comment by beffymaroo** [comment]
@alliemoon Are you still working on this issue? Please let us know when you have a moment. Thank you!
