### ISSUE TITLE
hatching pet modal does not always show all text (language-dependent)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10232]
When you are hatching a pet, the dialog that asks you to confirm that you want to hatch is not large enough to show the full message explaining what the new pet will be, if your language has longer words than English. For example, in this screenshot, the lines of non-bolded text directly above the buttons have words cut off:

![image](https://user-images.githubusercontent.com/1495809/38453072-0d2e9004-3a93-11e8-9aa2-4e72dee8b68f.png)

That's from this modal:
https://github.com/HabitRPG/habitica/blob/f527221079b4ad8c89bb0adb73c1425533e545de/website/client/components/inventory/stable/index.vue#L212-L225

The modal should either be hard-coded to be large enough to always show all of the translated text no matter how long it is (which would likely produce a rather ugly appearance in shorter languages) or should expand itself automatically to be large enough to contain the full text (probably the best solution).

I'm marking this as needs designs for @Tressley to indicate if he has a preference for how to fix this.

**Comment by Tressley** [comment]
I'm going to pull "needs design" off of this as I think this is a code issue. Modals should have a consistent width, but their height should always be able to accommodate varying text lengths.

**Comment by citrusella** [comment]
I'm interested in taking a stab at this, but out of curiosity, is there any maximum height the modal shouldn't go over? (I think if there were, there's probably not a language with a dialog that long, but I figured I'd ask the question (and also claim this, heh) before moving any further than the playing around I've just done to see if I understand what might need to be changed.)

**Comment by Alys** [comment]
@citrusella Thank you! I've marked it as help wanted for you. Post here if you have questions. :)

I'm not in a position to comment on a maximum height so you might want to wait a day or two to see if the staff comment, but if there's no other responses then my feeling is that as you say there wouldn't be a language that would cause the dialog to exceed any maximum so it might not be something to worry about for this issue.

**Comment by citrusella** [comment]
The only reason I even thought to ask is because I found the easiest way to test was to add lorem ipsum text to the relevant English string to ensure the message was *always* long enough (as opposed to, say, switching to German and finding a specific pet string that's too long (like Desert Flying Pig's) and navigating to it every time I tried some changes).

...But a whole paragraph's worth of lorem ipsum has the side effect of making the modal large enough with the edit that I tried that it's taller than my screen height (but the page scrolls, and given other modals I've seen that seems like the desired option (versus only the text area of the modal scrolling and the class/element having a height limit, for instance)). I doubt many, if any, languages have a string that would cause that outside of a very small screen resolution setup.

**Comment by Tressley** [comment]
@citrusella — Modals should never have have a max-height. This is to accommodate the various types of content and the multiple translations. And sometimes the content of the modal may make it larger than your screen. In this case, the modal would scroll.
