### ISSUE TITLE
drawer text overlapping when window is small or font size is large or language is non-English with long words

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10264]
From Bug Guild, confirmed in Firefox on Linux as well:

> "Hi Habitica,
> 
> I found a minor issue that I think should not be happening.
> 
> Summary: Words overlapping from the quick inventory tab after clicking on Shops => Market
> 
> Steps to reproduce:
> 
> Minimize/reduce the size of the home page before continuing the steps
> Clicking on Shops on the top (header) of the home page using Safari browser and Market from the dropdown
> Expected Behavior: Fields and items on the page should fit the page no matter the page size
> 
> Observed Behavior: words/ sentences are overlapping. ..Thank you."

**Comment by Alys** [comment]
Firefox screenshots with small window (note the merging of "Special" and "What does my...."):
![1](https://user-images.githubusercontent.com/1495809/38975914-ea2bffec-43f2-11e8-94d6-281baa029dcf.png)

Firefox screenshot on smaller window:
![2](https://user-images.githubusercontent.com/1495809/38975915-ea7364c2-43f2-11e8-8c5a-42d5db9cf8be.png)

Firefox screenshot with larger window but an increased font size (e.g., for someone with aging eyesight):
![3](https://user-images.githubusercontent.com/1495809/38975918-eb4004e6-43f2-11e8-9ef3-a12e6e42dd89.png)

The latter one means that the same problem will exist for a normal-sized window with normal-sized font but in a language that has longer words than English. I can't get a screenshot of that since I can't change my language because I'm using Firefox (and no other browsers are installed on this machine).

**Comment by Alys** [comment]
I expect the same thing would happen in other drawers under similar conditions so ideally the fix for this issue would consider all of them.

**Comment by ianoxley** [comment]
Is it OK for me to work on this?

**Comment by Alys** [comment]
@ianoxley Please do, thank you! Comment here if you have questions, or would like any direction about how to fix it, or would like to discuss your preferred way of fixing it.

**Comment by ianoxley** [comment]
Can I just check what browsers you support please? Using CSS Grid seems to fix this, but I wasn't sure whether I'd need to get this working in things like IE11 😬 

Also, I've added a screenshot to my PR. Is the way the text wraps at smaller screen sizes acceptable? Let me know if it's OK, or if it needs tweaking.
