### ISSUE TITLE
Weird inventory spacing in Chrome

### ISSUE THREAD

**Issue by nafoster** [HabitRPG/habitica#1028]
![inventory-spacing-bug](https://f.cloud.github.com/assets/3391909/552422/ba617fd8-c352-11e2-8bc1-b78531104684.png)

In the most recent version of Chrome on a 1366x768 resolution, there are typographical/image bugs in the Inventory view. 

On the left, the egg hatching potion names are incorrectly spaced out so that some labels are incorrect. In the screenshot, the label closest to the Zombie hatching potion says "White" and the Skeleton hatching potion says "Zombie". It's like the labels are getting pushed down past their actual hatching potion.

On the right, there is weird image and text spacing amongst the hatching potions. See screenshot.

**Comment by Aiseant** [comment]
I have this problem with firefox too :

Eggs are weirdly spaced :
![align1](https://f.cloud.github.com/assets/4418868/553179/242c8768-c37c-11e2-8d27-a210fcb162c3.jpg)

Same trouble with potions : 
![align2](https://f.cloud.github.com/assets/4418868/553180/245d8462-c37c-11e2-99d0-27336733d37e.jpg)

**Comment by nafoster** [comment]
@Aiseant That's weird it happens in Firefox too. What is your resolution? Maybe it's related to that.

**Comment by AndreCaseyScott** [comment]
I don't think its a browser issue. My hunch is that it has to do with how the DOM is populated on this tab. I don't know the specific functions that are at work here, but mixing menu and div tags with tables leads to unpredictable results.

Is there any specific reason the DOM is laid out the way it is on this tab? I noticed that the left side (with the eggs and potions) uses a menu tag with divs within it, and the right side uses tables. My thought is to clean up the DOM and group each of the elements into blocks (the image and text in one div) which can have fixed dimensions, allowing them to be floated and arranged more consistently. This is for sure the reason the hatching potions are aligning incorrectly, since the name of the last potion in the column (cotton candy blue) is so long and not inside of any div or constraining element. Thus the whole column is affected. 

Willing to (try and) take this one on, but wanted to make sure you didn't have some grander logic to the layout that I might be missing

**Comment by lefnire** [comment]
There's simply a missing CSS class or mal-nested div somewhere, it didn't
used to be like this until I futzed with the containing div to make Alex
fit his word bubble better. It shouldn't require any html overhaul, simply
a 15m sit-down. I'll hit it when I can, but it's super low-prio by
comparison

**Comment by SpySauce** [comment]
I'm having this issue as well. Because of it, I can't highlight potions to purchase them.

**Comment by Aiseant** [comment]
By the way, can someone explain to me why there's no 'cub' for fox and wolf ?

**Comment by AndreCaseyScott** [comment]
Arg, so I don't know if I referenced the pull request correctly...first time using git and github :/. Definitely not perfect but should work for now, until pets system is redone.

Here is was the fix looks like.
![screen shot 2013-06-07 at 8 08 43 am](https://f.cloud.github.com/assets/3774345/624392/9289b3d4-cf84-11e2-8441-036f98f5162e.png)
![screen shot 2013-06-07 at 8 08 58 am](https://f.cloud.github.com/assets/3774345/624393/929da2e0-cf84-11e2-8294-137cdcc5f47b.png)

**Comment by Shaners** [comment]
@Aiseant originally the Tiger, Panda, Lion, and Bear mount were designed as pets so to distinguish the smaller versions were tagged as cubs. Wolf and Fox didn't have a larger version at the time.

**Comment by AndreCaseyScott** [comment]
Yay! Sometimes patience works best. Pull request successfully fixes inventory potions as well

![screen shot 2013-06-08 at 4 14 32 pm](https://f.cloud.github.com/assets/3774345/628278/be2f36d6-d091-11e2-8747-6d61d12eac15.png)
