### ISSUE TITLE
NOResetPasswordEmail!

### ISSUE THREAD

**Issue by Saramrkd** [HabitRPG/habitica#10359]
i need my passwort which i have forgotton.but git hub sends me no reset email link.what should i do.i t is urgent.plz help!

[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
Are you trying to reset your password for Habitica or for GitHub? 

You said "git hub sends me no reset email link" - if you're trying to get into your GitHub account, we can't help you here because this is the repository for Habitica. You'd need to contact GitHub for help: https://github.com/contact

If you're trying to reset your password for Habitica, please email us at admin@habitica.com and tell us which Habitica account is yours and/or what your login details are, as far as you can remember. An email will let us talk privately so that your account remains secure.
