### ISSUE TITLE
editing a Challenge gives inappropriate message about gems

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10419]
As reported by cTheDragons (bc10ec41-4213-4482-bbb8-558e3c3ea8d5):

"When I edit a challenge (to update the description for example) and I have less gems than the reward of the challenge, I get a false message that I don't have enough gems, or require gems for my Tavern challenge."

"The edit does go through but I needed to refresh to see it."

The message about not having enough Gems or needing Gems for a "Public Challenge" (Tavern Challenge) should be seen only when you're creating or cloning a Challenge.

**Comment by Alys** [comment]
The message about not having enough Gems or needing Gems for a "Public Challenge" (Tavern Challenge) should be seen only when you're creating or cloning a Challenge.

**Comment by thyme4soup** [comment]
I'm having trouble reproducing this error (I successfully update tavern challenges with a gem bank lower than the reward amount), but what I did find is that when you go to 'clone' the challenge, click out of the 'clone' challenge modal, and then go to 'edit' the challenge, the modal displays as though you are still trying to clone the challenge. I think this is because the 'cloning' flag is not reset in challengeModal.vue

This gives the 'not enough gems' message but blocks the edit, which doesn't match the bug report. Is this a separate bug? Should I file it?

**Comment by thyme4soup** [comment]
I got a fix for the update/clone bug working and can make the change, but should I put it under this branch or is it a different issue?
I'm adding a gif of the bug as well (before the fix)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/683134/41081580-41babfc4-69e0-11e8-9329-39c8739531e4.gif)

**Comment by Alys** [comment]
@thyme4soup Thanks for this! Please do submit a PR for what you describe, and write in it "related to #10419" rather than "fixes #10419".
 
(We'll do some more testing for the bug reported in this issue to work out if it still needs to be fixed.)

**Comment by TheHollidayInn** [comment]
I'm unable to recreate this. Is it still an issue?

**Comment by Alys** [comment]
I can't recreate either, looks like it's been fixed, but we can reopen if it happens again.
