### ISSUE TITLE
Add reward-value to certain tasks?

### ISSUE THREAD

**Issue by Chazward** [HabitRPG/habitica#105]
_Edited by wc8: See [Importance, Priority, Duration/Difficulty, Deadlines](https://trello.com/c/4C8w1z5h)_
To clarify, I want to make achieving certain tasks more rewarding than others. For example, if I get to my doctors appointment on time I'll receive one gold, but getting enrolled in a school should certainly be more rewarding than that. I'd like to be able to toggle how big the reward is when I create a habit, daily, or todo, much like we can choose the price of our rewards.

**Comment by The-Bard** [comment]
Perhaps have a maximum amount that it could be set to. If the task is worth more for instance, then the negative effects of not doing the task (For dailies) should be greater as well. If we have the option to have great reward for accomplish the task, then there should also be greater risk... Fort he sake of balance.

**Comment by FuelTheJet** [comment]
The issue that occurs with a person choosing their own rewards is that it takes away from the sense of accomplishment that makes the "mmorpg" style of games so enjoyable. Now of course if every task is worth one point then it ruins the whole concept, as you pointed out. This provides an interesting problem as everyone has a different view of the "value" of what they have accomplished, for example someone may consider them spending five hours studying for a history test as extremely valuable because they struggle with devoting time to school, although someone else may see very little value in studying 3-4 hours a day for an exam although huge value in something else. With that said, it's quite obvious that a solution is of profound importance, although a solution that fits a few things is still a "bad" solution and a solution that fits several things is not an easy solution.

As for right now I believe the one point value should stay until a solid fix is provided and can be simulated with successful results. I have several suggestions, although I feel as there is too much that is undecided and several suggestions could become void. I think this is something that should be brought to attention at a later stage, as it is too early to really work on a solution.

**Comment by eivindorama** [comment]
A easy way to avoid the inflation possible with letting players choose, is to let players -rank- the tasks instead.

If you can pick values, there's a temptation to say "everything is very valuable", but if all you can do is -rank- the importance of your tasks, then there's no risk of inflation: only one task can be "the most important one"

**Comment by wc8** [comment]
@eivindorama Might rank get difficult to manage in a long list of tasks? 

Methinks another way to avoid inflated values is the modifier suggestion of #53 which, if I understand it right integrates with the current system. The more frequently you complete a task, the less reward for each instance, right? So if you click too many times, eventually you'd get next to nothing for faking it.

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.
