### ISSUE TITLE
apidocs misleading - causes API requests to /user/allocate always up Strength

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10557]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

The data payload of a `curl` request to `/api/v3/user/allocate` appears not to be parsed correctly, leading to the default STR attribute being incremented regardless of the request. For instance, the following returns success but bumps STR instead of the desired INT:

`curl -s -X POST --compressed -H "Content-Type:application/json" -H "x-api-user:USERID" -H "x-api-key:API_TOKEN" https://habitica.com/api/v3/user/allocate -d '{"stat": "int"}'`

**Comment by TheHollidayInn** [comment]
That's because `stats` is supposed to be a query param. We document that:

- https://github.com/HabitRPG/habitica/blob/8b9bf88fa0d26a9d15f9b103e7eedafc807f2363/website/server/controllers/api-v3/user/stats.js#L12. 
- https://github.com/HabitRPG/habitica/blob/8b9bf88fa0d26a9d15f9b103e7eedafc807f2363/website/common/script/ops/stats/allocate.js#L12

I can see how this could be confusing, but it isn't a bug.

**Comment by Alys** [comment]
The [apidocs for that route](https://habitica.com/apidoc/#api-User-UserAllocate) have it listed under the heading "Body Parameters", which is probably how the confusion arises (even though it's "query parameters" in the text).

I'm reopening this for the docs to be clarified but I"m assigning it to myself to fix because I want to make a couple of other wording changes too (e.g., "Stat Points")

**Comment by TheHollidayInn** [comment]
Ah I guess that's because of the body after param. I saw the query param next to the name on the doc line.
