### ISSUE TITLE
Extra undesired spacing on checklists

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10569]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#10477 tidied up a bunch of spacing in Markdown list and header elements. However, it accidentally also increased the spacing between checklist items on tasks. Those should probably not be included in the CSS selector that adds the space--they look much nicer when displayed in compact rows rather than double-spaced.

![image](https://user-images.githubusercontent.com/4501321/43488607-e7825bf4-94df-11e8-90f1-fa4024b7fdf5.png)

**Comment by citrusella** [comment]
For what it's worth, it also affects spacing after the very end of a task title, I believe. I didn't report that in the guild because I didn't notice it originally. (I only caught it when making a CSS style that reverted the .markdown p change inside .task-content ([this style, FWIW](https://userstyles.org/styles/162990/no-p-padding-on-habitica-task-list)) as a fast fix and I thought it might be worth bringing up here, even though it sounds from the original issue like that part could be intended since spacing between paragraphs in tasks was mentioned there.)

**Comment by msaikaushik** [comment]
@SabreCat , can i take this issue?

**Comment by Alys** [comment]
@IceDune Please do, thank you! Comment here if you have questions.

**Comment by msaikaushik** [comment]
@citrusella ,@Alys may i know how much margin should i assign or is it none?

**Comment by citrusella** [comment]
I'm probably not really the one to ask (I was only here to add something I hadn't noticed/included when I reported this in the Report a Bug guild), but for what it's worth, [the previous `.markdown p` margin-bottom (what's causing the extra spacing right now) was 0px](https://github.com/HabitRPG/habitica/commit/0e648d85a08310cf3145458b38f7636beb87d003).

**Comment by Alys** [comment]
@IceDune  : Yes, you can give it 0px margin. Thanks for asking, and @citrusella thanks for finding that for us!

**Comment by msaikaushik** [comment]
@Alys , i put up a PR.

**Comment by paglias** [comment]
@IceDune it looks like you posted your PR on your own fork, it should be opened here :)

**Comment by msaikaushik** [comment]
whoops, my bad . thank you @paglias !

**Comment by citrusella** [comment]
Asking because I've been vaguely following this and am confused: Is that PR intended to remove the paragraph spacing from *all* places? Or just some? (#10477 seemed to express a desire for the paragraph spacing where it makes sense (i.e. after paragraphs), and this issue at the very least doesn't want the spacing in checklists but to my half-trained/half-untrained eye the PR seems to just be reverting the entire addition of padding to any `.markdown p` at all, and I wanted to know if that was the intent. ...IDK, my brain hurts.)

**Comment by Alys** [comment]
@citrusella thanks! You're right. I've commented on the PR.

**Comment by beffymaroo** [comment]
@IceDune Are you still working on this issue? Please let us know when you have a moment. Thank you!

**Comment by lucubro** [comment]
I have a fix ready locally for this that I did just to get acquainted with the code, but feel free to ping me If this still needs help, and you'd like me to submit a PR.

**Comment by SabreCat** [comment]
@lucubro The previous claimant on the issue hasn't responded--I'd say go ahead!
