### ISSUE TITLE
Username @ list in chat is positioned incorrectly from multiline messages

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10612]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If you include carriage returns in a chat message, then attempt to @ mention a chat user, the dropdown with name selections appears further down than it ought. The more lines in your message, the more pronounced the issue:

![image](https://user-images.githubusercontent.com/4501321/44368953-340d3600-a49a-11e8-917f-2cf05279cee0.png)

**Comment by rkojima** [comment]
Hi @SabreCat, mind if I take a look at this?

**Comment by paglias** [comment]
go ahead @rkojima !

**Comment by rkojima** [comment]
@paglias, I think the issue can be solved by automatically expanding the textarea after height of the text in the box is bigger than the textarea. Is that a viable option?

**Textarea not expanded:**
![screen shot 2018-08-21 at 10 08 35 pm](https://user-images.githubusercontent.com/4088176/44443857-d1499680-a58e-11e8-8485-8bda436f053b.png)

**Textarea expanded:**
![screen shot 2018-08-21 at 10 08 46 pm](https://user-images.githubusercontent.com/4088176/44443859-d3abf080-a58e-11e8-9b07-39417c99a4ba.png)

**Comment by Alys** [comment]
Even if this issue didn't exist, it would be good to have the textarea expand after you've typed more than will fit in its original size!

**Comment by paglias** [comment]
pinging @Tressley about the design change, I'm not sure expanding the textarea is a good thing UX wise

**Comment by Alys** [comment]
If you're writing a lot of text (the limit is 3000 characters), then it's helpful to see all of it at once. It means you can proofread what you've written without having to scroll up and down through your text.

**Comment by paglias** [comment]
I'm not sure how many users type 3k characters messages and imho it creates problems like shifting all the chat messages down as the textarea expands, then when the message is sent should it be collapsed again or not?

**Comment by Alys** [comment]
3000 is just the maximum size for the posts, not necessarily the size that the increase would cut in at. - the point of it is that long posts are possible.

In my browser, text that I've typed starts scrolling out of sight at less than 500 characters, which isn't a very large post. Socialites do about that often when they're giving detailed answers to questions, and discussions in various guilds can often involve long posts. 
_(For example, this one by Aerlita is more than 500 and it's not unusually long: "Apparently when you logged in to the website, you used different credentials (for example, you registered using e-mail and password, but on the website chose "Sign up with Google", which is not the same). Best option, to avoid confusion, would be to delete the 1-level account on the website (by going to User Icon on top right, under it Settings, scroll down to Danger Zone, red button "Delete Account"), and then log in to the website with the same method as you registered. To make certain, could you post here from the phone?")_

I don't think it would be troubling to see the elements under the chat box shift down as the chat box expands. The convenience of seeing all your text would outweigh that, especially since often once you've sent your post you scroll back down through many messages to get back to where you were up to. The extra scrolling from the larger box would be minor.

After the message is sent, I don't have a strong opinion about whether the box should stay large or shrink. If staying large is easiest (which I'd guess it might be) then I think that would be fine. Again, the convenience of seeing all your text outweights the slight disadvantage of the box taking up more space, and someone who's just typed one long message will be more likely than average to want to type another.

**Comment by paglias** [comment]
In case someone wants to expand the textarea they can do it by using the handle at the bottom right of the textarea

**Comment by Tressley** [comment]
@paglias -- I'm not against auto-expanding, but I do think that there should be a max-height to the textarea. My preferred UX would be similar to how GitHub handles their comment textareas. While typing, the textarea expands until hitting the bottom of the current viewport. Dragging the handle sets the same limit. 

For design feedback, the "@menu" should be snug to the bottom right corner of the `@` and follow our menu styles. Here's a mock-up for reference.

![image](https://user-images.githubusercontent.com/2686586/44467592-40f06d80-a5f1-11e8-9267-2d0f5f956f8f.png)

**Comment by paglias** [comment]
@Tressley I had never noticed that github's textarea works this way! My rationale for not expanding it is that, while in github's case the textarea is at the end of the page so expanding it doesn't move anything, in our case the textarea is followed by all the chat messages which means that every time a new line is added the messages get pushed down which I find quite annoying especially if you're replying to the last message

Then when you switch to another guild after the current one has the expanded textarea you'll find the textarea of a different size and thus the messages will be positioned differently as well

**Comment by Tressley** [comment]
@paglias -- True. You can test GitHub's experience by clicking edit on other comments as well. That would give you an idea of how they handle messages below.

As for a solution, there are two things I think we can do. One would be to update the textarea's font-size to be 14px (line-height of 20px) instead of 16px. That will allow more text to be shown at the default size. And two, have the textarea expand, but have a max-height of roughly ~3x it's default size. Once the user hits the bottom of the textarea, we grow it by 20px to accommodate the new line. If a user clicks the handle to expand the textarea, it only expands to it's max-height. Thoughts?

**Comment by rkojima** [comment]
@Tressley actually, I'll try to implement it like Github does. Also, I added a minimum height for the textbox. Let me know if that's something you don't want.

**Comment by Tressley** [comment]
@rkojima -- Adding a minimum height is great. We can set it to be 3 lines of text. 👍
