### ISSUE TITLE
Animal Ears should not be purchasable with gems after losing them

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10668]
When you lose Animal Ears due to Death (or the future Empty the Armory) feature, they appear in the Market to be bought back with gold (which is the correct behaviour and shouldn't be changed).

However they also appear in the User Icon > Avatar section to be bought back for Gems. This is not correct - once a player has bought them with Gems, they should never need to spend Gems on them again.

_This old issue is related so I'm linking it here in case anyone's interested in the discussion there: [Pet Ears cannot be obtained for free after Death or Orb of Rebirth](https://github.com/HabitRPG/habitica/issues/5236)_

_Thanks to Il Mago for reporting this._

**Comment by Aonepathan** [comment]
@Alys Is it possible I can I take a whack at this? I am totally new to becoming a Blacksmith and haven't contributed before but have spend some time reading the previous issue and looking at as much code on Animal Ears. 

Could you provide any additional clues to files directly effecting this? (the only canOwn reference I could find was in content and gear index.js)

I have seen the 20 gold allocation for ears:
```
 bearEars: {
    gearSet: 'animal',
    text: t('headAccessoryBearEarsText'),
    notes: t('headAccessoryBearEarsNotes'),
    value: 20,
    canOwn: ownsItem('headAccessory_special_bearEars'),
    canBuy: () => {
      return true;
    },
  }
```

Where can I see a reference to the gems being used?

**Comment by kirsty-tortoise** [comment]
I'd like to try this one, if that's okay.

If you've already bought Animal Ears with Gems but lost them to Death, should you be able to buy them back with Gold from the User Icon > Avatar section?

**Comment by negue** [comment]
@kirsty-tortoise You can try this one, if you need any help just ping me

Yes, if you lost the items then they can be repurchased back with gold. (not with gems)

**Comment by kirsty-tortoise** [comment]
Thanks.

I've had a go at it, but I'm running into a small problem with buying the set of all Animal Ears for gems.

I've made it so that you can't buy the set for gems if you have already bought all Animal Ears with gems for a first time (even if you've lost some to Death). I'm not sure if this is the correct behaviour, it seems reasonably sensible.

At the moment (on my branch, but also on develop), if you have some Ears you haven't purchased, and some Ears you've purchased and then lost to Death, buying the set with Gems restores all Animal Ears but doesn't remove them from the rewards (they are gone from the market). This persists even when I refresh. Attempting to buy them causes an error. This clearly isn't right.

I assume the right thing to do is to restore the ears and remove from rewards when the set is bought, but maybe the already purchased and lost ears should not be restored unless purchased directly with gold?

**Comment by Alys** [comment]
> I assume the right thing to do is to restore the ears and remove from rewards when the set is bought

Yes.

> but maybe the already purchased and lost ears should not be restored unless purchased directly with gold?

I think it's best if buying the set does restore lost Ears. The code for that will be simpler, and the behaviour will be more what the users are expecting since the set is intended to make all Ears available to you. I think we'd get occasional bug reports if gold-purchasable Ears were excluded from the set. I believe it would be very rare to hear complaints if they were included.
