### ISSUE TITLE
When cron runs, the RYA popup kills anything you're currently editing

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10679]
From katzalina in Bug Guild:

> I think I read something about this before, but can't find it again - entering data (in this case adding challenge tasks) interrupted by cron makes the data vanish... one second on the last line of a long challenge todo, the next cron and RYA and after that no challenge to do... The obvious lesson is "don't work that late!", but thought I'd mention it and ask if there might be an automatic save function some time in the future?

Rightfully irritating, in my opinion. If not an automatic save option, maybe not letting RYA close other modals?

**Comment by Alys** [comment]
Months late, but I've marked this as suggestion-discussion for the staff to comment on how it would best be fixed.

**Comment by Alys** [comment]
This happens even if the RYA modal doesn't need to appear (i.e., cron without the modal can also cause this issue). Here's a report from @citrusella:

@citrusella: "I cronned while editing my profile and the edit box closed and wiped all my changes (luckily I was doing something minor but...). I don't know if this is consistent on just cron itself or if the site tried to show me a modal (I never saw one other than my profile, though). The profile modal itself stayed open, it just switched out of edit mode."

@alys: "Do you recall if you SHOULD have seen the RYA popup? I.e., if you had due Dailies that weren't completed?"

@citrusella: "my dailies were all checked off and Habitica appeared to behave in line with that! o.o"

**Comment by Alys** [comment]
I'll leave this marked as suggestion-discussion for another week then if there's no objections, I'll mark it as help wanted for a contributor to work out a fix.

**Comment by citrusella** [comment]
I have no idea if I've even sniffed up the right tree but I suddenly wondered something special about cron but had no way off the top of my head to figure it out: Is there any other action on Habitica that will force a sync more or less just by existing? (That is, without clicking anything?)

I just had the thought because most everything you can edit is in a modal but *usually* the things that cause a sync are either the things that close the modal (i.e. a save button or something) or things that require the modal to be closed before you can interact with them because they're behind it (i.e. sync button or fetch messages button). But cron runs and makes you sync as soon as you're in the tab after day start, I think?

(While typing this the thought occurred to me that maybe Bailey does that too, but... hmm...)

...If this *is* the case I still have no idea how to *fix* it but I figured I'd share my mind's ramblings on the chance they're useful.

**Comment by Alys** [comment]
I wouldn't be surprised if @citrusella is correct that it's the automatic sync that causes this problem rather than cron/RYA itself. I can't think of anything else that would cause an automatic sync.

A contributor can force cron to be due on their local install by setting their test account's `lastCron` date to one or more days in the past, BUT I'm not sure if that would immediately trigger the website's check for whether cron is due. You're probably better off setting your test account's Custom Day Start time to an hour later in the day, sync the website to be sure it's picked up the change, then leave the website with an editing modal open until that time to observe the issue.

**Comment by paglias** [comment]
Is this still happening? Now opening a new modal should not close the other ones

**Comment by citrusella** [comment]
I could try having a daily open to edit right at day start (...or just set my day start to noon or 1pm) and test to see if it closes in line with cron running, with or without the popup.

(In fact, I think I *will* do that because it will have a side effect I'll enjoy, so why not? XD)

EDIT: Cron decided not to run *at all* in the tab I was editing the task on. Only ran in the other tab I had open when I switched to it. Must try again, maybe not on delta this time. XP

**Comment by citrusella** [comment]
...So I can't get cron to run **at all** while I'm editing things? So I can't test either flavor of this (i.e. with or without the RYA modal appearing), because those are both part of cron, right? And even after I close the thing I'm editing, it doesn't run until one of two things happen:

1. Cron runs elsewhere (i.e. another tab or platform)
2. The website is reloaded and not just synced

Number 1 happened the first time, on delta, at which point I had two delta tabs open. My day start was set to noon. Cron never ran in the first tab, where the (to-do) edit modal was open when cron was supposed to run, and it stayed in an not-yet-run state until I clicked over to the other tab I had open (also on delta, was getting some guilds read and messages posted to kill time). After that point, a sync brought it in line with the post-cron state.

Number 2 happened the second time, on production, while I had switched to production in the tab I was trying to test in and I still had the same delta tab open for roaming around Habitica. Cron was set to 1 pm. This time I went to apply some profile edits (namely, changing my display name back to its usual) and again, cron didn't run at all while editing my profile. It also didn't run after saving my profile, so at this point I switched to the delta tab that had forced the cron the previous time to see if it would run cron when I switched to the tab like I was expecting. It didn't, and cron didn't run until I did a full refresh (I know this definitely and for sure because that's when the boss damage posted to my party chat--I'm *pretty sure* I did the refresh on the production tab).

(In both of these cases, I stopped doing things in the not-editing tab a few minutes before the day start, just in case being active in that other tab too close to cron might affect it.)

Feels relevant to this. Don't know if it replaced the modal-closing behavior (i.e. now a complete lack of cron happens instead) or if it's just covering it up (i.e. this issue *would* still happen if the cron-not-running thing were fixed).

**Comment by paglias** [comment]
Thanks @citrusella for all the details! I'll give this a better look when I have some time

**Comment by paglias** [comment]
I just tried to replicate this issue after the bulk scoring PR was merged and I can't replicate nor the issue described here nor the one reported by @citrusella . In particular I left a tab open with an edit task modal and went back to it after cron time, the RYA modal appeared correctly and the edit task modal wasn't closed even after starting my day:

<img width="662" alt="Schermata 2020-08-25 alle 17 13 08" src="https://user-images.githubusercontent.com/589911/91192658-7a837400-e6f6-11ea-937f-fb52e6aa8521.png">

I'd say it's been fixed by the bulk scoring PR and the removal of the modals stack and can be closed but let me know if you see it happening again
