### ISSUE TITLE
Incorrect link in French version of site

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10707]
From Report a Bug:

> Harold (bfdd6e83-c0dd-4dd9-ab11-d123e4c9b5c6) 
> Hi.
> In French, in the settings, in the section API, the link to the wiki page for third application named in french "Autres extensions" links to a inexistent page of the wiki (http://fr.habitica.wikia.com/wiki/Int%C3%A9grations_d).
> Thank you in advance.

--- 
_edit by Alys: This needs to be fixed in Transifex, not by a Blacksmith._

**Comment by shanaqui** [comment]
From citrusella:

> I wonder if it's properly linked to [Intégrations d'Applications et d'Extensions](http://fr.habitica.wikia.com/wiki/Int%C3%A9grations_d'Applications_et_d'Extensions) (though that's a disambiguation page, so unless that's actually the best page, perhaps it should be changed), but the `'` is being understood as code instead of escaped so it stops at "d"?

**Comment by Alys** [comment]
Yes, it's a problem with the `'` symbols in the strings in Transifex. If they are escaped in Transifex as `%27` then the link works. However as citrusella suggests, it would be better to link to this page:

http://fr.habitica.wikia.com/wiki/Extensions,_modules_compl%C3%A9mentaires_et_personnalisations

This needs to be fixed in Transifex by changing the link in TWO places:

```
front.json:    "marketing3Lead2": "D'autres **outils tiers** connectent Habitica à d'autres aspects de votre vie. Notre API permet l’intégration facile de choses comme l'[extension Chrome](https://chrome.google.com/webstore/detail/habitica/pidkmpibnnnhneohdgjclfdjpijggmjj?hl=fr-FR), avec laquelle vous perdez des points en naviguant sur des sites non-productifs, et en gagnez sur des sites productifs. [Plus d'informations ici](http://fr.habitica.wikia.com/wiki/Int%C3%A9grations_d%27Applications_et_d%27Extensions).",

settings.json:    "otherExtensions": "<a target='blank' href='http://fr.habitica.wikia.com/wiki/Int%C3%A9grations_d'Applications_et_d'Extensions'>Autres extensions</a>",
```

The front.json link currently does work because the `'` are escaped correctly but points to the outdated disambiguation page.   (We should get that page changed to be a redirect but I'm not an admin on that wiki so I can't now. I'll work on that separately to this issue.)

---

I've tried to edit the settings.json link myself but it is marked as reviewed. We've always told translators that anyone can edit a reviewed string but that seems to not be the case. I'm not a reviewer and I can't edit it. I can edit un-reviewed strings. Assuming I'm not just mistaken about this, it is a significant problem for all languages because I would expect that many reviewers have become inactive.

Is anyone able to confirm that reviewed strings can be edited by only reviewers? The [documentation](https://docs.transifex.com/translation/reviewing-strings#unreviewing-strings) seems to indicate that Translators can't edit reviewed strings:
_"A reviewed string can be unreviewed. When you unreview a string, it brings the string back to the translated state, allowing Translators to edit the translation and Reviewers to review it again."_
but we've been telling people that they can for so long that I'm doubting everything now. :)

If it's confirmed that Translators can't edit reviewed strings, we might want to reconsider our policy of promoting only long-time translators to reviewers in cases where there are no active reviewers.

Is it possible for me to be made a reviewer for all languages? If there's an easy way of doing all at once? That would allow me to help fix translation bugs in cases like this.

pinging @paglias and @shanaqui

**Comment by paglias** [comment]
Fixed both strings, @Alys pinged you in Slack
