### ISSUE TITLE
Mana Points (MP) not decreased when removing Intelligence (INT) Stat Points

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10712]
This is a client-side display problem, not a problem with the underlying API call for allocating Stat Points.

When you allocate Stat Points to Intelligence, you're given 1 MP for each point and your total mana shown in the website is increased immediately, before you have saved your Stat Points allocation. If you change your mind and remove Stat Points from INT before saving, your Mana shown on the website is not decreased. Therefore after you do save, it looks like you have more Mana than you really do. When you sync, your displayed Mana becomes correct. 
Your actual Mana as recorded in your account in Habitica's database is only updated when you save your changes to your Stat Points so it's always correct.

I.e., there needs to be a client-side change so that when you remove a Stat Point allocated to Intelligence, your Mana shown on the website is immediately decreased, OR a sync is immediately forced to ensure that the Mana you're seeing is correct.

Steps to reproduce bug:
1. Have at least one Stat Point available to be allocated (e.g., level up).
1. Click the website's sync button to ensure you're seeing the latest data then record your Mana.
1. Allocate the Stat Point to INT (do NOT click "Save"). Observe that you see a notification for gaining 1 MP.
1. Remove the Stat Point from INT. Observer that you do NOT see a notification for losing 1 MP (ideally you should although that's not critical).
1. Click "Save".
1. Observer your Mana shown in your stat bars in the website's header. It will be 1 greater than what it was before (it should be the same as it was before). This is the part that most needs to be fixed.
1. Sync. Observe that your Mana is now correct (the same as it was before).

**Comment by kirsty-tortoise** [comment]
Can I have a try at this?

**Comment by paglias** [comment]
Go ahead @kirsty-tortoise !

**Comment by SabreCat** [comment]
Hmm, shouldn't we just _not_ show notifications for Mana changing until you save the stat points? It's actually kinda misleading that the notifications appear at all.

**Comment by kirsty-tortoise** [comment]
Perhaps, but changing the Mana without notifications would seem equally misleading in my opinion.

**Comment by kirsty-tortoise** [comment]
Also, now I think about it, is it a problem that you can close the modal without saving and go on to complete tasks etc. with the client and the server not being in agreement on mana and stat points until you save or sync?

**Comment by SabreCat** [comment]
Yes. You should get a single notification when you finish adjusting stats and click "Save", showing how much Mana you gained from the operation, and that should be it!

**Comment by kirsty-tortoise** [comment]
Should the Mana also be added at the end when you click "Save", or when you add the points? It seems to me like having the notification appear at the same time as the Mana is added makes some amount of sense.

**Comment by SabreCat** [comment]
Yes, the notification should coincide with the actual increase to MP.

**Comment by kirsty-tortoise** [comment]
I've found another possible bug (via the UI you can decrease the stat points below what they were to start with, but the server doesn't allow this and they don't match up until you refresh). It is easy to fix, should I do this here or open a new issue?

**Comment by Alys** [comment]
@kirsty-tortoise adding that to your PR was good. Thanks for finding and fixing it!

**Comment by kirsty-tortoise** [comment]
Having thought about it more, maybe changing the users actual stats should wait until after they've clicked save as well, and only the numbers in the "Stat Points" section right at the bottom should change. This would mean that if the user clicked off the modal without saving and tried to perform tasks, the client and server wouldn't be in disagreement about their stat points.

It would also mean we wouldn't have to avoid adding mana on the client but not the server, and could use allocateBulk on both the client and the server after save.

Also maybe some way of knowing that the points have not yet been saved would be helpful?

Opinions?

**Comment by SabreCat** [comment]
@kirsty-tortoise I'd agree with that. We should really only be using allocateBulk here--if we're making server calls on every click, that's not necessary!

**Comment by kirsty-tortoise** [comment]
@SabreCat I believe we aren't making server calls on every click - I've checked and we are updating the client locally on each click (via `allocate`) and then making a server call (to trigger `allocateBulk`) when save is pressed.

So currently the server is using `allocateBulk`, and the client is using `allocate`.

**Comment by kirsty-tortoise** [comment]
Okay, so I've done that mostly, but I have more questions:

### Question 1
See the image below, roughly divided into two sections.

When you click the up arrows on the panel at the bottom, the numbers change but the actual attribute points don't change until you click save. Should the numbers at the top change before saving?

My feeling is 'yes' because:
 a) That's the behaviour at the moment, so if we change it now people are likely to think something is broken rather than intentionally different.
 b) It is useful to be able to see what effects the stat allocations have on your overall stats before saving them.
I just thought I'd check here first.
![image](https://user-images.githubusercontent.com/20494051/46221449-1c508980-c345-11e8-9df6-a56af51fd10e.png)

### Question 2
Can someone explain the reasoning behind this code? It determines whether the little bubble with the number of stat points remaining (next to the 'Stat points' heading in the image above) is shown. Why do users at level 100 or above still need to see it even if they have no points remaining?
https://github.com/HabitRPG/habitica/blob/62c60ce520d00cbbf68c9f8aba2b33bd57d124df/website/client/components/userMenu/profileStats.vue#L126-L127
Anyway, then the question is "if a user had stat points remaining, has allocated them all but not yet pressed save, should they still see that bubble with a 0 in it?"
