### ISSUE TITLE
If you try to send an empty message, empty error appears and persists

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10723]
Pretty much as in the title! Screenshot: 
![image](https://user-images.githubusercontent.com/8144640/46046340-964ffb00-c118-11e8-9c84-1306e04b37b2.png)

Reported by Il Mago, tested by me:

> Il Mago (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) tier 7 Legendary Socialite 
> Bug: if for some reason I try to send an empty chat message I receive an empty red snack message

**Comment by kirsty-tortoise** [comment]
The response received from the server is 
```
error: "BadRequest"
errors: [{message: "You cannot send a blank message", param: "message", value: ""}]
message: "Invalid request parameters."
success: false
```
If an `errors` parameter is received, then the errors is translated into snackbars by the if statement of this code.

https://github.com/HabitRPG/habitica/blob/c5fb2d65066993370bd0f38da1c0e283276491b5/website/client/app.vue#L338-L355

where the errorsToShow list is joined at the end into a snackbar message.

The case `e.param === 'message'` is not handled, so nothing is added to the list of errors, and the error ends up empty.

Possible solutions are to try to change the error sent, or to add a case for `e.param === 'message'` to the code above. I think the latter is correct, since this may occur in many cases of validation, but I haven't been able to test this.

I can attempt this if this is the correct solution.

**Comment by kirsty-tortoise** [comment]
Actually, rethinking it, I got confused, and `e.param === message` is because the parameter which failed validation is the `message` they were trying to send to the chat. In that case, we probably don't want to add a case to this code for each parameter that could fail validation, and instead should rewrite the code to show errors from any parameters that fail validation. I'll have a go at this later.

**Comment by Alys** [comment]
@kirsty-tortoise Thanks!! I've labelled this as in progress for you.
