### ISSUE TITLE
User attempting to change email address to already-taken address gets uninformative error

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10740]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If you attempt to change your email address using site settings, and the address you're trying to swap to is already in the system, you get an error (as expected). However, this error doesn't tell you what's wrong; it just says "Your request cannot be fulfilled. Email admin@habitica.com if this error persists."

![image](https://user-images.githubusercontent.com/4501321/46559194-27f7ff00-c8b5-11e8-8b90-77cee6c35ca9.png)

We should return a more specific "already taken" error from the API if we aren't already, and display it on the client if we are.

**Comment by Alys** [comment]
That was done deliberately to prevent people using the registration form or change email form to find out if someone they know has a habitica account (e.g., in a stalking situation). It's analogous to how the forgot password feature does not confirm whether the email address exists. I recommend we don't change the message. In legit cases where a player sees it, it's (almost?) always because they have an old account they've forgotten about, in which case they benefit from admin help anyway.

I'm going to change this to suggestion-discussion in case we want to discuss further before deciding if we should change it. I hope that's okay.
