### ISSUE TITLE
Top Banner cut off on horizontal resize

### ISSUE THREAD

**Issue by stanhuan** [HabitRPG/habitica#10827]
![c84ecb33687269429dfa38fa885f0a90](https://user-images.githubusercontent.com/10003722/48258104-5dc36280-e3e2-11e8-8a8b-3a376ab51e4c.gif)

### General Info
  * Browser: Google Chrome Version 69.0.3497.100
  * OS: macOS Mojave 10.14 (18A391)

### Description
When resizing the profile page, on small horizontal viewports, the banner gets cut off

**Comment by SemperDisco** [comment]
@stanhuan Can I work on this issue?

**Comment by Alys** [comment]
@SemperDisco Best to wait until an issue is marked as "help wanted" before thinking about working on it. :) Not all issues that are posted in GitHub are suitable for working on at the moment (e.g., some need discussion first about how to best fix them). Have a look at [Guidance for Blacksmiths](https://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) (the "Ways to Help" section) for some tips on choosing issues to work on.

@stanhuan Sorry we never replied to this. The best way to report bugs initially is in the Report a Bug guild - we can do an initial assessment there to see if coding work is done, and then if an issue is needed, either an admin will create one or will advise you to post one. 

On a small screen it would be nice if the user's stats numbers were still visible (even if the coloured bars were very short or missing) and if the create/view party button could still be clicked on. The latter especially would help in cases where the app was not accessible (e.g., due to a temporary problem with the user's data in the app) or if the user's mobile device was too old to be able to use the latest version of the app and the user wanted to use party features that are not available to them in the app.

Pinging @Tressley for comments about whether this could be improved.

**Comment by SemperDisco** [comment]
@Alys Thank you for your comment. I'm a little too eager to work on issues. I'll checkout out the Guidance page. ;)

**Comment by Tressley** [comment]
While some of Habitica's website has been optimized for mobile, there are still a lot of areas that need improvement. This is definitely on our radar, but I think we'll need to do some additional design around the mobile header and tab structure before this being ready for help.

**Comment by Tressley** [comment]
For a quick solution, we should remove the empty party piece. No reason to hide it at a screen size this small. In addition, the Health, Experience, and Mana Points bars should scale accordingly so the text values are visible.

**Comment by jacobguinther** [comment]
@Tressley
When making the stats bars more responsive we would also have to consider how they appear on a users profile. Profile stats bars start to have issues at around the same screen width. I would like to propose tackling the status bars responsiveness on a separate issue where they are considered on both the header and profile.

For this issue.
What do you think about just removing the party piece when nav menu changes to hamburger?

**Comment by Tressley** [comment]
@jacobguinther -- I completely agree! Right now that component is a little messy as it's used in multiple instances (header, profile, member/participant list for parties/guilds/challenges.) I think creating another issue for responsive bars would smart.

As for this issue, yes, let's remove the empty party banner. However, it should only be removed when a user is below tablet size, since tablets still offer enough screen space to display the user's information and the party.
