### ISSUE TITLE
All kinds of bugs!!

### ISSUE THREAD

**Issue by ecska** [HabitRPG/habitica#1083]
My husband and I both play, so we go back and forth on the same computer.

Last night, after checking off all his dailies and getting a new pet (forget which one at the moment), he refreshed, only to have "memory leak." Past midnight, and this morning, he's lost all his streaks, the pet, and a lot of HP.

After him logging out this morning, I wasn't able to even sign on ("memory leak") until 7 pm today. And I'm having all sorts of similar issues. Check off everything, reload to make sure it saved, not only did it not save, but I've lost things. A different one every time, but I tried multiple times. Eggs, HP, EXP. I still have my streaks, thankfully.

And, reloading is taking FOREVER. And, no, it's not my internet connection. Tried to put out feelers in the tavern, but it's clearly having its own issues at the moment (hello gazillion reposts!) and it never posted. The screen wasn't frozen, exactly, but nothing would happen.

Now I'm back to the "memory leak" page and anticipating losing all my 17-day streaks in the morning, if I can even sign on.

I know it's a work in progress, and I am unfortunately unable to help, I just wanted to know if there's a particularly large amount of issues at the moment or if there's something wrong with just us.

Thanks!!

**Comment by PaulyG14** [comment]
Hi there, I'm very new to this, but what usually gets me past the memory leak error is typing https://beta.habitrpg.com/ instead of just https://habitrpg.com/ in the explorer bar.
Don't know if you've already tried this, or if it will work for you, but it certainly seems to work for me.
I also lost a pet today :'(

**Comment by ecska** [comment]
Thanks PaulyG14!
I'm pretty new also. The beta address super helped. The pages all responded at a normal speed, and correctly.
Now if only I could figure out how to get back the EXP, HP and pets. :-)

**Comment by PaulyG14** [comment]
Glad I could help! :)

**Comment by octern** [comment]
Changes I make on the beta server don't seem to reliably show up when I switch back to the main server, and vice versa. I assume they connect to the same database so I'm not sure how that's even possible.

**Comment by lefnire** [comment]
Things were really bad for the last 3 days at least. Most of these issues have been fixed in the last few hours, so things should be running smoothly now. It's a matter of high traffic and large database size, and the fact that Derby 0.3.x can't do horizontal scaling. The 0.5 upgrade will really save our butts here!

**Comment by ecska** [comment]
Glad to know it wasn't just us.

It has gotten much better, thanks!

Wish I was more of the right kind of nerd to be of assistance. :-)

**Comment by StanLindsey** [comment]
Also check out Settings > Restoire to manually set your Health, Experience, Items if a bug catches you of guard.
