### ISSUE TITLE
Account Deletion Feedback: update email

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#10880]
~We had to remove the Kafka queue that handled account deletion feedbacks, it should be re-implemented but instead of sending the feedback to a Google Spreadsheet file it should send an email to the admin inbox~

See @Alys comment right below for the changes that need to be made

**Comment by Alys** [comment]
I started writing some notes here as I was looking through the code, because I wanted to give some pointers about what changes are needed, and then I got confused because it looks very much as if the Kafka queue was already not being used for the deletion feedback. I tested by deleting a test account and the feedback email came through to us as normal, so it looks like removing the Kafka queue had no effect on the feedback process. Hence I'm not sure anything needs to be done. We seem to have already converted the code from using Kafka to using the same method as is currently used for emails to mods (the requirement to use that method is the main point I was going to make here). 

Anyway, here's some random gibbering about this issue... :laughing: There is actually a small improvement that could be made even if nothing else is done.

---

To the coder who works on this:

The current handling for deletion feedback is here:
https://github.com/HabitRPG/habitica/blob/de0c62a37ff05b63dd3a46ebeb664ba4662eb5b4/website/server/controllers/api-v3/user.js#L293-L303

It sends an email to admin@habitica.com (`TECH_ASSISTANCE_EMAIL`) containing the player's details and the feedback they provided.

The same email address and the same `admin-feedback` email template should continue to be used. 
However I'd like this line to be added to the parameters for the email template:
```
        {name: 'USERNAME', content: user.auth.local.username},
```
It should go just under the PROFILE_NAME line that you see above. I have already updated the email template in our Mandrill account to accommodate the USERNAME parameter (this has not caused the emails that we receive to break so it is not urgent to add the USERNAME parameter).

---

For comparison, here's the code that's used to send group flag report emails to moderators:

https://github.com/HabitRPG/habitica/blob/de0c62a37ff05b63dd3a46ebeb664ba4662eb5b4/website/server/libs/chatReporting/groupChatReporter.js#L56-L62

The `txnEmail` and `sendTxn` functions are the same, they've just been given different names in the `import` lines, for reasons I don't know. I'd quite like them to have the same name for clarity and I suggest using `sendTxn` everywhere if possible. Here's two examples of the `import` code:

https://github.com/HabitRPG/habitica/blob/de0c62a37ff05b63dd3a46ebeb664ba4662eb5b4/website/server/libs/chatReporting/groupChatReporter.js#L9

https://github.com/HabitRPG/habitica/blob/de0c62a37ff05b63dd3a46ebeb664ba4662eb5b4/website/server/controllers/api-v3/user.js#L17-L20

---

The Google Spreadsheet is updated manually from the data in those emails so there's no code that needs to be modified for that.

**Comment by paglias** [comment]
Ah okay, sorry I got confused. It looks like the email is sent and then the kafka queue was used to also update the Google Spreadsheet automatically. I'll rename the issue and remove the leftover code

**Comment by paglias** [comment]
The leftover code was removed in https://github.com/HabitRPG/habitica/commit/7873800f87ffebf207957e4743be4d86c3c16f20

**Comment by Alys** [comment]
I was clearly confused too. I was sure the spreadsheet was done manually. :)
