### ISSUE TITLE
Habitica wiki *.wikia.com links will change to *.fandom.com in January/February 2019

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10954]
_This is on hold for now. I want it here so we don't forget later and can plan for the work when it is needed._

As described at [Help:Fandom domain migration](https://community.wikia.com/wiki/Help:Fandom_domain_migration), the wikia.com domains are being migrated to fandom.com and the process is expected to be completed in early February 2019.

This will affect our habitica.wikia.com site and all of the non-English wikis.

When the change has been made, we'll want to update wikia.com links throughout the website and mobile apps (FYI @phillipthelen). However it won't be urgent because as that help page says "The existing wikia.com domains will all redirect to fandom.com, so any bookmarks or links across the web will continue to work as they do now."

There'll likely also be some links within the wikis themselves that have the wikia.com domain hard-coded in them but wiki editors will fix that so it doesn't need to be considered in this issue.

For this issue, we might want to consider editing the locales files for all languages since they aren't being managed in Transifex any more. A search-replace with sed or similar could do it with little effort.

I'll take this off hold when the change has been made.

**Comment by GiacomoLaw** [comment]
I'd be happy to take this when the time comes.

**Comment by cTheDragons** [comment]
Good morning, just letting you know fandom has migrated to fandom.com today.

**Comment by Alys** [comment]
@cTheDragons thanks very much for the notification!

**Staff**: Are you okay with all the locales files being changed in the fix for this issue? I'll wait a couple of day for objections and then mark this as help wanted if there's none.

@GiacomoLaw I'll ping you when it's marked as help wanted and you'll get first chance to confirm if you still want it. Thanks!

**Comment by GiacomoLaw** [comment]
@alys awesome, thanks!

**Comment by paglias** [comment]
@Alys I'm fine with changing them I'm just unsure how the situation regarding Transifex is and if we have a system in place to update locales across all languages

**Comment by Alys** [comment]
@GiacomoLaw You can start on this now. I've marked it as in progress for you but let us know if something's come up that prevents you having time. 

For this particular change, you can ignore the usual restriction that prevents people changing the locales files for the non-"en" directories. You're welcome to change all instances of "wikia.com" to "fandom.com" in all the locates subdirectories and anywhere else they appear. Note that some of the non-en locales files will reference non-English wikis (e.g., "de.habitica.wikia.com") and you should keep the language abbreviation in those URLs (so that example would change to "de.habitica.fandom.com").

**Comment by citrusella** [comment]
I think not all the wikis in various languages have changed over. Ones that haven't do still prefix the language and *will* fail as a link (redirect to Wikia's "community doesn't exist" page) if simply changing the "wikia" to "fandom" in the link.

Links in non-English languages that have changed domain already *also* fail with the link example provided above because Wikia has changed the link's format from what I guess I'll call MediaWiki's "default" (lang.wiki.site.com) to the following format: https://habitica.fandom.com/de/wiki/Habitica_Wiki (that being the de example equivalent, though a link to the main page). Changing the link of a non-English wiki that is still on the wikia domain to this format is another link failure state.

This format change is a separate thing that they decided to introduce in concurrence with updating the domain AFAIK, but it's a very important thing to note if you're updating non-English wiki links.

**Comment by Alys** [comment]
@citrusella Thank you!!! :heart:

@GiacomoLaw if you're not certain that a non-English wiki's domain name has been changed yet, just leave it as it is in all files for that language. If you'd prefer to do just the "https://habitica.wikia.com/..." links, that's fine (we can do the others later).

**Comment by GiacomoLaw** [comment]
Cool, I'll get onto it now.

**Comment by GiacomoLaw** [comment]
@Alys made the changes - hope it's all ok
