### ISSUE TITLE
Use AGPL instead of GPL

### ISSUE THREAD

**Issue by heyakyra** [HabitRPG/habitica#1101]
https://www.gnu.org/licenses/why-affero-gpl.html

The AGPL was designed for web apps. The GPL and most copyleft licenses don't work for software that is run as a service (because the users never get a copy of the software, they just interact with it on someone else's server, so the person running the software doesn't have to keep the code free).

The AGPL means that anyone providing access to use the software through a server still has to make the source available, so that they can't make changes and profit from it without sharing those changes back. This would probably alleviate the non-commercial requirement in the license page now, too! 
##

**Comment by lefnire** [comment]
Would that mean that we at habitrpg couldn't keep any private source as
well? We may want a private branch at some point for manager accounts IP
(which won't effect 99% of you)

**Comment by heyakyra** [comment]
Nope not at all. Unless you are importing someone else's AGPL code and modify it with the private source you're talking about. Otherwise, as the original licensor, you can keep whatever you want private. Just don't release the private code! [=

**Comment by wizonesolutions** [comment]
Yeah, I am thinking of open sourcing the code to a web app as AGPL as well, so people can run their own copies if they want, but the commercial provider of it would be me (and I could do whatever I wanted because I was the licensor). And I was thinking that that license'd fit Habit too.

@lefnire Remember iText free? That's AGPL. That's why you had to OS the fillpdf-service Java code.

**Comment by wizonesolutions** [comment]
@kxra I see a problem with the AGPL: https://news.ycombinator.com/item?id=1273416

If @lefnire wants to use people's contributions in a commercial version, will we have to start requiring contributors to assign their copyright to HabitRPG? That'd likely dampen contributions.

**Comment by wizonesolutions** [comment]
Having said all that... http://owncloud.org/about/contributor-agreement/ looks like a reasonable way to do it. See the link about the bottom about the "covenant." So people aren't assigning copyright wholesale. They do it and in exchange have assurance that Habit will stay open. And if they don't want to sign a CLA, they can license their individual contribution as MIT.

...although apparently there is dislike of the AGPL... http://redmonk.com/sogrady/2012/09/10/agpl/

Maybe worth asking someone from ownCloud how it's working for them. So, taking a random guess: @tanghus (you committed the latest change to `CONTRIBUTING.md` in ownCloud core)?

Also, I tried looking up if AGPL contributions can be licensed as MIT — I thought the AGPL prohibited relicensing — but maybe you guys have gotten legal advice on that?

**Comment by tanghus** [comment]
@wizonesolutions sorry, I'm really an ignorant license wise. I just corrected a path in that file :)

**Comment by heyakyra** [comment]
> If @lefnire wants to use people's contributions in a commercial version, will we have to start requiring contributors to assign their copyright to HabitRPG? That'd likely dampen contributions.

This is not true at all. The only case they would have to do this is if you wanted the power to suddenly relicense HabitRPG which would defeat the point of a copyleft license like the GPL. 

Also the dislike of the AGPL is about closing the loophole for web apps, which is exactly why it makes sense for HabitRPG to use it. 

AGPL cantributions can be relicensed by the copyright holder.

**Comment by wizonesolutions** [comment]
@tanghus Do you know who in ownCloud might be the license savant? :)

@kxra Ah I see, so the originator of the AGPL contribution can do what they want. Makes sense.

Some orgs, though, do want code under a commercial license so they don't have to think about AGPL compliance. In that case, requiring a CLA or MIT-licensed contributions seems necessary. The ownCloud model seems well-thought out.

**Comment by heyakyra** [comment]
I'm very confused by what you mean by commercial. All free software licenses are compatible with commercial use (GPL, MIT, etc). The point of copyleft licenses like the GPL is to make sure that anyone who does use the code (for profit or otherwise) and changes it, has to also share their code. I'm assuming that's why HabitRPG chose a copyleft license in the first place. To protect against people taking the code and making it proprietary.

**Comment by wizonesolutions** [comment]
@kxra Sorry, I wasn't talking strictly about Habit. I think it's a good fit for Habit as long as they will never relicense it commercially to any individual entities.

Example of this: iText. If people want to use iText in their apps, they can use it under the standard AGPL license or commercially. If they use it AGPL (e.g. https://github.com/wizonesolutions/fillpdf-service), then they have to provide the source code to the implementing application. Some organizations may not want to do this. In that case, they can pay money to iText to be freed from those license terms.

That means contributions to software like iText would either need to be MIT or would need to assign copyright to iText. Otherwise, they wouldn't be able to use the contributions in the commercially-licensed version.

I was mostly raising the point generally just to explore the topic from different angles.

**Comment by lefnire** [comment]
i'll revisit this soon. marking as critical so it's at top of list when i come back to it, should be simple enough.

**Comment by UsuallyPassive** [comment]
This issue has been quiet for a while now, despite being quite important, so I figured I'd try to reinitiate the discussion.
I'll start it off by arguing for the AGPL ('cause I'm a free software enthusiast).

<b>Counterargument to the Pro-GPL Arguments Above</b>
The only argument for the use of the GPL found in the previous discussions is the possibility of making a proprietary branch for manager accounts. I'll argue that this is not much of an advantage. Supposing that this branch has few extra features, it would not be very hard for anyone else to add these features themselves and release them to the public. And if the branch has a lot of extra features, it will almost certainly be useful to much more than 1% of the users. Plus, making a proprietary version of software using unpaid user contributions made with the expectation of the software being free is not very nice.

<b>Arguments for the AGPL</b>
For server-side software, the GPL doesn't classify as a copyleft license, because to be copyleft, it must not be possible for middlemen to take the code and turn it proprietary. This also means that while HabitRPG is free now, there are no guarantees that it will stay so forever. We have to trust lefnire to keep it free, and no offense to you, lefnire, but I don't know you, and I can come up with at least one plausible scenario where turning proprietary or shutting down would be the only options for HabitRPG, which I will describe in the next couple of paragraphs.
As it is, anyone can take the code and make a proprietary HabitRPG. They'd only need to remake some of the non-commercial sprites, which would be a minor inconvenience for any semi-large corporation.
This is not a paranoid fear.
When HabitRPG becomes popular enough (it's so effective, I have a hard time imagining it not succeeding), competitors will arise. These competitors will have two choices; write all their code from scratch, or take the free code from HRPG and improve from there. Obviously, they'll take the HRPG code. They would never have to give back the changes they make, and they would be able to integrate all the improvements made by HRPG itself into their own code. This is a serious competitive advantage, placing them forever one step ahead of HabitRPG.
Faced with such strictly better options, few new users will be coming to HabitRPG, and most users, not being particulary loyal to HRPG, will have no qualms with switching should they gain any incentive to do so. HabitRPG, facing serious monetary issues from lack of users, will then be forced to either stop being free software, or shut down. Either way, the free HabitRPG will be no more.

And that's my argument. Does anyone have any good arguments for the GPL? Being biased towards the AGPL, I'm having a hard time coming up with any.
But either way lefnire chooses, I hope for a quick resolution of this issue, so that I can know better what to expect from HabitRPG's future.

**Comment by wizonesolutions** [comment]
I was going to object, but realized I actually agree. If competitors who
rewrite moneymaking features have to publish that code, but Habit can keep
it private (as copyright owner) that's an advantage.

As for contributors, pretty sure Habit is getting IP rights to private
work, or @lefnire is writing the code, so unlikely an issue.

**Comment by lefnire** [comment]
cc'ing @veeeeeee in on this, I'll catch up on it soon

**Comment by crookedneighbor** [comment]
@veeeeeee Any thoughts on this?

**Comment by lemoness** [comment]
I've reached out to Vicky to see if this is still relevant.

**Comment by lemoness** [comment]
She says: One critical question to ask right now is what license everything else we're using (other libraries etc) is on. If there's code that's still licensed through GPL 2.0 that hasn't been upgraded (and doesn't look like it will be) then changing over to AGPL is right out.

**Comment by lemoness** [comment]
Unfortunately, it looks like based on our dependencies, this will not be possible.

**Comment by heyakyra** [comment]
Ah, which dependencies?
