### ISSUE TITLE
Mystery Item gift box number does not decrease when gifts are claimed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11029]
From @cTheDragons (bc10ec41-4213-4482-bbb8-558e3c3ea8d5), confirmed by me on the habitica.com site:

"When I click on my mystery box on the website, the box number does not decrease or disappear when I pull out each item."

I'm marking this high priority because it's going to confuse subscribers over the next few days.

---

To replicate this bug in a local install, use a database update command to modify a user's document in the `users` collection. Set `purchased.plan.mysteryItems` to an array like this:
`[ "eyewear_mystery_201902", "shield_mystery_201902" ]`
You don't need to set up any subscription details too - that array alone is enough.
You can put as many Mystery Items in the array as you want to make testing easier. Below are other examples. Note that once you've claimed a particular item, you shouldn't put it back into the `mysteryItems` array because claiming it when you already own it might give errors.

"armor_mystery_201402", "armor_mystery_201403", "armor_mystery_201405", "armor_mystery_201406", "armor_mystery_201407", "armor_mystery_201408", "armor_mystery_201409", "armor_mystery_201410", "armor_mystery_201412", "armor_mystery_201501", "armor_mystery_201503", "armor_mystery_201504", "armor_mystery_201506",

**Comment by ChesterSng** [comment]
Hi @Alys I would like to try this issue!

**Comment by alecbrick** [comment]
Currently looking at this, but if anyone else is interested, another set of eyes would be great.

**Comment by alecbrick** [comment]
It looks like the issue is that the Mystery Item object is getting changed correctly in client/components/inventory/items/index.vue, but the countBadge object (line 127) isn't being re-rendered. I've considered adding a key to the countBadge which links to the inventory's data(), then updating that key whenever we open a Mystery Item - that would force the countBadge to re-render. That feels a bit hacky to me, but since I'm not really a Vue expert, I don't really know the best way to handle this.
