### ISSUE TITLE
Gem purchases of avatar customisation items should not be possible when you own them

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11050]
Black Rabbit / @niela (a49e76ca-5f53-44dc-9c20-36abfbec375a) says:

"I just lost 5 gems 'cause the habitica sync didn't show me that I already brought my animals' ears pack."

Confirmed in Amplitude (links will work for only admins):

[event 1](https://analytics.amplitude.com/habitica/project/132025/search/a49e76ca-5f53-44dc-9c20-36abfbec375a?eventFilter=purchase&eventFilter=acquire%20item&sessionHandle=WlV9FDr_WlV9FSa_D%252Bjsav_gO5_070511e6-a0e0-49d5-936b-e34f81197752&eventId=0b49717c-4083-11e9-a76b-066ed5d8f214)

```
March 7, 2019 2:45:16 am UTC
acquire item

acquireMethod: Gems
gemCost: 5
itemKey: items.gear.owned.headAccessory_special_bearEars,items.gear.owned.headAccessory_special_cactusEars,items.gear.owned.headAccessory_special_foxEars,items.gear.owned.headAccessory_special_lionEars,items.gear.owned.headAccessory_special_pandaEars,items.gear.owned.headAccessory_special_pigEars,items.gear.owned.headAccessory_special_tigerEars,items.gear.owned.headAccessory_special_wolfEars
```

[event 2](https://analytics.amplitude.com/habitica/project/132025/search/a49e76ca-5f53-44dc-9c20-36abfbec375a?eventFilter=purchase&eventFilter=acquire%20item&sessionHandle=WlV9FDr_WlV9FSa_D%252Bjsav_gO5_070511e6-a0e0-49d5-936b-e34f81197752&eventId=15b32914-4083-11e9-a76b-066ed5d8f214)
```
March 7, 2019 
2:45:33 am UTC
acquireMethod: Gems
gemCost: 5
itemKey: items.gear.owned.headAccessory_special_bearEars,items.gear.owned.headAccessory_special_cactusEars,items.gear.owned.headAccessory_special_foxEars,items.gear.owned.headAccessory_special_lionEars,items.gear.owned.headAccessory_special_pandaEars,items.gear.owned.headAccessory_special_pigEars,items.gear.owned.headAccessory_special_tigerEars,items.gear.owned.headAccessory_special_wolfEars
```

`balanceGemAmount` on events before and after those shows that 10 Gems were indeed removed.

I've refunded the extra 5 Gems.

I'm leaving this as suggestion-discussion for the staff to comment on an appropriate way to fix it. The avatar customisation purchases for items like ears, backgrounds, etc, need changes for other reasons too (as discussed elsewhere in the past) so the fix for this issue might be best rolled into that.

**Comment by SabreCat** [comment]
The API should definitely catch this and return an error instead of deducting further Gems. We or a contributor can fix that much, pending a bigger refactor of how the customization "unlocks" work.

**Comment by benkelaar** [comment]
I can pick this one up, all the markdown-mention work is waiting for input from others :)

**Comment by Alys** [comment]
@benkelaar Fantastic, thanks! :)

You're probably aware of this, but if an equipment item is available in your account with either a `true` or `false` value, it means you have previously bought it (for either gold or gems), and those should always be re-purchasable with gold only (or for free, depending on the item). E.g.,:
```
"items.gear.owned.gear_key_1": true,  // owned and can be equipped
"items.gear.owned.gear_key_2": false, // lost due to death
```
So the API should prevent gems being spent if there's a `true` or `false` value.

An item that has never been bought will not appear in your `items.gear.owned` object at all.

**Comment by benkelaar** [comment]
OK, I finally managed to confirm the bug: I can curl the unlock endpoint as often as I like and it'll keep subtracting gems from the user.

```bash
curl -X POST "http://localhost:3000/api/v4/user/unlock?path=items.gear.owned.headAccessory_special_bearEars,items.gear.owned.headAccessory_special_cactusEars,items.gear.owned.headAccessory_special_foxEars,items.gear.owned.headAccessory_special_lionEars,items.gear.owned.headAccessory_special_pandaEars,items.gear.owned.headAccessory_special_pigEars,items.gear.owned.headAccessory_special_tigerEars,items.gear.owned.headAccessory_special_wolfEars" -H "Accept:application/json" -H "x-api-user:$HABITICA_USER_ID" -H "x-api-key:$HABITICA_API_KEY" -H "x-client:local-tester-curl"
```

**Comment by benkelaar** [comment]
Did some more research over the weekend. Both the unit tests and integration tests do not display this behaviour.

What happens is that after the request is done, the `purchased` values have not been stored in the database, and since that's what's being checked to see if the user already bought the items, the next time the endpoint is being called it just assumes you're buying it again.

Now why this behaviour does not happen in the integration tests I don't know. I think it might have something to do with how `markModified` interacts with `user.save()` (and perhaps that part might work differently in the integration tests, either through dependency injection or partial initialisation) but I'll need to go into that part of the code to figure it out.

What I've been wondering separate from all that is, why store the items in a separate `purchased` field at all? Why not simply check the owned field for ownership?

**Comment by paglias** [comment]
> What I've been wondering separate from all that is, why store the items in a separate purchased field at all? Why not simply check the owned field for ownership?

That is probably coming from a super old database schema from the initial days of Habitica. We fixed the ones that had the biggest impact on performances but not all of them.

> What happens is that after the request is done, the purchased values have not been stored in the database, and since that's what's being checked to see if the user already bought the items, the next time the endpoint is being called it just assumes you're buying it again.

Is this happening in the tests only or while making normal API requests?

**Comment by paglias** [comment]
@SabreCat or @Alys might know more about the `purchased` object behavior

**Comment by paglias** [comment]
And about the `markModified` call it's used to signal to Mongoose that an object of `Mixed` type has changed and should be saved to the database, it's used for schema-less objects like [purchased](https://github.com/HabitRPG/habitica/blob/develop/website/server/models/user/schema.js#L171) (either because they don't have a defined list of fields or because they have so many fields that they would slow down considerably the object creation)

**Comment by benkelaar** [comment]
Thanks for all the info! I'll see if I can perhaps look in to simplifying the DB model, kinda depends on whether the purchased information is used for anything else. But probably not something that should be blocking the resolution of this issue.

> Is this happening in the tests only or while making normal API requests?

That's the weird thing, it's only happening when making normal API requests, but not with the tests. So besides the bug there's apparently also a test coverage issue. Looking in to it now.

**Comment by benkelaar** [comment]
Phew, this was a fun one to track down!

The problem was that the unlock code was setting the purchased field to markModified, but the purchased field is in fact not schema-less in the schema. It has several declared sub-fields that are schema-less, but items was not among them. Therefor mongoose ignored the modified status of purchased and with it the values that were set there. Declaring a Mixed items sub-field in the purchased document fixed it.

There are still quite some questions open though:
- Why didn't the integration tests catch this?
- Do we need to migrate all current owned gear into the purchased column to guard current users against accidental double billing?
