### ISSUE TITLE
Orb of Rebirth should reload website

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11114]
When you use the Orb of Rebirth, the website should reload itself as soon as the Rebirth has occurred so that all changes caused by Rebirth are seen immediately.

Currently, there's no visual change after Rebirth has happened so it looks like Rebirth hasn't worked. Worst of all, if the user was at or above level 100 and so had Rebirth available for free, it looks like it's still free so they try to use it again not realising they'll be charged gems.

I'm marking this as high priority since it's causing players to buy Rebirth multiple times, which wastes their gems.

**Comment by GiacomoLaw** [comment]
Would adding `location.reload();` to the below function work?

https://github.com/HabitRPG/habitica/blob/e5d834b40aa4407ab8603dc911e94e052d15174a/website/common/script/ops/rebirth.js#L102-L105

**Comment by citrusella** [comment]
For what it's worth, the modal you get when you click the achievement notification (which does pop up in the corner of the page when you rebirth) still properly reloads the site when closed.

(Would making the site reload without actioning that notification prevent it from ever being available to the player? Would returning that notification into a generates-a-modal-instead-of-a-notification kind be an alternative solution?

**Comment by HydeHunter2** [comment]
I'd like to take this

**Comment by citrusella** [comment]
Question I still feel merits some kind of response: Does the suggested solution completely remove the rebirth achievement modal by way of rendering it inaccessible (that is, is there no delay in reload that would allow the notification rebirth generates to be clicked)? (I might have a sentimental attachment to that modal because I like the information it tells me, i.e. the whole "congrats, this is rebirth x for you, etc. etc." but I feel this is a question worth asking.)

Would it be more prudent to fix the issue by way of making the modal a modal-modal (like it was at some point previously) and not a notification-modal?

**Comment by paglias** [comment]
@Tressley do you have any indication regarding @citrusella 's question on how you'd like this to be solved?

**Comment by HydeHunter2** [comment]
If I understand correctly what you want, then the achievement "`Began a new Adventure`" will not be removed.

Here's how it will happen if this pull request is merged:
1) You buy `Orb of Rebirth`.
2) A notice "`You bought the Orb of Rebirth`" appears.
3) The page automatically reloads.
4) And only then the achievement "`Began a new Adventure`" appears.
5) You can click on it to see the modal with congratulations.

**Comment by citrusella** [comment]
Oh. I couldn't tell that from just reading the PR. Is this a case of my kindergarten-level understanding of Javascript again? (I might have also been remembering [a past instance where the site instead of the modal initiating the reload](https://github.com/HabitRPG/habitica/issues/9770) resulted in the modal being unreadable--though in that instance it was a modal that popped up before the site reloaded, not a notification or a modal that appeared after.)

Just to make sure *I* understand correctly, you are referring to the "snackbar" (righthand side) notification for rebirth that opens the modal that includes the [rebirthAchievement/rebirthAchivement100](https://github.com/HabitRPG/habitica/blob/2eab8b2c8b78fb4f0cb681632c99c9f68c543773/website/common/locales/en/rebirth.json#L17) text, right? (Saying "the achievement won't be removed" briefly had me thinking you thought I meant the actual achievement, like the one in the profile. XP)

**Comment by Tressley** [comment]
I think points 4 and 5 should be consolidated into one. I don't think we should be tucking achievements behind snack notifications.

**Comment by HydeHunter2** [comment]
Okay, I'll fix it soon

**Comment by Tressley** [comment]
@HydeHunter2 -- With that being said, I think we need to give the achievement modal some attention because at the moment you have no idea what you've achieved. 😅 

![image](https://user-images.githubusercontent.com/2686586/56607139-c9d30500-65d5-11e9-8303-576b2cda98f5.png)

**Comment by citrusella** [comment]
In that case, is it better to just un-snack the existing notification? Clicking close on it already initiates a reload. Or is changing the reload to before, showing it after, and un-snacking better?

Apparently the snacking came from the issue I linked in my last comment, but there's like four or five modals that have been put inside snackbars? (Or [seven, apparently](https://github.com/HabitRPG/habitica/pull/10564).) Looking at the chat on that PR actually appears that the "bug" may have been introduced then? It appears rebirth might reload the website without closing (or even opening!) the modal but not immediately.

**Comment by HydeHunter2** [comment]
Hmm, this is the screenshot[you sent] of what achievement?


Just the achievement "Began a New Adventure" has a description. Or are you talking about something else?
![Снимок экрана 2019-04-23 в 21 47 44](https://user-images.githubusercontent.com/46248839/56607919-50a5d300-6612-11e9-9852-720ba6c375f4.png)
![Github](https://user-images.githubusercontent.com/46248839/56607676-c9f0f600-6611-11e9-85bd-57db3df2c3b8.png)

**Comment by HydeHunter2** [comment]
@Tressley please help me choose.
Do I have to restart page before or after the achievement modal appears?

Like:
```
Option 1:
1) Buy Orb
2) Restart page
3) Show achievement modal 
```
OR
```
Option 2:
1) Buy Orb
2) Immediately show achievement modal
3) Restart page after pressing "Huzzah"
```

**Comment by HydeHunter2** [comment]
I consolidated points 4 and 5 into one. If necessary, I'll move the reloading page, wherever you want.

P.S. Thanks, @citrusella ! You were right. This issue introduced after [this](https://github.com/HabitRPG/habitica/pull/10564) pull request. Knowing this helped me thanks to you :]

**Comment by Tressley** [comment]
@HydeHunter2 -- The modal screenshot I shared is the modal that is displayed when you click on the snack notification. This was during testing on a new account.

As for the refresh, I think your first option is my preference.

**Comment by HydeHunter2** [comment]
Okay, thanks for answer!
I think we've discussed everything and a pull request's code can be reviewed.

**Comment by paglias** [comment]
thanks @HydeHunter2 ! Sorry for the delay but before the end of the week I'll be sure to give a look at your PRs
