### ISSUE TITLE
Font is very faint on quest modal

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11117]
Screenshot from user: 

![image](https://user-images.githubusercontent.com/8144640/56366758-beee2e00-61eb-11e9-82ee-1b39b6483334.png)

Screenshot from me highlighting the issue since it's difficult to see:

![image](https://user-images.githubusercontent.com/8144640/56366838-ec3adc00-61eb-11e9-9b17-2741a7ffae79.png)

Seems to happen for all quests. Both me and the reporting user are on Google Chrome.

**Comment by citrusella** [comment]
This happens on Firefox, too. Probably in all browsers. The color is set by the .row class, presumably in [questInfo.vue](https://github.com/HabitRPG/habitica/blob/9a6aa5f443a384a30ff26dab3d98037b30993d92/website/client/components/shops/quests/questInfo.vue).

**Comment by renatacavalheiro** [comment]
Hi!  Could I help on this issue? 😊

**Comment by paglias** [comment]
Sure @rezzycavalheiro ! Let us know if you have any question

**Comment by citrusella** [comment]
I was playing around with this myself even though it's already claimed (because I wanted to wrap my head around how editing things worked (using an issue I thought I mostly understood) and figure out if I was cut out for the Habitica coding life--apparently I might be? XD), but while I was doing all that playing, I noticed the HP/collect and difficulty labels are also extremely low contrast (in the other direction, grey on grey) in the popover when you hover over a quest in the menu on the left of the quest modal.

Is that something that should be considered relevant to this issue too, since it's also a faint font related to the quest modal, or is it a separate issue?

(I did manage to fix the issue (both ones) while playing around but I don't know if perhaps my own fix is kind of inelegant, *plus* rezzycavalheiro is already on it; I really only brought this up because of the contrast issue I saw that hadn't been noted here.)

**Comment by paglias** [comment]
> Is that something that should be considered relevant to this issue too, since it's also a faint font related to the quest modal, or is it a separate issue?

I'd say related :) But if it includes some changes in the color let's see if @Tressley has any advice

**Comment by Tressley** [comment]
Oh, wow. That is pretty faint. Here's what the modal should look like:

![image](https://user-images.githubusercontent.com/2686586/57144235-a3a82480-6d8e-11e9-8bfc-203bb088d505.png)

And here's what the tooltips should look like:

![image](https://user-images.githubusercontent.com/2686586/57144374-f255be80-6d8e-11e9-893b-7564d9f716f8.png)

**Comment by citrusella** [comment]
The PR that closed this issue appears to have only fixed the pale numbers on the white background, not the dark text on the dark popover background.

I think I got a working fix for that happening way back when I was playing around to get the hang of editing things for Github in May. My installation is a bit behind but I could update it and see if the fix still works, if that's wanted/okay.

...What on Earth, I was actually only going to ask if this issue should be reopened for that reason, but eh, I guess I'll volunteer to try out a fix too. XD

**Comment by Alys** [comment]
@citrusella  XD Thanks! Please do. :)

**Comment by citrusella** [comment]
Okay! I'll get my install updated (and hope I don't make brain farts and run into problems like the last two times I updated) and test it out! :)
