### ISSUE TITLE
Cannot unequip an item lost due to death

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11128]
> DipperDolphin   @dipperdolphin (1951d08e-56af-445e-8554-f70633b6eaa6) [web] tier 1: Friend Blacksmith hide user's details
> Hi guys, I want to remove my back accessory but clicking on it won't let me as it appears that I don't own it anymore. How can I remove it?
> 
> Thanks

Needs investigation, not replicated.

**Comment by Alys** [comment]
From what I've seen, that user didn't lose the item due to death (it was a mystery item that should never be taken by death). I think they might have got into an odd situation with their gear from using the API somehow. I've asked them in RaB to provide any details they can think of about how the gear item became equipped and what console messages happen when they try to remove it. 

I'm closing this now since we can't investigate further until we hear back from them but we can reopen it if it looks like it needs coding fixes.
