### ISSUE TITLE
Edit/deleting tasks in a challenge appears possible for people who are not admin/the creator

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11137]
_EDIT: see the first comment for the desired fix._

> Hello! For some reason when I view a challenge, even through I am not the challenge owner, the option to edit/delete tasks shows up. If I click the edit button, it does nothing. If I click the delete button, I get a message saying that only the challenge owner can edit/delete tasks.
> 
> If you need to check anything, I tested it using a challenge (now deleted) on my party using an account set up for this purpose (@testaccount_, user ID 45b888e5-e6ce-45b8-b75b-18019b27fdeb).

Reported today by @RobotKing (7966165f-4b5c-4ad3-b761-e99f3b729400). 

Not tested at the moment; is it possible this is intentional for some reason (since we do have an error for it)?

**Comment by Alys** [comment]
The desired fix for this is that when you are viewing a challenge's own page (i.e., a URL like https://habitica.com/challenges/cd2ad408-412a-4eba-9258-054754b26ffb ), then the three-dots menu on each task (shown in the screenshot below) should NOT appear unless you have permission to modify the challenge. This function can be used to determine if a player has permission:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/server/models/challenge.js#L81-L83

![image](https://user-images.githubusercontent.com/1495809/60394903-ad6fbd80-9b6e-11e9-82a0-bb02d630ad75.png)

_(To answer shanaqui's question: I believe it's not intentional that the edit/delete options are visible to everyone. The reason there's an error message is because it's a fallback protection for cases where a front-end user interface doesn't block editing.)_

**Comment by Xaz16** [comment]
Hi folks!
@Alys, could you please assign this task to me? :)

**Comment by Alys** [comment]
@Xaz16 Thanks! I've marked it as in progress for you.

**Comment by Xaz16** [comment]
@Alys or @shanaqui I noticed that such situation we have for group tasks. I mean that I can be non leader user, but have all options to edit and delete group task. When I'm tried to delete it I of course get the "Non Authorised user" error and when I try to edit something I can do that (even assign task, but only for my current user) but when I push "Save" button of group task I retrieve the same error. 

I tried to find some issue about it, but have no success. Maybe you can create new one or show existing? Then I can fix it in pull request for this issue due to I already have solution to centralised hide of options for some part of user (non admin, leader of group or challenge).

**Comment by Xaz16** [comment]
PR: https://github.com/HabitRPG/habitica/pull/11349

**Comment by Alys** [comment]
@Xaz16 Thanks for noticing that! Feel free to add a fix to your current PR now if you wish. It's not essential to have an issue for it first.

**Comment by Xaz16** [comment]
@Alys got it. I pushed fix for groups as well in current PR.
