### ISSUE TITLE
Guild suggestion incorrectly identifies account as new

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11159]
> Hello! I was asked to send this here. On mine (and other users') guild page, the description for the "ask a question" guild has a text saying "recommended because you're a new user." Or something like that. However, the user that originally complained had been registered for about a year, and I am 2 and a half years in myself. Should that text still be showing? Here's a screenshot for proof.
> 
> ![scr](https://snag.gy/yro2hj.jpg)

_edit by Alys 2019-05-21: See the comment below for the desired fix._

**Comment by Alys** [comment]
This is the code responsible for the buggy behaviour:

https://github.com/HabitRPG/habitica/blob/3c0cd7067a3608f4f071ea139f3103d3dd9e0be2/website/client/components/groups/publicGuildItem.vue#L28

https://github.com/HabitRPG/habitica/blob/3c0cd7067a3608f4f071ea139f3103d3dd9e0be2/website/client/components/groups/publicGuildItem.vue#L176-L180

I.e., it deliberately shows the "Suggested because you’re new to Habitica" text for anyone who created their account after 2017-08-01.

A more helpful behaviour would be to show that text for anyone who created their account in the past 60(?) days. ~I'll leave this marked as suggestion-discussion for a week or so and then if there's no objections, I'll mark it as help wanted for that.~

The fix for this issue should also convert that text to a translatable string and the `createdAfterRedesign` variable should be given a more appropriate name.

**Comment by garayj** [comment]
Hi Alys! If no one is working on this, I can get started on this. :]

**Comment by Alys** [comment]
@garayj Thank you! Please go ahead. Comment here if you have questions.
