### ISSUE TITLE
Heroku Server.

### ISSUE THREAD

**Issue by rafucuk** [HabitRPG/habitica#11177]
Hi, Again me! I fixed my last error. I want to share this with my friends. And I found heroku. But I don't know how can i share this. I have a question. If i give you a github account and heroku account, Can you open for me? 
If answer == no:
    print("Then How can i do?")
elif answer == yes:
    print("A lot of thanks!")

**Comment by paglias** [comment]
Hi @RaufSSen, I'm happy you managed to solve your issues but what do you mean with `I found heroku`?

Anyway we have a few heroku deployments for our own internal usage but don't support it for others, that being said you're free to deploy your own version of Habitica locally, on Heroku or any other server.

I'm going to close the issue since GH is not the most appropriate place to give support, but we have a guild on Habitica for that [Aspiring Blacksmiths (Coding For Habitica)](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f)

**Comment by rafucuk** [comment]
I'm saying Heroku, a nodejs etc. free hosting website.
