### ISSUE TITLE
right-hand side of private messages / PMs can be hidden under edge of inbox

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11213]
As reported by @-Horizon- (5a8238ab-1819-4f7f-a750-f23264719a2d):

"The private messages box needs a little padding (the end of the text is hidden behind the scrollbar)"

This occurs in both received messages and sent ones (the right-hand side can be slightly hidden by your avatar).

FYI @Tressley in case you'd like to comment. I've marked it as needs design for now.

![image](https://user-images.githubusercontent.com/1495809/59158271-ed58fd00-8afa-11e9-9835-f36462e31915.png)

![image](https://user-images.githubusercontent.com/1495809/59158275-006bcd00-8afb-11e9-9013-90ad0aac0e85.png)

**Comment by Tressley** [comment]
@Alys -- Thanks for the heads up! I don't think this is a design issue as much as a CSS overflow issue (and probably related to screen-size as well, judging by the avatar overlapping the message.) Would you happen to know what OS and browser @-Horizon- is using?

I do think we can have some discussion around how to handle the messages modal at smaller screen sizes. Perhaps hiding the avatars to accommodate the messages would improve the experience a bit more.

**Comment by citrusella** [comment]
I'm not that person by I have this happen on my 1280 by 800 Macbook Pro running Windows 7 and Firefox 60.7.0 ESR (up-to-date for that channel).

I also have it happen at all zoom levels on the default (Samsung) browser on the Smart TV my dad owns, which is, as far as I can tell, either 1920 by 1080 (the only online documentation I could find for any modern app size on Samsung TVs) or 3840 by 2160 (because it's a 4K TV).

I think the avatar just happens to overlap the message in the PM screen... though also the screen for the PMs themselves doesn't seem to grow with resolution--it engulfs my 1280x800 screen but was tiny on the TV's screen. Considering there's apparently [plans for PMs to be a page instead of a modal](https://github.com/HabitRPG/habitica/pull/11113) would that do anything to fix modal issues? I like seeing avatars in PMs at my screen size is why I'm saying that, but also because that WIP PR exists and I didn't know if it would affect any choices about what to do with the modal.

**Comment by Alys** [comment]
@Tressley I don't know about Horizon's browser but mine is Firefox on Ubuntu, on an average-sized laptop with the browser at full screen.

> Perhaps hiding the avatars to accommodate the messages would improve the experience a bit more.

Speaking for myself, I'd much prefer to have the edge of the message cut off (it's still readable, just a bit annoying) than to not see the avatars. :) Hopefully though it would be possible to have both on a screen that isn't tiny.

citrusella makes a good point about PMs moving to a page. Perhaps this should wait until https://github.com/HabitRPG/habitica/pull/11113 is merged. The problem might then fix itself.

**Comment by paglias** [comment]
Given the redesign of the PMs page, can this be closed?

**Comment by citrusella** [comment]
FWIW, it doesn't look like it's happening anymore.
