### ISSUE TITLE
unnecessary Equipment sub-heading in Market

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11232]
As reported by @ieahleen (c073342f-4a65-4a13-9ffd-9e7fa5410d6b):

"In the Market there is an Equipment sub-header in the Items section, below Food and Saddles and above Cards, I don't think it should be there:"

![scr](https://snag.gy/bQ2TuM.jpg)

**Comment by Scens** [comment]
I would like to take this issue as my first on the website. I already solved it. What are the next steps? I don't have much experience working with Github.

**Comment by Alys** [comment]
@Scens Thanks! I've marked this as in progress for you.

Have a look through [Using Your Local Install to Modify Habitica's Website and API](http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API). That will tell you the PR process and also give you a lot of other useful information. If you have questions after reading that, the Aspiring Blacksmith's guild is a great place to ask, although here is okay too.
Any questions about this specific issue can go here to keep all the information about it together.

**Comment by Scens** [comment]
Now the issue is solved and additionally filter options look like this (the proper order):
<img width="215" alt="Screenshot 2019-06-20 at 09 28 02" src="https://user-images.githubusercontent.com/15756047/59829719-64359780-933e-11e9-9db6-f5942756e5cd.png">

instead of this:
<img width="211" alt="Screenshot 2019-06-20 at 09 33 22" src="https://user-images.githubusercontent.com/15756047/59829753-77e0fe00-933e-11e9-8d39-e1bb8ceb4137.png">

Equipment section displays properly:
<img width="1099" alt="Screenshot 2019-06-20 at 09 34 22" src="https://user-images.githubusercontent.com/15756047/59829898-c098b700-933e-11e9-86db-5f29a1fb3bd1.png">

But as you can see, there is unnecessary "Items" heading which also had displayed before my changes in this particular case. That's for another issue I guess.
