### ISSUE TITLE
Second day in a row that health loss has turned into negative health/gold

### ISSUE THREAD

**Issue by savannahcookson** [HabitRPG/habitica#1123]
For the past 2 days my account has converted my ~5hp health loss into about -200 xp and -20 gold. What is going on? This is really frustrating and is killing my motivation.

**Comment by savannahcookson** [comment]
Just as a note, I am using the normal version on Chrome Version 27.0.1453.93, also logged into the beta but mostly use that when the server is freaking out. Just restored the account to more or less what I think the values were last night.

**Comment by pixellatez** [comment]
I also have been seeing this the last few days.

**Comment by lefnire** [comment]
This is an issue when you have two browsers open with habit. If you leave
habit open on the work computer, and you log in at home - it causes data
conflicts. This is the primary bit that will be solved with the racer 0.5
upgrade

**Comment by apLundell** [comment]
I hope this is fixed soon.  It's pretty much destroying the usefulness of this otherwise awesome project.

That seems like an exaggeration to say, since there's a workaround, but if the goal is to encourage me to have good habits, it doesn't do that at all if accidentally leaving a browser tab open is a worse sin than not doing any chores all day.

I don't understand why unchecking a daily is even allowed. What's that functionality for?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
