### ISSUE TITLE
Webhooks: API endpoint to get users webhooks

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica#11290]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Currently there is no API endpoint to get users existing webhooks. You can only create new, update existing or delete existing webhooks. But if you didn't save the UUID of the webhook when you created it, there's no way to get it anywhere. At least I haven't found a way. Or actually when you successfully delete an existing webhook, then you will get remaining webhooks in the response, but if you don't want to delete any or you don't know the id of any existing ones, then how do you know what hooks you have?

So just thinking it should be pretty easy to add a `GET /user/webhook` endpoint that just lists all existing webhooks (same response as the delete endpoint basically)? Or is there some reason this has not been implemented? If this sounds reasonable, I can also work on it.

**Comment by paglias** [comment]
@cvuorinen you're right that the endpoint is missing! That's likely because the webhooks are stored directly inside the user's document so you can `GET /user` and then the webhooks will be stored under `user.webhooks`. 

This comes from the earlier days of HabitRPG when we stored everything inside the user document. Since then we moved most sub docs out of it but not webhooks.

But yeah this looks like something that would be useful and will make it easier to remove webhooks from the user doc in the future so if you want to work on this it would be great!

**Comment by cvuorinen** [comment]
Yea, I also found them under the user object since I noticed that they are listed in the Settings > API page and figured it must get them somewhere. But I can take a look at adding the endpoint for getting them.
