### ISSUE TITLE
Bad description in repo's README

### ISSUE THREAD

**Issue by jaydinsweo** [HabitRPG/habitica#11328]
Is there a reason why Habitica doesn't have a proper README?
It lacking information and needed some description about the project. That way, people can easy nav around the project and contribute.

I'm planning to do a template README, but not sure if there are anything else I need to include in it

**Comment by Alys** [comment]
The reason is that we use our wiki as the primary source of our documentation and we don't want to have it duplicated in another place - there'd be far too much chance that the two sets of information would get out of sync.

If you see anything that could be added to the wiki documentation after you've read the pages that the README links to and all the pages that they link to, you'd be most welcome to edit those pages once you're sure the new information is correct.

If you still think the README needs more detail, you might like to describe here what you want to add before you make a PR in case we decide that the wiki is also the best place for it.

By the way, I'm about to change the title of this issue to clarify that it's referring to the README, not to a bug with a description in Habitica.

**Comment by noobling** [comment]
The README of a github project is the number one place a dev would look at initially. A suggestion could be to put minimal unlikely to change information that is relevant to developers.

Some ideas include
* Getting started
* FAQ
* Social/Community links
* License 
* Creating issues

I could make a PR for this but I lack the context for this project.

**Comment by Alys** [comment]
Thanks, that's good feedback! I'll update the readme later today to either
provide that information or indicate where it's found.
