### ISSUE TITLE
Gem gift modal: purchase buttons sometimes appear when "From Balance" is selected

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11386]
Sometimes when you go to give Gems to another player using your Gem balance, the purchase buttons appear when they should not. AnneLine and I have observed this. In the screenshot below (taken by AnneLine), you can see that the "From Balance" option is selected but the buttons for credit card, etc appear.

Steps to reproduce:
1. Ensure you have at least 1 Gem.
2. Click on a player's profile then click on the gift icon.
3. Enter at least 1 for the number of Gems to give.
4. .Do NOT click on either "From Balance" or "Purchase" - just let the default setting of "From Balance" be used.
5. Observe that even though "From Balance" is selected (since it's the default option), the payment buttons appear.

However this is an intermittent bug.  I noticed it a few days ago but can't replicate it now  (Firefox on Ubuntu).

AnneLine says:
 "... It's happening about 75% of the time... for the last 2 or 3 weeks (I think?) certainly for the last week, when I go to [send a gem gift], instead of it letting me just use the gem I have in the account, it keeps asking me if I want to buy them from various sources... But once that 'request' drops down, I can't get it to go away. There's no way to override it and it covers the normal 'send' button, so I have to keep starting over. I use Windows 7 and Chrome..."

When I observed the problem, I think I was able to use my Gem balance by clicking on the "From Balance" option, but I can't remember for sure.

![Selection_001](https://user-images.githubusercontent.com/1495809/65831257-10522b80-e2fb-11e9-9cf6-be18558730e6.png)

**Comment by evelynstender** [comment]
Hey @Alys can I help with this one?

**Comment by Alys** [comment]
@evelynstender Yes, please do! Thank you! Post here if you have questions.

**Comment by evelynstender** [comment]
hey @Alys is this still happening? I couldn't replicate. I tried with at least 4 different browsers on Mac and Ubuntu.
Do you have any clue or something?

**Comment by Alys** [comment]
I would guess that it's still happening because I think there haven't been any large changes to the modal but it was always an intermittent bug so it's hard to confirm if it's still there or not. :-/ I don't have a clue I'm afraid. If you'd prefer to take on a different issue than this one, post again here and I'll put this back to help wanted - totally okay if you do that since it's impossible to reliably reproduce it. :)

**Comment by evelynstender** [comment]
So, I think I'll pickup another issue then, but I'll keep an eye on this one to see if I can replicate somehow. Let me know if you find something new about it. I'll post here as well if I figure something out! (this is intriguing, so I don't wanna 100% give up on this as I'm curious to understand what happened, but like you said it's quite hard to reproduce it).
Thanks!

**Comment by Alys** [comment]
@evelynstender No worries, thanks!

**Comment by lulock** [comment]
Hey @Alys and @evelynstender 

It's strange, I'm able to replicate the bug on Firefox 78.0.2 (64-bit) by clicking the modal outside of the "gem" box. So I'm assuming it pops up only when you go to select the "subscription" area even without having selected one of those radio buttons. (see screenshots below - the gems box is greyed out when the payment methods pop up, while subscriptions is black) 

It seems to be registering a click on the "subscriptions" area as a focus pre-selection of a subscription amount. **I am thinking this is just a design flaw?** Or the identification of "subscriptions" is just pre-mature. Should only pop up once a radio button is selected, and should be able to deselect the radio button.

<img width="867" alt="no-payment" src="https://user-images.githubusercontent.com/8599836/87873592-f1c93800-c9d3-11ea-876d-f4fefde49852.png">
<img width="832" alt="payment" src="https://user-images.githubusercontent.com/8599836/87873594-f2fa6500-c9d3-11ea-8979-471347f94f74.png">

**_EDIT_**

After digging into the code I can confirm that this is the mechanism . 

![gems](https://user-images.githubusercontent.com/8599836/87883475-ad13c000-ca18-11ea-8cbc-5a24252182d6.PNG)

![subscription](https://user-images.githubusercontent.com/8599836/87883482-b6049180-ca18-11ea-9e60-7cd3d6e383e4.PNG)

![frombalance](https://user-images.githubusercontent.com/8599836/87883483-b7ce5500-ca18-11ea-89b3-bf8e09774e43.PNG)


Would you guys want to change the interface design? As in, make it more obvious which gift is in focus: Subscription / Gem (I would recommend this, considering accessibility as well. It isn't so obvious that one is bolder than the other. Colour change or selection shading may help distinguish)

Or would you want to change the mechanism so that the purchase buttons do not pop up UNLESS a radio button is selected, with the added functionality to deselect a radio button after having selected it (making purchase buttons disappear as well)

lol ok I hope what I'm trying to explain makes sense...:grimacing:

**Comment by lulock** [comment]
Hey @Alys, any thoughts or opinions on the above ? 

I know it starts to go into a design discussion - and I would even be interested in exploring whether splitting "gems" and "subs" under two tabs might make more sense when splitting the actions considered they're handled independently in this scenario anyway. You can't gift gems and a subscription in one go, can you? As this layout kind of suggests ... any UI designers wanna jump in with their experienced opionion too ? hehe 😬 

But let me know thoughts anyway and I can get started on some suggested fixes / revisions

**Comment by Alys** [comment]
@lulock I'm sorry, interface changes are not really something I should comment on. Habitica's staff will answer your questions. :)

**Comment by SabreCat** [comment]
Paging @Tressley!

I'll also label this as needing design input.

**Comment by Tressley** [comment]
The Gifting modal actually has updated designs that can be found in our Zeplin: https://zpl.io/bLxmdL7, https://zpl.io/VqlPvm7

![image](https://user-images.githubusercontent.com/2686586/88196535-4efcfd80-cc0f-11ea-8d74-f5585e82f338.png)

@lulock -- Are you interested in taking on the updated designs? If so, can you provide an email address for a Zeplin invitation.

**Comment by lulock** [comment]
@Tressley oooh looks sweet! Sure send the Zeplin invite to lulock00@gmail.com

@SabreCat @Alys thanks guys 😺

**Comment by lulock** [comment]
Hey @Tressley ! Is this design implementation still open for grabs? I wouldn't mind having a look at the designs on Zeplin and taking a shot at it.

**Comment by Tressley** [comment]
@lulock -- Yes! I have not forgotten about you. I just need to make some small adjustments to the designs before exporting them to Zeplin (we've since made updates to some of the components.) I'll have them in Zeplin and an invite over to you today.

**Comment by Tressley** [comment]
@lulock -- Invite sent! Please let me know if you don't see it. Here's a link to the Zeplin artboard: https://zpl.io/V10ZNxZ

**Comment by lulock** [comment]
> @lulock -- Invite sent! Please let me know if you don't see it. Here's a link to the Zeplin artboard: https://zpl.io/V10ZNxZ

woohoo I'm ON it! Thanks @Tressley 

<img src="https://lumiere-a.akamaihd.net/v1/images/mi_stickerbook_kim_possible_kim5_986b3e4c.png?region=0%2C0%2C1850%2C1484" width="100" />

**Comment by paglias** [comment]
I'll fix this

**Comment by paglias** [comment]
@lulock I'm fixing only the issue described here originally, if you want to work on the redesign that's still available, just comment here
