### ISSUE TITLE
@username inside markdown code backticks should not be converted to link

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11504]
In group chat messages,  if you type an @Username inside backticks for markdown "code" highlighting, you expect to see exactly what you type with the markdown code formatting (red text on a white background), however the @Username is converted into a link and you see the markdown link code.

For example, if you type exactly this: `` `@username` ``

then you expect to see this: `@username` (in red text on a white background)

but instead you see this: `[@username](/profile/d904bd62-da08-416b-a816-ba797c9ee265)` (and the @Username part is blue instead of red).

See the screenshot below for an example.

I believe this counts as a bug because the markdown code highlighting is intended for displaying exactly the text you type.

<strike>I'll leave this issue as suggestion-discussion for a few days and then if there's no objections I'll mark it as help wanted, with the fix being to not have the @Username converted to a link and to have the @Username appear as red text, not blue text.</strike>
EDIT: 
The desired fix is that when @Username appears inside backticks, it should not be converted to a link and should appear as red text, not blue text.
This should be done for private messages as well as for group posts (see the comment below from Nikosmonaut about PMs).

![image](https://user-images.githubusercontent.com/1495809/68082959-d5e62c00-fe6e-11e9-9e5a-95382ab90934.png)

**Comment by nikonhub** [comment]
Hello.

It seems the same behavior happens to private messages.
Without and with backticks :
![image](https://user-images.githubusercontent.com/45662151/68085093-44aa9180-fe3d-11e9-9de1-24fde6c158c4.png)

Because the regex in highlightMentions function only match `@username` wherever it is. Should it also check if we are inside a backticks block ?

**Comment by Alys** [comment]
I've marked this as help wanted and mentioned in the top post that it applies to PMs too - thanks @Nikosmonaut !

EDIT: There's a loosely related issue at https://github.com/HabitRPG/habitica/issues/11520

**Comment by evelynstender** [comment]
Hey @Alys can I work on this one?

**Comment by Alys** [comment]
@evelynstender Yes, thank you! Comment here if you have questions!

Note that I've just edited my previous comment here to remove an issue that wasn't directly related (I had misread it). The top post hasn't been changed and still accurately describes this issue.

**Comment by shanaqui** [comment]
@evelynstender Hi! Are you still interested in working on this issue? If so, please let us know!

**Comment by evelynstender** [comment]
@shanaqui Hi! I'm still interested. I've been dealing with some metal health issues but I'm better now and will start working on it next weekend. But feel free to grab it and work on it! I can find other issues to work on haha

**Comment by shanaqui** [comment]
I won't mark it as help wanted again yet, then! :) Thanks for taking this on!

**Comment by evelynstender** [comment]
Hi @shanaqui @Alys I've been having some personal issues and I can't work on this issue right now. I hope I can get back to contributing soon!

**Comment by Alys** [comment]
No worries and thanks for telling us! I hope things improve for you soon!

**Comment by benkelaar** [comment]
Hi @Alys Can I pick this up to get my feet wet with contributing?

**Comment by Alys** [comment]
@benkelaar Sure! Thank you! Post here if you have questions or run into trouble.

**Comment by benkelaar** [comment]
Cool, relatively smooth sailing so far. Got the local environment running both with Docker and natively on macOs. Found the highlightMentions function and its tests, but having some trouble running the tests (describe.only doesn't seem to work for me and some timers are timing out, I'll figure it out tonight).

Am a JVM guy normally, so node is not really my home game, but this might be a fun opportunity to give Eclipse Theia a whirl!

Also when it comes to solution, I don't think the proper way is to overload the regex with complexity. Theoretically it could probably be done with a bunch of complex negative lookaheads and lookbehinds (Not even sure if JS regex support those), but that quickly becomes a disaster to maintain. So what I want to look in to is find the code that's also being used to isolate the code blocks to turn them into separate `<code />` elements so I can use that to take out the code blocks, then run the regex replace on the rest of the message and rebuild the message. I think that'll lead to a better function in the end. I suspect however that that code is in some markdown processing dependency somewhere, but perhaps it's exposed enough that I can still use it.

Anyway, tonight I'll look into some tests first!

**Comment by benkelaar** [comment]
Alright, got the tests running, also did some more research and found that all this also goes if a line starts with 4 spaces.

I also found the https://github.com/HabitRPG/habitica-markdown module, which uses tokenisation to parse the markdown, so that's not really usable for our problem.

However, I did notice that we need the same logic to run on the highlighting of user mentions in code blocks in highlightUsers.js, so I'll probably introduce a common function somewhere.

So am I right in assuming that both the highlightMentions function on the server side and the highlightUsers function on the client side need to not transform text in code blocks? 
(With code blocks defined as any text between unescaped single backticks on a single line, between lines that start with (some optional spaces and) unescaped triple backticks, or on a line that starts with 4 (or more) spaces)

**Comment by benkelaar** [comment]
Hmmm yeah, so I dove into https://spec.commonmark.org/0.29/. The definition of what entails a code block is (of course) even more complex than all that. 

Don't think it's a good idea to write our own code for this. Did a quick google, this might be a good package to use: https://www.npmjs.com/package/gfm-code-blocks

**Comment by Alys** [comment]
> So am I right in assuming that both the highlightMentions function on the server side and the highlightUsers function on the client side need to not transform text in code blocks?

Yes. :)

**Comment by benkelaar** [comment]
Nevermind, the package is insufficient (Uses a trivial regex that doesn't cover all the usescases), will take a shot at implementing a better solution tonight.

On the whole, since we're using a custom markdown parser anyway, wouldn't it be better to integrate this somehow into the parser? You'd need to supply it with the users of course, but perhaps that can be done with some form of callBack.

**Comment by benkelaar** [comment]
Alright, kinda went down the rabbit-hole on markdown parsing today. 

**Conclusion**
Since inline-code blocks can invalidate fenced code blocks and any other document block (Paragraphs, list items, etc) can invalidate inline-code blocks, it's impossible to determine the distribution of code blocks in a markdown string without knowing the entire distribution of blocks in the document. i.e. to find the code blocks, you need to parse all the markdown formatting.

**Alternative solution**
Now as a temporary solution I was thinking we could invert the order. So first do the markdown formatting and only then replace the user mentions with links or spans. Skipping the code blocks then becomes a matter of finding code tags, which is much easier. Of course we'd also have to inject fully fledged HTML, but we can just call markdown.render on the replacement text to get that.

Edit: The other approach that would work is only do best-effort selection of code blocks. For example ignore the line-collapsing behaviour of in-line code spans (so only look at single-line in-line code spans), since that would probably fix this issue for 90% of the cases.

**Follow up**
I feel more and more strongly that user highlighting should be integrated in habitica-markdown instead. There now are two separate abstraction levels with only blackbox knowledge of each other making decisions about the exact same subject matter. A recipe for disaster, which explains why besides this issue, there's also https://github.com/HabitRPG/habitica/issues/12033 , 
 https://github.com/HabitRPG/habitica/issues/11520 and probably several others that haven't been found yet.

I'll see if I can throw up a pull request that uses the temporary solution I proposed, but I think it would be worthwhile to open up a follow-up issue to see if there can be only a single location that has the responsibility of making decisions about rendering markdown formatting.

**Comment by kareenf** [comment]
So, I've been working on #12033 (thanks for the comment btw!) and I'm not sure if inverting the order would necessarily help. When I was poking around and trying to get an understanding of how the code was working, I noticed that after the markdown parser ran and sent the code off to highlightUsers, all of the tags were gone. So instead of having `@_spider_` as what the code was searching for (when trying to match and highlight the username), it was searching for `@spider`.  I'm also not sure if the logic would make sense anymore by flipping the two, it's seems to me that the parser will get it's hands on the username and turn it into emphasized text regardless.

**Comment by benkelaar** [comment]
Indeed, flipping the order would not fix https://github.com/HabitRPG/habitica/issues/12033

However, if you check for presence of `@_([\w-]+)_` before, you should then just be able to do something like `s/@<em>$1<\/em>/@_$1_` after to fix the erroneous formatting right?

**Comment by benkelaar** [comment]
@kareenf BTW I noticed when testing your issue locally that the autocomplete for users also seemed to ignore the user that started with an underscore. Not sure if it's the same issue, but could be related.

**Comment by kareenf** [comment]
@benkelaar That may be the case. I noticed that it doesn't pop up if I haven't used it before (i.e. no chats), however it does pop up after I've used it once. This is the case even if I delete all chats and start again. I'm guessing it might have something to do with a different part of the code but I'm not sure.

I was wondering if you could help shed light on something that has been tripping me up when I'm trying to read the code in highlightUsers.js. Where does mentionStr come from? And what is the difference between mentionStr and fullMatched?

I was thinking of editing the code to add in a similar text = text.replace() statement before the one that already exists that looks for em tag after a @ appears and then replace them with underscores.

**Comment by benkelaar** [comment]
OK, so continuing. Inverting works for this scenario for highlightUsers, but highlightMentions (which is a strange name, since it's about injecting links, not so much about highlighting anything) is actually done on saving, not on display, so this is something that you don't want to intermingle with HTML rendering.

So I looked into using the parser directly, which is actually possible. So now that I understand the API of markdown-it better, I think it should be done like this:

`highlightMentions` uses the parser ~and then inspects code block tokens to figure out which parts of the text to skip.~ Edit: Silly, if we create the parser plugin, we can of course just look at the new "mention" type tokens. However I'm now so far with this implementation I'll create a PR for it anyway, we can always simplify it again later.
`highlightUsers` should be done in a duo of markdown-it plugins, one to create a new type of user token and one to render it as the required span. I think this should be a merge request on habitica-markdown, and that should also fix  #12033 and #11520 (and prevent future bugs since we're doing the html rendering in a single place compatible with the way markdown-it was designed).

**Comment by benkelaar** [comment]
Created an issue on habitica-markdown for the user highlights, will look in to that tonight.
