### ISSUE TITLE
Group Plan tags are not deletable after leaving group

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11522]
When you're in a guild/party that has a Group Plan, a tag for the group is added to your personal tags (this is correct behaviour).

When you are no longer in that group, the tag remains and you are not able to edit or delete it. I'm not sure if this happens when you leave the group or when the leader removes you or both.

The correct behaviour is that the tag should become one of your personal tags. I.e., the `group` attribute should be removed from the tag (see the sample tag below which shows that attribute).

The tag should not be deleted automatically because the player might have used it to tag their own tasks, which is permissible.

This was reported by @Ceran (aabe567b-aa55-42c1-b612-b7699a7ba9b7):
_"I still have the tag from the group I used to be in. I don't see a way for me to remove this tag. Could this tag be removed, please? "The Groupish Group". Only group tag I have."_
I've confirmed they are no longer in the associated group and have deleted the tag for them. This is what the tag used to be:

```
    "tags": [
        {
            "id": "d2397cb7-e92d-42dc-aba8-6686cab105e3",
            "name": "The Groupish Group",
            "group": "d2397cb7-e92d-42dc-aba8-6686cab105e3"
        },
 ```

For any coder wanting to work on this, [Using Your Local Install to Modify Habitica%27s Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) shows you how to add a Group Plan to a guild or party (in the "Creating Test Data" section). So, in your local install, you can create a guild or party as normal with one test user account as leader, run that database command to convert it to a group plan, invite a second test user to it, then use that second user for testing how tags behave on leaving / being removed. At least in theory. :) Post here if that doesn't work (say what goes wrong) and if you need help working out how to replicate this bug.

**Comment by nikonhub** [comment]
Hello.

May I work on this one ?

**Comment by Alys** [comment]
@Nikosmonaut Sure, thank you!

**Comment by nikonhub** [comment]
@Alys 

I'm trying to figure out what should be the behavior if this same user is reinvited to the group ?
Imagine I remove group field from tags when the user quit/is removed from a group, I think it will create another side effect later.

The thing is the tag.id = tag.group

If the user quit the group they have "The Groupish Group" as a simple tag. They can change it's name, and even forget it once was a group tag. But if later the user is reinvited to this group I can not create a new tag because the id is already taken.

So should I reuse this tag and change it's name et re add the group field ?

Edit : Why not to use the same behavior as challenge tags ? But the only difference would be : the tag can not be deleted if the user is currentrly in the group.

**Comment by Alys** [comment]
@Nikosmonaut Good question, thanks for asking! I think using the same behaviour as challenge tags would be best if that's possible (specifically, when you rejoin a challenge, the existing tag is reused and its name is changed back to what the challenge says it should be). You're right that the group tag should not be deletable while you're in the group.

**Comment by nikonhub** [comment]
I created a draft pull request.

I'm not sure how should the tag name change if the user rejoin a party a second time. Because a tag is not added when the user accept the invitation but when a first task is assigned to him. But in this call I'm not aware if this is a first assignement since the user joigned the party or a second to choose if I should update the tag name.

**Comment by Alys** [comment]
@Nikosmonaut In my opinion, tag behaviour for a Party with a Group Plan should be the same as for a Guild in all respects. However I might be missing something so please tell us if I am!

In case it's not obvious (and I'm sorry if this has caused confusion!) the word "group" when written alone generally includes Guilds and Parties and the Tavern - it's a generic term for all of them. (When it's written in the phrase "Group Plan", it refers specifically to Group Plan features.)

**Comment by nikonhub** [comment]
@Alys 

Sorry for the wrong naming.
So I'm not totally sure about what should be done because fixing this bug almost adds a little feature and changes business rules.

What I understand so far is that you have 3 types of tags 

- Normal tags
- Challenge tags : added to the user list of tags when they join a new challenge. The user can change the name and delete this tag like it's a normal tag. If this user changes the challenge name, quits the challenge and then rejoins it, the name is updated back to original. But we have this comment in challenge code. So maybe it will change in future.
![image](https://user-images.githubusercontent.com/45662151/68991470-8ab11d80-085f-11ea-9eda-fa06717f4b65.png)

- Group tags (party with a group plan): Added when a task is assigned to a user. It's only possible in a party with a group plan subscription. This one the user can not change it nor delete it.

That's why I call it group tags, because it's in a groups category. But I found no other case to have a group tag except when you are in a party with a group plan subscription and someone assigns you a task.
![image](https://user-images.githubusercontent.com/45662151/68991651-2ee79400-0861-11ea-81ef-77ea08b39ee1.png)


What I changed :

- Allow modifications on group tags. But remove the delete icon if the group tag belongs to the current user party.
- Obviously disallow the deletion of user party tag on server side

It works like expected, the only the difference is, I can not find a way to change the name of a party tag back to original if a user rejoin a party again. But looking at this challenge comment (image above) maybe it should not be implemented.

**Comment by Alys** [comment]
@Nikosmonaut Yes, there's three types of tags (normal, Challenge, and Group Plan tags).

> Group tags (party with a group plan): Added when a task is assigned to a user. It's only possible in a party with a group plan... This one the user can not change it nor delete it.

That's correct except that it also applies to a Guild that has a Group Plan. Both Guilds and Parties can have Group Plans. The Group Plan features should be identical for both types of groups.

> Allow modifications on group tags. But remove the delete icon if the group tag belongs to the current user party.

That's okay but there should also not be a delete icon if the Group Plan tag belongs to a Guild that the player is still a member of.


> I can not find a way to change the name of a party tag back to original if a user rejoin a party again. But looking at this challenge comment (image above) maybe it should not be implemented.

I agree that it's not important to change the tag name back to the original. The specific situation where it might be helpful would happen so rarely that it's not worth worrying about. Any affected players can report the problem for a manual fix if they wish to.

You're welcome to ask more questions if I haven't been clear about any of this!

_(One small point (mostly for our reference rather than for you), Group Plan tags should also be deletable if the player is still in the group but the Group Plan has been terminated. We can log another issue for that later if needed. The situation where a player is no longer in the group that had a Group Plan is more likely I believe.)_
