### ISSUE TITLE
Profile pages have no information when opened as non-modal pages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11525]
If you open a player's profile screen in a window by itself, then you see the header and tabs but with no information shown:
![screenshot](https://i.snipboard.io/8I06lE.jpg)

The correct behaviour is that the information from the "Profile" tab should appear.

You can reproduce this bug in any of these ways:
- Right-click on a player's name / avatar image and select the option to open in a new tab or window.
- Normal click on a player's name / avatar image and then reload the page.
- Click on a profile link that you find elsewhere such as in the wiki. Here's an example: https://habitica.com/profile/d904bd62-da08-416b-a816-ba797c9ee265

The same problem does not occur when you open a profile in a modal.

**Comment by vamsijv** [comment]
@Alys I would like to work on this item, if that's fine. 

I see that all 3 scenarios from ticket description eventually end up accessing the profile page url which I believe has the root cause. As such, I guess following components need to be looked at for fixing the issue:

- profile.vue

- profilePage.vue


Please let me know if I can proceed further on this. Thank you!

**Comment by Alys** [comment]
@vamsijv  Please go ahead, thanks!

Yes, those three scenarios are just different ways of accessing the profile page as a stand-alone web page.
