### ISSUE TITLE
saving a Reward with no value / cost should not be possible 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11560]
As reported by Togohogo1 / @yiybtheumes (9bb5ff83-dac5-450e-89a9-213ef54c97d6) and confirmed by @citrusella:

"if you set your custom rewards amount to no value and click on it, the site freezes, and reloading it does not unfreeze it. After opening it again in a new tab, your gold value for the reward is set to the value that you last assigned it."

The desired behaviour is that you should not be able to save a Reward if it does not have a value ("cost"). Note that a value of zero IS allowed! The situation that needs to be avoided is having no value in the cost field.

**Comment by nikonhub** [comment]
Hello @Alys 

May I work on this one ?

Actually the reward is not saved to the database. It just appears on the client site. But if we refresh the page it's not there. We even have an error from the server that value is required.

It's a general case. For all tasks (habit, daily, task or reward) the user can submit and the modal closes sending the request with no checks for required fields on client side. Then it appears as is in the column list.

- So there is a quick fix : fix the value to a number 0 if it's empty. Because the calculation enters an infinit loop otherwise and blocks the browser.

- Or add client side validators for required field and disable the submit button for all type of tasks. In both cases it may be wise to force the reward value to a number to prevent the infinit loop.

**Comment by Alys** [comment]
@Nikosmonaut Thank you for that assessment! I've marked it as in progress for you.

I think we should do the quick fix: "fix the value to a number 0 if it's empty" however you might want to wait a day or so to see if the staff say otherwise. I like that option because it's nice and simple, and if the player has cleared the value field, it's probably because they want a zero-cost reward anyway.
