### ISSUE TITLE
weekday habits

### ISSUE THREAD

**Issue by ghosttie** [HabitRPG/habitica#116]
Some of my habits only apply to when I'm at work, so they're things I want to do Monday-Friday but shouldn't be penalised for not doing on the weekend.

Ideally holidays would be taken into account as well.

**Comment by racuna** [comment]
1. Read the FAQ https://github.com/lefnire/habitrpg/wiki/FAQ (the vacations question)
2. Holidays are not the same in every country

**Comment by the-economancer** [comment]
I don't think the actual habits automatically penalize you, they are handled manually, so you would just ignore those on the weekends (and holidays). If they are in your daily list, you can select which days they occur on; clicking edit (the pencil icon that shows up on mouse-over), and clicking the days you don't want it to apply to (since by default every day is selected). And for holidays you can always go in and manually de-select those days.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Basic Holiday (Day Off) support, see [Rest in Tavern](https://trello.com/c/A2w2orSc)

**Comment by Furgas** [comment]
I've joined in recently, and I've just got penalized for not doing everyday task on weekend. I don't see a simple way to make every day task ignore weekends (I've duplicated a task 5 times and repeat it every 7 days).
