### ISSUE TITLE
Dropdown menu can get "stuck" until you mouse over it again

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11615]
_Edit by Alys 2020-01-04:_

See [this comment](https://github.com/HabitRPG/habitica/issues/11615#issuecomment-570763238) for a way to reproduce this issue.

In brief, reloading a page causes the mouse on-hover effect for the menu of THAT page to be reversed (hovering over it hides the menu, moving the mouse away reveals the menu).

_end of edit_

----

> @JohnJSal (624e48a3-cbea-4bbe-ae44-ca9183f49626): "I don't know if this is a bug, exactly, but I've noticed for a while that when I hover the mouse over the "Guilds" tab at the top of the website, the dropdown menu often remains stuck on the screen even when I've moved the cursor away or even navigate to a different part of the site. It doesn't go away until I move the cursor back over the Guilds tab and sort of "unstick" it. It doesn't happen every single time, but often."

I've seen this as well in Google Chrome. I can't seem to trigger it on demand, though, so it might be difficult to reproduce.

**Comment by paglias** [comment]
I'm not able to replicate the problem, which browser are they using?

**Comment by shanaqui** [comment]
I asked folks in RaB to drop any further information here. :) I've had it happen recently, on Google Chrome.

**Comment by JohnJSal** [comment]
I'm using Chrome. I'll post again if I notice any patterns in when it happens.

I don't know if this is related, but last night I noticed a similar problem with the Inventory drop down, but rather than retain the entire purple box with white text inside (which is what I see with the Guild tab issue), it didn't show the purple box, just the menu item text superimposed over the images underneath.

**Comment by Alys** [comment]
@geolojess reported something similar and I've reproduced it with the steps below.

1. Go to the Tasks page and reload the site. This is just to ensure that any other glitches are probably cleared.
2. Click on the top-level item for any drop-down menu that has more than one entry, for example, click on Inventory. (Don't use Tasks since it has no drop-down; don't use Help since it has a different behaviour to all the other menus.)
3. While you're on the Inventory page, move your mouse back and forth over the top-level Inventory item. Observe that when your mouse is over it, the drop-down appears; when your mouse moves away, the drop-down disappears. This is the correct behaviour.
4. Move your mouse away from the menu.
5. Reload the Inventory page using your browser's refresh button.
6. Move your mouse over the Inventory top-level menu, being careful to not touch any of the surrounding menu items. Observe that when your mouse is over the Inventory menu, the drop-down does NOT appear (incorrect behaviour).
7. Move your mouse away from the menu, being careful to not touch any of the surrounding menu items. Observe that when your mouse moves away, the Inventory drop-down DOES appear (incorrect behaviour).
8. Hover over any other menu item. Observe that it behaves correctly.
9. Hover over the Inventory menu again. Observe that it now behaves correctly.

I.e., Reloading a page causes the mouse on-hover effect for the menu of THAT page to be reversed (until you hover over any other menu section).

I've updated the top post to contain a link to this comment.
It's possible that the other reports here are referring to different issues instead of or as well as this one, but we can fix this one first and then it will be clear if there's any other problems.

**Comment by alexthomson1** [comment]
@laurel-thomson and I are interested in working on this issue.

**Comment by Alys** [comment]
@alexthomson1 @laurel-thomson great, thanks! Post here if you have questions.
