### ISSUE TITLE
extraMonths lost when free subscription from Group Plan is terminated

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11664]
If you have a free subscription from a Group Plan and have `extraMonths` stored up from a previous subscription, you lose those extra months when you leave the Group Plan.

Steps to reproduce:
1. Add a Group Plan to a guild (you can learn how to do that on a local install at [Using Your Local Install to Modify Habitica's Website and API](http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API)).
2. Invite a another user to the guild.
3. Make that user accept the invitation.
4. Modify that user's subscription data to set `purchased.plan.extraMonths` to any non-zero value (e.g., 12).
5. Make that user leave the guild.
6. Observe that the user's `purchased.plan.dateTerminated` value is a couple of days in the future and the user's `purchased.plan.extraMonths` is now zero.

The expected behaviour is that the user's `purchased.plan.dateTerminated` value should be as far in the future as the number of extraMonths that they had (e.g., one year in the future if you set extraMonths to 12).

----

To illustrate the bug, here's subscription data from a test user account while it was in a Group Plan with `// XXXXXXX` marking the fields of interest:
```
{
    "_id": "a56d9849-a7a4-4a1d-9653-248a5f821fd7",
    "purchased": {
        "plan": {
            "consecutive": { "count": 7, "offset": 0, "gemCapExtra": 10, "trinkets": 2 },
            "quantity": 1,
            "extraMonths": 12.052668652006172, // XXXXXXXXXXXXXXXXXXXXXX
            "gemsBought": 0,
            "mysteryItems": [ ],
            "planId": "group_plan_auto",
            "customerId": "group-plan",
            "dateUpdated": "2019-12-27T11:04:06.397Z",
            "paymentMethod": "Group Plan",
            "dateTerminated": null, // XXXXXXXXXXXXXXXXXXXXXXXXXXX
            "dateCreated": "2019-05-11T23:39:32.913Z",
            "owner": "a56d9849-a7a4-4a1d-9653-248a5f821fd7",
            "lastBillingDate": null,
            "nextPaymentProcessing": null,
            "nextBillingDate": null,
            "additionalData": null
        }
    },
}
```

Here's the same test user account after leaving the guild that had the Group Plan:
```
{
    "_id": "a56d9849-a7a4-4a1d-9653-248a5f821fd7",
    "purchased": {
        "plan": {
            "consecutive": { "count": 7, "offset": 0, "gemCapExtra": 10, "trinkets": 2 },
            "quantity": 1,
            "extraMonths": 0, // XXXXXXXXXXXXXXXXXXXXXX
            "gemsBought": 0,
            "mysteryItems": [ ],
            "planId": "group_plan_auto",
            "customerId": "group-plan",
            "dateUpdated": "2019-12-27T11:04:06.397Z",
            "paymentMethod": "Group Plan",
            "dateTerminated": "2019-12-29T00:00:00.000Z", // XXXXXXXXXXXXXXXXXXXXXX
            "dateCreated": "2019-05-11T23:39:32.913Z",
            "owner": "a56d9849-a7a4-4a1d-9653-248a5f821fd7",
            "lastBillingDate": null,
            "nextPaymentProcessing": null,
            "nextBillingDate": null,
            "additionalData": null
        }
    },
```
---

The bug is happening because when you leave the guild, the `cancelGroupSubscriptionForUser()` function is run twice (you can confirm that on a local install with a console.log line in that function). Here's the two places that run it:

https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/models/group.js#L1362
https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/controllers/api-v3/groups.js#L865

That function calls `cancelSubscription()` as you can see at the bottom of this code:
https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/libs/payments/groupPayments.js#L214-L243

So the `cancelSubscription()` function is run twice too. That function is responsible for calculating `dateTerminated` and then setting `extraMonths` to zero, as shown here:
https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/libs/payments/subscriptions.js#L332-L344

The first time that `cancelSubscription()` runs, it correctly reads the value of `extraMonths`, correctly sets `dateTerminated`, then correctly sets `extraMonths` to zero - all what it's supposed to do.
The second time it runs, because `extraMonths` is now set zero, `dateTerminated` is calculated without using the proper value of `extraMonths`, so the date is wrong.
You can confirm all that too with console log lines in `cancelSubscription()` that print out the values of `extraMonths` and `dateTerminated`.

---

I'm going to leave this as suggestion-discussion for a couple of days in case Habitica's staff want to comment on this or state that they'll fix it, then if there's no objections, I'll mark it as help wanted.

**Comment by hamboomger** [comment]
Wow, what a detailed issue description :) I could tackle this problem.

**Comment by Alys** [comment]
@hamboomger Thanks! Please go ahead and post here if you have any questions.

**Comment by shanaqui** [comment]
@hamboomger Hi! How's it going -- are you still interested in working on this? Please let us know!

**Comment by hamboomger** [comment]
@shanaqui Hey! Yep, as far as I remember I was able to reproduce the issue, but then I had to focus my attention on another project. I'll start working on it in a next couple of days

**Comment by shanaqui** [comment]
Alrighty, thanks for checking in!

**Comment by hamboomger** [comment]
@shanaqui I have a question, does this function checks whether the `group`(party/guild) is upgraded to a group plan _and_ the upgrade is still active? Because I can't quite comprehend what it means for a group to be subscribed/unsubscribed.
https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/models/group.js#L1652-L1657

**Comment by Alys** [comment]
@hamboomger Yes, that's the right function for checking if a guild is subscribed. 

When a player adds a Group Plan to a group (guild or party), the group's `purchased.plan` object is updated with information about the Plan and payment. You can see an example in [Using Your Local Install to Modify Habitica's Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) - search for the phrase "To add a Group Plan to a group". That data includes a `customerId` value (in the sample data it's set to `group-unlimited` but usually it's a value related to the specific payment account). The `customerId` is one of the important attributes for working out if a Group Plan is active. The other important attribute is `dateTerminated`. When a Group Plan is created, `dateTerminated` has a `null` value. If the group's leader cancels the Group Plan, then `dateTerminated` is set to a date in the future. At that point, the Group Plan is still considered active. Once the termination date is reached, the Group Plan is no longer considered active and the Plan features are disabled.

By the way, when we're talking about Group Plans, we try to avoid the term "subscribed", because it's too easy to confuse that with the subscriptions that a user has.  So to take your question as an example, we'd normally say something like "... what it means for a group to have an active / inactive Group Plan". This is in no way meant to be a criticism of your question! It's just an attempt to clarify. :) The isSubscribed() function is probably called that because there's a very similar function for working out if a user has a subscription, with the same function name.

Does all that make sense? Post again if you have more questions!

**Comment by hamboomger** [comment]
@Alys yes, right to the point of my question :) Then I guess the better name for `isSubscribed()` method would be something like `hasActiveGroupPlan()`? Then for example this method would be much easier to read:
https://github.com/HabitRPG/habitica/blob/039e7d40b85d10a6e4f8e0d3975a0d35d4c23095/website/server/models/user/methods.js#L483-L487

P.S. I can't find any tests which have groups with Group Plan enabled, I assume currently there is no short way to create such a test?

**Comment by Alys** [comment]
@hamboomger yes, in my opinion `hasActiveGroupPlan()` would be a clearer name, although I'm not sure if Habitica's staff would want the function renamed.
@paglias What do you think? See the previous three comments for details.

There should be tests for groups with active Group Plan. If you cd into the tests directory (one step down from the top-level directory) and then run the command below, there's a good chance that most/all of the files listed will contain tests for Group Plans (and there might be other files too with tests in them).
`git grep customerId | grep group | grep -v user`

Post again if that doesn't help or if you're having trouble finding a specific kind of test!

**Comment by paglias** [comment]
The name change sounds good to me 👍 Regarding the tests there are some unit tests at `test/api/unit/models/group.test.js`, `test/api/unit/libs/payments/group-plans` and some integration ones at `test/api/v3/integration/groups`

**Comment by hamboomger** [comment]
@Alys I actually have one question, what would be the best way to add extraMonths to the member of a group in integration test? Is it okay to modify user document in database directly? Or should I make some kind of createSubscribtion() call similar to this:
https://github.com/HabitRPG/habitica/blob/1a75c6a696850189e6870fd24e472d300045050b/test/api/v3/integration/groups/POST-groups_groupId_leave.js#L292-L305

**Comment by paglias** [comment]
I’d say in this case editing the database directly with an user.update call or when generating the user is probably the best way, would be too complex otherwise

**Comment by hamboomger** [comment]
After some investigation it looks like in both places checks performed before the `cancelSubscription` is called are actually the same: whether or not user is a member of any other group with active group plan.
Code in controller just double-checks everything that `cancelGroupSubscriptionForUser` is already taking care of.
The reason why `cancelSubscription` is executed only once when group type is `party` is because of an error here:
https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/controllers/api-v3/groups.js#L863-L866 
User model was not updated before the check, and party which user supposed to leave was still present in his `party._id`. After I fixed that, all 3 types of `groups` failed at calling `cancelSubscription` only once. Huraay...
So easy solution would be to remove this part from controller:
https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/controllers/api-v3/groups.js#L863-L866
However from design point of view I think it's better to call `cancelGroupSubscriptionForUser` function only from a controller(here), because `server/model/group.js` looks more like a data access layer to me, and if so then it's better to keep `leave` function as simple as possible. 
I propose to cancel subscription inside the controller and to stop doing it from model, what do you think? 
There are 2 direct usages of model's `group.leave` function btw:
https://github.com/HabitRPG/habitica/blob/a08b419411d7b4a1206e18578a4749779cec371a/website/server/controllers/api-v3/groups.js#L558
https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/controllers/api-v3/user.js#L293

**Comment by paglias** [comment]
good catch about the user.party not being updated! I'd say that we should update that controller to remove the party from the user object manually like we do with guilds (https://github.com/HabitRPG/habitica/blob/33b13a86da42c255bcdff9193b04c972104c7bb7/website/server/controllers/api-v3/groups.js#L859) The reason why it wasn't updated is that in group.leave we're sending a direct update command instead of changing the user doc and saving it

> I propose to cancel subscription inside the controller and to stop doing it from model, what do you think?

The problem with this, is that there are occasions where the group.leave function is called indirectly, for example when the user is removed by the leader or joins a new party. In those cases we still want the group plan to be removed

I agree that it's probably outside the group model scope but the leave function is already quite complex and will probably change it only when a bigger refactor is done

**Comment by hamboomger** [comment]
@paglias you're right, I kinda expected that kind of response, so I already prepared the changes. I also created some unit tests for the calculation of terminationDate in the meantime, so please tell me if you have ideas how to improve this pr, I'm open to suggestions!

**Comment by hamboomger** [comment]
@paglias could you please take a look at this issue? Before some other conflicts emerge between master and this branch.
