### ISSUE TITLE
Challenge categories can't be changed when editing

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11662]
After you've created a Challenge, if you then edit it, you can't change the categories.

You should be able to change categories from the Challenge's edit screen for cases where you select the wrong categories by accident.

**Comment by ok-ikaros** [comment]
Can I tackle this?

**Comment by ok-ikaros** [comment]
@Alys Just gently reminding that I'd like to take this issue! I took a look at it and it is actually quite a simple change.

**Comment by Alys** [comment]
@lelandhwu  Yes, please go ahead. Thanks.

**Comment by citrusella** [comment]
Question that might be more relevant on the PR, not sure: I think this happens when cloning, too (I cloned something from my party (where I do challenge readying privately before they're ready) to the guild I run and couldn't change the categories). Does that count as "editing" or is it a separate issue that would need to be fixed differently from the editing?

**Comment by ok-ikaros** [comment]
I believe that in both instances they use the same challenge modal, so the fix should work when cloning as well. Will test this manually later.
