### ISSUE TITLE
header partially hidden by body of page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11822]
_@Redpinkandwhite (7e608437-5403-42e2-81bf-c25cce8f6464) reported:_

"I am running into a small bug where my bar is overlapping my party images, partially cutting off my mana bar. I have tried refreshing the page and closing the tab.

I just tried closing the browser window as well and reloading Firefox. The images are still set under or over the bar. Image below:"

![scr](https://snipboard.io/7cr4IH.jpg)

"... I tried the [https://habitica.com/static/clear-browser-data] link and clicked the button. Logged on again. Same problem. 

All of my extensions I have used in the past I disabled before I asked. (Originally, this is what I thought caused the problem). I even uninstalled the add-on I was using in Firefox to manage the extensions. Still have a problem."

_I can reproduce the bug when I zoom out so I asked them to reset their browser's zoom but that didn't help:_

"... I found the View > Reset, but the 'Zoom text only' was not clicked. I checked it and clicked reset. Nothing happened. I unchecked the 'zoom text only' and hit reset again. Nothing.

I just noticed my browser also doing this. Hope it helps gain some insight into what is happening.

One with pictures over the background:
![scr](https://snipboard.io/VvZuWy.jpg)

One with pictures under the background:
![scr](https://snipboard.io/Cn51bx.jpg)

It tends to always be in the under the background mode, but it will sometimes go into the 'over the background' mode and then revert back to the 'under the background' mode."

_I noticed that their browser tab was pinned, which we know can cause various problems so I asked them to unpin it and clear the zoom again, but that didn't help:_

"The unpin did not help. Same problem.
Browser: Firefox 72.0.2 (64-bit)
OS: Windows 10 version 1903"

**Comment by DXCanas** [comment]
Does anyone mind if I pick this up? I'm new around here.

**Comment by DXCanas** [comment]
I'm thinking this line is the culprit:
https://github.com/HabitRPG/habitica/commit/53555a0f161a883a9a9bb3c801cf63e36153b8ed#diff-8cbf1baa36a2fdb9de136c1614f62226R51

as it uses `rem` to define the max height, and `rem` draws its height from `font-size` on `<html>`, which I believe is set by the browser according to the DPI on your display (or something). If the `font-size` on `<html>` is anything less than `16px`, you can replicate the effect since the height on avatars is hard-coded. 

I'd submit a PR, but it seems there's a vue-related reason @SabreCat made the change. Do you foresee any issue changing this?

**Comment by SabreCat** [comment]
@DXCanas I suspect the height change was unrelated to the Bootstrap-Vue syntax fix. We've slowly been trying to be more consistent with using `rem` instead of `px` for our sizing and spacing units, but as you point out it's problematic here due to the pixel-absolute nature of the avatar. Do feel free to submit a PR!

**Comment by DXCanas** [comment]
Would the better fix be to set the toolbar to `px` or the icons to `rem`?

**Comment by Tressley** [comment]
It would be better to use `rem` as it is the preferred unit. Additionally, we can convert the avatar unit to `rem` using the formula: `pixel value ÷ rem value`, e.g. `147/16 = 9.1875rem`

**Comment by Alys** [comment]
I've just realised we have a similar issue logged from before this one: https://github.com/HabitRPG/habitica/issues/11071

I suspect it's either from the same cause or will be affected (hopefully positively) by the fix for this issue, so I'm putting that one on hold until this issue is closed. ~I'm labelling this issue as "notify helpers" to remind me to check on the other issue later.~

**Comment by DXCanas** [comment]
Took a very long time to apply a single-line fix, but I've updated the PR with the fix after a rebase @Alys

**Comment by Alys** [comment]
@DXCanas Thank you!! I've marked this issue and https://github.com/HabitRPG/habitica/issues/11071 as in progress for you.
