### ISSUE TITLE
navigation menu leaves ghost image visible after clicking on a menu item

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11833]
This bug started about a day ago, so it's from a recent change.

JohnJSal (624e48a3-cbea-4bbe-ae44-ca9183f49626) reports:

"when I go to a menu item that has a drop-down list (e.g. Shops, Guilds, Challenges) and click on one of the list items (e.g. Market, My Guilds, Discover Challenges), it leaves a 'ghost' image of the drop-down list. This doesn't seem to happen if you are already on that particular main page (e.g. Challenges and you click one of the Challenge items), but it does happen when you go to a different page (e.g. you're on Challenges and then click 'Market' in the Shops drop-down). This last aspect makes it seem similar to the other problem that had been happening with the drop-down menu getting stuck.

"[Below is] a screenshot of what happens. Notice the Challenge drop-down list after I clicked 'Discover Challenges' from the Guilds page.

"... it does not persist. It goes away when the cursor is moved away. I also want to add that it happens even when you click the main menu category (Inventory, Shops, Guilds, and Challenges) and not just a drop-down menu item.

"... this issue doesn't seem to happen when clicking on the 'Help' menu or its drop-down items. The drop-down menu does remain open until I move the cursor away though. Is that intended, or should it immediately disappear?"

The Help menu is configured a bit differently than the others, which explains the difference in behaviour.

The bug was confirmed by geolojess, shanaqui, and me.

The desired fix is that the menu should close as soon as you've clicked on it.
~I guess it could be fixed by either keeping the menu looking normal after you've clicked on it until you've moved away or making the menu close as soon as you've clicked on it. I've marked this as "on hold - needs design" for a design-related decision to be made about that. @Tressley~

![image](https://user-images.githubusercontent.com/1495809/74082823-88024500-4aa9-11ea-9602-91e19522a599.png)

**Comment by Tressley** [comment]
The menu should close after you've clicked on a menu item.

**Comment by Alys** [comment]
I've updated the top post to indicate the desired fix and marked this as help wanted.

**Comment by artur-borys** [comment]
Hello, I'm new here and I would like to work on this issue.
I have already tried some change in my local instance and it seems that it is solveable by changing selectors related to topbar-item and topbar-dropdown in the style section of `components/header/menu.vue` component.

**Comment by artur-borys** [comment]
Hello I'm new here and I would like to work on this issue. 

At first I thought the dropdown should stay after user clicks and have a background color (which currently becomes transparent after user click). I have achieved this, so if maybe you would like the dropdown to stay I can commit this change.

**However** after a while I've seen that you want the dropdown to actually close - and I've achieved this too, by changing closeMenu() method in the menu component. There is an if statement that checks if `this.isMobile()` is true. There is a code that iterates droppable items and closes them, but since this code ran only on mobile version - the dropdown didn't close after user clicked on link on the desktop. After moving that fragment before the `if()`, everything seems to work as expected.

Before:
```javascript
closeMenu () {
      if (this.isMobile()) {
        this.menuIsOpen = false;

        Array.from(document.getElementsByClassName('droppable')).forEach(droppableElement => {
          droppableElement.classList.remove('down');
          droppableElement.lastChild.style.maxHeight = 0;
        });
      }
    },
```

After
```javascript
closeMenu () {
      Array.from(document.getElementsByClassName('droppable')).forEach(droppableElement => {
        droppableElement.classList.remove('down');
        droppableElement.lastChild.style.maxHeight = 0;
      });
      if (this.isMobile()) {
        this.menuIsOpen = false;
      }
    },
```

So you can choose which behaviour do you want to have and I will commit and make a pull request if you will allow me to.

**Comment by Alys** [comment]
@artur-borys I've marked this as in progress for you, thank you! The desired fix is from @Tressley 's post above ("The menu should close after you've clicked on a menu item.")
