### ISSUE TITLE
Android App Won't Sync With Site

### ISSUE THREAD

**Issue by abrillianttrek** [HabitRPG/habitica#1184]
There's a known bug for the android app that prevents the To Do's from syncing with the full site. But in reality, nothing syncs with the full site. For almost a full week, my dailies wouldn't reset; they maintained their check marks after completion for days on end. Manually unchecking them cost me health and gold. I finally logged into the site to discover that I had died, because the app didn't communicate any actions to the site.

**Comment by lefnire** [comment]
Which android app is this? There are two, and they both have public
repositories / issues queues - they'll likely be able to help you more

**Comment by ghost** [comment]
Why do we have TWO android apps?

**Comment by lefnire** [comment]
they're 3rd party, not official apps

**Comment by MagicMicky** [comment]
Hi there.
I'm the developer of one of those third party application.
This is a known bug of HabitRPG's API and is referenced here as #729. I think this will be resolved when the API will be updated to the v2.
A workaround would be to connect to habitrpg.com once a day, to let the dailies uncheck.

If you want to submit problems with the application just try to contact the developer using the contact link on their Play Store page, instead of coming here :).

**Comment by wc8** [comment]
Closing, then. Follow up on #729 or with the third-party developer as appropriate.
