### ISSUE TITLE
Group plan reminder email is using wrong value to generate price

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11864]
A user reported in email that their group plan for two people was quoted in their reminder email as renewing at 36 (instead of 12).

Alys already dug into what's going wrong:

> That's for [redacted for private details]
> It has 2 members (confirmed by checking in the database, not by relying on memberCount)
> The Group Plan's quantity is set to 3
> libs/subscriptionsReminders/amazonGroups.js has this equation:
> const subPrice = plan.price * (plan.quantity + group.memberCount - 1);
> subPrice is used to populate GROUP_PRICE in the group-renewal email template, which appears to be what produces the email the user is referring to.
> GROUP_PRICE is the "36" value.
> Is the wrong plan.price value being used?
> git grep price shows this (and other hits):
> libs/groupSubscriptionManager.js:9:  price: 3,
> libs/subscriptions.js:14:    price: 9,
> Both those values seem to be referring to Group Plans. I haven't followed the code through all the way but it looks like the price of "9" might be being applied in that equation, instead of the more correct price of "3". I.e., if you put "9" into the equation as the value for plan.price then you get the incorrect value "36" that the user is seeing in the email.
> If you put "3" into that equation as the price, you'd get the correct value of 12.

This only refers to the price quoted in the reminder email, not to the actual charges which are happening correctly.

**Comment by Alys** [comment]
I've marked this as important priority since it affects people who have paid to use Group Plans. It's actually not something that a contributor can fix because the code is in a private repo since it's related to sending emails (sorry shanaqui, I didn't mention that when I was describing the problem). I've chosen to leave this issue here though so that we don't lose track of it because I'm not sure how often issues in that other repo are reviewed. I've given it the "status: needs reply" label, even though it doesn't need a reply in the usual sense - this is just so we don't lose track of it here either since we don't have a status label for an issue that the staff alone will have to work on (this comes up rarely enough that I don't think we need one).

**Comment by paglias** [comment]
Sorry I had missed this one, I am supposing this is an Amazon Payments group since for Stripe we use the price provided by their api

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg-email-server/commit/93795a29bfaa2efa081e0af8dbb097729507f8d0
