### ISSUE TITLE
Searching guilds is inconsistent between "My Guilds" and "Discover Guilds"

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11860]
Reported by loremi:

> Hi, thank you for looking into the "CAD Cads" guild not being found under "3D" issue! Just as a follow-up: the guild leader has now included the word "3D" in both the summary and description, and the guild is now searchable under "Discover Guilds" :) This solved the problem, I just wanted to point to what's possibly a quirk for completion's sake: When searching for "3D" under "My Guilds", the guild still won't show up in the results. 

Confirmed by me in Firefox using that guild/keyword.

**Comment by Alys** [comment]
The desired fix is that the search algorithm in My Guilds should be the same as for Discover Guilds, although of course it should show only Guilds that you are a member of.

I've added the help wanted label.

**Comment by tsukimi2** [comment]
Mind if I take a crack at this?

**Comment by Alys** [comment]
@tsukimi2 Please do, thanks!

**Comment by tsukimi2** [comment]
@Alys Hi Alys, I think I"ll need some suggestion who have more experience with the code before making the changes.  Took an initial look at the code.  It seems that while "Discovery Guilds" searches by calling back the server api "/api/v4/groups" with params.search to retrieve only the guilds that satisfy the search criteria from the database each type the search box changes, "My Guilds" searches by retrieving all the guilds belonging to that group from the database only once  initially and then each time the search box changes it calls the filterGuild function in the client code to filter locally.

So "Discovery Guilds" search needs to call server api every time you type something in search box while "My Guilds" search calls the same server api only once initially and do a filtering locally on the client code every time you type something in the search box.  I would like to ask when it comes to searches, is there a preference that habitica is adhering to already, like whether the search should be contact server once then filter locally, or whether it should contact and filter at server level every time there is a search change? The changes should be easy to implement either way, just want to make sure before going ahead with the changes.  Thanks.

**Comment by Alys** [comment]
Each of those behaviours is correct for the page it's on:

The "Discover Guilds" page needs to show all public guilds in Habitica and there's more than 900 of them so it doesn't load them all at once. It has a "load more" button at the bottom. When the player has specified a search term, "Discover Guilds" needs to do a new database search because there's a good chance that some of the matching guilds were not loaded from the page's previous database search.

The "My Guilds" page displays many fewer guilds so it can afford to load them all at once. When the player enters a search term, it can do client-side filtering for that term to avoid a new database search query - that gives a faster response.

So I guess what's needed here is to look at the filtering method that "My Guilds" uses and try to make it the same as the search that "Discover Guilds" uses but with client-side code rather than server-side code.

Post again if any of that doesn't make sense.

**Comment by Alys** [comment]
One other thing:

It's possible that the "My Guilds" search is better in some ways than the "Discover Guilds" search, while being worse in other ways. If "My Guilds" does currently have some advantages for searching, it would be nice to keep those in addition to making "My Guilds" better.

As a simple hypthetical example, say that "Discover Guilds" searches through only name and description, while "My Guilds" searches through name and summary. You'd definitely want to add description to the "My Guilds" search. You wouldn't want to remove summary from "My Guilds" search.
