### ISSUE TITLE
Gems not removed after guild creation

### ISSUE THREAD

**Issue by loldude101** [HabitRPG/habitica#1186]
After creating a new guild earlier today, four gems have not been removed from my inventory. I've waited a couple hours before creating this ticket to see if it'll eventually be removed but my four gems (that were supposed to towards the guild) remain AND my guild has four gems. 

So I just wanted to let you know that this glitch exists and if more people notice it they can get away with creating new guilds without having to pay for them.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by PazZaitGivon** [comment]
So recently, two weeks ago, (a while after the rewrite) I (marquian on habitrpg as well) set up the guild: inHabitants of the earth. It told me it was going to take 4 of my gems, but it did not. The Guild does have four Gems but they are not mine, they appeared spontaneously as a gift/ newbie package? 

I think the bug is has the potential to be more serious than just people creating tons of guilds for nothing as if exploited under challenges, free guilds could be made and then immediately distribute out these "Free gems"

**Comment by paglias** [comment]
@lefnire https://github.com/HabitRPG/habitrpg/blob/master/src/controllers/user.js#L456 `balance` is protected, we talked about implementing a specific route or allowing only gems reduction some time ago but I think it's still missign

**Comment by lefnire** [comment]
oh shoot, is guild creation doing a User.log() for balance--? Yeah, most everything else is being handled on the server so this definitely needs to be updated. Good catch @paglias
