### ISSUE TITLE
private messages (PMs) screen is obscured by challenge/guild participant/member lists

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11910]
@mikoboy (0731c2a5-7ca8-446f-a86c-8121c1be3f1c) repored:

**"Opened my [challenges]. Opened the list of participants. And clicked to send a message I was in a chat room with this [person], but there were a list that covered up the visibility of the chat."**

It happens for me too with challenges and guilds. Below are the steps to reproduce, with screenshots. 

Step 1: view list of challenge participants or guild members:
![bug3](https://user-images.githubusercontent.com/1495809/75606622-59243f80-5b3a-11ea-86e8-20773c27d319.png)

Step 2: view profile of one participant:
![bug2](https://user-images.githubusercontent.com/1495809/75606621-588ba900-5b3a-11ea-8d40-edf1e6eec111.png)

Step 3: click private message icon, get taken to private message screen, observe that profile screen overlays it:
![bug1](https://user-images.githubusercontent.com/1495809/75606620-575a7c00-5b3a-11ea-9dbc-36411d74dcd7.png)

**Comment by tsukimi2** [comment]
@Alys Can I help out with this issue? Also, would like to confirm what's the desired behaviour in this case? Should it be displaying the private-messages page and closing the Members dialog (i.e. the list of participants of the challenge) and also closing the profile dialog box.  Thanks.

**Comment by Alys** [comment]
@tsukimi2 Thank you! I've marked this as in progress for you.

I guess now that the private messages screen is a regular web page rather than a modal, one option is that the Members and Profile modals (dialog boxes) should be closed when you click on the PM icon. I'm not sure that's the best approach though.

Another option is that both modals should stay open and the private messages page should be opened in a new tab (with no modals over the top of it). That would certainly be much more convenient for the case where a challenge or guild owner wanted to send PMs to multiple members. If we implemented the first option (closing the modals), then after they'd sent one PM, they'd have to navigate back to the guild or challenge, reopen the member list, and find the place they were up to in the member list. That would quickly become enraging. I hadn't put any thought into this before now (so thank you for asking!) but the more I think about it the more I feel that we do need to support the case where multiple people need to be PMed because that is a known use case.

You might want to wait a couple of days though to see if the staff have comments.

**Comment by tsukimi2** [comment]
@Alys Sure, let's wait a few days, at least until the coming weekend, for any useful user inputs. ^_^

**Comment by tsukimi2** [comment]
@Alys Sorry for the delay.  Have been recovering from the Wuhan virus and finally feeling fit enough to write code again.  Anyway, trying to implement the "open the private messages (PMs) page in new tab" approach you mentioned before but encounter a problem.  Hope you could provide some suggestions.

Under the current code, when you click the private message icon on the profile page of a particular participant (e.g. satou2 in the Profile Page Screen Cap below), you'll be taken to the private messages page with "satou2" selected.

Profile Page Screen Cap:
<img width="1440" alt="Screenshot 2020-03-21 at 11 07 44 AM" src="https://user-images.githubusercontent.com/3499949/77218240-45ca2a00-6b64-11ea-9f90-52d5fc93ae58.png">

Private Messages (PMs) Page Screen Cap:
<img width="1440" alt="Screenshot 2020-03-21 at 11 07 59 AM" src="https://user-images.githubusercontent.com/3499949/77218295-ce48ca80-6b64-11ea-895f-1cbf1fb35dd6.png">

The PMs page knows which user to select because when you click the private message icon on profile page by storing "satou2" info into vuex store before going to the private messages page:

https://github.com/HabitRPG/habitica/blob/f8aa756d524c250b21c4fee4427db316bb564460/website/client/src/components/userMenu/profile.vue#L861-L868

But if you are to open the PMs page in a new tab, then it cannot access the veux store and hence unable to retrieve the info to know which user to select, resulting in the following:
<img width="1440" alt="Screenshot 2020-03-21 at 11 54 59 AM" src="https://user-images.githubusercontent.com/3499949/77218854-d73c9a80-6b6a-11ea-8403-1cfd4cb33658.png">

One possible solution I'm thinking of is to pass the selected userid in profile component as part of url query when clicking the private message icon and opening the PMs page, like so:

/components/userMenu/profile.vue:
    sendMessage () {
      this.$store.dispatch('user:newPrivateMessageTo', {
        member: this.user,
      });

      this.$root.$emit('bv::hide::modal', 'profile');
      const routeData = this.$router.resolve({
        path: '/private-messages',
        query: { userid: this.user._id },
      });
      window.open(routeData.href, '_blank');
    },

and then in PMs page, retrieve the userid from the url query and use that to search the database for the required info to select the user, which results in the following PMs page:
<img width="1440" alt="Screenshot 2020-03-21 at 12 03 58 PM" src="https://user-images.githubusercontent.com/3499949/77218967-1ae3d400-6b6c-11ea-807a-325ad572b8e1.png">

But as can be observed in the screen cap above, this will expose the userid in the url.

Trying to google now but so far can't seem to find a way to pass info behind the scene in vue from component to another page when the page is being opened in a new tab.

Do you know if there is such a way to do that? Or any suggestion to a better approach to the problem? Thanks.

**Comment by Alys** [comment]
@tsukimi2 I'm sorry to hear you have COVID-19 and I'm glad you're recovering!

There's nothing fundamentally wrong with having the User ID in a URL, because User IDs aren't private information. In fact it would actually be helpful to be able to bookmark a URL that takes you directly to your conversation with a specific player if you PMed them often.

However I'll leave it for Habitica's staff to reply to your questions in case they have other ideas.

**Comment by tsukimi2** [comment]
@Alys Ic.  In that case I'll wait until after the weekend before submitting the PR if there are no response by then.  Thanks.

**Comment by paglias** [comment]
pinging @negue since he's the one most experienced with PMs

**Comment by negue** [comment]
Alys wrote:
> I guess now that the private messages screen is a regular web page rather than a modal, one option is that the Members and Profile modals (dialog boxes) should be closed when you click on the PM icon. I'm not sure that's the best approach though.

Yeah, when the PM was a modal it removed the previous modals in order to be the only visible now, now the member list -> profile modal, you click to private message but then the previous modal comes back up.

> The PMs page knows which user to select because when you click the private message icon on profile page by storing "satou2" info into vuex store before going to the private messages page:

@tsukimi2 as you explained in your post it sounds all correct :) 

Getting the target-user data by query-param would be the only way yes 👍 


What I would like to add, if the "private message" button would just always use the URL (`<a href`) if possible that way, the normal click would redirect in the same browser tab and with a middle click it would open a second tab

**Comment by Alys** [comment]
> What I would like to add, if the "private message" button would just always use the URL (<a href) if possible that way, the normal click would redirect in the same browser tab and with a middle click it would open a second tab

I love this idea!

**Comment by shanaqui** [comment]
Hi @tsukimi2! Just checking in again whether this is still in progress! :)

**Comment by tsukimi2** [comment]
@shanaqui Sorry, been a little bit busy lately.  Will try to see whether I can finish up the associated pull request either this weekend or the next.  Sorry about that.
