### ISSUE TITLE
Text contained in backticks is not wrapping on web

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11947]
Reported by JohnJSal:

> According to the Markdown Cheat Sheet, using ``` to highlight a block of text will cause long paragraphs to wrap automatically, but this doesn't seem to be the case on the website. Long sentences without line breaks will simply continue off the chat area and create a scrolling text box.

![image](https://user-images.githubusercontent.com/8144640/76087557-50a28d80-5fae-11ea-9009-056f81ea5c63.png)

**Comment by citrusella** [comment]
I think I reported this several months back but it was decided that non-wrapping was more in line with how a code block should theoretically work? (At the very least, it matches Github's behavior, so there's that.)

(I might have copied the answer as a to-do because I was meaning to fix the cheat sheet to align with the updated behavior. I'm... still meaning to do it. Might get to editing the cheat sheet next week (whether or not I edit for this--there are other things to be done to it).)

Hrm... can't find the to-do or anything else that suggests this (though IIRC the convo involved Alys and one other person), but I'm certain there was discussion surrounding this.

Only triple backticks cause this, though, IIRC. Single ones do wrap.

**Comment by Alys** [comment]
@citrusella Good memory! I've found two posts in a Report a Bug guild archive. I'm posting them in separate comments here to make it clearest where each one starts and ends. I don't want to use blockquoting or anything else to make the quoting clearer in case it interferes with the backtick and leading space markdown behaviour. The wrapping and non-wrapping that you'll see in your post below have been done by GitHub's own markdown handling, so it looks like Habitica is now doing the same as GitHub, which is a good sign. I think Habitica's current behaviour is probably correct. Mind you though, I've put only a tiny bit of thought into this while half-watching TV so point out if I've misunderstood!

**Comment by Alys** [comment]
**citrusella wrote at 2019-07-30 14:52 UTC:**

Is it intended for three-backtick and four-leading-space paragraphs to not wrap? I could see a reason for that, but on the flipside, the (not updated since the redesign, it seems) [Markdown Cheat Sheet](https://habitica.fandom.com/wiki/Markdown_Cheat_Sheet) on the website mentions wrapping on the three-backtick method at least.

Examples:

    This is a long paragraph that starts with four leading spaces. I'm trying to pad this out so that it for sure will be long enough that it would wrap if it were plain text. Is it long enough now? It's probably long enough. I think. Yeah.

as well as 

```
This is a long paragraph that has three backticks (`) on the newlines around it. I'm trying to pad this out so that it for sure will be long enough that it would wrap if it were plain text. Is it long enough now? It's probably long enough. I think. Yeah.
```

Compare: `This is a long paragraph surrounded by single backticks. I'm trying to pad this out so that it for sure will be long enough that it would wrap if it were plain text. Is it long enough now? It's probably long enough. I think. Yeah.`

It seems wrapping was removed sometime at time of redesign (most likely, to my brain) or post-redesign. Is that intended or an oversight?",

**Comment by Alys** [comment]
**Alys wrote at 2019-08-04 07:57 UTC:**

@citrusella I've done some reading about the use of backticks and leading spaces and I think the website's current behaviour is actually technically correct, even if it's different than it was before (and therefore [Markdown Cheat Sheet](https://habitica.fandom.com/wiki/Markdown_Cheat_Sheet) probably needs to be updated).

Text with three backticks before and after is known as a [fenced code block](https://marked2app.com/help/Fenced_Code_Blocks.html). It's [an alternative to indenting the lines of text](https://github.com/trentm/python-markdown2/wiki/fenced-code-blocks) -- i.e., three backticks and indentation using several spaces should result in the same appearance (which they do seem to be doing in Habitica). Those styles of formatting seem to have been designed for [displaying blocks of code](https://github.com/trentm/python-markdown2/wiki/fenced-code-blocks), and so wrapping would actually be incorrect -- some code would be severely broken if automatic wrapping was done (e.g., in Python where whitespace and line breaks are highly significant).

A single backtick is for inline code which is a bit different. You'd typically use it for a single code command, or at most a few commands separated by semi-colons (or whatever the language uses for marking the end of a command). Because of that, wrapping makes sense.

Of course in Habitica we used code blocks and single backticks for other purposes (the system messages in party chat use single backticks for coloured formatting; code blocks are used for quoting non-code text; etc). For some of those purposes it would be convenient to have automatic line wrapping in code blocks, but I think it's best that that not be done because it would break the \"proper\" use of code blocks. [Blockquotes](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#blockquotes) might be a better alternative for text that should wrap.

I think the previous website was incorrect in allowing wrapping in code blocks.

I'm interested to hear what you think about this though!

_[end of the Report a Bug guild posts]_

**Comment by paglias** [comment]
I'd like to close this bug as blockquotes would be more appropriate and we want to keep it possible to post non-wrapping code blocks. Opinions?

**Comment by Alys** [comment]
I agree and as citrusella noted, the previous behaviour was probably technically incorrect. I've updated the wiki to state that wrapping within three-backtick code blocks must be done manually.
