### ISSUE TITLE
Incorrect avatar for your own account in private messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12014]
When you're viewing your private message conversations with other players, all your previous messages show your current avatar.

The expected behaviour is that they show your avatar at the time that the message was sent. 

The expected behaviour can be achieved by using the avatar appearance data that's stored in each of the chat messages. For example below is one of the PMs I've sent and the `userStyles` object gives all the information needed to display my avatar. 

```
{
	"_id" : "a0a4b781-e96f-4088-a9c9-ad6d0a61a204",
	"sent" : true,
	"flagCount" : 0,
	"ownerId" : "d904bd62-da08-416b-a816-ba797c9ee265",
	"flags" : { },
	"id" : "a0a4b781-e96f-4088-a9c9-ad6d0a61a204",
	"text" : "test 2",
	"unformattedText" : "test 2",
	"info" : { },
	"timestamp" : ISODate("2020-03-25T10:24:49.305Z"),
	"likes" : { },
	"uuid" : "3e595299-3d8a-4a10-bfe0-88f555e4aa0c",
	"contributor" : { },
	"backer" : { },
	"user" : "Recipient's name",
	"username" : "RecipientsUsername",
	"userStyles" : {
		"items" : {
			"gear" : {
				"costume" : {
					"armor" : "armor_mystery_201410",
					"head" : "head_base_0",
					"shield" : "shield_base_0",
					"back" : "back_mystery_201410",
					"body" : "body_base_0",
					"eyewear" : "eyewear_special_greenTopFrame",
					"headAccessory" : "headAccessory_special_spring2015Healer",
					"weapon" : "weapon_base_0"
				},
				"equipped" : {
					"armor" : "armor_armoire_yellowPartyDress",
					"head" : "head_armoire_greenFloppyHat",
					"shield" : "shield_special_goldenknight",
					"back" : "back_special_aetherCloak",
					"body" : "body_armoire_cozyScarf",
					"eyewear" : "eyewear_armoire_goofyGlasses",
					"headAccessory" : "headAccessory_armoire_gogglesOfBookbinding",
					"weapon" : "weapon_special_2"
				}
			},
			"currentMount" : "",
			"currentPet" : ""
		},
		"preferences" : {
			"hair" : {
				"color" : "red",
				"base" : 0,
				"bangs" : 0,
				"beard" : 0,
				"mustache" : 0,
				"flower" : 0
			},
			"skin" : "6bd049",
			"shirt" : "green",
			"chair" : "none",
			"size" : "slim",
			"background" : "flying_in_a_thunderstorm",
			"costume" : true
		},
		"stats" : {
			"class" : "warrior",
			"buffs" : {
				"seafoam" : false,
				"shinySeed" : false,
				"spookySparkles" : false,
				"snowball" : false
			}
		}
	},
	"__v" : 0
}
```

**Comment by tsukimi2** [comment]
@Alys Can I help out with this one?

**Comment by Alys** [comment]
@tsukimi2 Sure, thank you!

**Comment by tsukimi2** [comment]
@Alys Just want to further clarify the expected behaviour before submitting the PR.

Let's say I am logged in as player A having a conversation on PM page with player B.  So the expected behaviour on my PM page (player A's PM page) are:
(1) To show my (player A) avatar at the time that the message was sent by me (player A).
(2) To show player B's avatar at the time that the message was sent by player B. 

Just want to confirm whether I'm getting the requirement correctly?

**Comment by Alys** [comment]
@tsukimi2 Yes, that's all correct.

Another way to put it is that the avatar next to a message should always be the avatar at the time the message was sent, regardless of whether it's player A or player B.
I.e., the avatar should always be constructed from the information in the message itself.

**Comment by Tressley** [comment]
> The expected behaviour is that they show your avatar at the time that the message was sent.

@Alys / @tsukimi2 -- This is no longer the expected behavior in Private Messages. Private Messages should only display a user's current avatar. This change was made due to feedback around differing avatars in PMs causing confusion. However, messages posted in The Tavern, Party, and Guilds will still retain the user's avatar at the time of the image.
