### ISSUE TITLE
Remove Merchandise page and all links to it

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#12039]
Right now Habitica is not running any merchandise campaign so the [Merchandise page](https://habitica.com/static/merch/) and all links to it should be removed.

Given that we may want to re-activate it sometime in future the original files should not be removed, removing the links to it and making it inaccessible by removing the entry in the client side router will be enough.

**Comment by benkelaar** [comment]
Why not remove the files? 

If you remove the files and the links in a single commit (e.g. by squashing before rebasing onto develop) getting it all back would be a matter of reverting that commit (And adjusting for the changed status of develop of course, but in general I would not recommend leaving dead code around)

**Comment by paglias** [comment]
I'm fine with removing them as long as we keep a comment maybe next to the old menu entry about the old file or we won't ever remember

**Comment by nathanzhu144** [comment]
I'm looking into this.

**Comment by nathanzhu144** [comment]
@paglias 
I've been able to remove the link to the merchandise page from the page footer; this was the only link I found - do you know if there are any other links to the merch page?

Also, how should I go about removing the merch page?  I tried commenting out the "merch.vue" file, but the page still displays on localhost.

We are currently looking into the server folder; could you clarify what you mean by "client side router"?

Thank you.

**Comment by Alys** [comment]
@nathanzhu144  You can do `git grep /static/merch` in the top-level directory of your local install to find all places where that string is mentioned (including in the router).

If you're on Linux or MacOS (or Windows if it lets you do this), you can do this command to find files and directories that might need to be removed: `find . -iname \*merch\*`
Note that it will show you some files that aren't related (e.g., any that mention "merchant" equipment)..

I'm not sure if you'd need to delete all of the locales files or just the `/locales/en/` one. Perhaps just delete the en one for now since the others _might_ be deleted by the Weblate translation process.

Note paglias's comment above:
> I'm fine with removing them as long as we keep a comment maybe next to the old menu entry about the old file or we won't ever remember

That means you'd actually NOT want to delete the old link but instead comment it out and add a comment to state that the associated files were removed. One way to do that would be to:
- do a PR with the file and directory deletions in it
- copy the URL of the PR into the code comment
- commit and push that code comment change so that it's added to the PR.

That way you won't have to list all the removed files in the comment since we can find them in the PR.

However if paglias gives you other instructions, listen to him not me. :)

**Comment by paglias** [comment]
Good point @Alys about removing un-needed locales strings!

regarding this 

> Also, how should I go about removing the merch page? I tried commenting out the "merch.vue" file, but the page still displays on localhost.

@nathanzhu144 the merch.vue file should be deleted, but it's loaded by Vue here https://github.com/HabitRPG/habitica/blob/develop/website/client/src/router/index.js#L21 in the client side route (which is separate from the server side one) and the entry that uses it (https://github.com/HabitRPG/habitica/blob/develop/website/client/src/router/index.js#L304) should be commented out with a comment linking to this issue

**Comment by nathanzhu144** [comment]
@paglias @Alys 

I've done the appropriate deletions, but when I run the test suite, I run into an assertionError on something I believe to not have touched.  Do you know what this might be caused by?

![Screenshot from 2020-04-12 18-45-15](https://user-images.githubusercontent.com/26507505/79081831-e2f52a00-7cee-11ea-9401-4d64b9c91644.png)
![Screenshot from 2020-04-12 18-45-19](https://user-images.githubusercontent.com/26507505/79081832-e688b100-7cee-11ea-93ac-4dd1c5a909b1.png)

I also ran the test suite on my develop branch, and ran into the same assertion failures, so I am a bit confused.

Otherwise, I've tested the changes, and they seem to pan out properly.

**Comment by Alys** [comment]
"Address already in use" in that message means there's two processes trying to use port 3000. Was "npm start" still running when you ran the tests? If so, stop it before running tests.

Or is any other process using that port? It might be a process not related to Habitica development, especially if you run local servers for other development purposes.

See also "Creating and Running Automated Tests" in [Using Your Local Install to Modify Habitica's Website and API](http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) in case any other information there helps.

**Comment by paglias** [comment]
@nataliechan regarding the tests error sometimes they happen, but they seem related to the API part which shouldn't be affected by these changes, if you create a PR I'll give it a look! it'll also run the tests automatically here on github so we'll see if it keeps happening

**Comment by nathanzhu144** [comment]
@Alys 

I believe it could've been another process I was running.
@paglias 
I have made the changes and made the requested PR!
