### ISSUE TITLE
When hatching the egg at the end of a row, eggs rearrange

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12040]
Report from Geolojess: 
> Also, found another display bug! When I'm on the items page and hatching eggs, if I hatch the egg at the very end of the row, then that egg and the eggs in the second row will all switch places! But ONLY if you hatch the one on the end of the first row. I tested to see if hatching any of the eggs in the second row produced the same results but they did not. Only discovered this because I was hatching hippos and when I went to hatch a second I ended up hatching a cuttlefish, because the hippo egg moved! XD (and I'll keep the cuttlefish, no big deal!)

To reproduce...

1. Egg at the end of the row is hatchable:
![image](https://user-images.githubusercontent.com/8144640/78345591-bd9d4900-7595-11ea-8ee2-42878adb9d4e.png)

2. Hatch it.

3. It has swapped with an egg from the row below.
![image](https://user-images.githubusercontent.com/8144640/78345620-c726b100-7595-11ea-9188-6a9f9bc234b8.png)

_EDIT by Alys 2020-05-13:_

As described in the comments below, reordering happens because the numbers of the items change (items are sorted by how many you own). It's disconcerting though when you're still using them.

**The desired fix is that the items should not change order while looking at the page.**
**Reordering should only happen if you reload the page, or sync, or go to another page then back again.**

**Comment by citrusella** [comment]
I've seen this happen when I start a quest, and it jumps down to a different spot lower on the list. At the time, I had assumed that there was a defined order to the listing but the count hierarchy took priority, i.e. the list's logic was "list in descending order of amount-of-item, then list in order-defined-somewhere".

That is, I don't think it's "random", precisely.

If one looks at the specific egg in this example, it didn't so much "swap" with anything so much as moved to the area of the list where eggs of an amount of 1 are, while the first item on the second line moved into the spot it no longer held on the first line. If it's anything like quests, I bet it moves to a consistent spot, but that spot can seem random because it's dependent of the varieties and amounts of every other egg you have, which is a lot more turbulent sort of a list than quests (which are either directly bought or given at defined times/less often).

Not defending the behavior, exactly, so much as trying to understand it, but...

**Comment by fmaximus** [comment]
In the screenshot, the eggs are sorted by *quantity*, so it makes sense that it will move to a lower position if an egg is used.

**Comment by Alys** [comment]
That's true, but it's disconcerting and annoying if you''re still trying to use that particular type of item (e.g., if you want to hatch several pets with the same type of egg). Perhaps it would be better the items didn't change order at all while you were looking at the page. They could reorder themself each time you reloaded the page, or synced, or went to another page then back again.

I'm labelling this as suggestion-discussion

**Comment by shanaqui** [comment]
> Perhaps it would be better the items didn't change order at all while you were looking at the page.

I agree.

**Comment by veeeeeee** [comment]
Agree with @Alys's assertion that items did not change order while looking at the page. Reordering should only happen on reloading the page/sync/navigating away.

**Comment by fmaximus** [comment]
PR ready: Moving away and going back resets the order.
Sync doesn't, new egg types end up at the end.
