### ISSUE TITLE
Challenge winner popup showed name of a previous challenge, not the challenge just won

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12067]
Reported by JohnJSal:

> A few days ago, maybe a week, I won a challenge called "Ideas and suggestions for higher level Habiticans" and properly received that notification. Today I won a challenge called "Royal Magus 3.2020" but a notification popped up with the name of the former challenge in it again. I never received a notification for today's challenge, or perhaps that was it but it had the wrong name in it. Just wanted to mention this in case it's something that can be investigated. I do have both challenges listed in my achievements, so that much is correct. It was just the notification that seemed to have the wrong name in it. (This was all on the website.)

I haven't been able to confirm this behaviour, so I've marked it as "needs investigation".

**Comment by Alys** [comment]
This used to happen but was fixed, however it sounds like the bug is back, even if intermittent. I've reopened the old issue because it had technical details in it (which might or might not be relevant now) and had links to the previous PRs that fixed it (which might also help): https://github.com/HabitRPG/habitica/issues/7716

I'll close this new issue but I've linked to it from the old issue.
