### ISSUE TITLE
Static overview page layout is completely broken

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12070]
![image](https://user-images.githubusercontent.com/8144640/78991293-8a782e00-7b30-11ea-8bc3-652201cc0b44.png)

The footer is appearing in front of the intended text, which also appears to be displaced downwards.

**Comment by paglias** [comment]
@shanaqui where is a link to that page? can't find it anywhere

**Comment by shanaqui** [comment]
The direct link is this: https://habitica.com/static/overview

I don't know where the user found it.

**Comment by Alys** [comment]
It's at Help > "Overview for New Users"

**Comment by Alys** [comment]
This problem is still happening in production but not on my local install (and a contributor in Aspiring Blacksmiths has also noticed it's not happening on their local install).  My install's two most recent commits are these:
```
commit 15c09691aff8e3a472bbcfafc0d9314b4a547746 (HEAD -> develop, upstream/develop)
Merge: 8ca5ee99b0 27263e9b2f
Author: Matteo Pagliazzi <matteopagliazzi@gmail.com>
Date:   Sat Apr 18 17:42:47 2020 +0200

    Merge branch 'release' into develop

commit 27263e9b2f83c569421d0fb7fa6e98b7b940953b (tag: v4.140.8, upstream/release)
Author: Matteo Pagliazzi <matteopagliazzi@gmail.com>
Date:   Sat Apr 18 17:41:40 2020 +0200

    4.140.8
```

And those should be what's on production now (see the [releases](https://github.com/HabitRPG/habitica/releases) page), so this bug might be related to a config difference between local installs and production??

**Comment by CraigInches** [comment]
It appears on a local install the elements are formatted with inline CSS, but on the production page its being sourced from https://habitica.com/static/css/static.692e5880.css. 

'container-fluid static-view' appears to be the culprit editing this inline so it isn't used  fixes this issue in prod.

**Comment by paglias** [comment]
Looks like some css from a different page was leaking into the overview one (thanks @CraigInches !) It's been fixed in https://github.com/HabitRPG/habitica/commit/d4b867acc3f6f356f5cca0d6db0d70d8bf71783d
