### ISSUE TITLE
purchase warning for Hatching Potions should stop you buying more than 9 when Mounts don't exist

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12103]
For premium / wacky Hatching Potions (the ones that can be obtained only with Gems), when you try to buy more than you need, you're given a warning that you don't need that many. (the `purchasePetItemConfirm` string "This purchase would exceed the number of items you need to hatch all possible <%= itemText %> pets. Are you sure?")

This does not work correctly for those potions that you can't get Mounts from (e.g., the new Confection / `Dessert` potion - not to be confused with `Desert`). It should give you the warning when you try to buy more than 9 potions.

https://github.com/HabitRPG/habitica/blob/8da36bf27c62ba0397a6af260c20d35a17f3d911/website/client/src/components/shops/buyModal.vue#L566-L569

<strike>I'm marking this suggestion-discussion in case the staff want to comment on how this should be fixed. If there's no comments or objections from them after about a week, I'll mark it as help wanted with a warning that before a Blacksmith starts coding for it, they should describe their proposed solution here so that it can be assessed for suitability (e.g., for ease of maintenence as other such Hatching Potions are introduced).</strike>

**Comment by veeeeeee** [comment]
We're fine with handling this exactly the same as premium Hatching potions, with the number changed to the appropriate amount.

**Comment by fmaximus** [comment]
As only the wacky Hatching Potions seem to be Pets only

https://github.com/HabitRPG/habitica/blob/f60b50d6fa77d1343ae13fff50221982c0923082/website/common/script/content/stable.js#L79-L82

I think it would suffice to add 

    if (item.path.indexOf("wackyHatchingPotions.") !== -1) {
        petsRemaining -= 9;
    }

to this if block
https://github.com/HabitRPG/habitica/blob/8da36bf27c62ba0397a6af260c20d35a17f3d911/website/client/src/components/shops/buyModal.vue#L560-L562

Since ItemInfo is set as
https://github.com/HabitRPG/habitica/blob/1e1c058d8274047bb2f704b9ede257f569c35817/website/common/script/libs/getItemInfo.js#L85-L98
