### ISSUE TITLE
Using the sync button in the private message inbox does not reload properly

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12139]
> Bug report: When, while in /private-messages, you click on the Sync button next to the Notifications at the upper right corner of the screen, it is expected to refresh the message list. Instead, it empties it.

Confirmed in Firefox. Actually, it doesn't empty the message list: it sort of half refreshes it, showing only a selection of my past conversations (not the most recent ones).

**Comment by Alys** [comment]
I've marked this as suggestion-discussion.

I think the ideal behaviour here would be for the sync button to cause the conversation you're currently looking at to be updated with any new messages that had come in since you opened the conversation, and also for the left-hand panel to be updated if a new conversation had been started by someone else. That's probably why you'd click the sync button while in the Inbox.

However that might take a bit of work since (if I recall correctly) the sync button currently loads data only from the user document.
Inbox messages aren't stored there.

**Comment by Tressley** [comment]
Best to loop @negue in for this discussion since he's handled the most recent PM work.

As for a solution, I agree with Alys' suggestion. Syncing while viewing a conversation should essentially "fetch recent messages" while remaining in that conversation. The Conversations list should also be updated with new messages.

**Comment by negue** [comment]
On pressing the header sync button - it reloads the user-obj, then once that is done, it emits this event `EVENTS.RESYNC_COMPLETED`.

In `private-messages.vue`:

```js
    this.$root.$on(EVENTS.RESYNC_COMPLETED, async () => {
      await this.reload();

      this.selectFirstConversation();
    });
```

the `this.reload()` reloads the conversation list (left sidebar) and then selects the newest (first) conversation (where the newest message is) to load the messages of this selected conversation.


But I think I found the issue:
- now that conversations (left sidebar) are loaded in pages
- and you were probably on page 2 ? - `this.conversationPage` is not reseted on `this.reload()` 

Gonna push a hotfix to release

**Comment by negue** [comment]
https://github.com/HabitRPG/habitica/commit/b1a348aee3b4958f4480c919cb3b592ee720dcd8 should fix it once its pushed to production

**Comment by paglias** [comment]
Closing so that we don't forget, the next deployment should be tomorrow
