### ISSUE TITLE
Why does it show this type of messages?

### ISSUE THREAD

**Issue by Danili5** [HabitRPG/habitica#12175]
Why does the program need to show, that someone found zero of something?
![Capture213](https://user-images.githubusercontent.com/54007091/81129444-f10f2280-8f09-11ea-9742-2f4c44369583.PNG)

**Comment by Alys** [comment]
We actually have a couple of guilds within Habitica for reporting problems and asking questions. :) For questions like this, the best place is the [Habitica Help: Ask a Question](https://habitica.com/groups/guild/5481ccf3-5d2d-48a9-a871-70a7380cee5a) guild, which you can reach through Help > Ask a Question from the website's menu. For bug reports, Help > Report a Bug will direct you to the bug guild (and it's also mentioned in the comments in the new issue template here). We generally use GitHub issues only for bugs that need code fixes, or sometimes for staff-approved features to be added.

However to give you a brief answer to your question, when you're in a collection quest, you are meant to find items that make progress towards the quest. You have a random chance of finding an item when you do a task. If you don't do many tasks, you might not find any items. Each day when you start using Habitica, cron runs ( [cron](http://habitica.wikia.com/wiki/Cron) is the process that performs actions at the start of each day such as resetting your Dailies and applying your quest progress), and it applies your found items to the quest and states in party chat how many you found. That's the message you've shown in your screenshot. It happens even when you've found 0 items so that you know you found 0. If you'd like more details, see the wiki's [Quests](https://habitica.fandom.com/wiki/Quests) page or ask in the Habitica Help guild. :)
