### ISSUE TITLE
New tasks added to existing challenge should always show up with challenge tag

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12224]
When you join a challenge, a tag for that challenge is created in your account (at least it is when [this bug](https://github.com/HabitRPG/habitica/issues/10689) doesn't happen). You have the ability to delete the tag if you want to while still in the challenge (that's intentional and shouldn't be changed; e.g., it's useful if you've retagged the challenge tasks with one of your own tags).

If the challenge owner adds new tasks to the challenge after you've joined, those tasks will be added to your task list but if the challenge tag does not current exist, the tasks won't be tagged probably. They will have the challenge/tag id in their `tags` list but since the tag itself doesn't exist, that isn't any use - you can't filter to find the new tasks.

The desired behaviour is that when new tasks from a challenge are added to your list, the tag is created IF it doesn't already exist. If it does already exist, a new copy of the tag should not be created.

However I'm not actually sure how easy this would be and it might add extra load if the only way to achieve it was to check for the presence of the tag for every challenge task, including the tasks that are added when you first join the challenge.

~I've labelled this suggestion-discussion for us to decide if it is a fix we want.~

_Thanks to @Altariel (be317a32-c027-4032-bbd5-25ccb21eb912) for reporting this._

**Comment by veeeeeee** [comment]
This behavior is reasonable. Ok to move forward

**Comment by tsukimi2** [comment]
@Alys Alright if I have a try at this issue?

**Comment by Alys** [comment]
@tsukimi2 Sure, thanks! Please go ahead and post here if you have questions.

**Comment by tsukimi2** [comment]
@Alys Just started working on the issue, but since I have only joined very few challenges in my habitica game play before and have not used the tags before, so I'm not 100% sure whether I'm getting the problem description correctly and so just want to confirm before proceeding.

In particular, concerning the desired behaviour "when new tasks from a challenge are added to your list, the tag is created IF it doesn't already exist".  Does it mean that, for example, if userA created a challenge called UserAChallenge with task ToDoA1, then userB joins the UserAChallenge but then deleted the UserAChallenge tag on userB's task list, then afterward userA added another task (called ToDoA2) into the challenge UserAChallenge, then userB's task list should have the UserAChallenge tag automatically added back, but when userB uses the UserAChallenge tag for filtering on userB's task, the userB's task list should show only task ToDoA2 (since ToDoA1 is now without any tag)?

Just want to confirm whether this is the desired behaviour? Thanks.

**Comment by Alys** [comment]
@tsukimi2 That's exactly correct in my opinion!

It may seem inconsistent that the re-added tag applies to only ToDoA2, but since the player had previously chosen to delete the challenge's tag, they would not want it re-applied to all challenge tasks. The point of adding the tag back is to easily let them find the new challenge task, so I think applying the tag to only ToDoA2 is correct.

**Comment by tsukimi2** [comment]
@Alys To produce the desired behaviour, instead of modifying the client-side to "check for the presence of the tag for every challenge task", which might add extra load every time you load the task page as you first mentioned in the issue, do you think the following approach would work without creating any undesired effect?

I'm thinking about modifying the server-side such that when userA who owns a challengeA adds a new task (e.g. task ToDo5) to that challenge, the server-side can use the mongo $addToSet to add the tag challengeA belonging to that challenge to the tags array in all the user documents in the user collection who have joined the challengeA.  This should have the effect of "creating the tag if it doesn't already exist, and if it does already exist, a new copy of the tag should not be created".  And afterward, when other users (e.g. userB) who have previously joined challengeA but deleted the challengeA tag from userB's tag list before, the challengeA tag will be displayed again on userB's tag list the next time userB loads his task page.

More precisely, what I'm thinking of changing is the following code in function _addTaskFn in server/models/challenge.js from the present code:
https://github.com/HabitRPG/habitica/blob/92dc332ab908416750c1ca5671dad62837123e31/website/server/models/challenge.js#L237-L239

to something along the following line:
```
  // Update the user
  const addToChallengeTagSet = { $addToSet: {
    tags: {
      id: challenge._id,
      name: challenge.name,
      challenge: true,
    },
  }};
  const updateParam = { ...updateTasksOrderQ, ...addToChallengeTagSet };
  // toSave.unshift(User.update({ _id: memberId }, updateTasksOrderQ).exec());
  toSave.unshift(User.update({ _id: memberId }, updateParam).exec());
  return Promise.all(toSave);
```
Since presently, the above existing code already involves sync-ing / updating the user documents of challenge members when a new task is being added to a challenge by adding this updating task  to a task queue where only 25 users are being updated simultaneously, just thinking whether it's a good idea to piggyback the "updating user tag list" as well along the way? Thanks.

**Comment by Alys** [comment]
@tsukimi2 That sounds great to me and I love how much detail you've gone into in your explanation! You may like to wait a day or two (maybe until next week since it's the weekend now in some places) to see if Habitica's staff have any comments. They are much more familiar with good coding practice for Habitica than I am. :)

By the way, this isn't strictly related but if you do change that file, could you also please adjust this comment?
https://github.com/HabitRPG/habitica/blob/92dc332ab908416750c1ca5671dad62837123e31/website/server/models/challenge.js#L247
Instead of saying "process only 5 users concurrently" it may be better to say something like "process only this many users concurrently". That will stop the comment getting outdated again if the number changes again.

**Comment by tsukimi2** [comment]
> @tsukimi2 That sounds great to me and I love how much detail you've gone into in your explanation! You may like to wait a day or two (maybe until next week since it's the weekend now in some places) to see if Habitica's staff have any comments. They are much more familiar with good coding practice for Habitica than I am. :)
> 
> By the way, this isn't strictly related but if you do change that file, could you also please adjust this comment?
> https://github.com/HabitRPG/habitica/blob/92dc332ab908416750c1ca5671dad62837123e31/website/server/models/challenge.js#L247
> 
> 
> Instead of saying "process only 5 users concurrently" it may be better to say something like "process only this many users concurrently". That will stop the comment getting outdated again if the number changes again.

@Alys Sure, will change the aforementioned comment in the next PR submit (forgot to do so on the first PR).  Just a quick question, instead of leaving a magic number of 25 here deep in the model layer, would it be better to have it as a part of the configurable items in config.json and use nconf.get in the challenge model? Or was it because it was anticipated that it's only in this part of the code that TaskQueue will ever be used and so it's alright to just leave the number here? Thanks.

**Comment by Alys** [comment]
@tsukimi2 My personal feeling is that the number doesn't need to be in config.json. It's not likely to be changed often, nor different for the various production/test/local sites, and the codebase has many other numbers hard-coded as constants. So I think it'd be fine to just change the comment and leave the number there but if Habitica's staff say something different, follow their advice not mine. :) Thanks for asking about this!
