### ISSUE TITLE
Renaming a party shows you the placeholder text for renaming a guild

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12273]
From Report a Bug:

![image](https://user-images.githubusercontent.com/8144640/83778813-1b780b00-a683-11ea-9367-5f4a73fc82a6.png)

It says "Enter your **guild's** name" instead of "Enter your party's name".

**Comment by Alys** [comment]
I've labelled this as "good first issue" so ideally it should be picked up by someone relatively new to Habitica's code.
 
As a note for anyone working on this, the same form is used for both Guilds and Parties, so the fix is NOT to merely change the text but to put in an "if" statement or similar. There's likely other code on the form that has different behaviour for guilds versus parties.

The [Using Your Local Install to Modify Habitica's Website and API](http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) wiki page has information about how you can use "git grep" to drill down through the code to find the file that you'd need to edit (search in it for "git grep" and you should find it).

**Comment by PitiTheGrey** [comment]
It would ne my second contribution to Habitica code. If that counts as relatively new, I would give it a try.

**Comment by Alys** [comment]
@PitiTheGrey That would be great! Thank you! Post here if you have questions.

**Comment by PitiTheGrey** [comment]
"Enter your guild's name" has an entry in the locales files (for translation), but   
"Enter you party's name" has not. 
Shall I go just with the english version? 
Otherwise we might have to add a new line to every locales files.

**Comment by Alys** [comment]
You can create a new string in just the locales/en/ file (put it directly underneath the "Enter your guild's name" string to keep them both together). You don't need to edit the other language files because the translation process will do that automatically (see the README file in the locales directory for brief details and there's more info on the wiki if you're curious).
