### ISSUE TITLE
Habits in the challenge view have incorrect and misaligned negative icon

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12311]
![image](https://user-images.githubusercontent.com/8144640/85136054-f238ac80-b236-11ea-9722-9fed4e14cebf.png)

Presumably they should have the lock icon, horizontally centred.

**Comment by Shuyinsama** [comment]
**UPDATE:** The core problem is the fact that the icon that is loaded should be the lock indeed. If that `v-if` check passes then the lock will load and the positioning will be correct and the whole check for `isUser` is working correctly. It is purely the icon that is incorrect!

![image](https://user-images.githubusercontent.com/650886/85182639-91868f80-b289-11ea-84b3-2e4a8874cb96.png)

I would love to solve this with some help. I think simply changing the `task.group.id` check to something more suitable would solve this.

**Original post:**
It seems like not all the needed classes are set in the `task.vue` component.

https://github.com/HabitRPG/habitica/blob/fd8f21455c5e865c9dcf1f8774bd7c19ee708bd2/website/client/src/components/tasks/task.vue#L311-L318

The `habit-control-negative-disabled` class should be set and is set when `task.down` equals `false` and when the `isUser` prop is set.

The `task.vue` component is used in the `column.vue` component:
https://github.com/HabitRPG/habitica/blob/fd8f21455c5e865c9dcf1f8774bd7c19ee708bd2/website/client/src/components/tasks/column.vue#L91-L101

which in its turn also has the `isUser` prop set. This prop is set to `false` by default in `column.vue`

https://github.com/HabitRPG/habitica/blob/fd8f21455c5e865c9dcf1f8774bd7c19ee708bd2/website/client/src/components/tasks/column.vue#L378-L381

Going up one more time to see where this column is set is in the `challengeDetail.vue` component:

https://github.com/HabitRPG/habitica/blob/fd8f21455c5e865c9dcf1f8774bd7c19ee708bd2/website/client/src/components/challenges/challengeDetail.vue#L127-L137

here the `isUser` prop is never passed in so it defaults to `false` all the way down to `task.vue`

I guess this should be expected behaviour. To be honest I am new to the codebase of Habitica so I am not 100% sure if this is a bug or if the check in `task.vue` should be something like
`!task.down && !isUser`

If I remove the `&& isUser` the icons align correctly. But as I said before I'm not sure if it breaks anything else.
![image](https://user-images.githubusercontent.com/650886/85181742-f8567980-b286-11ea-87b7-0ccd21ad3d06.png)

As for the icon not being the lock items that boils down to the fact that there is check in the `task.vue` that does the following `v-if="task.group.id && !isUser"`

https://github.com/HabitRPG/habitica/blob/fd8f21455c5e865c9dcf1f8774bd7c19ee708bd2/website/client/src/components/tasks/task.vue#L319-L324

Yet when I inspect the Component props and attributes the `task.group` object does not have `id` so it returns `false && true` which ultimately is `false` since both of them need to be `true` to pass. So it fails and runs the `v-else` code which is:

https://github.com/HabitRPG/habitica/blob/fd8f21455c5e865c9dcf1f8774bd7c19ee708bd2/website/client/src/components/tasks/task.vue#L325-L329

**Comment by paglias** [comment]
@SabreCat @negue might this be due to one of the recent design changes to the tasks?

**Comment by negue** [comment]
in #12274 (or rather in our ongoing refactor of #12142) the condition `task.group.id`  was removed for the positive icon, but not for the negative one.

@SabreCat so only the condition for the negative needs to be removed?

**Comment by Shuyinsama** [comment]
@negue If that is correct I've added a Pull Request. If something needs to change let me know :)
