### ISSUE TITLE
can't send second private message to new recipient after sending first message: "user is no longer receiving private messages"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12366]
As reported by @Nakonana (33bb14bd-814d-40cb-98a4-7b76a752761c): 

_"... bug that I encountered twice within ~2 weeks: when I send a PM to someone with whom I don't have a PM history (I think, that's when it happens), then switch to another PM or somewhere else in Habitica (I think), then open the inbox with said sent PM, it tells me that I can't reply to this conversation anymore. This got me worried both times because I ended up thinking that I bothered the person to the point, they either blocked me or opted out of the PM system after my PM o.o It looks like the system message disappears if I refresh Habitica via the browser."_

Confirmed on my account (which is a moderator account so it's allowed to send PMs to everyone regardless of blocks).

Steps to reproduce the bug:
1. Find a player that you haven't sent a PM to before (e.g., a test account you own).
1. Send a PM to that player. Observe that it's sent successfully.
1. Click on another conversation in your inbox.
1. Click back to the conversation that you had just started in step 2.
1. **Observe that the message screen says "You can not reply to this conversation. This user is no longer receiving private messages" and that the text box for sending a new message is greyed-out.**
1. Click the sync button in the header (or reload, but sync is enough).
1. **Observe that you can now send a PM to that player. This is the expected behaviour that you should see in step 5.**

For step 1, you can also choose a player that you have PMed before just first delete all messages to and from them, then reload the website with your browser's refresh button.

I have also been able to reproduce this when sending a PM to a player that I had PMed before, but that doesn't seem to be consistent. Often you don't get blocked from sending a second message. The steps above though were consistent every time I followed them.

**Comment by paglias** [comment]
Might be due to the redesign of the inbox? cc @negue

**Comment by Alys** [comment]
I've labelled it suggestion-discussion until negue comments.

**Comment by negue** [comment]
Oh, I fixed a same kind of issue some weeks ago.

The ability to send a message to an user is allowed if none of these conditions are true: https://github.com/HabitRPG/habitica/blob/develop/website/client/src/pages/private-messages.vue#L765

The message `This user is no longer receiving private messages` is from `PMUserDoesNotReceiveMessages` which is only shown if `canReceive` is false.

The last time of this issue it was that `this.selectedConversation.canReceive` was false but these were fixed with:
https://github.com/HabitRPG/habitica/commit/fe6c21800cea50597543f0abba264de607f234a2

I think `canReceive` should need to be added inside `sendPrivateMessage`

**Comment by Alys** [comment]
@negue Thanks! Shall I mark this as "help wanted" for a contributor to work on? Or "in progress" for you if you want to work on it?

**Comment by negue** [comment]
I'll fix it :)
