### ISSUE TITLE
Vue duplicate keys errors in Quests shop

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12396]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When running Habitica in a dev environment, and visiting the Quest Shop, you'll see various errors like this in the JS console:

```
[Vue warn]: Duplicate keys detected: 'starEmpty'. This may cause an update error.

found in

---> <QuestInfo> at src/components/shops/quests/questInfo.vue
       <BVPopoverTemplate>
         <BVPopover>
           <BPopover>
             <ShopItem> at src/components/shops/shopItem.vue
               <Index> at src/components/shops/quests/index.vue
                 <Index> at src/components/shops/index.vue
                   <App> at src/app.vue
                     <Root>
```

Most commonly you see `starEmpty`, but various values used in quest information may also appear, e.g. "Ruby" for the several Ruby potions obtained for completing the Ruby Rapport quest if you open its buy modal.

Presumably there's some way to iterate out a `v-for` list that may contain identical items, such that Vue doesn't complain about dupe keys?

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

see above!

**Comment by paglias** [comment]
For the `starEmpty` instance it comes from [here](https://github.com/HabitRPG/habitica/blob/develop/website/client/src/components/shops/quests/questInfo.vue#L31) using the star type from the for loop [here](https://github.com/HabitRPG/habitica/blob/develop/website/client/src/components/shops/quests/questInfo.vue#L165) as a key and there can be more than 1 star of the same type.

In this case I'd simply use  the index to distinguish the various items as the stars of a quest don't change so `v-for="(star, index) of stars()" :key="index"`

Otherwise Vue suggests that with simple arrays the key might even not be necessary https://vuejs.org/v2/guide/list.html#Maintaining-State but I don't remember if our linter will complain about it

**Comment by SabreCat** [comment]
Yeah, I tried dropping the `:key` line but it did indeed gripe that `v-for` needs a key!

**Comment by bigsee** [comment]
@SabreCat @paglias I'd be happy to take a look if this still needs attention?

**Comment by SabreCat** [comment]
@bigsee Sure, should be a pretty simple bit of code cleanup--you're welcome to it!
