### ISSUE TITLE
Intermittent issues with creating a new line in chat - Enter key not working

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12397]
AnneLine reports:

> I've been noticing an intermittent issue few times on web browser version (Windows 10 and chrome right now, but also on Windows 8 and chrome in recent weeks) where when I start to do a new paragraph in chat, the window will NOT allow me to do a 'return' to a new line. Its not consistent, did it a few moments ago abut now it is fine. Solution seems to be a cut and paste of what was typed, a refresh, and then I am good to go. I'm wondering if I'm the only one experiencing this, or if it is a known issue. Anything else I can do to help you identify it? Happened about 5 minutes ago if that is helpful for you, but not an issue in THIS chat window. Weird.

Ceran corroborates:

> I've had that too a few times! I thought it was an issue on my side for some weird reason and not happening to others. Also not being able to make a new line with hitting "enter", or not selecting a user from the dropdown menu when @ing. Refreshing is the only thing that works then.

Nakonana added some info:

> I've encountered the same problem as Ceran and AnneLine using Firefox on Win 10, in case it's relevant. iirc it usually happened when I wrote my reply in a word document and then pasted it into the Habitica text box (but not 100% sure).

Though it's worth noting that it happens to AnneLine while composing in the text box, so it isn't always due to pasting in. It may be related to #11516, but Ceran confirms it can't always be due to that.

**Comment by shanaqui** [comment]
A new report from ptdaisy:

> Not sure if this is considered a bug or not but I was convinced my enter key was having an issue because of this. In the website chat box, when replying to a user, if I use the dropdown list to select a username, the username will appear with a space right after it and if I delete that space that I will not be able to use the enter key to start a new line.
> 
> I think that it is linked to the automatically generated usernames because it doesn't happen if I copy and paste the username or type it out myself.
> 
> In case it is considered a bug, the steps to replicate are:
> 
> select the name using the name finder (it doesn't seem to matter if you select it using a nouse cursor or the keyboard's arrow keys)
> the caret should now be one space away from the name
> use the backspace key to delete the space
> now if you press enter nothing should happen but using other keys should be fine.

**Comment by Alys** [comment]
Another report of this, from @LindyBlues (924376bc-1045-447b-9c3f-4450516fd6c7):

"This doesn't happen every time, but it happens often: when I tag someone in a post, for some reason the "enter" key will not work, so I cannot start a new paragraph."

And from @citrusella (2d6ef231-50b4-4a22-90e7-45eb97147a2c), with mechanics that may help to investigate this:

"... where the dropdown disappears but still disallows pressing enter, generally because a character other than a space (or a few other characters, like commas, maybe periods?) was entered after a @ was typed out but nothing was chosen from the dropdown. For example, if I fully type out a mention and put a parentheses immediately after, i.e. (@alys) then I don't have the ability to press enter until I press space later (or theoretically if I press something else that's viewed as "ending" the mention, i.e. comma or something?)."

**Comment by maryketa** [comment]
Hi! I'm a first-time contributor, can I take a stab at this?

**Comment by CuriousMagpie** [comment]
Absolutely, @maryketa! Be sure to check out the Aspiring Blacksmiths Guild if you get stuck.

**Comment by maryketa** [comment]
Pretty sure I fixed this! I described the changes I made in the pull request, and when I played around with it locally everything worked as expected. I think this also might help with #11516.
