### ISSUE TITLE
Allow users to share their tasks with each other

### ISSUE THREAD

**Issue by ssalbdivad** [HabitRPG/habitica#12414]
### Motivation
For users with an accountability partner or group, the inability to share tasks with other users is a huge obstacle. The alternatives that come to mind are:

- Sending a screenshot of your tasks page
- Sharing your password
- Upgrading to a group plan and tracking everything as a group task

The last is probably closest to being acceptable, but the group interface isn't well suited for this as most of the time, you'd only want to see your own tasks, but the interface would always be cluttered with others.

This was really disappointing for me as a new user who was initially really excited about Habitica but considers the ability to share tasks critical to my ability to continue using it.

### Solution
Add a "Share" button to the tasks page that lets you maintain a list of users with whom you have shared your tasks. Those users can choose to share their tasks back, but are not obligated to do so.

Next to the "Share" button would be a "View Shared" button that would display a list of users who have shared their tasks with you. You can click on the name of one of those users to view their tasks through a read-only version of the existing Tasks interface.

**Comment by paglias** [comment]
Hi @ssalbdivad and thanks for posting this idea, we use Github exclusively for reporting bugs, in case of feature requests those can be suggested using the following Google Form https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform

**Comment by ssalbdivad** [comment]
I added this suggestion to the form and got no response.

If I were to implement it myself, is there a different process I would go through?

**Comment by paglias** [comment]
@ssalbdivad I'll talk with the team and get back to you next week

**Comment by paglias** [comment]
Hi @ssalbdivad currently there are no plans to include such a feature in the Habitica code base, this might change in the future and in that case the team might contact you to discuss the idea more in depth.

Habitica is open source but given the complexity of the product and the fact that it's used in production we cannot include any new feature that is being proposed both to avoid clutter and also because it would make maintaining the feature and related code very burdensome for the team.

Of course you can fork the repo and try to implement it in your own version or implement it as a 3rd party tool using the public Habitica API
