### ISSUE TITLE
"pre-doing" dailies

### ISSUE THREAD

**Issue by Gaelan** [HabitRPG/habitica#1248]
Sometimes, we might have some extra time, or be going on a trip and don't be able to do certain dailies, so it would be nice to mark a daily as done for "tomorrow", then get the Coins/XP/drops immediately and have the daily turn gray (like when you have it set to only repeat on certain days) the next day.

**Comment by wizonesolutions** [comment]
I've experienced/thought this, but it seems like that would be different than what dailies inherently are (which is something that's done daily).

Maybe you could just add a Habit or a Todo and up it/check it off?

**Comment by SabreCat** [comment]
In these circumstances, I usually tick the daily and temporarily remove tomorrow from the list of days the daily is active. What suggestion would you have for the UI on this idea?

**Comment by AndreCaseyScott** [comment]
Honestly, this seems like you just need to "check into the Inn" for the day, since you 'technically' won't be able to do certain dailies. Just checking them off when you didn't or won't be doing them is just cheating yourself. If you check into the inn, you do not lose gold, exp, or streaks. Everything is exactly as it was when you checked in. 

I'm going to close this one, but if I'm missing something, please do reopen it :)
