### ISSUE TITLE
feeding pets food cursor equips and unequips the pet

### ISSUE THREAD

**Issue by Liviathan2** [HabitRPG/habitica#12485]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: c38042bc-cccd-47e6-bf43-981f79e233f4
  * Browser: Firefox
  * OS: Samsung tab a

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Feeding my pets was working fine earlier today,  but then it began picking up the food onto the cursor as normal, yet not feeding it to the pet; it would just use the chocolate bar or meat to equip and unequip the pet, without feeding it.  As such, I  had to stop feeding them.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
Any feedback, questions, or concerns about the [Community Guidelines](https://habitica.com/static/community-guidelines) or any other aspects of Habitica related to the community, chatting, etc can be sent to the staff at admin@habitica.com. You may like to copy your comments and questions about that from this issue into an email.

Bugs can also be reported at that address if you don't wish to accept the Guidelines.  However for this specific bug, you don't need to email since we can handle it here now. Future bugs are probably best put into emails rather than GitHub and then we'll create an issue if one is needed (that's the approach we take in the Report a Bug guild).

If you do wish to email about any other bugs, please put that into a separate email than your comments about accepting the Guidelines as each issue is likely to be handled by a different staff member.

For the feeding bug, can you please reload the website using your browser's refresh button and post here to say if that fixes the problem?

Can you please also tell us if you've installed any browser extensions that may interact with Habitica?

Just so you know, I'm about to adjust the title of this issue to refer to just the pet feeding bug as that will help us search and filter for all bugs related to feeding. This means that emails after this one will come to you with a different Subject. The original title will still be visible in an automatic comment in this issue.

**Comment by Liviathan2** [comment]
I refreshed the website, and it's still having the same problem.  This time it would not feed meat to my griffin.

**Comment by SabreCat** [comment]
Removed the off-topic section of the main post to make it easier to read for anyone investigating the issue!

**Comment by Alys** [comment]
@Liviathan2 which type of Gryphon was it? E.g., Base, Desert, etc

Was there an error message when you tried to feed it?

Can you give us that list of extensions you have installed that may affect Habitica in any way?
