### ISSUE TITLE
Data Export Erroring Out

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitica#12482]
Users report being unable to export data via XML or JSON in #10100. 

Per suggestion from @paglias, the JSON export can be accomplished via this link: https://habitica.com/user/settings/data-export instead of accessing it directly

Previous discussion located at #10100 but as the cause is likely to be different, we are starting with a new issue ticket.

**Comment by SilkAndSlug** [comment]
`{
success: false,
error: "InternalServerError",
message: "An unexpected error occurred."
}`

https://habitica.com/export/userdata.xml

**Comment by benkelaar** [comment]
I can take a stab at this if you don't mind.

**Comment by Alys** [comment]
@benkelaar Thanks very much! Please go ahead.

**Comment by shanaqui** [comment]
Hi @benkelaar! Just the usual check-in to make sure you're still planning to work on this. :) Please reply within seven days to let me know, or I'll mark it as help-wanted again to open it up to other contributors.

**Comment by benkelaar** [comment]
Hiya, yeah been a bit busy.  Also have my son's first birthday coming up this weekend so don't expect to work on it before Tuesday.  But will make sure to look in to it then 👍

**Comment by benkelaar** [comment]
Alright, finally found some time to work my way through all the swallowed exceptions in the unit tests to figure out that the (or at least a) problem here seems to be that the newMessages element in the data export has messages keyed on `uuid`, which means that they would turn into xml tags some of which would start with numbers, which is not allowed.

There is of course several ways to deal with this, I could simply remove the `newMessages` element from the exported xml (easy), but that would make this information no longer available to people using the xml export.

Alternatives would be to either prefix the uuid-keys with underscores, or perhaps simply turn the map into a list (with the id fields present as messageId or something like that).

@paglias Since you worked on the original issue, do you have an opinion about how to best fix this?

**Comment by paglias** [comment]
@benkelaar I'd say that converting this to a list seems like a good idea but in this case, given the feature I'm not sure we care that much about exporting `newMessages` which is a list of groups with unreads messages as part of the data export feature

**Comment by benkelaar** [comment]
Indeed, I was thinking that too.  However, the fix turned out to be fairly trivial.  I'm having lots of trouble running the tests locally though, is that just me?

**Comment by paglias** [comment]
@benkelaar errors specifically for the tests for the data export or for tests in general?

**Comment by benkelaar** [comment]
@paglias For the API unit tests in general.

Something seems to be going wrong with the `dropDatabase` call in `helpers/api-unit.helper.js#afterEach`.  Unless I comment that line out I can only run a single api unit test (It times out on the first invocation of afterEach).

If I do comment it out though tests start failing that apparently depend on an emptied database state.

Then also this error is being obfuscated by what I think might be incorrect error handling in the `mongo.js#before` & `after` methods. I had to rewrite that handling to use promises i.o. the done callback in order to get the right debugging information. 

I notice here ( https://docs.mongodb.com/manual/reference/method/db.dropDatabase/ ) that apparently the locking behaviour of dropDatabase changed recently (Between 4.2.1 & 4.2.2), I'm running Mongo 4.2.8 locally, could that be the reason for the difference in behaviour?

Anyway, I'll see if I can figure it out, but it doesn't have to block this issue being resolved (Since the tests run normally in the github actions).

**Comment by benkelaar** [comment]
@paglias It's not the locking thing, I get the same behaviour when I run 4.2.1 (Would be weird anyway, since locking actually got looser from 4.2.2 onward)

**Comment by paglias** [comment]
@benkelaar what's the exact error that you get?

**Comment by benkelaar** [comment]
So if I run `npm run test:api:unit` I get:

```
  1) "before all" hook
  2) "after all" hook

  0 passing (16s)
  2 failing

  1) "before all" hook:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) "after all" hook:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

Then if I change https://github.com/HabitRPG/habitica/blob/develop/test/helpers/mongo.js#L125-L137 to
```javascript
before(() => {
  mongoose.connection.on('open', err => {
    if (err) return Promise.reject(err);
    return resetHabiticaDB();
  });
});

after(() => mongoose.connection.dropDatabase(err => {
  if (err) return Promise.reject(err);
  return mongoose.connection.close();
}));
```

I get:
```

  analyticsService
    #track
      Amplitude
        ✓ calls out to amplitude
        1) "after each" hook for "calls out to amplitude"


  1 passing (8s)
  1 failing

  1) "after each" hook for "calls out to amplitude":
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

Then if I comment out https://github.com/HabitRPG/habitica/blob/develop/test/helpers/api-unit.helper.js#L16 and either call or remove the done argument all tests run normally but a bunch of them fail (I guess due to unexpected database state).

So the problem seems to be that the dropDatabase call is taking too long, after work tonight I'll see if I can investigate the database lock state.

**Comment by paglias** [comment]
Hmm the unit tests are running fine for me, are your deps up to date? what's the mongoose version?

**Comment by benkelaar** [comment]
I do run `npm install` fairly regularly, I'll try dropping the node_modules directory to see if a clean sheet fixes it.

**Comment by benkelaar** [comment]
Removing node_modules in root and client and re-running `npm install` didn't change the behavior, mongoose version seems to be 5.10.3

**Comment by paglias** [comment]
Sorry about that but I've not been able to replicate, the tests are running fine for me :( Are you using the mongodb process from `npm run mongo:dev` or your own instance?

**Comment by benkelaar** [comment]
@paglias Wow, apparently, that was it.  I had been running mongo off of the official mongo docker container, but when I use the `run-rs` one through `npm run mongo:dev` the tests run normally.  Really weird though, since the docker container I use is the same mongo database version as the one configured for run-rs.  Something under the hood is going wrong, but at least I can run the tests locally again 👍 .
