### ISSUE TITLE
Tasks and Party menu items should be normal links

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12703]
The "Tasks" and "Party" items in the website's navigation menu are not normal links.

This means you can't right-click on them to open them in a new tab.

It also means you can't hover over them to see the URL they'll take you to - you see just the URL of the page you are currently on (screenshot below).

![image](https://user-images.githubusercontent.com/1495809/97128990-825ca480-1789-11eb-9b5b-8d2dae40a628.png)

_Thanks to Nakonana and citrusella for reporting this._

**Comment by J-Sanderson** [comment]
I can take a look at this one if it's still available!

**Comment by Alys** [comment]
@J-Sanderson Thank you! Please go ahead!

**Comment by paglias** [comment]
So I was testing @J-Sanderson 's PR but I can't replicate the issue in the first place. I'm not sure if anything got fixed by some recent update but if this is what I see:

- The links are normal `a` tags
- You can right click on them
- The url is shown correctly

<img width="220" alt="Schermata 2020-11-02 alle 17 20 05" src="https://user-images.githubusercontent.com/589911/97891946-b575d980-1d2f-11eb-91eb-b844968dd166.png">
<img width="482" alt="Schermata 2020-11-02 alle 17 20 18" src="https://user-images.githubusercontent.com/589911/97891951-b73f9d00-1d2f-11eb-985c-bd30aebbc6e6.png">

Is someone able to replicate the bug? If yes I'd need to know the browser you're using.

CC'ing @citrusella since they reported the bug

**Comment by citrusella** [comment]
I noticed the links working in that way instead of the other way a few days ago, but I'd just assumed it'd been deliberately fixed already, not accidentally! o.o

**Comment by paglias** [comment]
Thanks for confirming @citrusella , it was probably a bug in the bootstrap-vue library that we're using and it got fixed there :)
