### ISSUE TITLE
heading level hierachy size issues: plain text displayed as h3 in task titles, h5/h6 larger/bolder than h2

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12763]
As reported by @citrusella :
_"a couple weeks ago, I mentioned some headings being confusing (and heading level 3 specifically being identical to plain text, which was especially confusing--both in messages and in differentiating "header tasks" from other tasks)..._  [https://github.com/HabitRPG/habitica/issues/12704]

_"Now heading level 3 and plain text are still identical on tasks but it's because the plain text on tasks has blown up to and decided to use the same font as level 3 headings. XP Pretty sure this isn't intended because on element inspection it thinks all my tasks are h3... (If it is intended: I think it's both confusing and feels cramped--h3 was the largest header that didn't look unwieldy (read: just way too large and/or kicking text to a second line) with the "header task" titles I've been using, and it makes my non-header tasks feel cramped/like there's less onscreen. And if they look the same then what's the point of having h3 as an option at all?)_

The first two screenshots below show the problem with plain text looking the same as h3 text in a task title. (The markdown used to create them is at the bottom of this post.)

![image](https://user-images.githubusercontent.com/1495809/98351373-53d3a900-2068-11eb-87dd-46bfeb5df432.png)

![image](https://user-images.githubusercontent.com/1495809/98351176-166f1b80-2068-11eb-967e-a860e6ebb6f4.png)

Elsewhere in the site, headings 1 to 4 and plain text look better - examples:

In task notes, headings 1 to 4 and plain text look correct (plain text being smaller than h4):

![image](https://user-images.githubusercontent.com/1495809/98351028-e45db980-2067-11eb-8728-bcd5fdcb6381.png)

I _think_ the headings 1 to 4 and plain text in checklists are more or less correct although maybe the plain text looks a little different to my eye compared to the task note (but I think it's still fine):

![image](https://user-images.githubusercontent.com/1495809/98351136-09522c80-2068-11eb-8858-c9884768bf96.png)

Chat posts are the same as checklists I think (looks fine to me for headings 1 to 4 and plain text):

![image](https://user-images.githubusercontent.com/1495809/98350949-c09a7380-2067-11eb-8a46-290d30a51845.png)

Headings 5 and 6 are still larger throughout. :)

Here's the markdown I used to make all of those screenshots:
```
# h1 heading

## h2 heading

### h3 heading

plain text

#### h4 heading

##### h5 heading

###### h6 heading
```

**Comment by Tressley** [comment]
To note, task titles default to Markdown's h3 type style (plain text) when Markdown is not used. This is how the design was intended to create a default hierarchy. h5 and h6 were never included in the original type scale, but can be included if necessary.

**Comment by citrusella** [comment]
Is that new? It wasn't doing that before. I find it really confusing compared to the previous behavior, when I have h3 headers I included purposely. (And I've seen people in the Tavern slightly confused about it, though I think that's less my specific scenario, more just that the change was different enough as to seem "off" to them--some were just wondering if there was an intended change (maybe it seemed it came out of nowhere?), though I think I remember some feeling like there was something buggy.)

This is what my tasks looked like before (roughly--I've gone into the page source and replaced h3 that I didn't specifically add myself with divs instead) versus now:

![tasks with the not-end-user-intended h3 replaced with a div to simulate what appears to be prior behavior](https://user-images.githubusercontent.com/14182450/98549826-518c6d00-2269-11eb-996d-060eab742a7e.png "A simulation of before") ![tasks with the not-end-user-intended h3 left alone to show what it looks like now](https://user-images.githubusercontent.com/14182450/98549851-5c470200-2269-11eb-8768-47a7adf5e773.png "what it looks like now")

To me it's confusing because there's no difference between h3s *I'm* intending to include versus those *Habitica* is showing because I didn't specify something else. XP (Also, I now have a rough knowledge from doing that, that the smaller p text allows up to three more lines of text onscreen compared to the h3 (as judged by a long chat message I currently have copied to a to do), but that's really just me going "oh interesting" even though it *is* related on some level to the "feels cramped" I included in my original report.)

(Struck out because it's a tangent) ~~On the bright side, diving enough into the source code to get the "before" shot made me realize that it is in fact possible to at least personally style it back to "feels clearer to me" on my end--I hadn't been thinking about the p buried inside and was just like "these are functionally identical, how do I style on this"...~~

**Comment by Tressley** [comment]
The previous behavior was a bug and was recently fixed. If you add a task title without Markdown, it falls back to Markdown's default h3 styling to be consistent with the Markdown type scale. Apologies if that's confusing, but the previous style of plain text task titles was not supposed to exist. 😅

Additionally, "plain text" in various areas is going to look different as it's technically not Markdown. It's going to look different in a task title versus task description versus a chat message. It's increasingly difficult to create a universal set of Markdown that works in each specific use case.
