### ISSUE TITLE
chat posts by others look like yours when avatar images don't load

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12893]
As reported by @SuperSaraA (dbf5390d-6a57-42ad-ae14-af8fd8e570ca) and other players in the past:

"... the random display bug that shows other users posts as if they were me is acting up again. Both in the Tavern chat and also the message before mine here in the Report a bug guild."

She took screenshots and I've copied some representative samples of the bug below. The top post on the first screenshot was written by 
SuperSaraA. All others were written by other players.

It looks like the issue is that sometimes the players' avatar images don't load, and that means the posts aren't pushed over to the right the way that they would be if the avatars were displaying. This makes it look like the posts were written by you, since we're all used to seeing our own posts aligned to the left.

Ideally, any post by a player other than yourself should appear aligned to the right even if their avatar isn't visible.

Note that I would guess it's possible that sometimes the player's own avatar may not load. In that case, the player's own posts should still be aligned to the left. Whatever fix is done for this issue should not cause the player's own posts to bbe right-aligned when their own avatar isn't shown.

SuperSaraA reported that the problem disappeared later, so I would assume that reloading would fix it every time. 

**See the comments below from @veeeeeee and @paglias for the required fix, including the second comment by @paglias after @citrusella noted that the div being missing is the issue.**
**As noted in the post from @citrusella the fix should NOT affect system posts (the ones that have** `"uuid": "system"`**). They deliberately don't have avatars on either side and should stretch all the way across the chat space.**

![image](https://user-images.githubusercontent.com/1495809/102682814-0aa27780-4218-11eb-9aa8-3b1152530a30.png)

![image](https://user-images.githubusercontent.com/1495809/102682822-15f5a300-4218-11eb-85cf-18b0ad3fb6ac.png)

**Comment by Alys** [comment]
The problem disappeared later, so I would assume that reloading would fix it every time.

**Comment by citrusella** [comment]
> SuperSaraA reported that the problem disappeared later, so I would assume that reloading would fix it every time.

If it's anything like whatever made #11223 happen (same effect (no avatar load, probably the avatar node missing entirely?) but not necessarily same cause) then a reload might not *get rid* of it but lessen or change where it happens... but my own observations lately when I've seen it I've usually been having weird connection issues more often than not (but not always--a time or two everything has seemed to be fine)).

This might have little to do with a potential fix, but felt like saying it. XP

Other random thing worth discussing since maybe it could be overlooked: If the cause is a missing avatar node (as in the .card (chat message) is alone inside the chat line's html), then would a fix potentially end up modifying system messages as well (i.e. like quest progress posts in a party, etc.) since they... deliberately?.. completely lack the avatar node? Or would a fix be expected to take that into account and leave it alone somehow?

(I sure am asking a lot of questions for someone who is unlikely to put a fix attempt for this on my plate, if/when it were to go help wanted. XD)

**Comment by veeeeeee** [comment]
Staff suggested fix here is to set the div to have a minimum width of the avatar box (147 pixels? @paglias can confirm). Will adjust tag to help-wanted. Thanks!

**Comment by paglias** [comment]
<img width="311" alt="Schermata 2020-12-22 alle 18 49 05" src="https://user-images.githubusercontent.com/589911/102917984-6eca7300-4486-11eb-82cf-668ce574957a.png">

These are the sizes of the avatar box with padding (but not margin) included

**Comment by Alys** [comment]
I've updated the top post to contain this:

> See the comments below from @veeeeeee and @paglias for the required fix.
> As noted in the post from @citrusella the fix should NOT affect system posts (the ones that have "uuid": "system"). They deliberately don't have avatars on either side and should stretch all the way across the chat space.

**Comment by citrusella** [comment]
Is the suggested fix applying a minimum width to the `.avatar` div? I know in the case of previous times I encountered the issue and actually looked at the page code (i.e. the issue I linked to last time I posted in here), that div was missing entirely (i.e. only the `.card` div exists inside the `.d-flex` div)--if that's the case in the more recently spotted cases of this too, would putting a minimum width on the avatar div actually solve this if the div isn't there at all?

(I personally haven't been able to verify this is how it functions in this case since I haven't encountered the bug since the suggested fix was posted and hadn't looked at how it functioned since the times it was happening the other time--if this is completely irrelevant (either because I'm misidentifying the issue or the fix) then feel free to ignore this pondering.)

Also since I was playing around in the code while doing what I mention in the next paragraph: `.avatar` already has a width of 10% and a minimum width of 7rem--would a min-width of 147px accomplish anything different?

(Also also (because I went investigating after I read "should stretch all the way across"... and this *does* feel irrelevant), incidentally system messages (like users' messages with their avatar missing) actually only take up 90% of the chat space's width... ~~I might have just whipped up a quick userstyle just now that makes chat messages where there's only a `.card` (i.e. system messages) 100% to see what it looks like--which would also make it immediately obvious if I encounter this bug again whether it's caused by an entirely missing avatar div or not.~~)

...I feel like I'm just rambling here but the thought occurred to me back when the suggested fix was posted and didn't go away.

**Comment by paglias** [comment]
@citrusella sorry for the delay, I think the div might not appear at all if an avatar is missing, in that case the idea is to either add a new empty div in place of it or show it anyway with no content

**Comment by citrusella** [comment]
Happened by chance that I noticed this in the Tavern just now (somehow in two separate messages by JohnJSal, no clear connection issues or anything and a reload fixed it); the avatar div is *definitely* missing, just to confirm.

**Comment by benkelaar** [comment]
@paglias What seems to work pretty well for me is to add `margin-left: auto` to chat messages of others.  This does not change the layout if both elements are there, but when the avatar is not loaded, it pushes the message box all the way to the right.  Will fire up a quick merge request for this solution.

**Comment by citrusella** [comment]
Does that also affect system messages? (It looks like it might, which I'm only mentioning because it's been said a fix isn't supposed to.)

**Comment by benkelaar** [comment]
Good question.  I'll test it tonight.  Any idea how I can easily create system messages in a local install?  I guess party spell updates count?

I've thought of what might be a better solution this morning though (move the problematic conditional out of the `v-if` and into a `:class="{ invisible: ... }"`.  That way it will always take up space, just won't be shown.  I think this is more future-proof than correcting it on the card.  Haven't tested it yet though.

**Comment by benkelaar** [comment]
@citrusella @paglias This distinction between system and other users is indeed a problem.  Since the problematic code is probably somewhere in the user cache, but the way the code makes the distinction between system and user messages depends on this same code.  Therefor, any solution based on the setup will leave the spacing the same for system and other user messages.

I think the best solution for this part is to specifically identify system messages, perhaps there's already a property for that.  I'll look into it tonight or perhaps after my run if my son's still sleeping 😁.

**Comment by benkelaar** [comment]
@citrusella  So apparently system messages have `'system'` as uuid, so now that we can identify them like that, the distinction between those modes works well.  Updated the merge request to match.

Thanks a lot for your input, wouldn't have found this angle without it!
