### ISSUE TITLE
Opening and closing task edit modal changes outside elements to draggable=false

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12936]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

citrusella, the serving wench @citrusella (2d6ef231-50b4-4a22-90e7-45eb97147a2c): 

> Opening a task edit screen and then closing it (via save or cancel) applies "draggable=false" to the task-wrapper as well as to any links (a) inside the task title or notes. This doesn't appear to affect the ability to move the task or anything else functionality wise, but it does apply a different cursor to the "sidebar" of the task (where the checkbox is, though not the checkbox itself) and the links that have the "draggable" bit on it (inspecting the element appears to show that it doesn't matter whether the draggable bit is false or not, just that's it's present, though). The "draggable=false" is removed from the affected tasks' HTML upon reload.

**Comment by JohnFitzpatrick44** [comment]
Hello, I'm a first time contributor and wanted to take a look at this. It seems to be a good intro task. Mind if I pick it up?

**Comment by Alys** [comment]
@JohnFitzpatrick44 Thank you, please go ahead! Post here if you have questions or run into trouble!

**Comment by JohnFitzpatrick44** [comment]
It looks like this is due to vuedraggable rather than anything in Habitica's codebase. If you take a look at the demo [here](https://sortablejs.github.io/Vue.Draggable/#/simple), you can recreate the same effect. Each div starts with no draggable property, and one is added and set to true, then to false, when you click or drag one.

There's a couple ways to keep the cursor's appearance consistent, depending on what you want to do here. We could add a workaround to remove the draggable property after dragging, or we could have the tasks default to draggable = false.

**Comment by Alys** [comment]
I'm not sure what would be best from those options. @SabreCat what do you think?

**Comment by beffymaroo** [comment]
@JohnFitzpatrick44 pending an answer from @SabreCat , are you still interested in working on this issue? Please let me know, and I can adjust labels if needed. Thank you!

**Comment by SabreCat** [comment]
If it's causing cursors to behave oddly, I think removing the `draggable` property after we're done with it is the way to go.

**Comment by adamfitzgibbon** [comment]
Hello, I'm going to take a look at this. Looking at the functionality, I think we may want to have them start with the `draggable` property because otherwise we are defaulting to a normal pointer on the sidebars which feels less intuitive. But let me know if you disagree

**Comment by adamfitzgibbon** [comment]
Fixed in #14302
