### ISSUE TITLE
Snowball avatar transformation buff does not appear in Private Messages circle icon

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12941]
As reported by @Nakonana (33bb14bd-814d-40cb-98a4-7b76a752761c) and confirmed by me (Firefox 83 on Ubuntu):

"The snowman avatar in the round-shaped icon in the inbox is not visible on web
Win 10, Firefox 84.0.2, all Habitica related styles disabled."

The same issue does not happen with the other three avatar transformation buffs.

In Nakonana's screenshot below, you can see the red Accent items (earrings I think they are; the website doesn't show their name anywhere). If the avatar isn't wearing accents, all you see is a white circle.

![image](https://user-images.githubusercontent.com/1495809/104114152-ef291900-534c-11eb-9d2f-f06ab593a4b3.png)

The expected behaviour is that you'd see a portion of the avatar as in the example below using the Shiny Seeds transformation buff.

![image](https://user-images.githubusercontent.com/1495809/104114178-226ba800-534d-11eb-8c0f-5878a5834e75.png)

**Comment by JohnFitzpatrick44** [comment]
@Alys Mind if I pick this up?

**Comment by Alys** [comment]
@JohnFitzpatrick44 Thanks! Please go ahead. Post here if you have questions.

**Comment by shanaqui** [comment]
@JohnFitzpatrick44 Hi there! Are you still working on this one? If not, or if you don't reply within a week, we're going to mark this as "help wanted" again to make sure people know it's available to work on. Thanks!

**Comment by citrusella** [comment]
I haven't *confirmed* that I know how to fix this (usually I will straight up try what I think the fix is before I commit to claiming something) but I'm *pretty sure* I know what will fix this, so can I claim it?

(I'm trying to get my computer with a working local install up to date so there's a *small* chance I withdraw this very quickly if I run into an error I can't resolve while updating it, which I only worry is more likely because I dropped it *hard* while trying to bring it in here. 😬 EDIT: All is fine! It's running!)

**Comment by citrusella** [comment]
How can I add snowballs to my inventory (or manually transform the avatar)? Since they're not available right now my local account does not have access to them to test and fix this. (I am about bad enough at sniffing out any "proper" way to make them available that I'm considering figuring out how to make them temporarily show up for purchase within the install and buy them, like that's supposed to be easier. ._. EDIT: I did in fact just end up figuring out how to make the snowballs purchasable off-season by editing the files that dictated whether I was allowed to see and buy it. XP)

**Comment by CuriousMagpie** [comment]
It's all yours, @citrusella!

**Comment by citrusella** [comment]
Cool, I literally *just* fixed it, too. XD Just gotta commit it and open a PR

**Comment by CuriousMagpie** [comment]
Sweet! Thanks!
