### ISSUE TITLE
User requests darker text in player-generated posts, guild descriptions, etc

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12988]
> Could you please make it so that the text that now appears in light gray (things people have posted in guilds, non-header text in tasks) appears in black; or at least in the same dark shade as the text in the Chat text entry box? In the current color, it's quite difficult to read for those of us (such as myself) who don't have perfect eyesight!
> 
> Alternatively, could you at least offer the possibility to change the look of the site to "high contrast" (with the colors/shades I described above) for those of us who want or need it? I hope this is as easy as offering two slightly different CSS scripts that can be toggled by clicking a button...
> 
> (This concerns the website. I'm not using the phone app, so I have no idea what colors, or shades of gray, or what kinds of contrast, are used there.)

I asked for clarification, since the text looks dark enough for me; they replied with this screenshot:

![image](https://user-images.githubusercontent.com/8144640/105362192-7c445b80-5bf2-11eb-9355-277195113fe4.png)

**Comment by Tressley** [comment]
The color of a posted message (#4E4A57/medium-gray) meets WCAG AA and AAA contrast standards. The recommended contrast ratio is at least 4.5:1 and our ratio is 8.6:1. The sidebar non-heading font color (#4E4A57/medium-gray) also meets these standards with a 7.3:1 ratio.

However, the color for the post controls (#878190/light-gray) does not, but that's a known issue that we haven't tackled yet.

You can use WebAIM's contract checker for more information: https://webaim.org/resources/contrastchecker/

As for a "high contrast" version of Habitica, that's a much larger project and not as easy as a second CSS file.

**Comment by Alys** [comment]
I wrote the thing below to post here and then realised it won't reach the person who requested the change. I'll track down their bug report later and email them. I'm posting this here anyway for the benefit of anyone who may find this issue in future.

You may like to try @citrusella's [Habitica WCAG AAA Contrast](https://habitica.fandom.com/wiki/Habitica_WCAG_AAA_Contrast) Stylus/Stylish theme. I don't know if she made enhancements to the text you describe, and it may not help if she stuck strictly to the WCAG guidelines but it's probably worth a try.

**Comment by citrusella** [comment]
So, I saw this issue and was inspired to go looking into my style because there were a few (minor) places I knew I was going to need to mess with contrast anyhow (and one or two places that might have gotten accidental background-and-text-are-almost-the-same-color effects while I was making other changes, though I'm having trouble finding what I saw a few weeks back now, hrm).

I didn't mess with the text of chat messages (like the part the user posts) because it's already AAA (same with sidebar text even though I don't think that was in the original report). My style already had the light gray post controls (@, time, copy, report, delete, like) bumped to AAA and I did the same with task notes today (but that's not yet in the *published* style). The task notes weren't previously tripping Firefox's built-in contrast checker (I had stopped getting alerts for the most part when I ran it last on the task page before today 0_o) but were labeled as AA today so I bumped them up. (I think the person who reported the issue may have been talking about task notes because I think most formatting you can do on task titles will a) still leave it a header, and b) not change its color.)

Sharing this just to clarify what out of the report my CSS style does and doesn't address. XP (And what it might address in the near future.)
