### ISSUE TITLE
Negative experience but no level decrease

### ISSUE THREAD

**Issue by rs4231199** [HabitRPG/habitica#13011]
![image](https://user-images.githubusercontent.com/43215292/106242492-c601f700-622d-11eb-84ab-bdc57804a83a.png)
Negative experience. I checked a grey daily level my level increased and then I unchecked that daily. I thought my level would go down by one but instead I have this negative experience now.

**Comment by Alys** [comment]
It's intentional that a level-up is not reversed when performing any action that causes Experience to become negative. There are some comments about that at https://github.com/HabitRPG/habitrpg/issues/5736#issuecomment-127677025 and below. In brief, we believe it's simpler, more obvious to the players, and less bug-prone to allow negative XP after unticking a task than to reverse a level-up.

If you experience anything else that seems to be a bug, please report it in the Report a Bug guild, which is available from the website's Help menu or from the Guilds list. Issues are logged in GitHub only when a code fix or extended investigation is needed. There's a note about that in the new issue template here as a reminder. :)
