### ISSUE TITLE
inconsistent unlock behaviour for Mystery of Masterclassers quest line quests

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13013]
_This is suggestion-discussion. It's borderline between bug and feature change request, since I believe the current code is behaving as written, but I thought it best to put here. Even if it's closed with a note that the behaviour is intentional, it will be good to have in GitHub so that we can reference it if it's reported again and/or link to it from the wiki's Quests page._

_As reported by @Nakonana (33bb14bd-814d-40cb-98a4-7b76a752761c):_

"Might not be a bug, but it's still a bit funny:

"To purchase the 1st quest of the Mystery of Masterclassers quest line, [Read Between the Lines](https://habitica.fandom.com/wiki/Read_Between_the_Lines) [`lostMasterclasser1`], you have to complete the last parts of the other quest lines. But even if you don't meet the requirements yourself, you can still participate in the Mystery of the Masterclassers quests, if a party mate, who meets the requirements, invites you to those quests. So far, so good and as expected, however after finishing the party mate's Read Between the Lines, you are now able to purchase [Assembling the a'Voidant](https://habitica.fandom.com/wiki/Assembling_the_aVoidant) [`lostMasterclasser2`], but not Read Between the Lines. [screenshot below]

"I would expect that the quests are either all unlocked after I complete them or that they all remain locked until I meet the requirements for the 1st quest. Having only one of them remain locked after completion seems a bit inconsistent."

![image](https://user-images.githubusercontent.com/1495809/106376143-06a07280-63de-11eb-8277-a52cfd796b08.png)

**Comment by JohnJSal** [comment]
I'm not sure if the suggestion-discussion tag means this is only for staff and admins to discuss -- if so I apologize and I won't keep posting, but maybe this will help clarify further discussion anyway.

I'm confused by two things. First off, according to the wiki regarding The Mystery of the Masterclassers questline:

> To unlock the first quest, the other 4 Masterclasser quest lines (Dilatory Distress, Mayhem in Mistiflying, Stoïkalm Calamity, and Terror in the Taskwoods) must all be completed.

To me, this sounds like _all_ parts of each quest line must be completed, not just the last quest in each quest line as Nakonana claims in her post. However, what she said also sounds familiar to me. Getting clarification on this part would also be useful for the wiki, since a more specific statement on what it takes to unlock the first quest in Mystery of the Masterclassers would be helpful. So my first question is, what is the exact criteria for unlocking Mystery of the Masterclassers? Completing _all_ previous quests, or just the last one in each quest chain?

Second, I'm confused by the last statement in her post:

> I would expect that the quests are either all unlocked after I complete them or that they all remain locked until I meet the requirements for the 1st quest. Having only one of them remain locked after completion seems a bit inconsistent.

I don't know what she means by "having only one of them remain locked," because as you can see in the screenshot, _two_ remain locked: Part 1 and Part 4. Part 2 was unlocked by completing Part 1, as she described. My guess is that Part 3 was already unlocked for her because she previously completed Part 2 at some other time. Part 3 would not have unlocked (or at least _should not have_ unlocked) simply from completing Part 1.

It's entirely possible I am misreading or misunderstanding what she's saying, but I feel like maybe she's thinking that completing Part 1 unlocked all the rest (Parts 2-4) and left Part 1 locked, which of course would be weird behavior, but that's not what happened. (Whether completing Part 1 should also _unlock_ Part 1 is another question!)

**Comment by Nakonana** [comment]
@JohnJSal for the first question, that's what the text says when you hover over the quest on the website, iirc. 

For the second question, I completed the parts 1&2 and am currently doing part 3. Once this one is finished, I expect that the 4th part will be unlocked. This means after completing all four parts, the 1st one will be the only one I still won't be able to purchase. 

Hope that clarifies it :)

**Comment by JohnJSal** [comment]
@Nakonana I can't check on the first thing because they are all unlocked for me already, but it might help to clarify that in the wiki if that's the case.

I think I see what you mean for the other thing now. I guess I misunderstood that you were basically talking about how it _will_ be after you've finished Parts 1-4. I agree that it's kind of odd that Part 1 will remain locked even after you've done it, but that's definitely working as intended.

I'll leave it up to the experts to decide if that's how they want it to remain! :)

**Comment by SabreCat** [comment]
I think the simplest and most end-user-comprehensible approach here would be to include the requirements for unlocking quest 1 in the requirements for the later ones. So if Masterclassers I is locked, Masterclassers II-II will also be locked, even if you happen to have done Masterclassers I in a party at some point.

**Comment by ashaindlin** [comment]
> I think the simplest and most end-user-comprehensible approach here would be to include the requirements for unlocking quest 1 in the requirements for the later ones. So if Masterclassers I is locked, Masterclassers II-II will also be locked, even if you happen to have done Masterclassers I in a party at some point.

Can I claim this issue and implement this?

**Comment by Alys** [comment]
@ashaindlin Thank you! I've marked this as in progress for you. Post here if you have any questions.

**Comment by beffymaroo** [comment]
@ashaindlin Are you still working on this issue? Please let me know, and I can adjust labels if needed. Thank you!

**Comment by SabreCat** [comment]
Opening back up for now. If @ashaindlin resumes work, they can reopen the PR, or if someone else comes along first, they may be able to make use of that groundwork!

**Comment by davishuang9** [comment]
FWIW, from a consistency standpoint I would assume we'd want all the quests to behave similarly, something like a quest only unlocks IFF:
- the requirements to unlock the first quest in the quest line is met AND
- the previous quest in the quest line has been completed

Another question is should a quest be unlocked if someone completes it (via someone else in the party), should it be unlocked if they don't meet the requirements to unlock it?

Not sure who makes the 'product' decisions here.. 😛

**Comment by CuriousMagpie** [comment]
Putting this here mainly for my own reference as I work on this issue: 

I was able to duplicate this behavior for every single quest chain in the Masterclasser series. I was also able to duplicate it for the quest chains "Attack of the Mundane" and "Vice the Shadow Wyrm."

![quests-unlocking](https://user-images.githubusercontent.com/78037386/147702599-90ab44c9-9468-4c03-ac8d-3259bea1cac8.png)
