### ISSUE TITLE
Can't Delete Habits or Dailies

### ISSUE THREAD

**Issue by Zian** [HabitRPG/habitica#1307]
Whenever I try to delete a habit or daily, I get the correct alert with the OK/Cancel buttons but when I refresh the page, the deleted item is still there.

Context:
- Firefox 22.0
- Windows 7 x64

**Comment by AndreCaseyScott** [comment]
This is most likely due to the multiple Derby.js bugs we've been experiencing, including issues with the server crashing or disconnecting. The rewrite of HabitRPG on Angular.js should be released soon, if you are still having the issue then, please let us know. 

One thing to try (in case you haven't already) is to refresh the page, wait a minute or so for everything to load (will take longer than you think) and then try deleting the item. If it just sits open in the browser, it will lose the connection to the server without notification. So try immediately after a refresh and hope that helps :) otherwise we're all crossing our fingers with the rewrite in Angular.

**Comment by AndreCaseyScott** [comment]
This #165

**Comment by jamesO-ii** [comment]
I just joined this game/app/project and am experiencing the same thing. Only I can't delete anything -- habits, rewards, to-dos, dailies, anything. Clicking the Delete button just does nothing. No popups, no loading, nothing. And when I refresh the page nothing is deleted... so yeah, nothing happens.

I'd consider this a game-breaking glitch. Because if I can't delete any unwanted dailies, I'm forced to either take the damage continually, or complete them (thus getting unwarranted experience and basically cheating).

I really like the concept with this project, and I want it to flourish. But if something simple like the delete button doesn't perform its only function... then the entire thing becomes unusable and very inaccessible to new users.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
