### ISSUE TITLE
Hatched pet disappearance!

### ISSUE THREAD

**Issue by Somni-** [HabitRPG/habitica#1312]
Exactly what it sounds like - hatched a red bear cub only to have it disappear moments later when I had to refresh the page.

**Comment by AndreCaseyScott** [comment]
This is most likely due to existing bugs with the Derby.js backend. The rewritten site on Angular should be released soon, and is supposed to fix issues like these. #165 is the one that is causes most of this. Make sure you have refresh the page immediately before you check things off. Reduces the likelihood of losing drops. Check out #988, you might be able to get the drop back. no guarantees though. 

going to close this since we have quite a few issues open that reference lost pets. Sorry this happened to you :( and the rewrite should solve these issues.
