### ISSUE TITLE
Not Working In Chrome

### ISSUE THREAD

**Issue by OngOfSC** [HabitRPG/habitica#1314]
So I was trying out HabitRPG, and it worked in Firefox, but in Chrome (where it supposedly works best), it doesn't work for me at all!  There are no warnings/errors in the Chrome Console.

I can check/uncheck tasks, but cannot remove/edit/add them.  This is quite vexing, as I would not want to have to use firefox solely to use HabitRPG.

User ID: 2e8b8240-e6d9-4eff-a907-5b129e3a1735

API ID: 5f95a5ef-d9dd-480e-952b-39d82b3f7773

Browser: Chrome 29.0.1547.41 beta-m
WORKING BROWSER: Firefox 21

**Comment by Senth** [comment]
I'm not sure this is the same issue. I'm using Chrome (28.0.1500.71_p209842). Sometimes HabitRPG just freezes and I cannot interact with it at all. This usually occurs when:

I'm loading the homepage, everything has been loaded but I can still see that the page is loading because of the icon. If do an action during this time, nothing happens, it usually takes 5s before I can use the page, but sometimes it just freezes and I have to refresh the page to do some action, and again I have to wait 5s before I can do something.

**Comment by AndreCaseyScott** [comment]
I've mentioned [in another issue](https://github.com/lefnire/habitrpg/issues/840#issuecomment-20565383) that sometimes it takes up to 2 mins for the page to _fully_ load, where you able to click items and have it register. It is a known issue with the Derby backend, and should be fixed with the Angular.js rewrite to be released soon. 

The only workaround right now is to wait for the page to load completely. This usually means waiting for the activity icon (that shows the page is loading) stops the second time. Yes, I mean it will stop, then do a quick flash to load the async stuff a second time. It sucks, but they're working on it :)

**Comment by OngOfSC** [comment]
Well, ends up I do have errors:

http://take.ms/CXT1I

**Comment by AndreCaseyScott** [comment]
Interesting. @lefnire or @litenull might need to chime in on this one.

First, some questions:
- What URL are you accessing? [habitrpg.com or beta.habitrpg.com]
- If you haven't tried beta.habitrpg.com, try that and see if the errors still occur.
- Have you tried clearing your Browser Cache and such? 
- Do you have any extensions active in Chrome? If so, what are they (they could be interfering with the JS in some way)

**Comment by litenull** [comment]
Definitely extensions. Clean up your cache, disable extensions and try out.

On Thu, Aug 8, 2013 at 11:23 PM, onduhray notifications@github.com wrote:

> Interesting. @lefnire https://github.com/lefnire or @litenullhttps://github.com/litenullmight need to chime in on this one.
> 
> First, some questions:
> - What URL are you accessing? [habitrpg.com or beta.habitrpg.com]
> - If you haven't tried beta.habitrpg.com, try that and see if the
>   errors still occur.
> - Have you tried clearing your Browser Cache and such?
> - Do you have any extensions active in Chrome? If so, what are they
>   (they could be interfering with the JS in some way)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1314#issuecomment-22357411
> .

## 

LP, Tomaž :)

**Comment by OngOfSC** [comment]
Still not working... cleared cache and disabled extensions... still not working.. same errors.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
