### ISSUE TITLE
Streak Bonus

### ISSUE THREAD

**Issue by Gr4ssh0pper** [HabitRPG/habitica#1326]
When no days are selected for a Daily, and the Daily Task is greyed out, it is convenient that I don't lose life if I happen to not complete the Task that day. But a downfall to this, if I have a streak bonus (which I would assume means doing it in a multiple days succession) gives me bonus rewards. The problem is, the streak bonus doesn't go away on days I don't do the Task. If my Streak is at 3 for example, and I didn't do the task in a week, the next time I do it will make my streak 4 days. Which makes no sense to me.

The streak bonus should reset on days that I don't do the task.

**Comment by Nolori** [comment]
It used to be like that, I believe. And I would rather this be up to popular vote, unless the devs really like the idea. Mostly because I have "dailies" that are weekly and really can only be done once a week. Not to mention "dailies" that are daily for about three weeks before I have to take a week off (medical - again, something out of my control).

While I'm not super attached to dailies keeping streaks or not, I still feel like there are benefits to having them keep the streak even when they're greyed-out, mainly because my greyed-out tasks really <i>can't</i> be performed that day.

**Comment by Gr4ssh0pper** [comment]
I just feel like i'm lying to myself when I haven't done a daily in a month and I get awarded a streak bonus. Maybe even an opt-in/out way to do it. I obviously agree with streaks to work when a single day of the week is selected, but when everyday is greyed out the streak should not stay indefinitely.

**Comment by SabreCat** [comment]
Streak is about successfully hitting the daily whenever it's required (i.e., active). If you don't think the streak is deserved, you have a number of options with current functionality: 
1. Enable the daily, so you lose the streak if you don't complete the task on a day.
2. Delete the daily and recreate it to reset the streak. Bit of a hassle.
3. Manually reset the streak to 0 using the Restore Streak advanced option. Probably closest to what you're looking for, if you're conscientious about doing so whenever you miss a day.
4. Use a Habit instead of a Daily to represent what you're encouraging yourself to do. I frequently put notes like "hit only 1/day" in my Habits for things like these.

I do see that there'd be value to having a "reward only" style of Daily, one that you're rewarded for nailing on consecutive days but which doesn't deal damage to you if you miss a day--it just resets the streak. But the above options are pretty flexible!

**Comment by Gr4ssh0pper** [comment]
Thank you, I was not aware of the restore streak advanced option!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
