### ISSUE TITLE
Hover Over Details

### ISSUE THREAD

**Issue by Gr4ssh0pper** [HabitRPG/habitica#1327]
When I add details to a habit/daily/todo/reward. A little discussion bubble will appear beside it. Currently If I want to have a quick view of the details I have added I can either edit the habit or mouse over the discussion bubble.

Generally, when you mouse over a habit the mouse changes into the 4 arrow mover pointer in order to show that I can move the habit around. This makes it very difficult to accurately mouse over the discussion bubble and view the details of my habit. Make the Hover area larger of space I can place the mouse in order for the details to stay up, or only have the mouse change into the 4 arrow pointer when on the left half of the habit.

Something needs to change here, it is highly frustrating as is.

**Comment by SabreCat** [comment]
Is #399 or #1118 what you're describing?

**Comment by Gr4ssh0pper** [comment]
I'd say its more similar to #1118 . Very hard to be able to point my mouse in a way to actually let the description bubble show up and stay so I can read it. As in #1118 , most of my habits/dailies/todos have descriptions so I know whether I should be able to check it off or not. Some descriptions longer than others. But still, the area where I have to place my mouse has to be so accurate and spot on to actually be able to open the damn bubble that it drives me nuts. And once I finally do get the sweet spot for the hover description bubble to open, the bubble itself takes the place of where my mouse was and closes the bubble since its no longer in the 'sweet spot'

Not to mention, why is the entire field of mousing over a habit/daily/todo in the form of the 4 arrow pointer (I get it lets the user know that the habit is able to be selected to be drag moved), but it makes it a lot harder to pinpoint where i'm actually clicking with such a ridiculous pointer. /endrant

**Comment by AndreCaseyScott** [comment]
There are definitely some accessibility concerns that will be looked at after the rewrite. One of which will be to make sure that the description bubble and things like it are wrapped correctly so this doesn't happen. I'm sure this is being caused by the link being wrapped weird. There are issues with the hover at the moment, where the nice black bubbles don't load, and generally take a long time to load tooltips. Which makes hunting through the inventory a pain (due to the #1274 update), especially since the inv isn't sorted.

**Comment by paglias** [comment]
This should be revisted after sorting is re-implemented
