### ISSUE TITLE
Notification about reaching drop cap appears erroneously when logging in to web after using mobile

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#13275]
User report: "Sometimes, when I've been using the mobile app for days instead of the web, when I then log onto the web client, I get a notification that I've reached my daily drop cap when I haven't yet reached it for the current day."

User is @emwriter (42a0f951-ce2c-43cc-ab58-acd2e2f6cb0a).

**Comment by Alys** [comment]
For anyone working on this, to get a drop cap notification, you need to not have an active subscription and you need to have this in your account:
```
"_ABtests": {
	"dropCapNotif": "drop-cap-notif-enabled"
},
```

When you reach your drop cap, you will then see this in your notifications array:
```
{
	"type": "DROP_CAP_REACHED",
	"data": {
	"message": "You found all items for the day!",
	"items": 18
}
```

I think the current behaviour for that notification is that it stays in your notifications until you dismiss it, and since the mobile apps don't support that notification, you can only dismiss it on the website (leading to the behaviour reported by the user, when they hadn't used the website for several days).

I guess maybe one possible fix would be to have that notification automatically removed by cron each day? Cron's already pretty full of actions it needs to take though.

**Comment by SabreCat** [comment]
We're no longer running this A/B test, so users shouldn't be seeing this notification any more. I've sent commit 0480681006afc27a33a92f61e9f7fecc8a8d5b5d up to `develop` to clean out some old related code, but this issue ticket has already been fixed.
