### ISSUE TITLE
Profile links generated from @-mentions open in new tab

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#13276]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If you mention a user with the @ feature in chat, the resulting link opens the standalone profile page in a new tab, instead of the modal profile view you get when e.g. clicking a user's name at the top of a chat message they posted. We should be continuing to leverage the modal in this case!

Originally reported in the bug guild by @citrusella!

**Comment by Helcostr** [comment]
All old mentions are fine? It's only affecting the new chat?

**Comment by citrusella** [comment]
I noticed that, too (after my initial report), but I didn't look into it enough to be sure about saying "maybe this came with the change from relative links to absolute for some reason". (@ links were changed to absolute so that they don't break in the apps and third party tools.)

**Comment by Miciaha** [comment]
Can I take this on?

**Comment by Rovetown** [comment]
This also applies to links (like the link to a guild), it also opens up a new tab

**Comment by Alys** [comment]
@Rovetown That's intentional for some links, and may be a bug for others but could be caused by a different bug than for this issue. Can you please post to the Report a Bug guild to describe which link(s) have that problem and in which part of Habitica you see those links? You can reach that guild through the Help menu on the website (or from the Guilds area, but the Help menu is fastest).

**Comment by Alys** [comment]
@Miciaha I'm so sorry, we never replied to your request to work on this! :( Are you still interested?

**Comment by Lyqst** [comment]
If @Miciaha is not working on this, I'll take a shot

**Comment by Alys** [comment]
@Lyqst Thanks! Please go ahead.

**Comment by Lyqst** [comment]
This is due to the change to absolute links, when adding the event listener it is searching for links that start with '/profile/':

```javascript
if (links[i].getAttribute('href').startsWith('/profile/')) {
  links[i].onclick = ev => {
    ev.preventDefault();
    this.$router.push({ path: link.getAttribute('href') });
  };
}
```

If we only change `startsWith` to `includes` it would break cause it would be passing an absolute path to the router, so we also need to address that, changing `link.getAttribue('href')` to `link.pathname`:
```javascript
if (links[i].getAttribute('href').includes('/profile/')) {
  links[i].onclick = ev => {
    ev.preventDefault();
    this.$router.push({ path: link.pathname });
  };
}
```
A small issue with this change is that it will break on IE, since in that browser [pathname is returned without a leading slash](https://developer.mozilla.org/en-US/docs/Web/API/Location/pathname).

**Comment by SabreCat** [comment]
@Lyqst Generally we don't prioritize IE compatibility, but it depends how bad the break is--profile links not working at all in IE could be a nuisance. Can we catch and handle it if the user is on IE?

**Comment by Lyqst** [comment]
Ok, I think this should do it:

```javascript
let link = links[i].pathname;

// Internet Explorer does not provide the leading slash character in the pathname
link = link.charAt(0) === '/' ? link : '/' + link;

if (link.startsWith('/profile/')) {
  links[i].onclick = ev => {
    ev.preventDefault();
    this.$router.push({ path: link });
  };
}
```
Also realized that since we are extracting the link with the pathname property, we can just keep using the startWith('/profile/') function on it, instead of the include one on the whole absolute link.
