### ISSUE TITLE
Adding Habitica API to AutoWeb/Tasker / Authorization type?

### ISSUE THREAD

**Issue by zemmyang** [HabitRPG/habitica#13464]
I'm trying to follow [this tutorial](https://joaoapps.com/autoweb/adding-web-services/) for adding a web service API to Tasker using AutoWeb, but I can't seem to make a request, I get "unauthorized" error back at me. I used the username/password authentication, but I'm not sure if that's the correct one to use in Habitica's case. If not, which is it?

**Comment by majestic-owl448** [comment]
the habitica's API need your UUID and API Token that you can find in the settings of your account, maybe that's why it doesn't work?

**Comment by zemmyang** [comment]
> the habitica's API need your UUID and API Token that you can find in the settings of your account, maybe that's why it doesn't work?

thanks for the response.

i am using the UUID and API token in the username/password fields, but that's what's not working. the guide suggests "
To find out what type of authorization an API needs, search somewhere on the API website for details about authentication." but I'm not sure where to find this for Habitica's case.

**Comment by majestic-owl448** [comment]
I would suggest the Aspiring Comrades guild, there is where people creating third party tools hang out

**Comment by citrusella** [comment]
Since it's been two weeks and I don't think this has come to the guild yet and I couldn't resist answering:

https://habitica.fandom.com/wiki/Application_Programming_Interface#Using_the_API

Don't use the authentication options provided by AutoWeb at all. I don't think any of them will work for Habitica's case, though I may be wrong. (The way the secret key one works gets the closest (it sends the key as both a query and a header) but it only accepts one field for that that kind of authentication and Habitica requires 2-3 for commands that require authentication.)

You need to add header input fields into AutoWeb with keys of x-api-user and x-api-key (and x-client). I manually added these to every single action I have in my own AutoWeb service for Habitica but I probably could have put them in as default parameters... oops...

This doesn't allow you to safeguard your own information as cleanly but it's what I know will work from trial and error.

**Comment by zemmyang** [comment]
Ah, I forgot to reply that I did ask in the guild and got a response. 

Basically, I gave up on AutoWeb and ended up adding a function to [the old Habitica Tasker javacscript code](https://github.com/goldfndr/tasker-habitrpg) to do what I wanted. It worked in the end, but it took a lot of work.
