### ISSUE TITLE
Tavern "Rest in the Inn" message makes 4 Resources links unclickable when half-screened in 1920x1080

### ISSUE THREAD

**Issue by zeredek** [HabitRPG/habitica#1350]
Browser: Firefox
User ID: dd427ec0-b77e-42ec-8a33-4d00483666f1
No javascript errors occured, as far as I can tell.
I use the Windows Classic theme for my computer.
![untitled](https://f.cloud.github.com/assets/5265186/989882/897aae38-091d-11e3-9c9a-c33c4b0bc2ac.png)

**Comment by harningt** [comment]
Browser: Chrome
User ID: e9794762-db16-438b-b920-5e468f30e72e
I also see this - this looks to be a styling issue to do with the message from "Daniel". I experience this "unclickability" for any text to the left of the message which changes at varying widths due to word-wrap.

Looking at the elements - it looks that the table immediately within the first "tavern-pane" div is acting as a box overlapping the link list which - while only containing a div w/ "NPC-Daniel" (which itself is contained) the height for the text in the message box is causing the entire table row to expand.

Not quite sure how I'd solve this issue w/o affecting page look... trying to play with the z-index of the table and divs doesn't appear to do anything...

**Comment by Shaners** [comment]
Maybe we can just add click to kill that popover plus move the green button above Daniel.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by wc8** [comment]
Resources are covering Inn button, after a stay (check in, check out). You can just barely click the top of the green button, but you can't read it. Fluid (Safari based browser)
In Chrome, the button is completely hidden.

**Comment by paglias** [comment]
@wc8 which resolution do you have? For me the resources are covering the npc not the opposite:
![schermata del 2013-09-11 15 43 58](https://f.cloud.github.com/assets/589911/1123044/61c47950-1ae8-11e3-9167-f27e79564dbc.png)

This is probably happening only on phones and really small windows

**Comment by paglias** [comment]
Only small-to-medium windows on phones everything is stacked so no problem

**Comment by lefnire** [comment]
probably because i'm using an inline bootstrap modal. I'll give this a second gander when we're looking at BS3 upgrade, because BS3 has "Panels" for just this thing (which will handle responsive layout better)

**Comment by wc8** [comment]
I think this is resolved, no?

**Comment by lefnire** [comment]
Alas, http://gyazo.com/078c0be70300f5d202973ed6d22675e5 . We're not going
to deal with this until our Bootstrap 3 upgrade though

**Comment by deilann** [comment]
On my Nook Tablet, using Puffin, the inn button is entirely hidden under resources. There is no way for me to further zoom out and fix the issue. However, if I do manage to click the button elsewhere, it pushes resources down so I can see it.

**Comment by wc8** [comment]
FYI: I think this might be fixed with Bootstrap 3 (beta site).
So far tested Firefox & Chrome.

**Comment by deilann** [comment]
it is for me as well. Doesn't get covered up at any zoom.

**Comment by wc8** [comment]
@lefnire should we wait until #2636 reaches production site before closing this thread?
