### ISSUE TITLE
Gamebreaking: Can't complete dailies or todos, account seemingly stuck in time

### ISSUE THREAD

**Issue by AnonyMoses** [HabitRPG/habitica#1352]
Firstly I'd like to say I've been using Habit for about 7+ months now, and I love it. Yet there have been some crazy bugs. This is one of the worst so far.

So I am using Chrome, and I was able to check off dailies such as "Breakfast" and "Wake up at alarm" this morning. Due to the whole time zone error my character has 3hp because apparently hardly anything that was checked off stuck. 

Now every time I try to check off a daily or a todo, it shows an increase in xp and gp, yet if I check something else off it resets and counts the xp only for that new thing I selected. I tried to restore my character's health to 50 since it is crucially near dying, yet as soon as I checked something off...I'm back at 3hp again. So I don't entirely know what is going on. 

My user ID is 9708b42d-d9df-4d54-9e40-fe8ae6b71f5b.

**Comment by lefnire** [comment]
My initial thought is https://github.com/HabitRPG/habitrpg-mobile/issues/73 . The issue there though was usage of the API - mobile app, chrome extension, Anki, RTM, etc. However, that cron-on-api bit has been disabled as of early today. When was the last time this happened to you? If it was any time in the last 6h, then it's in fact something in the current habitrpg-shared/algos.coffee#cron rather than anything in the API, or any sort of timezone issues

**Comment by AnonyMoses** [comment]
It seems to be working now. The error was occurring in the past six hours, but we shall see if it arises again. Thank you and I'll comment again if it pops up again.

**Comment by lefnire** [comment]
Ok, this should be fixed as of the rewrit
