### ISSUE TITLE
Stealth can be cast from mobile app and then on website

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13616]
[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: ba175c69-7edc-43e9-8c02-141895074732 
  * OS: Windows 10
  * mobile OS: Android

### Description
As a rogue I cast “stealth” daily to minimise the damage I receive.  If I do so from my phone, it will only let me once, saying that casting again would make no difference.  If I then also access Habitica from the web page I can cast stealth a second time – costing me the mana but giving me no benefit.  Interestingly if I did it the other way around, web page first then trying from the phone, I wouldn’t be able to.

### Notes
We're working on replicating this issue.

**Comment by KrSkander** [comment]
@CuriousMagpie I'll try to look into this issue

**Comment by CuriousMagpie** [comment]
@KrSkander Sure thing! If you run into any problems, the [Aspiring Blacksmiths Guild](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) is a good place for help.

**Comment by Alys** [comment]
In the Aspiring Blacksmith's guild, @Sythh asked a question about replicating this, and I'm putting my answer here so that all the information about this issue is stored in one place.

The way I'd expect the bug to work is below but I have not tested it myself.

1. Log in to your account on the website.
1. Log in to your account on the mobile app.
1. Use Stealth on mobile. Use it multiple times if needed to be sure that all your Dailies are stealthed - i.e., use it until you see the message saying that casting it again would make no difference.
1. Sync on the app - NOT on the website! This is to ensure that the app is showing you your latest stats from the server.
1. Make a note of your total remaining mana shown by the app.
1. If your total mana is less than the amount required to cast Stealth again, use [Fix Character Values](http://habitica.fandom.com/wiki/Fix_Character_Values) **on the app** (not on the website) to give yourself more mana. Sync again on the app (not website) and record the new total mana.
1. Switch back to the website and do NOT sync or reload - that's important.
1. Use Stealth on the website. If this issue is correct, it will let you do that even though all your Dailies are already Stealthed. However, I suspect it may just be on the client-side that Stealth is used, not on the server. To confirm this:
1. Sync on the website (or reload using your browser's refresh button). Take note of your mana total **on the website AFTER syncing**. I predict that it will be the same as the total you recorded from the mobile app, meaning that Stealth was not actually cast again on your account. If my prediction is correct, the only fix required for this issue is client-side, but that might be difficult to arrange since the client (the website) won't know that all your Dailies have been stealthed until it has been synced.
1. If my prediction is wrong and your mana on the website has been decreased by the amount required to cast Stealth, then it probably means that the API needs to be adjusted - Stealth is not correctly identifying when it no longer needs to be cast. It might instead mean that something went wrong with Stealth on the mobile app. That can be assessed further depending on what you find.

**Comment by KrSkander** [comment]
Hey @CuriousMagpie, I managed to replicate the issue and deducted that the API works fine, this issue is only related to the frontend and is a display sync problem as @Alys predicted. Btw @Alys  it was me ,under the Nickname 'Syth' in the Aspiring Blacksmith's guild, who asked about this ^^

In order to replicate this issue, I hosted the latest version of Habitica locally and ran the latest mobileapp version on my local network using android studio, following both the guides provided for blacksmiths.
I conducted **3 Tests** : 

### **1.  Stealth all dailies (3 dailies) on mobile app then stealth it on webapp :** 

- Used stealth x2 ( Mana 130 --> 40). 
- Refresh mana (40 --> 130)
- Used stealth x2 again on mobile, as I have three dailies it casted 1 more time before popping the "Using this skill won't have any additional effect." alert (mana 130 --> 85, The webapp still has 130)


![MobileWeb 2](https://user-images.githubusercontent.com/57879188/164353206-fbc5fa46-a2d1-444b-9d0c-9d3d641f020d.jpg)

![WebMobile 1](https://user-images.githubusercontent.com/57879188/164353202-399305e4-8012-4683-abd7-909c3c53e787.jpg)

**This is the current stealth count in my character stats after executing 4 stealth on mobile**

![Test1 Stats ](https://user-images.githubusercontent.com/57879188/164352908-f9caf2ab-c267-4825-8a5e-9773994224d5.jpg)

- Casted stealth x2 on webapp with mana at max still : the spell drained mana ( 130 --> 40) but it had no effect as I got the notification "Using this skill won't have any additional effect." twice
Noting that stealth isn't locked it's still usable if I had more mana !

![WebMobile 2](https://user-images.githubusercontent.com/57879188/164353345-b81d286d-60a7-49b5-80c3-53e2b9049668.jpg)

- Refreshed the webapp which locked the stealth spell, so I can't use it again and synced my mana to the mobile app (40 --> 85)

**Noting that the stats in the database are still the same "stealth = 3"**

**Comment by KrSkander** [comment]
### **2.  Stealth 2 dailies out of 3 on mobile app then one on webapp without refreshing :**

- Used Stealth x2 (mana 130 --> 40 )  

![Test2 Mobileweb1](https://user-images.githubusercontent.com/57879188/164356116-a88c357f-4d92-4965-ba34-eaebfa2897de.jpg)

Stats in the DB after mobile cast : 

![Test2 Stats after first cast](https://user-images.githubusercontent.com/57879188/164356019-5ec67c18-1a63-468b-9ccd-a7103385bdb8.jpg)

- Used stealth x2 on web app as I still have 130 mana without refreshing; the spell got casted twice without telling me that it won't have any effect however checking the stealth attribute in the database it's still "stealth = 2" even though I have 3 dailies.


![Test2 WebMobile1](https://user-images.githubusercontent.com/57879188/164356205-f7661bef-b23a-4038-9fc2-3a4694657193.jpg)

Stats at the end of the test : 

![Test2 Stats after web cast](https://user-images.githubusercontent.com/57879188/164356812-f8d8c018-cd02-4ed6-a36f-94829d19419b.jpg)

### **==> this means the two stealth uses on the web app had no effect**

**Comment by KrSkander** [comment]
### **3.  Stealth 1 daily  out of 3on mobile app then stealth the 2 left on the webapp without refreshing :**

- Used stealth x1 on mobile (mana 130 --> 85)

![Test3 Mobile stealth x1](https://user-images.githubusercontent.com/57879188/164356893-b90c2d9d-d8a6-4a10-9e2a-1f62d3f3146d.jpg)


![Test3 stats after MobileCast](https://user-images.githubusercontent.com/57879188/164356924-4f64cc8f-1693-4d30-8740-61155a229f57.jpg)

- Used stealth x2 on webapp (130 --> 40), I got a "no mana" popup on second cast, only the first cast was counted as it should be cause in reality we have 85 mana, so as the second screenshots show; the stealth count in the stats "stealth = 2"

 ![Test3 Cast Webapp x2](https://user-images.githubusercontent.com/57879188/164356979-c4a3ee06-ad31-4c5e-808e-05c5a0c805da.jpg)

![Test 3 Stats after finals cast](https://user-images.githubusercontent.com/57879188/164357036-94f87bfb-8ce3-46c3-99a6-7898f478542b.jpg)

- Refreshed web app; mana still at 40
- Refreshed mobile app; (mana 85 --> 40) 
(Casting the third stealth on the mobile app will give us the same result)

### **==> The second stealth cast on the webapp should've not been allowed, however using it won't stealth any dailies**

**Comment by CuriousMagpie** [comment]
Thanks for your work on this, @KrSkander! It sounds like the problem here is essentially not syncing to the server when you switch from mobile to web and back again. And on that note--I'm going to close this issue!
