### ISSUE TITLE
Monthly Start Date is not correct

### ISSUE THREAD

**Issue by FirstLoveLife** [HabitRPG/habitica#13666]
* UUID: ef3f1e96-dcbd-4036-a8cd-3d5cb10b4edd
  * Browser: chrome
  * OS: arch linux

### Description
My timezone is utc+8, it should be friday now as the system calender shows, but habitica recongize it as saturday.
![image](https://user-images.githubusercontent.com/37442588/144609886-77ad3031-8ccc-4ea7-906e-4085a884c9f8.png)
![image](https://user-images.githubusercontent.com/37442588/144609964-2577dcdd-ac9a-4aa5-99d5-afb410450d27.png)
![image](https://user-images.githubusercontent.com/37442588/144610010-06b314cc-4284-43e7-b6e5-035a188abc2f.png)

**Comment by FirstLoveLife** [comment]
@CuriousMagpie Hi, i think this is not a minor issue, because it mess up my monthly tasks' due day

**Comment by Alys** [comment]
@FirstLoveLife Can you please tell us this extra information to help us investigate:

1. What time of day was it in your time zone when you noticed this?
1. Had you reloaded the website since the previous day? Or had you opened the website in a new tab on the current day?
1. Was it with a Daily you had just created? 
   * Or a Daily you had created in the past? If you had created it in the past, what was the Start Date set to before you clicked in to the Edit screen?
 1. Is it reproducable with other Dailies at the same time of day?
 1. Is it reproducable with other Dailies at different times of day, and if so can you tell us what other times that the bug does or does not occur for?
 
 ---
 
 For my own testing, at UTC+10 (and I've confirmed Habitica has the correct time zone for me), the bug did not occur with these details:
  
 1. At 15:30
 1. Website opened in a new tab at that time.
 1. A Daily just created did **not** have this bug (the Start Date was the current day).
 1. Not reproducable at the same time with other Dailies just created.
 1. Have not yet tried to reproduce at other times.
 
 Also:
 1. At 15:30
 1. Website opened in a new tab at that time.
 1. A Daily created in the past did **not** have this bug:
    * the Start Date was set in the past to 2021-12-01
    * that date was correctly highlighted in purple when I went into the calendar picker
    * the current date was correctly highlighted in grey when I went into the calendar picker
 1. Not reproducable at the same time with other Dailies created in the past (the current date was always correctly highlighted in grey when I moved to the current month in the calendar picker).
 1. Have not yet tried to reproduce at other times.
   
Firefox 94.0 (64-bit), "Mozilla Firefox for Ubuntu canonical - 1.0"
Ubuntu 20.04.3 LTS arch ~ x86_64

**Comment by CuriousMagpie** [comment]
@FirstLoveLife Are you still having this issue or did @Alys's instructions help you get it resolved?

**Comment by FirstLoveLife** [comment]
Sorry for late reply, I will verify it tonight

> @FirstLoveLife Are you still having this issue or did @Alys's instructions help you get it resolved?

**Comment by FirstLoveLife** [comment]
Sorry, this issue doesn't appear anymore.

**Comment by CuriousMagpie** [comment]
Thanks for letting us know!

**Comment by pleshevskiy** [comment]
![image](https://user-images.githubusercontent.com/7839004/146453189-5732a817-5ef3-48ab-8229-ee9f72f13a96.png)

@CuriousMagpie  I've reproduced it.

I opened the Habitica site on the 16th and decided to change the task date after midnight on the 17th. If you reload the page, the date will be correct. To fix the error, you need to get the client date before opening the modal.

**Comment by FirstLoveLife** [comment]
![image](https://user-images.githubusercontent.com/37442588/147578389-56fa1a95-86da-4a39-866d-2e370ba8ecfd.png)

![image](https://user-images.githubusercontent.com/37442588/147578435-29feb2d3-60b8-440d-9266-48004d4bf6ef.png)


reproduced again

**Comment by CuriousMagpie** [comment]
@FirstLoveLife Can you please describe what you are doing when you generate these screenshots? Without context, they aren't as helpful as they could be. Please also keep in mind that we are a small team and that minor issues such as this one can take some time to resolve.

**Comment by SabreCat** [comment]
@FirstLoveLife Agreed, I think we need more explanation before we can address this--

is it just that clicking "Today" goes to the wrong date?
is the task coming due on the wrong day?

what is it you're seeing that suggests "Habitica recognizes it as Saturday"?

**Comment by FirstLoveLife** [comment]
@CuriousMagpie I'm sorry that description was missing. 

@SabreCat 
> is it just that clicking "Today" goes to the wrong date?

I hope to change the monthly task's starting day.

> is the task coming due on the wrong day?

From my latest screenshot above, habitica thinks 2021/12/28 is Sunday, but it should be Tuesday actually.

**Comment by SabreCat** [comment]
> From my latest screenshot above, habitica thinks 2021/12/28 is Sunday, but it should be Tuesday actually.

The first screenshot shows Sunday, November 28. The second screenshot shows Tuesday, December 28.

**Comment by SabreCat** [comment]
The first screenshot shows November 28, which is a Sunday. The second one shows December 28, a Tuesday. Those are both correct. What am I missing..?

And the screenshot in your first post is July.

**Comment by FirstLoveLife** [comment]
@SabreCat That's my bad. I didn't notice they are different months. Sorry for wasting your time.

**Comment by pleshevskiy** [comment]
@SabreCat @CuriousMagpie I described above with screenshots of how I reproduce this error. Why did my comment go unheeded?

**Comment by SabreCat** [comment]
@pleshevskiy That's a different issue than the original poster described.

If you think you've found a bug, please use the bug reporting feature within the app or on the website. (We're likely to lock GitHub ticket creation to Habitica staff and contractors only, soon!)
