### ISSUE TITLE
Lost an egg tonight!

### ISSUE THREAD

**Issue by TheProjectShaman** [HabitRPG/habitica#1373]
Hi Team,

First of all let me say THANK YOU for such an awesome and rewarding experience! I just discovered HabitRPG a few days ago and it's already a MAJOR part of my families day! :)

Unfortunately the server crashed tonight at midnight while my wife was dropped a dragon egg in her account (she was using the habitrpg.com server an not beta.habitrpg.com). We took a screengrab to show our kids (we were very excited!). Not only did she loose her Level 4 status (after checking her dailies and habits off) but the egg is gone now too. :(

Can you hook us up with the egg so we can show our kiddos? 

Thanks so much in advance!

The user ID is: ab74a632-fc82-4da7-a269-182ba9c0f6f5

You rock!

**Comment by Shaners** [comment]
Aw, sorry to hear that. Tyler won't you please think of the children!

**Comment by fragmental** [comment]
Hey, @TheProjectShaman  I have a question, how many people in your household play habitrpg?  Do they all have their own devices or do they share?

**Comment by lefnire** [comment]
@TheProjectShaman I added tokens your account so you can buy back the eggs & potions

**Comment by TheProjectShaman** [comment]
Thanks so much @lefnire! You are truly all sorts of awesome. :)

@fragmental We just got started so the kids (5 and 6) are watching Mommy and Daddy to learn it all, and having them click the interface etc. We will be starting them next week, and will be with them daily in a web browser. Mom and Dad are using mobile phones mainly (I use a Samsung S3, and my wife uses an iPhone 5).

I love Habit RPG!!! :)

Thank you!

**Comment by lefnire** [comment]
Aw, thanks Shaman! Keep an eye out for the rewrite, it's coming soon and
will smooth out the bugs.

**Comment by fragmental** [comment]
@TheProjectShaman Cool.  How were you planning on managing multiple log-ins?

I ask because I was thinking about families who, for example, have 2 adults and 2 or 3 kids all using the same family computer and how all of them could manage accounts(My brother's and systems family specifically).  With two it would be easy to just use firefox for one kid and chrome for another without logging in and out.  Four or five is a little different though.  Some families might want to log out to prevent tampering, anyway.  Some families might have user accounts setup in the OS, which would allow individual settings system wide.  

I know there are plans to implement multiple user systems later.

edit: multiplier = multi-user

**Comment by lefnire** [comment]
Manager accounts! https://trello.com/c/kGFZUYH8/247-manager-accounts-teachers-project-managers-ieps

**Comment by TheProjectShaman** [comment]
@lefnire I just voted for Manager accounts :) As a newly minted homeschooling family that is using gamification to deliver curriculum to our kiddos and make education super engaging, this would be BRILLIANT! :)

@fragmental Currently, we are using 1Password (Mac) to hold accounts, and using a single browser (logged in by us, the parents).

**Comment by fragmental** [comment]
@TheProjectShaman so does each kid have their user account or do they share one?

**Comment by TheProjectShaman** [comment]
@fragmental Each kid has their own account, but we have a family 'Group' so we can see each other. :)

Manager accounts would make life easier of course, but for now we use multi-browsers (or single browser with 1Password to switch).
