### ISSUE TITLE
Fix Character Values should not allow operands

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13774]
### Description
User email:

> I wanted to reach out about the fact that if you try to fix a value by adding a certain amount to it directly (ex 11+ 5 health) then the game will assume that the value should be zero, and will kill you, but you don’t actually die, you just enter a glitched state where whenever you reload the game you get the death screen and you have zero health. 

I was able to replicate this in development:

Added "+ 25" to the health field:
![Screen Shot 2022-01-20 at 12 27 21 PM](https://user-images.githubusercontent.com/78037386/150390699-46f5d02c-bf91-45d6-a99e-ed96d077418c.png)

You died screen:
![Screen Shot 2022-01-20 at 12 27 44 PM](https://user-images.githubusercontent.com/78037386/150390783-f232f8a9-30ef-4e36-9b20-6fa326745843.png)

If you X out of the modal without taking the option to refill your health, then your character appears like this on screen--you lose a piece of equipment but you do not lose your gold when this happens:
![Screen Shot 2022-01-20 at 12 28 00 PM](https://user-images.githubusercontent.com/78037386/150391001-b92d592f-592f-4111-b8ef-473289948b44.png)

I also tested this on the other fields in FCV and was able to wipe out my experience, gold, mana, and 21 day streaks. I was not able to use operands in the level field.

The fix here is probably some smarter validation that disallows operands in all fields, not just level.

**Comment by vanathi-g** [comment]
Hey, I'd like to work on this issue!

**Comment by CuriousMagpie** [comment]
@vanathi-g Go forth and slay this bug!

**Comment by vanathi-g** [comment]
Hi @CuriousMagpie , while I add validation for not allowing operands, shall I also add validation to ensure the level and streaks fields are positive integers?

**Comment by CuriousMagpie** [comment]
@vanathi-g That would be a great upgrade and as long as you're in there...

**Comment by Alys** [comment]
Regarding this from @vanathi-g's closed PR:

> hp, exp, gp and mp are decimal values >= 0

It's possible for some of those values to be negative due to normal game play:
- HP can be negative if enough damage is done to a player to reduce their Health below zero (the next time the player syncs or crons, their avatar will die but HP will be negative until then).
- Exp can be negative if you complete a To Do or Daily and level up, and then uncomplete that task (or any other task) - e.g., if you realise that you completed a task by accident. There's details at https://github.com/HabitRPG/habitica/issues/13011 and in the older issue that its comment refers to but in brief, it's intentional that Exp goes negative rather than trying to reverse the level-up because reversing all the effects of a level-up would be quite complicated in some cases.
- GP and MP - I _think_ they can't be negative in normal gameplay.

My view is that negative values for HP and Exp should be allowed in Fix Character Values since they are legitimate values that can be obtained in other ways.

**Comment by vanathi-g** [comment]
Alright, I'll make the necessary changes! Thanks @Alys
