### ISSUE TITLE
API docs need to updated to reflect that "Render a user avatar as an HTML page" is not working 

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13777]
### Description
The API documentation needs to be updated to reflect that "Render a user avatar as an HTML page" is not working and reference #9489 as the HTML export issue is also discussed there

### Render a user avatar as an HTML page:
![Screen Shot 2022-01-21 at 4 40 32 PM](https://user-images.githubusercontent.com/78037386/150603812-f20ba8fc-3e7e-47a6-9c7f-9d84c2e73eb6.png)

### Render a user avatar as a PNG file:
![Screen Shot 2022-01-21 at 4 40 42 PM](https://user-images.githubusercontent.com/78037386/150603868-bed3ea75-b340-458b-bcb8-923813037f01.png)

**Comment by j-dover** [comment]
Hi, can I work on this issue?

**Comment by CuriousMagpie** [comment]
Hey there @j-dover! You sure can--thanks!

**Comment by j-dover** [comment]
Hi @CuriousMagpie , 

I successfully updated the API doc locally by adding this line into website/server/controllers/top-level/dataexport.js as api.exportUserAvatarHtml's apiDescription:

` * @apiDescription This HTML export feature is not currently working (https://github.com/HabitRPG/habitica/issues/9489).`

However, I ran the full test suite by following the directions from [
Using Your Local Install to Modify Habitica's Website and API
](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica's_Website_and_API#Creating_and_Running_Automated_Tests)

![Screenshot 2022-01-31 153107](https://user-images.githubusercontent.com/15676972/151869427-cbfef686-be23-4b60-880e-a3c82fbd51f6.png)

I only changed one line and experienced the same results from the full test suite in my branch and the develop branch.
Should I submit my code?

**Comment by CuriousMagpie** [comment]
Hey @j-dover, the folks over in the [Aspiring Blacksmiths Guild](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) may be able to help you troubleshoot this!

**Comment by Alys** [comment]
@j-dover This is in response to your question in the Guild (as well as above) but I'm posting here so that we can record the conversation here for permanent reference. 

If that apiDescription comment is the only thing you changed, then it's highly unlikely that the test errors are due to your code. Sometimes the tests fail for unrelated reasons - for example, for temporary timeouts (which is a pretty common cause), or hypothetically if code that hasn't yet been fully tested has been merged to the `develop` branch (that would then cause the tests for all pull requests to fail).

Even if your change was responsible for the test failures, it would help us to see your change so that we could fully assess the situation.

So yes, please do submit your code in a pull request. If you're at all uncertain about whether the code is ready for final review and testing (and then after that for being merged to `develop`) you can add "WIP" to the title of the pull request (that stands for Work In Progress) and explain the uncertainty in the PR's description, along with whatever other comments you'd normally put there. 

See also the "Submitting your Change for Review in a Pull Request" section in [Using Your Local Install to Modify Habitica%27s Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API), if you haven't already read it (you might have read it since this isn't your first PR). It describes the option for submitting a PR to ask for assistance.

An additional benefit to submitting the PR is that the tests will be automatically run over your PR, which may result in different results than running the tests locally.

**Comment by CuriousMagpie** [comment]
@j-dover Have you made any progress on this?

**Comment by j-dover** [comment]
@CuriousMagpie I'm really sorry for the delay.

I followed Alys's advice and pushed my changes to GitHub to open a pull request.
