### ISSUE TITLE
Edit Avatar Menu images placed incorrectly

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13871]
### General Info
  * UUID:d70fa9f4-4aa6-4086-8c75-2337fd4d7761 
  * Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

### Description
From user: 
> In the Edit Avatar menu on the website (Macbook Air), all of the options are offset and cut off; this includes the body, skin, hair and extra options, but the backgrounds are unaffected.

I was able to duplicate this issue in production.

This may have something to do with the shift away from spritesheets or in the CSS used to position the image elements on each page of the modal. 

### Screenshots
<img width="751" alt="Screen Shot 2022-02-19 at 3 10 01 PM" src="https://user-images.githubusercontent.com/78037386/155028692-eedbe7b1-9c77-482d-9da7-6554a557ae8d.png">

![Screen Shot 2022-02-21 at 4 33 58 PM](https://user-images.githubusercontent.com/78037386/155028744-1f7c2f68-c1d6-45ed-bb72-b696d23a5ab2.png)

**Comment by citrusella** [comment]
I feel it's worth noting that wheelchairs and headbands are also positioned correctly like backgrounds are. (Maybe also animal tails are fine?)

(Maybe in context that information doesn't help except to know what's fine, but maybe it *is* helpful? EDIT: Playing around in my browser, I think it may be worth noting because you'd likely want to be sure a fix hadn't negatively affected something that's working?)

**Comment by WaelChettaoui** [comment]
Hey guys! I was interested in trying to solve this issue would that be alright?

**Comment by WaelChettaoui** [comment]
Can't seem to reproduce the issue on my machine (Windows 11 Home Version 21H | Chrome Version 100.0.4896.127 | UID: 50d2ad84-00d9-4b55-9d3c-dfb0943420ea
)

**Comment by CuriousMagpie** [comment]
This was resolved by #13933, it wasn't linked to this issue. Closing this now.
