### ISSUE TITLE
Birds of a Feather Achievement is not being awarded to some users

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13903]
The Birds of a Feather achievement is not being awarded to some users who have met all criteria.

After the migration script was run, we received a number of user reports that they had not received the achievement despite meeting all criteria. 

Normally, awarding the achievement manually in the database is sufficient, but in this case, awarding it in the database only awarded it on the website, not in the mobile applications--mobile applications still displayed the unearned icon. 

Eligible users also were not able to trigger the achievement by completing a flying pet quest.

Using a local version of  the `develop` branch, I tried the following: 
- Run migration script on an eligible local user account - achievement not awarded
- Removed one flying pet from local user user account and rehatched the pet - achievement awarded 
- Removed achievement and had local user account complete a flying pet quest - achievement awarded
- While achievement `value` = `true`, triggered the base pet and mount achievements - achievement notification fired a second time

The code for the Birds of a Feather achievement and achievement notification does not differ from that of Zodiac Zookeeper except in the specific types of pets required. I validated the required pets and their keys in the database and they were correct. 

The migration script for Birds of a Feather also does not differ from Zodiac Zookeeper except in the specific types of pets required. I validated these as well.

**Comment by Alys** [comment]
It might have something to do with Gryphons being included in the Birds of a Feather achievement since they have an extra, special Pet and Mount.

**Comment by CuriousMagpie** [comment]
That's a good point, @Alys. I'll look into it--I suspect it may be the gryphatrice, not the royal purple one, since the royal purple is a magic potion pet that everyone can get but the gryphatrice is not. It may be that we have to specify the colors in the achievement, which we normally don't have to do on non-specific-color related pet quests. 

In the meantime, another user report:

> I completed all the Birds of a Feather requirements a long time ago and since the achievement came out, I have completed a couple more of those quests. Now whenever I complete ANY quest I get a notification that I achieved Birds of a Feather, but it never shows up on my Achievements.

**Comment by citrusella** [comment]
The royal purple *gryphons* are rare pets/mounts [awarded for Naming Day](https://habitica.fandom.com/wiki/Event_Item_Sequences#Habitica_Naming_Day_Items), not ones that can be gotten through magic potion combinations.

I remember at one point they erroneously were showing up as if you could combine a gryphon egg and royal purple potion to get it but I'm pretty sure Habitica refused to hatch them. I went looking for old issues like this and actually found a couple regarding different issues with the royal purple gryphons: #10253 (the one I was thinking of) #10866 (a similar problem) #13042 (regarding the over-purchase warning)

The royal purple potion is also only given enough times to fully hatch and rehatch a sets of *standard* pets, which the gryphon is not.

(Hmm... but would the problem being gryphons (whether it's a non-hatchable problem or a gryphatrice only problem) not also extend to Legendary Bestiary, then? Since it also includes gryphons?)

**Comment by Alys** [comment]
`zodiacZookeeper: Boolean,` is in website/server/models/user/schema.js but there's no similar entry for `birdsOfAFeather`

That may be causing some of the differences in behaviour.

**Comment by CuriousMagpie** [comment]
@Alys Thanks--that's definitely something to track down.

@citrusella Thanks for pointing out my misstatement on how the royal purple gryphons are obtained. I have investigated the gryphon situation and do not believe the royal purple or gryphatrice gryphons are the issue here, as I was able to get the achievement to award in development with both of them missing from the user account.

**Comment by CuriousMagpie** [comment]
Should be resolved with PR #13901.
