### ISSUE TITLE
Changing the UI language requires a workaround

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13941]
### General Info
  * UUID: 128c50f0-3f5c-47aa-94b9-f293a4920d0f
  * Browser: Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
  * OS: Macintosh; Intel Mac OS X 10.15.7

### Description
From the user: 

**Reproducible Steps:** 
1. Navigate to **[Settings](https://habitica.com/user/settings/site).** 
2. Go to the **Language** drop-down. 
3. Select the desired language. e.g. 日本語 
4. Wait for the page to refresh. 
5. Notice that the language has been changed but not the UI.
6. Try to **Clear Browsing Data: `chrome://settings/clearBrowserData`** 
7. Go back to **Settings** and refresh the page.
8. Notice the language has now been changed.
9. Repeat the above steps to change it back to **English**. 

[YouTube recording.](https://youtu.be/okIWtW49L_Q)

**Comment by Jeewhan** [comment]
@CuriousMagpie Is this problem difficult for first-time contributors to solve? When I saw the video, I couldn't immediately figure out how to fix it. I want to contribute to habitica, but I haven't found a suitable issue yet.

**Comment by W1-PopelierE** [comment]
@CuriousMagpie Have you tested this on the latest version of `develop`? I tried to reproduce this issue and this is working fine on the `develop` branch.

**Comment by CuriousMagpie** [comment]
@W1-PopelierE This is an issue which pops up intermittently for users--we get enough tech support email about it that we decided that it needed further investigation.

**Comment by saraolson** [comment]
report that sounds related

> A new bug report from @datschka:
>In Chrome (100.0.4896.127 (Official Build) (64-bit)) when changing the language to a different one than the browser default (e.g. Habitica english, browser german), this can only happen if there is no cookie set yet. You have to clear cookies and change the language in the same browsersession to get the language changed. If you start Habitica, close the browser, start it again and then change the language, it isn't changed at all. In FF the coockie seems to be updated correctly. Only if you delete the cookie there, the browser default language is used and not the one from Habitica-settings.

**Comment by bbqben** [comment]
Hey I got super interested in this issue and did some investigating and I _think_ I may have found the issue with this. So far this is just a speculation because I also was not able to reproduce this issue with the `develop` branch. I used Chrome Version 100.0.4896.127 (Official Build) (x86_64) on MacOS 12.3.

From what I can tell, the logic for setting the language code is correct and I was able to confirm this from the PUT call `https://habitica.com/api/v4/user`.

![Screen Shot 2022-04-24 at 6 08 52 PM](https://user-images.githubusercontent.com/26254566/164998801-62de7a70-0cae-40a2-8a47-615ab4fb2469.png)

![Screen Shot 2022-04-24 at 6 08 55 PM](https://user-images.githubusercontent.com/26254566/164998802-5c36b608-ebf5-4aa1-bf5f-5287d127510f.png)


Also I was able to confirm that it looks like the language code is being returned correctly as well when retrieving the user details.

![Screen Shot 2022-04-24 at 6 09 21 PM](https://user-images.githubusercontent.com/26254566/164998846-9f9367ad-cc4f-4146-9666-0aaa1af4104c.png)

![Screen Shot 2022-04-24 at 6 09 17 PM](https://user-images.githubusercontent.com/26254566/164998855-f2c0c8ea-d276-4870-9a43-cfc752f087b5.png)


However when the page reloads and tries to retrieve the translated content, it looks like what **should** happen is the language code is passed when making the GET request to `https://habitica.com/api/v4/i18n/browser-script` (reference [here](https://github.com/HabitRPG/habitica/blob/245e135be83e620e5cd3e4b73a0755cebe80d0fa/website/client/src/app.vue#L417)), which looks like it returns a function that sets the translation data to `window['habitica-i18n']`. However what I'm seeing in the network requests is that it's actually referencing the call from cache which contains the previously set language.

![Screen Shot 2022-04-24 at 6 18 34 PM](https://user-images.githubusercontent.com/26254566/164999036-206a7fbe-be17-4c3b-bb29-2d02cf3ac305.png)


You should also be able to see the currently set language by entering `window['habitica-i18n']` into the developer console as it contains data on the currently set language.

https://user-images.githubusercontent.com/26254566/164999315-8b71c761-8e79-47ae-9ff3-d9235091fc35.mov


I've only been able to reproduce the issue on production but I'm pretty positive that it's related to the `browser-script` call being cached. If we change the call so that it forces it to not use cache then that **should** solve the issue? I think the code should look something like this:

```js
// website/client/src/app.vue:417
          return axios.get('/api/v4/i18n/browser-script', 
            { language: this.user.preferences.language, 
              headers: {
                'Cache-Control': 'no-cache',
                'Pragma': 'no-cache',
                'Expires': '0',
              } ,
            },
          );
```

**Comment by CuriousMagpie** [comment]
@SabreCat You know a lot more about the cache issue we were having late last year--does this look like a potential fix or would it be re-opening that can of worms?

**Comment by SabreCat** [comment]
That sounds quite plausible. We turned off CDN caching of the resource, but it could well help to skip cache during the API request.
@CuriousMagpie Is this reproducible in the testing environments?
@bbqben if you're still around, care to create a PR with your proposed solution?

**Comment by bbqben** [comment]
@SabreCat Yup, I can work on getting a PR in with the mentioned changes 👌
