### ISSUE TITLE
Habit created by a third-party service with UUID (random text) as task name

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1402]
When I logged in this morning (8/30), a new Habit "eb7a2702-c263-4fd9-95ae-122cda453877" appeared. It had the "This task was created by a third-party service" text in the notes. I don't use any third-party services at the moment...

---

_edit by admin:_

![random habit](https://cloud.githubusercontent.com/assets/9218435/4633646/3031f604-53c9-11e4-84af-3f2c651f4115.JPG)
##

**Comment by lefnire** [comment]
AFAIK this is fixed as per the switch/case bug @SabreCat (that which shall not be named... too shameful)

**Comment by lefnire** [comment]
needless to say, if it happens again reopen

**Comment by SabreCat** [comment]
This happened well before the switch/case issue occurred. That said, I have no idea where it came from, I've since deleted the Habit, and it hasn't happened again. So we'll see!

**Comment by lefnire** [comment]
@meaganoff just experienced this bug. re-opening

**Comment by lefnire** [comment]
ok, i do indeed think this is from the super-bug. Meagan was also hit by it, so that could account. What's going on here is the API says:

if you're sending a score operation (task up/down) - if that task exists, score it. Naturally. If it doesn't exist, create a new "3rd party service" task (like how the chrome extensions creates the "Productivity" task). If they sent a name along with, give it that name - if not, give it the unique ID it passes along with ('productivity', 'chrome', etc). Well, the super-bug was wiping tasks - so when people ran score, their tasks which were stored in localStorage on the website sent up it's ID, but the task got clobbered from the user - so it saw is as an incoming API task.

I'm going to close again and keep a keen eye on it. I think of all the tasks I'm "closing and keeping an eye one", this one I'll be the closest to since its' the only one that we're not quite certain was a result of the super-bug, even if I'm highly leaning that way

**Comment by SeamlessIan** [comment]
This happened to me sometime last night or this morning.

**Comment by deilann** [comment]
@lefnire I'm not sure why this is closed? I know people still experience it. Do we have a new master ticket?

@SeamlessIan Just go ahead and delete it. :) It's not something to worry about.

**Comment by deilann** [comment]
:thumbsup: for cafe @lefnire action? :)

**Comment by negue** [comment]
I'm currenty testing my app to get toasts (sort of notifications), so I just create many todos and clear "score-up"em very fast, and then it happened here too, I've 8 new habits with "UUID" ^^

And sometimes I also create a todo and check it within a second.

So here's my explanation why this could happen:

On each request the servers loads all data from mongodb
- Create Task 1
  - Add Task to Db
- Create Task 2 
  - Add Task to Db
- Create Task 3
  - Add Task to Db
- Score Task 3 Up (maybe the score up is processed before the Task 3 is inside the Database)
  - which results in:
    - Task exists? No? => create a habit with random text

We could fix this really simple...

The Thirdparty Services which only using `/user/tasks/{id}/{direction}` have to add a param like "?addEmpty=true" , so IF the habit doesn't exist, then only requests with this parameter will create new empty (or filled with data) habits, all other API-Consumers (also the website itself) then still can check / uncheck as they like,  because they also uses `POST: /user/tasks`, to create their tasks.

The only bad what could happen is that "gold-farmer" may have to wait some seconds before they can check their task xD

**Comment by ladydragon76** [comment]
Ok, so I added a screen cap of what just suddenly popped up on my Task page.

So this is a bug, and not someone hacking my game?
![the heck](https://cloud.githubusercontent.com/assets/9218435/4633646/3031f604-53c9-11e4-84af-3f2c651f4115.JPG)

**Comment by deilann** [comment]
Yup it's a bug and you can delete with no worries.

**Comment by ladydragon76** [comment]
Ok, thanks!

**Comment by berriganator** [comment]
Still happening!
![screen shot 2015-05-11 at 12 49 03 pm](https://cloud.githubusercontent.com/assets/11406808/7563336/80eb5f24-f7dc-11e4-8fcb-cb065ef60aa9.png)

**Comment by Alys** [comment]
@berriganator Yes, it will keep happening occasionally until we work out exactly what's causing it and how to stop it. When we do fix it, we will close this issue. Until then, when it happens to you, you can delete the Habit. It hasn't done any damage to your account.

**Comment by bionicallyironic** [comment]
This has been happening to me today. I first noticed it on my phone app and then on my desktop. Reloading the page does not help. Approximately 30 minutes to an hour after deleting, a new one pops up.

User ID: 73dc0fed-1ade-4533-9f63-8cf3d862ce8d

This is on Firefox/Yosemite and the app on an iPhone.

**Comment by djstinkay** [comment]
this happened with me today, as well, in conjunction with the addition of a totally blank to-do.  Any chance that's part of the same bug?

**Comment by Alys** [comment]
@djstinkay Yes, as I said at https://github.com/HabitRPG/habitrpg/issues/5989#issuecomment-144165027, this is the bug you were affected by. It's harmless. You can just delete the tasks.

**Comment by nivl4** [comment]
Is this still open? or already fixed?

**Comment by crookedneighbor** [comment]
Yes.

**Comment by paglias** [comment]
Closing since with API v3 this can't happen anymore
