### ISSUE TITLE
Batch operations return big responses (and other api routes too)

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1419]
Each `batchUpdate` operation return the whole user model which can become a quite heavy response (hundreds of kb and will go up every day) and is mostly unused by the angular app itself.

We should return only modified fields, the only problem is how to identify if the user has been updated by a different app.

This is true also for other api routes like updateUser.

**Comment by litenull** [comment]
Yep, yep, we're aware of that. We need to refactor the whole process.
We'll do that after the release.

**Comment by lefnire** [comment]
Here's the background on that:

We need to know if a user has been updated by any 3rd party service (chrome extension, mobile app, habit-txt, etc) since they last accessed the account. So it's not enough to just send down the paths which were updated _during this API route_, we need additional paths which have been updated since _the last time they accessed_. This is really tough, and starts to get into the realm of real [Operational Transformation](http://en.wikipedia.org/wiki/Operational_transformation) handling, so instead we just send the whole user.

(Incidentally, if all we wanted was _this route's changes_ - they're already currently accounted for. There's a `paths` argument that's optionally passed to all the algorithms, and it tells the caller which paths have been updated during this score / cron function. When you get that back, you could so something like this: `updatedAttrs = _.reduce paths, ((m,v,k)->helpers.dotSet(k,helpers.dotGet(k,user),m),m), {}`. But again, that's not going to be sufficient in our case since it ignores any updates by 3rd party services.)

Ok - the solution! It's actually quite simple, and we're currently doing most of it. `user._v` is updated by Mongoose for every save operation. If `user._v (in database) != user._v (from request)`, then there were changes. If they _are_ the same, there were no changes and we don't need to update the UI with the returned user object because they're going to be the same anyway. So you'll notice I call `"/api/v1/user/batch-update?_v=#{user._id}"` throughout the app. The _v is significant, and if passed up the response object will get a `wasModified` boolean sent down. If it's true, update the UI, if it's false, ignore the UI and just update `user._v`. I override this periodically when we need to force an update. (1) when cron is run, (2) when the server drops an item, (3) on initial page load, etc.

Now - we're currently doing this. It's kinda ugly, since we're attaching `wasModified` to the `user` response object, which isn't an actual user property. I'm thinking about adding an apiv2 which wraps response objects in a container, which may include other meta such as `wasModified`, `droppedItem`, `streakBonus`, etc. But we can do that another time. If we're worried about the size of data being returned currently, the simplest solution is to only send the user object when `wasModified==true` ([it's currently sent down regardless](https://github.com/lefnire/habitrpg/blob/angular_rewrite/src/controllers/user.js#L709))! One line change, very simple. But I'm at work right now so I can't test it doesn't break things. Give it a shot!
