### ISSUE TITLE
Party Chat causes Anonymous Party Members

### ISSUE THREAD

**Issue by katfang** [HabitRPG/habitica#1423]
On beta, when chatting to my party (party of 2), my friend disappeared and was replaced by two headless people. The members list listed 2 Anonymous people. It seems to reliably do this.

**Comment by lefnire** [comment]
I know what it is. ngResource ties resource objects (represented by REST paths) to the angular UI. It expects and `resource.$save()` calls to return that exact resource. We're doing `group.$save()` in order to update the chat, but we're not running `Group.findOne(..).populate('members')` in the response, so it's replacing the party in the UI (not in the database) with the group resource sans its members.

**Comment by lefnire** [comment]
fixed at 41255dc (in repo, but not pushed live yet - heroku's down for a bit)
