### ISSUE TITLE
I get Error: Forbidden on habitica.com.

### ISSUE THREAD

**Issue by Vagamin** [HabitRPG/habitica#14305]
.

**Comment by citrusella** [comment]
Hmm... #14198 is the same problem (and... has the same image? weird) but was fixed at the end of August. Is this somehow the same cause or a new one?

(Actually, is the fix there related at all? The fix on that one was mentioned to be the fix for broken redirects I reported, but a broken redirect issue would not list "habitica.com" in the address bar (and would cause a not-found error IIRC)...)

**Comment by SabreCat** [comment]
Whatever this was, it doesn't seem to be widespread enough to suggest an ongoing issue. Closing for now!
