### ISSUE TITLE
All dailies, habits and To Dos disappeared

### ISSUE THREAD

**Issue by mokiman3000** [HabitRPG/habitica#1433]
As it said above, around an hour ago i refreshed the page (might have been just before a server restart) and now all my dailies, habits and to dos are gone. 
Items are as they were.

**Comment by lefnire** [comment]
uncheck [any active filters](https://www.evernote.com/shard/s17/sh/87dc5e35-e059-4381-b799-baeb7f92d4df/b43335f4b26218ae8c6d662cd74089eb).

**Comment by mokiman3000** [comment]
Hey, waddaya know, it's all back. Ahaha~  ^_^"

Thanks! (Should probably add that to the FAQ / common issues?)

**Comment by lefnire** [comment]
[FAQ](http://community.habitrpg.com/content/im-missing-some-or-all-my-tasks) :) 

Anyway, in the rewrite we're not persisting filters. @SabreCat and I will be revisiting this after a while to determine the best way to persist filters and yet let users know that's why their tasks are  missing, but in the mean time we've had too many of these tickets so we're just gonna make filters transient for now
