### ISSUE TITLE
"This feature is not yet ported from the original site."

### ISSUE THREAD

**Issue by saradesouza** [HabitRPG/habitica#1443]
I tried restoring and resetting my account, but upon clicking any of the buttons, I get the following error in a browser pop-up:

"This feature is not yet ported from the original site."

And no changes were made to my account each time. Help? :<
If it helps, I have the android app synced to my account.

**Comment by BlackEdder** [comment]
HabitRPG is being rewritten in order to solve many of the bugs and this feature has not been ported yet. Until all features have been ported the old/original version of the site is still available on old.habitrpg.com, so you can go there and reset/restore your account.

The good news is that because many bugs are now fixed you should hopefully need the reset/restore functionality a lot less often :)

**Comment by wc8** [comment]
Going to close this, since I think the explanation addresses the issue.
I think the buttons are gone now...
