### ISSUE TITLE
Unable to add anymore tags

### ISSUE THREAD

**Issue by unit613** [HabitRPG/habitica#1444]
With over 20 habits and after adding 8 tags to the list I'm unable to add anymore tags.

**Comment by falafin** [comment]
I experience a similar problem. Everything works just fine but can't add any tags.  I still have only those 3 from the beginning (morning etc), and can't add anything new ones. I hope you will fix it soon, because I'm loving this app!

**Comment by lefnire** [comment]
we'll add it. we're porting in features one-at-a-time from the [old site](http://old.habitrpg.com), just haven't gotten to this yet

**Comment by wc8** [comment]
So, I suppose if you log into the old site, you can add a tag there, and it will show up on the new site.

**Comment by lefnire** [comment]
yes indeed. but take heed: https://github.com/lefnire/habitrpg/issues/1452 . i'm recommending people not visit old.habit unless they have to.

**Comment by smartao** [comment]
I have the same problem, but I have an observation to make, the tags were functioning normally before last update. Now I can add a new tag and put into a task, but after I update the page the tag disappears. It seems that the tags were attached to the old site ...

**Comment by lefnire** [comment]
tag disappears from the task, or altogether? if from the task, make sure you click "save and close". used to be real-time edits, but now where there's a save button in the app, you have to click it for those changes to persist

**Comment by smartao** [comment]
Unfortunately it disappears completely ...
Example of what I'm doing.
1 - I click edit tags
2 - create a tag with the name home
3 - I click again after creating tag edit to save.
4 - Now if I refresh the page the filter disappears.
At first thought it might be my browser, but tested in several and the same thing happened.

**Comment by Desdemina** [comment]
I'm not going to make a new report, since my issue seems related. But I can't checkmark the tags at all within an item. I edited the tags, but when I went back to the page, the tags were back at the default. I'm not filtering just trying to assign a tag.

Update: Well, it seems to work sometimes now and not others. I'm going to play with it some more and see if I can figure out a pattern.

Update #2: Ok, I've found some patterns. If I edit the tags (and save them!) AND create a new item, I can checkmark a tag. However, if I open an existing item and try to checkmark the tag, I cannot. Also, if I reload/refresh the page, the tags revert back to the original (morning, etc.).

Hope that helps!

**Comment by smartao** [comment]
It is exactly as Desdemina said.
But in my case the tags back to the standard that I had set up, work, home and school.
I hope this is not a serious bug, because I have plans to build many tags as soon as possible.
Tks!

**Comment by lefnire** [comment]
it's not really a bug, we just haven't fully ported the feature yet. we'll be getting to this soon

**Comment by lefnire** [comment]
fixed, give that a whirl

**Comment by smartao** [comment]
lefnire
I did some tests and apparently is working normally now.
thank you very much
