### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by litenull** [HabitRPG/habitica#1451]
I'll tackle this one. Its a long-run thing.
The app can be optimized for quicker UI feel.

**Comment by lefnire** [comment]
Things to look into:
- ~~preen_history #1492~~
- filter out completed todos from list (ngFilter, instead of taskClasses)
- remove taskClasses since it's computed on every digest
- can we use ngResource for **user** GET & updates, it might save us a ton of perf compared to _.extend. We may have to change the API 
- Some watchers / class-updating functions are called infinitely. eg, `ChatCtrl : nameTagClasses()` - set a debugger in there, and open up console after the page is fully loaded - this will get called over and over. I _think_ it might have something to do with chatroom pretty timestamps? Seems that's continually updated, and could be triggering digest for GroupsCtrl over and over. If so, we can just lengthen the setTimeout time (like once every minute or two)
- Organization of controllers. Seems the higher up a controller, the more digest has to account for. One example is chat. `ng-model='newChatMessage'` causes the chatbox typing to go excruciatingly slow. When I moved ChatCtrl down to just the form wrapping the textarea, everything was fine. I couldn't keep it that way due to some function organization, but it validated my concerns
- use server rendering any time we can, for things that aren't going to change for this rendered session
- Move all shared logic out of controllers and into Services. This is a very important one, and was the biggest piece of advice I've gotten from the Angular IRC room. 

I'm just gonna keep updating this post as I think of things

**Comment by litenull** [comment]
@lefnire Hacking it as we speak.

**Comment by paglias** [comment]
The big delay when opening the option page is probably due to the fact that it loads all the controllers (there are 7 tabs and at least one - inventory - has more than one controller) together.

We could have a different route for each tab so that it should be a lot faster but that could means that tavern is reloaded every time (but maybe not since it's not reloaded when switching back to the tasks so probably angular doesn't destroy the controllers)

The only problem is with ng-view, angular doesn't support nested templates as far as I know, we may use angular-ui-router.

What do you think?

**Comment by lefnire** [comment]
Two options I see: 
1. Exactly what you're describing, using angular-ui-router for sub ng-views (this was something I saw too in research, definitely a possibility). Pros: easier to code, since we'd be letting angular-ui-router's do the grunt work. Cons: things aren't loaded permanently per session (as you described with tavern having to load each time you access it). This could _actually_ be a good thing, because tavern chat might have updated since the last time you accessed it - could be an easy way around the long-polling chat issue
2. Code a Groups lazy-loading mechanism when tabs are accessed. Check out memberServices.js and how it lazy-loads individual members or groups of members, we could do the same for groups, lazy-loading the group only when it's tab is clicked. Pros: Groups are then stored permanently for this session, so if you access the same tab you don't have to re-load. Cons: we have to custom-code all this, where angular-ui-router could save us a lot of time. Also, how likely is it someone's going to access the same tab twice in one session? 

I'm possibly _leaning_ towards the angular-ui-router approach, or at least experimenting with it. But if either of you have a strong opinion one way or another, I'll defer to you

**Comment by paglias** [comment]
I think that 2 wouldn't solve any performance issues, at least not the long time when opening the options page. 

As for 1 (which I would go for, personally) I think we could save things like the tavern/groups not having to reload them every time in a session: actually if you open the tavern and swicth back to the tasks then when you go back to the tavern it doesn't loads because it's already, I think we can use the same mechanism

**Comment by lefnire** [comment]
Well Tavern is like that because I manually coded it to be such via #2 above, it was re-loading each time before I added that functionality. So if we go with #1 (which I'm leaning towards personally as well), we're not going to get that Tavern mechanism unless we code it in. Sounds like #1 it is then!
