### ISSUE TITLE
Daily won't delete (bug)

### ISSUE THREAD

**Issue by Gr4ssh0pper** [HabitRPG/habitica#1452]
See the image here http://i.imgur.com/zZaetyK.png

I can click the trash icon and the popup shows up to ask if i'm sure I want to delete and press ok, but nothing happens. Refreshed and tried on the app too. Won't go away!!! Driving me nuts! What do?

(not sure how to add labels..)

**Comment by lefnire** [comment]
I'll explain more in a bit, but it's a vestige of the old site. The weird fix for now is: visit old.habitrpg.com once, wait a bit for your data to recalibrate (and don't touch anything on old.habit), then come back to the new sites and don't mess with old.habit any more. Shouldn't happen again. I'm gonna add a hack-fix to the new sites later, and once old.habit's dead I'll take the hack-fix out.

**Comment by Gr4ssh0pper** [comment]
On old.habit none of my habits or todo's show up, just the dailies. Will this remove them from the new site?

**Comment by Gr4ssh0pper** [comment]
Nevermind, it is solved. The blank daily went away and everything else stayed put. Thanks!

**Comment by lefnire** [comment]
you probably just had an active filter on the old site, is why they weren't showing up there.

Anyway, basically what's happening is old.habit loves to duplicate & corrupt tasks. so I was going around un-duplicating and un-corrupting on page refresh (see now why I worked so hard for a full rewrite?). well let's say you did one action (add a task, delete a task, whatever) on old.habit, and you now head to the main site or mobile app. Since they handle data cleanly, they don't need to uncorrupt data - so what you've got is corrupt data from old.habit, not uncorrupted at habit new. Kinda a rare situation, but some people are hitting it. Again, once old.habit's dead people won't experience this again.

You probably didn't' visit old.habit explicitly - more likely, you performed an action, and before you could refresh I switched everyone out to the new site last night, so you missed the "uncorrupt me" window.
