### ISSUE TITLE
Can't log in (Firefox on Android)

### ISSUE THREAD

**Issue by rixx** [HabitRPG/habitica#146]
With Firefox (fully updated) on a Samsung S3 Mini, I get the mobile page, but when I click the Login/Register button, it doesn't react at all.

**Comment by horusofoz** [comment]
Can you trying pinch to zoom out and see if the login screen becomes visible?

**Comment by rixx** [comment]
Doesn't help. I tried scrolling around, there's nothing there.

**Comment by rixx** [comment]
Whoops,  sorry, missed the button on my phone.

**Comment by rixx** [comment]
Hm, the first time I hit the button, it reloads the page to habitrpg.com/#login-modal

However, I still don't see a login, not even with scrolling around and along the borders.

**Comment by horusofoz** [comment]
I can confirm your issue after testing on my S2. The button "presses" (turns yellow for a second) but no further action.

I suspect the issue is caused by a bug in [Derby](http://derbyjs.com/) as the symptoms are identical to that reported [here](https://github.com/lefnire/habitrpg/issues/225) for Internet Explorer. Derby is the framework used to build HabitRPG. 

Alas, we can only build so much Awesomeness out of the tools available to us.

@lefnire Is there a way you can confirm this issue is the same as that previously cited? If so we can close that ticket and note [bug #146] is also affecting Internet Explorer.

**Comment by lefnire** [comment]
yep, happening on mobile. just using some standard bootstrap, will look into

**Comment by rixx** [comment]
Doesn't happen on Chrome, btw.

**Comment by DDzwiedziu** [comment]
Works on Firefox Beta.

**Comment by horusofoz** [comment]
Confirmed now working on Firefox Mobile.
