### ISSUE TITLE
Profile Text Wrap-around problem?

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1469]
Hi! I updated my profile and posted a link and when I went to check it by clicking my name in the tavern, the text of the link spilled over into the stats! You can click my profile to see what I mean.

**Comment by lefnire** [comment]
Ah, some css we'll need to update. We should also add `{{profile.blurb | linky:'_blank'}}` so the the links can be clicked. Until we can fix that, use bit.ly for long urls like that

**Comment by paglias** [comment]
@lemoness should be fixed in https://github.com/lefnire/habitrpg/commit/75613b0508bd8b94b8ff05db742923fbf3423a81, I also added linky and link for profile's websitte. Let me know if it works since I couldn't test it locally (it gives me 404 when I try to post to tavern)

**Comment by lefnire** [comment]
@paglias reason for that is that the tavern is an actual Group in the database, and doesn't exist on your machine. Just added a src/seed.js to add tavern to your db above

**Comment by paglias** [comment]
Fantastic thanks! Another question : the chat is an array of objects or a embedded schema with defined fields? To edit it I just edit the array and then call grop.save or need to use mongoose methods?

**Comment by lefnire** [comment]
Right now you just edit the array. I think though that we should _make_ chat an embedded schema, so that we can just call `group.chat.id(id);` (since we're actually already storing ids on chat objects) - though maybe we can postpone that, seems simple enough to do array manipulation with `_.findIndex(group.chat, {id:id})` We definitely don't want to work with indexes sent from the client, since those will be out of sync when A types a new chat message and B hasn't refreshed chat.
