### ISSUE TITLE
Move 'options' partial view to script

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1482]
Move 'options' partial code in a script template so that we have one less request to the server to make, but place it in the bottom of the body or it will slowdown the page.

It will give slight longer load time initially (but same rendering time for index) but better performances and one less request to server.

**Comment by paglias** [comment]
Also `tasks`

**Comment by lefnire** [comment]
oh that's a good idea, I hadn't thought of that!

**Comment by paglias** [comment]
EDIT: read the comment below

**Comment by paglias** [comment]
The only solution seems to be moving script tags (for google adsense) outside of the template as they break everything.

There's a way to move them somewhere else with angular? Maybe using a directive?

**Comment by lefnire** [comment]
Most of the adsense code is presently in a directive, since it has to be rendered after linking. See public/js/directives/directives.js:habitrpgAdsense . Might be we just cut & paste all the current adsense code in the views, right into the directive so that the directive contains everything, instead of just transcluding the html? Do some experimenting with that

**Comment by paglias** [comment]
I have pushed some code to **move-partials** branch, but it's not working, everything in ok with the html but the javascript `(adsbygoogle =...` inside the directive template is not executed. We really need to execute it there? There isn't another way? 

I tried to execute it in the link function of the directive but doesn't work.

**Comment by lefnire** [comment]
I'm not quite sure to be honest. I'm a bit newbie when it comes to directives. I may play with this sometime when I get the chance to see what issues you're hitting. Do you have a branch?

**Comment by paglias** [comment]
It's on move-partials branch

**Comment by paglias** [comment]
Anyway I've read that js code in directve's template property is not executed by angular so the only soution is to move it outside of it.

**Comment by lefnire** [comment]
Given your last comment, I was able to fix it (https://github.com/HabitRPG/habitrpg/commit/afb1687cf52e64ba09222df57b43c3669e3c4716 and https://github.com/HabitRPG/habitrpg/commit/af230bed77ce01674419e4e46d002290cf871667#diff-7a6d770c287cf03133942144e9f2c670R136 for getting around the ads issue) on the `challenges` branch. I'm going to close this, since it will come in once I merge challenges (it's only like 40% done, dealing with lots of scope issues), but it definitely increases performance!

**Comment by paglias** [comment]
Fantastic!
