### ISSUE TITLE
Suggest add gameify or gamification to the tag for better SEO

### ISSUE THREAD

**Issue by linonetwo** [HabitRPG/habitica#14835]
Today I try to find habitica again (sorry for AFK for years), and I try to find it by looking at https://github.com/topics/gamification?l=javascript list, but not found.

Could you add this tag to this repo so it show in the list?

**Comment by chavi362** [comment]
I am trying to work on it

**Comment by chavi362** [comment]
@@HabitRPG
In order to add the gamifaction topic, you have to: 
![image](https://github.com/HabitRPG/habitica/assets/140444217/bc8e8619-6237-4c20-9a6a-ec88b3f2d30a)
under Topics, start to type gamification, now you'll see gamification. Click on it and then click save changes.
Because I'M NOT THEOWNER I can't do it by myself since I don't have settings.
Good Luck!!!
post Scriptum: I would like to contribute code to Habitcia, please can you write me via email c44362@gmail.com when there is a new good first issue?
Thank you so much @HabitRPG

**Comment by SabreCat** [comment]
Thanks for the suggestion--not an app bug or code issue, though, so not a great fit for a ticket. Closing.
