### ISSUE TITLE
long-poll for chat

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1503]
just an ngResource `group.$get()` 20s interval for the active tab. I'd say socket.io, but I hear it's really rough on server resources. People chat so seldom I think we can just do a super spaced-out long poll
##

**Comment by paglias** [comment]
also socket.io doesn't run on heroku

**Comment by lefnire** [comment]
You can config socket.io to use xhr polling (we were doing that with Derby on Heroku before), but yeah - no socket anyway

**Comment by paglias** [comment]
What about this? I can implement it but we should decide a) how often to poll for chat b) something automatic after the user first loads the chat or an opt-in?

**Comment by lefnire** [comment]
I'm in favor of automatic after they first load the chat. Might be a pain to determine which group tab they're on and setInterval / clearInterval accordingly, so whatever you think is the best solution

**Comment by paglias** [comment]
Mmm... chat syncing seems to leak a bit of memory, about 60mb for every syncing...

**Comment by lefnire** [comment]
_whistles_ Yowzer. Ok, new plan… um… socket.io maybe? _nervous questioning
face_

On Wed, Nov 13, 2013 at 12:08 PM, Matteo Pagliazzi <notifications@github.com

**Comment by Aurornis** [comment]
I was directed here from 2141 to discuss the chat refreshing.  It'd be nice if it auto-refreshed, at least in party view.  I keep a tab open with my party view (since it's a pain to have to click the social tab, wait for the tavern to load, then click party) and, as another user put it in the thread under 2141: "the chat screens don't auto-refresh, and the timers on messages already displayed do auto-refresh (bizarre combo) - but it helps make them look as if they do autorefresh, which is unhelpful."  So if auto-refreshing won't work for one reason or another, could the time stamps be changed to the actual time instead of "X hours ago"?

**Comment by colegleason** [comment]
Could we use Websockets (which Heroku now supports) for this?

https://devcenter.heroku.com/articles/node-websockets

Additionally, this would be nice to tell the client when cron has run on the server if we end up moving cron there.

**Comment by lefnire** [comment]
Absolutely. And using a wrapper like Socket.io or Sockjs will allow us to fall back on long-poll where a browser doesn't support Websockets proper (older mobile, etc). Other places this would be useful are boss attacks, party buffs/heals, API hits (notify the browser when chrome extension knocked you), etc. I think it's clear Websockets will benefit us, though seems like we might have some memleaks & technicalities to play with a bit in the process

**Comment by jsplink** [comment]
Could also use server-side events w/ a polyfill to support older browsers
