### ISSUE TITLE
Strange behavior when inviting people to the party

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#1509]
I'm a party leader/creator. Whenever I go to Options -> Groups, when I enter player's User ID and click Invite, I see my own character avatar appear in the upper party bar (header) - so I appear there twice, as well as my username and user ID in the members list (normally it does not include me). It goes back to normal after refreshing. This happened EVERY time I invited people, 4 times so far. I attach a screenshot from the moment when I invited a 4th member.

It's not really a bug or anything, it's just strange behavior, probably unplanned.

Chrome Browser (Windows)
User ID: a5966c55-f839-49c8-8462-5400d2ee4166
![clipboard01](https://f.cloud.github.com/assets/4543072/1115116/b7c2c726-1a25-11e3-9f9f-29ec74b74f5a.jpg)

**Comment by lefnire** [comment]
I know what's happening, and the likely solution - but just some background info - "light reading" for @paglias and whomever may be interested :) 

The `Groups` mongoose model has `.members`, an array of User refs: `members: {type:String, ref: 'User'}`. When you fetch your party, you `Group.findOne({type:'party',members:{$in:[myself._id]}}).populate('members')`. Note we _populate_ the members so that the returned Group object doesn't have an array of ids, it has an array of full user objects. Tangent, but important for other bugs - eg, if you perform a group action and suddenly everyone loses their head, means we forgot to run `.populate()`. Anyway, it returns all the members including yourself. As often as I can remember I _exclude_ yourself after fetch (there's a way to do this in `.populate()`, but it's a broken Mongoose feature). Looks like I forgot to here. Will fix when I get the chance

**Comment by katfang** [comment]
Just a note, this happened to me when I invited someone to the party (and I was not the original party creator (I think)). In addition, when my friend joined, she saw herself on top as well.
