### ISSUE TITLE
Need a Desktop app for tracking progress, synced with mobile apps

### ISSUE THREAD

**Issue by ikabrain** [HabitRPG/habitica#15138]

**Comment by olisteadman** [comment]
Hi @Ikansh, as per [contributing guidelines](https://github.com/HabitRPG/habitica/blob/ff0bb9d005fba2b5fa04bbb79db23b12e46b223b/.github/CONTRIBUTING.md) Habitica uses [this Google form](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link) to track feature requests. Please post there rather than creating an issue.

In the meantime, I recommend using https://habitica.com as a desktop-optimised web app that syncs very well with the mobile app versions.

**Comment by CuriousMagpie** [comment]
@olisteadman Thanks for answering this! The website and mobile app use the same database and mobile uses the API, so they should be synced!
