### ISSUE TITLE
Update Tour wording

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1513]
@SabreCat - the first ticket I'm going to assign to you, should you accept your mission. https://github.com/lefnire/habitrpg/blob/master/public/js/services/guideServices.js#L14 has all the tour steps. This was from day one, and whilst adding it back into the rewrite I realized it's sorely lacking on information. Any chance you could take a go at it? it's the `title` & `content` sections - but if you decide you also want to point the bubbles at different things than currently, and need help doing so - hit me up

**Comment by SabreCat** [comment]
Ooh, cool. I can certainly take a stab at this! The trick will be getting all the right info in there without it triggering the "tl;dr" reflex...

**Comment by lefnire** [comment]
Totally - this & unlock notifs are those "must strike perfect balance" moments that make that a true art!

**Comment by SabreCat** [comment]
Getting some good ideas here. Quick questions--
1. Adding and rearranging objects in the tourSteps array should change up the length and sequence of the tour, right? No weird hardcoded boundaries I need to watch out for?
2. Not sure I'll need the bubbles to point anywhere different yet, but in case I do try to tinker! By the look of it, the "element" property tells it where to look on the page. Where are those regions defined? They look CSSish?

**Comment by lefnire** [comment]
Yep, they're CSS selectors. It uses jQuery, if you're familiar - so if you need to point to something different, think CSS

**Comment by paglias** [comment]
I would add a bubble to show that clicking on the avatar you're ported to the options page

**Comment by SabreCat** [comment]
Sorry I haven't been working on this much yet! September is a busy month for me. Users' group meeting for my day job...

**Comment by meganstrickland** [comment]
I was directed here by Ryan from the [Avatar Options](https://trello.com/c/lBR41FoO) Trello card. I've seen a lot of "avatar gender" questions come up in the Tavern and on Trello---both "How do I make my avatar female?" (mostly new users) and "How do I make my avatar male?" (mostly slightly more advanced users with healer and/or mage gear). It's been a while since I've been through the new user tutorial and I'm sure it's changed anyway, but perhaps the avatar customization needs to be included more prominently? I am a BIG fan of the fact that HabitRPG does not force a binary gender choice, and I think a lot of these questions will go away or at least get redirected a bit if the customization options are just a bit more obvious.

**Comment by paglias** [comment]
@meganstrickland the tour code is here https://github.com/HabitRPG/habitrpg/blob/develop/public/js/services/guideServices.js#L16 and you can find the actual content (in the file above, references to window.env.t('StringName')) here https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/npc.json

So if you find what should be changed you can send a Pull Request (or I can do that for you)

**Comment by meganstrickland** [comment]
@paglias Alas, I do not (yet!) possess the necessary skills, but I am working slowly to acquire them, and I will take a look at this (eventually) if it hasn't been sorted by someone else first. Thanks!

**Comment by paglias** [comment]
I think they have been updated long ago
