### ISSUE TITLE
Taking damage for uncompleted dailies even on days they aren't due

### ISSUE THREAD

**Issue by gldearman** [HabitRPG/habitica#152]
Dailies that I have set to be Monday — Friday only appear to still be causing damage if I haven't completed them by the end of Saturday or Sunday.

The client I'm observing this on is Firefox 13 for Ubuntu 12.04.

**Comment by wc8** [comment]
I too am possibly experiencing this or #145. All due tasks were completed. 6 of 60 HP loss.

**Comment by Pandoro** [comment]
I have the same problem I think. I have 1 task which I scheduled for two days in the week. Three times now I have gotten around 2-2.2 damage for this task. (I only started playing since then, so I'm not sure how it was before that.)  It might also be my many todos as suggested by wc8, but I have 14 todos, which somehow does not fit the 2.2 damage I got today after 12:00 :( 

Otherwise a GREAT idea and game. It already changed my life in just three days <3

**Comment by horusofoz** [comment]
If confirmed, I think this bug needs to be escalated as important if not critical.

It affects all users and could cause some unjustified executions.

Can a dev perform a controlled test? I don't have your mad skills.

**Comment by lefnire** [comment]
will test when i get a moment

**Comment by Pandoro** [comment]
Just to let you know, I think i haven't experienced this any more. I have been gone for 3 days now and because of that I turned of every daily. Today I got back to habitrpg and somehow I suffered 1 hp damage. But that cannot account for 3 uncompleted tasks each day. I think the damage on my side happened due to an invisible task which was fixed some days ago!

**Comment by StanLindsey** [comment]
I actually noticed that this happens sometimes on the temp profile when you're a new user. I loaded Firefox to test some code and upon page load the character lost health.

**Comment by horusofoz** [comment]
Can anyone confirm this is still happening in Prod?

**Comment by StanLindsey** [comment]
I'll be super productive today and check everything off, note my HP and come back to you tomorrow =D

**Comment by Pandoro** [comment]
I honestly haven't heard of this issue popping up in a long while. It seems to have been fixed when Tyler fixed the lost items that were still in the list. Can we close this ticket?

**Comment by StanLindsey** [comment]
I wasn't super productive as I promised a fortnight ago. 

I agree with you though @Pandoro - if anybody has similar issues feel free to post!
