### ISSUE TITLE
Tag filters sporadically auto-clear [$15 awarded]

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1528]
Every so often, while using the site, my selected tag filters automatically get cleared. I haven't been able to figure out what, if any, conditions cause it to happen: it's pretty random. I've had the filters reset while the site sits idle in another window, or while I'm in the middle of inputting a new task.

We had some uncertainty about whether tag filters should persist across sessions or during various navigation, but I'm pretty sure it shouldn't be quite like this!
##

**Comment by lefnire** [comment]
yeah, definitely a bug there - indeed not the filter-persistence issue .

**Comment by SabreCat** [comment]
This appears to be a whole mini-refresh of the page. I've had it happen in the midst of editing the value of a Reward, and not only did the tag filters clear, but my Reward went back to its previous value.

**Comment by snicker** [comment]
It seems that tags will clear if a new `Task` or `Reward` is added as well. I think that I'll look into this as it could probably be an easy solve with the implementation of [this trello card](https://trello.com/c/GYe6MCly/319-tags-save-selected-tags-between-sessions). I'm personally vested so I'll take this one on

**Comment by SabreCat** [comment]
This appears to happen whenever an incidental update forces a sync. For instance, the most common situation I see it with right now is when a party member checks in, triggering boss damage to me.

**Comment by lilyanne** [comment]
I am also having serious issues with my tags randomly unchecking themselves from my items. It's incredibly frustrating because my ability to not be overwhelmed with the site is dependent on the tags NOT resetting. If it keeps resetting, I'm not going to be able to do dailies that I need to nor am I going to be able to set up my "survival mode" (activate all dailies tagged survival and deactivate dailies not tagged survival) when I have a serious depressive episode or anxiety attack.

**Comment by SabreCat** [comment]
@lilyanne: That sounds like a different issue. I've updated the issue title to reflect that I'm talking about tag _filters_, not the tags themselves.

That said, I am getting seriously annoyed with this issue. This morning I clicked a daily, the filters randomly cleared, and it checked off a different daily than the one that was visible when I clicked!

**Comment by lefnire** [comment]
What happens:
- Filters aren't stored on server
- If you do something, and the server has updates for you (API hits from mobile / chrome / etc since you last interacted), the server will send down the new user object, updates & all
- That includes the blank filters, since the server doesn't store filters.

Anyway, that's the bug. It needs fix'n, but I won't be tackling it soon due to other crits

**Comment by SabreCat** [comment]
Interestingly, the workaround seems to be the same as for avoiding those VersionErrors we had a bit ago: if you wait for the loading bar to finish in between clicks, you're safe. It's if you queue up an extra action before the previous is quite done resolving that you end up resetting your tags.

**Comment by snicker** [comment]
fixed in https://github.com/HabitRPG/habitrpg-shared/commit/aa0c69e082b199f2ad3a3650630b65e082af0793

**Comment by snicker** [comment]
The solution is to store the current tag array clientside (including selections) and merge it with the incoming user data. This can cause some issues if a tag is deleted on another client, but if the user clears tags, all is well

**Comment by bountysource-support** [comment]
@snicker don't forget to claim the bounty on this issue: https://www.bountysource.com/issues/1038373-tag-filters-sporadically-auto-clear-15/claims :)
