### ISSUE TITLE
difficulty level incorrect when hovering over a rewarded quest scroll

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica#15297]
> A new bug report from @arandomtrout
> 
> So, when I look at the quest scroll for The Golden Knight 3 as a reward for its precursor, it displays difficulty of 1 instead of 3.5, like it should.

the difficulty level when hovering over the quest scroll reward:
![Screenshot 2024-08-18 at 3 57 52 PM](https://github.com/user-attachments/assets/eeda4710-8fb7-434f-9413-ae9b18d77e2f)

what it should be:
![Screenshot 2024-08-18 at 3 58 04 PM](https://github.com/user-attachments/assets/47d956e8-3d27-4cf6-94a1-5db328aa7840)

it looks like this is the case with all quest scroll rewards in the quest shop.

**Comment by harshmd7** [comment]
Hi @arandomtrout and maintainers,

I would like to work on this issue regarding the incorrect difficulty level displayed for "The Golden Knight 3" quest scroll. 

My plan is to:
1. Investigate how the difficulty is calculated and displayed for quest scrolls.
2. Verify why the difficulty is shown as `1` instead of `3.5`.
3. Fix the display logic so it correctly shows the difficulty as `3.5`.

If this sounds good, could you please assign the issue to me? I'll submit a PR as soon as I can.

Thank you!

**Comment by CuriousMagpie** [comment]
Hi there, this was fixed and went into production on 9/17. Thank you for your interest in contributing!
