### ISSUE TITLE
[Suggestion] A Rest Button For When You Will Be Away

### ISSUE THREAD

**Issue by The-Bard** [HabitRPG/habitica#153]
_Update by wc8: Vote: [Rest in Tavern Button](https://trello.com/c/A2w2orSc)_
I just noticed that if I wanted to take a vacation I'll have to delete all of my dailies in order to avoid killing my avatar. It would be nice to have a vacation button, or maybe a "Rest in the Tavern" button for when you'll be away from the computer or access to HabitRPG. Maybe when it's enabled nothing can be changed, added, or spent. It simply "Freezes" your account until your disable to resting button?

**Comment by lefnire** [comment]
See the [FAQ](https://github.com/lefnire/habitrpg/wiki/FAQ) on vacations. Still a slight pain to setup, but at least you don't have to delete your tasks. "Tavern" is a good idea, I'll keep this open for that

**Comment by The-Bard** [comment]
Oops... I should do my research more thoroughly... Thank you.

**Comment by Yughurt** [comment]
Seemed decent place to add a skip feature as some days things pop up and you're unable to do them yet these things are still productive.

**Comment by wc8** [comment]
@Yughurt Could you give an example of a skip situation?

**Comment by Yughurt** [comment]
So today I had a project meeting that required attention changing overall what I need to do. As my daily checklist includes work and exercise items, I didn't have time to do these things. I don't like pressing yes, i've done these as it ruins the "truthfulness" scheme that this system runs on as well as making the analytics less useful. So a skip would be a way to defer an item due to a legitimate reason.

**Comment by hookang** [comment]
Good idea. Added to Master list of Features #169. Issue closed for organization.

**Comment by wc8** [comment]
We have the [Rest in Tavern/Vacation button](https://trello.com/c/A2w2orSc) card in Trello, but I think it needs some fleshing out. 

The Rest-in-Tavern feature request was joined to the vacation mode feature request, because they seemed related. However, I'm realizing if the account-freeze is in effect, it could be problematic for a vacation/travel/illness mode. During **vacation/travel:**
- certain dailies are irrelevant: (take out the trash, sweep the floor)
- certain dailies are just as important as before but harder to remember: (take medicine)
- certain habits would still apply: (I've never smoked, but it seems taking a week off quitting wouldn't help long term)

What happens when Rest-in-Tavern is enabled? 
If account-freeze is in effect, would a user be able to [Record Yesterday's Activity](https://trello.com/c/CaAm7APS)?
What happens when the user disables Rest just before midnight?
Should resting in a tavern cost gold?

**Comment by wc8** [comment]
On a related note, should "Skip" [not yet in Trello(?)] cost a small amount of gold? Perhaps a percent of the users available gold?

**Comment by StanLindsey** [comment]
I'd say freeze it and then when they un-freeze (leave the tavern) they can look over the period and check off tasks/click on dailies for that period if they did get anything done/good habits.

**Comment by wc8** [comment]
If rest-in-tavern mode = frozen account, could there be a setting to enable certain dailies, habits, tasks? So everything else would be frozen except those tasks? Would that be difficult to work out?

@Yughurt Re: **Skip Button**—I like the idea, thanks for explaining it. 

I have a couple of suggestions for implementation for discouraging procrastination.
- Allow a limited # of free skips in a row or in a week. If the user tries to skip again, a message appears: _You skipped last time, it'll cost the same as missing it, are you sure?_ 
  - Add a field for user to enter # of days to skip task, (for travel or prolonged interruptions): eg. _Skip for 3 days_, on the fourth day, attempting a skip will cost as much as if you simply hadn't done it.
- Implement a reduced cost for skipped tasks, or charge GP instead of HP
  - Perhaps the reduced fee only applies if you do it before a certain time, eg. skipping just before midnight costs as much as missing it.

Thoughts?

**Comment by wc8** [comment]
P.S. Trello card for Skip Button [here](https://trello.com/c/Rt13zl9x).

**Comment by Yughurt** [comment]
Sorry I'm so late. I've been overseas and haven't had a chance to do stuff here.

Okay, I'll explain the basis of this. Don't call it skip or tavern. It assumes that you're resting. Call it... "Other quest" Or something along those lines. I suggested this because in the event of having a long meeting, have a hackathon, etc and you wanted to make a choice to do something else productive. As such, the skip feature would be used for that and should have no penalty. I think to use this non payment feature, the thing skipped can't be the same 3 days in a row or something to that effect. Otherwise there could just be more town like features. (you have tavern etc already?) You own the town and by deferring to doing work for "other towns" you are weakening your own town. Where one day would be fine for the town, too many and it would go into disrepair. I'm wary of this though.

(has been posted to trello)

**Comment by Pandoro** [comment]
I do see your point about the not naming it "skipping" something, but calling it something that still makes it sound productive. However that is just a naming thing in my opinion. The question is though, if we want to make it possible to skip single tasks. Apart from the fact that this is already easily done by just turning the daily of for that day, I get the feeling that if you are encouraged to do so. So I would rather have something like all in or all out. If you want to do your stuff, try everything, or if there is something more important than your daily routines, throw them out completely. Maybe it should be possible to still complete some stuff, even when "skipping, resting, or being in the tavern". This way you wouldn't loose the points from "doing your exercise" or whatever you still want to do that day. 

On the town suggestion:
Personally, although a big fan of stronger rpg and game features in general, I think this is going too far. If you have to take care of a city, this is really going to distract you. At least that is how it feels at first glance. If you further want to discuss this idea though, I suggest you make a new issue, to keep it a little clean here.

**Comment by StanLindsey** [comment]
I agreed with @Pandoro - if you want to skip a particular daily, turn it off or tbh leave it, the HP drop isnt that much. The idea of a vacation setting would be the essentially lock down your account whilst your away. Just like how a gym membership works.

**Comment by Yughurt** [comment]
I've better explained this in trello. It's got nothing to do with resting/tavern. It's called elixir todo under general features.

HP Drop depends. I give myself about 50 dailies where I have many elements of my day planned out. (I'm quite busy so this sort of thing is needed) 

I rethought out the town thing in https://github.com/lefnire/habitrpg/issues/319. Gamification elements are different but still periphery. Leveling a character doesn't work for everyone.

**Comment by Pandoro** [comment]
After reading the trello card I get the idea now.

I must say somehow I don't really care for it though. I set my dailies in
such a way that I WANT THESE TO BE DONE! Sorry for the caps, but that is
how I want my dailies to be. If I don't want them this badly, I make habits
out of them. As soon as I get the option to simply do something else
instead, I think I might start doing this.

So as I said, I don't care for this idea, but I guess I can make a daily
saying do not skip using todos and then I will refrain from doing it and
let other users use this if they want it so badly. Honestly I think there
are more important feature to realize right now though. Because, as I said,
if you don't want your dailies to be strict, make habits out of them.

**Comment by Yughurt** [comment]
That's why its an option in your settings.

This isn't an urgent thing but I think it would be nice. It's just like putting different colours on different tasks in calendars isn't necessary but it's nice and useful. It allows it to be used as a personal planner more than just a todo list.

**Comment by Yughurt** [comment]
The thing is with these things is to keep an open mind about how different users would like things. Sure you might personally not like it but others might. The way you're doing things is like our current education system. Yeah sure it might be best if students cared about exams and always worked hard to do well and that the competitive setting could be good. The issue is that for so many, its a pressure they don't want to deal with and so they have the "I'll didn't even try" excuse. Try and make the user get the most out of getting things done.

**Comment by StanLindsey** [comment]
I want an example of somebody who has 50 things to do every single day. =P 

That said if a lot of users are that busy and what the ability to skip dailies then it can be an incorporated feature. I have a gut feeling though that youre an exception =D

**Comment by wc8** [comment]
Didn't quite make it. Only 32.

**Comment by wc8** [comment]
@Pandoro The problem with using habits for things you really want to push yourself to do daily or weekly is the lack of a sense of done/undone. 
@Yughurt your post sounds like a reason _not_ to have a skip feature: don't take away the pressure :-)

While I can dismiss a task by disabling it for that day of the week, I prefer not to do so: besides not wanting to remind myself how easy it is, there's the chance of forgetting to re-enable it or giving up trying. Also, I want to keep the record straight. I'm not sure how disabling a task for a day might affect the progress report. 

So I'd prefer to be able to earn a chance to offset the damage. (Similar to #252's request for scheduled tasks and a way to fight them off.) It'd be enough for me if a high priority task was enough to buy a small elixir (healing about 5 HP)—an elixir only available for purchase once every two days and/or twice a week, for example. 

(22 of my tasks are still critical on vacations, so freeze account only helps me for lack of access to HabitRPG, not vacations. Let alone the ones I could still do on vacation, but wouldn't want to be penalized for. But I guess in that case, I'd just set myself a reminder to re-enable the daily tasks at the end of the week.)
