### ISSUE TITLE
Feature Request: Confirmation on Gold Spend

### ISSUE THREAD

**Issue by mgatten** [HabitRPG/habitica#158]
When you go to edit a reward, the brain sometimes makes you click the leftmost icon (especially since the edit icon isn't visible until after you've got your mouse there). It's just the spot where most apps would have you click to edit something.

The problem is that this is the spot you click to buy the reward. 

That makes it incredibly easy to accidentally spend your gold when you don't want to. 

Any time you go to spend gold a confirmation dialogue should appear saying, "You are about to spend X gold. Is this what you want to do?" 

m

**Comment by Zequez** [comment]
A warning would be nice, with the option of "don't show me this dialog anymore".
Also, a "title" when you hover over the gold icon, that says "Buy".
And an obligatory warning that tells you if you are going to die buying a reward.

**Comment by wc8** [comment]
:+1:  death warning, although since I sometimes record reward purchase after the fact, it might not help me.

**Comment by hookang** [comment]
Good idea. Added to Master list of Features #169. Issue closed for organization.

**Comment by wc8** [comment]
[Indexed on Trello](https://trello.com/c/uEo7wjkH)

**Comment by wc8** [comment]
I just wiped out all my gold not realizing that the edit to the cost of the reward item was erased by an Offline-Reconnect interruption and took an HP hit. Ouch.

**Comment by aergener** [comment]
I noticed this hasn't been implemented yet (at least on iOS). I work professionally as a developer, and I have experience with angular and node... would this be a good feature to try to tackle as a new contributor?

**Comment by Alys** [comment]
@aergener No, best that you don't work on this because your change would be unlikely to be accepted. Issues are closed because they've been resolved or are duplicates of other issues or a fix isn't desired, and the latter is true in this case. This issue was never taken out of the suggestion-discussion stage. When it was first logged, if you didn't have enough gold to pay for a Reward, the missing amount of gold would be subtracted from your health, which was very damaging if you let it happen by accident. That gold->health feature was removed a long time ago. Now, if you select a Reward by accident, the worst that happens is that you lose gold that you didn't want to spend, but you can always get it back from Settings > Site > [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values).

Because buying a Reward is a low-risk action, a confirmation step would be annoying more often than useful.

If you're looking for issues to work on, filter the issue list by the "help welcome" label. Your assistance on any of them would be much appreciated! You can also join the Aspiring Coders guild where we sometimes advertise easy issues. See [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) for more information about labels and the guild.
