### ISSUE TITLE
Party member doesn't show up

### ISSUE THREAD

**Issue by rrigor** [HabitRPG/habitica#1589]
I (rgorman) show up in my friend's account as in his party, but he does not show up in my account as in my party.

**Comment by djuretic** [comment]
What happens if you leave the party and get invited again to join it?

**Comment by meshachjackson** [comment]
Similar to my experience with #1597, though I never actually see any party members appear.

**Comment by rrigor** [comment]
Same thing. I also added a third member to our party, and she isn't showing
up for me either.

**Comment by paglias** [comment]
Actually the current behaviour is that a party member won't show up until
he/she accepts the invite.

Are you sure that they checked in the groups tab for yours invite?
Il 06/ott/2013 23:55 "beccairene" notifications@github.com ha scritto:

**Comment by rrigor** [comment]
In my case, at least my first party member accepted my invite... as I
accepted his when he invited me. In both cases, I show up on his profile,
but he does not show up on mine.

**Comment by rrigor** [comment]
I now have two members to my party... I invited them both, they both accepted the invite. Myself and the other party member both show up on both of their systems; mine shows neither.

**Comment by paglias** [comment]
They don't show up also on the members list of the party page or only in the header?

**Comment by rrigor** [comment]
They show up in neither.

**Comment by lefnire** [comment]
You caught a vestigial bug from back when we didn't have proper "already in a group" -checking on the backend. The database shows you belong to 4 parties, so what'll likely happen is when you load the page, you'll get one of the 4 setups inconsistently each time. I just removed the duplicates (which had only you in them) and left he one with 3 members. Git that a refresh & gander

**Comment by tib414** [comment]
I have the same problem. I created a party with my friend and the chars don't show up. In my party Menu hes name are showing but in him party menu my name don't show. Please help, thanks.
Im using Chrome (he too).

**Comment by noidexe** [comment]
@lefnire I have exactly the same issue. I seem to be in two parties at the same time. Sometimes the older one(with only one member besides me) gets loaded.

**Comment by lefnire** [comment]
@noidexe until we fix this, simply leave the older one when that's the one that shows up

**Comment by noidexe** [comment]
I was worried it would disband both parties. Thanks for the info, it worked! :+1:

**Comment by chillingrpg** [comment]
Hi, I don't know if this is similar but we have issues with missing party members:

1) When my party starts a quest, we always have at least 2 missing members from the quest invitation list each time. Due to our large party, it's hard to keep track of all the names that appear on the quest list. The quest initiator starts the quest because the entire list shows that everyone has accepted the invite and only after the quest has started that we discover leaving out members by accident.

2) When issue 1) happens, some party members are able to see the pending invite status of a couple of members (after refreshing the party page/chat) but others can't. The ones who can't say that the user names with pending invites are missing from the quest list (issue 1) ). 

3) Once, we have one member who was the first to accept the quest invite but issues 1) & 2) occurred and therefore was left out of the quest. 

Our group id is: 080f0d2d-0601-4a83-8da8-2ae9e4a69b40
Here are some screenshots:
![missing](https://f.cloud.github.com/assets/6725929/2238025/8a544d3a-9bd7-11e3-8b91-0a25889b6ad1.jpg)

![pending](https://f.cloud.github.com/assets/6725929/2238033/f6092dfc-9bd7-11e3-8ef1-1fb3e055b06c.jpg)

**Comment by paglias** [comment]
will reopen if it happens again
