### ISSUE TITLE
Excuses

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#1590]
I know that you are probably working on some kind of skip button for dailies, but i have an idea for it.

Excuses

When you skip a daily, a text box will pop up asking you why you are skipping it that day, the next day you will get a pop-up (or some kind of reminder of some sort) that you skipped that daily and why, and it will ask you if it is a legit reason to skip it (sometimes something seems like a good excuse at the time but the next day you think about it and it doesn't seem like it was a good idea) and if it wasn't a good excuse you lose HP for it

**Comment by wc8** [comment]
Discussion/voting of the idea to add a skip button can be found [here](https://trello.com/c/Rt13zl9x).

**Comment by AndreCaseyScott** [comment]
As much as I understand the the motive behind this idea, I don't think makes much sense in the grand scheme of HabitRPG. The Tavern is kind of the "giant" skip button anyways. 

It would become to easy to just skip instead of doing it, even with a %HP hit.  What's the point in skipping anyways? You keep your streak bonus even though it's not a streak?

**Comment by wc8** [comment]
Closing since it is in the feature tracker already. There’s also a [related idea](https://trello.com/c/NpknHuDm) for an :x:  to grey-out items that have been irremediably missed, HP penalty remaining.
