### ISSUE TITLE
Dying *after* completing task

### ISSUE THREAD

**Issue by Mr-Margaret-Scratcher** [HabitRPG/habitica#1593]
Hi, it seems that sometimes when you open habitRPG, and you should have technically already died, delays in connecting to the server mean you haven't yet lost the day's HP. Then it seems that completing  task makes everything update, resulting in your task being removed and then you dying as you should have initially.

Not a big deal, but annoying if you've managed to tick off the one thing you were planning on getting done that day, only to then have basically lost the XP that completing it brought.
##

**Comment by paglias** [comment]
Yes, when you connect to the site it uses the user saved in localstorage but it should immediately send a request to the server to get the updates, it is still happening?

**Comment by lefnire** [comment]
Every API action does authenticate > **cron** > action. So what happens if they're "dead man walking" so to speak, is they die, then their task gets checked. There may be a better way about this, this was the easiest way to go about it on the backend for the time being until we can think of something else
