### ISSUE TITLE
"Cannot POST /" after donating via Paypal

### ISSUE THREAD

**Issue by djuretic** [HabitRPG/habitica#1615]
When going back to the HabitRPG website from Paypal page (after donating), I get a blank page with this message:

Cannot POST /

The address bar shows this URL: https://habitrpg.com
Refreshing the page solves the problem. 

My suggestion is to show a "Thank you" page or something like that.

**Comment by lefnire** [comment]
Yeah, having a helluva time with this one. We're using the `return` variable [described here](https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/) (CTRL+F it), and the subsequent `rm` variable defaults to 0 which is GET. It's trying to POST to the return URL upon completion, but it's setup to GET it... [here's the code](https://github.com/lefnire/habitrpg/blob/master/views/shared/modals/buy-gems.jade#L29). Refreshing makes sense since the browser refreshes with a GET. It's benign, but might scare users.

The "Thank you" page suggestion - that's what this code is supposed to do (except it's going to homepage instead of custom thank you page). 

PS, you could have only seen that bug for one reason - thanks for your donation! :) :) PPS, I plan to merge your PRs soon. Sorry for the wait, been sidetracked for a spell

**Comment by lefnire** [comment]
fixed

**Comment by djuretic** [comment]
Great, thanks a lot!
