### ISSUE TITLE
Configuration item BASE_URL seemingly ignored

### ISSUE THREAD

**Issue by skyegecko** [HabitRPG/habitica#1621]
I'm trying to host my own copy of HabitRPG with a subdirectory in the URL i.e. http://domain/habitrpg/ however all page content (static files, links) assumes a base URL of / i.e. http://domain/
My config.json contains the following. Note the contents of the BASE_URL variable.

```
{
    "PORT":3000,
    "IP":"0.0.0.0",
    "BASE_URL":"http://domain/habitrpg/",
    "FACEBOOK_KEY":"123456789012345",
    "FACEBOOK_SECRET":"aaaabbbbccccddddeeeeffff00001111",
    "NODE_DB_URI":"mongodb://localhost/habitrpg",
    "NODE_ENV":"development",
    "SESSION_SECRET":"YOUR SECRET HERE",
    "ADMIN_EMAIL": "you@yours.com",
    "SMTP_USER":"user@domain.com",
    "SMTP_PASS":"password",
    "SMTP_SERVICE":"Gmail",
    "STRIPE_API_KEY":"aaaabbbbccccddddeeeeffff00001111",
    "STRIPE_PUB_KEY":"22223333444455556666777788889999",
    "PAYPAL_MERCHANT":"paypal-merchant@gmail.com"
}
```

**Comment by paglias** [comment]
Actually that option is used only to create the redirect url for facebook login (and will fail when using a port like http://localhost:3000).

**Comment by negue** [comment]
I think this can be closed?

**Comment by Alys** [comment]
For the record, these days the BASE_URL setting is also used for accessing the API, and some paypal stuff, and in some other code that I haven't looked at closely. I'm not sure what the situation was back when this issue was logged. However the BASE_URL is not used when crafting all the normal links within the site. It's not really the same as the <base> HTML tag, for example.

@dutchgecko, in case you're still interested in this, a root directory of / is pretty much assumed throughout all of HabitRPG's code and I believe would be very hard to change. Because this issue is so old, I'm going to close it, but if you'd still like help, comment here again and we can reopen it.

**Comment by LouisKottmann** [comment]
I'm also interested in running HabitRPG in a subdirectory.

Maybe with a clever nginx block?

**Comment by Sylvain-Delafoy** [comment]
I'm also interested.

**Comment by lefnire** [comment]
Ctrl f the project for its use. Its used for my misc things like 3rd party
callbacks (facebook, addthis, paypal), email templates, etc
