### ISSUE TITLE
Bailey looks more like she's bodiless than peeking

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1628]
Firefox on Windows 7, beta.habit. No JS errors.

The sprite for Bailey peeking out to say "psst" is positioned a few pixels too high up, making it look like she doesn't actually exist below the eyeballs:

![screenclip](https://f.cloud.github.com/assets/4501321/1368536/2a149116-39ab-11e3-80d4-7e1ad480ecc6.png)

**Comment by brightbold** [comment]
Why doesn't Bailey like Firefox? She looks great in Chrome and Safari on Mac, but here she is in Firefox Mac, where she's too low instead of two high:
![bailey-ff-mac](https://f.cloud.github.com/assets/405068/1368605/874e13e8-39b0-11e3-8173-f760a8fa9bb7.png)

**Comment by djuretic** [comment]
Firefox on Ubuntu 13.04:

![bailey](https://f.cloud.github.com/assets/1175986/1368776/7020219e-39be-11e3-8e3d-7f3da2152e07.png)

**Comment by paglias** [comment]
Firefox on Ubuntu 13.10 seems ok...
![selezione_002](https://f.cloud.github.com/assets/589911/1416292/6977fb40-3f46-11e3-88dc-edd964c3e422.png)

Maybe the new halloween screen is working better

**Comment by brightbold** [comment]
On Firefox Mac she still looks the same, albeit pumpkinier.

**Comment by brightbold** [comment]
Turns out this isn't solely browser dependent. In my fairly vanilla local install, she's perfect in Firefox. But on the live site, using an active character, the inline style on `#undefined-sticky-wrapper` is set to `height:138px` instead of `height:148px` as it is on my local, so Bailey's out of position.

I don't know what sets the height of that wrapper div (or why), but we don't necessarily need to worry about that. This would be pretty easily fixed by positioning Bailey from the bottom instead of the top. But when I went to set `.header-wrap` to `position: relative`, I saw that that had been done previously and commented out.

Locally, I couldn't see a downside to this, but I'm reluctant to reintroduce a style that was previously removed, since presumably there was a reason for it. (Although it could have been removed just because it wasn't serving any purpose.) Does anyone remember why this was commented out so I can figure out if it's OK to re-add it?

**Comment by SabreCat** [comment]
@brightbold: I vote you go for it. Take an end-user spin through the site with the change active, see if anything looks out of place. Maybe do a search through the pages to see where else that style is used, pay particular attention there. There will be additional eyes on it when you submit the pull request, after all (@lefnire does always say "be bold", and it's even in your username!).

**Comment by colegleason** [comment]
Move fast and break things!

**Comment by brightbold** [comment]
Cool. That's how I like to roll. But I'm new here so I didn't want to take the wrong tactic.

**Comment by brightbold** [comment]
Hmm. Getting a horizontal scrollbar in IE9. So I'll have to look at that more later. (Unless we're not supporting 9. I was kind of assuming 9+.)

**Comment by SabreCat** [comment]
Not sure how much we care about IE, period, but 9+ is as reasonable as it gets for IE, I guess.
