### ISSUE TITLE
Habit is really slow

### ISSUE THREAD

**Issue by Ohrange** [HabitRPG/habitica#1644]
I've searched around and can't find this issue reported recently. Apologies if this should be somewhere else. 

Habit is consistently taking over a minute to load up for me. This is way too long. I often find myself popping on to tick something off or to add a task to my to dos but by the time the site has finally loaded I've forgotten what it was. Ticking things off is slow as well and it's a nightmare if I am getting a drop. I have 64 to dos and over 50 habits, which may be contributing?

**Comment by paglias** [comment]
Do you have a lot of completed todos? Try clearing them, it has helped a
lot of people

**Comment by Ohrange** [comment]
Love the awesomely fast replies! Shamefully, I didn't have that many completed to dos but I've cleared the ones I did have. It's taking about a minute to load now. So, still painfully slow. I'm using Chrome.

**Comment by paglias** [comment]
Slow loading times are strange, we optimised the site some time ago so that
most resources are cached and even when they weren't I still was able to
load everything in less than 10secs... Are you sure it's not a connection
issue?

**Comment by lefnire** [comment]
I agree with @paglias: if you've already cleared your completed to-dos, and you don't have thousands of tasks, then slow loading time on the /#/tasks page (your main page) means something's up that we're not aware of. /#/options > groups slow-loading is a known issue, we're in the process of building a lazy-loading framework for each group tab (they're very heavy on data)

**Comment by kitsully** [comment]
I have cleared my completed todos as well. I had a lot. There was a noticeable difference, but its not as fast as it used to be a few weeks ago. Additionally, I've been getting unresponsive script warnings in both FF and Chrome.

**Comment by octern** [comment]
In addition to slow load times, I get a pause of ~10 seconds when I click my avatar in order to move between the main screen and the options screen. My entire browser is locked up during this time.

**Comment by lefnire** [comment]
I'm working on a fix to many of these performance issues right now. It will come when the Challenges feature is merged into master

**Comment by kitsully** [comment]
No pressure because habit is working great for me besides this and I may have just missed it on your blog or something. But, do you have an ETA on when this branch will be merged. 

—

**Comment by lefnire** [comment]
I'm hoping to have testers hitting it wednesday/thurs, and hope to be merged by Sunday

**Comment by CosmicPariah** [comment]
It's been unusably slow for me for maybe a week and a half. I have 40+ dailies and 40+ to-dos but it worked okay before. Thanks for looking into this!

**Comment by chadschultz** [comment]
I've had this problem for weeks--HabitRPG is painfully, painfully slow. I cleared out all my To-dos, leaving a few dozen Dailies and Habits, but the problem still persists. Chrome often kills the page because it is not responding. Firefox keeps popping up an alert dialog that says 
"A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete. Script: https://habitrpg.com/app-2b414e38.js:2 " 
Additionally, when I view the Performance tab of Task Manager, I note the memory usage of the computer, open HabitRPG (in Chrome or Firefox, I've tried both) and let it sit for a minute or so, note the memory usage, then close HabitRPG. I regularly see a different of 300-400 MB of memory being used just for the HabitRPG tab.
I use Windows 7.

**Comment by lefnire** [comment]
let's follow on #1499
