### ISSUE TITLE
21 Day Streak Achievements

### ISSUE THREAD

**Issue by peppervl** [HabitRPG/habitica#1658]
The 21 day streak achievement seems to be broken for me. I have three tasks that I have 59 day streaks showing in the task box as well as several in the 30s and 40s. I honestly thought I had to go 21 straight days on ALL my dailies to unlock the 21 day achievement. However, today, it gave me the 21 day streak achievement on a task that had a 38 day streak. It reset 3 of these dailies back to 1, but only gave me one 21 day streak achievement.

**Comment by Shaners** [comment]
The 21 day streak achievements weren't ported over since the rewrite until just recently. Unfortunately they won't be able to be retrofitted and you will only get one on the 21st streak or multiples of 21. For example if you have a 20 day streak today you should get a 21 day streak tomorrow (if you complete the daily) or if you have a 25 day streak you won't get another until streak 42.

But! What you can do is go Settings > Restore > Streak Achievements and manually set your total streak achievements. And if for some reason your daily streak on a task is messed up your can restore it by going Edit > Advanced Options > Restore Streak.

**Comment by peppervl** [comment]
Thank you! I was able to fix everything.
