### ISSUE TITLE
Challenges not showing up in Party

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1675]
I have a party with two members (one is a fake for testing). Each member created a challenge. 

First problem:
The challenge shows in each originators challenge section but not in the other player's.

![name009](https://f.cloud.github.com/assets/4084120/1442050/d39ee684-41b5-11e3-9cb5-ff64e7282e0e.jpg)

![name008](https://f.cloud.github.com/assets/4084120/1442052/da862778-41b5-11e3-8ad3-e1d412d555c3.jpg)

Second (related?) problem:
Neither challenge shows on /groups/party page for either player.

![name010](https://f.cloud.github.com/assets/4084120/1442069/1be2b51a-41b6-11e3-97df-0d5dd2e309af.jpg)

Testing with Safari and Chrome on Mac 10.8.5.

**Comment by lefnire** [comment]
This is some fantastic testing & data, thanks @bobbyroberts99! Confirmed, will hit soon

**Comment by bobbyroberts99** [comment]
Glad to be able to help. Love what you're doing. It's a very helpful tool for me and fun too.

**Comment by lefnire** [comment]
love your wikia work btw :) haven't forgotten, just hope to kill off drupal more by migrating most bits (sans wiki) to habitrpg.com, then we can make the official wikia leap

**Comment by bobbyroberts99** [comment]
thanks, that's nice to hear. I'll keep pluggin away. I like the idea of integrating as much as possible to habitrpg.com.

**Comment by bobbyroberts99** [comment]
This seems to be fixed now. All expected challenges are showing up in both member's accounts for my test party. 

Any way to collapse the space in How's everyone doing? Lots of white space. Seems like if we tighten we could avoid users having to scroll. 

If I can get my local copy working, I'll give it a try (seems like I'm almost there).

**Comment by lefnire** [comment]
v2 roll out (after we're live) will be some variation of @wc8's [comps here](https://trello.com/c/k0kSlT0Q/58-challenges-individual-party-guild-public), which will look much nicer

**Comment by lefnire** [comment]
this one is fixed, but only for new challenges. test again on v2 comin' up, and re-open if still an issue

**Comment by Doulatron** [comment]
I've got the same problem as detailed above by BobbyRoberts99 on Oct 30, 2013: "Neither challenge shows on /groups/party page for either player."

Anyone know what I can do about this? I am not as tech-savvy as BR99, but I can follow directions.

**Comment by Alys** [comment]
@Doulatron : The bug that caused the problem that BobbyRoberts had was fixed and there's been many site changes since, so what you're experiencing will be a new bug. This means that we'll need a few more details to work out what's going wrong. Can you please describe what you did, what you expected to see, and what you're actually seeing?

Is another person in the guild/party having the same problem? Is it exactly the same problem or slightly different? Is it more than one person?

 Please also paste in your User ID -- go to [Settings -> API](https://habitrpg.com/#/options/settings/api) to find it (this is **not** the same as your HabitRPG name) and include the Group ID for the party or guild, which you can find on the party or guild page.

**Comment by Doulatron** [comment]
Hi there Alice,

Thanks for your very swift reply!

My ID is 7744ee04-6372-41c9-a9fb-5d0bb3a8e944
My Group ID is 82a4a83f-3d63-45d7-9d0c-f51b792a1868

I've asked my one group member if the same thing has happened to him, but I
haven't yet received a reply.

_History_
I set up the group, then joined several challenges. I expected to see those
challenges populate to my own list of tasks and show up in the Challenges
list on the Groups page. The former worked fine, but the latter did not
happen. I do not see the Challenges that I signed up for in the list on the
Groups page.

Does that create a clear picture? If not, please let me know what else I
need to add to make it useful for you.

Thanks,

Doulatron

**Comment by Alys** [comment]
The original bug was about a person who **created** challenges for a Party - those challenges should have appeared on the Party page so that other party members could use them, but they did not appear.

What you're doing is different. You're joining challenges that other people have created. You can see those challenges on the "Challenges" page, and if the challenges belong to a specific guild, you'll also be able to see them on that guild's page. You won't be able to see them on your own "group" page - I don't know if you mean "party" or "guild", but in either case, challenges that you join are not meant to be imported into your party or into any guilds other than the guild that the challenge was created in.

**Comment by Doulatron** [comment]
Ah, I see. So if I join someone else's challenge, that will just apply to
me, is that correct?

**Comment by Alys** [comment]
Yes, that's right.

**Comment by Doulatron** [comment]
Thank you Alice! Sorry for being such a newbie. I do try to figure things
out myself, but sometimes it just doesn't come.

Thanks again.

Doulatron/Aimée
