### ISSUE TITLE
Participant count never increases

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1676]
Despite me participating in them, the Participants number on the challenges list shows 0:

![screenclip](https://f.cloud.github.com/assets/4501321/1442399/7f80b390-41bd-11e3-8e7a-5c9429d29857.png)

**Comment by paglias** [comment]
I get the count for a single challenge when I Join it...

**Comment by Shaners** [comment]
Yea mine seemed to show 0 until I joined one.

**Comment by lefnire** [comment]
fixed in ^ commit. Here's some brainstorming @paglias (nothing to worry about, just something for the mind-grapes). I added a `memberCount` attr to ChallengeSchema & GroupSchema a while back, to avoid having to calculate count every time on load for performance reasons, and I added a `pre('save')` Mongoose hook to update the count. Well it wasn't getting updated all the time. I realized it was [because of this](https://github.com/LearnBoost/mongoose/issues/964), which says: hooks only work when the object is loaded first (`Challenge.find[ById|One|etc]()`) and then `.save()`'d. `save` has to be called on the model object. It doesn't work for update operations `Challenge.[update|findOneAndUpate|remove|etc]()`. I was about to just go through and switch all our updates to find-and-update, but especially with challenges - there are many places where it's much simpler to just fire off an async update in the background (like task syncing stuff).

Anyway, let me know if you think we _should_ always use find-and-update and move a bunch of stuff to the mongoose middleware. I'm a bit back and forth on it
