### ISSUE TITLE
I would like to share my habits. Perhaps see habits of other users.

### ISSUE THREAD

**Issue by danj3ris** [HabitRPG/habitica#168]
Technically speaking, if each habitrpg user had a profile page (which they do in a way), as long as they allowed it, could not other users view their habits?

The purpose would be for motivation and inspiration.

Perhaps more could be made visible as well to other adventurers, such as progress on the individual habits, again for the purpose of motivating and advancing all of us through friendly competition and support.

I suppose in the end it could be up to the user how much information is visible to others and what remains private, maybe on an individual habit/daily/to do/reward basis.

**Comment by wc8** [comment]
Do you mean visible/shared within Party members or the general public?

**Comment by hookang** [comment]
Added to Master List.

**Comment by wc8** [comment]
[Library of Crowd Sourced Tasks](https://trello.com/c/dwIeOjZQ)

**Comment by Ferk** [comment]
It would be nice for sharing tasks if there was a way to pass a URL to a friend and get a task added to his character.

Something like clicking on a link like this and then having the "Help Joe with his stuff'" added to your TODO list: https://habitrpg.com/task/add?taskid=Help%20Joe%20with%20his%20stuff&date=2013.05.03&difficulty=normal

The same link would work for everyone (without needing to ask for userid/apitokens, adding him to your party or anything) and it would be a convenient way to share tasks. It would be useful for a public collection of tasks in a wiki page or similar.

**Comment by wc8** [comment]
@Ferk Something like or an enhancement for [Cross Profile Challenges](https://trello.com/c/k0kSlT0Q) and/or [Reward/Habit/Task Sharing](https://trello.com/c/5G7rcMpR)? 

By the way, you can now share new ideas on our [Community Site](http://community.habitrpg.com/forum).

**Comment by Ferk** [comment]
@wc8 Well, not sure if it's an enhancement or a simplification of those, since this would be just sharing a normal task, without a reward defined for it. My proposal would be easier to implement, I think. 

But if at some point tasks are extended to include an associated reward as if it was a quest, then I think it would make sense to add that property also to the task creation URL scheme I was talking about. So, perhaps this could be the first step to implement those.

It would be basically the same as the API for adding tasks that is already in place, but in the form of a HTTP GET request, with parameters in the url, instead of a POST request, and using the log-in logic from the website to determine which user are we adding the task to. If I have time this weekend maybe I could try to help implement it, if it's as easy as I think it would be.

EDIT: Btw, after I registered on the forum, this error showed up: Unable to send e-mail. Contact the site administrator if the problem persists.
Then I can't login, or register a second time (it says my username is in use)

**Comment by wc8** [comment]
OK, sounds good. For now, I added a subtask item with a link to this post on the Cross Profile Challenges card, to help avoid this simply getting overlooked.

**Comment by oswinrodrigues** [comment]
I have the same request as what [@danj3ris](https://github.com/danj3ris) originally suggested. I know the issue was created several years ago, so I'm wondering if this is now possible?

**Comment by tfojt** [comment]
Hi! Is this feature not even being considered? This is the number one question I get when new players starts playing Habitica. Like 'Can I see your habits/dailies for motivation and inspiration?'
