### ISSUE TITLE
Challenge participation changes colors, adds progress graph to challenge preview

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1685]
Created a party Challenge, and hit all its tasks with the user that created the challenge (24593eff-c4cc-43e3-950b-51f291a3468b). Now when I look at the challenge in the main list, those tasks are green, and show progress bars. The progress bars can be clicked, producing this mess (note that I clicked the Todo, and this is where the graph appeared):

![screenclip](https://f.cloud.github.com/assets/4501321/1442724/205db3a0-41c6-11e3-992e-551b0e674ff8.png)

**Comment by SabreCat** [comment]
Related to #1671: it exacerbates the lack of clarity on what that top area is all about.

**Comment by lefnire** [comment]
I'm working on a fix, but here's some rambling for posterity:

Looks like there are some issues with TaskSchema generating both `_id` & `id` separately. `_id` is generated by default from Mongoose, but `id` is our system's legacy field (and removing it would affect mobile). But for some reason, `id` isn't being passed down on challenges, which is used to create unique graphs. Graphs are created as `obj._id + task.id`, so without it we're only getting one unique graph container per challenge - which is why the first task in the list shows the graph. Anyway... _rolls up sleeves_

**Comment by lefnire** [comment]
So I fixed the charts showing on the right task. The color-changing by challenge participation for the overall tasks is _very_ deliberate - one of the strong point of challenges actually. You can see overall how the whole group is doing at particular tasks. Is there any way you can think for me to make that more obvious? I'll add a little question sign or maybe a <small> real quick so people know, and we'll start brainstorming on how to make this obvious otherwise
