### ISSUE TITLE
Master List of Features Requests

### ISSUE THREAD

**Issue by hookang** [HabitRPG/habitica#169]
Since there are many great ideas and its hard to keep track where all of them are:

Work in progress... be back to finish in a few hours.

Please continue to create a separate post for new feature requests... so its easier for to track and not one monster comment list.

I'm going to continue to maintain and keep this updated and organized the best I can.

A lot of these ideas are from Reddit as well as the Github right here. I would like to give credit, but github issues list isn't made for it.

General Features
-Sharing Common Reward Items/Habits/Dailies
-Most Popular Habits/Dailies List/For Example Lift App
-Stats Like Str, Dex, Int - When you level you get stats
-Habit Events - Everyone bike to work today or walk more - #70 
-Competitions/Quests - Battle creatures with your avatar - #140 
-Boss Fights - #66, #128 
-Translate Gaming Genre - e.g. Farming #164 
-Log/history of actions - #162, #55, #160
-Translations - #62 
-Movable Habits/Parsing Text - #151 
-Rest/Tavern/Going on Vacation - #153, #116 , #140 
-Time Zone Selection - #147, #149, #30, #26
-Optional Health Bar - #106 
-Task Prioritization/Difficulty - #53, #105, #94  
-Music/Sound Effects - #76 
-Awards and Badges - #61, #129
-Shared Tasks/Progress Sharing - #124, #29, #129 
-Completion Time - #96 
-Undo Button - #6 
-Long Term Tasks / Random Tasks - #19 
-Keep Tour Items - #44 
-Due Dates - #45, #177  
-Tags/Categories - #48 
-Random Rewards - #52 
-Partial Habits/Dailies/roll overs - #67, #131  
-Ultimate Consequences / Death - #72, #140 
-Unique items with modifiers - #137 
-Random Challenges - #140 
-Print/Offline Mode - #132 
-Locations and Themes - #110 

Groups Features
Groups Feature - #58
-Party Settings - Compete against your friends 
-Guildes - #140 

Data Features
-Data Display - #83, #65, #140 
-Password Reset - #99 
-Profile Settings - Share your avatar with public/friends - #168 
-Privacy Settings - for those who don't want to share their information
-Time Attack / Priority Task Mode / Habit Roulette - #159, #105, #53, #69, #44 , #174 
-Export Data - #68 
-Delete-able accounts - #27 
-Statistical analysis - #95

Aesthetic Features
-Colors for Rewards - #108
-Always Show Header - #100 
-Avatar Customization - #77, #97, #107 
-Different Classes/Types - #134, #74, #107 
-Confirmation of Gold Spent - #158 
-Viewing Tokens - #78 
-D&D/RPG Themed Notifications - #59 , #172 
-Mobile Browser Improvements - #63, #180 
-Icon/Avatar Marketplace - #181 
-Day Total for Habits/Rewards - #175 
-Pets - #140 
-Sync Status - #171 

Synchronization/API Features
-Remember the Milk - #149 
-Google Login/Tasks - #120, #136 
-Pomodoro
-Anki
-Myfitnesspal
-PivotalTracker
-Trello - #125 
-Geo Location - #126 
-Email Account Sync - #35, #41 
-Evernote - #95 
-Zombies Run - #182 

Chrome Extension Features
-Positive Sites - #127

**Comment by lefnire** [comment]
Would you look at this...wooooeeeee!

**Comment by kwelch** [comment]
What about a feature that gives rank to a task or habit. So the more you complete that action and the more it become a habit you have it also level increase. Similarly to skills in an rpg.

**Comment by wjordan213** [comment]
Maybe as an addition to the stats feature:
Frequently doing something like exercise would increase strength, but if a long time is spent not exercising, the strength stats would decrease. The same thing could apply to dexterity and practicing some fine skill as part of a todo list or habit or daily todo. That fine skill would have to be something like guitar or woodworking. Of course this task would have to be attributed to some kind of fine skill category by the user. The same thing would apply with intelligence and studying etc. I would like this feature because it would connect the game a lot more with the users actual life and it would encourage more consistent play in order to keep stats up. To make the user want to keep their stats up, bonuses could be given if stats are kept above a certain level for a certain period of time or after the user crosses some threshold a new reward is given.

**Comment by wc8** [comment]
If new feature requests are given a [separate post](https://github.com/lefnire/habitrpg/issues/new) it will allow for more discussion and consideration of each one. If I understand it right, this is to be more of an index. 
As hookang said,

> Please continue to create a separate post for new feature requests... so its easier for to track and not one monster comment list.

**Comment by benmanley** [comment]
@hookang – I think it's a noble idea to better organise the feature list. However, I think it would be better achieved within the existing structure of the issues list.

So long as issues are labelled "feature" they can be easily filtered as such. Similarly, adding custom labels for feature sub-categories (like the ones you suggest) would allow further filtering.

Also, closing an issue takes it out of the flow of open issues. You may inadvertently be killing discussions by closing them and thereby removing them from the default view. It also destroys the date order of issues by reorganising them into your list. How will we spot a new feature if it has been closed and added somewhere in the body of your master list? Closing an issue also prevents a feature from being closed later upon completion/inclusion.

Could a solution be for you to add to the master list without closing an issue? Then the master list could remain as a useful reference in tandem with the labelling system.

**Comment by lefnire** [comment]
Actually, why don't we move everything to a [Trello board](https://trello.com/board/habitrpg/50e5d3684fe3a7266b0036d6) - it allows user votes! Anyone wanna tackle that big task?

**Comment by lefnire** [comment]
@benmanley yeah - I think Hoo's attempt at organization is the best we could get with our current setup, simply because Github issue queue isn't suited for the discussions that have befallen habit. The reason is most tickets are feature requests, rather than bugs, and people are submitting duplicates, and there's no way of triaging importance. I think the Trello board, what with voting, will make this much better. IMO we should move this whole feature discussion over there (one person should do it so we're not stepping on toes), and keep the github issue queue open for code repository bugs (and the occasional feature-requester who stumbles here and we have to redirect them)

**Comment by wc8** [comment]
Makes you wish github had features for handling feature requests. Being able to look for and contribute to information about the app development in one place was nice. That said, I can see how it would detract from the more critical problem solving.

**Comment by lefnire** [comment]
@wc8 I was hoping you'd chime ;-) hoo is asleep other side of the world
right now. Cool, all you my friend. Hit me up if you need anything (you
have access right?) thanks to a milion

**Comment by wc8** [comment]
Access–I don't have a trello account yet. :-) I'm going to get in a couple of my dailies and then read up and see if I can jump in. Maybe hoo and I could work together.

**Comment by hookang** [comment]
Once, again thank you for your interest in this project and sharing your thoughts. 

Naturally, there is going to be a pro and con for everything.

It would be nice for Github to have that a feature for feature requests. 
Better tagging would also be nice. 

In terms of leaving discussions open. 
For now I believe it would be better to close them as there are too many features requests and overlaps and most people just want to be in and out.

The biggest priority right now are bugs, stability, and scalability of the HabitRPG service.

Rather than going through hundreds of issues. I thought a master list where all of the features were consolidated was the best way for now.

Voting on features would also be nice. 

With that being said I would like to go through and flesh out features through discussions, but that's challenging to do on this board.

Since Tyler's already setup the Trello board I'll start moving these over there. 

@wc8 I would be happy to work with you.

**Comment by wc8** [comment]
So, then, where do we direct people for tips and tricks (like how to make a HabitRPG a Mac "app" with Fluid)? [later]

**Comment by benmanley** [comment]
@hookang – Understood. Sounds like moving to Trello will make things easier all round. Hats off to you and @wc8 for stepping up to the task of migrating the feature requests!

**Comment by hookang** [comment]
Now everyone needs to make Trello accounts if they want to vote or interact :P.

**Comment by wc8** [comment]
If I understand right, also need to be invited. wc8t is my new trello user name.

**Comment by hookang** [comment]
Invited.

**Comment by wc8** [comment]
@hookang since you're collecting them here from the github issues, I'll start adding them to trello. 
@lefnire & @hookang If my mode of entry isn't quite it, let me know.

**Comment by hookang** [comment]
Roger that and Thanks!

**Comment by lefnire** [comment]
looks like trello only allows anon to comment/vote, and new cards require membership (anyone can invite, but alas - seems to require invitation). Maybe we should make that the "defacto issue / feature" request board - sort of to replace this particular ticket. While everyone can still send requests to this issue queue, we'll keep the master list there? What do you think @hookang

**Comment by hookang** [comment]
@lefnire. Exactly... everyone still shares their thoughts/request features here. We add them to Trello. People can vote on Trello. That's probably the best process for now. Since we're going to be using an honor based system anyway. After all RPGs are honorable.

**Comment by hookang** [comment]
Features are now going to be transferred from this list to https://trello.com/board/habitrpg/50e5d3684fe3a7266b0036d6 

If you would like to actively participate on the conversation on the Trello list you'll need to be added. 

I'll create a new Issue Thread for that.

**Comment by StanLindsey** [comment]
My Trello is Slappybag if you could add me.

**Comment by StanLindsey** [comment]
Or alternatively have a sub-reddit entitled HabitRPG-suggestions or similar because A. Reddit is Public, B. It allows upvoting, C. It allows discussion and D we already have one reddit so it makes sense to minimize the number of websites needed for development.

**Comment by hookang** [comment]
Yeah Subreddit is @ http://www.reddit.com/r/habitrpg - also need a reddit account to interact.

Too many sites.

Hard to maintain and organize them all.

**Comment by StanLindsey** [comment]
What I meant was that a reddit isn't invite only unlike Trello, plus the public are more likely to find it on Reddit + we already have a Reddit so its not adding to the "too many sites" count =D

Plus closing all the other threads for "organisation" i think will stop those threads getting relevant data and replies in. People will either make duplicates say if its still an issue or post here and get lost with everybody posting. 

E.g. I want to go through and write some UserStories/Design Details to flesh out some of the design of some of the suggestions, posting them in here is pointless where-as posting them in their original thread would make sense. 

I'd say use Github for bugs as thats essentially what its designed for & somewhere open like Reddit for public discussion of  features which @lefnire can then add to the roadmap as he moves forward.

**Comment by wc8** [comment]
A few thoughts on this:
- If users cannot find previous requests (or issues) whether because its on a different site or a closed issue they will create new ones; discussion gets fragmented and its hard to track the pertinent details and ideas resulting from a discussion
- If users cannot easily find where/how best to post features and issues it will increase the odds they post in the wrong place
- Sometimes bug requests are feature requests and vice versa
- Users are still going to post/comment on other sites (especially wherever they first hear about habitrpg) and in the wrong place, so some dev/support team effort is going to be involved; but it needs to be as easy as possible to redirect people to a better place to contribute or ask questions
- if maximum user input is desired, users need to be able to post suggestions/discussion anonymously, but also be able to easily register or at least know how (ask for an invite)

It would help if:
- Github & HabitRPG have a highly visible (sticky message/notification or Help (?) link which ideally would include:
  - Best Practices &/or where to go for feature requests, questions
  - Workarounds for Known Bugs
  - Link to #161 Current State of Habit or blog

I'm not sure Reddit is the answer either. (Personally, I find reddit awkward and confusing, but I might get used to it.)
Trello has the potential advantage of creating various columns for stages of a feature request: New, Needs User Input, Considering, Planned. If @lefnire were so inclined. The user could see at a glance where a particular request is. It has the potential to make a lot of requests visible at once as opposed to a long list of requests on multiple pages of github. 
(For now I'm planning on linking or at least mentioning the github issue so relevant older discussions can be looked up.)

**Comment by StanLindsey** [comment]
Yeah I share many of the same thoughts as you @wc8, hence my inclination to not like the use of trello (if its invite only that makes it extremely closed). Can somebody re-iterate why github isn't usable? You can organise by tags and such and it ties directly into the current version.

If you want a truly public addition then a report bug option on the website could allow emails to be sent to a bugs@habitrpg.com address which somebody can look at and add to github if they are needed.

**Comment by wc8** [comment]
If I understand right, you can vote and comment on trello without an invite if permissions are set that way (which they plan(ned) to do, see above). 

I think the chief thing with github may be to find away to 
1. filter out features
2. keep up with marking new requests as features (and/or give the user a way to) so bugs aren't buried
3. find a way to track feature popularity / allow votes
4. keep related discussion together... somewhat possible by closing new requests and redirecting to the original; maybe ideally, be able to merge discussions

**Comment by lefnire** [comment]
I'm totally open to whatever on this, so I'm deferring to y'all. This was
my reckonning:
- Github queue will still be very active, but we'll try to keep it to
  discussions around the code (bugs, and more "critical" features like "allow
  changing password")
- I liked Trello just as a place for holding "pie in the sky" feature
  requests for "the future of habitrpg" that everyone can vote on and
  discuss. I think it's a good place to replace just this one ticket in
  particular (the "master list"). It's super lame that it's invite only, are
  we sure that's the case? I looked at UserVoice instead, but it can get
  pricy and I'm not too keen on the interface.

**Comment by wc8** [comment]
check out: http://webapps.stackexchange.com/questions/35593/enabling-user-to-comment-using-other-login-provider 
Update: Hm... I got there via Trello help, but I'm not sure if it applies.
I'm checking with Trello help and support to see what options there might be for user commenting.

I have to say, I'm really like the possibilities for organizing requests. 
For example, with the suggestion to create a new list for integration of other apps, it should be very easy for users to find and vote on the app they want integrated. 
For now, if it's not there, users can request it via github and I'll put it in with a link/reference to the original request.
Update: If discussion can't be setup there, I can add in links between to original github issues and trello cards. @lefnire  that can make it a replacement for this index.

**Comment by lefnire** [comment]
I totally agree. Github will stay open and vibrant, we'll just keep that
Trello board to replace #169

**Comment by wc8** [comment]
I wonder if it might help to add a tag for in _trello_?
That way, rather than closed, a Feature Request could be marked as in Trello or not.

**Comment by lefnire** [comment]
added. @wc8, can you now use that tag?

**Comment by StanLindsey** [comment]
Can we open all those threads that were closed? I assuming closing is for issues that are fixed/done/ignored/non-applicable etc.

**Comment by wc8** [comment]
@lefnire, sorry, I'm new to github. How do I add a tag (label, I guess) to an issue?

**Comment by lefnire** [comment]
Top right of the ticket, under "Open" (sorry, skitch is giving me problems)

**Comment by StanLindsey** [comment]
Now that I've played with trello I really like it as an organised to do, its up to you @lefnire in the end as its your project. 

I also like that Trello is closed as then it doesn't get mobbed with duplicates, though I assume the plan was to only allow the "public" to vote. 

Then again there are work around, could have a poll on the website which has 4 options which you plan on implementing. E.g. "Whats do you want next from HabitRPG: Groups, Challenges, Customisation, APIs, Cake?"

That was each "release" can be focused a bit more as well instead of having the whole to-do list open. [/ramble]

**Comment by hookang** [comment]
Slappybag and Wc8 Amazing job with the Trello Board.

In terms of idea generation. I think everyone has a lot great ideas and we can all think of pie in the sky ideas. 

I'm not really sure what the best way to do something like this is. I should look into open source project management to see if there are any best practices.

It's awesome to see all of these ideas flying around. I just wonder if it is worth people flushing out an idea now, or later. 

The Github board was getting overwhelming now that so many people are involved and I can't see it helping any developers or potential developers to see 100s of problems and ideas. 

I'd actually like to start organizing the problem threads too e.g. Data not being saved, Can't register, etc...

**Comment by wc8** [comment]
@hookang 
Re: ideas now or later: maybe "marketing" advantages to having a place for users to chime in and discuss. If well organized it keeps us (users) looking forward to improvements, encourages patience, etc. but it does have to stay out of the developers way. 

Re: organizing threads: github labels maybe? with similar colors the color scheme? "Data Loss" "Registration bugs" 
Maybe that would be too many labels.

By the way, I wonder if you could add "trello" labels to the feature requests / issues where I've added links to Trello. I don't have access.

**Comment by lefnire** [comment]
@wc8 you're now a repo collaborator, you should have access

**Comment by Nelmalih0** [comment]
Could you add the trello links in the first post, so if we see something we like here, we can click on the trello link and vote for it

**Comment by wc8** [comment]
Would it seem strange to people to find their post edited by me? 
I can't think of another way to put the links at the top though, and that would be ideal for voting.

**Comment by hookang** [comment]
Do it. but add something like:

Edited by wc8: Vote for this feature here:

etc...

With love, joy, peace, patience, kindness, goodness, faithfulness,
gentleness, and self-control,

Hoo Kang

Test everything. Hold on to the good. - 1st Thessalonians 5:21

http://about.me/hookang

**Comment by wc8** [comment]
:+1: :+1: @hookang 

> Do it. but add something like:
> 
> Edited by wc8: Vote for this feature here:
> 
> etc...
> 
> With love, joy, peace, patience, kindness, goodness, faithfulness,
> gentleness, and self-control,
> 
> Hoo Kang
> 
> Test everything. Hold on to the good. - 1st Thessalonians 5:21
> 
> http://about.me/hookang

**Comment by wc8** [comment]
If discussion is happening on github, should feature requests be/remain closed?
I believe users _can_ still comment on a closed feature. (Note _can_: ability, not best necessarily best practice.)
If so, discussion can continue in a closed thread, but two kinds of notice might be needed:
- in the thread (maybe upgrade "*Edited by ______: Discuss in this thread. Vote for this feature here: *)
- in whatever notice explains to users how/where to post feature requests

**Comment by StanLindsey** [comment]
Trello is doing brilliantly, looks like voting is public which is great, I've reorganised so most voted are at the top. I'll be setting up a GDocs giving @lefnire the details this evening. Great job on putting all the issues on Trello guys.

Could we add a label in Github called "Sticky" for generally important threads like this and then create another thread with more information about our other resources (e.g. go to trello to vote).

Maybe have a label called "Suggestions" (Remove enhancements/Features?) so that we can keep that discussion separate and if it gets good feedback we can add to Trello manually. That would simplify between user input on here and a more organised list of to-dos/to-discuss on Trello. Thoughts?

**Comment by lefnire** [comment]
For "Sticky" let's just use the Github wiki (
https://github.com/lefnire/habitrpg/wiki) - you have edit perms Stan.
Renaming feature to suggestions, those are good ideas methinks

**Comment by wc8** [comment]
Is there a Trello limit on how many times users can vote? A couple have mentioned having issues voting on items.

**Comment by hookang** [comment]
Also weird when I tried to vote it went from 9 to 8.

**Comment by lefnire** [comment]
hoh boy.

**Comment by Nelmalih0** [comment]
I think we should also open a thread for suggestions on how the mobile app will look and work
I searched for one but I couldn't find one

**Comment by lefnire** [comment]
There's a trello column for the mobile app, there's also the github issue queue for the mobile app: https://github.com/lefnire/habitrpg-mobile

**Comment by StanLindsey** [comment]
Note; with voting I had issues with the voting button not appearing but I found that "v" is a shortcut.

**Comment by Nelmalih0** [comment]
thanks, i didn't notice that before :P

**Comment by wc8** [comment]
Just following up here. I believe all of these suggestions have been added to Trello or incorporated in some way.

**Comment by lefnire** [comment]
yeah, this ticket is deprecated
