### ISSUE TITLE
Hundreds of duplicates

### ISSUE THREAD

**Issue by loldude101** [HabitRPG/habitica#17]
This is the second day in a row this has happened to me. I go on the site, it freezes for a few seconds and then duplicates the entries I've recently made.

![December 26 2012](https://f.cloud.github.com/assets/3129563/31703/e1c72320-4fa3-11e2-8951-2c77a0fd13ff.png)

**Comment by lefnire** [comment]
Very strange! I was encountering duplicates before, I think it's a Derby/Racer bug - but I previously mitigated it with [this fix](https://github.com/lefnire/habitrpg/blob/master/src/app/index.coffee#L62), so you shouldn't be having this problem. I'm currently investigating

**Comment by loldude101** [comment]
Alright, tell me when you've finished investigating it so I can make a new account and start over.

**Comment by tanel** [comment]
Hi, I experienced the same bug moments ago. I left the HabitRPG tab open in my Chrome browser. Today, I believe it was after hitting refresh (I was offline for a while), some but not all habits were duplicated.

I played with going offline but it seems it makes no difference. Maybe the bug is somehow related to date/time? 

I believe the duplicated habits were actually the correct habits but they were rendered somehow many times. When I clicked on the trash icon on a duplicated habit, the duplicates went all grey.

But, I was not able to reproduce the bug after I wiped my account clean and entered test data.

**Comment by loldude101** [comment]
The bug comes at random times. I also have not been able to recognize any links with the bug.

**Comment by lefnire** [comment]
Man, can't seem to replicate this. @loldude101 which browser you using? It _might_ be connected to #16, which I'm still trying to pan out

**Comment by lefnire** [comment]
I think I got it, try a refresh

**Comment by loldude101** [comment]
The duplicates have disappeared, thank you very much.

**Comment by lefnire** [comment]
Woohoo!  c4099f8519f32beb9a7f1b56efe431eb6d87a90d
