### ISSUE TITLE
Leaving a challenge doesn't remove its tag from user's tags

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1704]

**Comment by ZainabAlAnsari** [comment]
yea I have that issue too

**Comment by MercuryChaos** [comment]
I have the same problem.

**Comment by wc8** [comment]
Deleting a challenge tag is very easy: just click the edit :pencil2: icon next to _Tags_, find the tag and click the trashcan icon to delete it. P.S. [new FAQ](http://habitrpg.wikia.com/wiki/FAQ#How_do_I_delete_a_tag.3F)

Since there’s a solution for this, I’m closing it. Re-open if @paglias / @lefnire if you think it’s still an issue, but I think the proposed fix (leaving a challenge deletes its tag) could be more of a problem for some users since challenge tags can be added to other items.
