### ISSUE TITLE
Cant access to account

### ISSUE THREAD

**Issue by fro0m** [HabitRPG/habitica#1745]
After login i got: Error 500: Internal Server Error (see Chrome console for more details).
actions didn't renew from yesterday!
After i relogin using facebook i have 1lvl noname character and heis in the party with my  
main character. 
http://www.evernote.com/shard/s154/sh/0f4b8775-768d-4f62-b390-769515b662ec/0ae1cb4a92c627d1c65d42fda720e2a4

my main is Konstantin....
please take action cause i need to mark my deals!!!

**Comment by erichcampbell** [comment]
I'm having the same error myself, though I am still logged in and can get to the social area, any attempt to sync or check anything off gives a new 500 error, and my dailies haven't refreshed.

**Comment by MllePandaRoux** [comment]
I have the same problem too !

**Comment by cjapplepies** [comment]
I am having this same issue too; it just started when the new challenges system was announced, so it might have something to do with that? Also, I have android 2.3 on my phone, and so I installed 2 different 3rd-party apps to use with Habit (HabitRPG and HabitAndroRPG). I cannot connect to habit through either of those apps, when they worked fine last week.

I logged in through the main page of Habit, and when I tried to log in, it just reloaded the login screen. When I refreshed my page, it brought me to what fro0m described: a level 1 character, with the standard level 1 habits, to-do's and dailies, that was in my party. There is alittle red box in the upper-right-hand corner of the browser that says: "Error 500: internal server error. See Chrome console for details."

I've tried on Safari, Firefox, and Google Chrome, and the problem persists, so it's certainly not a web-browser specific issue. Also, I tried the beta website, and it didn't work either.

Hope this helped?

**Comment by paglias** [comment]
Could you open the chrome console (ctrl+shif+j) and report here what you find there?

**Comment by themegchan** [comment]
This same thing is happening to me! All my todos, dailies, and habits are GONE but it's started over to the original character. This is really annoying because I don't think anything saved from last night and I can't pull up my todo list for today! I'm getting the error 500 as well, but my character appears in the corner. 

I tried to do the ctrl+shift+j thing but it didn't work. I'm using a mac if that helps, and I've done what the others have done as well, tried firefox, chrome, and safari, and nothing works. Not even beta.

**Comment by themegchan** [comment]
Ok, found it, here's what it's giving me: 

Uncaught TypeError: Object #<Object> has no method 'sendMessage' Browser.js:2
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1383583232585
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1383583232586
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1383583232587
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://habitrpg.com/api/v1/user/batch-update?data=1383583233081
Arguments[1]
 app-3b6110c9.js:15
2
Uncaught TypeError: Object #<Object> has no method 'sendMessage' Browser.js:2
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping:1
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1383583232588
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1383583232589
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1383583232590
Uncaught TypeError: Object #<Object> has no method 'sendMessage' Browser.js:2

**Comment by lefnire** [comment]
I think i have a fix for y'all. `TaskSchema.date` was of type `Date` (mongoose type casting is very strict, I'm still trying to figure out how to loosen it up). Well last night I was able to successfully restore tags, dates, and streaks that go lost in the Challenges migraiton. Turns out most people didn't store todo.date as a date format, but "today", "tomorrow", so I just needed to update the type as `String` instead of date. Anyway, it's throwing the error on user cron, aka morning roll-over, so y'all are getting kaibashed half-way through and it's not sending down your user. So, I'm trying to push the fix, but wouldn't-you-know-it that NPM is down (Habit's package manager). I'm going to be monitoring https://twitter.com/npmjs like a hawk, if someone catches a "it's back up!" before I do, hit me

**Comment by fro0m** [comment]
console

Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://habitrpg.com/api/v1/user/batch-update?data=1383596339174
Arguments[1]
 app-3b6110c9.js:15
Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=ht…26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey:1
12118 : BG -> CS : DISCONNECT onloadwff.js:2183
10137 : BG -> CS : DISCONNECT onloadwff.js:2183
9815 : BG -> CS : DISCONNECT onloadwff.js:2183
9751 : BG -> CS : DISCONNECT onloadwff.js:2183
9598 : BG -> CS : DISCONNECT onloadwff.js:2183
9509 : BG -> CS : DISCONNECT onloadwff.js:2183
2984 : BG -> CS : DISCONNECT onloadwff.js:2183
2086 : BG -> CS : DISCONNECT onloadwff.js:2183
2054 : BG -> CS : DISCONNECT onloadwff.js:2183
1795 : BG -> CS : DISCONNECT onloadwff.js:2183
1659 : BG -> CS : DISCONNECT onloadwff.js:2183
1586 : BG -> CS : DISCONNECT onloadwff.js:2183
1438 : BG -> CS : DISCONNECT onloadwff.js:2183
1254 : BG -> CS : DISCONNECT onloadwff.js:2183
1520 : BG -> CS : DISCONNECT onloadwff.js:2183
1146 : BG -> CS : DISCONNECT onloadwff.js:2183
1073 : BG -> CS : DISCONNECT

**Comment by MllePandaRoux** [comment]
My todos are back :) My character is now both on the left AND on my party...

**Comment by lefnire** [comment]
yeah, this should be fixed for everyone now. Unfortunately npm never came back online, so I still haven't been able to push the "real" fix - so I had to set any invalid todo dates (eg "today", "March 2013", etc) to today's date "11/04/2013". keep an eye out for those. If anyone is still experiencing this issue, comment and I'll re-open
