### ISSUE TITLE
Potions and eggs are in the wrong order for suggested workflow

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1759]
The new help text for egg hatching is great! But the current arrangement of the page is backward for it. The workflow described is to first click potion, then click egg; that'd be perfectly intuitive if the potions were just beneath the help text, then the eggs. Instead (especially with lots of accumulated drops) you have to go down to the bottom for the potion, then back up for the eggs.

**Comment by Shaners** [comment]
Yea I'm a little confused because you can click on an egg first as well no? Why click on a potion first?

**Comment by Everyst** [comment]
Perhaps the text should be changed and the page left the same. For me it makes more sense to choose what to hatch and then it's colour, not the other way around.

**Comment by bobbyroberts99** [comment]
I agree that the hatching process is a little confusing. I suggested the change because I thought it made it more clear, but I see what you mean. 

Would it be easier and clearer if  when you click an egg it highlights all potions that can be used on it and if you already have that pet the potions don't turn green? We could leave the layout as is and players wouldn't have to switch to Inventory to see what pets they have. 

Unfortunately, making that change is beyond my skill level at this point.

**Comment by SabreCat** [comment]
In my experience, clicking the potion first shows me a lot more
possibilities than the other way around. It's more pronounced for me given
that I've been collecting pet items for a while, but the nature of drop
probabilities (all eggs having even chances, potions having scaled rarity)
is going to trend things that way for everybody--I'm not an aberrant case.

Plus it makes sense in the imagined situation, as described: you take a
potion, then pour it on the egg. You don't grab the egg and dunk it in the
potion.

**Comment by Shaners** [comment]
I'm in the camp of choose the pet type then choose the colour, so egg then the potion to pour on it. I've never really though hmm I want some red pet then picked the pet type.

> Would it be easier and clearer if when you click an egg it highlights all potions that can be used on it and if you already have that pet the potions don't turn green?

Isn't this already happening? But I guess it's less likely to have a useable potion so the highlighting will happen a lot less.

What if we said something like: Click an egg and the useable potions will be highlighted below. You can also click the egg again to deselect it and instead click a potion first to have the useable eggs highlighted above it.

**Comment by bobbyroberts99** [comment]
@Shaners, I like your suggested text. You're right, it works both ways. For some reason, I thought it didn't. Oops! Do you want to do a PR or shall I?

**Comment by Shaners** [comment]
@bobbyroberts99 feel free to go for it! (The PR.)

**Comment by bobbyroberts99** [comment]
@Shaners, I tweaked the language a bit. If still unclear, I'll try again or feel free to edit.

**Comment by bobbyroberts99** [comment]
One last note: I'm new to GitHub and don't really understand it yet. My commit got added to a previous pull request. I'm guessing @lefnire will see that the PR has been modified but I'm not really sure. I'm guessing we're all good. If not, let me know if there's something else I need to do.

**Comment by paglias** [comment]
@bobbyroberts99 your commit got added to your previous pull request because it was made on the same branch, you should probably create a new branch in order to have a new pull request, usually a new pr is created for different features

**Comment by bobbyroberts99** [comment]
Thanks @paglias for trying to help, but now I can't even sync a new commit (slightly different from ba2b37d) from my mac GH client. Not sure what I did, but for now I think I'll head back to the wiki. Hope I didn't create too much of a mess.

Here's the revised instruction. Feel free to change it:

Click an egg to see usable potions highlighted in green. Click that egg again to deselect it, and, instead, click a potion first to have the usable eggs highlighted. You can also sell unwanted drops to Alexander the Merchant.

**Comment by Shaners** [comment]
@bobbyroberts99 https://github.com/HabitRPG/habitrpg/pull/1765 some tweaks to what you had above, hopefully this makes sense.

**Comment by lefnire** [comment]
normally "whatever" when PRs have accidental other commits. 2 birds 1 stone! But the first commit isn't ready for prime time. I'll merge @Shaners PR (which has your wording update, @bobbyroberts99), and will up Bob's contrib lvl. Let's count #1724 broken, I want to keep it up so we have it to reference when adding to the menu options, but note to devs not to merge

**Comment by bobbyroberts99** [comment]
@lefnire, thanks for bumping my contrib level, but all I did was make 
work for people on this one. @shaners wrote the revision and submitted 
it. If you want to count the original commit (and whatever my wiki work 
is worth), that would be fine. You could also not count the first commit 
because it more or less was an incorrect first draft (and learning 
experience). Whatever you're comfortable with. I really like the idea of 
the contributor gear and leveling system. It's very nice to have a gift 
acknowledged and very motivating (I'd like to see my name in purple or 
orange on the Tavern one day).

I've almost got my local copy running so maybe this doesn't happen in 
the future. @paglias has been trying to help me get it working 
(https://www.evernote.com/shard/s207/sh/650bd9cd-fcf0-44df-9cad-6af328d77ef8/9cab4700eccc69cb32d42912bdf32b85)

Tyler Renelle wrote:
