### ISSUE TITLE
Clicking Guild Gems does nothing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1774]
Now that I've got a few Gems (#1771 haha), I'd like to put some into the bank of the Guild I'm running, especially since I'm considering handing over leadership of the Guild to someone else. But clicking Guild Gems does nothing. This appeared in the JS console but may be unrelated:

[11:59:17.322] Unexpected value xMidYmid meet parsing preserveAspectRatio attribute. @ https://apis.google.com/u/0/_/+1/fastbutton?usegapi=1&bsv=o&size=medium&hl=en-US&origin=https%3A%2F%2Fhabitrpg.com&url=https%3A%2F%2Fhabitrpg.com%2F&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.VEeok-MGIMg.O%2Fm%3D__features__%2Fam%3DAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTMHnDe8RJ79_-cqmQP0vZOlkews0w#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh&id=I0_1384019956595&parent=https%3A%2F%2Fhabitrpg.com&pfname=&rpctoken=44542896
##

**Comment by paglias** [comment]
It seems like it's not implemented, here what is the supposed behavior? Possibility to move gems from user account to guild, to buy gems directly for the guild or both?

**Comment by lefnire** [comment]
Yeah I haven't implemented this yet - I figured it would be a pretty rare edge case, since only guild leader can dip into guild bank, and it deducts the excess (challenge prize) from leader's gems. The only case this would be useful IMO is exactly what @SabreCat described - want to xfer ownership and leave the new leader with some cash. I'm gonna prio-minor this, but put it on the docket

**Comment by SabreCat** [comment]
It can also be a discipline/accountability thing. "I want to make sure I don't use up these Gems on potions and such--I should save some for the Guild." Also the visibility of those Guild Gems to guild members is useful for generating some chatter about challenges.

**Comment by deilann** [comment]
Someone may also want to donate gems to a guild they particularly like, but are not running.

**Comment by malexmave** [comment]
> Someone may also want to donate gems to a guild they particularly like, but are not running.

This. Making it possible for non-leaders to donate gems into a guild vault could enable a guild to run a challenge with a large prize pool (or even just a bunch of regular challenges) without the leader having to pay for all of it. This could lead to way more interesting challenges and larger prize pools, leading to more encouragement for everyone to do well.

So, yeah, donating gems would definitely be a nifty feature.

**Comment by aussio** [comment]
> Someone may also want to donate gems to a guild they particularly like, but are not running.

This is exactly what I came looking here for. I wanted to support a Guild that is really motivating me and just generally being awesome. :+1:

**Comment by jamoseke** [comment]
I'd also love to see this feature implemented, for the reasons listed above. I run a party and I'd like to keep my personal gems separate from the party pool, and it'd be cool to have a system whereby challenges could have a buy-in for each contestant and therefore a larger prize pool that wasn't all at the leader's expense.

**Comment by crookedneighbor** [comment]
Guild gems are showing this popover:

![screen shot 2014-12-05 at 8 54 31 pm](https://cloud.githubusercontent.com/assets/2916945/5325867/0389c3a4-7cc1-11e4-961f-2b43a8b24233.png)

**Comment by lemoness** [comment]
If we're going to make it so that users can contribute gems to the Guild bank, we should discuss it as part of the Guild improvements/redesigns coming later this year. The feature has been requested on Trello, so it will definitely come up during that discussion -- I don't think we also need this ticket open. I'm going to close it now, but feel free to comment if you disagree and I can reopen it.

**Comment by immaterial-ctrl** [comment]
I don't disagree with closing it, but I thought I would express my interest so others would know it (my interest in the matter) exists. 

How I found this, was that I was looking for a way to send gold to fellow party members (I am not the leader), I thought it would be neat if there was a bank where resources could be shared or sent to party members, so I did a wiki search and found a conceptially similar object (the guild bank). 

If the concept of shared gold is too overpowered there could always be limits to how much money could be moved per a certain time period. Regardless of whether that would even be an aspect to such a discussion as you have referenced, I would be interested in listening to such a discussion.

Are the said discussions availiable to normal users to observe? If so where (and when) should I go to listen to the discussion. Thanks! :smile:

**Comment by lemoness** [comment]
Thanks for letting us know! Right now, the discussions aren't in a consolidated place because we aren't ready to move forward yet with the changes. If you keep an eye on Github, you'll start to see PRs and discussions happening later when we are ready to start implementing the features. In the meantime, you can comment on the Guilds Trello card https://trello.com/c/OY9PDkmn/84-guilds-v2-groups-guilds, because we will be reading over all those comments and discussions before making any changes, and will be taking them into account. I hope this helps!
