### ISSUE TITLE
Party invitation

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1785]
# Issue
- When I was in a party and got invited to another party, I didn't get any notification.
- When I left my party, I still didn't see any notification.

I have to ask the other party owner to reinvite me again.
## Possible Solution

Show invitations even if we are in a party. If clicking "Accept", it would make us leave our actual party, and join the new one directly.
##

**Comment by wc8** [comment]
:+1:  Show Invitations even if currently in Party _with confirmation dialog_

If user _accepts_ invitation:
show confirmation dialog, 
 “Do you wish to leave your current party, _The Working Wizards_ and join a new party, _The Habitual Healers_?” 
 button options: _Stay in Current Party_  or _Leave to Join New Party_

**Comment by wc8** [comment]
P.S. I think this is more of an issue to address as it could be a source of user bug reports (“I didn’t get invitation”) than an enhancement, so I’m not moving it to Trello yet, unless someone recommends otherwise.

**Comment by crookedneighbor** [comment]
Now that private messages have been implemented, I think the party invite should show up as a pm.

**Comment by Alys** [comment]
Will we need to make changes to the PM blocking code to allow that to work for users who have opted out of PMs?

**Comment by crookedneighbor** [comment]
Hmm... That is a good point. We might.

Either that, or just check if the person can receive messages, and if the person can, send it.

**Comment by Alys** [comment]
And if they can't receive messages, use the standard notification that we're using now?

**Comment by crookedneighbor** [comment]
Yes, exactly.

**Comment by Alys** [comment]
What are the advantages of sending party (and guild, I assume) invitations as PMs? Is it worth the inconsistency? We'd need more complex documentation if invitations could appear in two places, and user support would be harder, especially for less experienced users trying to help others in the Tavern. It might also be confusing if most group-related notifications appeared at the Notifications icon but group invitations appeared elsewhere.

**Comment by crookedneighbor** [comment]
I think it's worth it, because there's no indication that you've been invited to a party unless you go to the party tab. The pm could even just be 'so-and-so has invited you to party-name http://link-to-party`, so you end up going to the same place to accept it.

Same thing with Guilds. If someone invited me to a guild, I would have no way of knowing until I went to the guilds page (and I go long stretches without visiting the guilds page).

**Comment by Alys** [comment]
No, party and guild invitations show up on the Notification icon, and take precedence over the normal "new messages" notification, so the icon changes. The only time you don't get a party invitation is if you're already in a party (this issue), and that's only because the party is not able to invite you. If you find a way around that restriction (such as with the party invitation links that were in use a few weeks ago), then those party invitation notifications do show up on the Notification icon even when you're already in a party (and are a right pain in the neck to get rid of, but that's another matter, which I assume we'd fix along with this issue).

The Notification icon seems like the ideal place for guild/party invitations, because all other guild/party notifications happen there, and it means that users who have opted out of PMs can permanently ignore their inbox.

**Comment by crookedneighbor** [comment]
Oh yeah, you're right. 

I always forget about that thing, because there's no number indicator, or color change to set it apart from the icons around it, to show me I have unread notifications.

**Comment by Alys** [comment]
I'd be all in favour of the special notifications being more noticeable than the "new message" notifications. I think that would be a definite improvement. But I don't think moving party notifications to PMs would be the best way of making them more obvious. In fact, to people who get a lot of PMs, they could become less obvious. Sticking with the current notifications but improving their visibility really seems like the best way to go.

**Comment by crookedneighbor** [comment]
Oh yeah, I totally agree. The only reason I even suggested the PM route was because I had completely forgotten that there was a special notification system in place for them already, which indicates to me that the notification system needs more visibility.

**Comment by crookedneighbor** [comment]
@Alys Here's a mockup of what I was thinking:
![screen shot 2014-12-08 at 2 07 46 pm](https://cloud.githubusercontent.com/assets/2916945/5346595/51de4264-7ee7-11e4-8b16-6a8356eccb9b.png)

Here's the function I wrote to calculate the number, placed in the notifications ctrl js file. Since the new messages don't populate until a refresh (I think that's correct), this should work right?

```
    var newMessagesCountFunc = function() {
      var count = 0;
      if($rootScope.user.invitations.party)
        count += $rootScope.user.invitations.party.id ? 1 : 0;
      if($rootScope.user.purchased.plans)
        count += $rootScope.user.purchased.plans.mysterItems.length ? 1 : 0;
      if($rootScope.user.invitations.guilds)
        count += $rootScope.user.invitations.guilds.length;
      if($rootScope.user.flags.classSelected
         && !$rootScope.user.preferences.disableClasses
         && $rootScope.user.stats.points)
        count += $rootScope.user.stats.points > 0 ? 1 : 0;
      if($rootScope.user.newMessages) {
        for (var k in $rootScope.user.newMessages) {
          if ($rootScope.user.newMessages.hasOwnProperty(k))
            count++;
        }
      }

      return count;
    }

    $rootScope.newMessagesCount = newMessagesCountFunc();
```

The script could be better/I may have missed something. I started out by making it just a function, but then it was being called 3 times on page load and that seemed excessive.

**Comment by crookedneighbor** [comment]
Whoops, this really should be it's own issue. Sorry everyone.

**Comment by Alys** [comment]
(Sorry, that closing was cat on mousepad.)

I like that little number a lot!

_"new messages don't populate until a refresh"_ Correct, as far as I am aware, if by refresh you mean sync (as opposed to browser refresh). And by sync, I mean anything that causes the browser to talk to the server, such as ticking off a task (not just clicking the sync button).

That list of `if` statements... it's the sort of thing that we're bound to forget to update as soon as a new type of notification is added. I don't suppose there's any way of counting the items that have been placed in the Notification menu? I have not looked into that at all, so it could be a stupid suggestion.

We should probably not make this number live until this script has been run to clear out old buggy data: https://github.com/HabitRPG/habitrpg/pull/3936

**Comment by librarianmage** [comment]
@Alys Is this still being discussed? (Other than this statement) :smirk:

**Comment by Alys** [comment]
I'd definitely like to see the notification number being implemented. The clearing out of old buggy data from my previous comment has been done.

For party invitations, I'm concerned about people being spammed with invitations when they're in a party that they're happy with. I think that would be done often by new players not thinking about etiquette, and would happen often to those who post frequently to the Tavern.

**Comment by Alys** [comment]
Ah, the notification number idea was moved to https://github.com/HabitRPG/habitrpg/issues/4365

**Comment by lemoness** [comment]
Personally, since we have the notification counter in its own ticket, I think that this should be closed. We also send users an email when they're invited, and we're about to send them optional push notifications on their phones for the app. Given these changes, I don't think that we need to move invite notifications to PMs. I'm closing this issue, but feel free to comment if you disagree and I will reopen it!
