### ISSUE TITLE
Visiting challenge from link in group should scroll to that challenge in list

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1797]
If you click a link to a Challenge from within a group, such as one of the many and varied challenges available in the Tavern, the Challenges page opens with that challenge expanded. However, unless you happen to have picked something at the top of the list, it's not immediately evident that it's done anything besides take you to the Challenges page--you need to scroll down to what you actually want.

For the links to be useful, they need to scroll you to that challenge in the list as well as peel it open.
##

**Comment by thepeopleseason** [comment]
The ideal way of solving this issue would be to use hash locations and defined named anchors or ids. Because HabitRPG is already using some manner of hash location manipulation to evoke navigation throughout the site, I think that solution is lost to us (without a major overhaul). 

The only other alternative I can see is to create an individual challenge detail view, so challenge links go directly to the resource in question. I'm not sure, however, what navigational side-effects this solution would have on the general workflow.

**Comment by pbkhrv** [comment]
You can take the hashbang anchors back from Angular for the purposes of scrolling but it will only work in browsers that support HTML5 history API mode. Some good info here: http://stackoverflow.com/questions/20268213/can-i-reclaim-control-of-the-url-hash-fragment-from-angularjs and https://docs.angularjs.org/guide/$location

I'm thinking of a simple "scrolled-to-center" Angular directive that you can put on a div and it would execute a super simple JS that would scroll the window so that the top of the div in question is positioned in the center of the window, on a 0 timeout so that it happens after page renders.

Thoughts?

**Comment by UnexpectedMushroom** [comment]
Hasn't this been fixed?

**Comment by crookedneighbor** [comment]
Looks like it now opens the single challenge page, so yes. Thanks for noticing.
