### ISSUE TITLE
Renaming a Challenges tag marks ToDo as done the next day?

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1804]
I joined the 10K Steps challenge on 11/12. I completed the Challenge and clicked it done.

Then I renamed it's tag from Challenges to 10K. I also renamed the Contribute to Habitica tag from Challenges to wikiLive. (Is "Challenges" the default if no short name is provided? Suggestion: make people provide a tag name before they can save.)

This morning, the 10K Todo is already marked done (and the streak changed to 2) but I haven't walked those 10K steps and I didn't click it done.

The Contribute to Habitica is NOT clicked done and it's streak is correct.

**Comment by lefnire** [comment]
- the tag name is actually a required field, it looks like only browsers that don't support HTML5 required aren't triggering (who'd've thunk Firefox to be one! just checked). We'll have to do some extra "required" handling to force entry. It will default to the challenge's full name if no tag provided.
- I'd say this is one of those sporadic maybe-timezone issues, maybe day-start issues that have been floating around since the dawn of time (not challenges-specific). On the other hand, if some are acting properly and others not, likely a javascript error was thrown mid-process, preventing the rest from handling. Can you check for a JavaScript errors next this happens?

**Comment by bobbyroberts99** [comment]
I couldn't recreate the problem on my local copy. If it does it again, I send you errors.

**Comment by deilann** [comment]
If this is still a problem/can be reproduced, please reopen.
