### ISSUE TITLE
Yesterday Daily tasks

### ISSUE THREAD

**Issue by racuna** [HabitRPG/habitica#183]
_Edited by wc8: Vote for this feature here: [Record Yesterday's Accomplishments](https://trello.com/c/CaAm7APS)_
Please add a feature to check yesterday's dailies. Today I came home after midnight and i lost the chance to check some task i did yesterday, and i lost HP for that.

**Comment by StanLindsey** [comment]
+1

Eventually I imagine a week and/or calender type view would be possible so you could view what you've completed in the past, maybe check them off within the last 24hrs or so and the possibility plan for one off events in the future.

**Comment by wc8** [comment]
Trello [Record Yesterday's Accomplishments](https://trello.com/c/CaAm7APS)

**Comment by horusofoz** [comment]
@wc8 @SlappyBag Since this has now graduated to Trello I think we can close this ticket.

@racuna For further discussion see Trello Card 60 [Record Yesterday's Accomplishments](https://trello.com/c/CaAm7APS). 

Note at time of writing (10:53 PM 26/01/2013 CST) it already has 10 votes making it the 5th most highly voted feature out of 79.

**Comment by horusofoz** [comment]
Suggestion for a quick/nasty graphical implementation. When applied to dailys there would need to be a condition in place to ensure the option would only appear if the daily was not actioned the before.

![Image 1](https://f.cloud.github.com/assets/3202339/99863/2d64f336-67cb-11e2-9645-31f26e072983.png)

How one would implement the DB side of things so user recovers the lost HP, receives rewards at their original level and corrects priority is beyond me.
