### ISSUE TITLE
Replace 'relative-date' library with Moment.js

### ISSUE THREAD

**Issue by snicker** [HabitRPG/habitica#1832]
Moment JS has all the functionality of 'relative-date', why does HRPG use both?
http://momentjs.com/

**Comment by lefnire** [comment]
we're actually using moment. You won't see it on bower because we did a this big-ol thing wrapping moment & lodash to the habitrpg-shared browserify compile (some [details here](https://github.com/HabitRPG/habitrpg-shared/pull/17)), but the skinny is that lodash and moment are available in the browser. 

So yeah, let's just gut relative-date and replace it with the moment functions, good call!

**Comment by paglias** [comment]
I believe relative-date isn't used anywhere, it's in package.json but never required

**Comment by snicker** [comment]
should we trim it out? Guess this issue can be closed

**Comment by paglias** [comment]
I think so, it's used in habitrpg-shared though so we may give a look there
if it can be replaced by Moment. Will give a look to it tomorrow.

**Comment by paglias** [comment]
Fixed
