### ISSUE TITLE
Fancy text characters get mangled on @ repost

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1840]
Firefox on Win7 here--not totally sure if it happens anywhere else, but it sounds like it's preventing @wc8 from seeing chat highlights ever.

Our Legendary Scribe has a scroll character in her display name, which looks fine when called up via At and included in a chat post:

![screenclip](https://f.cloud.github.com/assets/4501321/1556459/531e0f1e-4ed3-11e3-80fd-8c075f355594.png)

But once it actually transmits, the scroll becomes a couple of "I don't get it" Unicode placeholders:

![screenclip](https://f.cloud.github.com/assets/4501321/1556466/7d7ec96a-4ed3-11e3-99d3-ec8e799a6d0b.png)

**Comment by brightbold** [comment]
I also see the double Unicode placeholders on Chrome Mac when wc8's name is typed in a comment. When trying to call it up via At or when viewing a post she's written, I see this: 
![wc8](https://f.cloud.github.com/assets/405068/1557547/2fc24b18-4f21-11e3-90c9-13fd0512aa04.png)

I only knew it was supposed to be a scroll because she mentioned it once.

**Comment by snicker** [comment]
Confirmed issue, I'll have to see if this is being caused my some library not being unicode friendly

**Comment by lefnire** [comment]
TMK it's probably Angular doing an html-safe filter, stripping emoji. Either going in (before saving it to `group.chat.0` in the database), or coming out (simply the display of `chat.user`). If this is indeed the issue, we're gonna want to keep it this way. Enabling html-unsafe means users can do cross-site script attacks and hack other users who view their chat messages

**Comment by snicker** [comment]
It should just be a Unicode character though, if not, it begs the
question of how it got there in the first place.

**Comment by lefnire** [comment]
good points, both!

**Comment by snicker** [comment]
Just confirmed, was able to set my username with an emoji, i'll check into where the problem happens ;)

**Comment by snicker** [comment]
Problem seems to be how Angular is encoding the URL before sending to the API, digging into it

**Comment by snicker** [comment]
Well, I've narrowed down the problem at least, unfortunately, I'm not an encoding guru on this kind of stuff.

It appears that the string is not getting encoded properly before leaving the client in the query string. the following string:

> @snicker 

according to http://www.url-encode-decode.com/ should get encoded in UTF8 as:

> %40snicker+%EF%91%BD

but for some reason, this gets encoded as

> @snicker+%F0%9F%91%BD

Then, on the Node side of things, neither one of these strings get decoded properly. The first result ends up as this:

> @snicker ï½

and the second result as this

> @snicker ð½

So I have no clue why it's happening, nor how to fix it.

I need an adult.

**Comment by snicker** [comment]
Well, Github helped me figure out another possible reason for this problem as I tried to post the above message:
![image](https://f.cloud.github.com/assets/221540/1564093/c653bf5e-506a-11e3-9bf6-c23c40fb16bd.png)

**Comment by snicker** [comment]
I'm guessing that's the problem. The only reason this is really an issue is that the message is being sent in the query string... if we sent the payload as JSON in the body, the issue would go away. I don't quite know how to do that either.

**Comment by snicker** [comment]
Here's a fun read:
https://gist.github.com/mranney/1707371

**Comment by snicker** [comment]
UGH... talk about chasing a rabbit down a hole... everything seems to be working just fine until the message is rendered using the ngBindHtml directive.

If I do this:
`span {{message.text}}`
instead of this:
`span(ng-bind-html="message.text | linky:'_blank'")`
unicode characters (emojis, really) are rendered correctly.

Hell, I didn't even notice it, but even highlighting works correctly, it's just not rendered right.

The problem is losing the functionality of automatically parsing urls into links in chat if we do the above. In addition, I can't seem to replicate this behavior in jsFiddle or anything.
http://jsfiddle.net/s8uKZ/9/

Stumped.

**Comment by lefnire** [comment]
I wonder is it worth it? Don't want to rain on your track if you're onto
something (or enjoying the challenge), but I'd personally toss in and say
"use emoji at your own risk"

**Comment by snicker** [comment]
At this point, probably not. Maybe one of those "fix later" sort of
things I'd enough people are bothered by it ;)

**Comment by snicker** [comment]
Issue was fixed with the implementation of Markdown in https://github.com/HabitRPG/habitrpg/commit/efe2ff5d70857d4b25bb5b5c3b455ab879200d4c
