### ISSUE TITLE
Add "Most Popular" vs. "Newest" sort options

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1841]
I thought of this with respect to the Public Guilds list (https://beta.habitrpg.com/#/options/groups/guilds/public), but it could also be handy for the Challenges list (https://beta.habitrpg.com/#/options/groups/challenges). Related to #1829, we could get some more love for less-frequented Guilds by letting people sort them in recency order. Definitely default to the current number of members sort--people getting involved with vibrant, exciting Guilds will help make their experience a positive one--but give a toggle to quickly see what's new instead.
##

**Comment by bobbyroberts99** [comment]
## Add "Category" sort option

Another way to get newbie challenges some love might be to assign challenges to a category/hashtag. Kind of like tags for tasks but globally available. And maybe instead of displaying a long list of all challenges in Tavern and Challenges, we display the list of categories and allow drill down. Better yet provide the option of how to look/sort (e.g. list by cats or name, sort by cat, name, date etc).

**Comment by lemoness** [comment]
Right now we have Guild search, which helps this, and the Pirates do a good job of managing things. I think this filter could still be a good idea, but think that we should evaluate as part of the Guilds/groups improvements that we are planning to make this year, so I am going to close this ticket. If someone disagrees, comment here and I will reopen it!
