### ISSUE TITLE
Deleted To-Dos reappearing, draining HP quickly

### ISSUE THREAD

**Issue by AndreaCs** [HabitRPG/habitica#1844]
I have created a To Do some time ago, and i realized that even after completing/deleting it, it keeps coming back, draining HPs very quickly. Simply refreshing the page makes it come back.
Is there any way around it? or i will be unable to continue at this rate.

![bug](https://f.cloud.github.com/assets/5063361/1558242/ea2f3786-4f76-11e3-860a-ac18990fe3f1.JPG)

**Comment by lefnire** [comment]
what's your UUID?

**Comment by AndreaCs** [comment]
Im not sure what the UUID is, my User ID under API, in the settings screen,
is 34b0bca6-82b2-4e74-953c-b9491dd1c049

**Comment by lefnire** [comment]
That's the UUID, thanks. I ran a script which should have fixed the issue, try again now.

The issue was (@paglias, keep an eye out with me - I'm not sure where this is triggering) that some users' tasks had the wrong type. In this case, the todo's task.type was "habit". @AndreaCs normally, To-Dos don't hurt your avatar as they go red (only Habits & Dailies do). Anyway, should be fixed now.

**Comment by AndreaCs** [comment]
Thank you!

**Comment by paglias** [comment]
@lefnire definitively very strange... if we used an array of tasks (User.virtual('tasks') is an array of ids only?) it wouldn't happen I believe

**Comment by lefnire** [comment]
`User.virtual('tasks')` is an object, the way user.tasks used to be stored, for backwards compatibility in locations that expect `user.tasks`:

```
User.tasks: {
  '24ccbad0-4fc7-11e3-8f96-0800200c9a66': {
     id: '24ccbad0-4fc7-11e3-8f96-0800200c9a66',
     type: 'habit',
      ...
}
```

The actual tasks are stored as arrays (User.habits, User.dailys, User.todo, User.rewards). We keep `task.type` on them anyway because we need to reference `task.type` periodically, where we may not know which list it's coming from (eg `lists.jade`). Well anyway, it could have been a fluke. We'll keep an eye out.
