### ISSUE TITLE
Add popovers with links to wikia

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1871]
How do I add a link to the wiki (http://habitrpg.wikia.com/wiki/Challenges) to this element 

i.icon-question-sign(popover="Challenges appear on tag-lists & task-tooltips. So while you'll want a descriptive title above, you'll also need a 'short name'. Eg, 'Lose 10 pounds in 3 months' might become '-10lb'", popover-trigger='mouse enter', popover-placement='right')

in 

/habitrpg/views/options/social/challenges.jade.

I've tried several things on my local copy with no luck and can't find an example of this in the current code. Although /habitrpg/views/shared/modals/new-stuff.jade has a link to more info, it's not on the icon).

Any hints would be appreciated. Thanks.

**Comment by lefnire** [comment]
Unfortunately, until we upgrade angular-ui-bootstrap you can't. ui-bootstrap v0.5 popovers don't accept html. I'll ping you once we upgrade.

The other thing is a mouseenter popover (note, no space) will cause the popover to disappear when you try to move your mouse _into_ the popover to click the link - because your mouse is no longer hovering over the original element. 

What you could do is make the `i.icon-question-sign` a link to the wikia:

```
a
  i.icon-question-sign....
```

and add "Click for more info" at the end of the popover text

**Comment by bobbyroberts99** [comment]
That did the trick. Thanks. 

If that makes sense, I'll start adding other links to the wiki.

#1872
