### ISSUE TITLE
Feature request: could the data export track streaks?

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#1873]
I've been periodically screenshotting Habit in case my streaks get messed up for some reason. So one of the things I was expecting Nick Gordon (don't know his github name)'s awesome export feature to do was to capture that information. But it doesn't do that and it's not clear to me whether you could use the Value column to figure that out. If the export could be enhanced to provide that information that would be fabulous.

**Comment by snicker** [comment]
hi, nick gordon here

it will be a challenge to export this information since it hasn't really been historically recorded. It _could_ be calculated for each row using a similarly defined rule to how streaks are tracked presently. At this point, when the check is done to see if a daily was completed or not, it simply increments or zeroes out the "streak" property of a task based on whether or not it was completed, and also whether it was _supposed to be_ completed that day (ie, dailies that are not set everyday).

A somewhat complicated solution to this is simply checking the delta between two consecutive completions of a daily in the export log and to see if the value falls between 0 and 2. This will only work for dailies that are completed every day of the week, and also could be slightly off based on when your "day start" time is. You'd have to make a slight correction for that as well (rounding down the completion time to your "day start" time before calculating the delta would be the solution)

**Comment by snicker** [comment]
Here, if you were to paste this in the F2 cell of the current CSV export:
`=IF(ROUNDDOWN(D2,0)-ROUNDDOWN(D1,0)<=1,1+F1,0)`
You should get a cumulative run of "streak", though this will only work for dailies that repeat all 7 days of the week.

**Comment by snicker** [comment]
closed for now, if streaks ever get tracked, they'll be exported ;P

**Comment by bobbyroberts99** [comment]
Just a thought, but could this be a feature that users purchase with gems? Basic export is free, more custom = gems?

**Comment by snicker** [comment]
@lefnire, got an opinion on the subject? I was just about to add support to export an entire user as XML...

**Comment by lefnire** [comment]
Can easily export them as JSON, just `user.toJSON()`. Plus, if they want to run a local instance, they can easily import a JSON dump to Mongo. And personally, tis a bit more human-readable than XML

**Comment by brightbold** [comment]
Well, yet another reason to get a local installation running. Maybe after Thanksgiving...

**Comment by snicker** [comment]
I can definitely do both. I just think data crunchers might want to eat XML more often than JSON.

**Comment by lefnire** [comment]
"why not both". Why do I always forget that possibility? (@wc8)

**Comment by snicker** [comment]
oh and @lefnire, I was asking more for the opinion on the gem cost that @bobbyroberts99 brought up rather than the export formats

**Comment by snicker** [comment]
![image](https://f.cloud.github.com/assets/221540/1607892/4f991796-54ad-11e3-86fc-09cabaf5e67e.png)

**Comment by snicker** [comment]
XML and JSON export added in https://github.com/HabitRPG/habitrpg/commit/c0a02eeef87e99d08ecad849ca004cb6fd802d7c
