### ISSUE TITLE
What is the workflow to update sprites ?

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1905]
Hi,

I would like to add more clothes options for men (not fair that only women can choose a different color :) ), and I started to work on 2 branches: [habitrpg/clothing_men](https://github.com/Fandekasp/habitrpg/tree/clothing_men) and [habitrpg-shared/clothing_men](https://github.com/Fandekasp/habitrpg-shared/tree/clothing_men).

The problem is that files like **spritesheets.css** are really unreadable. And I'm not sure if I should add the new images at the end of the sprite, or next to the first man armor 0 image, and then recalculate all sprites locations.

Can you explain me briefly how you handle this ? And I'll add a tip in the wiki :)

Thanks

**Comment by Pandoro** [comment]
This is pretty much related to HabitRPG/habitrpg-shared/issues/37 As there currently is just one big sprite, it is kind of hard to define a work flow. But hopefully we can jointly come up with something good, so that we can make future contributions easier.

**Comment by lefnire** [comment]
@Fandekasp I believe @lemoness actually added 4 or 5 more shirt colors somewhere, for both genders. We can pull them in, but I'd say
1. wait for classes to be finished, since that branch is completely overhauling spritesheets & css positioning - and our conflicts won't be able to be resolved because they are binary files.
2. unless we can get https://github.com/HabitRPG/habitrpg-shared/issues/37 resolved in time before classes is released, so you can add your changes at the same time

**Comment by lemoness** [comment]
Actually, those shirt colors were all Alex :) Our original pixel champ!
