### ISSUE TITLE
Zombie pets are all alone

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1907]
Firefox on Win7, beta.habit:

The Stable has rearranged for the worse, putting Zombie pets on a separate line despite having plenty of space available to hang out with their living counterparts:

![screenclip](https://f.cloud.github.com/assets/4501321/1608604/fa921698-5507-11e3-9797-193363743e09.png)

Zombies need love too. Bring them back to the cool kids table.

**Comment by paglias** [comment]
Edit: custom-menu width is set to 70%, we can remove this rule if it's not needed anywhere else

**Comment by SabreCat** [comment]
Ah yeah, this must have only started happening recently for me because I rearranged the desktop on my 4:3 monitor and knocked off some space on the right-hand side. But there's still space for it all, so at least in this case the 70% cutoff doesn't make sense.

**Comment by paglias** [comment]
I've test it and the effects would be these:

![selezione_011](https://f.cloud.github.com/assets/589911/1609040/beb18eb6-5529-11e3-8d3e-ec4a82bace45.png)

Instead of 

![selezione_010](https://f.cloud.github.com/assets/589911/1609041/c53e2e06-5529-11e3-8c0a-ee77dffc62a3.png)

And 

![selezione_008](https://f.cloud.github.com/assets/589911/1609043/cba03960-5529-11e3-8431-a7fb711861e4.png)

Instead of

![selezione_012](https://f.cloud.github.com/assets/589911/1609045/e84dd284-5529-11e3-96a3-5963baad42c2.png)

(And of course would fix @SabreCat issue)

Let me know if it's ok this way or if it's better to change only the stable behavior.

**Comment by SabreCat** [comment]
Hmm, interesting. I'd mildly prefer only the stable be fixed.

**Comment by paglias** [comment]
fixed https://github.com/HabitRPG/habitrpg/commit/17c97308f307c7177bd7e3afbcf8d7e854726299
