### ISSUE TITLE
Drops: revisit chances and day limit

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1922]
As explained in #1625.

It came out later in #1921, we should decide if we want to keep dailies with a 10+ streak having a 100% chance of causing a drop.

Also it has been proposed to revisit the 2 drops/day limit, maybe reducing the drop chance after 2 drops.

**Comment by snicker** [comment]
I suggested a maximum of 75% chance of a drop when all factors are combined

**Comment by lefnire** [comment]
Sure, whichever y'all think is best. The algo is at https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L125tL128 , shouldn't be too tough to mod. Also, 2/day will be bumped to ~5/day once we release mounts (for food)

**Comment by Alys** [comment]
Ooo! Five per day!!! :) Then perhaps it's not worth considering my suggestion to revist the 2 drops/day limit; I imagine that random chance will often spread out five drops so some happen in the later part of the day.

**Comment by AdrienLemaire** [comment]
@lefnire as said on Trello, I really think we should use that opportunity to add bonus for contribs and insert special gears.

Example:
- 3/day by default
- +1 for legendary+ contribs (right now, not really interesting for champions to try and become legendary)
- +1 for a very rare gear (magical item like protection ring? )
- +2 for a gear that can be bought on the market (food only)

**Comment by lefnire** [comment]
@Fandekasp ah, yeah sorry forgot about that convo, I'm for it. Also remembering `PER` (aka rogues) will be increase drop amounts as well

**Comment by SabreCat** [comment]
I think it's important to scale the streak bonus to drop chance way down, whether we have a 2/day limit or 10. Five guaranteed drops is just as demotivating as two guaranteed drops, if not worse.

**Comment by lefnire** [comment]
@SabreCat. Does @Fandekasp's approach, + rogue boosts, sound sufficient? Won't be too hard to add once we're there

**Comment by SabreCat** [comment]
@lefnire: I like @Fandekasp's ideas, yeah! The third and fourth bullets could roll into the Accessory system if and when that happens. The streak bonus piece of the algorithm still needs to be fixed, though, once we have an idea of what the math _should_ look like.

**Comment by SabreCat** [comment]
I've just begun studying algos.coffee, so this is an uneducated idea. What if all boosts to drop chance were interchangeable percentage multipliers upon a core value?

Such a scheme might look like this:
Base chance for a drop, with no boosts or reductions whatsoever, is 1% per click.
Task value applies a modifier. Maybe something that's pretty red, or a just-added Medium difficulty task, is worth +50%.
Perception stat from the class system applies a modifier. Say straight PER%.
Streak applies a modifier. Percentage points equal to the streak.
If there are magic items that boost drop chance, those go in as a percentage multiplier too.

Example...
- Base: 1%
- Freshly made, Medium difficulty task: \* 1.5
- Perception 30: \* 1.3
- Streak 21: \* 1.21
- Accessory with 2% drop boost: \* 1.02

= ~2.4% drop chance that click

We could tweak the math for the different pieces until we get a chance per click that feels good, but something close to the above appeals to me for the following reasons:
- Different boosts synergize, but not to excess.
- Highly modular. If, say, contributor levels add to drop chance, you just pick a scale factor for it and plop it into the chain of multipliers. Want critical hits to produce a drop chance surge? Plug in "if critical hit, x2". And so on!
- Encourages the user to keep going after things. More clicks, more chances of a good roll.
- Overall chances are kept quite low. Drops are always surprising and special: big dopamine shots!
- Easy code to read.

Thoughts?

**Comment by SabreCat** [comment]
Once the user has scored a drop, we can make the drop _type_ chances nicely modular too, if designed right.

Imagine the different types of drop as colored stones shuffled together in a bag, or as a deck of cards. The way algos.coffee looks right now, it's a 100-card stack with 40 food items, 30 eggs, and 30 hatching potions. When a drop happens, you shuffle them up and draw one: ah! an egg.

If rather than hardcode rarities for things, we build an array on the fly representing that deck, then take a Math.random() vs. the length of the array and pick the corresponding item, the relative scarcities can be adjusted according to circumstance: magic items, spells, special events, etc. Maybe around Easter there's an "egg hunt" event with a major boost to the chance of drops being eggs. During that stretch, the deck consists of 40 food, 60 eggs, 30 hatching potions. You change the probabilities without ever having to touch the numbers on food or potions!

You could even make the deck consist of the _specific items_... with flat rarities, maybe those 30 hatching potion "cards" are 3 each of Base through Zombie. Equip a magic item that says "bonus chance to find Cotton Candy food"? Add a few extra copies of Cotton Candy Food to the deck before you shuffle and pick!

**Comment by brightbold** [comment]
Love these ideas. Personally I think a 75% max is too high - as @SabreCat mentions, guarantees (or near-guarantees) are de-motivating. But I definitely think having high-value tasks and good streaks increase your chances is motivating, as long as it's still a surprise when you get a drop. I assume people thinking about this are also referring back to [the Trello issue](https://trello.com/c/7CiJVag4/305-algorithm-drop-chance-and-streak-modifier) because there were a lot of good thoughts there.

**Comment by lefnire** [comment]
I'll be plugging in here when adding quest drops, probably in ~3weeks. Stay tuned

**Comment by SabreCat** [comment]
Since this ticket is primarily about drop chance, I'm closing it with respect to [this pull request](https://github.com/HabitRPG/habitrpg-shared/pull/155). We can continue to monitor things and see if the chances feel right yet--the updated code should be much easier to tinker with.

I do still intend to futz with the drop type algorithm as well, but that's a bit further off.

**Comment by Alys** [comment]
EDIT: I was wrong. ~~If I'm reading the new code correctly, being a subscriber no longer doubles your drop cap. The drop cap seems to based only on "5" plus a value depended on your PER. Is that deliberate? If so, is it a good idea, given that double drop caps are still advertised on the site and the wiki? If it is deliberate, I can modify the wiki.~~

This is the code I'm looking at (index.coffee line 1007):
randomDrop: (modifiers) ->
......
return if (api.daysSince(user.items.lastDrop.date, user.preferences) is 0) and (user.items.lastDrop.count >= 5 + Math.floor(user._statsComputed.per / 25))

**Comment by SabreCat** [comment]
Code specific to subscriber-only features is kept in a private repository.
So you'll only see the general-purpose algorithms in the public-facing
habitrpg-shared.

On Fri, Mar 7, 2014 at 9:46 PM, Alice Harris notifications@github.comwrote:

> If I'm reading the new code correctly, being a subscriber no longer
> doubles your drop cap. The drop cap seems to based only on "5" plus a value
> depended on your PER. Is that deliberate? If so, is it a good idea, given
> that double drop caps are still advertised on the site and the wiki? If it
> is deliberate, I can modify the wiki.
> 
> This is the code I'm looking at (index.coffee line 1007):
> randomDrop: (modifiers) ->
> ......
> return if (api.daysSince(user.items.lastDrop.date, user.preferences) is 0)
> and (user.items.lastDrop.count >= 5 + Math.floor(user._statsComputed.per /
> 25))
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/1922#issuecomment-37088112
> .

## 

The Hall of Twisted Mirrors http://sabrecat.wordpress.com/

**Comment by Alys** [comment]
Sorry about that! I've edited my comment so there's no chance of anyone seeing it and believing it. :)
