### ISSUE TITLE
Pets Out of Order

### ISSUE THREAD

**Issue by aurakami** [HabitRPG/habitica#1956]
I'm not sure if it's just me or not, but the pets are no longer listed in order of most common to rare. For simplicity's sake, here is a screen shot.

![pets_bug](https://f.cloud.github.com/assets/4622000/1655811/d1824d7e-5b68-11e3-9f47-0d6e43c95520.png)

It happened more than a week ago for me, I can't remember the exact date. I figured it was an accident due to some bug fix and that it'd be fixed quick, but however it hasn't thus me reporting it. I've refreshed a lot and such and no change, just in case it was that too.

And in case it's needed:
Windows 7 and the latest version of Chrome. I have not tested other browsers but I can if it can help.

**Comment by AdrienLemaire** [comment]
I think there are no longer any rare pets, they all have the same chance to drop. Therefore, the list order doesn't make sense anymore :)

**Comment by aurakami** [comment]
Really? Aw, why the change? I feel like rarity made it more exciting so when you get, say skeleton or one of the cotton candies, it felt extra special. Not to mention more challenging which made for when you did/do collect them all, it feels like a big accomplishment.

**Comment by SabreCat** [comment]
Yeah, they're just alphabetically ordered in the Stable, and drop chances are evened out. The only difference among potions now is that some of them cost more when purchased with Gems. We've been seeing quite a few Beastmasters pop up as a result! I'd be curious to hear if people like having varied rarities, though: I feel like flattening them out constricts our design space for uncertain benefit. (@lefnire, time for one of your famous Drupal polls?)

**Comment by aurakami** [comment]
Ah, alphabetical order, that makes sense now xD I still kind of feel like the Beastmaster award should be more difficult to get, but who knows if I'm in the minority, haha. A poll would be nice :)

**Comment by lefnire** [comment]
Potion rarity was _put back in_. We evened the algos out substantially, which is an improvement, and we're discussing whether or not to remove rarity - see bottom of https://github.com/HabitRPG/habitrpg/issues/1048 (it's still an open question). @SabreCat yes, I think a poll is in order. Care to do the honors?

They're alphabetical due to a technical issue, which I couldn't find a solution for, so I'm punting this issue till later (since this is low prio). The issue is that lodash transformation of objects to arrays removes key order ([see code](https://github.com/HabitRPG/habitrpg/blob/develop/src/models/user.js#L122tL127)). TMK, it's a javascript thing - everywhere I read is just like "yeah, thats the way it is - sorry"

**Comment by SabreCat** [comment]
Oh, interesting--when was the rarity curve put back? I've definitely noticed lots more Golden Potions lately, but the value of "lately" is fuzzy.

I will take a stab at a poll!

**Comment by aurakami** [comment]
Ah, thank you for explaining and referencing that thread. I'll give it a read-through :)

That's what I thought it was at first. No rush to fix it, I understand!

**Comment by lefnire** [comment]
Rarity was out for about 3 days, we put it back pretty immediately. But the
algo is much simplified, and leveled out so it's no longer
basically-impossible to get rares (hence your golds)

**Comment by SabreCat** [comment]
Cool. One of these jam sessions I wanna pick your brain about my "stack of cards" idea...

**Comment by deilann** [comment]
I don't think this is really an issue; people seem to be fine with the stable being organized as it is now.
