### ISSUE TITLE
Typo in hover-text for 'Other' attribute

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#1990]
When in the 'advanced' tab for making a habit, in the physical/mental/social/other (?) section, the hover-text for the (?) has a typo.  

It says Eg, professional persuites, hobbies, financial, etc. 

It should say: E.g. professional pursuits, hobbies, financial, etc.

**Comment by lefnire** [comment]
Will save fixing this for a final-pass content overhaul. I just threw in class-system starter text all over the place, @SabreCat and @Xatres have been really awesome about putting in legitimate text afterwards

**Comment by SabreCat** [comment]
Aye-aye, will scoop this up as I go.

**Comment by JennaMalkin** [comment]
Thanks! :+1:

**Comment by breadstrings** [comment]
There are multiple spelling errors all over the place. Should we list them here, or have you got a handle on it @SabreCat?

**Comment by lefnire** [comment]
actually, maybe list them here. I might bet to it before sabe if I launch tonight / tomorrow

**Comment by breadstrings** [comment]
- [x] "Auto Allocate" in habit tour for class system: "If 'automatic allocation' is checked, you're avatar" => _you're_ should be _your_
- [x] "Auto Allocate": I assume the comment about "jumping the shark" will be removed once everything is done? Not everyone is familiar with this cultural reference.
- [ ] "Class gear": In previous areas the plural of class is referred to as _class'_, here it's referred to as "class's" I believe the former is more grammatically correct.
- [ ] ~~Formatting of "?" in difficulty of tasks: All text within this pop-over is in italics, was this intentional?~~
  - **Unfortunately, it's inheriting the parent DOM node's styles. I dont' think there's anything simple we can do about this**
- [ ] Death notification: "Arise, Habiteer," should remove comma between arise and habiteer as pause is not usually needed between these two words.

Will add more as I see them. ;)

**Comment by JennaMalkin** [comment]
Could 'buff'/'debuff' be briefly explained somewhere on the HabitRPG site? (spells that boost or hinder your stats)  Not all RPGs use those terms, even if they use the concept.

**Comment by SabreCat** [comment]
@breadstrings "Class gear" is legit, as is "classes' gear" (plural) or "class's gear" (singular). "Class'" doesn't ping me as syntactically correct, because the word "class" is not inherently plural.

"Arise, Habiteer" is syntactically correct for an imperative + address (you can re-parse it as "Get up, you!" not "Get up you"), plus the pause is nice for dramatic emphasis.

You are quite right about the other bits, though!

@JennaMalkin: Good call. De-obfuscating gamer terminology is always a worthy move, IMO.

@lefnire, if this is rolling out tomorrowish, this is indeed all you. It makes me sad that I can't do full work days on Habit right now, but them's the breaks :(
