### ISSUE TITLE
Can't choose 'no class'.  

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#1991]
Class System Unlocked!
Select your class. Upon level-up, you will now be able to allocate points to various stats. Alternatively, you can choose which stat your tasks represent (physical, mental, social, or "other") and drive your class automatically.

Despite what the text implies, I can't exit out of this screen without choosing one of the four classes (and let my natural choices influence my class).

**Comment by JennaMalkin** [comment]
Some more information linked to in this text about what effect each class has on gameplay might be an idea.

**Comment by SabreCat** [comment]
Definitely planning on retuning the class descriptions, they're a little out of date with respect to the design. Not sure where we're at with the flow for automatic class selection, though.

**Comment by lefnire** [comment]
Not really gonna do auto class-selection, was too difficult. We have **auto stat-allocation**, and maybe we can just add some wording like "if you don't want to play classes, just pick warrior & auto-stats. If you want your class to represent your actions, pick any class + auto-stat. If you find yourself leaning towards a particular stat over time, it might be in your favor to re-class for that supporting stat".

**Comment by JennaMalkin** [comment]
How do you plan to implement the 're-class' option?  Is it likely to cost gems?

**Comment by lefnire** [comment]
Yeah, something simple like 3gems at first. Eventually we'll move to @SabreCat's cooldown approach, which is a bit more complex. Can read [about it here](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system)

**Comment by JennaMalkin** [comment]
I couldn't see an option in the popup screen for 'auto stat allocation'/'non-auto stat allocation' - would this have come up later if I had chosen a class?  (Or was it the extra thing in the 'Advanced' tab?)

**Comment by SabreCat** [comment]
I think it was suggested in the Trello card to have a just-in-time option to auto-allocate in that popup, but at the moment that option lives in the Stats screen.

**Comment by lefnire** [comment]
When you unlock classes, it shows the modal to select class. Once you select a class, it brings you to /options/profile/stats. There you see this:

![1](https://www.evernote.com/shard/s17/sh/f68b8a55-4175-454e-aad1-8f5bd5d09a6f/26ccf23ef836bdf83487a53ac9f6d4fd/res/14531b17-5675-4d6a-93a3-22ca5b0a28af/skitch.png?resizeSmall&width=832)

I'll work on adding a Justin popover guiding you through post-selection details (what are stats, what is auto-allocate, how to change class, etc). We'll work on balancing what text goes where when, and what amount of stuff to duplicate in multiple locations (eg, auto-allocate goes in both modal & stats page? is it too much info all at once in the modal?)

I'll work on this stuff later this week, right now my priorities are stuff that will effect mobile (eg, item definitions, passive stats, apiv2, bugs) since that has to go out monday, though web can go out later in the week.

**Comment by lefnire** [comment]
added "opt out" option ("no class"). We won't be doing auto-class, only auto-stats. Justin tour is much more obvious now.
