### ISSUE TITLE
error when using a spell with mana remaining same amount as cost

### ISSUE THREAD

**Issue by ZainabAlAnsari** [HabitRPG/habitica#2006]
I'm a wizard, I used Burst of Flames which costs 10MP when I had 10MP, but gave error of not having enough MP
I clicked again to use but again an error showed up
then I refreshed the browser, to see that I had -6MP (as in lost 16MP) but the task I was trying to burn was not affected

**Comment by Nostos** [comment]
Same here, I used Shroud of Darkness (30 MP) with 30 MP left, but a "Not enough mana" error showed up.
I refreshed a few times, however, and did not notice any negative value. It's just stuck at 30 MP.

Nostos

**Comment by lefnire** [comment]
That is very strange... I can't replicate, and [the code seems quite correct](https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/rootCtrl.js#L146). (I immediately checked to see if the code was using `<=` instead of `<`, but it's using the right one...) hmm...

In any case, the -mp thing is really weird. People are seeing that under different (inconsistent) circumstances, and trying to hunt it down as we speak. In the mean time, "restore character values" button now works correctly for MP

**Comment by SabreCat** [comment]
#2012 and this are duplicates, do we think?

**Comment by lefnire** [comment]
Very possibly, that's my hunch as well - but I'm not quiet certain yet

**Comment by deilann** [comment]
I'm gonna close this -- no one's commented on it since that fix was implemented.
