### ISSUE TITLE
Incorrect stats and equipment/gear on public profiles (stuck profile, wrong / lagged profile info; previous user's info) [$5]

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#2010]
Whenever I click a member of my party, I get his or her character sheet, but displayed stats and inventory items equipped are not theirs but mine.
##

**Comment by lefnire** [comment]
Indeed, party member stats & gear isn't yet implemented. Bumping prio

**Comment by MAZimbric** [comment]
Same problem only it's everyone I click on. The picture is fine as are the stats, just the list is weird. 
![screen shot 2013-12-17 at 10 33 10 pm](https://f.cloud.github.com/assets/6211463/1770815/1047340c-679e-11e3-80f2-2183bd5d98fd.png)
![screen shot 2013-12-17 at 10 33 27 pm](https://f.cloud.github.com/assets/6211463/1770816/105a88f4-679e-11e3-8ed1-b4707a9705fe.png)
![screen shot 2013-12-17 at 10 33 42 pm](https://f.cloud.github.com/assets/6211463/1770817/105ac9ea-679e-11e3-968a-5537a84083ca.png)

**Comment by katfang** [comment]
Is anyone working on this? I'd take a stab at it if it's open and no one's working on it.

**Comment by lefnire** [comment]
You down? It's a complex issue (more than it sounds), I'll do a write-up here when I'm back at my computer, but prepare yourself :)

**Comment by katfang** [comment]
Well, I'll definitely take a stab at it. Seemed like a good place to start learning the guts.

**Comment by lefnire** [comment]
@katfang so here's the scoop. This is the "common" library of habitrpg web & mobile: [habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared). There are two files: src/content.coffee & [src/index.coffee](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee). index.coffee is what you're interested in.

Way it used to work is all functions were stored top level, and they take user attributes as parameters. It got unwieldy, so we wrapped the user object (see `wrap()`) with `user.fns` and `user.ops`.

`user.fns` are all user-based helper functions, `user.ops` are all operations which will perform the same code both on the client (for speedy in-browser updates), and then on the server (to persist the changes). Well `user._statsComputed`, which is a wrapped attr-getter, requires the user be `.wrap()`'d. Only the main user is wrapped, not other players. We should use one of two solutions:
1. Wrap profiles after you click their name (which brings up their modal) so they have the `_.statsComputed` property. Probably here in [clickMember](https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/groupsCtrl.js#L21)
2. OR bring _.statsComputed back outside again, so we don't have to wrap user objects, and instead pass in the user object as the an argument. I'm concerned with the performance implications with this, since then every time any property on the user object changes, Angular will re-calculate everywhere a stat exists in the HTML

**Comment by lefnire** [comment]
I'm pushing a tentative fix (see two commits above), which wraps the member profiles when you click them. I want to keep an eye out for performance to make sure this doesn't slow things down. Additionally, there's a bug with party-member gear. On first party modal click, it's correct. Second party modal click gives the _previous_ member's gear - it's always one behind. Don't know if it's always been this way, `items.gear` has nothing to do with the `wrap` function, so my hunch is it's always been this way

**Comment by katfang** [comment]
@lefnire Just tested it out. It only bugged once. After a refresh, it worked perfectly.

**Comment by lefnire** [comment]
well, the first click is correct. Then every click after lags one member behind. So click A, √. Click B, see A. Click C, see B.

**Comment by katfang** [comment]
Yeah, I meant the clicks after that were fine. Here's what I did:

First try:
Click a: good
Click b: got a [only bad one]
Click c: got c
Click a: got a
Click b: got b

Refresh and try again
Click d: got d
Click e: got e
Click f: got f
Click b: got b

Everything seemed fine in the Tavern, too.

**Comment by mczuchnowski** [comment]
Confirmed. After a refresh, all works fine.

**Comment by lefnire** [comment]
We're talking about _just the gear_, right? All the stats are legit, I'm talking about the equipment listing

**Comment by mczuchnowski** [comment]
OK, yeah, I see that now. I didn't look at equipment close enough.

**Comment by Donaithnen** [comment]
For me it seems that after a refresh the first party member you view will have correct equipment. For each subsequent click however, the Nth person you view will show the equipment for person N - 1. So if you click on the same person twice it will "catch up" and show you the proper equipment, but if you keep cycling through a list of people, never clicking the same one twice in a row, you will always see the wrong equipment. (But as previously stated, the stats are correct, only the equipment is messed up.)

**Comment by deilann** [comment]
Known bug. It's not just party members. It's anyone you ever look at. Try
it in the Tavern, too!

**Comment by deilann** [comment]
Oh lol, sorry, I thought this was a new ticket in my inbox. Yes, this is what this ticket is about. It is known, just low priority.

**Comment by deilann** [comment]
Updated title for more search-ability!

**Comment by itokro** [comment]
Badges are messed up too, but not every time. Copying info from the ticket #3746:

If I view Person A's profile and then view Person B's profile... sometimes Person B's badge list will show me Person A's badges, but sometimes it'll show me Person B's badges. I can't confirm what determines whether the badge information is right or not, but it seems as though in general, if Person B has "better" badges, they're more likely to be correctly reported. For example, if Person B is Bailey, I see the "TownCrierNPC" badge on viewing her profile. Meanwhile if Person A is Bailey and Person B is not Bailey, I still see the "TownCrierNPC" badge on viewing Person B's profile.

**Comment by deilann** [comment]
How's that @itokro ? Clearer?

**Comment by itokro** [comment]
@deilann Certainly clearer to me - hopefully similarly improved for others! Thank you!

**Comment by deilann** [comment]
np! :)

**Comment by lefnire** [comment]
should be fixed in https://github.com/HabitRPG/habitrpg/commit/31fdc866c3682308447ff4ee1a4fb6d18e75f806
