### ISSUE TITLE
Negative Mana

### ISSUE THREAD

**Issue by Draayder** [HabitRPG/habitica#2012]
I don't know what happened but I'm sitting at -3 mana right now. All I can guess is that somewhere it double activated a skill (I've only used Pick Pocket) and pushed me into the negative.

**Comment by Qrystal37** [comment]
I have negative mana right now too. I was pretty sure I had 23 before using Backstab (which costs 15) and I now have -8, which makes me wonder if the subtraction was set up backwards: cost - currentmana instead of currentmana - cost.  (But I could be remembering wrong about the 23...)

**Comment by lefnire** [comment]
hmm.. good guess, but alas - [code looks correct](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L385). I wonder if it has to do with `_cast` at that scope... javascript scope issues maybe...

**Comment by FLJIM560** [comment]
I was double charged MPs. I used the pickpocket spell twice. Each time I was charged 20MP. The posted cost for the spell is 10MP.

**Comment by lefnire** [comment]
_think think think_ *taps head*.. I can't replicate this, could it possibly be that people are double clicking the spell? If so, we need to safeguard that obviously... but I can't think on what otherwise might be the issue, and I'm looking through this code and it looks correct. I'll keep perusing

**Comment by cleave29** [comment]
I backstabbed a daily and the first time it activated the results 3 times (+ gold, + XP, - mana) and then I backstabbed another daily and it activated twice.

**Comment by PaulRosenfield** [comment]
I had 13 MP left and I used Burst of Flames (10 MP) on a To-Do, leaving me with -7 MP.

**Comment by PaulRosenfield** [comment]
Also, are Mana Points supposed to restore to full after you level up? If so, then mine didn't. If not, then the usefulness of having more than 50 maximum MP is rather questionable. I have a maximum of 172, which I will never actually reach unless I go 17 days without casting even my smallest spell.

**Comment by PaulRosenfield** [comment]
Ah, here's a potentially interesting discovery: I was at -7 MP after leveling up. Because I leveled up, I got an extra stat point, which I spent on intelligence, thereby increasing my maximum MP from 172 to 174, AND increasing my current MP from -7 to -6.

I should also note that, despite my mana points being negative, my mana bar appears to be full.

Not sure if any of this is related or not, but I figured I would share it just in case.

**Comment by FLJIM560** [comment]
I'm confident that my situation was not caused by double-clicking the
spell. To make sure, that's why I used the spell twice yesterday and again
twice today.

I began yesterday with 91 MPs. I clicked the pickpocket spell and checked
off a task from my Dailies. My Gold went from 600+ to 1100+ and my MPs
dropped to 71.

A few minutes later Hrpg stopped responding, Chrome prompted me to kill the
page. When I reloaded Hrpg, my Gold was back to normal and MPs still showed
71.

Assuming I double-clicked the spell, I clicked pickpocket again. After
checking off a Daily, my MPs fell to 51. I reloaded the page and MPs
increased to 61.

Today my MPs started at 71 (increasing by 10 overnight as expected). I
clicked pickpocket, my Gold approximately doubled and my MPs fell to 51. I
reloaded the page. My Gold came back down by MP stayed at 51.

Before writing this post, I tried the spell again. Prior to clicking
pickpocket my MPs were 51 and my Gold was 236. I checked off a Daily, my
Gold increased to 428 and my MPs fell (correctly) to 41. I reloaded the
page. My MPs fell another 10 to 31 and my Gold increased to 620. I did
nothing but reload the page and my MPs fell by 10 and my Gold rose 192.

JG

**Comment by Draayder** [comment]
Just replicated the bug, I cast pickpocket on a daily while at 18 mana and got bumped back down to -3 again. It looked like it gave me 2 different gold received messages but I'm not sure if that's intentional to show the additional gold from pickpocket. I made sure not to double click, is there maybe some conflict with the task completing doubling the intended effects? Next time I'll try to get a screenshot of immediately after it double charges. I'm using chrome if that helps any.

**Comment by lefnire** [comment]
Tested locally, the issue is definitely when you cast the spell on the
checkbox, not on the task body (I didn't even think about people casting on
the checkbox, good find). I'll start debugging tomorrow-ish

**Comment by clmmerrill** [comment]
Burst of Flame says it cost 10 MP. When I used earlier I thought I went from 73 to 53. I tried again to see if I was imagining things. I now have 33 mp. After selecting the spell,  I checked on the checkbox both times, when I completed the tasks. I am using chrome. No pictures, sorry.

**Comment by Nostos** [comment]
I'm afraid it happened to me too :p
I cast "Burst of Flame" (10 MP), but instead of moving from 15 to 5 MP, I found myself at -16...

Nostos

**Comment by FLJIM560** [comment]
> Tyler Renelle
> 
> Tested locally, the issue is definitely when you cast the spell on the
> checkbox, not on the task body (I didn't even think about people casting
> on
> the checkbox, good find). I'll start debugging tomorrow-ish

After selecting Pickpocket, I clicked on the task, rather than the check
box this morning and all went well. I got a drop, 100+ Gold and 10 MPs were
deducted.  Then I went back and clicked the check box.

Does the check box bug find get me a contributor badge? That and
Beastmaster are the only ones I need (83-90).

JG

**Comment by Draayder** [comment]
Could it be that the code is reading the incomplete and the complete daily as two different values for spell.target and causing it to repeat the _cast? Completing it would alter the completion and value variables so if it's reading them both simultaneously it might look to the system like two independent dailies got completed. I tested it on habits while clicking a + and it didn't double cast but it does double cast on to dos when the check box is clicked so I'd assume the issues is something with the completion variable rather than the value variable. 

Locking people out of being able to click the check box with a spell seems like the easiest and fastest solution but I'm not sure how doable it actually is and the underlying problem might remain. It might be fixable with css if you can limit the selection to just the body of the task for spells but I don't know css that well to offer more specifics (all I know really well is php).

**Comment by lefnire** [comment]
@Draayder good observation, I'm adding in `$event.preventDefault()` to prevent checkboxing for now. Your'e right, it's triggering the click event twice - once for the checkbox (model=task), once for the task behind it (model=task). I'll look into this in the near future, but preventing checkbox will work fro now

**Comment by aghendrix** [comment]
Sometimes I use a skill right before I'm going to check a task as done. So I use the skill and click the checkbox right after. What I didn't know was that the skill stays selected even after use, and due to some kind of bug, if I click the checkbox it instead of checking uses the skill again, even if there is not enough mana.
