### ISSUE TITLE
Make it possible to unlock header

### ISSUE THREAD

**Issue by jaywink** [HabitRPG/habitica#2020]
Since the latest updates the header (showing xp, hp and mana) is locked to the top of the browser window. On a small screens this is not ideal - for me it's taking 1/4 of the vertical browser visible area.

Suggest possibility for user to configure whether it is locked or not? Already it is possible to hide it completely, though that is not ideal since then nothing is visible.

Any idea if this UX flow is discussed anywhere or could the settings be added to control this to the current UX?

**Comment by lefnire** [comment]
ceea1b5 adds the option to disable sticky header. I'm closing this since that's added (pushing now, 5m); however, the previous few commits (1) fix header to use jquery.sticky instead of bootstrap.affix, which should work much better; (2) makes the header un-sticky when on mobile devices. So theoretically, you shouldn't need to disable sticky header. Re-open if still experiencing issues
