### ISSUE TITLE
Attribute tags in tasks need popovers

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2044]
Win7 on Firefox, beta.habit, no console errors.

At present, mousing over one of the buttons to associate a task with an attribute doesn't display any additional information. There's even a ? bubble on Other, but it doesn't provide anything, whether the button is selected or unselected.

It would be great to have some brief suggestions or examples pop up on each of these, so users have a starting point for choosing which tasks get what.

_edit by Alys:_

[This comment from Lemoness desccribes what we want to do for this issue:](https://github.com/HabitRPG/habitrpg/issues/2044#issuecomment-223729060)

Reading through this discussion again, it sounds like the consensus is to change the names of the attributes to reflect the stats. Let's do that. I'm happy with deilann's proposed text:

Strength: e.g. relating to exercise and activity
Intelligence: e.g. relating to academic or mentally challenging pursuits
Perception: e.g. relating to work, or financial tasks
Constitution: e.g. relating to health, wellness, and social interaction
##

**Comment by DanielTheBard** [comment]
Agreed. Though for me, the ? bubble on other worked once I clicked on it. 
OS X Lion on Chrome.

The correlation between Physical, Social, Mental, Other and STR, CON, INT, PER should be made more apparent to the user. And as @SabreCat said, examples should be given of each.

**Comment by SabreCat** [comment]
Will fix this up in [this branch](https://github.com/HabitRPG/habitrpg-shared/tree/sabe/attributes).

**Comment by deilann** [comment]
@SabreCat Can this be closed?

**Comment by SabreCat** [comment]
@deilann: Alas, no. This is still one of my dangling tasks for that project (along with taskbased points backfill).

**Comment by deilann** [comment]
You can do it!

**Comment by Alys** [comment]
I'm unassigning SabreCat and adding the entry level coding tag. I'll advertise this in the Aspiring Coders guild when we've sorted out words.

To see the buttons that this issue discusses, you must go to your stats page and select "Automatic Allocation" then "Distribute points based on task activity", then edit any task and go into "Advanced Options". See screenshots below for the four buttons and the pop-over that shows when you hover on "Other".

@lemoness Would you like to suggest wording for the other three buttons?

![screen shot 2015-05-18 at 6 51 27 am](https://cloud.githubusercontent.com/assets/1495809/7672126/8619d0ea-fd2a-11e4-8b6c-de3e1ba82761.png)
![screen shot 2015-05-18 at 6 51 34 am](https://cloud.githubusercontent.com/assets/1495809/7672127/8624db34-fd2a-11e4-87d5-594234f8604e.png)

**Comment by lemoness** [comment]
Not totally sure they are necessary, but here's a quick stab at them -

Physical: "e.g. relating to health, wellness, and exercise."
Mental: "e.g. relating to academic or mentally-challenging pursuits."
Social: "e.g. relating to social interaction"

**Comment by deilann** [comment]
They should also make clear what stat they are connected to because it
really isn't obvious. Personally, I'd prefer we didn't proscribe which kind
of tasks relate to which stats. It'd be better in my opinion for the
buttons to be the stat it will go towards and the popover provide ideas as
to what kind of tasks could go towards those stats.

So like:

Strength: e.g. relating to exercise and activity
Intelligence: e.g. relating to academic or mentally challenging pursuits
Perception: e.g. relating to work, or financial tasks
Constitution: e.g. relating to health, wellness, and social interaction

**Comment by deilann** [comment]
The reason I think this is because when I was using this system, it was
very frustrating because for it to realistic work for me, I needed to
completely work-over what the attributes "meant." With my health problems
the divvies went something like this:

Strength: Cleaning and physical tasks, but not exercise.
Intelligence: Mental tasks, learning, etc.
Constitution: Meds, self-care, anything that would make me "damage
resistant"
Perception: Money related tasks, because PER gives you more drops and gold.

But that doesn't fit at all into "Physical" "Mental" "Social" "Other" and I
think it's a little weird for Habit to proscribe what the tasks should be.
Obviously, people can still use them for whatever they want, but it
certainly felt weird to put my meds under "Social" and the weirdness made
it more difficult to quickly sort tasks.

**Comment by Gbear605** [comment]
This isn't relevant anymore as tasks don't have attributes. This can be closed.

**Comment by nicolevonvon** [comment]
Hi, has this text been confirmed? It's the last task that hasn't been worked on in entry-level-coding and since I haven't worked in the environment yet I'd really like to tackle something basic before something more meaty...

**Comment by Alys** [comment]
@nicolevonvon It might be best to wait for final confirmation for this one, but you might like https://github.com/HabitRPG/habitrpg/issues/5979 which is ready to be worked on.

**Comment by nicolevonvon** [comment]
Thanks Alys will do so!

**Comment by librarianmage** [comment]
What is the current progress on this?

**Comment by Alys** [comment]
I think @deilann makes some good points about not overly specifying what they should be used for, and also about the need to state which attribute they affect. 

Do we want to keep it as simple as this?

Physical: "Boosts your Strength attribute."
Mental: "Boosts your Intelligence attribute."
Social: "Boosts your Constitution attribute."
Other: "Boosts your Perception attribute."

**Comment by librarianmage** [comment]
@Alys I think that makes sense, or it may make sense for the labels to just
be what they raise ("Strength", etc.)

**Comment by Alys** [comment]
@MathWhiz I think there's some benefit in not having the attributes displayed directly on the buttons. I think we want players to focus more on what kind of task it is, rather than on what attribute is affected (although providing the attributes as a hint on hover is still a good thing). If they want to focus on specifically what attributes are increased, then they're probably better of not using automatic task allocation.

Contrasting opinions are welcome! I'm not totally sold on what I've just written. :)

**Comment by librarianmage** [comment]
@Alys I think that makes sense.

**Comment by simbs** [comment]
I don't use automatic task allocation, but Physical/Mental/Social/Other doesn't make much sense to me, even unrelated to the attributes. "Social" especially. If the only point of having these is to increase the corresponding attributes, why not just give them those names? Even for people who want to focus on which attributes are increasing, it makes sense that they might want to take the decision out of their own hands, and add more difficulty to the game. Ie if they want to increase attribute X, they have to complete tasks assigned with the corresponding thing, and they can add it to the most difficult ones. For what kind of task it is, the user can add it's own customized tags.

Of course if these are the categories most people would like to group things into, then what makes sense to me doesn't matter.

**Comment by kdcarlsen** [comment]
Is this something that still needs work?  I'm looking to get involved.  Also how can I tell if there is a pull request associated with this issue?  I don't think there is but I'm not sure.

**Comment by librarianmage** [comment]
@kcswordfish My current understanding of this issue is that it is still under discussion, so if you have any suggestions, feel free to share them!

In most cases, if one submits a pull request associated with an issue, they will reference it using # notation, which will put a message in the comments of the issue.

**Comment by kdcarlsen** [comment]
Noted, thank you!

Any suggested tickets for somebody trying to get a feel for everything?

**Comment by librarianmage** [comment]
I would look through the "Help Welcome Now" issues, as they are generally
ready for work to be done on them.

**Comment by kdcarlsen** [comment]
Will do, thanks

**Comment by lemoness** [comment]
Reading through this discussion again, it sounds like the consensus is to change the names of the attributes to reflect the stats. Let's do that. I'm happy with deilann's proposed text:

Strength: e.g. relating to exercise and activity
Intelligence: e.g. relating to academic or mentally challenging pursuits
Perception: e.g. relating to work, or financial tasks
Constitution: e.g. relating to health, wellness, and social interaction

**Comment by librarianmage** [comment]
I can do that!
