### ISSUE TITLE
Tie UI placement of task attributes to user's class system options

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2045]
As someone who's excited to make use of the "Auto-allocate" feature for class system attribute points, it's frustrating to me that every task takes 2-3 extra clicks to get at the attribute assignment. For users who like this part of Classes, this isn't an Advanced Option, it's a core feature.

I would suggest moving the attribute tags out of the collapsed Advanced Options, in this scenario:
- The user has "Automatic Allocation" turned on
- The user has not chosen to opt out of the class system

For other users, leaving it under Advanced Options is preferable.

**Comment by Pandoro** [comment]
I would rather consider the comment @wc8 has made elsewhere. The idea was to select a subset of all tasks and then set an attribute for all of those tasks. That way I could select for example all tasks I want to set to social and then click on a social button, or all for easy etc. I guess both this and what @SabreCat proposed together are not mutal exclusives, but I would prefer the select and set option.

**Comment by lefnire** [comment]
Yeah, @wc8's feature suggestion is multi-select batch operations (tags,
attribute, difficulty, etc). I'm currently thinking on a solution

**Comment by brightbold** [comment]
@wc8's suggestion is great. Really editing of anything under tasks is getting unwieldy, with challenges adding more and more tags to stretch down the page. I suspect that since we all use Habit differently, trying to determine which elements deserve to be at the top will be hard ("I love difficulties and never use tags!" "No, tags are awesome! Extra Notes are stupid!") so the bulk edit seems to solve a lot of problems at once.

**Comment by SabreCat** [comment]
I'd be happy with #2186 here.
