### ISSUE TITLE
habitrpg android client

### ISSUE THREAD

**Issue by no1yudkno** [HabitRPG/habitica#2068]
the avatar both in the app and on the widget no longer show my armor or any of the changes ive made to my avatar on the website. it was working fine till a few days ago. if i try and rebuy the armor i had it says "the server wasnt found. please check your host settings."

**Comment by lefnire** [comment]
[MagicMicky](https://play.google.com/store/apps/details?id=com.magicmicky.habitrpgmobileapp) or [OCDevel](https://play.google.com/store/apps/details?id=com.ocdevel.habitrpg)? If @MagicMicky, that's the unofficial 3rd party app, and he'll need to update it for APIv2. Mickael, see [APIv2](https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/apiv2.js#L33tL131) routes. Let me know if you need help or more full documentation. I plan to write documentation soon, but I'm pretty swamped so see how far you can get with those route defs. See https://github.com/HabitRPG/habitrpg/issues/1977 for background on this move. In short, most basic APIv1 routes are still supported (scoring, edit-task, delete-task, add-task); but non-core routes have been migrated.

@uvwxy @pjf @wizonesolutions

@no1yudkno OCDevel is the official app, and always the most up-to-date (since I dev it concurrently with the website). Incidentally @MagicMicky's is by all accounts _better_ - it'll just have 1-2week lag periods when I make critical server updates.

**Comment by no1yudkno** [comment]
it was the magicmicky, is there an official widget i would use that if there was one available

**Comment by lefnire** [comment]
Nay, no widget on the official (I'm not sure of PhoneGap supports that). I'd say continue to use MM, but you'll have to wait till he updates. Follow [his Twitter](https://twitter.com/magicmicky) might be best bet

**Comment by no1yudkno** [comment]
thanks again im very happy with the program and everything and your awesome at responding keep up the good work

**Comment by lefnire** [comment]
:) :)

**Comment by MagicMicky** [comment]
@lefnire Thanks for your help (and your comment about my app).

I'll try to update my app as soon as possible, but with Christmas and the new year comming, you might have to wait a little bit!
