### ISSUE TITLE
SSL for HabitRPG locally

### ISSUE THREAD

**Issue by mr-flibble** [HabitRPG/habitica#2075]
Hi, I'm sorry if this is the wrong section for questions, but I would like to set habit rpg localy under https like you have on habitrpg.com. I have one old local instance under Windows with stunel, but its very slow. 
What is easiest solution to run habit rpg under SSL on Linux or Windows? Can you posilby add  to readme? Thank you!

**Comment by Alys** [comment]
Sorry @mr-flibble, we should have answered this a long time ago. In case you are still interested, you can read about various ways of setting up HabitRPG locally on the wiki: [Setting up HabitRPG locally](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally). You might also like [Guidance for Blacksmiths](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths). I'm not sure if they describe using SSL locally (it's generally not necessary since you're using test data) but you could modify your local webserver to use SSL instead of normal HTTP.
