### ISSUE TITLE
Interface Discussion: Move Mana to Rewards column, just above spells.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2076]
Follow the cue of Gold and Silver coins, which are placed above the Rewards they can purchase. Place Mana (create a mana icon, maybe or use a smaller mana bar) above the spells it can power.

HP and XP directly have a bearing on task progress. 
Mana has a bearing mainly on available special skills and spells. 
Mana is not a necessary feature in the game. It’s a help, a motivational tool.

This may help both users who are wanting to focus on Habit-Building/Productivity Progress and users who are feeling a little overwhelmed by the class system. They can review spells and mana when they are needing to those motivational helps.

**Comment by lefnire** [comment]
That could fit quite well, because I had future plans to make spells a tab
of the right column. [Rewards | Spells]. Click the spells tab, and you get
a mini mana bar + spells. Reason for this is (1) you shouldn't be able to
cast spells on rewards anyway (nothing currently preventing this), (2) less
scrolling, more hide-away until you need it

**Comment by SabreCat** [comment]
Ooh, @lefnire, that sounds delightful. :+1:

**Comment by DanielTheBard** [comment]
I think it'd feel weird if MP was hidden in a spells tab. It'd be quite customary to see a mana bar with your health bar in an RPG. I think it also looks nice aesthetically. If you think it's really an issue for it being there for non-gamers, could there be the option to keep it there instead for gamers? Like you just check a box whether you want it with your HP and XP bars or in the spell tab? I mean, I don't want to make it more convoluted than it has to be. Just to me the MP bar makes sense where it is. It also serves as a reminder that spells do indeed exist to help you and you have the ability to use them. If they're hidden in a tab, a user might kind of just forget about them. Which I suppose is fine for the people who are just outright opposed to the class system... but to be fair, there will always be people resistant to change. 

Though, I am a fan of the spells having a separate tab!

**Comment by SabreCat** [comment]
It makes a little more sense for the mana bar to be perpetually displayed now that it's a task completion reward. But I wouldn't mind having it tucked away, especially if #2072 is implemented.

**Comment by bennypowers** [comment]
slightly OT but I'd like an expandable sidebar with boss battles (which are currently buried under party? what?), etc.

**Comment by wc8** [comment]
@bennyp123 Personally, I'd have access to challenges and boss battles from the main page... at the least a visible link. Once one is participating, they are more part of the gameplay and less options.

**Comment by bennypowers** [comment]
i agree entirely

Benny Powers
Licensed Israel Tour Guide

In Israel 054-482-5726
In Canada 705-300-0072
In the USA 601-255-3532

bennypowers.com

**Comment by quin-jay** [comment]
What about completely inverting the current Rewards column? Then you have a Mana bar near the spells (and easily visible, if it's tucked in with the spells, of which there are only 4 so it's short), a Store right underneath which will eventually shrink after maxing out gear, and Custom rewards at the bottom, where theoretically the user would know to look for them, having already been there to create one.

Really the store and custom rewards could probably each go in either place, but I think having spells and mana at the top would help with the motivation/remembering they're there thing. I always forget I have spells, because I have so many rewards, but they'd be much harder to lose track of if they were at the top of the page.

**Comment by moshner** [comment]
Is the problem that you don't know if you have enough mana to cast a spell? That is certainly my most common question about it. 

If that is what other people think is the problem, can we not 'disable' the spells that we don't have enough mana to cast? They can't be clicked on and are crossed out or something like that.

**Comment by Alys** [comment]
Is this still something we want to discuss? I think the mana bar is working well where it is.

**Comment by crookedneighbor** [comment]
I do too.
