### ISSUE TITLE
Pickpocket Gives 160 Gold to an easy task with 93 day streak

### ISSUE THREAD

**Issue by jreatherford** [HabitRPG/habitica#2093]
Hey, I looked around for a similar problem posted but did not see one (I apologize if I just overlooked it)

The title pretty much explains it, I received 160gp for using pickpocket on a task marked easy.

I suspect it may be due to the 93 day streak that it has.

It is set as a physical task if that helps.

Hope this is helpful!
-James

**Comment by baconsaur** [comment]
I just used it on an easy task with a 230 day streak and only got 53 gold. I'm really curious how this is being calculated.

**Comment by sleepykit** [comment]
Would one those be a critical hit maybe?

**Comment by lefnire** [comment]
That was definitely a crit. Math is here:
https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L304,
please help fix :)

**Comment by lefnire** [comment]
@sleepykit you deleted comment, you were on track! let me know if wanna take a crack and need help, there's no such thing as too much hand-holding when someone's offering to help :)

**Comment by sleepykit** [comment]
I had suspected as much but the comment looked funky when it came out and then I got Hubby to give me a hand and he was like "that's definitively what we're looking at here". So it got answered for me. :) Now, it's Math time.

**Comment by sleepykit** [comment]
Is target.value in 

user.stats.gp += (if target.value < 0 then 1 else target.value+1) + user._statsComputed.per \* .075 

the GP earned from the task without pick pocket? Or some other magical number?

Also if there's a better place for me to go ask stupid questions, I will gladly migrate there.

**Comment by lefnire** [comment]
Out n about now, but when I get a moment I'll send you some resources,
there's some background info behind all this

**Comment by sleepykit** [comment]
I admit to boredom because I did more looking (and I apologize in advance because this is my very first run in with Coffee Script and I'm having a hard time reading it). 

It looks to me like target in this case is a task. So I was really supposed to be looking at task.value, I think. I checked task.js and it looks like tasks do have this variable in them. Task.value is described in the file as "the redness of a task" which I assume also means its blueness for tasks that have been maintained for a while. Maybe?

I then looked at the delta calculation in index.coffee because that looks to be where something is changing task.value (I think there is where I would be off). This is from index.coffee, lines 670 onwards (with the 93 day streak assumed, I think).

I am guessing that at the latest task.value will hit bluest possible option at 21 days. That might be wrong, but I didn't want to break one of my tasks to find out. But it looks like the delta calculation keeps adding to it in increments of .58 (+ some small bit of strength). Maybe? 

If that's the case, then a 93 day streak might have a task.value of 64-ish. Maybe? Maybe I am way off. Most likely.

Am I even anywhere in the same forest? Again, if you need me to go somewhere else to ask my questions, I'll make a disappearance.

Edit: I think I want to revise the idea of a blue daily in 21 days. I'm looking at my tasks and I have ones that are less than 21 but already blue...

**Comment by lefnire** [comment]
Ok, here we go - I added a bunch of info on the [Trello card](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system) (where most of the conversation has happened to date), in the "We need help with balancing / math" section - including some answers to some your questions. Quick bit: streaks don't play into passive or active stat calculations, they're _only_ used for streak bonuses (which is typically quite small) and drop chance. So that might be a dead end in the run-away spells investigtion

**Comment by SabreCat** [comment]
Critical hit on a spell? Should that be happening? Could explain why Rogues sometimes get utterly ludicrous values off Pickpocket sometimes.

**Comment by dwhitlow** [comment]
Several spells use the crit function, so it's by design. Unfortunately, it's being used in a lot of different ways and should be made more uniform.

**Comment by deilann** [comment]
This be fixed!
