### ISSUE TITLE
Lost gems after deleting challenge

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2094]
I deleted a party challenge that I had created, that had only ever had me in it, and which had 20 gems as a reward (an attempt to give a party member gems for Christmas), and the gems have disappeared: they are not in my gems, nor are they in party gems. If this is intended behavior, a warning at the delete prompt would be greatly appreciated!

**Comment by wc8** [comment]
There’s a warning at the beginning, but I agree that a warning in the delete prompt would be a good thing.
@lefnire ?

**Comment by SabreCat** [comment]
A warning is one thing, and easy to do quickly, but it would make way more sense to refund the Gems. It would, however, allow an exploit: Guild leader could use a chump Challenge to siphon off their Guild bank, effectively letting them make Guilds for free.

**Comment by lorian** [comment]
I think you can do that exploit currently anyway: just declare yourself the winner. Personally, I'd be fine with it always refunding to guild or party bank, if it was a guild or party challenge. It's very counter-intuitive for real-money currency to just vanish like that.

**Comment by SabreCat** [comment]
Good point! Total support for refund, then.

**Comment by lefnire** [comment]
What's your UUID re: the refund?

**Comment by lorian** [comment]
My userid is 142e1f47-6fae-4927-a5c2-3ea8a42b71d1 Thank you very much!

**Comment by lefnire** [comment]
√ give that a gander

**Comment by brightbold** [comment]
I just found the same thing. I created what are essentially 1-person challenges to motivate my daughter (Complete the three giant school projects by Monday and earn 7 gems, etc.) When she didn't successfully complete one, I deleted it assuming the gems would be returned to me. I would have declared myself the winner to get them back, but since I wasn't really participating and didn't win, I didn't want to have achievements I didn't deserve. 

I'm with @lorian that it makes sense for the gems to be returned to the challenge-creator in this case. 

And FWIW, although I've created 6 challenges, I've never seen the warning at the beginning! I once wanted to up the number of gems I'd offered in a challenge and couldn't, and my daughter said, "right, didn't you see that notice at the beginning?" but I hadn't. So I just went to look for it and I see it's in a popup. I think the "Note: this prize can't be changed later" (and, if you were to decide not to refund gems for deleted challenges, that info too) should be moved out of the popup and into text next to the gems field.

**Comment by psyche643** [comment]
This happened to me with 2 gems.  I created a party challenge but it turned out no one was interested in it.  I didn't want to "award" myself the gems because I didn't actually win the challenge, so I ended it and lost two gems.  I never saw a warning at the beginning!  Maybe it is because Firefox disables ads and it thought it was an ad?  Could I please have my two gems back?  d669ba12-c0ba-45a1-a586-c00864acb7b3 is my user ID.

**Comment by Alys** [comment]
@psyche643 : I'm giving you back your gems now. Wait a couple of minutes then reload HabitRPG and you should see your gems balance go up. EDIT: Done.

**Comment by breadstrings** [comment]
Has this been fixed? I assumed deleting the challenge would return gems too, but apparently it's still nor refunding. Granted I can just refund them myself, but I would have thought this would have been resolved by now.
