### ISSUE TITLE
RPG/Gamification Depth Option

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#211]
I think a slider option to define how much "gamification" a user would prefer would be a great value add.

HabitRPG has had an avalanche of feature requests and ideas to flesh out the RPG elements of the game. Personally I think I would enjoy and employ most of them.

However I know there are a lot of users out there for whom it would be overkill. I recommend a 3-5 tier slider that enables/disables different extended features like battles, travelling, classes, skills, sound, social media integration, events, mini games, etc.

As new features are added discussion can be had as to which level the feature falls into.

The reason I think a slider is better than selecting individual features is there could be unknown consequences of having different dependent options enabled/disabled. e.g. user disables attributes but wants classes or disables events but enables PvP challenges.

A tiered slider method mitigates the effort required by the devs to cater to every taste and rather aim for a handful of feature level sweet spots.

**Comment by Pandoro** [comment]
I think this is a great idea! When I spoke about my wishes for a stronger gaming factor in habitrpg, she immediately was like "mwwwwweeeeeh, do not like!" Since it is a game though, I think it is a valid route to take, people who do not like gaming, might probably not even see the real point of habitrpg. Nevertheless this would be a great thing to have as this will reduce the risk of loosing some users. Furthermore it could be used to make the game more/less time-intensive whenever it is needed in your life. 

What I am wondering a bit though how easy this would be able to realize. This means that everything needs to be modular such that it can easily be taken out or left in the game. But considering the current ideas I think most of this should be very possible?
:+1:

**Comment by lefnire** [comment]
It sounds pretty hard to me. I'll keep it on my mind-grapes, but I'm
currently a fan of the whole "you unlock things over time" (like the item
store) - which means it's easy for new users, and long-time users get
exposed to complexities over time. I'll brew on how we can make features
toggleable though

**Comment by horusofoz** [comment]
To further clarify I think if features can be grouped into dependencies that should make the scalability and the level of modulation more realisable. Like with Project Management breaking things down into itty bitty bits and linking as required.

For example combat is dependent on classes and stats. Classes are dependent on stats. Therefore stats would be at say second level of gamification. Classes at third level. Combat fourth level.

I imagine the lowest level would be labelled something like "Pure GTD" which would be the app in it's current feature state.

**Comment by Pandoro** [comment]
I think this idea becomes more and more related once more features are introduced. If the plan is to unlock everything at a certain state though, I figure that these things are rather modular anyways. This whole thing could then be realized with a simple flag in the code. If the conditions for unlocking are met, also check if the user wants to unlock this yes or no.

**Comment by horusofoz** [comment]
Additionally I think scalability of feature sets is Essential for an enterprise friendly version of the application.

HabitRPG offers so much that a business would love and many requested features such as party's and guilds will bolster this desirability. However options that individual home users may desire like battles and mini-games are likely to be seen as distractions by team leaders.

An example is one user wants the full experience but her partner is not a gamer yet they want to collaborate. She could have "Kitch Sink" mode enabled and him "Pure GTD". This way they can share progress on shared tasks without him feeling he's being overwhelmed or not focussing on work and her not missing out on "guiltless" pleasures such as battling a golem for gold. "I'm not gaming babe. I'm kicking procrastination's ass so I can buy us an ep of Game Of Thrones!" ;)

Designing HabitRPG to be modular at it's core is important to give the best chances of meeting all needs (within reasonable limits).

**Comment by StanLindsey** [comment]
Firstly; thanks for raising the issue. Secondly they are all suggestions and to to other priorities we haven't sat down and properly designed how some of the larger features will fit in. 

My personal thought is that many of the features are opt in. Don't want to use a party then don't set one up. Don't want integration with social networks then don't share your stuff. 

I foresee the options menu will balloon over time to help people customize their experience.  

Certain features will lend themselves to being toggled more-so than others but we have to wait until some of the more basic features & stability issues are finished.

Thanks again though =D

**Comment by horusofoz** [comment]
@SlappyBag I understand this suggestion is looking far ahead and as @lefnire advised it could be very difficult to implement. Let me try to explain why with these considerations in mind I feel this suggestion is worthy of implementation.

I think a slider option for enabling bundled features would reduce the testing/troubleshooting overhead in the future when some of the suggestions become live features. 

If users start enabling/disabling seemingly disparate features that tie in together at the backend there could be unexpected consequences. My first thought is bugs that crop up because HRPG doesn't have the resources to test every combination of features and how they behave when enabled/disabled periodically. E.g. decide I want to disable stats but still keep battles several levels into character development or later on choose to re-enable the feature.

If they are bundled together into "feature levels" this would greatly reduce the time required test how features behave together. Also it would reduce the inevitable resulting future support requests and time spent troubleshooting to resolve.

Another reason is customizability/scalability. Not just for home users but especially for businesses when HabitRPG goes down that track in the future. There are so many great options that could become available yet should be optional. 

If I were to collaborate/form a party with my girlfriend it would be hard to get her to want to use more than the current feature set yet I will want to enjoy battles, events, etc. If my department were to use it at work then I know we would want many of the requested features like team defined challenges and the tavern but Need to steer clear of mini-games etc.

Not only should the user's have the choice to opt-in/out of features but as my first point indicates, HabitRPG should be designed to ensure the combined options they want won't cause ill effects for their game and create support requests.

I know this is a future looking suggestion but it is also intended to offset possible future headaches in development and support.

**Comment by horusofoz** [comment]
While rereading my above response a simple yet elegant solution (my favourite kind)  has occurred to me. All options are active for all users. When they opt-in/out the function is simply hidden/displayed. That way all data is still collected, calculated and accessible to other dependant features. Also this way if a user enables the feature down the track there is no unintended consequences.

**Comment by horusofoz** [comment]
@lefnire I agree the unlocking mechanism needs to be in place to guide uesr's into functions gradually. Pandoro's suggest  [above ](https://github.com/lefnire/habitrpg/issues/211#issuecomment-12709064) is I think a good one for maintaining the unlock mechanism without affecting opt-in/out.

**Comment by StanLindsey** [comment]
You're an asset to this board @horusofoz thanks for taking the time for all this.

Depending on the implementation I don't suppose it would be too hard, I assume each "release" would target a certain feature and therefore all of the code specific to that feature could essentially be locked down/enabled separately. Almost like an expansion pack. 

E.g. one release we focus on Parties, because all the code for parties is in one area should be able to turn Parties on or off essentially. This would allow us to A. unlock as users level (which is the plan anyway) and B. enable disable in a settings menu.

**Comment by horusofoz** [comment]
@SlappyBag Thanks for the kudos.

Your explanation of targeting specific features with each release is spot on. This method enables the feature's code to be relatively self contained and tested against all existing code.

**Comment by StanLindsey** [comment]
Exactly, so hopefully the code will naturally fit into your suggestion as long as we keep it in mind in development.

**Comment by Pandoro** [comment]
Nice discussion going on here ^^ it worries me a bit that @lefnire  gives his opinion though ;) 

After thinking about this for a little while longer, I think it should be easy to implement in same cases, just as I suggested earlier. However I would go away from the slider a bit. The problem with the slider would mean you would always have to go one step further than the last point. The question remains though, if we get a new feature where to we place it?

Say we have the following three

|----------------------------------------|------------------------------------------------|
stats                           monsters                               mini quests

Now we want to introduce a new feature which is independent of monsters and miniquests, but it needs stats. This means we either force it on users who activated stats, push it in with the monsters, or add another slider option. The first two are things I wouldn't do as people might not like it. The second does not scale over time with more and more features. 

It becomes even worse if I want to do something very cool, which is a mini quest, and people might like that idea, but they never wanted monsters. Than you are forcing them to also have monsters, or not get the new cool feature.

Because of that I would use simple check/uncheck fields in a tree/gaph wise manor.
stats ---- battles 
        ---- mini quests
              /
         /--/
skills ---- feature x
        ---- feature y ------- etc.
                           -------- etc.

In this way you can even more package features away into little black boxes, which users can turn on or off. (If you minimize cross-dependencies.) While writing this however, it becomes more and more clear to me what @lefnire  meant in the beginning. For small ideas this is easy, but once you start building these dependencies, it will be awfully hard to do it with some things. Simply hiding it as @horusofoz suggested is not the best idea I think. This means the code is still active, so you are not getting the benefit of "it's not working, let's just turn it off" and also the server load is not reduced. So I think the stuff really needs to be on or off. But lets consider an example, if you decide that stats can be toggled and you can assign something like points each level (In the theoretical case that this is how it works), then what to do once a user activates it? Does he get a huge pool of points he assigns all at once? And what happens if the feature is turned off again, does the allocation of the stat points remain? I guess these are still things one can decide upon, but I think it also shows, that @lefnire was right when he said that it sounds hard. There seem to be more catches to the idea than you can see at first glance. However as already pointed out before, I also think that this can be greatly beneficial when done right and should be considered, better earlier than later ;)

**Comment by horusofoz** [comment]
@Pandoro I appreciate the input and I apologise as I didn't explain with the opt-in/out method outlined [above](https://github.com/lefnire/habitrpg/issues/211#issuecomment-12735919), the slider concept becomes redundant.

I think the hide/display option is optimal as;
- it minimises coding required to implement, 
- ensures no bugs caused by opting in/out, 
- users can switch functions back and forth on an ongoing basis, 
- parties with mixed feature sets should not be impacted,
- easy for users to use.

Also, I don't really see a user landing with a huge pool of skill points as a negative. If they enable skills they'll want those points. 

If the skills system proposed [here](https://github.com/lefnire/habitrpg/issues/195#issuecomment-12710155) were implemented, there would not be many skill points to allocate as the user would not have mapped their tasks to skills/attributes.

**Comment by lefnire** [comment]
We should create a Trello card so we can cast votes. In full disclosure I don't see this happening anytime soon - it makes me nervous re: difficulty, and I think more people than not will want the whole game. Important to keep the convo rolling here, could be people want this after all.

**Comment by wc8** [comment]
[Gamification Options](https://trello.com/c/EKxy5lYI).

**Comment by wc8** [comment]
As someone else said in another thread, all the RPG features need to add to, rather than interfere with, productivity.  If the gamification is clearly tied to productivity, an enterprise will be more likely to tolerate/appreciate it.

 As @horusofoz said, "As new features are added discussion can be had as to which level the feature falls into." I wonder if a few of the relevant features need to be implemented or fleshed out more to even assess the need/difficulty of levels of gamification. For example, to know if boss battles would even be objectionable on a job site, we'd need an idea of what it entailed. GIF? Video? Music? Sounds? A simple display [i.e. notification]?

If many of the settings that would be intrusive in an office environment (eg. #76 music/sounds) end up being optional anyway, maybe the enterprise leader could be given control over enabling/disabling those options.

Also, I wonder if a specific user's disinclination toward RPG gamification might be addressed via different genres, see #164.

**Comment by horusofoz** [comment]
As we have a Trello card for this I figure we can close this for now and if it proves popular, we can continue conversation there.
