### ISSUE TITLE
no way to sell old class items

### ISSUE THREAD

**Issue by TheWebTech** [HabitRPG/habitica#2119]
Once the class system was implemented I changed class twice, I have all this gear hanging out that is not for my class I want to sell it to get the money for the new gear. It'd be great if some sort of implementation of selling the gear was possible. Or "selling for shop credit" that way the money couldn't be spent on rewards outside habitRPG such as watching netflix. that way users wouldn't feel compelled to sell their gear when they want to splurge one day.

**Comment by lemoness** [comment]
I think this would be fine, but I do want to make the money you get by selling "used" gear back to the store be much lower than what it costs to buy, so that you are still motivated to earn gold for your tasks.

What do we think of selling back for 10% of the normal price? Buy for 30, sell for 3, buy for 100, sell for 10? I know it seems low, but lots of people will be selling all their gear at once, and I think that it will keep people from trying to sell all their gear to avoid having to work to earn gold. It'll be closer to what people get for selling drops, too.

Note that we'll need to make sure that people don't lose their "Ultimate Gear" badge even if they've sold all their gear. We'll need to keep track of what tier they're on.

**Comment by Aurornis** [comment]
That is a bit of a lowball, especially considering you can still wear your old gear, you just don't get the slight class bonus you'd get if it was for your class.

**Comment by lemoness** [comment]
Well, yeah, I thought it might encourage some people to keep the gear, since the higher-tier stuff especially can be useful for things like Boss Battles and Collection Quests... but I agree that the higher you get, the more frustrating the amount seems. Maybe 30% of the original price?

**Comment by deilann** [comment]
This would be better moved to Trello.
