### ISSUE TITLE
Missing Abilities from rewards column

### ISSUE THREAD

**Issue by leaks** [HabitRPG/habitica#2140]
My abilities have disappeared from my rewards column. I drained my mana to 0, when I logged in the next day, I had some mana regen but my abilities are gone. 
They do not appear on multiple computers in multiple browsers, nor on 2 different mobile clients. I tried Chrome in regular and incognito to rule out any plugins interfering. There are no errors in the JS console. 
I waited a little while to see if it was a temporary bug on my account but it hasn't gone away.

UserID : d65cf337-f496-45f4-9099-85060e836b9f
Chrome version : 32.0.1700.68 beta-m
Firefox version : what ever is current
official android app and Habit AndroRPG

If any more information is required I will do my best to collect it.

**Comment by SabreCat** [comment]
Are you only 10th level? Level up a bit more and they'll come back. The abilities have been spread out a bit further since their initial implementation.

**Comment by leaks** [comment]
Thanks for the prompt response.

**Comment by Macoris** [comment]
First of all, sorry to dig out this thread, but it's the only one that describes exactly my problem.

I've been having ]this problem for some time now. Also tried most of the things "leaks" did.
The only difference is that my life also dropped to 0, so I "died".
I'm a level 29 now, and have been checking on the abilities for at least the last five levels and nothing.
Is this supposed to happen because I died? Is there something I can do?

Image attached is from a couple of levels ago.
![erro habitica](https://cloud.githubusercontent.com/assets/18403290/14435929/8e4e27ba-fff0-11e5-8fb7-aa250c9acd34.JPG)

Thanks in advance

**Comment by Alys** [comment]
@Macoris 
Could you please tell us your User ID? To learn how to find it on website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu).

**Comment by Macoris** [comment]
Sorry I didn't do that before, just really didn't know where to find it.

UserID: cab70fa1-c70c-473e-834a-ea11d1b48ab4

Thanks for the quick reply, btw.

**Comment by Alys** [comment]
@Macoris No worries. :)  You've opted out of the class system, and so skills and some other class-related features aren't available to you. To opt back in, go to User > Stats, where you'll see a button for it. There's more information, including an illustration at "Enabling the Class System" on the wiki's [Class System](http://habitica.wikia.com/wiki/Class_System) page. Tell us if you have any problems after that!

**Comment by Macoris** [comment]
Oh.. My god. Can't believe it was so simple.
I'm so sorry I didn't think of that before... 
Guess I ended up disabling the class system when "I died". Is that possible? Because I'm _almost_ sure I had the abilities one time in my "life" :x (shame emoji)

Also... As you could probably guess from the attached image, I've bought some equipment over my levels, and all of them look like "warrior" equipment. Will I lose any of that? Or will it be non-usable for my character or something like that?

Sorry again.. To be posting on a closed thread, and obviously for my noobness lol
And thanks for all the attention, and even answering me faster than I did.

**Comment by Alys** [comment]
@Macoris No worries. :)

It shouldn't have happened when you died. If you don't recall manually clicking on the change class button and then selecting "opt out" then it must have happened because of a bug - sorry about that!

When you change class, you never lose access to equipment that is already appearing in your equipment page. You can still wear it as battle gear or a costume. It can be beneficial to wear items from another class as battle gear if you want to benefit from the stats they give.

However, when you change class, the equipment available to buy in your Rewards column will change. You're a Warrior now and you're seeing Warrior gear that you can buy, but if you change to, for example, Mage, you will no longer be able to buy the Warrior gear but instead will see Mage gear for sale. If you'd like to buy the Warrior gear, do so before you change class.

BTW, it's okay to post on closed threads if the bug is the same! Sometimes old bugs do come back to life. :)

**Comment by Macoris** [comment]
Never mind :)

I think I'll just buy the remaining warrior equipment, just so I have it :smile: (learned!)

Thanks again for all the attention you're giving me, I don't even deserve it :x

I'll stop posting here now, have a good one @Alys
