### ISSUE TITLE
Emoji don't show up in tags

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2164]
Which is tragic, because now I desperately need my tags to be as adorable as my tags. I can't have my tag just saying "Errands" when the errands themselves have a rocket ship!

**Comment by lefnire** [comment]
Hmm. this gives me a thought. Should we remove emoji from tasks,and instead only put them on tags. Then tagged tasks show the emoji, so you can see at a glance what your task is tagged as?

**Comment by lorian** [comment]
...I have never before been more in love with an idea in my life. I want tags that put emoji on tasks, yes please!

Not sure that you should/need to take emoji off tasks themselves, though.

**Comment by brightbold** [comment]
I too like this idea, but not at the expense of removing emoji from tasks. I have a lot of one-off emoji (:recycle: for Take Out Recycling and :boot: for No Shoes in the Living Room) and I wouldn't want to have to create special tags for those tasks just to emojify them. We're already dealing with tag clutter due to challenges, so we don't want to add to that.

**Comment by DanielTheBard** [comment]
@lefnire - While, I think that's a cool idea, I agree with @brightbold. I also have one-off emojis for tasks.

**Comment by lefnire** [comment]
Fair nuff. Tag-based emoji is a ways off anyway, and I'll be sure not to remove task-based emoji

**Comment by wc8** [comment]
FYI, temporary workaround if you’re using mac: a safari-based browser will show the emoji in tags. 
I’ve switched to emoji or initials for tags now that tags are limited to one line.
