### ISSUE TITLE
Zero damage to quest boss

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2168]
Party: 184163b5-24e3-4ce2-b51c-a10144cce794, users E (cca60406-1b8f-496e-af77-cd19df77c895), Jace (e3adacde-68c7-456f-ab88-d4cc020cb30d) and Veruca Salt (9ede3733-7671-498c-8fd7-011f63266a77) each did 0.0 damage to the boss on first day rollover; the boss did 5.5, 1.0, and 4.9 damage each time.

**Comment by lefnire** [comment]
You guys should be fine now, judging by your records in the database ([screenshot](https://www.evernote.com/shard/s17/sh/5756b419-a362-4b04-969f-d2a0cf477def/c685308c928d3a9cc92cad29407a8ed4)). I wanna keep an eye on this. I'm seeing this error #2167 pretty frequently (which I think is related), a very important error to fix; however, every time I go to test an account that's triggered it, everything seems "calibrated". Was this the first cron for everyone in the current battle? I wonder if something's on between leaving a boss and starting a new one. What was the sequence of party/quest actions (as much as you can recall) that lead to your current situation? Did anyone ever see any red `error 500`s in the top right corner at any time?

**Comment by casicastiel** [comment]
Veruca Salt started the quest the day it came out, but neglected to wait for people to join, so she aborted (this was pre-scroll refunds), and I restarted using my copy of it. Everyone in the party joined. My first cron for this battle happened when I logged in shortly after 7:00 am this morning, as usual; then Jace, and Veruca Salt. The other two members of the party haven't experienced one yet. I've never seen an error, although I haven't been looking for one, and don't know whether it's something I might've missed.

![screen shot 2013-12-29 at 4 35 33 pm](https://f.cloud.github.com/assets/6208739/1820117/9bb7ed88-70d1-11e3-84eb-4d840bb99152.png)

**Comment by casicastiel** [comment]
Update: those three crons were the only ones that did 0 damage; since then, it's all been fine.

**Comment by lefnire** [comment]
You know what also, I just noticed this morning when I did 0.0 damage but had completed almost all my dailies. You only start tallying _after_ the boss begins. So for me, I'd done most my dailies, then late night someone started the quest. Party took damage (for my missed dailies), and boss took 0 (since I hadn't started tallying yet)

**Comment by casicastiel** [comment]
That makes sense. I think the last person joined the quest while I was asleep that night, so all my dailies were done already -- and presumably Jace and V.S.'s, too.

**Comment by lefnire** [comment]
At some point I'll start looking into how to tally at the end, so this doesn't happen. I think there were some major technical hurdles. A lot happens when clicking up-score, that you can't sort of "simulate without actually applying" to determine what the point value _would_ be on cron. I'll keep you posted if I can find a way

**Comment by casicastiel** [comment]
I'm not sure it's necessarily a bad thing — it makes sense, after all, once you understand what's happening. Perhaps all it would need is some clarification/documentation somewhere.

**Comment by lefnire** [comment]
I have a solution. Don't clear `user.party.quest.progress.up` [upon boss-start](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/groups.js#L442). It's cleared on cron, and cleared on boss-complete - but if we just don't clear it on boss-start, it will maintain the full day's tally, even for a late-day boss-start

Should be a simple fix in case someone can get to it before me, just had to "note to self" for later

**Comment by tildelowengrimm** [comment]
I experienced this issue today. However, I did numerous tasks _after_ activating the quest.

I activated the Trapper Santa quest yesterday morning then went about completing lots of to-dos, habits, and tasks. My first cron was a few hours ago. When I checked the boss this morning, there was no damage. I had no incomplete dailies, and took no damage either.

I'm soloing with party ID `4b2733b2-4cac-4b2b-8a8e-8a0fa951ffec` and user ID `d704a894-509b-4bf6-a2a1-b6dd9e17fa36`.

**Comment by tildelowengrimm** [comment]
After a few hours, the damage appeared. _shrug_

**Comment by lefnire** [comment]
I pushed a fix, but I need to write some more tests before I deploy this - want to make sure it's not affecting other things.

**Comment by lefnire** [comment]
Happy to say this looks fixed :) let me know if anyone experiences it again

**Comment by casicastiel** [comment]
Bless you! We actually just started the quest again the other day, but everything's been fine. :3

**Comment by thebat137** [comment]
I'm doing a solo Egg Hunt quest (party: 33d17c3a-402f-4f29-a7a4-b35925807deb, user: dea8a9e8-c084-438a-9a14-7fe96a73fd0a) and I just refreshed after my 3 AM (EST) cron and seem to have found no eggs today, despite having done most of my dailies and having the dailies appear to otherwise refresh correctly.  (In other words, I received only the expected amount of damage from incomplete dailies and no more, I got my daily MP boost, all of the expected streaks were maintained, and everything ungreyed correctly.)  When I did the refresh I got some weird error (which I unfortunately didn't write down) that said something about a null quest; I'm assuming this is where the problem happened.

ETA: To be clear, i didn't even get a message that I found 0 eggs.  There's just nothing there at all.  But my daily Tools of the Trade cast after refresh _did_ show up in the party messages.

**Comment by deilann** [comment]
This is probably due to the Drag'on quest misfire.

**Comment by thebat137** [comment]
I see what you mean.  I should've paid attention to the tavern talk.  Eek.

I see that neither my current quest nor the world boss are currently showing up in the user data display at https://oldgods.net/habitrpg/habitrpg_user_data_display.html .  Does that seem like a likely outcome of the Drag'on glitch?

**Comment by thebat137** [comment]
Ah, observing the tavern talk, it looks like I'm not the only one who's seeing that symptom.  Guess the Drag'on really did a number on us all.
