### ISSUE TITLE
"Death doesn't screw up your career like it used to."

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#2179]
I am loving the boss battle, so I'm a little reluctant to report a bug, but I've already died twice and I'm still doing damage to the boss from beyond the grave.  Also it said that it destroyed two pieces of my equipment, but I seem to still have them.  
I am glad I'm still fighting this battle, but...

**Comment by SabreCat** [comment]
Hah! That tagline sounds... Harry Dresden, maybe?

**Comment by cleave29** [comment]
1st ep of Red Dwarf.

**Comment by lefnire** [comment]
You didn't lose the gear pieces? Definite bug. Do note, you can lose non-equipped gear from your inventory, so check to see if something disappeared from there, even if you're still wearing all your current battle gear.

Re: boss battles - yeah, death doesn't yet boot you. It's on my To-Do, I left it in the text to scare people into accountability while I work on it :)

**Comment by cleave29** [comment]
Hmm, I think I still have all of my gear.  If I don't how would I get that piece back?
The threat of death still works on me.  :)  Good choice.

**Comment by lefnire** [comment]
So let's say you have all your warrior gear. A random piece breaks on death, say Leather Helm. If you're wearing Gold, then it doesn't really matter to you - your equipped helm still stays intact, and where your item-store was previously empty for the helm tier (since you maxed it), Leather Helm has now returned. No point in buying it except for the collectors.

The item store will show items available from the bottom to the top. If you _can_ buy Golden Shield, but your Wooden Shield broke - Wooden shield will show in the item store, and Golden won't show again until you've re-purchased Wooden. Does that make sense?

So yeah, keep an eye on your Inventory when dying, not your avatar, and see if you've lost equipment as you should.

**Comment by lefnire** [comment]
Lil' heads up, the way bosses are coded - you can permanently lose your gear drops. You can get them back by re-completing the quest, but this was the easiest way to code it. I actually kinda like it this way, since "don't die!" - but thought I'd bring it up now as a point of discussion in case people aren't digging that

**Comment by cleave29** [comment]
Hmm, yeah, Inventory doesn't seem to have changed.  I have everything on the Cleric path at this level.  Take a look:
![image](https://f.cloud.github.com/assets/3587570/1824381/35663128-7196-11e3-86ad-45de6de00627.png)

**Comment by cleave29** [comment]
Whoa good to know.  That's the permanent part of death...

**Comment by lefnire** [comment]
Could you have lost a warrior or rogue piece? It's any class gear, or any
quest-drop gear

**Comment by cleave29** [comment]
Hmm.  I seem to have all of my Warrior gear.  5 pieces of armor each.  7 weapons.
I can't remember if I bought the other Kukri...  sorry.
![image](https://f.cloud.github.com/assets/3587570/1824403/efbc7974-7196-11e3-8ece-674c0992ee8a.png)

**Comment by lefnire** [comment]
Kk, just keep an eye out next time you die, see if you've lost what it tells you. Things work fine for me on local testing, so I have a hunch you lost the Kukri

**Comment by lorian** [comment]
@lefnire Is there a way to code certain gear pieces as non-losable? Specifically, gear drops from limited-time quests would be SUPER unfortunate to lose on death.

**Comment by lefnire** [comment]
@lorian not yet, but don't worry since we don't have any limited-time gear-dropping quests in the queue (note **gear**, pets & mounts are exempt). If/when we do, I'll find a solution

**Comment by deilann** [comment]
Let's follow the discussion here: https://github.com/HabitRPG/habitrpg/issues/2551
