### ISSUE TITLE
Leaving a guild doesn't make you leave that guild's challenges

### ISSUE THREAD

**Issue by erratio** [HabitRPG/habitica#2195]
Since you can't see the challenges for that guild anymore, the only way to leave any challenges you've joined is to rejoin the guild, leave the challenge, then leave the guild again. Seems a tad suboptimal :p

**Comment by colegleason** [comment]
Would we like to just automatically remove them from all challenges and add a note to the Leave Guild prompt? I believe that can be done in the callback for Guild.leave.

**Comment by colegleason** [comment]
So I have this somewhat working. When you leave a guild, it removes you from all challenges. However, I am giving the user the option to keep-all/remove-all tasks.

I'm hitting an odd issue in remove-all where the first API call to leave a challenge will succeed, but the second fails with 500. Specifically, it seems to fail while unlinking the tasks with this error:

```
{ message: 'No matching document found.', name: 'VersionError' }
```

It looks like a race condition to me. Need to investigate further.

**Comment by colegleason** [comment]
Yup, seems to be a race condition as noted in [this StackOverflow post](http://stackoverflow.com/questions/17499089/versionerror-no-matching-document-found-error-on-node-js-mongoose). Are there locks anywhere? I don't see them.

**Comment by lefnire** [comment]
You're right on the money for something I've recently been deeply diagnosing, so join my cause!

So, no need for locks or anything, what's happening is more obvious. In many cases (more and more as I discover, and fix as I go along) we're saving a something, and then saving it _concurrently_ somewhere else. The fix is proper callback handling. So an example would look like:

``` coffeescript
# update user
user.save()
# update members
_.each party.members, (m)->m.save()
```

well since `user` is one of the `party.members`, that double-save will throw the `VersionError`. There's two possible fixes.

(A) Use proper async-handling:

``` coffeescript
user.save (err, saved)->
  _.each party.members, (m)->m.save()
# or use async.series / waterfall
```

or

(B) In many cases (_especially_ with challenges), don't load and save all the users if can be avoided. Instead, run a database update `User.update({_id:{$in:[ids]}},{UPDATE})`. Loading all the users puts major load on the server (a single user can be ~1-2MB, some challenges have 2-3k users, Heroku maxes at 512MB). Running the batch update operation will avoid accidentally running `.save()` twice on the same object, and cut back on load. However, it's not always feasible. Eg, [this bit here](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/challenges.js#L182) is really irking me. _Super_ bad performance, often throwing `Error: request entity too large`, but we need to do a lotta computation on the user objects, so a `User.update()` might not be feasible.

**Comment by colegleason** [comment]
So my issue with this solution is that I currently only know I'm issuing concurrent request on the client side. Therefore, I can't use an update or async.waterfall on the save() callbacks. So while I can hack around this in the Angular.js code, it doesn't solve the underlying problem of the server-side API not being concurrent-safe.

Here are the possible solutions, in my opinion:
1. Use async.waterfall on the client side to sequentially send the Challenge.leave API call. While this is the easiest solution, it is pretty hacky. Continued usage of async.waterfall for API requests that should be async across the codebase may cause slowdown in the long run.
2. Add a Challenges.leave batch API method like `POST /challenges/leave/batch`. While this would let use sequentially save() on the server-side, the single object API still isn't concurrent-safe. Also this solution just feels bizarre, and adding batch methods everywhere would suck.
3. Modify the server-side API calls to use locks in order to be concurrent-safe. It could then queue up requests and properly modify them, making the process seem concurrent to the user. Not sure what support MongoDB might already have for locks, etc.

For the quick fix, I can easily implement (1). With the long-term and 'proper' solution in mind, however, I think we should apply (1) as a fix to push out the feature and then work on adding locks as in (3). We can then remove the async.waterfall added in (1) when (3) is complete.

**Comment by lefnire** [comment]
I agree that we may need to implement (3) for a safer API in general. Eg, race-conditions can happen if the Chrome extension hits at the exact same time as the website hits. Rare, but not out-of-this-world rare.

But for this particular case, why is the client calling multiple operations concurrently? For the case of "leaving a group should leave its challenges", that should all be handled on the server. The client should call one operation, like `POST /group/{id}/leave?remove-challenges=true` (eg handle the leave / don't-leave as a query param, and compute it all server-side)

**Comment by colegleason** [comment]
Oh, you're right. That's better. I don't know why I felt it should be done on the client side.

**Comment by lefnire** [comment]
I do it often m'self, lotta quest stuff I think I need to move to the server. In the end we want _almost everything_ to be computed server-side to support a robust black-box API, and prevent [the issues we hit in api v1](https://github.com/HabitRPG/habitrpg/issues/1977). 

Anyway, I'll start looking at that (3) when I get the chance, never dealt with locks before TBH
