### ISSUE TITLE
Class Tour buggy

### ISSUE THREAD

**Issue by katfang** [HabitRPG/habitica#2196]
This is pretty minor, and I bet people don't do this, but if you start a Class Tour, and then you click to somewhere the Tour doesn't expect you to be (for example, if you go back to your todo list), it'll get confused and not close the previous message box if you hit prev / next. But the buttons still work (so long as the Tour hasn't ended.)

**Comment by SabreCat** [comment]
I once had it get stuck so that none of the tour buttons responded at all until I refreshed the page. Very weird, and couldn't reproduce it.

**Comment by katfang** [comment]
Yeah. You can get it by opening up a tour, going to a place the tour doesn't expect (say, your todos), and then clicking through the rest of the tour. You will (or at least I did) have one window remaining that you can't do anything about.

**Comment by metasean** [comment]
Any progress on this?

I thought I had accidentally pressed the close button ( #3503  ) and hadn't found out how to restart the tour.  I did, however, figure out how to add, edit, and delete tasks, and promptly deleted all the default tasks.  I stumbled on how to restart the tour, but now I can't make it past the "Dailies" bubble (presumably because the only task I have now is a daily).

**Comment by deilann** [comment]
No, where the tour is stuck is going to be unrelated to anything to do with your tasks.

I've always been able to get out of it with a good old refresh. Have you tried that?

This is super low prio -- I don't think anyone's worked on it. Bigger fish to fry and all that.

**Comment by metasean** [comment]
First, I'm a new user who's just sharing a new user head-scratching, "is it just me?", "I really wish it didn't do that" moment.  I'm pretty tech-savvy and have found that if I have these moments, there will be others who have them but aren't tech-savvy enough to get past them.

"No, where the tour is stuck is going to be unrelated to anything to do with your tasks."  I just created a brand new, throw-away account and this statement is 100% incorrect.  On the throw-away account, I didn't click anything other than the tour's >> button and had tour stops on "Habits", "To-Dos", "Rewards", "Hover over comments", "Unlock new features" and was able to successfully reach the end of the tour.  

Last night, I restarted my own account's tour at least half a dozen times last night and I never got those items.  I'm sure that the reason that my own account didn't get those is because (a) I had initially encounted the "tour abruptly stopped" aspect of this bug, (b) so I started playing around with the app, _to include deleting the default tasks in each category_, (c) before finding out how to reset the tour, (d) at which point I encountered the "tour locks up" aspect of this bug.  In and of itself, this isn't what I'm reporting.  I included it more as an edge case of the parent "Class Tour buggy" report.  

The parent bug itself is that if a user clicks somewhere outside the tour then the tour may simply stop for no apparent reason and with no obvious way to restart the tour (remember, I'm talking about a new user who doesn't know the interface), or the tour simply gets "stuck" (which, as you mention, requires a refresh).  

I don't know what the priority of the bug is or should be, but as a new user this abrupt stop was irritating and left me with a lot of questions; i.e. not an ideal new user impression.

**Comment by deilann** [comment]
Sorry if I seem abrupt. I am not trying to be rude. I am trying to deal
with a multitude of tickets and I have RA, which makes typing very painful.
So I try to be brief, which many people take as brushing off. Actually,
it's just me.

I am still unsure how you say that the tour stops on Dailies because
dailies were the only tasks you have. Did you replicate it so that it stops
on To-Dos, if To-Dos are the only tasks you have? That's what I'm confused
about-- there should be no correlation there. It seems that it's not
because you only had Dailies, but because you clicked away, which is the
issue. Can you confirm?

And yes, this isn't an ideal new user impression, but we have some major
refactoring that needs to be done as well as critical bugs that need
smashing. It's also not something that comes up often... as you can see,
this ticket is pretty quiet. I think you managed to get it because you're
pretty tech-savvy and fiddle around. So there's some "new user impression"
stuff that's a bit ahead of this as well. And I felt like telling you that
it's low priority, when you asked the status, was important, so you didn't
get impatient or frustrated when it didn't get fixed any time soon.

**Comment by metasean** [comment]
Text-based communication does deny us many non-verbal and verbal means of interpreting one another (I can't even imagine living several hundred years ago and having only pen and paper.  At least we can have near real-time conversations which facilitates more rapid clarification of things that have been said!)

abruptly stopped = I clicked the >> button and expected another tour bubble but got none

**Issue testing steps and notes (all on the new, default user account):**
1. deleted both Reward tasks
2. restarted tour
3. only click the tour's >> button
4. the tour bubbles progressed through the "To-Dos" bubble as expected
5. the tour completely skipped the "Rewards" bubble
6. the tour did successfully showed me the "Hover over comments" & "Unlock new features" bubbles
   **Deleting a single category of tasks appears to cause only the the category bubble to not display**
7. deleted all the To-Do tasks
8. restarted tour
9. only click the tour's >> button
10. the tour bubbles progressed through the "Habbits" bubble as expected
11. the tour completely skipped the "To-Dos" and "Rewards" bubbles
12. the tour did successfully showed me the "Hover over comments" & "Unlock new features" bubbles
    **Deleting two categories of tasks appears to cause only the corresponding category bubbles to not display**
13.  repeated previous steps deleting all "Dailies" tasks, with the same results
14.  repeated previous steps deleting all "Habits" tasks...
15.  the tour bubbles progressed through the avatar bubbles as expected
16.  when I click the >> button on the "Avatar Customization" bubble the tour abruptly ended  
17.  added one new task to "Dailies", "To-Do", & "Rewards"
18.  restarted tour
19.  the tour bubbles progressed through the avatar bubbles as expected
20. the tour skipped the "Types of tasks" and "Habits" bubbles
21. the tour continued with the "Dailies", "To-Do", & "Rewards"
22. the tour abruptly stopped after I clicked the >> button on the "Rewards" button  
    **Without any Habit tasks the tour does not show the "Types of tasks", "Habit", "Hover over comments," & "Unlock new features" bubbles**
23. added one new "Habit" task
24. restarted tour
25. only click the tour's >> button
26. tour progresses as expected  
    **Without any default tasks, but at least one task in each category, the tour progresses as expected**
27. restarted tour
28. clicked >> button through "Welcome to HabitRPG" and  "Your Avatar"
29. with "Avatar Customization" bubble up..
30. clicked my avatar
31. taken to avatar customization screen; "Avatar Customization" bubble still visible
32. changed my shirt, hair, bangs, and skin
33. clicked the >> button
34. tour ends abruptly, leaving me on the avatar customization page  
    **Clicking outside a tour bubble while on the tour may cause the tour to quit abruptly**

Tests done on OS X 10.6.8 Firefox 30.0.
- I'm was sure I got it tied in knots because I had deleted tasks.  (Something that a non-techie user isn't likely to do.)
- **From a new user perspective, I suspect steps 28-34 are pretty typical, and ending the tour there is far from ideal; i.e. as a new user on a tour, I expect to be able to 'play' with the section being toured.** 
- **Not having an easy and obvious way to restart the tour is still a problem.  I haven't 'leveled up' so I don't know how different the gui is, but perhaps a super simple solution is to have a button on the first level's interface to restart the tour.**
- If a user deletes all the "Habit" tasks, they loose not only the "Habit" bubble but also the "Types of tasks", "Hover over comments," & "Unlock new features" bubbles, which covers a lot of information.

RE: "It's also not something that comes up often... as you can see, this ticket is pretty quiet. " - The people who would be most negatively effected are not users who would even know about bug reporting yet alone GitHub.  So, it may be more important than can be gauged by GitHub issue reporting. ;-)

RE: "we have some major refactoring that needs to be done as well as critical bugs that need smashing" - I'm just starting to learn JS, so I can't help a lot, but I'll try to do the little things that an apprentice can do while learning.

---

I couldn't see how to delete this account (created solely for testing purposes) and am running late for work.  Feel free to delete this account. :-)  
Testing Account info:  
    Name: TempTemp  
    Email: gu9uh@ce.mintemail.com

**Comment by deilann** [comment]
Awesome! Re: being able to help
And thank you for the awesome breakdown

While you are correct that a lot of users wouldn't know to come to github I
mostly feel the pulse for new user issues in the Tavern and the Newbies
guild... and I don't think I've ever really seen this come up. Not trying
to argue with you that it's a problem -- I agree that it is, but it's
really not something brought up much. But I'll definitely keep more of an
eye out for it.

Also yes... text based communication is tough. I never really thought about
how much harder it would be with delays. That might be why Victorian era
letters come off so polite, even when they're not.

**Comment by Alys** [comment]
The class tour has been changed and this no longer happens.
