### ISSUE TITLE
Preen user document periodically

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#220]
The database is getting very large because:
1. The user document gets huge over time - every Habit click and Daily reset records a history entry (per task)
2. Every website visit is a new "staging user" - which is never deleted.

This causes en-masse user updates (cron, re-roll, reset) to go very slowly, or sometimes even fail. To fix this we need to
1. Consolidate history entries periodically by merging really old entries together as an average. Instead of every day, we'll keep 20 or so on file, and it would look like `(2010 avg) (2011 avg) (nov avg) (dec) (last week) (day) (day) (day) (day)`
2. Periodically delete all users who never followed through creating an account, and who haven't visited in a month (user.lastCron)

**Comment by lefnire** [comment]
I figured I could create a Mongo script for #2 easily, but Racer stores dates as strings (https://github.com/codeparty/racer/issues/42), so we can't do Mongo date comparisons on `user.lastCron`

**Comment by Pandoro** [comment]
I'd say whatever works out best for your! ;) I would not delete users, I see the negative stories how accounts were deleted bla bla bla... Considering these users didn't click stuff? It doesn't matter as their data does not grow, so the main concern will probably be the data of active users? So average seems just fine, I'd even say that you can delete the stuff as I will not be looking back so far anyways. But that is just my opinion.

While we are speaking about inactive users. One possibility would be to create a little tutorial. Something like, setup a habit, setup a todo, setup a daily, setup a reward (and later on maybe some other tasks) People who do not make it in the end could be deleted after a while, at least their data, maybe getting a message on a new login stating that they did not conclude the tutorial and because of that were deleted.

**Comment by lefnire** [comment]
no no - by inactive, i mean they never _registered_ in the first place. When someone visits the site, it creates a "staged user account" - that way they can play around for a bit, and if they like what they've done so far they can register and it carries in all their data. If they leave without registering, and come back in a week - that non-registered user would have been lost (not deleted) anyway due to session clear. So we just want to delete "dummy" accounts, definitely won't be deleting any real accounts.

And yeah, a "delete" button need to happen soon.

**Comment by Pandoro** [comment]
In that case I would go for a full on delete ;)  Especially considering their non checked dailies will create data and their habits will be tracked as well right? Probably you can better handle that 1% of new users which gets angry after loosing some stuff after 1 month, then having all active players suffer due to these few. 

Btw. about the date stored as strings, is it really so hard to write a little data parser? I have no idea about web-development, but in languages such as java or c++ there will probably even be some predefined methods for that right?

**Comment by lefnire** [comment]
Not difficult, can be done with map-reduce if we want it as a mongo script, or easier yet if handled by Derby which fetches those fields as a proper date with `model.get('_user.lastCron')`. Maybe a once-a-day server-side poormanscron which uses `model.fetch 'users'... -> _.each users...`. Was just forewarning my initial attempt in case anyone was going to take a stab at it before I return to this.

**Comment by StanLindsey** [comment]
Would it be possible to maybe "archive" data from live users after a certain time period. Export them as after a number of days the entries are static anyway?

**Comment by lefnire** [comment]
i'll look into that, but the reason I think we should _delete_ >1mo non-registered users is that their browser will have lost that session anyway when they revisit the site, so they have no way of recovering it anyway - it's lost in space.

**Comment by StanLindsey** [comment]
Yeah i agree with that, I was commenting on live users though.

**Comment by lefnire** [comment]
ah, i see - good thinking

**Comment by lefnire** [comment]
I've got the code for preening staged users [here](https://github.com/lefnire/habitrpg/blob/30db654eead8d635e021709038b79ce6f396de76/src/server/cron.coffee). I've got some pre/post sanity checks, but given recent bad success with simple update queries, I wanna make sure to run this after a backup, and when some people can test around afterwards. @SlappyBag @toebu wanna take a look at at the code to spot any dangers? I've run this locally, check - but should we run this stuff on a staging server instead?

**Comment by lefnire** [comment]
notes: it runs every time the server restarts, a poorman's cron - maybe I should probably create a real midnight cron for this?

**Comment by lefnire** [comment]
stales users are now being preened periodically. still need to preen user history lists

**Comment by horusofoz** [comment]
@lefnire Should this be on Trello for tracking?

**Comment by lefnire** [comment]
naw, this quite technical and non-feature-ish. I'll keep keep this open until I fix it.

**Comment by switz** [comment]
Why do you need a date string? Why not use epoch time?

**Comment by lefnire** [comment]
just simpler storage, no? I can't remember what the issue was, it may have been in mongo date comparison or something? But previously I had some trouble working with js date obj stored in the db. I saw in all derby examples they store dates as `+new Date`, so I didn't think anything of it and switched over. Do you prefer to use js objects instead of string? (is that what you mean by epoch time?)

**Comment by lefnire** [comment]
history-preening added in https://github.com/lefnire/habitrpg/commit/22d4bb27acc53a58724c338679df3c62e9898117

**Comment by wizonesolutions** [comment]
Does it work the way it was specced? e.g. my history will begin getting averaged after a while? As long as I can see the last few days in order to know when I last did something to a Habit, I guess it's fine. Even better if the UI would tell me somehow so I wouldn't have to use a CLI app to check :)

**Comment by lefnire** [comment]
Better if the UI would tell you what?

Yes, works the way spec'd. See https://github.com/lefnire/habitrpg/blob/989d5839c4fbd3948c328ee89ab21aff53c3f38f/migrations/preen_cron.js#L43

**Comment by wizonesolutions** [comment]
If the UI would have a sort of activity log or something (the chart can be hard to grok). I often think, "Have I already upped that Habit today?" It's particularly tricky to check how often I did it with +/- habits. With +-only or minus-only that I only up/down once a day, the color tends to give it away.

**Comment by lefnire** [comment]
Ah - well at present, if you've been around for 1.5 years it keeps about 18
entries. The first 7 are days, but if it's a habit that you clicked
multiple times they'll be multiple entries for today. If you just look at
the right-most graph points, and and you see any entries for today - that's
how you can count how many times you've clicked today
