### ISSUE TITLE
Daily checklists didn't clear after rollover

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2202]
The dailies themselves are unchecked after refreshing the page, but the checklist items are still checked as they were yesterday.

**Comment by lefnire** [comment]
they'll be fine tonight. The reason was checklists was only on beta, and so was the server cron for handling them. So if you opened habitrpg.com this morning, or any API hit your user (mobile, chrome extension, etc) then it used production cron. Checklists are going live now, so we'll be solid

**Comment by marcelosizer** [comment]
@lefnire I believe this issue is still happening. Last night I ran home to check off a **gray** daily that already had some of the checklists marked. Then I checked the last one and then the daily itself but when the page reloaded it was already past midnight. My other dailies reset while this one was checked as well as the checklists that I marked yesterday.

**Comment by lefnire** [comment]
That sounds more like #1057

**Comment by marcelosizer** [comment]
The point is I don't use custom day start and the other dailies that were checked got reset, only this one with the checklists didn't. Also I checked off the checklist/daily near midnight so I'm not quite sure whether I checked it yesterday or today. I actually ran home an opened my notebook as I parked my car in the garage at around 23:58 and rushed to the website but it took a while to connect.
