### ISSUE TITLE
Checklists on Challenges?

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2205]
When adding a todo to a challenge, we have the Add Checklist button, but nothing happens when clicked.

**Comment by lefnire** [comment]
I can (only one):
1. remove them completely
2. user can add a checklist (not challenge creator)
3. challenge creator can add a checklist (not user)

your call

**Comment by lefnire** [comment]
Crap, I can't remember which was B in the tavern, I delete my message to take it here :) Which one again @wc8?

**Comment by wc8** [comment]
I’d say 3—challenge creator and see how it goes.

**Comment by lefnire** [comment]
Ok, will do when I hit the code. 1 is mechanically implemented (though button's still there), then I'll implement 3 when I can

**Comment by wc8** [comment]
@lefnire have you done anything with this? 
I’m leaning toward #2, now: user can add a checklist, not the challenge creator. 
Should we do a poll?

**Comment by lefnire** [comment]
I'm leaning towards 2 as well. So as it turns out, that's the way it functions presently (by accident) and works just fine. The only flaw was the button is visible when creating a challenge, but doesn't do anything. Pushed the fix to hide the button, but didn't touch anything else and 2 is done

**Comment by ld89** [comment]
Hi, I'm here from #2343 and I'd just like to vote on the Challenger being able to create the checklists. I have a group of perhaps 25 items I'd like to add four steps each for, which make 100 to-dos if I separated them all, or it would be a huge pain for the Challenge-ees.

**Comment by bradleyrose** [comment]
@wc8 and @lefnire: I'd like to appeal for the decision on challenge to-do tasks having checklists to be changed to include implementation of allowing the challenge creator to add checklist items. 

As a challenge creator, I would like to be able to create a to-do task and add checklist items. Imagine, for example, a "learn math" challenge where "geometry," "algebra," and "calculus" are to-do tasks. Within each of those tasks, I'd add checklist items like "pythagorean theorem" or "factorials." 

I understand that checklists in at least some contexts can contribute toward earning rewards and/or taking damage, and I don't know if this is what is creating an issue with implementing checklists for challenge to-do tasks. Because of this possibility, I'd like to mention that I care less about having that functionality hooked into the checklists correctly and more about having the ability to organize my tasks with checklists.

Implementing this feature to allow challenge creators to add checklist items will help the potential hassle of having dozens, if not a triple-digit-number, of tasks to organize, as me and @ld89 are currently dealing with at the moment.

Thanks.

**Comment by wc8** [comment]
I'd be fine with challenge creators having control of checklists for organizational benefits, etc.. The main thing lost (that I've thought of) is a participant-editable field, but maybe that could be addressed with participants having the ability add their own notes. 

If it seems helpful, we could add a poll in [The Gatehouse](http://habitrpg.wikia.com/wiki/Board:The_Gatehouse), e.g.:
`<poll>Who should have be able to add checklists to challenge tasks? Comment with why.
Challenge Creator
Challenge Participants
</poll>`

**Comment by ld89** [comment]
A poll sounds rad! It'd be a good way to sort of give it a final settling I guess?

**Comment by bradleyrose** [comment]
I was going to put up a poll, but using the markup and formatting as @wc8 provided gave an odd visual in the Preview section. I wasn't sure if that's because of the preview mode or because I wrote something incorrectly.

I see that I can edit initially posting, so when I have a block of time, I'll work on putting that up and then making sure it's formatted correctly. Unless someone beats me to the punch!

**Comment by bradleyrose** [comment]
There we go. Created a poll on the Gatehouse board. Thanks, @wc8, for the suggestion! http://habitrpg.wikia.com/wiki/Thread:10126

**Comment by wc8** [comment]
I added a mention in the Tavern.

**Comment by bradleyrose** [comment]
@wc8 Thanks for that! For how long should the poll run before a decision is made? @lefnire
