### ISSUE TITLE
[Issue] Basis for death.

### ISSUE THREAD

**Issue by Yughurt** [HabitRPG/habitica#223]
While dying is a sound concept in gaming, if you ever remembered playing for hours and you forgot to save; dying in this is worse. Having tried out dying as a motivational concept, dying makes you want to quit all together. I think that you should simply lose a level (which is a significant amount of work still)

**Comment by wc8** [comment]
Curious, as one who barely escaped death due to now-resolved bug of hidden todos (now visible again) followed by no internet access until after midnight, what happens on death?

**Comment by Yughurt** [comment]
You go back to level 1, losing all gold and equips. Although you can still buy all the equips previously unlocked.

**Comment by wc8** [comment]
I wonder if there could be incentives for getting restarted and a banner/notification to that effect: 
For example, 
- Every habit completed after death is worth twice as much
- Completing all your dailies that day results in one item of equipment being restored
- completing an old todo gives a half-price on one item (not a real currency item, items such as, "potion", "armor")

**Comment by rixx** [comment]
Sounds good except for your first point: If every habit was worth twice as much after dying, you might consider suicide if you were close to death anyway.

**Comment by horusofoz** [comment]
Possibly a motivational message or two in the "Game Over" message to get users to want to try again.

Examples:
- “Never give in, never, never, never, in nothing great or small, large or petty, never give in except to convictions of honour and good sense. Never Yield to a force; never yield to the apparently overwhelming might of the enemy.”  ― Winston Churchill,
-  “Many of life's failures are people who did not realize how close they were to success when they gave up.” ― Thomas A. Edison
- “When you get to the end of your rope. Tie a knot and hang on.” ― Franklin D. Roosevelt
- “Never confuse a single defeat with a final defeat.” ― F. Scott Fitzgerald
- “You go on. You set one foot in front of the other, and if a thin voice cries out, somewhere behind you, you pretend not to hear, and keep going.” ― Geraldine Brooks
- “Children have a lesson adults should learn, to not be ashamed of failing, but to get up and try again. Most of us adults are so afraid, so cautious, so 'safe,' and therefore so shrinking and rigid and afraid that it is why so many humans fail. Most middle-aged adults have resigned themselves to failure.” ― Malcolm X

**Comment by horusofoz** [comment]
I think we should avoid lowering difficulty post-death. It would take away from the experience of earning in game advancement through real life action. @rixx's [point](https://github.com/lefnire/habitrpg/issues/223#issuecomment-12753326) is a very good one. If death loses it's digital sense of finality and indeed becomes advantageous at the lower levels, the motivation to avoid it by GTD in RL is drastically reduced.

What we need is a motivational tool to encourage user's to pick themselves up, dust their digital shoulders off and get back at it.

My first thought is a motivational quote such as above. 

Second thought is targeted advice that states what was the biggest HP sapper and recommending the user pay special attention to completing that habit/task in this new life.

**Comment by wc8** [comment]
Suggestion here #246: give the user new life after death.
I suppose the idea is dying is a new beginning.

**Comment by ghost** [comment]
@wc8 after you run out of health your character should regenerate to a totally new character, maybe a ginger? It seems to work for BBC television =D. Fish sticks and custard.

**Comment by ghost** [comment]
@wc8 maybe a heaven or hell sort of thing could be implemented complete with background change?

**Comment by wc8** [comment]
@Neohuman More of a seed dying in the ground and becoming a new plant, but I was just thinking of emphasizing the positive: you restart the game when your character dies; so as soon as dying is done, draw the user's focus to re- **start**.

I thought your idea might be one way of drawing attention to the new chance. 
If there are enough character options (red-head (is that what you meant by ginger?), elf), it might be a fun twist on a new beginning. However, the user should be able to change back, in case they don't like the random assigned character. I suppose it could also backfire, and emphasize the loss.

**Comment by ghost** [comment]
@wc8 maybe it should just be an option instead of a default. Oh and the ginger thing is a doctor who reference.

**Comment by horusofoz** [comment]
In addition to the [proposed](https://github.com/lefnire/habitrpg/issues/223#issuecomment-12766850) motivational attempts, I would suggest we "reincarnate" the character as a descendant of their original character.

This maintains RPG/D&D immersion and a sense of continuity for the user without reducing the impact of "death".

The reincarnated character would have the same visual representation as the original character did on level 1. Add to that the motivational messages and warning of how their ancestor passed (possibly a linkable rofile page with a tombstone) leading into a recommendation of how they can avoid such a fate (worded using D&D themed language).

Does this cover all bases? 
- Death is deifinitive.
- Motivation to continue.
- Sense of continuity.
- Advice on what could be done better.
- RPG/D&D immersion unbroken.

If interested please give a +1 so we can migrate this to Trello for voting.

**Comment by Pandoro** [comment]
A different idea that comes to my mind which would make the system a little less harsh, but still hard would be something as you also see in many games.

If you die, you can click a revive button. (This makes sure nothing happens automatically if you are on vacation or sick etc.) Then you are revived with only 10% of your hp and you go back one level (or receive a large exp penalty) As said earlier, level one is a bit dramatic and I too think so. However if you loose 1 level and your hp gets reduced to only 10%, then you will have to work hard in order to stay alive until you level up again or earn enough gold to get your potions. This way you will not start from scratch, but you will be motivated to work harder next time, with the added bonus of gentleness towards not being able to reach the computer.

**Comment by StanLindsey** [comment]
@horusofoz - just like in Infinity Blade. I like it. But I also like the idea of simply going down 1 level and loosing your gear. It isn't completely demotivational then.

**Comment by wc8** [comment]
The descendant idea is well thought out. 
It might be able to be combined with the revive button (hm... what does reroll do?). 
I suggest revive only be available once in a row. Perhaps after that, your guy's descendant takes over.

**Comment by wc8** [comment]
Clarification: I suggest revive only be available once in a row _within the same level_ you regain the revive button if you can make your guy level up.

**Comment by horusofoz** [comment]
I like @wc8's idea. Possible additions;
- One free revive per level up to level 10.
- One more free after level 10 and user advised no more freebies.
- Expensive revive potion available from digital store (User has to earn a lot of GP for this).
- User can only hold one revive potion at a time.
- When user revives, loses all GP.
- Possibly increase price of revive potions per purchase.
- Possibly earn a potion through "streaks" or completing difficult public challenge?

This way we do give plenty of opportunities to stay alive, within reason, and have the descendant/ancestor method in case of user still dying.

**Comment by Pandoro** [comment]
I can see that many people seem to like harsh penalties when dying. I would like to stress though, as I have in the disease thread, that not every one plays on the same level. If we start speaking about "expensive" potions, then I think this might not be acceptable for people, including myself. I don't have the time to gather something like 50GP in order to revive myself. And if I die by some stupid circumstance like broken internet or a broken pc, I will be severely demotivated to play on when loosing all my gear and levels. What attracts me about the game is collecting new games and levels. Would I loose all this I think I would stop playing right away. 

I get however that there are other people who like the hardcore style. So I would suggest different levels of difficulty to solve this problem. Those who like it easy can still play, as it doesn't really affect other users and those who like it the hardcore way can do that as well! 

I would think of something like:
1. Easy: You die, you loose up 50% of the currents level exp, but never more than down to 50% of the previous level. Furthermore you revive with only 25% of your max hp.
2. Medium: You die, you loose 100% of the possible exp for this level. Furthermore you get revived with only 10% of your max hp. You also loose all your gold.
3. Hard: You die you restart. (Or whatever fancy ideas you guys have for hard ;) ) 

Or other distributions, this is just to give a rough feeling for my idea on this. 

I get that there should be a penalty for dying in any case! And I also think the game is made in such a reasonable way that we never need to die. However would it happen, I don't want to be so discouraged that I stop playing :-/

**Comment by wc8** [comment]
I haven't invested so much that I would lose much if I died. I'm beginning to appreciate more the potential for discouragement/despair:

1) repeated death at lower levels. _I'm never going to get anywhere with this_
2) death after months of hard work _one bad week and it's all for nothing_ especially if combined with:
3) death after many in-game purchases, character development, etc. with the prospect of a lot of hard work in real life (not fun game time) to recover
4) death by circumstances outside the user's control: no internet access, broken pc, illness, etc., in-game bugs, user misunderstanding how the game works
5) unequal vulnerability to death because of different kinds of playing: 
- a user who only records 5 major tasks is not going to earn enough gold to buy a revive potion, whereas a user who enters 25 minor tasks may be able to buy 50 revive potions; 
- a user who plays by himself cannot be revived/healed by his party member

**Brainstorming for solutions:**
2&3) in many typical games, you can save your character and reload; there's no way to do that in real life or in HabitRPG. In real life you haven't really lost those months of good habits; you still have them, death in HabitRPG does not acknowledge that
- health levels up: the more you play, the stronger your constitution #248
- Major injury before death: lose a level, lose particular kinds of gear
- let users inherit some/all of their ancestor's items, along with a letter from their ancestor about what went wrong in his life ;-) [**update:** with encouraging words of wisdom for the descendant's life]

4) I think this is critical, it's a problem even outside of the purview of this thread. I suggest:
- make #153 Rest-In-Tavern as account-freeze automatic triggered by a specified period of user inactivity: no loss/no gain until the user clicks again
- provide options for correcting previous the record such as [Record Previous Activity](https://trello.com/c/CaAm7APS) and [Undo Button](https://trello.com/c/RQIp0Yl5). 

5) 
- @Pandoro Your suggestion of different difficulty modes sounds good.
- make revive potions a percent of available gold, so it would always be expensive, but always be an option.

**Comment by StanLindsey** [comment]
Fantastic work @wc8 & @pandoro - I am loving the ideas and analysis in this thread. I'd not thought about people who would struggle with HabitRPG as it is not only fairly easy at the moment but I assume most of us who are involved with it right now are already comfortable with out productivity/motivation.

Great work.

**Comment by dbueller** [comment]
How about a "Critical HP" status.  Maybe something like: if you had HP in the evening, but undone dailies cause you to drop below 0, you have "Critical HP."  At this point you have the day to try to restore your HP and do nothing that will cause it to drop.  Maybe tie that in with a +1 HP as a bonus for completing all dailies.

**Comment by wc8** [comment]
[Auto Freeze for inactivity](https://trello.com/c/UqxYFiqG) added to trello.
Edit: This does not represent the main request of this thread, just the suggestion to address the problem of death-by-lack-of-internet. ;-)

**Comment by horusofoz** [comment]
@lefnire What would be the probability of setting up difficulty levels with different "Death" outcomes?

**Comment by W1ndW0lf** [comment]
The only thing that got me to do my habits this morning was my low health and that I would lose everything.  If I was just going to lose a level I probably would not have done them.

**Comment by Pandoro** [comment]
Then I guess the hardcore level would be good for you ;)  However I wonder how long you could really keep it up like that. Soon you will loose another level and another and another etc.

**Comment by W1ndW0lf** [comment]
Forever :)  That's the whole point of me using this.  (until I run out of real life hp ;))

**Comment by Yughurt** [comment]
Sorry I've been overseas but anyway I'll give my however many cents.

I was thinking actually something like a diablo sort of system where if you die, you have the chance to get all your equips back, but lose exp and gold.(the descendant thing can still work. You're going to go find... your ancestors body...) To get your stuff back you must complete everything that killed you for three days straight. That way you're motivated to try hard to get things back and three days and loss of exp and gold, or maybe more, is enough work to be a deterrent. Failure to do a task that killed you results in loss of a piece of equipment + more gold (get looted by that monster) Maybe not 3 days in a row but a total of ten times (a choice?)

This sort of system is sort of cool because he can be naked (loincloth) and have a little message for you with a progress bar (which could be a dungeon move the hero and status to the left) to see the "monsters"/tasks that you have to overcome in order to get your thing back!

**Comment by wc8** [comment]
I like the idea of 3 days of consecutive task completion to recover items (or find ancestor's bequests), and the progress bar &/or messages, but not the attire suggestion. I think level one attire is simple/plain enough.

**Comment by Yughurt** [comment]
The attire wasn't seriously about being a loincloth. I meant it with starting clothing.

**Comment by StanLindsey** [comment]
I thought the attire was only during the 3 day streak you have to do. I like that idea =P

**Comment by danj3ris** [comment]
@Yughurt The Diablo system I think would work really well.

My tweaks to it: Death should take bribes. Lose half your gold, and you get half your health back. Lose all of your gold and you get your 50 health back. No levels or experience lost. But Death's offer will get worse if you do it again. If such a feature were to be implemented, I don't think Death should take bribes from anyone less than level 10. When you die you die. Above that, Death wants your soul to possibly mature a little more for his Army.

Hence a character over level 10 who cannot provide death with a high enough bribe, dies and begins back at level one. Now death has a servant, an undead version of the player who died. This servant shows up either as a boss or a lesser battle to interact with other players who have now reached the level at which the original unfortunate player finally "gave up the ghost" to death.

Edit to add: Perhaps the player who died (as long as they are over level 10) has a tombstone placed to the side of their  dashboard. When another player later on manages to vanquish death's servant, the tombstone should glow and read "Here lies "player", avenged by "Other Player". The player who died in his/her past life receives gold or an item due to the bravery of "Other Player". Player hopefully says thank you. Maybe even forms a party with them.

**Comment by StanLindsey** [comment]
That idea is genius. (Yes, thats all I have to say)

**Comment by Yughurt** [comment]
The bribe idea is really good! But especially for people who just start using habitrpg, I think they'd like the ability to take bribes otherwise the issue where you're like "...well that sucks happens" and the magic of the gamification wears off. The feature would also be hidden because you wouldn't know it was going to happen. Let them learn early, then they're like crap, don't want to die. :P 

P.S. Should be laid to rest not avenged but it is a nice idea. 
And lol slappybag

**Comment by StanLindsey** [comment]
Aha, well, it most likely wouldn't go in exactly how its typed on this page but overall its a great way of managing failure and promotes cross-user interaction in some way.

**Comment by lemoness** [comment]
I'm glad people are addressing this; as someone who is not a gamer I can tell you I would instantly quit if I lost all my levels or items, even right now on level 4. This is ESPECIALLY true if people lose equipment that they have spent tokens (real money) on! 

I think the only way to make everyone happy is to use @Pandoro's self-imposed difficulty settings. Those of you who say that you need the threat of death to keep going, that's awesome! 

But people like me who are not in the hardcore gamer world see that sort of thing as a huge negative to using the service at all. When I started to read this thread I was so appalled I considered just deleting my account. If I can have an easy death, where I just lose some stuff and go down a level, I don't feel that preemptive frustration.

Also - I do not like the descendent idea, not at all. This has to do with a difference in viewing the avatar.

For the people contributing to the thread, it sounds like the avatar is a character - some random video game person that they've invented.

For me and my friends, the avatars are US. My avatar is leveling up when I do real-life activities - obviously, this is because she is me! The idea of dying and suddenly being replaced by my hypothetical future grandchild completely goes against my big motivation to play, which is seeing "myself" get better.

Since I imagine that there will be a substantial proportion of players who feel this way, and they are likely to be the players who are not browsing through the issue list threads, I thought that it was important to share my perspective.

**Comment by StanLindsey** [comment]
@Lemoness - Thank you so much for your input. Obviously many of us are hardcore gamers and are bias towards certain playstyles. You're input is incredibly helpful!

**Comment by danj3ris** [comment]
In taking into account @Yughurt's and @lemoness's input, I've had some thoughts.

Death should accept bribes earlier. Let this be an unlocked advantage at level 3. But maybe don't announce it to the player. Let them discover it if they unfortunately have to meet death. :) I say level 3 because a level 2 player is still inexperienced, the chance of death is still too high, so ANY negative affect of it may make someone quit outright.

Death should be damning. If death wasn't severe, players would not care if it happened. But @lemoness has a point. The bribe idea allows you to suffer a penalty, but not a "point of no return" punishment. HRPG wants you to keep playing. So I propose the bribe to death is always half of your gold. Considering better items get more and more expensive, losing half your gold hurts, but it doesn't hurt enough to make you quit outright. You still have your items, you still have your levels, but death took it's toll.

I agree with @lemoness in terms of the descendant idea. While the idea is cool, your descendant is not YOU. My prior idea about creating "a servant of death" was a different way of continuing  @horusofoz's idea of a descendant, plus creating a possible monster or boss to contend with.

I modify the idea in 2 ways:

A: 

All the gold that goes towards bribing Death funds Death's army. Give Death it's own profile page, let it show who (players), and how much they have contributed to Death's coffers. Heck, give it an HP bar. Every servant of Death (the army) that is vanquished decreases some of Death's HP. I suggest Death's HP be 1 million by the way. It would be great to see how much Death has been hurt by the players over the course of a month, week, year even. If not enough player's die to fund Death's army, let the act of buying a potion also fill Death's wallet (You are holding Death off by purchasing it, so consider it a death tax). Perhaps, somehow, some way, even if it takes all year, if enough of Death's army is vanquished...

B.

As inspired by @Pandoro's idea of varying difficulty levels, the introduction of "Hardcore" mode. Entirely different rules that Death plays by. Maybe even my original Death's Servant idea above.

**Comment by StanLindsey** [comment]
I really like idea A, thats an awesome encapsulation for some great meta-gaming.

But, the bribe being 50% of your gold basically eliminates death altogether, who would die & lose all their gold over giving half their gold?

Maybe death should roll a dice to give some variety and also give the sense that dying is always unknown. You could lose an item, lose some gold, lose a level or other effects. Each time you die within a certain time frame (
say a week or fortnight) death changes his dice to slowly have worse effects until the only option is to fully die and reset from 1.

This would act in a similar way to the above suggestions as it would motivate people to do better in order to rid deaths effects but would also act as a punishment for failure that wouldn't be too harsh at first.

And it could easily fit into the above meta game, every item you give to death improves his armies attack or defense, every time somebody fully dies he gets a soul to add to his army. There would be more stats build into a meta game. 

Thoughts? Especially @lemoness

**Comment by wc8** [comment]
Graveyard profile page: **Privacy** could be an issue for some players. Maybe a way to opt out or, for an extra GP fee, be added to the Tomb of the Unknown Player?

Graveyard suggests contrasting idea: **Grand Habit Masters**—with privacy option, qualifications to be discussed elsewhere.

**Comment by lemoness** [comment]
I think that the difficulty levels plus Death's dice could be work perfectly and also be interesting!  I'd choose the easy setting, and knowing that Death's rolls would cause me to lose some gold or a weapon or - EEK! - a level, that makes me want to avoid Death, but it doesn't make me despair. Meanwhile, all you less-wimpy players can risk ultimate tragedy to your heart's content :)

I also really like the idea of Death having his own profile page, although I absolutely agree with @wc8 that a graveyard profile page could have some big privacy problems. Having Death as a character is compelling! And it gives the players a fun common enemy. 

Thanks for listening! You guys are great.

**Comment by horusofoz** [comment]
We've had some awesome input and discussion here guys. Now lets try to group and summarise into three available difficulties.
- Adventurer (Easy) - ....
- Journeyman (Medium) - 
- Hero (Hard) - ....

**Comment by Yughurt** [comment]
Sounds like this has been pretty much well summed up. You'll have to try some implementation and user testing to see how well it works. (Should ask the user some questions about the type of player they are, etc, etc so you can try identify more users like lemoness :D )

**Comment by MicahSaco** [comment]
What if, when you die, you are sent to a form of Purgatory, where you shown your weakest habit by Death. 

You then have to create three new sub-habits to support the death-bringing weakness.

 For instance, if it's brushing your teeth that is your downfall, the three supportive habits would be: 1) leaving your toothbrush out in a place that reminds you to use it, 2) adding a one reminder post-it note to your environment each day 3)read one article about dental hygiene.

You would ONLY concentrate on this habit as an act of Redemption for your soul in Purgatory. When you have accumulated enough points working on your weakest habit, you will be resurrected to your character at 30 percent of his experience, but now empowered by facing your greatest weakness, which ultimately led to your doom.

**Comment by caycefischer** [comment]
OK so this is something we just talked about in the Hangout, a natural evolution of some of the comments here and on kickstarter.

Death is a "state", so when you die you temporarily lose your gear and pet. You have to do something good (either complete X tasks, or go 1 day without missing a task for example) and that will mean you clawed your way out of the underworld and then emerge to claim your gear and pet again.

This makes death not a large penalty, but more like part of the narrative and keeps people engaged.

@lefnire @SlappyBag

**Comment by maxiboch** [comment]
Maybe using a phoenix as a metaphor might make this moment more exciting? You emerge from death reborn and have a window of time during which your tasks & habits are worth a bit more, allowing you to quickly earn back your gear, your pet, etc.

**Comment by ghost** [comment]
The phoenix is exactly that in mythology

**Comment by wc8** [comment]
I think #363 is a good/best option. 

• it's simple and uniform
• Death is Significant: game over message, loss of equipment
• Motivation to continue: Attractive Phoenix Quest. 
You have a chance to recover your character and regain equipment. If you fail to achieve the quest in time, by the time you do, you've been moving forward in the game, accruing XP, GP etc. as before.
• Sense of continuity: your character stays the same, you keep on going, etc.,
• RPG/D&D immersion unbroken.
• Advice on what could be done better could still be implemented.

Anything missing?

**Comment by lemoness** [comment]
I think that sounds good! I would still suggest giving the users some kind of choice over a difficulty level, so that if they are on easy mode and fail the resurrection quest, maybe they only, say, lose three levels and three pieces of equipment.

**Comment by lefnire** [comment]
I added this to [Trello](https://trello.com/card/death-mechanic/50e5d3684fe3a7266b0036d6/204) for my own tracking purposes. Feel free to edit (@wc8) and people vote

**Comment by wc8** [comment]
Card updated. I used #363 with a variation on the really dying part to match my last comment. If that's not what was intended, it can be changed.

**Comment by lefnire** [comment]
Perfect, thanks a millino

**Comment by wc8** [comment]
@lemoness I'm thinking the quest should be significant but achievable, such as [quest tasks being _x_ % of daily tasks to be completed for _x_ number of days](https://github.com/lefnire/habitrpg/issues/363#issuecomment-14233050)

**Comment by lemoness** [comment]
The quest seems fine - I am more concerned with the consequences if the quest is failed for whatever reason. 

Why do we have two different threads for this? Is there a way to merge them, or confine discussion to only one?

**Comment by wc8** [comment]
@lemoness I was originally responding to that particular idea, but since it has become part of this thread. I'll stick with posting here. Which consequences concern you?

Maybe this is a terrible idea, but what about tokens to preserve armor? If you buy say, a Castle Keep, you can put your armor, equipment pets in it and you won't lose them after death. You can restore them to your character in a new game.

I added the following to the Trello card, after reading @Pandoro's reply in the other thread:

> **Difficulty Slider**
> Allow user to choose playing level, changes allowed at start or after Phoenix Quest ends: 
> Habit-Building, Moderate, Severe (placeholder names).
> _Habit-Building_: No equipment loss, player loses a level before dying
> _Moderate_: Phoenix Quest as listed on [Trello card](https://trello.com/c/k2MWBcxl).
> _Severe_: Full Game Over & Restart: lose all equipment, no phoenix quest, no elixirs

**Comment by wc8** [comment]
See Trello Card. Updated Slider per @Pandoro's suggestion, except for slight tweak of _severe_ to:

> Severe: Fail quest, restart character from level 1 with XP, GP gain from whatever was accomplished during quest.

**Comment by wc8** [comment]
Updated card, cleaned up description. If there's any concerns left, chime in. Hopefully, though, we have something that will meet most people's needs now. 

A few more details remain to be worked out, such as how many days, what percentage of daily tasks need to be done. I'm thinking 75% of daily tasks and 1 day per level. Maybe for the higher levels (eg., above 14), 1 day for every 2 levels +1 day. So level 14 recovery would take 8 days.

**Comment by lefnire** [comment]
Thanks so much @wc8, some of these tickets are completely escaping me as I'm working on criticals - having the full story in a Trello card like you've done is going to help me _so_ much when I jump into this issue

**Comment by lefnire** [comment]
gonna break my own rule a bit here and remove the `critical` tag, only because I'm gonna track it's important on Trello for my own house-keeping.

**Comment by wc8** [comment]
Should we close this for housekeeping?

**Comment by lefnire** [comment]
let's
