### ISSUE TITLE
Purchased Gems Not Showing

### ISSUE THREAD

**Issue by stormyhearted** [HabitRPG/habitica#2238]
I just purchased gems; the payment shows as completed in my Paypal, but after refreshing and logging out/in, they're still not showing.

(I see this issue's come up before- I wasn't sure if I should start a new thread or post in a closed one.)

**Comment by lefnire** [comment]
What's your UUID?

**Comment by stormyhearted** [comment]
It's 103c0def-d25f-424f-a4c1-ab7ca7655710. Sorry, should have included that to begin with.

**Comment by lefnire** [comment]
give that a shot, sorry for the inconvenience!

**Comment by stormyhearted** [comment]
Not at all, these things happen. Though I'm showing 40 gems, when I only bought 20. :)

**Comment by lefnire** [comment]
auto-grants gems for the troubles ;)

**Comment by stormyhearted** [comment]
Oh wow, thanks!

**Comment by Liviko** [comment]
Hello, I'm not sure if this is the right place to say this, but I also donated 5 USD on paypal that are not showing in terms of gems.The paypal transaction was on 27th December and I waited, because paypal... My user ID is 78db1000-fed6-44af-a2fe-3fa5d241a9f6 . I also wanted to say thank you to the developers for creating such a wonderfull thing !! :)

**Comment by lefnire** [comment]
Hey, sorry about that. Give that a whirl, extra gems for the extra troubles.

**Comment by Liviko** [comment]
I'm sorry but they're still not there. Am I doing something wrong? Is my level too low?

**Comment by lefnire** [comment]
check again per chance? showing as √ in the db.

**Comment by Liviko** [comment]
Oh, they're home now! Thank you very much!
