### ISSUE TITLE
Sort button for guilds/party members does nothing

### ISSUE THREAD

**Issue by erratio** [HabitRPG/habitica#2239]
In Chrome on a PC. Tried different sort options, reloading the whole page, no change.

**Comment by erratio** [comment]
Actually, turns out it does do something - it changes the order of my party members' avatars up the top of the screen. And that's regardless of whether I try to change the order from within my party or from within a guild

**Comment by deilann** [comment]
Wait, no, reopening this:

Sort button doesn't do anything except things that are not really useful. It would be nice to actually sort things.

**Comment by brightbold** [comment]
Also, (feature request) it would be nice to have Alphabetical as a sort option. So that if you were looking for someone in particular you don't have to try and guess how many pets they have. :)

**Comment by casicastiel** [comment]
Why was sort by number of pets even ever a thing, anyways?

**Comment by deilann** [comment]
I was wondering the same thing, the other day, wrt number of pets.

**Comment by ThisIsBlank** [comment]
I've been trying to sort, and now it seems it doesn't sort the members list nor the avatars at the top of the screen.

**Comment by swagath-s** [comment]
Chiming in.

Same issue, except for me it doesn't even sort the avatars on top. Firefox, OSX.

Agree with adding 'Alphabetical' as an option and removing 'No. of pets'.

**Comment by lemoness** [comment]
For what it's worth, I have it on random sorting, and that works! But I agree that it would be nice to have other ways to sort.

One type of sorting that I'd like to be able to do is backgrounds vs. no backgrounds, though I don't know how difficult that would be. It would be aesthetically pleasing to have all your party members with backgrounds grouped in a line, without blank spots in between!

**Comment by Alys** [comment]
From the look of the code, the sorting was only ever meant to affect the avatars in the header. The bug is that it's labelled badly and it appears in the guild pages when it shouldn't since it's not (yet) relevant for guilds.

I'll add alphabetical and background sorting (I LOVE the background sorting idea).

I won't remove the pet sorting. There's no reason to remove existing features unless they are confusing or they produce too much clutter, neither of which is true in this case. Also, I use pet sorting in the party that I'm normally in. :P

After that, I'll see if I can make it sort the list of members names too, in parties at least, and in guilds as well maybe. No promises yet.

**Comment by brightbold** [comment]
Yeah I was really only talking about guild sorting. The last time I checked, no matter what I did I could only see the same X members of each guild, so if you wanted to know if a certain person was in the guild and they weren't one of the names shown, there was no way to check the rest of the list. (note: just checked; this is still true although someone has renamed it "Party Members list ordering" to indicate it doesn't work on guilds, but it's still right there in the guild members section so it's confusing.)

**Comment by Alys** [comment]
Pull request https://github.com/HabitRPG/habitrpg/pull/4022 adds sort by name and sort by background. Due to how the original code is written, sort by name is actually from Z to A, rather than A to Z. Reverse sort makes sense for some of the other sort options, and I didn't think it was worth building in an exception for names.  However an exception can be added later if needed.

I've also clarified the wording above the sort option drop-down menu to indicate that it's just for sorting the party avatars in the header.

I've removed the sort option feature from all guild pages.

I've thought more about sorting the lists of members names for parties and guilds and decided it would be best to not do it. For guilds, I think it would probably be dangerous. A guild with hundreds of members could require a lot of processing for sorting them all - slow page load time, more load on the server. Also, there's not much point since only a few guild member names are shown (again, for load reasons).  For parties, sorting the names would be less dangerous (unlikely to have very large parties) but it's still not really worthwhile when the list of names shows only some, not all. And you can use the avatars in the header to see the members, sorted, anyway. If the potential load issues are ever reduced enough that you we can display all guild/party members names, then sorting those names could be revisited.
