### ISSUE TITLE
Beast Master achievement disappears when pets become mounts

### ISSUE THREAD

**Issue by baconsaur** [HabitRPG/habitica#2243]
This makes sense, but personally I'd prefer that once we have it, it sticks even if the pet count drops due to growing them into mounts. Achievements are permanent in most games. I don't know if this is intentional or not, so I thought I should bring it up.

**Comment by SabreCat** [comment]
There's more funkiness afoot with this. My "pets found" count continues to increase, on my Stats & Achievements page, even when I raise a pet into a mount, then replace it by hatching a new pet of the same type.

**Comment by lefnire** [comment]
@baconsaur not intended, but known. The achievement calculation is handled on `user.save()` as a [dirt-simple math op](https://github.com/HabitRPG/habitrpg/blob/develop/src/models/user.js#L338). We'll need to put some thought into how to otherwise handle it, I've just been wrapped up in other things

@SabreCat woa :o that's a-strange

**Comment by talljosh** [comment]
I have the same issue as baconsaur - I had the Beast Master achievement and now it's gone, presumably because one of my pets is now a mount.

**Comment by lefnire** [comment]
This should be fixed now as of https://github.com/HabitRPG/habitrpg/pull/2557 .
