### ISSUE TITLE
Automatic Allocation

### ISSUE THREAD

**Issue by eineg** [HabitRPG/habitica#2247]
I checked the "automatic allocation box" and I now got the third time in a row 1 point to strength, although 7 of my 8 daylies are mental ones. 

Shouldn´t my character get a point to int attribute?

**Comment by lefnire** [comment]
@SabreCat has fixed this on a PR which I'll be merging either today or
tomorrow, stay tuned

**Comment by eineg** [comment]
Thank you! 

Will I get those strength points back to allocate it myself after that or will this points be automaticly allocated to the right attributes (regarding to my tasks) after the fixing?

**Comment by eineg** [comment]
In my opinion the perfekt solution would be if all the points which are not allocated yet (which I got before I could check the box to automaticly allocate) were automaticly distributed to the tasks I did most at this specific former level. Don´t know if this is possible.

**Comment by SabreCat** [comment]
@eineg: To your first question, the fix won't address any points already assigned, unfortunately. If you use the Change Class button, you can get all your points back. Since your points were misallocated due to auto-allocate not working as you expected, post your user ID (from Settings > API) here and we can give you some Gems to buy that class change with.

To the second question: adding a backfill button for distributing banked points is on my to-do list, but won't be implemented until a little while after the initial fix @lefnire mentioned above.

**Comment by eineg** [comment]
Hi Sabre Cat,

thank you very much for your support!

Unfortunately i still get wrongly automatically points to strength attribute :-( (despite the new choices system)

My user ID is:dbf2fb40-890c-4eda-863c-922b9f8ed6e4
Thanks for the gems in this regard!

**Comment by eineg** [comment]
@SabreCat 

Hi SabreCat,

for your information: It worked 2 times in the meantime when i got int points, but the last 2 levels i unfortunately again got automatically strength points (although i alomost exclusively did mental tasks). 

I wonder if you can tell me when the automatically distribution of the attribute points will work, so i am gonna change the choices to manually distribution until then.

Furthermore i would be very thankful if you send me the above offered gems to refund my attribute points.

Thank you very much in advance.

eineg

**Comment by SabreCat** [comment]
@eineg Gems added. I'll try to look into the problem today.

My hunch at the moment is that maybe it's scoring Reward purchases as Strength training, which is an issue that crops up now and again (@lefnire was too clever by half, using "task value" to mean both the price of a Reward and the "redness" of actual tasks).

**Comment by SabreCat** [comment]
@eineg: I found the problem. What's happening is that when your To-Dos get redder, they "de-train" the associated attributes. So if you have lots of Mental, Social, and Other To-Dos in your list, and don't check them off, they'll tend to drag those attributes down and cause Strength to pull ahead by default.

I've written a fix, so that now only missed Dailies de-train attributes. Should be deployed this week sometime.

**Comment by eineg** [comment]
@SabreCat 

AH OKAY, that sounds reasonable! I really have a lot of red mental to dos!

Nice to know that red daylies also influence the stats! Good idea!

Thank you for the gems, for the fix and the great game!

**Comment by eineg** [comment]
@SabreCat 

Now i get "per" although just 1 of my 12 daylies is "other"... :-(
