### ISSUE TITLE
Lost HP For Ending Challenge

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2248]
I ended a private challenge that I was in and awarded the winner.... only to immediately get a notification that I had lost .9 HP. The challenge was for a private guild, and as far as I could tell, all the tasks had been completed by both of the participants.

**Comment by lefnire** [comment]
Is the hp loss the only issue that occured? If so, that's normal. What happens is Habit consumes updates from the server for any action on your account. Eg, if you change your profile name, and your Chrome extension docked you points since the last time you did anything, you'll get an HP loss notification.

**Comment by lemoness** [comment]
Just HP loss... but why does that happen? It's pretty confusing.

**Comment by lefnire** [comment]
Here's how it works. Firstly, it's always been this way, even since Derby. Only now it gets a lag where Derby was instant, which is sometimes what confuses people. I'm explaining thoroughly here since people ask about it all the time (even in Derby - "I just lost hp and didn't do anything?" "yes you did, you were on Reddit") - and maybe people can start linking here or we can copy this into the Wiki or something.

When things hit the API, they interact with your user's stats. Chrome extension, mobile app, Anki, Pomodoro, etc. Up-scores give you Exp, down-scores dock you HP. When you interact on the website, it will send up the operation, and it will _send down_ any changes to your stats since the last time you talked to the server. 

So, example. This is sequenced in time:
1. (website) You check off a To-Do
2. (chrome-extension) You go to Reddit, and lose HP from the Chrome extension.
3. (website) You change your profile name. You'll now get a notification from step 2 that you lost HP.

It happens with any interaction that causes a User object sync. Finishing a challenge syncs your user ("breaking" the task-challenge linkages). Chatting in group chat does _not_ sync your user. It was less noticeable with Derby since the out-of-sync actions synced immediately to the website. IE, if you `+`d a habit on mobile, you'd immediately see that `+10 exp` on the website. Well now, you won't see that until you _do_ something on the website, and you'll see it along side whatever you just did.

This may be confusing, but the way it works is _good_. It's similar to Gmail. Why when you send an email might you suddenly see 3 new inbox messages? Two of them are from 5 minutes ago, why didn't I immediately get them 5 minutes ago? Well Gmail has a slow long-poll, it's not using a real-time channel (eg, socket.io) to sync every operation immediately as they occur. That's an expensive addition to the tech stack (computationally & scalability) for a very small gain. So it takes the opportunity to fetch changes at the same time as posting them. So while it may seem confusing to receive 3 emails "as a result of sending one", it's more efficient, and just takes some understanding of the process.

For you, what I believe triggered it was the boss battle. Someone probably missed a day, boss hurt you (hitting the API), queued the HP loss on the server, got sent down with your next action.

**Comment by lefnire** [comment]
[Wiki'd](http://habitrpg.wikia.com/wiki/FAQ#My_stats_changed_from_an_unrelated_action)

**Comment by lemoness** [comment]
Awesome, thorough explanation. Thanks!
