### ISSUE TITLE
To Dos missing Physical, Emotional, Social options under Advanced Options

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2264]
I added a new To Do tonight and noticed that while I can still choose the task's difficulty, I can no longer choose its category (aka Physical, Emotional, Social, Other). It was there yesterday and I haven't knowingly changed anything on my end. has this feature been removed for To Dos?

User name: Anysia
OS: iOS 7
Browser: Safari

**Comment by lefnire** [comment]
I hid them from users who aren't using "Automatic Allocation based on Task Activity" ([screenshot](http://gyazo.com/acc10a46a200df072adb3dbdeedfd4e5)) since the option won't do anything unless that preference is selected, and I didn't want to mislead users into thinking it's doing something. Head to https://habitrpg.com/#/options/profile/stats , set to Automatic Allocation > Task Activity, and the options will show again

**Comment by lefnire** [comment]
I just ran a migration for users who have auto selected, but no allocation-mode selected, to use 'taskbased' by default

``` javacript
db.users.update(
  {'preferences.automaticAllocation':true,'preferences.allocationMode':null},
  {$set:{'preferences.allocationMode':'taskbased'}},
  {multi:1}
)
```

so any user who previously selected autoAllocate should have the options

**Comment by ghost** [comment]
Thank you. That makes more sense as a default.
