### ISSUE TITLE
setting automaticAllocation not setting allocationMode to a default

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2277]
I didn't think this would be an issue, but looking at the database  seems some users are checking `preferences.automaticAllocation` but then not subsequently selecting a `preferences.allocationMode`. This is fine for new registrations since Mongoose will pick up the default value on newly-created records, but doesn't backfill for existing records. Probably best solution is to set it automatically to '`flat'` or `'taskbased'` (IMO, taskbased) when they click auto-allocate

**Comment by SabreCat** [comment]
Ah! Whoops. The way the radio buttons behave, it looked like it _was_ automatically selecting `flat`, but I must not have tested that. Will fix, thanks.

**Comment by lefnire** [comment]
oh! maybe something else is going awry then actually

**Comment by SabreCat** [comment]
Could it be that those are users who previously had automatic allocation checked, before it had modes? If they don't visit the settings page, or if just visiting it without changing anything doesn't add the mode...

**Comment by lefnire** [comment]
Well, I ran [this migration](https://github.com/HabitRPG/habitrpg/issues/2264#issuecomment-31630059) for that case, after which the following returned 0 (previously 2k or some such):

``` javascript
db.users.count({'preferences.automaticAllocation':true,'preferences.allocationMode':null})
```

However, when running the same count today just out of curiosity, back up to ~10. If your checkbox is auto-radio-ing flat, it could _possibly_ be some 3rd party-ists API-ing. I haven't dove in to see what could be going awry yet, just saw the db results and thought I'd note-to-sabe/self for later

**Comment by SabreCat** [comment]
It can't hurt for me to add an explicit mode set upon click of the main checkbox, in any case. I'll push that fix, you can re-run the migration, and you can monitor your query over the next few days to see if it's resolved.

I've got a couple of other little fixes to do tonight after I get something to eat. My avatar, for instance, looks like he's not equipping anything because (a) you need to unlock the Market to get at the Equipment tab, and I haven't leveled up that far post-Rebirth yet, and (b) Rebirth doesn't turn off Costume mode xD
