### ISSUE TITLE
Challenge tags got wackified

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2316]
Recently, the list of tags stopped showing up neatly on one line, and now appear in this awkward arrangement:

![screenclip](https://f.cloud.github.com/assets/4501321/1874533/829f09e4-78d3-11e3-8d06-8aa810788c90.png)

Possibly due to ec236f3?

**Comment by SabreCat** [comment]
Happens both on Chrome and Firefox. Moreover, there's a tiny vertical scrollbar on the right-hand side xD

**Comment by wc8** [comment]
Maybe intentional design?

**Comment by lefnire** [comment]
not intentional, indeed came with the markdown+emoji support. But minor

**Comment by wc8** [comment]
I actually like it. I'm not sure if I would choose it, but it has some advantages.

Speaking of markdown+emoji support, the challenge tag length limit is rejecting emoji which would be one character as an emoji. For example, `:european_castle:` is one letter too long to enter, which is a pity, because the result, :european_castle: is shorter than spelling out castle.
