### ISSUE TITLE
Rogue Ski-sassin equipment doesn't give Class Equip Bonus

### ISSUE THREAD

**Issue by moskupols** [HabitRPG/habitica#2322]
Currently I'm wearing Ski-sassin parka and Ski-sassin helm with ordinary rogue weapons, but I don't receive any Class Equip Bonus for PER. Is that OK?

**Comment by AgroDesu** [comment]
I'd like to add on that I'm wearing both of the Ski-Sassin weapons (with normal rogue armor) and they're not giving the class equip bonus either. So it's definitely affecting the whole set.

**Comment by lefnire** [comment]
known issue, due to the nature of the item storage it's difficult to fix this. They're currently considered "specials", which are separately handled than class gear. I'm looking at a fix, but got some other hot-button issues to fix first

**Comment by lefnire** [comment]
fwiw, [this is the diff](https://gist.github.com/lefnire/8319357) that would fix this. However, the bug it introduces is they don't show now in the item store (rewards column)

**Comment by GargamelCZ** [comment]
How about fix on the other side - all "specials" will be counted/calculated as class equipment for any class?

**Comment by SabreCat** [comment]
My vote is to leave it as is. The main appeal of the winter event items (and likely other limited-term equipment for future events) is in their looks and their limited availability. That they have modest stats without a class bonus is fine, allowing the baseline class gear to retain its value.

**Comment by SabreCat** [comment]
Another reason to keep it as is: this equipment is already _really good_. It's equivalent to a penultimate gear piece used cross-class, or a 3rd/4th tier piece used in-class, and you don't need to buy any previous tiers to get it. If you use it after switching classes (likely a very common scenario), you've saved 160 Gold vs. buying the equivalent in the ordinary class progression.

It doesn't need any buffs.

**Comment by Nurylon** [comment]
<コ:彡  I thought that the armour not having buffs was intentional. As Sabre said, the stats are equivilant to the second-to-best armour/weapon of each type, and the entire set costs 310 gold, which is significantily less than the normal set does... if it doesn't give the bonus, it's actually (for same class) only as good as the third armor upgrade (or fourth weapon upgrade) which is reasonable but still cheaper, which still gives the incentive to save up for the main armor instead of just giving a complete shortcut to getting almost-top-tier gear.... while the exclusive armor is for its appearance, collector's status and if you're new, giving a boost for less coin.
Edits:: Oh hey hi I basically said exactily the same thing you said but rephrased sorry didn't realize that till later OTL___

**Comment by dwhitlow** [comment]
It shouldn't be left as is. It costs as much as a penultimate gear piece but actually gives the stats of a piece one tier lower than it when you factor in the class equip bonus. If players spent their gold on the regular tier items instead, they wouldn't be far off from the stat gains from the special items, and they'd also be that much closer to being able to buy their ultimate gear.

**Comment by SabreCat** [comment]
I don't think the principal value of these items is in the stats, so it doesn't bother me that they're weaker than their equivalents of similar cost.

Might be time for a poll on the topic, in any case.

**Comment by SabreCat** [comment]
Or heck, we could get rid of Class Equip Bonus altogether. That was a compromise thing from me being grumpy about classes swapping gear around for stat optimization, and since then I've come around to the notion it's not that big a deal :P

**Comment by lefnire** [comment]
I'm not opposed to that. This might be one for the polls
