### ISSUE TITLE
Checklist multiplier on todos works whether completed or not

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2327]
This was intentional, but it should be discussed. This makes the reward generated from a ToDo and Daily with a checklist (uncompleted) different.
- Daily reward is multiplied by completed checklist items
- ToDo reward is multiplied by all checklist items, regardless of completion.

Is this too confusing?

**Comment by lefnire** [comment]
Well, as it turns out Daily rewards aren't multiplied as such. Currently, daily _damage_ is simply reduced by the amount of CLIs checked. The CLI bit is skipped if the daily is completed (TMK). So they're even more inconsistent than ^

I think actually, we'd like to make dailies _more like todos_:
- Checked CLIs reduce damage. √ so far for Dailies, not implemented yet for To-Dos since over-due damage isn't yet implemented, but we'd like for CLIs to act like Dailies for To-Dos when over-due damage is implemented
- Checking a To-Do or Daily completely off is a short-cut for checking all CLIs, then clicking complete. 

Does this make sense? So basically, both To-Dos and Dailies are missing a piece that the other has, and we actually want to add to them so they both have all the pieces

**Comment by lefnire** [comment]
(overdue damage meaning, if your To-Do is past its due date, it starts hurting you like a Daily each day)

**Comment by wc8** [comment]
#2405 related.
As I said there, I'd rather not have the system check anything off for me, e.g. having to-do/daily be a short-cut for all CLIs completed. Perhaps this could be a user option?
