### ISSUE TITLE
"Not allowed" cursor on Add field is confusing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2340]
I've answered this call for help in the Tavern a few times now:

"I can't add any tasks! When I go to click the plus sign, I get a little red circle and clicking it doesn't do anything!" (or similar)

It seems it's not obvious why a user can't just click the button to add a new task--it's right next to a label "New To-Do" etc., and the only feedback is the cursor change and the fact that clicking the plus doesn't work. It tells the user that they can't do that, but not why, so it looks like a catastrophic bug is afoot. Folks have asked if the server's frozen, if there's some update going on that tasks can't be added right now...

Possibilities:
1. Provide a popover or similar feedback if they click the + erroneously, asking the user to add a title in the New _foo_ field first.
2. Make clicking the + without a title work. Have it create a new task, in edit mode, with the focus in the title field. (If necessary, it could have a default name like "New _foo_", and the default start off highlighted so they can immediately type over it.) If then they navigate away without adding a title, they'll get the existing "please add a title" alert.
3. Don't even provide the + button until there's something in the title field. That way it's immediately intuitive that "New" is what needs to be clicked first.

Option 1 there is easier and sufficient, 2 is maybe trickier but superior. EDIT: Added an option 3 which is sort of slantwise to the others, maybe almost as good as 2.

**Comment by wc8** [comment]
I didn't realize what was being described by one affected user who reported _deleting his tasks in an attempt to resolve it._ Since he thought his account was corrupted, and only had a few tasks, I mentioned _reset_ as a last resort to fix his data. Poor fellow. I'm glad you figured out what was going on and helped him out, but this **definitely** needs improvement.

**Comment by Nurylon** [comment]
<コ:彡 This was something that confused me for a few minutes when I was making my very first tasks after sign up before I finally figured out it; I was trying to press the +sign and from there get an interface to make a task (so solution 2)
I had just finished deleting the 'default tasks' in dailies, and thought it was glitching because I had no dailies and wasn't going to let me make new ones >: Only took a few minutes to figure out what was wrong, but I'd really thought I'd completeily screwed up my account's functionality, aha.

**Comment by wc8** [comment]
I, too, favor option 2. 
Ideally, still continue adopting the current tag selection when opening in the edit mode, and I'd probably use the plus button as a shortcut whenever I want special settings, like due for Tuesday.

**Comment by Alys** [comment]
Fixed earlier this year. The + button shows a hover message when you haven't typed any text.
