### ISSUE TITLE
Split up "Stats & Achievements" to "Stats" and "Achievements" (or similar)

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2373]
The current layout of the "Stats & Achievements" page gets ungainly once the user has Classes unlocked. The left column is quite long compared to the center column, and the "Pets" information is placed rather arbitrarily. The right column, in turn, can look tiny and wasteful of space if the user has no achievements, or even longer than the left column if they're glittering with badges.

Here are some thoughts on how to make this look better:
- Split information about the RPG "character" from information about the player or user. Put the current Equipment, Attributes, and Character Build sections on one tab (I'd call this "Character"), and Pets and Achievements on another (maybe just "Achievements").
- Achievements themselves could use an overhaul. Rather than a table or list, make it into a grid of badges--something akin to the Pets and Mounts grids. Attainable but unachieved badges could appear in gray or black, with their name and maybe a hint on mouseover. (The number of pets found out of 90, for instance, as a progress bar mouseover for the Beastmaster badge.) Achieved badges would get the full gold look, with complete description on mouseover.
##

**Comment by breadstrings** [comment]
I've just recently thought of having only the badge icons visible without their descriptions, exactly like the grid you suggested. XD Seems like I'm almost a year late, haha. I believe the title of the badge should also only be seen on roll-over. Is a description of how to get it necessary if we add clues first?

**Comment by SabreCat** [comment]
Badge title only on mouseover would be quite elegant! Not sure what you mean by your last question, can you elaborate?

**Comment by breadstrings** [comment]
@SabreCat - Of course. :) I meant, would we need a description of how the badge was obtained? For example, with the Beast Master Badge it says: "Has found all 90 pets (insanely difficult, congratulate this user!)" which based on your second point would also be visible on mouseover. However, I thought it would be cleaner if only the title of the badge (just "Beastmaster") is visible on mouseover once the badge is achieved. When the badge is grey, we could simply give a hint of how it's completed.

**Comment by lemoness** [comment]
I think I'd keep the full text on mouseover, because some are specific
(especially event-based ones).

**Comment by Alys** [comment]
I'm going to advertise this in Aspiring Coders, assuming it's still desirable - @lemoness @AnitaYCheng ?

I think this should be done in two stages. First, create a separate Stats page and Achievements page by splitting the current page as described above, but with the Achievements page looking very much like the current Achievements column. 

Then once that's live, we can work on improving the Achievements page, which is likely to take more time because of back-and-forth about how it should look. When we're up to this stage, we should look at https://github.com/HabitRPG/habitrpg/issues/2893 "Achievement List Renovation"

**Comment by Alys** [comment]
When we're up to the stage of improving the Achievements page, we should look at https://github.com/HabitRPG/habitrpg/issues/2893 "Achievement List Renovation"

**Comment by lemoness** [comment]
I would like to see this, personally!

**Comment by Alys** [comment]
I've mentioned this in Aspiring Coders.

To anyone who wants to work on this: comment here to claim it, and also to ask any questions you might have. I'd like to see the two new pages go live before we start work on improving the appearance of the Achievements page.

**Comment by AnitaYCheng** [comment]
Having a separate achievement page just for badges, based on the pet and mount pages, would be awesome! I've always felt that they weren't highlighted enough, especially considering so many people work hard to get their badges.

**Comment by khipkin** [comment]
I would like to work on this!  I really like the idea of a grid for achievements.

**Comment by Alys** [comment]
@khipkin Great! Thank you!

**Comment by Alys** [comment]
@khipkin By the way, have a look at https://github.com/HabitRPG/habitrpg/issues/6933 "User profile modal looks messy with complete lists of challenges won and quests completed - add counters and show/hide buttons?"  You absolutely do not have to work on that one as well, and in fact it's probably best to handle it separately after this issue is finished, but I wanted to draw your attention to it in case it gives you any ideas.

**Comment by khipkin** [comment]
Okay, so here's my plan, pulling from the discussion above.

_edit: moved to PR #7791_

**Comment by khipkin** [comment]
@Alys I'm not sure where the "Enable Class System" button should end up.

Right now, if the user has opted out of the class system, the button just randomly sits on top of the Achievements column:
![image](https://cloud.githubusercontent.com/assets/5641207/14062153/279eea7c-f36b-11e5-981a-cfa18f55ba11.png)

It would be weird if the button was potentially in a column all by itself on the new stats page, and possibly even weirder if it was just thrown into the new achievements page.  It doesn't even seem to fit in "Stats and Achievements" where it is now.

**Comment by crookedneighbor** [comment]
It's related to stats, since you allocate your bonus stat points.

**Comment by khipkin** [comment]
Hmm okay.  Maybe it could go near the "Attributes" part of the stats page?  Something like this:

![image](https://cloud.githubusercontent.com/assets/5641207/14062335/a01808d4-f371-11e5-817f-d13faaba787c.png)

**Comment by Alys** [comment]
I think "Enable Class System" could go at the top of the stats page. It doesn't take up much space and so won't be too annoying for those who never want to enable it. We get questions about how to reenable classes, so keeping the button in a very obvious position would be helpful.

I'm wondering if keeping "Stats" as the page name would be better than using "Character". "Character" seems vague to me and doesn't necessarily imply statistics, where as "Stats" definitely does. Does "Character" come from RPG character sheets? If so, it might be one of those things that is instantly recognisable to gamers but not necessarily to other players. But maybe I feel like this just because I'm used to "Stats". Other opinions would be good!

I like the idea of progress bars for the *master achievements!

**Comment by khipkin** [comment]
I think the most intuitive place for the "Enable Class System" button is on the settings page!

**Comment by Alys** [comment]
@khipkin [I respectfully disagree](https://github.com/HabitRPG/habitrpg/pull/3965) ;) 

It used to be on the settings page but we received a lot of questions about how you could opt back in to the class system. The questions decreased when we moved it to the Stats page. I think it's helpful for users to be able to opt in to the class system from the same page where they opted out.

**Comment by khipkin** [comment]
@Alys Well, you can't argue with data!  Heh heh. :)

I'll leave the button where it is for now, in the left-most column, but it'll be all alone without the achievements.  I'll post screenshots.

**Comment by Alys** [comment]
> I'll leave the button where it is for now, in the left-most column, but it'll be all alone without the achievements

Did you mean to type **right**-most column? 

Putting it at the top of the **left**-most column is what I have in mind, and so it won't look alone there. In fact I should have put it there to begin with. I think I put it in the right-most column because that column was very short at the time. :-/

**Comment by khipkin** [comment]
@Alys Yeah I meant right-most. :disappointed: But changed my mind!  I agree that the left-most column, aka the stats part of the division, is better!

---

Surgery was a success!  The pages are now separate:

**Achievements page**
![image](https://cloud.githubusercontent.com/assets/5641207/14063887/5245bf30-f3b6-11e5-91a6-69b26b83b45f.png)

**Stats page (w/ classes disabled)**
![image](https://cloud.githubusercontent.com/assets/5641207/14063888/7bcb5766-f3b6-11e5-9e97-0b846846cce8.png)

**Stats page (w/ classes enabled)**
![image](https://cloud.githubusercontent.com/assets/5641207/14063895/ba3fad58-f3b6-11e5-948d-f5c1e5fe9ef8.png)

**Comment by Alys** [comment]
It's looking pretty good!

**Comment by khipkin** [comment]
For the next step, I think the stats page should be shuffled around a bit so that the columns are of a more similar length and there's less wasted space on the right side, similar to how full the page was with the achievements column on the right.

Here's my vision:

First Column: (misc stats)
- Avatar Stats
- Equipment
- Pets
- Mounts

Second Column: (Class-influenced stats)
- _(if applicable)_ "Enable Class System" button
- Attributes

_(if applicable)_ Third Column: (Character Build)
- Character Build

**Comment by Alys** [comment]
:+1:

**Comment by khipkin** [comment]
Maybe it would look better if the Character Build thing was in the middle?

---

**Stats page (w/ classes disabled)**
![image](https://cloud.githubusercontent.com/assets/5641207/14063997/472a5416-f3bc-11e5-98c0-cdccb4c954da.png)

**Stats page (w/ classes enabled)**
![image](https://cloud.githubusercontent.com/assets/5641207/14064006/adcc11a0-f3bc-11e5-9841-4100f0984ad4.png)

**Comment by Alys** [comment]
I think having Attributes in the middle works because then the first two columns are things you look at for reference, and you only look at the third column when you want to change something. But that's just my current opinion and I'm not strongly bonded to it.

**Comment by khipkin** [comment]
My classes end in the next few weeks, and then I will start working on this again!  Not looking forward to merge conflicts. :stuck_out_tongue_closed_eyes:

**Comment by khipkin** [comment]
@Alys Done done done and ready for review (finally)!
