### ISSUE TITLE
Task won't delete after leaving a challenge

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2378]
I left a challenge, but the tasks didn't delete. I tried to re-join the challenge and then to leave again, but it didn't work.

**Comment by colegleason** [comment]
When you leave the challenge, are you choosing 'Remove All'? Could you also post your UUID?

**Comment by ghost** [comment]
Yes, I did choose "remove all". Also, I just noticed one task moved from Dailies to Habits.
UID: c33b5bf4-f1cd-4488-861c-f9a971f2d635

**Comment by ksoltys** [comment]
Hi, I seem to be having the same problem. I was setting up a challenge for my party for the first time, and somehow managed to produce two copies of exactly the same challenge. Then I left and eventually deleted one of them, stupidly clicking "do not delete tasks". Now it seems I am stuck with them forever, because they don't have delete buttons. Also, it's confusing not only for me, having 4 duplicate tasks on my list, but also for your system - when I click to score one of the "correct" tasks, hailing from the original copy of the challenge, I get this message:
<!DOCTYPE html>
    <html>
    <head>
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

followed by an Application Error 503 message. The progress seems to be getting assigned to the other copy of the task. My user ID is 10963edb-552b-47f9-8a37-1d051139e84c

I would be really grateful if you could fix that, and by the way, thank you for your great work, I really love HabitRPG and it already helped me change some of my habits.

**Comment by Yughurt** [comment]
Secondary issue is that the "tag filter" for the challenges doesn't disappear after you remove the challenge.

**Comment by Alys** [comment]
This problem is also described in https://github.com/HabitRPG/habitrpg/issues/2763 so I'm closing this issue. 

Note that the tag for the challenges is not meant to be deleted because the user might still be using it (e.g., if they created tasks for themself that are related to the challenge).
