### ISSUE TITLE
Party member died during quest and was not booted from participating

### ISSUE THREAD

**Issue by TheOfficePicnic** [HabitRPG/habitica#2407]
The explanatory text beneath the Trapper Santa quest says that if you die during a quest you're booted out. One of my teammates died during the quest yesterday, did damage to TS on cron, and is still active in the quest as of today. This is either a bug or the text does not agree with the intended behavior.

**Comment by colegleason** [comment]
I also experienced this, actually.

**Comment by lefnire** [comment]
It's to-be-implemented, I have it half-progress on my localhost. I'll push in coming weeks

**Comment by Alys** [comment]
I'm closing this to clean up the issue queue and because I'm pretty sure it's been decided that being booted from a quest on death would be a bad thing (at least until Hardcode mode is implemented, if ever). See Lemoness's comments in https://plus.google.com/108645589277926899961/posts/2zJfQMZpeyZ (staff and contributor private G+ group). Feel free to reopen if I'm wrong. :)
