### ISSUE TITLE
Balance suggestion: Rework the way Pickpocket and Burst of Flames interact with streaks/blues

### ISSUE THREAD

**Issue by TheOfficePicnic** [HabitRPG/habitica#2408]
The range of possible benefits from Pickpocket and Burst of Flames is absolutely massive, based on the fact that they seem to grant exponential benefits when cast on tasks with high streaks or those that are very blue.

I have used each spell on standard yellows and gotten roughly 8 Gold or XP. When used on a blue with a streak of 50+, that benefit has been as high as 85 or so. 

This presents three key issues:
1. A benefit range of 10x is far too extreme. It presents only one viable usage of the spell (the way that gives you the huge benefit), or else you're left feeling like you ripped yourself off.
2. The biggest benefits are given when spells are cast on the habits that have already proven to be the least challenging to you. If you get good at, say, flossing, and you're doing it every day thanks to Habit, you have a free 80 GP or XP waiting for you each day. That's just too much for something you're not having any trouble with in the first place. What's more, once you've built up a really deep blue habit, it would take a LOT of consistent failure for it to no longer be deep blue, so you have no real risk of losing access to all of this excessive reward.
3. Issues 1 and 2 are compounded by the fact that these spells only cost 10 MP and offer arguably the biggest benefit-to-MP ratio in the whole game when used in this way. Since you get 10 MP on cron, you can do this every single day without fail. 

Granted, a user can choose not to take advantage of this, but that shouldn't be seen as the solution when considering balance issues.

**Comment by lefnire** [comment]
I definitely see an issue here, but I probably won't be jumping in to fix this personally for a few months (just due to backlog of criticals). If anyone wants to get started on this, the code is under [habitrpg-shared/content.coffee#api.spells](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L248), and simulations to test the output are [here](https://github.com/HabitRPG/habitrpg-shared/blob/develop/tests/simulations/passive_active_attrs.coffee)

**Comment by SabreCat** [comment]
I've been giving this some thought, too--been playing a Rogue and spamming Pickpocket to try to build up the Gold for all the winter gear. Which is great for the completionist in me, but has revealed the game balance issue all too clearly. And I'm playing a Reborn Rogue who only has ~40 PER!

The swing of output needs to be addressed, but the "spammability" of them is a big part of it too. You can keep using Pickpocket/Burst of Flames on the same solid Daily or Habit, over and over. What if those tasks became "tapped" or "exhausted" by having a cash-out spell cast on them? Subsequent castings would either fail, or give only a tiny fraction of their initial output. The exhausted status could remain (1) indefinitely; (2) until a special condition is met, such as a week of time passing, or a certain amount of other tasks scored naturally; (3) until the user purchases and uses a Gem-based spell item to rejuvenate the task.

**Comment by lorian** [comment]
I think having them only be usable once per daily per day would definitely improve things; it would grant an advantage for having multiple long-streak dailies, instead of just one you spam indefinitely. Having the task be "exhausted' for longer than a day or two, however, seems unnecessarily punitive, and an annoying thing to have to keep track of.

Also, I'd like to speak out in favor of benefits for large streaks. There's a common sentiment that dailies with long streaks are easy and shouldn't be worth much, which really frustrates me, because I am extremely consistent with my dailies, and thus they always have long streaks. The fact that I have read a journal article every day for 39 days doesn't mean scientific papers are easy to read; it means I'm awesome! So I actually like how BoF and Pickpocket reward those of us who are consistent; it feels like the rest of the game rewards procrastinators who have lots of reds all the time.

**Comment by SabreCat** [comment]
Having task exhaustion only last until next cron makes some sense. But in most cases the limiting factor is cron already--you get back your 10 Mana, you burn it on Burst of Flames/Pickpocket on the same daily, you move on with your day.

**Comment by lorian** [comment]
That may be true; I tend to get most of my mana from to-dos, so I can cast it a lot more than once a day, but most people seem to do a lot fewer to-dos. If exhaustion lasts more than a day, though, there will have to be some sort of visual indication so you know when your task has refreshed.

**Comment by SabreCat** [comment]
Yeah, that crossed my mind. Trick there is that we have a _lot_ of icons stacked up on tasks already, so adding another glyph would require careful consideration.

It's just one possible solution, in any case. Rebalancing mana cost and output may be easier and just as effective.

**Comment by deilann** [comment]
Discussion going on here: https://github.com/HabitRPG/habitrpg-shared/pull/125#issuecomment-34152583
