### ISSUE TITLE
Ethereal Surge unexpected behavior

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#2410]
I noticed this happening at least twice. Example:

1) I have 35 mana and cast Ethereal Surge. I lose only 25 mana, which I assume is the result of the spell also working on me.
2) When I do anything else after that (like complete a daily or to-do, edit a task), I lose additional 5 mana (so my real cost gets paid).
3) If the "anything else" I do happens to be casting the Burst of Flames (I still have 10 mana after losing 25 from 35), I also instantly lose that extra 5 mana, so I end up with -5 mana.

There is one more mage in my party (not sure if that's important).

**Comment by SabreCat** [comment]
Was about to write this up myself, glad I searched. Can you tell if your party members are getting the correct amount of Mana, or is that getting rolled back too?

**Comment by mczuchnowski** [comment]
No idea. At least none of them reported such an event to me.

**Comment by MrMakara** [comment]
Same thing happened to me, party members get the right amount of MP but I lose what I would have gained from the spell

**Comment by rcichy** [comment]
I also experienced this. It's occurring if you are in a party.

I recreated this issue on my local instance: https://www.youtube.com/watch?v=tid3n9JJOP0

**Comment by deilann** [comment]
You are supposed to lose what you have gained with the spell, otherwise, at high enough INT, you would gain what you would lose, meaning free MP. It is expected behavior -- what's unexpected is _when_ you see that you lose it.

**Comment by brightbold** [comment]
This is definitely confusing behavior. I just cast it several times and only lost 20MP each time; because it was such a nice round number I thought it was accidentally mis-coded and actually only cost 20 instead of 30. (If I'd been at a different level and it had been -19 or -23 I probably would have figured out that the difference was the benefit of the spell.) So I almost cast it another time, thinking I was getting Ethereal Surge: Now On Sale!, which definitely would have left me with negative mana once the additional debt was paid.

**Comment by Alys** [comment]
This behaviour changed earlier this year (https://github.com/HabitRPG/habitrpg/pull/4919). You still get two separate notifications for the MP you spend when you cast the skill, but they appear at the same time, which makes the total cost a bit clearer. See also https://github.com/HabitRPG/habitrpg/issues/5228
