### ISSUE TITLE
Username not registered

### ISSUE THREAD

**Issue by 9schahrer** [HabitRPG/habitica#244]
I've re-registered 3 times now because every time I end up with "username not registered" when I try to log in. I've refreshed, restarted the browser and computer, and even cleared all data from other browsers/devices I have logged in with with no results. Also, when I was logged in I checked a daily and it emptied my exp displaying NaN. I like the concept, but have been plagued by bugs.

**Comment by lefnire** [comment]
I'm so sorry @9schahrer :( I guess the only thing I can say is check back after the kickstarter, after which (luck be with us) I'll be able to hire developers. It's pretty "proof of concept" quality at present, and I'm only able to work on it nights and weekends. I hope things will start looking up soon, and we can really nail these bugs. 

If you really want to use it now but can't get through the bugs, I'd say run it [on your own computer](https://github.com/lefnire/habitrpg/wiki/Running-Locally) - you won't experience most of the bugs, which are caused by MongoDB load triggering a memory leak and crashing the server - then clients who were on the site before the server crashed lose subsequently-entered data, including occasionally registration data. That stuff won't happen if you're running it locally.

**Comment by 9schahrer** [comment]
Thanks and good luck. Would it be better on windows 7 or 8?

--- On Mon, 1/28/13, Tyler Renelle notifications@github.com wrote:

**Comment by lefnire** [comment]
Probably 7 given what I've been hearing about 8
