### ISSUE TITLE
Change Class user confusion

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2451]
It’s come up again in the tavern, a user expecting they would to change classes for free  because of in-game wording. [Edit: previous in-game wording, in this latest case, so maybe this isn’t so pressing.]

@SabreCat had suggested [class change](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system) become a Market Item, with users getting one for free when they choose a class. @lemoness and I both favored this approach. @lefnire would this be hard to implement?

**Checklist:**
- [ ] implement market item, 
- [ ] give users one free item
- [ ] maybe pixel art parchment with a seal “Class Change"
- [ ] update wiki
- [ ] update tour
##

**Comment by lemoness** [comment]
Just chiming in to say that the Class Change market scroll was indeed the
agreed-upon solution... And to subscribe to this thread from my phone ;)

**Comment by lefnire** [comment]
@wc8 shouldn't be too tough. I think we have a roll-up scroll (kinda "hear ye hear ye" looking) floating around we could use so it doesn't look too similar to our quests.

**Comment by putrocca** [comment]
This is a different issue related to class changing, but it seemed reasonable to put it here.  I noticed that when I change classes, I arrive with a full MP bar.  I think it would be better, if possible, if the MP stayed at the level it was at before you switched.

The reason for this is that it's an accidental hack.  For a subscriber, who can buy gems with gold, switching classes costs 60 gold, so for 60 gold you can switch to the SAME class you just were and have a full MP bar.  This is particularly an issue for Rogues since you can use Pickpocket to turn MP into gold, and a full MP bar gives you much more than 60.  Thus a Rogue can use pickpocket to generate a ton of gold, then switch classes spending only 60, return to Rogue with full MP, generate a ton of gold again, repeat and generate infinite gold.  Presumably most people will be responsible and won't do this, but it might be worth fixing.

**Comment by deilann** [comment]
I'm not that worried about it-- you have a gem cap of 25 gems a month, so
if you want to use this exploit, you'll lose out on other great ways to use
your gems. Also, I remember that I _didn't_ get a full MP bar when
switching classes. What I'm guessing is that your max MP went down, unless
something's changed.

**Comment by lemoness** [comment]
Ah, I think what is happening here is something I've found mildly annoying
- when you change classes, the stats are all at zero, so you reallocate
  them.... And every int point gives you 1 MP. This is frustrating because it
  leads to MP I haven't earned, so I understand you there. Personally, I'd
  prefer that the max mp go up, but the mp itself stay frozen to what you had
  before (excepting the issues that arise from having a lower max int, of
  course.)

Could that be contributing to your issue?

**Comment by deilann** [comment]
But you still won't get a full MP bar that way -- Max MP goes up by 2, but
you only get 1 MP per INT point allocated.

But so, let's say you had points allocated to INT before. Those points
meant that you had a higher max MP. Without those points in INT, the actual
amount of MP you have is higher than your max. (Let's say my max is 72,
thanks to 10 allocated points.) So when I deallocate points, I have 52 max
MP. If I had 52+ MP beforehand, it now looks like I have a full bar, when I
actually have the same amount of MP.

**Comment by librarianmage** [comment]
@lemoness Is this still a requested feature?

**Comment by lemoness** [comment]
I think we've moved on from it, actually. So let's close it for now unless
someone feels very passionately about it.
