### ISSUE TITLE
Rethink STR effects

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2464]
A few users have noted that STR is the only "double-edged sword" attribute: reducing task redness might insulate you from future damage, but it also reduces the reward for getting your act together. It's the only attribute that has an inherent drawback.

This, however, seems to be mostly a philosophical objection, since the effect of even an off-the-charts STR score is unnoticeable when it comes to task threat. I just tested with a 1st-level chump, a 50th-level moderately-equipped Rogue, and a 100th-level Warrior with Golden Sword and Helm and every point invested in STR... and could not tell the difference when clicking a +/- Habit or Daily.

If it has barely any effect, and people don't much like the idea of it having a major effect in this way, maybe we should change it up?

There's not a lot left for STR to do, admittedly. But critical hits are cool, and a well-rounded sort of thing for the "I'll just play the default" users... what if it gave a bit better _chance_ for critical hits (like many people think it currently does), as well as change the _magnitude_ of the crits? The effect should be slow, not more than a tenth of a percentage chance per STR and probably even less than that, but it'd make it all-around desirable and if not immediately noticeable, at least palpable over time.

**Comment by deilann** [comment]
Would be interesting if STR went back to increasing XP gain, but only on "Physical" tasks, while INT did it on "Mental" tasks, but that would require everyone allocate and fiddle with more settings.

What if a high STR caused a chance of different status effects? You could "stun" a task on a chance, like a critical, and it wouldn't be able to hurt you.

STR is used in a lot of games to determine how much you can carry... CON is usually used to determine hit points, but what if you could increase your total HP by putting points in STR? From Wiki: A measure of how physically strong a character is. Strength often controls the maximum weight the character can carry, melee attack and/or damage, and sometimes hit points. Armor and weapons might also have a Strength requirement.

**Comment by JennaMalkin** [comment]
Thank you! Not sure what you mean by 'task threat', @SabreCat ?  

As it is, currently, a high STR works against habit formation.  If the goal is not necessarily the Gold/Silver, but the bright blue colour itself, (because green/blue means 'I'm doing ok, HabitRPG is working'), strength works against habit formation.  

For example, I use a habit to remind me to blog. Before the class system, I would simply say 'oh, my Blog bar's gone yellow again, I should find something to write about' - and that helped me blog more or less frequently enough and consistently - five or so times a month.  While I'd sometimes just spontaneously write a blog post and then hit the blog button on HabitRPG, I would often use the 'warming' feature as a reminder in that way.  With my new STR, my timing's a bit out of whack, and I still need the Yellow to incentivise blogging for me.

**Comment by SabreCat** [comment]
"Threat" is just another way of saying "redness," sorry. How dangerous the task is. I think I internalized it as a word for that, but I don't know that it ever caught on official-like. xD

**Comment by Streakiest** [comment]
Perhaps STR could have more of an effect on red tasks than yellow and blue ones? If you had a maximum red for example, then you completed that task, you should instantly see a colour change, but completing a yellow one wouldn't have as large as an effect. That would make warriors better at recovering, making them a more 'hardy' class. Coming back from the brink is totally a warrior thing to do!

I like the idea of a stun though, or anything else that would help them take on many tasks at once, kind of like 'tanking', or something. The crit chance/magnitude thing is good too, because it would affect the rogues to an extent as well.

**Comment by Caspid** [comment]
The underlying problem is that reds give much more benefit than blues do.  Players should _want_ their tasks to turn blue, but there's no incentive to do so except less damage for missed tasks (often a non-issue).
I wrote about it here: https://github.com/HabitRPG/habitrpg/issues/2639.

**Comment by lorian** [comment]
The redness Str ability is definitely a negative for me, and for anyone who don't take a lot of damage. I feel like Con is obviously the stat for people who would like to be "hardy", and Str needs its own niche. I'd much prefer it replaced with increased crit chance (which was actually what I thought it did, oops). Extra hp isn't terrible, but it feels weird for Str as a stat; strength is about doing damage, not taking it. Doing more and bigger crits seems totally on type, and would make it a nice balanced stat that would increase both xp and gold, over time: that way every stat would have its niche.

**Comment by Waldere** [comment]
I'm so glad to see this conversation! I was starting to regret staying a warrior, but these proposed changes give me hope.

STR is the worst stat in the game. Easily reducing task redness isn't an advantage; it's demotivating. I _want_ the threat of damage! And when I finally get something to blue and that threat subsides, I want it to feel like it was through my effort, not because I pumped up the Easy Mode stat. I would much rather see STR turn into a pure critical hit modifier, as others have suggested.

But keep the increased boss damage! That was a cool, flavorful use of the stat, and definitely Strength's greatest strength. (Sorry, couldn't resist.)

**Comment by SabreCat** [comment]
I'll take this on. Gonna go with stripping out threat reduction, adding +crit chance, and maybe making the +boss damage effect more pronounced.

**Comment by lefnire** [comment]
Fwiw Sabe, I totally agree. Been warr lately and it feels all wrong. God
speed!

**Comment by SabreCat** [comment]
This is live now, I think! Closing.

**Comment by emz83** [comment]
Does this change affect how Brutal Smash works? Because if so, then it's description should be modified.

**Comment by deilann** [comment]
No, Brutal Smash still increases a task's value.
