### ISSUE TITLE
inn not good for illness and other unexpected events

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2493]
The way the inn is set up now, it is very good for planned absences, like vacations. However, because dailies don't reset upon leaving, it is not good for illness. If I have a flareup, I may think everything is fine until halfway through my list. At that point, I have a choice: take the hit for the rest of the day so that upon returning, my dailies aren't half completed, cheat so that I can come back to a fresh list, or deal with having a partially completed dailies list upon return.

If exiting the in reset dailies without damaging the player, it would be far more useful for sudden problems.

**Comment by andrez89** [comment]
I agree. 
I injuried my ankle last week and since then I couldn't excercise, but also after completing the first time other dailies that I could perform, I could not check them (read, study, etc..).

**Comment by octern** [comment]
@andrez89 It sounds like changing the inn wouldn't solve your problem, since IIUC you want to be able to check off some dailies but be protected from others. For that case I think the only reasonable solution is to set the affected dailies to not recur (in the settings for that daily, unmark every day of the week) until you've recovered. For @deilann, I agree, checked dailies should clear at the end of the day even if you're in the inn.

**Comment by brightbold** [comment]
There are two Trello cards suggesting things that might work better: [House of Healers](https://trello.com/c/0KfFF92z/347-inn-full-gp-no-hp-loss-no-xp-gain-xp-gives-level-up-attributes) that would be designed to work better with illnesses - you could still check off any tasks you could complete, but maybe no XP gained or lost so you wouldn't die but nor would you want to stay there forever. And [Tavern tags](https://trello.com/c/Iu8tWUhx/298-rest-inn-tavern-applied-to-select-tags) where you could, say, go on vacation and only have your work tasks frozen, but you still want to floss and make your bed. If you guys haven't voted on those you should check them out.

**Comment by deilann** [comment]
Yes. I am aware of this. I contribute heavily on Trello. You're missing my
point.

The Tavern doesn't reset dailies after you enter it. Let's say you had a
family emergency and had to suddenly ship across state for a day. You go
into the Tavern, but when you come out, all of the dailies you checked off
before having to ship across state remain checked.

In other words, the Tavern is only useful for planned absences, not
emergencies. While I agree that systems for mild illness would be fantastic
or systems that allowed you to have location-based tagging disable tasks,
they still don't solve the problem of emergencies. Emergencies would be
best handled by the Tavern, but can only do so to full potential if coming
back out reset your dailies.

**Comment by brightbold** [comment]
No I know you're very active on Trello - but there are a lot of cards so I didn't necessarily expect you to be familiar with every single one of them! Sorry if that came off as know-it-all - not how I meant it. 

But when we had the original discussion in the Tavern that led to the Sanctuary idea, I was making all the exact same points you made here about why the Tavern doesn't work. (In my opinion, it's not even great for vacations - if I leave on a Thursday evening and check out when I return Sunday morning, my dailies aren't remotely in the state I want them to be.) The sanctuary idea was what came out of that, so I thought it might work for you. 

The tags idea was directed at @andrez89, since it seemed like if he had a tag for physical activity he could disable all those and keep his others active.

**Comment by deilann** [comment]
Nah, I probably don't know all of them, but as a person with severe chronic
illness, those are cards of extreme interest to me.

Sanctuary doesn't work as well for me because often times severe illness
means I lose the capability to be on the computer at all. I'm trying to fix
that by making my computer hands-free and create a setup where I don't have
to get out of bed, but until I've perfected that, there may be periods of
time in which I suddenly cannot check off any dailies what-so-ever after
completing half a day.

Even if that was perfected, there's ER visits to deal with...

I imagine it would be possible to uncheck checked dailies upon checking
out, then reset their stats back to what they were before they were
unchecked. This would reset someone after checking out of the inn without
triggering cron, without them taking damage, and without them having to go
and fix everything.

There's really no logical reason to have the inn not reset your dailies
upon check out, just logistical ones, as far as I can tell.

**Comment by brightbold** [comment]
Personally I like your tavern reset-on-checkout solution better than the sanctuary idea for either an off-the-grid vacation or a debilitating illness. (Sanctuary is preferable if you're able to do some but not all tasks.) Although I don't understand why you couldn't use sanctuary in a situation where you're doing no tasks - I don't see the downside of it unless they implement it so that streaks aren't retained. @wc8 seemed undecided on the streaks issue.

**Comment by deilann** [comment]
Not just streaks, but redness. In my vision of Sanctuary, tasks would still
change color-- it only makes sense. It's a great way to tell if you're
making progress, even if there's no XP gain. Freezing your account entirely
allows you to preserve it the way it was, letting you come back to the way
things were.

I definitely would like Sanctuary for mild illness or an on-the-grid
vacation (although I would even more prefer the tag system allowing me to
completely switch out for a different set of dailies).

**Comment by brightbold** [comment]
Oh good point. I didn't think about redness.

**Comment by deilann** [comment]
Yup. Some of my hospital visits have lasted over a month. It's not uncommon
for them to last a week. Often, my assumption leaving to go to the hospital
is that it will be a quick ER visit, not in patient. Can you imagine coming
back after a month! Those would be some _red_ tasks.

**Comment by deilann** [comment]
logistics: possibly it would be necessary for the game to recognize if
you've had cron in the last 24 hours, so you can't sign in and out of the
inn repeatedly to spam dailies? If coming out of the inn doesn't trigger a
true cron, and instead just refreshes dailies, they wouldn't be able to
spam it for drops, but they could really mess with challenges this way.

**Comment by wc8** [comment]
Hm... would manual day start button address your needs? 
My thought with making check out of the inn = reset dailies is, what if I check in the inn just in case and want to check out before night fall if I get better? Everything I log will be wiped, it'll discourage checking-out.

**Comment by deilann** [comment]
Thta would be another reason to do the 24-hour check.

The way I'd set it up, the system would check to see if cron has run in the
last 24 hours. If it has, nothing would happen upon checkout. This would
solve your situation as well as keep people from using the system to really
screw up challenges.

If cron has not run in he least 24 hours, dailies are reset.

**Comment by deilann** [comment]
That being said, manual day turnover is the one feature I want more than
any other.

But BrightBold has a fair point -- the way the Tavern is set up, it's
really not useful for even vacations, unless you're leaving in the morning.
While manual cron would be a boon to me, many users would want automated
cron and the ability to use the Tavern.

**Comment by brightbold** [comment]
I had also thought of that and was thinking you'd need a cron check. No idea whether that's technically easy or not. But manual day start might be a better and less complicated solution than any of this.

**Comment by kuiperbelter** [comment]
This is my biggest problem as a newbie to HabitRPG. I have a chronic illness and the inn is just not useful to me, because of the lack of reset. 

Behaviour I was expecting: everything greyed out but still checkable. Reset each new day, with no penalty for missed dailies. This would work well for me, as I could still see to check off my meds and stretches, but could skip the housework and exercise. And when I left the inn, my dailies would be freshly reset for the next day.

**Comment by wc8** [comment]
@kuiperbelter this is how I'm handling it, for now: for prolonged illness, I'm activate only medically relevant dailies as my dailies. All others are greyed and I'm out of the inn. This way, I can still check them off. For acute/severe illness, I stay in the inn and track my meds (for example) with alarms.

**Comment by deilann** [comment]
I've been using Stealth instead -- with high PER, it turns into the inn,
basically, but your task list resets.

**Comment by Alys** [comment]
FIXED!
