### ISSUE TITLE
Business Model Discussion

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#25]
[Edit: see [the Wiki](https://github.com/lefnire/habitrpg/wiki/Business-Model) for TL;DR]

I have a question regarding usage of "tokens"...are these going to be your method of making money?  I am a bit concerned about the implementation of this, but am very happy your code is at least open-source.  Is this just kind of a placeholder, though, or is it your profit model?  It seems ads or another model would be a bit wiser if you actually want long-term growth.  Also, I would hope that your overall goal would be to actually motivate people to improve themselves rather than attempting to arcade/gamble us into spending.

Furthermore, I was just playing around with the app this morning, toggling things, breaking things, seeing how everything works by quickly making changes, and I've already spent all my tokens before actually even using the webapp.  :(  I thought there was a reset option in the upper right, but I can't even get to it now as the tokens javascript popup prevents me from using the "login/logout" controls...feeling a bit miffed at the moment and I figured I'd just let you know, as you seem like someone who probably would take feedback into consideration.  This is not a tool I'll be using at all unless this is fixed (which would be a real shame, as it is beautiful), and I'm sure there are plenty of others who feel similarly.

Can my account at least be reset so I can play around properly and test other features?  Also, if you aren't going to change the token structure, you should warn people about it, as in BIG FAT RED LETTERS, haha.

Thanks - if you improve this, I'll keep submitting my feedback for you!

**Comment by lefnire** [comment]
Tokens are indeed my business model. I'm absolutely open to suggestions, including removing tokens completely if people think it's shit - but I actually thought it was a pretty good idea. Here's my reasoning. First off, I have to make money somehow because this project eats a lot of time. Ads would be annoying, but I could do a $1 to disable them kinda thing. The idea of tokens is that it keeps the whole project "in character" - like using tokens at an arcade when you die. It penalizes you in a real way for doing poorly, to _really really_ motivate you to do better. [stickK](http://www.stickk.com/) has the same model. In fact, I use it against myself to help me try harder - the reason I built Habit (true, I get the money back - so it's just the Stripe fee I incur, but busting out my credit card frustrates me to motivation). One thing I batted around if I found a decent alternative business model was to keep tokens around, and the money goes to charity of your choice. I really do think tokens is a pretty good motivator. 

Just for users' info, I totally promise I'm not twisting my mustache in evil glee as people lose and have use tokens to continue :) I mean it to be a real way to motivate you to stop failing, while also providing a way to make some money on the project - 2 birds. 

Anyway, maybe I should start a business-model poll somewhere people could vote, in case users really hate tokens. Side note, I have a [project brewing](http://ocdevel.com/blog/gittip-github-project-royalties) where contributors to this project could make a cut of the money Habit makes - respond here if anyone's interested in that coming to fruition.

Ok, that's that. As far as you not being able to reset because your'e dead, and tokens not being clear enough - bugs & features that need panning, totally not trying to dupe you. I'll put that high up on the list, and I apologize for that. If anyone else has this problem, email me with your userid / username and I'll give you tokens.

**Comment by loldude101** [comment]
I always thought that as the site grew and become more built-up you would make an smartphone app and earn money from selling the paid app. The site and its features would be better viewed through the app. 

I never even knew about token since last week when I clicked the "reset" option to see what it was. I never had my character die since I bought potions and did my best to not lose HP. The game isn't hard enough for people to keep dying, at this point it's at a safe balance of challenge. But it might make sense later in the game as it is becomes harder to level up while HP remains the same number and potions become less effective. If that is your main potential profit module then I consider better structuring user-benefits and making it worth-while to purchase tokens to stay alive because now if people run out of tokens there's nothing stopping them from creating a new account and continuing to improve their habits, since that is what it's all about. A while ago I suggested good ideas to help build upon the "RPG" aspect to keep users more grounded to the game behind the website and not just the habit-improving aspect. 

There's always the potential of if you make something awesome and appealing enough you will be rightfully rewarded. Look at the Chrome extension "Pocket", they raise $40 million this year alone. Obviously it's not fair to compare habitrpg to Pocket but it shows that when an idea is good enough and grows to be popular it will bring in the money you always wanted. 

Regarding what you mentioned about finding contributors, I'm interested in contributing. Email me, you know who I am ;)

**Comment by lefnire** [comment]
death modal bit separated out to #28

**Comment by lefnire** [comment]
@loldude101, [email me](mailto:tylerrenelle@gmail.com) and we'll chat the "gittip royalties" notion offline. You rock for being so patient with this app btw.

**Comment by hookang** [comment]
I went ahead and tested out dying. Realized it took 2 tokens to revive. 

After reading about the reset - button I reset.

So I killed myself again to see if the tokens would also reset back to 8.

No go. I'm at "4 Tokens." 

Completely understand the business model - need money to live idea. (Perhaps a Firestarter thing to raise some initial funds for the project?)

Also +1 to the iphone/android app - unless you already designed this to be mobile responsive. (Which it looks like you did).

If I knew what the consequences of dying was- I wouldn't have killed myself.

I can help write up documentation if you would like some help. 

I suck at coding. I would like to contribute to this project some how though.

I think it has tons of potential.

**Comment by lefnire** [comment]
- not resettings is a bug, I added that to my list - thanks for pointing it out. 
- I'm batting around KickStarter in my head, been brewing for the last few days on whether or not I should do a campaign - what do y'all think?
- the mobile app is indeed responsive, and should work just fine on your mobile browser. but a mobile **app** is definitely coming also (see [habitrpg-mobile](https://github.com/lefnire/habitrpg-mobile))
- perhaps a wiki page on tokens in general will be in order

**Comment by loldude101** [comment]
Before you share it on KickStarter you should have a clear plan drawn out outlining the future of habitrpg. Plus, what are you funding? Are you seeking funding for your grocery expenses so you stay alive and continue fixing habitrpg bugs (just kidding). KickStarters are usually done when I project requires finance to take a huge leap forward, but I personally don't see any "leap" that habitrpg needs to take, I think that this is one of those projects that slowly grows over a long period of time.
You also haven't presented the advantages of a potential app over the mobile site.

**Comment by lefnire** [comment]
What it's funding: the mobile app. Aka, enough money clear my plate of
grocery-funding contracts to work full-steam on HabitRPG mobile.

Benefits of mobile: Offline. Plus, while the mobile website is usable, it's
not a pleasure to use. Habit involves clicking checkboxes every time you do
something in life, which is so much easier if it's in your hand than on a
computer.

**Comment by lefnire** [comment]
Also, my full plan for Habit is completely [outlined here](https://workflowy.com/shared/cd06313a-7c93-ae5f-ae55-e64cae0556e4/). It's not a pretty format, but if it needed cleaning/formatting it's simple enough.

**Comment by jchubber** [comment]
Could there be an enterprise play here? If you can actually help people be healthier, more productive, and more generally awesome people, then I would want to pay for an enterprise account to gamify life for my team members.

**Comment by lefnire** [comment]
Absolutely, I think that's the best way to fund Habit - something of a white-label intranet version with company-specific functionality, licensed.

**Comment by loldude101** [comment]
I concur. This is a great idea with a lot of potential.

**Comment by hookang** [comment]
+1 to enterprise play. I think that's probably the best way to monetize this. You want users to do well with their habits. But still find a way to monetize.

**Comment by lefnire** [comment]
Alright, here is my current leaning: primary source = enterprise / white-label. Remove tokens from death, keep for re-roll and possibly emergency potions or decorative items, etc (Farmville, you brought this upon us).

Mobile... ads? Don't know how I feel charging for it if I'm running the [Kickstarter campaign](http://kck.st/XoA3Yg)

**Comment by hookang** [comment]
Digital Items for the win.

**Comment by lefnire** [comment]
Update: tokens are no longer required for "continue". they'll be relegated to digital items (optional pieces, weapons/armor still purchased with gold) which are yet to be developed, as well as re-roll and emergency potions.

Business model will be digital items and white-label / enterprise. Mobile app will likely be free, still ruminating.

**Comment by lefnire** [comment]
added [a wiki](https://github.com/lefnire/habitrpg/wiki/Business-Model) - will update every time we decide on stuff

**Comment by loldude101** [comment]
If you continue persuing the idea of users being able to connect with friends then please consider the potential of users cheating by gaining unrealistic EXP to appear better than their opponents. This problem is only solved by implementing an automatic moderation system limiting users from unrealistic activity. Otherwise users, especially in an enterprise team will start to cheat to try to rein of others, by going out of their way (in the enterprise case users will launder their gains through pointless "task completions" in front of watchful team admins and/or just going on EXP rampages by repeatedly "completing" tasks) to get on top. Such a regulation system would definitely take away the "magic" and I would never want to see habitrpg be strongly restricted to fit a community bias. 

Regarding the #1 bulletin in the new wiki, I think the enterprise option is a guarantee finance generator with incredible potential to draw not only corporate clients but regular families too. Team managers will quickly jump at the opportunity to increase productivity and organization while doing it in a fun way. I strongly believe habitrpg should be left as it is and work started on a powerful enterprise version offering advanced features such as admin control panel (where members are moderated with task history and the ability to add tasks), fun team ranking, and custom group incentives (easy to determines "employee of the month" with a clear outline of monthly progress). I can see many tech companies subscribing to enterprise subscription with a fee of $2.95/month/per team member (this fee fair for small organizations and large companies who have the money to spend) . I think it goes without saying the habitrpg demographic is mostly made up of geeks with a history of RPG gaming and I think we can find these people in tech-related fields. Employers are ready to sink money into a system where they better organize the professional duties if theirs employees while doing it in a relatable way. I don't think the "big-fish" would jump on this now since the project is young and not very credible but I defiantly see Internet startups using the service to better organize work-flow through a young group. Hip companies such as twitter and, especially, IAC would like the service very much.

**Comment by lefnire** [comment]
@loldude101 - words of wisdom. Thanks for in the input Igor

**Comment by lefnire** [comment]
@loldude101 @hookang y'all have been pretty involved - make sure to track any hours directly contributing to the project (Kickstarter marketing, bug diagnosing, etc.). I want [Gittip Royalties](http://ocdevel.com/blog/gittip-github-project-royalties) to become a reality if this project ever makes money. Hoo has been tracking hours in GDocs, I use Harvest - we'll all consolidate later.

**Comment by horusofoz** [comment]
I believe it would be a better business decision if you develop HabitRPG to a level more polished, robust, bug free and popular before looking at entering the marketplace or devoting development time to enterprise functionality.

I think loldude101's suggestion of an enterprise version with the added features of being able to host on a private server with admin/team leader/individual views and added performance management features is great. Depending on your financial position when you choose to enter the marketplace you could even look at providing hosting for private deployments. 

Still the base product needs to further mature first.

To be able to spend more time on development and stay in the black I suggest;
- Slick mobile app for $1.99.
- Digital items
- Feature bounties
- Open a donations portal
- Made to order merchandise

Also once the bugs in the system are worked out I think resurrection tokens for a dollar is workable. New accounts could start with 3~ tokens, by the end of which users can purchase a token for $1 to keep that character with all existing digital items or start a new one. However all bugs contributing to HP loss Must be fixed before reconsidering.

**Comment by lefnire** [comment]
re: donations portal, gittip link is at the bottom of the page but nobody has been using it. Should I add paypal to the github main-page?

**Comment by hookang** [comment]
You should definitely put it somewhere easily visible, but not annoying.

With love, joy, peace, patience, kindness, goodness, faithfulness,
gentleness, and self-control,

Hoo Kang

Test everything. Hold on to the good. - 1st Thessalonians 5:21

http://about.me/hookang

**Comment by lefnire** [comment]
I know it's anathema, but I'm testing ads for a while. Kickstarter's looking grim, and I just wanna see how this goes for a bit.

**Comment by mirolabs** [comment]
2 ideas:

1) a white label or closed version of habitrpg might be interesting for coaches. - Similarly to http://lifetick.com/coach.html.  The best tool is of little use if people use it poorly. 

I think there's a huge potential for tools like habitrpg, but a lot of potential customers won't realize that.

If they already have a coach or therapist or personal trainer, these guys could explain it to them and use habitrpg as there usp.

2) What if there was a temple where you go and pray for ressurection, and make an offering? If I fuck up, it makes sense that I need to make amends for that. So it might work better if you let people decide what they want to give. You could still reject cheapskates of course, but I think this would be worth trying.

Alex

**Comment by lefnire** [comment]
@mirolabs #2 used to be in place. pay 50 cents to rez, pissed people off big time. Your idea of optional donation is a good idea in that respect though, i'll throw it in my list. Good idea on 1

**Comment by racuna** [comment]
$1 for a one day in IDDQD "god mode" (health and xp bars frozen). Useful for vacations.

Anyway, Enterprise Mode is a good idea for teams.

**Comment by the-economancer** [comment]
So, having read through all this, I can't say much about an enterprise mode, no experience there. But the ads are unobtrusive enough (at least on my computer and Nook) that if they are generating any kind of revenue, stick with them.
I wasn't around for pay to resurrect, so I don't know what that was like, but if it just resets you to zero (like death does now) I could see what the fuss was about. A possible solution would be to have the premium tokens available for a full resurrection with the same exp, coins and level that you had before death, with HP restored and all tasks "re-rolled" (if this wasn't already the case). Without paying you could either restart from zero, or perhaps just lose all your progress tnl (as well as reward coins). Ideally, death should have consequences, otherwise, who is really going to care about losing HP, but if you have to shill out some money to cheat death in order pick up where you left off, that is probably incentive enough to try and avoid it.
I mentioned in my post https://github.com/lefnire/habitrpg/issues/98 the idea of a quest system based on tasks with dependencies on other tasks, and that other players could post quests for others to accept (adding the tasks and quest chain as well as reward) to their "character sheet". This could be monetized by having sponsored quests appear prominently in the list of quests that users can look through (possibly with a notification on log-in if there aren't too many going on at the same time). Companies or groups could create quests (alternatively, we could create some for them) relevant to their purpose. For example, in 2016, rockthevote.org might be interested in sponsoring a quest with the tasks "Register to Vote", "Check out the Candidates", and "Vote" with a reward for completion being either regular reward coins or premium tokens, extra exp, or premium vanity items.
On the subject of premium items, I am not fond of any that would give actual "in-game" advantages, since you're essentially supposed to be leveling up your life as you level up your character. That being said, you gotta get paid some how. Vanity items without actual in-game bonuses would be a good compromise, especially if it was spun as a reward for donations, rather than an out-right purchase (You aren't wasting real money to make your avatar pretty/cool, you're contributing money to help an app you like, and you get cool items for your avatar in return). This would be especially useful once a group/party system was implemented, or any kind of social network integration.
That's all I've got for now, I'll be sure to check back and see what everyone's thoughts are, and maybe throw in a few more ideas as they come to me, since they are certain to do so.

**Comment by lefnire** [comment]
Brilliant. You're providing wonderful food-for-thought @the-economancer, thanks for getting so involved in the queue! I'll address the others later once we start monetizing, but specifically "in-game" advantages: No purchasable item will help the user, except emergency items (cheat death like you said, I was going to use [Firepotion](https://github.com/mozilla/BrowserQuest/blob/master/client/img/1/item-firepotion.png) - right there with you) and I'm sure we'll devise a way to prevent that from being abused. But no stats modifiers can be bought, they'll all be earned because this _will_ be competitive. Purchaseables will be decorative.

**Comment by hookang** [comment]
Game Changer!

Saw a comment by Alicia Gibb on Kickstarter - She wants a cookie delivered automatically as a real reward.

If we take credit card numbers and then order stuff off of amazon and deliver it to our users.

The affiliate commissions alone will turn this into a very viable business model.

Of course we would want to automate this.

**Comment by wc8** [comment]
[Tangible Rewards](https://trello.com/c/dcNk6aKV) delivered cookies, etc.

**Comment by wc8** [comment]
@hookang Alicia Gibb's idea would involve in-game coin and real currency right?
If not in-game coin, I do think there should be some way in which users earn the right to purchase the reward. 
As noted by Andrew Kenney

> This could be implemented if the user pays for it themselves with real currency. Going with the t-shirt idea, many people would pay for the t-shirt if it was hard to earn the right to buy it in the first place.

**Comment by killroy42** [comment]
RE: White label.
We do SCRUM for our MMO title, currently using DevSuite (Ugh) and Perforce. A tie-in with HabitRPG would be awesome.
Habits would be the ongoing stuff we "should" do, like code reviews, pulling defects and such.
Dailies are our regulars, like daily stand-up, Updating our tasks in DevSuite and pulling/pushing to/from MAIN.
ToDo would be the tasks and stories.
Seems like a good match. Of course the company should be able to add perks as in-store items and adjust/balance income and value of gold.

Of course security is a big issue, since our IP is pretty tight and nothing, including wording of tasks/stories can leave the studio.

Let me know if you wanna talk about matching HabitRPG features to white-label requirements.

**Comment by lefnire** [comment]
Awesome, let's definitely talk about this once the white label feature
starts becoming a reality

**Comment by lefnire** [comment]
FYI - I've gotten a _ton_ of emails since Lifehacker day from teachers, project managers, and special ed instructors asking for the "white label" part (see my modified # 2 of [wiki](https://github.com/lefnire/habitrpg/wiki/Business-Model)). They didn't know about that wiki, and they all started with "I have this wild idea! what if...". Unfortunately none are willing to contract a pilot implementation ;) However, I believe the white label is going to be our most promising business model.

Our competitor in that space is [ClassDojo](http://www.classdojo.com/), but evidently it's a bit more targeted than our approach, so we'll need to play with it a bit for comparison sake.

**Comment by lefnire** [comment]
@SlappyBag queueing you in on this convo too, since you're a major contributor.

**Comment by killroy42** [comment]
Is it time yet to promo it to our scrum master?

**Comment by lefnire** [comment]
I think enough bugs are fixed for organizations (eg, your scrum master) to take a look at it, that would be great! Before organizations can use it though, we need to implement (1) Parties and (2) Quests. After that we need to make Parties manageable by a single account (this will be specific to white label version). That's the "MVP" white label.

**Comment by killroy42** [comment]
Is this the right place to reply to?

I want to get in on the code base. I haven't worked on a biggish open
source project before, so will need to get used to it.

I've been doing fancy web tech since long before it was fancy, and it's
time I get back up to date. Aparently I've been asleep at the wheel... I've
been begging for server side js, and while I've blionked aparently Node.jas
and techs like Derby came about... 8 years passed in a blink,and web techs
moved on in the mean time ;)

Let's have a call this weekend if you can schedule it!

Cheers,
Sven

**Comment by lefnire** [comment]
unfortunately going to be out this weekend, take a peek at the codebase and see how deep you can get - then let's touch base next week sometime

**Comment by horusofoz** [comment]
Thank you to everyone for the great ideas. Your input has been most enouraging.

We are closing this topic for now. Will re-open or raise a new ticket when requesting further input from the community.

Thanks again.

**Comment by Pandoro** [comment]
Mentioning #479 for organizational issues.
