### ISSUE TITLE
Realtime features

### ISSUE THREAD

**Issue by killroy42** [HabitRPG/habitica#252]
Trello Card: https://trello.com/c/edwHxp5G

I woke up around 3am with this brilliant idea.

Real-time features.

I'm thinking stuff like OGame or Travian. Things that inexorably march towards you, not like ToDo items that can just sit there forever. A true commitment to get something done in a particular time span. Then you have a "snooze" option that may be purchased, or better even, fought for. This could be an RPG-style combat, or something more HabitRPG like. For example you fight with habit++ and dailies.

The idea is for these interactions to be real-time, but slow. The battle might wage for hours, days or even weeks. For example, a few extra pounds of weight loss over a 4 week fitness quest might buy you some extra days of procrastination on that visit to the in-laws.

I have always found procrastination to be a powerful motivator to do other things. Let's make it work for us. In truth, there is ALWAYS something else you'd rather not do then the task at hand. We just have to be threatened with that!

This needs a re-write ;)

**Comment by StanLindsey** [comment]
I like the sounds of this, especially as many are asking for mini-games and more game-like elements which are hard to fit into the design of HabitRPG at the moment. 

So to confirm the idea could be maybe each week/month etc you face off another boss or enemy or other challenge on your journey through life, these battles/journeys/challenges would although in real time would battle out of the course of hours or days. They would be fueled by your progress through each day; completing habits/tasks could heal/do critical damage etc in the ongoing battle in the header of HabitRPG.com

I view it to work similar to this
http://www.youtube.com/watch?feature=player_detailpage&v=URrhSa_XfXk#t=165s
In the top of the window is a real time "quest", you match3 tiles to interact with the "journey" above. In HabitRPG it would A. be a whole load slower and B. be fueled by your habits. 

In the game above there are also chests/doors/jumps etc that must be performed by matching 3 (al-la Bewjeled) which could work very well for a Habit/ToDo fueled game.

(Am I even remotely close to what you are describing @killroy42 or have I just creating something new?)

**Comment by killroy42** [comment]
Pretty much! I like this even better as it fits the RPG expectation more. My comparison to games like Travian feed into a different type of player. These are games I found highly addictive. I am still trying to get myself addicted to succeeding at live and getting stuff done!

Also, the longer term strategies can better mesh with real world habits and ToDos.

I think the important part though is the real-time aspect of games like OGame and Travian, as many productivity and ToDo systems miss the sense of urgency. I know that ToDo tasks going stale and starting to hurt you are part of that, but I don't think that is nearly as compelling as an incoming attack on Travian, 24 hours out. I've set alarms for 4am to send attacks or sort out defense for Travian before... I've never done that to sort out my real-world troubles ;)

**Comment by StanLindsey** [comment]
Exactly, combining that sort of methodology and design with a to-do list/habit tracker seems like a fantastic motivator. I also believe this sort of element could easily tie in many of the other suggestions people are making. It could easily tie into parties, rewards, skills etc as well as being that constant motivator. What are your thoughts on this @lefnire @horusofoz  @wc8  @hookang - I only tag you all in here because I think this has the potential to focus a lot of the other more "gamey" suggestions into a coherent whole with fracturing the HabitRPG experience. 

If people like the idea I will absolutely love to write this up as a proper design document/pitch. 

I've created the Trello card here
https://trello.com/c/edwHxp5G

**Comment by wc8** [comment]
I like the idea of a header that your "guy" moves through, as he gets things done. Level up sends you to a new header. A variation of the [Background Zone](https://trello.com/c/6P9dDIly) suggestion.

The idea of **certain tasks** moving toward you/coming up in your way (represented by objects in the header) and arrive at a certain time is also interesting. Perhaps the task icon (if that feature is implemented) could appear.

I think the idea of Earned Items Hunt could also fit in: you suddenly find a ruby in your path (in the header) when you complete a habit. Every time you find an item for the hunt it appears in the header (briefly/until clicked).

The idea of boss battles/creatures also fits in. They could appear when the [Checklist](https://trello.com/c/PJ1iJ413) items are complete, etc, as otherwise suggested. 

As far as real time commitments to do things at a certain time: this needs to be LIMITED. 
A limited application may be the intention, but on personal experience, let me say, this is very important. 
If every task is urgent, nothing is urgent and the user is frantic.
Some things need to sit on a todo list. 

I've tried using an app, Alarms, and setting an alarm for todo. 
The problem: interruptions, over commitment, unrealistic expectations, etc.
You end up postponing the alarm or letting it slip and forgetting it anyway.

As far as an announcement/alarm of an impending invasion, battle or attack for tasks with [dates/deadlines](https://trello.com/c/i6kXvNY2), it seems to fit in with the general idea of RPGing the tasks.

**Comment by StanLindsey** [comment]
In my head I view it as very passive and more of a visual representation of how you are doing with your tasks. If you don't do well then there wouldn't be any negatives that haven't been suggested already in other threads. 

But as your post demonstrated @wc8 this addition could incorporate a huge amount of other suggestions into one coherent feature.

**Comment by killroy42** [comment]
For real-time tasks I would design it similar to such real time games
(Travian) which don't suffer from that effect. In fact they seem to get
more addictive to the point of displacing real-world stuff to handle game
events.

Not for everything of course, but some items just don't make sense if they
are open ended and loose value the longer they sit.

And if an event snooze costs gold, it might take away from buying rewards
and be a motivator.

**Comment by wc8** [comment]
Answering a game alarm (not familiar with Travian) rarely overwhelms because answering the call of an attack is 1) more fun than paying bills 2) far easier than running for an hour 3) an escape from doing the dishes, 4) requires less mental energy than reading a textbook, etc.. 

However, it is true that part of the reason digital games have so much appeal is they **get your attention** and call you to answer in an appealing, engaging way, which is, after all, what HabitRPG aims for.

@killroy42 It sounds like **Scheduled Task Attack** might need its own trello card. Is that a good title for it?

Let me see if I get the idea:

Example: Project **Write/Read Chapter 12** _Starts Monday_ and is _Due Thursday_
- Monday arrives: battle starts (visible in header)
- You're running behind Tuesday night, so you purchase Delay Shield for 5 GP or 20% of available gold. **Chapter 12** holds off for Friday.
- Wednesday, your boss/teacher hands you Task Essay to be done by Monday. You fight off **Chapter 12** for 5 days by completing Task Essay by Monday. **Ch. 12** retreats to Wednesday.
- Tuesday: **Ch. 12** is due tomorrow, but you haven't quite finished. You buy Delay Shield for 25 GP or 50% of available gold. (The cost is higher closer to due date). **Ch. 12** retreats to Thursday.
- Wednesday, you finish **Ch. 12** and win the battle.

Is this anything like what you have in mind?

**Comment by StanLindsey** [comment]
Could totally work like that incorporating daily and the like as well, dailys loose you health anyway so they could easily be incorporated into having a visual representation. Again, this is something I plan on spending some time properly designing utilising all these suggestions people keep piling on.

**Comment by killroy42** [comment]
Sounds pretty good.

The way games like Travian and OGame and the whole genre work is that
things take real time. For example an attack to a village may take 10, 20
or more hours. Then on your UI all pending actions have live JS count down
timers. The idea is that strategy has a lot to do with timing. Send your
defense troops so they arrive seconds before the attack and whipe them out.
that sort of thing. So it doesn't require constant attention, but specific
attention and planning. I think that is what makes it addictive. It feels
like you're nto in total control, since events continue to happen even if
you cannot attend them... a bit like in real life.

But I love the idea of illustrating timers with RPG events. For example,
timed events might be an advanced strategy feature, when your'e a lvl 10+
hero with a village to defend ;)

**Comment by StanLindsey** [comment]
Exactly this is another feature that could go further and be pushed. We'd have to look into how timings and things like that may crop up. At the start I envision it more like a randomly generated dungeon crawl (similar to the video I posted). Maybe parties can have villages etc and send out their members on particular quests or whatever. 

One issue to try not to make it too gamey, it is predominantly a motivational tool and should support people completing their tasks instead of being the main focus. This is honestly my favourite and in my mind most potential single idea.

**Comment by wc8** [comment]
[Scheduled Attacks / Real Time Events](https://trello.com/c/vPuLG1G0) has a trello card. Is it too soon?
@SlappyBag I really like the way that video's guy moves **while** you play the game. 
Something similar in the header could keep the **game** going only insofar as you are getting things done (or being warned that you need to get something done).

In that case (the video), the game is always going. In HabitRPG the character's movement could be triggered by game play (habit completed, task due objects) or by passage of time: real time. He moves across the scene as the day goes by.

**Comment by StanLindsey** [comment]
@wc8 Sorry I made [This one](https://trello.com/c/edwHxp5G) in relation to this thread. 

And exactly, you've hit the nail on the head, the translation from the video example to HabitRPG would be that HabitRPG would be ongoing 24/7 (or during the night you rest and you maybe get "free time") and the enemies represent either in-particular tasks or your character attacks random enemies by completing any task and takes damage from failed dailys. 

I prefer the second option personally because the fights will last faster and would promote broad range improvements. Bosses could appear though that require certain tasks, maybe ones you aren't doing well at. Red to-dos and Dailys could cause criticals. All manner of mechanics could be implemented including from other suggestions;

Loot Drops
Stats
Achievements/Badges
Incorporation into parties & sharing etc

**Comment by wc8** [comment]
@SlappyBag I saw the Ongoing Real-Time Adventure card [even voted for it]; the real time scheduled task attack feature seems to fall into a separate (albeit related) request, no? 
That is to say, I saw scheduled task attacks as _one kind_ of enemy/obstacle that could come up in your header path. 
My thinking is, the feature (scheduled attacks) could be implemented even if the Ongoing Adventure is not. If the two are really fused, they could be merged or the second one (Scheduled Task Attack in Real Time) archived.

It might be useful to create links in the On-Going Adventure card to potential sub-features, possibly with a brief note on the Adventure card about how they might be integrated.

**Comment by wc8** [comment]
@SlappyBag 

> and the enemies represent either in-particular tasks or your character attacks by completing any task and takes damage from dailys. I prefer the second option personally because the fights will last faster, bosses could appear that require certain tasks.

Could you explain further what you're thinking? My initial reaction is: both-and, but that suggests I'm not understanding it.

**Comment by StanLindsey** [comment]
@wc8 

Your reaction is correct I was just a little bit rambley in my post and also your reasoning for splitting the two into separate cards is perfectly sound.

A little bit of clarification on my part though;
After your previous two posts; mixing the two would be the perfect way of implementing this feature. I'd split them into two groups;

A. Mobs
Mobs are general monsters which could be damaged by any tasks you complete.

B. Bosses 
Boss monsters would only be damaged by a specific combination or individual task/habits and are much harder than individual mobs. They would pick habits/dailys that are red and not performing well and therefore force the user/player to focus on those bad habits. This could actually replace the diseased tasks idea in some ways in that the redder/worse a task/habit/daily/todo gets the most likely it is to appear as a boss.

Mechanics for bosses could range from you cannot do damage to it until a particular task is complete, then regular tasks cause damage like a regular mob or in the case of a daily you may fight the boss for 7 days and need a recurrence of 6/7 of a particular daily habit. 

You would lose health only upon defeat by an enemy but there will be ample time. There could possibly be items or drops (or one off spells?) that allow you to skip individual enemies or knock off some HP.  (Their HP essentially being the number of tasks to complete before they die).

Lastly there could be chests that drop. These would be time limited and could take place of the various challenge suggestions. You must complete a task from your list or a task offered (e.g. "Go for a run today" even if its not on any of you lists) - if you complete that task then you get the contents of the chest; health, gold, one off items usable later etc.

**Comment by horusofoz** [comment]
I think this sounds Awesome. 

Can someone draft a more detailed consolidated concept of how it would be implemented? There's a lot of grey in my understanding of how this would work.

**Comment by StanLindsey** [comment]
Yeah I'm on planning properly designing this soon.

**Comment by horusofoz** [comment]
With Trello cards up are we cool to close this ticket? Discussion can continue here even if it is closed or moved to Trello.

**Comment by Pandoro** [comment]
I think closing it is fine for now. I like the idea, but I also have the feeling for now we need to focus on getting the game bug-free and stable ;) Let's see what @SlappyBag will come up with in a proper design.
