### ISSUE TITLE
clicking on habit activated wrong one.

### ISSUE THREAD

**Issue by AtomicVagabond** [HabitRPG/habitica#2526]
I clicked on one of my negative only habits twice, but it selected the positive option on one of my other habits a few spaces above twice instead.

**Comment by negue** [comment]
Can't reproduce, does the error still exist?

**Comment by AtomicVagabond** [comment]
Not that I could see when I was last using the program. 
Sent using CloudMagic
On Fri, Aug 29, 2014 at 7:24 AM, negue notifications@github.com wrote:Can't reproduce, does the error still exist?

**Comment by negue** [comment]
Okay, then we need some more Informations^^

What Operating System? 
What Browser? 
What Resolution? 
Do you have zoom activated from OS and / or the browser?

Do the habits have the same name?

Could you create a second account and try to reproduce there?

Are the "other" habits are always the same, that get the positive option?

**Comment by Alys** [comment]
In addition to negue's questions, which are important:

Have you noticed mis-clicks in any other app or OS feature on your device? There might be a problem with your mouse/trackpad/touchscreen.

What is your [Unique User ID](https://habitrpg.com/#/options/settings/api)?

What are the names of the two Habits? If there's anything private in them, give us just enough of the names so that our database administrator can uniquely identify them, if it turns out that we need to ask for his help.

**Comment by deilann** [comment]
Another good question: did you recently sort your tasks? I've actually had
this happen because the sort happened on local, but wasn't saved server
side due to sorting too fast.

**Comment by AtomicVagabond** [comment]
It was on my old phone, a Motorola photon q. I used google chrome. It did have some software issues. That's about all the info I can give you. I don't really use habitrpg anymore.
Sent using CloudMagic
On Fri, Aug 29, 2014 at 3:04 PM, deilann notifications@github.com wrote:Another good question: did you recently sort your tasks? I've actually had

this happen because the sort happened on local, but wasn't saved server

side due to sorting too fast.
