### ISSUE TITLE
Non-breaking space errors on character build view

### ISSUE THREAD

**Issue by crashrampage** [HabitRPG/habitica#2536]
Under the 'Character Build' section on Stats & Achievements, there's a &nbsp; that prints out in plaintext, and a few more places where I suspect there's supposed to be a space, but there isn't one ('Class:Rogue' and 'Unallocated Points0').

This happens with Firefox and Safari under OSX, as well as Firefox under Linux.

![screen shot 2014-01-23 at 5 44 26 pm](https://f.cloud.github.com/assets/6486421/1990134/ff2951e2-847f-11e3-9247-865a120a182a.png)

**Comment by marcelosizer** [comment]
@crashrampage I believe this one has been fixed. Did you find more?

**Comment by SabreCat** [comment]
Should have been fixed in [this habitrpg-shared commit](https://github.com/HabitRPG/habitrpg-shared/commit/02311e8500f13a4f10fd8f67f870591a1858e867) and [this habitrpg commit](https://github.com/HabitRPG/habitrpg/commit/d782fc6b6a3cd7e90d327c93a5764626b2990c74). Hasn't deployed to the site yet, though.

**Comment by marcelosizer** [comment]
@SabreCat , I removed the discrepancies on my PRs so they don't interfere with yours.

**Comment by paglias** [comment]
Should be fixed, thanks to @Sinza-

**Comment by marcelosizer** [comment]
And @SabreCat who had already fixed most of them. ;)
