### ISSUE TITLE
Confirm Chat Deletions

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2540]
Went to go click on my name to test and see if the display name had stuck. Apparently accidentally clicked a trash can right above it and deleted a message. Can't remember what the message said. A prompt asking if you'd like to delete your message would be nice.

**Comment by marcelosizer** [comment]
Proposed fix in #2545.

**Comment by ghost** [comment]
Or an "undo" button, like in Gmail.

**Comment by marcelosizer** [comment]
The "undo" button is being worked on and all other delete buttons have that confirmation prompt.

**Comment by Alys** [comment]
The work required for this was done some time ago, but due to commit issues it's not able to be easily merged. This issue can probably be fixed by duplicating these two changes in a new pull request:

https://github.com/Sinza-/habitrpg/commit/f19f258ad09bc792a5b7c3c9f52b035eabd2d1e4
https://github.com/Sinza-/habitrpg/commit/b0eb9251969b79a679e19f107cf6a1c00d2701f3

@Sinza- Would you like to work on this? If not, let us know and we'll see if any new developers would like to take it on.

**Comment by crookedneighbor** [comment]
I took @Sinza- 's change and merged it in. @Sinza- should definitely get credit for it, I just copied and pasted.
