### ISSUE TITLE
Odd application error alert

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2554]
Created a new habit. Got this: 

![temp](https://f.cloud.github.com/assets/1575692/2000691/35e25ef6-8564-11e3-83f6-0f64312c70f7.png)

After dismissing it, got this notification in the upper-right:

![screen shot 2014-01-24 at 17 53 35](https://f.cloud.github.com/assets/1575692/2000694/40ebc67a-8564-11e3-9676-39423a5a308e.png)

However, the habit was created and is usable, and this didn't recur when I tried creating another new habit.

**Comment by ghost** [comment]
I got this as well a couple days ago, around 9sm UTC. It was worse, though, with the app becoming entirely unusable. Refreshing resulted in a full size version of the content in the modal window in your screenshot. I waited a few hours and the problem went away. I assumed their servers were creaking under the strain, but people in the Tavern were telling me they'd experienced no downtime around then.

**Comment by colegleason** [comment]
This occurs when the app actually breaks on the server. I believe thats Heroku's 503 error page. Since you still have a version running in your browser, it may look like things succeed when they don't, etc.

We may want to explicitly handle this to make more sense to the user.

**Comment by dbueller** [comment]
I got that error yesterday.

**Comment by AWrightIV** [comment]
I got the same thing today. I took screenshots, but they don't contribute any new information. Is there a log somewhere I can submit?

**Comment by paglias** [comment]
May this be happening when the app is being updated?

**Comment by AWrightIV** [comment]
I don't recall, unfortunately. I'll report back if it happens again.

**Comment by lefnire** [comment]
Bummer that Cluster wasn't working, since cluster + domain-middleware work together to crash a pid, fall-back users on the next pid, respawn new pid - which would prevent users immediately after a crash from getting an error. 

Sounds like the steps are:
- Solve the VersionError bug
- Get Cluster back in
- Close this ticket

**Comment by colegleason** [comment]
Could we catch errors instead of crashing the pid?

On Wed, Jan 29, 2014 at 2:09 PM, Tyler Renelle notifications@github.comwrote:

> Bummer that Cluster wasn't working, since cluster + domain-middleware work
> together to crash a pid, fall-back users on the next pid, respawn new pid -
> which would prevent users immediately after a crash from getting an error.
> 
> Sounds like the steps are:
> - Solve the VersionError bug
> - Get Cluster back in
> - Close this ticket
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2554#issuecomment-33625123
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
Actually, TMK it currently does catch errors, send them to email, and
ignores. I wonder if that's causing issues...

**Comment by colegleason** [comment]
Oh, look [here](http://nodejs.org/api/domain.html#domain_warning_don_t_ignore_errors). We want to crash the worker right after sending the email because the state isn't really stable after an error is thrown.

**Comment by lefnire** [comment]
Ok, so options then:
1. Crash worker. We'll want to use nodemon to restart the worker (is it setup to do so in prod already?). This will make that dyno unusable for the next 5-10s, but that shouldn't be too-too bad since we have 4-6 dynos (depending on load).
2. Double down on VersionError and add in Cluster. TMK, domain-middleware will automatically crash pids if cluster is in use.

**Comment by deilann** [comment]
Party member hit Vice's Shade twice today:

![screenshot from 2014-02-02 13 04 14](https://f.cloud.github.com/assets/6274734/2061419/34eea0ba-8c51-11e3-93eb-a459f7076308.png)

**Comment by lemoness** [comment]
Hate to break it to you, Tyler -  I hit another 503 this morning. It hasn't been happening nearly so frequently, but it's definitely still a thing. It's keeping me from accessing Habit right now.

**Comment by lefnire** [comment]
@lemoness I'm mucking around with beta right now, did you experience it on prod?

**Comment by lemoness** [comment]
Beta both times. Switching to prod for the rest of the day; I'll be on
alert and keep you guys posted.

**Comment by deilann** [comment]
I'm on prod, one 503 all day. Been hearing about 503s in the Tavern, but no
idea if they're on beta or prod.

**Comment by deilann** [comment]
Just got another 503. On prod.

**Comment by lemoness** [comment]
Just spent some time chatting with Tyler about this - he'll be much better
at updating you guys on the technical side, but the gist is that the
majority of the 503 errors were apparently reflections of another user
hitting a bug. Those have been dealt with. HOWEVER, 503 errors will still
be thrown when people encounter bugs themselves, so he and Cole are going
through and patching those up individually. [Very dumbed-down explanation.]
Rest assured that this is taking up the majority of his time right now.

**Comment by lefnire** [comment]
Should I do a blog about it? Don't want to bury the update, or bore people with mumbo jumbo - but then again, many people are probably curious, and it may go on another week or so until we peg it

**Comment by deilann** [comment]
My thoughts: a blog at least shows people who don't follow github that
you're aware of the situation and listening to them. It would make sure
that people don't give up and leave.

**Comment by colegleason** [comment]
Right, so the 503 is a general error that we get when the server crashes.
The intention is that when a server crashes it is immediately taken offline
so you don't try to access it when you load the page. Doing that fast
enough can be difficult, so that is why it still happens.

So the number of times you se this bug (503) is really a reflection of how
many other server-crashing (critical) bugs we have to work on right now. I
would love to have few or none, so I'm trying to dedicate the next ~4 weeks
to site stability work (as opposed to new feature work). This is a purely
personal decision and I can't speak for the other devs,.

I know the current error message is a bit opaque, and I do think we should
look at making it a bit more friendly to the user. Here are some things we
can do:
- Make a custom error page for the entire site (if it goes down due to
  crash or error). See here: https://devcenter.heroku.com/articles/error-pages.
  If someone makes a nice page, it's easy to add (@lefnire).
- Make special error handling code inside the client to handle this error
  when you encounter it after checking off a habit, etc. This would probably
  make a notification pop up and remove the alert that you currently see,
  which is weird.

On Mon, Feb 3, 2014 at 11:15 PM, deilann notifications@github.com wrote:

> My thoughts: a blog at least shows people who don't follow github that
> you're aware of the situation and listening to them. It would make sure
> that people don't give up and leave.
> 
> On Mon, Feb 3, 2014 at 9:12 PM, Tyler Renelle <notifications@github.com
> 
> > wrote:
> > 
> > Should I do a blog about it? Don't want to bury the update, or bore
> > people
> > with mumbo jumbo - but then again, many people are probably curious, and
> > it
> > may go on another week or so until we peg it
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HabitRPG/habitrpg/issues/2554#issuecomment-34031411>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2554#issuecomment-34031524
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
@colegleason I'm with ya. I'm holding off on Trello features for a good long while, sans maybe Undo (kickstarter promise). I'm gonna focus on **bugs**, gettings PRs finished & merged (esp cron), and business stuff / group plans.

**Comment by colegleason** [comment]
This milestone is what I'm using to track these issues: https://github.com/HabitRPG/habitrpg/issues?milestone=3&state=open

If you see stuff that seems like bugs relating to infrastructure (duplicate ops, stuff like that) as opposed to more benign stuff, place it there!

**Comment by lefnire** [comment]
:+1:

**Comment by lemoness** [comment]
Write a blog post and queue it for Wednesday at 1 PM. That way it will be
post fanart and the important information won't get buried. It doesn't have
to be long. I'm happy to take a look at it before you post, if you like.

**Comment by lefnire** [comment]
@lemoness @deilann I put the full description here https://github.com/HabitRPG/habitrpg/issues/milestones . This is probably better than a blog format, since it allows users to track all the remaining tickets (and since I can use markdown, and reference GH stuff). @lemoness probably best is to just send out tweet/fb/tumblr with a small "if you've experienced issues in the last week, read up on the issues & follow progress [here](https://github.com/HabitRPG/habitrpg/issues/milestones)". Shall I leave that to you so you can fit it into scheduling setup?

**Comment by lemoness** [comment]
Yep, I'll do that! Perfect.

**Comment by deilann** [comment]
I like all of that.

**Comment by deilann** [comment]
@lefnire If the 503s are related to clicking too fast, it might be prudent to bring back click delay, for 500ms to 2sec. Unlike 10s, this will let people batch update, but reduce the speed at which people click?

**Comment by lefnire** [comment]
@deilann i was thinking about that. Unfortunately that was only a drop-in for habits + / -, which was dirt simple. To add it in for other actions (checklists, dailies, todos, etc) is much less simple. Plus handling daily check-off HTML-proper vs model-binding is a bit difficult. I think best we spend that time working on the main solution

**Comment by deilann** [comment]
Agreed, but I know I mostly trigger it when I batch update habits -- people
tend not to click as fast with dailies and whatnot. It's something we've
already coded, so I figured it could be pushed while the main solution's
being looked at.

**Comment by paglias** [comment]
@lefnire actually batchupdate usually receives a single operation right?
Multiple ones are sent together only when the previous ones couldn't be
sent because the user was offline, right? In this case could we use normal
api routes unless strictly necessary, putting each op in the queue and
sending it to the server when the previous one is completed?
Il 07/feb/2014 22:50 "deilann" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
@paglias I think that might be a pretty difficult task actually.
1. Both mobile & web are using the same batch-update client-side framework, so we'd need to update in both locations
2. The way they work is to depend on `user.ops.*` to perform the same operation client-side (for speedy update), and then send the operation to the server to be re-preformed. Then the server doesn't send down the updated user unless it's changed since (bandwidth++). Switching to standard routes means we wouldn't get this in-browser auto-update thing.

It strikes me we just need to fix `userServices.js`'s batch-update handling, it's totally broken. FWIW it was written a year ago in very short time via oDesk, and hasn't really been mucked with since :/ So I'm not surprised..

**Comment by lefnire** [comment]
Anyway, closing this ticket because Application Error is finally solved!! See [convo here](https://github.com/HabitRPG/habitrpg/commit/e36d3264bed5a015888f834c967d92f953365e51)

**Comment by paglias** [comment]
Ok, I understand. Anyway, don't know if it's because there are less people
on saturday on the site or the recent chnages you and cole made but I gave
a quick look to NR's numbers and wow the responses are way faster than a
few days ago.

2014-02-08 17:38 GMT+01:00 Tyler Renelle notifications@github.com:

> @paglias https://github.com/paglias I think that might be a pretty
> difficult task actually.
> 1. Both mobile & web are using the same batch-update client-side
>    framework, so we'd need to update in both locations
> 2. The way they work is to depend on user.ops.\* to perform the same
>    operation client-side (for speedy update), and then send the operation to
>    the server to be re-preformed. Then the server doesn't send down the
>    updated user unless it's changed since (bandwidth++). Switching to standard
>    routes means we wouldn't get this in-browser auto-update thing.
> 
> It strikes me we just need to fix userServices.js's batch-update
> handling, it's totally broken. FWIW it was written a year ago in very short
> time via oDesk, and hasn't really been mucked with since :/ So I'm not
> surprised..
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2554#issuecomment-34548491
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment]
@paglias no we found the issue - it was memory overload by using too many Cluster cores. On Tues I'm gonna monitor it, because we're now butting at 800/1GB - 200mb padding, which I _think_ should be plenty, but I'll monitor it in case. We really wanna use cluster if we can due to domain-middleware corrupt worker killing, so gonna try to make it work.
