### ISSUE TITLE
Subscriber Gem cap not working?

### ISSUE THREAD

**Issue by VerbingNouns** [HabitRPG/habitica#2584]
I just subscribed the the monthly feature ("jazzmoth"), and bought my 25 gems. Just to check what the cap would look like, I kept clicking, and kept buying gems. (I only tried up to 27, for a total of 46.) I'm not sure whether the cap is in place, or not working, or whether there is something else that is going on that means I can "legally" buy more than 25, but I figured it was worth mentioning.

**Comment by colegleason** [comment]
@lefnire Could you please add me to the repo so I can look into this?

**Comment by lefnire** [comment]
@colegleason done. Things are about to get messy, I'm not sure the best way to handle this... probably just merge `HabitRPG/develop` into `lefnire/premium` for both repos. Since we'll now have multiple contribs, rebasing is no good (requires force-pushes). I'm really anticipating a strong dislike for maintaining separate branches, I'm gonna put my mind to how we can do this biz model with full OS code. 

CC @sabrecat @paglias

**Comment by lefnire** [comment]
We might be able to ease the process if we pull all non-essential premium IP out of the current `lefnire/premium` branches, really the only required stuff is in habitrpg-shared#index.coffee

**Comment by deilann** [comment]
This is working now.
