### ISSUE TITLE
Spritesmith has incorrect width/height on many of the sprites.

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2594]
110% zoom level on Chrome 32, Mac OSX 10.9.

![screen shot 2014-01-27 at 8 27 35 am](https://f.cloud.github.com/assets/232327/2009512/5ec85576-875f-11e3-87ad-2c8e127cea78.png)

**Comment by JadelynnOpal** [comment]
Now that you mention it, I'm seeing this glitch too.

**Comment by lefnire** [comment]
@colegleason yeah, I've noticed that ever since the spritesmith move. All sprites are separated cleanly, so spritesmith is adding width too high or something. First time I noticed it I thought, I'll just wait for a SS upgrade. Actually, not even sure if there's a ticket filed in there... let me check...

**Comment by lefnire** [comment]
https://github.com/Ensighten/spritesmith/issues/7

**Comment by negue** [comment]
@colegleason @JadelynnOpal Is this still happening?

**Comment by colegleason** [comment]
Haven't been on Habit lately, so I can't tell. The referenced issue seems
to have been closed.
