### ISSUE TITLE
Party members who rejected quest still get rewards

### ISSUE THREAD

**Issue by hattieshoe** [HabitRPG/habitica#2597]
We have a party member who rejected participating in the Gryphon quest. We watched carefully to be sure they would not take damage from the quest, and indeed they did not receive any boss damage. But on quest completion they received the rewards along with the rest of us. Related to #2407?

**Comment by Alys** [comment]
I haven't been able to replicate this on my local install, using the same code that's in habitrpg/develop so I'm thinking it was either a once-off glitch or a bug that has been fixed in the intervening months. I'm going to close this, but, @hattieshoe, if you suspect it might still be happening, tell us and I'll reopen this.
