### ISSUE TITLE
Gold and Experience not given on Trapper Santa completion

### ISSUE THREAD

**Issue by bobalicious** [HabitRPG/habitica#2612]
Completed the Trapper Santa quest today and received the Polar Bear mount.

However, I don't appear to have been given the Gold or Experience Points.

As far as I am aware my compatriot party member received all relevant bonuses.

Username: bobalicious (I think)

**Comment by deilann** [comment]
I can't investigate this, but they're going to need your UUID in order to investigate. You can find it under settings > API

**Comment by bobalicious** [comment]
Thanks.

Should I post it here, or elsewhere?

**Comment by deilann** [comment]
Go ahead and post it here.

**Comment by bobalicious** [comment]
Apologies for the delay...

9a1d2161-a881-464c-8de8-eab5e111d3ca

Also, thanks in advance for your help!

**Comment by bobalicious** [comment]
Hi, Is there any news on this?  Cheers

**Comment by tekvet** [comment]
I had about 20 points left on the Trapper Santa quest yesterday. I was in a solo party. Today, the quest is gone and I don't see the reward or achievement on my profile. I didn't die and I didn't see anything about the quest expiring so no idea why it's gone. Help?  

UID = bf311b37-a51b-4097-8711-914d6d595a9c

**Comment by tekvet** [comment]
My quest in progress was back yesterday. Thanks to whoever fixed that!

**Comment by deilann** [comment]
@bobalicious You should be able to add the XP and GP manually again through Fix Character Values under settings.

@tekvet Did your party page load completely without the quest showing or was it claiming you weren't in a party? If it's the latter, that's just the page not loading completely.

**Comment by bobalicious** [comment]
Thanks, appreciated

**Comment by tekvet** [comment]
@deilann The party page looked like it loaded completely but just didn't show any record of my ever being on the quest. All the other pages loaded/worked properly -- my health and XP bars responded to what I did on my dailies/to-do's, etc. Then a couple days later, the quest was back with my progress and all like it had never been gone. Not sure what the root cause was, but I was able to finish the last bit of the quest and get my rewards so I'm happy. :)
