### ISSUE TITLE
To-Dos randomly re-sorting themselves

### ISSUE THREAD

**Issue by daraxlaine** [HabitRPG/habitica#2637]
I have a pretty substaintial list of To-Dos because I use them to keep track of assignment due dates, etc. I have assigned almost all of them with a due-date. Since HabitRPG doesn't let you sort by due date (someday I hope it will) I manually reorganized it by due date. Except sometimes when I rearrange something, it will "unorder" itself. It's hard to describe, but to-dos jump all over the place! I know they are because I have them numbered and I also have assigned due dates. Sometimes when I check back in the morning, things are not where I left them. Other times I can see them rearranging themselves when I move a to-do back into place.

**Comment by 9fruits** [comment]
I have the same problem. Every time I refresh, the to-do's are jumping in a different order. Same with the random jumping while organising. They seem to have some sort of preferred order, since after refreshing twice they stay in the same unorganised order. While rearranging I have countered a 404 order, and a message from the website with some code. Would be great if this was fixed soon, makes using to-do's near impossible this way.

**Comment by lefnire** [comment]
Guarantee this has to do with archived to-dos. I'll look into when I can

**Comment by lefnire** [comment]
Do me a flavor all, do a quick search before filing tix, helps with organization. Dupe here: https://github.com/HabitRPG/habitrpg/issues/2606

**Comment by daraxlaine** [comment]
That's my bad. I saw two other ones that had been closed but didn't see the open one. I thought though the issue had been solved once it had reared up again. Only saw it after I posted. Thanks!! Bad searching on my part. 

---

Please excuse the brevity and spelling. Sent from a smartphone.

**Comment by lefnire** [comment]
np np! will dive in when I can
