### ISSUE TITLE
Red tasks are better than blue tasks

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#2639]
-    Experience gain decreases as goal value increases.
-    Gold gain decreases as goal value increases.
-    Item drop chance increases as the magnitude of a goal's value increases. A bright red goal with a value of -25 and a dark blue goal with a value of 25 have the same magnitude.
-    Damage from bad habits or missed dailies decreases as goals value increases.

So the redder a task, the more stuff you get for completing it.  Bluer tasks offer no advantages except for damaging you less (which is often a non-issue with dailies, and a definite non-issue for to-dos). 

This means that it's advantageous to purposefully fail a task in order to keep it redder (especially just before a level-up) or to put off completing a to-do, so when you complete it, you'll get a huge/bigger reward.

I understand the system is designed to make completing difficult/avoided tasks more appealing, but in practice, it has the opposite effect.  It'd be better if making tasks bluer / completing blue tasks conferred some advantage over red tasks rather than reds presently being better in almost every way.

**Comment by lorian** [comment]
While it may have the opposite effect for you, it has the intended effect for many users. I, for one, would be extremely unhappy if my "knit sweater" to-do gave me less xp and gold, just because it took a month of concerted effort to do!

There are discussions on this topic on the trello page; perhaps you would like to read the arguments on either side there. Personally, I wouldn't mind a per-task option to be an "early bloomer" or "late bloomer", as it were, but I haven't seen any interest in implementing such a feature.

**Comment by Waldere** [comment]
I agree with @Caspid, but I also don't think reds should give less rewards, because yeah, sometimes the promise of a bigger reward from a task I've been having trouble with is what made me grit my teeth and finish it.

Right now item drops increase based on value magnitude, rather than numerical value. Why not XP and Gold? I feel like bringing a task to dark blue should be worth more than ticking off a yellow. It doesn't have to strictly mirror the red values, either, because completing red tasks should be the _most_ incentivized goal on the site. Getting to and keeping a task at blue, though, should be the second most.

**Comment by lorian** [comment]
@Waldere For dailies, gold does increase on value magnitude, via streak bonuses. They work quite well, too; at high streaks I get more gold from the streak bonus than from the daily itself. Obviously they don't work for habits, but because habits can be clicked way more than once a day, I don't think the same incentives should be used.

**Comment by Hunkoys** [comment]
What I'll do now is just have a separate to do list in a planner, put the to dos I need for the day in Habitica, then have a daily that says "Empty out to do's".
