### ISSUE TITLE
Amount of Gems Became Negative

### ISSUE THREAD

**Issue by extrajordanary** [HabitRPG/habitica#2642]
I just subscribed earlier today and have been buying gems to grab the quest scrolls before they go away. So as of a few hours ago I had converted enough gold to get 16 gems, from which I bought 3 quest scrolls (2 trapper santa, 1 cub), leaving me with 4 gems.

I went back just now and decided that I definitely should get another cub one. I went to click on it and the "buy gems" popup came up, which was confusing. It correctly said I was subscribed so I closed it. Then I noticed that my number of Gems was now -4 and in the semi-transparent non-functional button looking mode. I wasn't sure if it was really a negative sign though, so to confirm I converted gold into another gem and my Gems then went to -3. 

So, not sure how it happened, but I should have 5 gems now, not -3.

Thanks!

**Comment by deilann** [comment]
Post your UUID -- it'll be needed to fix your account.

**Comment by extrajordanary** [comment]
Opps! Forgot. :)

7c389c86-74c3-419b-9cd7-94baafce2d49

**Comment by lefnire** [comment]
Ok, I'm seeing a pattern @colegleason. Somehow actions are being replicated. And I think when the action duplicates a second, or third, or fourth (etc) time, it comes with an empty body. In the case of people getting UUID-named tasks, they probably added a task, and then the "addTask" op got repeated a ton of times. The UUID-named API-based task is exactly what happens when you send `op:'addTask'` with an empty body (see https://github.com/HabitRPG/habitrpg/issues/2456). So here, I'd wager that @extrajordanary has more quest scrolls than they intended (replicated purchase op).

What could be causing duplicated ops? I feel like it's probably repeating on the server, not being sent from client-to-server multiple times. Reason is these actions are passing the validation checks that would normally fail (@extrajordanary should have been denied with "not enough gems"). 

Anyway, @extrajordanary I just set you up with 4Gems, let me know if you need anything else while we mull on this

**Comment by colegleason** [comment]
I wonder if these are user.ops calls that are somehow being called multiple
times. Perhaps one op is calling another? You pointed that out to me on
ultimateGear, and it wasn't obvious to me before that.

On Wed, Jan 29, 2014 at 10:09 PM, Tyler Renelle notifications@github.comwrote:

> Ok, I'm seeing a pattern @colegleason https://github.com/colegleason.
> Somehow actions are being replicated. And I think when the action
> duplicates a second, or third, or fourth (etc) time, it comes with an empty
> body. In the case of people getting UUID-named tasks, they probably added a
> task, and then the "addTask" op got repeated a ton of times. The UUID-named
> API-based task is exactly what happens when you send op:'addTask' with an
> empty body (see #2456 https://github.com/HabitRPG/habitrpg/issues/2456).
> So here, I'd wager that @extrajordanaryhttps://github.com/extrajordanaryhas more quest scrolls than they intended (replicated purchase op).
> 
> What could be causing duplicated ops? I feel like it's probably repeating
> on the server, not being sent from client-to-server multiple times. Reason
> is these actions are passing the validation checks that would normally fail
> (@extrajordanary https://github.com/extrajordanary should have been
> denied with "not enough gems").
> 
> Anyway, @extrajordanary https://github.com/extrajordanary I just set
> you up with 4Gems, let me know if you need anything else while we mull on
> this
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2642#issuecomment-33658836
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by extrajordanary** [comment]
I did add a new Habit earlier that got duplicated that I noticed recently as well, but at least that I could delete myself. Can't remember now if I made it shortly before or after my original gem and scroll purchasing spree.

@lefnire Looks like it just added 4 to my -3 so now I'm at 1 instead of 4. Thanks for being on top of it!

**Comment by lefnire** [comment]
@extrajordanary sorry, round 2

**Comment by extrajordanary** [comment]
Thanks :)

**Comment by colegleason** [comment]
@lefnire, I don't see a balance check in `user.ops.purchase` is that an oversight? If so the client may still be the culprit.

**Comment by lefnire** [comment]
@paglias added it here https://github.com/HabitRPG/habitrpg-shared/commit/6cf7160f659bba239ead5dce370c121d9bb04463 . Not live yet though, so it could very well be in this case.

I'm looking at your `user.ops` duplication theory now, it's a good hunch. I'll crashing, so might have to peek again tomorrow. Pushing a temp fix to the spells bug

**Comment by wc8** [comment]
I'm not sure if this is related, but just in case it's helpful, I found applescript API (e.g. Pomodoro) was only working with a new (applescript-created) habit, it doesn't seem to update an existing habit. (Of course, this could well be user error.)

**Comment by MtnLioness** [comment]
I'm having the same issue. I had 10 gems earlier today, and now I have 0! I also had a couple to-dos duplicate themselves a few hours ago (and they turned green when checked instead of vanishing, which was weird), so I'm thinking the underlying problem is likely to be similar if not identical to the OP's. My UUID is 2205917b-5cd0-484f-a863-b1fcdcc146b6.

**Comment by lefnire** [comment]
@MtnLioness i updated you, check now

**Comment by MtnLioness** [comment]
Balance of 20 gems. Thanks!

**Comment by crookedneighbor** [comment]
@lefnire Ha. Closed it less than 5 seconds before you changed the title. I assume you're working on something related to it, so I re-opened it.
