### ISSUE TITLE
Not clear from Subscription page whether sub is for calendar month, or 30 days

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2650]
In fact, I'm still not sure: is the subscription for, say, the month of January, or for 30 days since I subscribed? Making this clear would make it easier for people to decide if they want to subscribe near the end of the month.
##

**Comment by deilann** [comment]
@lefnire Can we please please please get this updated? It's a biggie.

**Comment by lefnire** [comment]
On mobile now, could you do me a favor and add a subscription tag (if not already) and throw these in there? I'll hot them on coming days

**Comment by deilann** [comment]
done

**Comment by negue** [comment]
ping @lefnire

**Comment by lefnire** [comment]
Subscription is 30 days. ie, you are charged every 30d starting from your subscription's creation. Canceling a sub will not cancel your benefits until the end of your current billing cycle. So payments-wise, everything acts as expected.

The thing that _doesn't_ act as expected (due to a limitation I'm trying to figure around): gem cap resets on the 1st of each month, not tied to billing cycle

**Comment by librarianmage** [comment]
Is this still a problem?

**Comment by Alys** [comment]
Yes, there's still confusion from players about when their subscriptions will renew (although that's partly because there's also no notice about what date they started). I'm marking this as "suggestion-discussion" so that we can work out how best to handle it or whether it's better done as part of other work.

**Comment by librarianmage** [comment]
Should this be put on hold to see if it changes with the new client update?

**Comment by Alys** [comment]
This is being redesigned by the staff in an internal project so I'm closing it.
