### ISSUE TITLE
Allow user to set Monday as first day of week

### ISSUE THREAD

**Issue by pafcu** [HabitRPG/habitica#2652]
Monday is the first day of the week in many cultures and the ISO 8601 standard. A user should be able to specify that weeks start on Monday and this setting should be considered when displaying a calendar, such as for the due date of a task.

**Comment by DanielTheBard** [comment]
With the due date calendars this suggestion makes more sense to me. If only as a matter of convenience for our users from other countries.

**Comment by patena** [comment]
This would be great for the day order on dailies, as well as for due dates. The Sunday-starting week for dailies confuses me and I keep picking my dates wrong.

**Comment by DanielTheBard** [comment]
@patena - I see that as less important. I don't get confused when I see the Portuguese (European) setup of the week (Where monday is the first day) instead of the American (Sunday). Especially, since it is only showing one week's worth of days. Fixing the calendar for a non-American style though seems much more important to me. If we can customize that option, then fixing the day order for dailies should happen as well, but as a lesser issue. IMO.

**Comment by patena** [comment]
For me the daily display is more important because I use it more often. But either way, if they implement the option they should do it for both, otherwise it'll be inconsistent and even more confusing.

**Comment by DanielTheBard** [comment]
Yes, obviously.

**Comment by paglias** [comment]
I think we can use moment.js for that, it has country specific formats for weeks, dates...

**Comment by deilann** [comment]
Let's follow this at #2653, even though it's newer.

**Comment by Berad** [comment]
@paglias Hello Mateo. I'm not sure if I mentioned you correctly.
But the problem with the first day of the week (Sunday or Monday) was never solved. 
And it's painfull.
Is there any chance to fix it?
Should I open new issue?

**Comment by paglias** [comment]
Hi @Berad I am not active in the project anymore, you can try to create a new issue about it

**Comment by Berad** [comment]
@paglias got it. Sorry to bother you. And thank you =)
