### ISSUE TITLE
Private Guilds Cost Gems To Make?

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2670]
This got brought up and I was surprised to find it was true. I thought that Private Guilds were meant to be free, and only Public Guilds cost gems - am I conflating them with challenges? I may be behind the times with this one...

**Comment by lefnire** [comment]
My, this hasn't been brought up for an age... I think this was decided ~8mo ago. IIRC the thought was if fitness groups, writing groups, etc were creating ad-hocs for their IRL participants then that's a legitimate premium feature. Figured parties were sufficient for standard friend groups. Now we'll be adding family & group plans, I think we can reconsider this. I'll start making private guilds free, someone stop me if they have objections

**Comment by lefnire** [comment]
actually, jumped into the code and realized it's not so easy as that. Got some other crits occupying me, I'll leave this open

**Comment by deilann** [comment]
@lefnire I have some ~thoughts on this as well as some issues with the feasibility of group plans for educators -- can we chat on google about it? (My mom's a prof, so I have some understanding of some obstacles educators are going to have)

**Comment by lemoness** [comment]
Stick those in the G+ for us to look at!

**Comment by lemoness** [comment]
Those thoughts, I mean. Sorry. It's late.

**Comment by deilann** [comment]
The educator stuff I'll move to G+, if I can figure out how to condense it. I think my thoughts on this can be easily condensed and would be good to have public:

I have mixed feelings about private guilds "costing" gems.

1) Parties and private guilds are not always the same

I recently created a private guild for my roommate and I, so that we can track household stuff. It's just 2 of us, so having us be a party wouldn't give as much much benefit. At the same time, we don't want to flood a party with all of the household stuff. So, in that instance, we needed a private guild.

2) Private guilds take up space

At the same time, private guilds take up space on the server and are not necessary for the game's function. They are, in essence, a premium feature.

3) In reality, the cost is checking to see if the user has ever donated

Because you can immediately refund yourself the gems used in creating a private guild, it's less of a gem cost, and more of a check to see if the user has ever donated.

This means that free users can't create a private guild that takes up space (and they might not actually use), but that anyone who has four gems can, in essence, for free, create a guild.

**Comment by lemoness** [comment]
Hm, the fact that you can refund yourself the gems is a good one. Tyler,
what do you think about the server space? If private guilds are free, there
will be a flood of them for sure.
