### ISSUE TITLE
Boss causing health to become negative; doesn't kill, doesn't boot from battle

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#2673]
We are fighting the gryphon. One of our members had low HP and had a bad day yesterday, so he got some damage from uncompleted dailies AND even more damage from the gryphon. He now has a negative number (-10) of HP, this did not kill him and he is still participating in the quest.

It's not that I want him out of the quest, it just doesn't behave according to the decription of boss quests, so I feel it needs to be reported as a bug. This is similar to EXP rising above the level upper cap and not leveling the character when killing the boss.

**Comment by mczuchnowski** [comment]
So the party member did something and the application finally noticed that he should have died. So he lost one level, his HP and EXP went back to 0. But he is still participating in the quest.

**Comment by deilann** [comment]
Yeah, the "boot" mechanics haven't actually been coded in, iirc.

**Comment by deilann** [comment]
Oh, and jsyk -- they won't die until they log in, triggering a stat update.

**Comment by mczuchnowski** [comment]
That member logged in, this triggered damage from his own dailies and from boss, became negative. He stayed negative in HP until he ticked some task - this caused him to die, not the logging in by itself. Just like experience gained from quests can go above the level cap and does not level up the character until he/she completes a "standard" task (i.e. gains experience from source other than the quest).

**Comment by deilann** [comment]
That is an issue-- perhaps logging in needs to update stats as well?

**Comment by Alys** [comment]
I'm closing this but it can be reopened if there are objections to that.

Health becoming negative and not triggering death until the player takes an action on the site is a known thing and can be considered beneficial (see comments in https://github.com/HabitRPG/habitrpg/issues/3438).

Not being booted from a quest on death is also the preferred behaviour now (https://github.com/HabitRPG/habitrpg/issues/2407#issuecomment-54293696) and the description of boss quests has been modified accordingly.

The comment two above here talks about how logging in was not enough to kill the player; they had to take an action first. That might have been a bug but it was months ago now and I haven't heard of it happening since so it's likely that a site update has fixed that problem. If it's reported again we can investigate it with fresh data.
