### ISSUE TITLE
Unexpectedly died, dailies did not reset. Related to partial daily?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2675]
HabitRPG account name is Paqi (UID 6121da04-a6fb-449d-9e42-e3d0695565ab). Not sure if the first part is a bug, but the second has to be. I'm using a daily with a checklist for the first time, and only partially completed it before the end of yesterday. 

First part:
My character just died unexpectedly. He was at full health, and had completed the large majority of his dailies, enough so where I didn't think he should die, although I'm not sure how to calculate that to know for sure.

Second Part:
Upon refreshing the page this morning and clicking OK at the death notice, I noticed that most of the dailies I completed yesterday remained clicked, including one of my new dailies that includes 3 subitems: I had only completed 1 of the three yesterday, and that one remains clicked.

**Comment by FLJIM560** [comment]
I've been having the same problem (habits not resetting) for the last 3 days (Jim560). Last night I suffered an unwarranted death :( 

I have been using checklists since the roll out without a problem. However, in these last 3 days, when I switch computers, I start the day on a desktop and switch to laptop, I cannot get my laptop to sync with the site. Reloading the page has no effect and, in my experience, the SYNC button never works. Completed tasks from earlier in the day appear as unchecked. The first couple of days, I just re-checked the completed tasks. Last night, when I saw that the laptop wouldn't sync, I just closed the site without checking off any tasks. This morning I'm dead, even though I did most of my DAILIES and had 45-50 Health.

Since these problems started I've been seeing "503" errors a few times a day if that helps. I'm accessing the site on both computers using Chrome 31.0.1650.63 m.

FYI, my death didn't cause me to lose my Mana or my Level but I lost 3000+ Gold. The "Fix Character Values" option in Settings does not give the option of restoring Gold, even though that option appears in the description.  PLEASE GIMME MY GOLD BACK!!!

**Comment by JustinCope** [comment]
Same issue.  Completed all dailies yesterday.  Refreshed this morning, and received notice I had died.  Lost a level, my gold and a random item.  Yesterday's dailies are still checked, but my Friday dailies are active now.

User ID: e6b8154c-8920-4779-adde-469004dfdbd0
Facebook login, Firefox 26.0, MacOSX 10.7.5

**Comment by jdunlop81** [comment]
Same, I died unexpectedly. Had 48 hp and completed almost all dailies and my tasks will not reset after syncing, refreshing, closing habitrpg tab and opening new one. I thought maybe it was because I  changed cron time to 2:00 and it messed up but it looks like this happened to a few others this morning. I lost my newly bought yeti helm I bought yesterday and its limited edition, disappearing after today:( What an undeserved kick in the teeth.
UID: 778ee2a8-72d3-485b-8ace-0021557c6b55
Chrome  Version 32.0.1700.102 m, Windows 7
PS: I have no gold to replace and I don't want to do or make any new tasks while this is not working

**Comment by FLJIM560** [comment]
My UID 2419a180-11e2-4266-8466-93160c1daf6a

**Comment by jdunlop81** [comment]
Something else I just noticed is that some of my dailies and to dos have replicated, there are doubles of the same task

**Comment by lorian** [comment]
The still-checked dailies bug is being discussed at #1057 ; the cloning items is unrelated (I've gotten each bug separately, as well as together).

**Comment by lefnire** [comment]
Let's follow on https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-34134544 . As @lorian pointed out, #1057 for still-checked-dailies
