### ISSUE TITLE
Debug +XP +GP, GP is taken away upon refresh

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2681]
Trying to give a test account some monies, I used the debug +XP +GP. XP worked just fine -- but when I refreshed, it took away all of the test account's monies. Is this due to patching exploits?

**Comment by lefnire** [comment]
Yep, it is indeed. GP is no longer supported in `PUT /user`. However, that was meant to mitigate (1) holiday event, (2) basic account. Since holiday's over tomorrow, and basic caps at 25 gems - maybe we should put restore GP (& the requisite PUT route) back in? worst case, subscribers will be able to gain 5 more G/mo than if they bought it out-right, but whatever - they're subscribed, right?

**Comment by deilann** [comment]
_insert Ryan's schpiel on cheaters_

I think people who subscribed for gold2gems are unlikely to use the PUT
route to get a few extra, as the point is to help them feel like they've
earned it and/or use up excess gold.

**Comment by deilann** [comment]
At the very least, enable the PUT route on develop, to make debug work?

**Comment by lefnire** [comment]
I totally agree. And, this was added when gem cap was 50, I think that made it a more likely issue. I'll restore the "restore GP" function (+ the debug button_
