### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#269]
Maybe we are all thinking about the graphs all wrong. Instead of each being directly under the task,habit,or daily they should all be at the bottom. Singular graph with a line for each habit or daily. Maybe that would be too cluttered so maybe a graph for habits and dailies. In the style of xkcd would be plain awesome https://github.com/imkevinxu/xkcdgraphs.  Or maybe they should be placed right next to the avatar for quick access. I just think their current position is ill placed.

**Comment by abednego** [comment]
Similar to what I was suggesting yesterday, agreed, the graph should show up in one place.

Whenever you click on a Habit or Daily the graph should show up automatically, in my opinion.  There should be no need to click on a special icon, in my opinion.  Just select the Habit or Daily and you get a history and graph for that particular item.

An overall (but separate) graph for Habits, Daily, and To-Do's showing progress or other information would be nice; something you could select for the overall list rather than an individual item that would show up when selected.

**Comment by ghost** [comment]
@abednego care to sketch something up

**Comment by abednego** [comment]
I'll give it a try later if I have time.  Busy day today.  I'll maintain the four columns since everyone likes those.  ;)

**Comment by horusofoz** [comment]
Added as related suggestion to [Progress Views and Options](https://trello.com/c/h0pezwDR). Please add your voice and votes there.

**Comment by Ferk** [comment]
Wouldn't using the same graph put all the habits on the same scale?

Something you do pretty often might get higher values and change more drastically, shadowing the habits with lower frequency, it will be harder to notice progress on them.

Specially if you use some apps/extensions that use the API to regularly reward/punish on some habits, the distribution of points will be uneven against the habits that you have to click by yourself manually.

Also, some habits are harder or take longer time to fullfill. Before putting everything in the same graph some thought should be given on what value will actually be represented and on which scale.
