### ISSUE TITLE
Add Days of the Week to Habit Options

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2699]
If I have a + or a - only habit, it will change color upon cron. But if that habit is a work habit, or another habit that I only do on some days, rather than others, it's changing color when it shouldn't be.

If we added days of the week to Habits as well, to prevent them from changing color on greyed off days, it would prevent this issue.
##

**Comment by Alys** [comment]
Is this still desirable? It sounds interesting. You could also use the days to hide Habits that weren't "due" that day, as is done for Dailies. @lemoness what do you think?

**Comment by lemoness** [comment]
I don't have a strong opinion either way... it may add unnecessary complexity. I'd be curious to hear what @anitaycheng and @veeeeeee think about it.

**Comment by veeeeeee** [comment]
I don't have a strong opinion either. It might add consistency to Habits and Dailies, which is in keeping with some people's using Habits as a kind of baby-Daily, or as a bonus to the Daily for those who need to structure their setups to "double dip". But adding complexity is a definite concern. Perhaps hide it under advanced options for Habits?

**Comment by AnitaYCheng** [comment]
Since it's already a feature in Dailies, I don't think the added complexity would confuse people much. Needing to tighten up the UI is a concern, but I don't think the feature would confuse people.

Another thought (that will likely add a bunch of complexity to the coding end, but just throwing it out there) is to make a weekday-only tag? Or people could set a "work" tag that automatically activates a task or grays it out, and set the days they want it active. That way they can just tag a Habit or Daily with it, instead of having to choose the days each time. It'd be a customization shortcut.

What I'd also like to see is a pattern tag for my Dailies. "Every other day" or "Weekly" or something of the sort, from when I last do the Daily. That way I don't keep having to remember to reset the days if I forget it one day. `looks guiltily at my cat's IV bag`

**Comment by lemoness** [comment]
@anitaycheng - Weeklies and Monthlies are being built :)

Sounds like we can go ahead with this!

**Comment by paglias** [comment]
We've decided that we're not going to implement this and it's better to use tags for it
