### ISSUE TITLE
Rate limit exceeded error

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2708]
I was working quickly on my local instance, refreshed, and I seemed to have exceeded the rate limit. This was after a bunch of +1 levels.
![screen shot 2014-02-02 at 1 48 09 am](https://f.cloud.github.com/assets/232327/2059860/91b4d92c-8bde-11e3-95b7-f903ea01215c.png)

**Comment by colegleason** [comment]
That is in the browser by the way. The Jade files won't load.

**Comment by paglias** [comment]
Rate limiting should be limited only to api routes, not to views I suppose

**Comment by lefnire** [comment]
I disabled it for `NODE_ENV=development` so we won't hit this when coding. At first I had it as API-only, which prevent +habit spamming. However, having it at the top-level protects against DDoS (well.. hopefully... maybe a DDoS will still overwhelm the server, even if not handling full responses). I think we should be safe from this being an issue in prod, because everything is min/cat so that few-enough requests are made on page-load. It's set to 80 requests/m, I see about 10-20 tops on page load, which leaves quite some leg-room for interaction. Let's keep an eye on this though if anyone reports an issue. NR reports HTTP errors, as well as crash-errors. I've only ever seen 429 reported once, and it was like 500 of them all at once, which says to me we just blocked a cheater / DDoSer... Score!

**Comment by lefnire** [comment]
FWIW, the limit regens by the second, not the minute. So if you use 40requests, you don't have 40 remaining for the next full minute - you regen them second-ly so it's sane. I've done some tests on prod, it's pretty difficult to trigger 429

**Comment by Alys** [comment]
I'm closing this because I've never seen a report of it and it seems to have been handled appropriately.
