### ISSUE TITLE
Daily habits aren't resetting

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#271]
My daily habits are all still checked from when I completed them yesterday

**Comment by horusofoz** [comment]
Can you advise if this is still happening and your timezone please?

**Comment by ghost** [comment]
Yea, it's still happening. My timezone is AST (GMT-4)

**Comment by Pandoro** [comment]
Just to make sure that this is a bug, are you sure you checked them before 0:00 ? I have also checked things at around 0:30am and wondered why they didn't reset the next day. Considering you posted this around midnight last night, I just want to make sure you actually checked them within the previous day. Have you noticed this before or has it only happened once ?

**Comment by ghost** [comment]
This is the first time it's happened, but it's going on day 3 now. Also I usually check them throughout the day, so at least some of them are definitely from Tuesday.

EDIT: I just checked again and they have reset. It still took an extra day for them to reset, but they have now.

**Comment by lefnire** [comment]
I noticed `db.users.count({lastCron:{$exists:false}})` returns a surprising amount, which is weird because it should _always_ be 0 - I've made sure to set it first thing on page load if not present [here](https://github.com/lefnire/habitrpg/blob/c15d272e1275486dbd3bc9fc71293fc35187071a/src/app/index.coffee#L111) (to pick up user timezone, is why it's not on server), and right when cron starts running [here](https://github.com/lefnire/habitrpg/blob/c15d272e1275486dbd3bc9fc71293fc35187071a/src/app/scoring.coffee#L186). It seems that first part doesn't catch for you. 

What browser are you on? Derby basically sucks on IE (they're [working on it](https://github.com/codeparty/saddle)), so it might not be executing that script properly.

**Comment by ghost** [comment]
I hope no one uses IE anymore, I'm using chrome on Ubuntu 12.04.

**Comment by lefnire** [comment]
shoot, ok i'll start digging

**Comment by horusofoz** [comment]
Same/similar bug is affecting me this morning.

Only 5 of my 20 Dailys reset over night. 

The majority of my Dailys were completed yesterday morning. All were definitely completed before 12:00 AM.

I can't spot any other lost progress.

**Comment by horusofoz** [comment]
My Dailys did just reset as it ticket over 12:00 AM  (ACST 10:30) :)

**Comment by squirrel7** [comment]
Happening to me now - it was working fine over the weekend. I turned my computer off before 11PM (EST) last night. This afternoon (4 or 5ish - well over 12 hours since it should have reset), my daily tasks still showed things I checked off yesterday as grayed out, nothing seemed to reset overnight.

**Comment by horusofoz** [comment]
Is this bug still affecting users?

**Comment by squirrel7** [comment]
Not me, haven't had it happen again since I commented on it above.

**Comment by horusofoz** [comment]
I'm going to consider this bug squashed. Thanks for your reply @squirrel7
