### ISSUE TITLE
Don't auto-equip if newly-purchased equipment is worse than current equipment. [$10]

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#2711]
It seems that buying equipment from the shop will auto-equip it even when it's inferior to the currently-worn equipment.  This is rather annoying, especially now seeing as the Winter equipment is better than everything except the final gear.
##

**Comment by deilann** [comment]
Incorrect! It is better than everything except for the last TWO tiers of gear, because of class bonus.

But I get you. Small problem: people could want it both ways.

Folks who bought absurd party robes before level 4, might have wanted to wear them despite not being as good as their armor. They would have had no way to do this. At the same time, folks who bought absurd party robes might want their armor on, and they have no way to fix this.

**Comment by patena** [comment]
I agree that auto-equipping is really annoying. 
Even more annoying when I have a costume on and I don't realize anything changed until I go to check my inventory for some reason!

Maybe have an "equip?" question when buying something?

**Comment by lorian** [comment]
Or just let people change their armor as soon as they can buy it; that seems like a weird oversight, to have access to armor but not the armory at level 2.

**Comment by deilann** [comment]
Drops would have to come at the same time then -- or the equipment tab would have to be moved out of inventory.

**Comment by lorian** [comment]
Ah, I didn't realize drops didn't start until even later. Man, as someone facing a rebirth soon, I really wish there was a "non-tutorial mode", where access to all the basic features started at level 1. To anyone coming from an RPG background, it's not that complicated.

**Comment by deilann** [comment]
Drops are level 4. But it's more than easing you into the system -- it's
giving you early reasons to level up. I'd go to Trello to talk about
rebirth leaving basic features.

**Comment by JanChec** [comment]
Just make it changeable in options.

**Comment by deilann** [comment]
"Just make it changeable in options" means a lot more lines of code and
therefore legacy on top of the code hours to implement it and therefore
would need to be for more than mild inconvenience.

**Comment by JanChec** [comment]
From the user's point of view it isn't an argument. From dev's point of view it means that probably the code should be refactored anyway.

**Comment by deilann** [comment]
Actually, as a dev, it is an argument that I am making: there is not enough value in making it a setting for the amount of legacy it would create and code hours it would take.

If we made everything people disagreed on an option, we would have too many options and too much legacy. Especially for an OpenSource project that mainly relies on volunteers. So no, this is not something that is likely to ever become a setting.

I could see getting behind asking when the item is purchased whether or not to equip it, but that could get annoying when buying many items.

Either way, this is a low priority issue, and will likely be unresolved for much time, unless someone who feels strongly about it takes it up.

**Comment by SyntaxPickax** [comment]
I'd love to see this, so I put a small bounty on it. In my view (in line with @deilann and @patena), it would be best to prompt the user at time of purchase whether they would like to equip it or just send it to the inventory.

**Comment by Alys** [comment]
The way I'd like to see this done is a preference setting that specifies whether new gear is auto-equipped or not (with the default being auto-equipped, for the benefit of new users). I am normally not in favour of too many settings, but this is an issue that affects **all** players after they have obtained Ultimate Gear and I think it would be a significant usability improvement.

A preference setting means that the user wouldn't be bothered by having to make the decision with each item purchased. Once you already have a lot of gear (most of our users), new items are usually cosmetic and you very rarely would want them to be auto-equipped.

I'd like the setting to be on the Equipment page (rather than under Settings -> Site) - I think that's a natural location for it, and we already have a "use costume" setting there so there's a precedent for it. In fact it could be in the same location as "use costume" but on the Battle Gear side of the page. On-hover text (or a more-info popup) could explain in detail what the setting is for.

I'd be against having the setting under Settings -> Site because we see evidence that many users don't look there for settings (we often have to tell users about custom day start, sticky header, etc - they just don't notice them).

**Comment by crookedneighbor** [comment]
I'm :+1: on Alys's thoughts.

**Comment by robeden** [comment]
Here's a mockup. Is this how you would want it?

![autoequip_propose](https://cloud.githubusercontent.com/assets/1891321/8288909/c29d3032-18de-11e5-94f8-05fbaafb2038.png)

("Auto-Equip" or "Auto-equip"?)

**Comment by Alys** [comment]
I like that! Although perhaps "Auto-equip new gear" because it looks to me a bit odd all in capitals (I know Use Costume is all caps though).

@lemoness What do you think of this? 

@robeden It might be a couple of days before Lemoness replies because she's rather busy at the moment. We'd need her approval before this change would be accepted, so you might want to wait for her comments before going further.

**Comment by robeden** [comment]
Sounds good, I'm in no rush. If you want it to be sentence case rather than title case, let me know if you would like "Use Costume" to be changed to match.

**Comment by lemoness** [comment]
I think Auto-Equip New Gear is okay! I don't have a strong opinion, though.
Having this Setting on the Equipment page is a very good idea.

**Comment by robeden** [comment]
If everyone is agreed how it should work (no auto-equip when checked) and where it should go, I can start working on it and we can change wording whenever. I'm an Angular noob, so it might take me a bit anyway.

**Comment by Alys** [comment]
If you mean "no auto-equip when UNchecked" that would be fine! :) 

The default should be having the checkbox ticked (so that all new users have their gear auto-equipped as they buy it, which is the current behaviour).

The wording and positioning shown in your screenshot are good. 

Please do start when you wish and ask here if you have any questions or run into any problems.

**Comment by robeden** [comment]
> If you mean "no auto-equip when UNchecked" that would be fine! :)

Err... yeah, that. :-) Also agreed about the checkbox default state. Sounds like a plan!

**Comment by locks** [comment]
Is anyone working on this?

**Comment by crookedneighbor** [comment]
@locks To my knowledge, no one is working on this. Go for it.

**Comment by robeden** [comment]
I've been meaning to but haven't gotten to it. So I'll gladly pass you the baton.

**Comment by chrisamiller** [comment]
> Maybe have an "equip?" question when buying something?

I really like this solution, which would make buying something a bit more exciting. I'm picturing a popup screen that says something like: 

   _image of sword here_

### "You found the Ruby Sword!

Attributes: Strength +5. 

[Equip this item]   [Stow it in my inventory]
