### ISSUE TITLE
Exponential Quest Reward Scrolls

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2715]
So... as far as I can tell, if the second scroll is a reward of the first, everyone's going to get it. So a party of 7 finishes Vice pt 1. They get 7 scrolls of Vice pt 2. After that, they have 49 scrolls of Vice pt. 3.

And then another member hits level 30...

---

_edit by Alys:_

This issue applies to these four quest lines (which contain three quests each; the first only is linked to below):
- [Vice](http://habitica.wikia.com/wiki/Free_Yourself_of_the_Dragon's_Influence) - `vice1`, `vice2`, `vice3`
- [Attack of the Mundane](http://habitica.wikia.com/wiki/Dish_Disaster) - `atom1`, etc
- [Recidivate](http://habitica.wikia.com/wiki/The_Moonstone_Chain) - `moonstone1`, etc
- [The Golden Knight](http://habitica.wikia.com/wiki/A_Stern_Talking-To) - `goldenknight1`, etc

The way it is supposed to work is that when the first and second quest finish, the scroll for the next quest is given to only the person who had started the quest. All other quest rewards are given to all participants, as normal.

There's some old code in these two PRs, but they developed significant merge conflicts before they were reviewed, and I never found more time to finish it:
- https://github.com/HabitRPG/habitrpg-shared/pull/303
- https://github.com/HabitRPG/habitrpg/pull/4004

The code might be so outdated now that it could be better to start from scratch.

Here are screenshots of what we had in mind then. They were made a long time ago, so they might not exactly match the current site appearance - if so, the current site appearance should be retained. These are just a guideline for how this might be implemented now. If you want to handle it in some other way, that's fine!

**Quest Scroll when you click on it in Market or Inventory:**

![1 - quest scroll when you click on it in market or inventory](https://cloud.githubusercontent.com/assets/1495809/16891671/0b7bc4f4-4b41-11e6-8a84-b4477bbeb07a.png)

**Quest Invitation:**

![2 - quest invitation](https://cloud.githubusercontent.com/assets/1495809/16891676/0f28bf12-4b41-11e6-9ce9-dae719231b5e.png)

**In-Progress Quest on Party page:**

![3 - in-progress quest on party page](https://cloud.githubusercontent.com/assets/1495809/16891679/1555a666-4b41-11e6-9110-004d38780ce5.png)

**Quest Completed pop-up:**

![4 - quest completed pop-up](https://cloud.githubusercontent.com/assets/1495809/16891682/1bbab0f0-4b41-11e6-8f92-c41870f75f68.png)
##

**Comment by colegleason** [comment]
So should it just be awarded to the party leader? Or the person who started
the quest?

**Comment by deilann** [comment]
Person who started the quest.

**Comment by DanielTheBard** [comment]
@colegleason - I think it should be awarded to the person who started the quest. Probably more reliable that way, too. If they just started the quest, then it's unlikely they've gone missing. Party leader might be away while the party is doing the quest, stopping them from continuing.

**Comment by deilann** [comment]
Party leader might also be too low level to start the next quest.

**Comment by deilann** [comment]
Also also, I don't like the idea of items you've earned going to someone
else. What if you wanted to switch parties?

**Comment by ghost** [comment]
So what if the person who started Vice goes MIA with the next scrolls. Does that mean even though the entire party completed Vice they now have to do it over if they want to continue? Just because you started the quest doesn't mean you're the only one who "earned" the subsequent quests. If that was the case then why quest as a party at all?

**Comment by deilann** [comment]
Well, it's your scroll that you're sharing with your party. It dropped for
you, not your party. If you find after doing Vice that you're not a good
match for a party, should you be locked in with them to complete something
you earned? That seems ridiculous, especially considering that the members
of your party will get their own Vice scroll, but they're using yours.

**Comment by ghost** [comment]
I'm not quite understanding how you're stuck with your party after completing part 1 if everyone gets the part 2 scroll. Can you explain? Maybe I'm just not understanding how all 3 parts fit together to make this different from the Trapoer Santa two-part quest.

The whole party may have the scroll drop but only one person can use it so it's not necessarily true that the rest of the party should be beholden to you just because you happened to use your scroll when it could just as easily have been someone else's that was used (5/7 of my party had the scroll drop).There has to be better way than to make everyone beholden to one person in the party.

**Comment by deilann** [comment]
The issue with the entire party getting the next scroll is that you end up
with partynumber^2 Vice pt. 3 scrolls out of 1 Vice scroll. That's just...
really off.

**Comment by ghost** [comment]
Can you get the "prize" that many times? It would seem the way to limit things would be like Trapper Santa where you can only get the mount/pet once. Or to limit the number of times a player can do a quest rather than hope the player who happened to use their scroll doesn't fall of the face of the Earth before part 2 or 3 (already had that happen with one party member). Or have the Vice scrolls disappear for everyone who participates in part of a quest if you only want people to do it once.

**Comment by deilann** [comment]
You can continue to redo the quest and you could just do part 3 with a new
party who hasn't done part 1 or 2. I understand it's tough that you would
have to redo part 1, but considering you get a version of the scroll for
free yourself, it's not like you're being locked out of doing it.

**Comment by DanielTheBard** [comment]
@Anysia - Uhm yes. This actually definitely needs to happen. Working on a gen 2 pet quest right now that is a 2-parter. It would create all kinds of problems for the quest if everyone got a copy of the second scroll. It'd also be the easiest set of pets to get since you'd only need to buy it once or twice.

**Comment by ghost** [comment]
The description of Vice did not sound like a pet quest (I was under the impression that those didn't drop and could only be bought and were a separate type of quest).

It seems that the fact you can do part 2 or 3 without having done the previous parts is a bigger issue. If winning just unlocked buying the scroll rather than getting the scroll for everyone else that would at least mitigate the problem of party members disappearing with the key to the following quests. I'm not saying the original issue doesn't need solving. I'm saying the proposed solution creates unnecessary problems if a party member disappears (not flounces and leaves, but abandons Habit). Everyone else so far seems fine with this. So be it.

**Comment by DanielTheBard** [comment]
@Anysia - It doesn't create problems though. The person who initiated the quest should have the right to continue it? Either they earned it themselves by hitting lvl 30 or bought it with their gems. So they have the right to leave and keep their quest scroll. Everyone else has the same ability to earn that quest and initiate themselves.

**Comment by lorian** [comment]
Yeah, this problem actually occurred to me when we started the vice quest: as a party of 7 with 4 over 30, we'd definitely end up with WAY too many copies of the second and third step of the quest, to the point of absurdity. I support the next quest scroll only dropping for the original quest-scroll-user.

**Comment by lemoness** [comment]
Anysia, Vice is in fact not a Pet Quest. Daniel was referring to a different quest that he is working on.

I am also in favor of the quest-initiator receiving the next piece of the scroll.

**Comment by casicastiel** [comment]
Has this been worked on yet? My party just finished Vice 1 and we seem to have all received a copy of the second scroll (even though I am the only member with a high enough level to use it).

**Comment by lemoness** [comment]
As far as I know, it's intended, but none of the devs have had a chance to
fix it.

**Comment by Alys** [comment]
Apparently, there are DINOSAURS and I have only JUST now been informed. I will work on this issue.

And when I get my DINOSAURS, certain people will be sorry that they did not inform me sooner! You know who you are.

**Comment by Alys** [comment]
[Screenshots of proposed changes](https://imgur.com/a/cuRvK) to the various screens that show the rewards for a quest. Comments? Improvements?

This example is for Vice1. The same thing will be done for Vice2, Mundane1, Mundane1, and future chain quests.

**Comment by lemoness** [comment]
Looks good to me!

We'll have to be thoroughl about announcing this change so people don't
flood us with questions asking why they didn't receive their scroll rewards.

**Comment by Alys** [comment]
The code required for this is in https://github.com/HabitRPG/habitrpg/pull/4004 and https://github.com/HabitRPG/habitrpg-shared/pull/303

Ha! Look at the two numbers. 4004 and 303. I should get a present for that too.

**Comment by librarianmage** [comment]
@Alys Is this still a problem? I am fairly certain it is.

**Comment by Alys** [comment]
Yes. Waiting for API v3 though.

**Comment by Alys** [comment]
I've edited the first post here to add a lot of details about the previous work that has been done.

**Comment by Hus274** [comment]
I'll look into this.
