### ISSUE TITLE
Clarify that silver is a tenth of gold [suggestion]

### ISSUE THREAD

**Issue by sveinns** [HabitRPG/habitica#273]
I found it confusing when I first opened HabitRPG, that the silver coin appeared to the right of the gold - it might as well be platinum or something. I suggest either of the following changes to help ease people into the interface:
- Make the silver coin a tenth of a gold coin instead, to emphasize the fraction.
- Have a tooltip on the coin and the text saying "silver: .1 of gold" or something to that effect.

**Comment by lefnire** [comment]
hmm, seems defacto in RPGs: [WoW backpack](http://images2.wikia.nocookie.net/__cb20091228031804/wowwiki/images/b/b1/Backpack.png), [GW2 items](http://median.gw2forfree.com/2012/11/GW2-Gold-Guide-1.jpg). Maybe if I included copper. Tooltips not a bad idea though.

**Comment by sveinns** [comment]
I agree. But the backpack has the copper, which clarifies a bit. Maybe we should add copper and lessen the numerical error in rewards? :-P Maybe the silver can be a bit smaller, so as to emphasize its relative value to the gold? Both the gold and silver seem a bit dull right now, maybe making the gold a bit shinier would help?

**Comment by wc8** [comment]
[Tooltips](https://trello.com/c/Mv1yqQbP) in general have been requested. I added a note for showing coin value tooltips. 
Slight size adjustments and/or introduction of copper seem helpful, if not too difficult to implement. 
Note: the value question has come up before #192.

**Comment by ghost** [comment]
Maybe use the loz style of monetary progression? I think would add to the rpg nature of the app.

**Comment by StanLindsey** [comment]
@neohuman - what is the this loz you speak of?

**Comment by ghost** [comment]
Legend of Zelda

**Comment by StanLindsey** [comment]
I forget the way Legend of Zelda does currency... care to explain?

**Comment by ghost** [comment]
Green Ruby is one and so on and so forth. We start with a green coin and
move up from there.

**Comment by lefnire** [comment]
Sorry to kibosh, but we're gonna stick to gold silver copper. just need to
fix silver to 100 instead of 10, and add copper

**Comment by ghost** [comment]
Sounds good to me

**Comment by Pandoro** [comment]
![coin_single_copper](https://f.cloud.github.com/assets/1872333/116348/f013756a-6bf4-11e2-847e-99590fc18709.png)
![coin_single_gold](https://f.cloud.github.com/assets/1872333/116349/f012f95a-6bf4-11e2-8d03-bc2e01ee902d.png)

In case of need ^^

**Comment by lefnire** [comment]
@Pandoro to the rescue!

**Comment by CaBil** [comment]
I'm new, so I may have missed this detail, but from what I have seen, GP rewards can be listed as fractions when you complete a todo.  That defeats the purpose of the GP/SP split.  Rather than list a GP fraction, it should list it in the appropriate coinage.

In the announcement of the completion of the todo, you have the star symbol for experience, perhaps the appropriate symbol for the GP/SP/CP should go up also?

This may be a problem, but part of the joy/pain of being a PC is figuring just the hell what you are going to do with your coins.  I know people that have dumped tons of loot simply because it was all CPs, because of encumbrance rules.  Rather than automatically doing the conversions in the least possible coinage, perhaps have players lug around the coins as they are given, then make an upper limit for coinage you lug around, then get around that limit by first buying a coin purse to increase your coinage load, then other mechanisms as needed.  So that players do tasks to earn ways to keep all of the cash that they have earned....

**Comment by Pandoro** [comment]
For this see also issue #51 Maybe we can close one of them to reduce the duplicate posts?

**Comment by StanLindsey** [comment]
Agreed @Pandoro

**Comment by lefnire** [comment]
vote this card if we want copper added: https://trello.com/card/add-copper-to-gp-system/50e5d3684fe3a7266b0036d6/225
