### ISSUE TITLE
Rebirth count only increases when your level is higher then previous Rebirth

### ISSUE THREAD

**Issue by marcelosizer** [HabitRPG/habitica#2742]
When you use the Orb of Rebirth if your level is lower then your highest Rebirth level the Rebirth count won't add up and no modal will show up.

(cc @SabreCat)

**Comment by DanielTheBard** [comment]
@Sinza- I think this was intentional. Because if you had an ultimate gear or beastmaster achievement you could keep spamming Rebirth at lvl 1. Which is cool money-wise for the site, but stupid if racking up badges. If it is intentional, maybe it should warn you though?

Though, if it is intentional, kinda sucks if you rebirth at 100 because... will it give you a badge ever again for rebirthing?

**Comment by marcelosizer** [comment]
@DanielTheBard you lose badges when you Rebirth? About the level 100 I believe @SabreCat fixed it to give you the badge once you used Rebirth on level 100 again.

Anyway, what I meant was that when you are able to use Rebirth again it doesn't add up. Let me use what I got on my local install as an example:

I had a character up to level 60;
Then I used Rebirth;
Then I leveled up to 50;
Then I used Rebirth again;

That second Rebirth got me back to level 1, but didn't pop up the modal saying that I was Rebirth neither added to the Rebirth count. I just remembered that Sabrecat said his intention was to add to the count only when you overcame your highest Rebirth level. Is there a way to give you the achievement only when you overcome your highest level but count how many times you used Rebirth? Like `2x Rebirth achievement; 10x used Rebirth`

**Comment by DanielTheBard** [comment]
@Sinza- You lose badges when you Rebirth? Huh? No you don't. Or at least I didn't. I was saying @SabreCat intended to only add to the count when you overcame your highest Rebirth lvl because Beastmaster and Ultimate Gear also allow you to use the Orb of Rebirth, right? So you could Rebirth before lvl 50. And could theoretically keep Rebirthing if you have either of those badges. (stupidly money-wasting as it would be)

**Comment by marcelosizer** [comment]
@DanielTheBard but you don't need to overcome highest Rebirth level to be able to Rebirth again, you only need to overcome level 50. That's why I want to know from @SabreCat if it's possible to make a count for Rebirth achievements and a count for number of Rebirths.

**Comment by DanielTheBard** [comment]
@Sinza- I realize that. It wasn't really the point though.

**Comment by marcelosizer** [comment]
@DanielTheBard didn't get it then. =p 

The Beastmaster and Ultimate Gear achievements don't come into account after you have used Rebirth or only if you've already had them?

**Comment by SabreCat** [comment]
It's intentional that the achievement doesn't stack unless you beat your previous level, for the reasons @DanielTheBard mentioned. I think that's even mentioned in the modal that comes up when purchasing the Orb (though it's such an information-dense thing that I could understand someone overlooking it). Achievements are meant to recognize a notable accomplishment, and having it be stackable via "spamming" Rebirths seemed kinda silly to me.

That said, when I first came up with Rebirth, it was at a point in the game where attaining Ultimate Gear or Beastmaster was really as far as you could go--there wasn't much to do after that point. Now that we have four classes and an ever-growing collection of quest content, those probably make less sense as unlock prereqs. Should I strip those out and have it unlock strictly at level 50, then on successive playthroughs unlock only after you've surpassed your previous Rebirth level? Or take out the "go farther" idea entirely, unlock at level 50, and let you stack it however many times you like from there?

**Comment by marcelosizer** [comment]
I agree with leaving only level 50 as unlock method to Rebirth AND as counting the _achievement_ only when you surpass the highest level. My point since the beginning is that you should be able to see how many times you've used Rebirth as a separate way as the number of achievements you got from Rebirth. I think I'm not expressing myself very well =/

What I wanted to see was:

You've begun a new adventure! This is Rebirth **10** for you, and the highest Level you've attained is **60**. You've got this achievement **4 times**. To stack this Achievement, begin your next new adventure when you've reached an even higher Level!

What do you think?

**Comment by SabreCat** [comment]
Ah, I see. So for your example, in your profile it'd say "Began 4 New Adventures." And the only place you'd see the actual number of Rebirths is in the popup immediately upon buying an Orb?

If so, I get what you're after, now. It'd take a database migration for it to even work... or wait, I could give the Rebirth op a special handling for nulls. OK, I'll assign myself.

**Comment by marcelosizer** [comment]
Yup! Cool, thanks! =]

**Comment by deilann** [comment]
Yeah, the gaining Rebirth upon Ultimate Gear, now that it counts rogue
gear, is a little crazy. (Suuuper easy to gain all the rogue gear as a
rogue because well, rogue.) Without really trying, I unlocked Rebirth
somewhere in my mid-thirties.

**Comment by lemoness** [comment]
Can put this in a different thread if requested, but just received this message on Facebook: "Just did my first Rebirth at lvl 105. But the achievement says lvl 100. Guess that's okay. Still came a long way and will do it again."

**Comment by deilann** [comment]
Yes, it will always say 100 if you did it higher than 100, as users
shouldn't have to beat levels higher than 100 in order to stack the
achievement. That was specifically requested when I coded it. If you look
at the wording of the achievement, it says "after level 100" or something
like that, which I feel is appropriate.

**Comment by lemoness** [comment]
Good to know!

**Comment by SabreCat** [comment]
Hmm... what that user said makes sense, though. All we'd need would be to allow the achievement to stack regardless of level post-100, but update the highest-level-achieved counter independently if they've topped it.

**Comment by deilann** [comment]
We could do that. What I did was quick and dirty.
