### ISSUE TITLE
Have a ticket be landing page for "Report a Problem"

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2753]
I highly suggest creating a ticket that explains how to search issues on Github (and possibly links to some of the bigger known problems on the moment) as the link to "Report a Problem" on the site. This would reduce the number of dupe tickets, and therefore the amount of time spent going and closing them.

Thoughts @lefnire @colegleason @Sinza- @SabreCat, the folks I see closing tickets most often?

**Comment by paglias** [comment]
We should think abou opening a public board where users can report bugs outside of Github and move them here if they aren't duplicates or similar, or keep Github for everything but screen every single new issue because we're getting to big numbers (almost 500 open issues) but probably most of them can be closed or marked as duplicates

**Comment by marcelosizer** [comment]
There is a forum but it's not used: http://habitrpg.wikia.com/wiki/The_Keep:The_Dungeon

**Comment by deilann** [comment]
@paglias There will not be 500 issues later today.

@Sinza- I'm aware of that, but like the Trello card, a lot of people coming to github don't know how it works. So really, less than the "known issues" thing, I want it to say "HEY THERE IS A SEARCH BAR. MAYBE USE IT?"

**Comment by paglias** [comment]
@deilann ahah great! let's make so we don't have to do these close-the-issue marathons again

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/commit/908a5a2408b96e60986ecc48c42c0d6037cab489

**Comment by lefnire** [comment]
Currently [this](https://www.evernote.com/shard/s17/sh/53e88fbb-908c-450c-b4ca-addd0dc15841/72bf40c82973123628064b359090d2c2) points to [this](https://github.com/HabitRPG/habitrpg/blob/develop/CONTRIBUTING.md), but people are ignoring it. Possibly because it says "contributing guidelines". Should we:
1. Use @deilann's ticket, point tavern (& all other external "report a bug" links) to it?
2. Copy @deilann's text into the contributing text, and do the above?

**Comment by deilann** [comment]
I pointed the Tavern to the ticket. I don't think people are going to click
it. I think it needs to be text that shows up immediately.

**Comment by deilann** [comment]
(The commit was made to develop, jsyk.)

**Comment by lefnire** [comment]
kk
