### ISSUE TITLE
Inn Issue

### ISSUE THREAD

**Issue by somnabulist** [HabitRPG/habitica#2800]
I was in the inn for two days. I was not on any quest. Then after firefox crashed, I reloaded to get the message that my character was dead. That said, and looking over another issue, it also seems relevant that I loaded my character on the ios app. It seems connected to other issues, but not quite enough to confidently comment there.

**Comment by deilann** [comment]
Hey that sounds like it was a #2601 -- you weren't in the inn at all; it didn't save to the server. If this happens again, please let us know.

**Comment by amazuonna** [comment]
Hi!
So I checked into the in maybe a week ago as I'm traveling. I happened to get online today and check habitRPG and I noticed that sometime in the past 24 hours I apparently got checked out of the in and because I didn't do my dailies and for some silly reason was on a quest, lost 63.7 health and died.
Any thoughts on what might've happened?
My user ID, in case you need it: 2f6f0406-8bc5-4619-8f85-0fbb99ef0ce5

**Comment by deilann** [comment]
Most likely you never actually checked into the inn, server side. After
taking an important action like checking into the inn, it's always a good
idea to sync to make sure your request went through.

**Comment by amazuonna** [comment]
But what confuses me is that the party log for the past week only shows other members doing things, and there was no damage before yesterday—If I never checked into the inn, why didn't the damage happen right away, but only 6 days later?
Also, what am I supposed to sync? I'm only using habit RPG on one device.

**Comment by deilann** [comment]
Because cron doesn't happen until you log in. So if you don't log in, it's
not going to trigger cron, and therefore do no damage.

And like I said, you need to sync with the server. It has nothing to do
with using multiple devices. There's a button on the toolbar that does
this. It may be that you made a local request that didn't save to the
server. So it looks like you're in the inn on your local device, but it
never saved to the server. Syncing with the server will fix that.

**Comment by amazuonna** [comment]
Thanks so much!

**Comment by deilann** [comment]
no problem! You might also be interested in Alys' tool:
https://oldgods.net/habitrpg/habitrpg_user_data_display.html

Because it pulls its data from the server, you always know if it's
accurate. :)
