### ISSUE TITLE
Marketing to Meet Kickstarter Goal

### ISSUE THREAD

**Issue by Pandoro** [HabitRPG/habitica#282]
A little suggestion my girlfriend came up with.You implemented the female avatar type, but people who are not on kickstarter, or active around here, will not notice this at all. 

Neither will they notice any other changes unless of course they are obvious. It  might be a good idea to make a little pop-up that lets people know about innovations, or maybe just put it in the green header bar, next to the kickstarter, bug fixes and group feature advertisement. 

Just to make it clear, I don't want to do this because of me making the girl avatars, I just think this might be a good idea in general, especially after seeing the two reactions on the kickstarter post about it ^^

**Comment by StanLindsey** [comment]
I concur, if you visit HabitRPG when logged out there is a little bar that advertises the Kickstarter. Personally I think that whilst the Kickstarter is so important we should keep that even for logged in members as well as using it to promote new features.

**Comment by horusofoz** [comment]
- Links to Trello cards for the more exciting features that are most likely to be introduced features when KS reaches it's goal.
- Links to articles from some of the more popular publications that wrote up during the Reddit Rush period.
- One liners from users about the product e.g. "I've never been more motivated to GTD. Exercise, productivity, developing good habits and nixing bad ones. HabitRPG is shockingly that good".

**Comment by horusofoz** [comment]
- More imagery on the KS page showing the female sprites, armour sets, even just concept art.
- On the KS page, links to Trello cards for the more exciting features that are most likely to be introduced features when KS reaches it's goal.
- Also the one-liner reviews about HabitRPG as above on KS would be good.

**Comment by Pandoro** [comment]
Considering we are speaking about publicity. @lefnire have you tried to submit habitrpg to makeuseof cool websites and tools? http://www.makeuseof.com/contact/

I think this is specially targeted at the makers of a website, otherwise I would have sent them a mail myself ;) \

EDIT: I went ahead and figured, screw this, it's not my site, but I can give it a shot! Let's see if it gets through, they do have a rather big queue!

**Comment by lefnire** [comment]
Most new features will have a pop up when unlocked (eg, parties), but for
those that don't (eg, female) that's a very good idea.

**Comment by lefnire** [comment]
I'll check into makeusof . I'll revisit this ticket soon as I sit down to
do some marketing, on the road for a bit - thanks for the suggestions guys!

**Comment by horusofoz** [comment]
The rewards of a quick Tweet :) http://t.co/sYJvGNFs

**Comment by Pandoro** [comment]
Nice :D 

As I said, I also submitted it to their cool websites and tools list and commented on a similar post about habit tracking tools lately. I never thought they'd feature habit rpg this soon :D What was your magic tweet ^^? 

It doesn't seem to appear in their main rss feed though :( But let's hope this still gives us a nice publicity boost!

**Comment by horusofoz** [comment]
The tweet wasn't anything special. Here's to hoping we see a nice boost on KS :)
![Image 6](https://f.cloud.github.com/assets/3202339/120774/606b7c5a-6d2f-11e2-9c1d-bcd1550394a7.png)

**Comment by Pandoro** [comment]
Hmmmm according to the article, it has been there since Januari 30th :x

Does that mean they already added it before the tweet :o ?

This however does also mean that it's been there for 3 days now and the
effects haven't been noticeable on the kickstarter project yet :(

**Comment by horusofoz** [comment]
<redface> I didn't see that. Theresponse led me to assume it was posted following my tweet. My Bad </redface>.

Now how to get some $$$$ heading to KS?

**Comment by Pandoro** [comment]
Don't get me wrong ;) I didn't want to attack your assumption in any way.

The thing that worried me was the fact that there wasn't a noticeable
effect yet :( This might still come up, but at the rate that Makeuseof
keeps spitting out new posts, I doubt that this will randomly happen after
a few days.

How to get it rolling is really a good question. I've been breaking my head
over this since the last few days. My "internet presence" is by far not big
enough to influence this in any way x) And I think any major site will
notice if I follow them NOW on twitter, and tweet that they should check
out habitrpg. Apart from the fact that they'd soon notice I have been
tweeting this to every major geek-tech-news-site.

I've even thought about hanging little posters around campus with habitrpg
links, but I think that I myself wouldn't be motivated to start playing
some random game just from a link on a piece of paper ^^;

**Comment by Pandoro** [comment]
Hmmm, I thought I'd do a quick post on the reddit, but somehow it isn't showing up, does anyone of you see a new post? 

I've never posted there before... so maybe I just did something wrong :-/
my post is here: http://www.reddit.com/r/habitrpg/comments/17r24m/a_small_update_about_habbitrpg/

How to get it to there: http://www.reddit.com/r/habitrpg/ ?

**Comment by ghost** [comment]
I tweet daily about habit https://twitter.com/wesleypennock and try to tell as many people as possible. If each one of us tweeted about habit on a daily basis traffic would sore.

**Comment by StanLindsey** [comment]
I had issues postitng threads on our reddit, I'm not sure what that is. I've posted elsewhere on Reddit but I'm not knowledgeable on Reddit at all. I assume its a limit on new accounts.

**Comment by Pandoro** [comment]
Guys, ....

This might be a bad or a ... well extremely bad, or rather cool idea. Should be jump onto this train? 

![grumpy](https://f.cloud.github.com/assets/1872333/121174/19772f4c-6d7a-11e2-8629-474325ce8855.png)

We could ask the site for permission to use grumpy cat it in the game as a pet . Knowing them they will host it on their page and this... well might lead to another bit of traffic.

**Comment by lefnire** [comment]
omg. Tard. That - is - awesome!

**Comment by Pandoro** [comment]
I knew something was wrong :-/ The face was too long. Fixed!
![grumpy2](https://f.cloud.github.com/assets/1872333/121300/266c38d2-6d84-11e2-8d9b-e7fceb2ad1fb.png)

So you think it is a good idea?

**Comment by horusofoz** [comment]
That's sweet. I can easily see myself or other chucking a RL buck for that. As long as i get to name him/her :)

I think an entire line of feline pets could be possible. Such as lap cat>grumpy cat>street cat>bob cat>marbled cat>golden cat>caracal>leopard>Puma>jaguar>snow leopard>Cougar>clouded leopard>Lynx>panther> tiger>lion>tigler>liger>sabre toothed tiger.

These could be upgraded through XP or purchase.

The extended cat range of feline pets is a down the track  idea.

Nice work.

@Pandoro I thought you hadn't done pixel art before. You're showing an acuity for the style :)

@lefnire I think adding this and the other sprites Pandoro has put together on the KS page may add to donations.

**Comment by Pandoro** [comment]
@horusofoz  although I like the idea, this will be one hell of a lot of work to realize, apart from the fact that with the limited amount of pixels, It will probably hard to realize the fine differences between some of these felines ;) I'm not dismissing it, but I guess for the KS a general bigger variety of different pets will be easier to realize :)

I went ahead and asked the guys over at the grumpy cat website for permission to use it in a nice mail. Hopefully they will reply. Until then I would refrain from using this in a public sense. I'm not sure, but according to their website grumpy cat is a trademark. I'm not sure what problems you can get into for using that to draw publicity to your work :x

**Comment by horusofoz** [comment]
@Pandoro Any word back from Grumpy Cat?

**Comment by Pandoro** [comment]
Sadly nothing yet :( I'm beginning to wonder if I sent it to the right
person, but so far nothing :-/

In fact I wonder if we can just use it, without saying OMG THIS IS GRUMPY
CAT! But considering I sent the mail, now they know it.... sooo :-/

**Comment by horusofoz** [comment]
Do they have a Twitter account? Gets the quickest response in my experience.

**Comment by Pandoro** [comment]
@horusofoz I tried that as well after you suggested it. But I only asked if they got my mail. Maybe I should have asked just again. Slowly I'm starting to wonder if I just sent it to their shop mail address, which might be handled by completely different people.

**Comment by lefnire** [comment]
I added Alex's sprite-sheets to the Kickstarter page. I'll add quotes and press-releases to the splash page soon. Tweeting is only useful if you have a solid following, or are tweeting at a salient profile. What we really need is guest posts on [these major websites](https://docs.google.com/spreadsheet/ccc?key=0AurKa4-KGKIvdGtFZUVHQmNkWWNZOFYwLTh4M241ZUE#gid=0). Reddit and Lifehacker brought the majority of money to the KS, there was also a recent surge from Facebook (meaning some lovely fan is popular, and caused a viral effect). Kickstarter & in-app updates are only seen by the backers / users, who already believe in the app. I've found that each update blast (female avatars, Alex's art, party system) causes a handful of people to up their pledges, but since it doesn't target new audiences, it doesn't bring new users. We've gotta get on websites somehow.

The only thing I can think of is submitting guest posts to these sites. I actually submitted to Lifehacker, dirty little secret. I didn't know they'd pick it up so soon, I figured I had time to fix the bugs while that article worked it's way up the stack. But that goes to show that anyone can submit to these sites, as long as they either (a) have a guest-post feature, or (b) you can find a contact on the site to say "hey, thought you might be interested in this". So if anyone has an "in" or is willing to submit guest posts, [here's my template](https://docs.google.com/document/d/1RsovQl8l-4v7eQPaPh0GRqYfAGThBQ6HETCx4lhvyes/edit?usp=sharing)

**Comment by lefnire** [comment]
@hookang in case you're interested

**Comment by ghost** [comment]
@lefnire I will submit that to every relevant blog I know about. Plus any development blogs I can think of.  I am also tweeting any relevant startups, developers, and general techies I can think of.

**Comment by wc8** [comment]
It might be good if some of us can write use case examples, perhaps with pictures like @SlappyBag's of his daily list. I have no twitter followers, so I haven't tried tweeting. 
Would reddit be a good place to post tips, tricks and jerryrigs? Something like that might pique people's interest and maybe broaden appeal.

**Comment by ghost** [comment]
We could all create posts about how habitrpg has changed our lives for the
better including images. Maybe even a youtube series of walkthrough by all the main people of habitrpg?

**Comment by lefnire** [comment]
Totally. Don't post to the /r/habitrpg, because that's only being followed by us. post to /r/LifeProTips/, /r/GetMotivated, /r/GetDisciplined, etc. LifeProTips is the best for this topic. And Reddit thrives on re-posts, unlike the other sites, so no worries that we've already been featured there. Also, LPT is all about rigs and hacks, so that makes "workarounds in habitrpg" extra useful.

Keep an eye on other productivity blogs. Lifehacker, 43Folders, TechCrunch, ZenHabits - as well as gaming sites, and things like PennyArcade. We don't want to just post willy-nilly there, one guest-post submission per site will suffice. However, we want to comment on any salient posts that surface on those types of blogs. Only salient posts, things about productivity + gamification, etc. So for example my comment on [this article](http://lifehacker.com/5975824/gamify-your-life-a-guide-to-incentivizing-everything) got us a lot of traction, because it was topical. But I've commented on other, less pertinent articles, which got me banned as a spammer.

**Comment by ghost** [comment]
@lefnire I just asked a couple of my blogger friends if they could do a post about habitrpg. Only 2 of them did I send that template. I will prefer to cold email or cold comment because it doesn't seem like a marketing campaign at that point. It seems like people showing off an awesome product and I prefer that.

**Comment by lefnire** [comment]
Fair enough, to each their own style - just throwing out some pointers.

**Comment by Pandoro** [comment]
How likely would it be that lifehacker would do some kind of update post,
telling how awesome we have been doing?

**Comment by StanLindsey** [comment]
http://www.reddit.com/r/LifeProTips/comments/181ywv/lpt_timeblock_your_day_with_habitrpg/

**Comment by wc8** [comment]
http://lifehacker.com/5982195/show-us-your-to+do-list 

I haven't added mine yet, but the post seems to have a few comments from users using the same application, so it seems if the todo list includes a picture of one's own todo list and a personal use case scenario, it won't hurt if a couple users comment about the same app. 

(Yes, it is important not to get HabitRPG perceived as spamming—negative press won't help.)

**Comment by lefnire** [comment]
Oo, add yours that seems perfect!

**Comment by lefnire** [comment]
I jumped the gun and posted, sorry :)

**Comment by wc8** [comment]
The order of my daily's got messed up and now rearranging them isn't saving—not the best picture. I'll hold off until I can get it straightened out.
