### ISSUE TITLE
Gold sword broke and died!

### ISSUE THREAD

**Issue by Babychick82** [HabitRPG/habitica#2820]
I've been on habitRPG for a long time. I went to check off one of my todo's list and it said my Gold sword broke-which I do NOT have equipped and it said I died. I was supposed to level up and instead I went down a level. My username is Babychick82

**Comment by brightbold** [comment]
Are you in a quest? Checking off a task will trigger a sync with the server, so if someone in your party had just logged in and their damage to the party registered, you would lose those HP the next time you checked off a task. That can kill you and it seems very random, since it's not obvious why you're suddenly losing those HP.

As for the sword, currently the death mechanic allows you to lose an item from your inventory whether or not you have it equipped.

**Comment by deilann** [comment]
Furthermore, if it was close to your cron time, if you check something off, it goes cron before checking, so that could have triggered cron, killing you.

**Comment by Babychick82** [comment]
I bet, that is exactly what happened. It's happened to all of us in our party. Thank you

**Comment by Babychick82** [comment]
My HP was 50/50, and then checked off a task. Supposed to level up to 62 and died and lost over 5,000 coins and went to level 61.

**Comment by Babychick82** [comment]
No, it wasn't even close to cron time. Kelley told me what it was, which makes sense.

**Comment by deilann** [comment]
@Babychick82 You can get your GP back by going to Fix Character Values under settings. :)

**Comment by Babychick82** [comment]
Thank you!!! I had no idea!!
