### ISSUE TITLE
Signify Quest Mounts

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#2836]
Quest pets are now indicated separately and correctly, but quest mounts are not.

**Comment by deilann** [comment]
I think lorian put in a PR for that, but it hasn't been merged.

**Comment by quin-jay** [comment]
I don't think they have, actually. The only pet-related PRs I see by that person are **2803** (Changed pet/mount count in stats page to include all pets/mounts) and **2801** (Fixes beastmaster to not count gryphons)

(sorry for the longhand, I just didn't want this to turn into an official Reference on those threads because they're not actually that related.)

I might be able to do this, if no one else picks it up, but it most certainly won't happen before Wednesday.

**Comment by deilann** [comment]
The PR was merged, then reverted due to issues.
