### ISSUE TITLE
Put an icon or picture of dropped item into drop notification

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2852]
Split off from #2092.

It would be hella sweet if, instead of the simple "gift" glyphicon currently used in the drop notification, we would actually display what item dropped.

The pic could be full-sized, with minimal text (perhaps "You found an item!"), or scaled down to emoji size and retain some descriptive text.

**Comment by lefnire** [comment]
Some thoughts: I have a hunch full-size might be too big, but would be worth experimenting anyway. If we need to down-scale, I'm actually not sure how because of the following. We can use `background-size` + `width` + `height`. However, since we're on a spritesheet where we don't programmatically know the coordinates, determining `background-position` is gonna be hard/impossible. I'm not actually sure if it's needed, I've never attempted it before - and there could be a different approach to all this, just some brain-dumping

**Comment by paglias** [comment]
@lefnire for the coins icons which now use images from the spritesheet I've had to use `transform: scale(percentage)` to scale the image size. Background-size resized the whole spritesheet.
