### ISSUE TITLE
Rebirth does not allow the player to receive equipment quest scroll drops again

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2873]
Being reborn takes away the weapons you gain from Vice, but then when you hit level 30, you don't get another scroll.

**Comment by SabreCat** [comment]
I can fix this pretty easily. In the meantime, though, can you grab the weapons back from the Rewards shop once you unlock it? Quest weapons should get the same "purchase back after loss" treatment that limited-edition equipment does.

**Comment by deilann** [comment]
I don't recall seeing it as an option when I tested it.

**Comment by Alys** [comment]
Proposed fix: Adjust the rebirth code so that flags.levelDrops is set to {}. I.e., remove this from their data:

```
    "flags": {
        "levelDrops": {
            "vice1": true,
            "atom1": true
        },
```

Advantage: It lets the player experience this aspect of the game as a new player would (something I will want when I rebirth).

Disadvantage: Less likely that the player will use gems to buy these quest scrolls. However, since there's not much point to doing those quests more than once (a pet quest will give a bit less XP and GP but be easier to do), I think that few players would have bought these anyway.

**Comment by lefnire** [comment]
SGTM

**Comment by Alys** [comment]
Okay, I'll get this done in the next few days. @SabreCat be distracted by this [awesome cat product](http://files2.coloribus.com/files/adsarchive/part_493/4933405/file/friskies-pamper-cat-food-zen-small-89985.jpg) while I steal this issue from you.

**Comment by wildcate** [comment]
I used rebirth and now seem to miss pet quest scrolls (Vice scrolls are still there, though)...

**Comment by Alys** [comment]
@wildcate, I suspect that's a different issue, and probably not something that needs to be handled in GitHub. Could you please drop into the [Tavern](https://habitrpg.com/#/options/groups/tavern) and post there, so that I can see your profile? I'll help you there.

**Comment by Alys** [comment]
fixed in https://github.com/HabitRPG/habitrpg-shared/pull/307 (not live yet, but works well in testing and this issue can be reopened later if needed)
