### ISSUE TITLE
Windows App Development

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2885]
Currently, Habit has an iOS and an Android app. This ticket is for bounties related to developing a Windows app.

**Comment by negue** [comment]
Why I didn't see this Issue earlier? :smile: 

I am currently developing a Windows 8.1 App for HabitRPG.

Or are you (HabitRPG Team) already started on creating an App on your own?

**Comment by lefnire** [comment]
@negue because our mobile app uses Phonegap, we hope to eventually just add a WP8 release from that codebase. We've held off because people have had issues when attempting to use the Phonegap version, and we don't have much time to investigate - but the fact is that a WP8 app is basically 99% there, ready to go if someone can do some testing and deploy.

There is at least one unofficial WP app in the store. It has _really_ poor reviews. I know I've seen a lot of twitter activity, someone asking Qs about developing a WP8 app (was that you?) so at least one other is on the rise.

Anyway, that's just a dump of the current situation.

**Comment by negue** [comment]
I've have seen atleast two different persons here who want to create or already have an Windows Phone App.

Nope none of them was me 

My Target will be the Windows 8.1 Tablet / PC (no WP8 by me, since I dont have a device to test for it)

**Comment by lefnire** [comment]
oh, sorry - tablet/PC. Only person I know dev'ing a client is @fragmental , but competition is good! ;)

**Comment by paglias** [comment]
Ionic should support windows phone in future, don't know exactly when but I
read something about that
Il 25/ago/2014 21:00 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by fragmental** [comment]
Hello.  I'm using Unity, and I can build my client for desktop, including osx, linux, and all version of windows but I can't make a "Windows store app"(which includes windows 8.1 tablet and WP8), because the windows store app build target in unity doesn't support network classes.  Because it's lame.  

I have an account with the windows store, and can publish and sell apps, but I can't build for that target because of the previously mentioned problems.  There might be ways around it, but I'm not sure.

I also have visual studio 2013 pro with a windows phone emulator.

**Comment by akshay2000** [comment]
Has there been any update on this issue? I have been thinking of creating a port - especially since Visual Studio officially offers Cordova integration and supports WP 8.1 and Windows 8.1.

**Comment by negue** [comment]
There are currently these Apps available:

My HabitRPG Metro:
- Desktop / Tablet: http://apps.microsoft.com/windows/en-us/app/habitrpg-metro/bf3088cd-701c-4b2e-a765-7ee3adc30171
- Phone: http://www.windowsphone.com/en-us/store/app/habitrpg-metro/16136b45-3188-4c93-b6f1-da0b9e23ba4f

and also others for WindowsPhone
- http://www.windowsphone.com/en-us/store/app/habitrpg/3ce66e8b-811d-4701-b78b-b05fb766457d
- http://www.windowsphone.com/en-us/store/app/habitrpg-unofficial/e9d4bd28-9868-4b5e-a568-6f63510aa645

But sure why not :)

AFAIK Cordova itself can run as a Windows App, but I don't know if Ionic (our Mobile Frontend) runs on Windows Phone

Edit: If you HabitRPG Mobile running via the Cordova Integration in Visual Studio, please tell me how... kinda dont worked for me

**Comment by akshay2000** [comment]
You're right, @negue - Ionic doesn't support Windows Phone yet. Sadly, it also looks like they don't have immediate plans to support it. In that case, I think I'll stick to the third party alternatives. I wish one of those alternatives were open source, so that I could contribute and make them better.
