### ISSUE TITLE
Add Reasons for Leaving Group/Kicking from Group

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2898]
Need to add an optional text field so people can state why they're leaving a group or party leaders can send a message explaining why they're kicking someone out.
##

**Comment by paglias** [comment]
And also notification when a user is booted

**Comment by librarianmage** [comment]
Hasn't this been implemented?

**Comment by Alys** [comment]
We've implemented the ability for a leader to say why they've removed a player, but not the ability for a player to say why they've left the guild. Not sure if it's needed since they could post to party chat or PM the leader.  It might be more open to misuse for rude complaints about a guild.

I'm closing this but I have no objections if another admin reopens it.
