### ISSUE TITLE
New GUI Idea

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#290]
This is just some random idea I had but I think it has potential. Why not use a circle, allow me to explain. Put the avatar dead center of the page. Top is habits right is daily bottom todo left is reward. Everything is in a circle around the  avatar. You are the main point of habitrpg in other words. Both figuratively and literally. I have never heard of someone doing that and it would be a challenge. It would be interesting to say the least. Background is the dungeon,area,world,whatever. Just throwing this out there. Any thoughts?

**Comment by lefnire** [comment]
I'd rather keep it as is. There's a lot of GUI alterations we'll make to accomodate new features over time, but I think this poses a pretty unusual user experience. If this idea gets a lot of votes I'd consider it.

**Comment by lefnire** [comment]
Another thought Wes: some of your ideas are pretty different from Habit standard - what do we think of forking Habit? It would be nice to make the project fork-friendly, so that if a community of users prefer the Wes way (rupees, circle-gui, reactive tasks, etc) there's a shard to support that - `wes.habitrpg.com`. It would be a bit DIY (you'd build those features into your fork), but food for thought.

**Comment by ghost** [comment]
Hmm very interesting food for thought but I don't think I would have support for it so nah. However when I start doing my own thing I would love to try this idea out. Closing it.
