### ISSUE TITLE
In the Inn, Gained Mana

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2914]
I'm in the Inn and while my dailies did not reset, at cron time, I still gained my daily allotment of mana.

**Comment by Alys** [comment]
I haven't noticed that happening in recent months, and it doesn't happen on my local install when I simulate day turn over. I'm thinking that it was either a once-off glitch or a bug that's been fixed in the months since it was reported, so I'm closing this, but if necessary @deilann knows how to reopen it and where to find me to lodge complaints. :)
