### ISSUE TITLE
Vacation mode

### ISSUE THREAD

**Issue by virgiliu** [HabitRPG/habitica#293]
I was away for the last few days and had no internet access. Because of this my character died due to the dailies not being checked. It would be nice if you'd allow the user to say when the dailies should reset or at least add a vacation mode so that dailies won't kill people when they don't have a PC near. 

Some other time I just forgot to come to the PC and mark the dailies as done even though I did then and that caused me to lose HP and it started making this game feel more like a chore than a self-improvement thing.

**Comment by Pandoro** [comment]
If you know that you aren't at your pc for a while, you can toggle the dailies. This can also generally be used if you only want dailies to occur for example once a week. These options can be found by clicking the little edit button on each daily. This of course isn't a solution, but for not it can be used to achieve the same effect. 

A vacation mode is already a requested feature which you can vote for here. [Trello card: Rest in Tavern/Vacation button](https://trello.com/card/rest-in-tavern-vacation-button/50e5d3684fe3a7266b0036d6/14)

There is also a popular feature request asking that people will be able to check yesterdays todos. [Trello card: Record Yesterday's Activity](https://trello.com/card/record-yesterday-s-activity/50e5d3684fe3a7266b0036d6/60)

And another feature request so that you can set the time at which the day changes yourself. [Trello card: Timezone & Day Start options](https://trello.com/card/timezone-day-start-options/50e5d3684fe3a7266b0036d6/15)

As for specifying reset dates for each task, I think this will not be very likely. Of course this might make the game feel a little like a chore itself, however without the incentive of a possible penalty, the whole thing boils down to a simple todo list which habitrpg is not trying to be ;) 

So feel free to vote for the features on trello, but considering all of these are very popular already, I think that there is a good chance these will be implemented once the Kickstarter goes through and @lefnire  gets more time to work on habitrpg :)
