### ISSUE TITLE
Additional lines for blurb and gems in translations

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2932]
1. User profile settings have a header "Blurb" and a grayed comment in the field below: "Blurb". Can we make 2 separate lines: e.g. "Blurb" and "Introduce yourself" or "About myself" - to make it more clear in languages that do not have an exact equivalent for blurb.
2. Gems is used in indication of how many gems you have e.g. "6 Gems" and as a title for the popup. Russian translation requires these to be separate lines because of the word ending e.g. "Самоцв.", "Самоцветы".

**Comment by oleg-sh** [comment]
This is really an issue for Russian and potentially a few other languages.

**Comment by paglias** [comment]
@GitHubSphinx do you need different versions of Gems when it is used as a title and when it expresses a quantitiy?

**Comment by oleg-sh** [comment]
@paglias yes, that's exactly what we want.
It would be even better if we could reorder like "Gems: %number%" so that we didn't have to use ugly shortenings like "самоцв." because the word has different endings for different numbers (1 самоцвет, 2 самоцветА, 5 самоцветОВ). But I presume this is a bit harder to implement.

**Comment by ghost** [comment]
@paglias 
It's been noted by other people too. Contraction is better to express quantity (or word order change is needed as oleg-sh said), but it doesn't look nice as a header of the popup
http://oi62.tinypic.com/2rr9zmf.jpg
