### ISSUE TITLE
Guild Message notifications even if I already left that Guild

### ISSUE THREAD

**Issue by MicioDelCheshire** [HabitRPG/habitica#2944]
As the title says.
I'm in a bunch of guilds. 
I just left one of them, but the new message notification system's always notifying me of new messages of that guild.

BTW: I'd like to see the option to choose which guilds should notify me, anyway.

**Comment by Alys** [comment]
I can't replicate the bug. I'm not getting notifications for any guilds that I've left. I think we have fixed this problem. I'm going to close this now, but if it's still happening for you, please comment here and I'll reopen it.

For your idea about choosing the guilds that notify you, could you please go to Help -> Request a Feature and suggest it there? That will let us assess the idea along with others related to guilds and notifications so that we can best plan how to improve the feature.
