### ISSUE TITLE
The "Company" column in the footer

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#2945]
I really don't know where is the right place to speak about this, however - I think that "Company" is a bit confusing, in my opinion this word has nothing to do to with the other links but "Privacy" and "Terms". Even in Italian sounds weird to find "features" under "company", I think nobody would expect it to be there...
##

**Comment by quin-jay** [comment]
Actually I think that whole footer could use a little makeover, now that I'm looking at it. Here are my thoughts on rearranging:

**Mobile** >> "Get HabitRPG for:"
- iOS
- Android
- Browser add-ons and extensions (currently there are 2 links to the same page, in different columns)

Also, since there's at least one official browser extension, maybe it'd be a good idea to link to that directly, rather than hiding it in a list somewhere

**Company** >> "HabitRPG" or 'official stuff' or something
- Features
- Privacy
- Terms
- Blog
- FAQ

**Community** >> "Make HabitRPG better!"
- ~_Donaaaate~ <3_~
- Submit a bug
- Request a feature
- Contribute to HabitRPG (and here would go a link to the wiki so people could learn about all the ways they can get involved with making Habit happen)

**Social** (stay classy, "Social" column)
- Facebook
- Reddit
- perhaps the G+ community that a few people have been talking about in the Tavern recently?
- any other social network-type accounts the head dev team has set up since this footer was last updated

The Kickstarter link brings you to the correct page, but you can't back the project there anymore, so what do we want to do about that?

I can't figure out whether the API link should go under the (currently-named) Mobile or Community headers because right now the link is dead (well, not outright, you have to follow it through another couple pages, but you end up on a page that says Access Denied). Anyone wanna weigh in on that?

**Comment by deilann** [comment]
Personally, I would wait to redesign the footer until the static pages are
finished.

**Comment by quin-jay** [comment]
Ah, good point. Anywhere I can find the status on that project? Besides pestering the lovely devs for answers, of course

**Comment by deilann** [comment]
It's chugging along! I need some more info for some pages, probably gonna
get some more copy banged out tonight.

**Comment by Atomk** [comment]
Usually API stuff goes in a "developer" section that is not always in the footer. Here on GitHub it is on the bottom because in this site they're all developers, and it is a "popular" interest. Maybe you could add a link in the page (in settings) where API tokens are, if you're planning to make the footer focus on the most important things..

I agree that "company" should really be replaced with "HabitRPG", it makes much more sense.

**Comment by librarianmage** [comment]
Are the static pages done?

**Comment by librarianmage** [comment]
@Alys Do you know the status of this?

**Comment by crookedneighbor** [comment]
The static pages are done.

**Comment by librarianmage** [comment]
I can work on the footer, then.

**Comment by Alys** [comment]
@MathWhiz Note that this issue is marked as "suggestion-discussion". Nothing has been decided yet and there's no approval to proceed from the staff.

**Comment by librarianmage** [comment]
Derp. My bad.

**Comment by librarianmage** [comment]
Should this be put on hold / closed because it will probably be changed by the visual redesign?

**Comment by lemoness** [comment]
The footer has been changed, so I am closing this ticket.
