### ISSUE TITLE
Only one task per column showing for challenge participants [$15]

### ISSUE THREAD

**Issue by hattieshoe** [HabitRPG/habitica#2947]
It used to be that when you clicked on a challenge participant, you could see the status of all the challenge tasks for that person. Now I can only see the first task in each column (i.e. the first to-do, the first daily, the first habit). This will make it difficult to judge challenges when choosing a winner depends on the status of more than one task. I noticed it 2 or 3 days ago and waited to see if it was just a temporary bug, but it's still showing up that way. I am using Chrome, if that's relevant.
##

**Comment by hattieshoe** [comment]
Updates: 
1. Same thing is happening in Internet Explorer.
2. I tried "export to CSV" (in both browsers) and the resulting file included only the first to-do (out of eight).
3. I noticed that a few people were showing a different to-do, still only one, but possibly they had re-ordered them so it was the first one in their list?
4. I checked several other challenges and this seems to be happening with all of them, whether they have many participants or just a few.
Hope that helps.

**Comment by RedRarebit** [comment]
Came here to report the exact same issue, with both viewing in-browser (Chrome here) and trying to export the CSV file.

**Comment by deilann** [comment]
Thought I posted here, but apparently I didn't. It's happened to me, too.

**Comment by deilann** [comment]
@lefnire This is showing up in the same time frame as these changes: https://github.com/HabitRPG/habitrpg/commits/9da5d4d6d4b71388a1c8249537a4bb3d7a9be82f/src/controllers/challenges.js

Can we revert for the moment, so they don't keep breaking challenges for everyone?

**Comment by meganstrickland** [comment]
I just put a $15 bounty on this, which I am happy to leave hanging around for the time it can get fixed _with_ the other changes to make challenges lighter.

**Comment by lefnire** [comment]
Just pushed a commit. It's not the real fix, and it doesn't help csv. Here's the scoop.

Turns out `$elemMatch` only returns the first elem matched in the projection. That's really stupid, I really don't understand why. [SO](http://stackoverflow.com/a/18546277/362790) offers an aggregation-framework alternative to return multiple items, if that works then that's the fix - I'm diving in now. 

Background: without using mongo to strip the non-challenge tasks from users, the whole user object is loaded into memory. For single user loads (per the fix above), this is not the end of the world (I still want a real fix, per above, but we can use this temporarily). For csv-export, it straight-up crashes the server. Reason is it has to load all participating user's full data into memory, wilddle them down, but by then it's too late. So we need Mongo to do the widdling, hence the `$elemMatch` attempt. This is also why closing some challenges crashes the server, we'll need a similar fix. So we can't push this temp fix for csv, we need the real deal. I'm looking into now

**Comment by deilann** [comment]
THANK YOU SO MUCH TYLER. This makes things twenty times better, even if it
doesn't fix csv. I'll be able to see who's completed what to dos by
clicking on their name.

I know a lot of folks who need to see all tasks also use an RNG and then
click on someone's name to see if they've done what's necessary and if not,
move on to the next person. So csv is useful, but this at least gives us
something to work with!

**Comment by lefnire** [comment]
Awesome. Will push with event tonight, gonna see if I can get the real fix
in before then

**Comment by deilann** [comment]
:heart: :heart: :heart:

**Comment by lefnire** [comment]
This is [attempt #1](https://gist.github.com/lefnire/9906282), but from what I've read if any `$unwind > $match > $group` pass returns an empty result, then the top-level result is empty. Aka, the gist works when a challenge has at least one of each type of task, but returns an empty user otherwise. Seriously, why does `$elemMatch` only return one projected element? I don't see the point in that? Docs: [aggregation](http://docs.mongodb.org/manual/core/aggregation-pipeline/), [$elemMatch](http://docs.mongodb.org/manual/reference/operator/projection/elemMatch/)

So... I think we'll have to use map-reduce, the last boss of MongoDB. In the mean time, I'll push the temp fix on standard view and revisit after vacay

**Comment by deilann** [comment]
Again, thank you so much @lefnire for looking at this before vacation.

**Comment by Eraldo** [comment]
One of these links might help:
http://stackoverflow.com/questions/18545950/mongodb-select-multiple-sub-dicuments-from-array-using-elemmatch
https://groups.google.com/forum/#!topic/mongodb-user/of9Fltr3OB0

**Comment by Sulfirh** [comment]
Oh, perfect, this place seems to be the topic I was looking for: something similar happened with the monthly challenge I launch for a few month (Clean the Dungeon). I couldn't see the daily task for something like half of the challengers, and it was quite complicated to select winners (there is a final to-do that help, but checking the streaks is sort of a double-check).

![capture d cran 2014-06-01 22 23 03](https://cloud.githubusercontent.com/assets/5315062/3143074/b2fdb5e0-e9e4-11e3-9f2e-b142b9b110ce.png)

The more annoying thing is that I'm not sure the winner was awarded: there was an error message when I ended the challenge, and now the broken-link message don't talk about any winner. (who was Tehc, by the way) :x: 

![capture d cran 2014-06-02 01 09 55](https://cloud.githubusercontent.com/assets/5315062/3143076/bb06600c-e9e4-11e3-8f9f-790acd49f3a5.png)

**Comment by deilann** [comment]
Sulfirh, do you use a theme/setting that hides completed dailies?

**Comment by Sulfirh** [comment]
Yep, yours in fact and... problem solved, thanks >_<
So, the only problematic thing is the winner: since his name doesn't appear in the challenge broken message, how can I be sure that he has been awarded?

**Comment by deilann** [comment]
I don't think he has. What I'd do, is put out an announcement in the Tavern
and put up a dummy challenge for him to join so he can get the gems and the
badge. You can even put his name in the title then edit it out before you
end the dummy version, so he sees it even if he doesn't check the Tavern.
How many gems was the challenge for? I'll refund you, as you probably lost
them.

**Comment by Sulfirh** [comment]
Oh thanks, that's some good idea ! I'll try something like this.
Since the gem reward was just one of them, that's not very important, but thanks ,)

**Comment by psyche643** [comment]
Hello!  I read through this thread and don't have the know-how to use the temporary fix on figuring out who is leading a challenge (since only the first line of data shows in the CSV).  Any suggestions?

**Comment by deilann** [comment]
The temporary fix is that you can now at least check manually from the
site. If you go to the challenge and click on the user's name, you can see
all of the tasks. The CSV only shows one, but the site shows them all.

**Comment by psyche643** [comment]
I see - so just to clarify, does that mean I can figure out who has been most consistent by clicking on each participant, one at a time, and seeing who has the longest streaks?

**Comment by deilann** [comment]
Yup! You can also click on the progress graph and see the task value.

**Comment by psyche643** [comment]
Okay, thanks very much!

**Comment by deilann** [comment]
No problem. :)

**Comment by Alys** [comment]
This seems to be fixed.

**Comment by Alys** [comment]
There was a commit by lefnire and others by @Verabird. We should work out who gets the bounty. Also, this was marked as a "critical".
