### ISSUE TITLE
Experience NaN/20 & Avatar Missing

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#295]
I am on Chromium Ubuntu 12.10(64 bit). I have closed and reopened the browser. I have reset and it's still there.
![HabitRPG Gamify Your Life](https://f.cloud.github.com/assets/3267747/121893/6660b3cc-6e0c-11e2-8d99-1c88c4b9fa17.png) I took the wrong image but earlier exp was NaN/20.

**Comment by StanLindsey** [comment]
Have you tried CTRL-F5ing to ask for the images again.

Also what are you reffering to with the Health NaN/20 bit? You'r health appears to be 50/50?

**Comment by ghost** [comment]
@SlappyBag let me try that and I meant exp. I know the image doesn't show it but it was happening earlier. Just did CTRL-F5ing didn't fix anything.

**Comment by Pandoro** [comment]
Gosh you are hard on yourself when it comes to rewards ;) Anyways, did you die? Or did the bug itself lead to these numbers? Or why are you level one with zero exp and money? Or is this a test account? 

I think it would be good to know if this is after dying, or if it simply is  problem that occurred randomly

**Comment by ghost** [comment]
I reset my account and this just happened. I cannot even use the thing at this point.

**Comment by Pandoro** [comment]
Ah! Okay, sorry, I misunderstood. With reset do you mean the reroll thing? Or is there some other way to reset?

But well... from the looks of it I guess Tyler will have to take a look at this then. Have you tried to see what it is like in a different browser maybe?

**Comment by ghost** [comment]
Reset the account. I have not used any other browser.

**Comment by lefnire** [comment]
The images are probly when the server goes down. I'm not seeing the NaN in your screenshot - your account still acting like that? Pandoro, you can reset the account from user -> reset (top right)

**Comment by ghost** [comment]
No I didn't capture the NaN screenshot but it happened. It is fixed now though.

**Comment by Pandoro** [comment]
Urg faceapalm.... sorry for the stupid question. I completely forgot about the reset button :x I get it now.

I could imagine that the NaN error appeared through some minor glitch on the machine learning side? Maybe a division by zero or an overflow?

**Comment by ghost** [comment]
Division by 0 or overflow is possible.

**Comment by Pandoro** [comment]
Considering it was affecting you exp, I would expect the error to either happen after you check a daily, todo or habbit. Did you buy any new items before this happened? Maybe the exp multiplier of a weapon isn't initialized correctly. Otherwise I figure the error could just spring from the machine learning part that somehow reduces the exp to a very small or large value depending on how often it was clicked in the past. Or it might be an uninitialised variable, but I'm not sure how Javascript handles this. 
I would personally exclude transmission errors, as I would hope that error checking is done on a lower level in the network stack.

**Comment by ghost** [comment]
No new items were bought and this just came up after I reset my account. Nothing had even been done yet.

**Comment by Pandoro** [comment]
Aah okay, I still got it wrong... I thought it happened and because it happened you reset your account... Sorry man, somehow I'm a little slow today -.-; 

Well in that case I don't really know, maybe some uninitialised variables in the reset code? But considering if you reset your account, the database etc. has to be modified, the error could have happened in many places I guess :(

**Comment by ghost** [comment]
Everything is working now
