### ISSUE TITLE
Instant Death on New Day

### ISSUE THREAD

**Issue by sirsavary** [HabitRPG/habitica#2957]
Today I woke and opened Habit to find that I had died, by a lot. Over the past few days I noticed I was taking more damage than normal from missing a daily. I kept taking around 22 damage each day and had to buy a health potion. It's worth mentioning that I am in a quest right now but I do not appear to be taking damage from that or doing damage to the boss.

Today I did not take 22 damage, I took 69. I died instantly and was pretty upset. I checked my dailies and noticed that many of them had their streaks reset to 0. I checked the quest page and saw that the boss did not damage me today.

I did not get any errors at all. Everything worked perfectly fine last night.

Edit:
UserID: 83bf7c90-b9aa-4acb-ae62-705eecf3ad94
Browser: Waterfox (64 bit Firefox)

**Comment by Bokononist** [comment]
I've been having this same issue. The last few days. I've had a few Winter limited items break as a result (oddly they still show up in my inventory). 

UserID:723e1fb1-8709-4177-bc7f-ed1fc82a7f8a
Browser: Firefox version 27.0.1

**Comment by sirsavary** [comment]
Just checked my inventory and I still have that item that 'broke' when I died.

**Comment by brightbold** [comment]
@sirsavary @Bokononist - There's an open issue for the item that is reported as lost on death being different from the one that is actually lost: [#2789], so if you check your inventory you will probably find that there are missing items, just not the ones you were told had broken. 

As for the main issue here, it sounds like you might be affected by a quest, but that there's something buggy going on because no damage is being reported. What, if anything, does it say on your party page about quest damage?

**Comment by sirsavary** [comment]
@brightbold The quest damage for the 25th did not show up until today (the 27th), same thing with the quest damage on the 26th. Damage on the 25th from the quest was 7.6. That was the day I took roughly 70 damage. I can confirm that I did lose an item. I was told I lost my dagger but I actually lost my Ski-sassin robes.

**Comment by scheidm** [comment]
Not sure if related. logged in on desktop and had full health. logged in using the mobile app, same day, instantly took full damage and died.

**Comment by sirsavary** [comment]
Just logged in a minute ago and took 45 damage even though I did all of my dailies. Checked the quest log and the Gryphon hit a 0 on me. Only debugging help I can provide is that I got a yellow alert bubble on the right side of my page with 'undefined' in it just below the health loss bubble.

**Comment by bree333** [comment]
I keep having this issue as well! Except I seem to be getting double the damage that the boss gives out, per person that he gives it out too. So I've died first thing in the morning every day for probably two weeks now.
User ID: 7e75ed15-7682-4d7f-8e23-8535d5c3327b
browser: chrome

**Comment by deilann** [comment]
@bree333 That's most likely this: https://github.com/HabitRPG/habitrpg/issues/2805

**Comment by bree333** [comment]
@deilann but it doesn't actually get counted. like, this morning, I got hit with 50.6 damage. The only message under party lists my team member dealing 7.5 damage, and the shadow wyrm dealing 25.3 damage to the party. they didn't list the damage twice, i just received it double.

**Comment by deilann** [comment]
It's definitely more related to that bug than this bug. We know where your damage is coming from, even if it's doubled. Also, can you refresh your party page, just to make sure it didn't show up twice?

**Comment by bree333** [comment]
I checked, it definitely didn't show up twice. Now it's showing my own damage done and damage received, but since my damage received was 15.3 it wouldn't make sense that it's that plus the party member. I occasionally get dealt these huge hp hits and die twice a day, so maybe i'll get hit with 30.6 damage later?

**Comment by deilann** [comment]
Oh, I just realized the issue here:

The shadow wyrm dealt 25.3 damage to the party.

But there are also your dailies to take into account. That's the missing
damage.

**Comment by bree333** [comment]
that really doesn't seem like the case, because I only missed doing 4 dailies. And this has happened even when I've completed all my dailies.

**Comment by deilann** [comment]
The damage you personally caused from Vice shows that you should have taken about 10 damage from your dailies. That adds up exactly to what you're seeing.

**Comment by Alys** [comment]
There's been quite a few changes to death and quests since this was logged, and some of the errors reported in here are either described in other issues (see links above) or have been explained as due to normal damage mechanics. So I'm going to tentatively close this, but we can reopen it if anyone is still experiencing repeated deaths that aren't due to quest damage.
