### ISSUE TITLE
Different Font Size for Latin and Non-Latin (Cyrillic) Text

### ISSUE THREAD

**Issue by oleg-sh** [HabitRPG/habitica#2963]
Hello. We received it as a feedback from Russian-speaking guild.

Since the default HabitRPG font doesn't support Cyrillic Russian (and others' who use it) texts are displayed with different font. Font sizes differ significantly:

![snapshot37](https://f.cloud.github.com/assets/1823612/2280481/895df072-9f8b-11e3-9e87-1da29cdd076f.png)

Whenever we have English and Russian text side by side it looks a bit messy.

**Comment by deilann** [comment]
I think the color is different too. Cyrillic looks like a darker black.
oleg-sh notifications@github.com wrote:

> Hello. We received feedback from Russian-speaking guild.
> 
> Since the default HabitRPG font doesn't support Cyrillic Russian (and others' who use it) texts are displayed with different font. Font sizes differ significantly:
> 
> ![snapshot37](https://f.cloud.github.com/assets/1823612/2280481/895df072-9f8b-11e3-9e87-1da29cdd076f.png)
> 
> Whenever we have English and Russian text side by side it looks a bit messy.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/2963

Hello. We received feedback from Russian-speaking guild.

Since the default HabitRPG font doesn't support Cyrillic Russian (and others' who use it) texts are displayed with different font. Font sizes differ significantly:

Whenever we have English and Russian text side by side it looks a bit messy.

**Comment by oleg-sh** [comment]
Duplicate of https://github.com/HabitRPG/habitrpg/issues/2956
