### ISSUE TITLE
Sync caused by creating new task makes edit mode collapse; can interrupt editing of checklist items

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2965]
I have 'open new tasks in edit mode' enabled, since I often add checklists to my To-dos. However, I've noticed that the sync that is triggered by creating a new task causes the task to recollapse itself sometimes — not all the time, though, and I think it may be only when there's a new chat notification that appears in the header. I'm not sure how those two things are related, but it's been happening a lot.

**Comment by lefnire** [comment]
Any time an update happens to the user object on the server, and your user
is told it needs to update (eg, you got a chat notification; your stats are
updated from the chrome extension; etc) this will happen. Not ideal,
leaving ticket open, but just background info.

**Comment by Alys** [comment]
This can also interrupt editing of checklist items, including removing some or all of the text that had been entered into a new, unsaved item.

The frequency of this problem can be reduced if you click the website's sync button before editing a task.

**Comment by khipkin** [comment]
Ping on this issue since this irritates me on a daily basis.

**Comment by Alys** [comment]
For the record, since this was just asked about in the Report a Bug guild, it can also be caused by anything else that causes a sync, such as casting a skill. Naesten ( 8041974e-1c29-400f-b19e-563e27c8d4dd )  wrote:

"so if you start to edit a task (for example, add a bunch of checklist items) but then cast, say, 'tools of the trade' while the task is still open for editing, you (can?) lose your edit in progress just like that.
If it's not practical to leave the task open while casting a spell, there should either be
A 'doing this now will abort your edit' OK/Cancel warning dialog
A 'save/discard/cancel' question dialog."

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
This should no longer be a problem on the new site, but if it happens again, definitely let us know and we'll open a new ticket to investigate!
