### ISSUE TITLE
Changing password bug

### ISSUE THREAD

**Issue by stemvork** [HabitRPG/habitica#3007]
Hi there,

If you try to change the password in-game, but use the wrong "old password", it will still notice "Password changed succesfully". It however does not change the password (luckily!).

Cheers,
Jasper

**Comment by Alys** [comment]
This code seems relevant:

$ grep -r passSuccess habitrpg/\* habitrpg-shared/*

```
habitrpg/public/js/controllers/settingsCtrl.js:          alert(window.env.t('passSuccess'));
habitrpg-shared/locales/en/settings.json:    "passSuccess": "Password successfully changed",
[snip other languages]
```

And in habitrpg/public/js/controllers/settingsCtrl.js (line 68+):

```
    $scope.changePassword = function(changePass){
      if (!changePass.oldPassword || !changePass.newPassword || !changePass.confirmNewPassword) {
        return alert(window.env.t('fillAll'));
      }
      $http.post(API_URL + '/api/v2/user/change-password', changePass)
        .success(function(){
          alert(window.env.t('passSuccess'));
          $scope.changePass = {};
        })
        .error(function(data){
          alert(data);
        });
    }
```

I'm wondering if /api/v2/user/change-password doesn't return success/fail correctly? But that is SO far out of my league that I'm backing away slowly now. :)

**Comment by ebiagogo** [comment]
It looks like the root of this problem is in public/js/app.js, specifically myHttpInterceptor isn't rejecting the promise correctly when there's an error. The fix is pretty simple but it has implications in other parts of the UI because there are several $http.post calls that have .error doing the wrong thing (handling the data instead of data.err). Related to this problem, the check for '400 range?' (also in public/js/app.js) is incorrect. It's checking if response <  500 instead of response.status. Again, not sure if this is going to cause any other unexpected problems. I'll have a look to see if there are any unit tests related to any of this...
