### ISSUE TITLE
Getting the drops when scoring a task via API

### ISSUE THREAD

**Issue by TastyPi** [HabitRPG/habitica#3012]
I want to be able to get the items dropped when a task is scored, but I'm struggling to find the information. I've managed to figure out, from looking at the source, that the _tmp field in the response will have a "drop" field when there is a drop, but I can't seem to find the format, and attempting to make a drop happen to see it is hard.

The documentation should have information on the format of the _tmp field, as I also notice it includes information on critical hits. Does it provide any other information?

**Comment by lefnire** [comment]
`user._tmp= {crit, streakBonus, drop}`. `user._tmp.drop = {text,type,dialog,value,key,notes,(some more)}`. At present our API is still a bit wild-west, so you'll typically need to dive into code. `user._tmp.drop` gets setup [here](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L1053), and the default drop attributes [here](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L505). Note-to-self to document this information when I get a moment, but if you beat me to the punch shoot us a pull-request. Would be super helpful for us, since it will be fresh on your mind
