### ISSUE TITLE
Our whole party died, but the quest keeps dealing damage....

### ISSUE THREAD

**Issue by kb-code** [HabitRPG/habitica#3019]
our party started the Vice Awakens quest.  Unfortunately, one member forgot to check all dailies, and everyone in the party was killed in ensuing damage.  However, we are all still dealing and receiving damage even though no one is alive to participate in the spoils.   Seems the quest should end if there is no one left to complete it!  We are keeping the quest open long enough to have this bug report investigated...
![unorthodox swords of marvelous sundry](https://f.cloud.github.com/assets/3348252/2345698/20b712ac-a539-11e3-9d9f-fa730498bc2b.PNG)

(my user name = kb)

**Comment by deilann** [comment]
Death mechanics for quests are not yet coded in. This is expected behavior. The quest will continue as before. No need to abort.
kb-code notifications@github.com wrote:

> our party started the Vice Awakens quest.  Unfortunately, one member forgot to check all dailies, and everyone in the party was killed in ensuing damage.  However, we are all still dealing and receiving damage even though no one is alive to participate in the spoils.   Seems the quest should end if there is no one left to complete it!  We are keeping the quest open long enough to have this bug report investigated...
> ![unorthodox swords of marvelous sundry](https://f.cloud.github.com/assets/3348252/2345698/20b712ac-a539-11e3-9d9f-fa730498bc2b.PNG)
> 
> (my user name = kb)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3019

our party started the Vice Awakens quest.  Unfortunately, one member forgot to check all dailies, and everyone in the party was killed in ensuing damage.  However, we are all still dealing and receiving damage even though no one is alive to participate in the spoils.   Seems the quest should end if there is no one left to complete it!  We are keeping the quest open long enough to have this bug report investigated...

(my user name = kb)
