### ISSUE TITLE
Cannot save challenge

### ISSUE THREAD

**Issue by atpunk** [HabitRPG/habitica#3020]
When creating a new challenge for the Tavern, the GEM value error messages are inconsistent. 

GEM value is 0:
- "Value must be greater than or equal to 1"

GEM value is 1:
- "Value must be greater than or equal to 0"

**Comment by wc8** [comment]
@atpunk FYI: gem value in the tavern has to be at least 1, so the first error message would be correct. The second one is a bug.

**Comment by ebiagogo** [comment]
To recreate this, the user has to have 0 gems (and if the user is the group leader, that group has to have 0 gems as well). When you create a new challenge for the HabitRPG group, the logic forces a min gem value of 1. However, since the user doesn't have any gems (and in this case, the user isn't the group leader so there are no gems available from the group), the max setting for that input field calculates to 0 (max="{{maxPrice}}" where maxPrize is calculated in challengesCtrl.js). When you try to save the challenge with a gem value of 0, you get the message "Value must be greater than or equal to 1" which as @wc8 points out is correct. If you set it to 1, you get the message "Value must be greater than or equal to 0", which is the bug.

It doesn't make sense to set the max on the prize input to 0. Maybe the fix for this is to update the page so that if the maxPrize is 0 the system displays a message explaining that there has to be at least one gem (from the user or group, if the user is the group leader) to create a challenge. Something along those lines but better of course.

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/pull/4836
