### ISSUE TITLE
Cannot cancel subscription

### ISSUE THREAD

**Issue by djmistak** [HabitRPG/habitica#3021]
Hi. I am trying to cancel my account (my credit card was stolen, and I need to use my new card for the account), but I cannot click on the "cancel my subscription" button. Someone help!

**Comment by paglias** [comment]
@djmistak wht does it mean that you cannot click it? Does it show an alert?

**Comment by djmistak** [comment]
It's there in front of me. Anytime I click on it, nothing happens.

**Comment by lefnire** [comment]
@djmistak can you see if there are any javascript errors in the console? (I can't reproduce the no-click bug). In the mean time, I'll manually cancel your account for you - what's your UUID?

**Comment by djmistak** [comment]
My user id is f07aca7f-4bad-4ad3-b1b0-1c0197c1f143

I, unfortunately, do not understand what you mean by "javascript errors in the console." I wish I were better with computers. Sigh.

For your diagnostic information: I tried in both chrome and safari to no avail.

Thanks for your help, all! I hope I'm able to resubscribe with my new card!

**Comment by lefnire** [comment]
Ok, I canceled the account - give that a peek.

**Comment by djmistak** [comment]
Great. And I was able to resubscribe. Thanks for all your help.

As a note, I was accessing the subscription page by clicking on the "donate" box at the bottom of the page instead of the "subscribed" button at the top. Perhaps the bug is when I try to access it through that route.

**Comment by lefnire** [comment]
Thanks for re-subbing! That sounds about right re: page access

**Comment by chornsby** [comment]
Also trying to cancel account in order to resubscribe using PayPal. (Stripe is cool but the foreign currency charge doubles the amount I have to pay per month...).

I've been trying by clicking the "subscribed" button on the top bar and then the red "cancel subscription" button. This produces a dialogue box asking for confirmation but when I click "okay" nothing changes.

I do want to keep supporting the site but I'd rather do it through PayPal to avoid my bank's transaction fees.

My user ID: db393d59-b0cc-41ee-998d-e1b7888a6eea

**Comment by lefnire** [comment]
Ooo, good bug find. Fixed! Can you try again and tell me if it works?

**Comment by chornsby** [comment]
@lefnire Worked perfectly -- this is why I like you guys! Thanks for the quick response.
