### ISSUE TITLE
Completed To Do list not saved when exported to cvs

### ISSUE THREAD

**Issue by lamca274** [HabitRPG/habitica#3036]
If noticed that all my completed To Do lists that are wiped after 3 days are not saved to my exported cvs file like the habits and dailies. Please rectify this as the statement about the completed To Do list being accessible via the export function is misleading.

**Comment by lefnire** [comment]
Currently archived to-do items are wiped when you click "Clear Completed" (not just the currently visible to-dos). That's not ideal, so if you have some time we'd love some help fixing that

**Comment by WisTex** [comment]
I have not pressed "Clear Completed" and my tasks are still visible on the completed list, but my tasks still do not appear in the CSV file.  The CSV file only contains habits and dailies.

Since HabitRPG does not sync with other project management systems yet, I need this functionality to import my tasks into my other project manager.  If there is any way we can add this, it would be appreciated.  Thank you.

**Comment by WisTex** [comment]
Upon further investigation, this appears to be a bug or an oversight.  The XML file does contain the todo items, however the CSV file does NOT contain the todo items.  

Very strange that todos are included in the XML export, but not included in the CSV export.

Unfortunately, my app cannot import your XML, so I need todos in the CSV file.

**Comment by negue** [comment]
There was recently an update for csv export, do this Issue still exist?

**Comment by Alys** [comment]
@WisTex and @lamca274 : The CSV actually has a special purpose that's intended for only Habits and Dailies. It shows the change in value for those tasks each day (i.e., indicates how consistent you have been about doing the Habits and Dailies). It's designed for importing into a spreadsheet so that you can examine your progress over time.

To-Dos aren't included because they wouldn't make sense in this context. They have just one value. That value does change over time but only to indicate how old the To-Do is. That value change is not the sort of thing you might want to track in the same way as your Habits and Dailies values, because it gives you no indication about your performance. This is why To-Dos are not included in that CSV file.

The XML and JSON "User Data" formats are designed to show you all the current details of all your tasks, including To-Dos. Have a look at our wiki's [Data Export](http://habitrpg.wikia.com/wiki/Data_Export) page which has a section on "How to Open the Exported Files". Unfortunately your best option might be a plain-text editor, unless you have advanced programmers tools for those formats (and there is a problem with the XML structure that prevents it being used by some applications).

There might be a case for making a different CSV file that contains only the current data (not historical data) for all tasks. However it probably wouldn't include all the detail that you find in the XML and JSON files.

You can also look at the [HabitRPG User Data Display](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) tool. It shows you all your To-Dos including completed ones.
