### ISSUE TITLE
Repeated loss of gold and items

### ISSUE THREAD

**Issue by themadscholar** [HabitRPG/habitica#3038]
On several mornings this week I've woken up to find items and/or gold mysteriously gone. For example, two days ago c. 80 gold disappeared, and last night 1 nunchaku disappeared, and the gold I spent on it was not replenished. I also lost a level and thus "reached" level 18 twice. 

I only use HabitRPG on 1 computer and I use Chrome.

**Comment by deilann** [comment]
Are you also losing streaks/taking damage from dailies you know you've
completed?

Also, you can replenish the gold (and the gold to repurchase items) by
going to Settings > Site > Fix Character Values

**Comment by themadscholar** [comment]
I haven't noticed any unfair/extra damage from missed dailies. Streaks are working normally. Unfortunately I re-purchased the nunchaku this morning and it disappeared again within a couple of hours. Thank you for cluing me in to the manual fix!

**Comment by lefnire** [comment]
I think this is due to https://github.com/HabitRPG/habitrpg/issues/2301 . If so, the solution is to click slower - a lot people check off a big batch of dailies really fast. The first one goes through, but the database is still computing and the second, third, fourth click don't get saved, though it appears they did from the browser. What happens then is they get Gold, Exp, etc. They spend the gold on items. However, since they don't _actually_ have the gold - the server denies their purchases, and a refresh would tell them they're back a few squares. Wait for the blue load at the top to finish before continuing to next actions

**Comment by themadscholar** [comment]
I can verify that it happens whenever I use Backstab. I sometimes get a "Load Error" message with it too. Now that I know the manual fix, I can just re-renter my gold amount after it gets lost.
