### ISSUE TITLE
Fix Character Values can't fix # of Perfect Days

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#3051]
Fix Character Values can fix # of 21-Day Streaks but not Perfect Days.
##

**Comment by crookedneighbor** [comment]
I don't think we want to allow fix character values to adjust # of perfect days, since those are technically achievements. 

@lemoness @Alys thoughts?

**Comment by Alys** [comment]
The number of Perfect Days also affects drop chances.

I'm in two minds about this. It would be nice to add a perfect day when you legitimately lose one, but it is open to abuse, although we don't normally worry about that. It's possible to get Perfect Day achievements (albeit much more slowly) by just spamming Dailies. 

Sort of related, you can also get challenge achievements by creating your own challenges and assigning yourself as the winner immediately, and we don't do anything to prevent that.

I think for me it comes down to: Do we care more about helping honest users who have lost a Perfect Day due to one of our bugs, or more about stopping mischievous users from making themselves look more productive than they are and for getting more drops than they earn which _might_ make them buy fewer drops with gems (although I don't think that would create a significant drop in income). I think I'm tending towards helping the honest users recover from bugs.

The current workaround for losing a Perfect Day you should have had is to remember that happened and the next time you're close to a PD, tick off the last couple of Dailies without actioning them. That's a really dodgy workaround though.

**Comment by lemoness** [comment]
Personally, I'm leaning towards making it possible. If they really want to
incorrectly give themselves a perfect day achievement, they could have just
checked off all their Dailies in the first place. However, it's not a super
high-priority need.

**Comment by librarianmage** [comment]
Should this be closed, as the addition of the RYA feature allows one to retroactively get a Perfect day?

**Comment by lemoness** [comment]
Good call!
