### ISSUE TITLE
Bought scroll, gems deducted but no scroll in inventory

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3064]
I bought a Fiery Gryphon scroll. Had 12 gems, now I have 8 and no scroll. I tried it again and got a scroll but I've now paid 8 gems for it. Is it possible to get 4 gems refunded?

User ID: db190b28-8ce5-422e-8076-d43a62a7b204

**Comment by deilann** [comment]
How many scrolls does your inventory say you have?

**Comment by ghost** [comment]
The other one finally showed up in my inventory this morning, but I didn't want two.

**Comment by deilann** [comment]
Anysia, I don't understand. Can you backtrack a bit? As far as I know, no
one's made any changes to your account, so we're not aware of what's going
on.

**Comment by ghost** [comment]
As it says in my original comment above: I paid for a scroll but didn't get one. I paid again and got one. This morning the second scroll finally appeared in my inventory but I didn't want to buy two scrolls, I wanted one. I only did the transaction twice because the first one didn't  produce a scroll (although it did after some hours but I didn't know it was going to do that). So I want to return the duplicate scroll and get those 4 gems back.

**Comment by deilann** [comment]
Okay. Now I get it. Sorry -- the missing info here was the second
transaction. Which apparently was always there, but my brain isn't working.

I'm going to go ahead and refund you your 4 gems-- don't worry about the
extra scroll.

(Sorry for the double comment. GH was being weird and only displaying part of it.)

**Comment by ghost** [comment]
Oh, well, I wasn't looking for a freebie. You can just leave the gems then if the scroll stays (unless you've already changed it).

**Comment by deilann** [comment]
Ohhh, okay, I see the issue--

I handle tickets mostly through email (as do a lot of other folks here, I think), rather than going to Github. When things are edited, I don't get an email notif with the edit. So I missed out on your comment about buying a second scroll. If you reply to your own ticket, rather than edit it, everyone'll be kept up to date.

**Comment by ghost** [comment]
Okay. It offends my sense of order but I can do that. 😄

**Comment by deilann** [comment]
Don't worry about it -- I didn't feel like you were looking for a freebie. Be careful with the stacked scrolls, though. I, along with others, have found that sometimes when I have more than one of a specific scroll, two get used instead of one, and that bug has not been fixed.

And thanks wrt the email thing. It actually kind of hurts my head as well, but whatever works best, right?
