### ISSUE TITLE
Rebirth Doesn't Wipe Buffs

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3077]
So, I had a perfect day yesterday. Yay!

I also hit level 100 today, and decided to do a rebirth. Except, it's kind of awkward because I have a +50 buff for each of my stats (and a total buff of over 100 from some Earthquakes I cast) due to Rebirth not wiping buffs.

**Comment by SabreCat** [comment]
Hah, nice. Will address with Rebirth v2.

**Comment by deilann** [comment]
I am having ~thoughts on Rebirth.

1) Doing a Rebirth basically takes you out of the running of any challenges you're in. Sad!
2) I now have absolutely no motivation to do ANY of my out-standing To-Dos because they're all yellow now.

**Comment by SabreCat** [comment]
1) Why would it affect Challenges? Because people judge things based on streaks and task color? That's more an issue with the current limitations on how Challenges work than with Rebirth.
2) I hear ya, but I'm not planning to change that. Rebirth is supposed to feel like a fresh start in most respects, and leaving task colors untouched would be incongruous with that. People react differently to task colors. The reward motivation may work really well for you, but I for instance am one of the folks who feels like that deepening red is a sort of judgment upon me, and those tasks begin to take on a negative connotation. I sometimes buy Fortify Potions just to clean the slate!

**Comment by deilann** [comment]
1) Yes, most people judge challenges based on streaks or task color. I agree it's a limitation wrt challenges, but for me it was more of a "sad" and not a "wow, this needs fixed"
2) Oh, no, I agree that it should not be changed. I definitely wanted my habits and dailies to go yellow! I just didn't think about the fact that I'd lose motivation for smaller stuff sitting on my To-Do list.

**Comment by deilann** [comment]
Oh, also... after unlocking Rebirth at level 50 for the first time, you can then do rebirth at any age.

**Comment by Alys** [comment]
fixed in https://github.com/HabitRPG/habitrpg-shared/pull/307 (not live yet, but works well in testing and this issue can be reopened later if needed)

NB: _"after unlocking Rebirth at level 50 for the first time, you can then do rebirth at any age"_  -- that seems to have been fixed already elsewhere
