### ISSUE TITLE
tags reset daily

### ISSUE THREAD

**Issue by Bashala** [HabitRPG/habitica#3083]
I set tags for all my Habits, Dailies and To Dos.  Every day after my reset the tags are still at the top and the tasks all have the tag icon but no label is assigned.  The tags associated with challenges do not reset.

Username: Bashala, 
browser: Chrome

**Comment by deilann** [comment]
See this issue: https://github.com/HabitRPG/habitrpg/issues/2370

It's not that your tags are resetting, I think... It's that while the server remembers that you tagged it, the tagging never saves server-side.

**Comment by lefnire** [comment]
What happened is this. (we're gonna likely need to revert it, it's confusing a lot of people). Tags are stored in localStorage on your machine. So it's persistent between refreshes, but doesn't span different computers. The thought was something like "When I'm at work, I want the work tag to be semi-permenant. When at home, same deal.". The problem is it's not intuitive (or explained); but worse, we're back [to this issue](http://habitrpg.wikia.com/wiki/FAQ#I.27m_missing_some.2C_or_all.2C_of_my_tasks.21) of (many!) people thinking they've lost their tasks because they forget they have an active filter.

**Comment by lefnire** [comment]
@snicker you cool if I revert https://github.com/habitrpg/habitrpg-shared/commit/aa0c69e ? Anything else that's tied to that commit that needs updating?

**Comment by deilann** [comment]
@lefnire I think this is a different issue, where something is tagged then
when the server syncs, the tasks are no longer tagged. So it's not that the
tasks are being filtered-- you can see all of them. But they no longer had
the tags you applied.

**Comment by snicker** [comment]
would you be more apt to leave it in if we added a demonstration for clearing tags in the tour? Personally, I think that that tiny update to make tags persistent improves my personal user experience a TON and I have heard similar sentiments from others as well. It seems that a few outliers that don't seem to pay attention are the ones that have problems. 

Tag filters should probably be cleared on log in/out though, as I'm sure that is the first things most users will try in order to fix the problem (not clicking the clear filters button)

(a more obvious clear filters button might also, perhaps one that changes color when filters are active)

**Comment by wc8** [comment]
@lefnire I agree with @snicker that tag persistence ( [aa0c69e?](https://github.com/HabitRPG/habitrpg-shared/commit/aa0c69e)) is a really good feature, and I suggest making it opt-in. Thus, only users who _understand_ and _want_ it will be affected by it, and someone who doesn't find it useful can disable it.
- [ ] checkbox on Settings page for "use Context Persistent Tags", disabled by default
- [ ] popover "If this is checked, your tag filter settings will remain between refreshes. Each computer/browser will use its own settings" [or better explanation]
- [ ] implement
- [ ] bonus: add text "__ Habits Hidden" "__ Dailies Hidden" "__ To-Dos Hidden" "__ Rewards Hidden" to bottom of each column when tag filter is in effect. (@dusan's suggestion)
