### ISSUE TITLE
Lvl 100 player just used Orb of Rebirth and got charged gems for it

### ISSUE THREAD

**Issue by FLJIM560** [HabitRPG/habitica#3089]
Isn't the Orb free once you reach lvl 100? I had 54 gems. After the rebirth, I have 46.

So far I'm not happy with it. You need to offer something to acknowledge the players who complete all levels. Am I to understand, a player who uses the orb at lvl 51 is rewarded the same as a lvl 100 player? 

How about a special mount that's only awarded at lvl 100 or, better yet, a group of elite pets (Unicorns?) You get one elite pet egg every time you reach lvl 100.

UID: 2419a180-11e2-4266-8466-93160c1daf6a

**Comment by deilann** [comment]
No, the Orb is not meant to be free to level 100 players afaik. And personally, I don't think there should be anything special for hitting level 100. The point of Habit is not to hit a specific level, but to keep it at a point where it works for you. The reason the Orb is offered before level 100 is because many players find that they lose motivation at this point. The orb gives them a chance to stay motivated.

By putting a false prize at the end, it could create discouragement, rather than encouragement. Also, in order to stack your rebirths, you have to rebirth at a higher level than before, unless you were at level 100.

That being said, if you want to talk about non-bug bits of Rebirth v2, head on over to Trello, as that's where features are developed.

**Comment by casicastiel** [comment]
Plus, if stuff was automatically awarded at level 100, the players who cheat their way to the top in one day would be able to earn the same ~prestige as people who've actually worked for their achievements, thereby nullifying the point of it.

**Comment by FLJIM560** [comment]
From the wiki: An Orb of Rebirth is granted free of charge to any user who reaches level 100 (as announced in this official blog post). 

I didn't cheat to get to lvl 100 but, as you suggested, the site is incredibly boring at lvl 100. I did it for two weeks before rebirth. @casicastiel I WORKED MY WAY TO LVL 100 AND I LOVE THIS WEBSITE! If you're worried about cheaters, why give out any achievement badges?

**Comment by deilann** [comment]
I'm not sure why the @lemoness said that. I do not believe @SabreCat ever
put any code towards granting a free Orb to level 100 users.

Can we get some chiming in here?

**Comment by casicastiel** [comment]
@FLJIM560 Well, because, with the exception of Ultimate Gear, all the badges are uncheatable; either you put in the legitimate effort to earn them, or you don't earn them.

**Comment by lefnire** [comment]
I'm not seeing it in the code. Leslie & us devs sometimes get out of sync (inevitable), so let's wait to hear back from @SabreCat if the free orb was a code or an announcement issue.

**Comment by deilann** [comment]
:thumbsup: @lenfire

I pinged @SabreCat on GChat a bit back about it, so we'll see soon!

**Comment by FLJIM560** [comment]
@casicastiel My point is...someone who gets board with the game at lvl 50+ shouldn't be treated the same as someone who plays through. The game is essentially over at lvl 100. I don't know why the levels stop there. It should be relatively simple to program infinite levels with with the experience points needed to level again increasing by say 200 each level. 

I haven't been here from the kickstarter but I've been here since 4/2013 and I've been contributing  by buying gems and now a subscription. What kind of an idiot would pay to cheat on this site?

I got to lvl 100 quicker than most because I was here before the checklist feature was added. With checklists, my Dailies dropped by about 2/3.

I resent the fact that you and @deilann would immediately jump to the conclusion that lvl 100 players might be cheating. There is no oversight. Perhaps we're all cheating. Perhaps nobody is cheating. As is usually the case, the answer lies somewhere in the middle.

As for me, if habitrpg offers nothing beyond lvl 100 other than a do-over, I'll probably soon go back to my to-do list and stop supporting the site.

**Comment by deilann** [comment]
I never accused you of cheating @FLJIM560 -- I tend to assume that people who care enough about Habit to subscribe or submit GH tickets are using the site in a way that helps them.

I shared my personal feelings on why I feel like rewarding high levels isn't good for Habit-- it only encourages certain play styles, rather than embracing all of them. I recently hit level 100, and did so without cheating. And as a full INT mage with many dailies, did it quite quickly. But many players start losing motivation well before level 100 because it's hard to level up with their play style.

I then directed you to take discussion on further Rebirth features to Trello, as that's where feature development is being done. This is where we handle bugs and sometimes very code-specific non-bug issues.

**Comment by lefnire** [comment]
@FLJIM560 not everything was designed with utmost deliberation. As I recall, the conversation happened in 02/2013: "should we cap the levels?" "uhmm.. I guess so, 100?" "sure why not." If that's dissatisfactory, feel free to create a Wikia poll / comment in Trello

**Comment by DanielTheBard** [comment]
@FLJIM560 - I don't think anyone was accusing you of cheating. They were instead using cheating as an example why what you're asking could be problematic. That said, @deilann is correct. If you'd like to make suggestions for how to change/add to Rebirth, go to Trello and comment on the cards there. Github is for bug issues (typically)

@lefnire - I remember the good ol' days when we capped at lvl 20 ;P

**Comment by deilann** [comment]
(Oh, also @FLJIM560 I refunded you 8 gems because you were misled.)

Edit: omg daniel correcting my typos

**Comment by casicastiel** [comment]
@FLJIM560 Oh, no, I'm sorry if you thought I said that. I'm just saying that there _are_ people who realize that the top level is 100, and decide to go all the way up in one day to see if anything happens at level 100. And currently, the achievement _is_ the same whether you decide to Rebirth at level 50 or 100.

**Comment by DanielTheBard** [comment]
@casicastiel - Exceppptt, for what level it shows you "Rebirth-ed" at.

**Comment by casicastiel** [comment]
@DanielTheBard Ah, true. My bad.

**Comment by MANDRO1D** [comment]
@lefnire - if it was a semi-arbitrary decision, and the cap gets lifted, can you give users the option to restore their highest level if they've already been reborn?

Most RPGs I've played have a level cap, but once that level cap is reached, there is a wider range of incentives available to unlock. Armor, pets, or more complex achievements like badge collection. 

By giving the user limited options when we max out, you're unfortunately abandoning the most intensely focused users of the site. I'm just about to hit 100, and I'm really not excited about the next phase or restarting at level 1. 

Honestly, it wouldn't be a bad idea to have levels 101—(X) only available to subscribers. You could even have every level increase in XP exponentially. Level 101 could take as much effort as 1-100, 102 as much as 1-101, and so on.

If you want to avoid the typical "freemium" model of letting the user advance so far and then requiring payment, allow the user to select a charity for their subscription (or a portion thereof) to go to. There are multiple elegant solutions to this issue.

**Comment by lemoness** [comment]
Ah - I'm so sorry if I misled you! I really do think that at some point in the process we were intending for Orb of Rebirth to be unlocked at level 50, but then drop for free at level 100 - but obviously, the idea was either scrapped or not implemented.

However, I personally do believe that the Orb of Rebirth should be given free of charge at Level 100 for a very important reason - if we don't, it will discourage some of our users from continuing to play. There are many different play styles, as Ryan said, and the fact of the matter is, for some  people leveling is the single most motivating thing. I honestly do not believe that it will get much abuse - and if it does, who really cares? If somebody cheated their way up to a free rebirth, maybe it will encourage them to actually use the site the second time around. 

But as it is now, we're telling some of our most devoted users that they have to pay to continue having HabitRPG stay as motivating as it was - and I don't think that's fair. Plus, I don't think that it penalizes people who don't level obsessively if that's the only thing you get - it's not even really an item; it's a one-time-use spell. Sure, you get the drop bonus, but there are other ways to do that. 

So my vote is still squarely on Rebirth dropping at Level 100.

**Comment by deilann** [comment]
@lemoness I'm less worried about Rebirth dropping for free at level 100,
and more opposed to anything special (like a pet or an achievement)
happening.

**Comment by lemoness** [comment]
Totally agree on that. I'm intrigued by a new type of leveling (specialty
levels), though!

**Comment by deilann** [comment]
I think the level cap could be removed entirely if there were, instead,
stat caps.

**Comment by DanielTheBard** [comment]
@lemoness - Most frequent "specialty leveling" idea I've heard is for class levels. Which... is problematic.

**Comment by DanielTheBard** [comment]
@deilann - I won't rest until I hit lvl 696969.

And then I shall rest.

**Comment by SabreCat** [comment]
I have no idea where the free Rebirth at 100 idea came from. This is the
first I've heard of it.

Peeling off the level cap would be trivial; the current function for XP to
next level scales pretty nicely no matter how high you go. I also think I
know how I could grant a free Rebirth at 100 if that's what we want to do.

Let me know via GitHub ticket assignment what needs implemented, and I'll
add it to my list! (Unlike other top-tier contribs, I don't get much
mileage out of Trello, eheh)

**Comment by deilann** [comment]
I'd say cap all stats at 250 or 300, let levels go forever. That would keep
super high levels from breaking the game. I also say do not give out any
sort of achievement for maxing out all stats.

**Comment by DanielTheBard** [comment]
Nonononono :( I disagree, don't do that. Then, eventually you hit a point where you're a master of all stats. Your class loses half of it's purpose and there becomes little reason for anyone to specialize/diversify in their party. Sure it'd be at a super-high level, but it opens up that possibility. Also, then we'd have to start making quests that a small percentage of god-tier users could actually be challenged by, and would wipe the floor with everyone else.

I could however support the free Rebirth at lvl 100. It makes sense, to keep users playing.

**Comment by deilann** [comment]
@DanielTheBard Nah-- don't make quests for those users. In this theoretical world, they got a free Orb at level 100, which they can use at any time. If they want a challenge, they can rebirth at any time. And honestly-- your class loses its purpose stat-wise the moment you have cross-class gear? Which is not restricted.

**Comment by DanielTheBard** [comment]
@deilann - I... like the level cap for some reason :P It gives me something to strive for. If I hit it, I rebirth and try again. If it's a nebulous never-ending... I don't know if it poses a goal? But I really don't know I guess! Could we at least try out a poll on the matter before making that change?

**Comment by deilann** [comment]
Oh, that would definitely be a poll situation. The poll would also have to
make it clear that in this situation, the Orb of Rebirth drops for free at
level 100, in order to really get people's opinion.

**Comment by lemoness** [comment]
Hm, yeah, there are advantages and disadvantages to both. I'm leaning
towards lifting the level cap, free orb at 100, and the super-high stat
cap, but this is something the community needs to weigh in on.

So, three options as I see them (chime in with changes):
1. Current method: Level Cap at 100, stats freeze as-is; to use the Orb of
   Rebirth and start again at Level 1, you must pay gems.
2. Level Cap at 100, stats freeze as-is; you are given the Orb of Rebirth
   to start again at Level 1.
3. Level Cap is removed, but a Stat Cap is introduced. No Stat can be
   leveled past 300 (aka to max out all four stats, you must be level 1200).
   You still receive the Orb of Rebith for free at Level 100.

Any tweaks before we set up the poll?

**Comment by deilann** [comment]
Actually, you wouldn't need to be level 1200 -- without attribute points,
you'd need to be level 600. And then there's attribute points.

But still, you'd have to be a seriously high level to cap them all out. I'd
also make it clear that game mechanics would be working to make the site
work best from levels 1-100. We're not going to implement quests and stuff
 meant for level 300 characters.

**Comment by lemoness** [comment]
Ahh, so it wouldn't be an attribute-stat distribution cap, but a cap on
overall stat. I _thought_ that seemed awfully high!
1. Current method: Level Cap at 100, stats freeze as-is; to use the Orb of
   Rebirth and start again at Level 1, you must pay gems.
2. Level Cap at 100, stats freeze as-is; at Level 100, you are given the
   Orb of Rebirth free of charge to start again at Level 1.
3. Level Cap is removed, but a Stat Cap is introduced. No Stat can be
   leveled past 300 (aka to max out all four stats, you must be level 600).
   You still receive the Orb of Rebith for free at Level 100. The game will
   still be optimized for Levels 1-100, i.e. no quests will be introduced that
   you can't unlock until you are level 300, to keep things fair for people
   who level more slowly.
4. Level Cap is removed, but a Stat Cap is introduced. No Stat can be
   leveled past 300 (aka to max out all four stats, you must be level 600).
   You still receive the Orb of Rebith for free at Level 100. Quests and
   rewards will still be unlocked after Level 100.

Four options?

**Comment by deilann** [comment]
I personally don't want to offer number 4 because even if the majority
wants it, it greatly ruins the game for a minority of users. And if we put
it as a poll, and that's asked for by the majority, we'll have to defend
not implementing it.

**Comment by lemoness** [comment]
Hmm. And you don't think that it would just encourage those users to stay
with HabitRPG over the long-term? RIght now we've got a big influx of users
who are starting to reach 100 because they've been with us since February.
Ideally, we'll be making a game that people can continue to use voer the
course of, say, 5 years with increasing enjoyment.

 At some point, most of our first-year users are going to be over Level 100
if we give them that option. Sure, it will take some longer than others -
but really, you think it will ruin the game if, at some point one year from
now, we decide that Level 150 users should have a quest that they can
unlock?

I'm not being combative here, I'm genuinely curious - because if we should
remove #4, I will happily do so. But I want HabitRPG to be a game that you
can continue to play for years and years, like the best RPGs, and if we're
removing the cap, we may as well remove it fully. Why box ourselves in
again?

I'd love to have some feedback from multiple people on this.

**Comment by deilann** [comment]
If we remove #4, we still have the opportunity in the future to consider
adding quests and whatnot for higher levels, but aren't pushed into doing
so by majority opinion.

My worry here is that many users with the way that they play would _never_
be able to reach level 150. The amount of XP they gain vs the amount of HP
they lose would make it extraordinarily difficult (or impossible) to reach
higher levels without dying and putting them back a level. So either they
have to change their play style to accommodate this, or they will never be
able to attain some of what Habit has to offer.

**Comment by DanielTheBard** [comment]
I don't want any dirty lvl 300s in my party making the game a cakewalk. _shakes fist_
But really, the problem is, if we _don't_ offer new content past lvl 100, there's very little reason or incentive to keep leveling up. At the same time you create a larger level disparity and a divide in players. If you offer content for those over lvl. 100, you could be preventing a good chunk of users from ever being able to use that content due to how unequal different people's playing style is for the site.

I think we should offer more "end-game" content for people at lvl. 100 (I know we should be adding a bit with random encounters). And we should make the Orb of Rebirth free at lvl. 100, as well. But, I don't know about raising/removing the cap.

**Comment by deilann** [comment]
That's kind of the point, Daniel. I don't want to offer incentive for going
past 100... but I know many people want it an option, just to keep leveling
up.

**Comment by DanielTheBard** [comment]
@deilann - But why? Remove the level cap and there's no point to leveling up past 100. I feel like next they'd eventually complain and want content for lvl 100+. So same problem, just bigger level gap.

**Comment by deilann** [comment]
Because some people get pleasure merely from leveling up.

**Comment by DanielTheBard** [comment]
Alright, well put it up to vote. I'd definitely remove option #4 though. Def make it clear it's just continued leveling but no new content past lvl 100.

**Comment by deilann** [comment]
:thumbsup:

**Comment by lemoness** [comment]
A-OK!! Will get to it soon (probably not today), so if somebody else beats
me to it, just stick the poll here and I'll pop it on Twitter as well as
plugging it in the Tavern.

**Comment by AranelS** [comment]
Did this get done and I missed it?  Or is it still under discussion?

This is getting kind of urgent for me because I'm one of those people who's been here since early last year, and I'm getting closer and closer to 100.  And ever since I learned about the level cap a couple of weeks ago, I've been actually using the site less because I dread reaching that cap.  (Before that I was thinking about subscribing to get more quests but what's the point if I'm just going to lose interest in a few weeks?)

Honestly, I would get a kick out of watching that yellow bar creep across the screen and my level numbers going up even if I stopped getting stat increases entirely at level 100.  (Not letting my sister get too far ahead of me in level is a major motivator!)

**Comment by deilann** [comment]
Aranel, if you subscribe, you can put some of the gems you get for
subscribing into an Orb regardless. This is still under discussion, and it
may be a bit because we all have jobs and other things on our plate.

**Comment by lemoness** [comment]
Thinking about stats cap - what if we just capped all the stats as though they were a level 100 player? As in, you were allocated 100 stat points, and that was it. Would that be more logical than an arbitrary 300-stat-point cutoff?

**Comment by deilann** [comment]
But what about the lvl/2 stats?

**Comment by brightbold** [comment]
I want to weigh in supporting @lemoness and @AranelS in the pro-#4 camp. People in my party are kind of dreading rebirth, for the following reasons:
- it feels like losing all the progress we've made
- all our valuable dark red to dos will reset to yellow and not be valuable any more (this is the biggest obstacle, frankly)
- because we're not excited about rebirth, we're going to put it off until level 100. But we're mages, so if we do rebirth and come back as a different class, we're going to be much slower to level and might get ready for our next rebirth earlier (maybe it will be more fun than we think?) But we'll have to stick it out to 100 again to get the achievement. (If I'd known it was going to work that way, I would have done the leveling classes before mage.)
- my personal preference would be to wait to do rebirth until I've achieved Mount Master&trade; and do a pets rebirth (assuming that's coded by then) at the same time, so it's really a 100% fresh start. But I don't think I'll have all the mounts by level 100.

Anyway, didn't mean to go off on a Cons of The Orb bit, but my point is that for some people, rebirth can be demotivating, so it would be nice to have options for people who don't want to do it to keep going.

**Comment by lemoness** [comment]
@deilann - Set it so that your max level bonus to stats is 50 (100/2)

**Comment by deilann** [comment]
@brightbold The problem with #4 is that it basically requires an infinite amount of content. Okay, so we've put stuff that unlocks at level 150, what about people at level 250? Never mind how frustrating it would be for folks who cannot, with their play style, ever reach such levels. They'd never be able to reach that content.

**Comment by AranelS** [comment]
It really doesn't require infinite content--at least, not infinite content that is tied to level.  

I joined early enough that I can't really remember the last time I got a new feature because of my level. It really doesn't matter to me.  I'm fine with obtaining new content if/when it is released, as I have been doing pretty much for the entire past year with no objections.  I level up to level up, not to unlock new content.

If I got to the point where I could beat a boss like Vice in one day, I would not actually object to that, either. (And if I did object, it would be my own silly problem, and you would be justified in telling me to either use an Orb of Rebirth or get over it.)  The quests do not have to scale with higher levels.  You can let people at higher levels either (a) enjoy being ridiculously good at everything and having no challenges or (b) restart if they want it to be challenging again.

**Comment by deilann** [comment]
#4 is specifically the version in which we continue to roll out unlockables after level 100.

**Comment by AranelS** [comment]
Well, then make that a vote for "I don't see much point in #4".

**Comment by brightbold** [comment]
OK, I'm going to have to admit that by the time I'd read through this entire thread and started to comment, I'd forgotten that #3 included removing the level cap and was thinking only #4 had that. So #3 addresses my concerns equally well. I like the idea of giving people the Orb at 100, basically saying, we're encouraging you to use it now, but we're not forcing you to.

**Comment by deilann** [comment]
The question here is really what we want to do with stats.

**Comment by MANDRO1D** [comment]
Option 3 sounds excellent to me. I don't think there needs to be special content for 100+ players, just gaining XP again would be sufficient. A stat cap would be sensible, but overall I don't think level disparity between users is a major issue. Parties can organize themselves based on user level if they so choose.

I've been at 100 for about 8 days now, and it's definitely changed the game for me in a mostly negative way. After a certain point, more gold doesn't help your char at all, and without XP that's all you gain from Habits and Dailies. I've been shifting tasks into my To-Dos to at least gain some mana to help on quests. Having less perceived reward for Habits and To-Dos is definitely warping the game dynamics. 

Will this be going to a vote soon, or will a decision be made here?

**Comment by lemoness** [comment]
I think at this point, it's really a vote between 2 and 3, and people seem
to be mostly chiming in for #3. Do we still want to make a poll?

**Comment by deilann** [comment]
I think the best answer is to do the following:

1) Make the Orb free upon level 100 (just check if user is level 100+ don't
charge gems)
2) Put up the poll

The orb can certainly be free while we figure out what we want to do with
the leveling cap, which will make people happier short term.

**Comment by lemoness** [comment]
Hear, hear!!

**Comment by deilann** [comment]
I'ma go do that.

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg-shared/commit/1db3b7cf98cf15cfbb518760e2606f5623e95d43

**Comment by meganstrickland** [comment]
I'm late to the party here, but I just want to chime in with my vote for
-  making the Orb free at level 100 (which is already done---yay!)
- freezing stats at level 100 (no new stat cap business, keep the stats as they are at level 100)
- otherwise maintaining the levelup/heal mechanic with ever increasing XP required to heal

My reasoning for wanting the stat freeze at level 100 is that it still encourages players to diversify within a party and feel like they are crafting individual characters. With a per-attribute stat cap, everyone who didn't Rebirth would end up with the same maxed out stats eventually. And freezing solves the issue of quests and whatnot being targeted for players with level 1-100 stats. So those who don't want to Rebirth can keep leveling for the sake of leveling and for the heals, and those who are not motivated by that can use the free Orb and start over. My two cents. I would very much like to see that option represented in a pole at least.

**Comment by deilann** [comment]
I'd also point out that people who don't want to rebirth can reroll their
class whatnot to better align their points how they want them. Yes, that
does cost gems, but doesn't come with the unwanted effects of an Orb of
Rebirth that make some people less likely to choose it.

**Comment by lemoness** [comment]
Awesome job, Ryan! Gonna make the poll this afternoon :)

**Comment by deilann** [comment]
I'm gonna need to change the modal at some point (it'll still _look_ like
it costs gems for level 100 players at the moment, which is not true), so
an announcement is probably definitely due.

**Comment by lemoness** [comment]
How hard is it to make it drop automatically when you level up?

**Comment by deilann** [comment]
It's not actually an item that goes in your inventory. You click the button
and you rebirth. It would have to be turned into an item.

**Comment by lemoness** [comment]
Ah, got it. Then we should have a pop-up upon reaching Level 100 that says,
"Congratulations on reaching Level 100! You've reached the maximum level,
so all further XP will be converted to gold. But never fear! You can always
use the Orb of Rebirth in the Marketplace! The Orb of Rebirth will restore
you to Level 1, restore all your tasks to yellow, and start you over at the
basic armor set (although you will have the opportunity to re-buy all
Limited Edition Armor that you previously purchased). Now that you are
Level 100, you won't be charged gems if you click on the Orb of Rebirth, so
it's free to use!"

Making a poll with two options: the current option (everything freezes at
Lv. 100, Orb is free) and option 3 (keep leveling, but stats are frozen at
their Level 100 mark and we never introduce any benefits for Lv. 100+
players. Also, Orb is free.)

Good?

**Comment by deilann** [comment]
Yeah, that all sounds good. I think the stat freeze is better than a stat
cap, especially as you can reroll your stats, even though that costs gems.

I'd go further and have an option in the popup of "Rebirth Now!"

I can work on that tonight.

**Comment by lemoness** [comment]
Ooh, love the "Rebith Now" option!

Okay, here's the poll! It's by A WIkia Contributor because the Wiki won't
email me my password and it won't let me make a new account because the
capcha is broken and I need to leave five minutes ago.... BUT IT'S REALLY
BY ME.

http://habitrpg.wikia.com/wiki/Thread:11495

Posting in the tavern now!

**Comment by lemoness** [comment]
Okay, this is looking pretty landslide-esque... But let's wait til tomorrow
to call it.

**Comment by deilann** [comment]
I'm gonna write up the PR assuming we know the answer, but we can wait to
merge.

**Comment by lemoness** [comment]
Yeppppp, looks like forever-levels plus stat freeze is the clear winner!!!

**Comment by lemoness** [comment]
Ryan, what exactly does your PR contain? Just the solution from last night
with a revised level 100 pop up announcement, or also the ability to level
past 100 + stat freeze? If it doesn't contain the second, do you want me to
make a new Github ticket for that, or just keep it looped into this one?

**Comment by deilann** [comment]
I haven't put forward the PR yet. I was gonna do both together.

**Comment by lemoness** [comment]
Sweet! Want me to write up a quick bailey and send it to you for tweaking?

**Comment by deilann** [comment]
Sounds awesome!

**Comment by lemoness** [comment]
Cool. Will do later tonight!
