### ISSUE TITLE
Lost pet!

### ISSUE THREAD

**Issue by anitli** [HabitRPG/habitica#3117]
Just made it to level 10, but when hatching pets, noticed it would allow me to hatch a white wolf although I had one with my avatar. Switched pet to see if the option would still be there if it was in my inventory, but poof! It was gone. Kind of a bummer.

**Comment by Alys** [comment]
@anitli I'm very sorry we didn't get back to you about this before now. The site has had significant changes to its code since you reported this, and we haven't seen any other reports of the same issue in the past several months, so I am guessing this is fixed for you, but if it is not, please reply and I will look into it!
