### ISSUE TITLE
Aborted Quest, Scroll Did not reappear in inventory

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3121]
I aborted the Fiery Gryphon quest, and the scroll didn't reappear in my inventory.  My inventory says I have 2 scrolls (and I currently do, Dragon's Influence & Lair of the Wyrm.)  My user ID is 0de6fb27-b3b8-4a8d-aaba-cfe049201733

**Comment by deilann** [comment]
Okay, that's good. What I think happened here is you had a negative number of Fiery Gryphon scrolls (so your inventory might have said 1 scroll before you aborted). Aborting then gave you the scroll back, which left you with zero scrolls. Because your scroll count matches the number of scrolls you have, you should be able to repurchase the scroll with no difficulty. (If it said you had 1 scroll, you might have had to repurchase it twice.)

I have refunded you 4 gems. Repurchase and prosper. :)

@lefnire Do we have a fix on the horizon for negative number of scrolls? It's a consistent issue, and requiring a lot of support.

**Comment by ghost** [comment]
Thank you!!

**Comment by deilann** [comment]
np :)

**Comment by lefnire** [comment]
@deilann do you have a master ticket for it? I'll put it on my prio

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/2592

**Comment by impr** [comment]
Just had the same issue... I aborted the Spirit of Spring quest and it did not reappear in my inventory. My user ID is: 42502b01-7aac-4b5f-b813-457a03e50f89. Thanks!

**Comment by deilann** [comment]
Can you do a hard refresh for me of your inventory?

After said hard refresh (if the scroll doesn't appear), two things:

1) How many scrolls do you actually have in your inventory
2) How many scrolls does it say you have in your inventory (total)

**Comment by impr** [comment]
Um, not sure how to do a "hard refresh". My closest guess was closing and reopening HabitRPG entirely so I did that and it worked! Thanks! In case it helps with future cases of the same issue, I had already tried hitting the "sync" button in the top right but that didn't change anything so apparently the full reboot is necessary.

Thanks!

**Comment by deilann** [comment]
Hard refresh is a refresh without cache -- the issue is that your local
side is using old data to make the pages load faster.

For future reference, shift+ctrl/cmd+F5 should give you a hard refresh.
