### ISSUE TITLE
Instant Death on New day and all streaks reset

### ISSUE THREAD

**Issue by Simsgirl89** [HabitRPG/habitica#3125]
I have been pretty consistent at longing in and getting perfect or almost perfect days for a few weeks now. I had some streaks past 42. Today I logged on instantly died and all my streaks that I would have marked yesterday were reset to zero. I know I logged on yesterday and it seemed that my dailies were being marked off. I noticed that one of my added tasks from yesterday (around when I would have marked everything off was there). I will note that I am in a party. I ended up getting 18 damage and giving 0 even though I know I checked a ton of stuff off. What could have went wrong? It was really sad to lose enough hp to die, lose an item, all my gold (I was up to over 1000 gold), and especially sad to lose all my streaks. What can I do to make sure this doesn't happen again?

**Comment by deilann** [comment]
Sounds like you hit some server errors and the clicks didn't save. There are a few things you can do to make sure this doesn't happen again.

1) Click slowly. If you click fast, you increase your chances of this happening. Always wait for the blue bar at the top to finish before clicking something new.

2) Do a refresh at the end of the day to make sure everything is checked. If you refresh the page (without cache), you should be able to tell if anything just looked like it was checked off.

Now, here's the good news:

If you go to settings> site, there's a button called fix character values. You can then restore all of your stats. In order to restore your streaks, go to the advanced options in those Dailies.
