### ISSUE TITLE
Organizing To Do list

### ISSUE THREAD

**Issue by Melodei** [HabitRPG/habitica#3131]
Hello,

The program is awesome. Thanks.

I am a freelancer with an extraordinary number of to dos. For the list to be useful to me, I have to be able to organize it as I need. I am able to organize the other lists (habits, dailies), by sliding the names of the items about into the order that I want. 

I can slide the to do items around as much as I want, and I am able to create an organized list. However, unfortunately, every single time, the game has eventually reset them to a random configuration.Sometimes it does this if I check the program on my ipad and come back to my computer. Since I knew that might be origin of the error, I deliberately didn't do that for a while, but unfortunately, the to do list still scrambled itself. It last happened when it auto-synced. 

The problem has been happening since I started using the program which was admittedly only a few weeks ago. Thanks again for designing this; it's both cute and useful.

User name: Melodei
Browser: Chrome
Error message: None, I'm just getting a flaw.

**Comment by deilann** [comment]
This is a known issue. Clear your completed To-Dos then reorganize. Should
fix your problem!

**Comment by Melodei** [comment]
Thanks! Sorry to bother you with a known issue. I checked the tickets, but
i guess I didn't use the right search terms.

Thanks again.

Best,
Rachel

**Comment by deilann** [comment]
np! Happy To-Do sorting!

**Comment by Melodei** [comment]
I hate to say it, but I cleared the completed tasks, reorganized, and got
the error again. :/ Working on a single machine in the same browser window
without closing it.

**Comment by deilann** [comment]
Are you waiting for the blue progress bar at the top to finish before
moving another task?

**Comment by Melodei** [comment]
Ah. No. Well, thank you.

Terribly sorry for bothering you. Will go subscribe now so at least I'm
funding you. :P (Was planning to anyway, but it's a good impetus to do it
now and not tomorrow.)

**Comment by deilann** [comment]
No, no, it's fine. XD You're not bothering me. (I have a "respond to github
tickets" habit, so I even get XP)

I have had this issue myself. Took me forever to even realize the bar was
there.

**Comment by Melodei** [comment]
Phew. ;) Thanks for your help, again.

**Comment by GloomyMoonie** [comment]
Hi, I'm having the same problem, despite following all of the proposed solutions.
I've deleted completed To-Do's, waited for the progress bar to load completely after every time I moved something, but when I click the Sync button, or simply refresh the page, some of the tasks get to a position I've never set them to be at. I've tried reorganizing a different group before refreshing in hopes to get the arrangement of the To-Do's to "sink in", but to no avail. 
This gets increasingly annoying the more tasks I put in, so I really hope that there's a way to fix the issue, rather than finding workarounds. But if there is one that I'm missing, I guess it would be better than nothing. 
Otherwise the game is epic, really happy I've found it.

**Comment by Alys** [comment]
@GloomyMoonie did you delete the completed To-Dos by using the "Delete Completed" button at the bottom of the list, or one-by-one manually? If the latter, you need to use the button. It will delete old completed To-Dos that have been archived and so do not display in your browser.

**Comment by GloomyMoonie** [comment]
Yes, I've used the button.
I've found a method that seems to be working though, which is waiting until the list stops reorganizing itself, and then rearanging the tasks one by one, with a sync/refresh in between each action. I can't say that this is what fixed the issue, but if it is, the auto sync (progress bar) would be the thing to blame I think, otherwise what I'm doing is borderline superstition. But hey, at least it actually works _knocks on wood_ :D.
