### ISSUE TITLE
Gender Neutral

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#314]
Email from a user:

> I'll start by telling you that HabitRPG is a brilliant idea. Thanks to the site, I've already written three paragraphs to an essay today, and that's more than in a month! So thank you, you turn my love for video games into productivity. :D
> 
> But I do have a suggestion. Seeing as there is a large amount of people who identify outside of the gender binary, have you considered adding a gender neutral option to the character creation? It would definitely mean a lot to many people, who often even feel anxious of choosing their gender in Pokémon.
> 
> Thanks again for making HabitRPG, it's brilliant!

**Comment by lefnire** [comment]
I say we just make a "neutral" checkbox and use the male character, the avatars are pretty indistinguishable as is, especially with armor.

**Comment by ghost** [comment]
Maybe make a neutral looking avatar? Plus introduce the gender thing as
soon as you register. Like in Pokemon!

**Comment by Pandoro** [comment]
Honestly I'm wondering if it is going to get a lot more neutral than the current starter male is. I'd go with @lefnire 's suggestion on this one.

**Comment by StanLindsey** [comment]
It was hard enough for @Pandoro to make the female avatar look female with only 8bit pixel limits =D

**Comment by Pandoro** [comment]
I wonder what the fuzz is about these 8-bit pixels x) I use 32bit pixels if
anybody cares about it ;)

But yes, with the limited amount of pixels it is rather hard to get
anything looking expressive. You can also see that at @Shaners pets. For
example the little fox has just a tiny back leg, probably making it
recognizable would look plain weird and for the lion to be more detailed he
made it pretty big.

**Comment by lefnire** [comment]
btw, i deliberately used the heads instead of "M" and "F" for this reason. In the next iteration (@Pandoro's character customizations mockup) I'll similarly use art over text to save us from the same issue.

**Comment by Pandoro** [comment]
@wildcate let me explain the gender thing a little. It was indeed intended to be a gender thing. At first there was just this... rather stupid looking female character from the BQ set. So I set out and created a female avatar, as people were asking for this! The lady was wearing pink, and at the time I cared more about the hair than about the dress thing. I created the basic avatar and later on modified the other armors, made a little smaller shields and a little slimmer armors. You can say that I am a sexists bastard, but my intention was to make the female avatar a little more gentle to have some kind of difference. Since it was hard to make the difference visible for some of the characters, I decided to make several versions for people to vote on. Later on these was actually added to the game, hence only the female characters have the option to pick styles. Only because my girlfriend was nagging me about the pink, and I agreed that this was too stereotypical, I added the yellow one, as white didn't look so nice. 

I guess it should be doable to add a white shirt to that as well, but... structure wise, it are seriously male and female characters currently. The female has a little redder cheeks and also a little different face shape. Given the limited number of pixels, it is not trivial to distinguish between males and females here, but if I get you right, that is something you don't want at all anyways ^^; Adding different hairstyles is something that we should do at some point for sure and if the flower is bugging you, that shouldn't be too hard to change, but I would still prefer to just have the male and female gender and then just make long and short hair for both of them. Because a male that has long hair would still look a little different than the female with long hair looks now. (apart from the flower.) 

The mail from the user mentioned in this post states that "...there is a large amount of people who identify outside of the gender binary...". I personally still don't understand the whole fuss about not having genders :x Don't get me wrong, I am not judging, I just have trouble understanding it. Maybe you can explain the underlying motivation for this a little? I'm still wondering what would happen if we really remove the gender thing and make it completely neutral again. Probably soon that would result in complains about why there are no more female characters. But well... that is just my feeling.

**Comment by wildcate** [comment]
@Pandoro, thank you for the gender thing explanation! I had not realised that there was actually a change to the face shape and skin variations for the female character.

You say that you have trouble understanding the gender issue... let me try to explain as well as I can.

Gender stuff can be a serious issue for some folks, and it's usually tied in with privilege. There's a gazillion of blog posts and blog rants that deal with this much better than I could here, but regarding RPGs and in a nutshell, it boils down to people not getting to choose an avatar that correctly (or mostly correctly) represents them. Those that are the majority (male and female, in this example) can choose a male or female avatar and everything is well. Those that are not do not get the options that fit them. Same with romance tied into RPGs: typical and most frequent romance (or romance opportunity) built into a story is male hero woos female NPC. If you are a lucky heterosexual female player, you get to choose a female avatar that flirts with a male. Same-sex romance opportunities, as far as I gather, are very rare indeed.  

And sometimes, the female version of a character looks not like a kick-ass heroine, but more like a typical comic-book "heroine", or maybe a wet dream template for a male. In these cases, though I strongly identify as female, I will pick the male version to play... and be slightly miffed about it. Our world is sexist enough, I don't want to be reminded about that when I play. Sort of on the same note, even though I much prefer the long hair of the current female version, I would have stuck with the male avatar if there had not been the yellow clothing choice. And I would have preferred the white, or a light blue, even more.

You say the limited pixels in the 8-bit graphics make gender differences small and hard to realise - I would say that is a definite plus and we could run with it. The pixel-style artwork leaves a lot to the imagination and interpretation of the viewer, and that can be used to everyone's advantage in this case. So my suggestion would be to make a few different hairstyles, give everyone the option to choose between the face forms (slimmer and wider), 2 or 3 body types, and the long and short garment in 3 or 4 colours, and everyone can mix and match. That way it would be possible to have a stocky body with a feminine face and a pink dress as well as long hair and a slim body and a white shirt... to each their own. Plus it would not waste your hard work on the slimmer version of the character. 

Yes, I do realise it would mean a good bit more work, and that it might not be possible to fit all styles in a true mix-and-match. However, being able to choose an avatar that is not clearly gendered might not matter to a lot of people who identify as more-or-less typical male or female... but to those sensitive about the issue it would matter a good deal, and make them very happy. And probably make them feel included in a way they rarely do.

**Comment by Pandoro** [comment]
@wildcat, I can understand the extremely overdone looking female thing can
be very offensive, but I still cannot understand why people are so against
simple gender characters, especially when they are un-gendery like they are
in habitrpg.But everyone has their own feeling about issues and I can
probably not judge since I am just a guy not minding it all that much. So
please don't feel like I am trying to attack your opinion. I just feel like
people are minding details too much in some cases, when I have the idea
that this will not fix the actual problem at hand. But let's see what we
can do in habitrpg.

@lefnire it might be worth looking into it, a lot of stuff is rather
redundant in both gender sets currently. How do you feel about fusing them
again, having :
1. Hairstyle (will pretty much determine pony tail or not right now)
2. Face shape (Will determine the current male or female look)
3. Skin color (choose the skin color)
4. Armor (here you can choose between the current female and male version)
5. Shield (Choose between current small and large shield version)
6. Weapon (Pretty much no choice, as there are no different versions of
   weapons yet )

It would make the file a LOT messier to handle again, but the development
could be done in a separate file and only being fused into the big file
once it checks out. In general I still feel that people who clearly want to
look female like, like they look now, should have that option, but people
who want to look in whatever different way can have that as well I guess.

It would still have to show if this will or will not work out, but if
people feel like this would be worth looking into, we can see how it works.

**Comment by caycefischer** [comment]
I think it's safe to say that we want to be respectful and please everybody. 

We should not _enforce_ a binary gender choice, but we _should_ offer gender choices because frankly, a lot of people will want to choose a gender too.

There's no good solution to the _very complex_ issue of gender identity in a web application such as this. So given that we're only human, due to what assets we currently have we should _default_ to no gender, and allow choosing from _the current options_ of "male" and "female", _which we hope will expand in the future to allow additional inclusive options_

Sound fair?

**Comment by caycefischer** [comment]
@Pandoro While it is complicated, I think a more robust chargen system is a good idea, as you describe. Like a pixelly stripped-down Elder Scrolls game :P

Though I do want to say that for easy entry into the system and a good user experience, a default neutral avatar should be assigned and the prompt to customize given later. We want it to remain as simple as possible to sign up and hit the ground running.

**Comment by caycefischer** [comment]
If anyone finds some interesting articles on how other apps have worked with this issue, post them here. 

Here's a couple interesting links I found, that I haven't gone through yet but I will:
- http://nonbinary.org/wiki/Websites_and_social_networks
- http://stackoverflow.com/questions/6627197/how-do-you-ask-gender-to-match-people-on-a-site
- https://www.wpi.edu/Pubs/E-project/Available/E-project-042612-150925/unrestricted/Designing_the_Gender-Neutral_User_Experience.pdf
- http://ux.stackexchange.com/questions/13413/default-gender-male-or-female

**Comment by wildcate** [comment]
Is the gender question really a question that needs to be answered by the user? Is it planned to include gender in the profile, for example?

If not, I'd think it would be easiest to just provide several avatar options (like suggested above) and just not label them. Then everyone who wants to can make a slim avatar with long hair and a pink dress and interpret it as female, or transmale, or a drag queen, or whatever. Since the avatar choices will presumably include the now-existent choices, and since nobody will expect an incredible lifelikeness from 8-bit pixelated figures, that should be fine. No need to label bits and pieces, or folks.

If gender is supposed to be included in the user profile, non-traditional gender folks seem to prefer being asked about their preferred pronoun, not their gender. Or have a gender field as a blank that can be filled in with whatever (or left blank).

**Comment by Pandoro** [comment]
Honestly I completely stopped thinking about this after my last push of
pixel stuff. It lets people choose whatever they want to look like. I don't
think this needs further discussing. I removed everything called
male/female.

Someone needs to change the system a little (regarding the no helmet
hairstyles) and that is it :-/

**Comment by Pandoro** [comment]
Well to be fair, gender is still in there :p

**Comment by lefnire** [comment]
[comment removed] sorry bout that, was a bit too blunt

**Comment by wildcate** [comment]
I also thought this was solved with merging @Pandoro's label-free version in. (Though it does not seem to be merged in yet, at least I still get the old dialogue with the labels.)
I hope that it did not seem to be upset, I just wanted to get clear on why this came up again...

**Comment by lefnire** [comment]
ah, looks like they weren't merged in indeed. I apologize

**Comment by caycefischer** [comment]
Tyler you're right, we can only do our best and there will always be people
who aren't happy. You and @Pandoro are also 100% right, I think removing
gender entirely and focusing on appearance is the right move. I'll keep
tabs on this issue, and address concerns that come up—we can always get
better and questioning our assumptions is a good thing.

For now, we're in good shape, once those changes get merged in. Label-free
is the way to be.

On Mon, Mar 11, 2013 at 5:10 PM, Tyler Renelle notifications@github.comwrote:

> ah, looks like they weren't merged in indeed. I apologize
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/314#issuecomment-14742896
> .

## 

_– Zachary Kain_

Designer, Creative Technologist
416-712-8895
zakkain@gmail.com
→ view my resume/profile http://zerply.com/zakkain/public
