### ISSUE TITLE
Double crit notification.

### ISSUE THREAD

**Issue by DimTwin** [HabitRPG/habitica#3166]
My ID: 91ab86a8-6fb0-4be4-8eeb-7f6b96aef698

Have a look at it:
![1](https://cloud.githubusercontent.com/assets/6949144/2546920/ee1da762-b644-11e3-96fa-7bf59477b2e9.png)

It's the issue I experience quite often. Normally it happens when I do critical hits to habits. Once it happened with a daily. To me it seems random, not every crit notification becomes doubled. I haven't been able to trace any pattern yet. Though some say that it's pretty regular.
##

**Comment by deilann** [comment]
This pretty much always happens to me with crits. It's just a double notif.

**Comment by DimTwin** [comment]
@deilann Hm I'm gonna check it several more times. Don't think the notiff always gets doubled.

**Comment by deilann** [comment]
No, no, it's p much always doubled for me. But the notif is what's doubled;
not the crit.

**Comment by DimTwin** [comment]
@deilann well I guess you're right ;) still its an issue, although tiny ^^

Updated the title and the post not to confuse people.

**Comment by deilann** [comment]
Yeah, I keep meaning to post it. Just keep forgetting. Just wanted to
clarify that

1) It's not just you
2) it's a double notif, not a crit applying twice

I'm honestly surprised you're the first one to post about this, considering
how often I see it.

**Comment by DimTwin** [comment]
@deilann Well sooner or later someone should've posted it. Better sooner I say))

**Comment by deilann** [comment]
Indeed! I'm just surprised it took this long. If I had been on top of my
game... :P

**Comment by DimTwin** [comment]
@deilann Sometimes it does no harm to relax and let others have fun posting some issues ;P

**Comment by deilann** [comment]
Ahahaaha, fair enough

**Comment by DimTwin** [comment]
@deilann I finally managed to get another crit and the notification didn't double. So it's irregular after all, at least for me.
![2](https://cloud.githubusercontent.com/assets/6949144/2549092/a76f55c0-b66e-11e3-979c-20249cfd35bd.png)

**Comment by deilann** [comment]
So did I. Which leads me to believe I only noticed when it doubled, not
when it was normal. Hmmm. Extra interesting.

**Comment by SabreCat** [comment]
I believe this happens when additional data gets synced from the server after your action. For instance, if there's been a new party chat message since you last synced, you will get the double crit notif; if there's nothing of the sort (which may be the less common case, thus the frequency of seeing the double), then you get only one display of the crit. That's my guess, anyway, because the slight hesitation that occurs before the second notification appears "feels" very much like a sync happening--see also the additional +Gold notification that can happen if somebody in your party cast Tools of the Trade since you last synced.

This may thus be the same underlying issue as #3048.
