### ISSUE TITLE
change class popup does not have a cancel/dismiss option

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3207]
I was a rogue and had a second thought while changing my class, I clicked rogue again in the hope that it would kick me back but it charged me gems anyway, moreover the class geat popup won't dismiss
##

**Comment by deilann** [comment]
If you want to dismiss, you should click the dismiss button, as changing
class is also to get rid of how your points are allocated -- so you might
want to remain the same class, but deallocate your points.

What's your UUID? The persistant tour thing is a known issue; refreshing it
should fix it, iirc.

**Comment by ghost** [comment]
had to clean cache to dismiss the class gear popup
what dismiss button? didn't find one, only select and opt out

**Comment by deilann** [comment]
Huh. I might be remembering wrong.

Still, UUID, so I can refund you the gems?

**Comment by ghost** [comment]
that's the user ID right?

288d231f-cedf-4c51-a3e1-49f087829738

thank you very much, I'll be more careful next time

**Comment by deilann** [comment]
Gems refunded! Sorry it took a bit.

Now that I'm thinking about it, the warning is _before_ the part you got
to. By that point, there's nothing you can do-- the points have already
been deallocated and it's just you choosing your class again.

**Comment by kawunngg** [comment]
i won't recreate what was happening, because it would cost me gems ... maybe in a few days again, because right now i'm shopping seasonal gear. 
also i can't provide the exact words of everything, because i use habitrpg in german. 
so... i clicked "change class".
habitrpg: "3 gems ok?"
me: "ok"
there was the dialogue "choose new class or deactive class system". well, the button was not named like this, but something with "do not decide yet" (at least in the translation.)
i admit i did not read too carefully. but i did not want to decide yet and as i renember there was no other option. so i clicked the button and it deactivated my class system for 3 gems. i could then choose a new class again, as it seems without paying. but this confused me a little...

**Comment by deilann** [comment]
Opting out doesn't give you all the benefits of the class system. It allows
you to purchase warrior armor, but doesn't allow you to allocate attribute
points or to use warrior spells. Whenever you opt out, you can later opt in
and choose a new class for free. That is expected.

Also, when you click change class, it should say more than 3 gems ok? And
in fact, I just checked it and it does at least in the English translation
say something to the effect of "Are you sure? This will reset your class
and attribute points and costs three gems."

That is when you are supposed to cancel. Or, as you found, you can opt out
and then later opt back in again.

**Comment by kawunngg** [comment]
of course it said more than "3 gems ok?" ;)

i guess it would make more sense to show the options and after that to ask the question if one's shure. as i said i really did not read too close. which i did not because i thought i "know" the procedure. totally my fault. but now i wonder if this would not be too weird for people, who are not aware of what they can choose.

**Comment by paglias** [comment]
Should be fixed
