### ISSUE TITLE
Spending gold/hatching pet reset

### ISSUE THREAD

**Issue by meshqwert** [HabitRPG/habitica#3216]
Whenever I go to spend my gold on armor or hatch a pet the action is reloaded by the next time I log in.  I have to rebuy or rehatch.  However, my avatar has changed to match my purchases and hatches.

**Comment by Alys** [comment]
@meshqwert I'm very sorry we didn't get back to you about this before now. The site has had significant changes to its code since you reported this, and we haven't seen any other reports of the same issue in the past several months, so I am guessing this is fixed for you, but if it is not, please reply and I will look into it!
