### ISSUE TITLE
Tasks created under one tag don't get appropriately tagged under the checkbox

### ISSUE THREAD

**Issue by mezarque** [HabitRPG/habitica#3226]
Also, upon page reload, sometimes only the last tagged items get displayed.

**Comment by deilann** [comment]
I'm not entirely sure what you're trying to say. Can you be more specific?

**Comment by mezarque** [comment]
So, when I have a specific tag selected, it displays all of the items selected under that tag. When I create new tasks while that tag is selected, they appear properly. However, when I deselect the tag (using the "x" button), the checkbox for the tag is not checked when I edit the task.

**Comment by deilann** [comment]
Oh, so, what's going on here (and I totally get why you wouldn't intuit
this) is that they appear because you've added them, but aren't actually
tagged for that. So if you refreshed, you'd no longer get to see them.
Unfortunately, there's no way right now to auto-tag things upon creation.
So they were never actually tagged with that.

**Comment by Alys** [comment]
This was fixed a while ago. Now, when you have tags active, and create a new task, those tags are applied to that task.
