### ISSUE TITLE
Gems toolbar popover: explain gem cost $…

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#3228]
There's not a clear indicator in the toolbar popover the _gems cost real money_ and **support habitrpg** (unless something was lost in translation—using Spanish version). 

Should we add something in the popover or in the dialog that appears when one clicks Gems to indicate the cost purpose? Or maybe just describe gold & silver more?

@lemoness  thoughts?

**Comment by lemoness** [comment]
Hmmm, you're correct - since you can also get gems from challenges, and
clicking on the gems immediately pulls up the "Buy Gems" page, I think the
initial pop-up text is okay, but I would modify the hover text on the buy
gems page to include a comment about supporting the site. There is a
"donate to the developers" link, but the gem-purchase link could use a
sentence added to the hover text that says something like "This is the
easiest way for you to support HabitRPG!" or something similar.

**Comment by Alys** [comment]
seems fixed
