### ISSUE TITLE
Certificate Revoked

### ISSUE THREAD

**Issue by jbutz** [HabitRPG/habitica#3243]
When I try and access https://habitrpg.com/ using Firefox 28.0 on Mac OS X I get a "Secure Connection Failed" error. It says that "Peer's Certificate has been revoked"

**Comment by habitrabbit** [comment]
I'm having the same issue. I'm also using Firefox 28.0, but I'm on Windows 8. 

Full error message I'm getting:

"Secure Connection Failed

An error occurred during a connection to habitrpg.com. Peer's Certificate has been revoked. (Error code: sec_error_revoked_certificate)

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

Please contact the website owners to inform them of this problem. Alternatively, use the command found in the help menu to report this broken site."

**Comment by ChrisInCanada** [comment]
I get the same error in Firefox, when running it on Windows.  Fortunately (unfortunately?) it works in Internet Explorer.  :P

**Comment by deilann** [comment]
I imagine this is related to #3230

**Comment by jbutz** [comment]
Yep, it looks like it is. I didn't see that ticket. I'll close this one.

**Comment by deilann** [comment]
It's not a problem. :) I wouldn't necessarily expect you to piece the two together unless you read every single ticket.
