### ISSUE TITLE
Let buttonless Habits use the full space available

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3260]
It can be handy to add an unscoreable Habit (disable both + and -) as a sticky note reminder of a guiding principle or other concept that's not easy to track discretely. However, doing so comes out looking a little ungainly, since space is still reserved for a button that isn't there:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/2686254/c8d22aa0-c1f2-11e3-96c1-ebe6c74fd2fa.png)

It'd be nice to have the task title fall to the left in this situation, same as it reclaims the space when you remove just one of the two directional buttons.

**Comment by deilann** [comment]
I also use these for lables for sorting.

**Comment by benlind** [comment]
This seems like a simple enough bug for my first stab at contributing code.

However, it appears that the files I'll need to edit are in the /public/bower_components/ and /node_modules/ folders. Both of these folders are in the .gitignore file. Does that mean that I should not edit those files (though I don't know how else I'd fix this bug)? How can I get git to track the changes I make to the files so that I can commit those changes?

**Comment by SabreCat** [comment]
Which directory are they in specifically? If it's habitrpg-shared, there's a separate repo for that: https://github.com/HabitRPG/habitrpg-shared

**Comment by benlind** [comment]
Yes, they were in the shared repo, and I had to clone that one as well. Thanks!
