### ISSUE TITLE
Everything on my account reset?

### ISSUE THREAD

**Issue by KusuKusu** [HabitRPG/habitica#3262]
Yesterday after clearing some browsing data, the game said I couldn't log in. About an hour later when I tried again it allowed me to log in but came up with the announcement saying I'd died - even though I'd been on 30+ hp. All of my tasks, dailies and habits had disappeared, and tasks I'd completed back when I first started reappeared like I'd never completed them.
I was back down to level 1 from 24, with none of my armour or pets and I wasn't in the student party I'd joined any more either. It also says I'm not subscribed any more (though it hasn't been a month since I joined the subscription program) and the pastel hair and extra base hair I'd unlocked... isn't unlocked.

Is this a problem on my end or yours? Do you have a back up of the lost data?

-Kusukusu

**Comment by thebat137** [comment]
I got some kind of similar hit last night that might be related.  I didn't clear any browsing data (at least, not deliberately), and I didn't lose everything the way KusuKusu did.  But here's what did happen:

0) I'm in the middle of a single-player party quest against the ghost stag.  I've missed the occasional daily before against him and taken a few points of damage, but never any really big deal.
1) I completed all my dailies except a single brand new (and therefore yellow) medium-difficulty one.
2) I fell asleep at about 2:30 AM EST with my computer still on and logged in, with my cron set at 3:00 AM.
3) I woke up, returned to my habitrpg browser tab, and saw that my dailies hadn't refreshed from grey status yet.
4) I refreshed the tab and was informed that I'd somehow suffered 40-some points of damage and died.
5) I lose the usual 1 level (19 to 18), one item (my cat suit!), and all of the 500 gold I'd been saving for a shopping spree.  I didn't get fully reset the way KusuKusu did, though, and my subscriber status still appears intact.
6) Many, but not all, of my dailies are grey, as if they didn't register as having been done until today.  There appears to be no specific pattern to it, since it includes ones I'd completed in the morning as well as ones I'd completed in the evening.  I know I synced several times during the day.  I also gained a number of 21-day streaks for the first time yesterday, and somehow only one of them is listed on my achievements, several of the dailies I got the streaks in are listing me as having a 2-day streak now, and my progress bars seem to be showing much of what I did yesterday as having happened today.

Was there some kind of database corruption or clock hiccup yesterday?  And is there anything I can do to get my records straightened out?

**Comment by thebat137** [comment]
Also, I should add that I don't know what to do now.  I feel like I shouldn't be recording stuff for today, because I don't want to add to the confusion if I can get my account restored.  But I also don't want to just sit in the inn all weekend until somebody has time to look into this.  So if anybody can offer recommendations about how to wait out the interval before this gets addressed, that would be much appreciated.

**Comment by KusuKusu** [comment]
Well I'm in a bind since I don't really feel like doing anything at all if everything I've done until now has up and disappeared... A month and a bit of hard work just completely gone, I don't feel like restarting from scratch, especially since I spent money to further the development of the game and this kind of issue crops up not long after. I know there are people who've been working on their characters a lot longer but still... Bit of a downer.

**Comment by thebat137** [comment]
Indeed.  It feels the same way for me even though I've lost less than you have.  I'll admit that I may have been asking for it by setting a non-midnight cron for myself, but it's still pretty frustrating.  Were you using a non-midnight cron too?

**Comment by KusuKusu** [comment]
I'm not entirely sure what a 'cron' is so I'll assume I wasn't using one haha.

**Comment by thebat137** [comment]
KusuKusu, this isn't a perfect fix, but I've just remembered you can sort of restore yourself by going into Settings > Site > Fix Character Values.  You can reset your level, experience, gold, streak count, etc. there, if you remember (roughly) your previous values.  You can also give yourself enough extra gold to buy back your lost items from the market.  If you had any special items this might not help, but it'll fix a lot of things.  If you add your missing tasks back, you can also edit them to put in the correct streak count (last item).  Again, this won't restore all of your lost history, but it'll help some.

**Comment by KusuKusu** [comment]
Thanks! If they haven't backed up my data, I guess that's the best I can do. I'll have to try and find the thread for the party I was in before as well. _sigh_ I should have paid more attention to my stats...

**Comment by Alys** [comment]
@KusuKusu and @thebat137 I'm sorry we never replied to help you with this. :(

KusuKusu's problem sounds like there were duplicate accounts for the same username, with one having much less progress than the other. We've fixed that issue by making it impossible for duplicate accounts to occur now.

thebat137's issue seems to be https://github.com/HabitRPG/habitrpg/issues/4313 - there's an Advice section near the top to help you if it happens again.

**Comment by thebat137** [comment]
Yeah, I should've mentioned, I eventually concluded that mine was a variation on the cron bug, as Alys says.  I began taking steps to be more careful about my cron and haven't had anything like this happen in a long time.
