### ISSUE TITLE
Dying after midnight

### ISSUE THREAD

**Issue by phantomprince** [HabitRPG/habitica#3290]
After midnight, when I refresh the page, I die.  Even if I log out before midnight I die.  I don't know what's going on I lose points every night and then die?

**Comment by deilann** [comment]
Midnight is the default day start. The first time you log in/mark a task/refresh or take any other action, "cron" or day turnover will happen. During day turnover, any unfinished dailies will damage you. This is expected behavior, and if you have many unfinished dailies (or even a few unfinished red dailies), you will die due to lost health.
