### ISSUE TITLE
Suggestion: highlight username you address with @ in the Tavern Chat

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3293]
Many people have names/nicks with more than one word in them. So it may be more convenient to read the Tavern Chat if the name of the one you address will be highlighted in some way. Not necessary circled with the color corresponding to title, as the chat may get too colorful in that case. I vote for underlining or other simple text decoration.
http://oi61.tinypic.com/mw740g.jpg
http://oi59.tinypic.com/15f6eix.jpg

**Comment by wc8** [comment]
The underline looks nice and subtle. I'd rather not have a highlighting effect, for the reasons you mentioned.

**Comment by sbreiler** [comment]
There is a problem with the names including spaces: its too intensive to lookup for the right user in the database at serverside, because the server doesn't know where the name ends.
Example:

```
Hello @some one how do you do?
```

The name could be "some", "some one", "some one how", "some one how do", ... you get the idea.

My approach would be: change the input style of @username to something like
@[user_ name] or @user_ name@
It could be easily added to the popup at the chat input (if you type @) and processed by the server.

**Comment by kangabell** [comment]
@GitHubSphinx Can this be closed, as per https://github.com/HabitRPG/habitrpg-shared/pull/339?

**Comment by crookedneighbor** [comment]
@kangabell Good eye!

**Comment by ghost** [comment]
https://github.com/HabitRPG/habitrpg-shared/pull/339 is a different thing.
I've shared my thoughts here: https://github.com/HabitRPG/habitrpg-shared/pull/339#issuecomment-97937521
So I guess I'd better move my suggestion to trello card.
