### ISSUE TITLE
Suggestion: Enable notification history

### ISSUE THREAD

**Issue by thepeopleseason** [HabitRPG/habitica#3297]
cc: @benmanley 

When replacing growl with pnotify, I backburnered one of the more useful features of pnotify, because I wasn't sure how to handle it in the interface: the history container. At the bottom of the habitrpg page, you'll see  

`<div class="ui-pnotify-history-container well" style="top: -94px;">`

If you use chrome dev tools to push that out to 200px or so, you can click on the 'All' or 'Last' buttons that appear to see the historical notifications (note: the div will hide itself back to -94px after a few seconds). As I mentioned in #3237, the toolbar's z-index overlays the history carat, and there are some other interface issues with just using the existing history, but I think it's a useful feature to include with a different interface. 
##

**Comment by benmanley** [comment]
I’m thinking the best thing would be to somehow incorporate the buttons into the notifications dropdown.

@thepeopleseason Can `div.ui-pnotify-history-container` be moved anywhere without breaking the functionality?

Even better might be to view recent history as a list rather than reactivating all the alerts. Would that be possible? Then perhaps we could toggle between the list of social notifications and the status notifications.

@deilann Is there a naming convention to differentiate between types of notifications?

**Comment by deilann** [comment]
I have no idea! :D

**Comment by benmanley** [comment]
Ha. I was thinking maybe 'messages' for guild & party notifications, etc and 'status' for the pnotify stuff.

**Comment by thepeopleseason** [comment]
@benmanley Not sure. From what I can tell, pnotify add that div in automatically. You can, however access the functions that both buttons call. I documented them as bookmarklets here: 

http://habitrpg.wikia.com/wiki/User_blog:Thepeopleseason/Bookmarklets

**Comment by benmanley** [comment]
Thanks @thepeopleseason. I'll look into using the functions.

**Comment by paglias** [comment]
see also #1562

**Comment by Alys** [comment]
We have this recorded in Trello now as a feature request so I'm closing this issue.
