### ISSUE TITLE
The pets will not gain experience

### ISSUE THREAD

**Issue by Bitterbops** [HabitRPG/habitica#3325]
When ever I hatch an egg, then feed it the correct food, no experience is gained for the pet. I currently have multiple pets and have blown through a lot of food, but not a single one has a green bar. Suggestions?

**Comment by deilann** [comment]
If there isn't a green bar at _all_, then it's probably a display issue. What browser are you using?

**Comment by Bitterbops** [comment]
I am using internet explorer.  There is the shape of the bar, just no green filling in it after any amount of feeding.

**Comment by deilann** [comment]
Yeah. The issue is IE -- it doesn't render the progress in the bar.  Habit
is not optimized for IE. I highly suggest you use Chrome or Firefox.

**Comment by Bitterbops** [comment]
Awesome, it works fine on chrome. Thanks!

**Comment by deilann** [comment]
Np! :)

**Comment by carolhabit** [comment]
Does it record progress on the server, but is just invisible? So, are they actually getting experience without showing it? Or is it just lost? I could record on paper just so I know who I should be focusing on just in case.
I am unfortunately stuck on IE because I use a Surface tablet and from what I can tell there isn't a way around it. An app would be great but that doesn't exist and is faaaaar outside my skill set.

**Comment by deilann** [comment]
Yes, it's just invisible.
