### ISSUE TITLE
'Stealth' overpowered?

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3353]
After the exciting discovery yesterday that I could look at how many dailies 'Stealth' would avoid on a party member's stats (4 in her case, at ~50 PER), I ended up casting it myself today — knowing I was going to miss a few things — and as it turns out, I have enough PER to avoid 31 dailies. I don't even _have_ that many dailies.

Now, granted, I have 158 PER, thanks to a Perfect Day buff, but still 31 seems high. I was expecting the max to be either a lowish fixed number like 10, or most but not all of your due dailies.

Thoughts?

(Addendum: I just went to the wiki and found the calculation, which is Total number of dailies \* PER / 100, so I guess it's user-based. It's not _super_ hard to get up to 100 PER though.)

**Comment by deilann** [comment]
I agree -- there should be a cap that's a percentage of the total number of
dailies.

**Comment by chimericdream** [comment]
This should be addressed in #3029

**Comment by Alys** [comment]
No, we decided not to change Stealth in #3029 because it wasn't as critical or as clear-cut as the other skill fixes. Verabird has some good ideas in https://github.com/HabitRPG/habitrpg/issues/4604

**Comment by chimericdream** [comment]
Oops. That's right. I got a little trigger happy trying to help update old issues.

**Comment by Alys** [comment]
Verabird has fixed this in https://github.com/HabitRPG/habitrpg/pull/4736 and I've decided it will go live as part of the skills rebalancing soon, since it's ready in time. It results in one casting of Stealth hiding a maximum of 50% of your Dailies (so a high-PER Rogue must use 90MP to hide all their Dailies). More details are at https://github.com/HabitRPG/habitrpg/pull/4736#issuecomment-79378076

I'm closing this now for neatness but we can reopen it if it turns out the fix isn't sufficient.
