### ISSUE TITLE
With API, Checklist task id does not register as valid.

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#3362]
I'm trying to set the checklist items to completed.  I can set other task ids to completed, but checklist items ids return a 404 "Task not found"

**Comment by lefnire** [comment]
There's currently no route for checking off checklist items. Instead, save the task with the checklist item set to true. Checking a checklist item doesn't actually do anything on the backend, instead cron looks at what's checked in checklists to do calculations later.

**Comment by fragmental** [comment]
For my purposes, having a route to set a checklist item's "completed" value would be amazing.  Is it impractical, undesirable, or particularly difficult?  I've jokingly wondered if it would be easier to learn enough javascript to make the necessary modifications in habitrpg, than to reconstruct the checklist object in my own code.

The current incarnation of the code assigns the api/v2/user JSON object to generic array lists using foreach loops.  It then uses the generic array lists instead of the the JSON.

I know that not being able to easily and simply modify the checklist JSON object and send it back is either a deficiency in the software I'm using, or a deficiency in my own programming ability, so either way that responsibility falls upon my shoulders.  Having said that...a "completed" route for checklists would make it so much easier.

**Comment by Alys** [comment]
Hi fragmental. I've used the API several times to set checklist items to true, and it's always worked well. It's a reliable method for handling checklists. While it would be easier if we third-party developers could use a dedicated API call to tick off checklists, I can see that building such a call would take a not-insignificant amount of time, and it would need to be done by HabitRPG developers who are already overloaded with many feature requests. I think it's more important that the developers focus on features that help a large number of "normal" users, rather requests for API features, because those of us who use the API are always knowledgeable enough to write our own implementations for anything we need to do.

In this particular case, rewriting a block of JSON data to change a checklist value to true and then PUTting it to the server is pretty simple and fast, so I don't think that a dedicated API call would be of particular benefit. I would say that building such a call is impractical and undesirable simply because there are so many other demands on the developers' time.

**Comment by fragmental** [comment]
No matter how I implement checklists, I'm going to have to learn something new, and I was only asking about the difficulty of implementing the route, to determine if it would be better for me to learn how to do that in habitRPG or learn how to do that in my own code.  Perhaps it was a stupid question.

**Comment by Alys** [comment]
I understand now, however I can't really tell you which is easiest. It depends very much on your learning style and abilities, how your app is already written, what language its written in and how familiar you are with that language already, and a bunch of other factors (you don't need to explain any of these to us; this is just for you own information). The advantage of implementing it in your own code is that you have full control over how it's done, the timeframe it's done in, and you can experiment as much as needed without fear of damaging production code.

I personally have found that working with my own third-party code has been easier than working with HabitRPG's code, simply because I'm more familiar with code I've already written. It's also much less stressful because I know I can't break anything that I can't fix myself. The disadvantage of working with my own code is that of course I cannot expect HabitRPG developers to assist me at all, but I find that's outweighed by the advantages.

**Comment by fragmental** [comment]
Well, I have this working, in my code, now.  I think that in Unity C# it is considerably more complicated than in javascript, but it works.  Admittedly, a better coder probably would have had much less difficulty.

@Alys Thank you for your responses.  I like your data display app.  I've always thought that habitrpg could benefit from having all of it's data more easily accessible and visual.
