### ISSUE TITLE
Api: Upping and Downing Dailies and Daily checklist items does not work as expected.

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#3363]
In the API, Upping and downing a daily works the same way todos work, where the adding and removing of points is instantaneous, instead of waiting for cron.  Upping and Downing  Checklist items works like habits;  points are awarded or taken away instantly, and life is also removed on down.

I also tried simply setting the task as completed, which had it's own difficulties #3362

**Comment by fragmental** [comment]
I'm still having problems with the apis and dailies.  As mentioned Upping and downing a task via /api/v2/user/tasks/{id}/{direction} awards points immediately instead of waiting for cron.  Sending {\"completed\" : true} via put does not actually check the daily, and setting "{\"direction\": \"up\"} via put does nothing. (The \ escaping is a c# thing)

I think the @MagicMicky client is using /api/v2/user/tasks/{id}/{direction} because dailies award points immediately instead of waiting for cron.

**Comment by fragmental** [comment]
Eh...apparently {\"completed\" : true} and {\"completed\" : false} works perfectly fine for checking and unchecking dailies.  My mistake.

**Comment by Alys** [comment]
I haven't done any work related to creating the API, but I have used it a bit and I'm familiar with some of HabitRPG's code. From what I've seen, all kinds of tasks (even rewards) are built so that they all have very similar properties and are controlled in very similar ways. The API seems to be generic in that provides the same methods to all kinds of tasks. Some of those methods might not be appropriate to use with all kinds of tasks, but I believe the API isn't designed to enforce appropriate use. Instead, it gives a third-party programmer all the methods that are essential for controlling tasks "properly" and also the flexibility to use those methods more creatively if desired.

Since I don't know what you're using the API for, it's hard to give specific advice, but in general I'd say that if you want tasks to behave exactly as they do in the HabitRPG website, then write code that limits which API features can be used (e.g., if the task is a plus-only habit, then don't allow "down" to be used).

For assistance with the API, it's probably most helpful to report which "proper" actions you are NOT able to do. For example, for a daily, one "proper" action would be marking it as having been completed that day, so if you are NOT able to do that, you should definitely say so. As a counter example, using "down" on an uncompleted daily is clearly not a "proper" action, but if the API allows you to do so, I think it would NOT be worth reporting that, since it would be merely a side-effect of the API being a generic tool, and you could avoid the problem by not using the "down" feature with uncompleted dailies.

"Upping and downing a daily works the same way todos work, where the adding and removing of points is instantaneous": I believe that adding points ("up") should be instantaneous. In the HabitRPG website, as soon as a daily is marked completed, you get XP and GP. I think downing a COMPLETED daily should also be instantaneous, because it is (I assume) the same as unticking an incorrectly ticked daily. Downing an uncompleted daily, as mentioned above, is not a "proper" action, so the API's behaviour for that is irrelevant; a third-party programmer can write code to ensure that the user can't perform that action.

I think (but am not certain) that support for the MagicMicky client can't be obtained in this github branch. It's an unofficial third-party client and I don't know if MagicMicky reads issues here. The best way to seek support for that client or to report problems with it, would be to use the app's contact details from the Play store.

At this point, it would probably be helpful to see a summary of which "proper" actions you are still not able to do with the API.

**Comment by MagicMicky** [comment]
Hi there @fragmental . I didn't answer there because you seemed to have found an answer to your question.
So, what I do in my app is upping a daily (using `/task/{id}/up`) when a user check it, and downing it when he uncheck it.
But I guess it works the same way setting `complete:"true"` using the PUT api

**Comment by fragmental** [comment]
@MagicMicky Thanks.  `{"completed" : true}` sets the task item as completed, without assigning points

@Alys Thank you for your response.  This is related to my habitRPG client I've been building with the unity game engine.  The old release can be found at www.fragmentalstew.com.

I realize now that upping and downing works as intended.  I thought setting the task to `"completed" : true` wasn't checking the task, but it is.

I still don't have checklists working, but I'll continue the discussion at #3362
