### ISSUE TITLE
Egg hunt: "Egg Egg" instead of "Plain egg" tooltip in inventory

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3369]
I'm sorry, if it's a false alarm, but I really don't understand the mechanics of naming eggs obtained from the Egg hunt quest: I've already told @paglias that it doesn't fit into translation pattern in Russian and possibly some other languages (as we agreed to have "in the egg" in translated version instead of a simple "Egg" for the sake of grammar in ("Animal"+"Egg") phrases) and in the "Egg hunt" quest "Egg" is both an animal and an Egg, as it seems. So what really would help is to have "Egg-as-a-pet" as a separate line from the second ordinary "Egg-as-just-an-Egg".

Anyways, it really looks strange even in English to see "Egg Egg"'s instead of " Plain eggs " in inventory. If it's meant to be like that, then I just want to ask the quest writers to try to avoid such solutions in the future and consider having independent strings (text lines), that will be easy to translate.

**Comment by deilann** [comment]
I believe it's meant to be done like that. The point of not calling them
"Egg Eggs" in the quest is because that would be a spoiler as to what they
do.

So go ahead and translate the quest as if they're "Plain Eggs" but
translate the item as if they're "Egg Eggs"

It would be like if you got "Mysterious Eggs" but then in your inventory
after the quest you found out they were "Dog Eggs"

There's no real way to get independent strings for the eggs.

**Comment by ghost** [comment]
Thank you, now I can see all the points except for the last one... "Egg " is used as a pet, right? Why not use just additional translation variable for this case?

**Comment by deilann** [comment]
So, "Potion Color" + "Egg" is the pet name. Egg names are generated by "Pet
Name" + Egg. So if we want to have a "Cotton Candy Blue Egg" then "Egg" has
to be the petname. Therefore, the egg name is "Egg Egg."

Is the same string "Egg" being used for "Pet Name" Egg and all other eggs?
If that's the case, I would definitely have no issue with "Pet Name" Egg
being its own variable.

However, we can't not have it show up as "Something" + "Egg" and that
"Something" is going to be in the pet name, due to the way the pet system
works.

**Comment by ghost** [comment]
Yep. I'm talking about having "Egg-as-a-pet" an independent variable from "Egg" so that we could compile "Egg-as-a-pet"+" Egg" and which is more important "Potion name"+" Egg-as-a-pet" - just for the sake of grammar, with no quest spoilers or whatever. In fact I've seen @paglias updated some strings on transifex, but I have no time to look at it till Wednesday. So it may be the case it's been already changed, or simply I haven't found the right strings yet

All in all, thanks to your explanation, I believe the ticket may be closed, I'll just mention it on the i18n master ticket for @paglias to have a look...

Thanks again!

**Comment by deilann** [comment]
Yup! That's all good. :) But yeah, keep "Plain Egg" as its own thing, methinks.

(Also, if you didn't know, you have the ability to close your own tickets.)
