### ISSUE TITLE
Integrate with If This, Then That

### ISSUE THREAD

**Issue by MatthewDarling** [HabitRPG/habitica#337]
[IFTTT](http://ifttt.com/) has been around for a while, and you can do some pretty cool stuff with it. I get the impression they don't add a lot of new channels to their service, but being able to activate things when a certain task is completed and so on would be neat. Inspired by [this](http://lifehacker.com/5981625/), I"d love the have something like "fail a daily, turn off the outlet".

Also, you'd get SMS+email+etc integration for free, as users could text to IFTTT in order to activate things on HabitRPG.

They've got a page for being added to the channel list [here](https://ifttt.com/platform).

**Comment by lefnire** [comment]
Actually, moderators - I think this one might be worth looking at as it's
sort of a catchall for many services. Might save us some time

**Comment by ghost** [comment]
This would save us a lot of time in the long run but if IFTTT ever has problems everything goes down not just one specific thing.

**Comment by danj3ris** [comment]
Im surprised at myself for not thinking of this. I currently use IFTTT for email to sms alerts. Actually, just being able to have HRPG send you reminders, possibly utilizing IFTTT, would be fantastic.

"If daily is not complete by 7pm, send email" for instance. Good suggestion @MatthewDarling.

**Comment by elssar** [comment]
Actually, there is an IFTTT like service that you can use, to complete tasks. [Zapier](http://zapier.com) has webhooks(watch or call an url), so you can fire a task with various triggers, like say posted a blog post, or pushed code to github. And when the API is extended, you could use tasks as a trigger.

AFAIK, IFTTT does not support webhooks, or have any way of polling a url.

**Comment by StanLindsey** [comment]
This actually seems pretty awesome, I assume they have a bunch of the APIs we want to incorporate so as you say Tyler, could be a great catch all. 

We just provide an API and create some sample "recipes"? 
Do they have an API that we can incorporate into a section on HRPG? (So people don't have to leave the site)
Does every user want 2 logins to make the most out of HRPG or is having native API support (through the site & extensions) more valuable?

**Comment by Pandoro** [comment]
This is actually one of the concerns I have had as well. If we integrate 10
things, that is great for current users of these applications, but I'm not
sure if I want to start using an application in order to integrate it into
habitrpg. PROBABLY I would, but it wouldn't feel that good. So everything
which you could log into with habitrpg would be awesome ;)

**Comment by horusofoz** [comment]
Added to [Trello](https://trello.com/c/kcuVB0ZM).

**Comment by jessicalc** [comment]
this. would. be. AWESOME!

**Comment by fuzzyweapon** [comment]
While I would love this, and the ability to create things in HabitRPG (so data coming in, not just going out)...it sounds more like a /shortterm/ win.  However, the gains here could be so much that implementing something like this first while hacking away at high value more reliable and robust direct integrations would be a great user experience over time.

I do however worry about this route, because I believe that a lot of  these services are freemium, either by the amount of recipes/integrations you can specify, or things like polling frequency, etc.
My concern here from the user perspective is that this now starts to put an onus on your integration heavy users (probably the ones already subscribing to HabitRPG in the first place) to then pay more money through another service.

For a user, that's a terrible experience.  That's why I think doing this in the short term, and using the longterm to develop support for a quicker and code clean way to develop integrations would be a good route to consider.

**Comment by Alys** [comment]
@fuzzyweapon Have a look at the API at https://habitrpg.com/static/api. It provides ways to read and modify many aspects of HabitRPG's data and is the ideal way to integrate with HabitRPG. IFTTT would be used for services that can't or don't have time to or don't want to develop custom HabitRPG integrations (which is probably most of them, unfortunately).
