### ISSUE TITLE
Recurring to-dos upon sync

### ISSUE THREAD

**Issue by tvaz** [HabitRPG/habitica#3387]
I have had a problem for a few days now where whenever I sync (on my iPhone app or the web app) two todos from a long time ago continue to recur and no matter how many times I check them off on my phone, web and both they always come back upon sync. How can I fix this?

**Comment by Alys** [comment]
Have you tried deleting the todos instead of checking them off? If not, please try that, using the web interface (there should be a trashcan icon next to each of them).

If that doesn't work, tell us your [User ID](https://habitrpg.com/#/options/settings/api) and also paste in the text of the todos (not the Extra Notes).

Are the todos from a challenge? Is there a megaphone icon in them, like you can see in [this image](http://img4.wikia.nocookie.net/__cb20131125120558/habitrpg/images/thumb/5/5b/Challenge_megaphone_icon_in_habits.png/640px-Challenge_megaphone_icon_in_habits.png)?
