### ISSUE TITLE
Item on me that's not in my equipments anymore after reset (deilann: reset does not dequip new gear types)

### ISSUE THREAD

**Issue by ShadowSky13** [HabitRPG/habitica#3392]
Ok so a while ago, maybe a week or less, I reset my account. When I did, all my equipment items reset like normal, except the dog ears I bought from the spring event in the rewards section were still on my icon. They don't show up in my equipments page, and I can't get them off. I was going to save up to buy them again to try and take them off my icon regularly, but now all the spring items are gone. I also just tried to overwrite the code or whatever by buying a head armor item, but the ears are still there when they shouldn't be.
![untitled](https://cloud.githubusercontent.com/assets/7461445/2856580/d0ce08a4-d16b-11e3-89b0-ab3c36dacad4.png)

@deilann sez:

To fix:
- [ ] update reset code to dequip any back accessories or head accessories

Related: Rebirth also does not dequip these items.

**Comment by deilann** [comment]
The ears are separate from head armor -- they're a head accessory. So
buying head gear is not going to help.

The issue here is that reset hasn't been well-maintained. So reset does not
dequip back accessories or head accessories.

**Comment by deilann** [comment]
If you find this to be an issue, you can put on a costume -- that should hide them.

**Comment by ShadowSky13** [comment]
I've acturally tried that what I first noticed it after resetting, and I just tried that now as well and it doesn't hide it unfortunately.

**Comment by deilann** [comment]
Ach, you must have had it on as a costume as well then.

**Comment by ShadowSky13** [comment]
Yeah I did. I don't remember if I had it on for real, but I did have it as my costume. Is there anyway to reverse this then? (I have to go do laundry now so I'll be back later, hope this isn't a problem.)

**Comment by deilann** [comment]
Not at the moment, no.

**Comment by ShadowSky13** [comment]
I see... I'll be looking forward to when this can be fixed, though I get that this isn't a priority, it's just an annoying bug.

**Comment by ld89** [comment]
Sorry to bump such an old topic, but I'm having this same issue. I spent gems to reset my character specifically for a costume change (I changed to healer to get the mer-gear), but I had rogue's cat ears from the spring event on when I rebirthed and now they won't come off. D: Is there a way to at least rebuy the cat ears and take them off the old fashioned way? When I used the rebirth orb, it did say event gear would be repurchasable, but I don't see any of it.

**Comment by deilann** [comment]
The reason you can't repurchase them is because you are not a rogue.

**Comment by ld89** [comment]
Oh, okay! That...makes sense. In that case, two things:
1. Theoretically, if I shelled out the gems/cash again, and bought another rebirth orb, got back up to level ten, and rebought the cat ears, I could take them off properly, right? (Then buy another orb or rebirth etc so I could go back to playing healer.) This would absolutely be worth it to me. I know this is classified as a minor bug, but the pets and costumes are my primary motivation for playing habitrpg. I haven't even logged into my account since my costume messed up. I just 
   hen buy another orb or rebirth etc so I could go back to playing healer.) This would absolutely be worth it to me. I know this is classified as a minor bug, but the pets and costumes are my primary motivation for playing habitrpg. I haven't even logged into my account since my costume messed up. I just want to check before I spend the money.
2. Perhaps on using the orb of rebirth, where you explain what you lose and keep, there could simply be a warning that you need to unequip all your gear before changing? I think that would do quite a bit to prevent this from happening to anyone else until the bug gets fixed (since it doesn't seem to be urgent, it could be awhile). I don't know much about coding but I can't imagine it would be a horribly complicated addition?

**Comment by deilann** [comment]
It would actually probably be about the same amount of effort to fix it than to add the warning.

However, with the summer equipment, you can fix this without any workaround! Equipping any head accessory will fix it.

Also, did you know that for much cheaper than an orb of rebirth you can simply change your class? For 3 gems, you can purchase a class change under the stats page.

**Comment by ld89** [comment]
Oh MAN, I wish I'd realized about that class thing earlier. That's great news, thanks for letting me know! Unfortunately my ears are on with my costume and my pirate eyepatch without, and equipping a head accessory in either case still has them both showing up. So, I'll try switching classes back to rebuy them and take them off. Worst case scenario is just that I've wasted three gems.

**Comment by deilann** [comment]
What's your UUID?

**Comment by ld89** [comment]
User ID? It's fa28b8a2-16fd-4377-ad3c-3b11b8ce4bec.

**Comment by deilann** [comment]
Refunded you some gems for your trouble. :)

**Comment by ld89** [comment]
Oh my gosh, THANK YOU so much!!!! For the record, switching classes back to rebuy and unequip the items in question worked PERFECTLY.

**Comment by deilann** [comment]
Glad to hear it. :)

**Comment by Alys** [comment]
duplicate https://github.com/HabitRPG/habitrpg/issues/3377

I'll be uploading a fix for this along with some changes to implement eyewear in (probably) a couple of days.
