### ISSUE TITLE
Mounts without bodies on the Mounts page

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3397]
Since I don't even know when Mounts has no bodies, only heads and wings (dragon).
Graphic is loaded correctly.

http://imgur.com/KcxNT11

**Comment by deilann** [comment]
I'm not sure what you're trying to say? The mounts page only shows the
mount head -- otherwise the mount page would be huge!

**Comment by ghost** [comment]
so maybe better would be to be just heads (without wings) and without this spacing, that suggest that something should be there? It doesn't look right.

**Comment by deilann** [comment]
I still don't understand what you're saying.

The dragon also has wings because mounts are actually two-part images. The
mounts page uses the further front image that goes in front of the avatar.

**Comment by Aquea** [comment]
I think the author says that it looks like a bug, because the positioning of the head to the top left suggests that there should be something loading in the rest of the empty space. Suggestion is to centralise the heads' images on mount page so that they do not confuse.

**Comment by deilann** [comment]
That is easier said than done. The image is not a centered image.

I'll leave this open -- I agree that it would look cleaner. But it's a more significant amount of work than one might think.

**Comment by quin-jay** [comment]
I was actually thinking of taking this on, or at least part of it. Perhaps we could add a different batch of sprite files called "Mount_Face{{mount}}", that would have the head more or less centered but not have the complete wings in the image too. These would only be called on the Mounts page, so that actual rendering of the animal in the avatar wouldn't be disturbed. I don't mind doing all that in photoshop; it'll be busywork so I can feel super productive without working too hard ;)

I also have been trying to organize the Mounts page like the Pets page, but I haven't been able to track down which documents to modify. _stable.jade_ looks promising, but I think it would also require creating some things such as _content.questMount_ in some other place, so I'm not sure where I should start.

**Comment by quin-jay** [comment]
Update: I've figured it out! I submitted a [pull request to reorganize the mounts page](https://github.com/HabitRPG/habitrpg/pull/3906), and if that gets approved I think making new icons just for the stable will be my next pet project (no pun intended!)

**Comment by Alys** [comment]
@lynnyliz : I think it should be possible to show only the heads of mounts in the stable without creating new images. All the image sections you need are already in the sprites, so you could probably use just CSS to display the correct portions. This would have the advantage of not significantly increasing the size/number of sprite files and not requiring extra image creation when new mounts are introduced. I would guess that all that would be needed would be adding a section to css/css.template.mustache and an associated "if" statement in Gruntfile.js, and then a small modification to the class name in stable.jade. I haven't looked into it in detail though so there might be more required.

**Comment by quin-jay** [comment]
*takes notes*

That'll take a little more reading up, I think, but I'm excited to give it a try! Thank you @Alys for telling me where to start :)

**Comment by crookedneighbor** [comment]
This is currently being worked by replacing mounts with head only version of the mounts on the moutns page. Closing this.
