### ISSUE TITLE
Self and party killed when checked tasks/dailies did not record at all

### ISSUE THREAD

**Issue by freedomshocked** [HabitRPG/habitica#3416]
All checked off around midnight (5/5), deadline set to 3am MST. Log-in today (5/6), nothing was counted, party is dead.

**Comment by Alys** [comment]
Please add your [User ID](https://habitrpg.com/#/options/settings/api) (not API Token) and your party's [Group ID](https://habitrpg.com/#/options/groups/party) (left-hand column, in the box that has the name of the party). Can you also tell us how many dailies you have? Please also add a screenshot of the party page showing the line that describes how much damage the boss did due to your dailies (see the message under the "Write" box for how to add images).

When you checked off your dailies, did you check them off all at once (i.e., all of them around midnight), or did you check off some of them at different times of the day?

**Comment by deilann** [comment]
Check out [this section of the FAQ](http://habitrpg.wikia.com/wiki/FAQ#My_character_died_when_it_shouldn.27t_have.21_What_do_I_do.3F)

Things that can increase the chance of dailies not syncing include clicking quickly. Always wait for the blue bar to finish before clicking another task.

**Comment by freedomshocked** [comment]
My first bug report, apologies for not including everything!

As requested @Alys 
UserID: 009b2f28-a6fb-4981-8656-48cd5d7ef61f
Group ID: b98e44a2-b105-426e-9f16-a8707aab8ee9
Number of Dailies: 23

![screenshot 2014-05-05 at 2 01 29 pm](https://cloud.githubusercontent.com/assets/7491170/2882574/4061ca12-d490-11e3-8698-5bc459c3d689.png)

Unfortunately I mass clicked, very quickly, as well as on my habits. Seems that is an issue I wasn't aware of! Crap! Thank you for bringing it up also, @deilann .

**Comment by deilann** [comment]
Click slowly and carefully, and all should be good. :)

Luckily, death won't do anything wrt the quest and everyone in your party can fix themselves up with Fix Character Values.
