### ISSUE TITLE
[day change] tasks reset in sync with midnight even with custom day start

### ISSUE THREAD

**Issue by Aquea** [HabitRPG/habitica#3430]
I have Custom Day Start set to 9, so my game day starts at 9 in the morning. If I check out of the Inn at 8, I lose a game-day because my tasks do not reset. If I check out of the Inn the night before, everything resets at midnight and the next game day starts after midnight instead of at 9. The expected result would be that tasks etc reset when my custom day starts, not at midnight, even when checking out of Inn.

**Comment by deilann** [comment]
Generally, you have to check out of the inn with more than an hour for cron
to run.

However, the rest is very strange. When are you logging in? Cron doesn't
actually run at your custom day start -- it runs when you first log in
after your custom day start. Did you log in between 9 and midnight
repeatedly and cron did not run? Then, when you logged in after midnight
(but before 9) cron ran?

**Comment by Aquea** [comment]
I usually log in a couple of minutes before 8, so I assume cron should run fine given it has more than one hour before custom day start. But every time when I logged in in the morning, and checked out of the Inn after weekend, I lost Monday. 
I haven't tried logging in earlier. I have no other issues tasks throught the day, and I log into HabitRPG several times in the afternoon.

**Comment by deilann** [comment]
Okay, that sounds like you're getting a #1057 after coming out of the inn, but not that your CDS is using midnight. Sound right?

Are you going into the inn every weekend? It might be more convenient to simply set your dailies to be weekday only, rather than go into the inn every weekend.

**Comment by Aquea** [comment]
I have weekend dailies too, but there was a period when I had no internet access on weekends and I solved that by going to the Inn.
Yes, the problem sounds like #1057 although it only occurs when I check out of the Inn, Otherwise, my tasks re-set just fine. Does cron only happen at a set time, or should the tasks reset if I leave at least a hour before my day start?

**Comment by deilann** [comment]
Cron does not happen at a set time. So here's what happens with the inn:

1) You tasks do not reset whilst in the inn.
2) You check out of the inn
3) Next time you log into the site after your Custom Day Start cron runs

Cron in general only runs once you log in after your custom day start -- it
does not happen automatically.

**Comment by Aquea** [comment]
Ok, so here's what happens on my end: 
1) I'm in the Inn
2) I log in and check out of the Inn
3) 9 AM hits, which means it should be my custom day starting
4) I log in. Cron doesn't happen. Tasks remain checked after hitting "sync", checking a new task (like one I hadn't checked before going into Inn or that became active while in the Inn), re-logging.

So I figure something is wrong.

**Comment by deilann** [comment]
Yes, I agree something is wrong.

I think what you're doing is triggering #1057

I've had similar things happen with me and the tavern and Custom Day Start.
I think it has something to do with the timestamps, which is being looked
at. That bug is a doozy.

I'd imagine that not going into the inn on the weekends would help, but if
you aren't having stable internet, that's obviously not an option. What you
could do is temporarily (until you know you'll have internet access on the
weekends) disable your weekend dailies. You can still check off grey
dailies, so if you do have internet access, you'll be able to check them
off. And if you don't have internet access, they won't hurt you.

It's not the best solution, but I'm hoping it'll keep it from happening.

I'm gonna close this ticket -- if you could share this info in #1057,
that'd be rad. We can keep up the convo there, need be.
