### ISSUE TITLE
Maximum mana decreased?

### ISSUE THREAD

**Issue by Sethycakes** [HabitRPG/habitica#3456]
Hello! I am a level 100 Rogue, and a few days ago my max mana was somewhere in the 200s, but today it decreased to 175 and I don't know why. I'd love to post some more details, but I don't feel like there's anything else to say.

Oh, and my browser is Google Chrome, my UUID is 8a1db51b-01f8-4794-8f9b-a0da605b9bcb, and I get no Chrome console errors related to HabitRPG (I do get Twitter-related errors, but I don't think that's relevant).

**Comment by thepeopleseason** [comment]
Did you recently lose the effect of either the Perfect Day buff or the Ethereal Surge party buff? Have you switched equipment? You can read about how mana fluctuates [here](http://habitrpg.wikia.com/wiki/Mana_Points_%28MP%29).

**Comment by Sethycakes** [comment]
Hmm, I think the Perfect Day might be it! Is there a way to restore it? Because yesterday I checked off all my dailies, but for some reason HabitRPG didn't think I did.

**Comment by thepeopleseason** [comment]
Sadly, no. Several people recommend reloading after you've clicked your final daily of the day to make sure that all of your checks have made it to the server. I'd also suggest using Alys's [User Data Display](https://oldgods.net/habitrpg/habitrpg_user_data_display.html), because, in my case, that's easier than scrolling down 70 or so dailies to make sure they're all greyed out. 

I'm going to go ahead and close this ticket, since there's not really any issue with the code itself in this case.

**Comment by deilann** [comment]
@thepeopleseason You might enjoy this:
http://userstyles.org/styles/100649/hide-completed-dailies

**Comment by thepeopleseason** [comment]
@deilann: I just posted that style to the wiki under the Customizations page! I don't use it because there are some grey dailies that I check off when they're not due. I tried my darndest to figure out how to differentiate the checked vs. unchecked greys.

**Comment by deilann** [comment]
@thepeopleseason I do, too, but I just disable the style when doing that.
:) Super peasy with Stylish to do that.
