### ISSUE TITLE
Strings in a foreign language

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#3466]
I was terribly excited by this message until I a) looked at my inventory, and b) looked up what a kartoffel is. 

![screen shot 2014-05-14 at 17 08 57](https://cloud.githubusercontent.com/assets/1575692/2979106/b8347468-dbc5-11e3-8bb2-caa528b0e963.png)

I'm in the US and I've never had anything on HRPG, my browser, or my system set to German.

Attempted to replicate and got an esqueleto hatching potion. This is actually really fun! But if it's not intentional then I guess you probably want to fix it. 

Using Firefox 28 on Mac OS 10.9. UUID: 9b508a2e-1d1b-44ee-a437-266583e756e3

**Comment by hattieshoe** [comment]
This appeared to happen at the same time -- is it related? On my Tasks page, my stash of snowballs says "String 'spellSpecialSnowballText' not found." instead of "Snowball." The comment when I hover over it says the same thing.

**Comment by deilann** [comment]
Man, I wish I still had snowballs.

Yeah, it's likely related.

**Comment by lefnire** [comment]
Yes related. Not just food names (and outlier snowball), but drops in
general. If anyone experiences anything BUT drops (and snowball), report
here. Fwiw this is minor-medium prio. We'll fix soon, just don't want devs
panicking due to all the recent commotion.

**Comment by Alys** [comment]
snowball issue not directly related to the translation things. It was just a typo in a couple of places.

**Comment by Astu04** [comment]
I have just recieved this: "You've found a Fraze! Nourrissez votre familier avec ceci et il pourra se développer et devenir un robuste destrier." 
I'm in Spain and my computer is set to English, my game is in English too. 
My user-ID is 4f72f741-e268-4f13-86e4-275fdc13488c, I'm using Debian  and Iceweasel 24.5.0.

**Comment by phillipthelen** [comment]
The /content/content API call returns a bunch of strange things. Both from my app and directly through Swagger UI the result seems to be the same.

Quests are completely lacking any strings. (Things like amount of life is still there. just none of the strings). Also Gear, Food, Eggs, Hatchingpotions are missing the "text" field (the name of the object that is presented to the user.) Eggs, Hatchingpotion and Food (sometimes) have their description text in a random language.

This all seems to be connected to some issue with translations, as it only affects strings that would appear translated.

**Comment by phillipthelen** [comment]
https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee

Here in line #6. Where does the lang variable come from? As content api calls are done without authentication, it can't be the language the user set, right? Maybe that's where the problem comes from? That no language is set and it just randomly picks languages when loading the strings? (or no language at all resulting in an empty string)

Sorry if this is no help. My Javascript skills really aren't that great. I just thought it might be the problem

**Comment by tjwds** [comment]
This has got to do with inventoryctrl.js, since the locale stuff was updated but it has yet to be implemented there.  See @paglias and I's solution that has yet to be tested (I've been really busy) https://github.com/HabitRPG/habitrpg/pull/3428

**Comment by paglias** [comment]
@vIiRuS Ok, first of all sorry, this change was unannounced and I didn't thought about content api.

For normal api endpoints the language of messages is get from the user's system or from the settings if he has decided to use a custom language.

Content api call, instead, doesn't return a plain string but each object's string have been migrated from plain english strings to functions that need to be supplied a language (https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L6). In internal api calls this is handled by the system, if you want to display strings manually you have to set the language on your own.

For example:

`content.gear.weapon.base[0].text('en')`

The language code is a two letter code choosen from the ones avalaible [here](https://github.com/HabitRPG/habitrpg-shared/tree/develop/locales). Trying a missing language will cause problem, will fix it so that it fallbacks to english.

Drops in a random language is a separate issues, hope to fix it soon.

> Also Gear, Food, Eggs, Hatchingpotions are missing the "text" field (the name of the object that is presented to the user.) 

Mmm... Every string is translated, can you point me to an example?

Let me know if you need anything else.

**Comment by phillipthelen** [comment]
I'm not sure what you mean with "you have to set the language on your own". The content API doesn't return any translatable string (besides a few, which are in a random language).
https://habitrpg.com/static/api#!/content/content
text and notes are missing from the json. This probably isn't because they are missing, as it affects nearly everything.
Would a possible fix maybe be, to provide an optional GET parameter to the content api call, that contains the language? That way every string could be translated to the language if the parameter is supplied and if it is not supplied, they are returned in english.

**Comment by paglias** [comment]
@vIiRuS f*ck... https://habitrpg.com/static/api#!/content/content you're right, json doesn't serialize functions.

Let me work on a fix

**Comment by phillipthelen** [comment]
depending on how much work my idea is, maybe hardcoding it to english for now is the best quickfix?

**Comment by paglias** [comment]
@vIiRuS optional query paramater with hardcoded english for ease of use and also backward compatibility. it may be a little slower than it used to be

**Comment by phillipthelen** [comment]
As this API call usually isn't used that often I would say the ease of use and backward compatibility is preferable over a little speed decrease

**Comment by Alys** [comment]
@vIiRuS, you can work around it with a bit of a nasty hack. Take the "gear" object from  dist/habitrpg-shared.js (and the "event" and "mystery" objects which it relies on), and use the type, klass, and index attributes from the API's "content" JSON data to extract the correct "text" value from the "gear" object,  then do a lookup in locales/en/gear.json from habitrpg-shared to get the English (or whatever) name of the item. It's messy but it works. If you want to see the code I wrote yesterday, it's here: https://github.com/Alys/tools-for-habitrpg/commit/e515159a870396a1c8b8a56e24419cc8070f8083  (although that relies on the "gear" etc objects being copies into the code, which would have to be re-done every time new gear was updated; like I said, messy).

**Comment by paglias** [comment]
@vIiRuS the speed decrease is coming anyway as the strings must be compiled, even in english

**Comment by paglias** [comment]
@vIiRuS @Alys fixed, sorry for the incovenience. Will arrive with the next version of the site, but if you clone the repo locally you can test it

**Comment by paglias** [comment]
The good news is that I've been able to replicate the issue.

@lefnire @deilann try this: fetch the latest commits, open `http://localhost:3000/api/v2/content`, then try another language `http://localhost:3000/api/v2/content?language=it` most strings will be cached in the old language, not only drops.

**Comment by paglias** [comment]
@lefnire @deilann and if you add `console.log(locale)` [here](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/i18n.coffee#L17) it will show that is the locale being cached (most of the times but not always...). Going to bed now, maybe you'll find a solution to the mystery

**Comment by paglias** [comment]
Ok this is totally crazy, strings compiled are fine (https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/i18n.coffee#L21), strings uncompiled gets cached

**Comment by paglias** [comment]
@lefnire pushed hotfix for the issue, have NO IDEA why is this happening and we need to revisit it with a real solution for performances but... it works https://github.com/HabitRPG/habitrpg-shared/commit/f1e1ea11eff011bb8832c6c8a3fc88ca981dd404

**Comment by phillipthelen** [comment]
@paglias just saw, that the update already is live. thanks a lot, works great!
