### ISSUE TITLE
Random LvL ups

### ISSUE THREAD

**Issue by Flightone2** [HabitRPG/habitica#347]
Keep up the good work I love this app!

So me and my gf use this app and we have both noticed that our levels have raised for no explainable reason. 

First it was hers about 2 weeks ago. She got a game over message one day (Maybe left a FB page open?) and when she reset her level had gone from 2 to 5.

As for me last week I died (probably from leaving FB up) and when i restarted I went from level 2 to level 5.

Is this a bug? and if we keep playing will it effect our store items and experience?

**Comment by StanLindsey** [comment]
I take it you're using the chrome extension as you're referencing websites. I'm planning on putting in a check for if you've not been active on a site in a while so sorry for your deaths! I guess you've learnt the extra hard way. 

Are you saying that on death you were level 2 and then when you're character reset you were level 5?

**Comment by Flightone2** [comment]
yes, i was level 2 when i died. I went back to level 1 actually. Then when i checked back about a day later i had increased to level five. I think this has happened to my girlfriend more then once too.  

 Thing is i know this is beta so we are kinda just rolling with the punches but I'm not sure why this happened and if it will effect us in the future as far as leveling up buying items and stuff like that.

**Comment by StanLindsey** [comment]
Well again, if you're using the chrome extension it could be possible that you've left your browser on a productive site and that is giving you a lot of EXP. But you'd have to leave it on for a hell of a long time. 

Under Habits do you have one called "productivity" - that is the habit that the chrome extension links in to. If its there can you take a screenshot of the graph and post it? It'll give us an idea of how often the extension has posted to your character. 

If its not the extension then it is something @lefnire will have to look at, but you're the first person to report this error.

**Comment by Flightone2** [comment]
![habitrpg progress](https://f.cloud.github.com/assets/3385790/141545/9080491e-724f-11e2-8d12-8052d0e9a820.jpg)

**Comment by Flightone2** [comment]
yea i'm using the chrome extension. I agree it might be that but her problem happened before the positive productivity add on i think. And 3 levels is a big jump..

**Comment by StanLindsey** [comment]
3 Levels is huge in terms of EXP. Plus everytime the habit is put up or down it is worth less or more. 

I'm going to look into it and hopefully a check so that you can't be scored say more than 5 times without changing page will be a good way to stock it when you leave your site up. (Atm it should only score on the active window, so it shouldn't be multiple windows doing it)

We have only recently fixed a number of big time bugs with server stability, so how recent were these issues?

**Comment by Flightone2** [comment]
Thanks A lot for the help! It happened A while ago. before big bug fixes.. I'd say mine happened a week/ week and a half ago. But hers happened more like 3 weeks ago.. 

If it doesn't effect much we are willing to just keep going with it. but if it effects how the game is played later on id rather delete and start over.

**Comment by StanLindsey** [comment]
Ah if its that long ago that I'd place my bets on it being one of the server issues we were having. If it happens again, let us know but I think you'll be okay. 

At the moment it has no bearing at all, only on how much experience you need to progress to the next level. Plus due to the fact that people level at different paces (due to how they play) we don't want to make levels too much of a limiting factor at all. 

Either way thanks for reporting this! At the very least you gave me a good idea for the extension!
