### ISSUE TITLE
Undeletable and repeated todo

### ISSUE THREAD

**Issue by BlackEdder** [HabitRPG/habitica#3471]
I've got a todo that I can't delete and that is repeated about 9 times in my todo list. It is called "Reply to Judith". My user id is:
62cf3b41-a297-4dd9-aa2d-2d1e051abbde

Note that this is likely caused by me using the API wrongly. I've been trying to develop my own todo list app, that integrates with HabitRPG and might have misused that in some way :(. I've tried deleting it using the API, but that also didn't work.

If you have any idea what went wrong then I might be able to fix my app so it doesn't happen again.

**Comment by Alys** [comment]
What happens if you tick off the todos? Do they all disppear? And then when you go to the Completed tab, do you see them all there? After one has been ticked off, are you able to delete it from the Completed tab? After they've all been ticked off, when you clear completed todos, do they all disappear again (and still not appear on the uncompleted todos tab)?

**Comment by BlackEdder** [comment]
When I tick one it will disappear (but not the others). After a sync it is back though. When I tick a second one the first one will appear again and I will get deducted money etc (like I unticked a previously done todo). Clearing the completed todos after ticking one causes the list to empty, but like before if I refresh it is back under non completed todos.

**Comment by Alys** [comment]
You said initially that you can't delete these todos, but is what's actually happening that you CAN delete them but then they come back? That's an important distinction, so let us know.

Is it possible that whatever you created with the API is still running and is still putting tasks into HabitRPG? If so, track down that process and kill it, see if that fixes the problem.

If that doesn't stop it, it might help if you tell us exactly what you were doing with the API, in full detail.

**Comment by BlackEdder** [comment]
I cannot delete them. With ticking them I meant ticking them as done, not deleting them. Pressing delete (the trash icon) does nothing. And with causing the list to empty I meant causing the completed list to empty. (Sorry for the confusion)

I'm pretty sure that if you look in the database under my user id you'll find that there are some wrong entries in there that confuse habitRPG (maybe the id field was not properly initialized before I added them). 

The process is not running continuously. Basically the app just adds new todos to HabitRPG.

**Comment by Alys** [comment]
For privacy reasons, only a very few (maybe just one) of the people who work on this site are able to look in the database. He/they need to prioritise site bugs that affect many users (and we have a couple of such bugs at the moment), so they probably won't be able to look at this immediately.

Did you use a test account for this, by any chance? If so, I'd recommend just [resetting or deleting](https://habitrpg.com/#/options/settings/settings) the account and starting again. Obviously though you should not do that if it's your real account!!

If you'd like advice about what might have caused this and how you can fix your app, then we'll need to know full details about what the app does and how it works with respect to the API, BUT that sort of support isn't really something the site developers can spend time on because they do need to concentrate on HabitRPG itself. I'm not one of the site developers (except for tiny fixes here and there), but I've worked with the API a fair bit, so I might be able to give useful advice, although of course I can't promise in advance that I'll be able to work out if there's something wrong with your app. 

EDIT:
Here's something you can do to try to work out what's wrong. First, create one or two to-dos in HabitRPG itself (i.e., through the web interface at https://habitrpg.com/ ). Test that you CAN delete them and that you CAN tick them off and they stay ticked off. Then, create a couple more to-dos through the web interface and use the API to examine the JSON data for those to-dos, and for the to-dos that you aren't able to delete. If you examine both carefully and compare them to each other, you should be able to see if there's something wrong with the JSON data for the to-dos created by your app.

**Comment by BlackEdder** [comment]
Thanks for the response, I understand that this will be low on the priority list. I kinda stopped using habitrpg as my todo list (still use it for dailies etc), so I hide the todos anyway (using tags), so I can wait :)

I did start out on a test account, but guess I started using my real account too soon. This todo was created fairly early on, when I was still in development mode, so I am reasonable confident that it won't happen again (it hasn't happened since then).

Thanks for offering to help with the API. Like I said I think it should be fine now, but will definitely post more details if it happens with other todos.

**Comment by Alys** [comment]
No worries BlackEdder, and thanks for being willing to be patient! That helps. :)

@lefnire : When you have time, could you look at this please?
Summary of everything above:
BlackEdder's userid is 62cf3b41-a297-4dd9-aa2d-2d1e051abbde.
He has about 9 to-dos called "Reply to Judith". They were created by his third-party app in the past when it was buggy, and he can't delete them (clicking the trash icon does nothing). If he ticks them off, they come back after a sync.
He'd like to have those to-dos deleted if possible - are you able to do that in the database? He's aware that you have other priorities and he isn't asking for it to be done immediately.

**Comment by BlackEdder** [comment]
Thanks Alys!

**Comment by BlackEdder** [comment]
I don't know what happened, but I could suddenly delete all those todos without any problem. Closing this since it seems to be solved now.

**Comment by Alys** [comment]
BlackEdder, thanks very much for letting us know!
