### ISSUE TITLE
bad emoji and italic text parsing

### ISSUE THREAD

**Issue by liordon** [HabitRPG/habitica#3488]
hey guys!

I noticed this bug several days ago but from some reason haven't thought of reporting it until now. i hope I'm not reposting anyone.
as you well know, there is an option of creating an italic text when writing tasks, by using underlines on both sides of said text. there is also the option of using emojis which is a great feature we all know and love.
The problem is that combining both features is probably tricky to whatever parser interprets the emojis. for example, if I have the following task:
![image](https://cloud.githubusercontent.com/assets/4543336/3008114/663708e2-deae-11e3-9bd2-36c8fd5d5169.png)
And I want to turn the words "out of" to italic text, I get:
![capture](https://cloud.githubusercontent.com/assets/4543336/3008136/4421ab44-deaf-11e3-9c39-1e76a7c80e9b.PNG)

The above examples are shown with the translated site, but I saw the bug with the site untranslated, so it's a general thing rather then a hebrew issue.
actually, in what language is the parser written? perhaps my meager skills are enough in order to examine it?
and why are most Emojis available on the site whareas others (like :octocat: ) are not?

Thanks in advance!
##

**Comment by deilann** [comment]
Use asterisks for italics instead.

**Comment by snicker** [comment]
Github uses an extended set of emojis that are not part of the unicode standard.

**Comment by crookedneighbor** [comment]
If this is still an issue, please reopen it.

**Comment by Alys** [comment]
The code for the emoji and markdown conversion is at https://github.com/HabitRPG/habitrpg/blob/dc2fab14d01161aeff17dbc3e6c985226ee22f3e/common/script/public/directives.js#L29-L31

```
      markdown = marked(markdown);
      markdown = emoji.replace_colons(markdown);
      markdown = emoji.replace_unified(markdown);
```

Note that moving the two emoji lines above the marked line does not improve the situation. No one should be foolish enough to try that. `cough` It produces this:
![screen shot 2015-07-19 at 11 15 14 am](https://cloud.githubusercontent.com/assets/1495809/8764151/753ff61a-2e07-11e5-9dab-36933ef0e293.png)

I'm abandoning this now, so if someone else wants to look at it, go for it. It's not high priority since there's the workaround of using \* instead of _ but that won't be obvious to all users so we should fix this at some point.

**Comment by Alys** [comment]
In response to @crookedneighbor's comment which wasn't showing when I was looking into this, yes, the original issue still occurs.

**Comment by crookedneighbor** [comment]
With the new Habitica Markdown module, this is fixed.
