### ISSUE TITLE
Updating Subscription and no payment

### ISSUE THREAD

**Issue by clmmerrill** [HabitRPG/habitica#3494]
I know I am being honest. Just my way. I had a visa gift card with $20. It ran out in April. I wanted to update my subscription with new information. Preferably with Paypal but will use my credit card if need be. 
1. I couldn't find a way to update subscription.
2. When I canceled it doesn't cancel until June 2. Which would be fine if I knew I paid in May. I did not.
3. Now I can't re subscribe or update info.

Thanks for any help. This a bug or an issue not fixed yet?
Cindy

**Comment by Alys** [comment]
Thank you for reporting this clmmerrill! It's very good of you to take the time and to be honest.

Could you please add your User ID to this job? You can find it by going to [Settings -> API](https://habitrpg.com/#/options/settings/api). It will look something like this: d904bd62-da08-416b-a816-ba797c9ee265. Be careful to paste in your User ID but NOT your "API Token". The token is like a password and must be kept secret.

I expect you'll be able to resubscribe after 2 June without any problems, so from that point of view you don't need to worry. :) You should also be okay to receive this month's mystery item on the 23rd - either the problem will not be resolved before then (i.e., your subscription will still be valid), or it will be fixed but you'll still have a week left at the end of the month to resubscribe and you'll then get the item.

**Comment by clmmerrill** [comment]
User ID # 2b44124d-f9bc-49a9-bc97-26e5b3cd099c

**Comment by KellenM** [comment]
Hello -- I have the same issue. I suspect others will have this same issue as well. I recently changed credit card numbers, so I needed to change my subscription payment method. That's not possible, so  after reading about the subscription information, it seemed like I could cancel and have until the calendar month ends before my subscriber status changes. But then I assumed, incorrectly, that during this grace period I could enter new subscription info and avoid a lapse in subscription.

Alys, according to what you've said it sounds like I can also resubscribe on 8/01 or 8/02 without missing subscriber benefits like bonus items, etc. -- although maybe my history will all be lost or "compacted" due to the one-day or two-day lapse in subscriber status? What, if anything, should I do in the meantime? Is this procedure what a user is  expected to do if he/she wants to change payment methods?

If HabitRPG wants to have subscription services -- which I really think is great -- it needs to fix issues like this with payment plans. I consider this a bug, although maybe it sounds like a "feature request." Users need to be able to change payment methods -- not being able to do so (or to not do so without canceling the subscription) is something I would call a bug.

**Comment by deilann** [comment]
Alys isn't saying it isn't a problem-- and it's something I know Tyler is
working on. :) She's just trying to help until it's fixed!

Right now, unfortunately, that is the procedure for changing payment
methods. You'll wait until the subscription lapses. Your history will be
compacted due to the lapse in subscriber status, unfortunately, so I highly
suggest exporting your data before the end of your subscription.

I really know this isn't ideal, and it sucks, but again, I know it's
something Tyler has his focus on.

**Comment by KellenM** [comment]
Thanks -- I just needed some clarification. I am glad to hear it's already on the radar.

I am curious about how the data compacting works. For example, if I save my data now, it gets compacted on 8/01 (plus or minus one day, I guess) and then I resubscribe on 8/02 or later, how much of my history is missing between today and 8/02? Should I wait until 7/31 to export the data?

I assume the payment service (Stripe) doesn't have  any method for users changing settings without changing their settings in HabitRPG.

**Comment by deilann** [comment]
I think it compacts it into weekly data... but I'm not entirely sure. I'd
wait until 7/31 to export the data, just to be safe.

And yeah, Tyler has to do his magic in order to change this. Before we had
the ability of subscriptions to last a month, you just had to cancel and
resign up, but you lost whatever subscription you had left in doing this
and your data was compacted immediately. For some reason, a lot of users
find the "wait but don't pay more" even more frustrating, which I
understand.

**Comment by Alys** [comment]
I'm closing this because now, when you cancel a subscription, you can start a new one immediately before the previous subscription period runs out.
