### ISSUE TITLE
Extra Notes Popup Doesn't Expand to Fit Text // Markdown in Notes

### ISSUE THREAD

**Issue by aedunn6** [HabitRPG/habitica#3508]
![popup overflow](https://cloud.githubusercontent.com/assets/6609895/3045998/d8c86aaa-e123-11e3-9c8e-636df2a50ffd.png)

Extra notes popups don't expand to fit longer text, resulting in overflow.

**Comment by deilann** [comment]
Ooh, thanks for the report.

That's kind of hard to fix. The issue is that there's no line break. You'll see the same thing on a lot of forums and stuff. When a really long link is posted, it causes horizontal scrolling. But there's no real way to make horizontal scrolling work for something like this.

The best solution, imo, would be to get Markdown functional in the details section. Then, it could even be a clickable link. If it expanded to fit, it could get really, really big and awkward.

Thoughts?

**Comment by aedunn6** [comment]
Markdown functionality would be great!

**Comment by deilann** [comment]
Desired and planned iirc

**Comment by negue** [comment]
I think I found a solution / implementation for this. :smile: 

I will create the pullrequests  tomorrow after cleaning up the changed code^^.

![markdown_innotes](https://cloud.githubusercontent.com/assets/842273/4342427/b97ecede-4044-11e4-84f5-3f58c8f3cf39.PNG)

**Comment by deilann** [comment]
Oh man, that is AWESOME.

**Comment by Alys** [comment]
`whimper` Want. Want **NOW**.
