### ISSUE TITLE
Drop cap not being applied

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3513]
User 4ace4d66-0372-4c65-931c-7b06ac35ad57 reported getting over 20 drops today, when drop cap should have been seven.

My guess is if contrib level is NaN it's not an int and so can't be added, breaking the drop cap.

**Comment by deilann** [comment]
cc: @lefnire @SabreCat

**Comment by lefnire** [comment]
it's not `NaN` for this user, so I don't think that's the fix. It's currently 84, meaning either the math is allowing for excessively high dropcap, or it's not getting caught somehow (cc @SabreCat)

This is the private code:

``` coffeescript
dropMultiplier = if user.purchased?.plan?.customerId then 2 else 1
return if (api.daysSince(user.items.lastDrop.date, user.preferences) is 0) and (user.items.lastDrop.count >= dropMultiplier * (5 + Math.floor(user._statsComputed.per / 25) + user.contributor.level))
```

**Comment by deilann** [comment]
I don't understand how it's currently 84. The user had 60-ish PER and not contrib levels.

**Comment by SabreCat** [comment]
Yeah, I don't get what's going on here. dropMultiplier is set to 2 if they're a subscriber, else it's 1.

2 \* (5 + (60/25) + 0) = 14, yeah? I'm not seeing anything wrong with the formula.

My own is coming out 30. 2 \* (5 + (59/25) + 8) = 30, right as expected...

**Comment by Alys** [comment]
I don't think it's a subscriber issue. I only mentioned the subscriber code
because my fix needs to be applied to it too and I don't have access to do
so.

The only issue that I can see was that user.contributor.level was in the
formula without protection for the case where user.contributor.level did
not have a value. If a user does not have a contrib level, then in their
json data, user.contributor = {}  so 'level' isn't defined at all. This
means that when you put user.contributor.level into a maths sum, the total
comes out as NaN, and then any code that uses that total (e.g., to check
for whether the drop cap has been reached) doesn't work. If the formula has
(user.contributor.level || 0) then the problem goes away.

The user's formula wasn't actually 2 \* (5 + (60/25) + 0) = 14, it was 2 *
(5 + (60/25) + NaN) = NaN

**Comment by deilann** [comment]
That was my assumption as well, Alys. but if Tyler is seeing a drop cap of
84, I don't know what's up.

**Comment by negue** [comment]
@deilann @lefnire  Is the drop cap still not working correctly?

**Comment by lefnire** [comment]
@negue on fire today! I think we're good, but I'll check when home

**Comment by negue** [comment]
Yup xD, have to catch up, since I was "away" because of my app development :P
