### ISSUE TITLE
Missing Pet After Hatching

### ISSUE THREAD

**Issue by spekularyon** [HabitRPG/habitica#3515]
i saw some old, closed tickets about this issue, but none recently, so idk if it's been fixed or not...

but yeah, i used a blue potion on a wolf egg, and then both items were gone and there was no blue wolf in my stable. i thought maybe the site was just taking a while to update, but it's been weeks, so needless to say i don't think it'll be popping up any time soon. 

user ID: 36720def-d0ad-4462-be6a-c3008a1f5050
browser: chrome

**Comment by deilann** [comment]
The reason the tickets are closed is because usually what happens is that
the pet was never actually hatched. You got the potion and the egg back,
but it's not clear because of your cache.

Go to your inventory page, do a hard refresh (shift-control-r) or log out,
log back in, and look at your inventory. See if you have your egg and
potion back.

**Comment by spekularyon** [comment]
nope, they're not there...

**Comment by ignu** [comment]
I just made a zombie wolf. My egg and potion are missing but the wolf isn't there.

(I did click sync before hard refresh... so maybe that was bad.)

Len Smith on HabitRPG.

**Comment by Alys** [comment]
@ignu Log out of HabitRPG, clear your browser's cache, log back in, go to your pets page, refresh using your browser's refresh button. Does the zombie wolf appear? If it does not, go to your inventory page and refresh. Do the egg and potion appear? If not, we will need to know your user id - see the [instructions here](https://github.com/HabitRPG/habitrpg/issues/2760) for how to find it.

**Comment by Alys** [comment]
I'm closing because I'm guessing @ignu's zombie wolf (or egg and potion) reappeared. @ignu, if that's not the case, we can reopen this if you tell us your user id.

@spekularyon, I'm sorry we didn't get back to you. :( I see from your account now that you do have a blue wolf. I hope it wasn't hard to come by.

**Comment by ignu** [comment]
That's true. It appeared like six hours later! Thanks!

**Comment by Gill4401** [comment]
Hi, I'm new and I don't know where to put this message.  I have the same problem as spekularyon: I used a blue potion on a wolf egg, and then both items were gone and there was no blue wolf in my stable. I tried it last thursday I tought and it never appeared.

user ID: ad08e751-6b7b-41bb-83eb-fd7c7f04cfa4
 browser: I checked with Chrome or Explorer and nothing.

Thanks and sorry for my bad English.

**Comment by Alys** [comment]
@Gill4401 Sorry about that! I've given you the blue wolf. Please reload your Pets page if you don't see it straight away. Tell me if it doesn't appear after a reload.

**Comment by Gill4401** [comment]
Thanks my blue wolf is back!  :-)

**Comment by KPhoenix** [comment]
Think my issue is closely related enough to post here—if not, let me know and I'll start a new one!

So, yesterday I purchased some gems so I could buy the spooky hatching potions. I bought enough to hatch one of every pet except the bear cub and used them in relatively quick succession. I checked my stable and all eight expected pets were there. I then bought a few more spooky potions to use on the bear cub and save for new pets after I'd grown the first set into mounts... but when I clicked to use the potion on the bear, I noticed that the site said I could hatch spooky versions of some pets I already had. I haven't yet fed them anything or used any saddles, so it wasn't that any had grown into mounts. Curious, I checked the stable again after hatching the bear and saw that several of the spooky pets I had already successfully hatched had disappeared completely, showing as the question mark paws again.

Specifically, before I bought the last batch of potions, I had the spooky wolf, tiger cub, panda cub, lion cub, fox, flying pig, dragon and cactus. After I bought the last batch and hatched the bear, I correctly gained the bear but the tiger cub, lion cub and fox all disappeared. I do still have the wolf, panda, pig, dragon and cactus in addition to the bear.

I've tried the methods suggested earlier in this issue, both yesterday when it first happened and just before coming to file the issue tonight—I've logged in and out, refreshed the page, cleared the cache. I've even tried switching to my other main computer and checking on a browser I have never opened Habitica in before. I'm still missing those three pets, and neither the gems spent nor the potions bought for those pets have been returned to my account. (I do still have potions and gems, but those potions were all bought after I'd hatched the initial eight pets.)

Since I do have more potions and gems I can always just re-hatch the pets, but as real money was spent to acquire the gems I'm hoping that there's a way to get them back without having to resort to that (especially since I don't know what caused them to disappear and don't know if it will happen again).

User ID: fe79b325-2079-4486-81ed-0a2705e10b58
Browser: Firefox 41 (Win and Mac) and Chrome Canary 47 (Win)

Any help you can provide or other resources you can point me to would be appreciated. Thanks!

**Comment by Alys** [comment]
@KPhoenix I've given you back your six gems for the missing three spooky pets. If I've misunderstood how many spooky pets you lost, please tell me.

**Comment by KPhoenix** [comment]
@Alys  No, that's all of them. Thank you for the quick response!

**Comment by linklisa** [comment]
User ID: 
88e9551b-c9be-4711-b81d-3ffc059d6310

This happened to me 11 hours ago, using a blue potion on a wolf egg. No blue wolf, no blue potion, still one wolf egg but I may have had two to begin with. Going into a different browser doesn't change anything.

**Comment by Alys** [comment]
@linklisa You should have the blue wolf pet now (reload if you don't see it; tell me if it's still not there).

**Comment by linklisa** [comment]
Thanks, @Alys.

**Comment by Sebendarius** [comment]
USER ID:
5b950817-d8b1-4328-92b2-d502f41a8f34

This also happened to me a few hours ago.
Hatched a Royal Purple Dragon-pet and got the notification and everything, but it haven´t appeared in my stable thus far.

It was my first pet hatched, so when i saw the Stable say I had 0/90 pets I figured something was amiss.

**Comment by CarmenB1** [comment]
Hi, 
My user ID is: 7f3055a8-564f-451d-829a-b1b9db9c2244
I had a desert lion cub yesterday that is missing today... No clue how that happened but using different browsers or clearing my cache doesn't make it come back. Any help?

**Comment by majestic-owl448** [comment]
@CarmenB1 : when you have a bug report it is better to write in the Report a Bug guild! It is pretty unlikely you will get an answer from someone that can help you if you write in an old closed issue

**Comment by H-Wolf** [comment]
Last evening I used a hatching potion on a dragon egg. On the screen it showed the Royal Purple Dragon and congratulations. I don't find it anywhere, and the egg and potion are gone. I've restarted habitica, waited until the morning, but no dragon. Can anybody help?

**Comment by la1ris** [comment]
I have the same problem: Hatched a white bear cub, got the notification and everything, but it has´t appeared in my stable. 

Any help?

This is my user ID: ef4f2e6f-fd6f-4583-add8-50d48036be1d

**Comment by CuriousMagpie** [comment]
@la1ris please email admin@habitica.com for assistance. We don't provide customer support via GitHub. Thanks!
