### ISSUE TITLE
Mount is partly invisible on stable

### ISSUE THREAD

**Issue by jpfteixeira** [HabitRPG/habitica#3545]
Hi, just grew up my first mount and something weird happens. The mount on the stable only partly appears. However, when I ride it it appears fine. Here's a picture of what happened:
![invisiblemount](https://cloud.githubusercontent.com/assets/7592981/3115712/5520e5a2-e70d-11e3-9d1e-fda0f19bd065.png)

Thanks

**Comment by Alys** [comment]
Hi jpfteixeira. That is actually how it is meant to appear. You'll find it makes a bit more sense when you start to get other mounts on there - the dragons are a bit of a special case. The mounts page never shows the full mount because that would take up a lot of space and make it harder to use the page (more scrolling, both sideways and up-and-down). Instead, it shows only the part of the mount that goes in front of your avatar when you ride the mount. For most mounts, that part is the head, so you see something like the image below. However for the winged mounts, one of the wings also goes in front of your avatar, so you see the wing as well on the mounts page.

![screen shot 2014-05-29 at 6 52 14 pm](https://cloud.githubusercontent.com/assets/1495809/3115858/60e539a4-e70f-11e3-8f78-11110576a2c1.png)

There are no plans to change this. Showing the full mount would be prettier, but would decrease usability. Showing only the head for winged mounts would be significantly harder than you might think because of the way the mount images are handled - for ease of "drawing" your avatar picture, each mount is created with two separate images, one for the front (head + wings) and one for the back (everything else). The front image is what's shown on the mount page, which is a very simple thing to do programatically. Showing only part of the front image would be harder.

**Comment by jpfteixeira** [comment]
Hi alys, thanks so much for the clarification. I guess I was fooled by the mount's wikia.

**Comment by Alys** [comment]
Interesting point. I'll arrange for a note to be put in the [mounts page](http://habitrpg.wikia.com/wiki/Mounts) to briefly explain about the mounts' appearances in the stable. You're at least the second person to ask about this, so it'll be worth documenting it. Thanks!

**Comment by jpfteixeira** [comment]
Just left a little warning there myself. Feel free to change it.

**Comment by Alys** [comment]
That's shorter, neater, and clearer than what I had in mind! Thanks! I've added a link for those who want to know more.

**Comment by jpfteixeira** [comment]
Thanks. Glad I could help.

**Comment by leephon** [comment]
Would it still affect speed or be difficult to make happen if we combined mount images into single .png files used only in the stable?  That would give three files per mount instead of two, but they are not large files... We've already got a bunch of them combined for use in the Wiki, so it wouldn't be hard to complete the set (I volunteer to complete the image library if we do this, since I'd really like to see the change), and it could be easy to add a submission requirement for the pixel artists that they also give these combined files.  It would certainly make the stable cooler.
