### ISSUE TITLE
Missing Quest Completed Dialogue and Rewards

### ISSUE THREAD

**Issue by Reesachan** [HabitRPG/habitica#3546]
My party was working on the Egg Hunt quest, and when I checked in today I noticed that the party page registers the quest as having been completed and that one of the other party members has a fancy looking egg as her pet now, so presumably other people didn't have any trouble with this issue. I never received a "quest completed" dialogue, however, and I can't find any sign that I received any of the quest rewards, either. I tried syncing it again in case it just hadn't caught up, but that didn't make any difference. If anyone has any suggestions or ideas, I'll gladly try them out.

4c076644-3805-45e4-98e5-686f43d3d541

(I looked through the first page of issues and used the search bar to check for key words, but if I missed another post about a similar issue, I'll gladly join in with that thread instead.)

**Comment by Alys** [comment]
Hi Reesachan. Popups "quest completed" dialogs don't appear for anyone due to an issue that will be fixed in time.

Firstly, are you certain that you were on the quest? It is possible to be a member of a party but not be part of the quest that the rest of the party is doing. While the quest was running, did you see any messages in your [party page](https://habitrpg.com/#/options/groups/party) that looked like this: "Reesachan found 3 Plain Egg"? If you saw at least one of those messages, then you were on the quest and you will have received the rewards, even if they aren't visible yet. If there are no such messages anywhere on the party page that include your name, then it is likely that you weren't one of the quest participants.

If you were on the quest, and the "Plain Egg" eggs aren't showing up on your [inventory](https://habitrpg.com/#/options/inventory/drops), then it's purely a caching problem. Go to that page, refresh it using your browser's reload or refresh button, while holding down the shift key on your keyboard. After that click HabitRPG's sync button in the top right section of the page. If the eggs still don't appear, clear your browser's cache and reload again and/or wait until tomorrow and reload.

**Comment by Reesachan** [comment]
I was definitely a contributing member of the quest. There is no doubt about that whatsoever.

I tried both of your suggestions as well as going to a different browser that hasn't been used for Habit before and checking there, but the eggs still aren't showing up.

**Comment by Alys** [comment]
Could you please attach the following screenshots so that we can see if there's anything odd going on apart from the eggs not appearing?
1. [Your party page](https://habitrpg.com/#/options/groups/party) showing the Group ID of the party (top of the left-hand column).
2. [Your party page](https://habitrpg.com/#/options/groups/party) showing the most recent message about the Egg Hunt quest (this might be the same screenshot as number 1).
3. [Your party page](https://habitrpg.com/#/options/groups/party) showing the most recent message about your progress in the quest.
4. [Your Inventory page](https://habitrpg.com/#/options/inventory/drops) showing all of the eggs and hatching potions you currently have.

**Comment by Alys** [comment]
Reesachan, are the eggs showing up in your [Inventory](https://habitrpg.com/#/options/inventory/drops) now? Can this issue be closed? If it's still a problem, please show us the screenshots listed in my comment above.

**Comment by Reesachan** [comment]
Sorry, things went crazy and I had to take a break from Habit for a
bit. Go ahead and close it. Thank you for the help!
