### ISSUE TITLE
died while on quest, then un-died, then leveled up, then lost gear?

### ISSUE THREAD

**Issue by earthfirefly** [HabitRPG/habitica#3551]
My party is doing the "spirit of spring" quest.  I noticed this afternoon when I got back from work that I'd died because the boss did 33.5 points of damage (!).  But then I refreshed the page and...I'm not dead?  I think I leveled up (or at least had all of my health restored)?  And...the mage hat I bought before the one my character has now is no longer in my inventory and is available for sale again...?

I'm very confused!  Is this some sort of bug?  Do quest bosses usually do that much damage?  (Other attacks have been more in the 2-5 points rage.)

(My user name is earthy, if you need that.)

Thanks!

**Comment by Alys** [comment]
It is possible for a boss to do that much damage if one party member has many uncompleted dailies.

Because a hat that you bought is now available to buy again, you can be certain that you did die.

When you die, as soon as you click "continue" on the death notification (or possibly reload the page), then you'll no longer be dead and your health will be restored to full (but you'll have lost one level).  You can read about the full effects of death in the wiki's [Death Mechanics page](http://habitrpg.wikia.com/wiki/Death_Mechanics).
