### ISSUE TITLE
Issues when logging in from multiple computers

### ISSUE THREAD

**Issue by turetske** [HabitRPG/habitica#3555]
When I log in to habitrpg from work, it for some reason then thinks I didn't complete my dailies for the previous day (or more, I'm not sure) and doesn't register the tasks that I logged at home in the morning.  Even though I definitely checked the tasks and checked after midnight the previous day to make sure the system has registered that I've done the tasks and it seems to believe I have.  I'm losing my streaks and health, I know how to refresh my health using fix character values, but I hate the fact that I keep losing the streaks that I build up over the weekend.

**Comment by Alys** [comment]
As a partial work-around until this is fixed, you can [restore the streaks on your dailies](http://habitrpg.wikia.com/wiki/Streaks#Restore_Streak_Counter).

If you want an easy way to regularly record your stats and streaks so that you can restore them accurately, use the [Unofficial User Data Display](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) - see the "Stats and Streaks Backup" section.

**Comment by Alys** [comment]
This sounds very much like a local storage issue, which is being tracked in https://github.com/HabitRPG/habitrpg/issues/4313 so I'm closing this. There's an Advice section near the top of that issue which might help, if you're still experiencing this.
