### ISSUE TITLE
Booted from Party

### ISSUE THREAD

**Issue by Dranian** [HabitRPG/habitica#3561]
Hello,

I logged in to my HabitRPG account today and noticed some difficulty while loading. When the platform did finally load, I noticed that I was no longer in my party (and my boss fight, which was almost over, was nowhere to be found).

How should I go about correcting this issue?

Thanks so much for a fabulous program! :-)

Cheers,
Devin

P.S. I'm running Chrome 34.0.1847.137 on a OS 10.7.5 machine.

**Comment by lefnire** [comment]
how long had you been in the party? what's your UUID?

**Comment by Dranian** [comment]
Hmmm... apparently the issue has automatically corrected itself as of the
send-time of this email.

My UUID for reference is 670fd741-46a8-4360-a2a7-c5669ff720f2.

My Group ID for reference is 333ed46b-cd68-468a-b094-1a0866a288f4.

Thanks! :-)

On Wed, Jun 4, 2014 at 2:38 PM, Tyler Renelle notifications@github.com
wrote:

> how long had you been in the party? what's your UUID?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3561#issuecomment-45132621.

## 

Best regards,

Devin

**Comment by lefnire** [comment]
We've sometimes seen users belong to two parties somehow. It could be that you belong to the correct party, and also belong to an empty party. if it happens again, open the party page and see if it there's a party there (it has a title, instead of "create a new party"). If so, click "leave" and refresh.
