### ISSUE TITLE
API returns 502 on /user/inventory/feed/{pet}/{food}

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#3570]
For some reason the API returns an empty response with the Status code 502, when trying to feed a pet through the API.

The process seems to be successfull (at least the food is gone, and I think the pet progress is also set.)

I could not reproduce this on my local development setup (fresh habitrpg installation).

Also it would be nice, if feeding would return the same respones as equipping. (containing all the owned pets and the owned food, so that those values are known.)

**Comment by phillipthelen** [comment]
has anybody had time to take a look at this? really seems to be some problem with production server, as I am unable to reproduce this with a development setup :/

**Comment by Alys** [comment]
Please don't expect bugs like this to be fixed quickly. This affects only a very small number of users and since the process is successful, it's a very minor problem. The developers' time is much better spent on serious bugs that affect many users or on adding new features that might bring in more users and hence more revenue (thereby eventually allowing more developers to be hired). It's good that you reported this, and I would guess that it will be fixed eventually, but it cannot reasonably be considered even a medium priority when there are several other bugs and large number of feature requests. Remember that almost all the developers are volunteers and they have limited time to give up to HabitRPG.

**Comment by crookedneighbor** [comment]
@vIiRuS Haha. You were just having this issue again, right?
