### ISSUE TITLE
The potato issue (using articles in languages with gendered nouns - ryan)

### ISSUE THREAD

**Issue by hahabloodyha** [HabitRPG/habitica#3571]
Hi, I just reached level 7 in HabitRPG and I won a potato, my game is set to French and I got a message saying "vous avez trouvé a patate" and then it said "donner à manger le/la patate" Well.. I guess it's not important at all but I just thought it might be nice to mention that "patate" is feminine in French so it's "une patate" and "la patate"..
Ok  that's all I have to say, have a wonderful day. This game is great by the way.

_edit by Alys, 2017-10-29:_

There's a lot of discussion below but we've settled on ellenhutchings's and crookedneighbor's idea of having separate translatable strings for "potato", "a potato", and "the potato" (and all other foods as well of course). In content.json, we currently have this string:

	"foodPotatoe": "Potato",

The fix for this issue would add these two strings:

	"foodPotatoeA": "a Potato",
	"foodPotatoeThe": "the Potato",

I've kept `foodPotatoe` in those strings rather than using foodAPotatoe and foodThePotatoe so that we'll be able to grep for `foodPotatoe` and find all three strings.

The fix will also need to adjust any related code and other translatable strings that it uses. As one example, we have this string in messages.json:

	"messageDontEnjoyFood": "<%= egg %> eats the <%= foodText %> but doesn't seem to enjoy it.",

It would need to be changed to this:

	"messageDontEnjoyFood": "<%= egg %> eats <%= foodText %> but doesn't seem to enjoy it.",

and the code that inserts `foodText` into that string would be changed to use `foodPotatoeThe` instead of `foodPotatoe`.

##

**Comment by deilann** [comment]
Because of the way the dialogues are written, there's no way for it to know
what gender the item is -- some of the food items are of a masculine
gender, and some of them are not, like the potato.

That's why it says "le/la" there -- it doesn't know that it's a potato.
Kind of like when something says X day(s) -- because it doesn't know if X
is going to be 1 or 562.

**Comment by hahabloodyha** [comment]
Ah ok, that's how it works, well  I thought I'd just mention it, even if we can't do anything about it :) I guess the potato issue isn't the most important issue anyway ;)

Date: Sat, 7 Jun 2014 16:53:41 -0700

**Comment by SabreCat** [comment]
We have a separate "article" attribute for each food in the base script file. Could those be I18Ned? It wouldn't work for every language, I'm sure, but it would cover this case.

**Comment by deilann** [comment]
Updated with edited title.

**Comment by paglias** [comment]
@SabreCat I left it this way, that isn't nice, because many languages (French, Spanish, Italian... for example) have different articles for different genders and the gender in some cases changes from a language to another for the same item. We could have a different article for each different item but it would easily become messy and difficult to explain on transifex

**Comment by deilann** [comment]
@paglias So... consensus is, getting the articles correct with gendered nouns would be a mess of a bucket and a half, and keep the current system?

**Comment by paglias** [comment]
With the current system I have no better idea than sticking with this
situation. If you have any other idea it would be fantastic

2014-06-15 14:10 GMT+02:00, deilann notifications@github.com:

> @paglias So... consensus is, getting the articles correct with gendered
> nouns would be a mess of a bucket and a half, and keep the current system?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3571#issuecomment-46114186

## 

Matteo Pagliazzi - paglias.net

**Comment by deilann** [comment]
Nah, I think you're right. I just was thinking if that's the case, this
ticket could be closed. It's intended and unlikely to change.

**Comment by ellenhutchings** [comment]
Edit: sp.
It seems like this could perhaps be done as a part of translation. If gendered languages put the articles as a part of the item text rather than the message, i.e. "la patate", rather than just "patate".
I realise that this isn't perfect, sometimes you would need un/une/des instead of l'/le/la/les but it seems like a way to think about it that wouldn't require changing the whole system.

**Comment by deilann** [comment]
Maybe the French translators and reviewers could look and see if they could
get the system working better for them? I mean, it's all crowdsourced.

**Comment by crookedneighbor** [comment]
One way to do this would be to have separate translatable strings for "potato" and "a potato"

**Comment by rbreu** [comment]
I'd be interested to look into this (and #5639).

**Comment by Alys** [comment]
@rbreu Thanks! You're welcome to ask questions here if you wish to.

**Comment by librarianmage** [comment]
@rbreu Are you still working on this?

**Comment by SabreCat** [comment]
More than a year idle; changing the tag!

**Comment by Alys** [comment]
I've edited the top post to add the text below to it. Further discussion of this is welcome.

----
There's a lot of discussion below but we've settled on ellenhutchings's and crookedneighbor's idea of having separate translatable strings for "potato", "a potato", and "the potato" (and all other foods as well of course). In content.json, we currently have this string:

	"foodPotatoe": "Potato",

The fix for this issue would add these two strings:

	"foodPotatoeA": "a Potato",
	"foodPotatoeThe": "the Potato",

I've kept `foodPotatoe` in those strings rather than using foodAPotatoe and foodThePotatoe so that we'll be able to grep for `foodPotatoe` and find all three strings.

The fix will also need to adjust any related code and other translatable strings that it uses. As one example, we have this string in messages.json:

	"messageDontEnjoyFood": "<%= egg %> eats the <%= foodText %> but doesn't seem to enjoy it.",

It would need to be changed to this:

	"messageDontEnjoyFood": "<%= egg %> eats <%= foodText %> but doesn't seem to enjoy it.",

and the code that inserts `foodText` into that string would be changed to use `foodPotatoeThe` instead of `foodPotatoe`.

**Comment by Feywood** [comment]
I wouldn't mind getting to work on this one. It seems so tragically abandoned and so very much needs doing.

**Comment by TheHollidayInn** [comment]
Thank you! Please feel free to work on it.

**Comment by beffymaroo** [comment]
@Feywood Are you still working on the unresolved aspects of this issue (noting that the related commits are "partial fixes")?

**Comment by Feywood** [comment]
@beffymaroo I think the partial fix was in the end added onto and made into a complete fix, so as far as I know, this one is completed and merged.

**Comment by Alys** [comment]
@Feywood Thanks! :)
