### ISSUE TITLE
Burst of Flames uses MP but XP disappears on sync (Need to Disable Spell Use on Habit Buttons - ryan)

### ISSUE THREAD

**Issue by AranelS** [HabitRPG/habitica#3579]
**To fix this we need to disable using a spell on a Habit's button, just like you cannot use a spell to check off a daily. - Ryan**

**Original Post:**

Okay, this gets a little complicated.  Before taking the screenshots I logged out, cleared my browser cache (Firefox), restarted the browser, and logged back in to eliminate any issues on my end (as far as I can tell).  My user ID is 77f27b3d-09fc-4d21-8484-d945d39c198a. 

When I use "Burst of Flames", half the time it gives me an error message and promptly restores the XP and MP to previous levels.  The other half, it APPEARS to work, but when I sync or refresh the page, the extra XP is gone (but the extra MP has still be used up).  

Here is a screen shot from before I used the spell:
![new picture 10](https://cloud.githubusercontent.com/assets/4458101/3212241/42e6d35e-ef4d-11e3-9623-7fc3e3abf933.png)

Here is immediately after I used the spell (on the top habit, if it matters):
![new picture 11](https://cloud.githubusercontent.com/assets/4458101/3212243/50867f32-ef4d-11e3-98d8-08762e1924de.png)

And here is immediately after a sync:
![new picture 12](https://cloud.githubusercontent.com/assets/4458101/3212245/56ac86b8-ef4d-11e3-971d-1bfeb566c1b9.png)
What appears to be happening is that I lose the mana, but I also lose the extra XP (the net XP gain is what it would have been if I had clicked that habit without using the spell, as far as I can tell).  

I couldn't really say how long this has been happening, because I have been out of town (uhm...really, really out of town) for a couple of weeks and so I was using the mobile app exclusively (and not that much).  Since I gained access to the spells, this has happened every time I've tried to use Burst of Flame.

**Comment by Alys** [comment]
When you use the skill, are you clicking on the habit's + button so that you both "do" the habit AND cast the skill at the same time? If so, it's best that you don't. Instead, cast the skill by clicking somewhere else on the habit instead. Casting a skill is not directly related to checking off a task (or clicking + or -) - they are separate actions (I realise that that's not obvious until you are told!). You can cast a skill on any task even if you have no intention of actioning that task.

When you cast the skill at the same time as you click on + or a checkbox, you are actually sending two separate commands to HabitRPG's servers at the same time, and then you tend to get sync errors (the same as you do if you check off two tasks in rapid succession).

**Comment by AranelS** [comment]
That seems to solve it, thanks.  (Of course the bug is still there, but I don't mind so long as I know how to get around it.)

**Comment by deilann** [comment]
We've disabled clicking on the daily checkbox; we'll need to disable
clicking on Habits, too.

**Comment by deilann** [comment]
Updated with info for fixin', labeled.

**Comment by etaiklein** [comment]
This affects Rogue Backstabs as well as wizard Burst of Flames

**Comment by etaiklein** [comment]
Wrote a fix here: https://github.com/HabitRPG/habitrpg/pull/4516
