### ISSUE TITLE
Change payment information for subscriptions

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3625]
Currently the only way to change your payment information (say, updated credit card number or switching from paypal <=> credit card) is to cancel your subscription, wait for the sub to run out, and then re-subscribe. That's a PITA (noting when your sub runs out post-cancel), and ideally users would be able to just update their payment method. What I've been telling users in the interim is to cancel their sub, re-sub with their new information, give me their UUID, and I'll refund the overlap $5. 

_edit by Alys, 2016-03-12:_

Current status is that if you've subscribed by credit card, then there's a button that lets you change your credit card. To change from one payment method to another (i.e., swap between paypal/stripe/amazon) you still have to cancel and resubscribe, but you can resubscribe immediately and the new subscription will be added to the end of the previous one. That makes this less of a problem than it used to be, although still something to be fixed.
##

**Comment by deilann** [comment]
Can they resub whilst they still have a subscription? Like, if they cancel, won't it still say they're subscribed?

(Also, if they wait until it runs out, they lose their data.)

**Comment by lefnire** [comment]
Both valid points. Looks like there's no getting around this right now until the feature can be added

**Comment by deilann** [comment]
My solution would be to separate "active subscription plan" from "active subscription" -- the former being "currently paying money" and the later being "has subscription features"

This might also be able to fix the fact that currently if you subscribe after the mystery item is announced to get the items, then cancel your subscription, you get 2 months worth of items for one month of subscription. (Give items to if active plan or plan updated that month)

Then, if people have no active subscription plan, they can see the option to resub, with a warning that it will cost them more monies, but then at least they don't lose their data and you can refund, rather than having a lose-lose situation.

**Comment by lefnire** [comment]
Marking to crit 'cause I'm getting ~1request /2d

**Comment by connieop** [comment]
This problem could easily be fixed by adding a Payment Options page, and having the Subscription check that page every payment. Unless that doesn't work.

**Comment by Alys** [comment]
I've updated the top post to contain this text: "Current status is that if you've subscribed by credit card, then there's a button that lets you change your credit card. To change from one payment method to another (i.e., swap between paypal/stripe/amazon) you still have to cancel and resubscribe, but you can resubscribe immediately and the new subscription will be added to the end of the previous one. That makes this less of a problem than it used to be, although still something to be fixed."

I'm removing the critical label because it's no longer an urgent issue.

We're planning improvements to the subscription code and this is probably something that should be done during or after that process, rather than before, so I'm marking this as wait. Opposing opinions are welcome! I'm happy for any admin to change the labels again if they disagree.

**Comment by SabreCat** [comment]
Will need enough client UI work that this should be pended until after the frontend redesign.

**Comment by lemoness** [comment]
Is this still an issue?

**Comment by SabreCat** [comment]
I'm pretty sure it is, yes.

**Comment by lemoness** [comment]
Have added labels!

**Comment by TheHollidayInn** [comment]
We've decided that the current method of cancelling and resubscribing is good.
