### ISSUE TITLE
Feature request: Resurrection Quest 

### ISSUE THREAD

**Issue by Hermione333** [HabitRPG/habitica#363]
If one dies she or he should be able to go on a resurrection quest that packs a few positive habits and todos with a time limit (time limit and quantity of habits, and therefore the difficulty of the quest, increase with level). The habits/todos to put in the quest will be decided by the game (among the ones the user has in her/his dashboard), not the user. If one completes the quest before it expires, one will not get experience points for the things done, but will instead get 10 health points and will be saved from Death (Death will give the user her/his life back in admiration of her/his will power). If one fails, one dies for good.
If there is the possibility to purchase a resurrection elixir with coins accumulated before death, one should have the choice between purchasing the elixir and going on the resurrection quest. If one chooses the resurrection quest and fails, Death will not be bribed and one will not be able to buy the resurrection elixir (Death has monopoly over the resurrection elixir, meaning one cannot purchase it from someone else)

**Comment by ymarcus93** [comment]
This is a great idea!

**Comment by maxiboch** [comment]
Maybe call it a phoenix quest?

**Comment by ghost** [comment]
The Rise of The Phoenix Quest

**Comment by Pandoro** [comment]
Honestly this is one of the best takes on death I have seen so far. It fits the rpg genre as you do some quest, with a little bit of a story in there as well. Furthermore it actually helps you to get stuff done. Instead of just dying and trying again, you are now motivated to finish something. However there are two big buts as well.
1. You cannot simply pick something from the todo or habit list. Many people will have stuff on there that has an undetermined due date. Unless of course the todo has a certain due date (at some point in the future.) However this would already be a todo which you are motivated to complete, so I'm not sure if that would be the best todo to pick in such a quest. So in general I would limit it to Dailies.
2. The "you really die" part is still a problem. It would still have to be determined what that would mean for people, but for that see the #223 thread.

**Comment by wc8** [comment]
@Pandoro 
1. Also, a task with a due date within the quest timetable might not exist. Perhaps daily tasks plus a quota of todos/habits, for example, 1 todo or 3 good habits. 
1. I think this is compatible with "really dying"—have your cake and eat it, too: game over and game not over. In one sense, it is a new game with a new quest, and in another, the old game, with your character and equipment coming back. 
   How this could work: leave everything about death as is now ("Game Over" message, etc.) except: put a prominent button for the Phoenix quest on the user's header. The discouraged user will wonder, what's that? Then they'll find the opportunity to bring their character back. 

Resurrection ideas have been mentioned a few times, and I'm starting to think it might be the best approach. I like this one particularly.

By the way, there's a fantastic phoenix that could be used for dialogs in #107.

**Comment by wc8** [comment]
Alternative to "really dying" (I misread the original suggestion, and consequently missed the point of @Pandoro's 2):
Rather than dying after failing the quest, you start on Level 1 after game over, but the Phoenix Quest gives you a chance to revive your character as he was before game over.

So, if you complete the quest, you get your levels, pets, equipment, back. If you fail, you find yourself with whatever you've gained so far from your level 1 start. In a sense, you're starting from scratch on game over, but if you miss the quest, you're not starting from scratch at that point. 

I think it would be potentially discouraging if one just barely fell short of the mark and died.

**Comment by wc8** [comment]
See also/vote [Death Mechanic](https://trello.com/c/k2MWBcxl).

**Comment by Pandoro** [comment]
@wc8 I agree that the quest will probably be realizable, although it will need some tweaking regarding the stuff you need to do. For example lately I saw that my girlfriend does not have habits at all. It's all dailies and some age old todos for her :x 

So maybe it should rather be some kind of streaks like "do at least x% of all your dailies for the next 3 days".

However whatever happens. I am still strongly against loosing everything by definition. For some this might be very much desired, for others not. I do not think that this is an issue worth loosing customers over. I would never go for a solution without the option of opting out of this feature. So either make it less dramatic by default, or add an opt out option. I do think you should loose something, don't get me wrong. But maybe make it like loosing 50% of your gold, but at least 5 gold \* your level and furthermore going down by a level or loosing a certain lvl dependent amount of exp. But well, we have discussed many options already. I am fine with a lot of options, but loosing everything is well... you know, something I don't desire ;)

**Comment by wc8** [comment]
1) I was thinking exactly along those lines: x% of dailies for x days. 
I thought of 1 day for every level plus one level, maybe with a max length of days. 

2) I think the quest should be something hard to fail unless you really weren't trying.
I'm also thinking quest tasks could have options. So meet your streak OR do one or two really old high priority tasks.

3) How about disabling equipment? So it's "lost" but not lost. 
Divide # of equipment pieces by length of quest and regain/reactivate equipment accordingly. 
Thus, you would again be unlikely to lose everything unless you were giving up.

4) Maybe Include an option once to do an account freeze for x days—in case what's happening is a major life crisis. 

What do you think?

**Comment by Pandoro** [comment]
All of those combined make it a lot less threatening, but I still have the
feeling that it is too threatening. For example in the weekend I spend time
with my girlfriend and often forget about some of the stuff I wanted to do.
Yes this is bad, but in the end I find spending time with my girlfriend
more important than doing something EVERY day of the week. So if I disable
8/10 from my tasks for the weekend, I just got two left to get a "streak"
with. But If I fail to do these, I loose a level and an equipment piece?
Doing this Saturday and Sunday means I loose two levels and two pieces? I
find this too threatening and would definitely opt out of this. I'm not
trying to attack your ideas, but I think you might come up with some other
idea which would make it a little softer, but in turn, I would argue again
that it would still be to harsh for me.

Just to make it clear, when I say "I would" and "for me", I am trying to
overdo the point a little. Don't think I am the whiny kid that is trying to
make life easy for himself. To be honest I simply try not to die and I
would probably be fine with the system, but I also think there are
sufficient users who still don't like this idea and it would demotivate
them to keep playing.

So let's consider we drive this idea further. There are two options. Either
the resulting quest is so easy, that death looses it's meaning for many
people, which isn't desired, or it is so hard and you again disappoint
other people, both aren't desirable I think.

For many issues I read, where people start saying that this should probably
be an opt-in/opt-out thing, I am feeling that it would simply become too
complex if you have 30 things you need to opt-in/opt-out of.... you will
probably be spending a lot of time to find the right way for you. However
as this is a VERY critical issue (death), I would really make this such a
feature.

Nevertheless I really like the idea of such a quest, as it gives a nice
touch and you will motivate people to get stuff done. So I wouldn't make
the quest itself opt-in or opt-out, but rather the results of failing it. I
would still make it an achievable quest, meaning if you want to make it you
can without too much trouble, but also make it somewhat hard, to show
people that if you slack in general, you will have to work hard again. This
is a really good motivational factor and I wouldn't sacrifice this while
making it so easy that everyone can make it without doing anything really.
STILL people should be punished in the way they see fit regarding their
playing style. Meaning that for the hardcore people, they can go full-reset
if they fail to do it. For the mediocre people they will loose something
substantial and for those that want to play it easy, they just loose a
level and a big bunch of gold. (Just examples.)

We had this discussion for death in general already and if I recall right,
a slider with different options was  seen as a very valid idea. I don't see
why we should force a great idea like this to fit everyone, while probably
loosing the actual meaning of it. Instead we could just keep the slider
option and make the quest meaningful.

**Comment by Pandoro** [comment]
Tokens is a very tricky thing indeed :x But also this would mean that
people who pay money will get less "damage" when dying, so that means if I
invest money, my life is easier. This is a message that will not motivate
people to really get stuff done?

I agree regarding the payed items that they should not be lost, but an idea
would be that if you buy them for tokens, you will loose them, but after
unlocking them once, you could rebuy them from the store for gold.

Regarding the slider. I would not make the quest itself opt-in or opt-out,
but rather the kind of results. I would always use the quest, as it is
motivating for people and then depending on the slider you will get
different results if you fail the quest. However the hardcore people might
indeed not like it and just want to start over? For this it might be an
option to indeed make 1 setting where you just start over, but in general
you should do the quest I think, as this will result in extra motivation.
The slider might also determine how hard the quest really is maybe?

I would propose:
Habit-Building: You do the quest -> You fail -> loose 1 level (or certain
amount of exp) and gold.
Moderate: You do the quest -> You fail -> same as before, but also loose
certain items, depending on how bad/good you did in the quest.
Severe: You do the quest -> You fail -> restart the character
Hardcore: You just restart the character.

What do you think @wc8 ?

**Comment by wc8** [comment]
@Pandoro Sounds perfect. Updating the card. I'm thinking of closing this thread in favor of #223 because they now overlap, and much important discussion is in that thread.

**Comment by Pandoro** [comment]
This is fine by me, I think this will make is easier to keep track of all the ideas.

I'll close this then ^^
