### ISSUE TITLE
All Equipment Disappeared

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3652]
Refreshed this morning to see my avatar in Lvl 1 clothing. Checked my equipment in my inventory and everything is gone, except that Lvl 1 stuff. Username is Azasal.

**Comment by lefnire** [comment]
Did you register yesterday? If so, it could have been you caught the server on a down-swing and your actions didn't stick. If not, it could be you have a stray account (the lvl1 character). The way to tell is if you have two different UUIDs - try logging out and back in to see if you have a different character (I can't check because user with username Azasal doesn't exist, that's likely your profile name. Facebook registration?)

**Comment by ghost** [comment]
I've been on HabitRPG for awhile now. Logging out and back in worked to bring everything back though.

-----Original Message-----

**Comment by lefnire** [comment]
In that case, the next time you see the lvl1 character (logging in will give you a char at random) - make sure they indeed have different UUIDs (just to be sure), and if so delete the lvl1 char

**Comment by Alys** [comment]
@Azasal : The fix suggested by @lefnire has worked every other time I've seen this issue, so I'm assuming it worked for you and I'm closing this issue. If you're still having problems, comment here and we'll reopen this.
