### ISSUE TITLE
My wooden shield disappeared suddenly

### ISSUE THREAD

**Issue by valentim** [HabitRPG/habitica#3658]
My ID: 985234ac-c6c9-4c21-818f-b762eb0db5e5

**Comment by Alys** [comment]
Did you recently die? When you die, you lose one item of gear, chosen randomly.

**Comment by valentim** [comment]
No, I never died in the game yet

**Comment by Alys** [comment]
Go to your equipment page (https://habitrpg.com/#/options/inventory/equipment ). Does it appear there? If not, clear your browser's cache, reload the page, and check again. If it doesn't appear there, go back to your tasks page, refresh, and look in the rewards column.

**Comment by valentim** [comment]
Nothing yet

**Comment by Alys** [comment]
Please take a screenshot of your entire equipment page, and of the equipment section of your rewards column. For the latter, you can trim all personal information out of the screenshot, but it's important to leave in enough of the image so that we can be certain we're seeing the entire set of equipment available.

We can use these screenshots to see if there's any image glitches that might be causing the shield to not appear or to look different than it's supposed to look.

**Comment by valentim** [comment]
OK, I will take a screenshot, but the wooden shield now is in my rewards column now, but I already bought this item...and after a day it disappeared suddenly

**Comment by Alys** [comment]
If it's appeared, you don't need to take any screenshots. You can buy it again; use Fix Character Values (Settings -> Site) to give yourself the gold for it if necessary.

If you're certain you didn't die, then the reason it disappeared was because of a sync error. Sometimes when you take an action (e.g., buying an item), your browser registers the action but it doesn't send it to HabitRPG's server, so the server never knows that you took the action. The next time the browser syncs with the server, the browser takes on all the data that the server has, and so the action that was never synced was lost.

**Comment by valentim** [comment]
Tks
