### ISSUE TITLE
[EXPLOIT] Too Much Mana

### ISSUE THREAD

**Issue by xiontawa** [HabitRPG/habitica#3660]
A friend and myself was working to build back up our mana after a quest. We took turn casting around 5 Etherial Surges each, and after about 1.5 hours of work, got about half our mana back. We did see this as a problem, as we figured our other party members would simply stop gaining mana after they hit their max. This is not the case. **Our other party members continued to gain MP far beyond their cap, which lead to them casting 100s of buffs and essentially breaking everyone's characters.** Hitting + on a simple habit would level us over 100 times. This has ruined the game for me and many others. Please fix it so that people cannot gain MP outside of their max.

Attached is a screenshot of my easiest daily...

![untitled](https://cloud.githubusercontent.com/assets/3139771/3407100/1b107c38-fda1-11e3-9b28-36c813252be7.png)

**Comment by alohangel516** [comment]
I'm in the party mentioned, and this completely ruined my character, and my experience with HabitRPG. PLEASE FIX THIS!!! :(

**Comment by Alys** [comment]
Everyone in your party can reduce your level, gold, XP, etc to approximately what they were before by using Fix Character Values, which you can find in the Settings menu under Site. You can also read about F.C.V. on the wiki at the http://habitrpg.wikia.com/wiki/Settings page. You will find after you've reduced your level that you still have a great many attribute points, however the excess ones will disappear the next time you level up (and if you never assign them to attributes, then they won't have any effect on your stats).

F.C.V. is easy and fast to use and it should remove all the issues that have caused the game to appear to be ruined for you.

The buffs that your party members cast are designed to increase various factors such as XP gain, and so they were working as designed. It's probably best to not cast a buff many times if you want to avoid a dramatic increase in its effects.

I'm not sure whether allowing MP to increase beyond its maximum is a feature or a minor bug that hasn't been fixed yet. I do know that some players enjoy making use of this feature/bug so I'm not sure what the plans are about changing it. I realise that other players don't like having more than maximum MP, but that issue can be worked around by not using the extra MP. Note that as soon as you tick off a task, the excess MP will disappear immediately, so excess MP is generally not something that you have to put up with for long. In your case, it's probably best if you don't cast any skills until you have ticked off one task - that will allow you to avoid the issues with using more than your maximum MP.

You might wish to submit a feature request on Trello to have a feature put in place to prevent MP ever rising above the maximum. Please note though that even if this is fixed, it probably won't happen quickly because there are other, serious bugs that need to be worked on, and many other features that people have requested. This one has to be considered a minor bug at most, because it is easy to work around. I realise that in your case that's not idea, but the programmers do need to prioritise bugs that cause serious, unavoidable side-effect.

alohangel516, could you please be a little more polite when you submit or comment on bug reports? "PLEASE FIX THIS!!!" (and anything written in all-caps) is generally considered on the internet as shouting, and so it has a demanding tone about it. Please keep in mind that most of HabitRPG's features are free and always will be, so there is a limited amount of money available to pay for programmers. This means that development is slower than we all might desire, but there is no way around that unless significantly more money can be raised. Almost all of HabitRPG's programmers are volunteers, who see no money for any of their work (apart from occasional bounties if people use Bounty Source to pay for a fix or feature). This means that they have to fit HabitRPG programming into their free time, as all or most of them have paying full-time jobs which must take precendence. Please be more considerate of their time and try to write more politely when asking for fixes rather than sounding as if you are demanding work to be done.

**Comment by Alys** [comment]
xiontawa or alohangel516, could one of you please paste the URL for this issue into your party chat so that all of your party members can make use of this advice? They will **not** need to have Github accounts to read it.

**Comment by xiontawa** [comment]
I don't consider using FCV as a solution to the problem.

Also, in response to your wall of text about people being polite, I was once a developer on the side, with a full time job, and that's a pretty polite comment compared to what I've had to deal with.

Also, HabitRPG offer's a sub, and microtransactions, not to mention ad revenue. There is money involved, and some are paying monthly for the service. In any situation where you pay regularly for a service, you expect it to work, and get upset when it performs not as expected.

Finally, why would I not encourage all my party members to come here and comment, when the more comments an issue get's the more attention is gets? I've been around Github long enough to know how to get someone's attention.

**Comment by thepeopleseason** [comment]
As Alys indicates, using FCV is a workaround while submitting a request to Trello. HabitRPG is open-source, so as a one-time developer, your contributions are welcome. 

In truth, exploits like this are low-priority because such using a cheat in a productivity tool only robs the cheater (and sadly, in this case, they cheater's partymates) of productivity. 

Finally, if you read her posts carefully, Alys suggested that all your party members come here to read the workaround, the implication being that they don't need to have Github accounts to do so, but if they wanted to comment, they could.

**Comment by Alys** [comment]
There was a discussion about various aspects of this in https://github.com/HabitRPG/habitrpg/pull/3662, outlining the bad points and the good points about being able to gain more than maximum mana. The advantages seem to outweigh the disadvantages, and there are ways to avoid or undo the disadvantages. 

In addition, since this issue was logged, I believe there's been a couple of changes that reduce the occurrences of more-than-max mana: your mana is now reduced to your maximum during cron and when you tick off tasks.

Hence I'm closing this issue, although it can be reopened if needed.
