### ISSUE TITLE
Damage Logging Problems

### ISSUE THREAD

**Issue by Pandah** [HabitRPG/habitica#3666]
Okay so my family is in a group together and we are fighting a boss monster. We have been making sure everyone has been doing their stuff every day. My little sister SWEARS she did her stuff yesterday, but it still logged 53 damage as if she had not clicked anything. It killed us all, and I lost the clover armor, which I can NOT get back and which I ALSO used gems to change my class to get. I don't feel this is fair at all, whether this was a glitch or not. I really hope someone can help this time around. Thank you.

**Comment by deilann** [comment]
Most likely, your little sister clicked too fast and didn't refresh or sync before the end of the night to make sure it all "stuck." I highly suggest using [Alys' tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) to make sure that everything saved to the server. Because it goes off of server data, it's more accurate.

Can you do me a favor? Log out and then log in again, and make sure your clover armor was actually what you lost. (Or you can use Alys' tool's "Missing Equipment" section to check that.) Sometimes local reports a different item lost than the server, so you might not have lost it.

Also, once you've confirmed me what gear you've lost, can you toss me your UUID?

**Comment by Pandah** [comment]
Ooh, you are right. I didn't realise it showed a different object than what might have been taken. It doesn't look like anything was actually missing except my savior shield, which I can easily earn back. Just so I know, is it not supposed to remove armor that is not reobtainable?

**Comment by deilann** [comment]
No, it could remove the clover armor, and then you'd have to wait until
you're a warrior again to buy it back. There's some debate on this subject.
Generally, if it's a glitch death or yanno, someone's little sister taking
shortcuts for the first time, I'll set up a class hop back and forth to get
the items.

But for some folks, the chance of losing an item they'll need to pay gems
to get back is really motivating...

It's also not a super high prio worry thing. It'll get sorted out at some
point, what the official stance is, I'm sure, but for now, I just try to
handle it case by case. :)

**Comment by Pandah** [comment]
I thought the clover armor was off the market completely, though, since we have now switched to mermaid/pirate outfits? So I didn't think I would be able to get it back at all, even if I did switch back to warrior.

**Comment by deilann** [comment]
Oh, no! Once you own a piece of armor, if it breaks, you can repurchase it
if you're the right class, even if it's limited edition.

**Comment by Pandah** [comment]
OH! wonderful! thank you!!

**Comment by deilann** [comment]
No problem! Now make sure your little sister doesn't click so fast. ;)
