### ISSUE TITLE
Lost HP and Perfect Day?

### ISSUE THREAD

**Issue by Malaryush** [HabitRPG/habitica#3678]
I had a Perfect Day yesterday, and started the morning with the buff in place.

I always keep the browser open with an active tab for HabitRPG.  I had completed several Dailies and Habits already today, with no problem. At approximately 9:30pm, I came back to the Task screen to check off a couple more completed Dailies. When I checked the first one, the screen refreshed, then displayed the message that I lost HP, gold, and experience points. It was only 3hp, and not a lot of gold, so I wasn't worried about the loss, but it appears I've also lost the Perfect Day buff, dropping my total available mana.  

Two Dailies that I had completed and checked off earlier today became unchecked. It's also showing that my streak counter has reset on two other Dailies that had already been completed for the day, and I'm positive they had been checked yesterday.   However, other completed Dailies that I'd checked off earlier today are still showing as complete.

None of the losses were particularly concerning, but the combination of issues seemed rather peculiar, and I have no idea what happened.

**Comment by deilann** [comment]
The loss of HP and gold together seems to show that the tasks didn't sync with the server. This usually happens due to sending too many requests (clicking too fast). Generally, you want to refresh Habit before the end of the day, so you're sure that the data you're seeing matches what the server has stored.

You can also check with the [Data Display Tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html), as it pulls its information from the server.
