### ISSUE TITLE
Massive data loss

### ISSUE THREAD

**Issue by ericwilmoth** [HabitRPG/habitica#368]
yesterday I made sweeping changes to my habit lists and entered lots of points, so this morning I go to refresh the page so that the dailies update, and all of the changes I made are gone (as well as the points added); it's like yesterday never happened...which is very frustrating. I love this thing...because it's really helping me get on task...but I've effectively lost more than an hour's work.

I saw this happen early on, too...but I was getting the hang of things, and I know you guys are hammering on it to work out the bugs (and yes, I've contributed via kickstarter)...and so I'm wondering, what is being done to make data entered more secure? Is there going to be a 'save' feature? can any of my data from yesterday be restored? I'm reluctant to even touch it until I can be confident that my changes will not go 'POOF!'

**Comment by StanLindsey** [comment]
@lefnire will know more about this but I'm fairly sure your data is not truly being lost, its just an issue with getting it to display on page-load. Arguably there is no difference from the perspective of the end user. Not only are these issues getting better every day (as you noticed in relation to how bad things were a few weeks ago) but we'll be adding additional UI elements to confirm to you when things are saved. Think those Google Drive status notes at the top of the page letting you know all is saved.

Thanks for the input and thanks for sticking with it. Sorry about any frustrations you have =(

**Comment by wc8** [comment]
I think 

> I'm fairly sure your data is truely being lost

was supposed to be 
 I'm fairly sure your data is **not** truely being lost

**Comment by Nelmalih0** [comment]
This happened to me too, all of my habits and rewards just disappeared

**Comment by StanLindsey** [comment]
Thanks @wc8 - that is indeed what I meant. ;)

**Comment by ericwilmoth** [comment]
Thanks for the feedback. So, if the data is not being lost, what can I do to restore it? I've tried clearing the cache in my browser (firefox), but no dice.

**Comment by lefnire** [comment]
Oh no - I haven't heard this issue in so long, I thought we defeated it! If _changes_ you made yesterday are gone, @ericwilmoth, then indeed it sounds like those changes got lost. On the other hand, @Nelmalih0 - all tasks disappearing is a glitch - if a refresh doesn't fix you, [email me](mailto:tylerrenelle@gmail.com) your uuid / username and I'll see what I can do.

@ericwilmoth we're working on a status feedback for items saved, though a save button in particular won't do any good because everything is synced automatically. If changes don't sync, it can't reach the server for one reason or another. You might have started adding tasks during a long bout of downtime. Did you refresh yesterday at any point, and see the changes stick - only to find them gone today? Or was it one long session, and this is the first refresh since all those changes? If # 2, we can't restore unfortunately. If # 1, send me your uuid and what time-ish you know your character was in a good spot and I'll try to find you in the backups.

Our first order of business now that the KS tipped, is to implement a test harness using CasperJS to for some _major_ bug fixing. We've already got a contractor for the job. This will prevent future issues like this. In the mean time, my recommendation is to refresh every time before you're about to make any big changes.

**Comment by lefnire** [comment]
What timing! We have an explanation : #371

**Comment by ericwilmoth** [comment]
Thanks again for the rapid responses! I checked out #371...though that's a little over my head, technically. 

I don't think i refreshed yesterday, unless it was early on...before I made most of my changes. So, it sounds like for now I should test-refresh every few changes or so to make sure things are sticking?

**Comment by lefnire** [comment]
Yeah. like, the workflow is - have it open in a tab like you do, do some work, etc - then right before you're about to make any big changes on Habit, do a refresh. Each refresh should put you in a "good session" for a few hours, but if that session is broken by the server going down, you'll lose subsequent data. I'm quite confident #371 is the solution to this (Thanks @Olathe!), so I'll be pushing a fix soon

**Comment by ericwilmoth** [comment]
Thanks--you guys are really on top of things! Congrats on the Kickstarter success!

**Comment by lefnire** [comment]
We'll be more on top with a testing harness, I feel soooo bad when people just straight up _lose_ data. God. Anyway, thanks man! and glad you're sticking around through the roughness :) The fix has been pushed, hopefully this shouldn't happen again!

**Comment by ericwilmoth** [comment]
Hey, when you've got an idea this good, riding out the bug-waves is worth it!

**Comment by kwilson328** [comment]
I was experiencing the same issue, and appreciate the refresh advice and insanely fast response time. Proud to have donated to the Kickstarter! This app changed my life!

**Comment by lefnire** [comment]
yeah, it's a pretty terrifying glitch - i gotta get that sorted out :)
