### ISSUE TITLE
Support Bitcoin as a means of payment [$50]

### ISSUE THREAD

**Issue by ripper234** [HabitRPG/habitica#3684]
Hi folks, lovely game you have here! (A friend showed it to me the other day).

I noticed you don't accept Bitcoin, and I think you should.
1. It's [rather easy](https://en.bitcoin.it/wiki/How_to_accept_Bitcoin,_for_small_businesses) to do it. You can integrate with something like BitPay, and get all Bitcoin payments as either Bitcoin, USD, or some combination thereof.
2. There is zero risk involved. Literally, it's perhaps 1-2 days of integration work, and that's it.
3. You're going to get free publicity. I'm posting this issue to reddit, and once you do accept Bitcoin, that's another post right there.

Rock on!
##

**Comment by ripper234** [comment]
http://www.reddit.com/r/Bitcoin/comments/29vuad/lets_get_habitrpg_to_accept_bitcoin/

**Comment by sanblu** [comment]
Came across this project via the reddit entry mentioned above, absolutely love it. Will be happy to subscribe once bitcoin payment method is an option.

**Comment by ripper234** [comment]
@sanblu - FYI only some premium features cost money, you can check it out even before they accept Bitcoin.

**Comment by deilann** [comment]
This is desired, but not super high priority. Also, we tend to use our [Trello](trello.com/b/EpoYEYod/habitrpg) for feature requests, not Github. However, I wanted to point out that if you wanted to sweeten the pot a little, give the developers more incentive (beyond you subscribing) to accept cryptocurrency, Bountysource, which we use, now accepts Bitcoin. So I'll leave this issue ticket up, for anyone who desires to put a bounty on adding cryptocurrency as a payment option!

(Also, sorry for the late response. I thought I'd already responded, but apparently not!)

**Comment by SabreCat** [comment]
Yeah, it's a little disorienting that feature requests go on Trello... unless you want to put a bounty on them, in which case you need a GitHub ticket. >.< Here's hoping for Bountysource-Trello integration in the near future!

**Comment by sanblu** [comment]
@deilann Thank you very much for the comments and the remark regarding Bountysource accepting Bitcoin. I just put up a bounty of 50 USD to support the devs.

**Comment by steelstyle** [comment]
I might start a solution with bitpay, but bitcoin doesn't provide recurring payment.

**Comment by ripper234** [comment]
https://www.coinbase.com/docs/merchant_tools/recurring_payments

**Comment by steelstyle** [comment]
From my research and some talk in #bitcoin irc : coinbase is something to avoid.  Also as this would also break behavior for user who have coinbase wallet and user who don't. ( I do believe that recurring payment are somehow not respecting the bitcoin protocol). But something we could do is send them a reminder.

**Comment by srwalter** [comment]
I would certainly not advocate requiring users to use a coinbase wallet,
which coinbase's recurring payment feature would.  However, I don't think
anyone would object to also supporting it in addition to pure
bitcoin+reminders. I would agree with starting with the pure bitcoin
approach, however.

**Comment by ripper234** [comment]
There is no recurring payment option inside the Bitcoin protocol.
Any solution for recurring payments would have to be either
semi-manual/custom (you remind your users when they need to pay), or
automated via a 3rd party.

If you have to use a 3rd party, Coinbase is a pretty decent option.

On Mon, Nov 17, 2014 at 5:15 PM, Abou Konaté notifications@github.com
wrote:

> From my research and some talk in #bitcoin irc : coinbase is something to
> avoid. Also as this would also break behavior for user who have coinbase
> wallet and user who don't. ( I do believe that recurring payment are
> somehow not respecting the bitcoin protocol). But something we could do is
> send them a reminder.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3684#issuecomment-63318889.

## 

Ron Gross
CEO & Co-Founder, ReverseFunder
Skype = ripper234, Schedule my time - meetme.so/RonGross
CNO http://www.chiefninjaofficer.com/

**Comment by ripper234** [comment]
+1

On Mon, Nov 17, 2014 at 5:19 PM, Steven Walter notifications@github.com
wrote:

> I would certainly not advocate requiring users to use a coinbase wallet,
> which coinbase's recurring payment feature would. However, I don't think
> anyone would object to also supporting it in addition to pure
> bitcoin+reminders. I would agree with starting with the pure bitcoin
> approach, however.
> On Nov 17, 2014 10:15 AM, "Abou Konaté" notifications@github.com wrote:
> 
> > From my research and some talk in #bitcoin irc : coinbase is something
> > to
> > avoid. Also as this would also break behavior for user who have coinbase
> > wallet and user who don't. ( I do believe that recurring payment are
> > somehow not respecting the bitcoin protocol). But something we could do
> > is
> > send them a reminder.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/3684#issuecomment-63318889.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3684#issuecomment-63319528.

## 

Ron Gross
CEO & Co-Founder, ReverseFunder
Skype = ripper234, Schedule my time - meetme.so/RonGross
CNO http://www.chiefninjaofficer.com/

**Comment by ripper234** [comment]
BTW I think that the Coinbase solution already does this.
I think it allows one-time payments regardless of the choice of wallets,
and simplifies the process if you have a Coinbase account.

I don't know how recurring payments work there.

On Mon, Nov 17, 2014 at 5:45 PM, Ron Gross ron@reversefunder.com wrote:

> +1
> 
> On Mon, Nov 17, 2014 at 5:19 PM, Steven Walter notifications@github.com
> wrote:
> 
> > I would certainly not advocate requiring users to use a coinbase wallet,
> > which coinbase's recurring payment feature would. However, I don't think
> > anyone would object to also supporting it in addition to pure
> > bitcoin+reminders. I would agree with starting with the pure bitcoin
> > approach, however.
> > On Nov 17, 2014 10:15 AM, "Abou Konaté" notifications@github.com
> > wrote:
> > 
> > > From my research and some talk in #bitcoin irc : coinbase is something
> > > to
> > > avoid. Also as this would also break behavior for user who have
> > > coinbase
> > > wallet and user who don't. ( I do believe that recurring payment are
> > > somehow not respecting the bitcoin protocol). But something we could do
> > > is
> > > send them a reminder.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/HabitRPG/habitrpg/issues/3684#issuecomment-63318889.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/3684#issuecomment-63319528.
> 
> ## 
> 
> Ron Gross
> CEO & Co-Founder, ReverseFunder
> Skype = ripper234, Schedule my time - meetme.so/RonGross
> CNO http://www.chiefninjaofficer.com/

## 

Ron Gross
CEO & Co-Founder, ReverseFunder
Skype = ripper234, Schedule my time - meetme.so/RonGross
CNO http://www.chiefninjaofficer.com/

**Comment by steelstyle** [comment]
The bitcoin implementation with bitpay is ready for review.

**Comment by lefnire** [comment]
Sorry for the delay on this, I've got a lot on my plate re: payments for the next month. I'll have to hold off on this PR until things have settled down & ping ya back

**Comment by steelstyle** [comment]
Yes, I could see that lot of things was going on about the payment, thanks for advising.

**Comment by steelstyle** [comment]
Hey @lefnire is there any improvements ?

**Comment by steelstyle** [comment]
Just to be sure is it okay for me to work on it again ?

**Comment by Alys** [comment]
In https://github.com/HabitRPG/habitrpg/pull/4262#issuecomment-110353260 we reluctantly decided that we were not currently able to support Bitcoin, so I'm closing this issue.

**Comment by koalalorenzo** [comment]
I decided to not subscribe to the service just because you are not supporting Bitcoin, but I may find interesting the reasons behind your decision. Why you decided to not support Bitcoin @Alys ?

**Comment by Alys** [comment]
@koalalorenzo From my point of view, it was a matter of us not having enough admins and enough time to be able to support it. I deal with all the emails from our users who ask for help with subscription and gem purchase problems. This includes problems from payments that failed for various reasons, payments that were duplicated because the users accidentally subscribed twice, payments that were made but the users didn't want them to be made because they'd changed their mind about subscribing but had forgotten to unsubscribe, and other issues. For this, we already need to deal with PayPal, Amazon, Stripe for credit cards, Google app purchases, and iTunes purchases. Adding another purchase option would add more complexity to an already complex task.

One of the most common issues I need to deal with is giving refunds because users have changed their minds about purchases that they'd signed up for. When we looked into refunds for Bitcoin, it seemed troublesome for financial reasons. There was no guarantee of stability in the Bitcoin exchange rate, and if a player had paid using Bitcoins and demanded a refund in the same currency, we could lose a lot of money if the exchange rate had changed dramatically. The potential risk seemed to outweigh the potential benefit.

Another factor for me personally is that all of the time that I spend on dealing with purchase issues comes out of my free time. I'm a volunteer and don't get paid for any of that work. This means that minimising the time I spend on it, and minimising the stress it puts me under, is important to me, since it affects my personal life. This is not to say that I mind doing  that work - I did literally volunteer for it :) - but I did not want to add Bitcoin to the mix because it seemed more risky than the other methods and hence more stressful.

We also needed to consider the programming time required to support Bitcoin. We understand that volunteer developers were willing to develop the new code for it, and we did appreciate their willingness, but we would also have had to spend time reviewing and testing the code manually, and writing (or reviewing) automated tests for it, and at future times when our code based changed (e.g., to upgrade third-party libraries or to improve our test suites), we would have had to re-test the code and possibly modify it. Once code is added to any project, it's not necessarily finished there. There's usually an ongoing "cost" to supporting it, which can sometimes outweigh the benefits from having that code.

When we balanced all these reasons (and perhaps other reasons that other staff/admins had that I'm not aware of) against the benefits, it seemed to be best overall to not support Bitcoin. We are aware that some people will refuse to subscribe because of this, but we have only a small number of admins, and we have many demands on our time (support, development, bug fixing, etc), so we need to make decisions about where we can best spend our time. Bitcoin did not seem to be one of the best options because of the added complexity and risk.

**Comment by koalalorenzo** [comment]
Thanks for your quick answer! I have to say that I really appreciate that and I understand. BitPay made some changes to help the users to be refunded, as well as I don't really understand why you should refund somebody with more Bitcoin than you received! 

Anyway, that is helpful to understand why a service thinks that Bitcoin is risky and complex. Thanks!
