### ISSUE TITLE
New task fields have "please fill out this field" hover text on Firefox

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3705]
When I'm using Habit on Firefox, mousing over one of the New (tasktype) fields produces an alt-text-like tooltip saying "Please fill out this field." It's a superfluous thing, best removed if possible.

It doesn't appear to do the same on Chrome, oddly enough.

**Comment by kangabell** [comment]
This is how Firefox handles the HTML5 "required" attribute. Since those fields have the attribute "required", the browser adds that message on hover. To my knowledge there is no way to remove it (as long as the field is "required"), but with some javascript the message copy can be modified. See: http://stackoverflow.com/questions/13798313/set-custom-html5-required-field-validation-message

**Comment by AR-Student824** [comment]
> This is how Firefox handles the HTML5 "required" attribute. Since those fields have the attribute "required", the browser adds that message on hover. To my knowledge there is no way to remove it (as long as the field is "required"), but with some javascript the message copy can be modified. See: http://stackoverflow.com/questions/13798313/set-custom-html5-required-field-validation-message

You can also modify `title="something"` to change the hover text from Please fill out this field to whatever you wish
