### ISSUE TITLE
Unexpected level and gold

### ISSUE THREAD

**Issue by nihongineer** [HabitRPG/habitica#3714]
I'm on day 3 and really loving the web site.  For some reason when I logged in the frames wouldn't load and my avatar wouldn't display.  When I refreshed the page it permanently bumped me up five levels (level 2 > level 7) and gave me 80 or so gold I didn't have before.

Is there a way to get rolled back to my original stats without wiping out my account?

Edit:  Just noticed that my account has also been awarded the The Dread Drag'on of Dilatory medal, though I'm pretty sure I wasn't participating in that at all.

**Comment by colincreighton** [comment]
I also experienced this issue yesterday. Refreshed the page and jumped 4 levels. Looks like it's related to the Drag'on bug. Just manually reset my stats.

**Comment by Reminiszenz** [comment]
Had this bug too, fixed the character values manually but I still have The Dread Drag'on of Dilatory as a completed quest . Is there any way to get rid of that , since I didn't participate?
Possibly related : I also got the 12 Perfect Days achievement + buffs this morning , but my longest streak is 8 days , tried to reset that manually via the fix values too but it didn't do anything. 
I'm pretty new to habitrpg so it's entirely possible I did something wrong ^^°

**Comment by deilann** [comment]
Guys -- the glitch has not been able to be fixed yet because it was 1am
when it happened. Please give us some time. Perfect Day achievements have
nothing to do with your streaks. They are when you do all of your dailies.
You could easily have a longest streak of 8 days, and have 12 Perfect Day
achievements.

Just please, give us some time. You did participate, and the quest isn't
over yet, so really, just give us some time to sort things out.
