### ISSUE TITLE
Username blacklist

### ISSUE THREAD

**Issue by kluzny** [HabitRPG/habitica#3721]
I was able to sign up with the username 'administrator' would make for some confusing tavern talk if other similar names weren't caught at validation time.

**Comment by Alys** [comment]
That's an interesting point, however it's not as bad as it seems. In the Tavern (and all guilds), true administrators, staff, and moderators are all identified by a particular colour that's used as a background to their names. Also, very soon now, there will be an additional visual (non-colour) indicator that clearly marks admins/staff/moderators.

Also, the name that a person uses in the Tavern/guilds doesn't have to be the name they signed up with. They can change their name from the User -> Profile menu. There's also no validation on profile names, because of the visual indicators for admin names.

**Comment by crookedneighbor** [comment]
Closed per Aly's point.
