### ISSUE TITLE
Didn't hit boss for correct damage.

### ISSUE THREAD

**Issue by spade1350** [HabitRPG/habitica#3723]
I normally hit a wide range of damages greater than 40, but when i checked my damaged for yesterday it said I did 4.6. I had completed a lot of to-dos and all my dailies so this is just not possible.

my UUID
1cdbba7d-b6ec-4121-965e-db72f22d9944

**Comment by Alys** [comment]
This is a once-off side-effect of the Drag'on bug that's described in this [blog post](http://blog.habitrpg.com/post/91584540316/wow-whats-going-on) for details, and this issue: https://github.com/HabitRPG/habitrpg/issues/3712

Your damage from this point forward should be recorded correctly.

**Comment by Fractionless** [comment]
Progress notifications during our Egg quest have become glitchy as well, and it appears to be related to the Drag'on bug in [3712](https://github.com/HabitRPG/habitrpg/issues/3712) too, because that's when this began happening.

Notifications after the Drag'on bug began appearing like this: "(player) found . "

The last cron notification before quest completion reads "(player) found NaN Plain Eggs," followed by  "All items found! Party has received their rewards." 

It's sweet to have completed the quest, but there's satisfaction in knowing how much you contributed too!

Let me know what additional information you need (e.g., party ID) to continue.

**Comment by lemoness** [comment]
@Fractionless - This is, alas, also due to https://github.com/HabitRPG/habitrpg/issues/3712. Could you repost this over there? That way, the programmers will be able to see it and keep track of it! Thanks so much, and sorry about all of the hassle.
