### ISSUE TITLE
Vice, the Shadow Wyrm attacks party for 679.3 damage.

### ISSUE THREAD

**Issue by steelwolf** [HabitRPG/habitica#3731]
This is BS, under no circumstances should the boss be able to kill me thirteen times over in a single hit. Ever. Lol.

**Comment by deilann** [comment]
I'd guess what happened is a party member didn't sign on for days and days. All of the damage gets rolled up into one hit. However, there's almost no info to go off of here! Need a _little_ more backstory.

**Comment by steelwolf** [comment]
That's exactly what's happening, a party member logged back in after a while and I'm guessing a month of unchecked dailies combined. Sure, they could have have used the Inn or something; the point though is that this shouldn't happen, ever. When maximum HP is 50 there should be a cap on how much damage it is possible for a boss to do in a single roll regardless of how long it's been since party members were active, how many dailies are undone, etc.

**Comment by deilann** [comment]
But if the cap were, say, 50 (max HP), what would the difference be? (This
is a genuine question, not snarkiness.) Because I definitely don't think it
should be less than 50 -- after all, a player should have accountability
for doing their tasks. If it were less than 50, a player with a ton of
dailies might have no incentive for doing more. My current daily setup has
me starting out doing something like 150 damage. If doing a task doesn't
reduce that damage, it feels kind of... pointless. Especially if the cap
were less than max HP.

**Comment by steelwolf** [comment]
I have a party of three people and we have been fighting this dragon for seven months. I guess it's made for people with 150 daily tasks to check off, because that's certainly not how we've been using the website. We do between two and fifteen damage per person, per day. I find that ten daily tasks is about the maximum I can reliably expect myself to actually complete.

**Comment by deilann** [comment]
That sounds tough. Do you have no mages and/or warriors in your party? Casting Brutal Smash or Burst of Flames does quite a bit of boss damage, and is a good way to get some damage in. The boss isn't really meant for people with 150 daily tasks, but I can understand how you might feel that way.

However, it really doesn't answer my question -- how do you think that limiting the amount of damage the boss can do will change anything? If the boss does enough damage to kill you, it does enough damage to kill you regardless.

Again, I'm really not being snarky. I'm trying to understand what you think this will change.

**Comment by steelwolf** [comment]
I find it incredibly discouraging to be one-shot by a boss based on something outside of my control (another player not doing dailies or logging into the website). The maximum damage incurred on one party member by another party member should, in my opinion, be MaxHP/n of party. If maximum HP is 50 and I'm in a party of three, I shouldn't sustain more than 16.7 damage from one person's tasks. If all three of us do nothing and we all take 50 damage and die it makes sense. If two people do none of their dailies and one person does all of their dailies, the person who did their dailies should take, at most, 33.3 damage. What these massive damage amounts mean is that one person can be at full health, having done everything in their own power to stay alive, and be completely dead the next day because a party member forgot to log in.

**Comment by deilann** [comment]
I understand how that might be better for you, however, that could greatly impact the way that others use the site. In other words, it would damage the accountability they get from quests.

The whole party business can be tough. You're putting your trust in someone else's hands -- and with it, your character's stats. It can sometimes be difficult to find the right party, someone who... won't disappear or fail to do their dailies.

The good news is, I think it would be completely appropriate in this case for you to use Fix Character Values to get your stats back. Obviously this is frustrating you, rather than motivating you, so I wouldn't consider it cheating at all.

If you're not familiar with Fix Character Values, if you go to Settings (gear wheel on the toolbar) > Site, there's a button that will allow you to give yourself back the XP and GP you lost from the death. Make sure to also give yourself enough gold to repurchase whatever piece of equipment you lost!

Again, I understand you find it incredibly frustrating... but I know that for me, the fact that my dailies alone could kill my party is a major reason I'd do them at all. I highly suggest that you maybe see if there's a better party out there for you. I know you probably feel like you've sunk a lot into this fight with Vice, but with a party more suited to you, you might find that it goes faster and you feel better about it in general.

**Comment by steelwolf** [comment]
Three months into this horrendous fight I got tired of dying every day and deleted half my own dailies and gave myself 500 HP after each level up. As you can see from the title, even that is not enough to do anything when over 600 damage is applied in a single hit.

**Comment by deilann** [comment]
Well, you can't really have more than 50 HP -- that being the max and all, so no, that's not going to fix it. You can use Fix Character Values to restore yourself after a death, though.

If you're dying every day, yes, it sounds like this party isn't for you. I really do suggest that you find some folks who care whether or not they're dealing you extraordinary amounts of damage. After all, it seems like these folks don't.

**Comment by steelwolf** [comment]
You can use Fix Character Values to overlevel your HP, it works until the next level up when it resets to the max of 50.

**Comment by deilann** [comment]
Ah, good to know! I would thought when damage would be calculated, it might go away before the damage was applied.

**Comment by deilann** [comment]
But seriously -- at this point, I'd cut my losses and run. These folks do not sound like a lot of fun to party with, and it sounds like they're damaging your Habit experience. I'm sure you can find another group to party with, that will do basics like log in every day.

**Comment by steelwolf** [comment]
I think this is straying from the original point, which is that IMO it doesn't make sense that one person is capable of single-handedly wiping out the entire rest of the party independently of how well or poorly each person is doing on their own tasks. I'd love to see the multipliers that are being applied here.

This is a typical day of perfect completion from one party member: attacks Vice, the Shadow Wyrm for _2.4 damage_, Vice, the Shadow Wyrm attacks party for 0.0 damage. 

Here's a day with the same person missing a few: attacks Vice, the Shadow Wyrm for 1.7 damage, Vice, the Shadow Wyrm attacks party for _7.0 damage_.

If the only solution is "get better friends" maybe HabitRPG isn't really for me after all. :/

**Comment by deilann** [comment]
Vice has a STR of 3, which means that he does 1.5 times as much damage as a task does normally. So if you consider that tasks tend to do about 1-2 damage, that's easy understood numbers. Two tasks could deal out 7 damage. My guess, wrt the task values, is that your tasks are very blue at this point? The amount of damage you do, is related to Task Value as well, and it goes down as your tasks get bluer. Because if they're rather blue, the idea is that they aren't presenting a challenge to you.

And I understand that in your opinion it doesn't make sense for one person to single-handedly wipe out the rest of their party. However, I am saying that the fact that this can happen is what makes quests work so well for many other people. Changing that would greatly damage their Habit experience. Hence, it is very unlikely to happen.
