### ISSUE TITLE
Free gold (and food and eggs and XP)!

### ISSUE THREAD

**Issue by jtamanas** [HabitRPG/habitica#3759]
I just completed one of my old To-Do's that was extremely red. Upon completion, I leveled up  and gained 64(?) XP, 8 gold and about 30 silver (Sorry for not having exact numbers). I wanted to see if I would level down by unchecking this task, however. When I did, I did not level down, I lost 60 XP (which gave me a negative amount of XP), and lost around 7 gold and 80 silver. 

To check if this was all really adding up, I kept checking and unchecking the To-Do. Unfortunately, this also caused me to happen upon many eggs, potions, and foods, which all stayed in my inventory.  

All in all, after about 10 cycles of checking and unchecking the To-Do, I gained ~5 gold, 2 eggs, 3 pieces of food, and ~40 XP.

**Comment by deilann** [comment]
Yes, clicking and unclicking a task isn't going to give/remove exactly the
right amount of XP due to the way Habit's system works. If you search, you
can find a ton of issue tickets on this, all of which point to the same
master ticket. In the end, the amount you gain/lose is insignificant...
even 5 GP and 40 XP in higher levels is very little. The solution is not to
click and unclick a task 10+ times. Also, you have a daily drop cap, so not
losing the drop... not really a big deal.

So yes, please search before opening new issue tickets, and look and see
why similar ones have been closed.
