### ISSUE TITLE
Mana Regeneration misleading.

### ISSUE THREAD

**Issue by carsonbarlow** [HabitRPG/habitica#3779]
I thought that mana regeneration would be +1 per point allocated to intelligence per day.  I'm a warrior, and would have rather spent my points on strength if I realized that the mana I got was a one time gain.  I submitted a change to the wiki page that will hopefully clarify things for others.  May I have 3 gems to reset my stats please?

Thanks!

http://habitrpg.wikia.com/wiki/Mana_Points

**Comment by deilann** [comment]
Generally, I only give gems to solve bugs. The wiki article clearly states that MP regenerates at:

"Mana naturally refills at a rate of 10 MP or 10% of max MP (whichever is higher) per day and is added at cron."

When you compare with other statements:

"Players can also gain 1 MP or 1% of max MP (whichever is higher) per to-do or to-do checklist item upon completion."

which are clearly a one time gain, I think it was always clear (and has been to other users, before your edit) that it was a one time gain. Otherwise, it would have been mentioned with the daily gain.

I am sorry that you misunderstood, but I do not want to set a precedent for users to file bug reports because they allocated their points in a way that makes them unhappy, demanding gems so they can fix it. You are free to use your own gems to deallocate your points, or you can view the points in INT as something that will help you get to a Rebirth faster, after which, you can more carefully allocate your points.

**Comment by carsonbarlow** [comment]
Thanks for the quick response.  Although I am not happy because I didn't get what I want, I do understand the dangers of setting a precedent to something like this.  I accept your response.  I supposed that once I get around to subscribing, I can always just fix my money and buy the gems to reset my character.  This is a great product, and I look forward to being able to support it in the future. =)

**Comment by deilann** [comment]
Thank you so much for understanding! I cannot tell you how relieved I am to
see this kind of response.
