### ISSUE TITLE
Dailies unchecked not at cron

### ISSUE THREAD

**Issue by KateStrange** [HabitRPG/habitica#3780]
All of the dailies I did today just unchecked, but the undone dailies didn't damage me or break my streaks. It's still an hour and a half before my cron. May have had something to do with a party member logging in / getting damaged by quest boss.

Temp fix: deactivating all my dailies for today to avoid damage but also not get credited twice.

**Comment by deilann** [comment]
Actually, this most likely means that the dailies you did today never saved
to the server, which means you were never credited for them. This usually
happens when users click too fast. It saves locally, but fails at server,
so the tasks aren't unchecked until data is pulled from server (like when
damaged by a quest boss).

**Comment by KateStrange** [comment]
I checked in at least twice today, though (the second time after reloading my browser), and the second time my stuff was still checked. Wouldn't that mean it referenced the server?

**Comment by deilann** [comment]
Not necessarily, if it was drawing info from your cache.

**Comment by KateStrange** [comment]
All right, thanks!
