### ISSUE TITLE
Drops not displaying on webpage popups

### ISSUE THREAD

**Issue by nelle013** [HabitRPG/habitica#3787]
When you click a task or daily, there's a popup that tells you the XP, GP, and drops you earn. However I'm noticing that I get drops into my inventory without them showing up in a popup. This isn't a huge issue since I'm still getting drops... but I like seeing what each drop is without going to my inventory.

**Comment by deilann** [comment]
Do you use the mobile app ever?

**Comment by nelle013** [comment]
Yes. But I wasn't when this bug occurred. 

Janelle Rowe
School Psychology Student
University of Alabama
(585) 727-8433

**Comment by deilann** [comment]
I'm not sure what you mean when the bug occurred. The reason I ask is
because when you use the mobile app you get drops but the mobile app
doesn't give you a notification. That is a planned feature in the future.
What I am thinking is that those items are drops you got checking off tasks
on mobile. Is that possible?

**Comment by nelle013** [comment]
As I stated in my original post... I was using the webpage when I realized
that it was not notifying me about drops. They just appeared in my
inventory. I do use the mobile app, but I know that it doesn't notify you
about drops. I was using the webpage when i didn't get notifications about
drops.

On Fri, Jul 25, 2014 at 12:44 PM, deilann notifications@github.com wrote:

> I'm not sure what you mean when the bug occurred. The reason I ask is
> because when you use the mobile app you get drops but the mobile app
> doesn't give you a notification. That is a planned feature in the future.
> What I am thinking is that those items are drops you got checking off
> tasks
> on mobile. Is that possible?
> On Jul 25, 2014 9:41 AM, "nelle013" notifications@github.com wrote:
> 
> > Yes. But I wasn't when this bug occurred.
> > 
> > Janelle Rowe
> > School Psychology Student
> > University of Alabama
> > (585) 727-8433
> > Sent from my iPhone
> > 
> > > On Jul 25, 2014, at 10:27 AM, deilann notifications@github.com
> > > wrote:
> > > 
> > > Do you use the mobile app ever?
> > > On Jul 25, 2014 7:24 AM, "nelle013" notifications@github.com wrote:
> > > 
> > > > When you click a task or daily, there's a popup that tells you the
> > > > XP,
> > > > GP,
> > > > and drops you earn. However I'm noticing that I get drops into my
> > > > inventory
> > > > without them showing up in a popup. This isn't a huge issue since
> > > > I'm
> > > > still
> > > > getting drops... but I like seeing what each drop is without going
> > > > to
> > > > my
> > > > inventory.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/HabitRPG/habitrpg/issues/3787.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/3787#issuecomment-50174120.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3787#issuecomment-50174400.

## 

Janelle Rowe
University of Alabama
School Psychology PhD Program '16
585-727-8433

**Comment by lefnire** [comment]
Can't replicate on my end, getting drop notifs fine. @nelle013 do me a favor, on the start of a new day before you begin checking off tasks, open up Chrome Console to see if you get any errors when you check off the tasks?

**Comment by nelle013** [comment]
Okay. I will do that if you could tell me how to open up Chrome Console? I
googled and couldn't figure it out.

On Fri, Jul 25, 2014 at 1:24 PM, Tyler Renelle notifications@github.com
wrote:

> Can't replicate on my end, getting drop notifs fine. @nelle013
> https://github.com/nelle013 do me a favor, on the start of a new day
> before you begin checking off tasks, open up Chrome Console to see if you
> get any errors when you check off the tasks?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3787#issuecomment-50179207.

## 

Janelle Rowe
University of Alabama
School Psychology PhD Program '16
585-727-8433

**Comment by deilann** [comment]
Ctrl+Shift+i

I guess I'm just confused as to how you know these items are from website
and not mobile? Even if they're from mobile, they may not show up
immediately, and may only show up later as you're using the web app because
Habit relies heavily on cache. I have to specifically refresh my inventory
to see items I gained from mobile.

I mean, I trust you, I just don't know how I could tell, so I want to make
sure.

**Comment by iamcrumpet** [comment]
I just started having this same problem today. I too have the mobile app, but I haven't used it in well over two weeks. The problem only started today - I did a lot of ticking things off this morning and was sad I hadn't gotten any drops, but I went into my inventory and there were some there (they weren't from yesterday because I used my food yesterday night). Done nothing differently other than I THINK yesterday was the day I updated the HabitRPG app, but I haven't opened it or used it. I just updated it. I'm currently exclusively using the website on my desktop computer.

**Comment by nelle013** [comment]
Yea... I've found that it helps to use the User Data Display page
information at https://oldgods.net/habitrpg/habitrpg_user_data_display.html

On Fri, Aug 8, 2014 at 12:28 PM, iamcrumpet notifications@github.com
wrote:

> I just started having this same problem today. I too have the mobile app,
> but I haven't used it in well over two weeks. The problem only started
> today - I did a lot of ticking things off this morning and was sad I hadn't
> gotten any drops, but I went into my inventory and there were some there
> (they weren't from yesterday because I used my food yesterday night). Done
> nothing differently other than I THINK yesterday was the day I updated the
> HabitRPG app, but I haven't opened it or used it. I just updated it. I'm
> currently exclusively using the website on my desktop computer.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3787#issuecomment-51625381.

## 

Janelle Rowe
University of Alabama
School Psychology PhD Program '16
585-727-8433

**Comment by Zelah-Meyer** [comment]
I'm having the same issue as of today.  I logged into the Data Display Tool thinking I'd been remarkably unlucky with drops today and not received any - but saw that I'd apparently had three.  I've since gained another one - and I've tried watching for a couple of minutes in case a drop pop-up appeared, but it didn't.  I'm guessing I might have got food, as I don't think my egg or potion collection has changed.  However, I couldn't swear for sure that the drops have actually gone into my inventory.

Edited to add:  I'm using the website on my desktop.

Edited again:  I used a different browser to check off my last daily, so that I could see whether any drops showed up if I received one.  The Data Display Tool says I got a drop for it, but it didn't show up on that browser either.  The two browsers I used were Chrome & Internet Explorer.

Yet another edit!:  I've just remembered something that was different about today.  When I first visited the site this morning, I was back at the page you get when you're logged out, even though it normally remembers me and I go straight to my tasks page.  I clicked 'Play' and it then took me to my tasks page.  Thought I'd mention that in case that was significant.

**Comment by Zelah-Meyer** [comment]
I opened Chrome Console this morning (Ctrl-Shift-J on a PC) and I had to get a lot of tasks done before I got a drop (I refreshed the data in the Data Display Tool after every tick) - but I finally got one - and I could tell because I finally had an error message show up in the console!  Here it is:

TypeError: undefined is not a function
    at Object.fn (https://habitrpg.com/app-605e6bbd.js:22:31188)
    at i.$digest (https://habitrpg.com/app-605e6bbd.js:7:3756)
    at i.$apply (https://habitrpg.com/app-605e6bbd.js:7:5502)
    at o (https://habitrpg.com/app-605e6bbd.js:6:5430)
    at x (https://habitrpg.com/app-605e6bbd.js:6:7190)
    at XMLHttpRequest.s.onreadystatechange (https://habitrpg.com/app-605e6bbd.js:6:6839) app-605e6bbd.js:6

Hope that helps.  :)

P.S.  I can confirm this time that I did get the drop, because it was an egg & that was more noticeable!

**Comment by Alys** [comment]
There was a change made 8 days ago which made it impossible for drop notifications to appear for eggs and food (@Zelah-Meyer that was your "TypeError: undefined is not a function" - thanks for your detective work!). I've reverted that change in https://github.com/HabitRPG/habitrpg/pull/3870

However, this issue was logged 17 days ago, so there could be another bug somewhere. We can reopen this issue if people are still having problems.

**Comment by Alys** [comment]
NOTE: It might take a few days for my fix to be deployed to the website, and you'll still be missing notifications for eggs and food until it is deployed. Please don't re-report it in the next few days.

If it's still happen a week from now, then it's probably a different bug that we need to know about. Keep in mind that the mobile apps never report drops.

**Comment by Zelah-Meyer** [comment]
Thanks.  :)

Yes, it's still happening at the moment, but I'll hold fire for a week and speak up if it's still an issue.  Cheers!
