### ISSUE TITLE
Broken Party + Quests

### ISSUE THREAD

**Issue by Gizama** [HabitRPG/habitica#3794]
About 4 months ago our party started the **Egg Quest**. We _started it without other members_ in our party because they appear inactive. I believe we **completed the quest**. But, when I go to the party page, it shows the **egg quest still listed** with pending and accepted members, and **no Begin/Abort button**.

I **tried to start the Vice Part 1 quest**. The **first error** message told me I was already on a quest and could not start another one. The **second** time I tried I get the message "Please reload, "Error Group not found" (see Chrome console for more details)." Now when I check my party page, **the party is missing completely**. 

I have saved both Chrome Console messages if they are needed.

**Comment by Alys** [comment]
Do you have an achievement for the Egg Hunt quest? If so, you completed it. If you don't you definitely did not complete it.

Is it possible that some other party member recently started a new Egg Hunt quest? If so, and if the party doesn't want to do that quest, get that person to abort it. The scroll for it will go back into their inventory so they can use it at another time.

"I was already on a quest and could not start another one." That always happens when you are already on a quest.

If your party page does not show a party, and continues to not show a party after you have reloaded (wait a few seconds for it to reload completely) then you either left the party by accident or were removed by the party leader.

If you'd like us to investigate, tell us your User Id (read [API Options](http://habitrpg.wikia.com/wiki/API_Options) to learn how to find it). Without that, we can only make guesses and suggestions.

**Comment by Gizama** [comment]
I do have the achievement for the Egg Hunt 
![Egg Hunt](http://i59.tinypic.com/10wjxw0.png)

![Quest Image](http://i59.tinypic.com/30vbyvb.png)

![Actiivty](http://i57.tinypic.com/e9bsi0.png)

My user ID is 3f9c3b2f-d4c9-4271-9cf9-186063acce11

**Comment by Alys** [comment]
I would guess that some other party member recently started a new Egg Hunt quest recently. If so, and if the party doesn't want to do that quest, get that person to abort it. The scroll for it will go back into their inventory so they can use it at another time. If so, this isn't a bug; it's just a party member doing something you didn't know about.

However, please check one thing for me. Scroll down to the bottom of the quest invitation. If you see an orange "Begin" button then it means that you yourself started this quest. If you have no memory of doing so, then there might be a bug. If you do not see that Begin button, then all is well, there is definitely no bug, and you can close this issue.

**Comment by Gizama** [comment]
There is not Begin/Abort button, unless it's located in some other place, I'm scrolled all the way down in the image from my last reply. I've also checked in Firefox in case it was just an error with Chrome.

**Comment by Alys** [comment]
Then there is nothing wrong here. All that happened was that your party did finish the Egg Hunt quest (months ago) and then one of your party members started a new one recently. The party is not broken.  You yourself can't start a new quest because someone else got in first. This is how it's meant to work.

The "Error Group not found" message that you saw was just a temporary glitch that happens sometimes. As you've found, reloading fixes it.

I can explain further if you are still not sure what is going on, but otherwise, can you please close this issue? You'll see a close button on this page.
