### ISSUE TITLE
Chilling frost issue

### ISSUE THREAD

**Issue by amazuonna** [HabitRPG/habitica#3795]
A few times, I tried to cast chilling frost, did cast it, only for it to seemingly get de-cast at chron and me loosing HP.
After having some issues with the inn, i learned that syncing is important. So yesterday, I cast chilling frost, I pressed the sync buttion. Got rid of a few tasks and increased my MP a bit. I visit habit today and my MP is full, but I have 25 HP less. What is the issue?
Before I thought it was because I was on a quest but I am not on a quest now.

**Comment by deilann** [comment]
You would lose HP if you cast chilling frost. Chilling frost just preserves
your streaks.

**Comment by Alys** [comment]
It might be worth adjusting the text of the skill to state that.

"Ice erupts from every surface, swallowing your tasks and freezing them in place. Your dailies's streaks won't reset at the end of the day. **Incomplete dailies will still damage you!**"

The bold text is what I'd add. I'll do this in the next day or two unless anyone says otherwise. Feel free to provide better text, especially if it can be gamified a bit.

**Comment by SabreCat** [comment]
In general, I think we've been nudging toward more clear game-mechanical text on the skills, since the gamified stuff--while colorful--has obscured what the skills actually do at times.

**Comment by Alys** [comment]
PR to change the text as I described above: https://github.com/HabitRPG/habitrpg-shared/pull/254
