### ISSUE TITLE
XP for task not displayed during Level Up

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3796]
When you check off a task that causes you to level up, the "Level Up!" notification displays, but the amount of XP doesn't. It would be nice to see how much XP you got from the task that leveled you up :)

**Comment by Alys** [comment]
For the record, here's Ryan's explanation from the Tavern a couple of days ago for why this is done:

"The reason you don't get told the full amount of XP is because if you level up, it would show as the full amount of XP minus all the XP that's deducted upon leveling up. Players freak when it looks like you're losing XP, so the easy solution was to turn it into a 'Level Up!' notification, and turn off the XP gain notification."

**Comment by negue** [comment]
So can be closed?
