### ISSUE TITLE
Gear rewards do not display on site, do display on app

### ISSUE THREAD

**Issue by scalegraze** [HabitRPG/habitica#3797]
As above, I can create my own custom rewards, but the gear is invisible.
I can purchase it through the app however.

**Comment by Alys** [comment]
This is probably because you are a level 1 player. On the website, the equipment store unlocks at level 2. See the wiki's [Levels](http://habitrpg.wikia.com/wiki/Level) page for details.

If you are not a level 1 player, please add your User ID to this issue so that we can investigate this properly. [This page](http://habitrpg.wikia.com/wiki/API_Options) shows you how to find it.

If this has answered you question correctly, could you please close it? You'll find a close button on the page. But do tell us if this hasn't helped!

**Comment by scalegraze** [comment]
This answers the question.
Just leveled up and found the extra equipment.

Thank you!
