### ISSUE TITLE
Boss Missing Days

### ISSUE THREAD

**Issue by stellHex** [HabitRPG/habitica#3800]
The last 2 days, Vice did no damage to me and I did no damage to it. Should I be worried?
![screen shot 2014-07-28 at 6 27 02 pm](https://cloud.githubusercontent.com/assets/7636423/3728797/789e468c-16b0-11e4-9131-be333697ba1f.png)
(I didn't stay at the Inn)

**Comment by Alys** [comment]
There's a known issue where sometimes cron does not run, resulting in various effects including lack of boss damage. https://github.com/HabitRPG/habitrpg/issues/1057

I would guess that the damage you did today was very roughly two or three times as large as it normally is - this is the damage accrued over the past two/three days being applied to Vice all at once. However, I can't tell for sure since your screenshot is cut off on the right.

Since you're doing damage now, I don't see any reason to worry. 

If you're happy with this explanation, can you please close this job? You'll see a close button on this page. If you think what I've written isn't relevant, please provide more information:
1. Your User Id, pasted into this issue as plain text. See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.
2. Your Group Id, which you can find on the party page (a 36-digit sequence of random characters, like your User Id).
3. A screenshot of the entire party page showing the full messages about the Vice attacks. You can use an image editor to remove any personal messages from party members.

**Comment by Alys** [comment]
@stellHex : I'm pretty confident that this was just the https://github.com/HabitRPG/habitrpg/issues/1057 bug (you can use that link to track progress on it), so I'm closing this issue. It can be reopened if it turns out to be something else.
