### ISSUE TITLE
Potion type in "hatchingPotionNotes" text is not translated

### ISSUE THREAD

**Issue by bannmann** [HabitRPG/habitica#3802]
In the German locale (`de`), `hatchingPotionNotes` is translated as

> Gieße das über ein Ei und es wird ein `<%= potText() %>` Tierwelpe daraus schlüpfen.

However, on the web site, when I loot a hatching potion, I get popups like this:

> Gieße das über ein Ei und es wird ein **Base** Tierwelpe daraus schlüpfen.
> Gieße das über ein Ei und es wird ein **Skeleton** Tierwelpe daraus schlüpfen.

I first suspected that the hatching potion types were not yet translated, but they are. The expected results would be:

> Gieße das über ein Ei und es wird ein **Normaler** Tierwelpe daraus schlüpfen.
> Gieße das über ein Ei und es wird ein **Skelettierter** Tierwelpe daraus schlüpfen.

So it seems the `potText()` placeholder is always replaced with the English text, never with the German one.

**Comment by Alys** [comment]
From the habitrpg-shared repo:

```
locales/de/content.json: "hatchingPotionNotes": "Gieße das über ein Ei und es wird ein <%= potText() %> Tierwelpe daraus schlüpfen.",
locales/en/content.json: "hatchingPotionNotes": "Pour this on an egg, and it will hatch as a <%= potText() %> pet.",
```

Also related:

```
locales/de/content.json:    "eggNotes": "Übergieße dieses Ei mit einem Schlüpftrank und ein  <%= eggAdjective() %> <%= eggText() %> wird schlüpfen.",
locales/en/content.json:  "eggNotes": "Find a hatching potion to pour on this egg, and it will hatch into a <%= eggAdjective() %> <%= eggText() %>.",
```

When you view the Marketplace in German, and hover over the eggs and potions, both of those translations (hatchingPotionNotes and eggNotes) DO occur correctly. But neither of the translations occurs when those strings appear in the popup you get when you find a drop.

As a wild stab in the dark, maybe it's because of () in the <...> string? () isn't used in any of the other text that appears in popups, for example:

```
pets.json:    "egg": "<%= eggType %> Egg",
```

If translations are handled differently for popups compared to in-page text, then this might explain it, but I know very little about the translations code so this could be wrong.

@paglias can you advise?

**Comment by paglias** [comment]
@bannmann @Alys the problem is the same as #3531
