### ISSUE TITLE
Default bangs do not show head color

### ISSUE THREAD

**Issue by metasean** [HabitRPG/habitica#3807]
I just created a new user and, during the initial tour, when I went to change my avatar its hair color didn't change as I expected.  I did finally figure out that the new avatar's default bangs don't have a hair color.  It might be useful for other newbs to had a different default bang or move the bangs selection above the color selection.

priority - minor
interface

**Comment by Alys** [comment]
This is behaving as it's designed to, because the default bangs are no hair at all. The avatar defaults have been deliberately chosen to be as basic and gender-neutral as possible.

A better option might be to move the bangs to above the hair colour, so that the player will be encouraged to experiment with them first, and also to highlight the bangs in use (as equipment is highlighted), and perhaps to have on-hover text over each bang, saying for the first option "no hair". 

I've been contemplating having on-hover text for each avatar option because that would make it easier for players to describe which option they've used when they've created a specific "look" that they want to record permanently (e.g., on the wiki's [Cosplay](http://habitrpg.wikia.com/wiki/Cosplay) page).

**Comment by deilann** [comment]
Actually didn't we want to swap to orange ponytail? That would solve this
issue.

**Comment by lemoness** [comment]
We did indeed want to swap to orange ponytail - it just hasn't been implemented yet. I designed a new default avatar a while back. Can't seem to find that ticket?

But this is what the new default avatar was supposed to look like:
![sample character avatar default](https://cloud.githubusercontent.com/assets/3494081/3755065/4cc1215c-1821-11e4-8464-2d7d3f4bcb1b.png)

**Comment by metasean** [comment]
@lemoness - <opinion>As a dude, I'm totally cool with a ponytail on the default avatar, especially as it would likely help new users understand the relationship between the bangs and head color, but please don't put a flower on the default avatar</opinion>

**Comment by deilann** [comment]
As a dude, you'll be able to remove it and you'll know you can remove it.

A lot of thought was put into changing the default avatar to look more
feminine simply because men don't have to question whether or not their
gender will be represented in a game, however, women don't always have that
option. The current default avatar was meant to look gender neutral,
however, reads as male to most users. By having a more feminine default
avatar, it will cut down on how often we get asked how to make a female
avatar and accusations that you have to pay to be a woman.

In fact, the fact that the flower makes you uncomfortable should make you
question yourself. Why does a more feminine avatar upset you, when a more
masculine one doesn't? Why should the default avatar have to represent you,
rather than the other half of our users?

**Comment by lefnire** [comment]
*gulp*

**Comment by metasean** [comment]
@deilann - I'm aware that I could remove it.  (I'm assuming that existing user avatars aren't going to be changed, so I won't have to remove it from my avatar.  Of course, that means it's new users who are going to see it, and as we've discussed, for new users we know that the tour breaks the second you try to change your avatar while the avatar bubble is displayed. #2196)

As a guy I had the unusual experience to attend and graduate from a residential women's college [1] and have been very active in many predominantly female groups my entire life.  But this also means that I have been in enough situations where the default gender actually was female, and none of those groups would have gone so far as to "flower up" the default (and in many situations they would have found such stereotypical gendering to be even more offensive than I do).  So I understand this issue from both sides of the coin, and in a way that very few people can.  

I agree that while the current default avatar would be considered gender neutral by historical standards, it has more in common with men [2].  Since most people with long hair are women, simply adding the pony tail moves the pendulum to the female side.  But there are plenty of guys with long hair, so it certainly isn't excluding men.  **However having a flower in the hair makes me as uncomfortable -- in the same way and to the same degree that a beard on the face would make me [3] and for the same reason -- because it IS STILL GENDERING, the gendering just happens to be in the opposite direction.**  It's overcompensating and reversing the problem, but it's not resolving the problem.  **Why exclude either half of users?  Why not have a genuinely gender neutral avatar?**  The long hair accomplishes this.  (It excludes Sinéad O'Connor as much as it excludes Oliver North, and it includes Lady Gaga as much as it includes David Beckam.)

---

[1] For those who care, the school had a non-residential, distance education program for adults.  If we lived close enough then we were encouraged to attend classes on campus, and I had the opportunity to do so for my last two years.  Because of the school's curriculum, as well as discussions that likely only happen in such a female-predominant environment, I've intentionally examined more gender studies and feminist topics than most women have.  In the years since I graduated, I'm been unexpectedly disappointed at how uneducated most women are on these topics.  
[2] But the current default avatar still has more in common with [many, many feminine women](https://encrypted.google.com/search?tbm=isch&q=women%20%22short%20hair%22&tbs=imgo:1) than a flower in the hair avatar does.  
[3] IRL I have a beard, but I'd also never want that to be part of the default avatar.

**Comment by deilann** [comment]
I still don't understand why it's a problem to have a super feminine
default avatar. Adding the flower is actually kind of important because
it's so far down that many users aren't aware it's there and desire it. The
point is that users are not aware of the more feminine avatar options. This
portrays them so that users can make their own choice. Without the flower,
it wouldn't do that.

**Comment by thepeopleseason** [comment]
Just as a counterpoint, I'm a dude, and I wear flowers in my hair sometimes.

**Comment by lefnire** [comment]
Here's the other ticket for ref: https://github.com/HabitRPG/habitrpg/issues/1529

**Comment by lemoness** [comment]
Thanks for your feedback, everyone! By reading the other ticket that lefnire just linked, you can see the full details of our logic in selecting this avatar. It was prompted by many, many unhappy users who were sad to find "yet another game in which you can't be a woman." As a result, we've made the avatar appear to be a WOC - an option which, sadly, does not exist in many games - with the hope that this will make more of our users comfortable. Changing the default avatar in-game is immediately possible, but many new players were not finding either the long hair or the flower options. Until we change the UI to make these options more clear, having a default character with long hair and a flower is the simplest way to alert the user to these possibilities. 

Given that, and the fact that there has already been a long discussion about this, I think we will continue to use this avatar as planned :) Of course, we're not set in stone - if we receive a lot of negative feedback from new players who don't like the flower, we can always remove it in the future - but we'll give this one a try, first.

Thanks!

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg/pull/3834 changes the default avatar to have hair as described in https://github.com/HabitRPG/habitrpg/issues/1529 which should fix this issue (default bangs WILL show hair colour when this change goes live)
