### ISSUE TITLE
Streaks resetting every day

### ISSUE THREAD

**Issue by sthalor** [HabitRPG/habitica#3812]
It's been about a week now, my streaks have been getting reset when I get up in the morning. I'll get the streak bonus when I complete the task, but the next day it registers like I didn't do it. It doesn't even count the task as completed on the drop-down chart showing my progress, so my tasks are getting worse and worse for no reason. I use Habit on my Android phone, my work computer, and my home computer, but I don't see why that would cause any issue.

**Comment by Alys** [comment]
Sthalor, usually when this happens, it's because of sync errors the night before. Your browser knows you ticked the dailies, but it doesn't send that information to HabitRPG's server. This especially happens if you tick several dailies in quick succession, but can happen at other times too. Some tips:

When you tick one task (or take any action), wait for the thin blue line at the top of the screen to finish moving to the right and then disappear.

Just before you finish using HabitRPG for the night, press the sync button in the top right corner and wait for blue line to finish (or refresh on the phone app), and then check that all your dailies are still ticked. If not, tick them and sync again. Could you please try that tonight, and report back on the results?

**Comment by sthalor** [comment]
I tried that last night and none of my dailies were checked again. I synced
on every device I used and waited for the blue line to send after clicking
something, but its still showing everything as having gone down and it
reset my streaks. I also took a huge amount of damage. It seems that all of
the habits I checked off yesterday have gone down, as well, as if they
weren't even sent yesterday.

**Comment by deilann** [comment]
Rather than syncing can you check the data display tool? It will check
server side data, so it can't be mistaken.
https://oldgods.net/habitrpg/habitrpg_user_data_display.html in particular
you will want to look at how much damage it says you will take and what
dailies have not been completed.

**Comment by sthalor** [comment]
The data display tool is telling me something crazy. According to this, I
did none of my dailies yesterday, but the day before I did a bunch that I
didn't actually do. According to this, I'll take 9 damage today if I don't
complete any dailies.

**Comment by deilann** [comment]
Yeah, it sounds like something is keeping your data from syncing to the
server. Do you have a custom day start?

**Comment by sthalor** [comment]
No, my day start is at 0. Always has been.

**Comment by deilann** [comment]
Okay. I'm really sorry this is happening to you. I think one of two things
is happening: like Alys stated, it's just that things aren't syncing. If
that's the case, we figure out why and things should work out.

The other thing is that it could be the use of multiple devices. Are you
using the official app or a third party app?

Again, I know how frustrating this is, but I'd like you to look at the DDT
at the end of the day. If it says you're going to take damage, log out of
Habit on your computer then log back in. Check off all your dailies, making
extra sure to let the blue bar finish before clicking the next one.

Then, I'd like you to go a day only using Habit on the web app. I know it's
inconvenient but it will help us narrow down what's causing this for you.

**Comment by Alys** [comment]
@sthalor : How's this going for you? Are you still having problems even when you've checked for sync errors at the end of the day?

**Comment by sthalor** [comment]
I stopped using Habit for a weekend and everything seems to be working fine
now.
