### ISSUE TITLE
Remaining / Complete buttons are hard to get to with long To-Do lists

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3827]
I've recently begun the practice of scanning through my completed To-Dos as part of a GTD daily review type thing, and as a result I've discovered it's a bit of a headache to get to the Remaining/Completed switch buttons when the To-Do list is long. It's a lot of scrolling! Might it be feasible to put these switches at the top of the list instead of the bottom?

Perhaps they could be icons, next to the To-Do progress icon, if putting buttons at the top of the list would throw the balance of the task columns out of whack.

**Comment by deilann** [comment]
My workaround (for your use, not to fix this) is to enable a tag to get to the remaining/complete button.

**Comment by SabreCat** [comment]
Yeah, that's a solid workaround. Filter, swap to Complete, unfilter.

**Comment by ghost** [comment]
I've been messing around with this a little bit, and this is one of the better options I've found so far. It feels a bit weird with the empty spot from the add task form, but it makes the buttons easy to get to and retains their location. Any feedback?
![screen shot 2014-08-29 at 11 41 42 am](https://cloud.githubusercontent.com/assets/8461012/4092538/94a48908-2f93-11e4-949a-12fa64cd46fb.png)
![screen shot 2014-08-29 at 11 42 52 am](https://cloud.githubusercontent.com/assets/8461012/4092542/9619d5e0-2f93-11e4-838a-0d72d266fdd1.png)

**Comment by lemoness** [comment]
Paging @benmanley!

**Comment by benmanley** [comment]
Looks OK to me. If you do it this way, it would be good to bump the remaining / completed tabs down a bit to align horizontally with the first line of the other columns.

Do you need to hide the add task area when you're looking at completed tasks? Why not keep it there and just switch to the "Remaining" view when you hit the plus button?

One alternative to this layout might be a toggle button next to the stats button. Something like this:

![completed](https://cloud.githubusercontent.com/assets/3317594/4174710/b10f3542-35a2-11e4-9039-8963360ca29c.png)

**Comment by lefnire** [comment]
Oo, i like that approach @benmanley!

**Comment by lemoness** [comment]
I like the look of buttons, but that icon doesn't suggest "Completed
To-Dos" to me, and I'm not sure it would to a new user. Would it be
possible to have one button there that said "Completed", and then if
toggled, the button would switch to say "Remaining"? I know it's not as
aesthetically pleasing, but new users frequently have trouble finding new
features on their own.

**Comment by Alys** [comment]
It would be nice if whatever was done for this would be compatible with the similar requirement for Dailies, which needs three options (remaining, complete, all). A toggle wouldn't work for Dailies.

I think for these buttons, usability and clarity are more important than prettiness or space minimisation. The buttons are important for managing your tasks and should be very obvious to new users and very easy to use. I know that when Gaelan's [change for Dailies](https://github.com/HabitRPG/habitrpg/pull/3574) is made live, I'll be using the three buttons a lot.

**Comment by ghost** [comment]
At the risk of taking up too much space, we could do something more like a toggle. It might suggest to the user more that there's a state that can be changed, and get them to mouse over to see what it is.
![toggle](https://cloud.githubusercontent.com/assets/8461012/4203738/985e0bd6-3831-11e4-8541-1eb3f7de2751.png)

**Comment by Alys** [comment]
After thinking about this for several days, I'd really like to see the buttons kept as plain text, or at least as icons that are so obvious and noticeable that they can't possibly be overlooked or misinterpreted by anyone (and I suspect that designing icons like that might be impossible). Accessing tasks is so fundamental to the purpose of HabitRPG that it is essential that every user can always do so immediately without a moment's thought.

Support work has taught me that users don't always notice icons, or don't understand what they are for and are reluctant to click on them, or don't realise that they can hover over them for an explanation. If we changed the buttons to icons, I am certain there would be people asking how they could access their completed To-Dos ("WHY did you remove the BUTTONS?!"), or worse, accidentally viewing their completed To-Dos and being unable to get back to their uncompleted ones.

New users faced with too many icons and no clear way of switching task views would be more likely to go away and not come back.

But regardless, this issue started out as a way of making the Remaining/Complete buttons easier to access. Perhaps we can try moving the text buttons to the top as @kumarei initially suggested and see what people think? If they really do look too intrusive or take up too much space, then we could work on reducing their size/appearance in a second stage.

I would actually quite like to have the buttons at both the top and bottom to help people who have a lot of To-Dos (i.e., me :smile:). Also, having them at the bottom is actually more important now because a [recent change](https://github.com/HabitRPG/habitrpg/pull/4007) caused each completed To-Do to be sorted to the bottom, so if a user wants to undo an accidental completion, they'd need to go to the bottom of the list, and then having the "Remaining" button there would be convenient.

@kumarei, do you think you could experiment with code that puts the buttons at both top and bottom? But maybe automatically hide the buttons at the bottom if the user has fewer than about six To-Dos?

**Comment by Alys** [comment]
Gaelan's [change to add All/Due/Grey tabs to Dailies](https://github.com/HabitRPG/habitrpg/pull/3574) will be going live soon and I think those tabs are going to get a lot of use, so making the tab buttons easier to access will be even more important. 

@kumarei It looks like you made code changes locally for your [suggestion on 30 Aug](https://github.com/HabitRPG/habitrpg/issues/3827#issuecomment-53893535). If so, would you like to modify it for Dailies as well and submit a PR for it, or would you prefer that I do it? I'm okay with either option. :) The latest code for the Dailies tabs is at https://github.com/HabitRPG/habitrpg/pull/4129

I know there were suggestions for using icons instead of text tabs, but I feel strongly that for these tabs, clarity and ease of use are far more important than saving space. Disagreements are welcome, but I will continue to push my viewpoint with more words. :)

I'd also like us to consider having the tabs at both top and bottom. It looks a bit odd when there's only a few tasks (see screenshots below), but it would be very useful for people with many tasks (most players?), especially for Dailies. What do you all think?

![screen shot 2014-10-10 at 9 11 30 am](https://cloud.githubusercontent.com/assets/1495809/4585788/778fa616-500b-11e4-9ba4-6ab9d65f7a5c.png)
![screen shot 2014-10-10 at 9 11 43 am](https://cloud.githubusercontent.com/assets/1495809/4585787/7783463c-500b-11e4-8760-c890909ad756.png)

I played around briefly with code to make the bottom tabs appear only when there are more than x tasks, but to do it properly would be complex (need to count the tasks being showed not just the total number of tasks) and I don't think it's worth the effort (at least not initially; maybe after kumarei's proposed tab change goes live).

**Comment by lemoness** [comment]
These look great, and I also strongly feel that icons, while pretty, would
be obfuscating in this situation. I also agree that having tabs available
at the top will be excellent for usability. I don't mind having them both
at the top and the bottom!

**Comment by SabreCat** [comment]
+1 to text instead of icons, here. I'd be willing to try tabs at both ends--I personally would use the top ones the vast majority of the time, but I can see how it might help in some cases.
