### ISSUE TITLE
Challenge prize changed

### ISSUE THREAD

**Issue by psyche643** [HabitRPG/habitica#3862]
Before saving a challenge, I selected "Tavern" as the group the challenge was for, then hit "Save."  It reset the number of gems I had as the prize (7) to 1!  Now when I edit the challenge I cannot fix the number of gems.  It didn't delete any of my gems; I have 6 now.  I just want them to be part of the prize.

**Comment by psyche643** [comment]
My user ID is d669ba12-c0ba-45a1-a586-c00864acb7b3.  It would be great if you could move my six gems to that particular challenge.  It would be even better to have a way to edit prizes on a challenge after posting them, since deleting and reposting also deletes the gems from your inventory!

**Comment by Alys** [comment]
This might have been done "deliberately" by you but without you realising it because of the way that the gem field works (I often accidentally change the numbers in similar types of fields). That field can be changed by typing, or using the arrow burrons, OR by certain mouse/trackpad movements. For my laptop, if I do a two-finger scroll on the trackpad while the cursor is over the field, then the number changes. The two-finger scroll is what I use to scroll up and down pages, so what usually happens is:
1. I adjust the number with the keyboard.
2. While the cursor is still in the number field, I do a two-finger scroll to try to move up the page to the submit button.
3. I notice that the two-finger scroll caused the number to change instead of moving the page.
4. I fix the number with the keyboard.
5. I use a one-finger movement on the trackpad to move the cursor away from the field.
6. I successfully use a two-finger scroll to move down the page (the number does not change).

I would guess that certain mouse button/movement combinations might also have the same effect as a two-finger trackpad scroll.

@psyche643, is it possible that something like this happened with you? If you wanted to check, you could create a new challenge and test how the gems field behaves, without saving the challenge.

To have the challenge gems modified, you'd need to tell us which challenge it was (click on the challenge to get the unique ID number from the URL). However... I think only the lead developer / cofounder would be able to do this (no one else has database access) and it might take a while for him to do this. If it didn't take you long to create the challenge, you might find it faster to delete the current challenge (you will lose the gem) and create a new one. If you decide to do this, tell us and I will give you one extra gem.

**Comment by psyche643** [comment]
Great!  I will delete the challenge and accept the extra gem.  Yes, I think I just didn't realize how the gem field worked.  I will be more careful next time...  I appreciate this.  I have just deleted the challenge "Money Management."

**Comment by Alys** [comment]
You should have the extra gem now. Reload if you don't see it. If it still doesn't show up, you can reply here even though I'm about to close this issue (we'll still see reply notifications and we'll still be able to work on this).

**Comment by psyche643** [comment]
You are so awesome!  Thanks.
