### ISSUE TITLE
Infinite coins via resetting dailies non-stop

### ISSUE THREAD

**Issue by Fruglemonkey** [HabitRPG/habitica#3866]
If I toggle a daily on and off back on again, I end up net positive on silver coins. I gain 98 coins when I tick the box, but lose 97 coins when I untick.

Not sure if this is expected behaviour or not.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/964

It occurs because of the way rewards are calculated from task values and the way task values change when tasks are completed and uncompleted. It's a very low priority because if people want to spend their time cheating like this, it hurts no one but themselves. :)

**Comment by SabreCat** [comment]
Especially since you can cheat much more efficiently via Fix Character Values!
