### ISSUE TITLE
Phone Jumeped An Hour Ruining Perfect Day and Killing Me

### ISSUE THREAD

**Issue by lothlorienwoods** [HabitRPG/habitica#3872]
My phone jumped an hour and it made the cron reset before midnight, so I had a bunch of unmarked dailies and made us attack vice an hour early and  I died. I would have finished marking off my dailies for my 15th perfect day in a row. I want my perfect day and I want to reset this battle, since it was the first day, and I would have attacked with no unfinished dailies. I have worked real hard to get to where I am to have my perfect streaked runined because my crappy phone jumps an hour. I have OCD and not having a perfect day when I deserved it, ruining my streak does not help my ocd and anxiety.

**Comment by lemoness** [comment]
We're so sorry that this happened! That's incredibly frustrating. I probably would have thrown my phone across the room in despair :/

The good news is that it is easy to reset your battle. Simply scroll down through the quest bubble and click the "Abort" button. Your scroll will be returned, and you can start it again! :)

You can also very simply restore your lost stats by going to Setting > Site > Fix Character Values and resetting your level, HP, gold, and equipment. You can also restore Dailies' streaks by going to Task Edit :)

Unfortunately, there is no way to restore a perfect day bonus and achievement :( However! There are a few things that you can do to compensate for this. 

First, know that there actually aren't any "perfect day streaks" tracked in the game - every time you have a perfect day it is logged, but the system will not remove your previous perfect days or anything negative due to not having a perfect day in a row. That being said, it still totally sucks to lose out on your bonuses and your achievement. What I do when this sort of thing happens is create a "perfect day bonus" Habit that I can hit many times over the course of my day to give myself the extra XP and gold that I would have received if I'd had a Perfect Day logged by the system. It's approximate, which may not be as satisfying, but it is much better than nothing.

As for the achievement, there are other workarounds that you could use, like giving yourself a 0 gold reward called "Perfect Day Deficit." If at some point in the future you wouldn't have a perfect day, you can write down your stats, delete the reward, and check off all your Dailies. This will restore your Perfect Day Counter to the correct amount. The next day, you can use Settings > Site > Fix Character Values to restore your stats to what they would have been if you hadn't checked off the Dailies you didn't do.  If you want to be very comprehensive, you can even use the Data Display Tool (https://oldgods.net/habitrpg/habitrpg_user_data_display.html) beforehand to calculate how much damage you would accrue without checking off the Dailies you didn't do, and then the next day use Fix Character Values to subtract the exact number from your health! (Note that you'll need to do that BEFORE you check off the Dailies, though.)

I'm so sorry that there isn't a cleaner, more efficient way to restore a Perfect Day - we'll definitely need to look into that for the future! I hope that these workarounds help :)

**Comment by lothlorienwoods** [comment]
Thanks a lot!! This is very helpful!

**Comment by lothlorienwoods** [comment]
Lemoness, you rock!

**Comment by lemoness** [comment]
No problem :) I'm just glad I could help! Hope you have a much better day
today.
