### ISSUE TITLE
Language choice ignored on page change

### ISSUE THREAD

**Issue by Kingdutch** [HabitRPG/habitica#3882]
As I prefer reading English above Dutch I changed the language in the footer of the static pages to English. However on page change this setting is undone and I'm back to Dutch. Changing the menu links to append ?lang=en, where 'en' is the chosen language of the page, would fix this problem.

**Comment by paglias** [comment]
@Kingdutch hi! that button is implemented if for any reason, like your, you prefer to read the static pages in another language when you're not signed in, so it doesn't save the preference anyway (but it saves it in the game)

**Comment by Kingdutch** [comment]
I understand that but browsing your website is quite tedious if I have 
to change the language for every page I visit (and one of the reasons I 
left after two page views). The simplest fix would just be to not link 
to /static/nextpage but to /static/nextpage?lang=chosenlang once I've 
chosen a language once.

This doesn't persist the language accross sessions which is something I 
can live with (you could do that with cookies) but it at least makes 
sure that once I change a page's language, all subsequent pages are in 
that same language.

**Comment by paglias** [comment]
@Kingdutch you're totally right, sorry for my previous answer. I'll add this functionality as soon as possible. I'm thinking about session only because the situation where the user uses a differen language than system settings is already quite rare and would like to avoid it happening where there is a shared pc (libraries, internet points...) Are you ok with that?

**Comment by crookedneighbor** [comment]
I believe this is fixed. Please reopen if it is not.
