### ISSUE TITLE
Taking damage when checked into the inn

### ISSUE THREAD

**Issue by BabyCharmander** [HabitRPG/habitica#3885]
I'm in a party that's currently in the middle of a quest. I was on vacation for four days, so I checked in at the inn.

After returning from vacation, I found that party members had taken 45 damage... including me, even though I'm still checked in. Why is that?

**Comment by Alys** [comment]
This is intended behaviour. You'll find it documented on the Tavern page directly under the "Rest in the Inn" button (_"Be warned: If you are participating in a boss quest, the boss will still damage you for your party mates' missed dailies!"_) and it's discussed in the wiki's [Tavern](http://habitrpg.wikia.com/wiki/Tavern) and [Boss quest](http://habitrpg.wikia.com/wiki/Boss) pages. The reason is that party quests are a way to increase motivation by making every party member partially responsible for the safety of their party mates (if you know that you are going to damage other people, you are less likely to skip your dailies). This motivational feature would have some of its power removed if resting in the inn would protect party members.

If you want to rest in the inn while on a quest, it's advisable to check your account each day, if you can, to see if you need to buy a healing potion. Alternatively, you can ask healers in the party to keep a special watch over your health. You can also leave the quest by leaving the party and then having a party member invite you back in (you'll be back in the party but not on the quest) - give them your User Id before you leave (it's safe to paste it into party chat).
