### ISSUE TITLE
Double boss damage sometimes occurs

### ISSUE THREAD

**Issue by georgit** [HabitRPG/habitica#3893]
Not sure if this is a known issue, but in the past, I've had to refresh the boss page in order for my damage from the last day to be displayed. From what I can tell, if I refresh the page while it is being refreshed, it registers as a separate instance. I'm still trying to set up HabitRPG so I'm not sure how the code is set up but maybe there is a lock missing somewhere and both requests get served?

**Comment by Alys** [comment]
Reloading the boss page specifically doesn't trigger damage being applied to the boss or to the players. All it does is read what's stored on the server and display it. 

Here's what happens with damage: As you do tasks throughout the day, your damage TO the boss is added to a counter (not immediately applied to the boss). When you use HabitRPG for the FIRST time on the next day, the cron process runs. Cron applies the damage to the boss, and also tallies up your undone dailies and applies the damage from them to you (and it does some other things).

Cron is triggered by your first action on the site each day, so if your very first action was reloading the boss page, then that would have triggered cron, but not because it was the boss page - just because it was your first action.

The very first thing that cron does, even before applying damage, is it changes the date recorded for the last time cron ran to the current moment. This "lastCron" date is used to work out when cron should be run next. If lastCron is less than a day old, then cron will not run again. Hence reloading a page twice in theory should not cause cron to be triggered twice, although _maybe_ if you get the second one in fast enough it will. I'm not sure at what point the new date is written back to the database. The code is in habitrpg-shared repo, in the file script/index.coffee, if you're curious (roughly line 1165).

With the specific case you've noticed, was reloading the boss page your first action of the day? Can you describe what you saw that made it look as if damage was being applied twice?

**Comment by georgit** [comment]
Oh, sorry, I keep meaning to reply to this.

I really don't think reloading the boss page was my first action. I always
start at the tasks page, then go to social, and from there party. Then, I
sometimes do not see my damage from yesterday reflected, so I hit refresh,
and it loads up. This time I hit refresh twice and saw the boss damaged
twice.

I haven't set up habitrpg locally yet and even them, I'm not really a web
developer but it does seem like there's a race condition of some sort.
Silly question, but does lastCron take a look at seconds? It probably does.
Maybe a caching issue? It could be that everything just runs fine but I see
all the old information until hitting refresh.

-Teodor

**Comment by lefnire** [comment]
Are you also taking double damage on your dailies / todos? It could indeed be a race condition on cron, if you say hit refresh twice _really_ fast, then it could be the previous code is still processing and `user.lastCron` hasn't been updated yet. Perhaps we should have that var set first thing?

**Comment by georgit** [comment]
The boss page says I dealt 75.3 damage twice and took 0 damage back twice.
Also, it currently says both happened "3 days ago" although at the time I
remember it said same minute.

The case was rather unique; my internet was just being laggy so I slammed
refresh after a few seconds of the page not loading. But maybe that just
means it sent both bits of information twice? I am unsure how these actions
are relayed to the server; I have not worked with server requests
extensively. I may have also hit refresh twice very fast but I definitely
remember I waited a few seconds before rage-refreshing. Sorry I can't be
more helpful.

I would however agree that user.lastCron should be set first. That seems to
be just good programming if I remember my locks correctly.

I also see HabitRPG contributors would like more unit tests. Maybe this can
be investigated with one of those. If you load the boss page in a loop,
what would happen?

-Teodor

**Comment by SabreCat** [comment]
Something wacky is going on here--while we were running the first Mundane Quest, my "found 5 Bars of Soap" notification doubled, and so did the quest progress.

**Comment by Alys** [comment]
Tch. I've just realised this is a duplicate. I should have checked that days ago. @georgit, you can follow the progress of the fix by subscribing to https://github.com/HabitRPG/habitrpg/issues/2805 (Notifications section in right-hand column).  @SabreCat , you know the drill. :)
