### ISSUE TITLE
Difficulty info on right side of the screen

### ISSUE THREAD

**Issue by unholyHub** [HabitRPG/habitica#3894]
I registered today and after viewing the tour guide saw the difficulty setting and the info on the right side of the screen was cut off. So I decided to inform you for this behaviour.

![habitrpg](https://cloud.githubusercontent.com/assets/5253959/3978054/f0bb0e18-2842-11e4-9399-d8957c04ccd6.png)

**Comment by efim** [comment]
Do also have that.

**Comment by negue** [comment]
This is due to the angular-ui/bootstrap plugin, there is no way to set a Popover to an "auto" placement, so only one placements works, see angular-ui/boostrap#375.

Currently only hope is that the "auto" placement will be added in angular-ui/bootstrap, or we do have to refactor the popover width?

**Comment by kangabell** [comment]
Not sure if I'm understanding the issue because it says "right side of screen" but the popover I'm seeing cut off is on the _left_ side... I think this might be resolved though? 
@unholyHub @efim 
![screen shot 2015-01-06 at 2 22 23 pm](https://cloud.githubusercontent.com/assets/5122304/5634642/782f77a6-95af-11e4-8fd8-20885f6964d8.png)

The placement isn't quite right (https://github.com/HabitRPG/habitrpg/issues/4440) but at least it's legible.

**Comment by Alys** [comment]
Good point @kangabell, thanks.
