### ISSUE TITLE
The plate helm's image does not look right

### ISSUE THREAD

**Issue by loial1** [HabitRPG/habitica#3896]
The image representing the plate helm doesn't look the way it should I think. I'm having this issue on safari, OSX. The android application shows a different image, which seems to be the correct one. The image on safari, OSX:
![capture d ecran 2014-08-20 a 21 01 33](https://cloud.githubusercontent.com/assets/8407714/3986704/52cfc6fc-289d-11e4-9f85-a3e2e218ffd2.png)

**Comment by Alys** [comment]
Every time you see something looking a bit odd in HabitRPG (e.g., pixel art not being correct), reload the page using your browser's refresh function. That almost always fixes the problem but sometimes you might also need to clear your browser's cache.

Glitches like this happen because HabitRPG uses [image sprites](http://www.w3schools.com/css/css_image_sprites.asp) and when a new image is added to the sprite, sometimes your browser does not correctly pick up the modified sprite. Reloading forces your browser to do so.
