### ISSUE TITLE
Spontaneously new habit

### ISSUE THREAD

**Issue by Rici-chan** [HabitRPG/habitica#3901]
Hello,
today without input from me, a new habit writed itself down on my page. It is namend f21d7971-4ca1-400f-bbe9-93e2a5c22a01 and has the text "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task." I do not know if this is something from habitrpg or a virus, so I wanted to aks first.
Greets,
Rici-chan

**Comment by Alys** [comment]
duplicate: https://github.com/HabitRPG/habitrpg/issues/2558

@Rici-chan : This problem is described on the wiki's [Known Bugs](http://habitrpg.wikia.com/wiki/Known_Bugs#Habit_Added_by_a_Third-Party_Service) page ("Habit Added by a Third-Party Service"). You'll find a solution there too (delete the task). It's not dangerous.
