### ISSUE TITLE
No Health Potion API?

### ISSUE THREAD

**Issue by 71** [HabitRPG/habitica#3905]
So I've been through a lot of docs, and I still haven't been able to find any API for the Health Potion. Does it exist? As a 3rd party developer, can I add the ability to buy this potion, thus recovering some life? I think there is no thread talking about that, and if there are, I'm sorry I didn't see.
When I use the Dev Tools on Chrome, I can see that it comes from the "ItemStore", but I haven't found anything related to that in the API.
Thanks!

**Comment by negue** [comment]
I would also like to have an API for the ItemShop :)

**Comment by Alys** [comment]
@aedotj  : In the habitrpg-shared repo, script/content.coffee has this:
`api.potion = type: 'potion', text: t('potionText'), notes: t('potionNotes'), value: 25, key: 'potion'`
and locales/en/content.json has this:
`"potionNotes": "Recover 15 Health (Instant Use)"`

Even if you can't use the first piece of code directly in your third-party tool, you can mimic the health potion easily enough. Have a button or whatever that subtracts 25 GP and adds 15 HP - that's all the health potion does. You'd add checks to ensure the user had enough GP and to prevent HP > 50 but you'll likely already have code for those checks for use with rewards and skill casts.

You can use both pieces of code above to extract the gold code and health increase, in case HabitRPG ever changes them. Of course for the health increase, there's bound to be better code to monitor than the locale string (that was just the easiest piece for me to grab) - grep through the code base for "potion" to track it down.

Someone more familiar with the API than I am might give you a better answer than this but -25GP +15HP would be an easy thing to code if you want the feature immediately.

@negue : If the /user/inventory/buy/{key} API call isn't enough, then you'd need to provide more details about what you're hoping for, ideally in a different issue since health potions and gear work in a different way.

**Comment by lefnire** [comment]
[POST /user/inventory/buy/potion](https://habitrpg.com/static/api#!/user/user_inventory_buy_key)

**Comment by lefnire** [comment]
[Here's the code](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L632) for more info

**Comment by negue** [comment]
Oh, right , seems that I kinda forgot this api route.

@Alys what I would like to have is a short list of possible items to buy. AFAIK the list is generated in browser (by habitrpg-shared code)

**Comment by Alys** [comment]
@negue Have a look at `GET /content` from the "content" section of the [API](https://habitrpg.com/static/api#!/content/content). Use the browser's find feature to search for "flat" and you'll see this:

```
"flat": {
      "weapon_warrior_0": {
        "text": "Training Sword",
        "notes": "Practice weapon. Confers no benefit.",
        "value": 0,
        "type": "weapon",
        "key": "weapon_warrior_0",
        "klass": "warrior",
        "index": "0",
        "str": 0,
        "int": 0,
        "per": 0,
        "con": 0
      },
      "weapon_warrior_1": {
        "text": "Sword",
        "notes": "Common soldier's blade. Increases Strength by 3.",
```

`weapon_warrior_0` and `weapon_warrior_1` are items you can buy. In the "user" section under `POST /user/inventory/buy/{key}` you'll see those items in the drop-down menu. Is that the sort of information you're looking for? Tell me if it's not. :)

**Comment by negue** [comment]
On Item Information Part is this right, yes! Thanks. :)

On the other part, in the Website a User see a list of X Items which he can buy.

And this List would be great as an API-Call.

If not, I (using the API) would have create my "own" list of Items which a User can buy, and then I could also show Items which wouldn't be visible on the Website.

Kinda hard to explain :smiley:

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L134 (api.updateStore). Are you able to use that directly in your code?

**Comment by negue** [comment]
It won't be impossible but It would be take much time to create a working Communication between C# and an embedded Website which holds the compiled index.coffee script ^^ and then try to create a user object and pass it to the updateStore method. :zzz: 

Hm, I could try to create this API-Call and if it works I would create a pull-request, only If this kind of api call is "approved" :smile:
