### ISSUE TITLE
Died unfairly

### ISSUE THREAD

**Issue by Syndehy** [HabitRPG/habitica#3916]
This is total crap. Habit was reloading and failed to load and putting up all these errors while I was checking off my dailies yesterday and today I find a DIED because it didn't count anything I had done, even though when I checked it off it looked like it was fine. I even refreshed the page and looked again because I thought the errors might have reset something and it was all checked off! 

Now I lost all my gold (which was quite a lot) and items, and I CLICKED EVERYTHING LIKE I WAS SUPPOSED TO. 

This is totally unfair. I have been playing for months and never died and now I've lost everything because habit glitched out on me. 

Is there any way to get this reset? Or at least see if this was an error? I really have no intention of continuing to play at this point, and I was a donator. I wasted real money on something that glitched on me and ruined my whole experience. 

My API is: b3ff969f-bc6f-4bf6-9495-8bf36cf3921a

**Comment by lemoness** [comment]
I am so sorry that this happened to you :( That's incredibly frustrating,
especially since it wasn't at all your fault. There's good news, though -
there is a way that you can restore everything!

To restore your gold, items, level, and XP, you can go to Settings > Site >
Fix Character Values. Unfortunately we can't check what your exact values
were before they were lost, but it's okay to round up to account for all of
the stress of this experience :(

To restore your streaks, go to Task Edit and scroll down to where it says
"Restore Streak." You'll be able to enter the number manually. If you're
not sure what your streak was, you can check the graphs to approximate.

For the future, you may be interested in the Data Display Tool, found here:
https://oldgods.net/habitrpg/habitrpg_user_data_display.html If you find
that HabitRPG is having trouble for whatever reason, you can use this tool
to check how many of your Dailies are completed, to prevent this same thing
from happening again.

We're very sorry about all of this. Hopefully these solutions will help
you. We really do appreciate your donations to the site, and hope that you
have a better experience in the future!
