### ISSUE TITLE
Suggestion: Separate money for in-game rewards and other rewards

### ISSUE THREAD

**Issue by toebu** [HabitRPG/habitica#392]
I'd really love to get that awesome chain-mail. But then again there's this reward I've added that allows me to go out for dinner. I don't think I'll ever give up a real life reward for a new bunch of pixels on my character. But especially when I'm playing with a party, I still want to show how well I'm progressing with some new fancy equipment.
For me it would be great if the resource that is used to get in-game reward is separate from the resource for real life (user added) rewards. I imagine that every time you get one resource, you get the same amount of the other.
Maybe this would make things too complicated though as one would have too many resources (tokens, two kinds of money, experience). Instead of adding a new resource, one could use the experience points to get new equipment. In most RPGs, you can improve your abilities when you level up (or continuously as you get experience). One could interpret the spending on experience as learning to use a new type of equipment. It would also give the experience/level more importance than now.

I realise that whether this will be useful depends a lot on how one uses Habit. If you track a lot of things and get tons exp/money every day, you might not have this problem. Especially if you make your rewards cheap. But I think if you want to stay motivated, you need to make your money scarce, and then you'll always have to make the impossible trade-off between in-game and real life rewards.

What do you guys think? Do you have the same dilemma and would like this change?

**Comment by Pandoro** [comment]
Very useful idea!

I've been really struggling to get new stuff in game as well. If ALL the
money you get can be spend on ingame rewards, this is will be by far
easier. Furthermore it will become by far easier balancing your real life
reward costs, as you don't need to think about MAYBE also wanting that
fancy armor and thus making everything cheaper.

I really like it!

**Comment by wildcate** [comment]
For myself, I rather like the mixup of virtual and real-life rewards - I put in real-life things that I would ordinarily not get for myself, and foregoing the virtual rewards and spending the money (and the real money) on the real-life things makes them a very special thing for me. But if it does not work for you, why make things more complicated with two sorts of reward money? You could, for yourselves, decide to save coin until you can buy armour X for amount Y, and that then means you treat yourself to dinner in real life. No need for multi-balancing that way either... would that work for you?

**Comment by Pandoro** [comment]
For me it wouldn't be more complicated, but rather a means to the end of being able to buy virtual stuff. Right now it takes me more than a week to get a new item. I simply don't earn more gold, even though I work pretty hard on getting everything done. Each day I watch some series, I don't want to stop doing that, but I do want to pay some gold for that. I could decide to make all the rewards cost 1 gold, so that I can buy them and not loose to much gold. But then it will be hard to show the difference between a small and a big reward. 

Your idea is one possibility, but that for me would mean free series all day long, since I would just buy an item like once a week. So with my current playing style that doesn't really work out. 

The main benefit I see of splitting it, is that the player can easily handle the balancing of the real life rewards. You soon get a feeling of how much money you get each day and then you can wage how important that reward is for you. The reward for the ingame items could than be balanced by the game, so that every player, if they complete all their stuff, could progress in a similar way. My girlfriend got a full armor set on herself already, I just got a sword and she has lots of money left. So a bit of balancing would be a good idea in my opinion and it could become easier by implementing a thing like this.

**Comment by wildcate** [comment]
Since the difference is in your playing styles... I would (wildly) guess that your girlfriend uses the lists more intensively than you do. If you are working from home and use it to structure or keep track of freelancing business tasks, for example, that will mean much more use (and thus more gold) than just using it for some household or personal tasks after work. 

Maybe for cases like yours it would be a possibility to add a daily task with a special, pre-set worth of gold and XP? Like, say, 12 g/XP for "studying at uni" or "going to work and doing stuff there"? There's possiblity for cheating there, of course... but then someone who wants to beat the system will always be able to do so. And maybe it can have a global cap (no more than one special daily task, no more than x gold/xp on that task). 

And to get back to your answer.... it would not mean free series. You could either decide to keep paying a small amount for the series (half a gold coin, perhaps) or tie it in to the weekly reward-buying (I buy this sword, I also get to watch 7 episodes of series x during the next week).

**Comment by Pandoro** [comment]
Hmmmm yes, now that you explain it like this, it makes a lot of sense.
Hopefully soon the priority multiplier will be added. Then I can make a
daily called university and set it to a high reward. As you say... cheating
will always be possible and thus there shouldn't be all that much done
counteract it as this might also stop people from doing other things which
need to be done. With the multiplier, I can freelt change the stuff in such
a way that I can buy everything I want, even at the speed I want it. The
problem I still see a bit is that you will then get people that buy through
the full armor within just a few days and thus get bored. So I would still
say that there needs to be some way of slowing down how fast people can buy
armor.

I guess we should revisit this, once some new features are added. It might
be the case that this will not be needed in the long run.

Regarding the series, I wouldn't like to buy the full series set for the
whole week ;) Somehow I think this makes it less painful to see how much
points I spend on them. In the end I might even start watching more series
and that isn't my current plan ;)

**Comment by toebu** [comment]
Of course I can do what I described with the current system. As you said @wildcate, I could couple in-game rewards with real life rewards or say that I always use half of my coins for in-game rewards, the other for real life ones. But then I would have to again keep track of this outside of the application. I won't remember how much I already spend on which category of rewards and I can quickly go back to using a simple text file to keep track of my tasks, points and rewards.
Also, it doesn't work well to couple in-game rewards with the other ones, because the in-game ones keep getting more expensive: leather armor: 30, chain mail: 45, plate mail 65, and so on. This means I would get to my real life reward less and less often, or I would have to keep adjusting what things are coupled. Not an ideal situation either. I think its good that the items get more expensive, that's generally how RPGs work and probably what people expect. I don't mind to wait longer to get my in-game rewards, but I want to got out or watch my series every week, otherwise I'm quickly gonna lose my motivation.
Another thing that was suggested, is to make the real life rewards quite cheap to be able to get a big in-game reward (possibly linked to a real life one) at the end of the week. But if e.g. watching a series is to cheap, I might get tempted to just watch an extra one or two during the week and then not being able to get the big reward later. But this is probably another discussion (it's difficult to trade-off short-term and long-term rewards).

I'm not sure how much exp/money you guys make on average. If I look at my experience chart over the last few weeks, I seem to have gotten a pretty constant 50 exp/money per week (I've been good :) ). It might be interesting to have some statistics on how many points people get on average. @lefnire: did you ever extract some statistics from the db? That might be needed to decide on the usefulness of many features. (If you don't have time I could write some queries that you could run.)

One last point to clarify my suggestion: I don't think we should introduce a new type of money, it makes more sense to use the experience points. I didn't describe this very clearly above because I was just writing down what I was thinking, and didn't revise the idea after.

**Comment by toebu** [comment]
I know, I wrote too much, but I'm still going to push this again since I really feel this is important for the game after you've played for a few weeks.

Summary of my suggestion:
- Experience points are used to buy (learn to use) in-game items
- Money is used to buy custom defined (real life) rewards

Why?
In-game rewards get more expensive for every item you buy. Your experience and money intake stays roughly constant. This means you have to save longer and longer to get an in-game reward. This is OK, but in the mean time, you want to eat cake, watch series, go out to dinner, all draining your money. These custom defined rewards have a constant cost, and are going to be cheaper than the in-game rewards. If you want to save cash for an expensive in-game reward, you'll have to forgo some of your regular rewards. But getting regular rewards is important to stay motivated.
Therefore: a constant amount of real life rewards to keep you going through the day to day business bought with money and every now and then an in-game reward for the the long-term motivation acquired with experience points.

For more detailed reasons, read above :)

**Comment by Pandoro** [comment]
The question remains if you really need this if you simply earn more? Right
now I very much get what you are feeling. You might roughly make 5 gold a
day and spend 4 of the 5 on real life rewards. That means you need to save
up very long to get 30 gold for a cool new weapon and VERY long for the
next weapon etc. But once we get multipliers, we could normalize our stuff,
so that we actually earn, say 15 a day. Then we spend again our 4 on real
life rewards and save up the 11 for the other items.

I think what makes you want this, is that you cannot afford both things at
the same time, but your suggestion might not even fix this. Even if you get
5 for ingame AND 5 for real life rewards, then you will be able to get your
real life rewards as usual, but you still have the problem that you cannot
buy this cool new armor set which costs 200 gold, without saving up for
ages. So I think the problem is not that they are combined, but rather that
some people, like me and probably you, will earn too few GP each day. And
if at that point, you decide NOT to go to dinner for the extra 5 gold, but
rather want to buy the 200GP armor NOW, then I think you will probably see
the armor as a bigger reward than the dinner for that day ;)

Do you think that this might actually be the deeper reason for the problem?
Because when this idea came up, I really felt like it, but soon I realized
that at least for me it would not fix all my problems regarding a too low
GP income.

**Comment by toebu** [comment]
That's definitely an important factor, yes.
How about this: there should be a chest where you can put in some of your money. As long as the money is in the chest, it is not used for any rewards. So if you buy something that you don't have enough money outside the chest, you are going to lose health as if you wouldn't have enough money at all.
You can always put in money in the chest but you can only take some out once every week (or similar). And the most important feature: you can configure which percentage of your earnings go directly into the chest.

That could even be a better idea than what I suggested above, since you can also use it to buy other long term rewards (e.g. a weekend get-away).
What do you think? This would be much less intrusive and people could completely switch it off.

**Comment by wc8** [comment]
Correction (last link wrong): #438 (Currency/Gemstone idea.)

**Comment by toebu** [comment]
I'm closing this in favour of #438.
