### ISSUE TITLE
completing todo,  reduced health

### ISSUE THREAD

**Issue by kulalking** [HabitRPG/habitica#3929]
I have completed the todo after long time, it was red/yelllow todo . after  that i lost huge health (6)

as per the wiki we should not loose the health after completing the tasks

**Comment by Alys** [comment]
It's coincidental that you saw the health loss at the same time as you ticked off the To-Do. I guarantee that the To-Do itself did not cause the health loss.

Are you in a party that is running a boss quest? If so, it's likely that the 6 HP loss came from the boss attacking the party due to the uncompleted Dailies of one of your party mates. That damage would have been recorded by HabitRPG's server at some time in the past (maybe just a couple of minutes or seconds in the past, or a few hours), and then when your browser communicated with the server to tick off the To-Do, the server passed on the message to your browser about the health loss, and your browser then reported it to you.

If that does not seem to be an appropriate cause for the health loss, you can comment here again and give us your User ID. See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.
