### ISSUE TITLE
Duplicate popover bubbles after re-sorting task

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3932]
I just joined a Challenge and moved one of its Habits to the top of my list (by manual drag... the "push to top" feature hasn't quite sunk in for me yet!). Then mousing over the new position also started to show the notes popover at the old position as well as the new:

![screencap](https://cloud.githubusercontent.com/assets/4501321/4052496/1f70f4b0-2d6c-11e4-8dd0-ae53b3144522.png)

Hitting "Sync" clears up the issue, making this solidly minor in impact.

**Comment by lefnire** [comment]
[Switching to angular-ui-sortable](https://github.com/HabitRPG/habitrpg/commit/750135b6734b8a3978885e97d83bc14fb423a3cb) may have done more harm than good. I made the jump because jQueryUI#sortable was periodically providing very strange from/to indexes, causing wacky sorting "jumps". I figured, using Angular-aware module would be better as it follows the model (`user.habits`, etc) such that additions / deletions are accounted for. 

One thing worth testing is reverting to before that commit, and testing if this Notes issue is present before. If so, maybe it's not angular-ui-sortable's fault after all.

**Comment by Gaelan** [comment]
I would tried to git bisect this, but it didn't work because of habitrpg-shared.

**Comment by lefnire** [comment]
Bah! We've gotta get these repos merged. It's such a big task, but it's such a pain without...

**Comment by Gaelan** [comment]
Submodules might help for the time being.
