### ISSUE TITLE
Please assign me as Guild Leader

### ISSUE THREAD

**Issue by androidadvocate** [HabitRPG/habitica#3937]
Hello! My guild has been without leadership for some time. There is no way to find out who the leader was before, they may be inactive or left the site. Please assign me as guild leader, as I'm very active, and our guild needs a leader to pull us together. I heard in the chat that this can be done in the database side of things, 

Thank you!

Group ID: 8a191317-0c7e-44f7-ad4c-2947789d3868
My ID:d6ae8212-1a94-4d88-bd11-429be75412d9

**Comment by Alys** [comment]
Using the [API](https://beta.habitrpg.com/static/api) which reports publicly-available information about groups and users: the guild's leader is 1b47f98b-8ffd-41dc-8591-efffe32ff392 ("Winner") and they last logged in to HabitRPG on 11 August.

**Comment by lemoness** [comment]
Since the Leader logged in recently, I think we should leave them as-is. I
know that I went through a period of two months where I was so busy that I
couldn't participate in the Knitting and Crocheting Guild, but now I am
back and running Challenges again. I think Guild leadership should only be
reassigned when the Guild leader requests it, unless they've left the site
completely for a long period of time, such as a year.

**Comment by androidadvocate** [comment]
Great. Fair enough. He still has not posted anything in the guild for a few months. I'll try to reach him somehow thanks for the extra info. I think it's unfair on the other members when the leader is not active but at least we know who he is now. So umm....do i get my 15 bucks back?

**Comment by lefnire** [comment]
@deilann do you know how to refund?

**Comment by deilann** [comment]
I think you just cancel the bounty through bountysource?

**Comment by lefnire** [comment]
@androidadvocate maybe it was already refunded? Checking https://www.bountysource.com/issues/4077342-please-assign-me-as-guild-leader shows a $0 bounty.
