### ISSUE TITLE
Reorder completely broken after recent update.

### ISSUE THREAD

**Issue by Itshalffull** [HabitRPG/habitica#3941]
There is a pause when dragging and  dropping a daily to a new space, then instead of the dropped daily going to the correct place, a random daily will be moved to a seemingly random position.

**Comment by Alys** [comment]
Can you confirm that this is happening with Dailies? Not with To-Dos? The reason I ask is that it is a very common problem for To-Dos but very rare for Dailies, so we need to be sure that you really are having this problem with Dailies.

**Comment by Itshalffull** [comment]
Yes, this is happening with dailies for me.

**Comment by Alys** [comment]
Okay, then it's the same issue that's reported here: https://github.com/HabitRPG/habitrpg/issues/2667
You can follow the progress of the fix in that thread (use Notifications in the right-hand column if you'd like email updates). Could you please add a comment there stating that you're having this problem (pasting in the sentence from your initial message here would be good) and also add your User ID which you can find at https://habitrpg.com/#/options/settings/api (it will be a long string of random characters).

Something that MIGHT help: Manually sync with the server after you order your tasks (using the sync button in the top right of the tasks page). This forces your browser to send an update to the server with everything, including item order data. Do this especially if you are using HabitRPG on two or more devices, and then when you move to a different device, sync on that device before making any changes of any kind. If you try this a few times and find that it does not help, then give up on it. It's a bit of a stretch to be honest, since syncing is supposed to happen automatically when you move a task. BTW, when you do move a task and you see the blue bar appear at the top of the screen, wait until the blue bar has vanished before doing ANY other action on the page.
