### ISSUE TITLE
Party members and quest damage missing

### ISSUE THREAD

**Issue by gwenicus** [HabitRPG/habitica#3942]
A new friend just joined my party (Group ID: 7592b476-4c9b-49e3-a34c-84a790bcb2c3), and now for me, the party is displaying as just containing me and her, and our in-progress quest isn't showing up, and group chat is blank.

HOWEVER, when I got a notification related to our party yesterday and today, clicking that brought me to a version of the chat page that had the four original members listed (but not the new one), a full chat history, and quest damage for everyone except me.  (Older damage from before this issue started is still there).  The header still displays just me and the new member.  And when I refresh the party page, it goes back to being empty with just me and the new member.  

I have confirmed with one of the other members that she sees the party page with the four original members, but not the new person, and everybody's quest damage except mine.

I was traveling and had appallingly bad internet yesterday; I don't know if that's related to the problem.

**Comment by gwenicus** [comment]
Also, I've tried viewing the page in several different browsers, clearing history, logging out and logging in again, and nothing's helped.

**Comment by Alys** [comment]
Can you please paste in the Unique User IDs of all party members? You can find them on the Party page in the Members box in the left-hand column. Click on each person's name to see their profile and their UUID will be at the top.

EDIT: Hmmm. Of course that will be difficult since you can't see most of the party members. Sorry. :) Bewildebeest has posted in the Newbies Guild so I'll get them to help with UUIDs too. Just paste in the ones you can. :)

**Comment by gwenicus** [comment]
I managed to get all the UUIDs off the page I get linked to when there are messages posted in the party.  Thanks for your help!

gwenicus (me): 0fcc93cd-a567-4c64-98e3-b9abb0d66c43
bansheekitty (the new member): 69e659b0-39d1-4521-a660-1577c88a532b

Other party members:
bewildebeest: fc1b3c1a-fb3c-4070-acf3-7acf64432156
jspeed: 43e7f5b9-6003-44dd-a4da-387d09570997
ampere: 0aefacda-19b5-4b88-8c1b-cbcfc9acf594

**Comment by Alys** [comment]
@gwenicus Nice work. :)

For the record, here's bewildebeest's message from the Tavern explaining the issue from the opposite point of view:
_"More party weirdness to bother you guys with.. A 5th person was invited to join and then did join our party. However, only one other person in the party can see her. (Heh. Imaginary friend?) For me, I just see the original 4 members; for her, though, she suddenly just sees herself and the new party member. Also, her damage to our quest isn't showing up, but she's still listed as in the party and participating on my screen."_

@gwenicus : There's a couple of ways we can proceed.
1. We can ask Tyler (co-founder, chief developer, database admin) to fix this problem but it might take him a few days because he's always busy. For security and privacy reasons, he is the only person with direct access to the database and I think direct access will be essential for this.
2. You and your party could probably fix it yourselves: you and bansheekitty could leave the party and then one of the others could invite you both back. This should work, unless things are REALLY messed up! The disadvantage is that you (gwenicus) would no longer be taking part in the Gryphon quest. To fix that, your party would have to cancel the quest and restart it, and they would lose all progress made so far. (But an advantage is that bansheekitty could join the new quest! She wouldn't be able to if we use the Tyler option because it's impossible to join a quest that's already started.) If you choose this option, then to compensate you for this annoyance, I'd give you a free Gryphon quest scroll. If you can't communicate with your party about this, then you or I can do so via bewildebeest in the Newbies Guild.  (And I should have thought of this option earlier; it's only just occurred to me - sorry!)

Which option would you like to proceed with?

**Comment by gwenicus** [comment]
I'd been wondering about leaving the party and rejoining...That's probably the most straightforward option.  Would it affect it at all that I was the founder of the party?  Then, if that doesn't work, we can go to option Tyler.  And we would definitely be appreciative of a gryphon scroll; we are fans of pets. 

Thanks again

PS I've known our newest party member since we were both four years old.  I'm pretty sure she's not imaginary.  Probably.  Maybe.

**Comment by Alys** [comment]
It probably does mean that you would not longer be leader of the party; someone else would become leader at random. If that bothered you, we could ask Tyler to fix that - I think it would be an easier fix, and would not be so urgent for you I imagine? 

You being leader now will not stop this from fixing the current problem. I say try it! :)

Isn't four years old exactly the time that imaginary friends are developed? ;)  Please tell her from me that she has an absolutely adorable name.

**Comment by Bewildebeest** [comment]
Hey, sorry, I'm back!  Gwen, I'd rather like to finish this scroll, given that we're past the halfway point, and I think it'd be especially frustrating to our other two party members to have their progress suddenly erased (especially since this is their first quest).

Can you wait a few days while Tyler takes care of it?  (We could also discuss this elsewhere and come back with a decision.)

**Comment by gwenicus** [comment]
Ok, let's wait a few days and see if Tyler can fix it.  But if I don't get baby gryphons, can we do the quest again?

**Comment by deilann** [comment]
If Tyler can't fix it, I will manually grant you the eggs. :)

**Comment by Bewildebeest** [comment]
Of course!  Hm.  I'd sort of assumed that since you're still showing up on my party screen as part of the quest you'd still get the reward, but I guess if your damage isn't showing up, who knows...

So how do we get this to Tyler?

**Comment by deilann** [comment]
@lefnire (Tyler) has already been pinged, I believe but if he hasn't he now
has.

**Comment by Bewildebeest** [comment]
Thank you!

**Comment by lefnire** [comment]
So, for some reason @gwenicus belongs to two parties. Duplication operations happen periodically on a server down-swing. Eg, user account gets created twice, party-creation happens twice, etc. In this case, @gwenicus created a party, a duplicate create0op went through to the database, gwen belongs to both. That "bad" duplicate party ID started circulating, and now some members belong to one and some to the other. @gwenicus you may notice, if you refresh over and over and over, you'll sometimes get one party and sometimes the other.

Unfortunately, the solution is for everyone who's in the "bad" party to leave the party. Upon refresh, the "good" party will show up automatically, and if it doesn't you'll need to re-invite those users. I may be missing something here, does the "bad" party have some data tied up to it people don't want to lose?

ps, make sure when you click "Leave" to click "Confirm". That popover takes a bit of time, and some people miss it

**Comment by Bewildebeest** [comment]
Hi!

There's nothing we want to save in the "bad" party (I assume that means the accidental party of 2?), but we're currently doing a quest in the "good" party (the one that currently has 4 people but should have 5), and we don't want to lose our progress in this quest.  If she leaves, will the "good" party stay intact and have our progress still there?

**Comment by lefnire** [comment]
Yes indeed, as long as you only click "Leave" during a browsing session where the "bad" party is what you see.

To explain fully (to easy your fears):
- When a duplicate party-creation DB op goes through, it will create two separate parties, with the exact same details, but with different `_id`s (the thing that uniquely identifies the party)
- When you load up the page, the database say "give me the one party this user belongs to". Well bug, there's two - so it will give you one at random. 
- When you click "Leave", it will leave the party that you're currently viewing _right now_ in the browser, because it will send the `leave` operation with the `_id` of the group loaded in your browser - _not_ a backend-calculated party id.

The same goes for users with duplicate accounts. They need to delete the account, based on what's loaded in their browser currently. 

If you have any troubles, hit me up and I'll help out. The only reason I'm suggesting do it on your end is that the "Leave" op triggers some backend scripts which I can't trigger by deleting groups manually from the database

**Comment by deilann** [comment]
Can I suggest to turn the confirmation of leaving things (groups and
challenges) to an actual dialogue box? Leaving a challenge without pressing
confirm also causes issues.

**Comment by lefnire** [comment]
I'd like that too

**Comment by lefnire** [comment]
Oh, you know why we didn't do it. You can't provide JS confirm dialog with multiple options. The way these popovers work is if you have challenges associated with the party, it asks if you want to keep those challenge tasks, remove tasks, cancel, etc. Same goes for leaving challenges. We could do a modal if that's better than a popover, but I don't think we can use `confirm()` or `alert()`

**Comment by deilann** [comment]
Modal would be more obvious at least. Groups don't need multiple options
though just challenges yeah? Just confirmation?

**Comment by lefnire** [comment]
No, if a group has chals the member is participating in, it triggers the
same chal-leave options

**Comment by deilann** [comment]
Oh see I even screwed that up then last time I left some guilds.

**Comment by gwenicus** [comment]
Leaving the duplicate party worked like a charm for me; I started showing up in the original party right away.  I'll just wait to see if my quest damage starts showing up on chron tonight.  I think bansheekitty is now in a party by herself.  I assume we should tell her to leave that party and then send another invite?

**Comment by Alys** [comment]
@gwenicus : Yes.

**Comment by gwenicus** [comment]
So my quest damage is not showing up, despite several refreshes and signing out and back in.  However, I'm still listed as a participant in the quest and I took damage from another party member's missed dailies.  The party is displaying correctly in all other respects.  Any ideas about what's still wrong?  Thanks for the help.

**Comment by lefnire** [comment]
I think the damage wasn't accounted for during that period, it should pick back up next cron

**Comment by gwenicus** [comment]
Nope, second chron and still no quest damage.  Is it just this quest? Will it normalize when this one ends and we start the next one?

**Comment by Alys** [comment]
It looks like it kicked you out of the quest. I'm about to give you the three gryphon eggs that @deilann promised you. If you refresh your inventory in five minutes you'll see them there (tell us if you don't). Yesterday I gave you the promised quest scroll so that should be there too.

This is pretty much the best we can do without time-consuming manual database manipulations, so I'm going to close this issue BUT if you're not happy for any reason or if you or your party have any more problems, tell us here and we'll reopen it!

All future quests should behave normally.
