### ISSUE TITLE
Lost equipment glitch

### ISSUE THREAD

**Issue by LeFnob** [HabitRPG/habitica#3950]
Every time I die, I always lose a piece of special equipment, not a piece of regular equipment.  It says I have lost a piece of regular equipment (like a sword), but then when I reload the page, it's revealed that I've lost a limited-edition piece that sometimes cannot be bought back.  Or, most recently, it says I lost the Rainbow Warrior armor, but upon reloading, I lost a Ninja-to instead.

**Comment by wysawyg** [comment]
Are these items not available to re-buy in the Rewards column? They should be!

**Comment by Alys** [comment]
duplicate: https://github.com/HabitRPG/habitrpg/issues/2789

When you die, you lose a random piece of gear. If its always special equipment, that's just a temporary run of bad luck.

There's a known bug (see the dup. link) where the wrong piece of gear is reported as lost.

You can always buy back gear lost on death even if it would not normally be available. If it's gear that belongs to a specific class, you have to be in that class to buy it.

**Comment by LeFnob** [comment]
The issue is that the gear I actually lost is not what it says was lost.  It would say my Hook Sword broke, only to reveal it was actually my Pirate Cutlass.  And this time, the Rainbow Warrior Armor, because it was only available one day, could not be bought back.  However, later that day it re-appeared.

**Comment by Alys** [comment]
Yes, that has been reported before. That's what's it means when on github someone says "duplicate <link>" and then closes the issue - it means the issue being closed is a duplicate of one that's been reported in the past, and the link points to the previous report.

Often, all you'll see is "duplicate <link>" with no further explanation, but I generally try to give more details. In your case, that is what I was referring to when I said "There's a known bug (see the dup[licate] link) where the wrong piece of gear is reported as lost.". If you click on the link from my previous comment, you'll see an issue that's very similar to yours. It reports the same problem you reported, and because it was reported first, it's the one that is being used to track all information related to this issue. Your issue is closed because we don't need two issues reporting the same problem - it's much easier for the developers if there's just a single issue that contains all information related to the bug. If you look at the issue I linked to, you'll see that github automatically edited it to include a link back to your bug report, so the developers can still very easily find your bug report when they need it.

_"because it was only available one day, could not be bought back. However, later that day it re-appeared."_  --- That has nothing to do with the availability of the item. It's just a browser refresh/cache issue. As soon as you lose a piece of equipment due to death, it immediately becomes available for repurchase. However you might need to refresh the page to see it (and as soon as you refresh, you WILL see it). If you don't refresh, then it will appear later when your browser picks up recent information from the server (refreshing forces that to happen immediately).
