### ISSUE TITLE
test

### ISSUE THREAD

**Issue by OlliePage** [HabitRPG/habitica#3962]
.

**Comment by deilann** [comment]
I believe the issue is that it takes a bit for it to "trickle" through all
the users. What has to happen is that your number of purchased gems has to
be set to zero.

Now, it's also possible that this is a caching issue. Logging out and
logging back in, or clearing your cache may fix the issue. Basically, your
browser would be holding onto the old number of gems you had purchased.

**Comment by Alys** [comment]
@Revix, regarding unsubscribing: How much benefit you get from a subscription you have just cancelled depends on when your subscription first started; older subscriptions behave differently than newer ones. Please read the section called "Unsubscription Procedure" in [Subscription](http://habitrpg.wikia.com/wiki/Subscription) for full details.

**Comment by OlliePage** [comment]
@deilann Ok that makes sense. I have cleared my cache from my brower (chrome), tried again, same result. If it is the trickle-down effect, I suppose I must be all the way at the bottom scraping the barrel! 

@Alys I did mention in the OP that I have only had 30 days of subscription (thus a new subscriber, with the new behaviours). I also mentioned in the OP that I had already read the Wiki on the subscription and I made sure to communicate that I understood how the subscribing model worked. Perhaps I should have made that more explicit. Thank you for your suggestion anyway.

**Comment by deilann** [comment]
It's only noon here in California. :) and database order sometimes can
be... very random seeming. If this issue persists more than 12 more hours
let us know.

You said you wanted to change classes, right? What's your UUID?

**Comment by OlliePage** [comment]
My UUID is fb2c26cb-1072-4dad-a57f-d6b2aadc78a7 - I should have mentioned that in the OP! Apologies. (Mage, if you're wondering what class I wanted to switch to :) )

**Comment by Alys** [comment]
"about half a month's worth of membership" - I took that to mean that your current month's subscription had lasted for only half a month, rather than you subscribed for the first time half a month ago. I did see that you said you had read the wiki, but there's a lot of information on the wiki about subscriptions and it's possible that you had not read the section that I specifically pointed out. We do often have cases where important bits of information are missed because they're overshadowed by a lot of other information, so we often try to point out exactly where relevant documentation is just in case the person needing it hasn't found it yet.

When you click on the gem in the header (i.e., NOT in the market, but the gem icon next to your gold) what do you see in the subscription notice? Does it say that your subscription has been cancelled and will expire on zzz date? If so, your subscription is still in effect and the only issue here is that you just need to wait a bit longer for the gem purchases to reset for you,.

**Comment by Alys** [comment]
I have given you three extra gems so that you can change class immediately. I do not have the ability to change your class for you.=
