### ISSUE TITLE
All dailies, todos and habits disappeared

### ISSUE THREAD

**Issue by Ciremme** [HabitRPG/habitica#3964]
Dear mods,

when I created a new tag and dragged it to a different position all my other dailies, habits and todos disappeared. Now I only have the two new dailies left I have created in the new category and they are not even sorted in the new tag. All my tags are empty.

Username: Ciremme
ID: 5d757a68-7975-4547-a4c5-efe421a495ab

Could you please look into this?

**Comment by Alys** [comment]
Click the "clear" button to the left of your tags. Your tasks will reappear.

When creating new tags, it's important to follow the advice given in the wiki's [Tags](http://habitrpg.wikia.com/wiki/Tags) page ("Creating Tags" section) due to the bug that's described there. Reply here if you have any questions about that.

**Comment by Ciremme** [comment]
Thank you :) That was amazingly fast!
