### ISSUE TITLE
add one-time "donate" option that doesn't grant in-game purchase

### ISSUE THREAD

**Issue by m1rrag** [HabitRPG/habitica#3995]
Just as important as a code issue: if I donate to developers, I can just buy all of the things I would have otherwise earned on the site. Because of this, I don't think I'd ever want to donate- it would make rewards feel meaningless. I know it feels like a good idea but don't you think there are ways to get people to donate without jeopardizing the entire point of the game? 

Aside from my personal incentive to be able to use this site meaningfully (it's SO COOL!!), I'm also concerned about that option taking away donations from developers. Easiest solution is to at least add a paypal donation link at the bottom of your page so members can at least have the option of a click donation that DOESN'T compromise the incentives system HabitRPG is built on.

Thanks!

edit: oops I'm very sorry- did not realize there was a suggestions board...
##

**Comment by Alys** [comment]
I know what you mean about not wanting to buy eggs, hatching potions, and food. I am very much enjoying earning them through drops and never buy them with gems.

However I find that there's enough other uses for gems that I'm never tempted to buy the things I can earn. Instead, I buy all the backgrounds and avatar customisation options, and many copies of those quests that can be obtained only with gems. I have a monthly subscription (25 gems) and every so often I have to buy still more gems to be able to get all the gem-only items that I want. But if you're not interested n those items, then it might be too tempting to buy eggs, potions, and food! :)

There is a slightly obscure option for you if you'd like to donate but don't want gems. Buy a  monthly subscription for $5/month and then, if you want to donate only $5, cancel the subscription immediately. You'll be charged for just one payment of $5. The subscription does give you the ability to swap gold for gems, but you can ignore that feature.

You might be interested in these two Trello cards:
https://trello.com/c/fHudKPp2/360-donate-to-contributors
https://trello.com/c/dSYhZK8E/399-gem-packs-bundles

**Comment by m1rrag** [comment]
Thanks! I guess if I were to shorten my post I would say:

developer to-do: add one-time "donate" option that doesn't grant in-game purchase.

**Comment by Alys** [comment]
@AnitaYCheng Since you're looking into redesigning the subscription modal (https://github.com/HabitRPG/habitrpg/issues/4837#issuecomment-97939112) you might want to consider this.

My personal feeling is that while it is VERY nice that @m1rrag wanted to donate and gain nothing in return, I think having an extra payment option could lead to extra confusion for some users. We already have users who buy gems when they mean to subscribe, and vice versa, and two or three times a month I have to mess about in PayPal or Stripe to refund an undesired purchase.

A pure "donation" option could more easily be implemented by having a gem-purchasable item that did nothing at all. So you'd buy gems just as you do now, and then spend gems on this item that gives you no benefit. Related ideas at https://trello.com/c/Rjx3bmZd/363-gifts-v2-tavern-brew-market-gifts-gem-items-to-thank-developers

**Comment by TheHollidayInn** [comment]
Closing because we now have a donation button. Further discussion can be continued on Trello.
