### ISSUE TITLE
AutoSave or QuickSave

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#40]
Can you please add an autosave feature similar to that of Google Products.?

AutoSave would be optimal but if the bandwidth load is too much maybe a Quick Save button next to the user button allowing users to quickly "commit" any changes.

This would be great for users like myself who keep HabitRPG as a pinned tab along with other webapps such as Gmail and GCal. Also reduces the likelihood of adding a lot of tasks and forgetting to log off before closing the tab.

Maybe there is a more D&D/RPG friendly word/icon than save and a disk but here is a quick concept pic.

![Image 3](https://f.cloud.github.com/assets/3202339/47381/8d83d838-58ce-11e2-91fc-8d5c66502ea7.png)

**Comment by lefnire** [comment]
All changes are automatically synced with the server's database using Derby's socket.io + redis realtime capabilities. If it's not syncing, that's a bug. Try a refresh too, if the server goes down between the time you connected and the moment you make a change, your socket.io connection has been broken. I'm working on fixing this, obviously, but temp. workaround. Closing because the real issue lies in some of the other tickets currently in the queue.
