### ISSUE TITLE
Mounts menu is bugged

### ISSUE THREAD

**Issue by PrinceLucian** [HabitRPG/habitica#4008]
My mounts are appearing in all of the wrong places, not just in their own lines, but I have tigers in the bear line, a zombie wolf in with the bears that has no face, the white tiger I made before discovering this doesn't seem to have been made, despite the food and the pet being used up, and I have a Zombie octopus that I definitely shouldn't have and these are just the things that I can remember.  I believe something went terribly awry?

**Comment by Alys** [comment]
Have you tried reloading the page? That's worth doing anytime you see anything looking very odd (on any website, not just HabitRPG). Your browser is probably just displaying the images incorrectly and a reload should fix it.

**Comment by Alys** [comment]
More information here: https://github.com/HabitRPG/habitrpg/issues/3830

I'm closing this because every time I've seen this reported so far, it's been fixed by a reload, or at worse by clearing the browser's cache. However if you're still having trouble, comment here and we'll reopen it and keep on helping you.

**Comment by PrinceLucian** [comment]
I did a refresh and yes, that did handle it, thank you!  That was super weird, though.  It let me equip the zombie octopus and everything.  O.o
