### ISSUE TITLE
Cron ran after checking out of Inn

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4011]
So I checked into the Inn earlier tonight, got more done than I expected, checked out again (I've done this before without issues and I'm not sure whether it's relevant). Midnight hits and all of a sudden my cron runs. My cron has been set at 7 am for months (and when I checked it's still set for 7 am). I haven't touched my cron setting and it doesn't appear to have changed so why did it randomly run at (I assume) midnight? This is potentially deadly during quests!
##

**Comment by Alys** [comment]
@Anysia I'm sorry we never replied to this. It would have been because we had no idea what might have caused it. I'm hoping it was just a once-off glitch. The code has changed quite a lot since then (and there's bigger changes coming up soon from an API rewrite), so if there was something that caused it, it's probably gone now or will be soon. We can reopen this if it happens again.
