### ISSUE TITLE
Can't delete dailies from challenge (checking and sync does not work)

### ISSUE THREAD

**Issue by JMDTRM** [HabitRPG/habitica#4026]
I wanted to get rid of all my challenges so I left all the challenges while choosing to remove the tasks. I did it really quickly and errors were springing up while I was doing that (I didn't get a screenshot, unfortunately). Now, the habits and dailies still exist and can't be deleted. I tried looking around and found that selecting the daily then syncing helps. I tried that but it didn't seem to work.

**Comment by Alys** [comment]
When you perform many actions in HabitRPG very quickly you get [sync errors](http://habitrpg.wikia.com/wiki/Sync_Errors) because your browser can't send the information about your actions to the server fast enough. The errors you were seeing were a sign of that.

To remove those tasks, rejoin the challenges they belong to and then leave the challenges again, choosing the "remove tasks" option. If you wait for the blue sync bar to finish after each action, everything should work well.

If that doesn't work for any reason, comment here and we can reopen this issue.
