### ISSUE TITLE
Equipment quests appear to drop multiple at once (excess ones disappear from inventory on reload)

### ISSUE THREAD

**Issue by ozziog** [HabitRPG/habitica#4030]
Have dropped 3 identical quests from doing dailies, called attack of mundane quest line Part one.

Log into today and only 1 quest of this name is showing.
##

**Comment by lefnire** [comment]
The 3 drop is a bug, it should only drop one  upon reaching a certain level

**Comment by ozziog** [comment]
It dropped in a 2 then 1 ratio. I was in the teen levels when these dropped.
I am now level 20.

**Comment by Alys** [comment]
This was happening to me today on my local install: Two or three quest drop notifications would appear, and two or three quest scrolls would be in the inventory (sometimes one more than the number of notifications) but on reload all the excess ones would disappear. It's definitely a thing that's happening.

**Comment by SabreCat** [comment]
The logic for dispensing quests on levelup is here: https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L1441

I suspect the issue is that this is in `user.fns` and thus is running both on the client and the server. The quest inventory is incremented once on the server, once on the client, thus 2 scrolls. The only one that "sticks" is the server save, however, so once a refresh occurs, it settles in to just 1 scroll.

Can we tell that code block, "only run on the server"?

**Comment by paglias** [comment]
Reopen if it happens again
