### ISSUE TITLE
Dailies stay checked off - show hint above Dailies if user is Resting in the Inn

### ISSUE THREAD

**Issue by nesmeisya** [HabitRPG/habitica#4034]
Dailies stay checked off from the start of my using habitrpg. At first I didn't understand that smth goes wrong, now I know that it's a bug. What to do with it? I want to use dailies.

**Comment by Alys** [comment]
Are you "Resting in the Inn"? To learn about what that means, read the Resting in the Inn section in the wiki's [Tavern](http://habitrpg.wikia.com/wiki/Tavern#Resting_in_the_Inn) page. That page will also tell you how to check out of the Inn (which will make your dailies start working on the **following** day). If your avatar has "Zzzz" next to it and its eyes are closed, then you are Resting in the Inn.

If that fixes your problem, please tell us so that we can close this issue. If it doesn't fix the problem, tell us your Unique User ID which you can get from the [Settings -> API page](https://habitrpg.com/#/options/settings/api).

**Comment by negue** [comment]
@Alys What If we would show a Hint above the Dailies if the User is resting in the INN?

**Comment by Alys** [comment]
That could really help new users. I like it.

**Comment by lemoness** [comment]
I like it too. We may want to start anticipating more frequently asked
questions this way.

**Comment by Alys** [comment]
Oh look. We did this. :)
