### ISSUE TITLE
ToDo order keeps resetting

### ISSUE THREAD

**Issue by patena** [HabitRPG/habitica#4043]
Whenever I reorder my ToDos, whether by dragging or by the new "to top" button, the new order only lasts an hour or two, or until I press the Sync button. Habits and Dailies stay where I put them, it's only ToDos that don't. This has been going on for several weeks. No errors are displayed.

User ID 28493c5d-00bb-4bc0-a471-9c4b40c9e642, Firefox 32.0 on Xubuntu Linux.

**Comment by lemoness** [comment]
This is a known issue that happens when you have too many completed to-dos! 

Here's the solution:

Go to the bottom of your To-Do list, and click "Complete." Click "Delete Completed."

This should solve the problem, especially if you wait for the page to finish loading after dragging and dropping a To-Do.

Let me know if that didn't work! Have a great day.

**Comment by patena** [comment]
@lemoness Oh, right! I used to know about that, but I forgot. That worked, thanks! (Although I'm not sure 8 completed ToDos should really be considered "too many" ;) )
