### ISSUE TITLE
Socket Policy Server for Unity Webplayer

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#4049]
I would like to get a webplayer version of my Unity HabitRPG Client up on my own personal heroku server, that can connect to habitrpg.com.  That way people can test the latest version of the client without having to first download it.  I can also link to it in resume's, and on my website to help me find work.

In order for a webplayer version of unity to connect to habitrpg.com it needs a socket served policy.  I think it works like this: a simple server program serves a crossdomain.xml file when the webplayer asks for it.  It's similar(possibly identical?) to what's needed for flash applications to connect to a domain.

There's more information http://docs.unity3d.com/Manual/SecuritySandbox.html under "Implications for use of Sockets"

If HabitRPG staff is receptive to hosting the policy server, I can make the necessary changes, and test the server and make a pull request.  Otherwise, I will have to set up my own,always-online habitrpg test server for the web player, which I would prefer not to do.

Also, I open sourced my HabitRPG Unity client at https://github.com/fragmental/habitengine as GPL V3.  I haven't publicized it, because I'm not sure that my licensing is 100% correct yet.

**Comment by fragmental** [comment]
@lefnire @paglias ?

**Comment by fragmental** [comment]
Should I assume that silence means habitRPG staff is not responsive to hosting the policy server?  The file is tiny so there should be no drain on resources, and I can make the pull request. I just don't want to go through with creating the pull request if there's no point.  I understand how busy everyone is.  Thank you for your time.

**Comment by paglias** [comment]
@fragmental I'm not against this addition if it's a simple static file to be added. Reading on the page you linked I see "Implications for use of Sockets:" where it talks about sockets, the port it connects to... what does it mean? I mean, what type of requests the player is going to do to the site? Simple api calls or something different?

**Comment by fragmental** [comment]
@paglias from what I understand the client ask

**Comment by fragmental** [comment]
Whoops.  Using phone app.   From what I understand the web player asks for the crossdomain.xml file and the policy server then serves that file, which tells it which ports it should use.  This is to prevent rogue Web players from accessing sites and ports they shouldn't be accessing.   Flash has the same thing.  I can set those ports manually for both the policy server and client to something that is appropriate.

As far as I know,  the only interaction a Web player can have with habitrpg.com is through the REST api.

**Comment by paglias** [comment]
Mmm... The proble I think is that the app is accessible only through ports
80 for http and 443 for https

2014-10-10 15:35 GMT+02:00 Stewart Martin notifications@github.com:

> Whoops. Using phone app. From what I understand the web player asks for
> the crossdomain.xml file and the policy server then serves that file, which
> tells it which ports it should use. This is to prevent rogue Web players
> from accessing sites and ports they shouldn't be accessing. Flash has the
> same thing. I can set those ports manually for both the policy server and
> client to something that is appropriate.
> 
> As far as I know, the only interaction a Web player can have with
> habitrpg.com is through the REST api.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4049#issuecomment-58655981.

## 

Matteo Pagliazzi - paglias.net

**Comment by i8degrees** [comment]
@paglias Hi, I've been helping @fragmental with developing a working prototype of his Unity3D client that can be built as a Web Player app, thus creating the dependency on the socket policy server.

The policy server working along side the client is, essentially, nothing more than a glorified software firewall, intended for the same goal as such -- restricting the flow of information to whitelisted locations -- via a `crossdomain.xml` file. 

The policy server's sole job is to accept incoming connections and send those clients the contents of its `crossdomain.xml` file. The client's responsibility is to obey the access restrictions as set in the file. (Doesn't sound very secure to me? Alas!)

An example `crossdomain.xml` for the policy server might look like:

```
<?xml version="1.0"?>
<cross-domain-policy>
    <allow-access-from domain="*" to-ports="80, 443, 3000" />
</cross-domain-policy>
```

Note that in a live setup, you may wish to consider restricting the access to specific domains...

The policy server sits on the server side -- of which, surprise, surprise is 
habitrpg.com. The client would be @fragmental client app.

The problem is that without the policy server, @fragmental client refuses to connect to the remote address -- habitrpg.com -- for REST API interaction, due to the restrictions set forth from the security sandbox model in Unity3D (requiring a policy server to help determine / authenticate a valid outgoing connection).

I've verified that the node module [policyfile](https://github.com/3rd-Eden/FlashPolicyFileServer) works as intended for us, using a non-default port number of 8433 instead of 843, since Heroku deployed apps do not have root privileges. This app takes care of generating the `crossdomain.xml` file for us as well as sending it along to clients that request it.

I'm afraid that it isn't _quite_ as simple as a static file, but it is close to it! Since this process requires a policy server (i.e.: policyfile module) to be listening along side on its own port number (i.e.: 8433 if you so wish, as long as it is above 1024), it requires me to ask what would be your preferred manner be in integration of this feature?

I do not think that you'd want it in the root server.js (as I have it on a local testing copy), since you'd want to minimize any chance of it interfering with the site. My other two ideas would then be: a) run a script from package.json; b) run a script from a grunt task. I'm leaning towards option B. I'm unaware of any other option we might have here, off the top.

The script to boot the server process looks something like this:

```
var flash_pf = require('policyfile').createServer();

flash_pf.listen(8433, function() {
  console.log('Flash Socket Policy Server is listening on port 8433.');
});
```

I'd be happy to try answering any questions that you may have!

-Jeff

**Comment by paglias** [comment]
Hi @i8degrees 

thanks for the explanation. I think that if serving it as a simple static files isn't possible then we're probably not going to add a different process just to serve this file. I'm sorry.

I don't understand what's the point in requiring it to be served on a different port, from the page linked above from @fragmental it seems that in order to use the WWW class it's enough to serve it on port 80, the default one you use when using the browser (443 for HTTPS).

It only speaks of ports higher than 1024 in the section about sockets where it also states that

> A Unity webplayer needs a socket served policy in order to connect to a particular host. This policy is by default hosted by the target host on port 843 but it can be hosted on other ports as well. The functional difference with a non-default port is that it must be manually fetched with Security.PrefetchSocketPolicy() API call and if it is hosted on a port higher than 1024 the policy can only give access to other ports higher than 1024.

so hosting it on a port higher than 1024 would restrict the access to ports higher than that making it not very useful give that habit is served only on ports 80 and 443

**Comment by i8degrees** [comment]
@paglias I _think_ it is because @fragmental client doesn't use the WWW class, but a lower-level one (HTTP) in order to make the connections, but I'm not at all fluent in Unity3D's environment, so I could be mixing something up here...
**UPDATE:** Confirmed that @fragmental 's client uses the UnityHTTP module / class (a third-party solution, AFAIK), because the official Unity3D WWW class does not support PUT or DELETE operations. This appears to be why _Implications for use of Sockets_ applies to us. Otherwise, I think that serving a static `crossdomain.xml` from a HTTP server would probably work.

Is it Heroku that restricts the inbound ports to 80 and 443?

Looks like it is back to the drawing board for us :D

Thanks

**Comment by paglias** [comment]
Yes, only 443 and 80
Il 13/ott/2014 23:52 "Jeffrey Carpenter" notifications@github.com ha
scritto:

**Comment by i8degrees** [comment]
Doh. Good to know! :]
