### ISSUE TITLE
Challenges remain among Tags even after removed

### ISSUE THREAD

**Issue by rajhathi** [HabitRPG/habitica#4062]
I am still seeing Challenges as a tag option for a new task even after leaving the challenge.

cb2101d5-a8a7-4a2a-babe-4e15b4294cfc

**Comment by Alys** [comment]
duplicate: https://github.com/HabitRPG/habitrpg/issues/1704

This is deliberate rather than a bug. Players are able to use the challenge tag for their own tasks if they wish (e.g., if they add their own To-Dos to assist them in completing the challenge), and they might also choose to leave the challenge tasks in their task lists after they have left the challenge. In either case, it would be inconvenient for them if the challenge tag was deleted. 

In theory, we could adjust the code so that the challenge tag was deleted if there were no remaining tasks using it, but the extra code complexity is probably not worth the small benefit. It would be more prone to bugs, and it would also produce seemingly inconsistent behaviour - users who didn't realise why the challenge tag was/was not being deleted would probably report the inconsistency as a bug.

It's best overall if the challenge tag is never removed automatically. That way each player can choose to keep or delete the tag, always giving them the outcome that works best for them. You can delete the tag by clicking "edit" next to your tags and then clicking the trash can icon on the tag.

**Comment by sidawson** [comment]
Ahh. Thank you for explaining, @Alys.

## why "filter"

re https://github.com/HabitRPG/habitrpg/issues/6191 I incorrectly used "filter" because 
    a) clicking it filters the list of visible tasks, and 
    b) the use of the term Filter in the iOS app.
Unfortunately, I don't have any suggestions for alternative/clearer nomenclature.

## a humble suggestion

Could I humbly suggest: From a UX perspective, the existing behaviour is VERY confusing (hence being listed as a bug, three times - goodness knows how many other people were confused but not technical enough to enter a bug report).
- If I exit the challenge but keep the tasks, having the tag at the top of the page makes perfect sense.
- If I exit AND remove the tasks, that would imply "complete exit" so having something left lying around is counter-intuitive.

It feels like two issues are conflated - 
1. challenges+their tasks, 
2. user being able to filter their tasks by user-defined or "custom" tags.

In this case, the tag name is prescribed by the name of the challenge - but if the person has left the challenge AND added their own tasks, essentially they're re-using the tag as their own personal filtering  (uhh, tag) tool. Allowing this as a work-around of not having custom tags has resulted in the UX confusion for all the people who AREN'T using it as such (ie, the default typical behaviour: "I want to leave this challenge, completely")

## how to test

A quick test whether the existing functionality is being used as intended - Select from the database - How many people have ONLY THEIR OWN tasks in a challenge they are no longer part of (ie, exclude those who've clicked "leave challenge / don't remove tasks."

This will include challenges with no tasks, where the user has a) added their own tasks, and b) clicked "leave challenge, don't remove tasks", but it should give a rough approximation how widely spread this "exit the challenge, remove the tasks, but keep using the tag for my own nefarious ends" behaviour is, across the user base.

## possible alternative

I don't know how complicated this would be to code, but...

IF the user leaves the challenge AND selects "remove all tasks" THEN remove the challenge tags (particularly since the "remove all tasks" currently removes any tasks the user manually added to the challenge anyway - we can guarantee if they select that option, there will be no tasks under that tag).

This then simply automates exactly the same outcome as the user manually clicking Tag Edit > Delete (if they're aware that possibility exists).

[As a side clarification: I am NOT arguing for custom tags. I think that would be a complete nightmare.]

**Comment by Alys** [comment]
@sidawson "the use of the term Filter in the iOS app" -- Ah, I didn't know that. Thank you for mentioning it!

The "remove all tasks" option should remove all tasks that are officially part of the challenge (tasks put in the challenge by the challenge creator), but it should not remove any tasks that the player has created in their own task list (even if they applied the challenge tag to it). I've just tested this successfully (a task I added was **not** removed). If you've found the opposite behaviour and it's reproducible, we definitely want to hear about it!

Players are able to create their own tags. Is this what you're referring to as custom tags? If you click "edit" next to the tag list, there's a field for adding a new tag. You can add as many as you like. Let me know if that's not what you were referring to.

The test you describe unfortunately wouldn't be quick. :) We have many thousands of users, and probably hundreds of thousands of tasks, so the search would be slow and the data set produced large. It's an interesting idea, but even if it indicated that most users didn't have any further use for the tag, there'd probably be some who do, and I'm reluctant to inconvenience them. I realise that keeping the tag does inconvenience the users who don't want it, but the workaround for that is simple and quick, whereas the workaround for the opposite case is a laborious process of finding and retagging tasks.

I think a better approach would be making the tag editing and deleting feature more obvious and perhaps having a notification about deleting tags when you leave a challenge. Or perhaps having an extra option when you leave a challenge to delete the tags too, although that's getting option-heavy.

**Comment by sidawson** [comment]
I tried to reproduce the "user added tasks are removed when leaving a challenge" but was unable. Possibly fixed since I last did this, possibly I mis-remembered it.

I didn't notice the field for adding new/custom tags. Thank you for pointing that out.

A super simple UI (rather than back end) solution might be to have a message pop up telling the user that now they've left the challenge (and removed the tasks) they have to manually click Edit Tag > Trashcan - ie, just explain to everyone who doesn't know (most people, I expect) as you did for me. Bonus points to only do it the first time someone adds a challenge.

**Comment by megbkwyrm** [comment]
I'm having a related problem, I think--I can't get rid of a challenge task ("mail it") for a long ago challenge. There's no trash can button on the task, and the challenge is no longer showing up anywhere. Is this just me being an idiot, or a bug? (User id: 8e140422-dfc5-4173-adaf-c9d1948866ef
)
