### ISSUE TITLE
Daily Streak Bonus bug

### ISSUE THREAD

**Issue by Katzen-Gott** [HabitRPG/habitica#4063]
Hi there.
1) mark daily task done (get task reward and series reward) - this is OK
2) unmark this task (task reward is substracted, but series reward is not) - I thought series reward should be substracted too
3) mark task again (task reward returned to you, and series reward is added) - or at least it shouldn't be added again.
My HabitRPG nick is Katzen Gott (it is said that I should put it here)

**Comment by Alys** [comment]
When unticking a Daily, the streak bonus (series reward) IS removed but it is not reported separately. Here's an example from my Daily, first being ticked:
![screen shot 2014-09-23 at 1 22 44 am](https://cloud.githubusercontent.com/assets/1495809/4358941/3d12fcb8-426e-11e4-9edd-fec7a27b63d6.png)
and then being unticked:
![screen shot 2014-09-23 at 1 22 57 am](https://cloud.githubusercontent.com/assets/1495809/4358946/456baa36-426e-11e4-8d82-11d146a0818f.png)

If you add up the gold and silver amounts being added in the first image, you'll find it's about the same as the amount being removed in the second image (there's a slight rounding error of about 1 silver, but it's inconsequential compared to the total amount (less than half a percent).

The easiest way to confirm this is to look at your total gold and silver before you tick and untick the Daily, and look at them again afterwards. They'll be the same (if you ignore the rounding error of about 1 silver).

For programmers who are curious, this is handled in habitrpg-shared's index.coffee script, in the addPoints function, in which 'delta' is negative when the task is being unticked. The streak bonus notification is controlled by user._tmp.streakBonus, which is deliberately not set when the amount of gold being "added" is less than zero (i.e., when gold is being removed). This is presumably because it was thought that a negative streak "bonus" would look odd. See also https://github.com/HabitRPG/habitrpg/pull/2290

So I suppose the only question is do we want to change the code so that it DOES report the negative streak bonus? I personally don't think it's worth the effort.

**Comment by Katzen-Gott** [comment]
Hi. I was not sure about notifications (missing substracting bonus notification was the first thing I thought of), so I checked total amount of coins. And it increases each time I uncheck-check my daily. So there must be some issue with this.
At the moment uncheck gives -1g60s
check gives +1g58s +4s

**Comment by Alys** [comment]
From those figures, it seems there's just an extra 2 silver from ticking a task compared to unticking it. That's the rounding error I mentioned above in a couple of places. It's about 0.7 percent of the total gold+silver (i.e., insignificant compared to the total amount) and it's caused by the task's statistics being slightly different after ticking or unticking than they were before.

**Comment by crookedneighbor** [comment]
I don't think this is worth tweaking.
