### ISSUE TITLE
Special gear (no benefit conferred) stays after Rebirth

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#4070]
There is a bug when using the Orb of Rebirth: if used while having the "Roguish Eyepatch" and the "Shining Capelet" equipped (both Summer Splash Special Gear), the character stays equipped with these. Even though the reset to starting character worked as it should, the avatar is still wearing both the eyepatch and the capelet. This happened to my husband, and he finds it quite vexing, as they get into the way, visually, of other equipment.

It seems that you can get rid of this kind of left-over equipment if you buy it again and then you can un-equip it (that was the case for me), but that would mean two class changes...

**Comment by deilann** [comment]
You can get rid of it with any other item slot of the same kind, not just
the item itself. :)

**Comment by Alys** [comment]
That bug should have been fixed in this PR: https://github.com/HabitRPG/habitrpg-shared/pull/307

@wildcate Can you tell me please about when he used the Orb of Rebirth?

**Comment by wildcate** [comment]
About a month ago - so before the PR you referenced. And there are currently no eyepatches or similar slot items available...

**Comment by Alys** [comment]
The eyepatch is actually a head accessory, so if he has any head accessories at all, he can replace the eyepatch with that. But if he doesn't have any, and he'd like to have the items removed from his avatar by us, we can do that if he can tell us his "User ID" (Settings -> API) and give us a list of the items to be de-equipped.

Since he experienced the Rebirth bug before that pull request, I'm going to close this issue, but it can be reopened if he ever Rebirths again and experiences the same bug (I think it really is gone for good though).

If he'd like us to de-equip gear, he/you can comment on this issue, even after it's closed. I'll be emailed with any replies you make so I can make sure his gear is fixed up.

**Comment by wildcate** [comment]
Hi Alys,

here is the User ID: 
a7886d4b-e617-4bd4-8698-c2c5f6224b26

Please de-equip the eyepatch and the shining capelet - thank you!
(BTW, putting on headgear such as the Scalp of Science, or a helmet, did not de-equip the eyepatch...)

**Comment by lemoness** [comment]
Yes, unfortunately that wouldn't, because they are helmets, not head
accessories. Working on this now!

**Comment by lemoness** [comment]
It should be fixed now. Refresh and let me know if that worked!

**Comment by wildcate** [comment]
It's fixed - thank you for your help! Now the lab coat and Monster Scalp of Science look much cooler  :)
