### ISSUE TITLE
Died 3+ Times for no Apparent Reason

### ISSUE THREAD

**Issue by PickySalamander** [HabitRPG/habitica#4076]
User ID: c7f08b0a-a0c7-4ca9-ad71-d7424e5d2d90
Group ID: c00f8fb8-7715-4733-ba9b-15d5e3e2fa79
Browser: Chrome 37.0.2062.120 m
OS: Windows 8 and Android Mobile App

Over the last 3 days I have died at least 3 times for no apparent reason. After refreshing the page, refreshing the recent messages, and syncing, my party log says I have taken at most 40 damage over the course of those days. Since I'm pretty much dying every day and getting full health that isn't nearly enough damage to deal the necessary damage to kill me each subsequent morning.

Today I logged on in the morning before all my party members and refreshed, synced, etc and had 50 health. Around mid-day I logged in and was dead (a death message didn't appear if that means anything), after checking the party log I only received 12 damage. 

I'm a little confused as to why I keep dying and what if anything I'm doing wrong. The last few nights I've had most if not all my dallies done as well.
##

**Comment by lemoness** [comment]
Hm. Have you clicked the sync button in the party chat? Frequently more
damage has been dealt, but you have to click that to display it. Keep in
mind that if you have red Dailies left undone, they will do a lot of damage
to you in addition to the amount of damage that the boss deals to you.

It's also worth noting that our servers have been under a lot of strain
recently, so perhaps not all of your tasks were syncing. You can verify
this by using the Official Data Display Tool:
https://oldgods.net/habitrpg/habitrpg_user_data_display.html Would you be
willing to use that tonight and monitor whether your tasks are being
checked off? If this turns out to be syncing errors, you can restore your
lost stats using Settings > Site > Fix Character Values.

We'll figure this out, never fear!

**Comment by deilann** [comment]
It's also worth noting that you take normal damage from your dailies on top
of quest damage, so it sounds like that should explain the missing damage.

**Comment by PickySalamander** [comment]
Everything seems fine today, but yesterday according to the data display I had completed all my dailies and still died. I'm going to fix the character values for now, and let you both know if it happens again. If it means anything I will often login on three different devices (my home computer, work computer, and android phone), so maybe something went wrong there?

Either way thank you both for the help and the prompt response, means a lot. Keep up the good work!

**Comment by lemoness** [comment]
Interesting - the Data Display Tool said you were going to take zero damage
from your own Dailies? I assume you're still in a Boss Battle. When you
sync the party chat, how much damage does it say you were dealt?

**Comment by PickySalamander** [comment]
I was only supposed to take only 12 damage. I haven't noticed this happening again, but I've been careful to keep my party synced and not to log in too often from different devices.
