### ISSUE TITLE
Stats page doesn't explain that effects of level are capped at level 100 (e.g., Perfect Day bonus maxes out)

### ISSUE THREAD

**Issue by nbeckstead** [HabitRPG/habitica#4084]
On the stats and achievements page, it says, 

"X Perfect Days
Completed all active Dailies on 134 days. With this achievement you get a +level/2 buff to all attributes for the next day."

My character is level 118. If this were correct, my buff to all attributes should be 59, but in fact it is only 50. I think the buff from the perfect day has been set to max out at level 100, contrary to the text.

UUID: 66440307-9628-4eca-b448-ba008e82a3b3
Browser: Chrome
OS: Windows 7

**Comment by Alys** [comment]
Everything related to levels is meant to max out at level 100, so the problem here is that the text is misleading.

FYI, level 100 is considered the maximum for effects related to stats because for a long time level 100 was the highest level you could reach, and the game was balanced with that in mind. More recently, the level cap was removed, but to prevent the game becoming unbalanced for very high level players, the level was still "capped" when calculating various stats.

I think there might be some stats that haven't yet had the level cap applied to them but we'll get that fixed up in time. When we do (or even before then) we should probably add a single message to the stats page that states that levels greater than 100 don't have any additional effects on buffs, etc.
