### ISSUE TITLE
Recently-released equipment/gear/costume not visible in app Rewards or Inventory or on Avatar

### ISSUE THREAD

**Issue by AaronFW** [HabitRPG/habitica#4086]
In the App, Autumn 2014 items are not visible in the market. I bought the "Grabby Claw" on the web, but the App neither shows it in my inventory or on my person. It does not affect the stats either.

UID: 459a284e-5f17-4559-84e5-03f8876352e5

**Comment by lemoness** [comment]
### So, when new art is added to the website, it always takes a while to show up on the phone - I believe it will be available after the next version is pushed.

Devs, definitely confirm or correct me.

That being said, since these items are part of the Fall Festival, it might be worthwhile to release a new update that is just "Fall Festival Costumes and Candy!" so that our mobile-only users can enjoy it as well.

@lefnire @huarui @negue @paglias

**Comment by paglias** [comment]
Yes, we should release a new version to get the new items. Something for
@lefnire when he comes back

2014-09-26 19:14 GMT+02:00 lemoness notifications@github.com:

> So, when new art is added to the website, it always takes a while to show
> up on the phone - I believe it will be available after the next version is
> pushed? Devs, definitely confirm or correct me.
> 
> That being said, since these items are part of the Fall Festival, it might
> be worthwhile to release a new update that is just "Fall Festival Costumes
> and Candy!" so that our mobile-only users can enjoy it as well.
> 
> @lefnire https://github.com/lefnire @huarui https://github.com/huarui
> @negue https://github.com/negue @paglias https://github.com/paglias
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4086#issuecomment-56991143.

## 

Matteo Pagliazzi - paglias.net

**Comment by amichaeln** [comment]
This is now an issue with the Winter gear as well. Bought the Gumdrop Sword but receiving no buff on it while on the mobile version. Makes me not want to use the mobile version, because my character will perform better on the web version (unless the actual character stats is on the server, in which case please let me know).

UID: cdef4bf0-269f-4429-9d3d-dc88e24d01d9  on behalf of  1ca90ee9-0d06-4068-ad16-93de74fead21

**Comment by Alys** [comment]
Actual character stats IS calculated on the server (even if messages you see in the app say otherwise). You're losing nothing by using the app. It's purely cosmetic.

**Comment by Alys** [comment]
I'm closing this because we've implemented a system that allows new gear to appear on the new Habitica apps very rapidly (the Android Habitica app is not released yet but is being actively worked on).
