### ISSUE TITLE
Tag Issues

### ISSUE THREAD

**Issue by theblanch** [HabitRPG/habitica#4087]
Hi there,

I can't seem to find a solution to this problem so I figured I would see if it is a bug or if you guys could help me out. I'm trying to use the tags to better organize my tasks - obviously. However, when I go to edit my task(s), and click the tag box to place that task into a specific tag, the box will not check. It makes a minor animation, but no check mark. Of course, I checked the tag as well, and it does not place. In fact, none of my tasks will place into ANY tags. Finally, I can't seem to delete tags. I click delete, they disappear, then I click save. A few minutes passes, I refresh, or I sync my account, and the tags will re-appear. 

There is one exception to all this. If I make a brand new task, and place it under a tag, it will work. However, if I do not do this immediately after creating that task, it cannot be placed under a tag. 

You can see how this may be frustrating. I absolutely love HabitRPG, so, I hope this issue can be resolved in the future. The tagging system would be a great feature to be able to use.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/4066

One of the comments starts with "TEMPORARY WORKAROUND" and contains your workaround and one other.

Since this issue is a duplicate, I'm closing it, but you can follow progress of the issue at https://github.com/HabitRPG/habitrpg/issues/4066
