### ISSUE TITLE
Reset account. Tasks are removed but the challenges still remain

### ISSUE THREAD

**Issue by Algogator** [HabitRPG/habitica#4090]
1. Join a challenge(s)
2. Reset account

Expected: Previously joined challeneges should have been removed
Actual results: Challenges accepted before the reset are still in list https://habitrpg.com/#/options/groups/challenges
![screenshot from 2014-09-28 07 09 56](https://cloud.githubusercontent.com/assets/1433469/4432863/62d869b0-46b0-11e4-8ea2-8ce2c42cb469.png)

edit: Completed quests aren't reset as well
##

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg-shared/pull/323

**Comment by waldofe** [comment]
There's someone working on it? I would love to give it a go. @Alys, I was reading your comment on the old repo issue and it looks like there's some doubt about which challenges should be removed from the user. I think that would be good to:
- Remove the challenges that I do not manage.
- Improve messages on "Reset" modal.

I still didn't setup the project yet, but what about the statements above?

/cc @TheCodeGator

**Comment by Alys** [comment]
I think if we're going to remove challenge tasks, we should remove all of them, even the ones that the player manages. They can always rejoin their own challenges later. The consistency will make the feature easier to explain in the help text, wiki, etc.

In the old pull request, I wrote this, which is utter nonsense: _"We also need to consider what happens when the user is the creator of a challenge. After a reset, they must still be able to administer the challenge. In that case, it's probably best to not remove them from the challenge at all."_  A challenge creator can still manage a challenge without being a participant, so just ignore that comment. Sorry about the confusion. :)

Similarly, challenge tags should be removed regardless of whether the player is the challenge creator or not.

However before proceeding, we should make sure that we do actually want to remove challenge tasks when a player clicks the "reset" button, even when the player has made significant progress in the challenge. @lemoness - is this okay to do?

**Comment by waldofe** [comment]
Thanks for the answer @Alys. On my point of view, it makes no sense to keep those challenges, I mean, it's an account reset after all. But let's see.. :+1:

**Comment by paglias** [comment]
Fixed in v3
