### ISSUE TITLE
Ability to hide some/all pets+mounts (e.g., spiders/arachnids) in HabitRPG website and mobile app [$5]

### ISSUE THREAD

**Issue by evanelric** [HabitRPG/habitica#4091]
Due to some concerns with phobias I was hoping someone could create some sort of workaround to hide other people's pets and mounts. I have a, shall we say, more than healthy fear of spiders, and with the Frost Spider pet quest due out next month HabitRPG could rapidly become a place that isn't really safe for me to traipse around freely, which would be a huge bummer. I know Merfy's can turn Habit into a boring/worksafe site devoid of images, but all I really want gone are the pets (and only some of them, at that).

_Ideally_ it would be something to toggle each individual kind of pet/mount (for example, hiding only snakes, or spiders and octopuses, etc, while leaving everything else visible), and replacing them with some sort of generic (possibly hatching potion color coordinated) cloud.

I realize that that will probably be pretty challenging and time-consuming and require collaboration from a coder and an artist for the pixel portion, but even just a stylesheet to hide all pets/mounts would be helpful at this point.

Please and thank you to anyone who can help!
##

**Comment by deilann** [comment]
Actually with a user installed script this would not be too difficult.

**Comment by evanelric** [comment]
A script will be a good stopgap, and greatly appreciated, but it would still only work on desktop versions of Habit, meaning the app and mobile browser versions would be unaffected (and thus potentially still full of triggers). That's why I'm suggesting this as an overall change to Habit for the future rather than just leaving it at the custom script level.

**Comment by deilann** [comment]
Changes to the habit site would have to be done separately from the app
anyway. I totally get this issue, but I'm concerned about whether or not we
have the code hours to create this as a setting for both site and app. I
can, however, tell you that the app won't have any spiders on it unless you
specifically get the spider pets. The scroll will be the same as the others
and the pet will be hidden unless you hatch it.

**Comment by lemoness** [comment]
To quickly clarify - on the app, you can't see any pets but your own, not
even your party mates' pets. So desktop is the primary concern for now!

**Comment by deilann** [comment]
And you can't see boss art.

**Comment by paglias** [comment]
Boss art will be in the Social -> Party section of the mobile app as soon as the new version we've been working on is released

**Comment by deilann** [comment]
Oh dear. In that case, that will be an issue.

**Comment by evanelric** [comment]
You also can't interact with your party except via chat in the Habit app, so if I want to cast a spell or accept or force start a quest from my mobile device I have to use my mobile browser, which doesn't support user scripts.

**Comment by paglias** [comment]
@evanelric I think the easiest thing would be a setting hiding all the images on the site and app

**Comment by evanelric** [comment]
@paglias Merfy's script has a worksafe mode that already does this, but I was hoping for a creature-by-creature toggle (eventually, not immediately or in the next weeks or even the next few months). The thing that keeps me using Habit is my completionist gotta-catch-em-all mentality toward the pets and mounts, so I won't be able to use the site at all if I have to just disable images outright because my motivation will literally be gone. :(

**Comment by deilann** [comment]
You'd be able to do that via a userscript and then use the setting for
mobile, where you have fewer options. We can't really do an image-by-image
disable setting without it getting rather intricate. Basically, we want to
keep the site accessible for you and others with phobias, but the amount of
code it would take to create a setting like that is more than a bunch of
volunteers can scrap together with so much else on the table.

**Comment by Alys** [comment]
@evanelric An extension like Merfy's should be able to hide specific pets and mounts because each pet/mount has its own class, such as "Mount_Head_Parrot-Golden". An extension could set display:none on a list of classes.

**Comment by Alys** [comment]
Ideally, we'd have a browser extension or similar for both Chrome and Firefox. Other browsers wouldn't hurt either. Internet Explorer is probably not so important because HabitRPG already does not have good support for it due to its many bugs (we simply don't have enough programmers to write code to work around all of IE's "quirks").

## Classes that need to be hidden

The class used to display the spider in the quest box is `quest_spider`.

These classes are used to display spider pets and mounts in avatars:

`Pet-Spider-Golden`
`Mount_Head_Spider-Golden`
`Mount_Body_Spider-Golden`

The word "Golden" can be any of these:
- Base
- White
- Desert
- Red
- Shade
- Skeleton
- Zombie
- CottonCandyPink
- CottonCandyBlue
- Golden

**Comment by Alys** [comment]
I've added a small bounty to this and changed the title to specify it's for a Chrome extension. The reason is that we might have different people creating extensions for different browsers (which would be great) but unfortunately the bounty can go to only one person (I think) and I believe Chrome is the most popular browser these days. It's also the browser with the best support for HabitRPG.

Note that a suitable extension for any browser will be rewarded with a contributor tier (once evaluation and testing is completed successfully).

(Sorry about the title change spam.)

**Comment by tjwds** [comment]
[Done and tested.](https://github.com/tjwds/habitrpg-arachnophobia) @Alys

**Comment by Alys** [comment]
From janey_p in the Tavern (something to consider for enhancements to extensions):

**But the extension sounds like a great idea, especially if it gets the "any pet toggle", because I'm sure there'll be more pets in the future that might trigger people. Which reminds me: There's the rat king already. The pets and mounts are rather cute, but the boss itself is another matter. I know some people who'd get nightmares from that, but would probably be fine with the pets. So a boss toggle might be a good idea, as well. :)**

**Comment by tjwds** [comment]
Alright, I'll add the ability to turn on/off various divs in the next update, and probably combine the two extensions as well.

**Comment by Alys** [comment]
@tjwds Well that was fast work! It definitely hides pets and mounts in my avatar and others. Would you be able to add the quest image class as well? `quest_spider` I added that to my earlier list of classes, but probably not till after you first read that comment.

**Comment by tjwds** [comment]
@alys While I'm doing that, do you have the rat king's class as well? Adding divs will take another few seconds, the individual toggles will take a little bit though (and I should be doing other work right now haha)

**Comment by evanelric** [comment]
Thanks so much!! Is there a way this could get built into the app at some point as well?

**Comment by Alys** [comment]
@tjwds `quest_rat` for the quest box image.

If you were wanting to add rat pets and mounts, it's the same classes as for spiders but with "Rat" instead of "Spider". We are impressively consistent with these things. :)

**Comment by Alys** [comment]
@evanelric : See [the comments above](https://github.com/HabitRPG/habitrpg/issues/4091#issuecomment-57220054) about that.

**Comment by tjwds** [comment]
@evanelric The short answer is at some point; I'm fairly confident with my javascript + jquery ability, but am still teaching myself just about everything else that habitrpg is built off of.  I'm working on it… just very slowly, haha. 

@Alys all rats have now been killed.

**Comment by evanelric** [comment]
@Alys yeah, but as @paglias [mentioned above](https://github.com/HabitRPG/habitrpg/issues/4091#issuecomment-57221366), the boss art is now the first thing you see when you go to the Social->Party section, so even if no one equips the pets/mounts the boss art will still display for the entire duration of the quest :\

**Comment by Alys** [comment]
@tjwds : Brutal but effective! Tier++.
Note that the higher tiers require more effort than the lower ones, so if you make any small changes from now on, you might find that they don't grant you extra tiers (although they still will be appreciated). There's a bit of information about that at [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards) but ask if you have questions.

I've just now realised the fatal flaw in my cunning BountySource plan! I have to close this issue for @tjwds to claim the bounty, even though there's requests in it that haven't been actioned yet. _[Note to self: Think things through.]_ We can reopen it after the bounty is claimed, or start new issues.

**Comment by tjwds** [comment]
Is there a way to roll over the bounty or just donate it to HabitRPG? 

Thanks for the contributor tier!

**Comment by evanelric** [comment]
@Alys I think it would be fine to open new issues, as long as they were linked to from the end of this and had a link back to this for context? But obvs I'm not a mod, so :\

@tjwds Thank you so much!!

**Comment by Alys** [comment]
@tjwds : Awwww. :)  I'll try reopening this and turning it into a bounty for HabitRPG website/mobile changes. (Although note that as described above, it's not necessarily a simple issue.)

EDIT: Yup, that seems to have worked. Bounty is still available.

**Comment by lemoness** [comment]
Do you guys have any quick instructions for how to enable and use this?
Maybe we could put it on the wiki?

**Comment by Alys** [comment]
@lemoness See the instructions [here](https://github.com/tjwds/habitrpg-arachnophobia) and also on the [Boss Button Extension](http://habitrpg.wikia.com/wiki/Boss_Button_Extension) page which has the same installation process. We'll be creating a wiki page like that one for this new tool.

**Comment by lemoness** [comment]
Great, thank you!

**Comment by tjwds** [comment]
Could someone tag this with the bounties tag so that I can come back to it easier later?  Haha

**Comment by tjwds** [comment]
:+1: Thanks!

**Comment by paglias** [comment]
We can match any CSS class that contains spider in CSS with
[class*="Spider"]
Il 18/ott/2014 00:43 "Alice Harris" notifications@github.com ha scritto:

**Comment by evanelric** [comment]
Chrome has disabled this extension because it's not on the store and there's no way to reenable it. Can we get a fix for that, please?

**Comment by Alys** [comment]
@evanelric There's some fixes here: [Re-enable extensions not coming from Chrome Web Store on Chrome v35+ (with enhanced security) - Super User](https://superuser.com/questions/767286/re-enable-extensions-not-coming-from-chrome-web-store-on-chrome-v35-with-enhan) or if any of those aren't suitable, you might find others here: [Chrome disabled extension because not on store - Google Search](https://www.google.com.au/search?q=Chrome+has+disabled+this+extension+because+it%27s+not+on+the+store&oq=Chrome+has+disabled+this+extension+because+it%27s+not+on+the+store&aqs=chrome..69i57.370j0j1&sourceid=chrome&es_sm=91&ie=UTF-8&qscrl=1#safe=off&qscrl=1&q=Chrome+disabled+extension+because+not+on+store)

**Comment by paglias** [comment]
Should this bounty be claimed directly by HabitRPG as asked here https://github.com/HabitRPG/habitrpg/issues/4091#issuecomment-59591552 ? @lemoness

**Comment by tjwds** [comment]
I'm no longer actively maintaining this extension & haven't been keeping up with the Habitica architecture--I'd encourage the functionality being rolled into the site (if it isn't already) or be more than willing to pass the project on to someone else.

**Comment by Alys** [comment]
I'm closing this because it's a feature request that doesn't fit into Habitica's direction at the moment. However it could be requested on Trello if desired (Help > Request a Feature from the habitica.com website's menu). @evanelric  With this being closed, the money in bounty source should be returned to you automatically but please contact bountysource if there are any problems with that. 

There is a third-party extension available that does this: http://habitica.wikia.com/wiki/Phobia_Protection_Extension
It's created by me and I'm willing to add more creatures to it when requested.
