### ISSUE TITLE
Record history for rewards. (was: Party challenge csv export does not show reward progress)

### ISSUE THREAD

**Issue by jenrit** [HabitRPG/habitica#4092]
When exporting a csv file for a party challenge, I am unable to see how many times a specific reward was claimed. I created a challenge with one habit and one reward, then claimed them both several times. The six columns added to the export were:

habit:Habit Name | Values | Notes | reward:Reward One | Value | Notes

I'm not sure what the value column for the habit is supposed to represent, as it's not a whole number, but it does increment every time it's clicked. But the value for the reward is a static "10" (the cost of the reward) even when I claim it multiple times. 

Also, if you add a new reward to the challenge, its columns in the export are inserted before the three columns  (name/values/notes) of the original reward. However, the data itself remains stationary, so the "10" mentioned above is now under the Values column for Reward Two
##

**Comment by Alys** [comment]
We can't change the value on rewards in the way that it's done for habits, but it would be technically possible to record history (one history entry for each click on a reward, with purging happening for older clicks, as is done for habits). We'd need to consider whether the extra database space and purging processing during cron would cause a problem.

This would be a reasonably popular change because it would allow us to provide a way for all users to see when/how often they've clicked on rewards (not just for challenge rewards), which players ask for every so often.

**Comment by lemoness** [comment]
Is this still an issue?

**Comment by Alys** [comment]
It's more of a feature request than an issue as such. It would involve adding a counter to Rewards (ideally both Challenge Rewards and normal user Rewards, as is done for Habits), and then adjusting the Challenge export CSV to contain that data. We wouldn't necessarily have to display the Rewards counter on the Tasks page, but I believe it would be popular if we did ("how many chocolates did I eat this week?"). It would be analogous to the Habit counters, and could optionally have the same feature for having the counter reset every day/week/month. I believe a lot of the Habit code could be reused for this. I'd like to see it done but it's low priority.

**Comment by jenrit** [comment]
It's not an issue.

Thanks,
Jen

**Comment by lemoness** [comment]
Since this is a feature request, I'm closing this ticket, but we'll keep the idea in mind during future development!
