### ISSUE TITLE
Pickpocket's Tooltip Phrasing is Terrible

### ISSUE THREAD

**Issue by Equilibrist** [HabitRPG/habitica#4095]
Instead of "You gain an increased gold bonus on the task, higher yet the 'fatter' (bluer) your task," it should say something more akin to "You gain additional gold from a task- the bluer the task, the more gold you steal!"

**Comment by Alys** [comment]
I'm pretty sure the original is grammatically correct, so I'm changing the title from "... grammar is terrible" to "phrasing is terrible". "Phrasing" can include grammar, so it covers this issue even if I'm wrong about the grammar. (I'm also not sure that it's bad enough to be considered terrible, but that's merely a personal viewpoint.)

I think keeping the word "bonus" (or similar) is important to make it clear that the skill does not add extra gold to the amount that you get when you tick off the task but instead gives a completely separate, unrelated amount of gold. We have enough users who are already confused about how the skill works, so that distinction needs to be made.

I also like the word "fatter" because it implies that you're pickpocketing a fat merchant - it adds a bit of flavour to the game. Since it's defined immediately as meaning "bluer" I don't think it's harmful. Disagreements are welcome.

How about this: **"You gain an additional gold bonus from a task. The 'fatter' (bluer) your task, the more gold you steal!"**

**Comment by Equilibrist** [comment]
Bonus doesn't imply a seperate amount, it implies an extra amount stacked on top of a known original amount. Either way, the wording is much better, though I would only use "bonus" if you mean that it's an additional amount on top of what you normally get.

**Comment by me-and** [comment]
I have to concur with @Equilibrist on the word "bonus"; this is something that confused me when I first started playing a rogue – based on that text, I expected Pickpocket to increase my gains when I next completed the task I used it on.

Possibly word it as "You gain an immediate gold bonus from a task. The 'fatter' …"?

**Comment by Alys** [comment]
New phrasing: "Your nimble fingers run through the task's pockets and find some treasures for youself. You gain an immediate gold bonus from a task. The 'fatter' (bluer) your task, the more gold you steal!",
