### ISSUE TITLE
Can't check tags within a task or delete them

### ISSUE THREAD

**Issue by EmperorNortonI** [HabitRPG/habitica#4099]
I recently added a new tag and, unaware of #2856 , tried to use it right away. Since then, I haven't been able to check the new tag or any of the old tags in the edit screen for a task. When I found out about #2856 , I tried to delete that tag, but after syncing or reloading it kept showing up. I renamed that one "Broken Tag" and tried making a new one correctly (syncing before using), but I still can't get any of the tags to check. Any solutions?

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg/issues/2856 has been closed and shouldn't be relevant any more. That bug has been fixed and you can ignore that issue.

However we have two new problems with tags that are probably affecting you. Both will be fixed soon.
1. [Cannot permanently delete tags (or get a sort of them to stick) - Issue #4072](https://github.com/HabitRPG/habitrpg/issues/4072). For this one, there is a workaround that allows you to delete tags (read the comments to find one with the heading "WORKAROUND"), but you might prefer to just wait for the issue to be fixed.
2. [Cannot edit tags on existing tasks - Issue #4066](https://github.com/HabitRPG/habitrpg/issues/4066). There is a comment with the heading "WORKAROUND" and it's important that you read that. I recommend following that advice until this problem is fixed.

I'm sorry about the inconvenience. We've had some significant server problems recently that are affecting tags. The server is undergoing upgrades which should fix the problems.

**Comment by EmperorNortonI** [comment]
Thanks for the quick response. Sorry I didn't see those solutions on my own - I searched on the Habit RPG wikia, not here. I'll close this one, as it's redundant.
