### ISSUE TITLE
Dailies appear to be stuck in grey mode from yesterday

### ISSUE THREAD

**Issue by Aevalle** [HabitRPG/habitica#4106]
Just set up my account yesterday. Logged in today to find that my checked dailies from yesterday have not turned over. Shouldn't I be seeing all yellow (or other colors) instead of grey since the reset time was in the wee hours of the am?

**Comment by Alys** [comment]
Before we can investigate this, we will need to know your user id - see the [instructions here](https://github.com/HabitRPG/habitrpg/issues/2760) for how to find it.

**Comment by thomkrillis** [comment]
Hey, figured I would jump in on this.

Today is the second time this has happened to me. I use Custom Day Start, though, and know this is a known issue. I've also never rested in the inn. I suppose I'll follow the instructions on the wiki on how to reset the values after unchecking everything. It might be worth noting I just levelled up and am at 0exp, so I don't know how that will work out.

User ID: d23e0538-e41b-48e5-aa38-c525607b5ab2

Image is the console output after hard-refreshing the task page on Chrome 37, Windows 7.
![habitrpg_errors](https://cloud.githubusercontent.com/assets/2342694/4519509/21b8adfe-4cbf-11e4-901c-9ee407c16c81.PNG)

**Comment by Alys** [comment]
Hi @thomkrillis. Thanks for the information! Unfortunately those console warning messages aren't related to the problem, so we're no closer to working out why this happens. :( I'm sorry for the inconvenience, especially since you'd just levelled up! I hope that didn't cause trouble in your account. If it did, reply here and we'll see what we can do to fix it. The issue you describe is actually being tracked at https://github.com/HabitRPG/habitrpg/issues/1057, so you can follow that thread if you want updates. Unfortunately it's like to take a while before we can find and fix this bug.

@Aevalle : You might be either experiencing the same issue as in https://github.com/HabitRPG/habitrpg/issues/1057 or you were Checked into the Inn. Without your User ID, I was unable to check. If you're still having trouble with your Dailies, look at the "Resting in the Inn" section in the [Tavern](http://habitrpg.wikia.com/wiki/Tavern) wiki page to see if that's relevant to you.

**Comment by thomkrillis** [comment]
@Alys I was able to uncheck the dailies and adjust the character values and streak counts. Oddly, the experience went negative but kept my level, health, etc. so I just had to put the experience value back at 0. Figured I would post that here in case in the future this happens to anyone else who is nervous about what happens when the experience drops below zero. Thanks for the help!
