### ISSUE TITLE
Reminder for Unallocated Attribute Points?

### ISSUE THREAD

**Issue by betaveros** [HabitRPG/habitica#4109]
Sometimes I get distracted after leveling up and forget to allocate my attribute points. I think it's reasonably widespread RPG practice to have a persistent reminder for players if they have unallocated attribute points. In HabitRPG, I'm imagining perhaps the "User" button on the menu and the "Stats" item in its popup menu changing color.

I wanted to try implementing this myself, but I considered there might be concerns that people whose playstyles don't include attribute points might be confused or distracted or something, so I decided to open an issue first. Thoughts?

**Comment by Alys** [comment]
Interesting idea! I can definitely see a use for some kind of reminder, because I used to forget about them all the time, until I wrote a shell script that gets run every morning to check and remind me. :)

I'm not too sure about modifying the menu buttons though. I suspect we'd get a lot of repeated questions about "why is the button a funny colour?" :) But I'm certainly not completely against the idea. There might be other uses in future for changing the colour of the menus (Pets if there's food to be used; Tavern if there's messages mentioning you; Party if there's a quest invitation). I think you're wise to be cautious about confusion and distraction, and it would definitely be worth getting opinions from others. @lemoness @benmanley  (Lemoness, is it worth mentioning this on the UI board? Would this clash with site design principles?)

Have you considered sending a notification to the Notifications menu? That would certainly reduce confusion. However if you get a lot of notifications from many guilds, it might not be as obvious when there's a point waiting. Although... The notifications menu icon does change sometimes (e.g., for Mystery Items). If we could make it change for attribute points, then those notifications would be more obvious.

There'd be occasions when you'd want to hide the notifications from the user. Any user below level 10 is incapable of assigning points, so they shouldn't be notified. Likewise anyone who has opted out of the class system. Maybe also people who have more than 15(?) points waiting, because there's a good chance that they have decided not to bother assigning them -- although that situation would occur if someone opted out of the class system for many levels and then opted back in, in which case they would want to be reminded about points, so perhaps a manual option to hide the notifications would be best (but then too many options in a website leads to confusion).

BTW, if you use the [User Data Display](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) tool, it will notify you when you have points waiting (a new tile appears in the dashboard). This is in no way meant to stop you adding a notification to HabitRPG itself; it's just a workaround that people can use until you've added the notification. :)  Now that you've mentioned this, I do like the idea of a notification in HabitRPG itself!

**Comment by betaveros** [comment]
I think putting it in notifications is a pretty good idea. I've begun implementing it but just realized that it probably calls for a new i18n string, something like "You have {n} unallocated attribute points!" What's the procedure for handling that?

**Comment by Alys** [comment]
The i18n strings are in the files at https://github.com/HabitRPG/habitrpg-shared/tree/develop/locales/en. To see how variables are handled, examine the "feedPet" string in https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/pets.json

Don't try to edit the files in the other locales/\* directories (see their _README\* files for why).

**Comment by betaveros** [comment]
Oh, I just add an English i18n version, and the other versions will magically take care of themselves later? Cool.

**Comment by paglias** [comment]
@betaveros yes, translations for other languages are updated manually from transifex and in case they are missing they fallback to english strings

**Comment by lemoness** [comment]
I agree that changing the button colors is something that could be useful in the future, but for now, notifications would be the most clear. There was some talk about implementing a counter on the notification bar as well, which would make this more clear, too - I know I always have Guild messages, so mine is always full. As for changing the icon.... maybe an exclamation point if it is a gameplay notification instead of a chat notification? Even then, we'd get some questions. Definitely a good thing to mention on the UI board.

**Comment by betaveros** [comment]
Oh, I made a PR already: https://github.com/HabitRPG/habitrpg/pull/4112
I thought it would automatically link the way issues do, but apparently not.
And I actually chose `glyphicon-plus-sign` because it looked like the plus button used to allocate points, but I'm open to suggestions.

**Comment by lemoness** [comment]
The plus sign makes sense! Seems good to me.
