### ISSUE TITLE
META HabitRPG

### ISSUE THREAD

**Issue by killroy42** [HabitRPG/habitica#411]
I've noticede that I had several META items in my HabitRPG. After the comment on the kickstarter post I'd like to share my thoughts.
I currently have to META dailies: "Do item from ToDo list" and "Update ToDo list". I found these incredibly useful and motivating. There has been talk of staleness, and it's the number one reason my other motivational tools failed. Items go stale. Once you have enough stale items the tools is useless. Making a ToDo item slowly redder isn't gonna fix it. If the item is stale enough it's no longer usefull and MUST be removed.

Now, perhaps forced expiry and item deletion won't work for everybody. How about turning old ToDo items into quests. Complete with RPG-style wording. "Will you accept the quest of CLEANING UP THE STORAGE ROOM for 10 gold, or risk your life and health on it within the  passage of two days?". The dialog should make it clear that if the quest is refused, the ToDo item gets deleted. Stale items are useless and slow you down.

My "Update ToDo list" daily helps me to clean old ToDo items, add nwe ones, and often change the "do everything" items that will never be into a realistic "Do, plan or think about the first step".

Also, clever auto-phrasing into RPG lingo could really help to guilt-trip you into "saving the villagers" by "doing the dishes" for the Dragon Lords.

**Comment by caycefischer** [comment]
I think a time-expiry mechanism of some sort is a really good idea. 

In the same vein, some kind of "expiry" on Daily Tasks. For example, I have a "30m analog reading" as a daily task. I haven't performed that task in about 2 weeks, because I'm a bad human being. If a Daily Task hasn't been performed in a long time, it should be removed from the Daily Tasks list, because it clearly isn't working. So, maybe turning that Daily Task into a Todo/Quest would re-vitalize it and make me more likely to do it.

... Because right now, I'm too stubborn to delete it and too lazy to perform it.

**Comment by StanLindsey** [comment]
I'm somebody who doesn't like the automation element of it only because I don't like stuff not being where I put it =P I'll put it in another column or delete it if I feel I unable to ever complete the task but I wouldn't want the system judging and changing my setup.

Thats just my 2cents, rest is all good! =D

**Comment by wc8** [comment]
Perhaps the Todo Quest could simply be expanded as an Option for Daily Tasks.
_An optional_ Expiration Date for items was mentioned under related suggestions on [Urgency Dates & Deadlines](https://trello.com/c/i6kXvNY2) in Trello.

Maybe Daily tasks, Todos that have an Expiration Date assigned could become an Expiration Quest as they draw near to the expiration date?

**Comment by wc8** [comment]
Vote: [Expiration Dates](https://trello.com/c/4XK5cqEg) also, comment there or here if I've missed anything.
The game phrasing suggestion I added to [Quests](https://trello.com/c/VPPjVRlF) as it could apply to any kind of quest or challenge.

@killroy42 does that capture your idea close enough?
