### ISSUE TITLE
iPhone app not syncing with website

### ISSUE THREAD

**Issue by CarrKicksDoor** [HabitRPG/habitica#4116]
I've been using my iPhone app to check off items when I'm away from my computer, but none of them have been syncing to the actual account, and I returned to my computer this morning to find that I'd died, losing all my gold, some 100-day streaks, and still had tons of things on my to-do lists that I'd checked off already on my phone.  I've got an iPhone 5s, if that helps any.

**Comment by lemoness** [comment]
We're so sorry about that! Were you manually syncing it by holding the page and pulling down until it refreshes? One way to verify if something is syncing is to use data.habitrpg.com, which will tell you how many Dailies the server thinks have been left unchecked.

**Comment by lefnire** [comment]
@CarrKicksDoor [UUID](http://habitrpg.wikia.com/wiki/API_Options)?

**Comment by CarrKicksDoor** [comment]
Lemoness, yes, I was.  Lefnire: f69585c8-a450-41cd-89b4-31152d9e03c1

**Comment by ktastical** [comment]
I'm also running into this issue but with the site not synching to the app. I check off my dailies in the evening via the site, wake up, open the app on my phone and refresh to start a new day. Anything unchecked on the phone dings me. Happened last week Friday/Saturday and again this morning.

UUID: 8b75d6d3-d58d-45f4-84da-a4a21c8d04f5
Mac OS X 10.9.5
Chrome 38.0.2125.77 beta
iPhone5, iOS 7.1.2

Thanks!

**Comment by lefnire** [comment]
@CarrKicksDoor bummer, checked your account for the common cause of this issue in some accounts, but you're clean. Y'all making sure to swipe down on your task list at the beginning of the day? The app doesn't auto-sync, it only syncs (a) if you've opened it after it's been fully closed (apps are kept open in the background on mobile devices sometimes for days); (b) if you perform an action (swipe, tick a task, edit something, whatever). Do note, if it's pulling down updates / syncing (@ktastical), it will inform you in notifications of the _difference_ between your current device's stats and the latest updates. In other words, say you open your app, tick of some tasks, open the website, tick off some tasks, open the app, refresh - it'll say you gained experience. Seemingly from just refreshing, but it's actually showing you the exp you've gained on the website since you last visited the mobile app. (does that all make sense?) Anyway, just trying a few common misconceptions in case that's what's going on here (rather than a bug)

**Comment by helloimtina** [comment]
Hi, 
I've had this problem as well when I would check off items whilst I was offline and then manually sync afterwards when I was online.
If you've done this as well, I'm pretty sure it's because the app isn't offline-compatible.

**Comment by iunn-sh** [comment]
Tasks syncing is trouble-free. Items syncing is having issue.
iOS 8.1.2

**Comment by Alys** [comment]
@jbytw Can you tell us what kinds of items you're referring to when you say that item syncing is having issues?

**Comment by iunn-sh** [comment]
It is somewhat fixed now! Thanks.

**Comment by Luthien22** [comment]
I just started using HabitRPG 12 days ago and haven't had any issues with the app until today. Today it hasn't been syncing tasks or checked off to-dos. Not really sure what's going on.

**Comment by CharlesCheval** [comment]
This morning I created my account on the iOS application, and took some time on the wiki and on the app to learn the basics. I then filled in some Habits, Dailies, To-Dos and Rewards. I intend to use this game for my life and work, so I expect it to be reliable. In order to check that, I went on the website (this time on my computer) and logged in. Well, as I unfortunately expected, it didn't sync properly with my phone (only part of the Habits I entered were here). The rest of the categories pretty much reseted to the tutorial level (some of which were doubled). I thought I could sync manually with the API token, but didn't manage to do it. Last, but certainly not least, when I re-oppened the app it had synced with the website. All my changes were gone, with the stats too...
I really love the concept, and would like to be able to use it without the fear of losing all my datas... I will use the app most of the time, and sometimes the website.
My first question is : Can I get those lost data back? If yes, how? and if not, is there a way to manually secure the future ones?

I use an iPhone 5S under iOS 8.1.3 and a iMac with Safari 8.0.3
my User ID is : c321109c-adf0-4617-a249-0d480bd1be71

Thanks.

**Comment by paglias** [comment]
Have you used the app offline or with an intermittent internet
connecion? Unfortunately we're awaiting for Apple to approve an update
that should fix some of these syncing problems. We understand it's
very frustrating on your side but we don't know why it's taking so
much.

2015-02-06 19:36 GMT+01:00, Salvish notifications@github.com:

> This morning I created my account on the iOS application, and took some time
> on the wiki and on the app to learn the basics. I then filled in some
> Habits, Dailies, To-Dos and Rewards. I intend to use this game for my life
> and work, so I expect it to be reliable. In order to check that, I went on
> the website (this time on my computer) and logged in. Well, as I
> unfortunately expected, it didn't sync properly with my phone (only part of
> the Habits I entered were here). The rest of the categories pretty much
> reseted to the tutorial level (some of which were doubled). I thought I
> could sync manually with the API token, but didn't manage to do it. Last,
> but certainly not least, when I re-oppened the app it had synced with the
> website. All my changes were gone, with the stats too...
> I really love the concept, and would like to be able to use it without the
> fear of losing all my datas... I will use the app most of the time, and
> sometimes the website.
> My first question is : Can I get those lost data back? If yes, how? and if
> not, is there a way to manually secure the future ones?
> 
> I use an iPhone 5S under iOS 8.1.3 and a iMac with Safari 8.0.3
> my User ID is : c321109c-adf0-4617-a249-0d480bd1be71
> 
> Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/4116#issuecomment-73288843

## 

Matteo Pagliazzi - paglias.net

**Comment by CharlesCheval** [comment]
I'm impressed by your reactivity. Thank you for that.
No, my internet connexion today was stable and continuous. I understand very well the issues you are having with Apple protocoles, but, to go back to my question, is there a way to restore what I have lost?

**Comment by paglias** [comment]
@Salvish we have daily backups but I'm not sure your changes got in one of them if you first used the app this morning. Anyway I think @Alys can give a look inside them for you.

**Comment by lemoness** [comment]
If the changes were completely reversed when they used the app again, it
may be an issue with a duplicate account - there shouldn't be an issue with
the website syncing to the mobile app, right?

**Comment by paglias** [comment]
@lemoness i checked and with his email address there is only one registered account. @Salvish to be sure, you didn't signup with email on the phone and maybe with facebook on the site?

**Comment by CharlesCheval** [comment]
No, simply entered my ID and password on the website.

**Comment by Alys** [comment]
@Salvish, for me to look inside database backups for your data, I'll need to know the date and time that you started entering the data, and the date and time that you first noticed the data missing, with both times as accurate as you can remember. I'll then be able to look at our list of backups, and if there is one that falls between the two times, I might be able to retrieve some data from it. It won't be immediate though; it takes two to three hours to download a backup and another one to two hours to import it locally, so I wouldn't be able to give you any information until several hours from now.

**Comment by CharlesCheval** [comment]
Alright, latency is not a problem. 
I first used the application this morning, around 11am (GMT +1). I used it all day. My connexion to the website was around 20 minutes before the first message I sent you (around 7:36pm).
I hope you will be able to restore the loss. Thank you!

**Comment by Alys** [comment]
@Salvish There was a database backup made about one hour after you started using the application but nothing more recent (backups are every 12 hours). Are there likely to be enough tasks in it for you to want the data from that backup? Note that this assumes the tasks were saved to the server at the time that you entered them, which might not be the case so I cannot guarantee finding any tasks.

**Comment by CharlesCheval** [comment]
@Alys Well it's worth trying, I as already lost everything!

**Comment by Alys** [comment]
@Salvish Okay, I'll do what I can, but it will be a while. The download and import process will take a long time. Also, I'm sorry, but the download part of it sucks up a lot of my bandwidth, so it's possible that I'll have to pause it if I or my housemate need a good internet connection for paying work, and the import process makes my local database unusable so I won't be able to start that until I have finished other HabitRPG tasks that require a working local install. The minimum time until I can (hopefully but not certainly) give you some of your tasks is six hours from now, but it might be as much as 12 hours.

**Comment by CharlesCheval** [comment]
Okay that does seem very heavy. Wish I could do it myself. If you didn't started the process, don't bother, I'll refill the data manually. My only concern is for the future, I wanted to know if there was a "solid" way to back up datas, and from what you guys said, there is. Losing a day or two isn't dramatic, though my level of frustration was very high when it happened (I guess dealing with angry customers must be the downside for you guys, after creating such a great concept. Greater the investment -> Greater the loss -> Greater the anger), but a whole year might be a little more of an issue. In my case, I guess I should re-start by entering the main datas through the website, and then use the app. Seems more healthy, until the iOS update breaks through.
Thank you all for your concern, it gives me confidence to use the game again. Have a good night.

**Comment by Alys** [comment]
Thank you @Salvish! That does make my day easier so I really appreciate it. :heart: From this point on, we can be much more certain that your data is being stored in the database and therefore will be retrievable (to be honest, I had little hope of finding many tasks in today's backup since you joined so soon before it was created). We definitely will go through the process of extracting information from a backup if a bug causes large data loss.

If you're interested in exporting your own data, have a look at [Data Export](http://habitrpg.wikia.com/wiki/Data_Export) on the wiki, and you might also like the Data Display Tool, available from the HabitRPG website's Data menu - it has things like "Stats and Streaks Backup" which can be useful if you want to recover from small issues such as internet connectivity failures that prevent you being able to tick off all your Dailies.

**Comment by Smashley027** [comment]
Hello! I seem to be running into the same issue with the iphone app and the website. I've sadly lost an entire level when I switched from using the app to the website :( Sorry if I've missed the solution or if I'm duplicating, I wasn't 100% sure if there was one from reading the forum. Sorry!

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. You can install it at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if you have any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
