### ISSUE TITLE
I can only log in with my old username

### ISSUE THREAD

**Issue by Cassolotl** [HabitRPG/habitica#4117]
Hello!

My current username is Cassolotl, and my old username is Lottiotta.

Today I downloaded the HabitRPG app for android and couldn't log in using Cassolotl and my password. It said my password was incorrect and I should ask to be sent a new one. I did, and it still said my password was incorrect. I tried logging out and back in in Chrome and that didn't work either.

It turns out that even though my username is now Cassolotl, I can only log in using my old username of Lottiotta.

Is anyone else having this issue?

**Comment by Alys** [comment]
There two different kinds of names in HabitRPG: your username and your display name. When you first create an account, you choose your username. That is what you log in with.

At the same time, your display name is set to be the same as your username. Your profile name is what appears in messages you post in the Tavern, guilds, party chat, and on your avatar. After you create an account, you can change your display name. However this does not change your username. Your username is always the name you first chose when you created your account.

You can continue to log in with your original username. You can also log in with your email address if you prefer. You might find that more convenient now.

I'm going to close this issue, since the behaviour you describe is what is supposed to happen. However, you are most welcome to comment here if you have questions or concerns, and I or other support staff will answer you. I'll also arrange for this information to be placed on the wiki, since it's certain not intuitive! I'm sorry you were confused by it.

If you really do need your original username to be changed, our database admin might be able to do that, but he is very busy at the moment dealing with server problems, so it could take several days or maybe even a few weeks.

**Comment by Cassolotl** [comment]
Ahh, that makes sense! I understand. Thank you for taking the time to explain, and for arranging to have it in the wiki too. :)
