### ISSUE TITLE
Party Quest Issues

### ISSUE THREAD

**Issue by Nemesai** [HabitRPG/habitica#4119]
My friend and I started a quest (The Spirit of Spring), and even though both of us are in the party together it seems that he is the only one attacking. Both of us are taking damage, and we've confirmed that both of us are quest participants (I'm the owner, he joined), but he's the only one causing damage still.

This also happened with our last quest (The Dilatory Derby), but we only noticed when we won because he got the loot and I did not. We figured that maybe I joined the party but didn't join the quest so it would've been our fault, BUT now I'm thinking that may not be the case. If there's a way to correct that as well, that would be great.

User ID: c1d3710e-acf5-45bf-86b4-bb6a61d87603

**Comment by MagBag** [comment]
I just opened an issue for something that sounds like the same problem.

**Comment by Alys** [comment]
@Nemesai, this happens occasionally and usually is only a temporary problem. It has been reported before at https://github.com/HabitRPG/habitrpg/issues/2613. You can subscribe to notifications for that issue if you want to follow the progress.

I believe this problem should not prevent a quest participant from receiving quest rewards because the code that applies damage to the quest each day is separate from the code that closes quests and assigns rewards. We haven't seen any reports of rewards not being assigned. However it's worth looking into that for your party. @Nemesai, for The Dilatory Derby quest, can you please look back through party chat to see if the damage messages for that quest are still there? Are there damage messages for both participants, or just one?

**Comment by lemoness** [comment]
Reopening until we get the information about the quest rewards.

**Comment by Nemesai** [comment]
I checked #2613, and the issue there is that the boss isn't receiving damage at all. Just in case, I read through the whole thing, but it doesn't relate to my issues because the bosses I'm referencing are being damaged by my party member but not me.

As far as The Dilatory Derby quest goes, the damage also ONLY comes from my party member even though both of us were participating in the quest. It does show damage from him, but just not me. I think the main issue is that I am not able to participate in a quest beyond actually joining it (no damage, no rewards).

**Comment by Nemesai** [comment]
I just checked the log again and it's actually showing up now for this new quest (awesome!), so the issue still exists but just for The Dilatory Derby.

**Comment by Alys** [comment]
For the Dilatory Derby quest, if all the messages in party chat are from your party mate and none from you, and if you didn't receive the rewards, then it's looking like you weren't part of the quest. It is possible to be in a party but not be in the quest that the party is running.

Thanks for letting us know that your damage is showing up now! Usually when a player doesn't damage the boss, it's just a once-off problem and it does fix itself the next day. It can also look like the boss wasn't damaged if the message hasn't appeared in party chat yet - clicking the sync button that's next to the "send chat" button will add all new messages to the page.
