### ISSUE TITLE
Notification saying "String 'haveUnallocated' not found."

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#4128]
Hi,

This happened to me this morning : I have a different icon for "Notifications", and when I look it up, there seems to be a problem with allocation of something ;)

http://hpics.li/32874e8 [see image below]

Best regards
Aiseant

![screen shot 2014-10-09 at 5 45 25 pm](https://cloud.githubusercontent.com/assets/1495809/4572612/64caf0f4-4f88-11e4-9ece-2ea2d0cd92d1.png)

**Comment by Alys** [comment]
## EXPLANATION FOR THIS BUG

It means that you have unallocated attribute points. If you want to allocate them, you can go to [User -> Stats](https://habitrpg.com/#/options/profile/stats). To learn more about allocating attribute points, see [Character Attributes](http://habitrpg.wikia.com/wiki/Character_Attributes) on the wiki.

The fix for this bug has been created but it might take a day or two for it to appear on the website.

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg-shared/pull/328 has been merged. When it's pushed to the live site, this bug will stop.

**Comment by Alys** [comment]
I'm keeping this open until the fix has been pushed to the site to help reduce duplicate reports and to assist with user support.

EDIT: It's live now.
