### ISSUE TITLE
Mod Tools Desired

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4133]
Figured we should open a ticket to start discussing some Moderator Tools that would make our lives easier.

Some things that would be helpful to me:
-  Ability to edit/delete Challenges
- Possibly, ability to edit messages instead of just deleting them (maybe to put trigger warnings at the beginning, etc). 
- Profanity filters. I know that there has been some debate about profanity filters, but it gets pretty tedious to filter out messages in the Tavern manually - and many of them are innocent mistakes. Even a popup with our stock message and a swapped in suggestion word (Curses! Pain in the neck! Dratitude!) would go a long way. Of course we'd occasionally get people going out of their way to circumnavigate it, but they're probably trolling anyway, so it would still minimize the hassle we have.
- Similarly, we should have something in place to prevent users from choosing usernames that contain language that isn't acceptable in the public chat rooms. I just received an angry email from someone who chose an inappropriate username unwittingly and when asked to correct it, got very upset.  She had a good point, which is that if it is inappropriate, she shouldn't have been allowed to choose it. (She also had some... less helpful.... suggestions about what we should go do, but I'm choosing to extract the constructive part of the feedback.)

I'm sure there are plenty of other useful tools - these are just some that I've been wanting a lot recently. Other mods should definitely chime in with what they want!

@Alys @deilann @DanielTheBard @veeeeeee @lefnire @SabreCat @paglias 
##

**Comment by veeeeeee** [comment]
Commenting just so I'm subscribed (on phone atm). More substantive comments forthcoming.

**Comment by Dewines** [comment]
I'm not a mod but I followed the link from the discussion in the Back Corner guild to add a comment. I think that a profanity filter is a good idea in principle, but working in education I have had problems in the past with over-jealous filters. It's probably easy enough to avoid [the Scunthorpe problem](http://en.wikipedia.org/wiki/Scunthorpe_problem), but the [Offa's Dyke](http://www.nationaltrail.co.uk/offas-dyke-path) problem is more subtle because whether the word is used offensively or not depends wholly on context. For example, over here in the UK, [faggots](http://www.waitrose.com/shop/ProductView-10317-10001-95404-Mr+Brain%27s+2+pork+faggots) are tasty meat products. Any auto-euphemising or requests to change wording for perfectly innocent words could easily result in angry complaints.

**Comment by breadstrings** [comment]
Copying my comment to here from Trello: 

I'd like the ability to filter and sort contribs by title. As the list of contribs get longer, it becomes more unweildy to handle if I want to see a Tier 1 contrib scribe without loading their data since I'm always scared I'd click the wrong button and it goes through accidentally. 

On that note, a confirm details button would be good too.

Also: not a mod tool, but a limit on the length of usernames. I've noticed a particular user who's display name is almost a sentence long, which makes it hard to distinguish where the @ tag ends and the content begins.

**Comment by Alys** [comment]
@breadstrings : Do you mean you want a safe way to look at one particular user's details? You can use your browser's "find" function (Ctrl-F usually works) to search on the Hall page for their name or their UUID and then click on their name to see their profile. If I correctly understand what you want, then I think this would be just as convenient to use as a custom-built filter, and would require no building. :)

**Comment by breadstrings** [comment]
@Alys - Good point.

But the I'd still like the confirm details button. :) Too often, scrolling accidentally gives a user negative gems or increases their level higher than it should and if I'm not careful, I'd miss it. A double-check area (can be optional for those more brave than me) would make it less risky to use.

**Comment by veeeeeee** [comment]
I'd really like to see functionality for what we've been doing via spreadsheets--tracking users who are good forces and who might be troublemakers. 

Also an easier way for mods to fill in standard responses, again so that we don't have to open a separate page.

**Comment by librarianmage** [comment]
Are these still desired? From what I remember, at least some of these features have been implemented (Profanity filter)

**Comment by lemoness** [comment]
We definitely still want the username filters, as well as Profanity Filters for Guilds, but it may make sense to split these into individual tickets. Thoughts?

**Comment by LunarGem** [comment]
@lemoness I don't know if it's any of my business, but generally in my projects if two similar problems don't have the same code solution, I put them in different issues to be closed with different pull requests for organizational purposes. In a large community like this one, that could also serve to allow the problems to be worked on separately and concurrently by different people.

**Comment by lemoness** [comment]
That's how we've been doing it in more recent years, as well. I'm closing
it now, but can reopen if needed.
