### ISSUE TITLE
Feature request: Instant private quest creation for parties

### ISSUE THREAD

**Issue by repomaa** [HabitRPG/habitica#4137]
Hi,

i'm missing the following feature: Being able to create own quest scrolls that can be completed with your party with rewards, that can only be obtained by completing the quest together.

Example: The family is coming over and the house needs to be cleaned and what not. If everybody involved participates and works towards the common goal of completing each task before reaching a deadline a reward such as going to the movies or something will be awarded to all party members so that they can share the reward.

**Comment by Alys** [comment]
@jreinert You can do something very similar to what you describe using a party [Challenge](http://habitrpg.wikia.com/wiki/Challenges). You can set up all the tasks that need to be done, and then all party members can join the challenge and get their own copies of the tasks. You might want to put individual people's names on each task so that there isn't any duplication of effort. When all tasks have been done, you can, if you want to, edit the challenge to add a reward and that reward will then show up in everyone's reward column.

Once it's all over, people can leave the challenge and choose to delete the challenge's tasks to keep their own task lists clean.

Creating quest scrolls actually involves quite a bit of effort. There needs to be artwork, writing of text, coding to set up the final rewards, and the "strength" and "health" of the quest. They're not simple things to craft. 

If you find that the challenges don't work well for your party, you might like to go to our Trello board to make a suggestion for a different kind of party quest/challenge. You can get to it from the website's Help menu ("Request a Feature").

**Comment by Alys** [comment]
@jreinert If the party challenge idea didn't work out for you, you can make your quest feature suggestion on this trello board: https://trello.com/c/odmhIqyW/440-read-first-table-of-contents
