### ISSUE TITLE
develop branch

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#414]
I just added a develop branch. Everyone's been doing a wonderful job staying on feature branches (unlike myself, jeez). When you do PRs, request them against the develop branch instead of master - I'm going to start merging stable `develop` snapshots into master, and likely use tagged deploys

@toebu @SlappyBag @zakkain and any others it may concern (I'm not so concerned on art, that won't step on code toes)

**Comment by lefnire** [comment]
Also note addition to the [running locally](https://github.com/lefnire/habitrpg/wiki/Running-Locally) instructions:

`git submodule init && git submodule update` - gonna be moving client vendor dependencies piece-by-piece into git submodules, so we can update them easily

**Comment by tmas** [comment]
I'm not sure how this would work out with the amount of strain that's on the server given the amount of popularity this project has, but running another instance of habit with the developer branch would be a nice way to preview how all of the latest features come together. I could see something like this being really interesting because it would allow people to easily piggyback off of each others' ideas. If you implemented this, it could potentially get updated automatically from github every few hours or each time you accept a PR.

**Comment by toebu** [comment]
Got it.
For a staging/testing/dev server: didn't you have one running over here: http://habitrpg.herokuapp.com? Do you update it manually? Might be worth looking into some automated deployment pulling from git.

**Comment by lefnire** [comment]
Yeah, we should most certainly setup a continuous integration system with
auto deploys of develop to the test server. Ideally, taking it down after a
certain time so people don't get too cozy there (or we could just do
.htaccess password-protect)

**Comment by switz** [comment]
This only works well if we have a solid test suite. I don't think we should worry about it yet.

**Comment by horusofoz** [comment]
@lefnire Is this ticket still required?

**Comment by lefnire** [comment]
nope!
