### ISSUE TITLE
Broken mana bar

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#4148]
My mana bar is completely blue, but it says I only have 1 mana, and I cannot cast any spell.

![broken](http://i.imgur.com/bxxppVj.png)

**Comment by negue** [comment]
Wow... 

also your levels, expierence points and gold is broken too?

But yes I think the ratio of (1 / 162656042 = 6,147942540001066e-9 ) is just too small for be viewed.
Maybe logic error (to calculate the background part).

Haven't looked at the code yet, but if think we should add a "minimum" of 1%.

**Comment by AdrienLemaire** [comment]
fixed after completed a task that gave me another 10 million levels, mana full ... probably a bug due to the insane numbers. We just have too much buffs at project mayhem ^^'

+1 for the 1% minimum, makes sense :)

**Comment by lemoness** [comment]
Q - has your party been casting a ton of buffs? In particular, Valorous
Presence?

**Comment by AdrienLemaire** [comment]
Yes...

**Comment by lemoness** [comment]
Okay - so buffs, in particular VP, can lead to massively unbalanced stats.
You must have had a critical hit that rocketed your level (and that of your
party mates) sky high.

Shall I leave this open to become the "let's rebalance Valorous Presence"
ticket?

**Comment by AdrienLemaire** [comment]
Would be great @lemoness :) Thanks

**Comment by Habitfan** [comment]
This is Seneca. I know you guys have a ton on your plate and I am in no way wanting to be negative but this is something that needs to be fixed for the long-term interest of the game. Fortunately the people that are playing around with this right now completely have your backs. I know the gaming community and if something is available in gameplay people are going to utilize it even though it may seem like an exploit.

**Comment by Habitfan** [comment]
I'm not trying to spam the thread. But, I will point this out to you. I think it's in Habits best interest to have long-term plan mind for players continuing past level 100....... including how buffs are utilized. I think the key to the success of Habit long-term is to get a bunch of people that are committed for the long haul and subscribe to the site providing a solid revenue stream for several years. Rather than have a bunch of people that come and go on free accounts or just hang around subscribing for a few months. 

I think looking at players that are committed to the long haul is in everyone's best interest. Breadstrings has indicated to me some of the discussion in the contributors Guild and that there's reluctance by some to provide goodies and spending resources for people over level 100. I honestly believe that is a huge mistake. 

I offer to provide some time and resources sharing my perspective on the issue if it's wanted. I just want to indicate that I really want Habit to succeed over the long haul and him only trying to help. I love this community and from a selfish perspective this is a valuable tool for me, and I would like to see it be a long-term productivity solution for many people.

Seneca

**Comment by breadstrings** [comment]
Also upon using orb of rebirth whilst mana buffs are still in place, doesn't reset mana buffs, so upon clicking the next task, you jump up massive levels and can't get out of the cycle unless everyone vows to stop using mana for the entirety of each party member's cron.

Before:
![screen shot 2014-10-16 at 8 54 00 pm](https://cloud.githubusercontent.com/assets/5908271/4661424/72f48212-5523-11e4-9fdb-5093a019242d.png)

After clicking one blue daily:
![screen shot 2014-10-16 at 8 54 22 pm](https://cloud.githubusercontent.com/assets/5908271/4661427/7ccaa636-5523-11e4-8f47-c27a96d51a70.png)

**Comment by deilann** [comment]
She won't need any gems. The orb is free after level 100. It also doesn't
cost 3 gems regardless

**Comment by breadstrings** [comment]
New experiment. Everyone in the party is starting from level 1 with no residual mana buffs at all. We'll see how long it takes with max mana (once unlocked) to get up to this level again.

**Comment by breadstrings** [comment]
@Fandekasp - I'm also a GM, so it's also won't be a problem.
@deilann - However, I did return Seneca's 16 gems that he lost from an orb of rebirth bug that occurred twice yesterday.

**Comment by Alys** [comment]
@breadstrings What was the bug?

**Comment by breadstrings** [comment]
@Alys - I believe the experiment might have been a key problem. But I could be wrong. Seneca should be on shortly to detail what happened since I don't really know.

**Comment by Habitfan** [comment]
I don't want to make a big deal about this. But, I did rebirth after our day of megabuffs and I was at like level a Brazilian. Probably least about level 330 million. We were so buffed that every time I tried to log an additional task I would get the error message. After I tried this a couple of dozen times and refreshing my browser it was pretty obvious that the server could not handle our level of buffs that our insanity group had applied with my current strength level. I thought the next best thing would be to do rebirth. I did go to the market bought the orb of rebirth and eight gems were taken from my account. I checked off one daily and then was up to a massive level over a couple million. Right after that I tried rebirth and again 8 gems were taken from my account. I got my rebirths, but they definitely were not free. So I went from 20 gems down to four. I've done rebirth a couple of times today, and my four gems remain. I'm not trying to make a big deal about this. I will probably just buy some more gems my concern is that if someone has gems in their account it will be subtracted even if they're all above level 100 when rebirth past level 100 is not supposed to cost eight gems.

 Seneca

**Comment by Alys** [comment]
Okay, so the problem was basically that your buffs weren't cleared when you used the  Orb. With insanely large buffs, if you want normal behaviour after rebirth, use the Orb just before bedtime and then don't do anything on the site until your cron has run (although I expect we'll fix the bug of buffs not being cleared by rebirth).

As for the Orb not being free after level 100, it definitely is. In your case, I'm guessing that the sudden level increase hadn't properly registered on the site. If it happens again, try reloading the page and/or ticking of a task to see if that makes the level increase "take" properly.

**Comment by Habitfan** [comment]
Thanks for the response Alice. The rebirths worked. I lost billions in gold, all my equipment and went back to level one.   It worked. The issue was that I was above level 100 for weeks and probably a couple months and still was charged eight gems for rebirth. From the bug issue I'm more worried about the first rebirth then the second because that should've worked normally because of the length of time that I was over level 100 and not been charged the gems.

**Comment by Alys** [comment]
@Habitfan I'm having trouble following the sequence of events. How many rebirths did you try? From what you and your party members have written here, I have the impression it was three. After the first one, you found your buffs were still in place and caused a sudden increase back above level 100, and so you tried two more rebirths, neither of which were free. Is that correct? If so, the latter two non-free rebirths are probably covered by my previous comment. Was the very first rebirth you tried free?

**Comment by Habitfan** [comment]
I will be very precise as I know that this is probably important for you to understand. I did my first rebirth several months ago. I probably was the first on Habit to actually hit level 100. Tyler, Redphoniex and Breadstrings were in the same party as me at the time. I'm guessing that was probably around February 2014.

My second rebirth was done yesterday. I hit level 100 the for second time probably around June or July 2014. So I've been above level 100 for quite a while, and this was long before any of the mega buffs. So if you're correct that rebirth should not have caused eight gems to be removed from my account. But they were.

I then scored a massive amount of damage with checking off one of my dailies yesterday. I checked off another and kept receiving error messages on the site and was again at a ridiculously high level for checking off only two dailies. At that time I kept refreshing my browser and even quitting and relaunching but would only receive error messages every time I tried to check off a daily. I again tried the orb. It worked but again 8 gems were removed from my account.  So 2 rebirths over level 100 for both yesterday cost me 16 gems. I understand what your concern is that the massive buffing may have not caused the server to calibrate the second rebirth journey especially with the error messages. The problem is the gems being removed from the account particularly on the first rebirth. My concern is that if someone has over eight gems it will automatically be removed from the account when repurchasing the orb after being at level 100.

**Comment by Alys** [comment]
Okay, that's very clear, thanks! We haven't had any other reports of rebirth above level 99 not being free, and several tests I've done locally with the latest site code show that gems are not subtracted, even when I have more than 8 gems, so I don't think this is a widespread problem. If you would like it to be kept on record, please log a separate issue for it, since this is now divergent from the mana bar display issue. :)

**Comment by Habitfan** [comment]
Alice,

Thank you so much for your attention to this issue. Also if you are the person that returned the Gems I also appreciate that as well. You are an incredible asset to the Habit community. I have deep respect for what you've done for the site. In addition you are an amazing human being that I have grown deep respect.

Seneca

**Comment by Habitfan** [comment]
I think it actually might be Ryan that returned the gems. whoever it was I wanted to say thank you!

Seneca

**Comment by breadstrings** [comment]
Lol, that was me, @Seneca. ;) and you're welcome.

**Comment by Habitfan** [comment]
Well thank you @breadstrings!!!!!! Have I ever mentioned that you are wonderful because you are!

**Comment by breadstrings** [comment]
As leslie mentioned keeping this thread for VP needing to be altered, can we rename the thread please?

Also, as an update, after level 75 there was enough mana for 5-6 buffs in a row for VP, boosting other party members to do the same. It's now Day 7 or 8 of the experiment and almost all of us are over 100levels (only 4 party members in group this time)

Edit 11/4/14: We officially started the experiment 16 days ago. HabitRPG is now crashing with every task I tick and I'm currently at level 980241. My party has confirmed that a party of newbies (all members starting from level 1) can indeed cause trouble in less than one month by use of valorous presence. Even with two halves of the party being from different timezones such that the VP is only effective from two members at a time.

**Comment by breadstrings** [comment]
What if we had a "cancel buff" option for those who don't want to be a part of party buffs? It can be selective, like: "cancel heal", "cancel strength", etc? That might resolve the issue of parties with different playing styles, especially if your party is for your family and you all play HabitRPG differently.

Also with VP, I was thinking of making it exponentially cost more mana the higher you go, to limit how often it can be cast. Perhaps make it 40-50 mana given it's strength.

**Comment by Habitfan** [comment]
I think the "cancel buff" is a potential short-term fix for some people, but mana just goes to waste if you don't use it. If you choose not use the buffs and want to play higher levels of play, it's so incredibly overpowered that anyone who ceases using it has no chance real chance to advance. But if you use it too well it's game breaking. 

That's the bigger problem that is in play......... legitimate buffing is game breaking. That is a big problem. A very serious long-term problem for the site. This is a flaw (more than a glitch) that causes the game to be nearly unplayable or so unbelievably powerful that it loses all sense of fun or being rewarding. And calling the ability to move up hundreds of thousands of levels in a day with legitimate gameplay - a style of play is only choosing to ignore a serious flaw in the structure of gameplay on the site.

I want this site to succeed, so I am only trying to help but it is foolish to not address this issue unless someone does not have the long term interest of the site as a top priority. 
Seneca

**Comment by lemoness** [comment]
I agree that a cancel buff button would be a stop-gap.

I feel that we probably need some smart math people on this case, but there
are two solutions that have occurred to me for party buffs:
1. Diminishing returns. The more you cast a certain buff in a single day,
   the less effect it has.
2. We already have a cap on stats with post-100 - should we also have a cap
   on stat buffing?

On a side note, we should probably look at every skill and try to make the
buffing ones correspond more evenly to each other.

**Comment by betaveros** [comment]
Has anybody considered simply making the critical hit multiplier ( https://github.com/HabitRPG/habitrpg-shared/blob/e788872932640310427f468d2ec6afa19d08d842/script/index.coffee#L1080 ) a function with diminishing returns of whatever stat is being used?

There are so many stats and values interacting with each other that I'm not sure if this is enough to avoid exponential explosion, and I personally would prefer slow-growing uncapped functions (like square root of stat) if it could be shown to avoid the problem, but I think there are enough diminishing returns functions in HabitRPG that this would be the most consistent choice.

**Comment by betaveros** [comment]
Another benefit of capping or reducing the growth of the crit multiplier would be making Backstab less overpowered, although I don't think that change would be enough by itself.

Here's a specific proposal (I didn't compile or run exactly this yet, only mocking-up in another language):

``` coffee
crit: (stat='str', chance=.03) ->
  if user.fns.predictableRandom() <= chance*(1+user._statsComputed[stat]/100)
    then 1.5 + diminishingReturns(.005*user._statsComputed[stat], 4, 1)
    else 1
```

Expanded version:

``` coffee
crit: (stat='str', chance=.03) ->
  s = user._statsComputed[stat]
  if user.fns.predictableRandom() <= chance*(1+s/100)
    then 1.5 + 4*s/(s+200)
    else 1
```

A table for comparison:

```
 stat old mult new mult
  1.0  1.52000  1.51990
 25.0  2.00000  1.94444
 50.0  2.50000  2.30000
 75.0  3.00000  2.59091
100.0  3.50000  2.83333
150.0  4.50000  3.21429
200.0  5.50000  3.50000
250.0  6.50000  3.72222
300.0  7.50000  3.90000
400.0  9.50000  4.16667
```

Reading the code base, so far I _think_ this will contain most of the overpoweredness of Strength buffing, but it's only a guess.

**Comment by lemoness** [comment]
I think that would absolutely help, although it might not be enough on its
own! It's a start, though. I think diminishing returns may actually be a
helpful route to take with other skills as well (like mana boosts with
ethereal surge, possibly boss damage, etc).

**Comment by Habitfan** [comment]
If the entire mana system is going to be revamped for 1-100 level play I think it can be done in such a way with the focus on levels 1 to 100 but still address the game breaking ability of stacking buffs. I think the problem is the staff is going to have to be prepared for the groaning of having mana neutered.  But sometimes you have to do the right thing for the greater good of the game.

Buff stacking is even an issue well below level 100. There is a person that's been on the site five weeks and there are ready over level 80. Sure they could be patting their stats as this is apparently there first trip to 100. This does even make me a little suspect. But a veteran can easily accomplish the same feet on their second or third trip with a relatively robust to do list and the desire to learn how to use advanced Habit tactics to level up.

Seneca

**Comment by Alys** [comment]
This issue was caused by very high buffs which, since the recent skills rebalancing, are now MUCH harder to obtain. Thus this bug would be either impossible or very difficult to get now. I'm closing this, but it can be reopened if the bug reoccurs (please provide new screenshots).
