### ISSUE TITLE
Mount Master/Triad Bingo

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4178]
I can't believe there wasn't ever a card for this!!

We've got the art for badges all set :) 

Mount Master badge: https://trello-attachments.s3.amazonaws.com/52e9d25cd467121630c6350d/52e9d76055a08df534a7aa7f/01abddbef1fff22a15dc7f54414f2908/wolf_badge_by_aiseant.png
Triad Bingo badge: https://trello-attachments.s3.amazonaws.com/52e9d25cd467121630c6350d/52e9d76055a08df534a7aa7f/24x26/be5175ad71bd0bc00ceb19ba03660075/triad_bingo_-_hanztan.png

Obviously, both Mount Master and Triad Bingo would only affect basic pets, not quest pets.

**Comment by taldin** [comment]
Maybe not so obvious.  :)  Question on this: Mounts show x/180, whereas the Beastmaster is only the basic 90.  Should you get Mountmaster while showing 90+(Quest mounts)/180 Mounts tamed?

**Comment by Alys** [comment]
There's a fix for that in the works. I've been meaning to track it down again and see what it needs to be merged.

**Comment by taldin** [comment]
Playing with some ideas while waiting for a manual to compile at work.  Is the other person's fix done?

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg/pull/3906  Waiting to hear from
lynnyliz about how they'd like to proceed. I should have followed up before
now; I'll do that soon. And then there might be more changes to make after
that. I can't recall the details and am also at work now. :) Feel free to
poke around if you want.

**Comment by taldin** [comment]
I've got a partial prototype working, but one of the algorithms is driving me nuts because it's not working like I think it ought to be.  This is why I'm not a coder. :D

**Comment by taldin** [comment]
I have the Mountmaster achievement working now.  Part of the process is adding language announcements for Mount Master.   Should I put ones in for all the other languages in, just in English for the time being?  Or leave 'em blank and have an error go through?

**Comment by Alys** [comment]
Just the locales/en/ files, none of the others (they're handled in transifex and fall back to /en/ when needed). See the README file under /locales/ for details.

**Comment by taldin** [comment]
Pull requests are at #4200 and https://github.com/HabitRPG/habitrpg-shared/pull/348

**Comment by crookedneighbor** [comment]
@lemoness What are the specifications for the Triad Bingo achievement?

I looked on Trello, and according to the [achievement card](https://trello.com/c/4uWICvDf/19-achievements-v2-awards-badges), it looks like Triad Bingo is a grouping of achievements, rather than a single one. Is that still the case?

If so, I assume they won't be stackable? Seems like a lot of trouble for very little payoff to make each iteration (19 in total, 10 potion types + 9 pet types, right?) stackable.

Should there be a separate achievement for getting all 19 iterations of Triad Bingo? Triad Bingo Master?

On the technical side, should the achievement be an object: 

``` javascript
user.achievements.triadBingo = {
    bearBreeder: true,
    cactusBreeder: true,
    skeletonBreeder: true,
    cottonCandyPinkBreeder: true
}
```

I'm thinking about just rolling this into the mountMaster PR so both can be deployed at once, but that'll depend on how complicated we want the Triad Bingo achievement to be.

**Comment by lemoness** [comment]
@taldin - The Trello is out of date, sounds like - we were thinking of
doing individual ones a long time, but we decided it would be too
overwhelming. For now, let's stick with Triad Bingo being a single
achievement unlocked when you get all 90 pets and all 90 mounts! I think
making it stackable makes sense :)

**Comment by taldin** [comment]
It makes sense to make Triad Bingo be a single achievement for now, and we can figure out how to make a collapsible bingo list later.
