### ISSUE TITLE
Challenge tag field does not allow all emoji because of character limit - remove limit in EDIT form

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4186]
The tag field for challenges appears to have a character limit that prevents some of the emoji from being used. Any chance of that being increased?

_edit by admin:_

**The form for creating a challenge no longer has a character limit for the tag field, but the edit form still does so that needs to be changed. Also in the edit form, the tag field should be moved to below the description field, and it should be shortened, to match what was done in the creation form.**
##

**Comment by sgabler** [comment]
Hey, first post here - I am interested in contributing to this awesome tool :shipit: 

Here's an idea:
Remove the 16 character limitation for the input field. We could instead have a validation that works as follows:
- Show the user that he can enter only 16 characters
- If no emoji are entered AND 16 characters are exceeded, show an error message when the user submits the value
- If emoji are entered, count how many there are and based on that number, allow a certain amount of characters for the remaining tag (needs to be fine-tuned)

I realise that this is probably a bit too much for such little benefit, but that's what I came up with. Does anyone have a better idea?

**Comment by Alys** [comment]
@sgabler It's a clever idea, but as you say it might be more effort than it's worth. It would be simpler to remove the character limit altogether (or at least make it much larger), and I don't think there's a significant problem with doing that. The limit is probably there so that thoughtless challenge creators don't create very long tags that would annoy the participants, but the participants are always able to edit the tag anyway. The tag field in the challenge edit form could have a note next to it pointing out to challenge creators that long tags are undesirable.

**Comment by ghost** [comment]
Still having a problem related to emoji in the challenge tag field only now it's because of too few characters rather than too many. Now that the character limit has been set to a minimum of 3 characters, I can't use a single emoji to tag a challenge because apparently that's only two characters according to the error message I get.

**Comment by Alys** [comment]
I'm sorry you're having trouble with this @Anysia! However I don't believe we've changed the character limit and I've just successfully created a challenge where the tag is the `:o:` emoji, with no error message.  Can you please reload the site and try again, and if you get the error message again, please show us a screenshot of it?

**Comment by ghost** [comment]
It's pretty consistent with any emoji I try (I paste in the image, not the code ... maybe that's the problem?). The error message (tool tip?) only shows up for a few seconds so I'm not sure I can get a screenshot of it.

**Comment by ghost** [comment]
The error only shows up when you save the challenge and it disappears too fast for a screen capture. :(

**Comment by Alys** [comment]
I think you might be right that it's from pasting in the image. The image will probably be interpreted as an actual image, not as an emoji. If you paste in the code, it should work. Emoji are a bit unusual - they aren't actually images except at the moment when the server formats them for display in a browser. Before then, they're stored as plain text, and are treated as plain text, and so they generally need to be entered as plain text.

**Comment by ghost** [comment]
What's odd is that pasting in emoji (or using the emoji keyboard on mobile) is what I've been doing all along and it worked fine right up until around the time HabitRPG became Habitica. :/ Oh well. I'll just have to look up the text I guess.

**Comment by crookedneighbor** [comment]
What you're doing is pasting in the Unicode character for the emoji, which is one character long. I would use the :emoji-name: syntax instead.

**Comment by ghost** [comment]
Well, I wanted to use the emoji :european_castle: but pasting in the image is too short and putting in the text is too long! Is there any way these character limits can be adjusted so that emojis work properly again?

**Comment by Alys** [comment]
@lemoness What do you think about removing the character limit for the Tag Name field in the challenge creation screen to allow emoji to be used, or at least make the limit large enough that a couple of emoji with long names could be specified?

I don't think there's a significant problem with doing that. The limit is probably there so that thoughtless challenge creators don't create very long tags that would annoy the participants, but the participants are always able to edit the tag anyway.

The tag field in the challenge edit form could have a note next to it pointing out to challenge creators that long tags are undesirable, and the field itself could be shortened as an extra hint that only a small amount of text is needed.

**Comment by lemoness** [comment]
Personally, I think that removing the limit is just fine. We probably don't
need a note about the tag, but I think we should shorten the field as a
nice visual cue!

**Comment by Alys** [comment]
I'm advertising this in Aspiring Coders as ready for someone to start working on it. The requirements are that in the challenge creation/edit form, we want the "Tag Name" field to have its length limitation removed, and we want the physical size of that field to be shortened to be perhaps a quarter of its current size. 

The Prize field could also be shortened by the same amount (no other changes are needed for that field). 

The form might then look better if the Tag Name field was moved down one position so that it was directly above the Prize field (thus putting both short fields together, which I think will stop the form seeming unbalanced).

When you submit a PR for this change, please include a screenshot of the form.

**Comment by Arodang** [comment]
I'll take this one on if that's okay. Found the max length and cut that out, moved the tags down by the prize. Working on the styling now, trying to wrap my head around how Jade handles styling and where habitrpg stores the CSS styles.

**Comment by librarianmage** [comment]
Can this Issue be closed @Alys?

**Comment by Alys** [comment]
Hah. Almost. I've just tested and when you're creating a challenge, there's no max length, but when you're editing a challenge there is. So we still need this open for making similar edits to the challenge edit form. I'm about to adjust the issue's title and drop a note into the top post.

@MathWhiz If you want to work on this, please do, just add a brief comment here to say you are. No need to reply if you aren't. Thank you for asking about this!

**Comment by librarianmage** [comment]
@Alys Since this is such an old issue, it may need to be advertised to gather attention (though it isn't a very high priority)

**Comment by Alys** [comment]
Good point. I'll mention it in Aspiring Coders. Thanks!

**Comment by Alys** [comment]
This is fixed. I can create a tag with :o: (`:o:`) and a tag with :european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle::european_castle: which should be enough. :)
