### ISSUE TITLE
post lvl100

### ISSUE THREAD

**Issue by k8sullyvan** [HabitRPG/habitica#4190]
At the moment 100+ players are still gaining Attribute points to spend, however I was under the impression that gameplay would stagnate after that point, with the focus put on using Orb of ReBirth and starting over again.

**Comment by breadstrings** [comment]
@UncommonCriminal - There's an interesting problem with this that my party stumbled across about a week ago. It can be found at #4148. Due to the accumulation of attribute points and use of spells, the game didn't stagnate but escalated to the point where it was almost impossible to log a single task.

My party is now replicating this effect from Level 1 to see if it will cause a genuine problem in future before the developers decide on a mechanism to combat "post level 100" issues. :)

If you have any suggestions on how to make the game stagnate after level 100, we're all ears.

**Comment by HSalgo** [comment]
Great timing! I just wanted to note a bug on this issue as well. Post Level 100, the Stats page gets sort of wonky. It looks like the intention from the final values is:
1) players gain an attribute point every level,
2) level bonuses cap at 50,
3) perfect day buff bonuses cap at 50,
4) everything else (i.e, equipment, class bonuses, buffs from party spells) stay the same.

However, what I see in the breakdown NEXT to the stats is:
1) players gain an attribute point every level (which seems to be correct),
2) level bonuses continue to increment (though again, mechanically it seems to have correctly capped at 50),
3) perfect day buff bonuses cap at 50 (which seems to be correct),
4) certain equipment or class bonuses don't appear correctly (though again, mechanically they seem to be applied correctly).

![habitrpg - post lv 100 stats bug](https://cloud.githubusercontent.com/assets/8142937/4811405/4da8683e-5eba-11e4-8c6e-3e2514ca224c.png)

I've attached a screenshot of my stats. The bolded attribute values are mechanically correct (confirmed using Perception and number of drops per day at a different point). However, the Perception bonus is all wacky, for example. It's 65, which should be 50 level, 10 equipment, and 5 class equip bonus, but the breakdown appears wrong.

I don't have the buffs from a perfect day down right now, but yesterday they were capped at 50.

Thanks!

**Comment by HSalgo** [comment]
Another example--the Royal Magus Hat bonus is missing, and the Level bonuses look incorrect.

![habitrpg - post lv 100 stats bug 2](https://cloud.githubusercontent.com/assets/8142937/4811638/a8bd0f76-5ebb-11e4-97c1-c00cdad53cc0.png)

**Comment by HSalgo** [comment]
Forgive my poor abilities with Microsoft Paint, but I put together an image to summarize some of the issues I've seen.

![habitrpg - lv 122 stats page glitch](https://cloud.githubusercontent.com/assets/8142937/4827808/2e71f3b0-5f7b-11e4-92b5-049ef6c855ca.png)

**Comment by thepeopleseason** [comment]
#3683 should fix the Level bonus display, but needs more eyes. 

It probably could use a rebase, too.

**Comment by HSalgo** [comment]
Not quite sure what you mean by the fix--I'm not the most proficient when it comes to code-y kind of stuff, sorry.

**Comment by thepeopleseason** [comment]
@HSalgo: Just that there is already a pull request which fixes the Level Bonus display problem. The coders in the audience should take a look.

**Comment by HSalgo** [comment]
I think I figured out the issue after a rebirth (at Level 102). It seems to be that while the final stats are calculated correctly, what is displayed is simply keyed to the level number. I can't be sure because I haven't seen the code (I am terrible at reading code), but through process of elimination, I think the following is happening with the displays:

![habitrpg - lv 102 no buffs - class bonus note](https://cloud.githubusercontent.com/assets/8142937/5090766/59b14a0c-6f12-11e4-8209-4f59162c928e.png)

The picture above is taken at Level 102. --> Use "LVL" as the variable.
STATS are correct. --> Use "STAT" as the variable.
- **Level = (LVL - 1)/2** --> should instead cap at 50
- Equipment is correct.
- **Class Bonus = STAT - Everything else** --> this is why it disappears at higher levels
- Allocated is correct.
- Buff (not shown here, but shown in pictures above) correctly caps at 50 for daily bonuses.

It seems like because Class Bonus is calculated as the remainder of the stat's value, when the Level Bonus is incorrectly calculated (does not cap at 50), the Class Bonus gets incorrectly calculated as well (begins to decrease as the Level Bonus passes 50).

I hope that helps?

**Comment by HSalgo** [comment]
Reconfirmed at Level 103.
![habitrpg - lv 103 with buffs - lv 100 glitch](https://cloud.githubusercontent.com/assets/8142937/5109968/fd91691a-6fe2-11e4-878f-38626d6d88b9.png)

**Comment by Alys** [comment]
Attribute points after level 100 are no longer gained.
