### ISSUE TITLE
account incorrectly deleted+recreated/cleared out? - Lost pets, and Lost inventory

### ISSUE THREAD

**Issue by jfrancom101** [HabitRPG/habitica#4199]
2517ca20-4b86-43ac-a689-0aa7f8983222
I had like 17 things in my inventory, eggs/candy/potions, and over 200 spooky sparkles, and one day I logged in and got an error message saying My account had been deleted, and I tried logging in nonetheless, and when i got in ,my gold was gone, i was at level 1, no mana, no inventory, and 17-23 pets were lost, and 3 mounts, what is the problem? is anyone experiencing similar problems?
Firefox, and windows 8
oh I also lost 5 quests, but I have 6 now,.

**Comment by Alys** [comment]
Related: https://github.com/HabitRPG/habitrpg/issues/4193 "Accidentally Deleted Account/Lost Pets"

Ping @lefnire @paglias. Is this a new bug? Or just coincidental that two people had their accounts deleted recently, possibly by others who discovered their passwords?

@jfrancom101 : Please go to [Settings -> Site](https://habitrpg.com/#/options/settings/settings) -> "Fix Character Values" (FCV) and give yourself all the gold that you lost, and also enough extra to buy as many Spooky Sparkles as you want. Sorry about the trouble, but that part is a bit urgent since the Sparkles will be removed from the site very soon (they are special October items) and moderators can't restore them for you. You can also use FCV to restore your level, experience, and mana. We WILL sort out the rest of your missing items; this is just an initial response.

Do you know the unique user ID for your original (deleted) account? If not, do you know the exact username that you used when signing up, or the email address?

It is possible that this was caused by someone discovering your HabitRPG password, logging in as you, and deleting your account. If you are using the same password on your new account, it is important that you change it now (also at Settings -> Site).

**Comment by Alys** [comment]
@jfrancom101 I was wrong, I CAN give you Spooky Sparkles. I'm about to give you 250 (since you said you had over 200) so you don't need to do that yourself.

EDIT: Done.

**Comment by jfrancom101** [comment]
This is the same user name and password, i can change it, i already restored user gold,etc but I have the same account, i never made a new one, i just can't figure out how i lost that many things, can you give me pets, and I have the same user ID I think because I'm still in the same party.

**Comment by Alys** [comment]
Thanks for the extra information about your party! Yes, we will restore your lost items; my first post was just the initial response. I'm not taking any further action just yet because it's best if our database admin looks into this. He might be able to find a record of exactly what items you had so that we don't have to guess at it. Be assured that we will keep following up on this.

**Comment by jfrancom101** [comment]
Thanks.

**Comment by jfrancom101** [comment]
Although I don't think it is the same user ID
I remember writing down my USER API thingy, and I think it is different from the one I have here. I diffidently could be wrong because I don't have my document anymore, I deleted it because I didn;t think I would need it, but I'm not so sure it is the same, but I could diffidently am probably just day dreaming or something. and I think i was in the same party, but it is weird, because someone named Sarah Elizabeth joined our party, and we have no idea who she is, and she got kicked out, then next thing we know she's some how back in, right around the time my pets/inventory got deleted, would that be o your record,

**Comment by jfrancom101** [comment]
*IN

**Comment by Alys** [comment]
Sarah Elizabeth is probably unconnected with your account problems. It is possible that one person in your party invited her without letting the rest of you know, and then reinvited her after she was removed. It's also possible that Sarah Elizabeth was already in your party but with a different name originally. The first time she "appeared" might have been just after she changed her name to Sarah Elizabeth; and the second time she appeared might have been after someone invited her back.

**Comment by jfrancom101** [comment]
There are only 6-7 people in the group all family, and none of them invited her. no one invited her back.

**Comment by Alys** [comment]
Thanks for explaining that! It does seem like a problem! 

Please tell us the party's Group ID, which you can find on the left-hand column on the party page. 

If Sarah Elisabeth comes back, please make a note of her unique user ID before removing her again (you can do that by clicking on her name to see her profile, and her UUID will be on the left column not too far from the top). Please note that this almost certainly isn't Sarah's fault. It sounds like there's some glitch with the party and/or account user IDs that is putting her back into the party.

**Comment by jfrancom101** [comment]
d599ceb6-6b50-4096-abe1-42720963be8a
Okay Thanks.

**Comment by jfrancom101** [comment]
Just so you know the person added today is my brother not Sarah Elizabeth.

**Comment by jfrancom101** [comment]
Are you still looking in to this?

**Comment by jfrancom101** [comment]
Can I just go with what the other person in the link you referenced this to, get gems like they did?

**Comment by Alys** [comment]
ping @lefnire

**Comment by jfrancom101** [comment]
What does that mean?

**Comment by lefnire** [comment]
She's pinging me to make sure I'm still on the issue. I am, I haven't been
able to find any leads yet. I'll continue looking today and get back to
y'all with any details I find

**Comment by jfrancom101** [comment]
Okay Thank You.

**Comment by jfrancom101** [comment]
So. can I just get gems???

**Comment by lefnire** [comment]
Definitely. Sorry for the wait, it's still on my (giant) list - email me
tyler@habitrpg.com, I'll give you gems

**Comment by jfrancom101** [comment]
When I get the gems do I close this or... what?

**Comment by jfrancom101** [comment]
I did send you an email too.

**Comment by lefnire** [comment]
Let's leave this open for now so I can continue to investigate. I gave you
gems (followed in the email).

**Comment by jfrancom101** [comment]
Thank You
