### ISSUE TITLE
Cannot buy limited edition healer outfit

### ISSUE THREAD

**Issue by jarrighi** [HabitRPG/habitica#4207]
I switched to healer today around 8p PST so that I could buy the mummy costume before it went way. I can buy other healer costume items but not the seasonal items. At first it seems like I can buy them. I click on the reward and I see the coins deducted and the reward removed from the list. When the page is reloaded, the items are back in the rewards section, and the money is returned. The special costume items are not in my inventory. I've bought at least one of each type of the standard healer armor items today. 

User ID: 8b6dc502-337f-4d83-838c-1bc7f0786f86

I'm pretty bummed not to get the items since this was the first time I would have been able to get the whole set of limited edition special items. 

Is this happening to anyone else?

**Comment by Alys** [comment]
Duplicate: https://github.com/HabitRPG/habitrpg-shared/issues/349

We need your unique user ID so that we can fix this for you. Please add a brief comment to https://github.com/HabitRPG/habitrpg-shared/issues/349 with your ID and mention that you need the mummy gear.

Your ID is a random string of characters like d904bd62-da08-416b-a816-ba797c9ee265. If you're not sure how to get it, you can find out how here: https://github.com/HabitRPG/habitrpg/issues/2760

**Comment by Alys** [comment]
@jarrighi Sorry, you already gave your UUID. I'm being an idiot this afternoon. I'll fix this up for you right now.

**Comment by jarrighi** [comment]
Oh thanks! I didn't find that one. I edited with my UUID, so you're not an idiot. :)

**Comment by jarrighi** [comment]
Seems to be working. Thanks so much @Alys !

**Comment by Alys** [comment]
Oh thank goodness, I'm not completely stupid. Thank you for telling me. :)  But you didn't find that original issue because I put it in totally the wrong repository....

Anyway, you should be all fixed up now. Check your [Equipment page](https://habitrpg.com/#/options/inventory/equipment) and tell me if they aren't there! I did not subtract the gold for them because I don't have access to do that, but if you want to you can using Settings -> Site -> Fix Character Values.
