### ISSUE TITLE
Drag And Drop + Completed To Do Issue

### ISSUE THREAD

**Issue by lovelies** [HabitRPG/habitica#4226]
A person in the issues also had this problem but mine won't go away.

I try to keep my To Dos very organized because I love doing a lot of challenges. A lot of which have To Dos that go in order either numerically or by the date they should be done. While it doesn't render anything unusable, it is very trying when I try to put them in order but they refuse to stay where I put them. It used to be that they would at least go where I wanted but on the next page hop or F5 they'd muddle themselves again, but now drag and drop doesn't even really work at all. I try and it sends them flying who knows where on my list.

I tried to delete my completed To Dos and maybe this is because they're challenge To Dos for the most part but none of them will actually delete, even my own. I've tried multiple times and would love help with this because it's driving me crazy!

**Comment by prismaticjill** [comment]
I have the same issue, and though it doesn't affect my ability to accomplish to-dos, because I have a lot of them it just makes the game less helpful. Prioritizing my tasks for the day by ordering them is really helpful when I want to glance quickly at what I should be doing (the tags system sometimes helps with this but not as well as prioritizing) and I wonder, too, if them getting out of order is a glitch with the addition of challenge to-dos. Dailies and habits stay were I put them, regardless of whether they are for challenges or not. 

My user id: 1a559244-50e4-414c-af24-6ff764bfa390

**Comment by Tadewi** [comment]
I have the same problem, my To-Dos are just all over the place. And there seems to be no pattern in which they reorganise themselves. I can still drag-n-drop them, but with the next sync or F5 they just shuffle. What's interesting, they don't shuffle if I don't reorganise them.
I can delete completed To-Dos, though, just checked and it works alright for me.

My ID is 02887641-8683-44ad-b8bb-d14470dcce92

**Comment by Alys** [comment]
This issue has been reported at https://github.com/HabitRPG/habitrpg/issues/2606. If you'd like to follow that issue to keep up with the progress of a fix, you can subscribe to email notifications using the subscribe button in the right-hand column.
