### ISSUE TITLE
Cron/Extreme Boss Attacks

### ISSUE THREAD

**Issue by prismaticjill** [HabitRPG/habitica#4229]
My user id: 1a559244-50e4-414c-af24-6ff764bfa390
Group id; f3b24a7f-cc5e-4e56-9359-68427217a6ec

I have two related issues, or an issue that I think is causing another issue. In a quest, my party has recently been experiencing what we think is a glitch (and it's been happening more frequently recently). We are in the Spirit of Spring quest and get hit by large amounts of boss attacks from just one user. Previously, when this happened during a different quest, the member assured us that she had done most of her dailies and thus this kind of damage really didn't make sense. I assume it's the same situation. Here is the copy and pasted party message: 

purplexanidou attacks Ghost Stag for 0.7 damage, Ghost Stag attacks party for 109.9 damage. -a day ago+1 

Related, our party has weird cron times. All but one party member are in the same time zone (gmt -6), and one is in a different time zone (gmt +9). The gmt +9 always rolls over at the correct time, but the other ones roll over two hours early, or sometimes all at different times, and sometimes not at all for a day or two. It's really pretty confusing and tends to change day to day. I'm not sure if this has anything to do with the extreme boss attacks, but seems to only be an issue in quests (the only time cron matters for the party I guess right?)

If it matters, the extreme damage is only ever dealt by that member, purplexanidou, whose id is: 6068eaa2-2954-45c5-9325-5f50841178d5

I personally don't think she has that many dailies, nor do I think that she misses all of her dailies every day.

**Comment by Alys** [comment]
If purplexanidou is completing all/most of their Dailies but still causing large damage, ask them to read [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors), especially "How to Minimise Sync Errors" (section 3) and "Completing most/all Dailies but still losing health and streaks" (section 4.1). 

Doing a very large amount of damage at one time can occur if the player has very many incomplete Dailies, or just a few Dailies but the player did not log in to HabitRPG for several days at a time (without resting in the inn). 

Regarding the weird cron times: In case you're not aware, each player can set their own "custom day start" (CDS) time. By default, it is set to midnight in the player's own timezone but it can be any other time of the day. Also cron does not occur at the CDS time. Instead, it occurs the first time the player uses HabitRPG after the CDS time has passed, which is often several hours after CDS. This probably explains the differing times that you are seeing. In particular, it's possible that when cron seems to happen two hours early, it might just be that the player didn't use HabitRPG until 22 hours after their CDS time. When cron doesn't happen for a day or two, it's usually because the player has not used HabitRPG at all in those days or has been resting in the inn.

**Comment by Alys** [comment]
@prismaticjill If you need more advice about this, comment here and we'll reopen the issue.
