### ISSUE TITLE
unable to access via opera mini

### ISSUE THREAD

**Issue by JamesComprsa** [HabitRPG/habitica#4231]
i tried several times last night to click the play button with my nokia c7 and opera mini.
it isnt possible because of the way opera mini loads pages, just thought i'd let you know.

on a separate note some times the tutorial doesnt finish running with opera desktop, usually stops right after avatar config
##

**Comment by Alys** [comment]
I'm sorry we never got back to you about this. I'm closing it now because the site has had many changes since you logged this, and Opera Mini probably has too. However if by chance you're still having trouble, comment here and we can reopen this, although if Opera Mini uses any non-standard browser behaviour, we might not be able to resolve the issue.
