### ISSUE TITLE
Party avatar Equipment/Costumes/Pets/Mounts in header not updating on sync -- reload/refresh is needed

### ISSUE THREAD

**Issue by bTackt** [HabitRPG/habitica#4235]
I'm not sure what the intended behavior for this is, but if, for example, somebody in my party has changed their clothes or displayed pet, the top bar with our avatars doesn't update on sync. I can click on their avatars to get the updated image, but otherwise I have to completely reload the page to get their new appearance updated. This is somewhat annoying if it isn't intended behavior, and it is annoying if it's intended behavior not working. :stuck_out_tongue: 

I'm using Windows 7, Chrome 38, etc. I do work behind a proxy server. If you need more of these details let me know; I have a feeling they're not very relevant.
##

**Comment by lemoness** [comment]
This happens to my party as well on Safari.

**Comment by paglias** [comment]
The 'sync' actually syncs only the user's data. Party, guilds and tavern are not affected by it actually

**Comment by bTackt** [comment]
Okay, so it is not intended behavior. But isn't it intuitive to have things like this update when they're changed? Is there a "party sync" button?

**Comment by Alys** [comment]
Sync is meant to be a relatively fast way to update the most critical aspects of the site (your tasks, your stats). If it updated party member images as well, it would be slower and that would be annoying when you were wanting to only sync your tasks.

There is no party sync button at the moment so reloading is the only way to update the avatars. It's a good idea to reload HabitRPG every so often anyway, to be sure you've picked up the latest content; I do it every morning.

You might like to request a party sync button on Trello. The site's Help menu has a "Request a Feature" link which will take you to the right place.

**Comment by paglias** [comment]
@knittingfrenzy18 in order to get what you want we would need to have a way to notify users of changes made by others which while something I would really like to have is actually not possible without a _rewrite_ of a good part of the infrastructure the website runs on, something not possible right now.

@Alys we could, when using the sync button, send two requests to the website in parallel: one is the one already used to fetch the user obj, the other could do the same with the party. It wouldn't have much impact on performaces, I would say none at all.

About reloading: we have a feature to force the website to reload  but we didn't use that much, we should force it everytime we deploy new code

**Comment by bTackt** [comment]
Alright, so this is not easily fixed. I hope you will consider some other way to do it another time, though. :)

**Comment by Alys** [comment]
Further discussion is here: https://github.com/HabitRPG/habitrpg/issues/3018
That has more details so I'm closing this one and reopening that one.
