### ISSUE TITLE
Loosen quest drop probability cap?

### ISSUE THREAD

**Issue by betaveros** [HabitRPG/habitica#4237]
I feel like capping the probability of a quest drop at 75% per task is a bit harsh. ( https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L1123 ) I'd still like to make the quest drop probability diminish, but not as harshly; there might even be a probability of multiple quest drops per task. (I'm fine with the probability of regular drops, i.e. the eggs and potions and food; the instant motivation they provide would get dull if their probabilities are not capped. I'd like to make quest drops more likely without affecting those.)

My main reason is that HabitRPG has already rejected several times the idea that Rogues might be able to deal boss damage with Backstab, because they're meant to be support classes. But with this cap, there's a severe limit on how effective they can be on supporting the party on collection quests (which are already rarer than boss quests, right?), compared to the effectiveness of the three other classes as either support or primary fighters on boss quests.

A secondary reason is that since quest drops are delayed until cron, they're already less motivating; quantity is the only way to improve this. (Particularly, unlike boss quests where everybody can do a little damage just by doing a task, there's a significant chance that low-level party members on the quest won't collect any items in a day, which might make them feel left out and is, I suspect, particularly demotivating. This suggestion might be wandering off topic, but perhaps we could substantially ramp up the probability for each player's first quest drop each day?)

Admittedly I see the contrast in that collection quests don't carry any risk, so dragging a collection quest out is not so harmful.

I have some specific formulae in mind, but I'd like to open this to discussion first to see if people like it.
##

**Comment by Alys** [comment]
<strike>I think it's actually worse than 75% because of the way that the diminishingReturns function works. I think the best you can get is 55%.  https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L87  If I'm wrong about that, do please tell me! I'm considering adding drop chances to the [UDD](http://data.habitrpg.com/) and I'd like to avoid a 20% bug. :)</strike>

<strike>55%</strike> It feels okay for the maximum for normal drops, but I agree that collection quests seem harsh. One of my accounts is in a party of eight, and it took us eleven days to finish the moonstone1 quest (500 items to collect). A couple of the party members were saying that 450 might have been a better target (but I'm not necessarily saying we should change the quest itself). My other account is in a party with two players doing the same quest, and we're only halfway through after thirteen days, so it will take nearly a full month to complete (and that's with a Rogue casting Tools of the Trade at least once a day).

I think there is actually some harm to long-running collection quests, because they prevent you doing boss quests, so you lose some motivation to do Dailies. I'm not sure the <55% chance of a drop from a Daily makes up for that.

It would be easy enough to change the code to have a different drop chance for quests compared to normal drops (as betaveros can probably suggest).

I'm wondering if progress for quests in general should be modified based on party size, or perhaps on party characteristics (e.g., leave boss quests as they are for small parties with a Mage or Warrior who are past level 15, but make them easier for small parties with only Healers and Rogues; make them harder for large parties). It sounds complex, but the difficulty-adjustment calculations could be done once at the time that the quest starts, and then those results used for the entire length of the quest.

I know that an easy solution to slow quests is to build a larger party, but since parties are the main way of having a "friends list" (a frequently-requested feature) it might not be reasonable to expect all parties to take on strangers.

But I don't know enough about the initial reasoning behind quest difficulty to know if these ideas are good or bad... :)

**Comment by Alys** [comment]
Ha, sorry, the probably IS capped at 75% because the base drop chance can be greater than 100%. But I think it'd very difficult to get it high enough to reach the 75% cap.

**Comment by betaveros** [comment]
Here's a try...

``` diff
diff --git a/script/index.coffee b/script/index.coffee
index 19ce75f..4954385 100644
--- a/script/index.coffee
+++ b/script/index.coffee
@@ -1120,19 +1120,21 @@ api.wrap = (user, main=true) ->
         (user._tmp.crit or 1) *                         # Use the crit multiplier if we got one
         (1 + .5*(_.reduce(task.checklist,((m,i)->m+(if i.completed then 1 else 0)),0) or 0)) # +50% per checklist item complete. TODO: make this into X individual drop chances instead

-      chance = api.diminishingReturns(chance, 0.75)

       #console.log("Drop chance: " + chance)

       quest = content.quests[user.party.quest?.key]
-      if quest?.collect and user.fns.predictableRandom(user.stats.gp) < chance
-        dropK = user.fns.randomVal quest.collect, {key:true}
-        user.party.quest.progress.collect[dropK]++
-        user.markModified? 'party.quest.progress'
-        #console.log {progress:user.party.quest.progress}
+      if quest?.collect
+        drops = Math.floor(
+            (1 + api.diminishingReturns(chance, 8)) /
+            (1 + user.fns.predictableRandom(user.stats.gp)))
+        if drops > 0
+          dropK = user.fns.randomVal quest.collect, {key:true}
+          user.party.quest.progress.collect[dropK] += drops
+          user.markModified? 'party.quest.progress'

       return if (api.daysSince(user.items.lastDrop.date, user.preferences) is 0) and (user.items.lastDrop.count >= 5 + Math.floor(user._statsComputed.per / 25) + (user.contributor.level or 0))
-      if user.flags?.dropsEnabled and user.fns.predictableRandom(user.stats.exp) < chance
+      if user.flags?.dropsEnabled and user.fns.predictableRandom(user.stats.exp) < api.diminishingReturns(chance, 0.75)

         # current breakdown - 1% (adjustable) chance on drop
         # If they got a drop: 50% chance of egg, 50% Hatching Potion. If hatchingPotion, broken down further even further
```

**Comment by Alys** [comment]
This is more of a feature request than a bug, and the items needed for collection quests have been dramatically reduced since this was logged, so I'm closing this. We can still refer back to it when needed.
