### ISSUE TITLE
Challenge tasks don't go away after leaving challenge that has NOT ended

### ISSUE THREAD

**Issue by kingcitywitch** [HabitRPG/habitica#4242]
I left a challenge and even though i clicked to remove the tasks they haven't disappeared from my habits or dailies.  To dos I removed by just completing them because it wasn't worth fighting with them.  But the rest won't go away.  I don't want to be a part of that challenge anymore and having to click them would be (for me) cheating to raise my character.   I can't get rid of the "1667" daily or the "word count dropped" and "extra words" habits.  I tried rejoining and leaving the challenge again, but no luck.

API: 3633778e-8bb6-463f-8507-ae7f0ac9c8d2
Username: KingCityWitch
I use Firefox and Windows 7 I think.

**Comment by ccaissza** [comment]
I'm having a similar problem in that my "Work on Costume" habit from the Costume Challenge won't go away, even though the challenge itself ended weeks ago.

User ID: 6774035c-d077-4c86-8af6-95bdfaa316ca
And I use Safari and Mac OS X.

**Comment by ccaissza** [comment]
Oh, never mind! This was the first related issue I found and so I posted here, but then decided to look through some of the other related issue threads and actually found a solution that worked for me (found on ticket #2763, "Tasks cannot be deleted after leaving a challenge"):

![screen shot 2014-11-26 at 9 40 06 pm](https://cloud.githubusercontent.com/assets/9970915/5211657/080d0ed0-75b5-11e4-907b-59a8a987ff69.png)
You can then go to Settings and click on Fix Character Values to remove the extra unearned gold and XP that'll come from getting rid of them this way.

**Comment by Alys** [comment]
@kingcitywitch Are you still having this problem? If so, please tell us which challenge it is.

**Comment by kingcitywitch** [comment]
Yes and it's a NaNoWriMo challenge that's not over yet.

**Comment by deilann** [comment]
Try rejoining the challenge then leaving again.

**Comment by kingcitywitch** [comment]
I did that. Even tried after logging out and in again. Nothing changed.

**Comment by Alys** [comment]
@kingcitywitch Please try joining the challenge again, and then leaving it, but show us a screenshot of what it looks like after you've clicked on the "Leave" button but before you've clicked on "Remove Tasks" - I want to make sure that little menu is appearing correctly.

Also, if you have the Chrome browser available, please use it for this test, while the Chrome console is open and tell us if any errors appear there.

**Comment by Laserpiano** [comment]
I'm having the same problem with 2 challenges. Unfortunately they have all ended.
User ID: 6eff9284-461d-490c-b168-4c0bdb10f2bf
Using Chrome for Windows 7 (it was when the bug appeared, now I use Windows 8 and it remains)

**Comment by Alys** [comment]
@Laserpiano : This issue is about challenge tasks that don't go away after leaving a challenge that has NOT ended. For your problem, please see "Deleting a Challenge Task" in [Challenges](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task). If you still have the problem after following all the advice there (including the recommendation to keep trying for a couple of days), then please report it at https://github.com/HabitRPG/habitrpg/issues/2763. If it works, you don't need to comment to let us know (that advice works in almost every case).

**Comment by Alys** [comment]
@kingcitywitch Are you still having this problem? Were you able to get the screenshots mentioned in my comment above from a couple of weeks ago?

**Comment by Artimax** [comment]
Hi, I am having the same problem. I left every challenge and deleted all of my personally added tasks before becoming frustrated and discontinuing use for over a month. However, the site is incredibly useful and I would like to be able to use it again... I do not know whether the challenges that go with my tasks are open or closed, and I do not remember which challenges they were, but I have tried the standard fix of checking it off and refreshing several times. Please say that there is a solution to this! I miss my habit!

My user ID is: 8d08b3b0-dd07-4263-bd63-2c4b3b570d22

**Comment by Alys** [comment]
@Artimax please go to the Challenges page at https://habitrpg.com/#/options/groups/challenges and in the left hand column, click the "All" button, and then scroll down a bit and click the "Participating" radio button. Now scroll up to the top of the page. Do you see any challenges listed there? If so, leave them, being sure to chose the option for deleting challenge tasks.  For any challenge tasks that are still in your tasks list, look at "Deleting a Challenge Task" in the wiki's [Challenges](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) page. There's a few steps in there, including advice to wait a few hours and try again for up to two days, and try using the mobile app, if you have it available to you. Let us know if none of that helps.

Also, @Artimax, I've looked at your database data and you have quite a few tasks that are not associated with any challenges, so you should be able to delete them without any problems. You have some tasks that are associated with challenges that are marked as "broken" (the broken megaphone icon) and you should also be able to delete those by clicking on the megaphone icon. If you want to start from scratch, you might prefer to go to Settings (the gear-shaped icon) -> Site and click on the red "Reset" button. That should remove all tasks, and also remove some other things (be sure to read the text that the button shows you so that you can decide if it really is what you want).

**Comment by Alys** [comment]
Also, @Artimax, I've looked at your database data and you have quite a few tasks that are not associated with any challenges, so you should be able to delete them without any problems. You have some tasks that are associated with challenges that are marked as "broken" (the broken megaphone icon) and you should also be able to delete those by clicking on the megaphone icon. If you want to start from scratch, you might prefer to go to Settings (the gear-shaped icon) -> Site and click on the red "Reset" button. That should remove all tasks, and also remove some other things (be sure to read the text that the button shows you so that you can decide if it really is what you want).

**Comment by Artimax** [comment]
Hello,
Thank you for the quick response. I have done all of this several times and none of it helped.

**Comment by Artimax** [comment]
I will try to reset, but my tasks page lists all of my tasks as associated with challenges and the broken megaphone icon does not appear with any of them, no matter how many times I check them off. Perhaps it's just a glitch in the way the data is displaying itself to me?

**Comment by Alys** [comment]
@Artimax Can you please give us a screenshot of your tasks page, or more than one if needed to show all your tasks? You can come to this issue to drag the image(s) into a comment (emailing them won't work).

**Comment by Alys** [comment]
duplicate https://github.com/HabitRPG/habitrpg/issues/2763
