### ISSUE TITLE
productivity third-party service return back after delete - bug

### ISSUE THREAD

**Issue by zero10xy** [HabitRPG/habitica#4245]
Hello,
I get every time in the "Habits" section a habit that i didn't add.
It's call: "productivity"
In the extra notice it say:
"This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task."

I delete it every time but it came back after few hours.
How can i delete it and that it will not return again?

User ID: 6d35bd4a-7997-403c-a975-6744ac7bf008
Browser: Google Chrome

Thank you

**Comment by Alys** [comment]
It's created by the [Chrome Extension](http://habitrpg.wikia.com/wiki/Chrome_Extension) or by a similar tool (that Habit is how the tool rewards and punishes you) so it will keep reappearing for as long as you are using that tool. If you really don't want it there, you'll need to uninstall the tool and delete the Habit one final time.

I'm closing this since I'm certain this is the solution but if you keep having problems we can reopen it.

**Comment by zero10xy** [comment]
Thank you for the Fast respond! =]
I love HabitRPG
