### ISSUE TITLE
Unexpected loss of gold and HP restored

### ISSUE THREAD

**Issue by brunomperes** [HabitRPG/habitica#4247]
Hi, I was using the HRPG app on my phone on the 'Rewards' tab, then I logged in on my computer on the HRPG web app, it gave me the update (as usual): 
- I lost some HP (can't remember how much, not that much, ~4 I'd say)
- Some XP increase

But my problem was this:
- Lost 80 GP and some silver (had 90GP)

My HP is (suddenly) full again, but since my XP stil on 203/250 and I still have some gold left I don't think I died. I was wondering what could have triggered that? Is that a bug? (I've been only using the android app for a long time, weeks, then logged in online). I didn't buy any reward.

So if there was any history for Gold changes, it could be checked it. Is there such a thing?

I know I can reset the gold, but I didn't want to do if it was a legitimate (but sad) decrease on the amount.

**Comment by Alys** [comment]
When you use HabitRPG on one device (e.g., your PC) and then move to a second device (e.g., your phone) and then move back to the first device, HabitRPG on the first devices shows you a summary of the changes that occured on the second device. So in this case, the change in HP, XP, and GP would have been the results of actions you took while using your phone. Note that you did not lose HP and GP a second time; HabitRPG just told you again about the loses that had occured in the past.

If you didn't deliberately buy any rewards, it's possible that you accidentally touched rewards while your phone was on the Rewards tab, or your phone turned on while it was in your pocket or a bag and rubbed against something that triggered reward purchases.

It's also possible that you did die but then a quest that you were on finished, giving you extra XP and gold.

**Comment by brunomperes** [comment]
In the case it did show the XP I won, thing was I had my phone on my hand and it had 79GP then after I logged in the decrease of gold and my HP was restored.
I wasn't on a quest either.

In any case, I've restored the GP I had previously. If it comes to happen again I'll get back to this issue.
But one thing that would be cool is to see the history of Gold changes on the data.habitrpg.com as well.

**Comment by Alys** [comment]
The data.habitrpg.com site can show only information that HabitRPG records, and it doesn't record a history of changes for gold (or XP, HP, MP). You might like to request that HabitRPG be modified to record history for those stats - use the Help -> Request a Feature menu item on the website.

**Comment by erricgunawan** [comment]
I've just had this experience too.

Logging in and check up some Tasks/Dailies, then when i get to the Web Apps, my Gold suddenly lost and my Health is restored.

If i remembered previously, my HP was 44 and my GP was ~25.

My guess is, probably on the Android, the 'Health Potion' was accidentally pressed. 
So my HP is fully restored (44+15 = ~50) and my GP was reset to 0. 

I can't confirm this, but it's the only reason i can think right now (seeing how my HP and GP calculated before and after).

I suppose this happened mostly because the interface on the Android is not really intuitive. (when you press something, it's not responding in real time, sometimes has to wait first). So probably things like this happening.
