### ISSUE TITLE
Suggestion: "Add-ons" section to website

### ISSUE THREAD

**Issue by ancientcampus** [HabitRPG/habitica#425]
I'd gotten the impression that a prototype Chrome already add-on exists, though I only found it by googling it. Are there other add-ons or app integrations already in existence? If so, there should be a page that lists them all.

Alternatively, if we had a dedicated forum, then it would be simple to make an "addon" subforum, including a sticky listing them all.

**Comment by Pandoro** [comment]
So there is the first call for a dedicated forum :D

I think your suggestions is very valid. So far I don't think there is a LOT
out there yet. Yesterday I saw some quick hacky script Tyler used to get
habitrpg to work with pomodoro? But otherwise I don't know of any real add
ons currently.

Regarding the forum this is most definitely in the queue, it is just that
there hasn't been a decision on which forum to use and with the
kickstarter, everything is a little crazy right now. Hopefully we can get
to this very soon though!

**Comment by lefnire** [comment]
I'll add a [wiki here](https://github.com/lefnire/habitrpg/wiki/Add-ons-and-Extensions), and a simple footer link to said [here](https://github.com/lefnire/habitrpg/commit/a644b572c4f4703fb5b14b9e5fa6b3fb04d6d108). Will flesh it out once the start rollin in

**Comment by horusofoz** [comment]
@ancientcampus With the new [forum](http://community.habitrpg.com) up with sections for the addon, mobile app and web app, are you cool closing this ticket?

**Comment by StanLindsey** [comment]
There is also this page; 
https://habitrpg.com/static/extensions

And yeah, lets close this =D
