### ISSUE TITLE
Upon logging in and syncing, dailies wiped, large increase in gold/xp, damage to health

### ISSUE THREAD

**Issue by MacBone** [HabitRPG/habitica#4251]
I have my daily chron set for 3 am.  Last night, I checked off my dailies using the app at about 12:30 am or so.  I logged on this morning, and my Habit synced.  The dailies on the screen vanished, I earned quite a bit of gold and XP, and I lost about 30 HP.

I logged in using both Chrome and Firefox, and my dailies are missing for both browsers.  My dailies are still present on the app, and they're still displayed as ticked.

**Comment by Alys** [comment]
I'm guessing you're the person who also logged this in the Tavern, so here are the responses that are already there:

From Faranae:
@MadMac Your death is probably due to a sync error. It's always wise to click the ￼ button to make sure you've synced and the server has actually "taken" your dailies. The missing dailies may be due to a tag filter being clicked on. Try clicking on "clear" tags. 

From Alys:
@MadMac : Click the clear button next to your tags, even if it looks like a tag is not selected. Does that make your Dailies reappear? When using either the app or the website, it's helpful to make sure it has synced before the end of the day. Click the sync button in the top right on the website, or drag downwards on the task screen on the app, and then after the sync is finished, make sure your Dailies are still ticked off. I suspect that last night the app did not sync, so your Dailies were not permanently recorded as being done.

**Comment by MacBone** [comment]
Thanks, I appreciate it!
