### ISSUE TITLE
Random Death

### ISSUE THREAD

**Issue by bmtpowers** [HabitRPG/habitica#4258]
I randomly went from 20-something health to dead, without my dailies being reset or counted.  I had taken some damage this morning, but still had half my health.  I clicked on one of my habits (1 hr productive work), and suddenly got a message saying I had died.  My custom day start is set to 6:00AM, and this occurred at about 3:20PM.

My user ID is 8dec90a2-380c-4f52-b6e8-10dfbd3845d0, and I am using Chrome Version 38.0.2125.111 m on Windows 8.1.

Let me know if you have any questions.

**Comment by Alys** [comment]
You're on a quest at the moment (The SnackLess Monster) so it's likely that you died because a party member caused enough damage to kill you by not doing their Dailies. Please go to the party page, click "fetch recent messages" and examine the red messages that show you damage to and from the boss. Are there any there in the past few hours that indicate that the boss did a lot of damage to the party?

If you're not sure about bosses damaging players, you can read more in the wiki's [Quests](http://habitrpg.wikia.com/wiki/Quests) page (especially the "Boss Quests" section).
