### ISSUE TITLE
HP/EXP meter bars always 100% on IE11

### ISSUE THREAD

**Issue by ryanttb** [HabitRPG/habitica#4259]
Issue #2879 has too generic a title & I thought you might want more specific reporting.

It appears Angular is ignoring the meter width binding on IE11. I don't know why that would be, possibly and issue with AngularJS itself, but the inline width is empty.

``` html
<!-- Chrome as rendered -->
<div class="meter health">
  <div style="width: {{Shared.percent(user.stats.hp, 50)}}%;" class="bar"></div>
  <span class="meter-text value">{{Math.ceil(user.stats.hp)}} / 50</span>
</div>

<!-- Chrome as computed -->
<div class="meter health">
  <div style="width: 65%;" class="bar"></div>
  <span class="meter-text value ng-binding">33 / 50</span>
</div>


<!-- IE 11 as rendered -->
<div class="meter health">
  <div style="width: {{Shared.percent(user.stats.hp, 50)}}%;" class="bar"></div>
  <span class="meter-text value">{{Math.ceil(user.stats.hp)}} / 50</span>
</div>

<!-- IE 11 as computed -->
<div class="meter health">
  <div class="bar"></div>
  <span class="meter-text value ng-binding">33 / 50</span>
</div>

```

**Comment by sbreiler** [comment]
Did a Pull Request: https://github.com/HabitRPG/habitrpg/pull/4291
Travis Build failed, however I think it didn't failed because of my changes. The Pull Requests prior mine had same error "Uncaught TypeError: Cannot read property 'length' of undefined at /home/travis/build/HabitRPG/habitrpg/test/api.mocha.coffee:290:51".
