### ISSUE TITLE
Lots of $parse errors on avatar page

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#4282]
When opening the avatar customization pages the console shows a lot of Angular errors: https://habitrpg.com/#/options/profile/avatar
![selezione_023](https://cloud.githubusercontent.com/assets/589911/5200695/c182468e-7568-11e4-9809-25e3b27f5216.jpg)

It seems to be that paths for items are invalid, should switch to `["path"]` instead of `.path`?

@lefnire

**Comment by lefnire** [comment]
@paglias ahhhh, that's a very likely candidate. Many customize options start with numbers (`user.purchased.hair.base.5` & `user.purchased.skin.2b43f6`) which is invalid javascript when accessed with `.` , maybe angular 1.3.3's upgraded `$parse` is more strict now than beta release.

**Comment by lefnire** [comment]
So yeah, `[path]` seems the proper fix

**Comment by paglias** [comment]
I tried something but didn't make much progresses, I'll try again later

**Comment by paglias** [comment]
[This](https://github.com/HabitRPG/habitrpg/blob/develop/views/options/profile.jade#L12) line is driving me crazy, if someone can find a solution

**Comment by negue** [comment]
1. what does this `#{ ... }`, can't find any docs about this in angular
2. why not put this in a well written javascript function, then it would be easier to test / fix IMHO

**Comment by paglias** [comment]
The #{} is jade syntax
Il 26/nov/2014 17:22 "negue" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
@negue the `#{}` is jade, it has a few benefits:
- better performance, since rendered server-side. Also, since habitrpg-mobile renders jade output, even better perf on mobile since no angular watchers are init'd
- cleaner DRY in many cases than what angular can offer
- easier access to `res.locals` vars

However, if in certain cases (possibly this one) angular methods are the solution, we can switch over. @paglias I'll take a look at this now

**Comment by lefnire** [comment]
@paglias give that a shot ^. I refactored the unlock & `ng-if`/`ng-hide` paths into a function, joined as `this["that"]` instead of `this.that`. It seems to work, but I'm kinda looking at it like warily "I hope that's everything...". Note, we don't want the `ng-click='unlock()'` paths to be joined "properly". Reason is they're joined as a string, which is an argument to the unlock function - not parsed by angular in the template. That string is sent to the server, which uses `index.coffee#dotSet()`, which expects the string exactly so. So it's just expressions which are eval'd by angular that care.

@negue I remember another big reason I used jade. Jade lets you have adhoc functions and templates, latter which accepts arguments for conditional rendering. You can do the same in angular with some complex directives workarounds (which I think is better in many cases), but very often it's cleaner & faster via jade. But I'm open to discussion if you disagree

**Comment by lefnire** [comment]
If we decide to use angular for stuff, take a look at https://github.com/a8m/angular-filter which we're already using in some cases

**Comment by paglias** [comment]
@lefnire great!
