### ISSUE TITLE
Cannot feed a strawberry

### ISSUE THREAD

**Issue by SoonerDVM** [HabitRPG/habitica#4284]
I cannot select strawberries to feed my pets. When I mouse over, the tooltip flashes, but I can't select it. I can select any other food type, but not strawberry. This issue is consistent in Firefox and Chrome. 

EDIT: I was incorrect - I can't feed food items on the right side of the column. When the strawberry moved to the left column, I could select it just fine.

**Comment by nagledb** [comment]
I am having the same issue: while on the Pets inventory tab, mousing over a food item on the right side of the "Food and Saddles" section causes the food's description tooltip to appear over the item, preventing you from clicking on it.

Specifically:
When you mouse over food on the left side, the descriptive tooltip appears to the left of the food item; the pointy part of the tooltip is just barely overlapping into the food icon and looks right.
When you mouse over food on the right side, the descriptive tooltip appears on top of the food item; the pointy part of the tooltip is off to the right of the food icon and the whole thing is very clearly in the wrong place.

While mousing over a food item on the right, the tooltip appears and disappears in a cycle (I assume the code thinks you are mousing on and off the food since the tooltip occludes it). Clicking while the tooltip is visible accomplishes nothing. Clicking while it is not visible (if you time it right) does seem to get through to the food but doesn't actually activate it for feeding.

The issue is consistent for me in Chrome, Firefox, and MSIE.

**Comment by Alys** [comment]
This has been reported at https://github.com/HabitRPG/habitrpg/issues/4278 and has been fixed but the fix hasn't been migrated to the live site yet (migrations take time so they can't be done immediately, unfortunately). It should be only another day or two I would guess.
