### ISSUE TITLE
Dailies not resettting or not treated as completed (but cron runs, quest progress is reported)

### ISSUE THREAD

**Issue by flutterbye** [HabitRPG/habitica#4317]
I've been having this problem since Friday night/Saturday morning.  **Cron is running but dailies are not resetting**.  I am in a boss battle and **the boss is dealing damage each night even when I have had a perfect day**.  There seems to be no consistency, some reset and others don't, I can't see a pattern.

I have never been in the inn.  I have tried synching, reloading, logging out and back in again.  I have never used a different device.  I hadn't changed the custom time until just now (thought it might help fix it, it didn't).

The site is becoming unusable for me now.
flutterbye
82deff92-7a31-4ce9-9403-0e718bd0943c

**Comment by Alys** [comment]
I'm so sorry this is being so annoying for you. :(   It really does seem as if cron has been playing up more than usual lately - a lot more than usual in your case!

However we do need to eliminate one possible source of these problems, so that we can be sure that we'll be focusing on the right part of the problem. Could you please look at the wiki's [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors) page, especially the sections called "How to Minimise Sync Errors" and "Completing most/all Dailies but still losing health and streaks". Does there seem to be any information there that might be relevant to the problems you're having? There might not be since you've mentioned that you have tried syncing, but I have to ask just to be sure.

In particular, for tonight and tomorrow night, could you follow this advice:
_"Just before you stop using HabitRPG for the day, use the sync button or the User Data Display tool to check that your Dailies really have been marked as completed."_
and then tell us if the cron problems still happen for you? Or have you already been closely following a process like that over the past few nights?

If we can completely eliminate sync errors as a possible source of your problem, that will put us a step closer to being able to work out what's causing this.

**Comment by flutterbye** [comment]
Hi Alys, thanks for the reply.  As the problem has been going a few days **I've been forcing a sync after I tick off anything and also completing the ticks earlier** so I'm not doing it close to midnight.  I'm also making sure the page is not open at midnight as I was logged in Friday night when the first error occurred and wanted to eliminate that as a cause.  I haven't tried the User Data Display so I will try that tonight once everything has been ticked.  I'll let you know how I get on :)

**Comment by Alys** [comment]
@lefnire, @paglias  - FYI!!! See the phrases I've bolded above in flutterbye's two comments (tldr: probably no sync errors, cron runs but incompletely/incorrectly?). Similar reports are in https://github.com/HabitRPG/habitrpg/issues/4313

@flutterbye  Thanks for explaining that! _"I've been forcing a sync after I tick off anything and also completing the ticks earlier"_ - that's very good to know because I think it pretty much eliminates sync errors as a cause of your problems. I suspect the Data Display won't make a difference since you've already been so thorough with forcing syncs. But certainly try it if you want to! Good luck. I'm sorry again that this is causing you so much trouble. Thanks very much for the detailed bug report! If we can help with anything, such as giving you back equipment that you lose due to unfair deaths, please do tell us.

**Comment by flutterbye** [comment]
Thanks :)  I'll let you know if I have any new info.  I've died once as a result, but really I'm more concerned about losing real life motivation and am just interested in getting to the bottom of it.  I've been considering making a new account but that seems a bit drastic, plus I'm level 35 lol.  Do you think deleting all the dailies and making them again might help?

**Comment by Alys** [comment]
It's really hard to say. Normally with cron problems I'd say that deleting and recreating Dailies wouldn't make any difference, nor would creating a new account, but then the usual cron problems tend to happen on one night and then disappear after that. I think we're looking at something new here, so I don't really know... But then I don't have a good understanding of cron. :) The people I flagged in my previous message (@lefnire, @paglias) might have a better idea!

When your Dailies don't become unticked after cron, is it ALL your ticked Dailies that stay ticked or just some of them? If it's only some, and always the same ones, then MAYBE recreating them MIGHT help. If it's all, or if it changes randomly each time, then it probably won't help.

I've given you back the piece of gear that you lost.

**Comment by flutterbye** [comment]
No it's not all of them, some of them reset.  Last night I think 2 out of 13 reset and the others stayed grey and ticked, yesterday I think about half of them reset.  I'm probably scraping the barrel of information I can give you, but last week I did have to grey some dailies due to lack of time, I'm wondering if that may have had an effect.  Also on the Friday night when the first problem occurred I was still logged in and cron did not run at all.  I tried syncing as I was interested to see how I did in the battle, but nothing would happen.  When I logged in Saturday morning, cron had run but the dailies had not reset.  Finally, I am sure the to-dos I ticked off on Sunday did not register as I dealt no damage to the boss.  Thank you for giving me back my staff! :)   I reset my character values today after unticking the dailies but this is the first time I have done that.

**Comment by Alys** [comment]
Thanks flutterbye. It's useful to know that it seems to be randomly choosing Dailies. Greying out Dailies shouldn't have an effect, and neither should staying logged in overnight or logging out overnight.

Please let us know whether it happened again on your next cron or not. Sorry about the extra hassle. :(

**Comment by flutterbye** [comment]
It worked last night :D I'll let you know if I have any more problems with it.  Thanks again!

**Comment by betsybookwyrm** [comment]
Something much the same as this happened to me today.

When I opened Habit for the first time today, **I received damage for yesterday's undone dailies** (I didn't actually see the notification, but my health is definitely less than yesterday and it seems about what I expected, or possibly a bit more damage than expected. I am not currently in a quest.), **however my dailies did not reset**.  As far as I can remember the dailies are exactly as they were at the end of yesterday, even with my partially completed checklist still partially completed. The only difference is that the correct dailies for the days of the week are greyed out (there's only one daily that's on for Thursday but not Friday, and I didn't complete it yesterday and today it's grey but still not ticked).

**I reloaded the page, synced, etc**, but I didn't notice that my dailies hadn't reset until I'd already ticked one for today, so that might complicate matters? 

**I looked at the data display tool daily history for yesterday, and it shows some of the dailies I completed yesterday as completed, but there are a couple that I know I ticked that are marked not ticked in the table, even though they are still ticked off in my dailies list and I definitely didn't tick them today.**

I haven't been on HabitRPG much in the past month, but for the past day or two everything has seemed to be working fine, until today. I've been making an effort to not click lots of things too fast because I'm aware of sync issues, but I'm not always good at it so who knows!

betsybookworm
0f5e92c0-71d9-417e-b92d-c8279fb2db0c

**Comment by Alys** [comment]
@betsybookwyrm Thank you very much for that detailed report! That's very useful information, especially the part about the data display tool. I've highlighted some of the most critical parts of your comment to make it easy for us to glance back at them.

@lefnire @paglias There's is definitely an odd new bug that's been affecting people for the past few days. Cron does run enough to give damage from incomplete Dailies, but doesn't reset the completed ones. Similar reports have said that zero damage is sometimes done to bosses even though To-Dos or Dailies have been completed (not missing boss damage reports but "0.0 damage" done to the boss). Sync errors don't seem to account for this - reports have come from people who are aware of sync errors and work to prevent them.

**Comment by lefnire** [comment]
I'm seeing this pretty frequently: `Cast to number failed for value "NaN" at path "purchased.plan.consecutive.count"`. I'm pushing a possible fix now, I'll keep an eye out otherwise

**Comment by betsybookwyrm** [comment]
It happened again, but I was a bit better prepared this time :) Only four of the dailies I ticked yesterday are marked as done in the data display tool daily history table. Three of those are no longer ticked in my dailies list, but one is. All of the other dailies I ticked yesterday are still ticked in the dailies list and not in the daily history table, and it looks like I received damage from them.

I think I've only had my dailies properly all cleared out at the start of the day once since this first happened to me, and that was after not logging in to habit for over 24hrs and missing a day.

**Comment by Alys** [comment]
@betsybookwyrm Thank you for those details! I have a request, but I do know this will be inconvenient for you -- would you mind not ticking off or unticking or editing any of your Dailies for the next three hours? That means that the current state of your Dailies will be stored in the next database snapshot, which will make it easier for the state of your Dailies to be studied in detail. If you'd rather not, that's okay, but the untouched data could be quite useful for us.

Also, would you mind sending us a screenshot of your Dailies as they are now? If they contain private information, you might not want to (and that would be fine) but it also would help us.

**Comment by betsybookwyrm** [comment]
![image](https://cloud.githubusercontent.com/assets/7349756/5348799/ba09d172-7f7e-11e4-89b9-1d404590a4eb.png)
![image](https://cloud.githubusercontent.com/assets/7349756/5348809/cbbc5fa2-7f7e-11e4-8be7-0258308ef091.png)
![image](https://cloud.githubusercontent.com/assets/7349756/5348833/0c09ef0c-7f7f-11e4-87d2-297a2cb1f807.png)
![image](https://cloud.githubusercontent.com/assets/7349756/5348851/48ac597c-7f7f-11e4-9fa3-63d9ced50802.png)
I haven't ticked anything yet today, and I can wait a few hours :)

**Comment by Alys** [comment]
@betsybookwyrm  Briilliant! Thank you so much!

**Comment by Alys** [comment]
@betsybookwyrm : The database backup has finished so you can now do whatever you like with your Dailies. Thank you for waiting! We'll be in touch in a day or two hopefully, if we can find anything useful in the data. [cross fingers]  

If we do find anything, it's likely to help the other people who have this issue too.

**Comment by Alys** [comment]
I haven't been able to find anything out of the ordinary in the data for any of the people who have reported this here, but we are adding extra logging to the cron process which might show us where errors are occurring.

**Comment by flutterbye** [comment]
Hello again.  The problem came back last night.  It dealt 45 damage to me and killed me, and dealt around 10 damage to each of my party,  I did leave the browser logged on last night and I know you said this shouldn't affect it but thought I would mention as I was also logged in the first time it happened.  Really disappointed :(

**Comment by flutterbye** [comment]
Oh I just wanted to add, I ticked off a lot of to-dos yesterday and got no credit for them as the damage I dealt to the boss was 0.0

**Comment by zuchinno** [comment]
This is basically happening to me too. My dailies never appeared today and when I look in the grey ones, it shows check marks next to all the ones due yesterday. I just lost 13 health and my buff and probably all my streaks for no reason. Who memorizes every streak counter?
(https://cloud.githubusercontent.com/assets/10258820/5517720/e8b497da-88ae-11e4-8525-3df2bc2f1520.png)

**Comment by paglias** [comment]
@zuchinno could you post your UUID? @flutterbye you too if it's still happening these days. We've some enhanced logging now and I want to verify a thing

**Comment by ghost** [comment]
UUID: 28771972-ca6d-4c03-8261-e1734aa7d21d  Cron is set to 8am, I'm on central time. 

Last night (which I am pretty sure was a perfect day), checked off all dailies, last few a little after 2 a.m., refreshed page to check they're okay (because my connection stability is shockingly poor), put computer to sleep and headed to bed. 
This morning, ~10 a.m., briefly open habit in my mobile browser without doing anything (and find 10 testimonies, according to party chat, but obviously no damage report with a gathering quest). 
Noonish, still in mobile browser,  check off both halves of a +/- habit, and check one part of a checklist daily, everything's A-OK. 
Noon-thirtyish, sign in on firefox. Despite refreshing, 3 dailies remain entirely checked off and finished. They are the same 3 dailies that I checked at 2 a.m. One is also the daily that I checked on my phone, so it has 1/4 checks on my phone and is fully-checked/finished on my computer. For what it's worth, my phone and computer display the same amount of health, but on the computer I have a little more XP and gold. I do have a perfect day. I can't speak to whether I did/didn't take damage from any dailies, but streaks are intact and the Data Display Tool says I did them all yesterday.
Just now (1pm), after refreshing habit on phone: Phone aligns with what's displayed on firefox, including borked dailies.

**Comment by Alys** [comment]
To all the people who have experienced this bug: Has this bug ever happened on days when you used ONLY the website? I.e., did it happen after days when you never used the mobile app?

**Comment by ghost** [comment]
Well, to clarify slightly, when I was on mobile today, that was not the app, it was the mobile browser (the default one with my phone (android), is not chrome, is just labelled "internet"). I did not use the app today or yesterday. I probably loaded the mobile site yesterday, since it's my mobile browser homepage, but don't recall if I actually"used it"-used it.

**Comment by flutterbye** [comment]
I've never used anything but the website.  No problems since my last post
btw :)

**Comment by Alys** [comment]
To all the people who have experienced this bug: You don't need to reply now about whether you were using the website or mobile app. @flutterbye and @Cantras have blown my theory out of the water. :)

@flutterbye It's great to hear that it hasn't happened recently for you! Are you aware of anything that might have changed at your end when the problem stopped? Perhaps you started using a new browser or new PC or ... anything ...?? I'm definitely not saying that the problem was caused at your end, I'm just trying to find anything that might explain why some people get this so often and others don't.

**Comment by zuchinno** [comment]
Hello! I'd mentioned I was having the same or similar problem. I was wondering how many people experiencing this issue have their days set to end some other time than midnight... 
I had set mine to 3AM because I'm a night owl and I feel good checking everything off at the end of the day.
Anyway, I realized that the issues started after I moved my time to 3AM in the settings. I looked back and saw this underneath: "Warning: this is a highly-experimental feature, and many experience issues with it."
So I changed my time back to 2AM instead of 3AM and things worked fine. Also, I think I can probably put my time back to 3AM, just if it gets stuck, change the time on the clock momentarily and change it back, and then it's kind of like a duct tape manual reload for Dailies. 
I hope it works for you... it's worth a shot anyway. I'll update if it breaks again.

@paglias here's my User ID: cc2b12b2-8bea-4fcc-819e-798b36b6aa85
Also, I use chrome on my laptop and also the android app, though I usually whip out my laptop if my phone doesn't work and the problem seems to be the same either way.

**Comment by ghost** [comment]
I'd seen mention of custom day start in another thread (I believe about a double-cronning bug, but I can't find it now), which is why I mentioned mine and the times I checked off dailies.  I changed my day start my very first day in habitica, 8 months ago. 
When you say that it's a "manual reload for dailies", is it possible it just ran your cron? I know that if you change your CDS too close to cron, that sometimes happens. If all your tasks had remained checked, the cron would have cleared it up. (Those of us with some dailies checked and some not would take damage/lose streaks in that process, though.)

**Comment by flutterbye** [comment]
No changes to my PC.. I try to make sure the site is closed at midnight as
I was logged in most times it happened.  The only other thing that's been
different is I haven't greyed any dailies out recently.  My account isn't
very old, a few months at most, don't know if it's possible it's newer
accounts having the problem?

**Comment by flutterbye** [comment]
Happened again last night, only 2 dailies have reset the rest have dealt damage and remain ticked and grey.  My ID is 82deff92-7a31-4ce9-9403-0e718bd0943c

**Comment by Alys** [comment]
The problems reported here definitely sound like the same ones that we are tracking in https://github.com/HabitRPG/habitrpg/issues/4313 and that issue has several links back to this one, so I'm going to close this issue. If you'd like updates on the progress of the investigation, there's a notifications subscription button in the right-hand column of https://github.com/HabitRPG/habitrpg/issues/4313.
