### ISSUE TITLE
[Suggestion] Daily Reset Time Setting

### ISSUE THREAD

**Issue by PsychShaman** [HabitRPG/habitica#434]
I just saw that the Dailies reset at midnight (CST).  Would it be possible to have a setting where we can select when we want the dailies reset?  For instance, I usually stay up until 2 am, and I don't know if I'm going to complete some of my dailies from midnight to 2 am.  I could just fill them out for the next day, but there's some satisfaction in crossing everything off at the end of the day.  For us late nighters or odd shift workers, it would be nice if we could pick when our dailies reset (by the hour is fine).  Thanks!

**Comment by Pandoro** [comment]
There is a [trello card](https://trello.com/card/timezone-day-start-options/50e5d3684fe3a7266b0036d6/15) for this suggestion already. You can vote for this feature, there, but looking at how high it is rated right now, I think this will be implemented at some point :)

I'll close this in order to keep the board organized. Feel free to post follow up stuff though.
