### ISSUE TITLE
Task page on mobile website

### ISSUE THREAD

**Issue by Nondescript1010** [HabitRPG/habitica#4398]
The task tab only shows a couple of each habit, daily, and to-to.
There is no way to see the other tasks when browsing on a mobile device.
Also, there is no way to apply a skill to a task on that page, such as backstab.
I also see no way to switch to a desktop version of the website from the mobile version.

**Comment by crookedneighbor** [comment]
Each column should have a the ability to scroll to see the rest of the tasks. Are you unable to do that? If so, what device, operating system and browser are you using?

Skills can be tricky on mobile, because the first tap might be interpreted as a hover command, which would open the popover instead of activating the skill. If you do successfully activate the skill, it's difficult to tell, since the way to tell on the website is that the cursor changes, but with persistence you can do it.

What does everyone think about eliminating the popover calls for touch devices?

And how about adding some additional indication that a skill is in process for touch devices? Like, maybe a border around the active skill?

**Comment by Alys** [comment]
@Nondescript1010:

If scrolling doesn't show you all your tasks, click the "clear" button that's to the left of (or possibly just above) your tags. Do that even if it looks like no tags are selected.

There aren't desktop and mobile versions of the website. There's just one version that changes appearance depending on the size of the window. You can get a similar view on your desktop machine by making your browser window very small. Hover/tap behaviour is different because of in-built differences in the browser and user interfaces on desktop versus mobile.

@crookedneighbor;
_"eliminating the popover calls for touch devices?"_ It would certainly make the main functions more usable, but for people who have no access to a PC, they'd never be able to see information about skills, gear, etc (I've seen a few such people in the Tavern). Perhaps on mobile, the note icon could be more prominent (maybe with a line dividing that end from the rest of the box) and when they tap on it, the info pops up.

_"additional indication that a skill is in process... a border around the active skill"_ Lovely idea! And not just for mobile. Occasionally I choose the wrong skill on my PC and don't notice until it's cast.

**Comment by Nondescript1010** [comment]
Ok. Hitting the 'clear' button seems to have revealed all the tasks. That's a bit obscure, though. I don't even know what 'clear' is supposed to do.

**Comment by crookedneighbor** [comment]
@Nondescript1010 The clear button clears any tags you have enabled. Having a tag enabled will only show you the tasks with that tag.

So either you accidentally turned on a tag, and no tasks had that tag, or there was a glitch and the system thought you had turned on a tag (happens sometimes).

Either way, glad to know you're up and running again!

**Comment by Nondescript1010** [comment]
FYI, I am running the Chrome browser on an Android phone.
