### ISSUE TITLE
Buy Gems popup has a link to open another Buy Gems popup. Clicking results in a second Buy Gems popup.

### ISSUE THREAD

**Issue by lucymhdavies** [HabitRPG/habitica#4401]
Steps to Reproduce:
1. In Menu Bar, click the Gems icon to open the Buy Gems popup
2. In the popup, hover over the X Gems link in the top right, to make the + icon appear
3. Click the + icon, to launch a second Buy Gems popup
4. repeat

See https://www.youtube.com/watch?v=lFg5WOd63Ec for example.

Doesn't seem user specific, but as per instructions here is the User ID used in the video:
4c0f767d-3ec4-463d-8f43-1d1cf11562f0
(My main account's User ID is ce001c25-d2af-427d-b739-7a3611d765fa)

In case it's relevant, I'm on Mac OS X Yosemite, Chrome 39.0.2171.95.

**Comment by crookedneighbor** [comment]
Thanks for reporting this.

It's because the gems modal is using the gem include in `/views/shared/gems.jade`

Probably the best course of action will be to add a variable like, `isGemsModal`, which, when set to true, skips the `ng-click` part of the `gems.jade` include. Then, just setting the modal to have `var isGemsModal = true` before the include will prevent the `ng-click` from being loaded in.

**Comment by lucymhdavies** [comment]
Yeah, it seemed like something simple enough to fix when I had a look at the code.

If I find time over my xmas break I'll get a local version of the app up and running, write a fix, then submit a pull request :)

**Comment by crookedneighbor** [comment]
:+1:

**Comment by lucymhdavies** [comment]
Simple fix in Pull Request https://github.com/HabitRPG/habitrpg/pull/4410

**Comment by lucymhdavies** [comment]
Same fix, but utilising mixins, in Pull Request https://github.com/HabitRPG/habitrpg/pull/4462
