### ISSUE TITLE
Need Quest Cancelled/Started

### ISSUE THREAD

**Issue by Yuubou** [HabitRPG/habitica#4435]
A party member invited us to a quest and hasn't started it after 2 weeks (we have a couple of people in the inn, so it won't start automatically).  I think the party member checks Habit from his phone, so maybe he isn't seeing our party messages/PMs.

Could someone help us by either starting the quest or cancelling it for us? 

User ID:
7846c2cc-400d-4aff-b1ad-40ee3d68305c

Group ID: 
67298e51-99d7-4530-871e-9c26fa1940cb

**Comment by Alys** [comment]
Starting or cancelling quests isn't something that an admin would typically do because we can't be sure that all party members would want us to do that. In particular, we would ideally want permission from the person who owns the quest scroll since they probably paid gems (real money, effectively) for it. It would also require direct database manipulation which always carries at least a small risk.

Is that person the party leader? If not, the party leader could remove the quest owner from the party. The quest would then be cancelled and the scroll would go back into the inventory of the quest owner (i.e., they would not lose it and would be able to use it again). The party leader (or any other party member) could then invite the person back to the party.

If it's the party leader who is being unresponsive, you might want to discuss making a new party. One person could collect all the unique user IDs of responsive party members, then those people could leave the party, and the person could invite them all to a new party. This is rather an aggressive solution though. :(

I suggest talking through these options with your party members, and let us know if you can't come to an arrangement that works for the majority of players.

**Comment by Yuubou** [comment]
Thanks, I'm the party leader, so I'll use that solution in the future.  I'm not sure if it was our quest owner or someone here, but the quest started, so you can close this ticket.  Thanks for your help.

**Comment by Alys** [comment]
It was almost certainly the quest owner. 

Thanks for letting us know!
