### ISSUE TITLE
I turned into a woman.

### ISSUE THREAD

**Issue by and1hof** [HabitRPG/habitica#4453]
Hey, I've been using habit RPG and today I logged in - whoops all the sudden I'm a woman!

Is this a typical random transformation, or part of a bug?

**Comment by crookedneighbor** [comment]
Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api). This will help us take a look at your settings.

**Comment by SabreCat** [comment]
Does it persist after a browser refresh? It could just be the sprite scramble that happens when new images are added.

**Comment by deilann** [comment]
Or it could be a dupe account. Do you have the same tasks?

**Comment by and1hof** [comment]
Here is my user id: 0542c617-2231-4605-8989-fe9991c41fa5
And It persists after browser refresh, I'm not sure why.

**Comment by paglias** [comment]
If you change back to a man in the avatar customisation page does it work?
Il 31/dic/2014 19:15 "Andrew Hoffman" notifications@github.com ha scritto:

**Comment by and1hof** [comment]
Hmm, 

Where is that option? I've never customized my avatar I just use this for tracking achievements :)

**Comment by crookedneighbor** [comment]
https://habitrpg.com/#/options/profile/avatar

**Comment by crookedneighbor** [comment]
Here's the preferences related to appearance your user has:

``` JSON
  "preferences": {
    "shirt": "blue",
    "skin": "915533",
    "size": "slim",
    "hair": {
      "flower": 1,
      "mustache": 0,
      "beard": 0,
      "bangs": 1,
      "base": 3,
      "color": "black"
    }
  }
```

Which results in: 

![screen shot 2014-12-31 at 12 54 12 pm](https://cloud.githubusercontent.com/assets/2916945/5589754/288270e0-90ec-11e4-9de2-6e83b9ff5b90.png)

Change your [appearance settings here](https://habitrpg.com/#/options/profile/avatar) and let us know if it gets resolved that way.

**Comment by Alys** [comment]
The "auth.timestamps.created" date for this account is "2014-12-31T03:09:52.426Z". This is a new account.  

@andhof-mt if you've been using HabitRPG for more than a day, then this is likely a duplicate account, as @deilann said (that can happen sometimes due to a bug). Your avatar therefore is the new default one. 

Are all your tasks correct? 

At any time in the past, did you happen to make a record of your user ID? If so, it will be different than the one you gave us above, and we would need to know what it is.

Do you happen to have HabitRPG still open from before this occurred in a different browser or PC or mobile device? If so, it will have your old user ID in it.

**Comment by Alys** [comment]
Also, @andhof-mt, please tell us roughly how long you have been using HabitRPG.

**Comment by and1hof** [comment]
I've been using habbit RPG for about a week now. I started on my mac PC and now I'm on my windows laptop. Both times using the web version not the source on github.

**Comment by Alys** [comment]
@andhof-mt We still need an answer from you about your tasks. Are all your tasks correct? Did you discover within the last day or two that some of the tasks you'd added had disappeared and you had to re-add them?

Did the method you use to log in to HabitRPG change in the past day or two? For example, are you now logging in with user name and password, whereas previously you were logging with facebook? Or are you using a different user name now? Or are/were you logging in with an email address instead of a username? 

The reason that I'm asking these questions is that I'm trying to work out if you do have a duplicate account, which is important because it could cause problems for you later on. 

Note though that if you started using HabitRPG in the past week or two and you never customised your avatar, then your avatar would always have been exactly as displayed in the image above. That's the default avatar that all new accounts have.

**Comment by and1hof** [comment]
Perhaps I just made another account without thinking (auth with Facebook by accident maybe?) :) I hadn't added custom tasks yet, I was just getting started.

**Comment by Alys** [comment]
It's important that you look into this before you get too far along the process of setting up your tasks. If you do have two accounts, it will cause endless nightmares. Try logging in on the Mac again if you saved your login info there. Or try logging in on either machine using Facebook. If you notice one login/machine/whatever gives you any differences than the other, choose one account to keep and delete the other one (Settings -> Site -> scroll down to the large red delete button).

I'm going to close this issue because the avatar you have is the standard one for all new accounts and you can change it easily as described above. There isn't a bug that caused you to have this avatar.

However if you need any help with sorting out your account problem, you are welcome to keep posting here and we will keep answering. :)
