### ISSUE TITLE
Suggestion: more gold for regularly done dailes

### ISSUE THREAD

**Issue by hjalmberi** [HabitRPG/habitica#446]
This one comes from someone struggling with daily exercise and flossing. Would it be possible to make it somehow valuable to keep them in a row? The current system works perfectly for me in all ways except this moment.

**Comment by wildcate** [comment]
This is a good suggestion, I think - I noticed that the comfy green has invited me to slack "oh, just that once, since that's not so bad".
Maybe dailies done in a row give less XP but more gold (a little more gold, up to a cap?) the longer the streak goes on?

**Comment by wc8** [comment]
Would [Completion Quotas](https://trello.com/c/E5CVJlW6) fit the bill or is _GP/XP gain for consecutive completion_ a separate request?

**Comment by hjalmberi** [comment]
It might be similar. Flossing and stretching are genuinely daily tasks and doing them in a row is supposed to be very good. But the quota of 7 from 7 sounds a bit complicated, isn't it?

**Comment by wc8** [comment]
Hm... as I reread it, I think maybe that suggestion is for a task that needs to be completed X times within a certain period of days rather than having to do with consecutive completion. 
So, here you go: [Consecutive Completion Bonus](https://trello.com/c/wTiRWiB2)

**Comment by wc8** [comment]
@Hjalmberi how about 1 silver for every day completed and 1 gold for every week without missing?

**Comment by wildcate** [comment]
I think it should be enough incentive (also relative to the other habits/dailies/fresh ToDo items) to get one started on the habit or regular tasks, but theoretically the amount of Gold/XP lessens the longer you do it, right? 
I'm not sure how to best handle this numbers-wise, though. A habit will need some time to start getting established (about 30 days consecutively hovers somewhere in my brain for that), and I think after some consecutive time it will be fully established so that space on the game can be occupied by something else (maybe tie that in to Mastered Habits?). For example, I've been flossing daily for so long that I can't imagine not doing it.
So the thing would be, maybe, to give enough incentive to start one off, and then sort of shift the rewards to consecutiveness so that the main bonus stays more or less the same value, but is only awarded once a week, maybe even with a note that says something like "You are well on your way to mastering yourself, young Padawan!" (only with different wording so it's more D&D, of course). And after long enough a consecutive streak/habit mastery maybe suggest that this is established and can now be taken out of the game? It's probably not the worst idea to have a quick look at some psychology regarding habit establishment for the timeframes for that.

Oops, wall of text.

**Comment by hjalmberi** [comment]
@wc8 Yep, Consecutive Completion Bonus is it. You seem to know everything about trello, do they already have 'redden long unclicked habit' somewhere?

@wildcate Unfortunately this applies only to people who can wire their brains after 30 days of doing the same thing. I always end up with coming home one day, crushing to bed and all the useful stuff I was supposed to do gets forgotten. Concerning pshychology I must have hit my head as a kid :|

**Comment by wildcate** [comment]
@Hjalmberi I've done some quick websearch and skimmed a few things; there is a study about making new habits that says on average, a simple small habit was formed after 66 days, though the complete timespan needed until it was as habit-y as it would get was between 18 and almost 300 days. And consecutive repetition in the early stages seemed to help form it. As does establishing firm cues (right after breakfast, before going to bed, just before lunch,...) So you are definitely not an oddity if you need longer than 30 days  ;)

So how about asking the user after 3 months whether it's still needed or not? Then you could still decide you want to keep it on the list - or remove it and make space for something new.

**Comment by hjalmberi** [comment]
@wildcate that's interesting stats, thanks!
Asking users is fine if it will be possible to keep everything in piece in one click :)

**Comment by wc8** [comment]
@Hjalmberi check out 
[Shading on +/- only Habits](https://trello.com/c/YSXfecBt). 

> Never/Frequently clicked (-) shaded green
> Never/Frequently clicked (+) shaded red

**Comment by wc8** [comment]
Hm... how about something like this:

Day 2 (in a row): .1 GP bonus
Day 3: .2 GP
Day 4: .3
Day 5: .4
Day 6: .5
Day 7: 1 GP + 1 week Achievement Badge
Day 14: 2 GP + 2 week Achievement Badge
Day 21: 3 GP + Achievement Badge
Day 28: 4 GP + Achievement Badge
Month 2: 5 GP  + Achievement Badge
Day 66: Mastery Badge 1 and dialog suggesting moving it to your Achievements page.
Month 3: 5 GP 
Month 4: 4 GP 
Month 5: 3 GP
Month 6: 2 GP  + Half Year Achievement Badge
Month 7: 1 GP
Month 8: .5 GP
Month 9: 3rd Quarter Achievement Badge
Day 300: Grandmaster Achievement Badge
Day 365: 10 GP & Achievement Badge

I don't know if HabitRPG could keep track that long, but if you did manage to complete a daily task every day for a year, that might be worth some commendation, depending on the task.

**Comment by wildcate** [comment]
@wc8: That, I think, is seriously cool. I'd love that!

Would that work for "daily" tasks that are not performed on every single day as well? Or just for "true" dailies? Restricting it to true daily tasks might make users stretch a little more, while adding something like "workday dailies" also provides incentive to not slack on the almost-daily tasks. I have a few things that I don't do on the weekend, since they are work tasks and I like to have the weekend off. But giving a weekly achievement badge on a daily task only performed on, say, Thursday, would be sort of ridiculous.
Would it possible (at some later time, perhaps) to implement the bonus for 5+ task performance days out of the week? That would mean workday tasks would still get commendation for being done in a row, and week achievement badges are sort of still meaningful for them.

**Comment by PhilipHow** [comment]
@wc8's thing looks good, I like it!

Achievements are powerful in that way, as long as they're properly advertised. I think the bonuses for consecutive dailies (habitstreaks?) should be displayed when you get them, to show that you're getting the bonus!

@wildcate: regarding achievement badges how about a fraction of the number of days selected? So you would get 1 /7 or 2/7 Monthly/Quarterly/Yearly badges, and 3+/7 Weekly badges (say, if I run every other day or something). This could scale with the number, so the reward for getting a Weekly 7/7 would be more for getting a Weekly 6/7.

**Comment by wildcate** [comment]
Yes to displaying the bonus prominently so that it makes one itch to see how much more, and what, bonuses will come in the future.

@MrConcept: I'm not sure I get what you are suggesting. So if I run every other day, it would mean that I have to run for 2 weeks to get the one week achievement badge? That sounds kinda weird for me, especially if the bonuses give you some popup saying "You have done this for one week in a row - take this badge and wear it proudly!". Also, that same scaling for something done once a week would mean you get the Grand Master achievement after 7 years without having missed a single week...

This is why I thought that it might work for 5+ days per week. But maybe it's easiest (and an added incentive) to have this only for tasks done every day without exception. That would also make it more special in a way.

**Comment by hjalmberi** [comment]
@wc8 that's a plan!

**Comment by PhilipHow** [comment]
@wildcate I mean separate each achievement, so the 1/7 achievement is different from the 2/7...3/7 etc,but it doesn't make sense to award a 1/7 every week. This sounds complicated, but it makes sense, the general message would be the same "You've Completed Your Dailies for X Weeks" etc... but the reward would scale with how many days out of the week you had set it to.

But yeah it is probably easiest to keep it simple. How about just a simple extra gold bonus for keeping your Daily streak, and then special achievements for long periods of 7/7 and perhaps 5/7.

**Comment by wc8** [comment]
@MrConcept what do you have in mind by long periods of 7/7 and perhaps 5/7?

**Comment by PhilipHow** [comment]
1 Week, 2 Weeks, 3 Weeks
1 Month, 2 Months, 3 Months, 4 Months.... etc
1 Year, 2 Year etc

**Comment by horusofoz** [comment]
@MrConcept [Priority Multipler?](https://trello.com/c/4C8w1z5h) should cater for your idea. 

This would include a minimum reward for each priority level. If the daily task was achieved in conjunction with other dailies on the day, the user would receive a proposed "streak" award. 

If a task of priority 2 or 1 level was completed consecutively on X number of days they would also receive a badge for it.

Can you confirm you are happy with this?

**Comment by PhilipHow** [comment]
@horusofoz Apologies, the fractions /7 refer to the number of days out of the week you have the "Daily" selected to!

**Comment by Pandoro** [comment]
Ooof long thread, I find it hard to judge if this is active or not. Several of these ideas are already votable on trello. 

The discussion here seems to have died a little, do we need to keep this open, or are you guys discussing on trello already :) ?

**Comment by wildcate** [comment]
I think the discussion has died down because it has been moved to trello and no one objects to how it's listed there : )

**Comment by Pandoro** [comment]
Great :D Then it is time to get it cleaned up here :) Thank you for the help @wildcate !
