### ISSUE TITLE
Watch for beastMaster

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4465]
@negue this is a performance question for you.

[There's a $watch on the number of pets](https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/notificationCtrl.js#L107-L114), it gets called every time a new pet is hatched. It looks like this:

```
    $rootScope.$watch('user.items.pets', function(after, before){
      if(_.size(after) === _.size(before) ||
        Shared.countPets(null, after) < 90) return;
      if (User.user.achievements.beastMaster == false) {
        User.user.achievements.beastMaster = true;
        $rootScope.openModal('achievements/beastMaster');
      }
    }, true);
```

Would it be better to take out the watch have this pet counting function in [the inventoryCtrl, and have it get called by $scope.hatch()](https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/inventoryCtrl.js#L80-L87)? Or would it not make much of a difference? Or would it be worse?

I ask because I'm working on the mountMaster achievement PR and right now, it's basically a duplicate of the beastMaster so, the way it is now, that would result in another `$watch`.

**Comment by negue** [comment]
I think moving this code to $scope.hatch() would be better either way.

For the performance part:
- the $watcher of user.items.pets would be only executed if you re-set the pets array, which would be only on sync.

If we stick to this code then we should use $watchCollection instead of $watch

Last time I checked I had about 6000 (or more, cant remember) watches, so 1 more isnt that big of deal yet :D

**Comment by crookedneighbor** [comment]
Thanks for the input. I'll refactor it in the mountmaster branch.
