### ISSUE TITLE
NPC Ian Fixed location for Quests on Android App

### ISSUE THREAD

**Issue by joshbDev** [HabitRPG/habitica#4467]
just browsing the android app (on the Moto X if that helps) I noticed that if I click a quest to preview it NPC Ian's character stays in the same place even while scrolling. Attaching a couple of screens
![screenshot_2015-01-01-20-59-29](https://cloud.githubusercontent.com/assets/5234453/5594322/07978896-91fc-11e4-87ee-2069e30d9d2f.png)
![screenshot_2015-01-01-20-59-52](https://cloud.githubusercontent.com/assets/5234453/5594323/0797c158-91fc-11e4-94c6-ba4b31cf2ae7.png)

**Comment by Alys** [comment]
I'm closing this because we are working on a new, native app for Android which will be an improvement over the current one. It's not finished yet but is close. We're still updating the old Android app for critical bug fixes, but for display problems like this one, it's better than we leave it as it is for now and focus on the new app. I'm sorry for the inconvenience and thank you for reporting this.
