### ISSUE TITLE
replace "off-hand" with "shield-hand" in equipment descriptions

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4472]
There was a question in the wiki about what "off-hand" means in "Mustaine's Milestone Mashing Morning Star (Off-hand Weapon)". They thought it might mean that it could be used even when both hands were occupied with weapons and shields (not unreasonable really, given the usual meaning of "off").

A google search for "off-hand" alone doesn't return anything on the first page about the left-handed meaning. A search for "off-hand weapon" returns results but mostly from gamer sites, which makes me think it's not a common term outside gamer circles and hence is probably confusing to non-gamers and perhaps ESL people.

Can we change it to either "left-hand" or "shield-hand"?  @lemoness What do you think?

All places where it's used are:

```
gear.json:  "offhand": "off-hand item",
gear.json:  "shieldBase0Text": "No Off-Hand Equipment",
questsContent.json:  "questGoldenknight3DropWeapon": "Mustaine's Milestone Mashing Morning Star (Off-hand Weapon)",
```

And FYI only (not to be changed), the "offhand" string is used here::
_public/js/controllers/inventoryCtrl.js:      var string = (type == 'weapon') ? window.env.t('weapon') : (type == 'armor') ? window.env.t('armor') : (type == 'head') ? window.env.t('headgear') : (type == 'shield') ? window.env.t('offhand') : (type == 'hatchingPotions') ? window.env.t('hatchingPotion') : (type == 'eggs') ? window.env.t('eggSingular') : (type == 'quests') ? window.env.t('quest') : (item.key == 'Saddle') ? window.env.t('foodSaddleText').toLowerCase() : type;_

**Comment by SabreCat** [comment]
I like "shield-hand", in the odd event that someday we have sprite flip functionality for people to have left-handed avatars!

**Comment by crookedneighbor** [comment]
:+1: for shield-hand.

**Comment by lemoness** [comment]
I like shield-hand too.

**Comment by nataliechan** [comment]
Newbie here: a search for gear.json within the habitrpg repo gives a whole bunch of files (./node_modules/habitrpg-shared/locales/sv/gear.json, ./node_modules/habitrpg-shared/locales/de/gear.json, ./node_modules/habitrpg-shared/locales/es/gear.json, etc). Does that mean I need to edit the string within all those files (maybe just using a search-replace?). Also, since this is a string change, does that mean I need to clone the habitrpg-shared repo as well and change things there, or no? I'm a bit confused because there's a habitrpg-shared within my ./node_modules folder, but that's in the habitrpg repo and not a separate one.

**Comment by deilann** [comment]
Only edit the English files. Yes, you will need to clone the shared repo.
There's a section in the Guidance for Blacksmiths page called "Working with
HabitRPG-Shared" that you should read.

**Comment by nataliechan** [comment]
Hi again. uhm. I followed the instructions on the Guidance for Blacksmiths page, then made changes, then committed and pushed the code, which showed up in the habitrpg-shared repo. I'm fairly certain that's all I had to do, because my limited github knowledge says pull requests are only necessary if I'm on a branch that isn't upstream (which I'm not capable of doing), so... please let me know if I've done something wrong that I'll need to fix?

**Comment by deilann** [comment]
But you're not on the upstream branch? You definitely do need to do a pull
request.

**Comment by nataliechan** [comment]
Oops, sorry about that - I think I just tried to create the request too early or accidentally tried to create a PR in the habitrpg repo instead of in the shared. Thanks for the clarification!

**Comment by deilann** [comment]
No problem! I looked at your commit and it's all good, so once the PR is
sent, it should be merged. :)
