### ISSUE TITLE
Consecutive counter rolls on the 1st, not on billing period

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4475]
Got some emails pointing out: the consecutive month counter (the point in code which also grants Mystic Hourglasses, Gem Cap Bonus, etc) checks on the 1st of the month, _not_ each start of their billing period. 
##

**Comment by kimbellina** [comment]
Hello! On March 31, I was emailed the receipt for my 3rd consecutive month via the recurring subscription plan. As of April 2, I haven't yet received a mystic hourglass, and my settings page shows "Consecutive Months: 2". I've attached a screenshot of my inbox to show the three consecutive month receipts:

![screen shot 2016-04-02 at 8 04 00 am](https://cloud.githubusercontent.com/assets/6069617/14226219/7de031e6-f8a9-11e5-9d21-fd2679f93dde.png)

I expected to receive the hourglass upon _paying_ for my third month, since paying for a full year provides you with 4 hourglasses immediately. I also expected that my gem cap would increase at the same time.

I signed up for the subscription on January 31 at 7:04PM EST. If the servers are configured to UTC, it would have been 12:04AM on February 1, just after the month/day boundary. Is it possible this is why my subscription is calculated incorrectly? (i.e., There may be a bug for all users who subscribe on the last day of the month in _their_ time zone when the servers have already passed the day boundary.)

**Comment by Alys** [comment]
@kimbellina When you buy a month by month subscription, you get the Hourglass and increased gem cap at the end of every three-month period. Yours will arrive around the end of April. If you'd like to read more about the benefits, the wiki's [Subscription](http://habitica.wikia.com/wiki/Subscription) page has a lot of detail. Ask again in the Tavern or at Help > Ask a Question or here if you have further questions. If you'd like to make feature requests for subscription changes, I think this would be the correct Trello card: https://trello.com/c/euDUHPpn/371-subscription-basic-plan
