### ISSUE TITLE
purchased background set, but it charged me individually (two months running)

### ISSUE THREAD

**Issue by kb-code** [HabitRPG/habitica#4487]
it happened again... both this month and last, when I went to purchase the bg set for 15 gems, it said it went through (this month, given last month's experience, I even made sure to wait for the blue bar to go completely across before setting a bg), but then a moment later, my bg changed back to prior one, and when I went to change it to new one again, I saw that it had registered my bg purchase as individual ones, and some were still locked.  When it happened last month, I just bit the bullet and purchased each individually for 6 extra gems, but this month, I really wanted to gift 7 gems to a party member who is not a subscriber so they can sport a new bg, and this is getting kind of "expensive" to pay 6 extra gems each month.  :(  

Happened once before back with spooky skin colors set, due apparently to server memory leak errors (that is what I was told here during resolution), and that time I was able to get a gem supplement to purchase all colors at no net gem loss.  Is it possible to have this done?   (ie restore the extra 6 gems so I can purchase each bg individually without net loss)

Also, is there anything I could be doing wrong to cause this?  I truly don't wish to make this error occur again!  Thanks for your assistance! 

UID: cf1ba132-f177-4865-a6b6-d16bcb89e5c0

**Comment by taldin** [comment]
I'm not a dev, but I didn't have a problem purchasing a background set this month or a couple of months ago.   Can you tell us what your HabitRPG setup (hardware/software operating system) is that you were using when this happened?

**Comment by kb-code** [comment]
hi taldin,

sure, I'm using HP Envy 15 with Win8 4 gb ram.  Internet over wireless
hotspot (which admittedly even with 4g will lag sometimes on hRPG page.
However, I don't think this would cause it, because if the signal was down,
then it shouldn't have registered the purchase at all, instead of
registering whichever ones I had clicked on before the page refreshed/reset
back to old bg).  I haven't had this problem with any other purchases
beyond the ones mentioned, and I have purchased pretty much everything/set
ever made available in the game.

Really didn't even think too much of it last month.  Chalked it up to the
internet connection doing something funky.  When it happened again this
month, combined with a random day last month when my costume time-ported
backwards a week in time, I figured this might be worth bringing up in case
it's systemic and not just my crappy luck trying to do purchases during a
server update or something! :)  So long as I can be assured this won't
happen again, I'm not so concerned about the gems. Just don't want this to
become a regular monthly thing!

thanks~

On Thu, Jan 8, 2015 at 11:05 AM, taldin notifications@github.com wrote:

> I'm not a dev, but I didn't have a problem purchasing a background set
> this month or a couple of months ago. Can you tell us what your HabitRPG
> setup (hardware/software operating system) is that you were using when this
> happened?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4487#issuecomment-69230657.

## 

"If you have a dream, don't resist or deny it - the whole point of dreaming
is getting to try it!"

**Comment by crookedneighbor** [comment]
@kb-code thanks for the info! (and thanks @taldin for commenting, I thought this had been addressed already, but apparently not)

I just granted you the 6 gems. The next time you purchase a set of backgrounds, could you do so in the Google Chrome browser with the javascript console open? You can open it by pressing `Control-Shift-J` on your keyboard. Since this has happened to you more than once, I'd like to get to the bottom of it.

**Comment by kb-code** [comment]
okay, thank you @crookedneighbor!  Much appreciated.  And yes, I will do that next month (making a to-do right now)...

**Comment by crookedneighbor** [comment]
Helping us out and getting xp + gold for it, I like it! :+1:

**Comment by kb-code** [comment]
hi @crookedneighbor ,
wanted to check in and let you know that I followed your instructions when purchasing backgrounds this month.  Didn't have any issues at all!  However, I'm still attaching the screen shot of the javascript console, in case is it of use to you.  Thanks again for your assistance! 
![2015-02-04 23_07_30-](https://cloud.githubusercontent.com/assets/3348252/6056534/110dd106-acc7-11e4-8154-f4f6da551d05.jpg)

**Comment by taldin** [comment]
Check in again in a month!  Just in case. :)

**Comment by SharmClucas** [comment]
This has happened to me as well.  I just started subscribing this month so it's only happened once so far.   Windows 7, Firefox.  87924a34-8dd3-437d-83a0-21270e31da15

**Comment by Alys** [comment]
@SharmClucas Can you please tell us exactly what happened? For example, what did you try to buy, what did you end up owning (if anything), and how many gems were subtracted?

**Comment by SharmClucas** [comment]
I bought the February 2015 set last week.  I don't know exactly how many gems were subtracted, I wasn't paying close attention.  I thought it was 15 but it could have been 14.  I definitely clicked on "unlock set" when I purchased it.  I thought that it unlocked all three originally, but I'm not 100% positive.  I've been using the last one and only tried to use the first one in the set yesterday and realized it was locked.  At the moment I have the last two but not the first in the set.

I'll be unlocking the October 2014 set as soon as I have enough gems.  I'll be sure to take the steps you suggested to kb-code and post it when I do.

**Comment by Alys** [comment]
@SharmClucas Your account shows that you purchased two backgrounds individually, instead of buying the set. This means that 14 gems would have been subtracted. I'm about to give you six gems so that you can buy the final background in that set, with the total cost to you being only 15 gems. Next month, before you buy backgrounds, reload the page with your browser's refresh function to make sure you have the latest site code, then make note of how many gems you have, then click once carefully on the link for purchasing the full set, and then wait for the transaction to complete (the thin blue bar at the top of the screen should disappear before you take any other action). Make note of the new amount of gems, and examine the backgrounds to ensure that they no longer have thick grey borders. If anything does not look right, comment here before trying to buy them again. Also, if you could do all this in the Google Chrome browser with the javascript console open (press Control-Shift-J or Command-Shift-J on your keyboard), we'd be grateful. If anything goes wrong, you can send us the errors shown in the console.

**Comment by SharmClucas** [comment]
Did what you asked, and nothing seems to have gone wrong.  I'm not really surprised though, the whole site seems to be working more smoothly in Chrome.  Do you want me to purchase my next set in Firefox and see if it's a browser problem?

**Comment by Alys** [comment]
@SharmClucas If you are willing to go to the extra trouble, I would certainly be interested in the results of that test! Thank you! But don't feel obliged to. :)

**Comment by SharmClucas** [comment]
I don't mind as long as I can get the gems back if it fouls up.  It'll be a bit though, I'm almost out of purchasable gems for the month and I've spent the ones I've already earned. ^_^;

**Comment by Alys** [comment]
You would certainly get your gems back.
