### ISSUE TITLE
Integrating Pomodoro App

### ISSUE THREAD

**Issue by mlivits** [HabitRPG/habitica#4492]
I saw in the wiki that a pomodoro app can be integrated with the habitrpg app.  Unfortunately I am completely ignorant about coding. Would it be possible to create a video tutorial about how to go about integrating the app with habitrpg?

**Comment by Alys** [comment]
This is probably better sent to the creator of the integration tool, or at least to our Trello feature request board, but for now, please paste in here the URL of the wiki page that you saw this on. I'll have a quick look at it and then give you better advice.

**Comment by mlivits** [comment]
Thanks for the prompt response! I also contacted the creator before bothering you guys but have not received a response.  

This is what I'm talking about:
http://habitrpg.wikia.com/wiki/Ugo_Landini%27s_Pomodoro
http://habitrpg.wikia.com/wiki/The_Keep:Webpage_and_Pomodoro
http://habitrpg.wikia.com/wiki/The_Keep:Installing_Ugo_Landini%27s_app

I contacted the guy who wrote this but got no response: 
http://ryandeussing.com/blog/2013/07/14/i-made-pomodoro-dot-app-post-to-habitrog-and-so-can-you/

And thanks again for your hard work.  I really enjoy this app.  I am an attorney by the way, is there a way I can contribute my work?

**Comment by Alys** [comment]
I think a video tutorial probably won't help as much as you'd hope because a large part of the integration seems to be just copying and pasting the curl command with your [Unique User ID and API Token](https://habitrpg.com/#/options/settings/api) in it. What you might like to do is post to our [Wiki Trello board](https://trello.com/c/X2YPckSn/17-submit-your-suggestions-for-the-board) to ask if a wiki editor can merge those three pages into one and make the instructions clearer. You could certainly also ask for a video tutorial, but please keep in mind that video tutorials can take a lot of work to put together, so it is possible that none of our volunteers will have time to do it. Hopefully you'll find that if the instructions are tidied up, then they will be easier to follow. In the meantime, you can do a manual integration by creating a Habit that you click each time you complete a pomodoro. That's basically what the integration does, from what I can see at a quick glance.

**Comment by crookedneighbor** [comment]
Note, the curl command listed on the wiki and the blog post is using version 1 of the api, not version 2 (the current version).

**Comment by Alys** [comment]
We've modified our pomodoro content on the wiki since this was posted, so I'm closing this, but if the instructions still aren't clear, let us know.
