### ISSUE TITLE
Color-only based visuals are unhelpful

### ISSUE THREAD

**Issue by mjtamlyn** [HabitRPG/habitica#4493]
I have color blindness and the emphasis on colour with no icons for the goodness of a task is unhelpful. Because I see the world in different colours to normal vision, the gradient from red to yellow to green is very muddled and it's not immediately obvious when something gets "more green".

For the sake of clarity - I have no problem using color, referring to completed things as grey, overdue as red etc - it's simply a case of having a visual clue so I don't have to think (or resort to inspect element!).

**Comment by deilann** [comment]
I'm colorblind as well and have brought this up as an accessibility issue in the past. Currently, the way I accurately gauge task "goodness" is by using Alys' [Data Display Tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html).

The grey is actually an issue for me because I have a tritanomaly, so it's difficult to distinguish between the blues and the grey. I'd really like folks to be able to set their own colors. However, as this isn't really a technical problem and more of a feature problem, we've been looking at accessibility issues on Trello -- you can see some of the discussion [here](https://trello.com/c/pxTcbKuD/381-accessibility-settings)
