### ISSUE TITLE
Dailies still unchecking before cron  -- possible sync errors

### ISSUE THREAD

**Issue by arajg** [HabitRPG/habitica#4503]
Hi, still having issues with Dailies resetting/not saving. Lost a lot of health last night in a boss fight because a bunch of dailies got unchecked before Cron. Happened on a mac using google chrome.

**Comment by Alys** [comment]
Dailies becoming unchecked before cron is most likely due to information from your browser (or mobile app) not being sent correctly to HabitRPG's server. Have a look at the wiki's [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors) page, in particular the sections called "How to Minimise Sync Errors" and "Completing most/all Dailies but still losing health and streaks".

The "How to Minimise Sync Errors" section has a few tips for preventing these problems. Could you please try them every day for several days in a row and see if that fixes the problem with Dailies becoming unchecked? Be sure to tell us if using them consistently does not help!
