### ISSUE TITLE
Error handler for failed sever calls never executed

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#4528]
This is for @lefnire 

When a request end with an error (either on the server or because of a lack of connection) it pass through [an interceptor](https://github.com/HabitRPG/habitrpg/blob/develop/public/js/app.js#L232)

At the end of it we [return the response](https://github.com/HabitRPG/habitrpg/blob/develop/public/js/app.js#L265). This causes it to be handled by the [succcess handler](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/userServices.js#L72) and the [error handler](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/userServices.js#L123) with its logic is always ignored.

There's a comment at the end of the interceptor about why we don't reject the response (and thus always ignore the error handler):

> ```
>        // this completely halts the chain, meaning we can't queue offline actions
>         //if (canRecover(response)) return responseOrNewPromise
>         //return $q.reject(response);
> ```

I couldn't find out what does it mean that it halts the chain but I suppose there's a good reason for it, so while we can still return the response instead of rejecting it what about moving the error handler logic to the `responseError` interceptor or to the success handler?

``` js
            // (Notifications handled in app.js)

            // If we're offline, queue up offline actions so we can send when we're back online
            if (status === 0) {
              //move sent actions back to queue
              _.times(sent.length, function () {
                  queue.push(sent.shift())
              });
              settings.fetching = false;
            // In the case of errors, discard the corrupt queue
            } else {
              // Clear the queue. Better if we can hunt down the problem op, but this is the easiest solution
              settings.sync.queue = settings.sync.sent = [];
              save();
            }
```

I would say that this is causing a few error when working offline but I'm not sure so if there's something I missed tell me

**Comment by lefnire** [comment]
God our repo is ugly. Sorry world. Anyway, investigating

**Comment by lefnire** [comment]
I'm a bit lost in code. I'm showing:
- I updated the _website_ [Jun 11](https://github.com/HabitRPG/habitrpg/blame/develop/public/js/app.js) to conform to Angular update.
- You updated _mobile_ [Sept 29](https://github.com/HabitRPG/habitrpg-mobile/blame/master/scripts/app.js) (message "final touches")

There's quite a few difference between the two blocks of code, we'll probably want to consolidate them into habitrpg-shared. Anyway, the code you're referencing in this post is regarding website/app.js, not mobile/app.js. It doesn't matter actually, since the main point of concern is the end `return response`. I'll look into that now, just thinking out loud.

**Comment by lefnire** [comment]
@paglias _great_ find! This is definitely why offline isn't working. As I recall, `$q.reject(response)` caused the chain of listeners to halt there in a previous version of Angular; where `return response` would continue to propagate to listeners, including whether or not the response is a success or error. It must be that since Angular 1.3, that had been fixed and everything works as expected. Sure enough, when I uncomment `//$q.reject(response)`, everything works the way it's supposed to. I think that's the solution, unless you have other opinions!

But yeah, we'll want to get these consolidated & merged into habitrpg-shared somehow, tough to maintain in two locations

**Comment by lefnire** [comment]
`$q.reject(response)` back in. Refactored mobile + web => shared. Closing now, @paglias if you get a chance could you double check it works for you on local - if not, re-open

**Comment by paglias** [comment]
@lefnire working perfectly :) I'm going to deploy with this change
