### ISSUE TITLE
Lost HP twice in a quest

### ISSUE THREAD

**Issue by zoli90** [HabitRPG/habitica#4532]
(i couldn't find this issue submitted, I hope this isn't a duplicate)
I was participating in a quest(moonstone pt. III) and I checked in to the inn yesterday. This morning when I refreshed the website(I only suspend the laptop without closing Firefox for the night) I lost some HP because of a party member. Then I went to the inn to check out. I pushed the button before the world boss quest was loaded and went to the party page. This is when I've noticed that I was still checked in and checked out again. This is when I lost the same amount of HP again.

I only use the habitRPG website from my laptop. I had no problems with the internet connection and I got no 'application error' messages. I'm using lubuntu 14.04 and Firefox 34.0 (the about page also says 'Mozilla Firefox for ubuntu canonical - 1.0'). My UUID is 02026ad7-00c7-4b95-ae91-b060cd8a49ad the party ID is 7ae975e5-6614-498a-8364-e4668e1e4679
##

**Comment by Alys** [comment]
I'm looking at your party's data (thanks for providing the party ID!) but I'd like a little more information about what you noticed. How much health did you lose each time? How many minutes, approximately, were there between the first loss and the second?

**Comment by zoli90** [comment]
Thank you Alys! Necro-vice did 30.7 damage both times and I died after the second time(I fixed the character values after this). The time interval was probably 1 minute or less.

**Comment by Alys** [comment]
What I'm seeing in the system logs for quest damage is that one party member did 30.7 points of damage at 2015-01-17 12:07:39 and then did the same amount of damage at 2015-01-17 16:57:54. I'm not sure what timezone those timestamps are in, so the times might look really odd to you, but the point is that they did 30.7 damage twice in five hours, which might indicate some sort of cron problem with their account. 

What might have happened with you was that you used HabitRPG after both pieces of damage had been applied to the party, but you got each piece of damage separately, which isn't really supposed to happen, but we have been getting some odd behaviour lately that is sort of like this. I don't know though....

The fact that you had to check out of the inn twice is probably just because the first attempt didn't go through because the party page was still loading (normal sync error or the correct code for the check-out action hadn't been loaded yet).

I would be interested to know if any of your party members also received 30.7 damage twice within a **short** period of time, or if they received 61.4 damage at once. Also if the person who twice did 30.7 damage posts here, we might be able to work out why their damage was duplicated. 

I think it's likely that this was just a once-off glitch, so I'm hoping that it won't happen to your party again.

**Comment by zoli90** [comment]
I've asked them and I'm waiting for their reply. The 30.7 damage only shows up once in the chat and it says it happened on 2015/01/17 03:07:39
The party member told us he lost his internet connection and couldn't check off his dailies.
It seems plausible that I had to check out twice because the page wasn't loaded fully at the time when I pushed the button.

**Comment by Alys** [comment]
@zoli90 Are you certain that it shows up only once? It's definitely in the database twice. I would be very grateful if you could check, because if it is showing up only once, we have another bug. If you have time, please click "Fetch Recent Messages" and look back for 30.7 damage. If there are two messages, they should be fairly close to each other - probably just a few messages apart.

**Comment by zoli90** [comment]
Now it shows up later in the party chat the second time, but honestly, I don't remember it was there yesterday morning.

**Comment by Alys** [comment]
I'm going to close this since we didn't hear from the person whose damage was duplicated. Unfortunately without getting more information from them, there wasn't really any way we could work out what happened. If it happens again, comment here and we'll reopen this.
