### ISSUE TITLE
All account data lost?

### ISSUE THREAD

**Issue by Icemelts** [HabitRPG/habitica#4534]
I just logged on today, was informed I died despite completing my dailies yesterday, lost all of my equipment, gold, pets, and mounts, as well as my checklists and the challenges I was subscribed to? My dalies and habits have been reset to the default ones... basically, every thing on my account is gone!

User ID: 4c1506d8-7178-4189-8922-41f7a54d5748

**Comment by Alys** [comment]
You most likely have a duplicate account. If you delete it, you'll get access back to your old account, with all your tasks and everything still in it. Basically, don't worry, it's not all gone, and even if it is we could restore from back up. :)  However before you do anything, let me do a little investigation into the situation, just to check that I'm right. I'll get back to you in a few minutes.

**Comment by Alys** [comment]
@Icemelts I can see that the account with the user ID you gave us uses a facebook login. Do you normally log in with facebook, or have you used a username and password in the past?

**Comment by Alys** [comment]
@Icemelts Okay, I've done some digging. The account for user ID 4c1506d8-7178-4189-8922-41f7a54d5748 was created about a year ago and uses facebook login. It's hardly been used, so I'm guessing you created a different account in the past and have been using that one (not using facebook login).

I recommend deleting the account that uses facebook login right now, so that it can't confuse the situation again in future. To delete it, please go to Settings -> Site, scroll down, and use the red "delete" button.

Your other account will use a user name (or email address) and a password. If you can remember what they are, you can log in as soon as you've deleted your facebooky HabitRPG account. If you can't remember what they are, I can track it down for you but I would need to get more information from you - we can talk about that if needed.

**Comment by Icemelts** [comment]
@Alys OH! Haha, you're right! Wow, I feel a little silly, that worked, thank you!

**Comment by Link000** [comment]
Not sure if this is the right place for this, but the community guidelines seem to imply I should post this under this existing thread. So for the basic overview, my account says I died, but everything (including tasks, dailies, etc) has reset to day 1 (I have even had a tutorial again).  I even am no longer in the party I created according to my account, but my other party member I am fighting the boss with says I am still there at level 6.

I originally had issues with the android app today, and eventually reinstalled it. Everything was okay on my PC (I use a Firefox browser), but after I logged out, sent a password reset request so I could log into my android app (since I have forgotten it), and came back only to be informed that I "died."  I am fighting a boss with my party member, but they still see me on the boss fight at level 6 with everything.  In other words, my other party member is fine, but I somehow "died" even though I have kept up with my dailies, and should still have 35-ish health.

If it helps, I am seeing now is the introduction tutorial, a complete reset of all my tasks (to the original default--I have none of my own there any longer), and the party I originally created is no longer on this account. In other words, I have (in essence) been rest to day 1.  Now, if I died, then perhaps I did die--but I find it odd that I no longer have any of the task lists that I set up nor am I in the party I originally created.  Is this normal, or did I somehow inadvertently create a 2nd account on the same email when resting my password (I only have used email, and never used a facebook login)?  Can someone please help me understand what's going on here???

My user ID (at least the avatar/character I have now) is: 13a0dd5f-a883-4d13-af8e-92fffad0ca05

Thanks!

**Comment by deilann** [comment]
"or did I somehow inadvertently create a 2nd account on the same email when
resting my password (I only have used email, and never used a facebook
login)? Can someone please help me understand what's going on here???"

Yes. Delete the new account and ask for a password reset again. See if that
helps.

**Comment by Link000** [comment]
Looks like it did not work. It keeps taking me back to level 1, with everything completely reset followed by a tutorial. Is this normal? (Sorry, I seemed to have accidentally deleted my original message).

**edit by admin -- here is Link000's original message**

Not sure if this is the right place for this, but the community guidelines seem to imply I should post this under this existing thread. So for the basic overview, my account says I died, but everything (including tasks, dailies, etc) has reset to day 1 (I have even had a tutorial again). I even am no longer in the party I created according to my account, but my other party member I am fighting the boss with says I am still there at level 6.

I originally had issues with the android app today, and eventually reinstalled it. Everything was okay on my PC (I use a Firefox browser), but after I logged out, sent a password reset request so I could log into my android app (since I have forgotten it), and came back only to be informed that I "died." I am fighting a boss with my party member, but they still see me on the boss fight at level 6 with everything. In other words, my other party member is fine, but I somehow "died" even though I have kept up with my dailies, and should still have 35-ish health.

If it helps, I am seeing now is the introduction tutorial, a complete reset of all my tasks (to the original default--I have none of my own there any longer), and the party I originally created is no longer on this account. In other words, I have (in essence) been rest to day 1. Now, if I died, then perhaps I did die--but I find it odd that I no longer have any of the task lists that I set up nor am I in the party I originally created. Is this normal, or did I somehow inadvertently create a 2nd account on the same email when resting my password (I only have used email, and never used a facebook login)? Can someone please help me understand what's going on here???

My user ID (at least the avatar/character I have now) is: 13a0dd5f-a883-4d13-af8e-92fffad0ca05

Thanks!

**Comment by deilann** [comment]
Can you ask your friend in the party to pull up your user ID for your
actual account? They can find it by clicking on your picture.. it's in your
profile.

**Comment by Link000** [comment]
Here's the ID according to my profile they pulled up: 474e6783-b379-4b8d-b842-1dfd8b1ab6eb

**Comment by deilann** [comment]
What is the ID for the profile you're seeing on your computer?

**Comment by Link000** [comment]
Now that's just weird, I logged back into my account, and now have my Level 6 character. Everything's there!

But as you asked, the number is now 474e6783-b379-4b8d-b842-1dfd8b1ab6eb (different from what it was for the level 1 account:  13a0dd5f-a883-4d13-af8e-92fffad0ca05)

**Comment by Link000** [comment]
I'm not exactly sure what happened, but I seem to have my account back with everything there! I just tested my account on my Android and everything is there and working great.

Thank you for all your help--I really appreciate it! :)

**Comment by Alys** [comment]
FYI for other admins: I looked into @Link000's duplicate account problem and discovered that the duplicate account (13a0dd5f-a883-4d13-af8e-92fffad0ca05) has already been deleted.

**Comment by ghost** [comment]
I have the same problem here. I tried delete my "new account" and nothing is happened when I sign in again. My old account (which I registered with my facebook) is still lost :/

My original ID is d0e8790d-35a2-49aa-8a31-2a752e7ec31a, my new one is 5d2ced52-04a3-4e00-bf0e-78bc91a0a222

**Comment by Alys** [comment]
@zumbibs There's no account with the User ID 5d2ced52-04a3-4e00-bf0e-78bc91a0a222.

The d0e8790d-35a2-49aa-8a31-2a752e7ec31a account has several tasks in it. It doesn't use facebook authentication; it uses your email address (z....@g.....). You can enter that email address in the "forgot password" form to receive an email with your username and password. Comment here if you need more help.

**Comment by ghost** [comment]
@Alys thank you so much! Seriously, thank you sooo much! It's alright! :)
