### ISSUE TITLE
Server Heavy Load

### ISSUE THREAD

**Issue by PiNotEqual3** [HabitRPG/habitica#454]
I get this error _a lot_: "The server is under heavy load or is experiencing issues."

Not sure if this is related to [memory leaks](https://github.com/lefnire/habitrpg/issues/165) or simply new bugs from new features or what ever. Anyway all of my friends left habitrpg because it is incredible unstable.

I know there is a lot to do right now but I think the over all **top priority** should be a stable server. Maybe a new big server or separate beta server would help?

**Comment by horusofoz** [comment]
@PiNotEqual3 We appreciate your feedback. The aforementioned memory leak is the cause of your issue. 

This is an issue our code monkeys are investigating on a daily basis. We assure you every effort is being made to resolve this ASAP. 

Add yourself to the watch list for the GitHub ticket you referenced to be informed as the issue is updated.
