### ISSUE TITLE
sprite image glitches when site images are updated -- css not updating at same time

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4542]
This issue is so we can discuss solutions for the common problem of image glitches every time the sprites change. If anyone has any suggestions, or wants technical information about the problem so that they understand it better, comment here!

**Comment by crookedneighbor** [comment]
So, as I understand it, the problem is that a new concatenated and minified version of the css is getting created whenever the grunt task for production is run, but if someone is on the site when it gets deployed, they'll be using an old version of the stylesheet (since the html file never got refreshed to point to the new version), but new versions of the sprite sheets, resulting in misalignment of the background positioning.

It's not even that the browser is caching the old one (thought that could be a factor too), but that the site is just pointing to the wrong css file.

Is there an easy way to require a refresh after a deploy?

**Comment by paglias** [comment]
If you're already on the site you shouldn't have already downloaded the
sprite sheets?
Il 28/gen/2015 22:46 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by thepeopleseason** [comment]
Timestamp/version the name of the css and spritesheets?

**Comment by paglias** [comment]
It's versioned at each deploy, an hash of the file is calculated and the
file renamed accordingly
Il 28/gen/2015 22:49 "James Hsiao" notifications@github.com ha scritto:

**Comment by crookedneighbor** [comment]
@paglias I suppose that's correct. Is it just a caching issue then? The browser is holding on to one and not the other?

**Comment by crookedneighbor** [comment]
@paglias are the sprite sheets hashed as well? I didn't think they were.

**Comment by paglias** [comment]
I think so...
Il 28/gen/2015 22:52 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by paglias** [comment]
Mmm... The sprite sheets I don't know
Il 28/gen/2015 22:54 "Matteo Pagliazzi" matteopagliazzi@gmail.com ha
scritto:

**Comment by paglias** [comment]
Yeah they are according to the grunt file. It seems an intermittent issue,
myself for example I never got it
Il 28/gen/2015 22:54 "Matteo Pagliazzi" matteopagliazzi@gmail.com ha
scritto:

**Comment by crookedneighbor** [comment]
You're right, they do get copied and renamed in the grunt file, but the stylesheets still use the regular files, right? Did inspect element and the class is pointing to this image: https://habitrpg.com/bower_components/habitrpg-shared/dist/spritesmith4.png

**Comment by paglias** [comment]
On prod? Ok, I'll check it out tomorrow
Il 28/gen/2015 23:00 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by crookedneighbor** [comment]
Yeah, I checked it on prod.

In order for the image has technique to work, wouldn't we need to update the image url that `grunt sprite` generates in the stylesheets?

**Comment by paglias** [comment]
Yeah and cssmin in grunt does this (rewrite the URLs) but it's run after
cssmin so will target files not renamed.

I'm wondering how we can have had this for such a long time. Totally my
fault :facepalm:
Il 28/gen/2015 23:17 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by paglias** [comment]
@crookedneighbor giving a better look at this the sprites aren't renamed at all. Running ``grunt build:prod` doesn't rename them because they are not copied to the build directory so they are seved telling the browser not to cache them. And indeed if you open the network tab it shows that their max age is 0.

And also my previous comment was wrong, their path inside the css would be updated but it isn't because they are not in the right directory.

This happened when we splitted the sprites in multiple files because the code in Grunt is set to copy as if there was only one:

```
          {expand: true, cwd: 'public/', src: 'bower_components/habitrpg-shared/dist/spritesmith.png', dest: 'build/'},
```
