### ISSUE TITLE
Can't do quests anymore

### ISSUE THREAD

**Issue by netman42** [HabitRPG/habitica#4553]
This has been annoying me for some time but it's probably my lack of knowledge on it 
but at one time I could do quests and now I can't. I keep buying more quests every now and then but it never shows up. It takes my gems but nothing happens. I was intending to do them solo as I did before but it never works. I also have tried many times to get into other parties but I never get added. Maybe they are related? It's probably something I'm doing wrong. I would like to do more with this aspect of the game however but haven't been able to. I use the website and ios mobile app as well.
Can you help me?
Thanks,
Netman42
userid 9973a170-542e-4a6c-9b99-33875db7a5f8

**Comment by crookedneighbor** [comment]
This is interesting. Here's the party info from the uuid:

```
"party": {
    "current": null,
    "invitation": null,
    "quest": {
      "key": null,
      "completed": null,
      "progress": {
        "up": 73.98665060566218,
        "down": 0,
        "collect": {}
      }
    }
```

Seems to think @netman42 is on a quest currently, with a key of `null`.

**Comment by Alys** [comment]
@crookedneighbor That party json data is standard for a user who is not in a quest.

@netman42 You own about eight quest scrolls at the moment. You'll find them in your Inventory in the Market page (on the left hand side of the page where you buy them). Click one to start the quest. Does that help?

**Comment by Alys** [comment]
@crookedneighbor When I say standard, I mean, probably more or less standard. Here's the data for one of my accounts that is not currently in a quest:

```
        "quest": {
            "completed": "",
            "key": null,
            "progress": {
                "collect": {},
                "down": 0,
                "up": 0
            }
        }
```

There's differences with respect to nulls and empty strings or missing data, but not anything that looks totally wrong to me. The `key` is definitely okay.

**Comment by crookedneighbor** [comment]
Interesting. Did not realize that.

**Comment by Alys** [comment]
@netman42 I've checked your party status and you're in a party by yourself. This means you can start solo quests.

You can't be invited to other people's parties because you are already in your own party. You'd need to leave your own party before an invitation could be sent.

BUT, before you leave your party, please do try to click on one of the quest scrolls in your inventory to make sure that you can start a quest. The quest will then appear in your party page and you can abort it if you don't want to do it. The aborted quest's scroll will go back into your inventory for re-use later (reload if you don't see it).

**Comment by netman42** [comment]
I have bought several quests but they just don't show up like they used to. I left my solo group awhile back and deleted it but I couldn't get into any other parties so I thought I would go back to solo questing but nothing appears. maybe I will try another browser. using chrome now
netman42

**Comment by Alys** [comment]
@netman42 Please show us a screenshot of the entire Inventory area (left hand side) of this page: https://habitrpg.com/#/options/inventory/drops
Use your browser's zoom function to zoom out far enough to get all of the inventory items in. Something like this: http://gyazo.com/781528cb782b8a9a6cee28240a5cbc38 is what I'd like to see, although of course there wouldn't be quest scrolls in yours. I'd like to see if there's anything else odd there.

After that, we'll probably get you to use the Chrome console to look for error messages, but I'd like to see the screenshot first.

**Comment by Alys** [comment]
@netman42 Also please send us a screenshot of your party page: https://habitrpg.com/#/options/groups/party
The database is showing that you are still in a solo party and so I need to see what's being displayed for you in case there's a bug there. 

Note that if you are not in a party, you won't be able to start quests.

It would probably also be helpful if you go into more detail about what exactly happens when you try to start a quest. For example, you buy the scroll and accept the confirmation that it will take four gems, and then what do you do, and what do you see happening?

**Comment by crookedneighbor** [comment]
@netman42 Just so you know, attaching pictures via email won't upload the picture here. You'll have to click on the Github link and attach the images to your comment.

**Comment by netman42** [comment]
Here is a screenshot of the inventory:
![habit-inventory](https://cloud.githubusercontent.com/assets/10659810/5868281/3c0cad70-a275-11e4-8eea-70af9dbbec3b.jpg)

Also the party page:
![partypage](https://cloud.githubusercontent.com/assets/10659810/5868319/9d029a18-a275-11e4-900f-fd7a1b0b3702.jpg)

**Comment by netman42** [comment]
I guess I have to say my bad. I forgot I had to click on the quest again after buying it from my inventory page. I figured it was something I was doing wrong. I see the quests just fine now. Thanks for listening.
netman42
