### ISSUE TITLE
Consecutive Months Count not updating

### ISSUE THREAD

**Issue by JimMackin** [HabitRPG/habitica#4561]
It seems like my Consecutive Months count isn't updating. I have a recurring paypal subscription that was set up in November and has had 3 payments. "Consecutive Months" still shows as 1 however.

User Id: cbb3d5ce-0d66-4555-ab35-841f2d4aa7aa
Browser: Firefox 34 on Ubuntu
No console/ JS errors
##

**Comment by JimMackin** [comment]
Am I just better off cancelling and buying a block?

**Comment by Alys** [comment]
@lefnire This is probably one for you to look at.

**Comment by JimMackin** [comment]
It seems as if it's now started counting - it shows Consecutive Months: 2. However this is still incorrect.

**Comment by deilann** [comment]
Can you actually email admin@habitrpg.com about this?

**Comment by zellah** [comment]
I have the same issue. I also signed up in November. Four payments have gone through now, but my month count is at 2. The display says:

Subscribed
Recurring $5 each 1 Month(s) (Stripe)
 Consecutive Subscription
Consecutive Months: 2
Gem Cap Extra: 0
Mystic Hourglasses: 0

**Comment by JimMackin** [comment]
No response from admin@habitrpg.com

**Comment by deilann** [comment]
When did you send the email? You might try sending another, just in case.

**Comment by JimMackin** [comment]
Feb 9. I've sent another.
Thanks

**Comment by deilann** [comment]
Sorry! It must have fallen through the cracks. I'm gonna toss you some
extra gems to make up for the delay.

**Comment by JimMackin** [comment]
It's no problem. I still :heart: HabitRPG :smile:

**Comment by lefnire** [comment]
Hey there, sorry for the delay. Got the email, gonna respond here for posterity. 

Cron currently only does consecutive calculations at the [beginning of the month](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L1454), rather than the subscription's calendar day (a bug). Ie, this counter will kick 3/1/15 (rather than 2/21/15 as it should). The current consecutive count is 2 ([screen](http://gyazo.com/e7fa789d559af8c9f51f67caafce08e9)), which makes sense: 11/21 -> 12/21 (1) -> 1/21 (2), which is the current. -> 2/21 will be (3), but per the bug above that actually won't kick till 3/1. 

I'll shoot you an apology consec month for the frustrations anyway.

**Comment by paglias** [comment]
Is this still an issue?

**Comment by TheHollidayInn** [comment]
There hasn't been a report in 2 years on this issue and we have a test case for this: https://github.com/HabitRPG/habitica/blob/be60fb06350123f5e5f8ea9c5d3e8b320b6f8a04/test/api/v3/unit/libs/cron.test.js#L99 . I vote we close this until we get the report again with reproducible steps.

**Comment by Alys** [comment]
Definitely. This is also another bug I've seen no indication of for ages.
