### ISSUE TITLE
A Stern Talking To: Quest Description Incomplete

### ISSUE THREAD

**Issue by Sporax** [HabitRPG/habitica#4570]
The description of the quest in the inventory says "Checked off a - habit?"
while in the wiki the description reads "Checked off a negative habit?":
![screen shot 2015-01-25 at 7 19 49 pm](https://cloud.githubusercontent.com/assets/10322112/5891638/a3db8f26-a4c7-11e4-8fb1-ae3b9c4a18bf.png)

I believe this is entry level coding, and if so, I'd like to take it up.
The issue is the same on Chrome (on mac) and on the android app.

UUID: 9f3d765b-e2d4-411e-aa5b-08e5f6c022b2

**Comment by deilann** [comment]
The wiki is wrong, then. (One can't check off a missing habit, but one can
check off a - (minus) habit)

**Comment by Alys** [comment]
I've fixed the wiki

**Comment by Sporax** [comment]
Sorry I seem to have misunderstood the - in the description, I read it as a hyphen, not minus. There wasn't anything wrong with the wiki, I wrote missing instead of negative to begin with, so thats my fault. What I mean to say is that [- habit] when read is just a little bit confusing for regular users (even RPG ones)

**Comment by Alys** [comment]
Hmmm. Good point. "- habit" is second nature to those who are very familiar with HabitRPG but I can see what you mean now about it being confusing.

@Lemoness, we're talking about this text for the Golden Knight quest:

_"The Golden Knight has been getting on poor Habiticans' cases. Didn't do all of your dailies? Checked off a **\- habit**? She will use this as a reason to harass you about how you should follow her example..."_

Is it okay if "- habit" is changed to "negative habit"? We should possibly also change "habit" to "Habit" and "dailies" to "Dailies" for consistency with other things on the site and the wiki. What do you think?

**Comment by lemoness** [comment]
That's fine! I agree about capitalization, too.

**Comment by Alys** [comment]
@Sporax Please do go ahead with the change if you would still like to! 

Also, if you wish, while you are editing that file, you could look for any instance of "Habit", "Daily", and "To-Do" that is not capitalised exactly like that, and change them (including plurals of course). The only exception would be if the word was referring to, for example, an actual real-life habit rather than a Habit task (e.g., "I have a bad habit of biting my nails so I created a negative Habit")

"To-Do" should always be hyphenated like that.

**Comment by Sporax** [comment]
So do I have to change the - to negative for every language?

**Comment by deilann** [comment]
No, only change it in en. Do not even change en_GB. Read the read me files
for more info.

**Comment by Sporax** [comment]
<a href="https://github.com/HabitRPG/habitrpg-shared/pull/453">Changes made.</a> I assume I don't have to also change habit and daily to capitals in other files, right?

**Comment by Alys** [comment]
No, that's fine. Changing capitalisation was optional. :)

**Comment by Sporax** [comment]
I would like to do it as well.

**Comment by Alys** [comment]
That would be lovely! Thank you. :)

**Comment by Sporax** [comment]
I have a couple of questions: should the descriptions on the login page be changed as well - from _Whenever you reinforce a positive habit, complete a daily task, or take care of an old to-do_ to "positive Habit" and "To-Do", and should daily task and daily list (like in the tavern - _your daily list is frozen_) stay in lower case?

**Comment by Alys** [comment]
In the Tavern, it should be "Daily list" (because it's talking about the list of your Dailies).

For the login page, @Lemoness, could you comment? The text on that page is for people who haven't used HabitRPG and aren't familiar yet with our task types, so maybe having capitals there for Habit, Daily, and To-Do would look odd to them. (Good question, Sporax.)

**Comment by Sporax** [comment]
I changed the files: they were communityGuidelines, defaultTasks, npc, quests, questsContent, settings and tasks (all .json and under habitrpg-shared/locales/en/). While committing the files though the `git status -s` didn't identify the edited files and I had to use `git add -f {path to file}` to commit them. Now when making a pull request it says that there is nothing to compare. Am I editing the wrong files or is there something else wrong?

**Comment by Alys** [comment]
Have you done `git commit` and then `git push ....`? If not, do that. If you have, do a pull request or paste in the URL to your branch in github so that we can see what's happened. We can always cancel the pull request if needed.

Be cautious about using any force (-f) options for any software. It often means that you're doing something that is best not done. In this particular case, -f is for adding files that would otherwise be ignored git, which could result in unnecessary files being pushed to github. It's likely that no harm has been done though, especially if you added only the existing files. :)

**Comment by Sporax** [comment]
I did do that. And while doing a regular add and commit it was ignoring the files. [Here is the link](https://github.com/Sporax/habitrpg-shared).

**Comment by Sporax** [comment]
I could also just change the files in my fork of the shared repo, it seems like that would be the easier way.

**Comment by Alys** [comment]
Nothing recent has been pushed to your github fork as far as I can see. Are you sure you did `git push...`? Did it give any error messages?

While it is simpler to edit files in your fork, editing them locally is good practice for using git. If you'd like to do more advanced coding changes (we'd love you to!) then using git will be essential, so I'd encourage you to persist with it now. Once we've sorted out this problem, you'll have improved your understanding of the process, which will help you later.

**Comment by Sporax** [comment]
Ok, I tried again. `git add 'pathtofile'` doesn't really do anything, since when I used `git commit -am "message"` it says `nothing to commit, working directory clean`

**Comment by lemoness** [comment]
Let's not capitalize the login page - we're easing them into the terms ;)

**Comment by Alys** [comment]
Thanks Lemoness!

Sporax, have you done `git push` since you committed the files? If not, you need to do that before your files will show up in github. The push command is what sends the files from your local machine to your github fork. Try just `git push` at first but if it gives you any error messages you might need to add other parameters so tell us what those messages are.

**Comment by Sporax** [comment]
I used `git push`, it says `everything up to date`, no errors

**Comment by Alys** [comment]
Please do `git log` and paste the output in here. Just include the output that's initially on the screen. Don't scroll down to see more output. We want only the recent entries, and they'll be at the top of the output (i.e., on screen as soon as you've done that command).

**Comment by Alys** [comment]
Also do `git diff upstream/develop` and show us the output

**Comment by Sporax** [comment]
`git log`:
![screen shot 2015-01-28 at 2 23 30 am](https://cloud.githubusercontent.com/assets/10322112/5926939/eca126ac-a694-11e4-8454-a90d2527aaa4.png)
`git diff upstream/develop`:
![screen shot 2015-01-28 at 2 26 29 am](https://cloud.githubusercontent.com/assets/10322112/5926958/1bce5fee-a695-11e4-9e06-84abe328a039.png)

**Comment by crookedneighbor** [comment]
@Sporax could you do `git diff upstream/develop > ~/output.txt`. That'll create a file named output.txt on your desktop with the full text of the diff. You can then copy and paste it here, rather than attaching a screenshot.

**Comment by Alys** [comment]
@Sporax The problem is that you're working in the main habitrpg repo instead of in the habitrpg-shared repo. 

Do you know if you set up the habitrpg-shared repo to be a separate repository? You might have followed these instructions: http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths#8._Work_with_habitrpg-shared which would have worked.

Please do `cd node_modules/habitrpg-shared` and then do `git diff` and show us the output.

**Comment by crookedneighbor** [comment]
@Alys good eye. I totally missed that.

**Comment by Alys** [comment]
Sporax, note that we are merging the habitrpg-shared repo into the main repo, and that will probably be completed in a few weeks, maybe sooner. If you haven't fully set up the habitrpg-shared repo yet, or aren't sure if you have, you might like to wait until it's no longer necessary. However this might mean that you would have to re-do your capitalisation changes. 

After you've shown us the output of `git diff` in the node_modules/habitrpg-shared directory, we might be able to give you a better idea of how much work would be required to push your changes now.

Are you using a Vagrant local install?

**Comment by Sporax** [comment]
I deleted and reinstalled the local Habit again and it seemed to fix it, I had to redo the changes though. Pull request: HabitRPG/habitrpg-shared#456

**Comment by Sporax** [comment]
Pull request updated with changes.
