### ISSUE TITLE
Refresh bug

### ISSUE THREAD

**Issue by RakiKraki69** [HabitRPG/habitica#4587]
I noticed that there's a 'refresh bug'. As an example, when I damage a world boss, and then I want to see his current health, it still shows his previous health status(like I didn't damaged it at all). The result appears only if I refresh my browser. Also, the same thing happens with tavern and party chat. When someone posts a new message in the tavern, I see the post only If I refresh the page or log in next time when the browser is refreshed. Or, when one of my party mates levels up, I don't see his new level right away. I must refresh the page. Can this bug be fixed?

**Comment by Alys** [comment]
I believe these aren't so much bugs, but side-effects of how those features have been implemented, often to reduce server load and increase browser performance.

For example, if the header bar was to show changes in your party as soon as those changes happened, then your browser would need to be polling the database constantly to look for changes, and you would notice a decrease in the site's responsiveness and an increase in your bandwidth consumption. A compromise between that and the current system would be that party changes don't appear instantly but do appear after you take an action on the site, but even that would have some performance implications (but might still be worth while) - you'd find that each time you took an action, extra syncing would occur to fetch changes to your party mate as well as fetching your own data. This _might_ make each action slower, but might not depending on how it's implemented. There's a discussion about that at https://github.com/HabitRPG/habitrpg/issues/4235 and https://github.com/HabitRPG/habitrpg/issues/3018

For Tavern, party, and guild chat, you don't need to refresh the page. You can click the "Fetch Recent Messages" button and all new chat messages will appear, much more quickly than with a refresh.

For the quest box on the party page, I believe there isn't a way to fetch new data into it without reloading, as you say. I personally would like to see syncing of the quest information happen at the same time as fetching recent messages, but I haven't looked into how easy that would be, and whether it would noticably slow down fetching of messages.

I'm wondering if these ideas are better suggested on Trello as feature requests, but I'm definitely going to leave this issue open for a while so that others can comment.

**Comment by paglias** [comment]
Fetching the party chat should update all the party info non only the
chat, like the quest and the avatars, I think

2015-01-28 21:33 GMT+01:00, Alice Harris notifications@github.com:

> I believe these aren't so much bugs, but side-effects of how those features
> have been implemented, often to reduce server load and increase browser
> performance.
> 
> For example, if the header bar was to show changes in your party as soon as
> those changes happened, then your browser would need to be polling the
> database constantly to look for changes, and you would notice a decrease in
> the site's responsiveness and an increase in your bandwidth consumption. A
> compromise between that and the current system would be that party changes
> don't appear instantly but do appear after you take an action on the site,
> but even that would have some performance implications (but might still be
> worth while) - you'd find that each time you took an action, extra syncing
> would occur to fetch changes to your party mate as well as fetching your own
> data. This _might_ make each action slower, but might not depending on how
> it's implemented. There's a discussion about that at
> https://github.com/HabitRPG/habitrpg/issues/4235 and
> https://github.com/HabitRPG/habitrpg/issues/3018
> 
> For Tavern, party, and guild chat, you don't need to refresh the page. You
> can click the "Fetch Recent Messages" button and all new chat messages will
> appear, much more quickly than with a refresh.
> 
> For the quest box on the party page, I believe there isn't a way to fetch
> new data into it without reloading, as you say. I personally would like to
> see syncing of the quest information happen at the same time as fetching
> recent messages, but I haven't looked into how easy that would be, and
> whether it would noticably slow down fetching of messages.
> 
> I'm wondering if these ideas are better suggested on Trello as feature
> requests, but I'm definitely going to leave this issue open for a while so
> that others can comment.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/4587#issuecomment-71910352

## 

Matteo Pagliazzi - paglias.net

**Comment by RakiKraki69** [comment]
@Alys Anyways, thanks for responding. I saw that 'fetch recent messages' button before, and now I know what is is used for. If that's the case with party stats than it's okay. We'll try to do something about it.

**Comment by deilann** [comment]
I'm closing this in favor of the older https://github.com/HabitRPG/habitrpg/issues/2126
