### ISSUE TITLE
all check-marked tasks suddenly unchecked

### ISSUE THREAD

**Issue by raisa1945** [HabitRPG/habitica#4595]
hello, I experienced quite often of this.
I marked tasks done in my smartphone using HabitRPG app by OCDevel from google play.
But, when I logged in from my laptop, in the first things are fine, the checked tasks show exactly the same from the smartphone. But AFTER I reloaded 1 time, all tasks suddenly  unchecked, and my character's life substracted a lot!
Plus, my habit streaks became quite messy because I had to re-mark all of the tasks that are done once again, so my streaks are so inaccurate because of it.

This is the first screenshot. this is before I reload the page from my laptop browser.
![capture](https://cloud.githubusercontent.com/assets/10771585/5974471/89840468-a829-11e4-8087-09e44a97b99f.PNG)

and This is after I reload my browser in laptop, all tasks remain unchecked compared from first image.
![capture 2](https://cloud.githubusercontent.com/assets/10771585/5974507/f2b20b10-a829-11e4-9a43-2a83baae11cb.PNG)

I am using Google Chrome Browser on my laptop, and my smartphone OS is Android JellyBean 4.1
This is the second time occurs.

my user ID 
ca78a595-54c9-43bb-a65f-6c4ea5203333

Hope you can fix this soon . 

Thank you
-raisa-

**Comment by lefnire** [comment]
@raisa1945 were things working before, but started acting this way after a certain date? @negue any thoughts on this, could it have to do with the directive?

**Comment by raisa1945** [comment]
Here is the chronology :

A week ago I installed HabitRPG apk into my smartphone. I usually checkmark all of my task from smartphone because I rarely on laptop.

So something is bugging me, I have thoughts what if the tasks I have checked from the Apk remain Unchecked in the website ? I directly open my laptop and looking at the tasks from browser. At the first time logging in to the website, the tasks show the same as in the smartphone. But, after I try reloading the page, Things are unchecked. So this problem has been occured since I installed the apk, though.. maybe the activites somehow did not synchronized into the website? 

And a couple days ago,  I rest in the inn with 1-2 dailies unchecked. After a day, I was out from the inn. Well, on my smartphone things are going fine, the checked and unchecked dailies are still like the previos days. But after a day of out from inn and open in laptop browser, the first time opening it is fine. After reloading again, all dailies are unchecked. my char's life drained a lot and lost many exp (well because I set most of my dailies to Hard).

Do you think it is the android Apk's fault instead of the website ? 

Thanks

**Comment by negue** [comment]
@lefnire Not because of the directive.

Just now I realized that the mobile app (if reactivated from the background) doesn't trigger a full refresh of the tasks, so if you let the mobile app running in the background and you have "luck" that android doesn't stop it and you re-open the app after 2 days , you could still have the data of 2 days ago.

This could explain some of this bug :( but not all of what happened to @raisa1945

**Comment by Kaned1as** [comment]
Have the same bug, all of strikes got erased suddenly, full wipe.

**Comment by DisbelievedMonK** [comment]
Same thing.
Morning: HabitRPG on Android 4.0.4. Checking some Dailies and Habits.
Day: Google Chrome on PC. Checking Dailies, Habits, and To-Dos. Adding and editing tasks, using skills, getting new level, spending attribute points. So, I did quite a lot of things.
Evening: Google Chrome on another PC. Everything, what I did since the morning is gone. No new tasks, no gold, no new level. Everything I reached during the day just erased. But what I checked in morning is still there.
Reloading, force synchronizing, and relogging doesn't help.
I never used the inn, if that could help to catch the bug.

My user ID is d2dc50d6-8431-4a8e-af70-77ad64b68c71 .

**Comment by Alys** [comment]
@DisbelievedMonK I'm sorry about that! It must have been frustrating. You were hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313
In brief, the PC you were using during the day was holding on to all your changes instead of sending them to Habitica's server, which means that they were never permanently recorded. If you reload that PC a couple of times, it is possible, although not certain, that it will cause the browser to send the data. 

There's an Advice section near the top of that issue. Most of it is about recovering from damage from Dailies because the actions that aren't sent to the server often include ticking off Dailies, however steps 3 and 4 are relevant to you. They tell you how you can sometimes recognise this bug as it occurs in the browser, and how you can use the Data Display Tool to recognise it for sure (in your case, the DDT would not show any of the new tasks you'd added).

**Comment by DisbelievedMonK** [comment]
@Alys Oh, I didn't find that post, when I tried to search for this bug.
Yep. I'm at my work PC now (which I used during the day yesterday), and all progress came back. And that's good. I already checked again all my tasks at home last night, so I've got double rewards, and that's no really good. But thanks for help anyway.

**Comment by Alys** [comment]
The Advice section talks about using Fix Character Values to adjust your stats. You can use that to remove the estimated double rewards.
