### ISSUE TITLE
The system is going berserk

### ISSUE THREAD

**Issue by loldude101** [HabitRPG/habitica#46]
I turn on my computer, go on habitrpg (Chrome) and I instantly see my health drop from 45/50 to 8/11 with the notification at the top right hand corner that I lost "11 HP". I thought this was weird but disregarded since I was a few EXP away from leveling and regaining all my health. I go check the things I've done so far on my itinerary, level up, continue checking tasks while after checking "Habits" tasks my EXP jumps from 4/80 to 3/80 to 4/80 and back - it's stuck - and out of nowhere my HP drastically drops again. And to make things worse some of my Daily tasks changed: I has three tasks called "Take pills: 1" "Take pills: 2" "Take pills: 3" reminding me to take them three times during the day and, again, out of nowhere all three change to "Take pills: 1". I hope this is just some one-time bug that only I experienced.

**Comment by lefnire** [comment]
habit has indeed been experiencing some wonkiness lately. I don't know where it came from, but I'm sitting down for the next couple days to diagnose these issues. It's been difficult because I haven't been able to properly test the client code (casperjs is the closest thing to a cigar, but still none). Stay tuned.

**Comment by loldude101** [comment]
![HabitRPG](https://f.cloud.github.com/assets/3129563/58956/50a09806-5b90-11e2-96ae-1668cbd0c5bf.png)

Today I level up on the site and after getting 1/80 EXP my health drastically drops again. UGH! What do I do? I like habitrpg but I'm tired of dying and paying tokens, and/or creating new accounts.

**Comment by lefnire** [comment]
Hey @loldude101, doing everything I can with very limited resources. I just launched a  [Kickstarter](http://www.kickstarter.com/projects/lefnire/habitrpg-mobile) with the goal of building the mobile app, but if it gets any funding I'll spend a great deal fixing these issues you've been seeing.

**Comment by loldude101** [comment]
How can normal users donate to you right now?

**Comment by andrewnez** [comment]
Count me in as your first backer. This is hands down the best ToDo/Goals/Habits tracker I've ever used.

**Comment by andrewnez** [comment]
Wouldn't hurt to drop your New Year's Resolutions blog post into the Kickstarter project. It explains the whole thing pretty well.

**Comment by jacksalvo** [comment]
I just saw this on kickstarter, donated at the $15 level because it's exactly the kind of app I've been looking for.

I've been using chrome and it has been going nuts on me as well (I installed the extension).... I understand you're working on this by yourself, and this is essentially a free program right now, so no complaints from me....keep up the good work!

edit...appears to be working better with the chrome plugin disabled

**Comment by horusofoz** [comment]
@lefnire I think this ticket can be closed off as the previous database instability issues appear to be resolved.

**Comment by lefnire** [comment]
yeah, i think this one got fixed actually. many of the other parts pointed out here are specific bugs in the queue anyway
