### ISSUE TITLE
Stealth prevents a Daily's checklist items being unticked by cron

### ISSUE THREAD

**Issue by bunnyplanet** [HabitRPG/habitica#4604]
I have several dailies that have two item checklists. Twice now, I've cast "stealth" and for a daily where only one item had been checked, that item has stayed checked when cron reset the next day.

User ID: 0396e6e1-0edc-46f5-9449-24891ba16698
##

**Comment by Alys** [comment]
Yes, the cron code has [a line](https://github.com/HabitRPG/habitrpg-shared/blob/32ed4dace7b6d713e659e6f0b7ff7cea0160a75b/script/index.coffee#L1481) that skips processing for a Daily if Stealth has been cast to evade that Daily. The processing includes [unticking the checklist items](https://github.com/HabitRPG/habitrpg-shared/blob/32ed4dace7b6d713e659e6f0b7ff7cea0160a75b/script/index.coffee#L1502), so that code is never executed when Stealth takes effect. 

Fortunately you can manually untick checklist items without affecting any of your stats, but that is annoying and shouldn't be necessary.

**Comment by Alys** [comment]
I'll publicise this in the Aspiring Coders guild after the habitrpg-shared repository has been merged into the main repo. This issue should be a fairly easy fix for someone with some understanding of coffeescript.

**Comment by deilann** [comment]
The fix should not keep grey dailies from retaining checkmarks, which is a
desired feature.

**Comment by Alys** [comment]
Oh, that's an interesting point! At the moment, I think checklists DO get reset on Grey Dailies (right?) but I can see it would definitely be useful to have them not reset. It would REALLY help people who want a way of keeping track of tasks taken over the course of a week (make the Daily grey for every day except Sunday, and tick off checklist items as you do them on all the grey days). It should be easy enough to do that. 

Can anyone think of any reason not to?

**Comment by deilann** [comment]
A bit late, but yes, I believe they currently do reset, and I think the benefits of them _not_ resetting are huge, for the reasons you mention. This behavior was actually suggested by hattieshoe a long time ago.

**Comment by Alys** [comment]
I'm going to get onto this, or find someone to get onto it, after the habitrpg-shared migration is complete. 

ADMINs: Note the new "After Shared Migration" label.

**Comment by Verabird** [comment]
To clarify the current and desired behavior:

Current: Grey daily checklists reset at cron unless stealthed.
Active daily checklists reset at cron unless stealthed
Stealthed daily checklists do not reset.
(Only uncompleted dailies can be stealthed)

Desired: Grey daily checklists do not reset at cron whether stealthed or not
Active daily checklists do reset at cron whether stealthed or not
Stealthed daily checklists (that are not grey) do reset at cron
(only uncompleted dailies can be stealthed)

Additionally, is allowing Stealth to affect grey dailies a feature or a bug?

**Comment by Alys** [comment]
The current and desired behaviour lists look correct to me.

I have never known whether allowing Stealth to affect grey dailies is a feature or a bug. I'd be happy with either interpretation. 

If it's considered a bug and is fixed, then we might want to make Stealth less powerful, especially for high-level players. I'm level 90 with 45 PER and if I were a Rogue, one casting of Stealth would hide 15 Dailies. If I bumped my PER up as high as I could with equipment alone, I'd avoid 40 Dailies. Both of those results are with zero points allocated to PER.

@lemoness What do you think of this?

@Verabird If you want to work on this, as I am assuming you do, that would be fantastic!

**Comment by Alys** [comment]
@Verabird If you want to work on this, as I am assuming you do, that would be fantastic!

**Comment by lemoness** [comment]
I'd say don't make it affect grey Dailies, since that seems like a waste -
and definitely weaken it/have diminishing returns. Having never cast Rogue
spells, I'm not very familiar with them, so I will leave the numbers to you
guys.

**Comment by Verabird** [comment]
@Alys Yes, I would like to work on this

**Comment by Alys** [comment]
Thank you! Do you need any information from me about what adjustments to make to the strength of Stealth? I'm happy for you to make your own recommendations if you wish to.

**Comment by Verabird** [comment]
For the strength of stealth (when it only affects non-grey dailies) I was thinking give it diminishing returns with a max of 6 and a halfway point of 100 Per (so at 100 PER the rogue will avoid up to 3 undone, active dailies with one cast of stealth)

For making the checklist changes, I think I should wait until the rebalancing branch is merged (or possibly denied) since this involves changing some of the same code as issue #4473 (reduce MP gained at cron for  undone dailies) and it's confusing to me.

**Comment by deilann** [comment]
I would _not_ make the max a static number because different folks have
different numbers of dailies. I would make it based on _percentage._

**Comment by Alys** [comment]
@Verabird Waiting until the rebalancing branch is merged sounds very sensible - good idea!

I agree with @deilann about percentages.

**Comment by Verabird** [comment]
Point taken on the percentages. If there are any other suggestions, I'm
happy to take them.

**Comment by Verabird** [comment]
I'm working things out here and I'm wondering what the desired behavior is for multiple days skipped between crons. Below are my thoughts.

What to do for a daily if multiple days are skipped:

All inactive: Do not stealth, do not uncheck checklists
All active: use multiple stealth counters for multiple days? Or one stealth covers all days? Currently the latter. Changes so far default to the former. (checklists are set to unchecked also)
Some active, some inactive. e.g. Sign in on Monday, and Thursday, active for tuesday, inactive for wednesday: Default so far: stealth power may be used for the active day(s). Uncheck the checklists.

I know there was some talk of changing cron to only count one day skipped. (https://github.com/HabitRPG/habitrpg/issues/4630)  Only one day worth of damage from cron would mean that only one stealth counter should be used per daily, rather than one stealth counter per daily per day skipped. But if only one day is counted as skipped, and some of the days are active and some are not, I think that damage should be done for any that are active at any time during the skipped days and also those ones should have their checklists unchecked.

**Comment by Alys** [comment]
We will soon be changing cron to count only one day skipped (almost certainly before the Stealth changes go live), however when difficulty settings are introduced, it's likely that we'll be re-enabling the current `daysMissed` behaviour (multiple missed days do multiple damage) as an option, so it's probably best to put in appropriate handling for Stealth for multiple missed days now.

However my thoughts are that the multi-day Stealth handling should probably be as simple as possible since it will affect only some users and then only some of the time. I personally would be okay with you choosing the option that you think is easiest to implement and/or simplest for the users / future programmers to understand. 

Others are welcome to disagree. :)

Keep in mind that if someone were to choose the multi-day difficulty setting, it would be because they wanted their Dailies to damage them more if they were not completed, so it would not necessarily be bad if Stealth did not reduce damage significantly over multiple days.

**Comment by Alys** [comment]
This has been fixed.
