### ISSUE TITLE
Extra notes of challenge participants' tasks don't pop up anymore on mouseover

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#4616]
Because I'm lazy, I'll just copy & paste my Tavern post:

"Does anyone else have trouble reading the extra task notes of participants in challenges? Usually, when you click on a participant in a challenge, that participant's tasks pop up, and if you mouseover over the tasks, the task's extra notes pop up (which is important if the challenge demands of them to write something in there). This has always worked fine on my computer - but not anymore! I've tried with different browsers. I've looked on GitHub if the issue already exists (apparently not). I've looked in the wiki if it's got anything to say on the matter (apparently not). I know how to get the extra notes via API (thank goodness - I've created a few challenges where it's important that I can read them, or I can't decide who wins!). Is anyone else dealing with this? Do I have to rethink my concept of "Tell the participants to write stuff (suggestions, answers, quotes, etc.) into the extra notes such that everyone else can see it"?"

I seem to remember that lately, the notes sometimes showed normally, sometimes showed somewhere at the edge of the screen cut in half and only partly readable, and often showed not at all. When I checked today before writing this bug report, though, I couldn't make any participants' notes show (whole or in part) at all.

Browsers I tried were Firefox, Explorer, and Google Chrome. This is on a laptop with Windows 7 (with all the recent updates - says here "Service Pack 1").

My HabitRPG User ID is 1aff9116-34b0-438c-9877-06038bdce161 .

**Comment by Alys** [comment]
Ha, I had just written several sentences in the Tavern and was just about to click send when your issue appeared. :P :)  Because I'm lazy too, here's part of what I wrote:

"Is it possible that the popup is appearing, but it's misplaced so far upwards that it's actually right at the top of the screen, or above the top of the screen? If you scroll so that the challenge task is at the bottom of the screen and maybe reduce the text size to fit more on the screen, and then mouseover, does that moved the notes popup far enough down that you can see it? If so, it's [this bug](https://github.com/HabitRPG/habitrpg/issues/4307)."

**Comment by habitrpguser** [comment]
I tried scrolling, but the popup containing all the tasks of 1 participant always shows up in the same place (in the horizontal middle, and rather high up to show as much as possible, as it should) and can't be scrolled or moved around. And the mouseover always fails to produce an extra notes popup. The only thing I can influence is the position of the challenge before clicking on one of the participants, and that position doesn't seem to change the results.

I also set the text size to really tiny, and still, nothing showed.

I just tried these things (scrolling, changing size) on all 3 browsers I mentioned. No extra notes popup.

 Thanks for the prompt answer, and for the link to the popup position bug though! It might have something to do with it (or not).

**Comment by habitrpguser** [comment]
Comment from @Castanwydden in the Tavern:

"Thanks for mentioning the problem with the mouseover text not appearing on challenge tasks. I'd noticed it while trying to follow links to blog posts in the Spread the Word challenge, but thought is was just something I'd somehow managed to switch off. I had to download the csv file in order to end the January Clutter Patrol so I could check that people had done everything they needed to do. I don't mind doing that at the end, but it's nice to be able to monitor progress as people are working on the challenge. "

**Comment by Dewines** [comment]
Thanks for copying over my comment. I would have done it myself, but I was at work and couldn't remember my Github password. If it helps, the mouseover text was fine a couple of days ago. In fact it seemed to stop working while I was actually looking at the entries for the Spread The Word challenge. I managed to follow the link in the pop-up mouseover text to one blog post, then when I tried to do it again, the text wouldn't work. That's why I thought I'd done something on my computer! But switching to Chrome didn't bring the text back (I had been using Firefox). This happened on either 31 Jan or 1 Feb, I can't remember which.

**Comment by crookedneighbor** [comment]
Hmmm... figured out the problem. The notes are appearing behind the modal:

![screen_shot_2015-02-03_at_9_57_45_am](https://cloud.githubusercontent.com/assets/2916945/6023615/4dc54a58-ab8b-11e4-9f4d-9b722e4e1c45.png)

Investigating how to fix it now.

**Comment by crookedneighbor** [comment]
Ahh, I know. It's because the popovers for tasks are being appended to body now to avoid the floating ever upward issue.

~~I've changed it so popovers are only appended to body if being used in a modal.~~

Edit: I've changed it so popovers are only appended to body if not being used in a modal.

**Comment by crookedneighbor** [comment]
@habitrpguser and @Castanwydden Thanks for reporting this. It will be fixed on the next deploy.

**Comment by habitrpguser** [comment]
Thank you very much for the quick debugging!

**Comment by Dewines** [comment]
Thank you, that was quickly dealt with!
