### ISSUE TITLE
Suggestion: Leveling Rewards

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#462]
As you near the end of a level, you might have a lot of HP in reserve. There is the temptation to spend that like gold on items or rewards you have not necessarily earned. Having this HP be used for something ('leveling bonuses') might halt that temptation. Maybe this leftover HP could be converted to a sort of currency that can be spent on exclusive or cosmetic items not available through the standard store.

**Comment by wc8** [comment]
I'm trying to figure out what "leftover HP" would be. Are you saying when you see you've got 45 HP points and you're about to level up, you're thinking, oh boy, I can spend 40 HP points on rewards without killing myself? I haven't thought of HP as something to spend. I see it a sign I'm doing well, not a sign I can take a hit.

For this **Bonus or Reward for every HP point when leveling up**, maybe a badge and allow the badges to be cashed in for a reward later? What do you think? Would a simple GP bonus work?

**Comment by eiron** [comment]
Something along those lines. I had a huge amount of HP and there is the temptation (which I did not succumb to, but I know I am not the only one to have thought of it), to spend the HP as currency, then do whatever it was that would push me over the level boundary. A bonus in the form of GP is probably not ideal, as it could mean a huge bonus at those leveling points, which would not aid productivity in the long run. I think something that cannot be spent on actual self-appointed awards would be best. A sort of badge-based currency. A certain quantity of badges could then be exchanged for a token or for cosmetic items directly. A means of showing off how the system is working. A sort of "You are doing well, so here is something to show that off" exchange.

**Comment by wc8** [comment]
So, at what point would it trigger a badge (50%, 75% HP?) or would the badge be worth, say, however many HP points you had when you leveled up?

**Comment by wildcate** [comment]
Isn't "getting yourself almost killed and not minding to spend potions because you are going to level up during that fight anyways so you can take it" a typical gaming move?
But I agree, a badge would be nice - or something else that will not wreak havoc with the rewards system otherwise, but prove an incentive to keep the HPs up before leveling. You could even add a "health tree" in the background of the header that gets some more growth for the HP count when leveling up? That would be fun for me, personally, since I like the green stuff. And a tree can grow slowly :)

**Comment by eiron** [comment]
Even something as simple as a health tree might be nice. It could get greener and bear fruit as you continue to level with health above 50% and lose its greenery and turn barren as you level with health below 50%. It would then work as a visible representation of how well you are doing in the longer term.

**Comment by horusofoz** [comment]
How about a 25% GP reward? Easily integrated, provides an attractive reward but not such a large one as to unbalance the rewards system.

**Comment by busterroni** [comment]
I actually like @horusofoz 's idea. If you have 50 Health Points left over at the end of a level, you'll get 12.5 (50/4) gold.

**Comment by wildcate** [comment]
While I'm not against a gold bonus for leveling up, technically that is nothing else than spending your "leftover" hitpoints on rewards, but with a worse conversion rate?

**Comment by PhilipHow** [comment]
I think the conversion rate of using HP for rewards (when you don't have the Gold) should be higher, i.e. it should be tougher to use health for rewards. Then giving a % GP reward on level up makes more sense.

**Comment by horusofoz** [comment]
@MrConcept Great idea. I think 150% is a fair rate. @wildcate Your thoughts?

**Comment by PhilipHow** [comment]
The HP > GP conversion upon level up should be equal or higher than this though, to make it beneficial.

**Comment by horusofoz** [comment]
I think 25% is a good rate so that it doesn't overshadow the earning of GP through task completion. This is meant to be a minor bonus not a major source of GP.

**Comment by PhilipHow** [comment]
HP -> GP = 0.25 (With a 25% conversion rate)
HP -> GP = 0.66 (With a 150% penalty)

So would still make sense to use your HP for rewards, unless there was another mechanic that is affected by this.

**Comment by wildcate** [comment]
Okay... here are some semi-randomly ordered thoughts.
I don't know the current conversion rate GP/HP when buying items you can't afford, but I'd guess it is 1:1. 
I agree with @horusofoz that it should be a minor bonus, not a major source of income; that would interfere with rewards (probably). However, if the conversion ratio to gold on level-up should be higher than the direct HP cost and 25% of HP in gold would be our figure to play with, it would mean that overspending 1 gold = 5 HP damage. I am sure this is possible, but it is a serious drain on HP, and I think it should only be implemented once the warning (this will hurt/kill you) is definitely enabled when buying stuff. Even with the 25% conversion rate, I would have gotten a bit more than 10 gold for my last level-up; that, for me, would have been a very big sudden income.

In some other thread, there has also been concern that folks would be tempted to cheat in order to level up faster; the reason given was that the feature unlock would be too tempting to resist. Adding an extra gold income to the leveling up will be even more incentive to level up faster, and I think that should be kept in mind.

Plus with more HP per level (that was either just requested or has actually been accepted or implemented?) it would also mean more gold bonus per level-up; also not necessarily bad since leveling up will probably become progressively harder, but worth keeping in mind.

All that said... I think I still like the health tree idea better because it will not lead to weird spurts in gold income, is something that could be scaled to the percentage of HP still available (flowers and fruit, just flowers, just green, sparse green/buds, no green, black and smoking ruin of a tree), and is visible for longer than some additional gold in the purse. The tree could be shown either on the main header or on the achievements/badges page, depending on how much visibility one wants for it.

**Comment by PhilipHow** [comment]
Yeah, changing each ratio up or down to equalise the two has detrimental effects on both mechanics. I really like the extra gold idea though, and agree it should only be small amount (<=25%), so another mechanic is needed to reward you for keeping healthy during the level!

How about just a flat bonus for being 100% upon levelling up?

**Comment by wildcate** [comment]
Hm - even though I've been not doing badly, I have never leveled up with 100% health, since one missed daily or one instance of doing a bad habit will stop that. And I will not manage to be so good for several days or, later, maybe several weeks in a row! So if I'm not at 100% anyway (or at, say, 75% or whatever will give the bonus), what is going to keep me from spending the rest of my HP on unaffordable rewards? I surely will not buy a health potion to level with the required HP% unless it would be worth it - and that, again, would mean a very substantial flat bonus, about 30 gold or so since the potion costs 25 and we're talking munchkin behaviour here. 

Sorry if I'm bashing your ideas, but if I were a munchkin, that's what I would do. And the idea @Eiron originally had was to add some sort of incentive to keep a non-hardcore-munchkin from temptation of overspending just before leveling up... by giving a non-gold bonus.

I think there's enough opportunity to earn gold by doing things and enough incentive to level up already... and there are some bonus gold drops planned as well, for very good streaks or consecutive doing of dailies, which should also give boosts. If the HP are giving you something that you cannot buy with gold or tokens, it's an incentive on a different level.

**Comment by PhilipHow** [comment]
No that's fair. I'm suggesting the gold on-top of a unique reward, such as an achievement for perfect levels.

I think it needs to be turned into some sort of stat, and map directly (as you stated @wildcate, cut-off points can be gamed) so you could use your health to to fund rewards, but it would stop you progressing in certain areas. You could then limit certain weapons or abilities based on the stat. What do you think?

**Comment by wildcate** [comment]
I'm not sure, to be honest. I think it might make stuff a little too complicated... and I could imagine that there will be a point in complicatedness where non-hardcore-gamers will turn away. 
And regarding rewards tied to health... what about those who are not gaming it, but trying very hard to kick a habit and just barely keep alive in HRPG? I think that tying another tier of rewards, or general progress, to overall health might be frustrating for them. 

But maybe it's time to let @lefnire or someone else of the core crew say what they think? They probably have a better grasp of what might fit into the system as it's planned now (even though they are probably all quite busy with other, more urgent and critical stuff at the moment).

**Comment by tmas** [comment]
Maybe each consecutive item purchased using HP could double the amount of HP lost buying it? That way if you're playing normally and you buy something you don't quite have enough gold for it doesn't punish you too much but if you're spending your HP before you level up it becomes difficult to do a whole lot.

**Comment by wc8** [comment]
I like the idea of a higher hit on the HP from spending gold you don't have.

Building on some ideas here: 
First Time: 1.5 HP for every 1 GP overspent.
Second Time: 2 HP for every 1 GP overspent.
Third Time: 5 HP for every 1 GP overspent.

On the other hand, the simple 5 HP for every 1 GP overspent resonates, but I suppose it could just result in users being disinclined to log rewards taken.

**Comment by PhilipHow** [comment]
Yeah fantastic idea.

Should the ratio decrease over longer periods however? Say I binged one level but then behaved myself for the next couple of weeks, should the cost still be 5HP?

**Comment by eiron** [comment]
If we are taking the punishment over reward route, then perhaps it could be a status effect, like 'wounds'? There could be a few levels, for instance: bruised, scratched, bleeding, wounded. When affected by these (by taking too much damage through reward spending) it will bring up a status on or around your health bar detailing what extra damage you will take for overspending. This damage should heal over time, rather than being reset at a level.

**Comment by PhilipHow** [comment]
@Eiron I like!

**Comment by wc8** [comment]
Having had a number of issues set me back on completing tasks, I'm finding myself suffering repeated deaths. I'm concerned that wounds would make it that much harder to rebuild good habits.

Building on earlier suggestions: **Health Tree** bears fruit according to your Health Points when you level up. The fruit can be eaten to restore health later. Neither the XP or the GP are affected, except that you potentially save on the cost of potions.

Thoughts?

**Comment by horusofoz** [comment]
This iteration of the Health Tree idea I like. I would still argue for a
conversion rate but with that included idea sounds great :)

**Comment by wc8** [comment]
Combining the ideas:

**Level Up Enhancement**
1. **Health Tree** bears fruit on level up according to HP at the time. Fruit can be eaten later to restore health.
2. **Wellness Reward**: 0.1 GP for every HP retained on level up: max bonus 5 GP
3. **Wounds**, for each time you spend GP you don't have you incur a wound: 
- 1st time: scratch: deducts 1.5 HP x overspent GP, heals in 1 day or on level up
- 2nd time: bruise: deducts 2 HP x overspent GP, heals in 2 days or on level up
- 3rd time and thereafter: bleeding: deducts 2 HP x overspent GP, heals in 3 days or on level up

If there are no objections/concerns soon, I'll post this on Trello and discussion can continue there.

**Comment by eiron** [comment]
I like it. The only issue with the levelling up healing the wounds is that it is most likely at the end of the level when one might be tempted to do this. Can they heal at one level per day instead and not be negated by levelling? Else, perfect.

**Comment by wc8** [comment]
Vote for [Level Up Enhancement](https://trello.com/card/level-up-enhancement/50e5d3684fe3a7266b0036d6/238)

**Comment by wc8** [comment]
A few small changes, follow up (**or vote**) on [Trello](https://trello.com/c/CLH3PMkH) with any comments/concerns:
- renamed suggestion to Health Incentive
- adjusted example wound values: x2 HP loss could kill pretty fast depending on reward prices
- changed wound healing to 1 _degree_ per day (since level refers to XP, using medical term of "degree" for wounds)
- added suggested fruit HP value
