### ISSUE TITLE
Repeated drops and collection quest items with check-uncheck tasks/Dailies

### ISSUE THREAD

**Issue by Ztee** [HabitRPG/habitica#4626]
I happen to checkoff one daily that I am not ready to check off, so I un-checked it, the drop, a hatching potion did not disappear, and when I rechecked the daily, I received another hatching potion, done it a few more times and now I have 3. I reloaded the page, and checking and unchecking does not drop me potion anymore, also, i am at 5 drop cap, not sure if that would continue to happen if it is not my cap yet. But the 3 hatching potions remained in my inventory.

User ID:54c98338-93cb-4f92-9045-4a07d9dbd432

**Comment by Alys** [comment]
Yes, this is expected behaviour. When a task is unticked, HabitRPG removes the XP and GP that you gained from it, but it does not remove any drops (neither normal drops nor collection quest drops). This is partly for coding convenience (keeping track of drops is harder than XP/GP and would require more database and browser resources), and partly to be nice to the players. :) Imagine that you had received a rare golden hatching potion when you accidentally ticked off the wrong task, and then had it removed on unticking, and then did not receive it again when you ticked off the correct task! I am certain that at least some of our users would be very annoyed by that, so I personally think it's best that HabitRPG does not do that.

This does mean that it's possible to "cheat" by repeatedly ticking off the same task, but you can do the same more easily by clicking on positive Habits, and that sort of cheating hurts no one but the person doing it.

Some users (myself included) actually use this behaviour as a feature to make a "wishing well" (http://habitica.wikia.com/wiki/Sample_Custom_Rewards#Wishing_Well ). We have a reward for a certain amount of gold, and whenever we spend that reward, we are allowed to tick off a task and then untick it, in the hopes of receiving a drop.

**Comment by Ztee** [comment]
oh i see, by the way good suggestion of reward. Thanks!

**Comment by JalanshMunshi** [comment]
@Alys I saw this issue mentioned in the Aspiring Blacksmiths guild and I went through this issue and the underlying logic behind how drops are rewarded on [Habitica Wiki](https://habitica.fandom.com/wiki/Drops). 

I don't know if this has been discussed earlier, but is it possible to introduce a property inside the `TaskSchema` which will indicate whether this task has been revived or not. 

For example, let us assume that there is a property named `isRevived` set to `false` by default. If an already completed task is being unticked or revived, then the gold and `XP` deductions would remain the same. But since this is a revived task, we will also check if a drop was awarded when this task was completed. We can keep a track of whether a drop was awarded by introducing another attribute (let's say `dropAwarded`. 

Finally, we will award a drop only if - 
1. `isRevived is set to `false`.
2. `isRevived` is set to `true` and `dropAwarded` is set to `false`.

Again, I might be missing something out here or this might have been discussed earlier and is not a good approach. But this is a general idea which I thought can be discussed with the Habitica staff. 

What do you think? Is it possible?

**Comment by Alys** [comment]
@JalanshMunshi Thank you for asking about this but we decided long ago that we don't want to change the current behaviour. In particular, the wishing well feature that it enables is popular. It's documented on the wiki in a few places, including articles that have been featured in Habitica's blog (e.g., [this](https://habitica.fandom.com/wiki/Sample_Custom_Rewards#Wishing_Well) and [this](https://habitica.fandom.com/wiki/Habitican_Shared_Task_Lists)).

As a general rule throughout Habitica, we don't care if people "cheat" by repeatedly ticking and unticking tasks that they haven't accomplished in real life to get stats or drops.

Cases where a player accidentally ticks the wrong task and wants that to be fully reversed are likely rare enough that I don't think it's worth the extra code and data bloat to resolve it. If a player ever gets a drop that they think they didn't earn, they can choose to sell it for gold (and then remove the gold if they wish).

**Comment by JalanshMunshi** [comment]
@Alys Yep, that makes sense. Thanks for letting me know! :smile:
