### ISSUE TITLE
Habits we are trying to avoid - can they turn blue?

### ISSUE THREAD

**Issue by webir** [HabitRPG/habitica#4627]
I can click a habit I want to stop (eating sugar) but the box will only ever stop at yellow, and never get bluer (no matter how long I ignore it). the completionist in me would love the box to get bright blue the longer I do not do that negative activity. It would be more motivating to me. 

Thanks!

**Comment by Alys** [comment]
What you're experiencing is the intended behaviour; Habits aren't meant to turn blue by themselves. The only way to get a blue Habit is to give it a plus button and click that regularly, which probably isn't what you want for this Habit.

However I do understand your desire for this particular Habit to turn blue! You might like to log this as a feature request in Trello, so that it can be discussed along with other requests related to Habits. To do that, go to the website's Help menu and click "Request a Feature".

**Comment by SabreCat** [comment]
You can also bluen a minus-only Habit by smacking it around with the Warrior's Brutal Smash skill... but it will slide back to yellow with time.
