### ISSUE TITLE
How should boss damage be calculated (Discussion)

### ISSUE THREAD

**Issue by keithhir** [HabitRPG/habitica#4628]
User ID: 57ab6504-1fd6-493e-b984-9b4ad2946c62
Group ID: 30fea9dc-239d-4d99-b529-1258cc9d87df

On 3 Feb 2015, Party had Rooster Rampage quest active.
I log in, and did 257.2 damage to Rooster.  Rooster has 43 HP left.
Cast Burst of Flames (6x)
Checked off 7 Habits.  Did 2 Criticals (350%).
Checked off 10 Dailies.
Fed 7 Food items to Pets.
Party member logs in, does 148.8 damage to Rooster, and Rooster is defeated.
Sent Quest Invite for The Icy Arachnid.
Party accepted quest.
I log out of HabitRPG.

On 4 Feb 2015, I log in and do 0.0 damage to Spider.

It appears that the tasks for 3 Feb are not counted towards the quest after cron.  Is this due to the fact that my tasks were checked while the previous quest was still active, even though the quest was completed prior to cron?

I did notice that if there's a pending quest and I check off tasks, they correctly apply damage the next day once the quest has been accepted.  
##

**Comment by crookedneighbor** [comment]
Related to #3693 

The big question is still this: should "attacks" performed before a new quest starts count toward that new quest?

**Productivity logic:** YES! I worked hard for that mana and I don't want it wasted.

**Game logic:** NO! How can an attack hurt a boss if the boss didn't exist yet?

**Comment by lemoness** [comment]
Ground is still on fire/brutally smashed when the boss shows up :)

**Comment by crookedneighbor** [comment]
Since Brutal Smash and Burst of Flames damage is calculated at cast, rather than at cron, I'd really like to see it damage the boss in real time. Though, that said, I like that rewards are distributed at a party member's cron. Delayed gratification can go a long way.

It'd be awesome if there was a "Defeated" version of the boss sprite, shown if health drops below zero before a party member's cron. This could also be used on the quest completion modal. 

I don't know, I'm of two minds about it. It should probably be either one way or the other, not this silly middle ground I just suggested.

**Comment by keithhir** [comment]
I figured that if "Damage to the boss, the party, and the player is meted out when each player's cron first processes for a new day (wiki)" that it would apply to any active quest.  That is, my results aren't specifically assigned to a particular quest, but rather "stored/saved up" until it's time to tabulate the outcome.

**Comment by crookedneighbor** [comment]
@NotShivering Right now the quest damage counter resets once the boss is defeated. 

That's why, as you observed, you could do damage when actions were taken while a quest was pending or nonexistant, but not if those actions took place while the boss was active, shortly before being defeated. 

So, in short, a change DOES need to be made to the code. Just not sure what that change should be.

**Comment by Alys** [comment]
_"Ground is still on fire/brutally smashed when the boss shows up"_   --- I love it! :)

_"Since Brutal Smash and Burst of Flames damage is calculated at cast, rather than at cron, I'd really like to see it damage the boss in real time."_

Damage from tasks is calculated at task checkoff too. I think skills and tasks should be treated identically for when the damage is applied.  I also think that should be at cron. The primary purpose of quests is to encourage you to do your Dailies before your day start time, and having much of your interaction with the quest happen at cron supports that. Here's one (admittedly selfish) use-case where damage being applied immediately would be detrimental:

In the party I'm in, we usually finish one boss quest every day. I, as a mage, will cast enough skills to kill it. I have my custom day start time set so that my cron happens after my other party members' crons, meaning that they still have motivation to do their Dailies. If damage was applied immediately, then the boss would die during the day, long before the day start time for any of us; even my own Dailies wouldn't have motivation from the quest. 
- One "solution" to that is prohibiting people from killing bosses in one day, but I really don't like that approach. It adds complexity, and removes the one-shot ability that I am sure a lot of people like, and reduces revenue because instead of one quest being bought each day, it would be one quest every two days. 
- Another solution is for the party to run more than one quest a day -- good for revenue but it really does de-couple the quest system from Dailies motivation. 
- A third solution is to have the boss defeated but still hanging around until cron has happened for all party members, but I don't like the code complexity for that, and we'd need to consider what happens if members don't log in for a few days (and aren't in the inn), and it also makes little sense for a defeated boss to be doing damage to players hours later.

_"Right now the quest damage counter resets once the boss is defeated... So, in short, a change DOES need to be made to the code. Just not sure what that change should be."_  From memory, that should be easy enough. The place in the code where the quest ends will wipe out the `party.quest` object for each participant. Instead of doing that, you'd just wipe those parts of it that are relevant to the specific quest (e.g., `key`) and leave in place the `progress` part. Then the only time the progress was removed would be at cron (and it always **should** be removed at cron, otherwise if you don't start a quest for many days, you could be one-shotting it from purely your task completions over those days). There'd been to be an exemption for collection quests, because we probably do want to start afresh for each quest, since the collection type is specific to the quest.

**Comment by lemoness** [comment]
People do sometimes request an "overkill" mechanic where there are bonus
points after everyone's cron occurs. After all, even in the current system,
it's common for people to not land a blow. Back when I played a Mage, I'd
frequently take down the boss before anyone else could land a single hit,
just because I could sign in first thing in the morning instead of after
work. (It's a big reason that I stopped being a Mage.). At least if the
damage was being dealt in real time, everyone would get a chance to hit it!
Plus, I think it is more satisfying from a game perspective. That being
said, it does make completing Dailies less necessary in cases like yours.
I'm not sure how common those will be, though, especially once we nerf BoF.

Collection quests are hard enough that I think that we should count
previous tasks towards the total of new quests started.

**Comment by Alys** [comment]
_"At least if the damage was being dealt in real time, everyone would get a
chance to hit it!"_ Not necessarily. If a Mage or Warrior cast their skills
early in the day (sensible if you have close to max mana) then the boss
would be defeated straight away. One-shotting is possible with the Warrior
attack skill too, and still will be with BoF after nerfing with weak bosses
and a full mana bar.

**Comment by Alys** [comment]
Of course once you'd used up your mana killing a boss during the day, you could start another quest straight away and not have enough mana to kill it until the next day. And that does double the number of quests bought. :) However I still am concerned about how this will help to disassociate quests from the need to complete your Dailies. If it's possible to finish a quest before anyone's cron happens, then that is the most sensible thing to do from a gaming perspective. I fear that we'll end up with people thinking that damage-free quests are the norm, and it's a bad situation if the party lets the quest last long enough for anyone to take damage.

Of course I'm coming at this from the perspective of always having been in a party where it's possible to complete most quests in a single day. It would be interesting to know how common that is.

**Comment by crookedneighbor** [comment]
In my party, the last couple of quests, we've deliberately limited the amount of damage our power users (me and a mage) do to the bosses so our lower level users can actually contribute some damage. If things get out of hand, we step in and take care of it. So, I definitely hear the feedback about allowing users to actually feel like they're participating in the quest.

I think it's wise to focus on quests as a motivator to complete dailies. Plus, if it happened in real time, people resting in the inn would do damage. And we don't want that. Kind of defeats the purpose.

Here's an idea (and maybe a bad one, but bear with me), what if there was a projected damage bar for the damage you are doing to the boss. It could look something like this:

![boss](https://cloud.githubusercontent.com/assets/2916945/6051054/4c58497c-ac8a-11e4-92f4-e9579b4f8326.png)

You could either have it make it show projected damage for the party, or just show the projected damage your user would do (if we were really crazy, we could have a toggle in the party page to show the preference) If just for the user, maybe it'd be hidden if the user is in the inn. 

Maybe that's a half baked idea. It'd just be nice to get some visual feedback for your work during the day.

**Comment by lemoness** [comment]
Oooh, I like that idea! I definitely refresh the Data Display Tool nonstop
to see how much damage I'm dealing; I'd love to have that visually in game
as a number in addition to bar color.

What do we think of an overkill mechanic in lieu of real-time damage? Also,
how do you feel about real-time collection quests, since doing Dailies
isn't a factor there?

**Comment by Alys** [comment]
Overkill does sound interesting. What effects would it have?

**Comment by crookedneighbor** [comment]
@lemoness I am all for real time collection quests. As much as I love the DDT (THANK YOU ALYS), I hate having to exit the site to look up that info.

What if overkill was calculated at the time of the cron of the user that killed the boss? IE, it loops through the party and calculates the damage they would have done at that moment, rather than at each user's cron?

**Comment by lemoness** [comment]
There's some discussion about these things on
https://trello.com/c/VPPjVRlF/212-quests-and-bosses-v-2-collection-quest-and-boss-fight-enhancements

**Comment by crookedneighbor** [comment]
I believe it would be additional rewards, once the extra damage crossed a certain threshold. I think mostly extra xp and gold, but I suppose it could award extra items too if we wanted. 

I think those rewards should be hidden, not displayed on the quest modal.

**Comment by deilann** [comment]
What if we looked at it like stretch goals. You get 3 eggs per quest. What
if you get an extra egg per percentage of overkill?

**Comment by crookedneighbor** [comment]
I'd want it to be capped. Quest eggs in particular are gem purchasable -> revenue, so I'd want to limit how many extra eggs you get. Not sure what a good cap would be, definitely should not receive more than double.

**Comment by deilann** [comment]
I would say double is a good cap.

**Comment by deilann** [comment]
We could possibly also go back to 2 eggs per scroll, with the ability to
receive up to double, or 4, which would be less of a jump than going up to
a possibility of 6.

**Comment by lemoness** [comment]
I would like it to add more XP/GP, not items, since egg purchases are one
of our bigger revenue sources.

**Comment by deilann** [comment]
We could just scale XP/GP rewards based on percent overkill then.

**Comment by crookedneighbor** [comment]
@lemoness :+1: 

Any idea how you'd want to scale it? 

Should it be a one time bonus, IE, achieve x percentage above the boss's health and get this bonus? Or a scaling bonus, as @deilann suggested?

**Comment by lemoness** [comment]
I like a scaling bonus :)

**Comment by crookedneighbor** [comment]
How about a cap of double. 

#### Examples

So if the boss has 600 HP and gives 100 XP and 100 Gold.
- Dealing 600 damage will result in 100 XP and 100 Gold
- Dealing 660 damage will result in 110 XP and 110 Gold
- Dealing 900 damage will result in 150 XP and 150 Gold
- Dealing 1200 damage will result in 200 XP and 200 Gold
- Dealing > 1200 damage will result in 200 XP and 200 Gold

#### How extra damage is calculated:
- User that did the killing blow: Any damage greater than that needed for killing the boss is added to the total
- User that has not yet cronned: All damage is calculated in overkill bonus
- User that cronned already, but boss was not killed, and has done more damage since then (@NotShivering's case) : that excess damage is calculated in overkill bonus

I think the real time boss bar updating and the quest collection updating in real time should be separate issues. 

Also, sorry @NotShivering for hijacking your issue. But I think the solution we came up with will solve your problem!

**Comment by lemoness** [comment]
I like that a lot!

**Comment by wildcate** [comment]
Since you were asking about non-one-day-finishers: I'm in a party that consists of three people altogether, and it usually takes us several days to finish a boss quest. Damage dealt ranges between about 4 points and ~360 points per person, depending on how much mana is available. We've never made it our goal to kill off a boss in one day, though. The possible damage to the party is a huge motivator for me to take care of all my dailies, so I'm quite happy with taking several days per boss.
That said, the projection on the boss bar would be absolutely delightfully awesome, as would the overkill mechanism. Capping the overkill revenue would be fine and a good idea. Personally, I don't actually speculate on the XP from the quests, so a nice overkilling reward for me would also be random extra drops of eggs, potions or food (maybe with a focus on the hard-to-get potions, even?)

**Comment by keithhir** [comment]
I don't consider it a hijacking if we're going to the same destination.  Thanks for discussing this!

**Comment by devnuhl** [comment]
+1 for Collection quests being real time. I think two in my party yesterday lost all progress as the third cron'd first, had enough items to solo finish it, leaving myself and the second with nowhere for our progress to go. I understand cronning the combat quests, but not collection. 
/2c

**Comment by Alys** [comment]
I'm closing this because it's more of a feature request than a bug and is not something that fits into Habitica's direction at the moment. However it could be requested on Trello if desired (Help > Request a Feature from the habitica.com website's menu).
