### ISSUE TITLE
Paid for a one-year subscription, subscription not applied to account.

### ISSUE THREAD

**Issue by TheIronSpike** [HabitRPG/habitica#4629]
User ID: 32d7b258-e32c-4f80-bd3d-386a114896ef
OS: windows 7
Browser: Chrome

Problem's simple. I paid $48 for a year's subscription. Pressing the payment button on the Paypal landing page resulted in an error. my Paypal balance was billed for the amount, but I'm still not considered subscribed by my account. I can't buy gems, I'm being urged to subscribe, etc.

Reloading the page and signing in again does not fix the problem.

Is this normal? Is there a waiting period?

**Comment by Alys** [comment]
@TheIronSpike I believe that is not normal and there should not be a waiting period. 

Because this involves your financial details, we shouldn't discuss it here. Please email admin@habitrpg.com and include the information you entered above and also anything you have about the payment that was extracted from your account (e.g., receipt emails or screenshots from PayPal).

I'm going to close this issue now, but if you wish to comment here again, you certainly can and we will see it and be able to reopen this issue if necessary.
