### ISSUE TITLE
Died overnight --- Prevent multiple days absence causing more damage than one day

### ISSUE THREAD

**Issue by thursdayb** [HabitRPG/habitica#4630]
User ID: e5330da6-8740-4139-8a94-163041a10dc7

Last night I left three tasks undone, woke up to find I'd taken exactly 50 points of damage and died. (I'd been at full health yesterday evening). Most of my dailies are also missing now, though habits, to-dos, and rewards look fine.

**Comment by deilann** [comment]
Have you tried clicking "Clear" on the tag filters? Please try this, even
if it doesn't look like a tag is active. Also, if your dailies list is
default set to "Due" please look at "All" to see if maybe the dailies are
still checked, which would be a different bug.

**Comment by thursdayb** [comment]
Clicking "Clear" didn't do anything.

You're correct, dailies are still checked. 

Thanks.

**Comment by Alys** [comment]
@thursdayb This is an instance of this bug: https://github.com/HabitRPG/habitrpg/issues/4313

You don't need to comment there; the two issues will be linked automatically. If this happens again, read the first post in that issue to find a workaround that should stop it, until we can find out how to fix the bug properly.

**Comment by mazeedt** [comment]
You die way to easily. I restarted after a period of not playing and instantly died the day after because I couldn't finish dailies that had to do with the morning routine. Despite finishing a ton of tasks (the absolute majority). Not cool.

**Comment by Alys** [comment]
@mazeedt Whenever your death is unfair, you can go to [Settings -> Site](https://habitrpg.com/#/options/settings/settings) -> Fix Character Values to restore your level, XP, and gold, and to give yourself extra gold to buy back the piece of equipment that you lost. You can also edit each missed Daily to reset its streak (in Advanced Options on the edit form). 

Death is designed specifically to encourage you to do your Dailies and avoid negative Habits, so it will kill you if you leave Dailies undone - that behaviour means it is working as intended - however with Fix Character Values, death can be completely reversed if you want it to be.

If you're ever in a similar situation in future, you can edit the Dailies that you can't complete to unschedule them for that day. You can learn more about this in the wiki's [Dailies](http://habitrpg.wikia.com/wiki/Dailies) page. You can also [rest in the inn](http://habitrpg.wikia.com/wiki/Tavern#Resting_in_the_Inn) for protection.

Regarding your tasks that disappeared (assuming there were some, since you commented on this issue), have you tried clearing tags as described above? Did that make them return? If not, can you please describe which tasks are missing and give us your user ID (see step 6 in [this page](https://github.com/HabitRPG/habitrpg/issues/2760)).

**Comment by deilann** [comment]
It's also important to note that if you let tasks go that long, they're
probably super red and so do more damage. Creating new tasks to replace
them or purchasing a fortify potion will help with that.

**Comment by lemoness** [comment]
Over a period of absence, do tasks keep getting redder and redder? It seems
like they shouldn't get more than a day's worth, to encourage people to
come back to Habit after leaving it.

Would it be possible to make the maximum number of consecutive missed crons
only one? That is to say, if you don't sign into Habit for 20 days, it's
the same as not signing in for 1 day? I really feel like that would make it
less punishing for people to come back to us, which we really want them to
do.

**Comment by Alys** [comment]
@lemoness Dailies do get redder for more missed days. It should be easy to make any number of missed days equivalent to a single missed day - we'd just disable the code that calculates missed days and iterates through the Dailies damage code for each day.

Technical details: I suggest this be done by setting `daysMissed=1` immediately after [this line](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L1437) with an appropriate comment, so that we can easily go back to using daysMissed in future if desired (e.g., as an option the user can choose in the future Difficulty settings).

You're certain you'd like this to be done? If so, I'll advertise in the Aspiring Coders guild.

**Comment by Alys** [comment]
@mazeedt Do you need further help? Are you missing any tasks?

**Comment by crookedneighbor** [comment]
@Alys I think including the option in difficulty settings would be a good compromise. Good idea.

**Comment by lemoness** [comment]
Yes, I think having the option to increase punishment for multiple days
would be a good candidate for the Difficulty Settings! In the meantime,
though, let's switch it over, unless anyone sees any major disadvantages.

**Comment by Alys** [comment]
Note to the programmer who works on this -- do not worry about building the difficulty setting mentioned above. Those settings are being worked on in a separate branch and will not be released for some time. For now, make the simple change to prevent punishment for multiple days absence. 

The important part of this is testing! We need to be sure that this change works as desired, so be sure to do appropriate testing and please describe all of your tests and their results in your Pull Request.

**Comment by deilann** [comment]
mmmmmmm I'm not sure we should do this.

There's no real way for Habit to tell if you wandered off for good reasons
or lazy reasons. If my tasks didn't get done for 3 days, they didn't get
done for 3 days. They need to redden to that extent, unless I signed into
the inn.

The issue we're seeing is someone who left the site for a really long time
and expected to just jump back into the same tasks, which I think is
actually kind of silly. It would have been best to reevaulate the tasks and
remake them anyway ... they probably needed to change.

**Comment by lemoness** [comment]
But I frequently see people who miss a couple of days of Habit and are then
scared to come back because of the punishment. Since we have big issues
with user retention, I'd rather make it as non-punishing as possible to
come back after ANY length of time, and then leave the difficulty settings
for users who want more punishment.

**Comment by deilann** [comment]
What if the tasks redden appropriately and the damage is only done for one
day? Then people have more incentive to stay and finish their tasks --
higher reward.

It's not an issue of wanting "more punishment" -- it's an issue of wanting
tasks that properly reflect what you have and haven't done.

**Comment by lemoness** [comment]
Which day will the damage reflect, though? The massive damage of the most
recent day, or the lesser damage of the first day? It seems weird to have
them mis-matched. I like it better than the current system, but I still
think it would be simpler to have only a single day's worth of absence
applied in terms of both redness and damage, and it would lead to less
confusion from players who don't understand why skipping a single Daily now
makes them die (i.e. because it got massively red). Not all players will
need to redo all of their tasks after an absence, and it is unrealistic to
punish them if they don't. Power users may be more motivated by the dark
red color, but I'm not convinced novice users will be.

**Comment by crookedneighbor** [comment]
I agree with @lemoness.

**Comment by remmz0r** [comment]
How can I run a cron at will? So I can replicate the bug and test locally?

**Comment by taldin** [comment]
You can set your test account to be in Debug mode, which lets you add 1 day at will.   However, I'm not sure if it allows for multiple day misses.   And my lovely girlfriend recently forgot to sign in for three days and killed the whole party -- 53 points of damage.    On the other hand, I didn't sign into my test account for a month and took 462 damage.   I'm not sure how many levels I lost though -- might have been just one.  :)

**Comment by crookedneighbor** [comment]
@remmz0r The debug menu @taldin mentioned is in the footer. It allows you to easily add gems, apply boss damage, and activate cron, among other things.

The -1 missed day does not stack, if you press it a second time, cron will run for the first instance rather than stacking them. 

You could temporarily modify [this line for testing](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/footerCtrl.js#L76)

**Comment by Alys** [comment]
I'm working on this.
