### ISSUE TITLE
Dailies appear grey from 2 days ago and No Drops for today?

### ISSUE THREAD

**Issue by IcanBEsoMUCHbetter** [HabitRPG/habitica#4637]
Hi!

User ID : 8f9ff296-d9c2-401c-aedb-1fe20c74ccc3
Browser : Chrome
OS : Windows 7

I woke up and log on HabitRPG on my computer. I start checking some dailies, and realize I lost 35 HP while I did all of my dailies yesterday while I did all of them but 3 blue.

Then I notice some dailies disappeared. Turns out, those ones were grey (but I didn't touch them as I just woke up) and they lost they're streak. For some reason, those dailies were back at streak 2 instead of 20, 40, 50, etc. I saw someone reporting a bug similar to this and said to uncheck them. I ended up losing XP for each unchecked grey dailie. I reset the streaks to the best of my memory.

Finally, I checked my User Data Display and it says I received all of my daily drops today, but I got nothing today.

I'm disgruntled from the situation. I had great streaks, great HP and was really looking forward to today's drops. I was hoping I would finally hatch my final pets. Is there anyway I can get my drops for today?

**Comment by Alys** [comment]
These problems will be caused by this bug: https://github.com/HabitRPG/habitrpg/issues/4313. If it keeps happening, there's a workaround described near the top of the page ("What to do if you experience this bug often" heading).

You can estimate your streaks from Data menu -> Data Display Tool -> "Dailies History" section. Ask here if you're not sure how to use that data.

You can use Settings -> Site -> Fix Character Values to restore your lost XP and GP from unticking your Dailies.

I've reset your drop count to zero. Post here if that hasn't worked and we can reopen this issue.
