### ISSUE TITLE
Equipment has disappeared

### ISSUE THREAD

**Issue by BastetsBard** [HabitRPG/habitica#4661]
Hi all! I have lost a piece of equipment that cannot be re-bought after dying. It was a cool-colored Party Robe, gotten for the anniversary celebration. I still have the Absurd party robe! What can be done about this?? Thank you!

User ID: 58596652-2861-4208-ade7-d51db0dc8c09
OS: Window 8.0
Browser: Google Chrome Version 40.0.2214.94 m

**Comment by Alys** [comment]
You wouldn't have lost that due to dying. Unfortunately there was a bug
that resulted in it being given to players who weren't supposed to have it,
and it would have disappeared when we fixed that bug. It was always
intended for those players who have celebrated two birthdays with us now.
If you're here next year, you'll definitely get it then!
