### ISSUE TITLE
Consider using auth.local.username in chat mentions (nix profile.name support)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4665]
@paglias is working on sending email notifications (opt-in/out) when mentioned in chat. He has concerns with how it's currently handled by highlighting either `profile.name` and/or `auth.local.name`, and there's also some fuzzy logic in the highlighting re: spacing, any mentions within a chat message (eg, your name is `E`? good not getting notif'd), etc. 

My thought was along the lines of Trello. You can look them up by typing @ either by username or profile.name, but what it enters into the chat message is username exclusively. So: how to handle Facebook users? One option is to assign a username of their `auth.facebook.id` upon registration. They're currently allowed to change their username anyway, if they don't like that value.

Additionally, IIRC @Alys & I were discussing (as part of an oauth2 migration, including bits discussed at https://github.com/HabitRPG/habitrpg/issues/4499), possibly removing `user.profile.name` altogether. One big reason is it causes confusion when users try to log in ("it's not recognizing my username" when turns out they're entering their `profile.name`). If we do this, we could default `auth.local.username` to Facebook users' full name, and everything would seem exactly as-is at present. 

Thoughts? I'm kinda spitballing here, so feel free to shoot me down
##

**Comment by Alys** [comment]
I'm not really in favour of removing user.profile.name. I like that users can have a profile name in chat that isn't linked to their login, and that therefore does not need to be unique. 

One reason is that it allows a user to do things like temporarily change their name without fear of not being able to change back. There are legitimate reasons for this. For example, one guild has this thing where if you fail to do a task in time, you change your name for a day  to "[realname] wearer of the cone of shame" which I think is cute, and is a useful motivational tool. But if your profile name had to be unique (ie, if it was the same as the login name), then you wouldn't want to do that in case a new user signed up on that day and took your original profile name.

What if we put a "reply" link after every post, and if you clicked that link, the user's name was inserted into the message box (exactly as if you'd used the current @.... feature) BUT ALSO the user's uuid was recorded (possibly in a hidden field) as being related to the message you are typing, and that's how the code works out who to send the notification to. You would HAVE to use the "reply" link for a notification to be sent. We would probably want to remove the @... feature to encourage users to use "reply" instead. We often do messages that are replies to two or more people at once, so it would have to be possible to click "reply" on multiple messages and have all the names added to the text box and all the uuids recorded for notifications.

People might want to sign up with Facebook but not have their Facebook account visible in any way to other users. Defaulting `auth.local.username` to Facebook users' full name and then using `auth.local.username` in chat might have privacy implications.

We might want to get rid of `auth.local.username` and just have either Facebook login or email addresses used as login names, to simplify the login system.

**Comment by Alys** [comment]
And because I didn't make it clear in that comment:

I've decided that I'm not in favour of removing `user.profile.name` because of those reasons. But that's just my opinion. :) 

People might want to sign up with Facebook but not have their Facebook account visible in any way to other users. Defaulting `auth.local.username` to Facebook users' full name and then using `auth.local.username` in chat might have privacy implications.

We might want to get rid of `auth.local.username` and just have either Facebook login or email addresses used as login names, to simplify the login system.

**Comment by crookedneighbor** [comment]
@Alys I like your reply button idea. What happens if someone starts writing a reply to someone, but then decides not to, deletes the name, but the uuid is still attached to the message. The old recipient will still receive the message, so would we need some kind of clearing mechanism when the `@name` is deleted?

What if clicking the reply button generates a text box below the message the person is replying to. This will have the added benefit of allowing the person writing the message to reference the original message they are responding too.

I'd also like to institute some kind of conversation ID, so messages with the same conversation ID can be grouped together. IE, if a conversation has at least 2 messages, a conversation button appears in the message. Clicking it opens a modal with all the messages in that conversation (in chronological order?) and lets you reply directly to it.

That could get hairy with email notifications though. If someone responds to a specific message, and then 10 other people respond to the original message using the text box at the bottom of the conversation, should the author + the 11 other people all get email notifications whenever someone sends a message in the conversation box?

Anyway, just some ideas.

**Comment by crookedneighbor** [comment]
Sorry, re-reading and you are proposing that we do away with the `@name` feature, but that's all the more reason to figure out how to cancel the reply if a separate reply box isn't populated.

**Comment by Alys** [comment]
@crookedneighbor Good ideas. The name(s) could be placed in a visible field
just above the text box, with an x next to each to remove that name (and
remove the invisible uuid). When the message is sent, the names are placed
at the start of it. Or something vaguely like that.

**Comment by lefnire** [comment]
I'm sorry, I remember now - it was _that_ conclusion we'd come to: doing away with username, and having signin be email address.

**Comment by Alys** [comment]
I didn't even remember that we'd come to a conclusion. :)

**Comment by librarianmage** [comment]
What is the status on this?

**Comment by Alys** [comment]
@MathWhiz still suggestion-discussion

**Comment by librarianmage** [comment]
@Alys Oh, that makes sense. Thanks!

**Comment by LunarGem** [comment]
Is anyone trying to continue the discussion on this? I was thinking that the display name should be just that, a display name, and that mentions etc. should use the username (which is changeable, so that shouldn't be a problem). Hovering over a display name could reveal the username for mentions, the suggestion menu could show display name and username (like Celestine, Rogue Lady of the Moon (@LadyCelestine)  or something like that). The mobile app version would require some thinking, but does this idea carry any merit?

**Comment by LunarGem** [comment]
*bump* Especially since the new site doesn't work on mobile, being able to use an alternate name for users with long names or foreign-language names would really help.

**Comment by Alys** [comment]
@LunarGem This is still under discussion by the staff, along with related
changes to how players are mentioned and how they log in. It has some
complexities because login names can be real-life names (privacy issues),
might violate the Community Guidelines (must stay hidden until changed by
the player), and don't yet exist for players who use only social media
authentication. An easier way to mention people is definitely desirable but
might not be done in the short term.

**Comment by LunarGem** [comment]
Just making sure cause this is one of my favourite ideas. Perhaps names could be checked by a mod before posting is allowed? Idk just a thought.

**Comment by Alys** [comment]
Speaking as a mod, that sounds time consuming. :) We wouldn't check in advance but would recommend community members flag posts from users with bad login names (as they already do for bad display names). However the other points are more troublesome: a lot of players don't have login names, and the privacy aspect is important so we'd need to tell players well in advance that their login names would become public (we'd mention the Community Guidelines at the same time) OR we'd implement a short name in a way that wasn't linked to login details. So there's several reasons why it's still under discussion. While it is something we are considering as an enhancement, we have other important fixes to work on at the moment too.

**Comment by LunarGem** [comment]
Ok! When you want to start working on this I'd love to at least participate in designing it if my coding expertise isn't up to implementing it...

**Comment by Alys** [comment]
I'm closing this because staff are discussing it internally. A new, more precise issue will be opened if it's decided to proceed with something like this and/or staff will do the coding themselves. [internal link for staff reference](https://trello.com/c/jFYr8tJC/1064-kill-the-uuid)
