### ISSUE TITLE
Remove shipping field from paypal process

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4676]
The paypal checkout / subscription process currently asks for users' shipping address, which is unecessary. Steps for removal at https://developer.paypal.com/webapps/developer/docs/api/#payment-experience
##

**Comment by davidmanheim** [comment]
I've gone through the docs, and the HabitRPG source, and think I have identified how to do this a bit more completely than the fix submitted - in order to do it, you need to manually create a "payment experience", which requires the HabitRPG authorization keys, which obviously are not available publicly, but allows for a greater degree of customization.

Outline of How to fix:
Manually / Using Curl, create a new "Payment experience" using the HabitRPG Authorization: Bearer <Access-Token>. This can be done as shown here: https://developer.paypal.com/webapps/developer/docs/integration/direct/rest-experience-overview/
The key thing to change is that in the "input_fields":, "no_shipping": must be set to 1. (This will fix the open issue.) Obviously, the new "experience profile" can contain other cool things like the name and logo for HabitRPG.
Full Documentation here:
https://developer.paypal.com/webapps/developer/docs/api/#payment-experience
Once this payment profile call is made, it will return a JSON object with a "experience_profile_id"
(At this point, nothing has been done that changes anything.)

Now, to use this profile when processing payments, I think there is only one change needed. In
habitrpg/website/src/controllers/payments/paypalBillingSetup.js - After Line 102 - Add new Line:
    "experience_profile_id": <"experience_profile_id" returned above.>

This should, in theory, work for all the payments processes through this call - which I think is all of them that use Paypal, but I am unsure.

**Comment by remmz0r** [comment]
I have code for this that works with the REST api but I keep getting this bug when trying to use subscriptions. I've made a subscription for the $5/month plan. It wokrs fine for the single time payment.

> {
>  "err": "{\"response\":{\"name\":\"TEMPLATE_ID_INVALID\",\"details\":[{\"field\":\"template id is ?>invalid\",\"issue\":\"Incorrect Template >Id.\"}],\"message\":\"\",\"information_link\":\"https://developer.paypal.com/webapps/developer/docs/>api/#TEMPLATE_ID_INVALID\",\"debug_id\":\"5bf0fc160fcbc\",\"httpStatusCode\":400},\"httpStatus>Code\":400}"
> }

**Comment by davidmanheim** [comment]
It seems like the exports.createPayment function should use a template, while the exports.executeBillingAgreement doesn't use them at all.

**Comment by kristian-welsh** [comment]
A lot of this is going a bit over my head, i'll let someone with more experience take a crack at it.
