### ISSUE TITLE
Daily accidental completion bug

### ISSUE THREAD

**Issue by ryannutley** [HabitRPG/habitica#4678]
If you toggle a daily (check it accidentally and uncheck it again), you will receive coins and then be deducted coins again. The notifications show that the deducted number of coins is greater than the received number of coins.

e.g
+93    - adding the check mark
-96     - removing the check mark

**Comment by crookedneighbor** [comment]
Is that 93 gold or 93 silver?

Usually the discrepancy is due to the streak bonus. For instance, one of my dailies is worth 2 gold and when I click it, I get 2 gold plus 3 silver as a streak bonus (separate notification). When I uncheck it, I lose 2 gold and 3 silver as a single notification. Is that not the case with you?

**Comment by Alys** [comment]
This has to be silver; I don't think it's possible to earn that much gold from one Daily.

@ryannutley This has been reported at https://github.com/HabitRPG/habitrpg/issues/4497. If you want to follow the progress of the fix, you can subscribe to notifications (right-hand column).

@crookedneighbor Excellent point about the streak bonus. I hadn't thought of that. I'm noting your comment in the original issue.
