### ISSUE TITLE
Menu icon (top left) is not shown properly on mobile

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4691]
The menu icon in the top left corner of the top toolbar is not shown properly on mobile. I encountered this problem on Android 4.4 when using Chrome browser. I have attached screenshots in both landscape and portrait. The issue I refer to is circled in red.

Portrait
![screenshot_2015-01-31-15-09-55](https://cloud.githubusercontent.com/assets/878118/6219476/fb1f9ad6-b64f-11e4-851d-b0598f518e38.png)

Landscape
![screenshot_2015-01-31-15-10-15](https://cloud.githubusercontent.com/assets/878118/6219477/fb2bc02c-b64f-11e4-9bb9-2eab8841f813.png)

**Comment by crookedneighbor** [comment]
Looks fine on my iPhone. Can someone with an android device confirm?

It's using the html entity: `&#9776;` instead of a glyphicon, which is my best guess for the problem.

**Comment by Alys** [comment]
Confirmed on Android. I'd always assumed it was meant to be like that, but now that it's pointed out, yeah, it should have an icon in it.

**Comment by deilann** [comment]
It also doesn't show on Android w/ Firefox.

**Comment by ghost** [comment]
An idea, use another glyph instead of the one being used currently which resembles the menu icon. One of them that I could find is: `&equiv;` or 

## **≡**

A list of all characters that render properly can be seen at [copypastecharacter.com](http://copypastecharacter.com/all-characters) by viewing it on mobile. That is how I was able to find an alternate glyph.

**Comment by crookedneighbor** [comment]
Confirmed that it shows up on iOS.

**Comment by JacobFrericks** [comment]
The icon shows properly on my Note 3. I'm running cm12 (lollipop) and using Chrome.

This hasn't been fixed already, has it?

![screenshot_2015-03-01-08-41-27](https://cloud.githubusercontent.com/assets/5521414/6431247/253eb7cc-bfef-11e4-9fac-e3462192c2bd.png)

**Comment by deilann** [comment]
I'd like to point out that this is a usability issue for me -- it makes it really hard to press that button.

**Comment by Alys** [comment]
I propose using glyphicon-align-justify which looks like this:

![screen shot 2015-03-15 at 12 59 57 am](https://cloud.githubusercontent.com/assets/1495809/6652106/b48e9f9a-caae-11e4-8fd0-442e52776b41.png)

It's sort of like the three-bar icon &#9776; given by `&#9776;` but it's a glyphicon so we know it will work everywhere. Even if it's not perfect, we could make do with it until we decide on something better. Since this is a usability issue, a non-perfect fix is better than none.

PR here: https://github.com/HabitRPG/habitrpg/pull/4855. If no one complains in two days, I'll merge it. Note that that change affects **only** the website when viewed on mobile browsers. It does not apply to PC browsers.

Also, these might be related: https://github.com/HabitRPG/habitrpg/issues/3411 https://github.com/HabitRPG/habitrpg/pull/3412
