### ISSUE TITLE
Contribution to Design?

### ISSUE THREAD

**Issue by donatasben** [HabitRPG/habitica#4707]
Hello everyone,

I am a professional designer and recently got hooked up on HabitRPG, it seems to be helping with some habits and tasks. As I understand this is an open-source project, I would like to contribute some of my time and skill to it. Wiki instructed to create an issue here, so please direct me somewhere else where I could discuss this.

First, I would like to improve the home page that non-logged-in visitors see. Right now it is very basic, bootstrap-like, and I could give it some more appeal. I could at least clean up the layout, arrange better  spacing for texts. And fonts, I would like to introduce a heading font with more character and style, to give the website more unique playful identity. Something like https://www.google.com/fonts/specimen/Germania+One

I could create some mock-ups and change the CSS if approved.

I have ideas for the "app" part of the website too. I've already started tweaking a little for myself using userstyles ![userstyle](https://cloud.githubusercontent.com/assets/4421344/6240472/c88fbcd6-b717-11e4-9ff3-3869e6459f17.png)

I could move in small portions and continuously improve parts of the website.

What do you guys think and where is it more appropriate to discuss this? How is it better to implement improvements? Or maybe there is already something in the works concerning design? Would like to hear from you all and looking forward to contributing.

**Comment by SabreCat** [comment]
Habit strikes an odd balance--it needs to be aesthetically pleasing and usable, but it also needs to retain a certain "retro" feel to fit with the pixely sprite work. Some proposals similar to yours (e.g. the revamp of the health and XP bars) have had to step back a touch for those reasons.

All that's just words of caution, though. There are MANY ways the layout could be improved. Your suggestion of making a few small changes to start with will work well! I'd hold off on the landing page because there's an overhaul of that already underway, but making improvements to one of the other pages or UI elements would make a great first contribution.

You can also float ideas and solicit feedback on Trello or in one of the Guilds dedicated to site help, such as Aspiring Legends.
