### ISSUE TITLE
Graph money earned / spent

### ISSUE THREAD

**Issue by AnmAtAnm** [HabitRPG/habitica#4712]
Pop-up balloon for gold/silver should include graphs of the money earned, and possible money spent. Possibly a one week timespan.

The wiki suggests designing your reward costs based on how much you earn each day, but I don't see anywhere in the UI to retrieve that info.  I think that balloon would be ideal for a small spark graph, or similar.

May involve combining the gold / silver balloons into one larger balloon.  Really, the two numbers are just different decimals on the same value, and should be represented by one graph.

Purchases could be marked as events lines on the graph. Summary title of the new balloon might read "Earned XX gold, YY silver in the past week."
##

**Comment by deilann** [comment]
A bit of technical info:

There is no history retained about how much gold is earned (or XP for that matter) so it would require refactoring as adding a graph.

Adding tags.

**Comment by paglias** [comment]
This fits inside a larger discussion about recording a player's activity

**Comment by jeffg-dev** [comment]
Added $15 bounty but didn't see it show up here, so... https://www.bountysource.com/issues/8685226-graph-money-earned-spent

**Comment by Alys** [comment]
I'm closing this because it's a feature request that would involve a lot of rework in the back-end and it's not something that fits into Habitica's direction at the moment. However it could be requested on Trello if desired (Help > Request a Feature from the habitica.com website's menu). @jeffgreenca With this being closed, the money in bounty source should be returned to you automatically but please contact bountysource if there are any problems with that.
