### ISSUE TITLE
Losing HP and XP When I Sync

### ISSUE THREAD

**Issue by aspie-hufflepuff** [HabitRPG/habitica#4724]
This has happened a few times now, so I thought I'd post. Whenever I try to refresh my page, I lose massive amounts of HP and often some of my XP. This past time it even bumped me back down after I had leveled up. 

Also, when I refresh I sometimes find that my dailies are already checked off for the next day (even if I checked them off prior to the reset time), and nothing I can do will give let me click them, which means I lose my streak, the XP I would have gained (both from the coming day AND the previous day), and I lose HP from the previous day even though I have already checked them off. This is very frustrating and takes away much of my enjoyment of the game (not to mention throwing off my scheduling).

**Comment by paglias** [comment]
@aspie-hufflepuff could you tell us if when you check off a task you see a blue bar appearing on the top of page?

**Comment by deilann** [comment]
@aspie-hufflepuff 

It sounds like you're dealing with sync errors. Whenever you click off a task, make sure to let the blue bar completely finish before you click something else. Otherwise, you're sending the server too many requests at once, and while it'll look like you did them locally (what you can see) it won't be saved to the server, so until you sync or refresh, it'll look like you did them.

You can also use the [Data Display Tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html), which is linked under Data on the website, to see what the server thinks you've done wrt tasks. Then, you'll know if what you're seeing locally matches up with what's on the server.

I'm going to close this issue for now, but if we need to reopen it to investigate further (aka, if what I've said doesn't help you) feel free to reopen it.
