### ISSUE TITLE
Can't turn off site tour on Beta with iPad

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4726]
All of a sudden on the beta site I'm getting the tour for introducing someone to the site. The Previous/Next buttons don't work in mobile Safari (iPad) so I can't progress through the tour or interact with the beta site at all (the regular site is fine so I'm not stuck, but I notice some changes on the Beta site so I'm wondering if it's a result of a recent update?).

**Comment by lefnire** [comment]
Good find, thanks! Will definitely make sure this is fixed before hitting prod

**Comment by Verabird** [comment]
Same thing is happening for me. I'm on chrome, MacOS X.

**Comment by lemoness** [comment]
We also need to make sure that previous users don't trigger the tour
automatically unless they click "show tour." What happens if a user who has
more than just the tutorial tasks DOES open the tour? Can they still
proceed through it?

**Comment by Verabird** [comment]
The first step of the tour it requires you to check off a to-do before it allows you proceed. I added a test to do and was able to do that. However when it gets to the reward step, I couldn't figure out how to get past that. I clicked on a reward and added a new one and clicked on it but the "next" button is still grayed out.

**Comment by lefnire** [comment]
Fwiw just hit escape on desktop. I'll add an "ok" or "done" button as an interim. Perhaps even disabling tour on mobile. The thing that concerns me is that the user was not able to click previous or next went on mobile, I'm going to investigate that

**Comment by ghost** [comment]
FWIW, I can't turn off +/- when setting up Habits either (used to be able to). Not sure if that's related to the Previous/Next buttons not working. The Habit problem is in both mobile Safari and mobile Chrome.

**Comment by deilann** [comment]
@lefnire Can we close this?

**Comment by crookedneighbor** [comment]
@deilann I'm taking over on this, so leave it open for now.

**Comment by deilann** [comment]
awesome!

**Comment by lefnire** [comment]
i've removed the tour for mobile. I've also added a "Hide" button anyway. Pushing to beta now

**Comment by lemoness** [comment]
Tour as new player works very well! Some exceptions:

SHOULD BE FIXED PRIOR TO RELEASE:
- ~~Since the gold is not highlighted on the Rewards slide, I'd like to change the text to make it a little more clear what they have to do to proceed:
  "Buy a Reward with the gold you just earned!"~~
- ~~There's no way to know that the tour has ended, since the Next button is also grayed out when there's an action you're supposed to do. Is there any way to make that slide have a "finish tour" button instead of "Prev" and "Next"?~~

IMPORTANT BUT CAN BE DELAYED IF TIME-CONSUMING:
- On final screen customization screen, scrolling scrolls the tour offscreen. Not important enough to delay the tour's release, but figured I should mention it:
  ![screen shot 2015-03-06 at 1 37 53 pm](https://cloud.githubusercontent.com/assets/3494081/6536938/b4cc902e-c406-11e4-8f15-6c79e7eba65c.png)
- When I click "Hide," there is no indication of how to get it back - and clicking "Show Tour" restarts it again from the very beginning. It would be nice if it had a memory. If this is difficult, it can be left for a later time.
- If they've already gone through the tour, is there a way to make it remember so that they can click next without having, for example, to add a new To-Do and check it off again? If you use the Previous button to get back to a slide, it remembers and keeps "Next" enabled, but not between sessions. Again, if this is too hard, we can postpone it for now.

**Comment by lemoness** [comment]
ALSO IMPORTANT: Just realized that if you click "Hide," the tour restarts from the point you were at whenever you refresh or reopen the page. This is fine for new users, but terrible for older ones when combined with the fact that it doesn't remember that they've done it and let them skip ahead. 

Maybe we should just temporarily get rid of the "Show Tour" button and link under "Help" until these issues have been fixed? I don't think they're used much, except for the Classes Tour.

**Comment by lemoness** [comment]
Another very important reason that we should disable the "Show Tour" ability until we can fix it so there is a "memory" of whether you've taken the tour before - you can get trapped in the Rewards page if you don't have enough gold to buy anything!

Actually, that could also be an issue for a user who hides the tour, spends gold on something, and then refreshes before they can buy the Training sword.

Anyone have ideas for how to address this?

**Comment by lemoness** [comment]
Here's an idea; might not be great, but could work:
- New users do not have a "Hide button" and must go through the whole tour before they can do other things. If they close the page and reopen it, they're on the same tour.
- Show Tour is temporarily disabled for all users, so only newbies are doing this tour. 
- Once we have the other issues fixed, we re-enable the "Show Tour" function. Users who have completed the tour once can then do it again, and they have a "Hide" button.  When they "Hide" the tour, it never reopens unless they re-enable it through the menu.

How does that sound for people?

**Comment by Alys** [comment]
That sounds okay to me. I worry though about users quitting permanently if they get bored with the tour and don't know how long it will last. Can we say at the beginning something like "This tour lasts x minutes"?

**Comment by lemoness** [comment]
I'm not as concerned about that as I am about the issues with "Hide" and
the fact that the current tour is broken - I want to get this new version
out sooner than later if we can - but I think that once the Hide button
issues are fixed, we should definitely A/B test whether or not having the
Hide button improves or worsens the rate at which we lose users. It may be
that more users quit when there is no Hide button but the ones who get
through it retain better overall, or vice-versa, or any combination.

@lefnire - Any thoughts about this, since you're the one programming it?

**Comment by lefnire** [comment]
@lemoness tour _does_ have memory. "Show Tour" actively resets its memory to step 1, so we can play with this any which way we need. Chance we can do a G+ soon and we can spitball via screenshare?

**Comment by lefnire** [comment]
Some thoughts: 

> Actually, that could also be an issue for a user who hides the tour, spends gold on something, and then refreshes before they can buy the Training sword.

When they buy _anything_ it progresses, so we're good there.

As for all the Show Tour / Hide issues, how about this. Memory of last step completed (like currently is). We rename "Show Tour" to "Restart Tour", and it restarts but remembers your last position and inserts as many "Next" buttons as necessary to get you there. Would that work out?

**Comment by lefnire** [comment]
And until that's built, I'll just hide "Show Tour" (if that's the agreement)
