### ISSUE TITLE
Make edit mode UI less sparse

### ISSUE THREAD

**Issue by chekunkov** [HabitRPG/habitica#4730]
I'll be happy if task edit mode UI takes less space and fits my screen. One way to achieve that is to replace input fields labels with placeholders.

![habitrpg___your_life_the_role_playing_game_and_skype](https://cloud.githubusercontent.com/assets/744331/6314304/4cf1bc50-b9e2-11e4-8d44-146cb9853f8e.png)

**Comment by kangabell** [comment]
Some people consider inline placeholders to be bad UX practice (e.g. [this article](http://baymard.com/blog/mobile-forms-avoid-inline-labels)) – but IMO in this case it would be an improvement. Curious to see what others think though...

**Comment by ghost** [comment]
I second this. I also think here it would be enough to have inline placeholders.

**Comment by kangabell** [comment]
It also can be noted that it seems like most everywhere else in the app there are inline placeholders used, so changing these would be consistent.

**Comment by Alys** [comment]
One thing to keep in mind is that the inline labels will not be shown if there is any text already in the field (e.g., for the default tasks) so if a new user sees instructions related to the 'Text' or 'Extra Notes' field, they will find it harder to work out what that means.

**Comment by Alys** [comment]
One thing to keep in mind is that the inline labels will not be shown if there is any text already in the field (e.g., for the default tasks) so if a new user sees instructions related to the 'Text' or 'Extra Notes' field, they will find it harder to work out what that means.

That [Mobile Form Usability: Never Use Inline Labels](http://baymard.com/blog/mobile-forms-avoid-inline-labels) article does criticise inline labels rather severely:
_'During the mobile e-commerce research study we observed numerous test subjects struggle with fields that had inline labels. This echoed what we observed during our e-commerce checkout research where subjects also struggled with inline labels – only the problem proved even more severe on mobile.'_

ping @anitaycheng (our usability expert)

**Comment by kangabell** [comment]
The article also mentions an exception though, for cases in which there are only 1-2 fields, which applies in this case.

**Comment by chekunkov** [comment]
@Alys I agree with @kangabell 

> In summary, the general advice is to avoid inline labels in forms. The exceptions are single standalone fields or “singular-purpose-two-field-frequently-used forms”, where inline labels may be used if space efficiency and aesthetics are significant concerns.

Also the article is more about mobile usability and this issue is about web app usability. Scrolling all the time to fill details (and what is important to me - set difficulty) is pain.

**Comment by AnitaYCheng** [comment]
Agree with @kangabell, kind of. _Login_ screens with 2 text fields are so commonplace and standard, that people just know what to do despite lack of labels. But only if there's just username and password - any more than that, you're going to have to explain what's going on. :)

For this particular case, I would leave the labels on top (for the reasons @Alys mentioned, especially with pre-filled content), and just tighten the spacing. No need for there to be quite so much room between the label and the field.

I would also rename "Text" to "Title" since "text" is too generic.

**Comment by Alys** [comment]
I've added a post to the Aspiring Coders guild to let them know that this issue exists, and to highlight Anita's comment above.

To any programmer who takes this up: It doesn't have to be just the Text/Title and Extra Notes field that you modify to tighten the spacing. The remainder of the task edit form would benefit from similar changes. Just be careful to not crowd it all together too much. :)  Also be aware that the different types of tasks and reward have different fields, so you'd want to look at each of them. When you make a pull request, please provide screenshots showing all changes for all task types.

You might like to initially provide one or two screenshots showing just a few proposed changes, before you do a full pull request, if you'd like feedback about your ideas before making code changes for everything.

**Comment by stran9er** [comment]
Another alternative to labels is the use of descriptive text within the
fields themselves.  Especially for those commonly used fields such as
username and password.

**Comment by crookedneighbor** [comment]
Late to this party, but I thought [this article on accessibility and placeholders was interesting](http://www.paciellogroup.com/blog/2011/02/html5-accessibility-chops-the-placeholder-attribute/)

Basic takeaways:

**Vision Problems**: 

> The default colour of the placeholder text, in browsers that support placeholder, is not of sufficient contrast with its default background colour.

**Memory Problems:**

> For keyboard users this can be problematic as they must read ahead of current focus when filling in forms.
> Users, especially those with memory impairments will not have the text label available for reference at the same time as filling in a field.

**Comment by crookedneighbor** [comment]
Also, I agree that "Text" should be changed to "Title". Does anyone else think that the title input should be pushed above the checklist button? So the order would be:

Title
Checklist
Extra Notes

**Comment by chekunkov** [comment]
> Does anyone else think that the title input should be pushed above the checklist button? So the order would be:
> 
> Title
> Checklist
> Extra Notes

@crookedneighbor yeah, I was thinking about that as well, but shouldn't that be separate GH issue?

**Comment by crookedneighbor** [comment]
Since it's all related to user interface changes, I don't think so.

**Comment by chekunkov** [comment]
As I can see you're member of the organisation so you might have better understanding of how issues are organised here. I'm cool with that. Just noticed that your last comment has nothing to do with reducing spacing in edit mode UI and this issues is not about user interface changes in general.

**Comment by AnitaYCheng** [comment]
**YES!** One of my pet peeves, for sure. 

Well, if we wanted to go one better, making the title itself editable instead of having it appear twice in the editor. You do have to put a title into the quick-add field before you're able to use the button to add the task/open the editor, at any rate. It always takes me for a loop.

**Comment by crookedneighbor** [comment]
@AnitaYCheng one benefit I can think of for having it appear above as well as in the text input is that doing so will allow the user to see any markdown or emoji that they're writing in the title right away. If it was just an input, the user wouldn't see it until they saved their changes.

**Comment by Alys** [comment]
'_one benefit I can think of for having it appear above as well as in the text input is that doing so will allow the user to see any markdown or emoji that they're writing in the title right away._'
Agreed. I use that feature very often.

**Comment by AnitaYCheng** [comment]
@crookedneighbor Ooooooh, that would be a nice addition too!

**Comment by nthomsn** [comment]
Been messing with this. I think it does save a lot of space and it doesn't look bad.
![UI](https://cloud.githubusercontent.com/assets/8507561/6541801/0060329c-c4b2-11e4-901c-8c38bfc20a75.png)
It might look better if the title was pulled down right above the input box and centered. Comments?

**Comment by Alys** [comment]
@nthomsn I'm sorry but we decided we would not use placeholders instead of field labels for usability reasons (e.g., Anita's comments above and [this one](https://github.com/HabitRPG/habitrpg/issues/4730#issuecomment-75449591)).  However if you'd like to make another proposal for changes, that would be great! Read through the comments here to see what we decided on, especially these ones: https://github.com/HabitRPG/habitrpg/issues/4730#issuecomment-75424292 https://github.com/HabitRPG/habitrpg/issues/4730#issuecomment-75424750 https://github.com/HabitRPG/habitrpg/issues/4730#issuecomment-75449835

**Comment by AnitaYCheng** [comment]
@crookedneighbor Another thought about having the emoji appear as the user is typing...Facebook has it such that any emoticons you type while posting or commenting (on desktop) appear as an image immediately after you type it in the text box. How difficult would that be to implement? 

The repeated title areas still reads as unclear and bothersome to me...

**Comment by marcelklehr** [comment]
When editing a task, I always think, "man, this would be way better in a pop over".
(My issue was closed in favor of this one, so I'm re-submitting this here.)
The advantage of a pop over is that you can use screen estate, particularly the width of the screen, so you don't need to scroll.

**Comment by deilann** [comment]
One major disadvantage to a modal, I think, is that you couldn't have two
tasks open to edit at the same time. Sometimes I'm copying information from
one to another and it'd be really annoying if I'd have to close out of one
task to open the other.

**Comment by AnitaYCheng** [comment]
@deilann That's a good point! Although tightening the spacing might help for that - I now use HabitRPG has a task tracker at work, and will move checklist items between days, if I don't finish something and wil have to continue the same task the following day. It's bothersome to scroll up and down because you can't see the checklist items for multiple days at once. 

Then I wondered how difficult it would be if we could move checklist items between tasks....

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/pull/4821
