### ISSUE TITLE
Cannot cancel subscription

### ISSUE THREAD

**Issue by emipow** [HabitRPG/habitica#4747]
I noticed that my credit card has not been charged for my recurring monthly subscription since December. It should have been charged on January 16 and on February 16. I've been receiving the monthly item drops for some reason, but my consecutive subscription value has not been increasing. 

Since I'm now pretty sure that missing the January payment was not a fluke, since this month's payment didn't process either, I wanted to cancel my subscription and re-subscribe. After clicking "Cancel Subscription" and confirming the cancellation in the pop-up dialog, a blank page loads displaying this error: 

```
{"err":"Cannot read property 'current_period_end' of null"}
```

When I go back to Settings > Subscription, it still shows my "active" subscription and if I try again to cancel the same error appears. 

I'm on OS X 10.10.2 and get the same error in Chrome v. 40.0.2214.115 (64-bit) and Safari v. 8.0.3 (10600.3.18).  

My User ID is 9d78a60b-5528-4d75-9404-9bd1bc4028f2. 

Thanks for your help.

**Comment by crookedneighbor** [comment]
Ping @lefnire

**Comment by Alys** [comment]
@crookedneighbor FYI : https://github.com/HabitRPG/habitrpg/issues/4420#issuecomment-69428997

I can fix this in about 7 to 8 hours if no one gets to it before then. :)

**Comment by Alys** [comment]
@emipow You should now be able to cancel your subscription. You will be able to start another one if you would still like to - you should do that within the next week to ensure that you don't lose your count of consecutive months subscribed (but tell us if you need more time for any reason!). I am not going to remove the monthly items that you've gained over the past two months. 

I'm closing this issue now because I believe everything should be sorted out for you, but if you have any problems at all or notice anything odd or inconvenient, please do comment here and we will keep helping you!

**Comment by emipow** [comment]
Looks good now, I was able to re-subscribe without any issues. Thank you!
