### ISSUE TITLE
Change Party / Guild Leader Automatically When Inactive and/or have multiple group leaders

### ISSUE THREAD

**Issue by pollockjj** [HabitRPG/habitica#4748]
_edit by Alys 2017-03-18: [this comment](https://github.com/HabitRPG/habitica/issues/4748#issuecomment-282563457) starts a discussion about having multiple group leaders_

----

I posted this to the Tavern and @crookedneighbor suggested I "Please open a support ticket on Github with [my] user id, the party's id, and the leader's user id (found by clicking on the avatar of the leader in the party header). We'll do some investigating and see if we can help you out."

my user id: ce70f261-3612-433d-b626-4724a8ae5b86
party id: ab945ee5-e7c7-4469-a267-0112bc05dbd0
leader id: 03f0d805-6430-4f6f-8513-e7a9746b2b32

Either myself or userid 3cac2d3c-f724-46d4-89f8-0727f3ca2039 have expressed a willingness to take over party leader duties. We want our leader to stay in the party (and hopefully she comes back to us someday soon) but her prolonged absence hampers our ability to effectively manage the group.

Thanks.

##

**Comment by crookedneighbor** [comment]
@pollockjj Okay, first step is to PM the party leader. You can do that by clicking on their avatar and pressing the message icon. That will now send them an email letting them know they have a private message to read. If they don't get back to you in 3 days, report back here.

Second step for us will be to set up a system to transfer party leadership when the leader has not logged in for x amount of days. Mods, any thoughts on the number? I was thinking 15 days, but that's kind of a long time to be away from Habit. Maybe 7? With an email warning at 4 and 6 days?

ping @lemoness and @sugarfiend @veeeeeee thoughts on number of inactive days and how many warning emails to send? Copy for email? Should this apply to guilds as well as parties? Should resting in the inn (a planned absence) be taken into consideration?

ping @paglias Thoughts on best way to send that email out? Should it check on party page load, or is there a better more efficient way to do this?

**Comment by pollockjj** [comment]
PM'd her a day ago, so I will report back in two days (or sooner if she responds).

Thanks.

**Comment by lemoness** [comment]
I think 15 days, with a warning at 10 days, personally.

**Comment by lemoness** [comment]
That way we won't get as many people who are on vacation. Should we check
for the inn? Should inn give a bonus of time (warning at 15, switched at
20)?

**Comment by crookedneighbor** [comment]
The other question is, should it be automatic, based on seniority? Or should a button become available to "Steal Leadership"?

Should a system message appear in party chat announcing the change?

**Comment by AnitaYCheng** [comment]
The time period to count "inactivity" depends on a lot of things. To play Habit properly, you have to check in every day, and a week of inactivity seems very lax for a party leader. But @lemoness is right, people could be on vacation and have every intention of coming back regularly afterwards. (Although one hopes they would let their party know, if there was a quest being suggested!)

I'd do a warning email a few days before (3 is good I think), as well as the day of.

**Comment by L1st3r** [comment]
Sort to drag this old issue back from the dead, but my party is dealing with issues surrounding this. Why don't we just implement multiple leaders? That way if one leader is away on vacating or something else, the party doesn't suffer? I'd be willing to look into implementing this in a week or so if nobody has an issue with the functionality

**Comment by Alys** [comment]
Copying @L1st3r's related comment and my reply from the Aspiring Blacksmith's guild to keep the conversation in one place:

**Lister**: Has anyone play with the group/party logic? I'm thinking of adding the ability to add "admins" to parties, and would like to ask a few questions before performing brain surgery...

**Alys**: Interesting idea! I know there's been feature requests that sound similar to that. What would those party members be able to do that would be different than for regular members? How would it look and work from a user's perspective? By the way, we typically use "admins" to refer to those staff and moderators who have the ability to access Habitica's database for troubleshooting and bug fixes, so we'd need to find a different term for the party members with extra privileges, but that's just a naming problem, not saying that the feature can't be done. :) However I'd recommend that you wait for staff or mods to say it's okay to proceed before you code, just in case it turns out that the feature shouldn't be added for any reason. We can certainly give you advice about the code once it's approved!

----

@L1st3r Getting back to your post here, would you like to go into more detail about how you're thinking of implementing this? I still suggest not starting the code until you've seen approval to proceed here. A couple of things to note are:

- It cannot be a breaking change for the [API](https://habitica.com/apidoc/) (i.e., all current API functions must continue to work as they do now, although *adding* features is fine).
- Guilds should probably be treated in the same way as parties for consistency.
- Groups that have been upgraded with group plans should probably not allow multiple leaders since the leader who upgraded the group is paying real-world money and must retain full control over the group.

**Comment by L1st3r** [comment]
So let's change the name from admins to party execs for now. To start with I'd just like to give them the ability to kick an unruly party/guild member. 

I didn't think about paying groups, I guess I'd be ok with that since a passing leader is probably going too stay active.

I don't think any APIs would break (tho I only took a cursory look at the code, and node it's not my strongest language) I would think we add another section for execs, and allow them to have the ability to add other admins, and kick non admins from the party. The leader could kick out an admin. 

At the end of the day what I'd like to fix is the issue with an MIA leader and players who are getting the group killed during quests. We have no way to Foxx the Dorian other than starting a new group, which we'd rather not do

**Comment by librarianmage** [comment]
Would a "party exec" be able to kick another "party exec" off?

**Comment by L1st3r** [comment]
Initially only the leader could. Future enhancements could have a voting system created where each admin could vote. But now we're getting more complicated.

**Comment by Alys** [comment]
I'm going to close this because it's a feature request rather than an actionable bug report, and we do have plans to expand the "managers" feature in Group Plans to work in parties as well.
