### ISSUE TITLE
Dailies Still Not Resetting 

### ISSUE THREAD

**Issue by Rickdude** [HabitRPG/habitica#4754]
I'm putting this in as a new issue because the previous one has "closed" attached to it.  My dailies are still not resetting after the problems of yesterday.

**Comment by deilann** [comment]
What is your User ID?

When did you come out of the inn?

What is your Day Start time?

If you came out of the inn _after_ your day start time, your tasks aren't going to reset until your day start time has passed again.

If this does not help, please comment on the previously closed issue. You don't need to open new issues in order to get our attention. :) We get email notifs for coments on closed issues as well, which makes for much better organization. (Frex: I have no idea which ticket you're talking about! But if you had responded there, I'd have more context.)

**Comment by Rickdude** [comment]
Okay, I'll wait until tomorrow.  I went back into the Inn because without completing my dailies (which I obviously can't do) I am going to die.  I'll spend the gold for a potion.

**Comment by crookedneighbor** [comment]
@Rickdude Being in the inn will prevent your dailies from resetting.  It effectively freezes the game so your cron code, the thing that checks which dailies are done and which are not, does not run. It's designed for if you're sick or on vacation and just need a break from your dailies.

**Comment by Rickdude** [comment]
Thanks, Blade. I hadn't realized that, but it makes sense. I'm out of the Inn and will wait to see if I refresh tomorrow. Sounds like I will. 

Rick 

----- Original Message -----
