### ISSUE TITLE
the daily habit has been greyed for several days. even though they are supposed to be on repeat daily

### ISSUE THREAD

**Issue by simkimsia** [HabitRPG/habitica#4765]
![screen shot 2015-02-27 at 12 57 40 pm](https://cloud.githubusercontent.com/assets/245021/6407691/513c1132-be80-11e4-8065-d918fd69b69f.png)

**Comment by Alys** [comment]
Please see this issue for an explanation and fix: https://github.com/HabitRPG/habitrpg/issues/4742 or alternatively [HabitRPG Outage Instructions -> Unplanned Tavern Visit](http://habitrpg.wikia.com/wiki/HabitRPG_Outage_Instructions#Unplanned_Tavern_Visit). In brief, you need to check out of the Inn. If you have any questions after reading that, please comment here. We will see them and help you, even though I'm closing this issue now since the bug no longer exists.

**Comment by simkimsia** [comment]
Apologies. Didn't realize I was in inn.

**Comment by Alys** [comment]
No worries! Not your fault. It was an unusual situation. We're finding a lot of people are having the same trouble and we're actually brainstorming ways to help them at the moment! :)
