### ISSUE TITLE
App and website not refreshing

### ISSUE THREAD

**Issue by kingkilter** [HabitRPG/habitica#4766]
Both the mobile app and the website are not refreshing daily so I'm not getting credit for doing my daily activities because it's not popping up as due

**Comment by Alys** [comment]
Please see this issue for an explanation and fix: https://github.com/HabitRPG/habitrpg/issues/4742 or alternatively [HabitRPG Outage Instructions -> Unplanned Tavern Visit](http://habitrpg.wikia.com/wiki/HabitRPG_Outage_Instructions#Unplanned_Tavern_Visit). A recent Bailey message in the website also has some other information about this (let us know if you'd like help with seeing it again). In brief, you need to check out of the Inn. If you have any questions after reading any of those references, please comment here. We will see your questions and will definitely help you, even though I'm closing this issue now since the bug no longer exists.

**Comment by kingkilter** [comment]
I have already checked out of the inn and it still hasn't refreshed

**Comment by Alys** [comment]
Yes, as with any Resting in the Inn event, your Dailies will reset tomorrow (although those two links give you advice about how to force them to reset sooner if you wish to).

**Comment by Alys** [comment]
That is assuming that you checked out of the inn only today. If you did it yesterday or the day before, please tell us.
