### ISSUE TITLE
Dailies aren't resetting

### ISSUE THREAD

**Issue by bendwithpride** [HabitRPG/habitica#4770]
My dailies haven't been resetting.  They remain gray unless I uncheck them.
my user ID is 3e59c99c-d4e1-4b52-b98c-517644b23112

**Comment by Alys** [comment]
Please see this issue for an explanation and fix: https://github.com/HabitRPG/habitrpg/issues/4742 or alternatively [HabitRPG Outage Instructions -> Unplanned Tavern Visit](http://habitrpg.wikia.com/wiki/HabitRPG_Outage_Instructions#Unplanned_Tavern_Visit) on the wiki. In brief, you need to check out of the Inn and then your Dailies will reset tomorrow (although those two links give you advice about how to force them to reset sooner if you wish to).

I'm closing this issue now since there isn't a bug any more, but if you have any questions, please do comment here! We will see your questions and we will answer them.
