### ISSUE TITLE
User Data Display Tool displaying different information than HabitRPG website/app

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#4774]
I use the page at https://oldgods.net/habitrpg/habitrpg_user_data_display.html to checkwhether habit really received my updates. This evening it did something new. 

1) I had already checked off various dailies this morning.
2) I got home and checked off some more. Habit was still producing popups when I clicked the re-fetch data button on my https://oldgods.net/habitrpg/habitrpg_user_data_display.html tab.
3) That site appeared to have seen very little of what I'd done that day. No screen shot, so I'm not sure whether or not only newly clicked dailies were still to do.
4) I clicked the re-fetch data button, and found myself with 3 dailies yet to do, in its opinion. One of these had been checked off this morning. 
5) I refreshed habitrpg using the browser's refresh button. Rather to my surprise, no tasks became undone, and no xp was suddenly deducted - everything it had been showing pre-refresh was still there. _Two_ blue dailies, which matched two of those showing at https://oldgods.net/habitrpg/habitrpg_user_data_display.html  
The other daily from that undone daily list is grey with a checkmark, as expected.

**Comment by Alys** [comment]
This is what I wrote in the Tavern a few minutes ago: reload the HabitRPG website. I suspect that some of the changes you are seeing there have not been properly synced to the server. The Data Display Tool reads data directly from HabitRPG's server, so it will have all of your data that has been stored in HabitRPG's database.

That's still a likely possibility. Your browser might not be clearing its local storage properly. Try logging into HabitRPG on a different browser - you'll probably find that what it shows you matches what's in the DDT.

Another possibility is that you have a duplicate account, which can happen due to a bug. Go to your API screen in HabitRPG and make sure the user ID matches what's in the DDT.

The way you've written your report implies that you click several tasks very rapidly. That's not advisable as it can cause sync errors, leading to behaviour similar to what you describe. Clicking more slowly is always recommended. See http://habitrpg.wikia.com/wiki/Sync_Errors for details.

**Comment by Alys** [comment]
@ArlieS I have adjusted the title of this issue to better reflect what's happening and to include some keywords that will be useful for people searching for a similar event in future.

**Comment by ArlieS** [comment]
Yes, I click tasks rapidly - then check with the data display tool. That's my answer to  http://habitrpg.wikia.com/wiki/Sync_Errors. Losing an update immediately after I made it is normal, though uncommon.

But this is different - the update was made 8 hours ago, and even after refreshing my habitrpg screen (via the browser refresh) it's still showing as checked off. 

The API tokens match (I had to relogin to https://oldgods.net/habitrpg/habitrpg_user_data_display.html to verify that). It's still showing a third daily incomplete, that's checked off on my HabitRPG screen.

![screenshot from 2015-02-27 19 27 36](https://cloud.githubusercontent.com/assets/4530463/6424648/bce64282-beb6-11e4-9072-a7d532f8a33c.png)

![screenshot from 2015-02-27 19 27 50](https://cloud.githubusercontent.com/assets/4530463/6424654/cf63387a-beb6-11e4-876c-41ec847e4be8.png)

**Comment by Alys** [comment]
Did you do the test in another browser? If not, please do that.

Keep refreshing your main browser. It's probably just holding on to incorrect information.

**Comment by ArlieS** [comment]
Interesting - logging in from a different comp gave me the three undone tasks. 

So why isn't this browser refreshing?!?!

**Comment by ArlieS** [comment]
and wow - got 338 xp when I refreshed the original browser yet again. Huh?!?! At any rate, the original browser now shows the task as undone, finally.
