### ISSUE TITLE
Daily Tasks are not refreshing

### ISSUE THREAD

**Issue by Pinky-Peach** [HabitRPG/habitica#4776]
It seem that my dailies are not un-checking themselves. This has been going on for about 3 days now. They're all grey, and have definitely all been grey and stayed checked for at well over 24 hours.

**Comment by Alys** [comment]
Please see this issue for an explanation and fix: https://github.com/HabitRPG/habitrpg/issues/4742 or alternatively [HabitRPG Outage Instructions -> Unplanned Tavern Visit](http://habitrpg.wikia.com/wiki/HabitRPG_Outage_Instructions#Unplanned_Tavern_Visit) on the wiki. In brief, you need to check out of the Inn and then your Dailies will reset tomorrow (although those two links give you advice about how to force them to reset sooner if you wish to).

I'm closing this issue now since there isn't a bug any more, but if you have any questions, please do comment here! We will see your questions and we will answer them.
