### ISSUE TITLE
Add button for sorting parties

### ISSUE THREAD

**Issue by AAorris** [HabitRPG/habitica#4778]
Currently, changing the sorting of your party is not reactive or immediately learnable:
- Users have to refresh the page, even though they get the blue progress bar at the top of their screen
  - This means that users will change sorting and expect to see something change, with no results.
- The text that describes to reload the page is currently not prominent.
  - Users will expect some sort of submit button if a page refresh is involved. And indeed, this would be a simple solution.

What do you guys think of this? It might work as is for people who take the time to explore it, but my initial feeling is that it isn't easy for new users to understand.

**Comment by Alys** [comment]
I believe we do have code that forces a refresh of the page, although I personally am not sure how it works. I think instead of having a button to cause the refresh, the refresh could happen automatically when the user selects the new sort order - if we're going to be forcing a refresh then there's no need to have a button as well, and adding a button that exactly replicates the browser's own refresh button isn't ideal. However I'm not sure that forcing a refresh is actually good for usability. It might be better to just increase the prominence of the text that describes the need to reload. @AnitaYCheng, what do you think?

**Comment by AnitaYCheng** [comment]
In terms of usability, forcing a refresh is accepted as long as it comes from the user. Automatically forcing a refresh randomly to get the latest content is no good, but if they choose an option (especially if there's only one thing to choose), forcing a refresh to reflect their choice is accepted.

My only concern with a forced refresh, in this case, is that the progress bar is pretty small and people might not know if the page is refreshing, and it often isn't instantaneous. If there was a "Submit" button of some kind with an animated loader that appeared when pressed, at least they could be assured that their input registered.

**Comment by AAorris** [comment]
My thoughts on usability here would be that users need to either see something change, or be notified about the status of a change (success, failure, confirmation).

With bootstrap and angular, we have other options too.
- You could have the party sorting actually updated and solve the problem immediately without a refresh
- You could have a modal that appears with the status of the change. Breaks user flow, might not be the best option
- You could have a tooltip that pops up somewhere
- You could append a status text under the element after the change, like a green 'your settings have been saved' after the request to update the sorting information returns.

My personal feeling is on investigating the last point. What do you guys think?

**Comment by AnitaYCheng** [comment]
The last idea makes the most sense to me - immediate feedback is extremely important, and some might not notice their party is updated. We could put the status text where the drops are - no tasks are checked off while someone is fiddling with the settings, and it would be consistent with already-existing actions.

**Comment by rdhammond** [comment]
Is it too late to work on this one? I haven't gotten into the codebase too much, but I would think it would be fairly straightforward to reshuffle the avatar tiles after an AJAX resort. I know from the discussion there's a standard "Push refresh to see changes" box though, so I don't want to waste anyone's time :)

**Comment by Alys** [comment]
@rdhammond It would certainly be popular if you can get it to work with minimal impact on loading time. If you'd like to work on it, go ahead. As with any change, we can't promise in advance that we'd accept it, but I'd like to see an instant resort working!

**Comment by rdhammond** [comment]
Nah, I expect it'll have to pass reviews and coding standards and &c. But yeah, I think I might be able to do this and make it work. No promises though!

**Comment by rdhammond** [comment]
Boom! Since the update happens through Angular automatically, there's no postback needed, and the changes should be instantaneous.

For feedback's sake, I retained the existing "Party updated" message, but I took off the "refresh to see changes." That message was only getting used by the party resort, so I elected to change the existing message instead of creating a new one. It will obviously need to be re-translated if the pull is accepted :P
