### ISSUE TITLE
[Exploit] Ticking and unticking a daily gains many items/quest drops

### ISSUE THREAD

**Issue by reenenlaurie** [HabitRPG/habitica#4783]
It seems that if you tick and untick your daily many times, you can earn many of the same type food, as well as quest drops (moonstones in my case).

I believe you can earn up to the point that the sync is complete, so slower or offline connections could probably gain more goodies than really quick connections.

User ID: 5b71bd34-22dc-4af8-a9c2-9c7bca83ec37

I am using Chrome on WIndows 7 64b.

**Comment by Alys** [comment]
This has been reported already but we don't really consider it to be a bug. Please see the response to this issue: https://github.com/HabitRPG/habitrpg/issues/4626  If you have any questions or still feel that it is a problem, please add a comment to that issue (we'll see it even though that issue is closed).
