### ISSUE TITLE
Chat Alerts from Groups Kicked from Persist

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#4802]
If a user is kicked from a group, any chat alerts they had persist, leaving them with an alert they can click on, generating an error that says they cannot access the group.

When a user is kicked from a group, all alerts for that group should be removed from the user object.

**Comment by rdhammond** [comment]
Do you have a little more information on how to reproduce this one? I tried having a party member sent a chat message and got no alerts from it.

**Comment by rdhammond** [comment]
Oh, nm. It's under the notifications tab. Working on this one, then.

**Comment by rdhammond** [comment]
Okay, we can do this one instantaneously if a person leaves a group of their own accord. Getting kicked is quite a bit trickier, since that's a status push to a seperate user account. What do we currently do when you're on the party screen and are kicked? That'll be a good indication of what direction we should go with removing the chat messages, i.e. when is party status updated and how do we react.

Honestly, the way to go here is probably...
1. Remove party notifications from the server when a user is kicked/leave
2. Remove party notifications from the client's browser instantly if they leave
3. Put up a courtesy "You are no longer in that party." message to catch anything else that falls through. (We may have one? It sounded like it wasn't user-friendly enough though)

That's my thoughts on the matter. I've got changes ready for 1 and 2 but don't want to go farther until I'm sure where to go :)

**Late Edit:** Actually, it looks like we automatically redirect to the Guilds page when a user leaves, so we really don't even need #2!

**Comment by TheHollidayInn** [comment]
I'm not seeing any message for when a user is kicked when trying to reproduce this. In fact, I see there is an issue for that: https://github.com/HabitRPG/habitrpg/issues/4801 . I think you should use your solution to #1 to solve this ticket and submit a second request solving #3 for the issue I linked.

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/pull/5596
