### ISSUE TITLE
Dailies not resetting two days in a row

### ISSUE THREAD

**Issue by mollyweasley** [HabitRPG/habitica#4805]
(my first two days using habitrpg)  

I've seen the work-around, just wondering if you're still working on this.  Is this a problem all your users are having everyday?

**Comment by crookedneighbor** [comment]
@mollyweasley Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token).

**Comment by mollyweasley** [comment]
ecb564c6-1f22-40d3-9bdc-e722e06ac2c8

**Comment by mollyweasley** [comment]
After I wrote the comment, it occurred to me that this morning I may just
not have refreshed my browser yet.  I started to unclick the checks on the
dailies and all of them turned green/yellow after one (or two??).   But
yesterday, for sure, it hadn't reset.  Refreshed browser a bunch of times.

**Comment by gretchenx7** [comment]
Hi, 

My tasks haven't refreshed since Sunday either. =[ I've tried different things that I've read that have helped people fix it, but it doesn't do anything for me. The sync button before I go to bed at night doesn't do anything. The only thing that seems to have worked in the past to get rid of this issue is being actively using habitrpg at midnight when the day switches over - but I can't stay up until midnight to do that. I've even tried setting the day start at a different time, but that didn't help either. This is really starting to aggravate me and taking the fun out of Habitrpg.

I'm using chrome, and my user ID is: 917df4c4-b625-4d9f-83ea-56d1b873370f.

**Comment by vishwasshrikhande** [comment]
I too am having the issue with dailies not resetting after midnight, my user ID : b02c933e-b976-430e-b26f-5f85e2125ffc

**Comment by deilann** [comment]
Vishwas Shrikhande, you are in the inn. Everyone was checked into the inn
when the servers went down due to an influx of registrations from imgur. If
you go to Social on the website or Settings on the mobile app, you can
check out.

On Thu, Mar 5, 2015 at 9:16 PM, Vishwas Shrikhande <notifications@github.com

**Comment by vishwasshrikhande** [comment]
thanks @deilann i too ventured on other releamns and found out i was in the inn. checked out now, thanks for replying

**Comment by Alys** [comment]
@mollyweasley and @gretchenx7 If this problem is still happening, please see the first comment in https://github.com/HabitRPG/habitrpg/issues/4313 , inclding the Advice section.

If it happens again tomorrow, please post here again. Let us know if it is all of your Dailies that have not reset or only some of them.

**Comment by architarious** [comment]
Huge thanks to @deilann.. after spending about 6 hours combing through github and the habitrpg forums I just finally found this. I don't do quests (don't know how to do quests), so i had no idea that i was checked into the inn. I'm finally checked out.. hopefully this fixes my problem of never taking damage and daily's not resetting, even though i've synced and ran the reset values command, after midnight (while in the inn).

**Comment by Alys** [comment]
@architarious When you're having a lot of trouble finding something, please do use the Help -> Ask a Question option. We appreciate it when people try to find information themselves but I'm really sorry you had to spend so much time looking for an answer! When you do want to search, the [wiki](http://habitrpg.wikia.com/wiki/) is likely to be much more useful than the forums.

**Comment by mollyweasley** [comment]
Something weird happened since last night.  This morning none of the things
I did yesterday evening seem to have registered (most obviously the Royal
Magus Robe I bought) and a weird selection of tasks were refreshed, but not
all of them.

I'm considering just calling this day a wash since I spent most of it doing
taxes anyway . . .

**Comment by mollyweasley** [comment]
And I just noticed it duplicated one of my To-Do tasks.

**Comment by Alys** [comment]
@mollyweasley You would have been hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313. I am sorry about that! There is an advice section near the top to help you recover from the damage. For the duplicated task, delete the one that is closer to the bottom of the list. Deleting from the top tends to not work.

**Comment by mollyweasley** [comment]
Again, a bizarre selection of dailies didn't refresh. Seems pretty random.

**Comment by Alys** [comment]
Yes, I am sorry, it is still the  #4313 bug. I am going to close this issue since it is the same bug, but you can follow the progress of the bug in that issue. There is a subscribe button in the right-hand column if you would like email notifications.

**Comment by mollyweasley** [comment]
Sorry, I don't have time to figure out how to post a new bug, but I just
wanted to let you know right away:

It seems to be letting me edit the FAQ area.  I'm not signed in.  I didn't
click save, but it let me add characters.  I'm sure you don't want this . .
.

The reason I was looking there was because my stats are behaving very badly
right now.  Last night I again had the undone but checked task issue, so I
unchecked all my undone tasks and restored my gold.  Now my EXP is stuck at
NaN (it's full but doesn't go up to the next level).

Just thought you'd like to know . . .

**Comment by deilann** [comment]
The FAQ is on our wiki, which is set to let anyone edit it, even if they
are not signed in. This is on purpose. If someone changes something that we
don't find quite right, ti's very easy to revert those changes.

As for the NaN issue... go to Settings > Site and click "Fix Character
Values"

Set your XP to a number and save the changes. NaN means "not a number" in
codese. It should then be fixed. :)
