### ISSUE TITLE
Error Message in Tasks, telling me to go to Chrome ... dashboard?  I use Firefox on a home computer

### ISSUE THREAD

**Issue by MMikhail1** [HabitRPG/habitica#4808]
I have repeatedly gotten this error message, I don't even have Chrome loaded on my computer.

**Comment by crookedneighbor** [comment]
@MMikhail1 That's just the default message when there's an error, regardless of what browser you're using. Do you have any additional information about what happens that prompts the message?

@lemoness, regarding the text of the message. We really should change it, because it's very confusing for users that don't use Chrome. File is here: https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/generic.json#L64

What do you want it to say?  Perhaps: `(if you're using Google Chrome, see the console for more details).`

**Comment by Alys** [comment]
I'd be in favour of not mentioning the console at all. Much of the time it will be a known error and we won't need the console details. For users who understand the console, there's a decent chance they'll provide the errors even when not prompted, and for other users it can be confusing (to no purpose when we don't need the error messages).

**Comment by crookedneighbor** [comment]
In that case, this is the only place that string gets called: https://github.com/HabitRPG/habitrpg/blob/a8cb0fd4e9785f257ca5edbc9c62dba7577d5ca2/common/script/public/config.js#L40

**Comment by lemoness** [comment]
Can we replace the error message with something that contains more helpful
advice to the average user?

**Comment by SpenserJ** [comment]
This can be closed now, thanks to @TheHollidayInn's changes in #4998
