### ISSUE TITLE
Language settings.

### ISSUE THREAD

**Issue by bakami** [HabitRPG/habitica#4823]
I can's set the language settings on any site, beside features, and the rest of the advertisement related pages. Even if I do, when I go back to my profile it automatically changes back. shouldn't english be the default one anyway?

**Comment by Alys** [comment]
We don't make English a global default because that would be unfair to our users from non-English-speaking countries. Instead, the HabitRPG website is supposed to pick up the language settings from your PC. If it's not doing that for you, we'd like to know - please tell us what language your PC uses in general.

Are you changing the HabitRPG language from [Settings -> Site](https://habitrpg.com/#/options/settings/settings)? If so, that setting should stick and work well. If that's what you're doing and it's not working, please tell us your user ID (see step 6 [here](https://github.com/HabitRPG/habitrpg/issues/2760)).

**Comment by bakami** [comment]
I wanted to change it to english, hungarian felt off. It's, I guess a habit of mine.

Yes, I found the site settings, sorry for not paying more attention, and thank you very much for the help.

**Comment by Alys** [comment]
No worries! I'm glad it's working for you! :)
