### ISSUE TITLE
Cron made boss deal 100% of my health, while all dailies were complete and damage listed did not add up

### ISSUE THREAD

**Issue by TheRepublic** [HabitRPG/habitica#4826]
We are currently fighting the Seahorse Stallion (for The Dilatory Derby quest, which I bought in gems), and on cron tonight the boss dealt 100% of my full health (50 HP). I had completed all my dailies and it still dealt 8.4 damage to the party, which somehow is equivalent to 50 damage and killed me.

I am not sure why it happens but hope no one else goes through the same thing, and maybe I can get my level, gold, and sword back? That would be cool.

Thanks for your support.

User ID: 17afaed3-28a6-4491-9faa-1fdb25fa12fc

Party ID: 5ee7f484-65dc-4dfd-bf6a-2a75ee28ef5f

Browser/OS: Chrome 40.0.2214.115/Windows 8.1

**Comment by Alys** [comment]
Please go to your party page (on the website, not the app) and click the Fetch Recent Messages button. Then look in paoty chat for other damage messages from you party mates. Are there any that explain the extra damage?

Note also that when the boss does damage due to your own Dailies, you yourself also take extra damage from the Dailies themselves (the same damage you would take if you weren't on a quest).

Any time you feel that a death was unjust, you can go to Settings -> Site -> Fix Character Values to adjust you stats.

**Comment by TheRepublic** [comment]
Alys,

Thanks for your the quick comment and assistance. I was aware of fixing the values through the site tab, but would be most interested in solving the bug so that no one goes through a similar situation.

The total damage from the party menu was nothing close to the 50 that would kill me. In fact, I had leveled up today, so it was a bit of a surprise lose all the health in one swoop. I had completed all of my dailies, but the boss only received 1 damage from me, and inflicted a whooping 8.4 to my party mates (an embarrassing moment I had to apologize for). Oddly enough, right now (after cron) it shows all my dailies checked off.

I am not really sure what the root of the problem is, but I am almost certain it is a bug.

Thanks.

**Comment by deilann** [comment]
Can you show me a screenshot of your party page? Feel free to blur out any personal chat or names, if you so desire. The bug you're experiencing is this one: https://github.com/HabitRPG/habitrpg/issues/4313 Unfortunately, we're not 100% sure what causes it. The good news is that it doesn't repeat for most users. If it does happen to you again, read the info on what to do if you experience this bug often.

**Comment by TheRepublic** [comment]
Deilann,

Here is a screenshot for your viewing pleasure. Enjoy the comradery and forgive me for the language.

![image](https://cloud.githubusercontent.com/assets/11401368/6569676/22faff5c-c6c5-11e4-9402-83d5c908084c.png)

**Comment by deilann** [comment]
You don't use any extensions, like the Chrome extension, do you?

**Comment by TheRepublic** [comment]
Nope, I wasn't aware of them in the first place.

**Comment by deilann** [comment]
Okay. Here's what I think happened:

You said you leveled up yesterday. With #4313 what we think is happening is that Habit things you did the Dailies tomorrow (hence them being checked off today, even though you did them yesterday!) so the damage was applied to your pre-leveling up amount of HP. Because in Habit's mind, you didn't level up until _tomorrow_.

I'm going to close this ticket, so you can follow the issue in #4313. I'm sorry we can't give you a more satisfactory answer, but we are working hard on #4313. And for most folks, it doesn't repeat. If it keeps giving you issues, see the advice in that ticket. If, for some reason, more things happen that you think aren't related to #4313, feel free to comment here. We still receive emails for closed tickets.
