### ISSUE TITLE
Cannot see the PM you are responding to

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#4827]
When you're responding to a long PM, it's very frustrating that the modal it brings up keeps you from seeing the content of the message you're responding to.
##

**Comment by ardavis** [comment]
I think that's a great idea. I haven't contributed to HabitRPG before, but I'm going to attempt this one. I'd love to contribute. :)

**Comment by khipkin** [comment]
Suggestion: add [interface] label.

**Comment by Alys** [comment]
I've marked this as "interface" and also "help welcome now" because even though it's something we could fix during an upcoming website improvement project, I think it would also be appropriate to fix it earlier if anyone's interested in doing it. It's also a very specific issue rather than site-wide, so would need to be documented somewhere for the project. Other admins are welcome to change the labels and/or close if desired.

The best approach might be to display the message you're responding to at the bottom of the modal that you're typing in to.

**Comment by librarianmage** [comment]
Isn't there a similar Issue?

**Comment by khipkin** [comment]
@MathWhiz These are the only other PM-related issues I could find:
- #6540 Not told that someone has opted out of PM's until AFTER you have composed the message
- #5205 Visiting Inbox Via Email Alerts Does Not Clear PM Notifs
- #4648 Flag issues: doesn't work in PMs, needs two flags before they can be cleared, etc

**Comment by librarianmage** [comment]
Oh. I was thinking about #6540

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Inbox messages are now handled very differently, so I am closing this ticket.
