### ISSUE TITLE
Subscription with paypal doesn't work

### ISSUE THREAD

**Issue by greatgreenArcleseizure** [HabitRPG/habitica#4830]
Hey

I want to subscribe but i don't use credit cards. Whenever I try to subscribe with Paypal it says -after logging in to paypal-account- that my request couldn't be processed and i should return to habitRPG.

There is no option for paying the subscription via bank-transfer.

User-ID
00c4c436-f7e8-4ed0-9985-47f8966f820c

Browser: Firefox 36.0.1 For Ubuntu Canonical 1.0
Add-on: Noscript (allowing HabitRPG, Github and Stripe.com)
System: Ubuntu 14.02

**Comment by Alys** [comment]
Unfortunately this is a known problem for people in some countries due to a bug in paypal that we haven't been able to work around yet. You can however still subscribe by giving yourself a gift subscription - that's a once-off payment for one or more months (your choice) and it gets around the paypal limitation. There's instructions on the wiki at [Subscription: Gift Subscriptions](http://habitrpg.wikia.com/wiki/Subscription#Gift_Subscription) but ask here if you have any questions or have any trouble doing it!

**Comment by greatgreenArcleseizure** [comment]
A friend of mine told me about the possibility of giving yourself a gift subscription. I have done this a few weeks ago, but have problems with it, too. I will open a new thread because of this.

**Comment by Alys** [comment]
Thank you!

I'll close this one because we're tracking the paypal issue at https://github.com/HabitRPG/habitrpg/issues/3381
