### ISSUE TITLE
Canceling subscription inconsistent with keeping block subscriptions

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4840]
From a user: 

> I was/am currently in possession of subscriber perks (nearing the end of a 3 month block).
> I decided to buy more time; in a 3 month block.
> 
> I picked the 3 month option (cost: $15), the payment was made, and I then unsubscribed (because I don't like automated recurring payments unless absolutely necessary).
> 
> Unfortunately, instead of calculating me as having paid for 3 months, it says my subscription is due to expire in 1 month (+ the credit I have remaining from the previous block).
> 
> This is the second time this has happened. 
> I believe a similar issue cropped up when I bought one of the new 3 month subscriptions just as my old subscription (ie: before the new subscriptions setup) expired.
> 
> Is this perhaps some sort of old code that assumes any subscription being canceled only lasts 1 month?

I've seen this from time to time, but haven't pegged the issue (plus it's inconsistent) 
##

**Comment by lefnire** [comment]
One thing that seems to be at play, if `user.purchased.plan.dateTerminated` is in the past (they had a plan before, re-upping now) then it might be adding to _that_ date and not the current date?

**Comment by zelq** [comment]
This just happened to me. I cancelled the recurring, but only got 1 month of my 3.

**Comment by Alys** [comment]
@zelq We need to know your Habitica account to be able to help you. Please go to Help -> Report a Bug and see step 6 (or just tell us your UUID if you already know how to find it; it is different than your user name).

**Comment by zelq** [comment]
Grrr, meant to include that. Sorry.
It's be67f33e-abb0-4242-8974-50b4704df771

**Comment by Alys** [comment]
@zelq I can't find a record of your payment. Can you please email admin@habitica.com and tell me which payment option you chose, and either which email address you entered into the payment form (for a credit card payment) or which email address you use to log into the payment processor website.

**Comment by Jolanda5** [comment]
Is this still an issue? Is somebody working on this? Can be worked on this at the moment?

**Comment by Alys** [comment]
@Jolanda5 This issue is best not worked on at the moment. Habitica's API and related code are undergoing redevelopment at the moment, and that includes the code related to subscriptions. Any changes made for this issue would conflict with the new API code.

I've actually just made a post about that in the [Aspiring Coders](https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f) guild. Drop in there and if you have any questions, you're welcome to ask them there.

**Comment by Jolanda5** [comment]
Now again =D is this still an issue?

**Comment by Alys** [comment]
@Jolanda5 I believe it's still a problem. I've checked with the other admins and none have given any objections to you working on this, so if you'd like to, please do!

**Comment by Jolanda5** [comment]
@Alys Thank you for your answer. But I'm afraid I don't have enough time 
right now, the day I asked I was on a coding camp but now that it's over 
I have to go back to studying, I am really sorry. I'll tackle it when I 
have time again if it's not done by then.

Am 30.05.2016 um 02:47 schrieb Alys:

**Comment by Alys** [comment]
@Jolanda5 That's okay! Thanks very much for letting us know, and I'm sorry we didn't reply on the day!

**Comment by Hus274** [comment]
So I was trying to look into this today and I had a couple questions.
1.  From the wiki: http://habitica.wikia.com/wiki/FAQ#How_do_I_cancel_my_subscription.3F if you follow the link, there's no button to cancel a subscription. Is this becasue I'm not subscribed? If so, is there a way to "purchase" a subscription on my local instance to test this?
2. I see that there's a script ( cancelSubscription.js ) which I assume is only run manually if an email is received by an admin but the code there makes the termination date now + 1 month. So in reference to this example, it wouldn't matter what the existing termination date is, it would result in a month of time from now being the new subscription date which sounds exactly like the bug here. If this is not only run manually, it seems the likely culprit. Either way, it should probably either be updated or removed. Can someone advise?

**Comment by Alys** [comment]
`./migrations/cancelSubscription.js` is only ever used manually, and in fact probably hasn't been used by admins for a long time. It was written back when there were only one-month subscriptions, and so the one month period in it did make sense then. However you can ignore it for the purposes of this issue. If admins ever used it again, they'd modify it as needed for the specific case they were using it for. Much the same applies to anything else in the migrations directory. They're either one-use scripts that are kept for the purposes of <strike>clutter</strike> archiving, or they're modified as needed for each time they're run.

You are correct that you're not seeing the cancel button because you're not subscribed. The easiest way to create a subscription in your local install test account is to manually change the account in the database to insert data like this, which I've taken (with modifications of the customer ID value) from one of my real-site accounts:

```
    "purchased.plan": {
            "extraMonths": 0,
            "gemsBought": 22,
            "mysteryItems": [],
            "consecutive": {
                "count": 28,
                "offset": 0,
                "gemCapExtra": 25,
                "trinkets": 11
            },
            "planId": "basic_12mo",
            "paymentMethod": "Paypal",
            "dateUpdated": "2016-06-01T22:00:02.623Z",
            "dateCreated": "2015-12-26T02:52:54.436Z",
            "customerId": "I-HE12345678"
        }
    },
```

**Comment by Hus274** [comment]
Thanks Alys! Has this been happening for all the payment types or just one of them? I see that the logic to get the date when canceling is slightly different for each of the three payments types, stripe, amazon, and paypal. Specifically, I'm wondering if this happened when people were paying with Amazon

**Comment by Hus274** [comment]
I believe I've found the issue. Amazon payments doesn't have a concept of when the subscription ends so it's assumed to be 30 days from the last billing date (this is inaccurate for any subscription type that is not one month).

So in the original case posted here, the user subscribed to a three month package. This set the last billed date to today. Then when we call cancelSubscription API, we send the nextBill date as the last billing date + thirty days which results in the code setting the subscription to expire in thirty days instead of the three months that the subscription has already been paid for. 

Can one of the admins potentially test and confirm this is the issue in production? All that should be required is following the original post.
1. Purchase 3 month subscription using amazon as a payment method
2. Cancel subscription
3. Confirm that the new dateTerminated of the plan is 30 days from now, not at the end of the subscription.

**Comment by Hus274** [comment]
I can probably test this out too if need be, it's relatively inexpensive.

**Comment by Hus274** [comment]
I think that it makes sense in this case to add another subscription field specific to amazon payments here as there's already a specific field ( lastBillingDate ) for this kind of use case in the subscription object. As the method that creates the subscription already has a concept of months that the subscription applies to, I would save that information to the database when the subscription is created. This way, upon subscription cancellation for the amazon payment method, the time that the subscription is terminated can be the lastBillingDate + 30 days \* subscriptionMonths (the new field). This should take care of the issue. 

Is it ok to add a new field like this to the DB?

**Comment by SabreCat** [comment]
We have had recent reports of that behavior in production.

Adding a field to the database is OK if it's the best solution for the problem!

As part of this fix, we'll want to get tests in place to ensure we're doing this correctly across all payment methods. I was investigating this some myself, and I have a suspicion we may be relying on `lastBillingDate` even when it doesn't exist.

**Comment by Hus274** [comment]
I'm having a hard time writing tests for the subscribeCancel method in amazon.js. The only existing test around it is an integration test and I'm not seeing a way to mock out the amzLib.closeBillingAgreement method so that the call doesn't return a 500 response. 

I'm also not sure quite how to make a unit test around a GET method. It seems like this should be a unit test, all I want to do is verify that the nextBill is set correctly.

Any thoughts?

**Comment by Hus274** [comment]
The other thing I can think of is to not send a next bill for amazon as it really doesn't exist and we're just making something up for it. Then the subscription cancellation can handle null. I think that this actually makes more sense as this could easily be expanded for new payment methods that don't support subscription based payments and simply record a one time payment. This would allow all those cases to be handled in the same spot keeping the behavior consistent.

I think I'm going to go ahead with this approach for the time being.
