### ISSUE TITLE
negative subscription credit

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4846]
It says I have "-2.95 months of subscription credit." I use to donate monthly, then I canceled, and now I am donating again monthly.
![snapshot2](https://cloud.githubusercontent.com/assets/5521453/6618420/3d25d5d4-c899-11e4-8fbf-c1f3295b1571.png)

Shows same thing in Firefox and Chrome.
##

**Comment by mustard-jedi** [comment]
same here... -13.55 months.

![screen shot 2015-08-18 at 6 18 02 am](https://cloud.githubusercontent.com/assets/2805854/9317894/25dd51fe-4571-11e5-84d9-b741c481dc16.png)

**Comment by crookedneighbor** [comment]
@breezedem sorry for not responding sooner. Somehow I missed this when it originally came in. 

@Alys @paglias Any idea why this is happening?

**Comment by Alys** [comment]
From memory, it happens when a subscription ends and then a new one is restarted after a break.

It's harmless and has no effect on anything, except if the subscriber is given a gift subscription (which would normally make the credit months go positive).

When we're told the user IDs (from Settings -> API) of people with negative credit months, we can set them to zero. 

Other actions needed (which I really should have thought of before now):
- [ ] Adjust code to set credit = 0 if credit < 0
- [x] Write migration script to set all current negative values to 0

I'll do this as soon as I can, if no one gets to it before me. It won't be until at least this weekend though.

**Comment by lovesthesoundof** [comment]
Same thing happened to me - I then resubscribed for a single month and immediately cancelled, just to get that one month, and now the following appears:

"Canceled Subscription - Subscription will become inactive on 02/03/2016"

As you can see from the date of my post, that is in the past. Hm. I can still buy gems with gold as if subscribed, and I have a pending mystery item box sitting around in my inventory, but I have no idea when my subscription is **actually** going to lapse...

**Comment by Alys** [comment]
@lovesthesoundof Sorry about that! Please email admin@habitica.com. Tell them your User ID (to find out how to get it from either the website or app, see step 6 of the [Help > Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions), and also what service you used to make the subscription (PayPal, Amazon, or credit card) and what email address is associated with that service.
