### ISSUE TITLE
Lost gems despite not buying anything due to bug with "Unequip Pet, Mount, Background" button

### ISSUE THREAD

**Issue by frillsdev** [HabitRPG/habitica#4857]
Hi, I started off today with 21 gems that I got through my subscription (gold -> gems). This afternoon I noticed that I only have 14 gems, and have therefore lost 7 gems. I've been scouring my inventory to see if there is something I bought by accident, but I can't find anything new!
I did get a 'Server Unreachable' error earlier today after casting my rogue pickpocket spell, but that is it.. Nothing out of the ordinary, I'm baffled!

My UID is 2ebecf01-1cc2-4cc2-b7d1-739bbdc0e78e
Today I have used Chrome (on my Mac) and the iOS mobile app.

**Comment by frillsdev** [comment]
May I add that no avatar items have been unlocked either

**Comment by deilann** [comment]
Log out and then log back in. Does the number of gems that it says you can
purchase show 7 more? In other words, are they not lost, but showing as not
purchased?

**Comment by frillsdev** [comment]
It doesn't change - still the 3 gems left to purchase with gold this month.

**Comment by frillsdev** [comment]
The way I worded it makes it sound as though I purchased the gems today - I didn't, I've had 21 gems for a few days now.

**Comment by deilann** [comment]
Someone will investigate this for you soon. :) I just wanted to make sure
it wasn't an easy answer.

**Comment by frillsdev** [comment]
Oki dokes. Thanks :)

**Comment by Alys** [comment]
@teganmm I'm sorry this happened! I have given you back your seven gems. Please let me know if it is not correct now.

I am trying to work out how this happened. At some time in the past few days, did you try to buy a background and it didn't work? Or did you go to the Backgrounds page at all?

The reason I ask is that your account has an odd entry in the place were purchased backgrounds would be listed, as if a non-existent background had been purchased (the entry is pasted in below for our other devs to see). This would not have been caused by anything you had done wrong! It's definitely from some glitch but I am not sure what triggered it. 

I think it is unlikely to happen again, but please do tell us if you notice any other gems going missing!

```
        "background" : {
            "undefined" : true
        },
```

**Comment by frillsdev** [comment]
Yes, the gems have been correctly restored - thank you!
I have definitely visited the backgrounds page in the past few days as well as today, however I have not attempted to purchase one (mainly because I'm still gearing up and chosing one to match!)

Actually! _eureka_

I used the "Unequip Pet, Mount, Background" button in the costume section today, and noticed the loss of gems shortly after - that would surely be where the bug lies!

**Comment by Alys** [comment]
OMG. Thank you so much for picking that up! That was a clever thought! I'll get that fixed right now.

**Comment by frillsdev** [comment]
Yay! No worries, should have thought of it earlier tbh.
I'll close the issue here, as it looks like we have gotten to the bottom of it.
Good luck squashing that bug :bug:

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/9199c6c7e2d0891eca2bc6a58532366501265c4b by removing the Backgrounds option. (I'll put it back in once I've done a proper fix that allows it to be used safely.)

Thanks again @teganmm. You thinking of that so quickly saved us from a lot of other bug reports!

**Comment by Alys** [comment]
proper fix: https://github.com/HabitRPG/habitrpg/commit/44259925e46ecc5d064ebd290c1d0ba100a97e9e
