### ISSUE TITLE
Quest items stack up when a task/daily is unchecked and checked again.

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4864]
For quest that require users to collect items (for example : _A Stern Talking-To_), if you gain a quest item by completing a task, then uncheck that task, the quest item stays awarded. Then, when the task is checked again, a new quest item may be earned.
I tried checking and unchecking a daily a few times, and counted quest items with the _Data Display Tool_. I confirm that they stack up, and the count can go up really fast, by just checking and unchecking repeatedly.
As far as I can tell, either unchecking a task/daily should reset the quest item, or checking it again should not award a new quest item.

**Comment by Alys** [comment]
This has been reported before and we're really not concerned about this kind of "cheating". If a player wants to do that, that's up to them. Please see https://github.com/HabitRPG/habitrpg/issues/4626 for details. If you have any questions or comments, please put them in that issue so that we can keep the conversation in one place.

**Comment by ghost** [comment]
I searched for an existing report but couldn't find this one. Sorry for the duplicate.

**Comment by Alys** [comment]
No worries. :) I've made the title of that issue a bit more descriptive so someone searching for quest items in future will have a better chance of finding it.
