### ISSUE TITLE
To-do not going away when checked

### ISSUE THREAD

**Issue by MsMadGirl** [HabitRPG/habitica#4870]
I have a to-go item that will not go away when checked as complete, and often duplicates instead. If I try to check off both the original and the copy, it gives me the credit, then takes it away, and neither item disappears. Deleting it does nothing at all. 

ef140088-589d-4e9c-9053-c972799944b2

**Comment by Alys** [comment]
Are you seeing two or more of that item in the website at the moment? If so, could you please try deleting them starting with the one closest to the **bottom** of the list?

If that doesn't seem to work immediately, please view your completed To-Dos, untick any duplicates that might be there (so that all instances of that To-Do are now marked as not completed), and then go back to the active list and try deleting starting at the bottom again.

I'm sorry this is so annoying! From what we've seen in the past, this might work.

**Comment by MsMadGirl** [comment]
Thank you, it’s fixed now.

-- 
Rebecca MadGastronomer
Sent with Airmail

On March 16, 2015 at 10:53:11 PM, Alys (notifications@github.com) wrote:

Are you seeing two or more of that item in the website at the moment? If so, could you please try deleting them starting with the one closest to the bottom of the list?

If that doesn't seem to work immediately, please view your completed To-Dos, untick any duplicates that might be there (so that all instances of that To-Do are now marked as not completed), and then go back to the active list and try deleting starting at the bottom again.

I'm sorry this is so annoying! From what we've seen in the past, this might work.

**Comment by Alys** [comment]
Thanks very much for letting us know!
