### ISSUE TITLE
weird day reset issue

### ISSUE THREAD

**Issue by whimsicality** [HabitRPG/habitica#4878]
So yesterday I cleared my dailies early.  No timezone change should have affected that, and nothing had been affected by daylight savings time that I know of before that.  Today I didn't get a chance to check off things until this evening - but half the things are checked off and I've taken damage I shouldn't have.  I thought maybe I'd been wrong and hadn't refreshed last night so maybe I'd checked off half the list late, and maybe that's the case.  But if it is, I should have been hit by the reset again and I haven't been. So I'm not sure what that was about.

My ID is e62e4381-9be6-45f0-9db5-bfa4120a34f2

**Comment by titaniafaery** [comment]
I had the same issue yesterday and today.

User ID:  7d823432-bca8-4680-b3a8-996fe54bdec6

**Comment by Alys** [comment]
This is an example of the bug described here: https://github.com/HabitRPG/habitrpg/issues/4313 

I'm sorry you were both affected by it! Have a look at the Advice section near the top of that page, especially if you notice this happening to you more than once. You don't need to read the entire issue below that.

I'm going to close this now since we're tracking the bug in that other issue but if you have any questions, you can post them to that issue and we'll respond as soon as we can.
