### ISSUE TITLE
[Proposal] Dailies task considered completed if more than N items in list are completed

### ISSUE THREAD

**Issue by broiniac** [HabitRPG/habitica#4882]
The whole idea behind this feature is to add additional option to task managing, that will define how many of subtask/list items have to be completed (in daily list), to considered whole task as completed.

Example:
- "Task": Eat at least 3 meals a day
- "List":
  1. Breakfast
  2. Brunch
  3. Lunch
  4. Dinner
  5. Supper
- "To complete, do at least": 3
- "Difficult": ...

etc, etc.

Additional idea: extra points for completing whole list.

**Comment by Alys** [comment]
This would be better done as a feature request (Help -> Request a Feature) rather than as a bug report, but since it's here:

I agree that for some cases it would be a nice feature to have, but from an overall perspective, I think the extra complexity for the end-user would cause enough problems to be undesirable. We have some users that are very young, some that are not technically proficient, some with learning difficulties, and extra features make the site harder to use (which in turn increases the support time that the site requires). That alone isn't enough to stop a feature from being created, but in this case there are easy workarounds that mean this feature, while nice, is not essential. 

You can create a Daily exactly as you describe, with the checklist of five items, and with the task title being "Eat at least 3 meals a day (mark completed when 3 are eaten)". The user can then tick off the entire Daily when three meals have been eaten. A feature that completes the Daily automatically when three checklist items has been ticked doesn't add a lot of value.

To gain extra points for extra meals, you can create a plus Habit labelled "one extra meal" and click that when you eat more than three meals. You could write a reminder to use the Habit into the Daily's title.

I realise this is a bit of a work-around, but the alternative is making Dailies such as the one you describe work differently to existing Dailies. You might not be aware, but for Dailies, the checklist is not designed to add extra points, but instead is used to minimise damage if the entire Daily isn't completed (see [Checklist](http://habitrpg.wikia.com/wiki/Checklist) on the wiki if you'd like more information). If we were to make the checklist for some Dailies add extra points, I think the inconsistency would be confusing.

**Comment by Alys** [comment]
I'm closing this because I think the workarounds I describe above are the best way to handle this, to avoid making Dailies more complicated and confusing for users that need a simpler interface. However if you'd still like the feature, please go to Help -> Request a Feature to describe it in Trello.
