### ISSUE TITLE
Newbie Guide Keeps Popping Up + App is Slow

### ISSUE THREAD

**Issue by sammylau94** [HabitRPG/habitica#4886]
Every time I would try to join a guild, and sometimes when I would come back to the task page, the cartoon figure who walks you through HabitRPG keeps popping up onto my page. Even when I type in the HabitRPG's website URL, the character still pops up. I have to press ESC on my keyboard all the time. I'm using my MacBook Air and Firefox as my Web browser.

I find that the HabitRPG app lags quite a bit. This usually doesn't happen to my other apps. Sometimes a couple of the tasks would show double. For my smartphone, I'm using Samsung Galaxy S4.

My API is: c993d213-5ea1-4e0a-bfd1-0e541da93a8d

**Comment by lemoness** [comment]
So, pressing escape on the tour just hides it - it doesn't finish it. As a result, until the tour is finished (i.e. you click "Next" until it is done), it will return every time you refresh. Try finishing the tour, and let us know if that helps!

 @lefnire We probably need to change this, so that escape either 1) auto-finishes the tour, or 2) does nothing. I'm torn between the two. @Alys has expressed concern that having escape auto-finish the tour would lead to newbies accidentally closing the tour forever. Regardless, the current behavior seems frustrating.

As for the app, it lags because it is not a native app. We're currently rewriting the apps from scratch to be native, so that will help!

**Comment by TheHollidayInn** [comment]
If we use option number 1, then should we add a place (link or button) for users to restart the tour? That would address @Alys 's concern.

**Comment by sammylau94** [comment]
Thank you! The Newbie Guide stopped popping up, and I understand the situation. I wish you guys good luck on rewriting the app!
