### ISSUE TITLE
Popup after class select (change class) shows wrong class - reports that I've equipped old class's gear instead of new

### ISSUE THREAD

**Issue by gkjt** [HabitRPG/habitica#4888]
I just hit level 10, and chose my class, Rogue, but the popup after tells me I am now wearing my Warrior gear. It appears to have applied the rogue equipment, but the popup is incorrect. You can see this in [this](http://puu.sh/gGY47/a541c9b2ad.png) screenshot, also attached below:

![Incorrect class on popup](http://puu.sh/gGY47/a541c9b2ad.png)
##

**Comment by TheHollidayInn** [comment]
Technical: I believe this happens because the user class is not synced before the Guide is called after this line: https://github.com/HabitRPG/habitrpg/blob/de67f44e1f0b6027871397610a37458a87cfdc91/website/public/js/controllers/userCtrl.js#L29 .

I'm unsure of how to use a callback to call the guide after the user has synced.

**Comment by relsqui** [comment]
Adding a couple of notes from my (duplicate) #5430:

The message is this one: https://github.com/HabitRPG/habitrpg/blob/4042c1ce7ae07c84da927501d7915cd828a10be3/common/locales/en/npc.json#L31
It seems to be getting its variable here: https://github.com/HabitRPG/habitrpg/blob/1743899dd49adae7887f73c300f9802a35307b9b/website/public/js/services/guideServices.js#L60

The reported class seems to be the one the user had at last refresh, which is not necessarily the class they're changing from. (It's different if you change classes twice in one pageload.)

**Comment by ghost** [comment]
In addition

`content: window.env.t('classGearText', {klass: User.user.stats.class})`

has `klass` untranslatable

( https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/guideServices.js#L70 )

**Comment by ghost** [comment]
Oh, the ticket is almost year-old... But is it really necessary to point out the class in that message?

Maybe simplify it and instead of 

> First: don't panic! Your old gear is in your inventory, and you're now wearing **_your apprentice <strong><%= klass %></strong> equipment**_. Wearing your class's gear grants you a 50% bonus to stats. However, feel free to switch back to your old gear."

just say something general like:

> First: don't panic! Your old gear is in your inventory, and you're now wearing **_the apprentice equipment of the class you have just joined**_. Wearing your class's gear grants you a 50% bonus to stats. However, feel free to switch back to your old gear."

**Comment by GitHubSphinx** [comment]
@lemoness @SabreCat may I draw your attention to this issue please?

Cutting the long story short for email notifications:
Tutorial popup after changing class shows wrong notification of the class - mentions old class, not the new one. Moreover, the class variable (e.g "warrior") seems to be untranslatable inside a translatable paragraph. Text as of now:

>First: don't panic! Your old gear is in your inventory, and you're now wearing **your apprentice <%= klass %> equipment**. Wearing your class's gear grants you a 50% bonus to stats. However, feel free to switch back to your old gear."

The ticket is already a year-old. During this time the fix was suggested to add watch, but it was rejected for the sake of resources efficiency.

In this regard, may the text of this tutorial message be simplified not to specify the class, e.g:

>First: don't panic! Your old gear is in your inventory, and you're now wearing **the apprentice equipment of the class you have just joined**. Wearing your class's gear grants you a 50% bonus to stats. However, feel free to switch back to your old gear."

**Comment by lemoness** [comment]
I think that would be an effecient way to handle this! Let's say "equipment of
your new class" - it's a little more succinct.

**Comment by ghost** [comment]
@lemoness Thank you very much!

I've advertised this ticket in the aspiring guilds.
So the task is (as it seems to me):
- change https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/npc.json#L39 as described above
- change https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/guideServices.js#L70 to exclude `klass` variable
- make a screenshot of how it looks like on the local install
- make a pull request =)

**Comment by khipkin** [comment]
@lemoness @GitHubSphinx I would like to work on this!

**Comment by khipkin** [comment]
I think this issue can be closed.

**Comment by SabreCat** [comment]
Excellent, thanks!
