### ISSUE TITLE
Gold filter for the Reward's

### ISSUE THREAD

**Issue by SoRG96** [HabitRPG/habitica#489]
Hello, today I tried to change the price of the award at the text ("abc")
and after I pushed the button to buy this award, I have lost all of my money. So I tried to insert a "-50" as the price, and it killed my hero. After his death, I tried to use "-5", and I was hit by 5. "+5" doesn't make any changes.

P.S.
Sorry for my English.

**Comment by Pandoro** [comment]
The following happened:
1. You set abc as a reward.
2. You use it, which adds abc to your current gold. any value + "abc" = not
   a number.
3. You set -50 as a reward. This is shown, but when using it, the absolute
   value is taken, so the reward costs 50 gold.
4. You use the reward. Since you don't have any money though. The reward
   affects your hp. 50-50=0;
5. You die.
6. You set it to +5 -> the actual cost is again 5 -> no change between -5
   and +5.

This will be changed at some point. I'm wondering though, why were you
trying to use a negative reward cost or "abc" in the first place :x ?

**Comment by SoRG96** [comment]
Well, I'm very curious =P .

> You use the reward. Since you don't have any money though. The reward affects your hp

Yeah, but i can't buy reward with my hp. Why does it happen?

**Comment by wc8** [comment]
@SoRG96 if you try to buy a reward you don't have money for, you lose health. I suppose, game-wise, the shopkeeper or the sheriff have come after you and given you a beating.

**Comment by wc8** [comment]
@lefnire the "You are about to spend more gold than you have, are you sure?" confirmation dialog on [Confirmation for Gold Spending](https://trello.com/c/uEo7wjkH) was marked "completed". Does that mean @SoRG96 should have gotten a warning before the -50 (registering as 50 GP) killed him?

**Comment by lefnire** [comment]
Yes, there should have been a warning. Was there not?

**Comment by wc8** [comment]
Tested: 
Had 2 GP, tried a -20 GP reward. Lost HP.
Clicked -20 reward again, fatal HP loss, no warning, Game Over.

**Comment by tmas** [comment]
I'm guessing that you check if price > gp, but price is negative so you need to check the absolute value of the price as you do for subtracting gp and hp.

**Comment by paglias** [comment]
This should be fixed now.
