### ISSUE TITLE
All images are gone

### ISSUE THREAD

**Issue by Vstorey21** [HabitRPG/habitica#4890]
I leveled and then all the images disappeared.  Nothing that's supposed to be represented shows up any more.

**Comment by Alys** [comment]
Have you tried reloading the page? If not, please do.

**Comment by Vstorey21** [comment]
Yea, I tried that a couple of times. Logging out, closing the browser, even shut down and restarted just to make sure lol.

**Comment by Alys** [comment]
It's always worth mentioning what you've already tried when you log a bug report so that we can skip past the initial questions. :)

Do you have any extensions installed that are hiding images? For example, did you install the HabitRPG "boss button" extension? If you're not sure what this means, then you probably didn't install extensions.

Please clear your cache (that's not something that happens when the browser is closed or the PC is restarted). Then reload again. If you're not sure how to clear your cache, google for "clear cache {your browser name}" without the quotes and replace "{your browser name}" with the actual name of your browser. Note that it's important to clear the actual cache, not just browsing history or other related features which are often configured in the same place, so please be sure that you are choosing the cache clearing option.

If that doesn't help, show us a screenshot of the tasks screen and also tell us your user ID (step 6 in [these instructions](https://github.com/HabitRPG/habitrpg/issues/2760]).

**Comment by SpenserJ** [comment]
This can probably be closed after four months with no response from @Vstorey21.

**Comment by crookedneighbor** [comment]
@Vstorey21 I'm closing this now, but if you're still having issues, please re-open it.
