### ISSUE TITLE
[Proposal] A flag near dailies telling you that your character is in the inn.

### ISSUE THREAD

**Issue by architarious** [HabitRPG/habitica#4892]
I couldn't get my dailies to reset for almost a month and took no damage. Since i never do quests or anything on the social tab and kind of just use habit RPG to manage my daily life, I didn't know that my character being asleep meant that he was in the inn and assumed that i had the [CRON did not run bug](https://github.com/HabitRPG/habitrpg/issues/1057).

If there was just a small flag of some sort by the headline of your daily list telling you that you're character is in the inn and that they're essentially useless, it could prevent a lot of headaches. Or better yet, instead of a flag, you could just disable the whole daily task list with a message that says you're character is staying in the inn and that it's useless until you leave.

**Comment by Alys** [comment]
@architarious Proposals for new features should go through Trello (Help -> Request a Feature). This allows them to be assessed along with all other feature requests about similar topics so that the best combination of requests can be chosen. I'm going to leave this feature request here, but please keep this in mind for future requests.

Have you noticed that when you are resting in the inn, your avatar's eyes are closed and "Zzzz" appears next to its head? I agree that there could be a more obvious indication, but that might help you if you rest again before we create something more obvious.

If you would like to know why you were resting in the inn, please read [Whats New 2015 -> SITE DOWNTIME EXPLANATION (AND SLEEPING AVATARS)](http://habitrpg.wikia.com/wiki/Whats_New_2015#SITE_DOWNTIME_EXPLANATION_.28AND_SLEEPING_AVATARS.29). It's a copy of a Bailey message from a month ago. The Bailey messages are the ones that pop up sometimes when you reload the site or sign in, and it's usually worth glancing through them to see if there's anything relevant to you. Sometimes important site information is included in them.

**Comment by lemoness** [comment]
We've been debating certain features to make this more obvious, such as a
notification by your avatar.... should we close this ticket and link it to
that one, or continue that discussion in here?

**Comment by Alys** [comment]
Good point; I'd forgotten that, sorry. I would say close it and link it.
