### ISSUE TITLE
Tavern Chat Suggestion

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitica#4897]
Hello everyone! I couldn't really find if anyone had suggested this idea before but I apologize if it has been suggested before. I posted on the HabitRPG mobile repository about this idea and I really wanted to share and see what you guys think of it. Here it is:

From the Post (Unedited):

---

4). Ability to see whether or not a message in the tavern has been seen from the website or from mobile. 
(I like this idea a lot and I think that the main website so do this too. I will likely be posting this idea onto the main repository so I can get some feedback on how the website views it. I think it could help see who is on what platform and be able to see what limitations one might be having by using said platform. (Although the website doesn't have much limitations compared to the mobile but I think you get the point))

---

I think it can better help those trying to assist people in the tavern who are asking a question that might be referring to a problem that is present on the mobile platform but not really on the main platform and vice versa. The text would more than likely be small and of a lighter text and if it was on the main website only chats sent from mobile would have the text (something along the lines of not exactly this text) "sent from mobile" and possibly vice versa with "Sent from main website". I think it might be better just to have "sent from mobile" but that's just my suggestion. What do you guys think?

Link to my original post: https://github.com/HabitRPG/habitrpg-mobile/issues/358

UUID: 6f14571c-f2e9-4446-8e4e-591a7a3a42eb
HabitRPG Username: Rbrinkley

**Comment by Alys** [comment]
GitHub is intended for bug reports. Feature requests should go on Trello. It's best to stick to this approach because we get a lot of bug reports and they need usually need to be fixed quickly if they can be. If GitHub is used for feature requests as well, it makes the bug reports harder to find. Also, we get a lot of similar feature requests, or related requests for the similar features, and if they are all placed into Trello, they can all be analysed together and a consensus can be reached for the best way to implement the features. Could you please post this to Trello?
