### ISSUE TITLE
Finished the Derby quest, but I don't have the ability to purchase seahorses

### ISSUE THREAD

**Issue by L1st3r** [HabitRPG/habitica#4903]
Yep that's pretty much it. Finished the quest forever ago. uuid: e177e5a0-2606-40b7-b448-bbc7359ca30f

**Comment by deilann** [comment]
As stated in the Tavern by Cantras:

You haven't done the derby quest. You were present for the dilatory world event, "The Dread Drag'on of Dilatory" (which gave everyone one seahorse egg) -- but not the quest, which is "The Dilatory Derby".

In order to purchase seahorse eggs, you will need to complete "The Dilatory Derby"
