### ISSUE TITLE
Progress not saved on logout (checked items not checked, new ones vanish…)

### ISSUE THREAD

**Issue by stuckfly** [HabitRPG/habitica#4905]
Mac OS 10.10.2 and Safari
If I forget to hit the sync button before logging out, when I log back in the tasks and dailies I had checked as done are not checked and my avatar often dies from this if I don't catch it before midnight.

If clicking the sync button is necessary (until recently it wasn't necessary), then why not just force a successful sync as part of the logout code? Very frustrating! I'm wasting time re-updating my progress and resurrecting my game stuff.

**Comment by WillyReyno** [comment]
Same here, when I was at work I was level 40, and had checked and edited many tasks.
Now back home I'm level 37 and all my edited tasks are not...
(at work I'm on Mac Firefox, at home I'm on Firefox but onWindows)

**Comment by SynapticWanderer** [comment]
I'm having this problem too, I died, and the rest of my party almost died, because it didn't take most of my checked dailies from the day before. Also, for some reason, some of my dailies are still checked from yesterday. This is doubly frustrating because we're in the middle of a boss quest, so extra damage is done. I had completed all of my dailies. Do we have to hit the sync button when we're done now? If so, some notification of that would have been nice. I just lost all my gold and some of my better armor, plus a level. Can that be fixed, since it wasn't a legitimate death?

User ID:
918ffa67-e9c3-4db2-9b5f-3b7383c82ca6

Operating System
Windows XP

Internet/Web Browser
Chrome/40.0.2214.115

Flash version
16.0.0.305

**Comment by lemoness** [comment]
We're sorry that this has been happening!

@GypsyDarkness It sounds like you are actually experiencing this bug, unfortunately: https://github.com/HabitRPG/habitrpg/issues/4313 We've been investigating it, but in the meantime, please see the "Advice" section. The good news is, you and your party can fix the unjust damage under Settings > Site > Fix Character Values :)

@WillyReyno @stuckfly It does sound like you're having sync errors. Usually everything will sync normally, but sometimes it does not, especially in cases such as low internet connection or the player performing several actions in quick sucession, such as ticking off several Dailies within a few seconds). (This overloads the browser, preventing it from sending some or all of the actions to the server.) 

To prevent sync errors, after you have taken an action, notice the thin blue line that appears at the top of the screen. It travels from left to right to indicate the progress of syncing from your browser to the server and back again. When the line has disappeared, syncing is finished, and it is safe to perform another action. (If the blue line does not appear after your action, it is because that particular action does not require syncing.)
Often, you can actually successfully perform actions without waiting for syncing to finish, but if you want to be certain of not getting sync errors, you should wait for the blue line to disappear between each action.

You can also use the User Data Display tool (click “Data” in the menu bar) to check for sync errors because it reads your stored data directly from the server. It will tell you which Dailies have not yet been ticked off. 

Let us know if these actions do not help you, and we’ll investigate further!

**Comment by WillyReyno** [comment]
I tried to follow what you said, I synced everytime I logged out from a computer.

At home I'm currently level 39, and now at work I'm level 42 with the tasks I had yesterday at work...
EDIT : It seems that my to-dos from my home and those I added at work have been merged, some of my to-dos were displayed twice so I deleted some of theme.

**Comment by lemoness** [comment]
@WillyReyno HM - that makes it sound like you might actually have two accounts. @Alys or other devs, can we check on this?

**Comment by paglias** [comment]
@WillyReyno can you provide your UUID?

**Comment by WillyReyno** [comment]
Back at home, now everything seems to be correctly synced...
My UUID is : aa137fd1-9b36-4c2f-ae2b-e651e2b764c5

**Comment by paglias** [comment]
No duplicate account, probably just some sync error, I'm sorry

2015-03-25 19:51 GMT+01:00, Willy Reyno notifications@github.com:

> Back at home, now everything seems to be correctly synced...
> My UUID is : aa137fd1-9b36-4c2f-ae2b-e651e2b764c5
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/4905#issuecomment-86170338

## 

Matteo Pagliazzi - paglias.net

**Comment by stuckfly** [comment]
@lemoness I've been watching the blue sync bar. I'm seeing things.

Most of the time it works fine, but often it hangs and just won't finish. Spinning blue thing, too. Re-clicking Sync does not help. Refreshing the page sometimes works; sometimes not. Logging out works best.

Sometimes there is no sync bar; it does not appear. What this happens, sometimes if I wait my rewards stats popup eventually, even if I've checked several things and hit Sync multiple times. But no bar. Most of the time when the bar does not appear, hitting Sync does nothing, nor refreshing the page. Logging out helps, but sometimes my changes aren't recorded.

New one: A task named "dd082f47-3f98-47f3-bae0-53ddd73c620d" appeared yesterday. Its extra notes say: "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task." From whence has it come? And why?

I'm getting better at clicking the Sync button before I logout and waiting for some sort of sync response between changes. Today, I have turned off the Click-To-Plugin Safari browser plugin. Maybe it doesn't play nice with HabitRPG, but I've had it running long before these quirks showed up…

**Comment by Alys** [comment]
@stuckfly The task named "dd082f47-3f98-47f3-bae0-53ddd73c620d" is a separate issue. You can read about it here: https://github.com/HabitRPG/habitrpg/issues/1402 (see the bolded text in the first comment). In brief, it's a benign bug and you can just delete that task. 

Thank you very much for the detail in the rest of your comment. When the sync button doesn't occur, I think it's likely to be an instance of the "two versions of your data" bug https://github.com/HabitRPG/habitrpg/issues/4313 and if I'm right about that, then the best response is to reload the page with your browser's refresh button. Sometimes a few reloads might be needed - I am sorry for the trouble! Any thing other than a reload can cause recent changes to not be permanently recorded.

**Comment by Alys** [comment]
We think duplicate tasks have been prevented by https://github.com/HabitRPG/habitrpg/pull/4845 (which was merged in https://github.com/HabitRPG/habitrpg/commit/ca72b9a9e1e86262fcab15c7d52ae902953dc7b8).

The other bugs mentioned here are being tracked in other issues.

I'm closing this but can be reopened if I'm wrong.
