### ISSUE TITLE
Feature request: Use HTML5 local databases

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitica#491]
It would be nice if HabitRPG used HTML 5 local databases. This would help to avoid data loss when the server goes down or the browser closes suddenly, allow the app to keep running if it couldn't connect to the server (though it should probably give some sort of notice to users), and so on. This would be especially nice for the mobile apps you're making, since temporary loss of cell service is quite a common thing and since I think PhoneGap permits use of HTML5 features like that.

You could even allow a lot of people to load the app while the database server was down by serving static Javascript files. For those people who only use HabitRPG in one browser, the browser would already have the data ready to go. New users would be able to get going as well.

**Comment by lefnire** [comment]
A fine suggestion, but a huge investment to develop. We'd need to build a Racer plugin. The problem is our bugs, because Racer is built to work offline - you can take habit on the bus, and it will push your changes as soon as it detects a connection. That's the way it's supposed to work, but it's not - so I think it's fixing our bugs that's the solution, IMO
