### ISSUE TITLE
Adding multiple tasks adds them in the opposite order they were entered

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#4935]
When adding multiple tasks simultaneously, they are placed into the to-do list in the opposite order than they were entered. Since I (and I'm guessing others) enter the tasks in the order I'd like to complete them, this is a little annoying, since it essentially creates my daily to-do list upside down. Any chance this could be changed?

**Comment by Alys** [comment]
I can definitely see your point with this but the current behaviour is consistent with adding tasks one by one (the most recently typed task appears at the top of the list). Consistency does have benefits for usability. I'm not sure whether that applies in this case though. @anitaycheng?

**Comment by hairlessbear** [comment]
That's a good point. Maybe there's a middle ground, like a toggle/checkbox to determine the order of the added tasks.

**Comment by AnitaYCheng** [comment]
Hmm, it's hard to say what people are using it for, since it isn't a checklist exactly, where the order really matters. You're just adding multiple tasks at once.

Heuristics-wise (without knowing how people are actually using it), I'd put it into the list in the order they typed it in. They're already looking at it in that order, and immediate feedback means keeping it in that order, despite what adding tasks individually might mean.

**Comment by TheHollidayInn** [comment]
Hello,

I can't exactly replicate the issue. I have added 3 rows worth of tags, and (with some maneuvering) I am able to reorder the tags. I'm going to see if I can make the reordering smoother by fixing the drag and drop.

Can you provide any more information to help me recreate the issue?
--Does the browser show that you are dragging a tag?
--Do other tags seems to wiggle when you are dragging a tag?
--Can you provide a screen shot?
--Anything else?

Thank you!

**Comment by hairlessbear** [comment]
Looks like this is fixed, so this issue should be closed, right?

**Comment by crookedneighbor** [comment]
Good catch.
