### ISSUE TITLE
Bailey Outdated without Refresh

### ISSUE THREAD

**Issue by gisikw** [HabitRPG/habitica#4940]
When Bailey pops up without a full page refresh, she lists the second-most-recent update, rather than the most recent (I got the March 25th update, rather than the 29th. On page refresh, it worked correctly).

**Comment by Alys** [comment]
Yes, that's common. It's because your browser doesn't have the latest content yet for the "new-stuff" page. A reload always fixes it.

@paglias @sabrecat This gets reported so often (usually in the Tavern) that I'm wondering if it's worth forcing a refresh when people view the Bailey. Although we wouldn't want a refresh every time they viewed Bailey, if they chose to keep it open in the menu bar. @anitaycheng how would you feel about the site reloading when you clicked Bailey for the first time after a new Bailey message was deployed?

**Comment by gisikw** [comment]
Sorry for the redundancy!

Feels like we can probably refactor to pull the latest up from the server, no? I can look into the code; just wanted to log it here first.

**Comment by Alys** [comment]
Refactor?

**Comment by gisikw** [comment]
I haven't looked at the code yet - just thinking we could probably change the way the modal is populated so we can load that content asynchronously; thus we avoid the need for a page refresh. I'll see if I can come up with something.

Closing this out for now as "known and redundant" :)

**Comment by Alys** [comment]
Sounds good. :)

**Comment by crookedneighbor** [comment]
We're also going to move the Bailey announcements to be stored in the database (rather than hard-coded into the new-stuff.jade file) and created and published via an admin-only portion of the site. That change should correct for this problem.

**Comment by AnitaYCheng** [comment]
I'm unclear as to how the Bailey is working in this context. Does Bailey pop up automatically without a hard page refresh?

At any rate, I would prefer "warning" the user before doing any hard page refreshes, or letting them control the action with a button on the Bailey. (Ex: "Bailey just received new announcements! Click the refresh button to get the latest!" _insert refresh button_ )

People might be editing or typing something when they get distracted and click the Bailey, and surprising them with a hard refresh without any warning might mean they'll lose what they have.

**Comment by crookedneighbor** [comment]
The bailey announcement is just a file (rather than pulling text from a database), the text of which is on the page, waiting to appear when the bailey image is clicked on.

So, a script gets run which puts a flag on each user's database object that a new announcement is ready. If the flag gets triggered while the user is on the site, and they haven't refreshed since the update to the Bailey file was made, they'll see the old version of the file. Forcing a refresh forces the user to see the new version of the site.

@gisikw 's (very clever) suggestion is that the 'new-stuff.jade` file be loaded into the modal dynamically when the bailey modal gets called, rather than just be sitting there ready like we have it now. Since it gets loaded in, this will pull in the updated announcement, instead of using the old one that was sitting on the page.

Ultimately, the CMS solution is the one we're going to want to go with, so it'll allow updates to be written without changing and deploying any code.

@AnitaYCheng does that clear anything up? Or did I just make everything more confusing?

**Comment by AnitaYCheng** [comment]
@crookedneighbor Makes sense to me! Thanks for explaining it so thoroughly. :smile: And yeah, @gisikw's solution sounds like it would solve it.

**Comment by gisikw** [comment]
@crookedneighbor How far out do you think the CMS solution is? Would it be worth my taking a look at dynamically loading the modal content until we have that running, just to avoid issues and questions for the mods?

**Comment by crookedneighbor** [comment]
My very optimistic answer is end of April for when it'll be ready, but realistically, it could be longer.

If you think it'll take you less than an hour to do it, I say go for it as a stop gap.
