### ISSUE TITLE
Jumbled images

### ISSUE THREAD

**Issue by GrayDays** [HabitRPG/habitica#4941]
When I logged onto habitrpg via mobile safari today, the images looked like this http://i.imgur.com/upBadZf.jpg http://i.imgur.com/pr1jSYT.jpg on both the regular and beta sites. (I infer this is the same spritesheet issue as happened last year.)

**Comment by Alys** [comment]
Please see the second comment (the one all in bold) in this issue for an explanation and fix: https://github.com/HabitRPG/habitrpg/issues/3830

**Comment by GrayDays** [comment]
I refreshed, used the 'clear cookies and data' in my iphone's safari settings (which was the closest I could find to a cache-clearing function), and loaded habitrpg again, and it fixed the issue on the beta site but not on the regular one.

**Comment by Alys** [comment]
It will still be a caching problem. If your browser doesn't let you clear the cache, then there's probably no option other than to wait until it clears itself. Reloading frequently might help, if you want to do that. If you're still not seeing the correct images in 24 hours, tell us.

**Comment by Alys** [comment]
@GrayDays I am sorry, it looks like this might be caused by spritesheets being too large for the iPhone software to handle. Please see https://github.com/HabitRPG/habitrpg/issues/4943 for details. If that's the case, then refreshing and clearing the cache won't work. We'll report on the progress of the fix in that issue.
