### ISSUE TITLE
My character is looks like it's asleep and the dailies won't reset.

### ISSUE THREAD

**Issue by KamiyaAkuto** [HabitRPG/habitica#4948]
I noticed a few months ago that the character on my account, 41bf5d1f-d918-47cf-9b6f-5826154c4f62, looked like it was sleeping. I haven't done anything out of the ordinary to make this happen, nor have I found anything about it on the wiki or any of the threads I've skimmed through. I've left the account alone since then in the hopes it would fix itself, but it's still the same when I logged on today. Worst of all my dailies haven't reset once since then, though my to-dos still give me experience when I clear them.

I would really appreciate some advice on the matter, and if this topic was already covered I will gladly take a look. I have Windows 8.1 and Google Chrome.

**Comment by Alys** [comment]
Please see this issue for an explanation and fix: https://github.com/HabitRPG/habitrpg/issues/4742 or alternatively [HabitRPG Outage Instructions -> Unplanned Tavern Visit](http://habitrpg.wikia.com/wiki/HabitRPG_Outage_Instructions#Unplanned_Tavern_Visit) on the wiki. In brief, you need to check out of the Inn and then your Dailies will reset tomorrow (although those two links give you advice about how to force them to reset sooner if you wish to). 

I'm closing this issue now since there isn't a bug any more, but if you have any questions, please do comment here! We will see your questions and we will answer them.

**Comment by KamiyaAkuto** [comment]
Thank you very much, I completely understand! :)
