### ISSUE TITLE
Lost gold, gear, and died

### ISSUE THREAD

**Issue by jchong42** [HabitRPG/habitica#4951]
Hello, I'm writing on behalf of my 7 year old son who is so distraught that after saving up 160 gold to buy his special edition magician's wand, that he simultaneously lost 160 gold, his wand, and died while having 50 HP.  His ID is 821229d2-3271-44ef-83c9-f5cadc60015e
Please help and explain if he did something wrong.  Thank you.  My name is Jenny

**Comment by lemoness** [comment]
Hi Jenny,

Is your son in a party that is doing a boss quest? If so, a party member's undone Dailies may have damaged him and caused his character to die. You can check on this under Social > Party by clicking Fetch Recent Messages.

Another option is that his undone Dailies were enough to kill him. You can see how much damage he will take from his incomplete Dailies every night by clicking the tab that says "Data."

If he completed all his Dailies, but he lost of all of his streaks, that means that the server didn't register that the tasks were checked off, possibly due to a faulty internet connection. Refreshing right before bed can help alleviate this, as can checking the Data Display Tool.

As for right now, since it sounds like an unjust death, you can go on his account to Settings > Site > Fix Character Values and give him back his lost level and gold. Also, if you give me his user ID (the string of numbers and letters under Settings > API; NOT the API code), I can restore his wand, or you can give him enough gold to buy the wand again from the rewards store.

Let us know if there's any other way we can help!

**Comment by ashlaya** [comment]
Is your son playing on mobile? Was he supposed to level-up? It happens to me very often that while checking my dailies, etc. on mobile I get to the upper level, but I die. Usually I can take care of it by not syncing with web, checking my dailies and such in my web browser, level-up on the web and then syncing the day after on mobile.

**Comment by jchong42** [comment]
We haven't had much success with mobile or ipad so we always use a laptop.  Thank you for your suggestions. Thankfully I was able to restore his gold to get a coveted magic wand!
 

```
  From: ashlaya <notifications@github.com>
```

 To: HabitRPG/habitrpg habitrpg@noreply.github.com 
Cc: jchong42 jchong42@yahoo.com 
 Sent: Thursday, April 2, 2015 2:07 PM
 Subject: Re: [habitrpg] Lost gold, gear, and died (#4951)

Is your son playing on mobile? Was he supposed to level-up? It happens to me very often that while checking my dailies, etc. on mobile I get to the upper level, but I die. Usually I can take care of it by not syncing with web, checking my dailies and such in my web browser, level-up on the web and then syncing the day after on mobile.—

**Comment by jchong42** [comment]
Thank you so much, you were very helpful!  I really don't know how it happened, as he checks off his dailies daily and everything seemed to be proceeding as normal.  No boss quest, just the April egg quest.  No more tears, he got his wand back. Thank you!

**Comment by SonOfSunTzu** [comment]
The same issue of losing a life happened to me ( not on any quests, fully completed set of Dallies, was at 50HP ), so thank you for posting the manual fix.  Are there any details I can provide, or things I can try, to give you more information on the bug?

**Comment by Alys** [comment]
@OakTwo Did you die at the time when you first used HabitRPG on that day? Or was it later in the day? 

If it was your first use of HabitRPG that day, did you notice if only some of your Dailies had become unticked instead of all of them?

**Comment by SonOfSunTzu** [comment]
It was my first use of HabitRPG, the "sync" button didn't appear to be doing anything so I reloaded the entire page, and none of my Dailies have unticked.

**Comment by Alys** [comment]
Thanks for the details @OakTwo. It was this bug: https://github.com/HabitRPG/habitrpg/issues/4313. Near the top of that page is an "Advice" section, which will help you recover from the unfair death and hopefully avoid the problem again. I'm sorry it hit you!
