### ISSUE TITLE
All or many tasks, habits, dailies, to-dos, rewards deleted / disappeared / erased completely

### ISSUE THREAD

**Issue by illuscat** [HabitRPG/habitica#4957]
I'm not sure what happened (I've been humming along with HabitRPG for quite some time now), but suddenly, after hitting refresh today to be sure I was checked in at the inn all right, all my habits, all my dailies, all my rewards -- everything -- is erased. What a mystery!  I'm wondering if there are any Sherlocks out there who might be able to help? (If so, thank you!)

Here is my user id: 45cab1d6-0a6a-453f-8a46-a2a807b803ef 

---

_edit by admin:_
# What to do if this happens to you:
1. **Click the "clear" button next to your tags, even if it looks like no tags are selected.**
2. **Type any text into the "search" box to the right of your tags and then use backspace to delete what you typed (then wait a second or two).**
3. **Reload the page.**
4. **If none of those help, add your User ID here (from [Settings -> API](https://habitrpg.com/#/options/settings/api) - do NOT copy your API Token).**
##

**Comment by Alys** [comment]
Click the "clear" button next to your tags. Does that help?

**Comment by illuscat** [comment]
Sadly, this did not bring them back. Thank you for the quick idea, though!

**Comment by Alys** [comment]
Sorry about that - it's by far the most common fix for this problem.

I've checked your account in the database, and I'm very sorry but all of your tasks except for three challenge To-Dos have been deleted. I am about to start downloading a database backup from up to 12 hours ago to restore them. As long as the tasks were still in your account 12 hours ago, they WILL be in the backup. If they are not there, I'll download a backup from 12 hours before that (and so on as far back as needed). We will get your tasks back.

Unfortunately this will take a while. :( Downloading each backup takes two to three hours (they're huge) and then there's another one to two hours to search through it for your data (that's an automated search, not actual hands-on time). It's actually likely to be 10 hours or more before I can restore the data because I'll probably have to sleep before the downloading and searching has been completed. But this will be my highest priority for tomorrow morning.

I also want to try to work out what caused this. Have you noticed anything out of the ordinary in the past day, even if it doesn't seem related? 

Which device(s) do you use HabitRPG on? E.g., PC, iOS phone, Android phone... Which phone apps do you use? The official ones or unofficial ones? (The unofficial ones I am aware of ARE reliable, but I'd like to know which ones you use anyway.)

Do you use any third-party tools or apps of any kind?

**Comment by Alys** [comment]
@illuscat Good news: the database backup that was made about 10 hours before you reported this contains many Habits, Dailies, To-Dos, and Rewards. I have them all downloaded, but I won't import them back into your account for another eight to ten hours because it's past my bedtime and doing database manipulations while sleepy is unwise. :)

Are you missing anything else from your account? Eggs, potions, or food, for example?

**Comment by Alys** [comment]
@illuscat I've restored your Rewards. I'm still working on your tasks. There seem to be formatting issues that I'll need to fix before the database accepts the data.

I have also caused you to Rest in the Inn so that you won't take damage for incomplete Dailies, if you happen to be sleeping when I restore your Dailies. If you're not sure what that means, you can read about it at http://habitrpg.wikia.com/wiki/Tavern#Resting_in_the_Inn

**Comment by Alys** [comment]
@illuscat All of your tasks should now be back in your account. Please let me know if there's anything still missing!

**Comment by illuscat** [comment]
Oh, thank you, thank you! (I'm sorry for my slow response. I was away from the internet today). I think you restored everything, which is amazing! (I was ready to accept the challenge of recreating my list...).  

To answer your previous questions (to help address causes, in case this ever happens to anyone else?):
- I use Habit both on my laptop (chrome) and on my Android. When the issue occurred, I was on my laptop. 
- At the exact moment the issue occurred, I think I had been deleting some tasks from a challenge that ended. 
- I don't seem to be missing any eggs, potions, or food from my account, so I think all is well. 
  -If there's anything else I can do to help solve any remaining mystery on your end, I am at your service.

I can't thank you enough for working so quickly on this! Wow!

**Comment by Alys** [comment]
You're welcome, I'm glad it's all back for you! Thanks very much for the extra details. I'll leave this issue open so that we can, hopefully, think of a cause for it.

**Comment by Alys** [comment]
**@lefnire @paglias @crookedneighbor and any other devs who are interested:**

**All of this user's tasks were deleted (not by the user). It might have happened when they were deleting challenge tasks.**

**Comment by lisamaystowe** [comment]
Help! This happened to me today; all but a couple of my tasks and rewards are missing and some have been added that are nothing but nonsense (just letters and numbers in no apparent sequence). I am on my work computer but have not had trouble before today. What do I do?

**Comment by Alys** [comment]
@lisamaystowe Click on the clear button next to your tags, even if it looks like no tags are selected. Also ensure that in each task column, the 'all' and 'active' tabs are selected. Have your tasks reappeared? If not, if you want us to restore them, we will need to know your user id - go to Help -> Report a Bug and see the instructions there about how to find it. 

You can delete the nonsense tasks.

**Comment by Alys** [comment]
@lisamaystowe Did the clear button reveal your tasks? If not, please paste your user ID here. We need that before we can retrieve your tasks from a backup.

**Comment by lisamaystowe** [comment]
You guys are awesome to put up with this middle-aged wanna be computer nerd who allows these things to get under her skin way too easily!!! Thank you for your patience and understanding. Here is my user ID: cf14261d-566a-42dc-8779-06463ab50420
As far as I know I have never given out my information except for that short time I had it posted yesterday; I have tried the clear button; I have tried everything you have suggested to no avail. Again, I apologize for sounding just like the kind of person I hate dealing with in my profession--jeesh! 

> > > > looking for flogging whip<<<<<  :-/

**Comment by Alys** [comment]
@lisamaystowe No worries. :) I'll start downloading a database backup so that I can get a copy of your tasks to restore. I'm afraid this will take a while though. The database backups are large and it takes at least two hours for one to be downloaded. The process that searches through it for your user account will take up to 90 minutes (sometimes longer). However once I have the data, adding it back into your account will be one of my highest priorities. You should have it all back in several hours, if nothing goes wrong.

Your user ID is completely safe to share - it's just like sharing your user name.

**Comment by Alys** [comment]
@lisamaystowe I've restored your Habits, Dailies, To-Dos, and Rewards from a database backup that was about three days old. Please tell us if there are any problems!

**Comment by lisamaystowe** [comment]
@alys Thank you so very much! I just glanced and everything looks good. I will let you know if anything has an issue-and again I appreciate yours and everyone else who helped/attempted to help me. I promise to be much more patient in the future; I pass on the word about your app to many of my co-workers and students :)

**Comment by skysailor99** [comment]
All of my habits, dailies, and to-dos disappeared! If I try to create a new one, the site reloads and nothing displays. I tried clicking "clear" and toggling my sole tag on and off, but no luck. Habits are toggled All; Dailies All; To-Dos Active. I can still see Rewards, however.

User ID: 365d75c6-e6d5-43fb-8f4a-5aed2ebe89db
Browser: Google Chrome 42.0.2311.90 m
OS: Windows 8
Javascript Console Errors:
4app-ea86f7ed.js:8 Error: [$injector:unpr] Unknown provider: aProvider <- a <- conditionalOrderByFilter
http://errors.angularjs.org/1.3.9/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-onditionalOrderByFilter
    at https://habitrpg.com/app-ea86f7ed.js:5:23698
    at https://habitrpg.com/app-ea86f7ed.js:6:15585
    at Object.g [as get](https://habitrpg.com/app-ea86f7ed.js:6:17289)
    at https://habitrpg.com/app-ea86f7ed.js:6:15682
    at g (https://habitrpg.com/app-ea86f7ed.js:6:17289)
    at Object.i [as invoke](https://habitrpg.com/app-ea86f7ed.js:6:17623)
    at Object.c [as $get](https://habitrpg.com/app-ea86f7ed.js:6:16052)
    at Object.i [as invoke](https://habitrpg.com/app-ea86f7ed.js:6:17656)
    at https://habitrpg.com/app-ea86f7ed.js:6:15702
    at Object.g [as get](https://habitrpg.com/app-ea86f7ed.js:6:17289)(anonymous function) @ app-ea86f7ed.js:8
tweet_button.20ed5cfd7315475c9d1d523194b1645f.en.html:1Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi)
ping:1 Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://habitrpg.com" from accessing a frame with origin "https://s7.addthis.com". Protocols, domains, and ports must match.
16app-ea86f7ed.js:8 Error: [$injector:unpr] Unknown provider: aProvider <- a <- conditionalOrderByFilter
http://errors.angularjs.org/1.3.9/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-onditionalOrderByFilter
    at https://habitrpg.com/app-ea86f7ed.js:5:23698
    at https://habitrpg.com/app-ea86f7ed.js:6:15585
    at Object.g [as get](https://habitrpg.com/app-ea86f7ed.js:6:17289)
    at https://habitrpg.com/app-ea86f7ed.js:6:15682
    at g (https://habitrpg.com/app-ea86f7ed.js:6:17289)
    at Object.i [as invoke](https://habitrpg.com/app-ea86f7ed.js:6:17623)
    at Object.c [as $get](https://habitrpg.com/app-ea86f7ed.js:6:16052)
    at Object.i [as invoke](https://habitrpg.com/app-ea86f7ed.js:6:17656)
    at https://habitrpg.com/app-ea86f7ed.js:6:15702
    at Object.g [as get](https://habitrpg.com/app-ea86f7ed.js:6:17289)

**Comment by pixelcat45** [comment]
The exact same thing just happened to me! I reloaded the page and all my habits, dailies, and to-dos were gone. I've cleared my tags and that didn't seem to do anything. Everything in my inventory seems exactly how it should be though.

**Comment by paglias** [comment]
@skysailor99 @pixelcat45 sorry about this! all your data is safe and if you reload everything should be ok.

**Comment by pixelcat45** [comment]
@paglias I refreshed the page and everything's back where it should be, thank you!

**Comment by skysailor99** [comment]
@paglias Oh, good, it's all back now. Thank you!

**Comment by lathias** [comment]
Hello! I've had this problem for some time now, but just in my laptop... the app on my phone (iPhone 5s) is working correctly, and it's where I've been recording my progress. 
All the tasks in the main page are gone, but everything else (pets, items, etc.) is still there :(

There are no evident javascript errors on my browser (Chrome), just a warning about an URL.

I hope you can help me with this. My user ID is e5d64f06-ffe2-4d34-b4ea-68c5b79858b2
Thanks!

**Comment by Alys** [comment]
Click the clear button next to your tags and make sure there's no text in
the search box at the top of the Rewards column. Does that help?

**Comment by lathias** [comment]
It did. Thanks! Such a simple solution makes me feel bad :P

**Comment by crookedneighbor** [comment]
@lathias Glad it's working for you!

**Comment by laneatlarge** [comment]
I've had this problem twice now. So far it's just with To-Dos. Last time I only lost one and simply re-added it, but this time I've lost almost all of them and I can't even remember everything I had. I tried all the fixes above and nothing worked. I'm using Mozilla Firefox and my ID is 9b103a77-9666-4655-bcb0-d2706c0b5e1a 

Thanks in advance!

**Comment by feedmeacat** [comment]
Hi!  This happened to me... sort of.  I'm not in my party any more and all my to dos, habits, dailies, etc are all reset to the basic standard ones you start with.  I tried the steps in the OP but it didn't work.  My user ID is 2d392c1f-650e-487f-9163-357419fd01a7

**Comment by Alys** [comment]
@laneatlarge You have two Habitica accounts and you've logged in to the wrong one. The one you're using at the moment (2d392c1f-650e-487f-9163-357419fd01a7) until very recently hadn't been used since it was created on 2014-05-08. 

If there's nothing in that account that you want, I recommend deleting it so that it can't cause confusion again in future. To do that, go to Settings > Site (https://habitica.com/#/options/settings/settings ) and click on the red "delete" button towards the bottom right of the page.

Once you've deleted that account, or just logged out of it if you prefer, log back in using your usual login method. 

If you typically log in with a username / email address and password and you can't recall what they are, then there's a "forgot password" feature on the login form on the website (not on the app).

**Comment by paglias** [comment]
Should be fixed, reopen if it happens again
