### ISSUE TITLE
Hatched pets disappearing

### ISSUE THREAD

**Issue by wonderlande** [HabitRPG/habitica#4960]
I hatched a bunch of different pets this morning and noticed later in the day the one of them had reverted back to unhatched. I refreshed and then signed out, but the pet stayed unhatched. I used another egg/potion to get the pet back and now one of my other pets has disappeared. The pet I hatched twice was a white lion and the one that disappeared was a blue dragon. I know that I hatched all of my dragon eggs with all of the potions, so this is definitely a glitch, not my own poor memory. 

uid: ac69fe8a-29ca-4281-b5fc-6ca36eb06f1b
chrome/windows 7

**Comment by Alys** [comment]
I'm sorry about that @wonderlande ! It might have been [sync errors](http://habitrpg.wikia.com/wiki/Sync_Errors) or it could have been a database glitch. I've given you an extra one Lion egg, Dragon egg, blue potion, and white potion, just in case they hadn't been automatically put back into your inventory. Let me know if they haven't appeared!

**Comment by wonderlande** [comment]
Thanks so much!

**Comment by Alys** [comment]
@wonderlande Did you happen to notice when your pets disappeared whether there was still a green feeding bar under the spot where the pets should have been? It might have looked like the image here: https://github.com/HabitRPG/habitrpg/issues/4973

I'm trying to work out if your problem was the same as that one.

**Comment by wonderlande** [comment]
No, the paw print showed where the hatched pet should have been displayed.
No green bar. I did take a couple of screen shots after you gave me the
replacement eggs and potions and that issue seems to have worked itself
out. Although the found pet counter was off by 1 or 2. I'm away from my
computer but I can send the screen shots when I have access to my desktop,
if you want them.

Thanks again!

**Comment by Alys** [comment]
Thank you but no. There's no need for the screenshots. Because you saw the paw print, it was just a standard sync error.

Let me know if the pet counter is still incorrect after you've hatched a few more pets (otherwise eventually you might not get the Beast Master achievement). I'm closing this issue now but you can comment here later and we'll still be notified.
