### ISSUE TITLE
Pet graphic not loading

### ISSUE THREAD

**Issue by Emmi-Eriikka** [HabitRPG/habitica#4973]
Sorry if there is already an issue made for this subject.. I tried searching but couldn't find any. 
I just did a GitHub account to ask this question and I have no clue what else I can do anymore.
Anyway, here goes: 

I just hatched a normal red fox, and the graphics don't show at all. 
It's now been a couple of days, I've tried refreshing multiple times and cleaned cache and everything. 
All my other graphics work perfectly 
(well, sometimes my flying pigs seem to be flying if the graphics don't load fast enough but actually that's sort of neat so I'm not complaining)
Any suggestions? 
And please, Please tell me where I should post this question (if this is the wrong place), and I'll delete this one immediately :) 
Thanks!

My API user ID:
1352b169-31f0-4503-a9dc-d803a12d752d
I mostly use Firefox as my browser, and have had some problems with flash earlier.
- Emmi
  ![invicible_red_fox](https://cloud.githubusercontent.com/assets/11790146/6988465/697f40a2-da5a-11e4-8521-e6e5642671fa.jpg)

**Comment by Alys** [comment]
This is a good place for it - you've done exactly the right thing! 

Another option when you have questions is to go to Help -> Ask a Question, but in this particular case we would have asked you to report it on GitHub (exactly as you did) since it's very clearly a bug. But if you're ever not sure where to ask something, that Ask a Question link is a good place to start. There's a lot of friendly experienced players there.

As for this bug... I have no idea at the moment... We'll definitely get it fixed up but it's odd that it persists even after clearing your cache. 

Could you please tell us what version of Firefox you are using and what operating system and version your PC is running (e.g., Windows 7 or Windows 8 or Mac OS 10.6 or ...)?

**Comment by Alys** [comment]
I've checked Emmi's account and she definitely does own the red fox, so this is a display issue.

**Comment by Emmi-Eriikka** [comment]
Hey Alys, and thanks for the quick reply :) 
I'm running the latest Firefox version, 36.0.4 (and it won't be updated in a while since they are doing something), and Windows 8.1. 

I have had some issues with flash on Firefox earlier, but I'd be surprised if this problem is in connection to that.. since HabitPRG has worked perfectly when other stuff fails. 
And do the graphics even use flash? Hmm, I should really look more into what makes this game tic.

**Comment by Emmi-Eriikka** [comment]
Hey! Amazing! My red fox appeared <3 And it's so beautiful.
If you did something, thanks a billion :) 
Or maybe there's just some magic happening here. I for sure didn't do anything new. 
Well, anyway, the problem is fixed. I'll wait just a bit more and then close this.

**Comment by Alys** [comment]
Yes..... let's pretend that I did something....... ;)

It must have been just an aggressive cache or something like that. The graphics don't use flash (they're png sprites).

[Contributing to HabitRPG : Coders (Web & Mobile)](http://habitrpg.wikia.com/wiki/Contributing_to_HabitRPG#Coders_.28Web_.26_Mobile.29) describes the technologies that the site uses, in case you are interested.

I'm glad it's working for you. The foxes were my favourite pet when I started!
