### ISSUE TITLE
Cannot cancel party quest - Begin and Cancel buttons not appearing 

### ISSUE THREAD

**Issue by Ealasaid** [HabitRPG/habitica#4979]
My user ID is ac82c0a6-46d4-46fc-8948-acaf238016e6
Party ID is 135d20f5-c53b-419d-9b6a-e5f97b3fab5f

In short: I invited my party on a quest ages ago. My fellow party members became inactive before accepting or rejecting the quest. I booted them from the party so they wouldn't take damage from my questing. Now the info box about starting or canceling the quest is visible, but not the Begin or Cancel buttons to which it refers.

Thanks!

**Comment by Alys** [comment]
I believe have set the quest to the state where you personally need to accept or reject the invitation. Please go to your party page, reload it with your browser's refresh button, and hopefully an invitation will pop up. You can choose either option. If you choose accept, the quest should start immediately. Let me know if this is not what happens! There is another fix I can do if necessary, but it's a little more complex (I'm happy to do it though if needed).

FYI to any devs wondering about this: @Ealasaid had sent the quest invitation, and had been automatically accepted to it as normal. The other invitees had then been removed from the party, leaving @Ealasaid as the only person still in the quest list. But because none of the other members had accepted or rejected, the code that starts the quest was never executed.

**Comment by Alys** [comment]
... which is not to say @Ealasaid did anything wrong! The quest code has not been set up to handle this situation.

**Comment by Ealasaid** [comment]
Whoa! Hella fast and kind response. You rock, Alys! 

I reloaded as instructed and the invite popped up. I hit Reject, but after the popup disappeared, the party page loaded with the quest already started. I'd prefer to do the mundane questline in order (hence the Reject - I'm not sure why/how I picked part 2 originally), but if it would bork things to undo the quest beginning, it's OK.

**Comment by Alys** [comment]
Thank you. :)

I've cleared out the quest details from your party page (your own account quest details were already cleared by you rejecting the invitation), so you should be able to reload the party page now and see that there is no quest present. Be sure to tell me if that's not the case or if you have any trouble starting a new quest!

**Comment by Ealasaid** [comment]
Success! Thank you so much for your help.
