### ISSUE TITLE
Display coin value of habits, dailies and todos before you complete them

### ISSUE THREAD

**Issue by KristenEberts** [HabitRPG/habitica#498]
I'd like to see in advance how much "money" I'll get from completing tasks.

For example, I want to watch a TV show starting in 30 mins, but I need to earn 2 more gold coins to get that reward. I want to do the tasks that will help me reach that goal in the next half-hour, and not waste my time on tasks that turn out to only earn a few silver coins each.

The potential reward could be displayed to the left of the task name, like on the Rewards panel, or it could appear in a tooltip when the cursor hovers over the task.

**Comment by antistic** [comment]
Good idea! I think maybe a tooltip over just the checkbox or plus/minus icon might be better, especially for the plus/minus habits where it could just make things messier or confusing.

**Comment by wildcate** [comment]
Actually... I personally would not like that. I like to get surprised with how much a task is worth : )  and somehow, on gut-level, I feel uncomfortable with the idea. I can see how it would be helpful in your scenario... but doesn't a "fresh" to-do list task give at least one gold anyways? And on my list, there's probably not so many tasks I could complete in half an hour, so it would be limited choice anyway for me. Plus it might keep people from doing a habit/daily if they see that it will only give them 0.4 gold... or let them do a bad habit since it will only cost 0.5 health.

Gamewise, in a typical RPG, they also don't tell you beforehand how much XP you will gain for doing a task...

**Comment by KristenEberts** [comment]
Wildcate, I get where you're coming from. Maybe this could be an optional feature?

The real reason I want this feature is so I can set the value of my time. Let's say I want to get 1 hour of a reward for every 3 hours I work.\* The default reward cost is 20 gold, but what does that mean in terms of tasks? If I have to do a ton of work for my rewards, the behavior reinforcement won't be effective--it needs to happen soon after I complete the desired action. If I reduce the value of a reward (say, to 5 gold), it may become just too easy to get rewarded and I'll have less motivation to tackle the big, hard projects on my to-do list.

As of now, I have to use trial and error to set the cost of my rewards and the difficulty of my tasks. I have habits like "exercise 10 minutes" that I complete 6 times, rather than dailies like "exercise 1 hour," because I want to get more reward from exercising than, say, flossing my teeth. I'm constantly adjusting the cost of my rewards to find that sweet spot where they are cheap enough that I don't lose motivation, but expensive enough that I have to exercise some self-discipline to earn them.

If the devs decide not to display the coin value of tasks and leave them a surprise, then at least I would like to have suggested costs of different types of rewards. (This could work according to the Pomodoro method: users set their ideal ratio of work-to-play, and then the site suggests a gold value for rewards of different sizes, based on the average user's gold-earning per day.)

*Since the value of repetitive tasks decrease over time, eventually I'd end up doing more work in order to get my reward (which is a good thing--builds self-discipline!). But take this as a starting point.

**Comment by wildcate** [comment]
I can see what you would like to do, but I'm not so sure that it would work out the way you intended... and that is basically due to a difference in how you define "time value".

For approach to rewards, you are doing a different kind of maths than the programme intends you to. The algorithm that is already at work means that something which will take longer will sit on the list for longer and thus give more XP. However, it also means that something I really do not like to do (even if it's just 10 min of work) will sit for a while and thus motivate me more to actually get it done. So it's not measuring time spent working, but "task hardness" with a task that sits for longer automatically regarded as harder. For me, that works out beautifully because I value actually motivating myself to 10 mins spent on something that I procrastinated on for ages higher than the same time spent on doing something that I don't much care for but also don't hate. Your proposed "measuring value of my time", though, will give a flat value to the time you spend on any task. For that you would technically not need HRPG - you could just set a timer, work one hour, then make a mark on a tracking-sheet or place a token in a bag or use whatever other counting method, and for every 3 tokens you get an hour of playtime.

I also think that the scenario you describe for assigning your time a (fixed or minimum) value in HRPG would mean you had to accurately guess how long a task will take you. I have a few small ones where I can more or less guess that, yes, but for most I know that it will take a chunk of time somewhere between a few hours and several days, depending on how things work out and fall together. To avoid this and get a minimum reward for a given time of work, you could always (in your scenario) say that you will work for two quarters of an hour, enter those as fresh tasks into your to-do list, do that and get the 2 gp you needed.

So, maybe this would work for you? And for the exercising vs. flossing your teeth, one thing you could do to motivate yourself is make it both - a habit and a daily. The habit will give you a + for every 10 mins, and the daily could be "do 6 exercise units". 

And finally, regarding the suggested costs: There are already 3 suggestions on the board when you start - cake, an hour of series watching, and something else that I do not remember. However, suggesting reward values on the average user's gold intake can be very misleading for those that are way off the average (there have been discussions on here due to problems with that already). And even if we had a perfect scenario with similar gold income per day for everyone... other things may come into figuring reward costs as well. For example, I have two rewards set at a very high cost because I want to have to work really hard for them, even though they are not very time-consuming or expensive in reality.

**Comment by wc8** [comment]
Vote for for [**option** to show GP, XP value and HP cost](https://trello.com/c/JRnhQYP3) or comment w/concerns.

**Comment by Pandoro** [comment]
I can understand why people would want this, but I also see the clear risks. 

Honestly I am thinking that the system as it is right now is somewhat broken. For example I have to write my thesis (a daily) and I want to do exercises ( a daily). For both I have approximately the same reward if I complete them, but writing takes up at least 5 times the time. So if I would need GP quickly, guess what I would do and guess again what I SHOULD do. That is why I am a big fan of the [priority multiplier](https://trello.com/card/priority-multiplier/50e5d3684fe3a7266b0036d6/17). I get that this would not fix your problem, but if you assigned a certain priority, you would already know what would give you the better reward. 

I think that I am personally a bit against the idea, since I fear that it would really interfere with the general motivation factor to get everything done, but I can also understand that people might need it to keep themselves motivated. If you do task A to get reward B, but after an hour you notice you also need to do C to actually get B, that will be frustrating :-/

**Comment by horusofoz** [comment]
Discussion moved to Trello
