### ISSUE TITLE
After using iOS app, XP and purchases disappear the next day

### ISSUE THREAD

**Issue by irideae** [HabitRPG/habitica#4983]
I primarily use the iOS app, and my phone is still on iOS 7.  After I refreshed the app (and the webpage) on a new day, some of the experience I gained disappeared, as well as my purchase of a Sword and some of my recently added tasks.  It seems like my account has regressed to a different point in time, if that makes sense.  All of the changes were done at least by 10 PM CST last night.  This has happened two days in a row.

My user ID is b3e2b832-ac1c-40e6-a49c-0eab5d065c93.

**Comment by crookedneighbor** [comment]
@irideae Can you open the About link in the mobile app menu and tell us the version number listed at the bottom?

**Comment by irideae** [comment]
It's v0.0.53

**Comment by paglias** [comment]
Are you sure you were connected to the internet?
Il 06/apr/2015 14:45, "irideae" notifications@github.com ha scritto:

**Comment by irideae** [comment]
Yes.  I was connected to WiFi both times and using the internet in between using the app.

**Comment by spudderpillar** [comment]
I too have had difficulty with my iOS not syncing correctly. I've only been using it about a week but the iOS app is very erratic even when actively using the manual sync. I've lost xp and coins several times after logging out and then back into the app because it has unchecked my habit/daily/to-do items. This sometimes happens immediately and other times it will act like it synced but then will loose the information after a few hours (and several log-ins/outs).

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. It can be installed at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if anyone has any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
