### ISSUE TITLE
Cannot level up with skill (burst of flames, backstab) to levels 15, 30, 40, 60 (from levels 14, 29, 39, 59) -- "Error Cannot set property 'drop' of undefined"

### ISSUE THREAD

**Issue by ThereWasADream** [HabitRPG/habitica#4986]
#### Level up using tasks or habits instead. You'll then be able to use your skills normally.

This is a temporary workaround until the bug is fixed. 
### If you experience this bug, you do not need to comment here. It happens for all players in this situation.

FYI, this bug only occurs when levelling up to a level that gives you a free quest scroll.

---

This is the error I get every time I use backstab. Furthermore, upon reload of the page or upon cron, my backstab is "undone" as it were and everything that would have happened had I not backstabbed is reversed.

Please let me know what I can do to fix this! :)
##

**Comment by Alys** [comment]
Please log out of HabitRPG, clear your browser's cache (make sure it really is the cache you are clearing, not some other thing such as cookies or browsing history - google for how to clear the cache for your browser if you are not sure), then close all browser windows, reopen, and log back in.

If it keeps happening, log in using the Chrome browser, open the Console (probably from View -> Developer -> JavaScript Console), then cast the skill again and copy the entire contents of the console into this issue. You'll also need to tell us your user ID - go to Help -> Report a Bug and see step 6 for instructions on how to find it.

**Comment by ThereWasADream** [comment]
Followed your directions, it happened again.

Errors in console:
https://habitrpg.com/api/v2/user/class/cast/backStab?targetType=task&targetId=484dec73-ac7d-4fb6-861b-5d8c5237fed8 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app-13e55e7e.js:40 Object
https://habitrpg.com/api/v2/user/class/cast/backStab?targetType=task&targetId=484dec73-ac7d-4fb6-861b-5d8c5237fed8 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

User ID: d49a68d7-607d-483e-af12-ef4f41d229da

**Comment by hjalmberi** [comment]
Happens to me too. Chrome&Backstab combo
User ID 97cd6acc-7f56-4066-a0e7-31a1f6b1b2f0

**Comment by fckngjss** [comment]
Having the same issue, using Firefox on Windows 8 (not 8.1)
User ID: a57a39a3-785e-4127-8430-6f0687950ed0

**Comment by deilann** [comment]
Also, make sure y'all are casting the skill on the _body_ of the task, not
any of the buttons. In other words, on the text, not the part where you'd
click to complete it.

**Comment by ThereWasADream** [comment]
I _wish_ that were my problem...this is an actual error, not a misclick.

**Comment by deilann** [comment]
Oh, no, I'm not doubting it is. I just want to make sure that everyone
reporting this issue as well knows that can cause problems. :)

**Comment by vaiil** [comment]
I have same issue too. I try to cast "Burst of flames" to one my blue task, but this error happens.
Console:
POST https://habitrpg.com/api/v2/user/class/cast/fireball?targetType=task&targetId=***** 500 (Internal Server Error)
Mobile and Desctop Chrome.
User id: 882e6f99-6848-4278-88ef-557a0bf12c10
When I casted "Burst of flames", I got new level (15) and I got quest. Maybe it relates.
PS I dont know English, I am sorry)

**Comment by VanZeidt** [comment]
Same here, browser cache emptied but it persists. Also tried changing casts, doesn't work. Tried to cast on another task, no avail.

Log:
Iframe attached successfully
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Object
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Object
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Object
Golden Staff is two handed
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Objectconfig: Objectcached: falsedata: undefinedheaders: Objectmethod: "POST"transformRequest: Array[1]transformResponse: Array[1]url: "/api/v2/user/class/cast/backStab?targetType=task&targetId=cf97eee7-7d29-4da2-8b63-7179bd9658c8"**proto**: Objectdata: Objectheaders: function (c){if(!b)b=sc(a);if(c){var d=b[g(c)];if(d===void 0){d=null}return d}return b}arguments: (...)get arguments: function ThrowTypeError() { [native code] }set arguments: function ThrowTypeError() { [native code] }caller: (...)get caller: function ThrowTypeError() { [native code] }set caller: function ThrowTypeError() { [native code] }length: 1name: ""prototype: Object__proto__: function Empty() {}<function scope>status: 500statusText: "Internal Server Error"**proto**: Object__defineGetter__: function **defineGetter**() { [native code] }**defineSetter**: function **defineSetter**() { [native code] }**lookupGetter**: function **lookupGetter**() { [native code] }**lookupSetter**: function **lookupSetter**() { [native code] }constructor: function Object() { [native code] }hasOwnProperty: function hasOwnProperty() { [native code] }isPrototypeOf: function isPrototypeOf() { [native code] }propertyIsEnumerable: function propertyIsEnumerable() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }valueOf: function valueOf() { [native code] }get **proto**: function **proto**() { [native code] }set **proto**: function **proto**() { [native code] }

POST https://habitrpg.com/api/v2/user/class/cast/backStab?targetType=task&targetId=cf97eee7-7d29-4da2-8b63-7179bd9658c8 500 (Internal Server Error)nrWrapper @ (index):1(anonymous function) @ app-d16b6171.js:8s @ app-d16b6171.js:8f @ app-d16b6171.js:8j @ app-d16b6171.js:10(anonymous function) @ app-d16b6171.js:10j.$eval @ app-d16b6171.js:10j.$digest @ app-d16b6171.js:10j.$apply @ app-d16b6171.js:10(anonymous function) @ app-d16b6171.js:11n.event.dispatch @ app-d16b6171.js:3r.handle @ app-d16b6171.js:3nrWrapper @ (index):1

**Comment by VanZeidt** [comment]
Ok, it's solved now for me. The problem was that it couldn't get to the 60th level via backstab, because there was a scroll waiting for me and the program couldn't handle the backstab, the levelup and the drop at the same time. I completed the level with a plain daily, got the scroll, and then I could backstab without problem.

**Comment by crookedneighbor** [comment]
Ahh, thanks for that info. We recently made a change to the code to allow skills to level you up. Good to know that there is a possible conflict when gaining a quest scroll. We'll try to reproduce it.

**Comment by VanZeidt** [comment]
Yes, I several times leveled up with backstab. But if you click again on the daily to take it back, your level points are reduced without reducing your level. So you find yourself with negative level points. Also the drops you received and the damage to bosses remain. In this way you can kill any boss in one day with clicking and unclicking one task. Should I open another issue for this?

**Comment by deilann** [comment]
No because we generally don't consider things like those bugs.

There are legitimate reasons someone might click and unclick a task and get
double boss credit, like extra motivation or needing to accumulate boss
damage while in the inn and having to uncheck and recheck tasks. If someone
seriously wants to kill a boss in one day via nefarious means, they'll find
a way to do so, and trying to stop them in ways that will inconvenience
players who are using the site to their advantage is uncool. We've also
repeatedly believed that losing the drops you receive would be problematic.

We're in talks on another ticket about the negative XP. I personally think
it should remain and is the most logical choice, but we've talked about
other ways to handle it.

**Comment by Alys** [comment]
The behaviour described by @VanZeidt has also been reported by rickyrocky in the Tavern: "if you receive a scroll at a given level, you can't level up with a skill (es. backstab). It says Cannot set property 'drop' of undefined"

**Comment by crookedneighbor** [comment]
@ThereWasADream I edited your original comment and the title of this issue to make it easier (I hope) for people experiencing the bug to find this one.

**Comment by ThereWasADream** [comment]
I'm fine with that. To be honest, I could have sworn I leveled up multiple different ways trying to fix this. I haven't used HabitRPG since this issue screwed up everything for me but I will log in later and see what happens.

**Comment by ThereWasADream** [comment]
How about that, it worked. :)

**Comment by VanZeidt** [comment]
@ThereWasADream, I'm very happy about it, this made my day!

**Comment by Mandragora2** [comment]
Hi, I cannot pass my level I have this error too :(

```
https://habitrpg.com/api/v2/user/class/cast/fireball?targetType=task&targetId=c22dd481-f1c3-4a56-97ea-0976c2433792
```

```
targetId    
c22dd481-f1c3-4a56-97ea-0976c2433792
targetType  
task
```

```
[object Object]
https://habitrpg.com/app-c9d8e338.js
Line 39
```

User-ID : 910f0443-1694-4853-a4c6-40d591dc3d54

**Comment by VanZeidt** [comment]
Try to level up without casting a spell.

**Comment by Mandragora2** [comment]
@VanZeidt Thanks for your answer, it works for me. Sorry :(

**Comment by altsalt** [comment]
Reached level 60, error occured and upon reload, I was level 59 again. Ranked up with dailies, but quest scroll was not allocated.

Currently missing first scroll in the Moonstone Chain. Can it be added? Thanks.

User ID: 08b7ea3d-3210-46df-a7ca-dd7234ac9ae0

**Comment by Alys** [comment]
@altsalt Your account shows that you do have the scroll.

**Comment by ellem-0** [comment]
In case this comes in handy either to developers investigating this bug or users suffering from it:

I seem to have experienced this bug two days ago, but I never noticed any error message. Everything else fits, though, so I'm quite convinced that it's the same bug.

**Comment by salfej** [comment]
Apologies for writing up a less informative duplicate bug (#6311). I used to work in a QA environment where writing up duplicate bugs was discouraged. The error message said to report it if it was reproducible, so I did. =p This suggestion won't apply to this issue if #6315 fixes it up, but for future bugs that are easy-ish to detect, would it be possible to change their error messages since as they'd be known issues, or could the issue numbers be added to a console log statement or something to that effect? 

It's just a suggestion, but if you think doing something like that would save your teammates time curating new issues (preventing duplicate issues) and provide meaningful feedback to users, it might be a worthwhile investment at times.

**Comment by Alys** [comment]
@salfej When we're able to identify the point in the code where a customised error message would go, we'd normally then have identified what causes the bug and be able to fix it in that location. When there's common bugs, we try to make them easy to find by putting meaningful keywords in their titles and marking them with the "Memorable" label. That causes them to show up in the "most common issues" list that the bug report instructions recommend looking through, and the keywords in the title also make them easier to search for.
