### ISSUE TITLE
Died for no reason :(

### ISSUE THREAD

**Issue by vestais** [HabitRPG/habitica#4990]
I was feeding my pets when I suddenly got the message saying I died and lost a level and had one of my pieces of equipment break ... it happened to the other member of my party as well but she isn't concerned about it, so she doesn't want to make a post.

Here is my user ID: c5c3c0d4-3464-4ad3-bd3e-871b2b6f32bb
Here is the party group ID: 239f7b85-99e4-477b-8e27-809357fd0f7e

My browser is google chrome and I'm using windows 7!

**Comment by Alys** [comment]
If at least two members of your party died at the same time, then it will be because of the boss quest you are one. You can learn about bosses and the damage they do on the wiki at [Boss](http://habitrpg.wikia.com/wiki/Boss). You can see the damage done by going to your party page and clicking the "Fetch Recent Messages" button.

**Comment by vestais** [comment]
I had about 48 or 47 health though, I don't see how the boss could do that much damage...

**Comment by Alys** [comment]
Please go to the party page, click on the "Fetch Recent Messages" button, and look at the recent boss damage messages.

A boss can do a lot of damage if a player leaves Dailies undone or if there is an error like this one: https://github.com/HabitRPG/habitrpg/issues/4313 (see the Advice section at the top of the page).

**Comment by Alys** [comment]
I'm closing this since it's been a few months without a response, but @vestais let us know if you are still having this problem and see my previous comment for information.
