### ISSUE TITLE
Subscription disappeared

### ISSUE THREAD

**Issue by RankkaApina** [HabitRPG/habitica#4992]
I have a subscription (I paid for 3 months, so it should be up to like june) but I can't buy gems. Also if I go to subscription page it shows as if I don't have a subscription. I know it was there last week (before Easter).

**Comment by Alys** [comment]
Sorry about this @RankkaApina! Could you please email admin@habitrpg.com to report this problem? You don't want to do it here in GitHub because that could release your personal financial information to anyone who reads this. Please include a paypal receipt number or similar. Also include your unique user ID - to find that, go to Help -> Report a Bug and see step 6 of the instructions. Please note that it might take a few days for the matter to be sorted out, but it will be fixed.
