### ISSUE TITLE
weapon obstructs view of pet

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#500]
I realize this feature hasn't fully launched yet, but it's a little annoying being unable to see the pet I chose due to my character's sword covering most of them. Now, if my pet had the option of standing at my character's other side this wouldn't be an issue. Any chance of implementing something like that?

Thanks! Keep up the great work!
![Untitled-2](https://f.cloud.github.com/assets/3685170/189423/bb12ef7c-7e7c-11e2-873c-9b2b44ac9856.jpg)

**Comment by tmas** [comment]
Another option would be having the pet stand in front of the character and moving the character up a bit, but this wouldn't work well with larger pets. Maybe an options panel that lets you select where your pet stands? If people think this is a good idea I'll get to work implementing it.

**Comment by tmas** [comment]
Alright, I'm stumped on this. Anyone else want to give it a shot or explain how the pet positioning currently works so I can do it myself?

**Comment by ruddfawcett** [comment]
@tmas I'll do a little digging then get back to you...

**Comment by heather1209** [comment]
What about having the pet on the bottom right?

**Comment by wildcate** [comment]
Or moving the pet further out to the side? So it can be seen completely?

**Comment by Pandoro** [comment]
I noticed this as well. I was working on putting the pets into a CSS sprite. I put the pets a little more to the left and a little lower. So that it works with the biggest sword, sadly it looks rather funny when only having a small sword. 

Either we have to accept that one version looks a bit weird, or we have to make the placement depending on the size of the weapon. I'm not sure how easy or bug-prone this approach would be. 

![large](https://f.cloud.github.com/assets/1872333/204937/0a820f2c-8191-11e2-8093-d82ad5b06ce9.png)
![short](https://f.cloud.github.com/assets/1872333/204938/0aa92fa8-8191-11e2-84d6-102a6a0d46f9.png)

**Comment by tmas** [comment]
Perhaps we could have the pet stand further way depending on the size of
the sword?

**Comment by wildcate** [comment]
I think it's better, even if it looks a bit weird with the small sword. Have you tested the dfferent size pets with the new placement? Or just the wolf? I can imagine it might come out differently with another pet...

**Comment by Pandoro** [comment]
I have tried it with different pets as well. In fact my goal was to take
each pet and align it so that it works the best with the small and the big
sword. This would mean that all the in between swords will probably work as
well. But I haven't finished aligning them all yet.

The problem will also be that new pets and new weapons might seriously be a
problem again afterwards. But I guess it would be a good idea to already
have this version as it will at least improve the current results.

**Comment by heather1209** [comment]
I still believe putting the pet to the right might be a good idea.

**Comment by Pandoro** [comment]
A darn it! I was thinking to try this as well, but forgot about it again.
It would be a LOT easier, but who knows what that would do the the whole
mount idea, considering the pet might cover up the mount.

We should experiment with this though! If after all we decide not to place
the character on the mount, the mount could go to the left, as it is big
enough and it wouldn't be covered too much and the pet could go to the
right?

**Comment by wildcate** [comment]
I'm aware that this would complicate things muchly, but I think it wold be the coolest thing ever if it were possible to mount and un-mount a mount. That way one could enjoy both views! Maybe that would work with the mount going to the left when not being sat upon and the pet to the right?
Speaking of mounts... is there somewhere or a good way to suggest possible pets/mounts?

**Comment by Pandoro** [comment]
Let's see how mounts will work out once they are there.

To suggest them, I guess just post them in the Pixel Artist issues #107

**Comment by horusofoz** [comment]
Fixed through Zak's interface tweaking
