### ISSUE TITLE
Help! Gremlins Hacked my Account!

### ISSUE THREAD

**Issue by lisamaystowe** [HabitRPG/habitica#5003]
I opened my task list this am and my tasks have been deleted except for a couple; in place are tasks that are nothing but a bunch of numbers and letters in random order. When I wave my cursor over one of these rogue tasks it says it was added by a third party. I am lost without my tasks and rewards! Please help.

**Comment by hairlessbear** [comment]
What's your your user ID (UUID)? (If you don't know where that is, [here's how to find it](http://habitrpg.wikia.com/wiki/UserID#UserID).)

**Comment by lisamaystowe** [comment]
cf14261d-566a-42dc-8779-06463ab50420

**Comment by lisamaystowe** [comment]
I left my ID up for a while today; if that is not going to help you help me I am going to take it down for now. I really love this app and am very disappointed it quit working. I really don't want to go find another. :(

**Comment by hairlessbear** [comment]
I'm not a developer on the site, so I can't check what happened with your account. But, [as detailed here](https://github.com/HabitRPG/habitrpg/issues/2760), the developers need your UUID to locate your account so they can determine what went wrong. They're a very small team of dedicated folks, so they can't promptly respond to everything, but they'll get to this as soon as they can.

**Comment by hairlessbear** [comment]
In the meantime though, I can try to help you troubleshoot. You said that the tasks said they were "added by a third party."  As you can see [here](http://habitrpg.wikia.com/wiki/Thread:8878), this means that a separate application changed the tasks in your account. This is only possible if you copied your UUID and API Token into the separate application. Do you remember doing that with any other apps? [Here is the current list of apps that might have accessed your account](http://habitrpg.wikia.com/wiki/App_and_Extension_Integrations).

**Comment by hairlessbear** [comment]
Actually, reading over your original issue again, it sounds like this might be an iteration of a known bug (#1402), although I can't find any mention of the bug causing tasks to be deleted before.

**Comment by lemoness** [comment]
Hi Lisa,

We're sorry that you're having this trouble! First, can you try clicking
the button that says "Clear" next to tags? A hidden tag may simply be
obscuring your tasks.

If that doesn't work, let us know, and we'll investigate further.

**Comment by Alys** [comment]
@lisamaystowe I am sorry you are experiencing these bugs and I will do everything I can to help you, but please be aware that as @hairlessbear says, there are only a few admins and we can't always respond immediately. In my case, I have only just woken up ten minutes ago, so I couldn't reply earlier.

@hairlessbear is correct about the bug in their post above this one. There is advice in that bug near the top - basically you can just delete the task.

For your missing tasks, please see the original message that you posted here: https://github.com/HabitRPG/habitrpg/issues/4957#issuecomment-91227974 ! You will see that I responded to that several hours ago. Please reply there so that we can keep this all in one place. I am closing this issue now since it is a duplicate. Please try not to make duplicate bug reports because it doubles the effort needed to help yo.

**Comment by Alys** [comment]
@hairlessbear Thank you for your help with this! :heart:

**Comment by hairlessbear** [comment]
@Alys Glad to help!

**Comment by gisikw** [comment]
False. We all know that @Alys does not sleep :p

**Comment by Alys** [comment]
:smile:  Giggling with slight bitterness because I was able to sleep for only 4 hours last night. :)

**Comment by lisamaystowe** [comment]
Thank you! I will look into this. I just got very frustrated yesterday,
sorry
