### ISSUE TITLE
Can't leave Guild from Guild page

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5026]
When on the page of a guild you're a member of, the button that should let you leave (left side of the page, to the right of the guild title) is still displaying "Join". Clicking the button refreshes the page, but doesn't change the button to "Leave" as it should. It is still possible to leave guilds via the [public guilds page](https://habitrpg.com/#/options/groups/guilds/public).

The bug occurs in Firefox and Chrome (I didn't test anything else).

**Comment by Alys** [comment]
It's a known problem but one that is surprisingly hard to fix. To know for sure that the user is already a member of the guild (and therefore needs to see the leave button), the website needs to look through the list of all guild members, which can be many thousands for some guilds, which creates a large load on the site. We're planning a fix here: https://github.com/HabitRPG/habitrpg/issues/4427

I'm going to close this issue now since that other one covers it, but you can subscribe to notifications for that one if you'd like to be emailed whenever there's an update.

**Comment by hairlessbear** [comment]
Got it, thanks @Alys!
