### ISSUE TITLE
Day task in habit

### ISSUE THREAD

**Issue by Nopinopa** [HabitRPG/habitica#5034]
This problem exists for months, so I decided to write you.
Safari 8.0.4 (10600.4.10.7), MacOS. No problem in JS was written.
My ID: febd6916-721c-48be-a3e2-f78e27793e06
![2015-04-16 0 56 19](https://cloud.githubusercontent.com/assets/11968893/7170132/26bb5a70-e3d4-11e4-944b-ed689f35f036.png)

**Comment by crookedneighbor** [comment]
@Nopinopa I've removed the bad task. Trying to figure out how that would have happened. Do you use any third party tools that interact the HabitRPG API?

**Comment by Nopinopa** [comment]
For me it's steal there (I cleaned the cache), but now I'm not found.
![2015-04-16 1 45 29](https://cloud.githubusercontent.com/assets/11968893/7170881/aa0e9954-e3da-11e4-9e9f-ba6d3c0dbc2d.png)

Well... Nope. Nothing.

**Comment by Alys** [comment]
We're very sorry about this @Nopinopa! The database must have been glitching when the task was removed. We will restore your account but unfortunately it's a very slow process and it might take up to four or five hours.

**Comment by Nopinopa** [comment]
OK, I understand. Thank you, you are the best support ever :)

**Comment by Alys** [comment]
@Nopinopa Your account should now be back the way it was when the database backup was made, which was about 15 hours ago. I am sorry that we could not give you any more recent information. I have deleted that Habit. Please tell us if anything else is wrong!

Note that I have caused your account to be Resting in the Inn, so that you won't take any damage from your Dailies if they are not yet marked as completed. If you're not sure what that means, this wiki page will explain it: http://habitrpg.wikia.com/wiki/Rest_in_the_Inn
And of course you are welcome to ask us as well.
