### ISSUE TITLE
Died while resting in the Inn, no boss.

### ISSUE THREAD

**Issue by cesarioviola** [HabitRPG/habitica#5039]
I didn't see a title corresponding to this, so I apologize if this is a repeat. I just came back from a couple of days out of town. The last thing I did before leaving the house was make sure I was resting in the inn. This morning I logged in and opened the Social tab to check out of the inn. I saw the "check out of inn" option, implying that I was actually resting, but before I could click on it I got the "you died" popup and lost all my gold, etc. Is there anything I can do about this? Thanks for your time.

**Comment by hairlessbear** [comment]
Were you participating in a quest? If so, any damage done to your party was also done to you, even though you're resting in the Inn.

If you weren't on a quest and want to get your lost level and gold back, you can manually change the values yourself by clicking on the gear in the top right corner of your page, and navigating to "Site -> Fix Character Values".

**Comment by cesarioviola** [comment]
I have a party of just me, and the only quest I'm in is finding eggs, so that shouldn't have affected me, should it?

**Comment by cesarioviola** [comment]
Also, I don't actually remember what my values were on Monday. Is there a way to find out?

**Comment by hairlessbear** [comment]
Nope, collection quests shouldn't hurt you (after all, it would be pretty difficult to injure oneself searching for eggs). I'm not an administrator here, but if you post your User ID (located in Settings->API), an admin will be along to help you as soon as they can. 

Unfortunately, it's not possible to get that info back. You'll have to do your best to approximate the values.

**Comment by cesarioviola** [comment]
Thanks for your help. Here's my UserID in case an admin can shed more light on the subject. 
a6af781a-54a6-4882-88dc-49b592c9eeff

**Comment by hairlessbear** [comment]
Glad to help. One last thing: I'd suggest editing this issue's title to include the fact that you weren't on a boss quest, just for clarity's sake. Often, when users bring up dying while resting at the Inn, it's because they didn't realize boss damage still hurts you, so distinguishing this issue from those would be helpful.

**Comment by cesarioviola** [comment]
Thanks! I will.

**Comment by GNAdv** [comment]
This just happened to me over the long weekend. Was NOT on a quest of any kind. Went into rest mode on Friday via iOS — or so I thought (there was nothing to indicate I hadn't). Logged in on desktop this morning to find I was almost dead (2<3s left).

**Comment by karolyuuki** [comment]
It happened to me today. I was on the Inn since sunday, because I was on two really busy days and couldn't do all my tasks, but today when I logged in I was dead. Still in the rest mode, but dead, lost a level and all my gold.
ID: 974a74af-04d2-4458-bd26-6c2718c3e733

**Comment by Alys** [comment]
@karolyuuki I've looked at a database backup that was made on 2015-08-24 12:01 GMT. It shows that you last logged in 2015-08-23 23:59 GMT (Sunday, as you say), but that you were **not** resting in the inn at the time that the backup was made. I believe that your action to rest in the inn was recorded by your browser but your browser did not send that action to Habitica's server until after you used Habitica again today/yesterday (by which time it was too late, unfortunately). This would be an example of [this bug](https://github.com/HabitRPG/habitrpg/issues/4313), although a different aspect of it than is discussed in most of that issue.

I'm very sorry about this! If you look at the Advice section near the top of that issue, point 2 will tell you how to recover your health, gold, etc.

If you need to rest in the inn again, reload the website after you've done so to make sure your avatar is still shown as sleeping, although that's not always completely reliable because the bug can sometimes be very persistent. A more certain check is to use the Data Display Tool from Habitica's Data menu -- it will display "Zzzz" in its dashboard if you are sleeping, and it takes that information from Habitica's servers so it can't be wrong.

---

I suspect that the same explanation applies to the other reports of this problem, although in the past I haven't had a database backup available to check that.

**Comment by Alys** [comment]
I'm closing this on the assumption that my explanation in the previous comment is correct (i.e., this issue is a side effect of https://github.com/HabitRPG/habitrpg/issues/4313). We can reopen it if there seems to be a different cause for it.
