### ISSUE TITLE
Change the size of the Reset button so it is smaller than the Cancel Button

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#504]
If the Reset button is bigger, it makes it easier to press, even if people don't want to reset their account.  Just a small thing.

![Screen Shot 2013-02-24 at 3 06 19 PM](https://f.cloud.github.com/assets/3122471/189954/e6bcaec4-7ebd-11e2-95f9-d7cd50f98757.png)

**Comment by Olathe** [comment]
I've heard an idea along those lines in some UI design book. It went something like: if a destructive action can't be undone, put the buttons that do it far away from the buttons that cancel the request so that there are no accidental clicks on the destructive action when you meant to cancel. This isn't a very common thing, but it should be.

**Comment by Pandoro** [comment]
I very much support this! I listed it as difficulty-easy considering it should be rather trivial to change this.

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/commit/b1c770c0f9d655ba2774675c463806460aeb7069 (next push)
