### ISSUE TITLE
Unchecking a "completed" To-Do in the Done tab resets gold to 0

### ISSUE THREAD

**Issue by kpbarry** [HabitRPG/habitica#5064]
If you move a 'Done' To-Do back to 'Active' by Unchecking it in the Done section under To-Do, your gold will be reset to 0.

100% reproduction rate

**Comment by deilann** [comment]
Not able to repro.

What I'm guessing here happens is that you're losing the gold you gained by
checking off the To-Do and it's more than or equal to the amount of gold
you currently had. Which would be expected behavior, that your gold would
be reset to zero.

If you're unchecking the To-Do not because you accidentally checked it off
but because you want to do that task again, you should create a new To-Do.
