### ISSUE TITLE
Costume pieces needn't respect Two-Handed tag

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5074]
Mage weapons have the Two-Handed property, meaning you can't equip an off-hand item when you have one equipped. That makes sense for battle gear, because they combine the statistical benefits of both primary and off-hand weapons. However, there's no particular reason you couldn't display a Two-Handed item and an off-hand item on the Costume, given the way the sprites are set up. Allowing those combinations would make sprite dress-up more flexible!
##

**Comment by crookedneighbor** [comment]
Personally, I'd like to keep it consistent, but I don't have strong feelings about it one way or the other.

**Comment by deilann** [comment]
My kneejerk reaction is I want to keep it consistent. I can't imagine the
newbie comments asking why...

**Comment by Alys** [comment]
Yeah, that was my thought too. Endless Tavern questions and the occasional bug report.

Also, it seems odd to me - a weapon is two-handed not because it's powerful but because it's big. It remains big even for costumes. I would love the extra costume flexibility but it doesn't feel like a right solution.

But maybe if we could buy/earn some magic trinket that would hold an extra item in place as a (costume-only) illusion...  Perhaps a gold-buyable thing that evaporates on cron...

**Comment by lemoness** [comment]
Yes, I think I'd like to do this as a work-around, such as Alice's special
item idea, rather than making it the norm.
