### ISSUE TITLE
Fix searing brightness (healer skill) logic a bit.

### ISSUE THREAD

**Issue by acoundexist** [HabitRPG/habitica#5075]
Searing brightness, the Healer class skill that reduces redness of all tasks, also reduces redness of To-Dos.
According to wiki (link below), red To-Dos are more valuable than the ones that were just added!
As a result using this ability reduces exp and gold income of To-Dos.

wiki link: http://habitrpg.wikia.com/wiki/To-Dos

**Comment by Alys** [comment]
As a contrasting point of view, some players find red To-Dos to be stressful; Searing Brightness would allow them to avoid red To-Dos.

There are probably also players who do want to reduce the earnings from To-Dos because we fairly often see people talking about how red To-Dos give more XP and GP than they should.

I don't feel strongly about this either way because I don't play Healer. Instead, I'm playing devil's advocate. :)

**Comment by Alys** [comment]
I'm closing this because we now have a Trello card for commenting on problems with skills: https://trello.com/c/TjZc6PnC/466-skills-v3-stat-rebalancing

@acoundexist If you still feel that the skill needs changes, please comment there.
