### ISSUE TITLE
Trouble Clicking Play Button on Mobile Site

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5111]
I've just received my fourth report of this, so I am going to make a bug report.

For some users, clicking the "play" button on the mobile website has no response. This is not the case for every user.

Some comments from affected users:

"When I visit the website to try and click on play habit RPG to try and log in as it were, the site go's no further.  The button changes colour slightly but no hyperlink is activated." (Phone and browser not yet known)

"when I click on the link it just takes me to your website which is unresponsive in the sense that it has the big blue 'play for free' button which doesn't seem to work." (Using the iPhone iOS 8.3 on Safari) 
##

**Comment by ramblinjan** [comment]
"Play" button no longer exists. Can we close this or does it persist with the current UI?

**Comment by Alys** [comment]
The "Play" button has been renamed to "Enter Habitica" and "Join for Free" but I don't think the underlying code was changed. I'd guess that both would display this problem on any system where the problem does exist. It was never occurring on all mobile browsers so it's hard to say if the problem still exists or not.

**Comment by joe-salomon2** [comment]
I could try and resolve this issue. I would use an automated testing tool like Selenium to try out all known mobile browsers and see if the button worked. If they all pass, would you consider this issue resolved?

**Comment by Alys** [comment]
We're re-writing the website's front end code so this problem will
disappear when that's finished or will have a different cause/fix. It's
probably not worth spending much time on this. My personal opinion is that
if it's quick and easy to set up the tests, you could go ahead with that,
but note that if you found a specific problem and the problem was hard to
fix we might recommend that you don't work on it and it's possible that a
fix would not be accepted if it was finished shortly before the new code
went live.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.
