### ISSUE TITLE
Saddles don't work in mobile app

### ISSUE THREAD

**Issue by DSDragon** [HabitRPG/habitica#5115]
User: 3789974f-65c6-4cb0-a048-dc958f138c35

I purchased a saddle with gems, and on the mobile app for Android (Samsung Galaxy S5) I tried to use it the same way food works, but nothing happened.  I didn't even get a pop-up question.  However, it worked fine when I tried the same thing in Internet Explorer on my laptop computer.

**Comment by Alys** [comment]
I'm closing this because we are working on a new, native app for Android which will be an improvement over the current one. It's not finished yet but is close. We're still updating the old Android app for critical bug fixes, but for optional features like using a saddle, it's better than we leave it broken for now and focus on the new app. I'm sorry for the inconvenience! You might find that this feature works on mobile browsers.
