### ISSUE TITLE
bought things dont stay bought

### ISSUE THREAD

**Issue by Muff1nD3rpXZX** [HabitRPG/habitica#5122]
i bought the puppy armor and it didn't keep. i tried multiple times but 5 seconds later it unset it and gave me my coins back. i tried with all the puppy stuff! i have safari and a macbook pro... i dont know why its not working... my username is same as here

**Comment by Alys** [comment]
This happened because the armour and other gear has been removed from the site, but your browser hasn't caught up with the changes yet. If you reload, you'll see that the gear no longer appears. However since that's a bit unfair to you, I can give you the gear. Please tell me your unique User ID (go to Help -> Report a Bug and look at step 6 to find out how to find it). We can't use your username because two or more people can have the same name.

**Comment by Muff1nD3rpXZX** [comment]
1d906dac-6ef7-447d-a439-f0584f9bf62f

**Comment by Muff1nD3rpXZX** [comment]
thank you!

**Comment by Muff1nD3rpXZX** [comment]
ive refreshed a lot and it still shows them in the shop...

**Comment by Alys** [comment]
Hmmm. Let's just ignore that inconvenient fact. :) 

I've assigned them to you. Reload your equipment page and you'll see them.  If you don't, comment here and we'll keep helping you, even though I'm closing this now.
