### ISSUE TITLE
Unable to delete a Test Party I created!

### ISSUE THREAD

**Issue by Melmel** [HabitRPG/habitica#5136]
Hello!! 
I am a university student and I would really like to contribute something to HabitRPG as part of a course I currently attend. 
As I am new to contributing, I apologize if this is not really a bug, but my misconception.

The bug I have found is that, when I created a Test Party (while I was just discovering the site), I did not have the ability to delete it, only to leave it.

My party does not have any other members, but me, shouldn't there be a delete button? 
If this issue is categorized as a bug, could I solve it by contributing? 

Maybe someone could give me some advice on this? Thank you in advance!! :)

**Comment by Alys** [comment]
Hi @Melmel! It's normal for there to be no way to delete a party. The party becomes inaccessible as soon as the final participant leaves it (because then no one can invite anyone into the party). We've never considered this a problem, although I suppose at some time we should go through the database to remove all the empty parties and empty _private_ guilds (not empty public guilds because people can still join them).

I'm not sure I'd be happy with a delete button on parties. There'd be too much chance of players using it by accident (even if we included a confirmation step). It's also another thing for players to have to think about, another thing for us to document. My opinion is that the current situation is better.

What do others think?

**Comment by Melmel** [comment]
Hello!! Thanks for answering to me!^_^ My suggestion is that a party could only be deleted by the owner and only when there are no other members there! Maybe then, deleting would be useful and less occurring, so it will be easier to maintain it as a feature, for you and for the players.

**Comment by Alys** [comment]
To be honest, I think the effort involved in answering questions about party deletion would be greater than the effort to occasionally purge the database of empty parties. We'd get questions like "I want to delete my party, why can't I see the button?" (to which the answer would be, because there's still other players in the party or because you aren't the leader) - questions like that are surprisingly common. 

There's no reason to remove empty parties except for reducing database performance, and we can handle that ourselves in the backend. Even if there were a delete button, not all players would bother to use it, so we'd still need to purge empty parties ourselves occasionally.

@Melmel What are your reasons for wanting to delete a party?

**Comment by crookedneighbor** [comment]
I would be fine with the leave code deleting the party/private guild when there is no one left in it, especially since there's no way to rejoin them. There need not be any change to the front-end implementation, it can still say "leave".

Doesn't make sense to me to have dead parties and private guilds sitting in the database waiting for us to clean them up eventually.

**Comment by Melmel** [comment]
Hello Alys, hello  crookedneighbor! 
Alys, to answer your question, I am just trying to find a way to contribute to Habit, and as a user that was the "bug", I saw when moving around the website. 

Thinking from the side of the user, I thought, that a feature a user creates, should also be a feature a user can delete. Like a group that a user creates on a social media platform, a party should also be something that could be deleted.

But that was just my thinking, and I can totally understand the issues it would cause, regarding the questions players would have etc. 

If  you would like, I could always try to implement the option crookedneighbor offered; for the party to be deleted only when the last member-owner selects the Leave button.

**Comment by Melmel** [comment]
Hello @Alys and @crookedneighbor, I will take the plunge to start working on this, and hopefully I will have a result by the start of June (I am new to contributing that's why I will need that much time!). 

Please let me know in case you disagree! Have a nice day!

**Comment by Alys** [comment]
@Melmel That sounds great! You can comment here if you run into problems or need any advice. You might also like to join the Aspiring Coders guild, where you can also ask questions or help others with their problems if you wish to!

**Comment by Melmel** [comment]
Thank you, I will join the Aspiring Coders guild, sounds like a nice idea!

**Comment by Melmel** [comment]
Hello @Alys and @crookedneighbor I would like to inform you that I have been working on my contribution, by understanding the technologies and the code of the website.

I think I should place the deletion of the empty party in the $scope.leave of the party inside the groupsCtrl.js public controller.

I actually placed db.groups.remove({_id: $scope.selectedGroup._id});   , but that did not work -obviously- on my local run. Could you please give me some advice? It would be greatly appreciated!!

**Comment by crookedneighbor** [comment]
@Melmel This is the function that will need to be modified: https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/groups.js#L479-L554

You'll want to use [the Mongoose model findByIdAndRemove function](http://mongoosejs.com/docs/api.html#model_Model.findByIdAndRemove), so for this case you'd do: `Group.findByIdAndRemove(group._id, function() { // do stuff })`

Things to look out for:
- Only do this if the group is a party or private guild and there are no other members. IE, public guilds should be allowed to have no members, since they are still accessible to be joined.
- Since you're changing API behavior, [we'll need changes to the api tests for groups](https://github.com/HabitRPG/habitrpg/blob/develop/test/api/groups.coffee). Looks like we don't currently have a test for the leave route, so it'll need to be added.

**Comment by Melmel** [comment]
@crookedneighbor thank you very much for your feedback!! I will try to test this locally and will let you know regarding my progress!

**Comment by Melmel** [comment]
Hello @crookedneighbor I added the following, on the src/controllers/groups.js, after the // FIXME comment, but again when I run it locally the group is not deleted:
      if(group.type == 'party' && group.members.length < 1) {
          Group.findByIdAndRemove(group._id, function(err) { 
              if (err) throw err;
          });
      }

**Comment by Melmel** [comment]
should I also add code on the public groups controller? Moreover, since it did not work, why the error was not thrown? :(

**Comment by Melmel** [comment]
I found the reason why it was not running!! When this method is checked, the user has not yet left the party, so the groups.members.length still equals 1. I changed it and it run perfectly!! :D

Moreover, I checked the case of multiple private-guild/party members and thankfully, the private-guild/party is not deleted when a random member leaves but there are still others left! So happy, it works!

Also implemented it for private guilds, with the following code:
if(group.type === 'party' && group.members.length == 1 || group.type === 'guild' && group.privacy === 'private'&& group.members.length == 1 ) {
          Group.findByIdAndRemove(group._id, function(err) { 
              if (err) throw err;
          });
      }

**Comment by Melmel** [comment]
@crookedneighbor hello once again! thank you for your great help!

I will be creating a pull request for typical reasons, although I understand it may not be accepted, unless me or someone else creates the additional required tests. I would be very happy to create them. Could you please direct me to some documentation regarding how these tests are created, and how they are run, so that I can start?

**Comment by hairlessbear** [comment]
@Melmel it would be much easier to help you troubleshoot and write tests if you created a pull request now, even though you aren't done writing your code. That would allow experienced people (like @crookedneighbor) to more easily examine your code and assist you. 

As it stands, it's difficult to understand exactly what you're changing when it's spread out across multiple comments with multiple changes. In a pull request, all your changes are shown in proper context of the code itself, making it much easier to follow.

#### Edit

I see a pull request has already been created, but this issue hasn't been linked. I'll fix that.

**Comment by Melmel** [comment]
@hairlessbear Thank you very much for the information, and for the advice of connecting the issue with the pull request!

**Comment by paglias** [comment]
Moved to #5871
