### ISSUE TITLE
Front page business.html dead link

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5142]
https://habitrpg.com/static/front has a link to https://habitrpg.com/business.html should it be https://habitrpg.com/static/plans instead?

**Comment by AnitaYCheng** [comment]
Yes, it should! Thanks for the note. I think since it was embedded in the use case carousel, it got missed the first time.

I'm still struggling with my local install of HabitRPG, and I should get that finalized before I tackle any more commits to the front.jade file. I keep bothering @crookedneighbor to fix my typos since I can't see what I'm doing, haha. But this should be a quick fix!

**Comment by NotGonnaGitUs** [comment]
Great catch! 
I'll send a pull request within the hour.
