### ISSUE TITLE
Boss not taking or giving damage for over 24 hours

### ISSUE THREAD

**Issue by shalera** [HabitRPG/habitica#5152]
We are in group ID: ff226c0e-6dda-4ee1-918d-f7ac5b8d136e and currently on the Vice part 3 quest. The boss has been on 391 remaining HP for over a whole day. No damage either towards the boss or towards us has been updated for over 24 hours. 

The last action we have is that one of us cast Earthquake on 05/04/15 at 06:37:30, but when I logged in at around 08:30 my damage from the previous day's dailies didn't show (and I did a lot the previous day!). 

The weird thing is that when I first logged in, I and at least one other person got the notification saying we had completed the quest, then went to start a new one and couldn't. I checked the party page and it was still the same quest as before. I tried Syncing and refreshing a lot of times, and trying on different platforms (PC, iOS, Android) but they all showed the same thing.

![viceproblem](https://cloud.githubusercontent.com/assets/12255356/7475283/a1b61c20-f314-11e4-85fa-62404487501b.PNG)

**Comment by Alys** [comment]
For my reference:

```
{
    "type" : "party",
    "quest" : {
        "leader" : "73d88f09-384f-4e75-a180-111d037e783b",
        "members" : {
            "b562e35d-3494-4839-abdb-606c5e4715db" : true,
            "d9903a8d-98f4-4104-8f08-1e07c1206ac6" : true,
            "e9bf00cc-761e-495d-8348-153cf3b9efe0" : true,
            "73d88f09-384f-4e75-a180-111d037e783b" : true,
            "6c62f58b-6788-4a5a-b637-78c4207ec655" : true,
            "cf31d1df-8768-4917-89b8-192930361b74" : true
        },
        "key" : "vice3",
        "progress" : {
            "hp" : 390.6417190368479,
            "collect" : {

            }
        },
        "active" : true
    },
    "members" : [
        "cf31d1df-8768-4917-89b8-192930361b74",
        "6c62f58b-6788-4a5a-b637-78c4207ec655",
        "73d88f09-384f-4e75-a180-111d037e783b",
        "e9bf00cc-761e-495d-8348-153cf3b9efe0",
        "d9903a8d-98f4-4104-8f08-1e07c1206ac6",
        "b562e35d-3494-4839-abdb-606c5e4715db"
    ]
}
{
    "_id" : "6c62f58b-6788-4a5a-b637-78c4207ec655",
    "party" : {
        "quest" : {
            "key" : null,
            "progress" : {
                "up" : 30.04952698994184,
                "down" : 0,
                "collect" : {

                }
            },
            "completed" : ""
        }
    },
}
```

All party members have the same quest data in their accounts as the latter entry there.

**Comment by shalera** [comment]
Hey, I'm not sure if it was you or someone else but it's finally fixed! Thanks!

**Comment by Alys** [comment]
@shalera The quest was completed and the quest progress information was removed from each party member's account correctly, but the party object wasn't updated so it looked like the quest was still running. I have edited your party to remove the quest. Post a comment here if anyone in your party has trouble starting a new quest.

I recommend that each person in your party checks to see if they received the rewards and achievement from the quest. You can see them in the "Rewards" section at http://habitrpg.wikia.com/wiki/Vice_Awakens (click on the spoiler button to show them). If anyone doesn't have them, post their name or user ID here (normally we require the user ID, but in this case the name would be sufficient since I have the full party list from your party object).
