### ISSUE TITLE
Missing Attribute Points 

### ISSUE THREAD

**Issue by JustTeaForMe** [HabitRPG/habitica#5153]
Since the last update, I was over one hundred in my levels, so I had more than one hundred attribute points. Now I have one hundred. What happened to all of my attribute points that I had distributed?

**Comment by Alys** [comment]
Please see [Skills Rebalancing and Other Changes -> Attribute Points Change](http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Skills_Rebalancing_and_Other_Changes#Attribute_Points_Change) for a description of how attribute points have changed since the latest update. The final paragraph in that section is the most relevant to you. You can reply here if it does not explain why your points disappeared.
