### ISSUE TITLE
Automatic translations updates

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5155]
Currently translations have to be updated manually running a script that download the files from Transifex, we should move it to a step in the build process, see https://github.com/alicoding/node-transifex
##

**Comment by ghost** [comment]
@paglias Thank you! It's a great idea to have translations updated automatically! I believe it's the way it should be

A couple of thoughts:
1. There should be some sort of protection against erroneous translation updates. Let's say someone misunderstands a concept and decides to "fix" what's been working before. Or someone's transifex account is stolen and can be misused - the bad guy can alter the text to show something wrong. Ideally only files reviewed up to 100% - and thus protected from erroneous edits should be updated automatically...
2. ... However quite a few lines are still questionable as reviewers don't completely agree on some variants of translations. That's why they are waiting for other suggestions and don't mark the lines as reviewed. This pattern should be changed if (2) is applied as I don't see any other way transifex can protect translation files from being changed. Reviewers (including myself) should mark lines as reviewed with less doubt and translators should use suggestions rather than translating the text directly then.

**Comment by ghost** [comment]
@paglias Well, after thinking it over once again, I must admit my comments from above have little to do with automatic translation updates. With manual updates the risks are just the same. So I believe in any case we (reviewers) should review the suggestions much quicker and only after that wait for better suggestions. Sorry for stealing 2 posts from your ticket )

**Comment by paglias** [comment]
@GitHubSphinx the current method is completely automated too (no reviews of translations before pushing) but it requires me to run it. I want to make it so that my intervention is not required. After that we can see to tackle the other points you wrote about

**Comment by ghost** [comment]
Somewhere in Transifex UI I've found something which seems to be an easy implementation of web hooks:
https://www.transifex.com/_/resources/ajax/habitrpg/habitrpg/content/autofetch/

As far as I understand, it's meant to automatically update files in Transifex projects when they are changed in the source url.

I haven't tested it yet as the risk of losing translations / translation memory is quite high. If you would like to test it, please use dummy file or even dummy project first.

**Comment by paglias** [comment]
I think I tried it but for some reason it didn't work. Actually running our own script is not  a big problem and we can simply automatize it

**Comment by ghost** [comment]
As I don't know the right place to ask for that, I'm using this thread (also sending notification to @crookedneighbor)

Could you please let us know when the next locales update will take place, if possible, so that one of the Chinese translators could check possible issue with two versions of MMMM reported previously here: https://www.transifex.com/habitrpg/habitrpg/translate/#zh/gearjson/22835800

**Comment by ghost** [comment]
I'm not sure who uploads the files to Transifex now, so may I have the attention of @paglias or @crookedneighbor or @SabreCat 

Please excuse me if it's a false alarm, but could you please check if your update script includes all the files. 
July 27, 2017 we get 5 files updated with new content on Transifex, but not the following files: front.json, messages.json, newClient.json (missing), npc.json, settings.json

**Comment by SabreCat** [comment]
@GitHubSphinx: newClient.json is intentionally left out for now, as that's not ready for public use yet. The update script has the rest, but the base strings either haven't been edited in those files recently or have only been edited on `develop`, not `release` which represents what's actually being deployed to production. You should see those files get updated today where necessary.

**Comment by ghost** [comment]
@SabreCat thank you very much for clarification!

**Comment by Alys** [comment]
I'm closing this since we're not using transifex any more and I _think_ the translation string upload/download process is at least partially automated or at least scripted now.

If I'm wrong, we can reopen this or start a new one that doesn't mention transifex, but it might need to have details of the current process to help work out where it can be improved.
