### ISSUE TITLE
no attribute points after leveling up

### ISSUE THREAD

**Issue by weksx** [HabitRPG/habitica#5164]
I recently cancelled my subscription, and since then I stopped receiving any attribute points after leveling up. 
My user ID is 4ecd43c3-09ad-48ea-9d5e-7ae85b27c807
I am using Google Chrome and Windows 7 64 bit

**Comment by hairlessbear** [comment]
Would you happen to be level 100 or higher? The attribute points behavior was recently changed so that no more attribute points are awarded after level 100 (although points you already have won't be removed). [Read more here](http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Skills_Rebalancing_and_Other_Changes#Attribute_Points_Change).

**Comment by weksx** [comment]
Yes, I'm above level 100, so that explains it. Thanks!
