### ISSUE TITLE
Sync doesnt update party quest invitation status

### ISSUE THREAD

**Issue by Nowbob** [HabitRPG/habitica#5176]
If I invite my party to a quest with me, I have to refresh the whole page to see their status update instead of just syncing. Intended?

**Comment by Alys** [comment]
It's expected behaviour, even if it's not always desired behaviour. See https://github.com/HabitRPG/habitrpg/issues/4235 for more details; it discusses avatars mostly, but party quest stats would be handled similarly. If you wish to, you can subscribe to notifications from that issue to follow its progress, in case we make a change that affects it.
