### ISSUE TITLE
Drops re-spawning when re-checking dailies

### ISSUE THREAD

**Issue by hannyyeung** [HabitRPG/habitica#5186]
For example:
Drop "Meat" is received after checking a daily "Daily A"
Unticking "Daily A" will remove the XP and Gold receive when it was checked, but not the drop ("Meat")

The main issue is, when "Daily A" is checked again, there is a 100% chance of re-receiving the drop calculated previously ("Meat").
This will encourage users to exploit the bug and duplicate the drops they receive, until they reach their drop cap. If Tools of the Trade is being cast multiple times by a high-level rogue in the party, everyone can have a very high drop cap.

**This bug heavily devalues the drop system, effectively cutting income for the game from the Market, and harm the purpose and mechanics of the game.**

I would recommend either, if not both:
- remove the drop received when a daily is unchecked, just like how XP and Gold are removed
- re-calculate drops when a daily is re-checked, instead of having the same results from previous calculation

**Comment by Alys** [comment]
We don't want to remove drops when tasks are unticked for reasons explained here: https://github.com/HabitRPG/habitrpg/issues/4626

Drops are calculated randomly but with the user's gold balance as a seed. A known seen is necessary because we need to perform the same drop calculation on the client for immediate feedback and on the server for permanent storage, so the "randomness" has to be predictable, while still being mostly random. It would be ideal to give a different drop every time the same task was ticked and unticked, but we'd need to find some other way to seed predictably (possibly gold + number of eggs+potions+food).

However I'm not certain this is an urgent problem. Your point about cutting income might be true but I'm not sure how often people buy eggs, potions, and food (@lemoness?). I would guess that it would only cut income noticeably if the drop happened to be one of the rare ones, and happened to a person who would be willing to keep clicking the same task and who would have been willing to buy that drop if they hadn't received it. 

We typically don't care about "cheats" that harm the purpose and mechanics of the game because the "cheat" hurts only the player who does it, and possibly not even them, if they are motivated by the action - for example, they might use a gold reward each time they re-ticked the task, and so they'd be motivated to do more tasks to earn more gold.

**Comment by lemoness** [comment]
People buy food, eggs, and potions in moderate amounts - but it's
definitely not our biggest income source.

**Comment by hannyyeung** [comment]
@Alys Apologies for forgetting to search closed issues before I post, and thanks for resolving the struggle I have been experiencing. Your suggestion of using custom rewards as a remedy for this "cheat" / the original "wishing well" idea are both excellent. Cheers.
