### ISSUE TITLE
No attribute points gained; wrongful death

### ISSUE THREAD

**Issue by mindykay32** [HabitRPG/habitica#5188]
User ID:  19864643-df4b-4ab2-bf7a-b19f32ec2b8d

Since the latest update to HabitRBF (concerning mana) I have have not earned any new attribute points when leveling up.  Then, yesterday, I completed all of my dailies and to-dos that were due for the day, but received a message that I had died when I logged in this morning, resulting in a loss of all my gold, a level, an attribute point (even though I was already missing several of those).

I am using Windows 8 and Google Chrome.

**Comment by Alys** [comment]
You can read full details about the recent changes at [Skills Rebalancing and Other Changes](http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Skills_Rebalancing_and_Other_Changes). The "Attribute Points Change" section explains about attribute points no longer being assigned when you are past level 100. 

The death you suffered was because of this bug: https://github.com/HabitRPG/habitrpg/issues/4313  I'm sorry you were hit by it! The "Advice" section near the top of that page explains how you and your party members can recover from the unfair damage.

If you have any questions, you're welcome to ask them here, even though I'm closing this now. If you'd like to follow the progress of that bug fix, you can subscribe to notifications from that issue.
