### ISSUE TITLE
Refactor: Move code out of controllers into services

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5190]
Per Angular best practices, very little code should reside in controllers. Controllers are instead used to instantiate or trigger services (models) based on UI action, and all the meaty stuff lives in the services. HabitRPG doesn't follow this practice; all sorts of app logic lives in controllers for root, user, inventory, and so on. This has performance implications in that code is kept in memory beyond when needed, and results in maintainability struggles as coders move or copy needed functions across controllers.

Refactoring to align Habit's controllers and services with Angular best practices would be a major project, but of substantial benefit long-term.

(Based on a conversation with @lefnire. He may be able to add more detail and/or correct my understanding of the issue.)
##

**Comment by crookedneighbor** [comment]
I'm very :+1: on this.

**Comment by TheHollidayInn** [comment]
From Pro-Angularjs Chapter 18:

"Services are commonly used to implement cross-cutting concerns, which is a catchall term for any functionality that is affected by more than one component or affects more than one component. Typical examples are logging, security, and networking. They are not part of the model (unless your business is logging, security, or networking), they don’t belong to the controllers because they don’t respond to user interaction or perform operations on the model, and they are not part of the view or a directive because they don’t present the model to the user. In short, if you need to create functionality that doesn’t go elsewhere, then you create a service."

**Comment by Alys** [comment]
Is this still needed? Something to consider for the website rewrite?

**Comment by crookedneighbor** [comment]
The principle will be good, but the this implementation is specific to Angular.
