### ISSUE TITLE
Copy as To-Do looks a bit misplaced on system messages in chat

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5201]
Thank you for this great feature!

A small comment: the Copy as To-Do button looks a bit misplaced to me in case of chat system messages: ![Screenshot](http://oi62.tinypic.com/2ql98ut.jpg)

If you look at the first message in the party chat above there is a space between the +1 link and the Copy_as_To-Do icon. The space grows bigger if the +1 button is hidden - as seen in the following messages.

EDIT: The space is created by some `&nbsp;`'s that separate the buttons hidden for system messages with `ng-if`s. https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/chat-message.jade#L35

**Comment by joyheron** [comment]
I also noticed that it doesn't really make sense for system messages, but it is probably a pretty simple fix.

**Comment by SabreCat** [comment]
It might not hurt to have it; like, you could send yourself a "Start another Quest" To-Do from the quest complete notification. But it does look awkward as currently laid out.

**Comment by deilann** [comment]
I think what's going on here is that most users cannot see the flag (which
should be visible to everyone in my opinion... it's a great way to flag a
username if the person doesn't chat) or the trash can (which is only
visible to moderators) and there's some extra padding because the PM
notification was removed, but the padding around it wasn't.

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/pull/5593
