### ISSUE TITLE
Prevent cron from running immediately when changing custom cron time

### ISSUE THREAD

**Issue by Slyrk** [HabitRPG/habitica#5208]
Today I was hit by two crons because I changed the custom cron time, which is annoying because I don't keep track of my streaks, and I can't reward a perfect day buff to myself.

I realized later that there is a warning that changing cron time may immediately trigger a cron. It would be so easy to make it safe (even for people like me who don't read the details): when the text field receives focus, check the user into the inn, when the text field loses focus, check her/him out. 

My ID: 2c6e11fe-5a7c-4f68-9a38-f19c400fb7d3

**Comment by Alys** [comment]
I'm not sure a forced rest in the inn is the best solution because the player might be relying on a full cron running that day (e.g., for quest progress and extra mana), and a forced rest would disadvantage players who had completed all their Dailies. 

We're discussing options in https://github.com/HabitRPG/habitrpg/issues/4488 and I think the solution proposed there will work well. @Slyrk you're welcome to comment on that issue if you wish.
