### ISSUE TITLE
Not counting damage for party quests

### ISSUE THREAD

**Issue by trepatukas** [HabitRPG/habitica#5213]
Couple days ago my party was on a quest and after midnight in my time zone, there was no update on my damage done. I did all my dailies and 1 or 2 to-dos that day, but there was no change in the damage for the boss and there was no line in the party chat of me doing damage (nor even zero damage).

Today I've done four of my dailies already, but when I check the data display, it shows 0 for Quest progress.

I still get experience for doing my dailies though.

User ID: 06fc800a-5131-4b28-91a7-1de87c0cd852
Party ID:11a2456c-8b39-438c-82c7-1467e10564a6

**Comment by Alys** [comment]
Your party is on a collection quest: [The Moonstone Chain](http://habitrpg.wikia.com/wiki/The_Moonstone_Chain)

If you've done only four tasks today, it's not surprising that you haven't received a quest drop because they don't occur after every task. You can learn more about collection quests and how to increase your drops at [Quests: Collection Quests](http://habitrpg.wikia.com/wiki/Quests#Collection_Quests)

**Comment by Alys** [comment]
Ask here if you need any clarification about this!

**Comment by trepatukas** [comment]
The former quest was a boss though, Laundromancer. And for the boss fights every daily used to get at least 0.8 of damage. I did all my dailies that day (which usually sums up to some ~12 points of damage), but there wasn't even a line saying I did 0.0 damage or something like that (which is always the case for others).

**Comment by Alys** [comment]
Are you certain you were part of that quest? Did the quest finish before your damage could be applied? Were you resting in the inn that day (which means the damage would not be applied)? Did you notice any other problems related to cron, such as Dailies not becoming unticked?

Unfortunately, since that quest has finished, it's very hard to troubleshoot. If you notice any future boss quests that aren't taking damage from you, without a reason, please tell us then.

**Comment by trepatukas** [comment]
Yes. I attacked Laundromancer for 16.4 damage a day before that empty one. And the boss was finished a day after (I checked the party log/chat).
I was not resting at the inn. 
The dailies themselves counted normally, I received the usual experience for them when ticked off, and they disappeared normally (I set my dailies to "due").
