### ISSUE TITLE
Can not end subscription.

### ISSUE THREAD

**Issue by programablocity** [HabitRPG/habitica#5218]
I get the following error when I click cancel subscription.

`{"err":"Cannot read property 'current_period_end' of null"}`

**Comment by Alys** [comment]
I can fix that for you but I need to know your user ID. Please go to Help -> Report a Bug and see step 6 for how to find your ID

**Comment by wardenkh** [comment]
f5368fec-1da5-4cd6-bced-864a267d3d8b

**Comment by Alys** [comment]
@wardenkh   What happened was that your subscription was already cancelled in the past by the credit card processing company (Stripe) due to multiple failed payments, but our systems weren't notified of the cancellation.

I have set the cancellation flag in your account, so your subscription should terminate tomorrow. You will not be charged again for that subscription.

If you were cancelling so that you could choose a different subscription option, you will be able to do that now. If you merely wished to cancel permanently, you don't need to take any action now.

**Comment by programablocity** [comment]
I closed this too early.  I still can not cancel.

**Comment by deilann** [comment]
As Alys said:

" If you merely wished to cancel permanently, you don't need to take any
action now."

**Comment by Alys** [comment]
wardenkh's UUID has been deleted from this issue. In case it's important for future reference, here it is:
 f5368fec-1da5-4cd6-bced-864a267d3d8b

@wardenkh Your user ID does not need to be kept secret. It's no more dangerous than your name.
