### ISSUE TITLE
Share buttons captions not translated in the footer and above avatar pic

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5223]
1. As more and more features of HabitRPG get translated I believe that the like and share social buttons in the footer may be shown in accordance with native language features of the respective 3rd party services (if available) e.g. the look of fb like button for various locales [DailyMail pic](http://i.dailymail.co.uk/i/pix/2012/09/01/article-2196808-14CA0DCA000005DC-554_634x385.jpg) (though a bit outdated) and example of adjusting language from fb documentation: [developers.fb.com](https://developers.facebook.com/docs/plugins/like-button)
2. **However** I totally agree with the decision not to use addthis built-in feature of showing language-sfecific share button caption in accordance with locale of a user's browser - for the share button above avatar pic. For quite a few languages the equivalent for share will be a much longer word e.g.  ![Hindi Share](http://s7.addthis.com/static/btn/v2/sm-share-bn.gif) or ![Slovenian Share](http://s7.addthis.com/static/btn/v2/sm-share-sl.gif)
   At the same time the word "Share" on the button (in the second case) may seem as something that has been missed by translators accidentally. I would suggest using some sort of a classic share icon instead, e.g. ![Share Icon 1](http://www.alfredforum.com/public/style_images/master/icon_share.png) or ![Share Icon 2](http://apps.franklincountyohio.gov/assets/images/apple-share-icon.png) etc.
##

**Comment by khipkin** [comment]
Suggestion: add [translations] label.  Also, maybe [interface]?

**Comment by Alys** [comment]
I've added labels, including "status: issue: suggestion-discussion" because I'm not sure what we're doing with the share button. This might be best marked "status: issue: on hold".

I like @GitHubSphinx's idea off using an icon instead of a word, if we think enough users will recognise it (I'd expect all/nearly all mobile+website users to know what it means but maybe there's some website-only users who don't use mobile phones often and who aren't familiar with those icons).

Another problem with using addthis's built in language-specific feature is that the player might have chosen a different language for Habitica than their browser uses (e.g., those immersing themselves in a foreign language while in Habitica or those who prefer the Habitica English translation).

**Comment by librarianmage** [comment]
@Alys should this be put on hold to see if this is affected by the client update?

**Comment by Alys** [comment]
There's no longer share buttons on the avatars so I'm closing this.
