### ISSUE TITLE
Paid subscription twice, did not receive two months subscription

### ISSUE THREAD

**Issue by LadyAviy** [HabitRPG/habitica#5230]
So I paid for a subscription once but found it was somehow going to my mom's email address. I couldn't figure out how to change the address. When I went to the credit card options I saw the 'log out' option near the email but assumed, fairly I think, that clicking it would log me out of my account and thus wasn't going to solve my problem. I eventually canceled my subscription and then immediately restarted it, this time making sure it was using the right email address. 

However even though it said I had an active subscription still, it also immediately charged me another one. That's fine. I don't mind, but it should at least give me 2 months subscription and not charge me again until that runs out.

User ID: 3504ff1d-15e1-4308-a1d9-1eeade6f4c67

Browser: whatsmybrowser.org/b/BAQ2JRD

**Comment by Alys** [comment]
Because this is about your private financial details, we should deal with it by email instead of here in GitHub where it's public. 

Please email admin@habitrpg.com. Include the message you've written here. Please also include the user ID of your mother's account.

If the email address that you use with PayPal or Stripe is different than the one you will be using to send the email, please tell us what it is. We'll sort this out for in hopefully a day or two of receiving your email.
