### ISSUE TITLE
Pet Ears cannot be obtained for free after Death or Orb of Rebirth

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5236]
With all equipment (including the Ears), when you own them, they exist in `items.gear.owned` with a `true` value. When you lose them due to Death or Rebirth, they stay in `items.gear.owned` but have a `false` value. 

For all equipment except the Ears, the false value causes the item to show up in your Rewards column where you can buy it back with gold (zero gold for stats-free items). 

However for the Ears, they don't appear under Rewards when they have a `false` value, so you can't obtain them for free after you've used an Orb of Rebirth or if you lose them due to Death. The only way to get them back is to buy them with gems again from the Avatar page (or get an admin to give them back to you - recommended solution :wink: ).

Also, when you go to the Avatar page, it doesn't show you which Ears need to be bought again. All of the Ears that you have bought in the past have a white/transparent background instead of the grey background that's typical of unpurchased customisations. However if you bought the full set previously, the "Unlock Set" button does has a grey background.
## What To Do If You Experience this Bug

Go to https://habitrpg.com/#/options/settings/api and copy the "User ID" string of characters. Paste it into a comment here. Do not copy the API Token (it is a password). You do not need to tell us which ears you are missing - we can see from your account which ones you bought in the past and we'll give them all back to you for free.

```
For reference for admins: 
items.gear.owned.headAccessory_special_bearEars
items.gear.owned.headAccessory_special_cactusEars
items.gear.owned.headAccessory_special_foxEars
items.gear.owned.headAccessory_special_lionEars
items.gear.owned.headAccessory_special_pandaEars
items.gear.owned.headAccessory_special_pigEars
items.gear.owned.headAccessory_special_tigerEars
items.gear.owned.headAccessory_special_wolfEars
```

**Comment by habitrpguser** [comment]
The same happens when you die and lose some pet ears. (It just happened to me with bear ears.) I'd bought the whole set of pet ears, now I still have all except the bear ears, which can't be bought back for gold in the rewards column but, apparently, can be bought back for gems. (I didn't try yet but the page offers it.)

I won't give you my User ID and won't demand my ears back for anything less than the gems - I'll just buy them with gems. It's high time I feel more consequences from death (and, therefore, work harder to avoid it) anyway. But thanks for the offer!

**Comment by Alys** [comment]
@habitrpguser Too late, I've already given them back to you.

I've also edited the issue to state that you can lose them through Death. I assumed that you couldn't because they don't give stats and therefore I assumed they had zero gold cost (and hence can't be lost on Death), but they're apparently worth 20 GP.

@lemoness, are the pet Ears meant to have a gold cost?

**Comment by crookedneighbor** [comment]
I think @SabreCat was modeling it after the seasonal shop purchases, which cost 20 gold because that's the price of one gem if you're a subscriber. 

Would it have been better to model the ears after the flower accessory instead of headgear? Then they'd just be selectable on the avatar customization screen (but you'd also be able to wear headgear)

**Comment by lemoness** [comment]
So, our logic was that all the head accessories so far cost  20 gold, and
can be lost through death. That includes the ones you get in the seasonal
shop (although, of course, they cost 20 gold before they were moved there).

I'm concerned that @hairlessbear said that they "can't be bought back for
gold in the rewards column" - they should be there, costing 20 gold. Was
that not the case?

They're definitely a head accessory, not like the flowers, but we can make
them worth 0 GP if people think that makes sense, since they were never
gold-purchasable, unlike the gem-purchasable head accessories in the
Seasonal Shop.

**Comment by Alys** [comment]
@lemoness No, they can't be bought back from the Rewards column - see the top post.

20 GP makes sense since the other head accessories cost 20 GP.

However, if we made them 0 GP temporarily, until this bug is fixed, it would mean that people couldn't lose them on death, which means fewer bug reports and fewer database fixes. It's up to you whether we do that! The database fixes are easy enough. (And of course it can be done through the Hall as well, although less easily.)

**Comment by lemoness** [comment]
@sabrecat seems to think it's easy enough to fix the bug that is keeping
them from displaying in the Rewards store. If it proves to be trickier ,
then we can switch it to 0 gold cost for the interim.

**Comment by Alys** [comment]
@lemoness yes, I've just looked at the code and it's an easy fix. It's just changing the name of the item in the canOwn code.

**Comment by Alys** [comment]
reopening until the fix goes live

**Comment by SabreCat** [comment]
Ah yes, bit of a drawback to GitHub's automated issue linking, that...
