### ISSUE TITLE
Events are (sometimes?) carried out in the wrong order

### ISSUE THREAD

**Issue by 3onyc** [HabitRPG/habitica#5243]
For example:
1. Boss hits party for 135 damage
2. Die and lose XP + gold
3. Party defeats boss 6 hours later
4. Don't have XP / gold from quest

I'd expect to receive the quest rewards death occurred before the boss was defeated.

Am I correct in thinking that HabitRPG considers you dead until you login, and dismiss the "you died" dialog, thus anything happening after death and before login isn't applied?

Not all party members reported this issue which would make sense if the above is correct.

Edit: corrected, did receive items for quest

**Comment by DemosMirak** [comment]
I'm in the same party, and also have this issue

**Comment by deilann** [comment]
Actually, you don't die until you log in. You just have negative HP.

So here's what happens:
1. Boss hits the party for 135 damage
2. You have negative HP
3. Party defeats boss.
4. You receive your quest rewards
5. You log in
6. Due to having negative HP, you die and lose XP and GP

The fact that this happens is actually pretty useful because a healer can
heal your party back to positive HP as long as they do it before you log in
again.

**Comment by 3onyc** [comment]
Is there an option to wait for a healer's revive, or do you always die when accessing the app or website?

**Comment by deilann** [comment]
You always die. The best thing for a healer to do when they see a huge
amount of boss damage is to start healing up.

**Comment by 3onyc** [comment]
A "wait for revive" option would be nice though, choosing to take the full penalty if you want to revive immediately.

But that's probably cause for a new issue, or part of an existing issue.

**Comment by deilann** [comment]
Features are handled on Trello, not on Github. As such, I am closing this
now.

**Comment by 3onyc** [comment]
Okay, thanks!
