### ISSUE TITLE
optOutText (suggestion when opting out of class system) may need slightly other wording

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5244]
When opting out of class system at level 10 the optOutText says:

`"Can't be bothered with classes? Want to choose later? Opt out - you'll be a warrior and your points handled automatically. You can enable classes later under Settings."`

However it seems what really happens is:
- 10 points gained by the time class selecting dialog pops up are "temporarily" allocated to STR
- points gained from further leveling up are not assigned to a user who has opted out - they don't appear in the stats and reportedly don't make any effect
- if open the class selecting dialog again by hitting "enable class system" - all points (10 initial ones + the ones gained by the moment) do show up - "temporarily" allocated to STR

By "temporarily" I mean the points are available for manual allocation after choosing a class later.

Is it the intended behavior?

Another thing, I can't replicate the second issue now, but it seems after using the orb of rebirth and then opting out of class system at level 10 by level 12 I somehow got 12 points to STR and 2 points to PER. The latter may be connected with many PER tasks on my list and task-based autoallocation which I had used before the Orb of Rebirth (and I could assign attributes to tasks starting from level 1). The 2 strange points to PER disappeared when I opened the dialog of selecting a class again - and only 12 points to STR were left then. No additional points appeared at level 13. UID ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
## Summarizing the topic: 

Thanks to the explanation by Alys I'd only suggest changing the line to:

`Can't be bothered with classes? Want to choose later? Opt out - you'll be a warrior with no special abilities. You can read about the class system later on the [Wiki:Classes] and enable classes at any time under User -> Stats.`

Thus attribute points may be regarded as part of the "special abilities" system a user may read about on the wiki
## Edit by Alys:

The wiki link is http://habitrpg.wikia.com/wiki/Class_System
The link should be part of the translatable text so that translators can link to the associated page on the wiki for their own language.

**Comment by Alys** [comment]
@GitHubSphinx Thanks for the summary! I was finding it too hard to keep track of the conversation in the Wizards of the Wiki guild. :)

Let's ignore (at least for now) the issue in your final paragraph since it can't be replicated.

This part of the message definitely needs to be changed: "You can enable classes later under Settings."  It should now say "**You can enable classes later under User -> Stats.**" We should have changed that months ago. :persevere:

The initial 10 points would always be awarded because until you've reached level 10, the site doesn't know if you're going to opt out or not. Those are automatically handled (by assigning them to STR as you've found). 

Level-ups after opting out don't give points because (I assume) points are considered to be part of the class system. So "your points handled automatically" means basically that you no longer get points.

When you choose a class later (either after opting out or after being a different class for a while), it's not exactly true to say that you get back all the points that had been temporarily assigned. It's more accurate to say that all your points (assigned or not) are deleted and you get a new set of points that exactly matches your current level. In most cases, there is no difference between these two ways of thinking about it, but occasionally there is a difference and it does matter - for example, if you've been modifying your level up and down with Fix Character Values, you could have more assigned points than your current level would normally allow you to have. When you chose a new class, all of those assigned points are deleted, and you get a new set of points that does exactly match your current level. (Does all that make sense?)

So I think that everything you've described is intended behaviour.

"your points handled automatically" does seem to be slightly misleading since you don't get points after level 10 when you've opted out. If we're going to change that message, perhaps removing all mention of points would be best. If someone is opting out of the class system, it might be because they want a simpler experience, and they might not want to read something about points and wonder what it's talking about.

But what do you think now? Do you still think that part of the message would be better if it were changed?

**Comment by habitrpguser** [comment]
Would it make sense to, instead of not giving people who opt out any points, just use one of the default allocation mechanisms? Either evenly to all attributes, or warrior-class-based, probably? Otherwise, I'd expect some Habiticans to think _"What? I didn't want to be bothered at the time, didn't have time to read the small print, and just wanted HabitRPG to do as much as possible automatically and by default - and now I realize that I got much fewer points that way? I already gave up spells, and now I don't even get the points? And I could have gotten them (to STR at least) by repeatedly clicking "Opt out" after every leveling up, but how should I have known? UNFAIR!"_ (Note that most Habiticans are nicer than that and wouldn't think something so resentful about such a minor matter! :) ) - But if it's an easy bugfix, I'd vote for switching to some default allocation mechanism and leaving the messages the same.

**Comment by ghost** [comment]
@habitrpguser The only auto allocation method for those who opted out of class system might be flat auto allocation. And TBH I wouldn't suggest it for people who just have no time to learn about the class system. When they get time, and opt in they might be more dissatisfied with inability to manage their points. So current behavior seems more than just logical, it's stress-proof ))

@Alys Thank you very much! Now it perfectly makes sense!

I'd only suggest changing the line to:

`Can't be bothered with classes? Want to choose later? Opt out - you'll be a warrior with no special abilities. You can read about the class system later on the [Wiki:Classes] and enable classes at any time under User -> Stats.`

Thus attribute points may be regarded as part of the "special abilities" system a user may read about on the wiki

**Comment by habitrpguser** [comment]
@GitHubSphinx _"When they get time, and opt in they might be more dissatisfied with inability to manage their points."_ - Why would that be? Wouldn't they be able to reallocate them, just like they can now when they either opt in or change class? (At least that's how I meant it.)

**Comment by ghost** [comment]
@habitrpguser Oh, I must have misunderstood you. Please forgive me, as actually your point does make sense, if we consider what @Alys has said about the mechanics (particularly: _"all your points (assigned or not) are deleted and you get a new set of points that exactly matches your current level"_).

Moreover, I believe I know what you are talking about. My first thought why and when I started to look into the way points were distributed was actually: "why didn't it show me which one of the auto allocation modes was used for me after I opted out".

However I'd still suggest making a quick fix for the text line and let further discussion about the way points are distributed go on on Trello.

**Comment by Alys** [comment]
@lemoness This is issue is proposing that for the Class system, the opt out text be changed from this:

"Can't be bothered with classes? Want to choose later? Opt out - you'll be a warrior and your points handled automatically. You can enable classes later under Settings."

to this:

"Can't be bothered with classes? Want to choose later? Opt out - you'll be a warrior with no special abilities. You can read about the class system later on the [wiki](http://habitrpg.wikia.com/wiki/Class_System) and enable classes at any time under User -> Stats."

Is that okay? It's more accurate.

**Comment by lemoness** [comment]
Yes, that is more accurate, and I like that it links to the wiki.

**Comment by Alys** [comment]
I've added this to the first post:

Edit by Alys:
The wiki link is http://habitrpg.wikia.com/wiki/Class_System
The link should be part of the translatable text so that translators can link to the associated page on the wiki for their own language.

@GitHubSphinx Do you want to do this? If not, I'll advertise it in Aspiring Coders.

**Comment by ghost** [comment]
@Alys thank you very much! Please give me some minutes to apply changes and run it locally to make screenshots.

**Comment by ghost** [comment]
@Alys @lemoness Please excuse me, I've missed one thing out before when suggesting changes:

optOutText it's a popover text, and we can't have clickable links in the popovers.
The modal does provide a link to the wiki in the heading: `Choose your [Class!] Or opt out to choose later.`
Screenshot: http://snag.gy/oMROA.jpg
But it's not obvious that a user can also learn more about opting out there.

I believe the dialog may have a "Learn more" link to the wiki in the footer on the left.
What would you think about it?

**Comment by Alys** [comment]
Oh yeah..... I'd like to see a "Learn more about classes" link in the bottom of that dialog. Then the link could be removed from "Class" in the top of that dialog, which I think would look nicer.

**Comment by ghost** [comment]
@Alys  May I ask for some help with this one please? 

Here's what I get: before / after
 ![screenshot](http://oi62.tinypic.com/viemms.jpg)
and the things changed work as expected, however there are some questions I can't make decisions about on my own:
1. **[Proposed solution: opting for a single line and deleting old parts]** Heading has been comprised of three lines: `Choose your + a(Class!) + Or opt out to choose later.`
   May I change it to a single line `chooseClassHeading` or should I stay with the `chooseClass1 + chooseClass2 + chooseClass3` pattern to keep the parts of phrase already translated in place? In case of the former option what am I supposed to do with the unused lines in character.json - leave them in place for possible future/other uses?
2. **[Proposed solution: I didn't want to add new lines for translation, but there's no other solution I can think of]** Links to the wiki articles on particular classes are left as is for now, as they may need a slightly different approach. Is it OK?
3. Link "Learn more about classes" is introduced with `div.pull-left!=env.t('chooseClassLearn')` as I haven't found any other established practice for such things in the code. Do you maybe have some other advise?
4. Opting out button gets altered popover text as agreed: `Can't be bothered with classes? Want to choose later? Opt out - you'll be a warrior with no special abilities. You can read about the class system later on the wiki and enable classes at any time under User -> Stats.`
   - **[Proposed solution - normal size button for opting out]** **_New bug**_: popover text gets misplaced vertically and it doesn't seem connected with the Learn more link - I can't find what causes it =(
   - **[I'll have to leave it as is ATM]** Old bug: the button itself misbehaves a bit: on mouse_over it slides to the right by some pixels. This bug/feature is also present in online version currently. At the same time the Select button is OK.
     The code is in [classes.jade](https://github.com/HabitRPG/habitrpg/blob/master/website/views/shared/modals/classes.jade):
     `.modal-footer`
     `button.btn.btn-sm.btn-danger(ng-click='user.ops.disableClasses({}); $close()', popover-placement='top', popover-trigger='mouseenter', popover=env.t('optOutText'))=env.t('optOut')`
     `button.btn.btn-primary(ng-disabled='!selectedClass' ng-click='changeClass(selectedClass); $close()')=env.t('select')`
     I'm not a coder and I can't find the reason for this ATM. May I leave it as is and post a bug report instead?

**Comment by Alys** [comment]
Heh heh, you opened a can of worms. ;)
1. From what I've read about translations, I think one long string (chooseClassHeading) is best, yes? It gives the translators more flexibility, especially in cases of languages that have very different word orders than English, or languages where word forms depend strongly on context. You would know more about that than I, so I will defer to you, but my personal preference is for your chooseClassHeading idea, and then delete the three old strings (they aren't used elsewhere; I've just grepped through the code base).
2. Okay, although if you change your mind and think of a way that you'd prefer to handle them, do tell us.
3. I think it looks good in your screenshot and pull-left is used in a few other places, so I'm happy with it, but I'm not very strong on the layout side of the code. If you hear differing opinions from others, believe them not me.
4. New bug: Is it just because the text is longer now? If so, we were probably already getting that bug with some translations. Maybe the vertical "space" that the popover has to fit into isn't tall enough and so the popover has to move down a bit? That's just wild guesswork though and isn't at all helpful. The my disclaimer from point 3. :) There is a `wide-popover` style that's used in website/views/options/social/group.jade like this: `.popover.static-popover.fade.right.in.wide-popover`. Maybe adding `wide-popover` to the popover might make it expand sideways and look better? Or worse. Who knows. :)
5. Old bug: Huh. I've never noticed that before. I'm happy with you leaving it as it is.

**Comment by ghost** [comment]
@Alys thank you very much for your help! 

Solution for the links to wiki pages about a particular class is not very elegant - I didn't want to create new strings for translation, but I guess, it's the simplest one.

Unfortunately I wasn't able to turn popover wide.

I've created the pull request stating the old bug and the new layout bug - maybe someone could fix it or give some more hints on them.

**Edit**: walkaround for the new bug has been applied, please see the comments in the pull request above
