### ISSUE TITLE
CLOSED: DUPLICATE

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#525]
**CLOSED**

**Comment by Pandoro** [comment]
Actually my question is a bit unrelated, but... how do you send a password
to the server? Every time anyone sends my passwords as human or computer
"readable" text, I seriously feel like punching them in face :-/ It's fine
if you send me a random password I need after resetting it. I use it and
then change my password... But if you send my password as clear text I feel
like AAAARG.

But... I guess any halfway decent developer things about this right :D ?

**Comment by lefnire** [comment]
:/

**Comment by Pandoro** [comment]
Oooh I just realized this was the duplicate issue. 

@lefnire please don't let me down on this one xD 

If this is how it is handled currently, don't take my comment personally please! I really like you and wouldn't want to punch you. But from a safety point of view, I think this is a very critical issue :x I know you are sending the "reset passwords" by mail right now (if I am wrong please correct me!) and I think this is okay, as you make one up and I can use that for logging in. However many users, of which I might be one :p , have a set of passwords they like to reuse. Leaking these actual passwords is something which REALLY shouldn't happen. Back when I implemented an android app, I went for creating the md5 hash and storing this in the database. For one that means people can't just see my password it if they log my traffic and also people don't have to think I could steal their password and login to their other accounts. I know this isn't safe either, but you could use some other algorithm which is a little safer. This should be a small effort and it will add a huge amount of safety to the system. Because eventually this might seriously become an issue. I don't think it is desirable that we get HabitRPG into the news as the website that was used to crack people's google, bank and facebook accounts with :x

**Comment by lefnire** [comment]
we should take this convo to https://github.com/lefnire/derby-auth/issues instead, but passwords are stored SHA-encrypted with a salt. The encryption libraries don't work on the browser, so initial sends (login, register, change password) have to send them to the server in the clear (that's why we're on SSL) - but they're encrypted when on the server. If you think this should change, and can help out, please jump in.

**Comment by Pandoro** [comment]
Darn it x) I should have payed more attention in the IT-security lecture! But if I'm understanding it correctly, that means if I go to some public network where people could just log my whole traffic, based on the SSL they couldn't just read my password right? It's nice that is is encrypted on the server as well :) I would trust you not to do messy stuff with it, but of course people that don't know you can just rely on that as well.

What I was meaning, is that I wouldn't like to see something like http://hapitrpg.com/query_apitoken?username=pandoro&password=abc123 
(Or whatever the correct syntax is here)

I guess then that the current system sounds, rather secure to me? Of course it has it's flaws, but as long as you don't start reading out the passwords before you encrypt them in the database, it sounds like there aren't any trivial attacks against the system.

@lefnire I really didn't mean to offend you and after reading this, my comment doesn't really apply to habitrpg :) I guess even sending passwords by mail over SSL sounds okayish. Please don't be mad at me now ^^; 

You know I'm not a programming genius, so actually helping out will be hard for me, especially when it comes to javascript. But I guess my security "needs" are pretty much covered.

**Comment by lefnire** [comment]
i'll keep that in mind as we develop the api. If we implement 3-legged auth as per this ticket, the first pass (requestToken) would send the password. We'll make sure to not send password as a url param.

**Comment by lefnire** [comment]
Also, I'll check out browserify + crypto. Last time I tried (when first creating derby-auth), SHA + salt didn't work on the browser. I did some reading after that and found that most auth setups sent pass in the clear (req.body or req.param, _not_ req.query) and covered their tails with SSL. Seemed common and secure enough, so I used it. If I can get crypto on browser, it would actually make derby-auth much simpler since we can do access checks over Racer rather than ajax.

**Comment by lefnire** [comment]
Let's take this to https://github.com/lefnire/derby-auth/issues/28 - there are some developers using derby-auth and they'll have some say

**Comment by lefnire** [comment]
https://github.com/lefnire/derby-auth/issues/30

**Comment by Pandoro** [comment]
I'll reply here as it is a little out of context in the derby auth repo and not really relevant.

@ruddfawcett Just to clarify, I don't mind about the new random password being sent to me. My original question just originated since I wanted to make sure my actually set password does not leak out. After the explanation I pretty fine with how it now is. However if it simplifies things, then I wouldn't be against sending the stuff in an encrypted way. But I also think that there are different things which have a higher priority right now as well.
