### ISSUE TITLE
No in-app visual indication of user being invited to a party

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5265]
This was mentioned by a user in the tavern and I confirmed it on my local install. When a user is invited to join a party, they are sent an email, but there are no notifications in the app. The easiest fix for this would probably be to use same style of notifications that are used for new messages (i.e., a number to the left of the "social" menu that, when clicked on, takes you to the relevant page).
##

**Comment by Alys** [comment]
When you're invited to a party, this happens:

![screen shot 2015-05-24 at 5 06 12 am](https://cloud.githubusercontent.com/assets/1495809/7785420/a4c6dd1a-01d2-11e5-8844-1dc652bc0eb3.png)

Are you sure that didn't happen in your local install?

**Comment by hairlessbear** [comment]
Ah, I didn't see that. I was looking over in the social menu for an indication. Maybe I'm alone on this, but that location isn't at all obvious to me.

Also, is there any reason that we shouldn't have a pop-up for this?

**Comment by crookedneighbor** [comment]
I agree that it is not obvious.

**Comment by lemoness** [comment]
I would be fine with a pop-up! I know some people find them annoying, but
presumably you're not being invited to too many parties.

**Comment by crookedneighbor** [comment]
@lemoness Should the modal also popup for invitations to guilds? (I vote yes)

What should be included in the modal? 
- [ ] Group logo (if present)
- [ ] Group name
- [ ] Group description (if present)
- [ ] Person who invited you
- [ ] Big join button
- [ ] Small decline button

**Comment by lemoness** [comment]
All sounds good to me!

**Comment by Alys** [comment]
I'd like there to be a "decide later" button as well, in case the modal appears while you're in a hurry to action tasks.

**Comment by crookedneighbor** [comment]
Let's not implement this until after the redesign.

**Comment by Alys** [comment]
I'm closing this because in the new website, the red notification count is incremented when a party invitation is received, so in that way it's more obvious than it used to be (although if you have guild notifications pending you might not notice the party invitation for a while; the notification icon no longer changes to show you that a party invitation is there, but that's intentional in the new site). 

A modal showing details of the party would be more complex now that multiple party invitations are possible at once.
