### ISSUE TITLE
Bubble Arrow for Notifications and Audio Theme Button is Misaligned off to the left 

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitica#5280]
Hello! I noticed this yesterday and thought it might be good to point out. I'm combining these issues because it seems more appropriate considering how small the issue is. Sorry for issues before hand.

Like with my previous bubble arrow alignment issue post concerning the settings button, I noticed that both the notifications bubble arrow and the Audio Theme bubble arrow are positioned to the left of the center of the button. 
## Here are some images showing that:

![notificationsbubblearrowmisalignmentissue](https://cloud.githubusercontent.com/assets/7588148/7799055/1b34da2a-02c7-11e5-8822-dc2300c35293.png)
and 
![audiothemebubblearrowmisalignmentissue](https://cloud.githubusercontent.com/assets/7588148/7799070/455888d8-02c7-11e5-879e-b223191bab7e.png)

---

Again, super small issue. Just wanted to point it out.

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42e

**Comment by crookedneighbor** [comment]
All fixed in https://github.com/HabitRPG/habitrpg/commit/165dd3a4a610fe9be5ca4b3c8d76c39ac7b63d71 . Will be live on the site after the next deploy. (probably sometime this week or the next)

![screen shot 2015-05-25 at 10 49 46 am](https://cloud.githubusercontent.com/assets/2916945/7799454/e914d040-02cb-11e5-8fe6-422dd791a58d.png)
![screen shot 2015-05-25 at 10 49 52 am](https://cloud.githubusercontent.com/assets/2916945/7799455/e91804cc-02cb-11e5-8b6d-a60430a2f418.png)
![screen shot 2015-05-25 at 10 49 58 am](https://cloud.githubusercontent.com/assets/2916945/7799456/e9202c38-02cb-11e5-921d-a3616fcb6b13.png)

**Comment by Rbrinkley** [comment]
Oops. didn't notice that in the fix. Thank you for sharing that with me.
