### ISSUE TITLE
Cannot unsubscribe

### ISSUE THREAD

**Issue by pompouswhompus** [HabitRPG/habitica#5308]
Username: whompus
As much as I love HabitRPG, I'm afraid I can't afford to subscribe anymore (grad school eats everything.) When I try to unsubscribe, however, it gives me the following error:

{"err":"Cannot read property 'current_period_end' of null"}

OS: Windows 8.1
Firefox, Chrome

**Comment by Alys** [comment]
We understand about not being able to afford subscriptions any more. Thank you for the subscription payments you've given us in the past!

Unfortunately, we can't help you without being able to identify your HabitRPG account. Please go to Help -> Report a Bug and see the instructions there for telling us your User ID (step 6).

**Comment by pompouswhompus** [comment]
Woops, sorry. API is: b8a9a521-bdcf-4c11-b326-91b480900098

**Comment by Alys** [comment]
I've investigated and what happened was that your subscription was already cancelled by the credit card processing company (Stripe) due to multiple failed payments since 21 April, but our systems weren't notified of the cancellation.

I have set the cancellation flag in your account, so your subscription is terminated. You will not be charged again for that subscription.

Thanks for letting us know!
