### ISSUE TITLE
Cron reset happening later in the day.

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5331]
I was using the phone app and the web version on 2 different computers.
Since a few days my cron is messed up. It doesn't happen when it is supposed to be. My dailies keep being checked. Yesterday in the afternoon when I came home, I think a cron happened on my home computer, as if the cron time on my home computer is different to the one on my laptop. 
Custom day Start is set to "0", I'm not resting in the Inn.

**Comment by Alys** [comment]
Please check the time and timezone settings on **_all**_ PCs, laptops, phones, tablets, etc that you use HabitRPG on. They need to be identical. If they are not, you will get crons happening at "incorrect" times (HabitRPG itself thinks the crons are happening correctly because it is using the time and timezone set on your own devices).

**Comment by ghost** [comment]
You are right, my timezone was about 10 hours off on my home computer O.o
