### ISSUE TITLE
Rewards help displays 'Error processing string. Please report to http://github.com/HabitRPG/habitrpg.'

### ISSUE THREAD

**Issue by noisephoenix** [HabitRPG/habitica#5333]
On the Tasks page pressing the Help ? next to Rewards shows 'Error processing string. Please report to http://github.com/HabitRPG/habitrpg.' 

![rewards](https://cloud.githubusercontent.com/assets/4841199/7931293/5f67fa1a-0907-11e5-9f2f-03658e7a8713.PNG)

**Comment by ghost** [comment]
@noisephoenix Thank you for reporting it!

This issue is because the code doesn't specify the link to be used with this translatable string:
[lists.jade](https://github.com/HabitRPG/habitrpg/search?l=jade&q=rewardHelp4&utf8=%E2%9C%93) has `li!=env.t('rewardHelp4')` with no variables while [tasks.json](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/tasks.json) suggests a line with a link:
`"rewardHelp4": "Don't be afraid to set custom Rewards! Check out some samples <%= linkStart %>here<%= linkEnd %>."`

@SabreCat are you still working on all these tasks and rewards hints? I remember you've made links to wiki customizable.

**Comment by crookedneighbor** [comment]
I have just fixed it.
