### ISSUE TITLE
Trouble cancelling subscription

### ISSUE THREAD

**Issue by NinthWorlder** [HabitRPG/habitica#5338]
I need to cancel my subscription as I can't afford it any more, but on trying to cancel it I get the message:

{"err":"Cannot read property 'current_period_end' of null"}

My user ID is: b036008e-f7be-4b23-ac0a-9751bb2a749c

My browser is Firefox 38 on Windows 7

Thanks in advance for any help with this

**Comment by deilann** [comment]
ping @Alys 

This usually happens because Stripe canceled a payment. Alys will be able to fix it for you. :)

**Comment by Alys** [comment]
@NinthWorlder That error was happening because our credit card processing provider made four failed attempts to renew your subscription and then cancelled your subscription but without informing our server. I've applied the cancellation to your account. You won't be charged for that subscription again.

**Comment by NinthWorlder** [comment]
Thanks for your help with this :)
