### ISSUE TITLE
Feature: Breaking and Repair

### ISSUE THREAD

**Issue by hhirsch** [HabitRPG/habitica#5354]
Items should degrade over time, also loosing stats. The Items should be able to be repaired using Gold.

Finaly a use for Gold.

**Comment by Alys** [comment]
To request features, please go to the HabitRPG Help menu (on the website, not the mobile app) and select Request a Feature. That will take you to Trello where all feature requests are collated and analysed to choose the best way to improve the site. 

Gold can be used to buy equipment, including from the [Enchanted Armoire](http://habitrpg.wikia.com/wiki/Enchanted_Armoire) released today, and for custom [Rewards](http://habitrpg.wikia.com/wiki/Rewards) (see also [Sample Custom Rewards](http://habitrpg.wikia.com/wiki/Sample_Custom_Rewards)), and to buy [Gems](http://habitrpg.wikia.com/wiki/Gems) if you are a subscriber. There will also be gold-purchasable quests in future.

**Comment by hhirsch** [comment]
Ah you mean the feature that helped me burn 500 Gold in a minute and then was exhausted? Thanks for the help.

**Comment by Alys** [comment]
There's actually ten items in the Armoire and each use of it costs 100 GP. Also it has a random feature so that it sometimes gives you food for your pets or experience. If you've spent only 500 GP on it, it sounds like there's at least another five items you could obtain from it, maybe more. You can see all the available items on the [Enchanted Armoire](http://habitrpg.wikia.com/wiki/Enchanted_Armoire) wiki page.
