### ISSUE TITLE
Custom Day Start thinks Saturday is Friday

### ISSUE THREAD

**Issue by ViviaMir** [HabitRPG/habitica#5357]
All this week I've gone without noticing this... somehow. Thinking back on some of the confusion I've been facing, I now realize this has been a problem since I first set my CDS to 16:00... it isn't resetting tasks at 16:00, it's changing its chronological date over at 16:00. I don't wake up at 16:00, I go to BED at 16:00 so at no point during my day do I ever see the correct due dailies.

I can't help but feel rather discouraged by this... yes, I could work around it, but "friday is actually saturday" is certain to be both confusing and disruptive. I'm already beginning to second-guess the date for other things.

**Comment by Alys** [comment]
I'm pretty sure this is expected behaviour, although obviously it's not working well for you!

There was a similar question in the Newbies guild yesterday (Help -> Ask a Question) from someone who had a CDS of 23, and here's what I wrote there but with 23 changed to 16 to make it more relevant for you, although note my uncertainty so if other devs add different information, listen to them. :)

"Your custom day start (CDS) is 16:00, and I think the logic for that means that "Friday" actually ends at 4pm on Saturday. Here are some less brain-twisting examples to help illustrate this: 
If your CDS is 0 (the default, midnight), then "Friday" ends at midnight between Friday and Saturday.
If your CDS is 1 (1am), then "Friday" ends at 1am on Saturday. That's what people would use if they typically go to sleep after midnight each day. 
Following through with the same logic:
If your CDS is 16 (4pm), then "Friday" ends at 4pm on Saturday. Your CDS of 16 tells HabitRPG that before 4pm, you want HabitRPG to consider that you are still on the previous day.
At least I think that is how it works at high values of the CDS. I am certain that's how it works at low values (e.g., I know that 1 works as I've described here, and so does 5). I am pretty sure that it will work the same for 16."

@ELRinley What time do you typically wake up? If it's after midnight, you could use a CDS of 0. If it's a little before midnight, you could do the same but not be able to use your Dailies until after midnight, which I realise is far from ideal. :(

We should probably consider improving CDS to be more helpful in cases like this.

**Comment by ViviaMir** [comment]
I generally rise at 00:00 to 03:00 depending on when I actually do get to bed, but most often a few minutes before the day or somewhere within the first hour.

Unfortunately the only acceptable solution for me at this time is to change the days of non-challenge tasks. I'm not all that good at completing all my tasks in time for bed, and I'm far worse at actually giving up on them. My stubborn streak is so bad I actually have to have HabitRPG hardcore brickwall me or I'll be up for hours more, or until I'm tired enough to finally give up.

I think the easiest thing to do code-wise would be to allow negative numbers, effectively mimicking the timezone system.

But perhaps most intuitive and powerful method would be to provide a starting line and finish line, allowing users to designate what time that chronological date's tasks are given out, and what time they end.

And if the day begins at 06:00 and ends at 07:00... well, you have an hour to work with. If it ends at 05:00 then it ends the next day and you have an hour of "dead space." Following this line of thinking I would also incorporate a "time to completion" feature that informs users of how much time they are giving themselves to complete tasks and to sleep.

**Comment by deilann** [comment]
I have a ticket about this somewhere. Lemme scrounge it up.

**Comment by deilann** [comment]
Here we go: https://github.com/HabitRPG/habitrpg/issues/5167
