### ISSUE TITLE
My dailies have disssapeared 

### ISSUE THREAD

**Issue by lukebarclay** [HabitRPG/habitica#5375]
My dailies have disssapeared along with all my tasks, have refreshed but no use

**Comment by crookedneighbor** [comment]
@lukebarclay So sorry to hear that! Fear not though, we have database backups. 

As a first step, please try clicking on the clear tags button above your tasks, even if you are absolutely sure you do not have a tag activated.

If that doesn't work, about how many hours or days ago did they disappear? It's important to give a time in number of hours/days instead of a a specific time, because we have many admins in many different timezones.

Also, would you tell us your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.   

This will let us find your tasks in the database backups, if necessary.

**Comment by lukebarclay** [comment]
Thanks so much it totally worked!!!! you are the awesomest!!!

**Comment by crookedneighbor** [comment]
Happy to be of service.
