### ISSUE TITLE
Enchanted Armoire drops equipment but no gear or the wrong gear appears in Inventory

### ISSUE THREAD

**Issue by X3SED** [HabitRPG/habitica#5376]
So I've never had this problem before... It started yesterday with the new Enchanted Armoire : 

When I check a task or I pay for the Enchanted Armoire (100g), sometimes I have some drops that counts, it says that I've earned them but when I want to feed my pets I don't find it anymore (It doesn't occure all the time but let's say there is  20% chance this happens...).

I think it's a bug so here is my report and PS: I did resync, refresh, hard refresh, etc...

---

_edit by admin:_
##

**Comment by deilann** [comment]
Are you making sure to wait for the blue bar to completely finish before
clicking anything else?

**Comment by X3SED** [comment]
Yes! It happened 3 times since yesterday

**Comment by quettandil** [comment]
Happened to me today, too. Only with the Enchanted Armoire, nothing else so far that I've noticed. I'd had one successful use of the Enchanted Armoire, then today I spent the 100G, it said I earned Gladiator Armor, but when I went to the equipment tab (after the blue bar finished), there was no Gladiator Armor to be seen. I've synced, refreshed, logged out and in, and still nothing.

However, the Armoire drop count now says I have 9 equipment pieces remaining, not 8, so I guess I'll just give myself back the gold and try again.

**Comment by crookedneighbor** [comment]
Any ideas Sabe?

**Comment by Alys** [comment]
I'm renaming this from "Drop counts but no item found" to "Enchanted Armoire drops equipment but the gear does not appear in Inventory"

**Comment by SabreCat** [comment]
My best guess is this is a new flavor of #3048. My hypothesis:
- On the client, the user has a certain pile of stats that will be used for a `predictableRandom` seed.
- The server has a different pile of stats. This could be due to a sync error, a party member having cast a stat-altering spell, a party member's `cron` triggering boss damage, etc.
- The user purchases an Armoire hit. The client pours its stat porridge into `predictableRandom` and says, "Hey! Equipment!". Meanwhile the server consults its own slurry and says, "You got some XP!" or whatever.
- Later, a sync occurs, and the client gets itself up to date. Server data always wins, so the equipment goes away.

This will only grow more obnoxious as time goes on, but I'm not sure what best to do about it. Force the client data to "win" when randomness is involved? (Seems risky/exploitable.) Always force a sync before obtaining the `predictableRandom` seed?

**Comment by Alys** [comment]
Reported in the Tavern by Claine (f6fd0781-0c16-4648-a583-f506ad227638):  "**I just opened the Enchanted Armoire and got a message saying I got a Rancher Hat, but in my inventory it appears I received a red hairbow.**" I have confirmed that they do have the hairbow, not the hat.

**Comment by Alys** [comment]
This is irrelevant for the case where there's a mixup between food/XP/equipment, but it might be relevant for the case where equipment is given but the wrong piece is reported (Claine's report above):

We used to have a similar problem with Death where the notification would specify a different gear piece than was removed by the server. I fixed it by sorting the array of equipment before an item was chosen: https://github.com/HabitRPG/habitrpg-shared/pull/295/files (scroll to the bottom; almost all of that page is habitrpg-shared.js spam). The reason was that the array items were in a different order on the client and the server. I'm not sure I ever worked out why. "JavaScript is weird and annoying" was probably my best guess.

If it's a similar problem for the Armoire, then we could prevent the error Claine reported by sorting eligibleEquipment just before `drop = user.fns.randomVal(eligibleEquipment)`. I'll do that tomorrow if no one gets to it before then or poopoos the idea. :)
_EDIT: Done here: https://github.com/HabitRPG/habitrpg/commit/6eac1174a2c2fb73808b8f5f8388e3c73b763520 (significantly later than "tomorrow")_

It will not help if the client and server are getting different stats when a random number is chosen, but I don't think that could happen too often. If it did, we'd have a lot more reports of drops being incorrect.

**Comment by Alys** [comment]
However about the stats and the mixup between food/XP/equipment.... 

We select the type of Armoire result (XP vs food vs gear) using a random number seeded by the user's gold:
`armoireResult = user.fns.predictableRandom(user.stats.gp)`
I chose gold for that because if the user uses the Armoire two or more times in a row, then GP is the only stat that we are certain will have changed. 

This should give identical results on the client and server if gold deduction and the call to predictableRandom have exactly the same timing on client and server (e.g., if 100 GP is always deducted before GP is used as a seed). However if it's deducted on the client **before** the seed is used, but is deducted on the server **after** the seed is used (or vice versa), then we'll get varying results for the type of Armoire result. But I have no idea if that variation is possible. This is just speculation really.

If it turns out that that is what's going on, we'll probably have to chose a different stat (XP I suppose) and just put up with the user getting the same type of result if they use the Armoire two or more times in a row. :(  That's far from ideal but it's better than giving an incorrect message about what the user received.

Or we could find some way of creating a seed that is truly random but identical on the client and server. Maybe each time predictableRandom runs on the server (not client), its final action is to choose a truly random number and save it to the user's object. The next time it runs, it uses that value as the seed on both client and server (and then on the server it chooses and saves the next seed). If that's possible and if it would work...
It would not work well if predictableRandom is used multiple times between saving the user object (which I think it is for the Armoire actually). Maybe it could save an array of seeds and the Armoire code could use a different index for each call to predictableRandom, and then on the final call it passes in a flag that causes the array to be regenerated... `shrug` :)

Did I mention this is rampant speculation? :)

**Comment by joedragons** [comment]
66902097-c79b-496f-acd9-b78cc5867b28 confirming I paid for Enchanted Armoire, it reported giving me a Rancher's Hat and I received instead Basic Crossbow.  I am using Windows 7 w/ FF38.0.5 and there are no messages in my JS console (tho sadly, I clicked around a bit before opening it thinking maybe I needed to refresh/resync...so maybe data lost there).

Thanks for the message about the switch, I probably would have missed that if you had not posted it, it makes this less sore and more confusing=)  I am content with the item I received, just wanted to possibly provide more info.

I am not sure if this is related but I also received 5 hp around the same time (my party member healed the group using Blessing).  They said it was earlier in the day, making me think I was not totally in sync when I purchased.

**Comment by Alys** [comment]
The eligibleEquipment.sort() idea that I mentioned [above](https://github.com/HabitRPG/habitrpg/issues/5376#issuecomment-111799217) has been done: https://github.com/HabitRPG/habitrpg/commit/6eac1174a2c2fb73808b8f5f8388e3c73b763520
I have no idea if it will make any difference, but it can't do any damage. I haven't been able to replicate this bug locally or with test accounts in production.

**Comment by SabreCat** [comment]
Been poking at this today. I was able to reproduce the issue in a way that supports my hypothesis:
1. Sync user who has access to the Armoire.
2. In the db, `$set` their Gold to a different value than they currently have.
3. Buy from the Armoire. You'll see one result. (During my test, it came up Horned Iron Armor.)
4. Sync the user again. The result rolls back to something else. (During my test, the Armor disappeared and I gained 17 XP.)

I'm gonna play with the idea of a random values array saved to the user object, per @Alys's suggestion above.

**Comment by SabreCat** [comment]
I did take a stab, but haven't gotten it to work yet. If somebody who's a little more adept at client/server mojo wants to give it a run, I'd love to watch and learn.

**Comment by SabreCat** [comment]
A suggestion from @crookedneighbor:

> One way would be to choose the item on the client and send that item onto the server
> Rather than calculating it both places

**Comment by crookedneighbor** [comment]
I'm recanting that idea. I don't think it'll actually work very well.

**Comment by SabreCat** [comment]
OK. I have an idea for a short-term fix: include a `User.sync()` w/timeout on click of the Armoire. It'll cause a momentary delay for the user, but all the better for suspense? :P

**Comment by crookedneighbor** [comment]
I think that'll just cause communication problems between the site and the server, like clicking a spell too many times in quick succession.

**Comment by Gumnos** [comment]
Just adding to this, last night I received a Basic Crossbow from the Armoire.  Went ahead and equipped it to get the +5 PER bonus.  Coming back to Equipment a short bit later, it was still there. Refreshed this morning and it had been replaced with an unequipped Soothing Lunar Sceptre (with no PER bonus ☹ ).

**Comment by Gumnos** [comment]
Following up: Received a second Basic Crossbow in the Armoire today. Equipped (Soothing Lunar Sceptre is equipped in favor of my hook-sword) and still around for now. But will monitor what happens to it tomorrow.

**Comment by Gumnos** [comment]
Another follow-up: upon refreshing this morning, my equipped Crossbow vanished (still have the Soothing Lunar Scepter which was unequipped), and had been replaced with the unequipped Lasso

**Comment by k2moss** [comment]
Just commenting to add to this. Both me and (especially) the other member of my party (709c0cd4-3fca-4b22-bd6f-933a19022cab) have had problems with the Armoire.

For me: The Armoire frequently triggers an alert for an item, but a different item or no item at all appears in my inventory (ex: Armoire says it dropped a rancher hat, but I have a crossbow).

For 709c0cd4-3fca-4b22-bd6f-933a19022cab: Gear randomly disappears upon refresh. So far this has happened with Golden Laurels and the Red Crook.

Problems seem more frequent with my partymate, so maybe you could scrub some data off of that account.

**Comment by jamesrmtwigg** [comment]
(UID c3c70916-b523-4f01-b20d-ab41a82103e4) I have noticed this problem with the armoire as well. Today it told me that I received a Mythmaker Sword, but looking in my inventory I had instead received a replacement for my previously broken Royal Crown. The number of available items for the armoire was still reduced by 1.

**Comment by Alys** [comment]
(Disclaimer: It's 1 am and I should have been asleep five hours ago. I take no responsibility for my ideas being stupid.)

The Armoire doesn't need to give equipment randomly, it just needs to seem random to the casual onlooker. If someone digs into the code and discovers a fixed pattern to the Armoire results, there's no harm done. So we could sort the Armoire contents randomly but with a known seed that **never** varies for each user (e.g., the seed could be all the digits from the UUID). Once the contents were sorted, we would give out the first item that the user didn't yet have. [deterministic shuffle](http://stackoverflow.com/questions/5371452/javascript-sort-array-according-to-an-input-number-should-appear-randomly-sort)

Sorting would then be guaranteed identical on client and server. This would, I think, solve the problem of appearing to get one piece of equipment but really getting a different one.

It wouldn't solve the problem of the Armoire appearing to give gear/food/XP but actually giving a different type of thing. However we could probably do something to work around that too. I'll think about it after nap time, if I haven't then realised that the whole concept is unworkable. :)

**Comment by Alys** [comment]
Food and XP could be added to the user's Armoire contents just before sorting, in appropriate amounts for the number of Armoire gear items remaining. That would (I think) solve the gear/food/XP inconsistencies too.

**Comment by Gumnos** [comment]
Strangely it seems to hate my crossbow.  I've had the Lunar Scepter, Lasso, and Blue Hairbow now for about a week or so and none of them have vanished on me.  I just got my 3rd Crossbow and will see if this one sticks around. It's currently unequipped.

**Comment by Gumnos** [comment]
Yep, lost my 3rd crossbow and had it replaced with a Mythmaker Sword this time, less than 10hr lapsed.  Based on this pattern, the next time it will be replaced with an Iron Crook which isn't exactly a _bad_ thing…

**Comment by Alys** [comment]
Interestingly, the crossbow is the first item in the Armoire array. I can't at the moment think why that would matter, so it's probably just coincidence, but I'm mentioning it in case it turns out to be relevant.

**Comment by Gumnos** [comment]
@Alys: That occurred to me as well. I noticed that, when it was swapped out, it was replaced with the next item in the array (as listed on the Wikia Habitica page for the Armoire) that I didn't already have:  Crossbow→Lunar Scepter, Crossbow→Lasso, Crossbow→Mythmaker, and thus my suspicion that the next time I get a Crossbow, it will be replaced with an Iron Crook.

**Comment by Alys** [comment]
@Gumnos Oh I didn't notice that progression. That's a bit weird. What's your User ID (from Settings -> API)? I'd like to look at your equipment list, if I may.

**Comment by Gumnos** [comment]
@Alys `{43e2413a-f440-43c8-b96c-85b93024488c}` if it will help.  The Blue Bow came from the Armoire and was never touched FWIW.

**Comment by Alys** [comment]
@Gumnos Thanks. I can't see anything wrong there (and can't imagine what could be wrong). When you use the Armoire, is it always when you have a specific amount of gold (e.g., when you balance hits exactly 100 GP, or any other amount)?

**Comment by Gumnos** [comment]
@Alys: it's rare that I hit 100GP exactly, but it's pretty soon after crossing that threshold that I drop cash on the armoire. I can look more closely the next time I cross that threshold, but I know the most recent was over 100GP (in the 102-105GP range)

**Comment by UnexpectedMushroom** [comment]
If it helps at all, I had the same progression as Gumnos with the September items. The yellow hairband was replaced with each of the other equips in the order they are listed in on the wiki.

**Comment by Gumnos** [comment]
Yet more data points, received the Rancher Hat yesterday (2015-09-18), or the day before, then woke the next morning to find that it had been replaced by the Iron Crook. A pretty good trade, IMHO, but still an odd bug.

**Comment by X3SED** [comment]
OK.. Just got all this month's équipement but after a relog, i didnt find
anything and the spent money didnt come back :(

**Comment by crookedneighbor** [comment]
@X3SED If you believe that was unfair, you can use the fix character values button on the settings page to grant yourself the gold back.

**Comment by fpepin** [comment]
I don't know if this is relevant, but I got the december items on iOS and they're not showing up anywhere and I got a notice that the armoire is empty.

Could someone check if I'm indeed in an inconsistent state and if we think this is related to this bug?

user id: 59227709-88a9-4722-afc1-1ed4d45dd686

**Comment by Alys** [comment]
@fpepin Everything looks fine. You have the items.  Have you reloaded the website?

**Comment by fpepin** [comment]
I had done a sync but not a reload. Reload did fix the problem.

Thanks for checking it out.

**Comment by crookedneighbor** [comment]
Personally, I think we should just change the armoire code to not guess what the user received, just report back what the server says.

**Comment by SabreCat** [comment]
@crookedneighbor: That sounds like a great route to pursue for a fix. I wonder if that might be a worthy refactor/fix for some other things too, like the clumsiness of watching `user._tmp.crit` for critical hit notifications.

**Comment by melarish** [comment]
Is there currently server code for an Armoire purchase? I found this comment:
"If a function is inside user.ops, it has magical properties. If you call it on the client it updates the user object in the browser and when it's done it automatically POSTs to the server, calling src/controllers/user.js#OP_NAME (the exact same name of the op function)."
suggesting there should be another buy function in user.js to handle server actions. However, I looked in /website/src/controllers/api-v2/user.js (is this the one?) and there wasn't one. Am I looking in the wrong place?

**Comment by Alys** [comment]
@melarish If you search through the code base for "armoire" (case-insensitive, without the quotes), you'll find all the code for it. From memory, the main buy code is in the same file as that comment.

**Comment by melarish** [comment]
Yep, I found the buy code in user.ops but it's only for the client-side, isn't it? I can't find the code where it actually runs on the server, to be able to send back the result from the server. If that's even possible.

**Comment by crookedneighbor** [comment]
I believe that code is run on the client _and_ the server

**Comment by melarish** [comment]
Is there any interaction between the run on the server and the run on the client side? Since the suggestion was to get the result from the server. Or what's the other options? Is there a command that attempts a sync with the server? So that if it can't sync, it could give an error message instead.

**Comment by Alys** [comment]
The idea with this code (and much other) is that the code rus independently
on the client and the server but produces exactly the same result on both
because the client and server (supposedly) start with the same data. This
works when the initial data is the same on both (i.e., when syncing has
occurred since the previous action). It fails when the client has a
different idea of the user's stats than the server, which can happen if the
user is clicking quickly, or for other reasons.
