### ISSUE TITLE
Introducing financial punishment (optional)

### ISSUE THREAD

**Issue by orschiro** [HabitRPG/habitica#5404]
Dear all, 

A quick thought that I had:

What would the effect on behaviour be if users were to automatically donate a small amount to the project each time that they don't fulfil a daily, don't work on their todos, or perform a negative habit?

Have you ever considered this option? Some people might need a further financial incentive to change. 

Warmly,

Robert

**Comment by hairlessbear** [comment]
@orschiro While it's great that you'd like to see new features added to HabitRPG, GitHub isn't really the place to request them. New features are requested [on Trello](https://trello.com/c/odmhIqyW/440-read-first-how-to-request-a-feature-table-of-contents) (you can also get to the Feature Request page by clicking Help -> Request a Feature). GitHub is used for bug reporting.

**Comment by crookedneighbor** [comment]
@orschiro That's an interesting idea, but right now we're not going to implement a feature like that. I'd suggest checking out the [HabitRPG integration with Beeminder](http://habitrpg.wikia.com/wiki/Beeminder). Should fit your needs quite well!

**Comment by orschiro** [comment]
@crookedneighbor 

Thanks for recommending Beeminder. I will have a look at it!

Robert

**Comment by Alys** [comment]
@orschiro In case you'd like more information, I've used Beeminder for a few years now and have found it very useful. The staff are friendly and helpful, and they are very good about refunding your money if your Beeminder goal fails due to no fault of your own. They're reliable and trustworthy.

There's a [Beeminder-HabitRPG integration](http://habitrpg.wikia.com/wiki/Beeminder) (e.g., to make sure you do an appropriate amount of To-Dos each day) and a HabitRPG [Beeminder guild](https://habitrpg.com/#/options/groups/guilds/dca65ca5-2bae-442d-a564-d1a1fb6a00b4).

**Comment by orschiro** [comment]
@Alys 

I appreciate your shared experiences although I haven't looked at Beeminder into more detail.

Thanks!

Robert
