### ISSUE TITLE
Refresh Issue with Alert

### ISSUE THREAD

**Issue by Evilferret** [HabitRPG/habitica#5417]
Clicking the refresh button in Chrome is giving me interesting results today:

![everything is everywhere](https://cloud.githubusercontent.com/assets/3458235/8197629/7d22d784-1468-11e5-8767-4b927aa3f783.png)

![refresh2](https://cloud.githubusercontent.com/assets/3458235/8197637/9f489830-1468-11e5-85b4-d8419140ffd1.png)

When I logged in today there was no alert.  I refreshed at some point and the page broke (First image).  It then continued to break on subsequent refreshes (Second image)

After several refreshes, I finally got the page to load and I had a new alert.  Haven't experienced any issues since dismissing the alert.  The issue may relate to having an open session when an alert is created?  I'm using Chrome (43.0.2357.124 m)

**Comment by crookedneighbor** [comment]
I too had this momentarily on my computer. Not sure what happened, but seems to be resolved now so I'm going to close this. Feel free to re-open if it returns.

**Comment by deilann** [comment]
This often happens when the site is refreshed whilst someone refreshes
immediately during an update.

Solution is generally a hard refresh.

On Tue, Jun 16, 2015 at 5:58 PM, Blade Barringer notifications@github.com
wrote:

> I too had this momentarily on my computer. Not sure what happened, but
> seems to be resolved now so I'm going to close this. Feel free to re-open
> if it returns.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5417#issuecomment-112616416.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature
