### ISSUE TITLE
Quest pets and mounts of the same "type" might have had different names - for the sake of better translations

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5419]
Currently only some of generation-1 pets and mounts and only one of generation-2 ones have different names for pets and mounts. E.g. Lion Cub - Lion; Egg Egg and Egg Basket.

The chosen ones seem to follow the pattern for English.
However for the sake of tailoring translations other pets and mounts might have their own names too.

E.g. in Russian we have quite different images of a lamb - sheep - ram; and I can't come up with a word to match the pictures of both a pet and a mount.
If we could use another name for a cub (lamb) it would be much-much better!

> The post was shortened to exclude irrelevant info
##

**Comment by librarianmage** [comment]
@Alys I could do this, if we want to.

**Comment by Alys** [comment]
@paglias @crookedneighbor Pinging you because of API v3. Do this after API v3 is released or now or both or neither?

**Comment by paglias** [comment]
This can be done!

**Comment by padm0** [comment]
Hello! Is this issue looking for:
1) continuity across the English names of the image files to translate to other languages better? 
or 
2) for better translations of existing files in other languages?

**Comment by lynxlynxlynx** [comment]
From what I read of it, it's more about 2 through improving the originals. Having two identical strings to translate is confusing in itself, let alone spurring the imagination. You have to look at the json key to differentiate and if you translate them literally, like suggested in the first post, you can get non-matching combinations of names and images.

**Comment by ghost** [comment]
I'm sorry confusion! Originally the goal was to bring the attention of the devs so that in the future we could have separate names for quest pets and mounts. Even if the names are the same in English, having 2 identical stings will help translators to get better translations. Imagine that for some languages it doesn't feel natural to call a small cow a cow - you can only use equivalent for calf.

And it's not very confusing for experienced translators to translate identical strings - in this case the keys for pets are mostly like `questEgg***Text ` while the strings for mounts are `quest***MountText`. I see that all the recently added new quests follow this practice and have separate names for pets and mounts. Thank you very much to all the developers! 

It seems like most of the pets and mount names have already been split up. I'll double-check a bit later...

**Comment by zerom1** [comment]
I might add something absolutely useless, as I'm no developer... but on https://github.com/HabitRPG/habitica/blob/develop/website/common/script/content/eggs.js it seems to me that only animals like "Unicorn" and "Egg" are having the "mountText" addendum.

Does it mean that other languages which would want to translate "Falcon" in two different words (for the pet and the mount) would be able to do so on Transifex, but would not see any change on the website ? Ain't it missing ?

I also don't understand why "Egg" does not have a "canBuy" line. Again, it might just be because of the way we can obtain it... if so I'm sorry.

**Comment by SabreCat** [comment]
@zerom1: Correct. At the moment, the `mountText` for most mounts defaults to the same text as the pet. https://github.com/HabitRPG/habitica/blob/develop/website/common/script/content/eggs.js#L16 That could still be fixed, per this issue!

Plain eggs lacking `canBuy`, I believe is meant to restrict availability of those pets to the Egg Hunt quest (and by extension the Spring Fling event). But if you'd like to raise that question in the Report a Bug Guild, we can double-check!

**Comment by zerom1** [comment]
@SabreCat I checked the wiki and you're right, that's the explanation for the Egg egg.

As for the defaults, the fix seems pretty easy to me. In Transifex, in French, I can see that all animals have a translatable mount name. For example, questEggRoosterMountText exists there. That's because it's in content.js. The Rooster lacks the mountText: t('questEggRoosterMountText'),' line in eggs.s. Is it as easy as adding these lines wherever it's missing there ?

**Comment by SabreCat** [comment]
@zerom1: If the strings exist already, then yes, overriding the default is all that need be done!

**Comment by MagnusFundal** [comment]
From the looks of it, the egg name is generated automatically by appending "egg" on the pet's name.
Can we change this in translations at all? It looks horribly wrong in Danish. 
About as wrong as "Fresh Lied Eggs" when you mean "freshly-laid eggs".

**Comment by Alys** [comment]
To add some more details for @MagnusFundal's report, below is the conversation from the Aspiring Linguists of Habitica guild. The workaround given is only partially useful since you can't predict in advance whether the pet's name will end in a consonant.

_Hagtar wrote:_
Does anyone know how egg, pet and mount naming works?
I have this horrible suspicion that eggs are named as [Pet type] [Egg], i.e. two different tags put together. That makes it impossible to translate the egg names properly to Danish.
Of course "Wolf Egg" is absurd as it is, but in Danish, double words are always put together as one word without capitalization, with an extra "-e-" if the first one ends in a consonant. So the proper translation is "Ulveæg", never ever "Ulv Æg"!

_Oto Ravenstaff wrote:_
Correct, it's horrible for many languages.

_MegaDerf wrote:_
@Hagtar You are looking for string #799:
<%= eggType %> Egg.
In your case, you can translate it as <%= eggType %>eÆg.
In italian we have translated is as Uovo di <%= eggType %>, so you can adapt the string to better suit the needs of your language.

**Comment by Alys** [comment]
The fix in my PR referenced above has gone live now, which means that any of the pets can have different names than the mounts they grow in to. I think this fixes the issue originally described in this issue, so I'll close this in a few days if there's no objection. Please do comment here though if there's still a problem!

This won't help with the two comments immediately before this one, which describe the problem of appending "egg" to a pet's name. I'm not sure there's anything we could do about that, but if anyone has any ideas, please tell us. :(
