### ISSUE TITLE
Dailies stay blue when clicked

### ISSUE THREAD

**Issue by cyranojones** [HabitRPG/habitica#5434]
3e7620d9-5a46-4a40-b8a5-e33164287c0b

This morning when I went to click on my dailies, the first three turned grey but the other three stayed blue. When reclicked, XP money and MP were deducted and then re-added on a third click. Regardless, they stayed blue and had no checkmark in the field.

Windows7, Chrome

**Comment by hairlessbear** [comment]
Could you provide a screenshot of the behavior?

**Comment by cyranojones** [comment]
Cannot reproduce it today, which is a good thing I suppose. If I see it again, I'll make sure to do so. 

```
 On Saturday, June 20, 2015 4:30 PM, hairlessbear <notifications@github.com> wrote:
```

 Could you provide a screenshot of the behavior?—

**Comment by cyranojones** [comment]
![capture](https://cloud.githubusercontent.com/assets/12978474/8465945/dd0bca7a-201b-11e5-9180-06f9740a0eda.JPG)
I'm not certain if this attached the file or not, but I do have a screenshot of... of one of my dailies not staying clicked.

**Comment by hairlessbear** [comment]
Hmm...the problem is that the screenshot just looks like the dailies haven't been clicked. As in, there isn't anything in the screenshot that indicates that something has gone wrong. 

I realize now that I misunderstood your original post when I asked for a screenshot. I thought you were saying that the dailies stayed blue, but with a checkmark (which is why I wanted a screenshot). My apologies for the confusion. I'm not sure how to observe the behavior you're describing.

Does your posting of the screenshot mean that the behavior is happening again?

**Comment by cyranojones** [comment]
Unfortunately. Today is the first time since then, though, and as long as I can remember I clicked it, then it's fine. It gives me the credit for completing the daily, but if I click it again it debits me.

**Comment by cyranojones** [comment]
Oh! And as of now those last three are grey. Do you want another screenshot?

**Comment by crookedneighbor** [comment]
@cyranojones It would be more helpful if we could know if there are any console errors happening in your browser. Here's a guide for how to open the console in Google Chrome: https://developer.chrome.com/devtools/docs/console

You can google how to do it in your preferred browser, but I find Google Chrome gives the best information.
