### ISSUE TITLE
Trying to update card for subscription to no avail. Error message "Cannot read property of "id" undefined

### ISSUE THREAD

**Issue by bingbangzoom** [HabitRPG/habitica#5447]
Hello! I have constantly been trying to update my credit card for HabitRPG since my old one was canceled. However, my new credit card has not been charged for over two months and my old one hasn't been either. I am receiving a message from HabitRPG as well that I don't understand. 
Here is the regular sub box: 
![sub box](https://cloud.githubusercontent.com/assets/6492597/8273500/aa1c6ee2-183e-11e5-8fc7-c406c7158a74.PNG)
 and here is the error message I am receiving after I click "Update Card" and receive a green check mark
![habit pop up](https://cloud.githubusercontent.com/assets/6492597/8273503/ce4d2be4-183e-11e5-9f87-21830fc0ad7a.PNG)
![bug report](https://cloud.githubusercontent.com/assets/6492597/8273504/d1556e28-183e-11e5-9f70-d6a3a461fa40.PNG)

I don't like HabitRPG not receiving money for their services and I'd love to know how to fix this problem as soon as possible so HabitRPG can receive the money it deserves. 

 I am using Chrome 43.0.2357.124 on Windows 8.1 and my User ID is bac90153-7cb5-46c3-94d1-c01a0287f588

**Comment by Alys** [comment]
@bingbangzoom Thanks for reporting this! I'll look into it over the next day or two (probably today).

**Comment by bingbangzoom** [comment]
@Alys Thank you very much!

**Comment by Alys** [comment]
I think that error was happening because the credit card processing company, Stripe, actually cancelled your subscription last year due to four failed payment attempts, however the cancellation message didn't get through to our server. So when you tried to cancel it now, an error occurred because it was already cancelled. :)

I've cleared your old subscription information out of our database (I kept a backup in case it's needed). You should be able to create a new subscription now. Please tell me if you cannot! I'm about to close this issue, but we'll still see any comments you make here and will reopen and keep helping you as much as needed.

**Comment by RainbowMegan** [comment]
I am having this same issue! I'm sure it's because I got a new card a while ago and never updated the info on Habitica. I only just recently noticed that I haven't paid my monthly subscription fee in a long time. I haven't been able to update my card info (same error message) or "cancel" my subscription, error message {"err":"Cannot read property 'current_period_end' of null"} 

So if you could cancel me subscription and I'll update the info, or fix this issue in general, that would be great! My User ID is 4f859ffd-6377-4dec-b4a3-3459c3cca695 . Thank you!

**Comment by Alys** [comment]
@RainbowMegan Thank you for letting us know about this! I've set a cancellation date on your subscription to one week from now, which means that you should be able to create a new subscription. If you do it any time within a week, you won't lose your consecutive benefits. It is necessary to start a new one rather than just changing the card because the subscription has been cancelled at our payment provider's end. Please let us know if you experience any problems with creating a new subscription!

**Comment by RainbowMegan** [comment]
@Alys Thank you, that worked perfectly!
