### ISSUE TITLE
Bought seasonal item, did not appear in inventory and subtracted 15G

### ISSUE THREAD

**Issue by thisisannoying** [HabitRPG/habitica#5448]
Bought the 'Ruby Tail' seasonal item which is priced at 90G. A confirmation message appeared that it was purchased and subtracted 90G from my account. But I am only down 15G and the item is not in my inventory (it's still being display in the rewards section).

**Comment by Alys** [comment]
Go to Settings -> Site and click on Fix Character Values to give yourself back the gold.

If it happens a second time, log out of HabitRPG, clear your browser's cache and local storage (google for instructions if you're not sure how), and then close all browser windows and reopen.

If it still happens after that, I'm afraid we can't help further without knowing which account you have. We can't search for "thisisannoying" because more than one player might have chosen that name. Please go to Help -> Report a Bug and see the instructions there for how to find your user ID (step 6).

**Comment by Alys** [comment]
I'm closing this now but if you're still having trouble, please reply here and we'll reopen.
