### ISSUE TITLE
HabitRPG Lore

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#545]
I think it would be a fun thing to create some HabitRPG Lore, i.e. why it started/the making of it. 

There would be a non-present day setting such as ancient Rome or Egypt, that kinda thing.  Maybe a moral at the end to have good habits?

The lore would also have pixel illustrations, so if you're interested in that, ping me, otherwise I'll put together a few things.

The lore would be a simple webpage with fadeIn/fadeOut line by line of the story with an illustration representing each code block. Lemme know if you're interested!

**Comment by Pandoro** [comment]
I guess that would be cool to have. The kickstarter video and other videos made by Tyler about habitrpg could be used as a source of info. Also see the kickstarter celebration hangout video on youtube. Tyler explained quite a bit about how it all started. 

For the pixel art, I guess you could look at the pixel art thread as always. For the history of habitrog I could think about the following: In the ancient version of the world (First version of habitrpg) everything was a simple excel spreadsheet. Later on people wanted to collaborate on the internet and thus habitrpg as a website was created. Soon it then become more and more graphical, people learned how to draw, albeit it might just be pixel art. At first it was just a male avatar, then soon a cute female avatar decided to gear up and join the game! Not a long time later, pets started appearing. (Just an idea I would think would be pretty funny ^^)

I think things like these could seriously be used to give the game a more game like feeling, without sacrificing the actual Get stuff done purpose. And if at some point we would get quests, we could incorporate things like these. Just think about the possibilities :D 

Archaeologist Quest: Uncover the ancient spreadsheet.
Archaeologists recently discovered an ancient document, shedding new light on how the world might have been created. Proof has been found that the first version of the world was actually a spreadsheet! The spreadsheet was found deep underground, but it was missing several code blocks. Because of this the creator of the spreadsheet could only be recovered in part: "Ty__r R_n_e_l_". Who could this mysterious person be? Might it be the creator of the universe? Help the Archaeologists find the missing blocks and look for an ancient version of the software that can decrypt the spreadsheet. 
Required drops:
3x missing spreadsheet code blocks
1x ancient spreadsheet viewer
Reward:
Historian Badge  

Just... A wild idea... sorry, but my mind sometimes drifts a little :-/

**Comment by lefnire** [comment]
Ha! You guys are amazing :) Actually, I'm having a discussion with a fine fellow about an animated intro to Habit, I'll post back with more

**Comment by horusofoz** [comment]
If this is to go ahead let get in on it. As someone who considered archaeology as a career I'd be very interested in contributing some ideas to an archaeology storyline.

I think it could be longer and include you you too @Pandoro. Aligning the development of HabitRPG from conception to it's current state with that of a civ rising from bone tools to the Internet in a fantastic story isn't hard yet always intriguing.

**Comment by Pandoro** [comment]
@lefnire and me just spoke about integrating team members into the game
actually, as easter eggs, or stories etc. Many of the team members will not
have backed to 800 dollar for an own NPC, but sure helped getting habitrpg
where it is now :D

I would be in there as Pandoro's Box ;)

I think this thread can very well be used to collect some ideas and topics,
which will then hopefully gradually create the "history" of habitrpg :D

**Comment by ruddfawcett** [comment]
@horusofoz Sure ill jump on this as soon as I can!

**Comment by horusofoz** [comment]
Should this be moved to Trello?

**Comment by lefnire** [comment]
Yep!
