### ISSUE TITLE
Page constantly reloads, can't fetch new messages

### ISSUE THREAD

**Issue by mlivits** [HabitRPG/habitica#5453]
My webpage for Habitrpg constantly shows the reloading/syncing icon, and it shows different data than what is on my app. When I try to load a party or guild page, the messages below don't load. When I then hit the "fetch new message" button, nothing happens.

**Comment by crookedneighbor** [comment]
Can you refresh your browser and try again? 

We've been getting intermittent reports about connection issues, but I haven't experienced any problems since I woke up, so I'm unsure if they've been resolved already.

**Comment by Alys** [comment]
@mlivits Is this still happening for you?

**Comment by crookedneighbor** [comment]
We did some work server side. Turns out that there's been a pretty serious memory leak in Node that [manifests itself when using New Relic logging](https://discuss.newrelic.com/t/memory-leaking-only-with-node-js-agent-installed/14448/28). We've disabled New Relic for now and are investigating how to patch Node so we can turn New Relic back on. 

From an end user perspective, you should see no change (except for improved stability \o/ yay!) 

Hopefully all is well now. Going to close this, but if you're still having issues, please re-open.
