### ISSUE TITLE
Can't Cancel Quest

### ISSUE THREAD

**Issue by emily381** [HabitRPG/habitica#5456]
I need to cancel the quest party. A party member started a quest then she was never able to begin the quest due to missing button so she left the party to bump it to someone else. When it bumped the request to me I had already rejected it so now I can't begin it or cancel it. Can you cancel the quest all together. Group 98e27972-d8e5-4423-8485-9a03ff8cb6e4

**Comment by Alys** [comment]
The owner for the quest is "Wonder Woman" (user ID 3bd673ab-ee84-44b1-b47b-4bfff44a8b53) and she's listed as having accepted that quest. Can you please ask her to cancel it? If she also doesn't see the start/cancel buttons, we need to sort that out otherwise this will probably keep happening to your party. The buttons should be at the bottom of the "Invitations" tab in the quest box. If she doesn't see them there, she should show us a screenshot of the place where they should be.

By the way, yesterday in the Tavern, I was trying to help Alien Mama with this problem. I assume she was the original quest owner. If she took the screenshot that I asked for, could that also please be shown to us?

You can drag the screenshots into a comment here, or you can upload them to any public image website and paste in a link. Attaching them to an email won't work because github doesn't display attachments.

**Comment by Alys** [comment]
@emily381 Have Wonder Woman or Alien Mama been able to get those screenshots? We do need to see what the bottom of the Invitations tab looks like to help us work out why you haven't been able to see the buttons. I realise it's been a few days now though, so if I haven't heard from you in another day I'll cancel the quest for you.

**Comment by Alys** [comment]
@emily381 I just now went to delete your quest but thought I should check first, and I noticed that it's been started. If you report a problem and then the problem fixes itself, please always tell us so that we don't spend time investigating something that isn't broken (and so that we don't incorrectly delete a running quest, which almost happened in this case).

I'm going to assume that the buttons were visible but that the quest owner hadn't found where they were when this was first reported, so I'm closing this.

If there was a problem with the buttons not being present, and if it happens again for future quests, please comment here and include the screenshots I described above.
