### ISSUE TITLE
Warning pop up on chrome 

### ISSUE THREAD

**Issue by JasonEdinburgh** [HabitRPG/habitica#5462]
I got a warning window pop up which said I should send a report. It disappeared too quick for me to screenshot it. 

Win7 chrome with extensions including adblock, adblock+, ghostery, collusion. 

Here's the output from the chrome dev console.

http://www.dowce.com/~FPH

All I did was click a few habit completion buttons. Some of the popups were fine, telloing me I had gold etc. then there was a big one with a warning message in red telling me to report it. 

Hope this helps :)

**Comment by Alys** [comment]
Thanks @JasonEdinburgh. This looks like it's related to the server problems we've been having. 

Is the popup still appearing?

**Comment by JasonEdinburgh** [comment]
Hi, I just tested and I got it again

http://www.dowce.com/~FPI

http://www.dowce.com/~FPD

It's not causing me any problems. I noticed earlier that some of my
equipment had become transparent, and I was going to report it to you, but
I have just looked on the equipment screen and I can see it has returned
(in all its glory)

-Jason

**Comment by Alys** [comment]
Hmmm. You're still getting 503 server errors (the others are nothing to worry about; just an ad blocker or similar blocking some third-party things). I had thought that the server errors were finished but apparently not. I've brought this to the attention of our other admins.

**Comment by crookedneighbor** [comment]
We did some work server side. Turns out that there's been a pretty serious memory leak in Node that [manifests itself when using New Relic logging](https://discuss.newrelic.com/t/memory-leaking-only-with-node-js-agent-installed/14448/28). We've disabled New Relic for now and are investigating how to patch Node so we can turn New Relic back on. 

From an end user perspective, you should see no change (except for improved stability \o/ yay!) 

Hopefully all is well now. Going to close this, but if you're still having issues, please re-open.

**Comment by crookedneighbor** [comment]
We did some work server side. Turns out that there's been a pretty serious memory leak in Node that [manifests itself when using New Relic logging](https://discuss.newrelic.com/t/memory-leaking-only-with-node-js-agent-installed/14448/28). We've disabled New Relic for now and are investigating how to patch Node so we can turn New Relic back on. 

From an end user perspective, you should see no change (except for improved stability \o/ yay!) 

Hopefully all is well now. Going to close this, but if you're still having issues, please re-open.
