### ISSUE TITLE
Mixed Content Warnings

### ISSUE THREAD

**Issue by anwilli5** [HabitRPG/habitica#5464]
In using the site this evening I've gotten the following Mixed Content warnings in Chrome:

Mixed Content: The page at 'https://habitrpg.com/#/options/inventory/mounts' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/GCuipwL.png'. This content should also be served over HTTPS.

Mixed Content: The page at 'https://habitrpg.com/#/options/groups/tavern' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/GCuipwL.png'. This content should also be served over HTTPS.

I believe on both pages I got an on-screen notification that caused this issue, but I have since acknowledged the notifications and can't recreate the warning messages.

Also, there is one on https://habitrpg.com/static/front

Mixed Content: The page at 'https://habitrpg.com/static/front' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lato:400,700'. This request has been blocked; the content must be served over HTTPS.

Finally, on a very minor note that didn't seem like it deserved its own ticket, it looks like the link to the favicon at https://habitrpg.com/static/front is not correct:

GET https://habitrpg.com/images/favicon-8b58f6a1.ico 404 (Not Found)

As always, thanks for a very useful site!

**Comment by Alys** [comment]
Thank you for reporting these!

The imgur link that triggered those first two "insecure image" warnings was posted by a user in a message in the Tavern about 19 hours ago. We'd get those warnings any time any user posted an image that wasn't served over HTTPS. This isn't a security risk, although the browser has no way of knowing that and so it warns you (which is the correct browser behaviour, but you can just ignore those two warnings). Let me know if you want more information about this.

The fonts.googleapis.com warning can be easily fixed by changing that link so it doesn't specify http. I'll do a commit for that in a sec.

The favicon file exists, but perhaps not in the right place. 

```
./website/public/favicon.ico
./website/public/front/images/favicon-8b58f6a1.ico
```

I'll have a look into that.

**Comment by Alys** [comment]
The fonts.googleapis.com error should stop happening the next time we deploy code to the website (might be in a few days).

The favicon thing is odd. I could replicate the error once, but not on a reload, and the site does seem to pick up a favicon (possibly the /website/public/favicon.ico by default). Those two favicon files I listed above are identical so I'm not sure what the intention is with them. I'm leaving this one to someone who knows more about why those two files exist. The link to favicon-8b58f6a1.ico was created by @lefnire on 2015-04-02 (possibly working with @AnitaYCheng) in https://github.com/HabitRPG/habitrpg/commit/47157a1b

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg/blob/develop/website/public/front/images/favicon-8b58f6a1.ico is now outdated and I'll delete it in a few days if no one objects, just to tidy up our code base.

https://github.com/HabitRPG/habitrpg/blob/develop/website/public/favicon.ico is the one that was updated for the recent site rebranding.

**Comment by Alys** [comment]
I've deleted the outdated favicon.ico file from https://github.com/HabitRPG/habitrpg/blob/develop/website/public/front/images/favicon-8b58f6a1.ico
