### ISSUE TITLE
Cron "skipping ahead" and taking damage overnight for no reason, despite completing all dailies

### ISSUE THREAD

**Issue by aj1125** [HabitRPG/habitica#5467]
Lately when I start up Habitrpg in the morning, I've been finding "damage" that shouldn't be there. For example, yesterday and the day before I checked off all my dailies, but in the morning I had significant damage and my task page had been reloaded with the new day's dailies, with some automatically checked and unchecked.  I also looked at my quest and the boss' health bar isn't registering the damage I've done for the last several days. 

User ID: 9ace84e4-f540-47e9-b618-6b1944ba8663

**Comment by Alys** [comment]
@aj1125 That will be because of this bug: https://github.com/HabitRPG/habitrpg/issues/4313
Please see the Advice section near the top for information about how to recover from the damage and how to try to prevent it. I'm going to close this issue now since we're tracking the problem in that other one, but you're welcome to comment here if you have questions and we'll see them and respond to you.
