### ISSUE TITLE
Repeat every 2 days dailies - not due yesterday but took damage/streaks reset

### ISSUE THREAD

**Issue by iiieeeoo** [HabitRPG/habitica#5510]
I completed all but one of my dailies yesterday and confirmed with the DDT, but I took more damage than predicted and have no streaks on my every-other-dailies. The DDT now has an x for them yesterday. I know they were grey when I went to bed, the pattern of not-due days in the DDT shows that yesterday should have been an off day, and they're both showing as due today, so it seems that everything's working as expected except that at some point since I went to bed (cron?) the server thought they should have been due yesterday.

I've only accessed Habit from one computer in the last few days. Date and time are correct. I have a CDS of +6. UID 8f0c35d7-ab70-415e-b5d1-cd4e9147ca20 and the dailies are "Trigger points" and "check emails" (if someone wants to have a look at my tasks that's fine).

I don't need advice for fixing the damage, just reporting. Thanks.

**Comment by Alys** [comment]
How many minutes or hours ago did your cron happen?

Please report as a number of minutes/hours in the past instead of as a specific time, because timezones make times hard to work with.

**Comment by iiieeeoo** [comment]
I think within the last half hour, certainly less than an hour ago.

**Comment by Alys** [comment]
When you look at the start date for either one of those Dailies, what date do you see? Please copy-paste it here.

What's the date and time now where you are, and the timezone as GMT+nn?

**Comment by iiieeeoo** [comment]
12/06/2015 (dd/mm/yyyy). I'm in GMT+1 (British summer time) and it's currently 0913 of the 28th of June 2015.

**Comment by Alys** [comment]
@iiieeeoo I'm really sorry, but at the moment I have no idea what went wrong. We did put some new code in place in the past few hours (https://github.com/HabitRPG/habitrpg/pull/5482) and that code is used by cron, but the changes shouldn't have changed how cron worked and they should have just fixed a display problem that was causing some "every X day" Dailies to appear due/not due on the wrong days. Also the new code passed all our automated and manual tests. In addition, tests that I've just done now on a virtual machine set to your timezone using your Dailies have shown the correct cron behaviour over a range of days including today. So I'm puzzled about why it didn't work correctly for you. I will keep thinking about this and I'll make sure our other admins have seen this.

BTW, thank you for all the information you provided. It had exactly the right detail and precision.

For admin use, these are the two Dailies and some other non-personal data from @iiieeeoo's account. I've trimmed the task history. The Dailies are showing streaks, but that would be because iiieeeoo has already reset them.

```
{
    "_id" : "8f0c35d7-ab70-415e-b5d1-cd4e9147ca20",
    "preferences" : {
        "dayStart" : 6,
        "timezoneOffset" : -60
    },
    "lastCron" : ISODate("2015-06-28T06:41:25.078Z"),
    "dailys" : [
        {
            "text" : "check emails",
            "challenge" : {
            },
            "attribute" : "str",
            "priority" : 1,
            "value" : 25.90492383241637,
            "tags" : {
                "99652cf4-ba5b-411a-a92d-90ce5aa706e0" : true
            },
            "notes" : "",
            "dateCreated" : ISODate("2015-04-13T11:12:17.040Z"),
            "id" : "896d7885-f8de-40fc-8697-dca812ed2fa1",
            "streak" : 36,
            "checklist" : [ ],
            "collapseChecklist" : false,
            "repeat" : {
                "su" : false, "s" : false, "f" : true, "th" : false,
                "w" : true, "t" : false, "m" : true
            },
            "completed" : false,
            "history" : [
                ...... TRIMMED ......
                {
                    "date" : 1435387586277,
                    "value" : 26.484733494407937
                },
                {
                    "date" : 1435473685120,
                    "value" : 25.90492383241637
                }
            ],
            "startDate" : ISODate("2015-06-12T00:00:00Z"),
            "everyX" : 2,
            "frequency" : "daily",
            "type" : "daily"
        },
        {
            "text" : "Trigger points",
            "challenge" : {
            },
            "attribute" : "str",
            "priority" : 1,
            "value" : 40.97997504419715,
            "tags" : {
                "6b976bc4-b07b-4cb5-ab4d-3dcb16a4adaf" : true
            },
            "notes" : "",
            "dateCreated" : ISODate("2015-02-23T12:58:42.771Z"),
            "id" : "596d116b-201a-4806-96ae-ea80ee932433",
            "streak" : 3,
            "checklist" : [
                {
                    "text" : ":zap:",
                    "id" : "a5da8426-edab-4674-831c-2ba9af166ab9",
                    "completed" : false
                }
            ],
            "collapseChecklist" : true,
            "repeat" : {
                "su" : false, "s" : true, "f" : true, "th" : false,
                "w" : false, "t" : false, "m" : true
            },
            "completed" : false,
            "history" : [
                ...... TRIMMED ......
                {
                    "date" : 1435387586278,
                    "value" : 41.559784706188715
                },
                {
                    "date" : 1435473685122,
                    "value" : 40.97997504419715
                }
            ],
            "startDate" : ISODate("2015-06-12T00:00:00Z"),
            "everyX" : 2,
            "frequency" : "daily",
            "type" : "daily"
        },
    ],
}
```

**Comment by iiieeeoo** [comment]
No problem, thanks for looking into it so quickly. I'll keep an eye on them and post if it happens again.

**Comment by LittleMupsMum** [comment]
I just had the same issue with an "Every 3 days" daily showing up as not done.  There is a cross showing up on the Data Display tool despite it being the day after it was due.  
Not sure what info you're after, so I'm going to copy what's above:

UID 32e0135e-5f3b-4dc3-b517-995f6f24d5d6

The daily which failed yesterday was "Soak apricots and check schedule".  It has a start date of "06/12/2015" and repeats every 3 days.  So it was not due yesterday and it's not due today, but somehow Cron thought it was due and not ticked for yesterday.  Not sure if it's relevant but I used to have a checklist on this daily with 2 tasks: "Soak apricots" and "check schedule" (the second item being to adjust which days it was next due).  I removed the checklist a couple of days after switching it to the 3rd daily repeat.  Also the day I changed it to a proper Every X Days was closer to 6/18 (when the feature came out), can't remember why I chose the earlier start date, something about it being easier to calculate in my head?

I also have also just noticed a similar failure on my other 3rd daily, "Make chias".  It shows up as failed on 15/6/22 and completed on 15/6/23.  Start date for that one is "06/19/2015" and repeats every 3 days. I'm pretty sure I've been doing them every 3rd day and ticking them off. Haven't been verifying them using the DDT as I didn't know to do that until now.  Same deal, this daily previously had a similar style checklist but I have modified it rather than removing it.

Other info: I'm on GMT+10 (Australian Eastern Standard Time).  Current date and time 29/06/2015 1:06am.  I have never changed the timezone on my computer, or edited my HabitRPG timezone since I made the account.  I checked these dailies off at about 2340 local time - so about an hour and a half ago.  I refreshed the site several times before midnight after doing this and could see them all grey.  Didn't know to check the DDT, will do that from now on.  I refreshed the site at about 0010 local time - so just under an hour ago now.  The dailies from the previous day still showed up as ticked and I thought that was odd.  So I refreshed again, and that was when I lost health, I guess that was when Cron triggered. I haven't edited anything manually since then.  If there is any advice on how much mana I would have received from a perfect day, I'd appreciate a link. I'm guessing there's no way to get my perfect day (and resultant stat buffs) back.

Sorry, I can't stay awake to reply to any comments right now, but will reply if needed later on.

**Comment by Alys** [comment]
@LittleMupsMum Thank you for your report. I still don't know what's caused this but I'm continuing to investigate.

**Comment by Alys** [comment]
On my own account (d904bd62-da08-416b-a816-ba797c9ee265), I have four Every X Days Dailies with a 2-day repeat. Two of them were due yesterday and two were not. All four were handled correctly by cron (the due ones were treated as due, the others were not). Unfortunately this means that the error you've both experienced is not a predictable, constant one, which might make it harder to track down.

Can you please both keep reporting here each time you notice your Every X Days Dailies not being handled correctly? For each report, you need to tell me only which Daily it was, whether it should have been due or not, and whether it was treated as due or not. If at the same time you also notice some of your other Dailies not becoming unticked by cron, please tell me that as well.

**Comment by Frikster** [comment]
So I may have the same problem. However, it is only a problem on my Android device. On my Android device tasks that repeat every 2 days are shown as shown as uncompleted even though I did them yesterday. However, on the habitRPG website everything is working smoothly and these tasks are greyed out as they should be. Am scared of what will happen when I wake up tomorrow.

I'm running the latest version (of the app). and have tried syncing multiple times.

For one of the tasks (VR) showing as not done on my android device but done on the website the start date is 06/27/2015, I'm in Vancouver Canada. Time here right now is: 11:40pm (UTC-08:00) Pacific Time (US & Canada)

For the other task (PC's) that also shows as undone on my phone but done on the website, the start date is 06/11/2015.

0eb245f4-862b-4eec-9c67-7803cf616e9c

**Comment by Frikster** [comment]
UID: 0eb245f4-862b-4eec-9c67-7803cf616e9c

**Comment by LittleMupsMum** [comment]
Happened again with my Make Chias (every 3rd) daily just now.  Should not have been due (29/6) as I completed it the day before (28/6).  Not due today (30/6) either.  Now shows on the DDT as incomplete 29/6 as if it were due.  I checked my DDT before midnight and it had only the two other dailies showing incomplete, not this one.  Had also repeatedly refreshed my tasks page showing tasks grey as planned.
Darn, I should have recorded my streak.
I am wondering if it happens when I 
1) Check the website soon after midnight (it is now 7 past, it happened a couple minutes ago)
2) Go to the Tasks page from another part of the site (having the browser open the whole time).  I had my Party page open before midnight, and when I went back to that tab after midnight I then hit the Tasks button to get back to that page.  It initially showed up with all the tasks from yesterday ticked while also showing some other tasks being due.  (Next time I will check what tasks are appearing due.) Did not seem to run Cron at that point, I was expecting to lose 0.8 health.  I refreshed and it ran Cron and I lost 1.3 health.
I am using Firefox 38.0.5.  Up to date as far as I know.  I also have the website open on my Nexus 9 but haven't refreshed it in a few hours.

(Edit: Have now restored my streaks on both dailies to my best guess.)

**Comment by Lenyberry** [comment]
This happened last night on my every 4 days "water houseplants" daily. It showed yesterday as gray, as it should have (it was due the 27th and should be due again tomorrow, start date 6/11), and I should have had a perfect day yesterday -- completed all due dailies and double-checked it with the DDT, both the site and DDT showed that I had completed everything. This daily also would not have been due yesterday by the twice-a-week scheduled days I had it set to before the every X day option existed (it was previously due Mondays and Thursdays, which would have made it due today).

This morning I logged in about 8:30am (half an hour ago, I have a custom day start set to 2am if that's relevant) and noticed I took damage (1.7 points of damage were done to my party in the final Vice quest, and 2.2 to me) and didn't have a perfect day buff, so I started looking for which daily's streaks were gone to figure out what happened.

I've reset my streak as best I can remember and used FCV to repair the damage, and let my party know I was hit by a bug so they can use FCV as well if they want to bother with it.

**Comment by rachelkachel** [comment]
This happened to me too, about a half hour ago (8:30ish GMT-6), on a daily set to every 2 days (Ten pushups), which has a start date of 6/17 (so it's due today, 6/29). DDT shows an X for yesterday. I don't have a Custom Day Start time set. I have been in the Inn for a few days - checked out yesterday - and did not do this daily the last time it was due, although before that I had an unbroken streak.

UID 7b9c41d3-6d21-4168-9dfd-e0c2489df8ff

Edit: happened again today, 7/1; I checked the DDT last night and it said everything was fine but this morning shows an X.

**Comment by Frikster** [comment]
_IMPORTANT UPDATE_: So last night the 'VR' daily that I had set to every 2 days was correctly greyed out on my PC. It is not also correctly greyed out on my android device. No clue if I lost health last night from this dailly but it looks like the reset fixed it? Except... I have a 'PC' dailly that repeats every two days. And what the hell, this morning it is unfinished as it should be on my laptop, but it is greyed out on my Android device! But last night it was active on my android device when it should have been greyed out. The app is clearly running on a different cycle than the website with regards to daillies that reset every X days.

How can I tell whether a specific dailly contributed to my lost health? Because I missed quite a few daillies yesterday due to slacking. I don't know whether I lost health from 'VR' or 'PC's' when I shouldn't have.

I don't suppose there's anything I could do to help? I have yet to take the time to get myself set up as far as getting myself familiar with the server-client paradigm you guys are using, but I mean maybe I'd be useful for unit tests. More than willing to do some grunt work here.

0eb245f4-862b-4eec-9c67-7803cf616e9c

**Comment by iiieeeoo** [comment]
Frikster - the Data Display Tool (https://oldgods.net/habitrpg/habitrpg_user_data_display.html or click the "data" link from the website) will help you work out what's going on.

**Comment by kinnnie** [comment]
I have a daily that was set to every 4th day (named "Tandtråd" if you look into my details). I had missed it the last times, so Saturday I finally did it even if that wasn't due day. To try and change that, I put Saturday 27/6 as starting date, it turned yellow or orange or what it was and I checked it and it turned gray. Sunday would have been due day if I hadn't change it, but it didn't show up as due, so I thought it worked out, but at cron on Monday morning (about ten hours ago) I got hurt from it.
I have costume day start at 3 am, and was awake past midnight and didn't see it due neither before nor after.
I use both PC, andriod tablet and iPhone, but as far as I remember I was just on PC (chrome) during the weekend.
User ID: 537bb3c4-790d-4ea2-8e6e-b1aa74482ed4
(now I've changed it to every Wednesday to prevent further damage, so I can't give feedback on if the problem comes up again)

**Comment by kaitmiller** [comment]
I have a similar issue.

This morning (~6:30 AM EDT) when I checked Habit on my phone (iOS app), I noticed that I lost health, which surprised me, as I was pretty sure I'd had a perfect day yesterday and my party is not in a quest. I couldn't look at the streaks then, but I looked this evening and saw that my every-4-days Daily, "Back up computer," had no streak.

It should not have been due yesterday, because it was due Saturday--I know for sure that I did it Saturday, because my computer keeps track and told me it was last backed up 6/27. It's possible that I failed to check it off on Saturday, but unlikely. _However_, I did go into the Inn for Saturday night.

Usually, the DDT shows a daily done when I was in the inn as done the day I come out (on the Dailies History page). However, the daily in question is not shown as done yesterday (6/28). In fact, it's not shown as due, either. It's yellow with a dash. 6/27 isn't shown on the DDT other than by a grey bar since I was in the Inn.

This daily is shown as having a start date of 2015/06/15, and I think that's before I changed it from "certain days of the week" to "every X days."

Today the DDT is not showing me this daily as due, but it is showing me a different every-3-days daily ("Clear completed to-dos") as due when it is not. I've already emailed Alys a few times (gwraig.annwn at gmail) about the DDT showing dailies as due when they are not.

Unfortunately, I don't remember whether I checked the DDT yesterday or what it showed.

I'm using Chrome on a Mac.

My user ID: 0974a026-4ff0-4f84-bc0c-c06f8e3c4303

**Comment by iiieeeoo** [comment]
The same dailies were not-due again yesterday and I took damage/lost streaks again today, but this time the DDT is showing that I had a perfect day - the dailies in question are showing as not due yesterday. Weird. Would it be useful if I don't check one of them off today although it's due and see what happens?

I should probably mention that the day before yesterday (the last time they were due) I completed both but also spent the night in the Inn.

**Comment by Alys** [comment]
Everyone, there's a change to HabitRPG which will be released soon (within the next day probably) that should make cron behave better for "Every X Days" Dailies. I've also released a new version of the Data Display Tool (version 6.0a) which has some small fixes. However I think we still need to make changes to both HabitRPG and the DDT to properly account for Dailies' Start Dates under some circumstances.

I believe the Android app still needs to be updated for "Every X Days" Dailies too.

Thank you all for your comments so far. They've been useful even though we haven't replied to the individually - sorry about that! I've been focussing on the code.

@iiieeeoo It's probably not worth deliberately leaving one of your Dailies unticked today since the new HabitRPG code mightn't be live until tomorrow. Maybe the next time it's due, if we haven't sorted out all the bugs before then.

**Comment by cmlobue** [comment]
I am having this problem as well.  I have an every 2 days task called "Water the Mounts" which damaged me on my last two "off days" before that even though it was not due on either of those days.  My user ID is a8769e78-9b13-400f-a24c-961ef29b80f8.  I only use HabitRPG on Firefox 38.0.5 on a machine running the latest update of Windows 7.

Edit: It also applied to my every 14 days "Care for the Hound" task the day after it was due, so it looks like the issue, at least for me, is the system thinking they are due on the day of and the day after.

**Comment by iiieeeoo** [comment]
Well, I actually didn't do one of my every-other-dailies yesterday (check emails). It was due yesterday and my cron ran a few minutes ago. The streak reset, but I didn't take damage from it.

**Comment by Alys** [comment]
@iiieeeoo Are you certain that the streak for it was not zero yesterday?

**Comment by iiieeeoo** [comment]
Oh, you're right. I didn't get around to resetting it.

**Comment by LittleMupsMum** [comment]
Thanks for your hard work Alys, but I'm still having this bug.
I checked off all my dailes which were due yesterday and should have got a perfect day.  Checked it on the DDT last night.  Lost health this morning on syncing my tablet (Nexus 9) at 7am (6.5 hours ago now).  I have lost my streak on my "Soak apricots and check schedule" daily (I'm pretty sure that I'd reset both to 10 a few days ago and I've completed the daily at least once since then).  It was not due yesterday, it's due today.  Actually I'm not sure if I have managed to get a perfect day at all since having this bug.

I'm also having problems with the DDT but I'm not sure where to report this, is it a different repository or maybe you haven't published it?  According to the DDT it was my "Make Chias" daily which failed.  This was also not due yesterday and not due today.  However I don't seem to have lost my streak on that daily according to the habitrpg website... 
I'm also not clear on how the data retention (or lack of) is supposed to affect the DDT.  I'm not a subscriber.  It says data from the past week is supposed to be shown?  Since the month ticked over yesterday all my data from June is gone, except for one or two days ticked for each task (not sure what determines which day in the past month gets a tick, but there's just one or two per task in the whole month).  And for the day before yesterday (1st July) it has been showing all but three of my list dailies as completed, even the ones that were grey and which I definitely didn't complete, including both of the 3rd dailies (only one of which was due that day).  Pretty sure it's not an accurate log of the habitrpg data, since I didn't get a Perfect Day out of it, so I can't tell whether my "Soak apricots" daily failed silently that day as well as the other couple of dailies I think I didn't complete.
Sorry to add more complexity to the situation, and good luck with the bug hunt!  Wish I was better at reading code so I could help you out :)

**Comment by LittleMupsMum** [comment]
Just realised that apparently I was hit by this bug twice in one day ... once when I first synced in the morning on my tablet, as above, and once when I synced on this desktop 2 hours ago after posting.  Lost some more health and also my streak on "Make Chias" at that point, so I guess that the DDT did reflect something in the habitrpg data...
Wonder if I should check what the DDT says on my tablet?  I haven't bothered pasting over the API key there.

**Comment by lanachristy** [comment]
I have the same problem with my weekly dailies. It should not due until every Tuesdays, but it often shown as undone while it occasionally actually went off as "done". That was when I use my computer to log in. When I use my phone, it is always undone before the due date. It also took damage from me, which I eventually need to use my rouge skill to prevent it from happening.

**Comment by storian** [comment]
The code change from 4 days ago has not stopped the bug for me.

**Comment by LordVladneutral** [comment]
Same thing here with a "every 10 days" task. It might just be useful to find the problem so look around as much as you want. It's named ":nail_care: Se couper les ongles" it wasn't due yesterday, but it way two days ago. I did it when it was due and I got unexpected damages as if it was due yesterday.

Start date : 13/06/2015 (nothing more precise)

I'm in wester Europe. Only use computers both on Arch Linux, using Firefox, and log everyday.

User ID : ce36e72e-50fd-4e98-908b-34b3c06e9664

**Comment by LittleMupsMum** [comment]
My "soak apricots" daily had this bug again yesterday - was due the day before and completed, not due yesterday and marked incomplete in the DDT.
I'm going to try syncing all my devices before bedtime and see if that helps.

**Comment by rachelkachel** [comment]
This is still happening to me too, same daily, and possibly another one - an every-6-days one that was due three days ago, shows on the DDT as incomplete two days ago, and as not due yesterday.

**Comment by Hiraelle** [comment]
This happened a few times to me too.
User ID : 8a164f87-9393-4707-82bf-b7c0d17f4da1 
I have several due every other day tasks, and yesterday and today I took damage from some that should have not been due - as a result even if I complete all my tasks, I can't seem to get a perfect day :/
It worked fine at the beginning but now it seems to be very buggy.
I'm afraid I deleted the incriminated task for the health loss of today before checking if there was a thread though ^^ (it was called "Pas de bière" if you can somehow check, I've decided to create a new task by the same name now that I'm not like "DAMMIT NOT AGAIN"). Got a similar problem with my task called "Nager" but it's inactive at the moment since I can't do it for now - usually it's on repeat every 2 days or 3 days : I saw in the display data tool that it wasn't completed 3rd and 4th july... both days it was supposed to be not due. In fact for this task, every time I "failed" it, it was not actually due. 

How it happens for me : 
1) I'm on the "tasks" tab. Before midnight I refresh + sync (else I have the bug of "two versions of your data")
After midnight usually part of my dailies (like one or two, and not those that caused problem) automatically appear in the "due" category, even if I don't refresh or sync, but I don't think it's related because it happens all the time, even when I have no problem. 
2) After midnight I go to my party tab, because we have a quest active pretty much all the time. I refresh + "fetch recent messages" to see how I did, and that's when I see I lost health and am not buffed
3) I go to the tasks tabs and see I've lost my streaks on the "repeat every X days" tasks that were not supposed to be active the day before (and that I had checked when they were active)

**Comment by Alys** [comment]
I've made a change that might fix these problems. If anyone still experiences them from their NEXT cron (not from any cron that happened before you read this), please comment here again.

**Comment by iiieeeoo** [comment]
Yay, it worked fine for me today (I've had a few days off). Looks like you smashed it!

**Comment by Alys** [comment]
Oh thank goodness! :) Thank you for letting me know. I'll leave this open for a few more days though to capture any other reports, in case there's situations where it's still broken.

**Comment by lanachristy** [comment]
I started clicking the dailies that did not work well before so I don't get damage. I am not sure if it is because I have clicked it before the actual due date This daily still show up as undone on my adroid phone app before the set date. Do you think I should try to delete and reset this daily?

**Comment by Alys** [comment]
@lanachristy Are you still having that problem? If so, deleting and recreating the Daily might help, if you are not sure that its settings are correct. If the problem keeps occurring after that, tell us your User ID (go to Help -> Report a Bug and see step 6 for how to get your User ID).

**Comment by lanachristy** [comment]
I have deleted it and created a new one. The problem remains.
This is my user id.
e062c73f-b7ee-4419-baff-8189040812f4

Thank you so much for helping!

**Comment by Alys** [comment]
@lanachristy Make sure you're using the latest version of the Android app. An older version won't display the new types of Dailies correctly. If that doesn't fix it or if you can't upgrade the app, go to the website and see if the Daily is displaying correctly there. If it's not displaying correctly, open it into the edit screen and take a screenshot of the Advanced Options section. Paste the screenshot into a comment here (don't attach it to an email because GitHub discards attachments).

**Comment by lanachristy** [comment]
![image](https://cloud.githubusercontent.com/assets/13166358/8641154/ccef7c2e-28d4-11e5-8c8c-05db12a10895.png)

I am not sure how to take a pic of the whole column. Does this help?

**Comment by Alys** [comment]
@lanachristy That Daily is due every day except Tuesday. When a day button is highlighted in a strong colour, it means it's on for that day; a pale colour means it's turned off. When you create a new Daily, by default it's on for all days.

**Comment by lanachristy** [comment]
Thanks you so much!! I feel like a fool lol
Sorry for bothering you for this mistake.

**Comment by Alys** [comment]
@lanachristy That's okay! Don't feel foolish; it's actually not an uncommon mistake. We should probably make the interface more intuitive so that people don't get confused by it. I've just logged https://github.com/HabitRPG/habitrpg/issues/5603 for us to work on that.

**Comment by Alys** [comment]
I'm going to close this issue now because I think the bugs have all been fixed, but if anyone is still having trouble, please tell us by commenting here. We'll see your comments even though this will be closed.

**Comment by Frikster** [comment]
Hi, I hate to be the bearer of bad news but the android app is still syncing incorrectly for "repeat every x days" tasks. On the website my "laundry" task is grey. On my app it isn't. I uninstalled and reinstalled. No change.

0eb245f4-862b-4eec-9c67-7803cf616e9c

**Comment by Alys** [comment]
@Frikster Can you please check in Google Play to see if there's an update for the app, and if there is, try that? If there isn't, please tell us what version you have installed - Play doesn't always make new versions available to everyone at the same time, so we need to be sure of the version number. It's under the Settings or About screen, from memory.

**Comment by Frikster** [comment]
No update available. I'm running v0.0.55. I wouldn't be surprised if an update isn't available for me yet. I have a Samsung Note 4. Touchwiz devices typically get updates later, or at least such has been my experience.

By the look of things (according to my user-data), I am getting hurt from incomplete daillies from the app even though they are grey on the site.

**Comment by Frikster** [comment]
What's the protocol if that is indeed the latest version?

**Comment by Alys** [comment]
@Frikster The same as for any bug - we'll investigate and fix it if we can.

Note that a new version will be released very soon, in a day or two I'd estimate. I've only just now found out about that. It's likely to have the most recent code which would probably solve the problem, if the current one doesn't.

**Comment by Frikster** [comment]
Sweet, I'll report back by the end of the week then.

**Comment by Alys** [comment]
Reopening this until I'm certain the Android app is correct.

**Comment by Alys** [comment]
I believe the latest version of the Android app now has the fix for this, and I haven't heard any more reports of this problem, so I'm closing it again.

If anyone still sees this bug happening, please comment here.

**Comment by Frikster** [comment]
Everything looks good on my end! Good job! Beer's on me if you ever find yourself in Vancouver, Canada :D

**Comment by ArcShade083** [comment]
I had this problem specifically with an "every x days" daily that I edited to change the frequency. It took me a while to figure out why I was being damaged. Today the user data display showed it as due even though it was supposed to be grey. I'm pretty sure it would have been due today if I hadn't changed the frequency.

**Comment by iiieeeoo** [comment]
My every-other-dalies spontaneously got out of sync a week or two ago (showing as due in the DDT when they were grey on my task list and vice versa). I reset the start dates and they've been working fine since then so I pretty much forgot about it. @ArcShade083, you might want to give that a try as a simple fix.

**Comment by ArcShade083** [comment]
I had to reset my start date just to make my every x dailies line up properly with each other. What I ended up doing was just deleting the old ones and re-creating new ones. I just figured the developers might want to know that it's happening.

**Comment by squirrel7** [comment]
I am having this issue...I checked the data display to see how much damage I was doing to the boss my party is fighting and it said I had one daily unchecked even though my daily list showed everything either checked or gray. Checked the "dailies incomplete" list and it's my "every 30 days" daily that I created about a month ago. I made a temporary fix by changing it to the other kind of daily and un-selecting all the days of the week and now it's showing all dailies complete but I still wanted to report that I'm seeing the bug.

**Comment by Alys** [comment]
@ArcShade083 @iiieeeoo @squirrel7 This is a problem in the Data Display Tool, not Habitica. I believe it's incorrectly calculating the start date in some cases, probably because of the time portion of the date which you have no control over or visibility of in the browser (certain combinations of the time portion and your timezone and your Custom Day Start time can result in the date being one day different than it should be). Until I'm able to correct the problem in the DDT, you can probably fix this by editing the Daily and changing the start date, and then if you wish to, changing it back to its original value. This will probably change the time portion of the start date, and with luck it will be different enough that the bug is avoided. If that doesn't work, deleting the Daily and recreating it probably will, for much the same reason.

**Comment by Alys** [comment]
@ArcShade083 @iiieeeoo @squirrel7 If you're still having trouble with this, edit the tasks to change the Start Date to a recent date (a date after daylight savings ended). Let me know if that doesn't fix it.
