### ISSUE TITLE
Dailies not doing damage

### ISSUE THREAD

**Issue by WhitneyFox** [HabitRPG/habitica#5521]
I really shouldn't complain about this too much as it means I apparently can't die, but when my day reset this morning all my checks from yesterday cleared and (I think) my streak counters updated, but I didn't take any damage from dailies that weren't checked off. I think I should have taken about 12 damage. I can't be certain as I wasn't really paying attention on the weekend, but I don't think this was the first day this happened.

I use FireFox on Windows 7.

Thanks.

**Comment by crookedneighbor** [comment]
@WhitneyFox Is it possible that you're currently [resting in the inn](http://habitrpg.wikia.com/wiki/Rest_in_the_Inn)?

We'll need your user id to investigate further. You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by WhitneyFox** [comment]
Hi @crookedneighbor I stayed in the inn a couple weeks ago, but I checked out and I've received damage since then. As far as I can tell, this only started happening this weekend.

My User ID is 8c487460-6480-46dc-bb7b-4850bd15ecb8

Thanks.

**Comment by Alys** [comment]
Are all of the Dailies that should have given you damage but didn't using the new "Every X Days" feature?

**Comment by WhitneyFox** [comment]
Hi @Alys I haven't set up any of those kind of features. I just have everything set as the default everyday setting.

**Comment by Alys** [comment]
Oh... Suddenly a lot has become clear. WhitneyFox's Dailies don't have start dates because they haven't been edited since the new Daily options went live (which is fine; that's a perfectly reasonable, permitted scenario). However my new `shouldDo` code assumes a start date of today if there is no start date specified. That works well for the case where `shouldDo` is being used to determine if the Daily should be due or grey (the bug I fixed with the new code), but it fails horribly when being used by cron to work out if the Daily should have been done YESTERDAY. This will explain some other reports we've seen too.

@WhitneyFox Thank you VERY much for reporting this and for answering our questions! We'll get this fixed up for you. It should be at most another couple of days during which you won't take damage, but hopefully much less.

**Comment by WhitneyFox** [comment]
Yay I helped, lol. Now lets see if I can complete enough dailies to level before you fix the code ;-)

**Comment by Alys** [comment]
@WhitneyFox This fix has gone live now so you should now take damage from those Dailies if you don't complete them.

**Comment by Alys** [comment]
As described in https://github.com/HabitRPG/habitrpg/issues/5549, this bug is still happening. I'm writing  a migration script to set a startDate on all Dailies that need one, which should fix it properly.
