### ISSUE TITLE
Tab crashes in chrome when site is left open for a while

### ISSUE THREAD

**Issue by Ytrog** [HabitRPG/habitica#5522]
In Chrome (On windows 7) when I leave the tab wit HabitRPG open for a few hours (more than 4h) the tab is crashed (the "aw snap" message). 

The workaround is reloading the page however.

**Comment by Alys** [comment]
I'm going to close this because we are slowly improving the site's code (including a large-scale change to how tasks are handled in the backend) which will make the site's performance improve over time. Glitches like the one you describe can be expected to disappear or become less frequent in future. I don't think there's anything specific we can do for your case, apart from these site improvements.

We have noticed from other people's reports that browser/site performance is bad if the browser has many tabs open, and improves if most tabs are closed, so that might help in the short term.
