### ISSUE TITLE
More diverse hairstyles

### ISSUE THREAD

**Issue by silverbucket** [HabitRPG/habitica#5527]
There aren't any hairstyles for avatars that aren't either - fully haired or completely bald. What about other hair like:
- windows peak
- bald on top, hair on the sides
- just hair on top

**Comment by lemoness** [comment]
Hi Nick! Thanks for the suggestion. The best place to suggest it would be this Trello card: https://trello.com/c/fDlvPaIG/14-hair-colors-and-hair-styles-temporarily-closed Currently we aren't accepting new hairstyles because we have a lot in the queue, but in the future we would like to have more of them, so you can go ahead and mention them. 

I'm going to close this now for organization, but if you have more questions, feel free to let me know on the Trello card!
