### ISSUE TITLE
Emacs Plugin

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5546]
Anyone want to write an emacs plugin so I can update habit via emacs instead of having to go to the actual website?

**Comment by Alys** [comment]
@AceJaxer You might like to mention this in the Aspiring Coders guild and The Developers guild so that third-party devs know about it. Include a link to this issue in each case so that if someone decides to take it up, they can comment here to avoid duplication of effort from other devs. The Bountysource plugin has been added to your issue so you can add a bounty if you'd like to encourage developers to work on it.

**Comment by Alys** [comment]
There doesn't seem to have been any interest in this, so I'm going to close this issue, however if you decide you'd like to add a bounty to it, we can reopen it.

Unfortunately the site's main developers have many other issues to resolve, so it's unlikely that they'd have time to write an emacs plugin. We'd welcome a plugin from any other developer, and a bounty might encourage them to write one.
