### ISSUE TITLE
Add HabitRPG app to F-droid store

### ISSUE THREAD

**Issue by forteller** [HabitRPG/habitica#5562]
F-droid is the leading app store exclusively for Free and Open Source Software for Android. It would be the most natural thing in the world for Habit, built as FOSS from the start, to be available there.

I want to use the app, but I don't want to connect my phone (my pocket computer that knows everything about me and a lot about my friends) to Google. Today that means that I can't use the app, because Google Play Store is the only place to get it.

Here is the information on how to submit an app to F-droid: https://f-droid.org/contribute/

I really hope you will be able to do this soon! Then you will also make HabitRPG known among a lot of people in the open source (development) community.

Thank you!

**Comment by Shadow53** [comment]
I fully support this plan. I'm in the same boat, with F-Droid as my only app store and a couple of apk downloads from the official sites of apps not (yet) in the F-Droid repos.

I have already opened a submission request in the F-Droid forums. There are no responses as of this comment, but you can find it [here](https://f-droid.org/forums/topic/habitrpg/). It would be really awesome if you guys could just put together a build recipe for F-Droid to use following their guidelines. I would do it myself but I know nothing of developing for Android...

Please and thank you!

**Comment by Alys** [comment]
We're currently creating a new, native Android app, called "Habitica" rather than "HabitRPG". The old HabitRPG app will remain available for a while but will be deprecated and unsupported except for necessary bug fixes for significant bugs. Hence the old HabitRPG app should not be made available in the F-droid store.

I think it would be nice if the new Habitica app does become available there, but please be aware that the developers currently working on it have other responsibilities as well and might not have time to do it themselves. After the app has been released, its source code will be released as open source, and that would be a good time for any developer to build it for F-droid.

I'm going to close this request now, but I'd encourage you to open a new one when Habitica for Android is released. It will have its own github repository, so the issue can be logged there. A BountySource bounty can be placed on it if you desire, to encourage a developer to work on the project. If you keep watching the Habitica website's Bailey news announcements, you'll find out when the new app is released and what the location of its repository is.

**Comment by Alys** [comment]
@Shadow53 Could you please add a comment to the [F-droid HabitRPG topic](https://f-droid.org/forums/topic/habitrpg/) to link back to my previous comment?

**Comment by Shadow53** [comment]
@Alys Will do. I'll also add the link to [news about the new app](https://github.com/HabitRPG/habitrpg-mobile/issues/385) to the F-droid topic for others to follow. Thanks for the feedback.
