### ISSUE TITLE
Change the Group Leader back to me

### ISSUE THREAD

**Issue by Awesumpunk** [HabitRPG/habitica#5567]
Late last week, I over-reacted and thought that I would be leaving Habit (which I am not) and changed the group leader of my party from me to someone who hasn't been on since June 11th.  RileytheWizrd (the current "group Leader) has only been on twice since I added him in November 2014. I would like to have the Group leader changed back to me, so we can Quest again.

**Comment by Alys** [comment]
11 June is only about three or four weeks ago, which isn't long enough for us to consider RileytheWizrd inactive. They might be on holiday or in hospital. Send them a PM to ask them to come back and change the leader to you. If they haven't done that in a couple of weeks, post here again and we will look into it further. You'll need to supply your UUID and Group ID (go to Help -> Report a Bug and look at step 6 for information about how to find them). I'm closing this in the meantime, but we will be emailed as soon as you comment and we can then reopen this.

We are generally reluctant to modify parties prematurely because often internal party communications can fix problems. In particular, regarding changing the party leader, there's usually no urgency because the only functions of the leader are to change the party name and message. Sometimes the leader is the only person who can create challenges, but we can change that separately - reply here now if that is a problem.

Any party member can start quests.

**Comment by Awesumounk** [comment]
Alys, He still hasn't been on.

**Comment by Alys** [comment]
Please read my earlier response. We can't help without additional information from you. I'll reopen this when we have that.

**Comment by Awesumounk** [comment]
What info do you need from me?

**Comment by Alys** [comment]
The IDs listed in my earlier response. Please read it for details.
