### ISSUE TITLE
Gibberish code (Math.floor(user.stats.exp) etc) on homepage / tasks ... again

### ISSUE THREAD

**Issue by Thor333** [HabitRPG/habitica#5568]
Hi guys,

I had the bad experience of bug #5473. (https://github.com/HabitRPG/habitrpg/issues/5473)
 I deactivated the anti-ads plugins, and i was back to normal.

But this time the bug stays! I tried to clear cache and all, to deactivate plugins, to use privacy mode (firefox), i used opera... and always the same stuff.

Only the orange and the red bar, my avatar in snowman and in starfish...
And those great formulas...
{{Math.ceil(user.stats.hp)}} / 50
{{Math.floor(user.stats.exp) | number:0}} / {{Shared.tnl(user.stats.lvl) | number:0}}

Any one has an idea?

(i can't have access to https://habitrpg.com/#/options/settings/api to give my ID, gibberish always...)

**Comment by Alys** [comment]
We'd like to know if there are any console errors happening in your browser. Here's a guide for how to open the console in Google Chrome: https://developer.chrome.com/devtools/docs/console. You can google how to do it in your preferred browser, but Google Chrome gives the best information. Let us know if you need help using the console. Once you have it open, please reload the site and then paste here all text that you see in the console.

**Comment by SamLefebvre** [comment]
Hello, I came here to say I have the same problem since yesterday.
Here is what I have in my console in Google Chrome (and the same thing in Opera)

Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 75-76 ['] in expression [variant < 2 ? 'Combattez des Monstres aux côtés d'Amis' : 'Inviter des amis'].
http://errors.angularjs.org/1.3.9/$parse/lexerr?p0=Unterminated%20quote&p1=…20Monstres%20aux%20c%C3%B4t%C3%A9s%20d'Amis'%20%3A%20'Inviter%20des%20amis'
    at app-dd587cf9.js:4
    at fd.throwError (app-dd587cf9.js:6)
    at fd.readString (app-dd587cf9.js:6)
    at fd.lex (app-dd587cf9.js:6)
    at hd.parse (app-dd587cf9.js:6)
    at o (app-dd587cf9.js:7)
    at k (app-dd587cf9.js:6)
    at ea (app-dd587cf9.js:6)
    at R (app-dd587cf9.js:5)
    at N (app-dd587cf9.js:5)(anonymous function) @ app-dd587cf9.js:6

https://habitrpg.com/partials/main.html Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ghost** [comment]
Same results for me here (using Firefox and IE11) since yesterday

**Comment by Alys** [comment]
@asouini is your browser's console displaying exactly the same thing that @SamLefebvre reported in the comment just above yours? If not, can you please paste the contents of the console here? See my first message for information about using the console.

**Comment by Alys** [comment]
@Thor333 and @asouini are you using HabitRPG with the language set to French?

@SamLefebvre It looks like the problem might be just with some bad French language strings. This might work if you are willing to do it: Set your PC or mobile device to use English rather than French, then try using HabitRPG again. If your device was already set to English, and you had French chosen in HabitRPG's own settings, try opening HabitRPG in a browser you haven't used it with yet. If your language is set in HabitRPG and you can't change it because you can't use the site, tell me your exact HabitRPG username or email address - if you don't want to display it publicly, email it to admin@habitrpg.com.

@Thor333 and @asouini if you are using French, try these ideas too.

**Comment by SamLefebvre** [comment]
Thank for the reply @Alys, yes my HabitRPG language is in French. 
I set my browser in English, but when I login, my default language is French and the website go back to french, then the same error. I have send you the email with my username.

**Comment by Alys** [comment]
We think we have either a workaround that we can apply to everyone or a proper fix. We're testing both at the moment. Hopefully it should be back to normal soon.

**Comment by Thor333** [comment]
Yep, i use everything in French.
I changed my favorite language to English, but it doesn't change the bug.
Waiting for the fix! :-)

**Comment by paglias** [comment]
@Thor333 @SamLefebvre @asouini we've just pushed a fix for this, if you reload the website it should work. Let us know if it doens't and sorry for the problem!

**Comment by SamLefebvre** [comment]
@paglias It's work ! Thank you !

**Comment by Thor333** [comment]
Yup, same here! Thanks guys!
