### ISSUE TITLE
Newly created items are automatically assigned a tag

### ISSUE THREAD

**Issue by orschiro** [HabitRPG/habitica#5575]
Hi all,

I am not sure whether the following is intentionally chosen or a bug. 

Please have a look at the following screenshot for a reference: 

![image](https://cloud.githubusercontent.com/assets/170947/8568631/cc508348-256f-11e5-89e6-f74613435253.png)
1. The to-do that is being created is automatically assigned the tag `Pomodoro Break` because this is the currently selected tag. 
2. I find this behaviour very disturbing. It prevents me from quickly adding a new item unrelated to the tag I am currently working. 

Is this a feature or a bug? If the former, is there any way to customise this behaviour?

Thankfully,

Robert

**Comment by Alys** [comment]
This is a deliberate feature. Players often find it useful to select a tag first and then add an item, because that's faster than adding an item and then editing it to tick the tag. 

There is no way to customise it, but you'd be welcome to request that feature. The best way to do that is from the HabitRPG site's Help menu. Select "Request a Feature" and then follow the instructions you'll see.

**Comment by orschiro** [comment]
Thanks for clarifying @Alys!

I might consider submitting a request but first try to adapt to this workflow a bit more. 

Thankfully,

Robert
