### ISSUE TITLE
Amazon error: Blocked a frame with origin "https://habitrpg.com" from accessing a frame with origin "https://payments.amazon.com". Protocols, domains, and ports must match.

### ISSUE THREAD

**Issue by Kristijan22** [HabitRPG/habitica#5582]
So I just finished a quest where the prize was I think 350 exp. And I only need a total 330 to level up. Now I have 600 exp and I'm still level 14.

User id: 591d2aff-0898-49f3-99f2-76800ef96740

I got 2 javascript errors in the console
-Uncaught ReferenceError: cxApi is not defined
chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2 Uncaught 

**-SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://habitrpg.com" from accessing a frame with origin "https://payments.amazon.com". Protocols, domains, and ports must match.**

**Comment by Alys** [comment]
Hi @Kristijan22 . Please see the information at the top of this issue : https://github.com/HabitRPG/habitrpg/issues/2433

The first error you found in the console isn't related to HabitRPG; it's from one of your extensions.

The second error is from a new payment method and isn't related to leveling up. We'll look into that though because it might be important for other reasons. I'm going to change the title of this issue to match. Thanks for letting us know about it!

**Comment by Alys** [comment]
@paglias FYI  This error has been reported:
SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://habitrpg.com" from accessing a frame with origin "https://payments.amazon.com". Protocols, domains, and ports must match.

**Comment by paglias** [comment]
@Alys this could be due to an extension, I wasn't able to replicare it. But anyway it's not anything important
