### ISSUE TITLE
Quest frozen

### ISSUE THREAD

**Issue by charzooka** [HabitRPG/habitica#5587]
I started the egg hunt quest three months ago on my own and made steady progress for a month up to 79 eggs and then it froze. I haven't been able to make find eggs since. I tried to cancel it and start a new quest and the new quest disappeared and I'm back to the egg quest. I'm happy with either one, so long as I can make progress! What's happening?

**Comment by charzooka** [comment]
User id: 419b2544-c0ad-4f56-829d-eee11dea1bd6
Party: 4bca0aac-0826-4e77-b9e8-efe5ef024e8b

**Comment by charzooka** [comment]
Is it because my "sleeping" friend joined the party after I'd started the quest?

**Comment by Alys** [comment]
Sorry about this @charzooka! Your account actually existed in two separate copies of your party, something which isn't supposed to happen but is a rare bug that we see occasionally (not due to your friend joining). You were getting inconsistent quest behaviour because each party had a different quest status.

I've deleted the non-Egg-Quest party, which means that everything should behave normally now. Please reload your party page and tell me if anything doesn't look right. 

Because you stopped being able to make quest progress, you're further behind on the Egg quest than you should be. Would you like me to increase the number of items collected by an appropriate amount? It's an easy thing for me to do. If you'd like me to, just tell me how many collected items to add.

**Comment by charzooka** [comment]
Thank you for replying so quickly, Alys! The party page looks the same as it did before, but I'm not sure what would have changed. I haven't found any eggs over the past day or two, if that helps. I have been completing dailies and habits. 
Hmm. Going by the rate that I was accumulating eggs before the bug I'd probably be done with the egg hunt by now, but let's just add all but five eggs so we can confirm that it will add eggs correctly so that we know that it's working right? Or should we just complete the egg hunt and I'll start with a new quest and test it out that way?
Thanks so much for your help!---Charlotte

```
  From: Alys <notifications@github.com>
```

 To: HabitRPG/habitrpg habitrpg@noreply.github.com 
Cc: charzooka net_chark623@yahoo.com 
 Sent: Friday, July 10, 2015 7:32 AM
 Subject: Re: [habitrpg] Quest frozen (#5587)

Sorry about this @charzooka! Your account actually existed in two separate copies of your party, something which isn't supposed to happen but is a rare bug that we see occasionally (not due to your friend joining). You were getting inconsistent quest behaviour because each party had a different quest status.I've deleted the non-Egg-Quest party, which means that everything should behave normally now. Please reload your party page and tell me if anything doesn't look right. Because you stopped being able to make quest progress, you're further behind on the Egg quest than you should be. Would you like me to increase the number of items collected by an appropriate amount? It's an easy thing for me to do. If you'd like me to, just tell me how many collected items to add.—

**Comment by Alys** [comment]
@charzooka I've bumped up the quest progress to 95.

I actually hadn't set up everything needed in your account for the collection to work properly for you - sorry about that! That's why you haven't found any eggs over the past couple of days. However it should be right now. If you haven't found eggs after your next cron, please post again here!
