### ISSUE TITLE
Enable New Relic again

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5592]
New Relic has been disabled since we found out ti was the cause of the memory leak.

@gisikw it seems that this might not apply to io.js https://github.com/joyent/node/pull/9064#issuecomment-119304596, we might try to switch to it in future

And also move `newrelic.js` in subfolder
##

**Comment by tobyfee** [comment]
I used to work at New Relic and am still pretty tight with the Node team. Tons of memory leaks have been fixed in the last year that the agent caused, and for sure changing node versions (or to io.js) will alter behavior. Can I help getting this off the ground?

**Comment by wraithan** [comment]
New Relic node agent engineer here: https://discuss.newrelic.com/t/an-update-on-memory-management-in-node-js-perception-vs-reality/31934 is worth mentioning.

Was looking at this project to contribute while I'm on PTO since it is node-y. I noticed in https://github.com/HabitRPG/habitrpg/commit/8ea69e90dd4c72ce41d82492ceb8fb9ed2ddc794 @paglias re-enabled the node agent. Unfortunately it is pretty late in the initialization process. We prefer the agent to be required before anything else. Similar to how `require('babel-core/register')` in `website/src/server.js` works, we hook into the module loader to be able to observe your application.

Ideally, we'd be on the line before `require('babel-core/register')`. Since the babel hook is only concerned with loading new files that contain es6 code, requiring the newrelic agent before the babel hook will not negatively impact babel ability to do it's job to the best of my knowledge, but will make sure any core libs that babel requires get instrumented correctly.

Also to moving `newrelic.js` to another folder can be achieved using `NEW_RELIC_HOME` and setting it to the dir that contains the `newrelic.js`. Another option is to go with pure environment variable based configuration.

**Comment by crookedneighbor** [comment]
Thanks for this info. We're in the process of upgrading to node v4 so we can re-enable New Relic. The current blocker is mongoose v3, which falls back to the js driver instead of using the native driver. We're going to try to upgrade to mongoose v4 so we can upgrade node as well, but so far have had trouble with stability.

**Comment by crookedneighbor** [comment]
Closed by https://github.com/HabitRPG/habitrpg/pull/7011
