### ISSUE TITLE
Free rewards (or severly discounted) for a certain time after extremely stressful events [suggestion]

### ISSUE THREAD

**Issue by derekantrican** [HabitRPG/habitica#560]
I'm a college student and tests can be pretty stressful (especially finals). I currently have a "Take a Test" Habit for getting rewards from simply taking tests, but I think it needs to go a step forward. Because I need to get better at logging EVERYTHING in HabitRPG, here is my proposal:

I think there should be a certain time limit that activates after a certain event/Habit (e.g. Taking a Test, giving a big presentation, etc). The time limit should be something like 3 hours or so where all the rewards in that time limit are free and don't take off of your gold amount (or are at least discounted to something super cheap like 10%). That way, you can relax and play video games or watch tv episodes to destress with no guilt about not logging it on HabitRPG.

Misc sub-ideas: 
- It'd be cool if this activated with a time limit of the entire day for special holidays like birthdays, christmas, etc
- For "full day" activations, it'd be nice to also set a "temporary vacation" status (http://goo.gl/qAVoF) where there is no penalty for not doing dailys
- It'd be cool if there was an option for "use this now" or "save it for later"
- Based on the above sub-idea ^ it'd be cool if this was giftable to others. Maybe some people might not activate it for themselves, but people could send it to others (by saving their own or buying one with tokens/gp) if they saw someone was having a particularly bad day. (See my other suggestion at #559)

**Comment by wc8** [comment]
There's something about this and the non-work hours reward discount idea that resonates. 

What types of tasks would qualify for the reward discount/free period?
- completion of a checklist?
- High Priority?
- old tasks?
  • or maybe a combination of the above?

If Supertask gives you free rewards for X hours, it should not give you GP. Otherwise you're basically being "paid" twice. 

#556 related to birthdays sub-idea

**Comment by derekantrican** [comment]
Yeah, I agree that "supertask" (I like the naming btw) shouldn't give you GP (or even necessarily xp for that matter). It's pure and only reward should be a "reward spree for X hours". 

As far as what a "supertask" should be:
- I think it is user-defined just like a regular task (this requires that people have integrity and don't cheat the system)
- High Priority- maybe, but I usually think of the priority tiers as multiples of each other i.e. low=1x usual amount of reward, medium=2x, high=3x, or something like that (or is that not what the priority system is evolving into right now?)
- Maybe the Goals (see http://goo.gl/VU3of) consisting of subtasks or a certain time "streak" of completing a task
- This could also be a result of the "Skill level up" (see http://goo.gl/YEcxt). As I mentioned in the comments on that card, it might be so great of a reward that it requires no xp/gp is gained for "skill tasks" until the level up event (aka, practicing guitar only gives you "skill xp" until you level up your "skill". Then you get the "reward spree for X hours")

**Comment by wildcate** [comment]
How about linking a special reward to a task on the to-do as an option? When making a task, you could opt to make it a special reward task, which would negate gold and xp for that task and give you the custom reward (like "take a day off and play video games all the time") - would that work for your idea? As far as I understand it, you would want to have a certain timespan as "off" time. Then you could just reward yourself with "take x hours off and have fun!" as a special reward, with no need to manipulate the reward costs or system in habit.

For whole days off, there will be the "rest in tavern" option that you can turn on (see https://trello.com/card/rest-in-tavern-vacation-button/50e5d3684fe3a7266b0036d6/14) so you could use that to cash in your custom reward of a full day off.

As for the holiday idea - I tend to take holidays off anyways, so I plan to just use the normal rest-in-tavern function for that. Birthday-wise I think that everyone should decide for themselves whether to have extra free time as a birthday treat or not. Since I tend to either work on my b-day because there are things that need doing or take the day off anyways (usually to do other things, like prepare food for having friends over), having a "free reward allowance" would not work out for me either way. Plus birthdays are not seen as of the same importance across all cultures/religions. Personally, though, I would totally appreciate some small flavour item drop on one day (in my case it would be the birthday), like maybe some pet food or a funny hat or a flower. That would also not really mess with the gold/xp system. For something like that, perhaps users could be given the opportunity to state "your special day" upon registration, so they can put in their birthday, name-day, wedding date, high holiday, whatever - a day that holds a special meaning for them and that would result in a little something from Habit.

**Comment by derekantrican** [comment]
@wildcate I agree with everything you just said! I think that a habit/todo should have a clickable option for "supertask" that would work just like you said. While I kinda prefer my own idea for holidays over the tavern idea (creator's bias) I'm willing to compromise. The main thing is I still want to see a count-down timer for free (or discounted) rewards  (and the ability to save the "reward  streak"  for later use, though that may wait if need be)

**Comment by Pandoro** [comment]
After reading through the thread, I must say I am very sceptical. 

I am a student as well, and I completely understand where you are coming from. After a test, you just feel dead. I want to relax, not do anything at all... BUT, the stuff that would need to be done, should still be done. Nothing really changed, you should still do your exercises, you should still clean your room, you know, the general stuff you wanted to get better at by using HabitRPG. This feature would clearly go against that whole idea and thus I am wondering if we really want to encourage this behaviour. 

Furthermore my "too easy to cheat with"-bells started ringing. How is an average user going to decide which stuff he or she wants to be a supertask? I think I would be very tempted to just have some important task each day a supertask status and boom :D Every day I get cheap rewards. I think this is just cheating yourself in the end. 

Regarding the birthday, holiday and other special days, I would really say that the Tavern will work fine for this. People will have to decide for themselves on which days they just don't want to track anything. Especially since some days are more important to some than they are to others. I don't think a christian person will feel like not tracking anything during ramadan and a muslim will probably not celebrate christmas as a christian would. 

I get the idea that these tasks which should be supertasks, could just as well be tasks with a very high priority. This would result into getting a big reward based on that task and then you could also buy some custom reward, like 3 hours of gaming. So instead of making stuff cheaper after a supertask, you could just give the supertask a bigger value. This is by far easier to implement. It is easier to understand and yes, it does not fix the cheating, nor does it make you invulnerable to uncompleted stuff. But as I said, I wonder if this is something that should be there at all. 

Discuss :D

**Comment by wildcate** [comment]
@Pandoro I can see how the temptation could be there... but for me, it would be no different from the temptation to make a reward just very, very cheap. I think it would be a good possibility also for those folks who want to tie a special reward to a special to-do, which they don't want to put into the list because it is the special extra "dangling carrot" to that task. This would also mean you would not need to guess the right amount of gold for that task (you might be able to afford it earlier, or not able to afford it after finishing the task); while higher priority would give more yield to that task, it's still not a guarantee that the guessed amount of gold will work out. 

I think tying rewards or reward classes to specific tasks has been requested by a few people already, it also sort of overlaps with the wish for multiple currencies or similar systems (a to-do like "eat healthy during all the week" could be tied to "cream cake on the weekend", for example). It could probably be implemented as an opt-in possibility for those who do want it.

@lefnire On that note, have you thought about making elements discussed as opt-in things available through spending tokens? That way, a basic version of Habit could be all free, but special options not strictly necessary for running it (such as this special reward thing, things that would possibly clutter up the interface such as multiple checkboxes/extra completion buttons for dailies, or others of the more disputed options) are available as buy-ins through spending tokens. I could imagine that this would be a good way to get some money for the project, and at the same time users could have some options integrated as soon as they want them or feel they have a need for them, without figuring out from the developer's side when to introduce them through the leveling system. It would also mean that the temptation to cheat/use an option just because it's there, and available, will be reduced. It's probably much less strong a temptation for most folks if the option has been bought beforehand. And with moderate pricing for all the options it will keep the options accessible for everyone. I would totally buy the checklist if it were not one of the Kickstarter thingies ; )

In the end, everyone has to figure out how to handle the reward system, and how not to keep from cheating - but cheating will always be possible even though the only one who'll get hurt by it is the cheater.

My turn to say "Discuss" ; )

**Comment by derekantrican** [comment]
@Pandoro I totally understand what you're saying. Quite possibly there
could be a "refresh" limit preventing this from being used every day.
Something like a "once a week" refresh limit.

-Derek

deltamu.com

Philippians 1:18,20-21

**Comment by wildcate** [comment]
I don't really see the need for a refresh limit when it is just a task linked to a specific reward - maybe we should not call it "supertask" though, but "special reward" task. The special reward can be something as simple as a fancy coffee, after all - a fancy coffee that is only available after doing, say, the washing-up.

And I think cheating with a special reward task will be just as likely, or unlikely, as setting your custom rewards at ridiculously cheap prices - such as an afternoon off for 3 gold ; )
If the "special reward task" gains you neither gold nor XP it's also a discouragement, in my opinion, to use it too often, since you will probably want to level up at some point.

**Comment by derekantrican** [comment]
@wildcate I see what you're saying here. The only thing is, the original
idea for the "special reward" would actually be for a discount on all
rewards. So everything that you usually spend coins on, is free (or really
cheap) for a certain amount of time. A special reward of "fancy coffee"
could just be a coin-based reward (in the same area as all the regular
rewards). But I see what you're saying: Link specific tasks with specific
rewards. That might require its own thread (or you could just only reward
yourself with that reward when you're finished with that task).

I was thinking a refresh limit might be necessary because if a user gets
"free rewards for X hours" on a specific task, that task shouldn't be
activated every day because it would defeat the system. Though I do see
what you're saying about how people might not be likely to cheat themselves
because they could just set all their rewards cheaper.

-Derek

deltamu.com

Philippians 1:18,20-21

**Comment by Pandoro** [comment]
@wildcate task bound rewards are something you can easily do yourself. Just write it in the task. Nothing different would really happen if it would be "implemented". Since you don't get gold to buy a reward, doing a task would just mean you can do the reward action right away. So the only thing one would maybe need is some kind of pop-up message to remind you of the reward upon completion. 

For resting after a special thing, just go to the tavern I would say. I cannot really see the added benefit of automatically going into break mode after doing something. It needs more implementation and if you feel like doing so, you can just click it, while if the task was easier than expected, you could just go on with your daily life and get some more stuff done. 

@derekantrican Regarding the cheaper rewards. This should not affect ingame items, so it will only be based on your custom rewards. Seeing you explain a little more, I can somehow understand this feature. If it would be limited to once a week (or something like that), there would be an actual ingame way to have some relax-time. This, without the need to make up extra rules for it. I am still wondering if this is really something you would want to encourage as a behaviour. Life is not going to stop because you do a test or something :p So Why would habitrpg give you a special break for this? But I can understand what you mean. I guess the only real reason you want this, is because you want to track everything in habtirpg right? Without making additional real life rule adjustments?

**Comment by derekantrican** [comment]
@pandoro Pretty much. I mean, I could just not charge myself for those
rewards after a test, but I thought it'd be cool if I could track it in
habitRPG. And I understand life goes on (dailys must still be done along
with the encouragement for other tasks) so this is not to excuse those
other things. It just provides a short break afterwards. Not a long break
like "5 hours", but I was thinking something more like "1 or 2 hours". A
certain amount of time where the break could be helpful to destress but not
so long that it overlaps other things like homework or projects.

-Derek

deltamu.com

Philippians 1:18,20-21

**Comment by Pandoro** [comment]
Please navigate to [the trello card](https://trello.com/card/special-tasks-that-give-extra-conditions-upon-completion/50e5d3684fe3a7266b0036d6/210) and vote for it there.

I tried to summarize a little, but let me know if I said something wrong, or should say something better. I explicitly did not at the invulnerability to damage idea, because I think the "life goes on" thing is actually true. Furthermore if it is time based, it is not very likely you would get damage from unfinished things, as this only happens during the day change.

**Comment by derekantrican** [comment]
@Pandoro Looks good to me, thanks! I also like how you eliminated the idea
as a time limit for "free rewards" and instead decided upon "10% of
original price" rewards. That actually gives this idea a purpose for
integration into HabitRPG whereas if the rewards were to be free for a
certain amount of time, the user might be better off just not counting them
instead.

-Derek

deltamu.com

Philippians 1:18,20-21

**Comment by horusofoz** [comment]
Moved to [Trello](https://trello.com/card/special-tasks-that-give-extra-conditions-upon-completion/50e5d3684fe3a7266b0036d6/210).
