### ISSUE TITLE
Dailies Restarting too early to finish all of them

### ISSUE THREAD

**Issue by xeraelia** [HabitRPG/habitica#5610]
My dailies have been restarting way too early for me to complete all of them, theyve been restarting at 7pm every day which is annoying because they used to restart at 12am for me. Either I dont tick some off when I do them and I plan to tick them off later in the evening or I do those things later at night. Is this a bug or can I easily change this??

User ID - a795167e-7b8d-45a1-8e77-8455fb7e51d6
I am using Windows OS and the Google Chrome browser.

**Comment by Alys** [comment]
FYI devs: xeraelia's Custom Day Start is 0.

xeraelia, can you please check the time and timezone that are set on your PC or mobile device to make sure it is correct?

What time of day do you typically start using HabitRPG?

What timezone are you in (this is unlikely to make a difference but I want to be sure). Please tell us the timezone in terms of UTC +/- n hours, rather than by a local name for it.

**Comment by xeraelia** [comment]
My timezome must have changed when i reset my whole computer, thanks it was on US time instead of NZ time :/ I changed it back to UTC +12:00. Thanks so much :)

**Comment by Alys** [comment]
No worries. Easy fix. :)
