### ISSUE TITLE
Android app urls aren't hyperlinks...

### ISSUE THREAD

**Issue by isaact-d** [HabitRPG/habitica#5615]

**Comment by Alys** [comment]
Can you please give some details about what is wrong? For example, where do
the URLs appear, do they look like URLs but not work like them, or do they
look corrupted, what happens when you try to click on them (nothing or a
freeze or a crash or something else)? If screenshots would help to
illustrate the problem you're seeing, please drag them into a comment here
(attaching to an email won't add them to the issue).

**Comment by isaact-d** [comment]
Sure so there are 2 problems one on the on the android app hyperlinks are like normal text and don't link and on the website clicking the link should open in a new tab atm clicking the link opens the url in the same tab so you lose where you were in habitrpg

**Comment by crookedneighbor** [comment]
@isaact-d I assume you mean links in chat messages and task notes, correct?

**Comment by isaact-d** [comment]
Yes

**Comment by lemoness** [comment]
We are currently rewriting the Android app from scratch, so I am going to go ahead and close this ticket, since we are only updating the old app for critical bugs. If there's still a problem after the new app is launched, we can file a new one in the correct repo.
