### ISSUE TITLE
Option to edit messages on guild board

### ISSUE THREAD

**Issue by isaact-d** [HabitRPG/habitica#5617]

**Comment by Alys** [comment]
Can you please describe what is wrong or what behaviour you'd like to see?
Note that if this is a request for a new feature, it should go through Help
-> Request a Feature, rather than here. Github is for reporting bugs with
existing features.

**Comment by isaact-d** [comment]
If it functioned more like a facebook fan page it would be great. Option to comment on a users post instead of pm and if you make a post having the option to fix a spelling mistake is always nice too

**Comment by isaact-d** [comment]
Yeah I will just nothing seems to happen on the trello board there are feature requests that should have been vetoed need something like https://www.uservoice.com/

**Comment by isaact-d** [comment]
This page we are using now has all the features that HabitRPG needs I bet there's a git with code for this purpose

**Comment by Alys** [comment]
We are planning to make large changes to the messaging system. Please add your ideas to Trello so that they can be considered along with the other suggestions we've had. The Trello board is monitored and used by staff and developers when planning site changes. We don't respond to every comment but we do read them all. We tend to not respond negatively to suggestions that might initially seem like undesirable ideas because changing circumstances can make them desirable and/or they might trigger additional related ideas from other players.
