### ISSUE TITLE
XP required to gain a level just changed?

### ISSUE THREAD

**Issue by ZdenkaWaldner** [HabitRPG/habitica#563]
I'm at Level 3, with 64 XP. I could have sworn that I only had about 11 points to go to gain a level -- but now it's saying 64/200. Is that correct? Am imagining things? I know I didn't just gain a level because my HP didn't reset.

**Comment by Pandoro** [comment]
The exp system has been revamped. You need more exp, but you will also get more exp for completing things. I think this wass just pushed this to the live server. 

Sorry for the inconvenience regarding the "lost" value of your so far earned exp. If this is an issue for you, feel free to restore your character to the same "percentage" of gained exp in your current level. (Using the restore your character button in the settings menu.) 

See the blog post for more details:
http://habitrpg.tumblr.com/post/44468869138/custom-day-start-better-algorithms-auth-enhancements

@lefnire We should probably make this banner thing on the site, so people know what just happened!

**Comment by ZdenkaWaldner** [comment]
Oh, okay! Good to know it's on purpose. :)  It's only a problem because my XP are running very low and I thought I would be all right since I was gaining a level soon. But I guess I can buy a potion or something.

**Comment by tropister** [comment]
erm yes, some banner would be much appreciated since I got very confused: throughout the day I got my usual 1 or 1.1 XP and now by clicking on 2 different habit tasks suddenly I get not only some 10XP or so but also the points went from 100 to 200 sth to 380. So I seem to have leveled up, but the health points were not reset which adds to the confusion (especially since the ratio went from 41/100 to now 62/380 points).

Overall I agree with the changes, but maybe next time put out a warning first or alternatively implement a random heart-attack villain ;)

**Comment by Pandoro** [comment]
@ZdenkaWaldner  If it is a problem, you can go to Settings -> scroll down -> restore -> there set a higher exp value. 
Say you needed 11/80 exp, you needed something like like 13%, so if you set it to 0.87*max_exp of your level, you will be back to the previous value.

**Comment by lefnire** [comment]
in-game notifications of new features it is, next time. Sorry about that guys!
