### ISSUE TITLE
Join Tavern Guild Error

### ISSUE THREAD

**Issue by AegisOmega** [HabitRPG/habitica#5638]
The following error is reported everytime when I try to join the "Tavern" guild. 
"Fehler Runner error: Overflow sort stage buffered data usage of 36128371 bytes exceeds internal limit of 33554432 bytes" 
Somehow I'm in there now... why isn't everyone by default in this guild?

**Comment by hairlessbear** [comment]
I think I know what's going on; I believe this is the same as #5303. I'm going to guess that you're using the HabitRPG chat extension, and that you're getting to the Tavern by clicking on it from the chat extension. When you do that, the URL is  `https://habitrpg.com/#/options/groups/guilds/habitrpg` instead of what it's supposed to be (`https://habitrpg.com/#/options/groups/tavern`). This causes the app to assume that the Tavern guild is identical to any other guild, and it processes it using this assumption. Since the Tavern guild is a special guild, it requires special processing, so this assumption leads to some strange effects, such as seeing a join button that doesn't work. 

The problem can be avoided by getting to the Tavern by clicking the Tavern button in the app instead of the chat extension.

**Comment by Alys** [comment]
@AegisOmega : hairlessbear is correct about what's most likely happening. You might also be seeing the Tavern in the list of guilds.

The Social menu is the best way to get to the Tavern and won't cause this error.

Since we're tracking this bug in the issue hairlessbear linked to, I'm closing this issue, but you're welcome to comment here if you have any questions.
