### ISSUE TITLE
"Can't send message to this user" - SOLVED

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5641]
A few days ago I receive a PM message from a user in my party, since then I cannot send anything to this user, the error message appear always I try "Can't send message to this user". The user confirmed he hasn't changed anything in his settings.

I have tried to send a PM to myself to check and that is working correctly.

Edit: Not a bug, I have blocked the receptor of the message accidentally.

**Comment by Alys** [comment]
It's likely that the user has either deleted their account or has opted out
of the PM system.

Try clicking on their name - if it tells you there's no such user, then
they've deleted their account.

If they've opted out of the PM system, there's nothing that can be done.
They've chosen to not receive PMs.

It's also possible that they've blocked PM  from you, maybe by accident.

Since they're in your party, you can put message in party chat for them,
although they might not see it if they don't read chat often.

**Comment by crookedneighbor** [comment]
One of the scenarios Alys mentioned is certainly the reason why. Here's the code where it happens: https://github.com/HabitRPG/habitrpg/blob/39cb9bfb990d883a794cdc4d514aff6765c0b0c8/website/src/controllers/members.js#L59-L62

@agroboy If you think something is still not right, please re-open the issue.
