### ISSUE TITLE
Leveled up and lost all my gold

### ISSUE THREAD

**Issue by MarchingBlankets** [HabitRPG/habitica#5665]
Hello,
I just leveled up, but instead of gaining gold, I lost everything!

**Comment by Alys** [comment]
I took your User ID (e1536063-eb67-4efc-83b7-8eefb48654f0) from your same comment in the Tavern. For any other bug reports, please include your User ID here so that we can find it easily.

You're on a boss quest and a party member did enough damage to kill you. That's what caused you to lose all your gold. It might have coincidentally happened at the same time that you levelled up.

If you feel the death was unfair, you can use [Fix Character Values](http://habitrpg.wikia.com/wiki/Fix_Character_Values) to restore your gold.
