### ISSUE TITLE
Surfboard and Sunglasses not showing

### ISSUE THREAD

**Issue by Mr-Operator** [HabitRPG/habitica#5667]
My HabitRPG name is Ecks. My character has the Surfboard and Sunglasses for the July mystery item for members. 

Even when I uncheck everything I'm wearing, they still will not show (yes, I am using the "costume" option).

**Comment by Alys** [comment]
Please reload the website once or twice. That will make them show up there.

If you're on a mobile app, they might not show up for a few days due to the need to wait for Apple/Google to approve changes.

I'm closing this now because reloading the site almost always fixes temporary problems like this (basically, your browser hasn't yet downloaded the new images and a reload forces it to). 

However if it doesn't work, we can reopen this. You'd need to provide your User ID -- go to Help -> Report a Bug and see step 6.
