### ISSUE TITLE
URGENT: Error message after finding a quest, now cannot update ANYTHING

### ISSUE THREAD

**Issue by Airova** [HabitRPG/habitica#5670]
I completed a task and found a quest as a reward. The quest opened up in its own little popup so I could read it. I clicked "do it later" or whatever, because I'm already on a quest. Then I noticed that there was an error message instead of a drop message: "Please reload, "Error Cannot set property 'drop' of undefined" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages."

I reloaded the page and tried to complete a task, but I got the same error message again. I tried reloading again, and it reset to how it was before I tried completing the task. Basically, no matter what I do now, it doesn't sync with the server. I just get that error message and nothing gets saved. I can't complete dailies, I can't do ANYTHING, nothing gets saved.

**Comment by Alys** [comment]
@Airova I took your User ID from your post in the Tavern (4f7694ac-30f7-4549-86f6-a81dcbcc5363), but if you need to report bugs in future, please include the ID. If you don't know how to find it, see step 6 in Help -> Report a Bug.

The quest drops at level 60 and you were level 59, so I've increased your level to 60 to stop the quest dropping. Can you please reload the site and tell me if it's working now?

I'm about to check your account to see if you were awarded the quest and if not I'll give it to you, so you should see it in your account in a few minutes.

@SabreCat Could this be caused by anything in https://github.com/HabitRPG/habitrpg/pull/5635 ?

**Comment by Airova** [comment]
OK, I can check off tasks now, but if I try to use a spell (burst of flames) I get the quest drop again and the error message. It seems that it is as you say, I leveled up to 60, the quest dropped, and everything stopped working... :(

**Comment by Alys** [comment]
Sorry about that; there's a flag that I forgot to set. I've set it now and that will tell HabitRPG to not give you the quest any more. Please reload again and tell us if it's still not right.

**Comment by Airova** [comment]
Works now. Thank you very much for the quick assistance! And I see I still have the quest, so that's good news. :)

**Comment by Alys** [comment]
No worries. :) Thanks for letting us know!

Devs:
I couldn't reproduce this on a test account, neither at level 40 nor 60. (This is not to say it's not a real bug, just that it's not easily reproducable.)

@Airova Before this problem happened, do you remember how long it had been since you had reloaded the site, or logged out and in, or closed and reopened your browser?

**Comment by Airova** [comment]
I reload the site regularly, maybe once every few hours, so it wasn't any longer than that. It's been a very long time since I logged out and in. The last time the browser was closed and reopened was a couple of days ago. 

However, I wonder if the issue is that I was already on a quest?

**Comment by Alys** [comment]
Thanks for the reload information. I was wondering if your browser had code that predated a recent change, but it can't have.

I've just done another test with an account that was on a quest, and the quest at level 15 didn't trigger this. This might be one of those inconsistent bugs that's hard to track down.
