### ISSUE TITLE
Android app data overwriting more recent website data?

### ISSUE THREAD

**Issue by shadowhaloedangel** [HabitRPG/habitica#5673]
I do not use the mobile app very often - only when I need to check off my dailies when I am away from the computer. I had not opened the app recently, but did so earlier and then closed it again possibly before it had finished syncing. The result on the website was a to do created at the beginning of the month with a checklist for each day being unticked from the 26th to the 4th, and being greatly reduced in damage - the data display tool shows the damage as -7.32 but with the correct creation date (15.7.2), whereas a task with a slightly shorter checklist created on the 15.7.14 has a damage of -24.12. Obviously since this is a long term to do I have been working hard to gradually complete I would much rather it did more damage and I have no skills which might have reduced its potential. After this I also noticed several dailies had been ticked when I had not ticked them today, and had another look at the app. In the app all dailies showed as ticked (despite the fact that last time I used the app to tick off my dailies none of them synced properly and I caused a lot of damage to my party).

I'm not entirely sure what happened, but I hope that this description helps (and that possibly something can be done to increase the to do value again!)

user id: 834b8c9b-7b95-47f1-bca8-c3e48bb04b23

I use firefox, and the official habit rpg android app
##

**Comment by Alys** [comment]
@shadowhaloedangel I'm very sorry we didn't reply to this earlier! 

The Dailies remaining ticked on one day while causing you damage on the previous day is this bug: https://github.com/HabitRPG/habitrpg/issues/4313
If it happens again, there's an "Advice" section near the top that will help you recover from the unfair damage.

For those two To-Dos, I think when you say damage, you're referring to the task's value? The way it changed sounds like a weird, once-off glitch possibly caused by some sort of corruption introduced by the incomplete sync. I haven't seen any other reports of something like that, so I'm hoping that it no longer occurs (the app and website have been updated several times since it happened). However if you've noticed it happening again recently with other tasks, please tell us and we'll reopen this!
