### ISSUE TITLE
When Unchecking Dailies, Checkmark Remains

### ISSUE THREAD

**Issue by janetmango** [HabitRPG/habitica#5682]
This has been a recent development (last 3 or 4 days?) that when I uncheck a Daily (usually a Wishing Well Daily), the checkmark remains until I sync or mark another task. When unchecking, the XP, gold, and mana all reverse correctly and it will turn back to blue if it's a due Daily, but the checkmark remains which makes it difficult for me to quickly tell if it has been completed or not. 

UserID is d075dca7-01ed-4666-ae2d-22feef18c7bc

This occurs in both Firefox and Chrome browsers

**Comment by Alys** [comment]
Confirmed in Chrome on Mac OS, although the tick mark disappears as soon as I click on something other than the task, like the page background.

@blade @SabreCat Do you know of any changes in the past few days that might have caused this?

**Comment by crookedneighbor** [comment]
This is related to the recent change to make tasks keyboard accessible. Basically, when a checkbox input is in focus state (such as selecting it with the tab key, vimium, or just checking or unchecking it), it'll show the check mark on the task. This is to show the user which task they are on. An unintended side effect of this is that when you uncheck a task, it puts the focus on that current task. The task itself is _not_ checked off, but since the focus is on the task, it appears to be.

A better solution would be to have a different kind of indication that your focus is on the that particular task. @lemoness @AnitaYCheng Any ideas? Should it be a separate icon? Or a border? or something else?

**Comment by lemoness** [comment]
A border might work, although it should be thin.

**Comment by crookedneighbor** [comment]
@lemoness a border looked funny to me. I ended up making the background slightly darker. Just noticeable enough to a user when tabbing through the tasks.

**Comment by Alys** [comment]
Once it's live, we should check if the darker background is noticeable to users with visual impairments. Slight changes sometimes aren't. If it's not, a border might be better even if it looks a bit odd.

pinging @deilann

**Comment by deilann** [comment]
Just lemme know when it's live

**Comment by janetmango** [comment]
@crookedneighbor The slightly darker background sound like a great idea. That would also differentiate it from the border that's used when we're casting spells on a task and help prevent confusion.

**Comment by crookedneighbor** [comment]
@deilann It is now live. I assume it doesn't have a good enough contrast for people with a visual impairment, but in the short term, it's better than making it appear like a task is checked when you've just un-checkd it.
