### ISSUE TITLE
Banner "You're resting in the inn" above Dailies doesn't appear/disappear when checking in/out from the mobile apps or API

### ISSUE THREAD

**Issue by fogbank** [HabitRPG/habitica#5693]
As stated in the title, when I choose to rest in the inn from web and check out from the mobile app, the yellow banner "You're resting in the inn!" above the dailies list doesn't disappear as it should.

Steps to reproduce:
1. Check in the inn from web
2. Go to the tasks web page
3. Use the mobile app to check out from the inn
4. Reload the web page

The character is correctly awake, but the yellow banner is still there.

**Comment by Alys** [comment]
Thanks @Roberto! Which mobile app do you use - Android or iOS "HabitRPG"
(which has a chest logo) or iOS "Habitica" (purple gryphon)?

You can probably fix this by resting and unresting from the Tavern on the
website.

**Comment by fogbank** [comment]
I'm using the Android app.

Yes, resting and unresting from the website fixes it. Mind you, it's really a very minor bug, it didn't cause any particular problem.

**Comment by Alys** [comment]
The same problem occurs resting / un-resting using the API. 

The message above the Dailies column can be made to appear / disappear as appropriate by reloading the website's tasks page, but it would be nice if it could change on a sync as the "Zzzzz" marker does.

I'm changing this thread's subject to this:
'Banner "You're resting in the inn" above Dailies doesn't appear/disappear when I checking in/out from the mobile apps or API'

**Comment by crookedneighbor** [comment]
It's because there's a one-time binding on it: https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/tasks/index.jade#L22

If you leave the tasks page and then return, it disappears. As far as I'm concerned, this edge case is fine. @alys if you feel strongly about it, just remove the one time binding marker. 

If you do that, we may also want to think about removing one time bindings from every other location where a sync from an api call could render them out of date.

**Comment by Alys** [comment]
Thanks @crookedneighbor, I will do this. I think it's jarring enough that it should be fixed.
