### ISSUE TITLE
I logged on today and my entire account was reset

### ISSUE THREAD

**Issue by ander571** [HabitRPG/habitica#5715]
Hello I'm Mike and my API is 98093a44-9368-4555-950d-00983d9413f2

Today I went to get on habitRPG. When I loaded the site I wasn't automatically logged in (has happened before so no bother) i went to login but forgot my password. I reset it without a hitch. When I logged on I saw that my entire account had been reset I had lost my equipment, my gold, my character, my party everything I was level one again. Before I was a twenty something healer in a nice little party is there anything can be done???

**Comment by Alys** [comment]
This almost certainly means that you have two accounts. 

Did you use a different email address to register another account? 

Do you normally sign up with Facebook login?

I strongly recommend that you delete the account you're logged in to at the moment so that it can't cause further confusion. To delete it, go to https://habitica.com/#/options/settings/settings and click the red delete button.

**Comment by ander571** [comment]
Welp you are right I'm stupid thank you very much

**Comment by Alys** [comment]
It's a common mistake. Don't worry about it. :)
