### ISSUE TITLE
Did not receive my July 2015 subscriber items

### ISSUE THREAD

**Issue by swooping-is-bad** [HabitRPG/habitica#5716]
I never received my Rad Surfer item set. I have never had a problem getting the subscriber items in the past. The problem is occurring in Chrome, Safari, and the Habitica app, all on iPhone.

**Comment by Alys** [comment]
We'll need to be able to find your account to help you. Please tell us your User ID. To find out how to find it, click on Help -> Report a Bug and see the instructions there (step 6).

**Comment by swooping-is-bad** [comment]
Sorry about that. Here's my user id. 
5a4b4229-591c-47f4-ab7a-5c962998a285

**Comment by Alys** [comment]
Your account shows that you do have them. You can see what they look like at [Mystery Item](http://habitica.wikia.com/wiki/Mystery_Item).

Please reload your Equipment page and look in the Mystery section. If they don't appear, log out, clear your browser's cache, close all browser windows, and then check again. If you still don't see them, please upload a screenshot of that section (drag it into a comment here rather than attaching it to an email).

I'm going to close this because I'm confident that you do have the items - they are showing in your account in the database, but we can reopen it if a caching problem is preventing you seeing them.
