### ISSUE TITLE
Muddled terminology on To-Do progress graph

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5724]
Regarding the graph visible on click of the "signal strength" icon above the user's list of To-Dos, from a comment by @TheRealQA2 on #5696:

> Oddly, now that I look at it, the mouse-over is tool-tipped with "progress", the graph is titled "history" and the blue square indicating what the line on the graph stands for is labelled "score". Might actually be worth putting in an intro-coders' issue to bring some consistency to the labels, given that it's creating confusion.

The several different labels at work on the progress graph make it hard to understand what you're looking at. Can we clarify this UI so the user has a clearer understanding of what's being tracked?
##

**Comment by audiolion** [comment]
Is this still something we want to pursue?

#### Tooltip says 'Progress'

![tooltip](http://imgur.com/qOb5EWV.jpg)

#### Graph Title is 'History'

![graph](http://imgur.com/fTlKDBm.jpg)

#### Graph Label and Tooltip hover is 'Score'

![graph tooltip](http://imgur.com/BYhtalB.jpg)

Relatively easy fix, the issue is that this styling is used on other graphs ('Progress -> History -> Score') e.g. the EXP bar graph

![exp bar graph](http://imgur.com/33h3Lju.jpg)

Notice too that the tooltip doesn't show correctly on the exp bar even though it is in the code:

``` jade

.meter.experience(tooltip='{{Math.round(user.stats.exp * 100) / 100}}')
        .bar(ng-style='{"width": Shared.percent(user.stats.exp,Shared.tnl(user.stats.lvl))+"%"}')
        span.meter-text.value
          span(ng-show='user.history.exp', tooltip=env.t('progress'))
            a(ng-click='toggleChart("exp")').glyphicon.glyphicon-signal
          span
          | {{statCalc.expDisplay(user)}}
```

The issue (and this is a separate bug in a way but related to this issue somewhat) is that the meter is wrapped in a tooltip that shows current exp, and that tooltip is overriding the nested tooltip which would display 'Progress'

We do have supported translation entries for 'Progress', 'Score' and 'History' so we should be able to make modifications if we choose.

**Comment by librarianmage** [comment]
Should this be closed, but considered in the eventual progress graph update?

**Comment by Alys** [comment]
Yes. When a replacement for progress graphs is implemented, we're likely to be more careful about  the terminology so this can be closed.
