### ISSUE TITLE
Negative experience in dashboard...

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5736]
<img width="158" alt="screen shot 2015-08-04 at 9 16 33 am" src="https://cloud.githubusercontent.com/assets/577460/9061421/a616d554-3a89-11e5-8809-26fd0ae4930a.png">

The score graph is positive.
<img width="313" alt="screen shot 2015-08-04 at 9 18 28 am" src="https://cloud.githubusercontent.com/assets/577460/9061463/d182ca18-3a89-11e5-9c8c-e4a52403e920.png">

**Comment by deilann** [comment]
Did you un-check a task after leveling up?

If so, this is expected. We've considered reverting the level up, but have come to the conclusion that the ramifications of deleveling someone aren't worth having to work up through some negative XP.

**Comment by crookedneighbor** [comment]
Another option would be to prevent experience deduction from lowering below zero.

**Comment by deilann** [comment]
Pretty sure we considered that as well, but didn't think it was a good
solution because the full value should be deducted.

On Tue, Aug 4, 2015 at 10:07 AM, Blade Barringer notifications@github.com
wrote:

> Another option would be to prevent experience deduction from lowering
> below zero.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5736#issuecomment-127677647.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by crookedneighbor** [comment]
It's such an edge case that I'd be okay with it.

**Comment by Alys** [comment]
If you level up by accidentally ticking off a red To-Do with a checklist, the XP gain can be large, and if if was deducted only down to zero, you could end up with a significant amount of unearned XP. Negative XP is better. I've seen more users disturbed by unearned things in their accounts than by negative experience. @Archimage This isn't intended to dismiss your bug report. Let us know if deilann's explanation isn't relevant to your situation.

**Comment by Gondulf** [comment]
Looks similar to issue #663

**Comment by Alys** [comment]
Thanks @Gondulf.
