### ISSUE TITLE
Spelling errors?

### ISSUE THREAD

**Issue by Batshua** [HabitRPG/habitica#5744]
In the mobile app, one can get a "potatoe" -- Sorry, I don't have a screenshot of this.

I just found the Golden Laurels, which "Increses" perception and constitution.

**Comment by crookedneighbor** [comment]
I've fixed the spelling of the golden laurels description, it'll be live on the next deploy. Thanks for reporting it.

For the potato error, the json key is potatoe (an unfortunate misspelling from the early days of the app), and the problem is that the app is pulling in the json key instead of using the name of the food item. I will open an issue on https://github.com/HabitRPG/habitrpg-ios
