### ISSUE TITLE
Missing Equipment

### ISSUE THREAD

**Issue by sheenasan** [HabitRPG/habitica#5748]
Re: user 4fc2eda2-b570-4bb2-af9e-03daa444fbbc

On 7/30 (in my timezone; might have already been 7/31 in yours) I changed class to warrior (specifically by choosing "change class" for 3 gems then "opt out", as I had no intent of staying that class) to purchase the last limited-edition equipment set (warrior). (I already had the tail from the beginning of the event, but purchased all remaining pieces at that time). After it was purchased, I checked my inventory, saw that it was there, and opted back in, changing my class back to mage. 
Today, when trying  change my appearance, I found that the 2015 summer set for warrior was missing (except for the tail). Instead, I now have additional normal warrior equipment pieces that I did not purchase.
I have not died since 7/30, nor do I have multiple accounts. The missing pieces are not available for purchase (although I have not changed class to check if they are available under warrior, as that costs gems). I can only assume this is some sort of bug, and I hope that it can be corrected so that I can get the limited edition equipment back. 

Thank you.
##

**Comment by Alys** [comment]
@sheenasan I've given you all of the 2015 Summer Warrior gear. Please tell me if any of it doesn't appear! I have not removed any of the incorrect Warrior gear, although I can if you don't want it in your account.

When you bought the Summer gear, did you also deliberately buy any of the non-Summer Warrior equipment? I'm asking because I'd like to understand the extent of the bug. I know you said that you now own gear that you didn't purchase, but I'd like to know if you also own non-Summer gear that you DID purchase. 

Also, when you were buying the gear, were you clicking on each piece in the Rewards column quickly with no other actions taken in between each purchase? We have a bug at the moment where a purchased item doesn't disappear from the Rewards column immediately, so I'm wondering if that was related. If you clicked on what looked at the time to be a Summer piece, the piece would have been added to your inventory in your browser, but the click might have been interpreted by the server to be on a different piece, resulting in the switch that you saw.

Did it seem like you had to click more than once to buy some or all of the pieces? Perhaps because purchased items weren't disappearing from Rewards straight away? 

For devs: These were the incorrect items in @sheenasan's account due to this bug (I had a database backup from shortly before they were bought so I can tell they were all new acquisitions):

```
"armor_warrior_1" : true,
"armor_warrior_2" : true,
"head_warrior_2" : true,
"head_warrior_3" : true,
"shield_warrior_2" : true,
"shield_warrior_3" : true,
"weapon_warrior_2" : true,
"weapon_warrior_3" : true,
```

**Comment by sheenasan** [comment]
Thank you for fixing this for me.

I had bought warrior gear in the past for certain. I believe I also purchased some that day, though I'm not 100% certain. If I did, it would have been a straight shot top to bottom, one of each type. I definitely didn't have enough extra money to do that more than once that day, so it would have been only a single set.

At the time I purchased the limited gear, it did not disappear from the browser, and I did indeed click on each one without other actions in between. However, I have noticed that same bug when purchasing the other sets (and also when purchasing non-limited gear), so I did not attempt to purchase the same item more than once. After clicking once on each, I went and checked to make certain that they had appeared on the inventory screen. They had, and when I returned to tasks, they were no longer listed there. If I purchased additional warrior equipment (as I said, I don't recall for certain), it would have been after returning to the tasks screen from checking inventory. 

I hope that description is sufficient to help you track down the source of this bug. 

As far as the other equipment goes, I'm not certain whether you can tell on your end whether or not some were purchased. If they were, it would have been one of each item type, so perhaps leave the lowest of each that was acquired that day (unless you can tell that they weren't). Anything above that is definitely the result of a bug, so please feel free to remove it. I'm trying to play as fairly as possible, so I don't want to take rewards I didn't earn.

Again, thank you for the quick resolution.
Angel

Date: Wed, 5 Aug 2015 16:58:33 -0700

**Comment by crookedneighbor** [comment]
The info about gear purchases should be in Amplitude.

**Comment by AtlasTurtle** [comment]
User ID 66f0de02-8e71-40cc-8a5f-b5d1ee8597ec
Browser: Chrome
OS X El Capitan

I have had a similar problem with disappearing equipment. I purchased the shovel, one of the limited edition winter items, last night. This morning when I checked in on my dailies the shovel was gone. I have checked the equipment section of my inventory but it is not there. I have had similar things happen before but my gold has always been refunded. This time both the item and the gold are gone and since it was a limited edition item I am now no longer able to repurchase it.

**Comment by Alys** [comment]
@AtlasTurtle I've given you the missing items.

**Comment by AtlasTurtle** [comment]
<img width="1280" alt="screen shot 2016-02-02 at 6 25 58 pm" src="https://cloud.githubusercontent.com/assets/17035319/12767958/7bda3142-c9da-11e5-8a5c-423d244c9a22.png">
 I just tried it on Safari and still can't see it. Am I looking in the wrong place? I'm sorry. I'm still very new to Habitica.

**Comment by Alys** [comment]
Sorry, my fault! I ran the command but neglected to do the confirmation step. They should be there now. Please reload if you don't see them. Thank you for asking again!
