### ISSUE TITLE
Vanishing Enchanted Armoire Purchase

### ISSUE THREAD

**Issue by Sumosan** [HabitRPG/habitica#5749]
Hi Habitica Admins!

I recently just bought my 4th installment of the Enchanted Armoire.  I've been really impressed with it so far, but after my gold was deducted, I could not find it in my inventory, even after refreshing the page.  I was too slow to take a screenshot.  I think it may fix itself in a little bit, but I just wanted to bring this to your attention.

Thank you!

**Comment by Alys** [comment]
Hi @Sumosan. Sorry about that! You can work around the problem by going to Settings -> Site and using [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to give yourself back the gold.

I'm closing this issue now because we're tracking this problem in https://github.com/HabitRPG/habitrpg/issues/5376. If you'd like to follow the progress of the issue, there's a subscribe button on the right hand side.
