### ISSUE TITLE
Tasks page loading/running extremely slowly after rebirth -- too many equipment/gear pieces in Rewards column

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#5750]
So, this is not so much something to fix for me right meow as a memo for something worth fixing in the near future:

I rebirthed today and it became almost impossible to use my tasks page. Checking something off took over a minute to register and adding a To-Do was almost impossible because the text was loading so slowly. After many tune-ups to Firefox (which I guess I needed to do anyway) I realized the problem was that my rewards column was insanely huge- due to over a year and a half's worth of subscriber gear and seasonal gear, as well as a large number of Enchanted Armoire items.

I have dealt with this by buying back all the zero-cost items, and then selling off a lot of potions and eggs so that I could buy as much as possible to speed things back up. This wasn't really a preferred solution, as I wanted to have the experience of starting over without all my equipment (I know I can just pretend I don't have it...) For someone who sold all their eggs/potions before rebirth, this might be even worse. 

Granted, I am running Firefox on a fairly old computer with a not-super-great connection, but every other site, and other pages of Habitica, were working fine.
##

**Comment by lemoness** [comment]
At one point we discussed making it so that you don't lose any of the 0 GP
items when you rebirth, which I think is a good idea. Not a perfect fix by
any means, but it might help.

**Comment by Alys** [comment]
Another idea: when there's many gear pieces to buy, display only some in the Rewards column and have a dedicated page for buying back gear that lists them all. We could ensure that the original class items always stay in the Rewards column (that would help to replicate the feel of having a new account), and we'd have to ensure that any current seasonal items appeared there, no matter what -- so the code would be a bit complex.
I'm not completely happy with this idea, so feel free to shoot holes in it. :)

A dedicated page would give us more flexibility with purchase options. For example, @deilann suggested once (paraphrased, possibly inaccurately) that after rebirth you could buy back all Seasonal items of a certain type (e.g., shields) with a single purchase of just one of those items. That would stop after-Rebirth gear purchasing becoming more and more unreasonable over time.

**Comment by Alys** [comment]
I've written code that prevents Rebirth removing any equipment that costs zero gold. I still need to write tests.

@lemoness We'll need to adjust the text on the Rebirth confirmation screen (screenshot below). Currently it includes this:

"... You return to full Health. You have no Experience, Gold, or equipment. ...
... Limited edition equipment you've purchased can be repurchased, even if its event has ended. ..."

I suggest that the two parts about the equipment be moved to one place because we often get questions about whether all gear can be repurchased. I suspect people don't read all the way down.

![screen shot 2015-08-12 at 3 37 48 pm](https://cloud.githubusercontent.com/assets/1495809/9217415/b345a494-410a-11e5-9231-261b3a2a7f4a.png)

On a slightly related note, I think we should remove "after you unlock the Item Shop" from this Seasonal Shop text:

"If you've used the Orb of Rebirth, you can repurchase this equipment in the Rewards Column after you unlock the Item Shop. Initially, you'll only be able to purchase the items for your current class (Warrior by default), but fear not, the other class-specific items will become available if you switch to that class."

**Comment by lemoness** [comment]
Agreed about removing "from the item shop."

"You have no Experience, Gold, or Equipment (with the exception of free
items like Mystery items)."

Unless we want to do a total rewrite to change the way they are grouped?

**Comment by Alys** [comment]
After our senior devs finish some significant API changes, we are considering adjusting Rebirth so that it does not remove any of the limited edition Grand Gala equipment. I.e., the only class-specific equipment that would be removed would be the basic class gear.

We might also (at the same time or later), add an option so that hard-code rebirthers would still lose that gear.

**Comment by Alys** [comment]
I'm closing this because it will be resolved when this fix is done:

#7917 "Orb of Rebirth: change to cost 6 gems, not remove any equipment"
