### ISSUE TITLE
Request Too Large to Handle message when editing Guild

### ISSUE THREAD

**Issue by Awesumounk** [HabitRPG/habitica#5755]
Months ago, I encountered this problem (which I am experiencing again)when editing my guild, Journey to Clean (0f754c79-cf74-4fbe-a628-ca70036394b5).  A red error message box appears in the right hand side after sync that says, "Request to large to handle".  In each occurance I was making a minor edit (fixing a spelling mistake, or grammitical correction).

**Comment by crookedneighbor** [comment]
@Awesumounk You already reported this here: #5579 and both of these are duplicates of #1471. If you'd like to subscribe to the progress of the bug, you can do so by pressing the subscribe button. 

I'm going to close both issues, but if you're still having issues since we're tracking the progress in #1471.
