### ISSUE TITLE
system messages in party chat are not translated (skills castings, quest progress / damage reports)

### ISSUE THREAD

**Issue by Jazzis18** [HabitRPG/habitica#5757]
Hello, can you somehow translate it in Russian and other languages? And other similar messages.
[/website/src/controllers/user.js#L462](https://github.com/HabitRPG/habitrpg/blob/68f5a162fd637938c4bd910daf212dba45a66ecd/website/src/controllers/user.js#L462)

```
var message = '`'+user.profile.name+' casts '+spell.text() + (targetType=='user' ? ' on '+found.profile.name : ' for the party')+'.`';
```
##

**Comment by Alys** [comment]
@Jazzis18 We would like to do that, but unfortunately it's not as easy as translating most of the site text. Currently, the messages about skills being cast (or about quest progress) are written into the party chat at the time of casting (or at cron) as a single string of English text, and then they can't be changed whenever the chat messages are viewed by people who use different languages. They aren't stored as variables that would allow them to be translated.

However we should try to change that for the benefit of our non-English speakers (there are many now).

This is more of a feature request than a bug, but I'm going to leave this open for our developers to suggest ideas.

One thing we'd have to consider is that languages can have very different word orders. We could store each message as a sequence of separate strings ("person's name", "casts", "skill name", "on the party") and then translate each one individually, and then concatenate them to produce the final message, but that could produce gibberish in some languages.

Ideas, anyone?

**Comment by SabreCat** [comment]
If we can make it a normal `env.t` style string, we wouldn't need to chop it up. It would just be `<%= userName %> casts <%= skillName %> for the party`, and translations could move the variables around as needed.

**Comment by Alys** [comment]
Good point.

So, we'd need to change the code that puts the system messages into chat so that instead of creating a `text` attribute, it creates an object containing `userName`, `skillName`, etc. We'd also change the code that displays chat so that when it sees a message with that object, it creates the text on the fly, using translations.

At the same time, we should stop using backticks to format the message and instead apply a style that looks the same but allows the text to wrap neatly (fixes https://github.com/HabitRPG/habitrpg/issues/3453).

We should also apply a class that identifies each distinct type of message (e.g., skillCast, questProgress) so that we can more easily allow the users to hide their choice(s) of skill and quest messages (https://github.com/HabitRPG/habitrpg/pull/5364 will then be easier to complete).

**Comment by khipkin** [comment]
@Alys Would it be worthwhile to have a GitHub label specifically for translation-related issues/PRs?

**Comment by khipkin** [comment]
@Alys Just kidding; I see that we already have a translations label. :stuck_out_tongue_winking_eye:

**Comment by Alys** [comment]
Thanks @khipkin. :)

_deleted my comment that's irrelevant in light of SabreCat's idea above_

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
Yes, all of this should still be relevant.

**Comment by lemoness** [comment]
I've updated the labels on this issue!

**Comment by Alys** [comment]
An important point is that each message should be readable by all party members, no matter what language each speaks. That would need to work regardless of what client each player was using, so the API should return the translated version of the message, using the user's chosen language.

**Comment by Yutsuten** [comment]
May I try doing it? I was thinking to do as @SabreCat wrote: change messages to an `env.t` string and then put `<%= userName %> casts <%= skillName %>` to the "translations" script.

**Comment by Alys** [comment]
@Yutsuten Sure, thank you!

One thing to note is that the translated string has to be constructed by the API so that it's returned in the correct language no matter whether the user is using the website or mobile apps or third-party tools.

**Comment by Yutsuten** [comment]
Got it, I'll make sure the API always returns the messages in the correct language.

**Comment by Yutsuten** [comment]
This change will need some planning before I can write some code...
I'll make some notes here so to organize my mind. Don't consider it final, so anyone can feel free to give opinions / help me plan it. It isn't complete yet too.

## Database change
In the chat object (Ex. query: `db.groups.find({name: "party1"}, {chat: 1})`), add a field `info` which is an object with information about the message.
For **old** chat objects that still don't have the `info` field, use the `text` field (current behaviour).
For **new** ones that have the `info` field, use it to build the text in the desired language.

### Before change:
```json
{
  "id" : "4a1df240-a8c6-4e23-8644-a2cb9bef9f47",
  "text" : "`user2 attacks The Basi-List for 0.5 damage.` `The Basi-List attacks party for 0.0 damage.`",
  "timestamp" : 1518349031167,
  "likes" : { },
  "flags" : { },
  "flagCount" : 0,
  "uuid" : "system"
}
```

### After change:
```json
{
  "id" : "4a1df240-a8c6-4e23-8644-a2cb9bef9f47",
  "text" : "`user2 attacks The Basi-List for 0.5 damage.` `The Basi-List attacks party for 0.0 damage.`",
  "info": {
    "type": "boss_damage",
    "user": "f227ba31-eb39-4bc1-9cc6-9ca8488a2744",
    "quest": "an_identifier",
    "userDamage": 0.5,
    "bossDamage": 0.0
  },
  "timestamp" : 1518349031167,
  "likes" : { },
  "flags" : { },
  "flagCount" : 0,
  "uuid" : "system"
}
```

## Messages types
I feel it will be necessary to list every possible system message, as each one will use different variables to display the message.
Began building this list by consulting `website/server/models/group.js`.

### Party
1. `Your quest, ${quest.text('en')}, has started.`
```json
"info": {
  "type": "quest_start",
  "quest": "an_identifier"
}
```

2. `${user.profile.name} attacks ${quest.boss.name('en')} for ${progress.up.toFixed(1)} damage. ${quest.boss.name('en')} attacks party for ${Math.abs(down).toFixed(1)} damage.`
```json
"info": {
  "type": "boss_damage",
  "user": "f227ba31-eb39-4bc1-9cc6-9ca8488a2744",
  "quest": "an_identifier",
  "userDamage": 15.3,
  "bossDamage": 3.7
}
```

3. `${quest.boss.name('en')} does not attack, because it respects the fact that there are some bugs post-maintenance and it doesn't want to hurt anyone unfairly. It will continue its rampage soon!`
```json
"info": {
  "type": "boss_dont_attack",
  "quest": "an_identifier"
}
```

4. group.sendChat(quest.boss.rage.effect('en'))
```json
"info": {
  "type": "boss_rage",
  "quest": "an_identifier"
}
```

5. `You defeated ${quest.boss.name('en')}! Questing party members receive the rewards of victory.`
```json
"info": {
  "type": "boss_defeated",
  "quest": "an_identifier"
}
```

6. `${user.profile.name} found ${foundText}.`
```json
"info": {
  "type": "user_found_items",
  "user": "f227ba31-eb39-4bc1-9cc6-9ca8488a2744",
  "quest": "an_identifier",
  "items": 
  {
    "item_identifier1": 5,
    "item_identifier2": 2
  }
}
```

7. `All items found! Party has received their rewards.`
```json
"info": {
  "type": "all_items_found"
}
```

8. `${user.profile.name} casts ${spell.text()}${targetType === 'user' ?  on ${partyMembers.profile.name} : ' for the party'}`
```json
"info": {
  "type": "spell_cast",
  "user": "f227ba31-eb39-4bc1-9cc6-9ca8488a2744",
  "spell": "an_identifier",
  "targetId": "an_identifier"
}
```

9. `${user.profile.name} aborted the party quest ${questName}.`
```json
"info": {
  "type": "quest_abort",
  "quest": "an_identifier",
  "user": "f227ba31-eb39-4bc1-9cc6-9ca8488a2744"
}
```

### Tavern
1. tavern.sendChat(quest.completionChat('en'))
```json
"info": {
  "type": "tavern_quest_completed",
  "quest": "an_identifier"
}
```

2. `${quest.boss.name('en')} tries to unleash ${quest.boss.rage.title('en')} but is too tired.`
```json
"info": {
  "type": "tavern_boss_rage_tired",
  "quest": "an_identifier"
}
```

3. tavern.sendChat(quest.boss.rage[scene] ('en'))
```json
"info": {
  "type": "tavern_boss_rage",
  "quest": "an_identifier",
  "scene": "?"
}
```

4. tavern.sendChat(quest.boss.desperation.text('en'))
```json
"info": {
  "type": "tavern_boss_desperation",
  "quest": "an_identifier"
}
```

**Comment by beffymaroo** [comment]
@Yutsuten Are you still working on this issue? Please let us know. Thanks! :)

**Comment by Yutsuten** [comment]
@beffymaroo Yes, my PR is ready for review, so I'm waiting for reviews or to have it merged in develop.

**Comment by beffymaroo** [comment]
@Yutsuten Excellent, thank you for the update!

**Comment by scarletwolfy** [comment]
Hello, I'm new. How can I help? (and if I'm not good at coding?)
