### ISSUE TITLE
To-Dos vanishing

### ISSUE THREAD

**Issue by TeragramKlaw** [HabitRPG/habitica#5764]
I heavily utilize the to-do list feature, but recently my to-do lists are vanishing. They are not accidentally being completed, as they do not show up as completed at any point. They just disappear. I think they are vanishing one at a time, but unfortunately by the time I noticed at first I had already lost a half dozen.

I suspect it has something to do with the new Habatica app (I am using the latest iPhone version on iOS 8.3). I have not experimented as I do not wish to lose any more lists, but I think when I add a new list via the app one of my old lists disappears. For the time being I have stopped editing to-dos on the app.

My user ID is e1a90a7c-c53f-4242-ac39-0a96b1c81960

Thank you!

**Comment by Alys** [comment]
Can you please go to the Habitica website (https://habitica.com/ ) and log in using the same login method that you use on the app. The website should work in a mobile browser. When you are viewing your task screen, click the "clear" button next to your tags, even if it looks like no tags are selected. Ensure that no text is in the search box above the Rewards column. Do all of your To-Dos now appear in the website?

**Comment by Alys** [comment]
Also, on the Habitica app, make sure no tags are selected. Does that make all To-Dos appear in the app?

**Comment by TeragramKlaw** [comment]
Sorry, I forgot to mention that I had tried this. I don't really use tags, but I tried clearing and it made no difference. The to-dos are still gone.

**Comment by Alys** [comment]
Can you tell us some words from To-Dos that were deleted, as accurately as you can remember? If they were private, you can email them to admin@habitica.com.

**Comment by TeragramKlaw** [comment]
One was called "Cleaning Party: Bedroom" and had stuff on it like "Bookshelf area" and "desk area." Another one was "Reading List: Novels" but I later recreated that one so that might be less helpful. I do not believe I ever recreated the "Cleaning Party" one (although I had several other "Cleaning Party" lists that did not vanish).

**Comment by Alys** [comment]
The "Cleaning Party: Bedroom" task is definitely missing. I have access to a database backup from 2015-07-21, so below are the versions of both those tasks that were in your account then.

We'll look into whether anything on the website or app could be causing the disappearances. If you notice any more going missing, please comment here as soon as you can.

```
text : Cleaning Party: Bedroom,
checklist : 
        text : Desk Area,
        completed : true

        text : Under Bed Area,
        completed : true

        text : Window Area,
        completed : true

        text : Dresser Area,
        completed : true

        text : Bookshelf Areas,
        completed : false

        text : Dust,
        completed : false

        text : Vacuum,
        completed : false

text : Reading List: Novels,
checklist : 
        text : Other Worlds,
        completed : true

        text : Midnight Riot,
        completed : false

        text : Demon's Lexicon,
        completed : false

        text : Raven Boys,
        completed : false

        text : Gilgamesh,
        completed : false

        text : Hansel & Gretel,
        completed : false

        text : Jinn and Juice,
        completed : false

        text : Turnip Princess,
        completed : false

        text : Trailer Park Fae,
        completed : false

        text : I Am Princess X,
        completed : false

        text : Isle of the Lost,
        completed : false

        text : Daughters of the Samurai,
        completed : false
```

**Comment by teamtoques** [comment]
Hi there! I'm having a similar problem, except it's not just my To-Dos... One of my Habits and many Dailies have disappeared as well. Clearing tags/the search bar does nothing.

I came back to Habitica after several months away, cleared out a bunch of old items, and added these new ones yesterday morning... But when I looked at the mobile app last night, they were gone. (I'd wondered if the app just wasn't pulling from the site correctly--but it turns out the site itself was the problem.) I can't remember exactly, but I think the missing Habit is called "social obligations", some of the missing Dailies are "morning tasks", "mail tasks", "laundry", "pow-wow", and the missing To-Dos are things like, "Office Depot order", "get water filter replaced", etc.

It might not be related, but I've noticed that one of my remaining Dailies, "Groceries", has reverted from a "repeat every X days" task to an, "on certain days of the week" task without any prompting.

My user ID is ed27f7b4-9047-4a57-b51d-765774faea34

I'm running Chrome and have the iPhone 5 app. No error message, unfortunately. :(

Hope you guys are able to figure something out! Thanks!

**Comment by Alys** [comment]
@teamtoques When your actions you took in the recent past are later reverted, it's an example of this issue: #4313 It's most commonly seen with tasks that were ticked becoming unticked, but it can also apply to task creation and editing. Your browser recorded your new tasks but didn't send them to the server so they were never permanently saved. I'm very sorry about the inconvenience!

If you find it happening often, see the Advice section near the top of that issue (that's really the only part you need to read). In brief, try reloading the page with your browser's refresh button often, because that helps to ensure that your actions are sent to the server for permanent recording.

**Comment by teamtoques** [comment]
@Alys Oh, thank you very much! I probably would have never found this issue/advice on my own, thank you for linking me. I'll retry with more refreshing and hopefully everything will sync as it should this time.

**Comment by Alys** [comment]
@TeragramKlaw We were never able to find out what caused this. :(  We haven't had any other reports of it, so I am hoping it was a temporary problem. I'm closing this now, but comment here if it's still happening for you.
