### ISSUE TITLE
Error Cannot set property 'drop' of undefined

### ISSUE THREAD

**Issue by sujunmin** [HabitRPG/habitica#5777]
When I use Burst of Flames on my Daily Task "hack the portal", there is a level up notification, and an error out. Every time I reload the page that the error says, the error comes out repeatedly.

My UID: ac6fbe37-b0dc-40d8-ba14-77dde66fbfa8
OS/Browser: Windows 10 Pro x64 w/ Chrome 44.0.2403.155m

![default](https://cloud.githubusercontent.com/assets/6415168/9243607/28dacc7e-41c5-11e5-91bf-972924163214.png)

**Comment by Alys** [comment]
@sujunmin When you log issues, it's best to provide a description of what you were trying to do when the error occurred and what happened because of the error. Otherwise it's often impossible for us to investigate. I'm going to close this now, but please see this issue: https://github.com/HabitRPG/habitrpg/issues/4986
If the information at the top describes your problem, you do not need to report anything. 

If you're experiencing a different problem, please provide full details, including your User ID (see Help -> Report a Bug for information about how to report a problem).
