### ISSUE TITLE
Cannot add new party member

### ISSUE THREAD

**Issue by gileryn** [HabitRPG/habitica#5786]
I invited my friend to play habitica via email, but I cannot invite him to my party. I am being told his user id cannot be found. We double, triple, quadruple checked to make sure I was spelling it right. He even made a new account, and that is how we discovered that this seems to be a bug on my end, because the same thing happened. I have invited a friend to the game and too my party before with no issues.

**Comment by Alys** [comment]
The User ID is a string of random characters, similar to this: d904bd62-da08-416b-a816-ba797c9ee265. Are you entering something like that, or are you entering a person's name?

If you're entering his name:
Your friend can read about how to find his User ID on the wiki's [Party](http://habitica.wikia.com/wiki/Party) page. See the Joining a Party section, where it talks about using the Settings -> API screen to find it.  You might also find useful information for yourself in the Adding Members to Your Party page.

Could you please ask your friend to delete his second account? He can do that through [Settings -> Site](https://habitica.com/#/options/settings/settings) - click on the red "delete" button. I strongly recommend this, because we see a lot of players having trouble with duplicate accounts, if they forgot their login details for one and accidentally use the other.

If you have any questions about this, you can ask here, but I recommend going to the [Habitica website](https://habitica.com/) and clicking on Help -> Ask a Question. That takes you to a guild that has a lot of helpful people who can fill in any details I've left out here, and you're likely to get an answer faster there than here.

**Comment by Alys** [comment]
@gileryn since we haven't heard back from you, I'm assuming that my previous comment gave you the information you need, so I"m closing this, but if you still need help, ask here or in the Newbies Guild (Help -> Ask a Question).
