### ISSUE TITLE
Bug in Gruppe 

### ISSUE THREAD

**Issue by koevenicus** [HabitRPG/habitica#5787]
User ID: 53703f06-85e0-4eac-b82d-c61f017ab67e
Gruppen ID: c27bd097-fe78-4127-955e-364e09c8a2c1

Sehr geehrter Habit Team,

vor einigen Tagen habe ich einen Quest gestartet und wollte verschiedene User meiner Gruppoe hierzu Einladen. Allerdings ist der Quest gestartet, ohne das die MItglieder meiner Gilde hierzu eine Einladung bekamen. Der Quest (Angriff des Banalen, Teil 3: Der Wäschebeschwörer) ist nun allerdings in der Gruppe gestartet, ohne das wer daran Teil nimmt, bzw irgendwelche Aktivitäten hieraus hervorgehen. Ich wollte den Quest verlassen indem ich die Gruppe verlies. Als ich der Gruppe wieder zusties, war der Quest immernoch da, ohne das hieran jemand teilnahm. Scheinbar handelt sich hier um einen Bug. Können Sie bitte den Quest in unsere Gruppe (siehe ID oben) entfernen, sodass wir wieder neue Quest starten können?

Vielen Dank vorab für den Support und ich verbleibe,

mit freundlichen Grüßen,

koevenicus

**Comment by Alys** [comment]
Google translate:

User ID: 53703f06-85e0-4eac-b82d-c61f017ab67e
Group ID: c27bd097-fe78-4127-955e-364e09c8a2c1

Dear Habit Team,

A few days ago I started a quest and wanted different User my Gruppoe this Invite. However, the quest is started without the members of my guild got this invitation. The Quest (Attack of the banal, Part 3: The Wäschebeschwörer) is now however started without it who takes part, or any activities arising therefrom in the group. I wanted to leave the Quest as I left the group. When I zusties the group again, the quest was still there, without thereto anyone participated. Apparently here is a bug. Can you please the Quest in our group to remove, so that we can start new quest again (see ID above)?

Thank you in advance for the support and I remain,

Best regards,
koevenicus

**Comment by Alys** [comment]
I'll remove the quest from the party in the next few hours, if another database admin doesn't get to it first.

**Comment by Alys** [comment]
The quest has been removed.
