### ISSUE TITLE
Token Store Logistics

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#579]
So, I have been thinking about the token store in terms of costumes/items, and have come to the following conclusions:
1. I know we've been talking about it in the profile thread, but before we can implement this, we really need to have an armory/closet so that people can buy multiple outfits and then switch them around whenever they like. Ex) I will buy bunny ears for Easter (working on making these, by the way), but I want to also keep my normal helmet, and then I also want a Santa hat for Christmas, etc etc etc. It should be as easy as possible to switch around and customize outfits.

WITH THAT IN MIND:
1. I think all token store item bonuses should be "transparent" - aka they give you exactly the same bonus as whatever item you currently have. Ex) I have a level three helmet, and then I buy and put on my bunny ears, and they give me a level three bonus! If I had a level two helmet before, they'd only give me a level two bonus; if I had a level four helmet, they'd give me a level four bonus, etc.

This is useful because it means that people's stats aren't penalized because they want to give us money and buy a cool costume, AND because it prevents accusations of pay-to-win (i.e. "Whattttt that token shop sword gives you a plus 30 bonus?!").  

ADDITIONALLY:
1. We may want to consider making the levels of all gear "fix" onto you once you've got it  - meaning that if you swap back to lower gear, you keep your high-level gear bonus. I know this seems counter-intuitive, but consider the following situation:

I buy a level two helmet. I love it! It's my favorite color, the design suits me, etc. Now I've got enough money to buy a level three helmet, and I'm torn. Although it's technically "cooler", I don't like it as much.... but I want those stats! "Fixing" gear level onto the character would enable me to buy the higher level hat, then swap back to my favorite design with no stat penalty.

RELATED:
1. The only flaw I can think of with the token item "transparency" is that it takes away the idea of progression for token items. I'd argue that this can be replicated by only unlocking certain batches of token items at a time, based on level. This way, people will constantly be excitedly checking the token shop to see what new items are available, and it will make leveling up more fun.

Plus, we can have limited-edition items based around seasonal times, like a custom winter hat that can only be bought December-February, a different Halloween costume every October, or a New Year's Hat that is only available once every year. 

If we give users the option to publicly display their armories, this would also encourage the acquisition of collector's item costumes.

Thoughts?

**Comment by Pandoro** [comment]
@lemoness 
1. Very much agreed, this will soon be done with the new pet and mount system. So don't worry too much about an inventory. It still has to be shown though if the items will be kept in there, I am very much pro this idea and I discussed it lately with @lefnire If we decide to keep gear items in the inventory, we would have to set an appropriate size, although we also have to think about the "bag monetization"-idea. 
2. I would not implement it like that, as it is a by far to big hassle, what I would do and what pretty much every game does: You get additional armor slots for these items. Typically they are empty, but once equipped, they override the other item, visually, while keeping the same old item equipped for the stats. 
3. Yes :p  It seems counter intuitive and probably a pain to implement. If we stay with the progression system, where you don't keep armor, but simply progress in a linear way, then it would be easy, as you would just need another variable which says gear x, while you are at gear level y for the stats. However if we really equip items, which have some stats, then we would need customizable items. To be honest I don't like this idea, I get what you mean, but having a normal background in gaming, items have their stats, sometimes you look stupid, sometimes you don't but by looking at you, I know what kind of stats you have. So for confusion reasons, I would not do this, rather make different items, so that people kind find something "cool" in higher levels as well and if they are soooo attached to a look, well, then just keep the crappy helmet :) You see this a lot in MMOs, it makes your life a little harder, but it will not be the worst. 
4. Hmmm how do you mean progression with the token items? Typically token based fancy looking items in games just make you look fancy right? No real progression in there? But releasing them in chunks would be doable I guess and we have already thought about event stuff :) Maybe with a small drop chance, but token buyable if you want something for sure?

**Comment by lemoness** [comment]
@Pandoro 
1. Awesome!
2. Sounds perfect. However is best and easiest. 
3. Yeah, I understand your points. I guess it'll just be on us in the pixel thread to come up with enough variation to keep people interested!
4. Yes, I didn't mean literally upgrading, I just meant that at level one a bunch of the token items are visible but not accessible, and that as you get better you have more and more options available. I like the small-drop-chance idea!  I do think that having an option to make your armory visible to, say, your party/guild/group would be a nice eventual touch.

**Comment by deilann** [comment]
This is pretty outdated, so I'm gonna close it.
