### ISSUE TITLE
Remove sensitive informations from API endpoints

### ISSUE THREAD

**Issue by 3onyc** [HabitRPG/habitica#5800]
The /user endpoint returns hashed_password + salt, these should never be required in any application using the API, and should be removed.

Related (old) issue #1914

**Comment by 3onyc** [comment]
Looking at [website/src/controller/user.js#L201](https://github.com/HabitRPG/habitrpg/blob/f9e337ed4084c9b2cc459118c89bfb779ef97bca/website/src/controllers/user.js#L201) it seems this is already fixed, but not yet pushed live?

**Comment by crookedneighbor** [comment]
[This commit from 2013](https://github.com/HabitRPG/habitrpg/commit/e568a5ba3119083b2ff1274c40d869a7eed1ca30#diff-4913b70c5883cd908f702f7e02f1397eR515) tried to do this, but the problem is that it's deleting `user.auth.salt` and `user.auth.hashed_password` when it should be deleting `user.auth.local.salt` and `user.auth.local.hashed_password`.

**Comment by crookedneighbor** [comment]
Not sure if there should be details in the facebook login that should also be deleted.
