### ISSUE TITLE
No damage from undone dailies. 

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5808]
I walked away for a while and did not check into the inn..   I see no lost HP or other penalties for not completing dailies.    It's kind of defeating the purpose for me when I can only gain points and not lose them. 

Display Name:  timothyfire

User ID: 7612ccb3-970a-4b00-9a0b-a31655e5ca7b

Using Chrome, most updated version on Win7x64 pro

This problem has been going on for a long time... more than a month or so.

**Comment by crookedneighbor** [comment]
I'm a little confused. Are you saying:

A) You came back to Habit about a month ago and since then have not received any damage from incomplete dailies?

B) You've been gone for a month and expected massive damage from not doing your dailies and that did not happen.

C) Something completely different

If A, that is very strange. May I have permission to inspect your dailies to see if I can see anything that might suggest why that is happening? 

If B, we recently made a change to the way the site works so that if you miss multiple days, it only punishes you as if you missed one day. So it's easier to pick back up if you leave for an extended period without resting in the inn. We are planning to add some difficulty settings, one of which will be to re-enable the old behavior, but have not finished implementing it yet. 

If C, what is it? :smile:

**Comment by ghost** [comment]
It's a bit of both a and b.  I was gone for we'll over a month and have
seen no negative effects.  I have been back for a few days and testing to
see if I could trigger bad results but have been unable to do so.

The reason that I wandered off in the first place was the same issue.  I
stopped receiving negative feedback and was only receiving positive
feedback which is great for my morale and for character growth.. not so
good for building habits as you might imagine... lol.

It was working correctly in the past with the same dailies... just suddenly
stopped one day.

You are more than welcome to take a look at my account... just let me know
if you need anything.

**Comment by crookedneighbor** [comment]
That's very strange. Nothing jumps out at me in your dailies data that would suggest a problem. 

Here's some obvious things, but I have to ask them anyway just to verify that you're not doing them:

1) You're not checking into the inn before going to sleep for the day, right?
2) Your incomplete dailies that _should_ damage you are not displaying with the color gray, right?
3) There's not a healer in your party that is constantly healing you, right? 

If you create a new daily and do not complete it, does it damage you? 

I see that you have about 40 hp currently. Was that damage incurred from negative habits?

**Comment by Alys** [comment]
Note also that if you complete all your Dailies before leaving the site for a while, you will not take any damage for them because they will still be completed when cron runs when you return.

**Comment by ghost** [comment]
I am not checking into the Inn before the end of day... I rarely ever use
the inn at all.

My incomplete dailies all show light blue and one daily that I almost
always complete always shows red no matter the streak attached to it which
I manually erased yesterday in the hopes that it would encourage it to
change from red to green.   For the ones that show blue, they have a streak
that is maintained often even when I do not mark them for a day.

I have no party as I've not really been involved with the more social
aspects of HabitRPG.

If I create a new daily, it does damage me as would be expected.

I'm not sure regarding the damage shown, I believe that it's because I
allocated points yesterday that increased my hit-points but had not leveled
yet to refill the bar.

At this point, I would be more than happy to delete my account and start
over if that would resolve any potential issues.   I am a paid supported,
and I'm happy that I paid, I just want the platform to function as
intended.  I'm not particularly stressed about it or anything, just anxious
to play and I've found this system to be the most effective type of to-do
list carrot to suit my needs.

**Comment by Alys** [comment]
Could you please tell us the text of the one daily that you almost always
complete but that always shows red? If it is private, you could email the
text to admin@habitica.com. If you'd prefer not to tell us, that's okay.

Note that if it does turn out that the only solution is a new account,
we'll ensure that all your items, progress, subscription, etc are copied
over. I don't think it will come to that though!

**Comment by ghost** [comment]
No problem... it's a daily.  Atlas balanced the Weight of YNAB.

It's to remind me to balance my budget everyday.
It's due everyday and I completed it yesterday.... but it's still red and
streak is at zero

**Comment by Alys** [comment]
By the way, the colour of the Daily does not necessarily indicate its done/not done status on the previous day, or even on the previous several days. It indicates your general history for that Daily over all the time the Daily has existed. More details about that are below.

In case you're not aware: A blue Daily gives you small rewards when you complete it, and only small damage if you miss it on one day. A red Daily gives you large rewards when you complete it, and large damage if you miss it.

If a Daily had been not done for a long time, it would be very red (e.g., if you created a Daily several months ago and then left it incompleted while not visiting the site). If you then started doing that Daily every day, it would still remain red for several days at least, however that doesn't mean it's hurting you. Its value (a numerical representation of its colour) WILL be changing towards blue, but the **visible** colour change for very red Dailies is slow. A red Daily that you do complete does not damage you, and rewards you highly with gold and XP.

If a Daily has been done consistently for many days, it will be very blue. If you then miss the Daily for a day or even a few days, it will remain blue. It's value will be changing towards red, but again, slowly. A blue Daily that you do not completed does damage you a little - you lose health overnight after days when you did not complete it.

The slow colour change for very red/blue Dailies is intended behaviour. The idea is that for blue Dailies, if you've been very good at them for a long time, you've built up a safety buffer that allows you to miss them for a while without doing too much damage to yourself (but you still do take a bit of damage overnight). The idea for very red Dailies is that because you've had trouble with them in the past, they stay red for a while to encourage you to complete them (to avoid large health loss) and to reward you highly when you do complete them. A very red Daily will turn blue only after many days of completing it.

The streak is not necessarily related to the colour. It indicates the number of days in a row that you've done the Daily. While we are sorting out this problem for you, I recommend that you do not manually change the streak on any of your Dailies. This is because the streak is usually a good indicator of whether a Daily was actually ticked off on the previous day. Adjusting the streak has no effect on the behaviour of a Daily - it won't cause the Daily's colour to change.

Until this is resolved, you might find it helpful to take a screenshot of your Dailies each night just before you finish using Habitica for the day. The screenshot will clearly show which Dailies have been ticked, and what the streaks are. You can then compare this to the Dailies the next morning - those that were ticked should have a larger streak, those that were not ticked should have a zero streak.

Note that there is an intermittent bug that causes Habitica to not recognise completed Dailies as actually having been completed (https://github.com/HabitRPG/habitrpg/issues/4313). To avoid this bug, reload the site each night just before you take your screenshot. If the reload causes any completed Dailies to be unticked, tick them again and reload again. Take your screenshot after that.

**Comment by ghost** [comment]
Right, I understand this completely and can screenshot as you've requested,
but this daily has literally always been red.   No amount of streak has
ever changed that and while I didn't expect it to change color after one
day of completion, I did expect it to gain a streak of one additional day
than prior.

I understand covering all of your bases in your explanations, as I
troubleshoot issues for a living much of the time as well, but I do tend to
read the rules, I have been a user for a while, and I do understand how
things generally occur on your site barring changes that are implemented
and even then, I read the release/update notes.

My concern here is not with the color, per se, but what the color is
indicative of, and was proven last night when I completed the daily, got
exp and reward from it, then on login today, find that it still has a
streak of zero.

Sorry if that sounds frustrated at all, but your response, while seemingly
cut and pasted, implies very strongly that there is a measurable amount of
ignorance on my end, and I promise you that is not the case.    I've read
the wikis, I've read through troubleshooting errors, and it was only after
many and varied attempts to solve the issue through those avenues that I
reached out for assistance.

As part of my personal test last night I left only one daily unchecked and
that was my daily for brushing my teeth.   I did, in fact, brush my teeth,
but I was hoping to see how it affected me were I to leave it unchecked.
 It does seem to have lost any streak that it might have had, as that has
been reset to zero.. so it seems as if that aspect of things is working as
intended.

Please let me know if there are any other pieces of information that you
would benefit from as this is looked into and I'm happy to provide what I
am able.

Thanks for all of your assistance.

**Comment by Alys** [comment]
Thank you for letting us look at that red Daily. It has a value of -53 which is very red, and so it will take a long time to go back to blue. It was added on 2014-11-11 which explains why it's very red - it would have been getting redder during a long period of absence from the site. It will get bluer over time. If you want it blue soon, delete it and recreate it, and it will be blue in a few days at most if you do it regularly.

_"My concern here is not with the color, per se, but what the color is indicative of, and was proven last night when I completed the daily, got exp and reward from it, then on login today, find that it still has a streak of zero."_
That is an indication of the bug I linked to in my final paragraph. Please read the Advice section near the top of that bug report. From your other comments about streak behaviour, I suspect you might be getting that bug more often than normal, so following point 4 in the Advice section is recommended.

My previous post was not cut and pasted. It was written specifically for you in case it helped you understand what was going on. Please keep in mind that I had no way to know you had read documentation thoroughly.

With any troubleshooting, we have to assume a lack of advanced knowledge on the part of the person having the problem, because to assume otherwise does not do the person any favours. If we assumed that a person had a clear and complete understanding of the matter, then we would not give them information that they might need, and that would be very poor customer service. Giving you as much information as I did **_does**_ assume ignorance of advanced knowledge (because many players do indeed have such ignorance simply from never having been informed), but it does **_not**_ assume that you are ignorant person in general and is not intended to be an insult.

From what I've seen of your account now, there are no problems that would justify deleting and recreating it, so please do not take that step. Everything I've seen so far can be ascribed to Dailies having a large positive or negative value (slow to change colour) and to worse than normal instances of that bug I linked to.

**Comment by ghost** [comment]
Thank you for that clarification and explanation.  I sincerely appreciate
it.

I will follow your advice regarding the linked issue/bug.

For the time being, I think we can put this issue to rest and if need be
I'll readdress it in the future, but looking at your suggestions, hopefully
working around this bug will alleviate some of the issues I have been
experiencing.
