### ISSUE TITLE
Feature request. sell all option. 

### ISSUE THREAD

**Issue by SHMAUS-Carter** [HabitRPG/habitica#5811]
I always have an abundance of eggs and would love to have the ability to sell them all vs having to click the sell button 40 or more times. 
##

**Comment by crookedneighbor** [comment]
@SHMAUS-Carter Thanks for suggesting it. I think that's a fine idea.

In the future, feature requests [should go through our Trello board](https://trello.com/c/odmhIqyW/440-read-first-how-to-request-a-feature-table-of-contents) so our community can vet them first. Going to leave this open though, because I talked with the staff already, and they think this is a great idea. 

Will advertise it in the [aspiring coders guild](https://habitica.com/#/options/groups/guilds/a141a5b9-0d69-46cd-93e6-2b76f18bcc54).

**Comment by crookedneighbor** [comment]
Whoops, linked to the aspiring pixel artists guild by mistake. Here's the link for aspiring coders: https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f

**Comment by SHMAUS-Carter** [comment]
I do apologize for posting in the wrong section I did not even know you had a Trello board that you use for feature request. I'm so used to feature request and issues being reported in the same place.

**Comment by crookedneighbor** [comment]
No worries. Like I said, this is a great idea. 

We do feature requests on Trello so a broader community (more than just devs) can discuss it.

**Comment by SHMAUS-Carter** [comment]
That makes sense. I keep forgetting that your average user (broader community) dose not know of github much less take an active role in filling out issues etc.

**Comment by melarish** [comment]
I'll try building this. Is there any way to assign yourself to an issue?

**Comment by Alys** [comment]
No there isn't. Just commenting as you did is enough. :)

Ask here if you run into problems or want advice!

**Comment by melarish** [comment]
Here's what I've got (the button is there for eggs, pots and food but no point uploading screens for all). Does the whitespace need any improvements? Should there be a proper plural of 'Strawberry' or leave it as is?
<img width="1332" alt="screenshot 2015-09-27 23 48 03" src="https://cloud.githubusercontent.com/assets/5783115/10125620/279a2162-6573-11e5-99e5-2026988ac913.png">
<img width="1318" alt="screenshot 2015-09-27 23 48 29" src="https://cloud.githubusercontent.com/assets/5783115/10125622/327c1b26-6573-11e5-8a13-3e511544b2d4.png">

**Comment by crookedneighbor** [comment]
I think it looks good. For now, leave it singular. I'm working on some changes to make the translated strings more readable. I'll adjust it to plural when I'm done.

**Comment by GeorgeSG** [comment]
I see there are no updates here since September. @melarish, are you still working on this? Can I take it?

**Comment by joshuaohana** [comment]
Been a while since this has been commented on... still need help with this feature? It's also one I would love to use instead of all the clicking to sell everything!

**Comment by TheHollidayInn** [comment]
Please do!

**Comment by joshuaohana** [comment]
Cool, I'm on it! Question on desired implementation, way I see it there's a couple ways to do it and since I'm new to the project want to make sure I stick with Habitica preferred conventions.

1) Add a deleteAll flag (and its associated pass-thru from client to service) to common/ops/sell which would set qty=0
2) Create a secondary endpoint and common/ops function for sellAll

I'd prefer #1, especially since method 2 would duplicate a buncha code, but I don't know y'all preferences on modifying existing stuff vs adding new. Since each item doesn't have its own guid or anything and is just a count this seems pretty straight forward to add a deleteAll flag to the params

**Comment by Alys** [comment]
Should `deleteAll` be `sellAll`?

Option 1 sounds best to me too, but if other admins disagree, go with what they say. I think it's likely that at some future time, we'll have support for selling a specified number of items, so it would be neater to have only one route that can handle 1 item (the default) or N items or all items.

In the API, I wonder whether this needs to be implemented as `sellAll` or whether it should be implemented just as an integer number of items to sell. The client could still have a "sell all" option but it would pass the current number of items through to the API. The API would have a check to make sure that the number passed through was not larger than the number owned (necessary because sync errors might cause the browser to think that the user had more items than they actually do). If the number passed through was too large, we could either return an error (but that's **really** not friendly to a website user suffering from a sync error) or just sell the number owned without an error or warning.

Another possibility is that we would not do a "sell all" button in the client but instead have a "sell N items" form where N is initially set to the total number of items. There could still be the sell one button for quick selling of small amounts.

@joshuaohana How do you feel about these ideas? I realise I'm hijacking the feature request a bit so I have no objections if you want to stick with the idea of adding a "sell all" button in the client. :) We are actually part way through a website improvement project, so further enhancements to the selling feature could be done during or after that. However I think it would make sense to change the API now in a way that would work well for both this current issue and future enhancements.

Important: Regardless of how this is implemented, when a player uses the "sell all" option (or a "sell N" option), they should be given a confirmation step. It should be a custom built popup (not the browser's default alert popup). Something like what you see when you leave a guild would be good.

**Comment by joshuaohana** [comment]
@Alys I am all for a sell N instead of sellAll. Could just be a text input (or slider?) that defaults to 1, and a param input on the api side. I'll get to it!

I'm not sure how approval or whatever works... am I "approved" to do the feature as you suggested above or do we need to go through the Trello board or anything?

Implementation plan;
1) UI - change sell dialog to allow quantity selection (thoughts on slider vs input box? I think habitica doesn't have any existing sliders...)
2) UI - create custom dialog for confirmation, model after leave a guild popup
3) Server - modify existing sell route to account for param.qty
4) Common.sell - using param.qty to delete selected qty and credit gold*qty, if qty > available, treat as sell all

**Comment by Alys** [comment]
@joshuaohana I think a text input would be better than a slider since it's probably easier to specify the exact amount you want to sell, especially for people with motor difficulties who might have trouble using the slider precisely.

My personal preference would be for `quantity` rather than `qty` in the code. Not sure if you were going to do that anyway and were just abbreviating it here. :)

You are definitely approved to work on this! :) I personally like your plan. I recommend though waiting a day or two before starting in case other admins have other comments to add. I'm not the most experienced admin with respect to the API!

**Comment by joshuaohana** [comment]
Sounds good thanks @Alys 

Agreed, quantity does look better, was just abbreviating here but intended to follow whatever naming conventions already existed in the code ... having a poke through the code seems quantity is used most of the time, but qty is used once in the analytics service, lol, guess I'll be going with `quantity` :)

**Comment by joshuaohana** [comment]
Unfortunately barely had any time to work on this save a few minutes here and there... much of which was getting used to navigating around the code base. Coming along well enough though should have a first pass done soon enough. As far as the UI goes, do we want to keep the existing button with the sell one going on and add in the new stuff, or just replace it all with an input+button where the input defaults to 1.

Having some trouble getting the layout to behave, new to jade and there's lots of stuff going on in here, but use your imagination for how it's "supposed" to look :)

The actual work is going fine per our plan, plus the input now won't let you go higher than your inventory - you mentioned something about splashing an error or something like that figured this was cleaner.

![screen shot 2017-02-09 at 10 13 49 pm](https://cloud.githubusercontent.com/assets/9626754/22816158/123ecf84-ef15-11e6-9cf8-d3b7399513ce.png)
![screen shot 2017-02-09 at 10 01 42 pm](https://cloud.githubusercontent.com/assets/9626754/22816157/123c51dc-ef15-11e6-8dd1-d6d581225282.png)

**Comment by Alys** [comment]
No worries about the delay; this isn't a high priority change.

I think you can get rid of the existing "sell one" button. 

I like the top screenshot with the wide button. That will be good for those languages where the translated strings are longer than in English.

**Comment by Alys** [comment]
I'm closing this since we have an item in Trello for it, and we're part way through a website improvement project that will make this feature request easier to add in the not too distant future.
