### ISSUE TITLE
Gems went missing

### ISSUE THREAD

**Issue by vegetalover168** [HabitRPG/habitica#5816]
So I had just recently bought some items with gems, and I still had some left over but when I logged in today they were all gone. I'm not exactly sure how many I had, but I would like to know where they went.

ID: 0b2bf43b-391b-48af-a57f-8396c20dba98

I am using google chrome.

**Comment by Alys** [comment]
How many hours ago did you last see the gems in your account? Please do report it as a number of hours ago, not as a specific time because timezones make specific times hard to deal with. If you are not sure how many hours ago, please give a range.

**Comment by vegetalover168** [comment]
I believe it was around 19-22 hours ago.

**Comment by Alys** [comment]
@vegetalover168 I downloaded a database backup that had been made about 24 hours before your last comment. It shows that you had 29 gems then, whereas when you first logged this issue (after the database backup was made) you had zero gems. However it also shows that your account made some purchases in that timeframe. When you logged this issue your account had 6 Deer eggs and 3 Deer pets (base, desert, golden) which weren't in the database backup - i.e., your account had obtained 9 extra eggs. The eggs must have come from purchases because your Ghost Stag quest achievement didn't increase in that time, so that accounts for 27 gems (the eggs cost 3 gems each). Your account also had increases in the feeding status of a few pets, which could have come from food drops or food purchases. Food pieces cost 1 gem each, so if 2 pieces of food had been bought, it would account for the remaining 2 gems that you no longer have.

Is it possible that someone had access to your account in the past day? Perhaps a sibling that enjoys buying, hatching, and feeding pets? Or did you leave your account logged in on a computer that other people have access to?

If you'd like a more thorough investigation, there is a database backup made about 12 hours before your last comment which I could examine, so it might be able to narrow down when the gems were spent. However downloading and importing database backups takes several hours, plus the manual time required to examine the account data, so I would not be able to get more information for you until at least this time tomorrow.

**Comment by vegetalover168** [comment]
Oh ok, cool. If the gems were all used on food and pets, that's fine. Must have been the roommate (who also has an account). I just didn't know it happened so I thought it might have been a bug.

Thanks!
