### ISSUE TITLE
Party member did orb of rebirth, party took huge amount of damage from boss

### ISSUE THREAD

**Issue by vg19** [HabitRPG/habitica#5817]
My User id = 99ab5aa5-ef23-4745-917a-2a8d14b6ea32
Party id = 99a69809-4cb2-446b-bc92-9cf41d576438
Party member who did orb of rebirth = cae108a4-5ba4-400b-a37f-39df47376b0b

Party member did orb of rebirth, this seems to have forced a cron that caused us to take major damage, killing us all.

Cindy4651 attacks Necro-Vice for 228.1 damage, Necro-Vice attacks party for 71.8 damage

At least I'm assuming that's what happened - it was nowhere near her regular cron time, but she's away for the weekend.

I don't think browser is relevant to this problem,.  I'm using Chrome, no idea what she's using.

**Comment by Alys** [comment]
It's very unlikely that the Orb of Rebirth caused this because it doesn't affect cron in any way.

If Cindy4651 is out of town, they might be under a different schedule than normal and so might have logged in at an unusual time and might not have done their usual Dailies.

If they're in a different timezone than normal, or if they changed the time on their PC/phone/tablet, that could have triggered cron to run at a different time than normal.

Your party can use Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to recover from the unfair damage, including giving yourselves enough gold to buy back lost equipment.

We're tracking the timzeone issue in https://github.com/HabitRPG/habitrpg/issues/3806 so I'm closing this one but if Cindy4651 would like us to investigate further, they can comment here and we'll reopen. Also, if you have any questions about using Fix Character Values, comment here or ask at Help menu -> "Ask a Question". We'll see and respond to all questions here even though this is closed.

We're planning changes to cron that will make it possible to avoid damage like this from unexpected crons.
