### ISSUE TITLE
Base drop chance doesn't make sense

### ISSUE THREAD

**Issue by wfenza** [HabitRPG/habitica#5819]
The code to calculate the base drop chance is:

chance = _.min([Math.abs(task.value - 21.27),37.5])/150+.02

If I'm reading this right, it means that the more negative a task's value, the higher the drop chance (but caps at 27%), and the more positive a task's value, the lower the drop chance. Then if the task's value exceeds 21.27, the drop chance begins increasing again, and likewise caps at 27%. 

For instance, a task with a value of -5 would have a base drop chance of abs(-5 - 21.27)/150 + .02 = 19.5%
a task with a value of 15 would be abs(15-21.27)/150 +.02 = 6.18%
a task with a value of 35 would be abs(35-21.27)/150 +.02 = 11.15%

It looks like this:

![image](https://cloud.githubusercontent.com/assets/13708824/9386629/64abbd3e-472a-11e5-911a-49c4e7686c21.png)

Is there some reason why we want the drop chance of blue tasks to decrease as the value increases, but then increase again after exceeding a value of 21.27? It seems kind of arbitrary.

**Comment by Alys** [comment]
A high chance for very red tasks encourages you to do tasks you've been bad at / procrastinating on. A high chance for very blue tasks rewards you for doing well consistently. I don't know if that was intentional but it doesn't seem too unreasonable. 

It's possible that the limit of -47.27 was meant to be in the calculations as well, to match the calculateDelta code, but was forgotten.

I'm not sure it really matters if it's arbitrary. However you're welcome to propose changes! Please be aware that we might not necessarily accept changes, so you might like to comment here first with a brief description of what you have in mind before going into more detail or submitting a pull request.

**Comment by Alys** [comment]
I'm going to close this for now, but if you'd like to suggest a new algorithm for consideration, you're welcome to comment here.
