### ISSUE TITLE
Can't abort quest, no progress being made

### ISSUE THREAD

**Issue by Rhiana** [HabitRPG/habitica#5825]
I started a quest with my party a while ago and found that I cannot abort the quest, nor has any progress been made in that time even though I have been playing on and off.

I would like to abort the quest and start a different one but the abort button does not show up (see screen shot). I am the group leader and believe I started the quest. 
Group ID: 93e41c1e-8278-4901-b048-6dcb4a300764 
UUID: f5feea9c-3a32-445a-902a-75430e1c4b04

Thanks

![habit rpg quest bug](https://cloud.githubusercontent.com/assets/5127756/9432748/07aa54b2-4a6b-11e5-8eb0-90f9cea9c127.png)

**Comment by Alys** [comment]
@Rhiana Can you please click the "Fetch Recent Messages" button and also scroll the quest box up to show the top of it, and then take another screenshot. Then please click on the "participants" tab in the quest box and take a screenshot of that.

**Comment by Alys** [comment]
Please also reload the party page before taking those screenshots. That will ensure that the latest information appears in the quest box.

**Comment by Alys** [comment]
@Rhiana Don't worry about the screenshots. I'm home from work and have looked at the database records. Here's what happened:

Last year, you were on the Egg Hunt quest, with at least one other in your party. That quest ended and it looks like you received the quest achievement and the 10 Plain Eggs that are part of the quest rewards. (BUT if that was actually the second time that you personally had done the quest, a bug might have prevented you getting the second set of rewards - tell me if you think that's the case and I'll give you the extra Eggs and achievement.)

After that quest ended, the same type of quest was started again by Lusankya and you were not part of that quest. Lusankya probably started the quest before you'd had a chance to accept the invitation. That's why you personally have been making no progress towards the quest this year.

Lusankya hasn't logged in for many months, so I'm going to cancel the quest. If you reload the party page in about five minutes from now, you should see that it's not there any more.

I'm going to close this now but do feel free to comment if you have questions or if there's still anything wrong. We'll see your comments and can reopen this if needed!

**Comment by Rhiana** [comment]
Thanks for that it's all working now. I'll make note of the screenshot criteria for future issues.
