### ISSUE TITLE
Guild chat notification window closing when x is clicked

### ISSUE THREAD

**Issue by Dewines** [HabitRPG/habitica#5845]
In the past, you could dismiss one or more of the notifications in the little guild/party chat notification window and then click on the guild you wanted to read. Now the box closes after each click, which is not as user-friendly as it was before. Someone has mentioned this problem in the Tavern, so I know it's not just something odd that's happened to my browser. 

It happens in both Chrome and Firefox on my pc running Windows 10. When I asked about this in the Aspiring Socialites guild, @Alys said that it was an unintended consequence of a fix to make menus no longer stay open inappropriately when you change to another page. However, in this particular case, the new behaviour is inconvenient so she suggested that things should be adjusted to get the old behaviour back for this particular situation.

**Comment by Alys** [comment]
This is the PR that I think is related: https://github.com/HabitRPG/habitrpg/pull/5812

I too would like to be able to remove individual notifications without the menu closing.

If that's not possible, one alternative would be to have a "clear all" option in the menu that removes any remaining notifications. Or both would be nice. ;)

@Castanwydden Unfortunately we might not be able to work on this soon due to more urgent priorities. :(

**Comment by TheHollidayInn** [comment]
Ah, I see why this is happening. I'll take a look into it today.
