### ISSUE TITLE
Habitica loads on one Windows user but not another (Firefox)

### ISSUE THREAD

**Issue by Taejang** [HabitRPG/habitica#5868]
Windows 7 Pro x64, Firefox 40.0.3, two user accounts (Y and Z). Possibly related to #3486

Using the same installation of Firefox 40.0.3, Windows user Y can use Habitica perfectly fine. If Windows user Z logs in, Habitica does not load. To be precise, the landing page loads but after clicking "play the game" in the upper-right, the blue loading bar moves slowly across the screen, pausing for a minute or so at roughly 98% completion, and disappears. The popup to log in does not appear.

Both Y and Z can log into Habitica on Y's Windows account and it works fine. Both Y and Z can use Habitica in Chrome on either Windows account.

Examining the Firefox profiles, user Y has Adblock installed, while Z does not. This comprises the only difference in addons/extensions/etc. NoScript is installed for both users, but even with all scripts globally allowed, Windows user Z still does not receive the login popup. Neither user has any toolbars installed. Clearing the cache did not resolve the issue.

**Comment by Alys** [comment]
Please ask the person who cannot log in to Habitica on one browser to log out of Habitica, then clear cache and cookies, and also clear local storage on that browser for the habitica.com domain. They should google how to clear local storage on that type of browser if they aren't sure - it's different than clearing the cache and it's important that it be done. Then close all browser windows, reopen, and try again.

If that doesn't work, please ask them to comment here. They should include any messages that might appear in the Web Developer -> Browser Console when they try to log in.

They should also include their Habitica User ID. They can find instructions about how to get that from Help -> Report a Bug (step 6). I'm afraid they can't really remain anonymous if we need to help them fix this.

If they'd prefer to remain anonymous, I'd recommend that they keep using Chrome. Please let us know if that's the case so that we can close this.

**Comment by Alys** [comment]
They should also include their Habitica User ID. They can find instructions about how to get that from Help -> Report a Bug (step 6). I'm afraid they can't really remain anonymous if we need to help them fix this.

If they'd prefer to remain anonymous, I'd recommend that they keep using Chrome. Please let us know if that's the case so that we can close this.

**Comment by Taejang** [comment]
Anonymity was unintentional; just trying to make it easy to follow the descriptions. I'm not sure Erky (user Z) will be excited to figure out how to clear storage, so I'll make time to do so tonight. The Habitica ID shouldn't make any difference, as the login popup never appears and therefore no user can log in at all. If for esoteric reasons I can't fathom you still want the ID, I'll provide it.

**Comment by Alys** [comment]
The reasons for asking for user details aren't esoteric but practical. As a general guideline, it's best to not start troubleshooting a problem until all basic information has been collected. Amongst other reasons, it helps us to correlate related incidents; for example, a person might have reported a bug in the past which might be related to a current issue. Also it's not uncommon for a person to report the same problem in two places, which leads to duplication of effort if we can't identify that it's a duplicate. These reasons might be irrelevant in many cases but we can't know that until we have information about the person experiencing a problem.

**Comment by Taejang** [comment]
Ah yes, the human problem. I do so often get bogged down in the technical that I forget the silly things we humans do at almost every turn. Erky's ID is unlikely to be the one you want for cross-referencing; mine would be the desired one. If you do still want Erky's, it'll have to wait til tonight. Here is mine info:
Taejang, 017947cd-7825-4287-8a40-4946f7df5b23

**Comment by Alys** [comment]
Since there's been no updates, I'm assuming that clearing local storage etc fixed the problem and I'm closing this, It can be reopened if it's still happening.
