### ISSUE TITLE
Show number of To-Dos

### ISSUE THREAD

**Issue by sgabler** [HabitRPG/habitica#5869]
Hey guys,

I just wanted to check how many To-Dos were still open (it's a lot!), but there was no option other than counting or using the JS console to check it. How about showing the number somewhere?

Some ideas:
- put it at the very top (next to the word To-Dos)
- display a number in each of the tabs "Active", "Dated" and "Done
- have an info button which triggers a popup
- make this optional by having a setting in the options? (possibly overkill)

Other ideas? Do you think this is a useful feature? I couldn't find any issues here that were dealing with this, but I think this could be useful for some people.

To make things consistent, this could also be shown for Habits and Dailies

**Comment by Alys** [comment]
This is a feature request rather than a bug, so could you please suggest it
under Help -> Request a Feature? Having all feature requests collected
together allows people to vote for features and helps us choose which
directions to develop the site.

Until/if this is implemented, you can go to Data -> Data Display Tool and
use the Task Statistics section.

**Comment by sgabler** [comment]
Alright, will do. I actually had this feature request board open, but somehow thought that my suggestions were too small to actually be considered a feature
