### ISSUE TITLE
Collection quest: user found NaN items

### ISSUE THREAD

**Issue by dfecko** [HabitRPG/habitica#5882]
My party was doing the golden knight, part 1 quest.  One of the users reported the following in the party chat:

`mokano7 found NaN Testimonies.`

It happened on 9/2/2015 14:21:37 MST (UTC-7).

Group ID: fc2ac851-37d0-4f10-991c-1458952e453c

**Comment by SabreCat** [comment]
When did you start the quest? Was that the first time the user checked in after the quest started?

**Comment by Alys** [comment]
Since there's been no updates, I'm assuming that this is no longer happening and I'm closing it. If it is still happening, please see the questions SabreCat asked.

**Comment by shanaqui** [comment]
Looks like user Olia (3f6a57c5-9321-408b-8ed6-db58dde1ad5a)'s party just had the same bug, which caused immediate quest completion. They'd started the quest six hours before, so it was probably the player in question's first cron since the quest started, but that's all I know. Hopefully Olia can give more details later!
