### ISSUE TITLE
wrong time zone for Moscow?

### ISSUE THREAD

**Issue by goffyara** [HabitRPG/habitica#5898]
Daily tasks renew at 23:00

**Comment by Alys** [comment]
Habitica uses the time and timezone set on your PC or mobile device. Please check the time and timezone to ensure that they are correct for the area you live in.

Also, look to see if you've set a [Custom Day Start](http://habitica.wikia.com/wiki/Custom_Day_Start) time. It it's set to 23, then your Dailies won't reset until you use Habitica after 23:00.

**Comment by Alys** [comment]
@goffyara I'm going to close this since behaviour like this has so far always been attributable to a Custom Day Start or to time settings being inaccurate, however if you have questions about any of this, ask here or go to Help -> Ask a Question (from the Habitica website's menu).

If you think there is a bug with your account, please tell us your User ID (not user name) - to find that, go to Help -> Report a Bug and see the information in step 6. We can reopen this if needed!

**Comment by goffyara** [comment]
thx
