### ISSUE TITLE
Health Points Dropped Mysteriously

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5902]
After setting up my account yesterday, I reloaded my Habitica this morning and my health mysteriously dropped 4 points for no reason. I even checked off one of my "Dailies" (drink water in the morning). Shouldn't this have boosted my health? Am I doing something wrong? 
![screen shot 2015-09-09 at 8 57 09 am](https://cloud.githubusercontent.com/assets/13575750/9767006/d63552de-56d0-11e5-83fb-16b60bcf4004.png)

**Comment by Alys** [comment]
Hi @LortheDoorLord. Health is removed overnight for any Dailies that were due but not completed. You can get Health back by levelling up or buying a Health potion. There's more details on the wiki's [Health Points](http://habitica.wikia.com/wiki/Health_Points) page. If you have questions about it, click on Habitica's Help menu and then "Ask a Question". That takes you to a guild where there's many experienced, friendly users who can help with almost any problem.  You are also welcome to reply here if you wish and we'll respond, but the Ask a Question link generally gets you an answer much faster because there's many more players there. :)

**Comment by ghost** [comment]
Ok. Thank you! I will remember that if I have a problem next time.
