### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by WolfKaN** [HabitRPG/habitica#5907]
I just logged in today and found that I lost all the foods I've earned last night and the zombie wolf mount I was riding downgraded to a zombie wolf pet.

**Comment by Alys** [comment]
When changes that previously appeared to be applied are later reverted, it's an example of this bug: https://github.com/HabitRPG/habitrpg/issues/4313
It's most commonly seen with tasks that were ticked becoming unticked, but it can also apply to drops and pet actions. The tasks that you earned drops from have most likely become unticked, so check your To-Dos for items that you can tick off again (Dailies and Habits could also have been affected but it's harder to tell which ones).

If you find it happening often, see the Advice section near the top of that issue (that's really the only part you need to read). In brief, try reloading the page with your browser's refresh button often, because that helps to ensure that your actions are sent to the server for permanent recording.
