### ISSUE TITLE
Killed after using skill

### ISSUE THREAD

**Issue by awoitte** [HabitRPG/habitica#5914]
I was at nearly full health and used the skill "pickpocket". For some reason I was killed as a result (and lost a level and equipment etc.).

This is the third time I've died in as many days. The first two times I assumed was due to a strong boss, but looking at the numbers they don't quite add up. I think the past deaths are related to the same bug.

User ID: 26a8b996-7702-40ac-9997-e3e44f309e0f
Browser: Chrome
OS: Windows 7 and 10

It may be unrelated, but I access Habitica from two different computers. Perhaps switching caused CRON to run too many times?

**Comment by awoitte** [comment]
More relevant info: Dailies that used to be checked are being un-checked. This happened yesterday as well.

**Comment by Alys** [comment]
The skill would not have caused your death directly. Instead, it would have triggered cron. When cron runs twice in the same day and you're using Habitica on two or more devices, it's almost always because the devices have different times or timezones. Please carefully check the time AND timezone on both your PCs and if they aren't identical, change them or try to avoid using Habitica on one of those PCs if you can.

**Comment by awoitte** [comment]
Yes, that makes sense. They are intentionally in different timezones. I guess I'll have to refrain from accessing Habitica with one of them.

Thanks for the help.
