### ISSUE TITLE
Dying before daily rollover

### ISSUE THREAD

**Issue by SkylarkLanding** [HabitRPG/habitica#5918]
Opened iOS app to check off my dailies and was informed I had died, likely due to not finishing dailies earlier. This shouldn't have happened though, as it was 2am and my daily rollover is at 4am. I can reset my streaks in the browser on my laptop, but I've still lost a level, an item, and all my gold. My best guess is that this is related to when it thinks the day changes, but as mentioned that shouldn't have happened yet. 

User ID: 28ba8f25-f0fd-4438-9abd-eee9b794435e
##

**Comment by Alys** [comment]
@SkylarkLanding I think this might be caused by a time or timezone issue on the device(s) that you use Habitica on. Could you please read [this issue](https://github.com/HabitRPG/habitrpg/issues/5919)? The final paragraph might be the most relevant but you should read the others two. 

Please comment here in this issue that you logged if that information doesn't seem to be relevant.
