### ISSUE TITLE
Dailies reset at wrong time / Cron ran early or twice / Health loss or death caused by undeserved damage from Dailies

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5919]
The information below is important for you to read if you experience any of the following problems:
- **your Dailies reset at the wrong time** or reset twice in one day
- you took a large amount of **unexpected health loss** that can't be explained by damage from a quest boss due to a party member's incomplete Dailies
- your party chat shows that **you caused two quest boss damages in one day at different times**
- **cron ran at the wrong time or twice in one day** ("cron" is the process that resets Dailies and assigns damage - i.e., it can cause the three points above)

Habitica uses the timezone set on your own PC or mobile device. It uses that timezone to determine when to reset your Dailies and cause damage from incomplete Dailies.

If you change the timezone on your PC or mobile device, it is possible for cron to run a second time that day. After that day, cron will behave normally. If you need to change the timezone, [Rest in the Inn](http://habitica.wikia.com/wiki/Rest_in_the_Inn) before changing the timezone and for the remainder of that day so that you aren't unfairly damaged.

If you use Habitica on two or more PCs or mobile devices, then it is very important that all those devices have the **same timezone**. If they do not, then cron is likely to run twice **every** day. If you are getting unexpected damage and resets of your Dailies, please carefully check the timezone on all devices. If any of them are different, change them so that they are the same. If you are unable to change one of your devices, it is best to not use Habitica on that device.

Please note that you do not need to read the comments below to get more information about this issue. All relevant details are above. However you are welcome to comment if you have questions about the specific details above. Any other problems should be reported in a different issue (see [Help -> Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760)).

If you or your party mates suffer from unfair damage because of this, on the website you can go to [Settings > Site](https://habitica.com/#/options/settings/settings) and click the [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) button to restore lost health, gold, experience, and level.
##

**Comment by lauragyre** [comment]
Hi, I'm having an issue with this, I think. My day is set to reset at 4:00 AM. Last night I completed several tasks between 10:00 PM and midnight. When I went to bed, it looked like all my dailies were done. This morning, it looked like I didn't get credit for finishing my dailies yesterday, I took damage from the boss I was fighting, and the tasks I finished last night were already checked off for today. My devices have the correct time for my time zone...any clues?

ETA: my user ID is 6a744a7f-7eca-4123-ae3c-2130da9b1e8a and I'm using Chrome on OS 10.6.8.

**Comment by Fancazzone** [comment]
Hi there. This is a bug that I don't know if it concerns me or another member of the party. Being a rogue, I usually cast 'tools of the trade' first thing in the morning to give a buff to all my party members.
When I do it this, everybody gets the buff (I checked). In the case of one of my party members, however, the next time he logs in after I have launched TotT, his character loses the buff. 
The interesting thing is that this does not seem to happen in reverse: he, being a warrior, usually casts 'valorous presence' and 'intimidating gaze' and the STR and CON bonuses he gives stick with everyone, including me, for the rest of the day.

My user id is 1799656c-e917-4200-9099-4ea81f07b10e

**Comment by Alys** [comment]
@lauragee Please see this issue: https://github.com/HabitRPG/habitrpg/issues/5941. It would have caused the problems you described. I'm sorry about that!

@Fancazzone That person will be losing the buff because his [cron](http://habitica.wikia.com/wiki/Cron) runs after you cast it. This is expected behaviour rather than a bug, although obviously not desirable in this case. If you have more questions about this, please go to Help -> Ask a Question on the habitica.com website, and we'll explain in more detail there!

**Comment by nyeung01** [comment]
@Alys I have the exact problem as you specified from the opening post. However, the tasks are running again from the previous day. In this case, today's Saturday, but it's rerunning Friday's tasks. I made sure the timezone and time are set correctly on all devices. From what I can assume will happen is that by tomorrow it will run today's tasks if the issue persists. I'll keep you posted if I see any changes or if the issue is unsolved. Here's a screenshot of the issue in case you need to see it:

![image](https://cloud.githubusercontent.com/assets/5438161/9977094/9fd05e4a-5ec9-11e5-8750-5207e4a98519.png)

![image](https://cloud.githubusercontent.com/assets/5438161/9977100/bdeb603c-5ec9-11e5-9a3d-a99462f3ca8d.png)

Thanks for being aware of this issue.

**Comment by Alys** [comment]
@nyeung01 Are your Dailies resetting the first time you use Habitica after 11pm (23:00)? If so, there's no cron bug. You are seeing active Dailies for the previous day because your Custom Day Start time is 11pm. Please see [this comment from me](https://github.com/HabitRPG/habitrpg/issues/5476#issuecomment-114787008) to explain how a CDS of 11pm works. You're welcome to ask questions if you'd like any clarification about that! However, could you please put the questions into that issue rather than this one?

**Comment by nyeung01** [comment]
@Alys Ahh okay, and thanks for the redirection. Now I understand why that was happening. I apologize for posting in the wrong issue.

**Comment by Raibean** [comment]
This is happening to me! It reset last night EARLY and again TODAY! My computer and phone are both set to the same time zone. User ID is 0b66bb30-8328-4e27-b2c6-7d293c57d52f and I'm using google chrome on a Windows 8 computer.

**Comment by AdrianTP** [comment]
I have been experiencing the same issue as @lauragee for several days (marking tasks off after midnight but before my cron time and them being marked as missed for the previous day and checked off for the next day). The fact that it has been happening for several days tells me it is unlikely to be issue #5941. This has messed up most of my streaks, and I cannot recall what they used to be, so I cannot fix them.

I suffered an additional issue and unexpected death today. My cron is set to 3 AM, and I just got home around midnight tonight after spending all day at an event which precluded me from checking my phone a bunch. As soon as I logged in, I died (and apparently dealt 0.4 damage to the boss my party and I are fighting before it dealt me 17 damage, despite not having checked anything off and despite not having missed any tasks yet). I had yet to check off any tasks for the day, and had logged in specifically to mark off some tasks I had completed much earlier in the day. I would just manually fix my stats and gold but I do not remember how much experience, gold, or silver I had.

And yes, the time zone and time on both my laptop and my phone are set correctly.

My User ID is dbd1f6f3-cb5e-4bb2-b4f5-cc759e7540e2.

**Comment by Alys** [comment]
@AdrianTP Because your time zone and time on both laptop and phone are set correctly, you aren't suffering from the problem described in this issue. Issue #5941 has been closed and is not happening any more, so it won't be that either. Dailies being marked as missed for the previous day and ticked for the next day is probably a sign of https://github.com/HabitRPG/habitrpg/issues/4313 - please see the "Advice" section near the top of that issue. Comment in that issue if you have any questions about what you see there. I'm sorry it's causing so many problems for you!

**Comment by HFranzen** [comment]
I'm experiencing the "2 times cron" problem. 
Last night the time was set from summer time to winter time at 3 am in Germany and I logged in (non moblle, although I guess that is not relevant) right after my cron (midnight). When I logged in this morning I had another day change that said the former change took place one hour before cron. 
My user ID is 34f7dd57-1ce7-4831-b5f7-c2b4e2cd1c73

This will probably appear a lot while countries change their times, which is why I'm mentioning it here.

**Comment by d1bbe** [comment]
I had cron run twice last night, and the second time it reset all my streaks and inflicted some damage to me. Looking at the chat history, I see a message after midnight, and another this morning shortly before 9. Between the two chats, Europe went back to standard time, as HFranzen noted above. I wonder if that triggered the issue. All my devices are set on the same time zone: CEST/CET.
My user ID is 0c0162b0-082d-4b37-a1f6-7428f84e3220.
It's not a sync issue, as I checked the state of all my dailies a few minutes before midnight using the Data Display Tool (I have a screenshot).

**Comment by jchiasson** [comment]
Often when in a boss fight with my party it is showing that I am doing damage and receiving damage twice at once when I log in. I think it's mostly when I log in on my phone instead of computer but I'm not certain of that. Both my phone and computer have the same time zone and my roll over time is set to 12 midnight. My user ID is fb257b2d-7f49-4631-bb29-a4f90af939bc It's been happening for a while but I thought it was just a glitch in what I was seeing but my party members confirmed that they are seeing double damage from me as well.

**Comment by Alys** [comment]
@jchiasson That's this issue: https://github.com/HabitRPG/habitrpg/issues/2805. You can follow it for progress reports although currently we don't know what causes it.

**Comment by joekatzman** [comment]
I'm noticing a real problem with Daylight Savings Time. Ever since that ended, the time on all my devices is correct but Habitica resets at 11pm (which would be midnight if DST was still operative). This has been 100% consistent, and really screws up my days,

**Comment by Alys** [comment]
@joekatzman The timezone on at least one of your devices is almost certainly incorrect.

**Comment by joekatzman** [comment]
> "Habitica uses the time and timezone set on your own PC or mobile device. It uses that time to 
> determine when to reset your Dailies and cause damage from incomplete Dailies."

I assume this doesn't mean any computer I've ever logged into Habitica from, just any machines showing the web page or running the iOS app.

@Alys I've double-checked. All devices in question show the identical and correct time, and are set automatically by Apple to the Pacific Time zone (GMT -0800). The end of Daylight Savings Time, which Apple adjusts for automatically, was the catalyst for errors to begin. And I am getting 2 cron hits per day, at 11:00pm and then midnight.

Will try resting at the inn for a day, and shutting down the laptop, iMac, and app entirely.

**Comment by Alys** [comment]
@joekatzman When you log in to the Habitica website (literally log in, using the login form) or when you reload the website in an existing browser window, or when you open the website in a new window, Habitica reads the timezone of the machine you are using, and it stores that timezone in your Habitica user account and uses it from then on. When you next perform any of those actions on the same machine or a different one, it reads the timezone again and replaces the stored zone with the new one.

I don't know exactly what triggers the Habitica/HabitRPG mobile apps to read your phone's  timezone, but I'd guess it was something similar.

Whether cron runs or not depends on the timezone stored in your Habitica account (i.e., the timezone of the device that you last logged in on or reloaded on). Thus if you are using two devices with different timezones or different daylight savings settings, you are likely to get more than one cron in a day.

**Comment by Athena-Eleven** [comment]
I just had this issue for the first time after having no issues since I joined a couple of months ago. Last night I got home at 1am (my cron is midnight) and I'd already ticked off all my dailies using the new app while I was out and about. I went on my computer and cron happened all fine, no damage and I found 12 items towards the quest I'm currently doing. I refreshed the page (as I also do to double check everything is up to date) and it was all good so I closed all windows and went to bed. However, when I went on this morning, cron happened again, I found 1 item towards the quest (because I ticked off one thing after the first cron), and all my dailies except the 2 that weren't due yesterday have had their streaks reset to zero and I lost a ton of health. I don't have any devices on different timezones. I'm wondering if this issue could have been triggered by using the new app, as it is the only thing that is different from what I've been doing previously. Can anyone tell me what I need to do to avoid this happening again? Perhaps I should just not use the new app at all?

**Comment by joekatzman** [comment]
A11, you might try shutting down the app on your phone, so it isn't running at all. Then sleep at the inn. Then shut down the browser entirely, and restart your computer.

That's basically what I did. Even though both computers and the iPhone had the same day/time setting (verified), the full shutdown + inn did seem to fix my dual-cron problem. I have since gone back to using the phone app and computer together, with no issue.

**Comment by bluebird8203** [comment]
My cron has been running at the time that I first load the web page or android app on any given day.  It should be running at 2am.  I verified that my time zone is the same on both devices.  Tonight I logged in about 630pm, and the party chat reports me as causing damage to my team at that time.  I"m not sure what to do next.

user id - bf4fcb13-9288-4154-9cdc-bb314d18efb6
running Chrome on Windows 10

**Comment by tsunamipebble** [comment]
Hi, my issue is that only ONE of my dailies seems to have a reset time different than the others. And it resets twice. 

I discovered it caused me health damage on Thursday when I was sure that I had checked it off on Wednesday. So on Thursday the first thing I did was check that as complete. Through the day I completed all my other dailies so they were all done. By chance I couldn't get to sleep last night and made a note on my phone and popped in to see the list. At 10:30pm, this one daily was now unchecked!

I am running Habitica on my PC as well as my Android phone. My user ID is bd6940fa-7685-44fb-993d-335cebe24a40. 
Also this morning a string of random numbers and letters appeared as something that a "third party API" had added--but I didn't use any third-party APIs to add to my list. Unfortunately I deleted that before I thought that it might be useful information.

**Comment by Alys** [comment]
@tsunamipebble The Daily has been affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313 -- see the "Advice" section near the top.

For the Habit, please see the top post in https://github.com/HabitRPG/habitrpg/issues/1402 (in brief, it was safe to delete the Habit and it hasn't damaged your account).

**Comment by joekatzman** [comment]
For me, the real issue appears to be the way Habitica handles cron - not "a set time and we'll notify you later," but "it doesn't trigger until you log in." The distinction is invisible for things like hit point loss, but highly visible for things like Buff skills,

**Comment by Alys** [comment]
@joekatzman The problem described here of having different timezones on your devices really does cause cron to run more than once a day. It's not related to the way that cron runs only when you use Habitica (which has advantages over running cron at a specific time regardless of usage - for example, if you can't use Habitica for several days, you don't suffer from crons on all those days).

Buffs wearing off before you can use them is a separate problem and is being discussed at https://github.com/HabitRPG/habitrpg/issues/2523. You'd be welcome to add any ideas you have!

**Comment by harleyalexander** [comment]
@Alys 
Hello!
I'm having the issue that cron triggers twice a day. It has caused me to die and lose all the things I've worked hard for. The time zone on the website settings tab shows a UTC -4:00 but my computer shows UTC -5:00. I've reloaded the page and restarted my computer but the website does not change. I don't know if this is the issue because cron triggered at 12:00am and then at 7:00am, killing not only me, but injuring my whole party. Is there any way to roll back this issue and get my level, gold, and equipment back?
Thank you!

**Comment by Alys** [comment]
@harleyalexander I've updated the first post in this issue to describe how to recover from the unfair damage (see the last paragraph, but in brief, you can use Settings > Site > Fix Character Values). We'll need to talk to you some more about the problem you're having, so please log a new issue as described in the second-last paragraph (in brief, go to Help > Report a Bug and follow the instructions there, especially point 6 about how to find your User ID).

**Comment by harleyalexander** [comment]
Will do!
Thank you for the quick response!

**Comment by Bottl** [comment]
My cron ran twice, so I dealt 837.2*2 dmg to our boss, this happen to anybody else since the recent maintenance?

So I know how to reset my character values but can some staff member give me the quest scroll back please? (Iron Knight)

**Comment by Alys** [comment]
@Bottl Could you please tell me your User ID? To find out how to get it from either the website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu).

**Comment by Bottl** [comment]
Silly why didn't you just link me to the API
<https://habitica.com/#/options/settings/api>?
7a1db680-def0-4bca-924d-4f271def1cd9

**Comment by Bottl** [comment]
Silly why didn't you just link me to the [API](https://habitica.com/#/options/settings/api)? 7a1db680-def0-4bca-924d-4f271def1cd9 Thanks

**Comment by Alys** [comment]
@Botti I didn't link you to that page because I didn't know if you were on the website or the app, and if you were on the app, then getting to that API page would not have been as easy for you. The page I linked you to has information that helps app users find their User ID as well as website users. It also has other useful information about reporting bugs, which might help you if you ever have to report a bug again, and the text I used provides the shortcut for getting to the page, which is helpful for those players who do use the website.

I've looked at the quest progress messages for the damage you did, and they both occurred at the same time. This means that the problem would not have been caused by your timezone being incorrect on any of your devices, so you can ignore the advice given at the top of this page. I've adjusted that text to make it clearer now that the problem is not related to two messages at the same time - sorry about the confusion! Instead, you were affected by this bug: https://github.com/HabitRPG/habitrpg/issues/2805

I'm sorry the quest ended early! However from the damage done so far, if this bug hadn't happened you would have been only 80 points off killing the boss anyway, so the quest would likely have finished tomorrow, if not earlier. I've checked all the party members and it looks like they've all received the quest rewards, so it appears that the quest finished normally, just a bit earlier than it should have.

**Comment by Bottl** [comment]
But Iron Knight has 1700hp - 837.3 - 13.4 - 17.4 - 9.7 - 9.9 - 17.2 - 17.6
= 777.5hp left, which my second strike incorrectly took care of.
I already adjusted my xp gold and mana I would just like the Iron Knight
scroll back pls

**Comment by Alys** [comment]
Ah yes, sorry, I was looking at the wrong data for the boss health. I've given you a free scroll and removed the other quest rewards from your account for you.

**Comment by Bottl** [comment]
No wait I already had the Morning Star from doing it before :( sorry for
the back and forth

**Comment by Alys** [comment]
For anyone who has a bug that seems to be covered by this, please read all the information in the top post. If you still think you experienced a bug, please describe it in the [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac) guild.

**Comment by dilkROM** [comment]
I'm experiencing an issues and I am not sure if it's caused by the above or something else. I missed checking my dailies before midnight so I went in to change my CDS to 1 AM instead of 12 AM. When I woke up this morning I seemed to have done damage and also taken damage from the boss in the quest I'm on. There was a system message in the chat at about 11:50 AM. First time I ever saw a strange behavior in the chat. It is quite frustrating as it killed me. All of my computers / phones / devices are certainly on the same timezone. What can cause this? Was there an update to Habitica recently? Is there a bug in the Android app?

My UID is: 58e382e1-5d2a-4dca-9152-9f2c12ca29e6

Here are some screenshots to show the settings and behavior:

<img width="781" alt="screen shot 2016-12-03 at 12 19 25" src="https://cloud.githubusercontent.com/assets/472328/20859005/cb2eae36-b952-11e6-8270-85f37b747ed3.png">
<img width="1086" alt="screen shot 2016-12-03 at 12 18 24" src="https://cloud.githubusercontent.com/assets/472328/20859006/cb44b726-b952-11e6-83ad-ca4aa508f659.png">

Thanks for any help or insight you can provide!

**Comment by Alys** [comment]
@dilkROM Cron always runs when you use Habitica for the first time after your Custom Day Start time. That use can be anything that causes your account to be modified - completing a task, changing a setting, etc. Cron runs **before** your action takes effect.

From what I can see in the logs, it looks like you used Habitica at 19 minutes after midnight (when you went in to change the CDS) so cron ran then because it was the first time you'd used Habitica after your original CDS of midnight. You then changed your CDS to to 1am. When you next used Habitica at 11:52am, it was after your new CDS so cron ran again. 

When you changed your CDS, the app or website should have told you when cron would next run. Do you recall the date and time that it told you? If it said something other than after Dec 3, 2016 01:00:00, please tell us because that would indicate that it wasn't reporting the correct time to you. Also tell us if this was on the website or Android app. However if it did say that date and time, then the behaviour is expected - Habitica was obeying the new CDS.

You can restore the stats you lost on the website at Settings > Site > Fix Character Values.

**Comment by dilkROM** [comment]
@Alys thanks for your fast reply. I did the CDS change on the computer. Unfortunately I did not screenshot / do not remember what message it told me. Apologies for that. Can you explain this behavior and why this is a design choice? This seems pretty unintuitive to me; It's 30 minutes past midnight, my cron has ran, I reset to 1 AM I would expect that the next time the cron runs is the next day, 1 AM, not in 30 minutes. I realize it may be more complicated than that when programming and designing the application, but this was certainly a shocker, that's for sure.

Also, if this is a design feature, when do you suggest someone is to actually change their CDS? I guess you must change it before it has run for the day in order to not have it run double? I'm not sure but it's very confusing.

I actually do not need to restore stats. I found an exploit that allowed me to recover from being dead without losing anything. Was very happy to discover this in such a situation, can't imagine all the people who did the same thing as me assuming the cron would run next day and then lost their gold and items etc.

If I change it again I'll pay closer attention to the alert. Thanks again!

**Comment by Alys** [comment]
@dilkROM It is deliberate design: Habitica is set up to run cron the first time you use Habitica after your CDS.

It is undesirable to have cron run twice in one day, but the feature that lets you change the CDS is designed to warn you about the next time it will run, and then you can cancel the change if that time doesn't give you long enough to do your Dailies. If you cancel, then cron will run according to its normal schedule using your unchanged, original CDS.

If you change your CDS again in future and notice that the time it warns you about does not match the time that cron ends up running, please do tell us!

If you change your CDS before cron runs, then you can expect that your next cron will obey the new CDS not the old one, but you can always use the warning message to be sure about the next cron time.

**Comment by dilkROM** [comment]
@Alys right, I think I get it. So in my situation I should've waited until after 1 AM then setup my CDS for 1 AM and the alert would've said that the cron runs at 1 AM starting December 4th. Perhaps that was my mistake. Will make sure to double-check this in the future!

Thanks for all the help!

**Comment by Alys** [comment]
@dilkROM No worries, and yes, that sounds right!
