### ISSUE TITLE
Weird behavior for bulleted lists in the new FAQ

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5920]
The bulleted lists in the FAQ seems to have an extra line before each list item :
![capture d ecran de 2015-09-12 15 26 44](https://cloud.githubusercontent.com/assets/4882150/9831747/3dc1bba6-5963-11e5-9eb6-3dc8d7b4d9ec.png)
This happens in every bulleted list on the FAQ. As far as I can tell, this may be caused because each `<li>` text is enclosed in a `<p>` tag, but since (as seen on Transifex) it seems to be Markdown text at first, I wonder if this is caused by the double new line between each item.
Tested on Firefox 40.0.3 on Ubuntu-Gnome 15.04.

**Comment by crookedneighbor** [comment]
I've confirmed this behavior in Firefox, but curiously, it looks fine in Google Chrome. I suspect that the strings just need to be adjusted (as you said), but we'll have to be sure it still looks correct in Google Chrome.

**Comment by zedutch** [comment]
It's definitely because of the <p>-tag. Apparently, Chrome renders list items on the same line as the bullet point if they contain a paragraph, whereas firefox (and a lot of other browsers) render the paragraph on a new line (which is, by the way, the correct way to render this according to [the HTML specifications](http://www.w3.org/TR/html5/dom.html)).
I tried to look into where the /static/faq page gets it's content from but I can't seem to find it. ~~Also, when I run the server locally, FAQ links to http://habitica.wikia.com/wiki/FAQ instead of the static page. Does this mean the static page is going to disappear from the public site soon anyway (so this isn't really an issue)?~~ Just noticed I hadn't pulled the update that adds a static FAQ page

**Comment by ghost** [comment]
The content comes from faq.json in the locale folder, but the text is written in markdown, not html.
This is why I suppose it comes from the double line between each item, which is generally interpreted as a new paragraph in markdown. But in the end, it depends on how the mardown parser works in Habitica.

**Comment by zedutch** [comment]
Yes, I think it's indeed because of that "/n/n" after every item. If we simply delete those from the files, will transifex still work? Or will it just add them again?

**Comment by Alys** [comment]
This is fixed in https://github.com/HabitRPG/habitrpg/commit/909ab4eb352e0fa793cbbc68019618e68ce7565f

I've removed one of the two line breaks from the end of each of the lines in webFaqAnswer2. The appearance in Chrome has not changed. The appearance in Firefox is now the same as in Chrome.

@lemoness There's still links to the wiki's FAQ in the footer and the Tavern. Would you like them deleted or changed to open the new FAQ in a new tab?

**Comment by zedutch** [comment]
@Alys Doesn't that only solve it when Habitica's set to English?
All other languages also have this problem (at least the few I tried randomly did)

**Comment by Alys** [comment]
@zedutchgandalf In Transifex, I believe in general it's best to not adjust any formatting in the translated strings, even if the formatting is producing incorrect appearances (there might be some exceptions to this guideline, especially for language-specific issues, but it's probably best to ask in every case). The change I've made should make its way to Transifex soon.

@Blablux and @zedutchgandalf Thanks for reporting this, and for your investigation! That helped me track down the problem quickly.

**Comment by Alys** [comment]
@zedutchgandalf Yes, this fix only solves it immediately for English, but when the modified strings are copied to Transifex and retranslated and then copied up to the site, it will be fixed for other languages.

**Comment by ghost** [comment]
@Alys while your update fixes this part of the FAQ, there are two other answers in the FAQ that use bulleted list. `webFaqAnswer9` and `webFaqAnswer10` have the same issue. Sorry for not mentioning them at first.

**Comment by crookedneighbor** [comment]
I've fixed the other strings and updated transifex. Thanks for reporting it!
