### ISSUE TITLE
Server errors, slow loading times, missing party, missing equipment, other problems

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5941]
### The Habitica server is undergoing a heavy load at the moment. This is causing the following problems:
- slow loading times
- red error message notifications
- avatars that do not show all equipped gear, pets, mounts, backgrounds, etc
- missing party information, or a party page that says you are not in a party when you know you are
- missing information from other pages
- reversal of actions such as ticking off tasks or buying items
- other inconsistencies or odd behaviour

If you notice these problems, you do _not_ need to comment here or create a new bug report. We know that these problems are likely to be happening to all players equally so new reports of them aren't necessary. When we've resolved the root cause, all players will find that the site returns to normal.

We'll comment here when it's fixed.

We're very sorry about the inconvenience! One of our best developers is working full-time on the problem!

**Comment by lemoness** [comment]
We believe that we have fixed the server problems for now. Thank you so much for your patience! If you are still encountering these issues after reloading, please comment and let us know.

If you are going to bed and/or will cron soon, please be sure to reload to make sure all your Dailies are appropriately checked! We also strongly recommend using the [Data Display Tool](http://data.habitrpg.com/) to verify that everything is checked off. 

### If you took damage overnight from your Dailies because of the server problems, you can restore your lost stats under Settings > Site > Fix Character Values.

Thanks again for bearing with us!

**Comment by Gwillewyn** [comment]
I seem to suddenly have jumped back in time at least 9 hours.  Everything I've done today suddenly seems to be gone.
I've cleared my cache and all cookies, but my phone and PC both look like they did this morning.
Is this a related issue?

**Comment by Alys** [comment]
@Gwillewyn Yes, that will most likely have been caused by the server errors. Your actions yesterday weren't recorded. I'm very sorry about that!

**Comment by kellarules** [comment]
I lost 60 points of mana buff because it thought I hadn't done one of my dailies that I checked off and I lost the streak for that daily. And then my drop cap wasn't reset and started the day with 7/9 drops already found. It also looks like I may be getting awarded damage to the boss I'm fighting twice, once for yesterday, once for today, but i can't be sure of that cause I don't know how much damage I actually did yesterday. Will any of this go back to normal or do I just need to reset the streak by hand, wait for more drops tomorrow, and rebuild my mana buff?

**Comment by Alys** [comment]
@kellarules I'm sorry about that! The server is back to normal now. Please see lemoness's post above about using Fix Character Values if you haven't already noticed it.

**Comment by wisteriacs** [comment]
None of the interactions with my account in the browser on any of my devices is syncing to the server. (I can check something off, add a task, delete it, but it doesn't talk to the server at all, so it hadn't actually done the task.) Changes made in the iOS app are syncing to the server, but there are things I need to do in my browser. When I refresh the browser, no matter what I've done, it goes back to the changes last made by the app. This started yesterday evening (Sunday Sept 20).

**Comment by Alys** [comment]
@wisteriacs that's this bug: https://github.com/HabitRPG/habitrpg/issues/4313 Please see the "Advice" section near the top of that issue (that's the only part you need to read).

If a few more refreshes in one browser don't fix the problem, please comment on that issue.

**Comment by Alys** [comment]
@wisteriacs If a few more refreshes in one browser don't fix the problem, please comment on that issue.

**Comment by pipisafoat** [comment]
I purchased all of the special seasonal equipment, but none of it is showing in my equipment tab (and it's gone from purchasable and the money is also gone, so I know it happened) - this has been a couple days and nothing has reappeared. Not sure if it's related to this or not!

**Comment by SabreCat** [comment]
@pipisafoat: This issue has resolved (I'm going to close it now), so what you've run into is probably something separate. Would you mind setting up a ticket of its own?
