### ISSUE TITLE
link to Newbies Guild / Ask a Question in the Tavern's Resources box

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5945]
As discussed in the Aspiring Socialites guild, the Resources box in the Tavern should have a link to the Newbies Guild. We probably want the link to include the text "Ask a Question" so it's obvious what it's for. 

I suggest the link's text should be "Ask a Question (Newbies Guild)" but look below to see if there's a comment from @lemoness suggesting something better. :)

I'm advertising this in the Aspiring Coders guild as an entry-level project.

**Comment by LuneFox** [comment]
I did some research, and noticed that  `habitrpg/website/views/options/social/tavern.jade` contains the table itself, and  `habitrpg/test/spec/translations.js` contains default names of the strings in English (why "test", though?). If these two files are the only ones that are related to solving this task, I can try adding the field.

**Comment by crookedneighbor** [comment]
@LuneFox `test/spec/translations.js` is a fixture that is compiled when a test is run so that the test suite has access to the translation strings.

IE: if my test is `expect(foo).to.eql('some string we change alot');`, the test will break everytime we change the string. However, if we use the translation string variable:

`bar: 'some string we change alot'`

`expect(foo).to.eql(window.env.t('bar'))` - no matter what we change it to, the test assertion remains valid.

In fact, you cannot commit changes to the translations fixture because it is ignored by git.

**Comment by lemoness** [comment]
As a title, "Ask a Question (Newbies Guild)" works well!

**Comment by LuneFox** [comment]
Ah, it makes sense. I also used to keep all "full" strings in a separate file and only referred to variables in main program when I was coding for myself. So the only thing that has to be done is just adding the extra field to tavern.jade using some new short name for the string? I'll try.

**Comment by LuneFox** [comment]
Okay... here we go. https://github.com/HabitRPG/habitrpg/pull/5955

**Comment by SabreCat** [comment]
@crookedneighbor: Ooh, I didn't know that about testing string outputs. That would have made things easier for me on some of my recent Hourglass stuff. `>.<`
