### ISSUE TITLE
When I log in, the progress from before I logged out last time has disappeared.

### ISSUE THREAD

**Issue by Illneverrememberthis** [HabitRPG/habitica#5946]
All the Dailies, To Dos, and Habits I'd completed before I logged out are undone. Posts I've made in the Tavern are gone. All the experience, money, pets, equipment, and levels I'd gained are gone. And if I completed all these things before cron and logged out, then logged back in after cron, all the things that have disappeared (like Dailies that became undone even though I did them) causes me damage to health. This is frustrating because I do all this work but when I log back in it's as if I never did it at all. This has happened to me three times so far this week.

**Comment by Alys** [comment]
@Illneverrememberthis I'm sorry this has been happening to you! It is likely to be because of this bug: https://github.com/HabitRPG/habitrpg/issues/4313
In brief, all of those actions that are being undone were being held onto by your browser and were never sent to Habitica's server. For example, your posts to the Tavern that were undone were never visible to other players because they were not stored on the server.

Please see the advice section near the top of that issue. It will help you recover from unfair damage and help you prevent the problem occurring often.

I'm going to close this now but you're welcome to comment here if you have any questions and we'll still see your post.
