### ISSUE TITLE
Damage while resting in the Inn

### ISSUE THREAD

**Issue by Carousel09** [HabitRPG/habitica#5948]
Last week I checked into the Inn of Habitica, knowing that I would be bust for a while and wouldn't have time to check off dailies. 
I logged in earlier today and found that I had lost all my health and died.   Yes, I was still checked into the Inn.  
I was currently on a quest, but I was in a party by myself, which should mean that the boss for the quest doesn't deal damage for missed dailies (as all party members are checked into the Inn). 
I reviewed the party messages to see where damage had accumulated.  The most recent message is from 6 days ago (the day before I checked into the Inn).   Then one message from today when I logged into the site for the first time (but I had not yet checked out of the Inn).   That message states that the boss dealt 25 damage.   This doesn't add up to me losing all 50 of my hp and dying.

**Comment by Alys** [comment]
@Carousel09 I'm sorry about this! To investigate it, we'll need to be able to identify your account. Can you please go to Help -> Report a Bug from the habitica.com website and see step 6 in the instructions?

**Comment by Carousel09** [comment]
@Alys 
Oops! User ID is as follows:  e26071ab-7982-444d-9eec-69b2c14a37b3
It's really not a big deal that I died, so if this is an issue that affects me only (as it looks like it might be) then I'll just chock it up to bad luck, and the game devs don't need to spend their valuable time investigating.   I just thought I'd report it in case this is happening frequently, in which case I thought the bug should be made known.

**Comment by Alys** [comment]
Sorry @Carousel09, I meant to reply to this a few days ago. I couldn't find anything to indicate a different cause than I had described in the Tavern, so I think that is what happened. I.e., you checked into the inn but the https://github.com/HabitRPG/habitrpg/issues/4313 prevented your browser from sending that action to the servers, so Habitica didn't know you were checked in, even though it looked as if you were. When you came back, cron happened, causing you to take damage, and after that, your browser sent the Rest in the Inn action to the server, resulting in you then really being in the inn, but too late. That issue has an Advice section at the top, and in particular, the Data Display Tool mentioned in step 4 lets you check that you really are resting in the inn (if the DDT says you are, you certainly are, because it takes its data from the server).
