### ISSUE TITLE
No Quest Reward: Dilatory Distress, Part 1

### ISSUE THREAD

**Issue by Blackgen** [HabitRPG/habitica#5959]
Me and my Party didn't get any reward for completing the quest "Dilatory Distress, Part 1 Message in a Bottle".
On our Party it states: "All items found! Party has received their rewards.", but noone got anything. 
There was no popup or anything else.
We collected 25/25 Blue Fins & 26/25 Fire Corrals. This might be an Issue.
Group ID: 3a61a98d-b80c-4ced-8835-f3fa30e93402
My ID: 712ccc34-c13f-4c3e-8860-3b92065f838f

**Comment by Alys** [comment]
@Blackgen I've given the quest achievement and rewards to all members of your party.

I believe that Timmay (7b62db60-7554-4455-8dbe-2c519586b652) had already got them (they had the achievement and gear already) but I included them anyway in case that was from a previous run through the quest. That means they now have two achievements instead of one. If that's incorrect and if they are bothered by having the extra achievement, they or you can comment here and I'll remove it. Note that this is by no means essential - none of us will mind if they keep the extra achievement. :)

For our ref: https://github.com/HabitRPG/habitrpg/issues/4252
