### ISSUE TITLE
Don't round HP if less than 0, or show decimal value

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#596]
Here's my current HP (spammed the -):

![Screen Shot 2013-03-05 at 5 25 48 PM](https://f.cloud.github.com/assets/3122471/224942/b954dc2c-85e3-11e2-9f63-86f1e6f67d7b.png)

Currently, it says "0/50," but still shows a tiny bit of red, and I have not died.  I think that this is because HabitRPG is rounding the HP (could be wrong).  If HP is less than 0, even if it's .876, I think you should die, or if it is less than zero, show up to two decimal places (.86). Let me know what you guys think.

**Comment by Pandoro** [comment]
Yes I agree, very confusing ^^; 

I think @MrConcept overhauled the exp system and fixed this kind of bugs there, do you think that kind of fix could be applied here as well?

**Comment by PhilipHow** [comment]
Yeah I'll look into it.

**Comment by PhilipHow** [comment]
I've made HP always round up, just like XP is currently always rounded down.

This is because, for HP, something happens when it's 0, but for XP something happens when its hit 20..or whatever.

This could be misleading, but I would hope noone deliberately used a reward just because they knew it wouldn't kill them...

**Comment by lefnire** [comment]
yeah, this bug is pretty darn minor ;)

**Comment by rixx** [comment]
but persists - wouldn't it be fixed if HP was actually always rounded up?
