### ISSUE TITLE
The game gave me 500 gold in which I DID NOT earn

### ISSUE THREAD

**Issue by nicolasstag** [HabitRPG/habitica#5970]
18015ace-89fe-45cf-95bc-231b91652029

I logged on this morning, to find that I had 500 gold! I immediately assumed it was from a boss, so I spent it all. Once I spent it all, I checked in with my party, and realised that it was NOT from a boss. 

The game just gave me 500 gold for no reason.

I'm in the process of correcting it by deleting all gold I earn over time, until I can delete the 500 I spent.

Still, this is a huge issue. I hope you guys fix it soon.

**Comment by NessyNoinex** [comment]
a7b42b00-3ff9-4e52-8486-ec367fa564ad
Same here.
I opened a new tab to write in the Tavern and saw that I had leveled up, gotten gold and exp for no reason. I made photos of the two tabs to compare them and then refreshed. The problem happened again.
Photos here:
![1](https://cloud.githubusercontent.com/assets/6381483/10081965/cdad9cd8-62f7-11e5-83a9-5fdbc7175028.jpg)

![2](https://cloud.githubusercontent.com/assets/6381483/10081873/568d7678-62f7-11e5-9e77-cdd4e0d3e32f.jpg)
![3](https://cloud.githubusercontent.com/assets/6381483/10081874/57b7a258-62f7-11e5-8bf2-2a51a648e8d8.jpg)

**Comment by Alys** [comment]
We didn't see any other identical reports around the same time, so I'm attributing this to glitches that happen sometimes.

@NessyNoinex This might be the same issue as https://github.com/HabitRPG/habitrpg/issues/5323. 

@NixIsAnAlien Yours could be similar, or it could be that you received back gold that you thought you'd previously spent, due to a [sync error](http://habitica.wikia.com/wiki/Sync_Errors).

Unfortunately there's not much we can do when odd things like this happen. We're improving Habitica's code base over time with refactoring, so glitches will become rarer in the future.
