### ISSUE TITLE
Odd error message...

### ISSUE THREAD

**Issue by catwoman153** [HabitRPG/habitica#5971]
I keep getting these two error messages: 
![image](https://cloud.githubusercontent.com/assets/14315860/10076932/f9ce22de-62ab-11e5-9ae6-715cc21dbd6f.png) ![image](https://cloud.githubusercontent.com/assets/14315860/10077125/f4067f3a-62ac-11e5-8b10-d4ef137ed5fa.png) 
every time I reload the page or check something off.  I think I've gotten slightly different ones as well but they're not easy to capture before they fade away.  I know all of the messages start with "Cannot GET" and reference /api/ in some way.  I don't think it's been affecting my habits, though it appeared at the same time I started having trouble with the iOS app communicating with the website.  Phillip responded to my bug report on the iOS app and said it's not related but since both issues appeared at the same time I thought I'd mention it.

User ID:  5adfdd5e-7f74-463e-ac67-f5fe22a823b1.  I'm using Google Chrome on Windows 7 Professional.  Here's what comes up in the Javascript console:
![image](https://cloud.githubusercontent.com/assets/14315860/10077313/c7ae9dd6-62ad-11e5-9c29-c622833bb5a8.png)

Let me know if you need any more info.  Thanks!

**Comment by Alys** [comment]
Can you please log out of Habitica, clear your cache and cookies, clear local storage for habitica.com if you know how to or are willing to google for instructions (clearing local storage might not be necessary, so it's optional at this stage), then close all browser windows, and then reopen and try again? It looks like your browser doesn't have access to all of the site's code, so this might help. Please let us know if it doesn't!

**Comment by catwoman153** [comment]
Hi,

It didn't help on chrome, but since you mentioned that my browser doesn't have access to all of the code, I switched to Firefox and I'm not getting the message there anymore.  So it seems to be isolated to chrome.  Let me know if you have other suggestions or questions!

Thanks,

Bridgete A. McAuley
Attorney at Law

**Comment by Alys** [comment]
We haven't seen any other reports of this so I think it was just a local problem in your browser. If it's still happening in Chrome, try logging out of Habitica (if you can), clearing your cache and cookies again, closing the browser, and reopening. If you have your browser set to sync data with browsers on other devices, you might need to repeat the same process on them, at the same time (or at least, don't reopen Habitica on any of them until they've all been done). If that still doesn't fix it, repeat the same process but this time clear local storage as well (on all devices). I'm going to close this since there isn't anything we can do directly to help with this, but comment here if you have any questions.
