### ISSUE TITLE
Dailies didn't reset+damage for dailies that were counted as done+multiple levels taken off

### ISSUE THREAD

**Issue by slytherinkhaleesi** [HabitRPG/habitica#5975]
Here's my id: 2f18532a-b2be-4437-a6ae-e8e6f3b036af. I'm using Chrome on Windows 10.

I logged in this morning, and a bunch of my dailies hadn't reset. However, some of the ones I had checked off yesterday were not checked off.  Some of my dailies weren't even showing up. In addition, I went down multiple levels (at least 4, maybe even 5 or 6) instead of a single level. I've tried refreshing multiple times, and it hasn't changed.

**Comment by silvrsurfr777** [comment]
Happened to me, too!  I only lost 1 level, but my hat broke and I lost all my gold.
About a half of my dailies reset, and I lost 48 health, Which shouldn't have been possible even if none of my dailies were completed.

I'm using chrome on OSX 10.9.5, my user name is Silvrsurfr777

**Comment by mikebranski** [comment]
I'm not sure if my party is experiencing this or a different bug. Our crons appear to be triggering randomly, causing us to take massive spikes of damage from "missed" dailies.

In addition, sometimes it triggers and causes a ton of damage, even though most of our dailies were already checked (even before the incorrect firing of the cron).

As a result, we all had to check into the inn and abandon our current quest.

Group ID: 226e3812-5144-4e78-a2a4-d4040aed1af5

**Comment by Alys** [comment]
@slytherinkhaleesi @silvrsurfr777 I'm sorry that happened to you! You've experienced this bug: https://github.com/HabitRPG/habitrpg/issues/4313  Please see the "Advice" section near the top for information that will help you recover from the damage (that's the only part you need to read).

@mikebranski I'm investigating your party's problem. Can you tell me please how long this has been happening? 

@mikebranski For every party member who has experienced their cron happening at an inappropriate time, please ask them to read this issue (just the first post; they can ignore the comments, and they do not need to add their own comments unless they have questions): https://github.com/HabitRPG/habitrpg/issues/5919
It is important that they follow the advice in that issue in case that's what's causing the incorrect crons.

**Comment by silvrsurfr777** [comment]
Thanks, @Alys, that should fix it for now, I'll update if it happens again.

**Comment by mikebranski** [comment]
Thanks @Alys; I'll have everyone take a look.

This all started 8 days ago: 09/17/2015 12:08:38, according to the damage report timestamp. I can private message you our chat log showing all of the incidents if it would be helpful.

**Comment by Alys** [comment]
@mikebranski Thank you but no, that's not necessary. I have a script that can pull the party chat out of the database. It removes all messages from party members, showing me only the automated quest attack messages.

**Comment by Alys** [comment]
@mikebranski I've moved your bug report to https://github.com/HabitRPG/habitrpg/issues/2805#issuecomment-143379666. The timestamps there are in GMT+10.

In addition to the timezone information, please ask your party members to read the "Advice" section near the top of https://github.com/HabitRPG/habitrpg/issues/4313. Some of the large damage might have been caused by that bug, although it doesn't necessarily explain cron running more than once per day. 

For the players who experienced cron running more than once a day, could they please comment on https://github.com/HabitRPG/habitrpg/issues/2805#issuecomment-143379666 to say whether or not they are using Habitica on more than one device (e.g., multiple PCs, mobile phones, tablets)? If you/they prefer, you can comment on their behalf. If they do use multiple devices, it's even more important to ensure that the time and timezone are correct on all of them, including that the time is the **same** on all of them.

Unfortunately, we've been tracking that issue for a while but we're still not sure what causes it. :(

**Comment by mikebranski** [comment]
@Alys Thanks for the detailed follow-up. I'll update the respective issues this weekend with more details from the party. Thanks!

**Comment by crhallberg** [comment]
Hi guys! I've had this problem a few times now recently, my dailies have not been resetting at cron and remain checked from the day before. At the same time, many of them (but not all) had their streaks reset to 2. I manually reset a few of the streaks, but I can't remember what they all were. I've also noticed recently that a lot of gold has been going missing--at cron yesterday, I took some party damage, lost some experience, but also lost about 200g, and I can't imagine why that would happen. Today, it appears that quite a bit of gold is missing as well, about 600. I've tried the manual fix as suggested of writing down my gold, exp, mana and streaks, unchecking the tasks, and restoring the values but it is time consuming and tedious since this bug has happened three times now within a month. My User ID is 6b915458-aea7-4d56-9dd9-eaabd404287f .

**Comment by Alys** [comment]
@crhallberg Sorry about that! You're suffering from [this bug](https://github.com/HabitRPG/habitrpg/issues/4313), which can be persistent and annoying. :( There's an advice section near that top that might help you avoid it. Note that you don't need to write down the values of gold, etc. What you can do instead is open Habitica in a second tab, go to Fix Character Values and leave it open, then in the first tab, untick your Dailies. Then go back to the second tab and submit the FCV form. It will still have the values in it from when you opened it - i.e., before you unticked your tasks.

**Comment by pipisafoat** [comment]
I just had damage marked on me (and my party!) for dailies that were checked off. This happened a couple days ago as well. I do have a mobile device, but I've checked that the time is correct on it as well. In fact, I don't use it very often. I've only ever had this happen on days when I've only used one device, though not on every day that I only use one device. It's also happened when my "only one device" is my computer OR my iPad. I haven't kept super great track of this bug, but I haven't noticed any regularities in when it causes damage. Last night, four days ago, and then prior to that I think it hasn't happened for over a month. User ID is b2293f3a-bffb-4e01-8db3-7b6926677f36

(I have advised my party to reset character values for today's damage, but it's killed people before, soooo.)

**Comment by pipisafoat** [comment]
Er, and now the dailies I completed yesterday won't untick so I can mark them complete for today. With my cron being at 3 am (and me having gone to bed before midnight and gotten up at 8 am), I absolutely know I haven't checked them off on the wrong day. Is there anything to be done for that? I am posting this error here as it seems like it is most likely related to the issue I just recorded.

**Comment by Alys** [comment]
@pipisafoat Sorry about that! You're also suffering from the bug described in my previous comment here (https://github.com/HabitRPG/habitrpg/issues/4313). There's an advice section near that top to help you avoid it and uncheck your Dailies.
