### ISSUE TITLE
Recurring subscription fee was charged, but haven't been subbed since name change

### ISSUE THREAD

**Issue by bonesarelazy** [HabitRPG/habitica#5977]
My subscription stopped showing as active at the same time that HabitRPG became Habitica. I figured it was due to the name change, but was ok with it lapsing for a while so I didn't do anything. Today I got notice of the recurring charge going through, but I'm still not showing as subscribed. 
user id: 961897d9-df53-4a92-b123-0aa5dbbb4a02
user name: lazybones

**Comment by Alys** [comment]
Sorry about that! I'll look into it for you today.

**Comment by Alys** [comment]
@bonesarelazy Your subscription was terminated on 2015-08-01. It wouldn't have been because of the name change but instead was coincidental with that date.

Could you please forward today's notice of the recurring charge to admin@habitica.com? I'll handle this after that through email so I'm closing this issue.

**Comment by paglias** [comment]
Was it an Amazon Payments subscription?
Il 25/set/2015 11:48 PM, "Alys" notifications@github.com ha scritto:

**Comment by bonesarelazy** [comment]
I've attached a screen shot of the paypal charge. 

Karma 


     On Friday, September 25, 2015 5:50 PM, Matteo Pagliazzi <notifications@github.com> wrote:
   

 Was it an Amazon Payments subscription?
Il 25/set/2015 11:48 PM, "Alys" <notifications@github.com> ha scritto:

**Comment by Alys** [comment]
@paglias It was PayPal.
