### ISSUE TITLE
Task page tabs with long text don't display the tab separator correctly

### ISSUE THREAD

**Issue by JoseCardonaFigueroa** [HabitRPG/habitica#5980]
I have notice that the section were the rewards are displayed is not working properly in the spanish version of the website, as you can see in the following image.
![Rewards Pane](https://cloud.githubusercontent.com/assets/9516846/10124860/56a1ba1c-6526-11e5-9e2d-9b3d47160714.png)

It appears that everything is ok in the chrome console. 
![image](https://cloud.githubusercontent.com/assets/9516846/10124897/9e8f31d2-6527-11e5-9619-410c6a600400.png)

I am using Chrome running on a Windows 7 and Ubuntu 14.04 LTS. My user ID is 3e670a15-99d4-4ab7-ba22-1eccfdacfe7c
##

**Comment by patriq** [comment]
It happens in every language.
![sto0soz](https://cloud.githubusercontent.com/assets/3120671/10150872/27018a48-663a-11e5-963c-22ff035f72b2.png)

**Comment by Alys** [comment]
That happens when the browser window is too narrow for the tab to be able to stretch to show the text on one line. If you're on a wide-screen device, you can expand the browser window to let the tab stretch (although for languages with long text in the tab, even that won't help). There's not a lot of options here - either the text wraps like this, or it stays on one line and runs off the end of the tab, or it's changed to a smaller font which would be harder to read. The current behaviour is, I believe, the best option.

It would be nice though if the dividing line between the tabs went all the way down, so that you saw two tabs of equal height. I'm about to change the title to indicate that.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
This is no longer an issue!
