### ISSUE TITLE
lots of JS errors

### ISSUE THREAD

**Issue by nomicode** [HabitRPG/habitica#5985]
I was updating some of the tags on a few of my todos, and the progress bar was taking longer than usual. then a weird, and improperly styled, red error window popped up. it looked like there was an iframe in it, but I can't be sure, as most of it was clipped

it suggested I look in my error console and report what I found to you

```
View.js:44
Uncaught SecurityError: Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "https://habitica.com". Protocols, domains, and ports must match.

ContentSelector.js:140
Uncaught SecurityError: Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "https://habitica.com". Protocols, domains, and ports must match.

View.js:44
Uncaught SecurityError: Blocked a frame with origin "https://payments.amazon.com" from accessing a frame with origin "https://habitica.com". Protocols, domains, and ports must match.

ContentSelector.js:140
Uncaught SecurityError: Blocked a frame with origin "https://payments.amazon.com" from accessing a frame with origin "https://habitica.com". Protocols, domains, and ports must match.

https://habitica.com/api/v2/user/batch-update?_v=48&data=1443448668831
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-8bdd0355.js:36 ObjectresponseError @ app-8bdd0355.js:36

View.js:44
Uncaught SecurityError: Blocked a frame with origin "https://s3.amazonaws.com" from accessing a frame with origin "https://habitica.com". Protocols, domains, and ports must match.

ContentSelector.js:140
Uncaught SecurityError: Blocked a frame with origin "https://s3.amazonaws.com" from accessing a frame with origin "https://habitica.com". Protocols, domains, and ports must match.
```

are those SecurityError messages expected?

is it related to the API error?

my user ID is 93ac1ab5-79f6-4b83-9062-8bf8355b7795

**Comment by nomicode** [comment]
here's the error window

![image](https://cloud.githubusercontent.com/assets/23469/10137686/1b9cd91c-65fb-11e5-8660-43b8f6f7e4e9.png)

**Comment by Silverai** [comment]
I've been having this issue (the above red error window) for the last 30-40min.  The bar across the top takes longer than usual and then either straight after or shortly after I get the red error.  To fix, I have to close the tab entirely then load habitica again.  The first time I had ticked off all my dailies and some habits, and paid attention to my xp points before reloading.  After getting back into habitica, one daily was unticked, but some habits must have still registered because I didn't have to repeat them all to get to the same xp points.  Then I went to feed my pets.  I ended up having to reload 3 times to feed my pets 4 candies.  At one point I noticed an earlier candy was showing still while a later candy had still registered as eaten. Then it happened yet again while purchasing in the seasonal shop.

My id is ca3da398-4f73-4304-b838-af3669ed4cbb
Using Samsung Galaxy S Tab.  Chrome 45.0.2454.94
Android 4.4.2 SM-T800 Build/KOT49H

**Comment by Alys** [comment]
We had server problems in the past hour and we've restarted the server. That should fix these errors. Please reload. If they are still happening, comment here and we'll reopen this.

**Comment by Alys** [comment]
@nslater For those security errors, if they are still happening, please disable all extensions in your browser, then reload the page. If they are still happening after that, comment here.

**Comment by nomicode** [comment]
disabled extensions. errors go away. thanks

I do get this though:

```
Given URL is not allowed by the Application configuration: https://www.facebook.com/connect/ping?[SNIPPED]
One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
```
