### ISSUE TITLE
Multiple deaths in quick succession?

### ISSUE THREAD

**Issue by harrislapiroff** [HabitRPG/habitica#5986]
I'm not sure exactly what happened, but I just died twice in a single morning (and lost equipment, gold, and a level both times).
##

**Comment by Alys** [comment]
You can learn about the causes of death on the wiki's [Death Mechanics](http://habitica.wikia.com/wiki/Death_Mechanics) page. See especially the "Sudden, Unexpected Death" section, and if you think the death was unfair, the "Undoing Death" section. If you have questions about anything you see there, either comment here or go to the Habitica website and click on Help -> Ask a Question. That will take you to a guild where there are many experienced users who can help with almost any problem and it often gets you an answer faster than here because there's many more people there. :)

If you think a bug occurred, we'll be happy to investigate, however we'll need to be able to identify your Habitica account. To help us do that, go to Help -> Report a Bug and see step 6.

**Comment by harrislapiroff** [comment]
I _strongly_ suspect this was a bug. The  chain of events was that I checked my Habitica, died (presumably from boss damage), lost a Wand of the Waves, my gold, and a level, and reset my health. Then I logged in again a couple hours later, died _again_, lost a Sailor's Neckerchief, another level, and gold I had gotten from a task in between.

The boss did not deal 50 damage in that time and I can't have taken damage from my dailies because I'm resting at the Inn (and also my cron should have run the first time I logged in this morning, anyway).

My user ID is 53ce6e53-eb34-4563-aaa3-737364fb7859. Let me know if you need any more information.

**Comment by harrislapiroff** [comment]
Unless it's possible for me to die twice in a row without actually resetting in between? I hadn't checked Habitica in a few days.

**Comment by Alys** [comment]
@harrislapiroff It's possible to die multiple times in one day from your own uncompleted Dailies if your cron runs more than once a day, and that can be caused by incorrect times set on your device(s). Please read [this issue](https://github.com/HabitRPG/habitrpg/issues/5919) (just the first comment, not the replies). Does that seem relevant?

**Comment by harrislapiroff** [comment]
I don't think so. All my devices are on the same time zone and it couldn't have been damage from my dailies, because I was resting in the inn.

**Comment by Alys** [comment]
Fair point, sorry, I'd forgotten you were resting in the inn.

**Comment by paglias** [comment]
Reopen if it occurs again
