### ISSUE TITLE
"invite party to quest" button on dropped scroll does not work for single-person parties

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5998]
When a player receives a quest scroll upon levelling up, they see a modal with an "invite party to quest" button. If they are in a party with only themselves, that button doesn't work.

We should either allow the button to work so that the player can immediately start the quest alone, or we should remove the button, perhaps replacing it with an explanation about how you need to invite people to the party before you start the quest.

@lemoness, what would you prefer to have done?
##

**Comment by lemoness** [comment]
I think we should take them to a slightly edited invite friends modal,
where one of the options is "Start Quest By Yourself" or something similar.
So that the flow would be:

"Invite Party to Quest" >
"You don't have any friends in your party!"

> 1 "Invite Friends"
> Pending Quest
> 2 "Start Quest Alone"
> Quest begins immediately.

When I am back from my business trip I will add this to the list of modal
mockups that @sabrecat is working on.

**Comment by Alys** [comment]
I'm closing this because the behaviour is different now (a solo-party player sees just the "quest later" button on the modal).

**Comment by Alys** [comment]
Sorry, my last comment was wrong (when I was testing this, the creation of a solo party hadn't properly taken effect). A player in a solo party DOES have the invite button and it now works correctly.
