### ISSUE TITLE
Undo Button?

### ISSUE THREAD

**Issue by bthallplz** [HabitRPG/habitica#6]
_Edited by wc8: Vote for this feature here: [Undo Button](https://trello.com/c/RQIp0Yl5)_
After signing up and going through the tour I still didn't understand how the plus and minus icons played into the system, so I tried double-clicking on Take The Stairs's minus icon to do something (delete the task?) and realized that it knocked back my health. I then tried to correct this by double-clicking the plus icon, but it just boosted my EXP. After both misguided attempts I received notifications, but neither included an Undo link.

Could you please add an Undo link to the notifications that popup?

**Comment by lefnire** [comment]
Good idea, adding to my todos. It won't be very soon, gotta finish v1 first ([roadmap](https://workflowy.com/shared/cd06313a-7c93-ae5f-ae55-e64cae0556e4/)), but if you email me your userId I can reset your user

**Comment by pfraces** [comment]
+1 (i will need a reset too :D)

**Comment by lefnire** [comment]
A reset button will be super simple, and undo button will take time. I'll
add a reset button for now

**Comment by pfraces** [comment]
Ohh, thank you!! i was thinking in opening another issue requesting for it! XD

**Comment by pfraces** [comment]
It will be good to offer reset button from game over screen too (in which i'm currently)

Removing the cookies solves the problem however

**Comment by lefnire** [comment]
I'm still a bit torn on "reset" - I'll probably add it now for debugging purposes, since people have been needing to reset due to the app's current bugs & usability concerns. But the point of the app (and my business model) is to enforce accountability by requiring the user to use tokens to reset (via "continue" on death and "reroll" for tasks). That way it really pushes them not to die, since it costs them money. But I'm looking into reset button for now in any case.

**Comment by lefnire** [comment]
I'm leaning against it now the more i think of it. The undo button makes sense for mistakes, but the reset button makes it too easy to lose accountability. Kinda the way the whole app works is be making tasks more valuable the worse you are, which drives accountability on your more difficult tasks. If you can just "reset" any time, it takes away that push.

Everyone, feel free to send me your userIds and I can reset you and load your tokens if you want. As far as "reset" goes, let's have a discussion around this as to whether or not it kinda defeats the logic of the app.

Incidentally I have the "reset" code built out in a private branch, so if I can be convinced...

**Comment by pfraces** [comment]
My english is so poor for exposing my thoughts on it, but i will try. Sorry about that.

_(add IMHO at the beginning of each of the following sentences XD)_
-   A "reset" button reduces false accounts. If I want to reset and I must pay to do it, I could register myself with another account.
-   It could be in the settings view and marked as dangerous (as deleting a repo in github)
-   This app is awesome and I think I will use for a long time. In a few days, my experience, tasks and its difficulty, history and maybe some other stat will be very valuable for me. If "continue" saves the stats (i.e. reinitializing difficulty in reds only) it make sense for me to pay for it
-   Another reward could be added which works like "reroll" but targeting a single task instead (and require gold like the other rewards) so if you have many reds you would die anyway and you will need to pay in order to recover your stats through "countinue", or do a "reset" and start from the beginning
-   "Reroll" can still making sense if "continue" resets your gold and "reroll" don't (not sure about that)

**Comment by pfraces** [comment]
Another idea could be offering the "reset" option in the firts few levels only (< 5 maybe, I don't know)

**Comment by lefnire** [comment]
Those are good points. I'll add it in for now as trial run (soon as I can get [git pushes to heroku](https://github.com/lefnire/habitrpg/issues/7) working)

**Comment by lefnire** [comment]
added the reset button. lodash stopped installing on heroku, had to go back to underscore + node-clone

**Comment by eteran23** [comment]
Not sure if this would be worth a new issue, but I think Undo would be best combined with some Log feature. This would list all user actions taken in descending time order, with the possibility to undo them. I think such a feature is especially important with the Habit area since you may easily forget wether you tracked a habbit already or not.

**Comment by p1agu3** [comment]
My girlfriend just spent a whole bunch of her gold by accident on something and got super upset about the lack of an undo button.  She almost created a blank task _just_ for the gold so she could give it back to herself.  There goes accountability...

I agree with the other users here. Having a log feature as the undo mechanism would be great.  It just makes the most sense to see a full perspective on what tasks I "actually" got done today in the system, for both server issue paranoia (as in "did the server eat some of my tasks today" which is bound to happen from time to time) as well as double-checking my own changes.

Later on, this log could be charted out nicely in a visual format (similar to how it's done on an individual habit/daily/todo basis right now), but I'm getting way ahead of myself here.  Undo comes first, imo.

**Comment by horusofoz** [comment]
I wanted to chime in on this and explain that I think an undo button should be considered a high priority feature request.

I feel this is an important feature because because the close proximity of the Delete button to the Edit button has caused me to accidentally delete tasks on multiple occasions. Therefore it stands to reason that other users have likely made the same mistake.

To reduce the occurrence of these accidental deletions, I believe the Delete option should be accessible from the expanded Edit view. The process for deleting a task would be Edit>Delete>Confirm>Task deleted.

If this is too difficult to implement, an option to restore deleted tasks is essential. 

Even if a user recreates a task/habit/daily and all it's notes, it loses it's history. Therefore progress chart is reset, urgency via colouring is lost and value of completing item is set back to default.

**Comment by lefnire** [comment]
ok, I upped it to critical. #80 is top priority, then the critical bugs, then the critical features (like this)

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.
