### ISSUE TITLE
Error Cast to number failed for value 'NaN' at path 'stats.gp' (Corrupted account)

### ISSUE THREAD

**Issue by fpepin** [HabitRPG/habitica#6003]
Please excuse the vagueness, I'm sure I can provide some extra details if someone can direct me in the right direction.

I am getting this error consistently when going in the equipment page (paraphrased): Error in casting value NaN to Number in path stats.gp

How to reproduce (I think...):
1- Log into mobile when finishing a quest (Dilatory Distress, Part 2)
2- Have a crappy network connection and be unable to update further
3- go into web version:
 a) quest not listed as completed
 b) equipment not available
 c) error message when loading the equipment page.
4- back with the mobile version (which I realize is another project)
 a) unable to check a task or change equipment: getting a network error. Creating a task works, but checking it done hangs with spinning hourglass and it is not present.
 b) reloading content or clearing the cache does nothing.

This is leading me to believe that my account is in an inconsistent state.

I can provide the console logs if someone can provide instruction, javascript is not my strong suit. I can also include my account id, I just wasn't sure if the public issue tracker was the best place to put it.

**Comment by crookedneighbor** [comment]
What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by fpepin** [comment]
59227709-88a9-4722-afc1-1ed4d45dd686

**Comment by Alys** [comment]
Also reported in the Tavern by CrazyCatLady (7648f5b3-bc3f-42c9-9505-e2bc89532560):

is there something going on with the database? my cron did not reset and i cannot park anything off or use any buffers

please help. i don't want to kill half my party >< "Error Cast to number failed for value "NaN" at path "stats.gp""

**Comment by Alys** [comment]
In case it's relevant:

fpepin has recently completed dilatoryDistress2.
CrazyCatLady has recently completed dilatoryDistress3.

**Comment by Alys** [comment]
More relevantly, both have `null` as a value for `stats.gp`. I'm fixing that now. @fpepin please wait a couple of minutes then reload the website and tell me if it's working correctly now.

**Comment by Alys** [comment]
Those two quests (and also dilatoryDistress1) do not give gp upon completion, which is rare - unique to those quests I think. I'm wondering if the code for ending a quest can no longer correctly handle giving rewards when gp is not one of the rewards. Investigating.

**Comment by Alys** [comment]
More importantly, I'm running a search through the database to find all other users who have `stats.gp` = null and I'll set it to 100gp for all of them. That's a figure pulled out of the air, but I can't do better without downloading a recent database backup (I will do that later if it turns out there's a lot of affected users).

**Comment by fpepin** [comment]
Seems to have fixed everything for me, both on web and on mobile.

Thanks and feel free to close if you want (in case more people got affected).

**Comment by Alys** [comment]
@fpepin Thank you very much for letting us know! Also for the initial report - it contained all the information we needed. :)

We'll keep this open until the root cause has been found and fixed.

**Comment by Alys** [comment]
These users from CrazyCatLady's party:

```
 "12d98578-65a2-4e5a-8c0b-6d56202aed77",
 "91ba0f3e-155c-4771-a32a-f88bf6e8bba3",
 "cdc7d641-c4eb-4f0c-8a40-1ffb7f5941c6",
 "e8f00f20-a8af-48ce-94f8-e09532916ede",
 "f0d499d1-dc1c-41dc-b26f-09ddd1d345e7",
```

and these from fpepin's party:

```
    "ff49463b-4158-4cdd-8589-b81b6e2a0b19",
    "d68616c0-0693-446d-becc-c097c0bf7b8d",
    "5ca5ab36-e700-4cd7-8e15-ed3cc5fe309b",
    "5b3c22e0-fd35-46e0-a142-4a3b2023f4b3",
    "b06d38e8-1e64-47da-9752-3a6494356e57",
    "4f71ca27-1762-46c9-a136-3d609868e02d",
    "3e581fa7-1b9b-4315-8476-5f9dc2f7f4c5",
    "b4a04544-0c83-4acc-ad86-a31dd8bdb77c",
    "bbbefe60-6232-4b0d-a812-28f5ab7e987f",
    "59227709-88a9-4722-afc1-1ed4d45dd686",
    "1a516005-d3f1-44d0-b472-19f43990a603"
```

had stats.gp = null. I've fixed them (set gp to 100).

**Comment by Alys** [comment]
The dilatoryDistress quests used to have `gp: 0` in their configuration, now they have no value for gp at all.

https://github.com/HabitRPG/habitrpg/blob/develop/website/src/models/group.js#L198 expects a value:
`updates['$inc']['stats.gp'] = +quest.drop.gp;`

I can't recall, and can't be bothered researching, what happens when you add a non-existent value to a number in JavaScript, but given that gp was null for several people in two parties who had recently completed a dilatoryDistress quest, I'm concluding that this bug was caused by the change to how the quests are configured. Either gp needs to be set to 0, or (probably better) that line of code needs to be wrapped in an `if` statement.

I'm still searching the database for affected users. I think it's actually not stored in mongo as null so my first search failed (it didn't find any of those party members, for instance; I had to look for them manually).

**Comment by Alys** [comment]
New report from CrazyCatLady (7648f5b3-bc3f-42c9-9505-e2bc89532560) from  50 minutes ago:

@Alys no worries about gold i got plenty as it is. :) i got my dailies to work but buffs are giving me the same error. i also got a notice of a quest completion when i first loaded so maybe that was what was holding up the error.

**Comment by Alys** [comment]
Tavern, 24 minutes ago, Athelinde (b69eb4a0-b36e-4277-8cc1-22dfae40d041):
Something is wrong with all accounts my group, Only two dailies were showing. And errors. After logout, clearing cache and cookies, we can't even login anymore. The login button recogniizes wrong passwords, but does nothing on a correct password.

```
{
    "_id" : "b69eb4a0-b36e-4277-8cc1-22dfae40d041",
    "stats" : {
        "gp" : NaN
    }
}
```

Also these party members, all of whom have just completed dilatoryDistress3:

```
    437203f0-8198-4d04-a352-5d3af826ad49  
    4b0228b2-1c51-460c-92a4-f3e78b117e6a  
    8e347eca-a1b7-4d85-a890-a5e38479f70a  
    cd180aea-f9bf-4bf0-99e6-b62a0f9e6359  
    f8cc66da-b76e-45bf-96a3-0452d4d60aa1
```

All fixed (gp set to 100).

**Comment by Alys** [comment]
A database search for gp set to `NaN` returns 37 other users, all had completed dilatoryDistress1 or dilatoryDistress2, now all fixed (gp set to 100):

```
0033d730-5ca6-4e66-adc7-9067b502dbd5
03fde1dc-bd06-4b1a-8661-7abf1b6f30a5
05415f11-2bde-4a33-9a86-28c9dfaadcc9
0f16c7c3-ea88-49e9-afb9-40d6b421beae
111f9978-217f-4755-8fef-a469ded53947
1a967a8d-2d00-4064-9496-c78eab83b651
2230253c-ffbb-4d41-83d2-009bcb5789c1
33991e0a-de55-4986-ac81-af78491a84de
37e7bf44-753a-459c-b8a4-369796deefff
3c71effc-a335-4f3a-8c2f-2de65e437c88
3d69f3ef-5425-4218-ae0d-335f224c3c69
3f0140e5-67ce-4619-bb15-769e79ce90dd
41db82ec-5b63-4c39-825b-345dab4f712f
41e75978-d746-43d9-932b-dcf1fbd7a91f
4a53950b-224b-427d-b193-8b8929c37cea
4d43ac29-46ba-4c6f-919f-c9d685aeb3f7
521c2fad-44ad-4943-b3a9-1adb555f8173
548724fc-53ea-426d-ad7a-2de16e3f02e8
5566b561-46b6-460f-a5eb-7e1a38c7ef10
5a9ac109-e8a3-49ba-998d-6841a3966a38
644ee620-36d7-4e64-9962-bf538463da77
6e5f93ff-de99-4c1c-a06f-cc7eb2e77d1d
714bfefd-7e1f-47ba-a08f-937e16c3d9dd
7b05f4c0-c391-4aa8-a76a-8bab69fd21c6
83803019-9b68-4c47-91cd-21fa7bbcb74b
8d2ebb4d-5ff8-4abe-8f17-787fe77e705b
8f9bf990-cebb-4d82-be46-0f7acf3684cb
922e6037-4635-4343-a2db-498af3750370
b2293f3a-bffb-4e01-8db3-7b6926677f36
bac22093-ac12-42a7-ac1f-4b38e76c8cf5
bb943344-5b48-4dfe-8a5d-f0aa05546438
bf4a934a-8c84-467a-b174-1caa73a27d5e
c1ffa941-ed99-4f5c-9476-6257fdc2b51b
d36e861c-0147-49ba-901e-78df422d09f1
e5f55d88-6e01-4571-b725-100cf33a496f
ed58f5e8-2569-46b1-ad52-69cf1c6a717a
f89ace05-0aed-4960-9dcd-554e0e906a12
```

**Comment by Alys** [comment]
To assist Socialites in explaining to players why their gold balance has changed, below are the affected users. If any of them report odd things in their accounts, especially missing gold, it's because of this bug.

aiseant  :  bf4a934a-8c84-467a-b174-1caa73a27d5e
angeline_  :  d68616c0-0693-446d-becc-c097c0bf7b8d
Aroq  :  3c71effc-a335-4f3a-8c2f-2de65e437c88
Athelinde  :  b69eb4a0-b36e-4277-8cc1-22dfae40d041
awesomelauren  :  ff49463b-4158-4cdd-8589-b81b6e2a0b19
Bejamin  :  f8cc66da-b76e-45bf-96a3-0452d4d60aa1
Boffin  :  12d98578-65a2-4e5a-8c0b-6d56202aed77
Cody  :  f0d499d1-dc1c-41dc-b26f-09ddd1d345e7
CrazyCatLady  :  7648f5b3-bc3f-42c9-9505-e2bc89532560
Dacorie  :  b06d38e8-1e64-47da-9752-3a6494356e57
Dallas  :  4d43ac29-46ba-4c6f-919f-c9d685aeb3f7
DJd34d1  :  5b3c22e0-fd35-46e0-a142-4a3b2023f4b3
Echo  :  cdc7d641-c4eb-4f0c-8a40-1ffb7f5941c6
Elianus  :  437203f0-8198-4d04-a352-5d3af826ad49
fighterkliu3  :  0f16c7c3-ea88-49e9-afb9-40d6b421beae
fightingthealbatross  :  5ca5ab36-e700-4cd7-8e15-ed3cc5fe309b
GodOfThunder6  :  0033d730-5ca6-4e66-adc7-9067b502dbd5
Holysnacks  :  41db82ec-5b63-4c39-825b-345dab4f712f
honeybearbee  :  ed58f5e8-2569-46b1-ad52-69cf1c6a717a
ibskier  :  b4a04544-0c83-4acc-ad86-a31dd8bdb77c
inspiredshane  :  7b05f4c0-c391-4aa8-a76a-8bab69fd21c6
Joshua  :  d36e861c-0147-49ba-901e-78df422d09f1
Kevin  :  8d2ebb4d-5ff8-4abe-8f17-787fe77e705b
Kfearnley85  :  2230253c-ffbb-4d41-83d2-009bcb5789c1
Kristie  :  5a9ac109-e8a3-49ba-998d-6841a3966a38
lanceur  :  59227709-88a9-4722-afc1-1ed4d45dd686
lavrim  :  6e5f93ff-de99-4c1c-a06f-cc7eb2e77d1d
leafy0512  :  83803019-9b68-4c47-91cd-21fa7bbcb74b
legend  :  03fde1dc-bd06-4b1a-8661-7abf1b6f30a5
LeonardoZhang  :  3e581fa7-1b9b-4315-8476-5f9dc2f7f4c5
LloydFury  :  c1ffa941-ed99-4f5c-9476-6257fdc2b51b
Logg_Dawg  :  3d69f3ef-5425-4218-ae0d-335f224c3c69
loki4759  :  37e7bf44-753a-459c-b8a4-369796deefff
M  :  05415f11-2bde-4a33-9a86-28c9dfaadcc9
Maeve  :  91ba0f3e-155c-4771-a32a-f88bf6e8bba3
MsStephie  :  521c2fad-44ad-4943-b3a9-1adb555f8173
MuzlL0dr  :  3f0140e5-67ce-4619-bb15-769e79ce90dd
Novaline  :  bbbefe60-6232-4b0d-a812-28f5ab7e987f
Petrobro  :  e8f00f20-a8af-48ce-94f8-e09532916ede
pip  :  b2293f3a-bffb-4e01-8db3-7b6926677f36
QuestingOrc  :  bb943344-5b48-4dfe-8a5d-f0aa05546438
Rissinussia  :  1a967a8d-2d00-4064-9496-c78eab83b651
Sabina  :  1a516005-d3f1-44d0-b472-19f43990a603
Severinus  :  8e347eca-a1b7-4d85-a890-a5e38479f70a
Shulamit  :  cd180aea-f9bf-4bf0-99e6-b62a0f9e6359
Shulinde  :  4b0228b2-1c51-460c-92a4-f3e78b117e6a
SMS13  :  bac22093-ac12-42a7-ac1f-4b38e76c8cf5
Snellopy  :  33991e0a-de55-4986-ac81-af78491a84de
spiderkiller  :  5566b561-46b6-460f-a5eb-7e1a38c7ef10
stormbringer97  :  714bfefd-7e1f-47ba-a08f-937e16c3d9dd
Tainty  :  4f71ca27-1762-46c9-a136-3d609868e02d
TheOutlandishPeabody  :  111f9978-217f-4755-8fef-a469ded53947
thor0512  :  f89ace05-0aed-4960-9dcd-554e0e906a12
Throlin  :  8f9bf990-cebb-4d82-be46-0f7acf3684cb
TichePotato  :  548724fc-53ea-426d-ad7a-2de16e3f02e8
triplesix0666  :  4a53950b-224b-427d-b193-8b8929c37cea
varuponyou  :  644ee620-36d7-4e64-9962-bf538463da77
whahappan  :  41e75978-d746-43d9-932b-dcf1fbd7a91f
wisp9  :  e5f55d88-6e01-4571-b725-100cf33a496f
YétiVolatile :  922e6037-4635-4343-a2db-498af3750370

**Comment by Alys** [comment]
CrazyCatLady (7648f5b3-bc3f-42c9-9505-e2bc89532560) reported in the Tavern 6 hours ago, referencing this comment: https://github.com/HabitRPG/habitrpg/issues/6003#issuecomment-145209715

"@Alys whatever it was it seems to have gone away now."

**Comment by Alys** [comment]
I've downloaded a database backup from 2015-10-02 midday GMT and extracted the gold amounts for the 60 users listed above. Lemoness and I will be sending a bulk email to those users to tell each of them what their balance was and to give instructions for using Fix Character Values.
