### ISSUE TITLE
suggestion: full-screen modal task editing

### ISSUE THREAD

**Issue by nomicode** [HabitRPG/habitica#6010]
when I go to edit a habit (or daily or task), make some changes, and click save, the habit window (which appears in situ in the list of habits) shrinks, and leaves me looking a different part of the habit list than I was looking at when I clicked edit

this becomes quite annoying when trying to work through the list of habits to make edits to every one, as I have to scroll back up and figure out where I was

would it make sense to have habit/daily/task editing appear in a full-screen modal? that gives more space for the crowded UX which atm is being fit into a relatively thin and long box

**Comment by Alys** [comment]
If you save and close by clicking the tick button at the top of the task rather than the save button at the bottom, you'll be left in the same part of the list as when you clicked edit.

Suggestions and feature requests are generally best placed on Trello (Help -> Request a Feature from the Habitica website) so that they can be assessed with related feature requests. However edit modals have already been proposed at https://github.com/HabitRPG/habitrpg/issues/3921

**Comment by nomicode** [comment]
ah ok thx!
