### ISSUE TITLE
Can't play any quests

### ISSUE THREAD

**Issue by printesa** [HabitRPG/habitica#6011]
I got one of the gold-purchasable quests a few days ago and when I went to check on it the next day, it had disappeared, but the gold was still gone. The quest hasn't shown up since then. In the meantime, I unlocked a new quest, but when I try to start it I get an error saying 'Your party is already on a quest. Try again when the current quest has ended.'

User ID: 1ce42912-21e0-43a6-afa4-b8ef13f88d0d

I'm using Mozilla Firefox on Windows 8.1.

**Comment by Alys** [comment]
After you bought the quest, you started it. It's running now. That's why you can no longer see the scroll, and why you can't start a new quest. You'll see the quest and its progress so far if you go to your party page. For more information about how quests work, and how to cancel the quest if you don't want to keep doing it, see the wiki's [Quests](http://habitica.wikia.com/wiki/Quests) page. If you have any questions, drop in to Help -> Ask a Question on the Habitica website. That takes you to a guild with a lot of experienced users who can talk you through it. You're also welcome to comment here with questions and we'll certainly answer, but you'll often get an answer faster at Help -> Ask a Question because there's many more people there. :)

**Comment by printesa** [comment]
Silly me, thank you!
