### ISSUE TITLE
Clicking and unclicking Todo has resulted in massive negative XP

### ISSUE THREAD

**Issue by Puppykinns** [HabitRPG/habitica#6015]
Accidentally checked off a large Todo earlier today, and gained an appropriate amount of XP per usual. But when I unchecked it again I lost easily about 2000 XP (currently at lvl 37 and was sitting at around 300/850). Checking off anything else which gives me XP seems to work normally, in that the negative value decreases. 

User ID: 915e4381-e5c4-4139-a466-3b99d7595afc

![negxp](https://cloud.githubusercontent.com/assets/14988982/10298325/be9af27e-6bab-11e5-8d87-eedc963be722.png)

**Comment by Alys** [comment]
Can you please tell us the name of the To-Do? If it's private, please email it to admin@habitica.com and quote the number 6015 (this issue number).

You can fix your XP using [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values).

**Comment by Puppykinns** [comment]
Sure thing. The To-Do involved was "Planned Short Term Tx". I'm a grad student, so at the start of my semesters I make some massive To-Do lists to keep track of all my work for each class. 

Thank you for reminded me about the Fix Character values feature. Totally forgot about it x.x.

**Comment by Alys** [comment]
I'm not sure there's a bug here, based on my current understanding. I happened to have a database backup stored locally from 2nd October. On that day, you were at level 33. The XP required to go from the start of level 33 to the start of level 37 is 3240 (770 + 800 + 820 + 850, [ref](http://habitica.wikia.com/wiki/Experience_Level_Chart)). What I think happened is that before you ticked off that To-Do, you were already part way along that progression because of your normal tasks, and then the To-Do gave you a large amount of XP that took you the rest of the way to level 37. When you unticked the To-Do, you lost that same large amount of XP, leaving you with a significantly negative XP. 

This is what's meant to happen when you untick a To-Do - you lose the appropriate amount of XP and if that takes you negative, so be it. We don't drop you down levels because the calculations for that are more complex than just giving you negative XP and there'd also be issues to consider with any features that you'd unlocked from levelling up.

I'm pretty sure you didn't lose anything by unticking the To-Do, except the same amount of XP that you'd gained when you ticked it. In fact, you actually gained something - you reached level 37 sooner than you would have. :) But regardless, you can use Fix Character Values to adjust your stats as you think best!

Let us know if that doesn't seem to be what actually happened. I'm going to close this now because I'm pretty sure everything was behaving normally, but you're welcome to keep commenting here!

**Comment by Puppykinns** [comment]
I'm more than happy to bank on that having been the case versus it being an actual bug, in which case I'm sorry for the faulty report. But thank you so much for looking into it regardless :).
