### ISSUE TITLE
Unable to Cancel Subscription

### ISSUE THREAD

**Issue by TwoKillerMockingbirds** [HabitRPG/habitica#6016]
I purchased a subscription using a pre-paid card- The card was $45, and I expected that at the end of three months either the purchases would bounce or I would manually cancel the subscription.

I fell out of using HabitRPG for a good while, and when I returned I saw that my subscription was still active and that I had been receiving subscriber benefits. However, whenever I try to cancel the subscription, I get redirected to a page reading "{"err":"Cannot read property 'current_period_end' of null"}"

I am using Windows 8 and a Chrome browser to view the page
User ID; 4f04fdcc-9948-49dc-b7b3-e908ff2cc659

Thanks!

**Comment by Alys** [comment]
When you see that error message, it's a sign that our payment processor has already cancelled your subscription due to multiple failed payments, presumably in this case because the card ran out of money. I'm about to remove the subscription information from your account, so you do not need to take any further steps to do that.

**Comment by Alys** [comment]
Also, I've checked your payment records and the first payment failure happened on 2015-04-12, so your subscription was cancelled in April. You were only ever charged the first $15 payment, for a subscription period from 2015-01-12 to 2015-04-12.
