### ISSUE TITLE
`Repeat Every` is duplicated under `Advanced Options`

### ISSUE THREAD

**Issue by ahstro** [HabitRPG/habitica#6025]
As you can see here, the `Repeat Every` option is duplicated in both the "regular" options as well as under `Advanced Options`. This seems redundant, but I'm not sure what the best solution is and decided against making this a PR.
Do you agree that one of them should be removed, and if so, which one? I think, as a user, I would prefer if it was removed from `Advanced Options`, but that the `Repeat` option remained there, but I certainly don't speak for anyone other than myself.
![habitica-repeat-every](https://cloud.githubusercontent.com/assets/3090888/10387267/584c017c-6e60-11e5-8ce2-34ac05bfee31.png)
##

**Comment by Alys** [comment]
That was a deliberate decision made when we introduced extra repeat functions a few months ago. Previously, the days of the week were the only repeat options and they were in only the main part of the edit form. 

The change added the "Every X Days" repeat option, and that was put in Advanced Options to keep the main part of the edit form simple (some players appreciate simplicity and don't often or ever use the advanced options). Because that drop down was in the Advanced Options section, the associated form fields were also duplicated there, so that when you changed the repeat type, you could immediately set new values for your chosen repeat type, without having to go back up to the top part of the form.

The idea was that once you've chosen your preferred repeat type, you're unlikely to want to change it often (so it's only in the Advanced section), however you might want to change the number of days or days of the week often, so that part is in the non-Advanced section.

We'd probably want to hear opinions from others before making any decisions to change this, and I'd recommend not starting any code changes until/if a staff member approved the change.

**Comment by ahstro** [comment]
My concern is that, for users that keep the `Advanced Options` open, like myself, the layout looks repetetive, while, for users that aren't concerned with the advanced features won't really use the second `Repeat Every` location.

**Comment by SabreCat** [comment]
I'm for taking it out of Advanced Options, but at the weight level of "somebody who uses Advanced Options sometimes" rather than "official Habitica staff member opinion", heh.

**Comment by crookedneighbor** [comment]
I say we leave it as is until the task page redesign happens.

**Comment by brendan98** [comment]
I'm not a contributor but I just wanted to chime in that I found this very confusing.  I ended up asking in the tavern what this meant and was surprised that there were 2 widgets on the same UI that controlled the exact same thing.

**Comment by Atomk** [comment]
I was about to open a new issue, glad someone did before me. All of you have great points to be honest, but it is really confusing. Maybe it could be put in a "Repeat section" external to avdanced options but Alys is still right, simpler is better. @crookedneighbor I can't seem to find information on this redesign but I'm interested, can you point me in the right direction?

**Comment by joedragons** [comment]
As stated/hinted, seems to affect "Every X Day" dailies the same way.  That's how I noticed.
I think my monitor is pretty big at 1920x1080 but under the new popout system I'm for less redundancy/anything that doesn't make me need to scroll more=)
Since advanced options are expanded by default I am for leaving it there tho there may be aspects of the tasks that others use differently or are different on mobile I'm not thinking of.

**Comment by Alys** [comment]
@joedragons Advanced Options are only expanded by default if you've selected that behaviour under Settings > Site.
We're part way through a project to improve the website in various ways so it's likely that we'll look at streamlining the task edit screen during that project.

**Comment by Alys** [comment]
This was changed in https://github.com/HabitRPG/habitica/pull/8477
