### ISSUE TITLE
Everything I did yesterday seems to have been undone

### ISSUE THREAD

**Issue by Gwillewyn** [HabitRPG/habitica#6026]
All the tasks I completed (which was a LOT yesterday) have become unchecked.  Everything I bought, everything I added or changed on my to-do-list is gone.
Yesterday does not appear to have happened. :/

**Comment by Alys** [comment]
I'm very sorry about that, @Gwillewyn! I can imagine how frustrating and annoying it must be!

It's an example of this bug: https://github.com/HabitRPG/habitrpg/issues/4313

Near the top of that issue, there's an "Advice" section, which will help you recover from any unfair damage you might have taken from your incomplete Dailies, and which will give you some tips to avoid this happening again. It's an intermittent bug and we're really not sure exactly what's causing it or how to stop it, unfortunately. :(

I'm going to close this now since we have the bug reported in that other issue, but if you have any questions, you're welcome to comment here.

**Comment by Gwillewyn** [comment]
I'm not convinced that this is the same bug.
Several _new_ (unfinished) tasks that I added to my to-do list also disappeared.  That seems not to fit with #4313.

First of all, it was not just dailies that were unchecked.  In fact, those actually appears to have stayed checked.  My streaks are still fine, and I didn't take any damage.

It seems like everything I did late in the day disappeared. (My dailies were checked in the morning.)
I strongly suspect this happened because I checked off a lot (and I mean a lot) of things at the same time. I might have clicked too fast and not allowed each task to process correctly.
Or it could be related to finishing a really massive , dark red, 12 sub-task TODO.

**Comment by Alys** [comment]
I'm afraid it is that bug. Dailies becoming unticked and doing damage is only one symptom of it. What happens in that bug is that your browser holds on to actions you took, instead of sending them to the server, which makes it appear as if they've been applied, but they haven't been permanently saved. Later, often after one or more page reloads, it then either sends them or looses them permanently. So for example, you can add several tasks and your browser makes them appear on the page, but it doesn't sync them to the server. Later, when the browser does sync to the server, the tasks disappear because they were not saved. "Everything I did late in the day disappeared" is a strong indicator of that bug. All the actions you took later in the day were not saved to the server. 

Ticking off many things at once can cause sync errors, and is not recommended for that reason, although that's not necessarily the same as this bug.

Completing a red To-Do with a checklist would not have caused this. A very valuable To-Do is no different than any other To-Do, except that you earn more from it.
