### ISSUE TITLE
A whole day missing from Dailies History

### ISSUE THREAD

**Issue by jgxpro** [HabitRPG/habitica#6027]
On 10/08/15 I forgot to check 5 of my 5 active dailies (I had done them in fact), so I expected considerable loss of life, etc. to be corrected today. 
Instead On 10/09/15 (today morning), I've found, that it's like the day before yesterday (10/07/15) doesn't exist in Dailies History, while the status of my character is like it should have been yesterday morning, and no loss happened. The column that is shown for 10/08/15 is for 10/07/15 in reality. And though I forgot to check it till 02.00AM 10/09/15 (my alternative deadline for checking). 
I would need 
1) CORRECTING A BUG/MYSTERY: a 10/07/15 column with data shown for 10/08/15 at the moment, and 
2) CORRECTING MY MISTAKE: a similar column for 10/08/15 with the same green fields as it is shown now, but instead of a red 'X', a yellow '-' for bike/running (not active on those days), if possible, not to loose my well deserved performance :)

![screenshot-oldgods net 2015-10-09 10-04-18](https://cloud.githubusercontent.com/assets/15045563/10388833/a2ec07ec-6e6d-11e5-8602-9c5d08633310.png)

UserID: 8eee6c4d-4fe5-423c-abfa-b9599bde61c0
Win7-64bit, Chrome: 45.0.2454.101 m

Thanks in advance!
##

**Comment by Alys** [comment]
If you didn't use Habitica at all on the day when you forgot to tick your Dailies, then your [Cron](http://habitica.wikia.com/wiki/Cron) wouldn't have run that day, and when you used Habitica the next day, your Dailies would still have been ticked from the day before.

Other possibilities are that cron just didn't run for you, which happens occasionally, although it would be a bit of a (fortunate) coincidence that it happened on the day when you'd forgotten to tick your Dailies! :)

You might have also been hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313. One effect of that bug is that progress made on one day is held onto by your browser and not sent to Habitica's server (resulting in Dailies that you had ticked appearing to have not been ticked). Then the next day, your browser releases the data, resulting in Dailies being ticked that day, even if you didn't tick them yourself. That issue has an Advice section near the top that will help you recover from any unfair health loss you might have received (although it sounds like there wasn't any, which is good!), and it will show you how to update the streaks on your Dailies. Even if that bug didn't affect you, that advice might still be helpful.

Let us know if you have any questions about any of that!

**Comment by jgxpro** [comment]
Wow, what a quick response :)
I've searched for a while before asking not to bother anybody in vain, but my problem is different in my opinion. My Dailies were unticked today, no problem with that, like it seems in  #4313. I can check/uncheck them, thery function properly.

To put it simple: it's like yesterday (10/08/15) hasn't happened, my status is like it was in the morning yesterday (10/08/15), only the date skipped from 10/07/15 to 10/08/15. Where is 10/07/15?? Quite spectacular :)) 
Consequensces:
+: no damages booked for forgetting to tick all 5 active dailies, all my streaks are intact (- 1 day), BUT
-: I made 10/08/15 Dailies, I'm a day behind, I can't book them in any way (not gained plus ~ loss),
-: at the bottomline: it should have punished me for forgetting to tick, if the system worked correctly. I can modify these things in a rather complicated process, but it would be more trustworthy, if it had worked, as it should.

Is there anything I/anybody can do to insert 10/07/15 at all, and correct 10/08/15? :)

**Comment by Alys** [comment]
If you're sure it's not #4313, then it might be one of the other two causes I mentioned.

There isn't an easy way to insert data for a day. We do have an [API](https://habitica.com/static/api) which lets you modify task data in a json format. The historical values for the Dailies are stored within the tasks so you could export your data, estimate what the missing values should be based on existing values, and use the API to reinsert the data for the Dailies with the new values in place, but it would be time consuming and give you only a rough estimate of the missing values. Let us know if you have any questions.

**Comment by jgxpro** [comment]
Thanks Alys for your kind support, even to read it is time consuming :)
Here's what I've done (with QUESTION outlined): 
- increased Streaks earned yesterday by +1 at the 5 appropriate task/daily individually
- ticked all the 5 items relevant for yesterday now (then unticked), checked the growth in Experience&Gold and added to the existing values ~ roughly the same gain like I'd have got from ticking them properly yesterday, only slight difference can be
- Health remains on the same level
- Mana: this is for later activities and hidden for me, but as far as I understood I should've got +10MP yesterday as I finished all my Dailies -> corrected it - IS THIS A GOOD ASSUMPTION?

IS THERE ANYTHING ELSE you'd advise to correct? 
I hope these problems are not so frequent (this happened within a week of usage), aren't they? :)

**Comment by Alys** [comment]
How much mana you gain overnight depends on your stats. You can learn about it on the wiki's [Mana](http://habitica.wikia.com/wiki/Mana) page.

Whether this happens often or not depends on what caused it. If it happened because you didn't use Habitica at all on the "missing" day (my first point in my first post), then the same thing will happen again on any other day you don't use Habitica.

If it was the second point in my first post, it's likely to be rare; we don't see many reports of cron just not running.

If it was the third point, it might be rare or common. Unfortunately [that bug](https://github.com/HabitRPG/habitrpg/issues/4313) is intermittent and hard to predict. The Advice section near the top of the issue will help you avoid it.
