### ISSUE TITLE
Only one daily reset

### ISSUE THREAD

**Issue by stormyhearted** [HabitRPG/habitica#6028]
Only one of my five dailies reset this morning. I have a custom day start at 5am, which I've had since I joined.

**Comment by Alys** [comment]
Did you receive more damage overnight than you were expecting, as if you hadn't ticked off the Dailies yesterday? If so (and perhaps even if that didn't happen), it's likely to be an example of this bug: https://github.com/HabitRPG/habitrpg/issues/4313. In brief, your browser held on to your actions of ticking Dailies instead of sending them to Habitica's server to be saved, making it look as if the Dailies had been completed, but they weren't. This morning when your browser communicated to the server, it then sent your actions, causing your Dailies to be marked as completed today.

Near the top of that issue, there's an "Advice" section that will show you how to untick your Dailies for use today without losing gold, etc, and how to recover from any unfair damage you might have received.

I'm going to close this now since we have the bug reported in that other issue, but if you have any questions, you're welcome to comment here.
