### ISSUE TITLE
My to-dos vanished

### ISSUE THREAD

**Issue by wispered** [HabitRPG/habitica#6029]
I spent all morning yesterday updating my to-do list (both writing in a ton of new ones and finishing a bunch) and today it's as if I didn't do any of it, my to-do list is missing all the new stuff and the completed stuff is still there. My ID is b5a371d4-c704-4867-b253-f584e5c9be86

**Comment by Alys** [comment]
I'm so sorry about this, @wispered! I can imagine how frustrating that was and how much of your time was wasted. :(

It's an example of this bug: https://github.com/HabitRPG/habitrpg/issues/4313. In brief, your browser held on to the changes you made instead of sending them to Habitica's server to be saved permanently, and then at a later time when it did sync to the server, it lost the changes. I'm very sorry but there's no way to get them back.

Near the top of that issue, there's an "Advice" section. Points 3 and 4 might be of use to help stop it happening again.

I'm going to close this now since we have the bug reported in that other issue, but if you have any questions, you're welcome to comment here.
