### ISSUE TITLE
Seasonal Shop items don't appear for repurchase after using Orb of Rebirth

### ISSUE THREAD

**Issue by TyranoTank** [HabitRPG/habitica#6031]
I recently used an Orb of Rebirth after reaching level 100. Before I did so, I purchased all the 2014 fall gear and the 2015 Rogue fall gear. After rebirthing those items have not appeared for repurchase like they are supposed to. I use an iPhone to access the site so I cannot be certain they don't appear on a computer. However, I don't have one at the moment. Thanks for your time.

**Comment by Alys** [comment]
You said that you recently used the Orb. Does that mean you are still below level 10 and have not chosen a new class yet? If so, you will see only Warrior gear available for purchase, since you are a Warrior now. If you choose Rogue at level 10, you'll then be able to repurchase all previously bought Rogue gear (similarly, if you choose Healer or Mage, you'll be able to buy Healer or Mage gear, respectively). You can read more about this on the wiki at [Orb of Rebirth](http://habitica.wikia.com/wiki/Rebirth).

If you have already chosen the Rogue class and still do not see the Rogue fall gear that you bought, we can investigate further, but we will need to be able to identify your account. Please see step 6 in the [bug report instructions](https://github.com/HabitRPG/habitrpg/issues/2760) (available through Help -> Report a Bug on the Habitica website).

**Comment by TyranoTank** [comment]
So I can only purchase the gear for the class I am currently playing. That would make sense. Thanks for letting me know, sorry to use up your time. It seems there is no bug.
