### ISSUE TITLE
Need a way to select multiple tasks to place into a tag all at once

### ISSUE THREAD

**Issue by Four2eightone** [HabitRPG/habitica#6035]
There are times where I add a bunch of tasks and it ends up getting quite disorganised. So when I decided to begin using the tags(as I've only just begun playing Habitica) to get my way around my tasks easily, it's quite annoying that I have to go through a single task, enable it, save, then move on to the next one. If there is a way to select tasks all at once in order for them to do be tagged the same thing, it would make tasks more faster to organise, meaning we'd have more time to get the actual work and dailies we've set to get done for the day. The multiple task selecting may also work well for deleting tasks, etc.

**Comment by Alys** [comment]
When you're adding new tasks, if you select one or more tags first, all of those tags will be applied to the new tasks.

If that's not what you're hoping for, please go to Habitica's Help menu and select "Request a Feature".  That will take you to our Trello board where we collect feature requests. It's helpful to have them all collected there so that we can analyse them all when we're planning the future direction of Habitica. 

GitHub is used for bug reports. Occasionally we create issues for features that are under active development or that people want to put a [bounty](http://habitica.wikia.com/wiki/BountySource) on to encourage contributors to work on the feature. I'm going to close this issue now, but if you did want to put a bounty on it, comment here and we'll reopen it.
