### ISSUE TITLE
Sorting the To-Dos list sometimes causes one task to jump to the wrong position after a sync

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6040]
When dragging To-Dos to new positions in your To-Do list, occasionally one will initially appear in the correct position but then after a sync, it will jump to a new position.

So far, we've found that every time this happens, you can drag it to the correct position a second time, and then it will stay in place permanently.

In most cases, To-Dos will remain in their new positions after only one move.

If you want to avoid all chance of To-Dos being mis-sorted, delete your completed To-Dos every three days. Export them first if you want to keep a permanent record of them. To learn how to delete and export To-Dos, refer to the "Clean up" section in [To-Dos](http://habitrpg.wikia.com/wiki/To-Dos) on the wiki. There is other useful advice about maintaining the sort order in the "Rearranging To-Dos" section of that page.

You don't need to comment here if you notice this problem because it happens to everyone occasionally. However if you notice it happening very often (e.g., almost every time you move any To-Do) or if you notice it happening two or three times with one specific To-Do, please tell us about that.

_NB: This is a minor version of a much more severe sorting bug that has been resolved: https://github.com/HabitRPG/habitrpg/issues/2606_
##

**Comment by kellarules** [comment]
I'm dealing with a consistent problem with the order of my To-do's that only started happening _after_ problem #2606 had been resolved. 

First, some explanation of how my system works: I use a tag system that allows me to see just the to do's that I want to be currently working on, while having other ones I want to do soon but not yet hidden. I do this by first having a #1 tag and a #2 tag that I apply to ALL of my habits and dailies and I keep both #1 and #2 tags on at all times. If a to-do is current and urgent, it gets tagged #1 and #2. If it's not urgent but I want to do it soon, it gets tagged only #1. If it's something I want to do eventually and just want a record of, it doesn't get either tag. I also keep my to do list ordered so that ones with #1 and #2 are at the top, just #1 are next, and neither tag are at the bottom. 

The issue I've been having is that when I switch from #1 and #2 on to just #1, whatever 2-4 to-do's were at the bottom of my filtered list move themselves to the bottom of the new expanded list. Sometimes one item from the expanded list gets put under those 2-4 items. The same thing happens when I de-select #1 and have my full list, this time pulling anything from the #1 list that made it to the bottom, meaning that I have things from my first and second list completely mixed together with my bottom list in several different places of the overall list. It makes things get mixed up really fast. The point of my system is so that the different types of to do's are all clearly sorted with or without the tags on, and with them getting mixed up so easily, I have to remember which ones are supposed to be attached to which tags and that partially defeats the point. 

Now for things I've tried: 
--I've tried re-sorting them again. But I can move them over and over and they just get moved to the bottom of the list again when I de-select the tag. 
-- I've tried syncing, reloading the page, and deleting my old to do's. No change. 
--I've tried using another browser. I'm currently in firefox but I tried safari and the same thing happened. 
--I've tried deleting my cache, browser, etc. This problem actually turned up after I cleared everything because of a different bug, but that was just a couple weeks ago. 

I don't quite have a big enough screen to easily take good screen captures of what's happening, but if it would help explain what I'm talking about i can figure out how to get a good one.

**Comment by kellarules** [comment]
Oh and I forgot to mention. I could not replicate this in the order of the dailies. If i messed with the tags and order in habits, I did notice that the order changed, but I didn't rearrange the order enough to figure out if it was the same pattern as with my to-do's.

**Comment by Alys** [comment]
The current To-Do sorting feature works by comparing the positions of all To-Dos. When you're filtering to show only some To-Dos, the position that you think you move a To-Do to might be different than the one you are actually moving it to. E.g., if you have two hidden To-Dos at the bottom of the list, and you move a visible To-Do to the bottom, the visible To-Do might be placed above or below or between the two invisible ones. You can't control exactly where it's goes because you can't see some of the To-Dos around it. If you sort To-Dos while no filters are active, you should find it works better, although I realise that's very much not in the spirit of your system.

We're making some large, back-end changes to how tasks are managed, and that will involve modifying the sorting feature. When it's finished you might find that the situation improves, although I can't guarantee that because the work is still in progress and will be for some time to come.

One thing I find useful is to assign an [emoji](http://habitica.wikia.com/wiki/Emoji) to each tag, and then add that emoji to every task which has that tag (tasks can have multiple emojis if they have multiple tags). That gives a clear visual indication of which tasks are attached to each tag. For me, that makes sorting less important.

**Comment by Alys** [comment]
Emoji in Habitica: http://habitica.wikia.com/wiki/Emoji

**Comment by kellarules** [comment]
Aha! I tried reordering the list while all tags were off and it worked! I messed with it back and forth and the order stuck. So I'll keep that in mind if things get messed up again. 

I also messed with the emoji idea and I liked it. I was a bit frustrated at how, because my screen is kinda small, it created line breaks in my tasks that I didn't want and there wasn't an easy way to get everything on the same line to look neater. But I decided to use it anyway.

**Comment by Alys** [comment]
@kellarules You can often prevent a line break occurring between two words by replacing the space with these six characters: `&nbsp;` which is the HTML code for "non-breaking space". If you replace all spaces in one task with that, the task **might** stay on one line, although the limits imposed by the task columns might still cause it to wrap. You can at least partially control where it wraps by putting `&nbsp;` in any places where you definitely don't want wrapping (e.g., perhaps in every space except the one just after the emoji, which should cause the emoji to be on one line and the words on another).

**Comment by paglias** [comment]
Should be fixed in v3
