### ISSUE TITLE
Forces you to purchase items during inspection (clicking on gold-purchasable items buys them instantly)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6041]
I was using chrome on my phone (Android) to access the website. I went to inspect items in the specials section of the market when I tapped on Spooky Sparkles. I wanted to know what it was, but without any confirmation the tap ended up buying it for 15 gold (ridiculously expense for a level 3). I didn't understand what happened and tapped it again, losing another 15 gold.
Tapping an item to inspect it on your phone, because there's no additional information apart from the image, should not force you to buy something. There should be a confirmation. Makes it even worse that I'm new to the game, and by exploring the game I'm forced to lose gold that's so difficult to come by. Its not encouraging at all, even though that's what this games all about.
##

**Comment by Alys** [comment]
I'm sorry about that, @Nomsterr. It must have been frustrating! You can go to Settings -> Site -> [Fix Character Values - Wikia](http://habitica.wikia.com/wiki/Fix_Character_Values) to give yourself back the gold. We typically don't have a confirmation step for gold purchases because gold spent accidentally is easy to refund and confirmations are annoying when you're buying many items, which people often do for Spooky Sparkles (for example, I bought about thirty at once to stock up on them). When you're on the website on a PC, you can hover over an item with your mouse to see an explanation of it, and you can access the same information on a mobile device's browser by tapping and holding. You can also go to Help -> Ask a Question to get to a guild where there's a lot of experienced users who will answer any question, or Help -> Overview for New Users to access the wiki where we have a lot of additional information about almost every feature on the site.

We'll leave this open for a while so that we can consider the UI aspects of it. Thank you for the feedback!

**Comment by anilanar** [comment]
Couldn't there be a confirmation-like dialogue where the user can pick number of items to buy, 1 being the default value. That way it would solve both problems, and the button would be called BUY so it sounds more explicit than clicking on a list item to directly make a purchase. I can work on a mock if this makes sense.

**Comment by Alys** [comment]
@lemoness What do you think of that suggestion?

**Comment by crookedneighbor** [comment]
I'm :+1: on it for things that can be purchased more than once (gems, the transformation items). Wouldn't work for the cards, since you have to distribute them immediately. 

In my opinion, anything purchasable in the rewards section should be a easy one click without confirmation.

**Comment by lemoness** [comment]
I think Rewards should be a one-click purchase, especially since it's so
easy to restore your gold, but I am fine with other things having a
confirmation.

**Comment by crookedneighbor** [comment]
It can be done piecemeal.

**Comment by crookedneighbor** [comment]
Whoops, wrong issue.

**Comment by Alys** [comment]
I'm closing this since the consensus is that gold-purchasable items should be one-click for ease of use, and because accidental purchases are easy to recover from with Settings -> Site -> Fix Character Values. 

I've checked gem-purchasable items under Inventory, Quests, Avatar, and Backgrounds, and they already have confirmations.
