### ISSUE TITLE
Suggestion: Improved checklists

### ISSUE THREAD

**Issue by rayman89** [HabitRPG/habitica#6050]
I wanted to ask for the feature to be able on the checklist to specify the difficulty of the sub tasks and it's deadlines and that you get rewards for checking them off and then some extra reward for clearing all of them.

I think this would be nice cause it motivates you to keep going if you are rewarded when you accomplish some part of the goal specially if it's a big one and creating a lot of new to do's to be able to get it makes a mess. So the list is good for keeping things organized and compact but at the moment lacks the features previously mentioned to make the system more useful IMO.

**Comment by Alys** [comment]
@rayman89 GitHub is used for bug reports, and Trello is used for feature requests. I see that you've already written your idea on the [checklists trello card](https://trello.com/c/PJ1iJ413/65-checklists-v2), and since this isn't a bug report, I'm going to close it now.

Note that for Trello, you don't need to create a new post for each suggestion - it's correct to add your ideas as comments on the existing posts, so what you've done on that trello card is correct. If you'd like more information about the feature request process, click on the Habitica Help menu and then on "Request a Feature". That takes you to a special card in Trello that describes the process of making feature requests (although you don't need to do that now for your checklist idea since it's already in the right place!).

**Comment by rayman89** [comment]
Thank you for the clarification.
