### ISSUE TITLE
Drops disconnected to tasks, received in the inventory in the morning.

### ISSUE THREAD

**Issue by Fabiele** [HabitRPG/habitica#6069]
User id: d11be208-652b-4ab9-8515-2451b89e1e92
OS X Yosemite 10.10.5
Google Chrome
For the last couple of days, all my drops are already in my inventory first thing in the morning, before I completed any task. My Data Display Tool, in the morning, before anything, was showing I had already received all my drops, so they are not getting connected to tasks randomly, as usual.
These last 2 days, one of my dailies (one with a checklist) was already checked, even though I hadn't completed it yet (it was due). Yesterday I completed all of my dailies, but today I lost some of my health and lost the perfect day streak.

**Comment by Alys** [comment]
Sorry about this @Fabiele! You're being affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313

In brief, your browser/app is holding on to actions that you take instead of sending them to the server straight away, and then later (e.g., when you reload the site in the morning), it then sends all your actions to the server, resulting in the server giving you drops for them at that time.

There's an advice section near the top of that issue which will help you recognise and avoid this bug.

**Comment by Alys** [comment]
BTW, I should have said, you're welcome to comment here if you have questions or would like clarification.
