### ISSUE TITLE
Lost Gems

### ISSUE THREAD

**Issue by isquish** [HabitRPG/habitica#6077]
c48300fd-f119-49b5-9e49-d794189437f8

I bought all the items from the seasonal shop + 9 spooky potions, however the next day I noticed that some of the items weren't appearing in my inventory.  Checking the Seasonal Shop, some of the items are once again showing as unpurchased (but my Gems were still spent).

I'd love to see a log of purchases to verify what happened, but I don't see any such data available.  I'm not too concerned with the lost Gems beyond getting the full set of Seasonal Shop items before they're gone (and I can't be any additional Gems until Nov).

Help!

**Comment by Alys** [comment]
I'm sorry about that @isquish! I've reset your gem cap so that you can rebuy the necessary gems. If you need gold for that, you can go to Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values). Let us know if anything is still wrong. You can comment here and we'll see it and respond, even though I'm closing this now.

**Comment by isquish** [comment]
Repurchase went fine, nothing else seems to be amiss.

Thanks for the quick help!
