### ISSUE TITLE
Manual timezone

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#6079]
We should give users the ability to set their timezone manually, it would have several benefits:
- Users who signed up with an app that didn't specify the timezoneOffset will have the ability to change it (in fact it'll be adjusted automatically once they use the site, but anyway)
- Users who travel a lot abroad may want to stick to the same timezone even if for a few days their actual timezone has changed

We should also rethink whetever the timezoneOffset should be adjusted automatically at all or not

cc @vIiRuS @Alys @veeeeeee @crookedneighbor 
##

**Comment by veeeeeee** [comment]
@Alys or @lemoness could probably tell you this more definitively, but I regularly see users asking about the cron times, so I think having the option to set it manually in settings would be extremely helpful.

**Comment by phillipthelen** [comment]
We would have to find a way to make it very clear what the timezone is/does and what the custom day start is and what it does… it feels like that can get confusing for people easily. As both kind of do similar things.

**Comment by Alys** [comment]
I think it would also be helpful for the automatically determined timezone to be displayed to the user. E.g., it could say "Habitica has been told by your PC / mobile device that your timezone is GMT+10. If this is incorrect, please adjust your device's timezone setting."  I'd like us to do that even if we don't provide an option for changing the zone. (If I don't hear any objections in a couple of days, I'll log a new issue for that alone. It would be suitable for a not-so-new contributor.)

It could then go on to say something like "If you need Habitica to use a different timezone than your PC / mobile devices uses, select a zone from the form below." 

My reasoning for this is that we really don't want the users to adjust their timezone in Habitica just because they don't realise that their own device has it wrong. That's going to cause them problems later (e.g., if they move to a new zone, they'll have to update Habitica manually).

We'd also need to put in strong warnings about daylight savings changes. They'd need to adjust their timezone manually then too.

It might be worth adding a feature that notices when their automatically determined timezone changes (`timezoneOffset`) and then notifies them that they might want to change their manual one.

**Comment by lemoness** [comment]
I like the idea of a warning that detects a timezone change, and I also
like the idea of displaying their time zone. I think separating the time
zone of Habit and the device i a big can of worms, and would like to avoid
it where possible.

**Comment by Alys** [comment]
The code to display the timezone has been merged (a comment from me near the end has a final screenshot) https://github.com/HabitRPG/habitrpg/pull/6228

I'm agreeing with Lemoness about a manual timezone change being a can of worms. We'd get some power users who'd use it appropriately, but we'd get many other users who'd change it without realising what it would do (and without reading any warnings we'd put around it) and who'd then run into problems with cron.

**Comment by librarianmage** [comment]
Do we still want this? It seems that it would either be misused or not be heavily used.

**Comment by Alys** [comment]
I still feel that a feature to manually change your time zone will be troublesome. If it's done, I'd like to be after we implement a planned feature that will give users more protection from unexpected crons - that will  dramaticlly reduce problems from people setting their time zone incorrectly.

**Comment by lemoness** [comment]
I'm going to close this thread for now. We can reassess it after we have other features that protect users against unplanned crons.
