### ISSUE TITLE
Eggs disappeared en masse from inventory

### ISSUE THREAD

**Issue by jkadlubo** [HabitRPG/habitica#6080]
Yesterday (possibly earlier, but I'm not sure) I sold almost all of the common eggs that I had, leaving 10 of each kind (9 of one kind, but I forgot if it was lion or panda). Today all of those common eggs are gone, I am only left with quest eggs and those I earned today.
I have seen a few "error, please reload" messages today and yesterday but didn't pay much attention to them.

My ID: 7d6c309a-50ea-4c30-9717-58f9e2906979
Since selling the eggs I've been only logged in on a Win7 computer running Chrome. Right now I also checked my android and the inventory looks the same.

**Comment by Alys** [comment]
Sorry about that @jkadlubo. When you see that reload message, it's really important that you do reload because otherwise your browser can stop syncing correctly with the server, resulting in a variety of possible errors. I've reset your eggs to the ones you had a couple of days ago. I haven't adjusted your gold balance - if you'd like to do that, you can go to Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values). However you're welcome to keep the gold that you got from selling the eggs if you wish to.

**Comment by jkadlubo** [comment]
I reloaded after almost every such message and that's why I thought it was
strange that the eggs disappeared. I just didn't read the message
carefully. Sorry for misleading writing. Thank you for the eggs.

Joanna

2015-10-22 0:29 GMT+02:00 Alys notifications@github.com:
