### ISSUE TITLE
Helm disappeared

### ISSUE THREAD

**Issue by saraehoule** [HabitRPG/habitica#6101]
I'm a new player, so apologies if this is a silly issue or if it has been mentioned already.  I could not find another mention of it.

I earned enough gold coins to buy a leather helm. I put it on my character, then closed my browser window and went away for a while. When I returned to the game later, the helm was gone.  It was not on my character, and is not listed in her inventory.  The gold used to purchase the helm is also gone.

Browser: Chrome
OS: Windows 8.1
user id: 990b58dd-4b0c-4cbc-af10-c5ebe8f1334e

**Comment by Alys** [comment]
If it's not shown in your Equipment page, then it will definitely be available to buy again from the Rewards column. Reload the website if you're not seeing it; if you still don't see it, clear your cache, cookies, and local storage and reload again.

I'm going to close this now because I'm confident that it's just a display issue, but you are most welcome to comment here again if you need more help! We can reopen this if it turns out I'm wrong and there's a new bug. :)

You can regain the gold using Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values). Settings is the gear-shaped icon on the top right of the site.
