### ISSUE TITLE
Task display gone, all menus open, no links working

### ISSUE THREAD

**Issue by kellarules** [HabitRPG/habitica#6104]
I opened habitica this morning and the display didn't load properly. A blank page was in place of all of the tasks, every one of the drop down menus was defaulted to drop down, even ones I would only be able to see if someone sent me a message. Of all the drop down menus, the only ones that had links that worked was the help menu, which was why I could access this thread. My avatar also appears to be a star fish and maybe also a snow man? Screen shot below. 

![habitica display 10 25 15](https://cloud.githubusercontent.com/assets/12877267/10717225/3f4da36e-7b0e-11e5-87ec-7abc2ecbdd93.jpg)

I tried reloading the page, I tried quitting firefox and restarting it. I'm currently on Firefox 41.0.2. and my operating system is Mac OS X. 

Unfortunately I cannot provide my User ID because the links I would normally use to access it are broken.

**Comment by Alys** [comment]
Please try using Habitica on another browser (preferred) or on the same browser using incognito mode (might not be as reliable). If that works, then the problem is likely that you need to clear local storage on your preferred browser - if you're not sure how to, google for instructions for your browser (it's different than clearing cache and cookies).

If that doesn't work, we'll need to identify your account. The easiest way would be for you to email admin@habitica.com with the email address you used when you created your Habitica account, or with the username you use to log in (NOT your profile name that displays in chat). If you use Facebook to log in, please email us the URL of your own Facebook page. Please also describe in the email a couple of your tasks so that we can be certain the account is yours. Sorry about this, we do need to be sure the account is yours before we look at it in detail.

**Comment by kellarules** [comment]
Thank you! 

I tried safari and it worked just fine, so I looked up how to clear local storage on firefox, did it and now it's working just fine on fire fox too! Unfortunately there isn't an easy way to _just_ clear local storage on firefox so I had to clear all my browsing history, cookies, cache everything. But from how long that took, it looks like it was time to do that anyway.

**Comment by Alys** [comment]
Thanks for letting us know! Good to hear it's working.
