### ISSUE TITLE
Daily task tick/untick loop

### ISSUE THREAD

**Issue by msaluste** [HabitRPG/habitica#6105]
If You finish a daily, You get certain amount of gold, xp and mp. If you untick the daily, the same amount is given back. However if You manage to spend the gold and mp gained, then it doesn't fall below 0, so by repeating this Your gold amount is relative to the amount of dailies You have. Lets say I got 0 gold and I make 10 new dailies and by completing them all i get 100 gold.If i spend all the 100 gold and untick the dailies and then finish them again i get 100 gold again. Same for mp, You can get unlimited amount of skills by doing that cycle. 

Also if You untick a daily , it doesn't remove 1 daily counter from boss damage. So by repeating the cycle mentioned above You can boost Your Damage high enough to 1 hit any boss.
I played around with it a bit and this was a result.
![damage](https://cloud.githubusercontent.com/assets/15314071/10717619/74527e92-7b66-11e5-9882-029c2d780171.PNG)

**Comment by Alys** [comment]
Thank you for reporting this, but we're not really concerned that you can use ticking and unticking a task to gain more gold, experience, and mana. Anyone who does want to "cheat" like that can use [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to do it more easily, and because it affects only their own account, we don't consider it harmful. In fact, if they honestly find it motivating or fun, we'd encourage them to do it! At least they're looking at their task lists while they're doing it. :) You might also be interested in https://github.com/HabitRPG/habitrpg/issues/4626 which is related.

The boss damage issue has been reported in https://github.com/HabitRPG/habitrpg/issues/5648
