### ISSUE TITLE
I mysteriously Died with 33 health left

### ISSUE THREAD

**Issue by WhitneyFox** [HabitRPG/habitica#6130]
When I went to bed last night I had 33 health left. I had 4 incomplete items (all bright blue so less than a health point each). I'm fighting Octothulu so I was expecting to lose 8 health points last night, but this morning I opened Habitica and it said I died and my wand broke. Can you look into this to verify why I died and if I did anything wrong, missed anything, or if this is related to the recent server/database issues?

Thanks.

**Comment by Alys** [comment]
At a guess it will be either because of [this bug](https://github.com/HabitRPG/habitrpg/issues/4313) causing your Dailies to not be recorded as completed (see the Advice section near the top; if your Dailies have lost their streaks, or have only very small streaks, then that bug would have happened), or because of damage from your party mates's missed Dailies (go to your party chat and click "Fetch Recent Messages" to see damage reports from the quest). 

I think it's unlikely to be anything else. However if neither of those causes seem likely, we can reopen this and investigate further. However we'd need to be able to identify your Habitica account using your User ID (see step 6 of the Help -> Report a Bug instructions).

Regardless of the cause, the Advice section near the top of that bug report will help you recover from the damage if you feel it was unfair.

**Comment by WhitneyFox** [comment]
Thanks Alys.
That bug does seem to be the issue. I only play with myself in the party, so thankfully this didn't affect anyone else.
I've reset my HP to 33 and gold to 3 as I remember those stats, but the XP I just guessed at as I knew I was approaching leveling, but didn't know the exact amount.
Is there anyway to get the wand back without repurchasing it, as I technically didn't die and it therefore shouldn't have broken?
My user ID (which I forgot to post in my sleep deprived state this morning) is 8c487460-6480-46dc-bb7b-4850bd15ecb8.
Thanks.

```
  From: Alys <notifications@github.com>
```

 To: HabitRPG/habitrpg habitrpg@noreply.github.com 
Cc: WhitneyFox arienstarr@yahoo.com 
 Sent: Wednesday, October 28, 2015 8:51 AM
 Subject: Re: [habitrpg] I mysteriously Died with 33 health left (#6130)

At a guess it will be either because of this bug causing your Dailies to not be recorded as completed (see the Advice section near the top; if your Dailies have lost their streaks, or have only very small streaks, then that bug would have happened), or because of damage from your party mates's missed Dailies (go to your party chat and click "Fetch Recent Messages" to see damage reports from the quest). I think it's unlikely to be anything else. However if neither of those causes seem likely, we can reopen this and investigate further. However we'd need to be able to identify your Habitica account using your User ID (see step 6 of the Help -> Report a Bug instructions).Regardless of the cause, the Advice section near the top of that bug report will help you recover from the damage if you feel it was unfair.—

**Comment by Alys** [comment]
You can give yourself extra gold to buy back the wand.

**Comment by WhitneyFox** [comment]
Hi Alys,
It happened again. I think it's because of the day light saving time switch. The last time I had noticed a glitch in my computer where it ended day light savings early and now it happened again today with the official time change. 

Not sure if that will help you assess the bug and update the code before more Habiticans are affected.
Thanks.

**Comment by Alys** [comment]
Thanks @WhitneyFox. It's a known problem that timezone changes can caused more than one cron in a day. We're working on a fix for it.
