### ISSUE TITLE
New algorithm issue (?) past lvl 10

### ISSUE THREAD

**Issue by Bandicooted** [HabitRPG/habitica#615]
So, just reached lvl11 and the new algorithm doesn't seem to match the XP limit of this level.
By getting 2 or 3 tasks done (very recent tasks - not old ones with bonus xp) I got to this point already: http://puu.sh/2dNDQ

**Comment by PhilipHow** [comment]
The base XP of each task has been increased to 15, so this looks about right.

The levelling has been balanced for people to reach level 100 in about a year, but earlier for keen users. We'll be adding in 100+ functionality over the next couple of months (so don't worry!)

**Comment by Bandicooted** [comment]
yeah I didn't mind having 57 points already. what I thought was strange was reaching a new level at only 280 points (should be pretty quick compared to the previous levels). That's what caught my attention :)

**Comment by lefnire** [comment]
Could have been an expert carry over vestige from previously buggy push.
I'd keep an eye on it

**Comment by PhilipHow** [comment]
Oh an XP update was pushed onto the server earlier today, hence the adjustments - the earlier values were a bit high for the progression we want, hence the change. Or it could a be a slightly quirk due to the database changes. I'll close this for now, but keep your eye on it, and comment back if anything else looks weird!
