### ISSUE TITLE
Second chron run

### ISSUE THREAD

**Issue by supermouse35** [HabitRPG/habitica#6161]
A second chron ran for me today. It ran as normal at midnight, and then again around 1:00 PM today. The second chron resulted in loss of 42 health points and reset all of my daily streaks to 0. I was able to fix the problem by resetting, but not sure why it happened in the first place. I'm assuming this is related to the time change, as I see several of us have reported similar experiences in the Tavern.

**Comment by gbear605** [comment]
I had the same as well.

**Comment by ChaoticTeal** [comment]
Ditto. It did a bunch of damage to my party too.

**Comment by Alys** [comment]
I'm very sorry about this! It was because of the daylight savings change that you went through. When the time changes, it can cause cron to run a second time. You and your party members can use Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to restore lost health, and you can edit each Daily to fix its streak. The "Dailies History" section in  Data -> Data Display Tool will help you estimate your streaks. If you have any questions, comment here, or at Help -> Ask a Question, or in the Tavern.
