### ISSUE TITLE
trapped in party

### ISSUE THREAD

**Issue by suorpio** [HabitRPG/habitica#6166]
I think my party leader has quit playing habitrpg, but I'm still stuck in his party! Quitting the party keeps producing an API error and I can't seem to get out.

**Comment by Alys** [comment]
Please either copy and paste the full text of the error message here, or take a screenshot of it and drag the image into a new comment (don't attach the image to an email because GitHub won't include it in this issue).

We'll also need to be able to identify your account and the party. Please go to Help -> Report a Bug from the Habitica website and see step 6.

**Comment by suorpio** [comment]
I'm not able to produce the error message anymore, but still trapped nonetheless. Glancing at the party leader's profile I can see he hasn't logged in for 2 weeks.

UserID: fd82e12f-72b6-44de-b389-1d5371478430

GroupID: 27edf2e9-35ae-4574-81bc-901f1164ddb6

**Comment by Alys** [comment]
You're out of the party now. Reload if it doesn't look like that. If it still doesn't look like you're not in a party, log out of Habitica, clear your cache, cookies, and also clear local storage for habitica.com (you might have to google for how to do that for your browser), and then close all browser windows.

Comment here if you're still having trouble. We'll see your comment and keep helping you even though I'm closing this now.

**Comment by suorpio** [comment]
Everything is fixed! Thanks!
