### ISSUE TITLE
Unable to Post in Tavern 

### ISSUE THREAD

**Issue by Aquamandias** [HabitRPG/habitica#6170]
When trying to post in the tavern using the iPad app, the page changes to what should be a text box but all it says is (null) and there is no way to edit or type.

**Comment by Alys** [comment]
Thank you for telling us! I've moved your report to https://github.com/HabitRPG/habitrpg-ios/issues/274 which is in the repository we use for the iOS app. Could you please visit that issue and click the "subscribe" button on the right-hand column? That means you'll be emailed when anyone updates that issue, so that they can contact you for more information if needed. You won't receive emails for any other issue in that repository.
