### ISSUE TITLE
Phoenix Mount problem - Weapon cuts through the mounts neck

### ISSUE THREAD

**Issue by sagerpg** [HabitRPG/habitica#6174]
First off sorry if I'm doing this wrong.

my warriors weapon goes right between the phoenix mounts head and neck

API user ID is:  8be36885-7014-4f45-8fcb-f87e90a31a12

Again sorry If I did this wrong

**Comment by lemoness** [comment]
Don't worry, you're doing this right! Thank you for reporting it.

It's an issue with the art asset which has a pretty straightforward fix.
It's not a high-priority change, though, so it may take a little while
before it is implemented.

**Comment by lemoness** [comment]
Had a spare moment, so here we go! If this is made the head layer, it should fix this issue. (No change to the back layer is necessary.)
![mount_phoenix_head](https://cloud.githubusercontent.com/assets/3494081/10949376/72f1174c-82e7-11e5-8191-005ddad141af.png)

This can probably be handled by an Aspiring Coder (@alys, correct me if I'm wrong). If there's any issue with the art once it's implemented, feel free to ping me!

**Comment by Alys** [comment]
I've advertised it in the Aspiring Coder's guild.

**Comment by carroux** [comment]
I noticed this too and thought it looked funky. I'll have a go at this tomorrow since it seems like a straightforward fix and no one's claimed this issue yet.

**Comment by danielvancamp** [comment]
Hello there!

I just started checking the codebase and playing around a little bit. I fixed this issue in order to get the know the structure some more (@carroux, sorry :P). I guess I'll make a pull request now? Sorry kinda a noob at the open community developing.

What I did : took @lemoness phoenix base sprite and added it to the spritesmith-main-8.png on the exact place as the previous one, flattened everything and saved. 

Any hints how to get it to you guys would be appreciated, in the meantime i'll look into it myself aswel!  

**update** found it (I think)

Thanks!

**Comment by danielvancamp** [comment]
<img width="140" alt="screen shot 2015-11-24 at 16 45 34" src="https://cloud.githubusercontent.com/assets/8830345/11372159/3d78ce1c-92cc-11e5-96a3-eab9d02f356d.png">
<img width="143" alt="screen shot 2015-11-24 at 16 46 08" src="https://cloud.githubusercontent.com/assets/8830345/11372160/3d7c4af6-92cc-11e5-8a39-9f5c2cc1ae59.png">

Visual change (don't know if i can post it here for spoilers or something like that :S)

**Comment by carroux** [comment]
No worries @danielvancamp I got caught up with midterm exams and let this slip, your fix looks perfect! Congrats on getting your first green GitHub squares and (soon) having your first pull request merged into an open-source project!
