### ISSUE TITLE
Lag when ticking off a TODO

### ISSUE THREAD

**Issue by jamesmgg** [HabitRPG/habitica#6175]

**Comment by Alys** [comment]
Can you give us some more information please?

Is it on the website (if so, which browser) or one of the mobile apps, and if so which one (iOS versus Android, Habitica versus HabitRPG)?

Has it only started happenig or has it been happening for a while?

Does it happen every time you tick off a To-Do or only sometimes?

Does it ever happen with other kinds of tasks or Rewards?

How long is the lag?

Approximately how many tasks of each type do you have, including Rewards? The easiest way to count them is to go to Data -> Data Display Tool and look in the Task Statistics section.

Can you tell us your User ID please? See step 6 in Help -> Report a Bug for how to find it (it's different than your user name).

**Comment by jamesmgg** [comment]
On website, chrome browser, app in general is very laggy (scrolling, typing, clicking, popdown animations), but when completing a TODO it is especially laggy, I haven't tried with other tasks or rewards, extreme lag after clicking done a TODO lasts around maybe 1-1.5 seconds

I noticed something: it seems like the lag occurs while the blue loading bar at the top of the screen is in around 20-50% and has not yet completed. Maybe some synchronous issue?

I have around 35 TODO list items, around 60 dalies and around 40 habits.

**Comment by Alys** [comment]
Does that 1-1.5 seconds lag happen every time you tick off a To-Do or only sometimes?

Can you please try ticking off Dailies and Habits to see if the same thing happens? If you don't want to modify your stats incorrectly, open [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) before starting your tests, and then save it afterwards to reset your values to what they were when you opened it.

Has it only just today started happening? If not, how long has it been happening for?

Can you tell us your User ID please? See step 6 in Help -> Report a Bug for how to find it (it's different than your user name).

**Comment by jamesmgg** [comment]
It happens every time I tick a todo. Scrolling makes it even worse.

Ticking habits don't cause lag. however dailies do produce the same lag like the todos.

It's been happening for a while, though I think it only started happening once I got long dailies and todos.

Here's my userid: 3f2abcfa-d140-4c8f-859e-61ffea50cf4d. Let me know if I can help with anything else.

**Comment by testsubject1987** [comment]
I am using Habitica with Firefox (42.2) on a Windows XP3 system and also on a Windows 8.1 system, the problem is more pronounced with greater frequency on the XP system, when scrolling or clicking around the whole site will lag, hang, glitch, give error messages, sometimes (censored) the browser ranging from 1-4 seconds on the 8.1 system and 5-20 seconds on the XP system.

The problem I have noticed on the XP system for... nine months or more... this past month I've also noticed it on the 8.1 system so I am here... It will happen for all items from clicking links, items, to-dos, habits, dailies, rewards... 149 Habits, 211 ToDos, 4 Rewards

Both my XP and 8.1 system are very comparable in specs and both otherwise run fine. The XP system has less graphics memory. However... 6-9 months ago this problem I really didn't notice and the site ran very smoothly almost all the time and the amount of items had was perhaps a little bit less but not so much less (I mean if it is then my bad, but I dont think its increased that much).

I think its important to note that this XP system is otherwise running fine and most sites open as quickly and smoothly as on the 8.1 system... and its really only habitica that does this for me.

**Comment by jamesmgg** [comment]
Some expensive computations must be occurring on the long lists. That is something we both have in common.

**Comment by jamesmgg** [comment]
@Alys Have you all be able to replicate the issue?

**Comment by Alys** [comment]
@jamesmgg No, it doesn't happen for me. You could try deleting your completed To-Dos (there's a button at the bottom of the "Done" tab), or try on a different browser.

**Comment by paglias** [comment]
Reopen if it's still occurring
