### ISSUE TITLE
I've gotten an "Application 503 Error" and I have no idea why?

### ISSUE THREAD

**Issue by nebularkatanae** [HabitRPG/habitica#6181]
![image](https://cloud.githubusercontent.com/assets/15656730/10946816/58ac38f2-82f2-11e5-8618-7ed9d28b13ab.png)

I'm confused and unsure what happened but when i try to mark down a task it gives me this message. I tried reloading the page but nothing really changed.

**Comment by Alys** [comment]
Hi @nebularkatanae. Thank you for telling us about this! When it happens, it's not because of anything you did. It indicates a temporary problem on Habitica's server, often associated with high levels of usage. We're investigating the cause of this particular occurrence and you should find it's already stopped. If not, it will stop soon. I'm very sorry about the inconvenience!
