### ISSUE TITLE
Leaving Challenge does not remove Filter from Tasks Pages (web & iOS)

### ISSUE THREAD

**Issue by sidawson** [HabitRPG/habitica#6191]
## PROBLEM
- Leaving a challenge (and removing all tasks) still leaves the related LI (and sub tags) on the Tasks page.
- Ie, the filter button for the challenge is still visible.
- These filters are also still visible in the iOS app (unknown re Android)

This implies that leaving a challenge does not actually leave the challenge completely, just deletes the tasks and removes your participation from the Challenges page. Specifically, **this is very likely a backend database issue, NOT a UI issue in either the web OR iOS app.**
## TO REPRODUCE
1. Join a Challenge
2. Leave the Challenge (select "remove all tasks")
3. Click on your web [Tasks page](https://habitica.com/#/tasks)
## OUTCOME
1. You will see the challenge filter button still visible on the web Tasks page
2. You will see the challenge filters still in your mobile app (tested on iOS, version 1.1.1)
3. On the Challenges page, filtering by "Participating" will show you are no longer in the challenge **[this is correct]**
4. The related tasks will be removed from the Tasks page **[this is correct]**
## EXPECTED OUTCOME
1. Challenge filters to disappear from top of Tasks page
2. Challenge filters to disappear from iOS Tasks > Filter pages (habits, dailys, to dos)
## NOTES
- The related tasks are removed successfully (whether they are tasks you added to the challenge, or official challenge tasks)
- Tasks are removed whether you add your own tasks to the challenge or not
- Tasks are removed whether you complete any of the tasks or not
- You are correctly removed from participating on the Challenges page
- Example (I am currently in zero challenges)
  ![challenge_filters_still_visible](https://cloud.githubusercontent.com/assets/4170320/10994762/3b27c7fa-84dd-11e5-8f4e-ce7909781537.png)

**User Id:** 78810b6b-221d-4baf-b6e7-1cbb8f028042

**Comment by Alys** [comment]
Hi @sidawson. It's actually a deliberate feature that the challenge's tag remains after you've left the challenge. Please see https://github.com/HabitRPG/habitrpg/issues/4062 for an explanation of that. If you have questions or comments about it, could you please comment on that issue so that we can keep the conversation in one place?

The official term for the filtering feature on the tasks page is tags. The word filters is more often used to describe the options on the challenge page that let you select which kinds of challenges you see (participating, owned, etc).
