### ISSUE TITLE
Random loss of health

### ISSUE THREAD

**Issue by gbear605** [HabitRPG/habitica#6197]
I just joined https://habitica.com/#/options/groups/challenges/1228c899-3e90-4102-9bfd-55fc8f3c1988 and then immediately lost 1.5 health. It was definitely not because of my cron, and I'm not logged on on any other computers.

**Comment by Alys** [comment]
This wasn't because you joined the guild, it was just reported to you at the same time. It was because of one of these causes:
1. If you are on a boss quest with other people, then one of those people cronned and caused damage to the party due to missed Dailies. If this is the case, you'll see a message about it in party chat (click "Fetch Recent Messages" to ensure you're seeing the latest messages). This is a likely cause.
2. You suffered the health loss in the past on another device that you had been logged in to back then, and Habitica is only reporting the health loss to you now.
3. You took an action on the current computer that caused you to lose health at some time in the past and Habitica is only reporting it to you now.
4. Something in the past had caused you to gain health but the gain happened only in the browser and was not sent to the server for permanent storage. When you joined the guild, your browser synced with the server and the browser-only action was lost, causing the browser to reverse the 1.5 health loss you had gained. (This one is unlikely because it would have to have been a combination of health loss and gain actions to produce an overall health gain of 1.5.)

I'm going to close this now because I'm confident it's one of those options, but you are welcome to post questions here and we'll see them and keep helping you.

**Comment by gbear605** [comment]
Yep, it was someone in the party.
