### ISSUE TITLE
Error: Cannot read property 'challenge' of undefined"

### ISSUE THREAD

**Issue by palerefraction** [HabitRPG/habitica#6199]
I think the challenge "Six Little Boxes" got deleted and now every single one of those six little boxes gives me an error that takes up the right half of my screen >.> Six 'little' boxes indeed, lol.
![capture](https://cloud.githubusercontent.com/assets/15708153/11017093/88b3c4d0-8562-11e5-82e3-fa83463d0199.PNG)

**Comment by Alys** [comment]
Just checking: Did you reload and did it keep happening after that?

If so, we'll need to know your User ID to help you. Please go to Help -> Report a Bug from the Habitica website and see step 6 for how to find your User ID (it's different than your name).

**Comment by palerefraction** [comment]
9b1367a9-31c2-4d96-81a4-57f4cbf77928

I did refresh, and it keeps happening. 
Interesting side note, those "six little boxes" habits don't show up on the android app (nor do I get the error) :l

**Comment by Alys** [comment]
That interesting side note is very relevant! :)  The challenge tasks have been deleted from your account. They're still appearing in your browser because it is caching them, and it's showing you the errors because it can't get full information about them from the server because they no longer exist there.

A quick workaround to regain access to the site will be to use a different browser or (probably) incognito mode in the same browser you're using now.

To fix the problem in normal mode in your preferred browser, you'll need to clear local storage. Go to chrome://settings/cookies#cont (using Chrome), search for habitica.com, click on the item found, and click the cross button on the right hand side. Let me know if that doesn't work.

**Comment by palerefraction** [comment]
Ugh! Thank you so much ((Heart eyes emoji)) That was bugging me allllllll day! Thank you thank you thank you!

**Comment by Alys** [comment]
You're welcome. :)
