### ISSUE TITLE
Food Drop Chance Not Reset/Reseeded After Awarded By Daily

### ISSUE THREAD

**Issue by roma0104** [HabitRPG/habitica#6205]
I was exploring the event sound themes and checked-off a daily to hear the sound.  I checked it, received a cotton candy food drop, unchecked it.  I changed the theme and checked the same daily, received another cotton candy.  It did this four times, repeated on the same daily.

I have not had another drop to test this and see if it recreated with other tasks.

Minor issue I think.  Breaks the award system, though, why someone would intentionally do it I don't know.

99111ff1-9257-40b0-9b53-b7ab14b53eae

**Comment by roma0104** [comment]
I have only seen this on the web application.

**Comment by Alys** [comment]
Thanks for letting us know, but this is expected behaviour. The drop chance is seeded by the amount of gold the player has (this is necessary to give the same random result on both client and server) so if you take actions that repeatedly produce a drop when you have an unchanging amount of gold, you will get the same drop every time. We don't really consider this a bug since it doesn't occur in normal use of tasks - if you untick a task normally, it's because you didn't mean to tick it, so you wouldn't retick it, and even if you then tick another task, you'd get only one instance of the repeated drop.

It will occur if the player uses a repeated tick and untick action for a Wishing Well and might be annoying then, but the behaviour is documented an a workaround is given: http://habitica.wikia.com/wiki/Sample_Custom_Rewards#Wishing_Well
