### ISSUE TITLE
Adding a new checklist item to an existing list sometimes closes edit mode

### ISSUE THREAD

**Issue by scalegraze** [HabitRPG/habitica#6242]
I am encountering this in Firefox.  
I will often edit existing to-dos with a few checklisted items.  The first time I do this when I return to the page, it will often close editing leaving me with a blank checklist item or sometimes with a couple of letters.

**Comment by Alys** [comment]
The underlying problem has been reported in https://github.com/HabitRPG/habitrpg/issues/2965, and I've just updated it to include the specific case of editing checklists. I'm closing this issue since we're tracking the problem in that other one.

This typically happens when unrelated changes are synced into the website at the same time that you are trying to save your changes. The frequency of this problem can be reduced if you click the website's sync button before editing a task.

You're welcome to post here if you have any questions. We'll still see your comments even though this is closed.

**Comment by scalegraze** [comment]
Thanks, I'll try this solution.
I wasn't sure if it was the same problem or not as my situation seemed similar, but different. I thought it best to start with a new ticket.
Out of curiosity, is there a shortcut key for syncing the page (other than completely reloading with f5)?

**Comment by Alys** [comment]
No worries about the new ticket. :)

There isn't an inbuilt shortcut key, but the [Vimium Chrome extension](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) adds keyboard controls to many elements on the site, including sync. There's similar tools for other browsers.

**Comment by scalegraze** [comment]
Any suggestions on where I might find a similar tool for firefox?

**Comment by Alys** [comment]
Yes, you can search for extensions for firefox at https://addons.mozilla.org/en-US/firefox/ 
Keywords like keyboard, shortcut, and accessibility will probably find something.
