### ISSUE TITLE
Add "Merch" Section to Static Page

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6263]
Now that Habitica has a Teespring and a Stickermule, we should make a static page for merch that links to them both. The Merch Page should also probably be accessible from within the site, maybe in the footer? Recommendations are welcome.

**Comment by danielvancamp** [comment]
@lemoness i'm having a go at the static Merch page. Just to get to know the structure a bit as well. So even if it turns out to be nothing, still good exercise. 
I'll post a screen when i'm done or shall I do a PR never the less? 

As recommendation i would indeed find this link a place in the footer. Maybe under a new title, something as goodies, which later on can grow with the option **Get your Habitica Avatar 3D printed!** ;-)

**Comment by danielvancamp** [comment]
This is what I got!
Let me know if it is something you can use as a first step. Of course with some feedback i can modify like you want. 
I tried to build is as dynamically as possible, so just add the number of merchandises you have, add the string in the .json file and everything will get sorted out! 

<img width="1174" alt="screen shot 2015-11-26 at 23 43 26" src="https://cloud.githubusercontent.com/assets/8830345/11431406/a4a1a4ac-9497-11e5-91e6-291bd6096606.png">

(the grey background is set as hover state, gives a nice feeling to it, imo)

**Comment by Alys** [comment]
That sounds pretty good! Feel free to submit a PR whenever you feel ready!

**Comment by librarianmage** [comment]
The PR referenced has been merged, so this issue should probably be closed as well.
