### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by gpenalba** [HabitRPG/habitica#6276]
dd75fadf-ba01-48d9-a3b4-22beb3b97a3e

There's something going wrong when I invite people into my party. I tried to invite 3 friends, none of them are actually able to do anything in my party, they constantly get an application error. One friend forwarded the invite that I sent him, so I clicked on the invite... NOW I'M GETTING THE APPLICATION ERROR. It shows up on the right side of the screen every time I refresh.

I think habitica is cool... but it seems really buggy, everyone I've referred to it so far hasn't been able to use it without this error!!!

![app error](https://cloud.githubusercontent.com/assets/15971873/11326906/a78a3e88-912a-11e5-96ff-74d66c2fe347.PNG)

**Comment by RingonMatrix** [comment]
I am having the same problem except it happens when I do a to-do or a habit and it will never save.

**Comment by IstraLouise** [comment]
I have the same error message but it started when I went to a page for a challenge that was just put up on the Short Term Goal Accountability Group for [Food Diaries](http://habitica.com/#/options/groups/challenges/2a40fbf2-da93-4d12-b1b2-4bd570e2aff1)  I managed to join by maneuvering the join button up at the top of the application error until I could get a hand.. Now the application error is following me everywhere.  Sometimes showing up double and covering half my screen. I can't use the notifications when they show up.  I am using Firefox browser 42.0 and Windows 10.  I've tried resyncing the page, reloading my browser, and going back and deleting the previous hour's cache, which should have included things before the error occured.

**Comment by Alys** [comment]
I've restarted the server so the errors should stop now. However comment here if they persist.

For future reference, when you see application errors, reloading the page using the browser's refresh/reload button is the only fix worth trying; syncing or clearing cache won't help (not that they were bad things to try because they can fix some problems, but they aren't necessary in this case).

**Comment by RingonMatrix** [comment]
It seems to have worked. Thanks a lot Alys

**Comment by gpenalba** [comment]
The errors persist. I browse to the habitica page, and it slowly loads my task page, I see the bar move across the top of my screen. It stops at the very end before completion, hangs there for a bit, and then application error shows up. After the error I cannot select anything. I'm running firefox, latest version, Windows 7. A friend of mine that I invited is running chrome, and he gets the same error. 

I repeat: I did not get the error at all until I clicked the link to be invited to my own group. My friend always got the error, because he was invited by me to the group. There's something that happens after clicking that link!

**Comment by Alys** [comment]
@gpenalba In the database, there's no invitations pending for your user account or your party, so that isn't causing the problem. There might be something corrupted saved in your browser. Please log out of Habitica, clear your cookies, cache, AND local storage (the latter is important), and close all browser windows. Alternatively, try using Habitica in a different browser (at least as a temporary workaround until your primary browser is fixed), or in an incognito window in your primary browser. Let us know how you get on with any of those options that you try.

**Comment by gpenalba** [comment]
Cleared everything and it works! It's funny how reluctant I am to actually clear out everything... but whatever it was, it's gone now. I won't be sending any more 'join my team' emails though... I'll just add people from ID.

I should also note that playing with incongnito mode worked just fine as well.

**Comment by Alys** [comment]
Thanks for letting us know!
