### ISSUE TITLE
Enchanted Armoire Item Disappeared

### ISSUE THREAD

**Issue by britnbutler** [HabitRPG/habitica#6277]
A few days ago I received the Shepherd's Crook from the Enchanted Armoire. It showed up and I equipped it, but then a few hours later it was no longer equipped to my avatar and it was completely gone  from my inventory.

**Comment by Alys** [comment]
Please see this issue: https://github.com/HabitRPG/habitrpg/issues/5376
in particular the section in bold near the top.

**Comment by britnbutler** [comment]
This isn't the same issue. The item did show up, so I know that I had it
and it wasn't just that the Enchanted Armoire told me the wrong thing. Then
later the item disappeared.

On Sun, Nov 22, 2015 at 8:13 PM, Alys notifications@github.com wrote:

> Please see this issue: #5376
> https://github.com/HabitRPG/habitrpg/issues/5376
> in particular the section in bold near the top.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6277#issuecomment-158831397.

## 

_Brittany Butler_

Physical Science Professor
Concordia University Chicago

Math Professor
College of Lake County

**Comment by Alys** [comment]
The item you're first told about can appear in your equipment list and even be equipped, but can disappear on a later sync. The bug is that your browser and the server have different opinions about what the Armoire gave you, and the server's information overrides the browser when a proper sync occurs.

If you feel that the Armoire's behaviour was unfair, go to Settings (the gear-shaped icon) then Site and then Fix Character Values to give yourself back the gold.
