### ISSUE TITLE
Interest in a Habitica GitHub sync website?

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#6285]
Hi!  I attempted to build a [PHP website about (3?) years ago](https://github.com/ruddfawcett/HabitRPG-GitHub) for (then) [HabitRPG and GitHub](https://github.com/habitrpg/HabitRPG-GitHub), where you would gain experience for committing to GitHub repositories.  Unfortunately I had to abandon the project, but I have begun using Habitica again, and was wondering if there was any interest in me rebuilding a small site to support this idea?

The original hook:  _For every x number of commits you push to a repository, you will get y number of up votes on your HabitRPG account!_

This may be something that just applies to me, so I will probably build it anyway, but I would love to get any suggestions/opinions from you guys.  Thanks!

**Comment by Alys** [comment]
Interesting idea! I can see the benefit to a Habitican running a local copy of it. The website that you're considering building - would that be a public one for anyone to use, with their data stored in the website's MySQL database? If so, that would be a problem because their tokens would then not be guaranteed private, however I might have misunderstood what you have in mind!

You might be interested in these tools, which I think might do similar things:
- http://habitica.wikia.com/wiki/GitHabit_-_GitHub_Webhooks
- https://www.openhub.net/p/habitrpg-github

I'm happy to talk more about this with you, and once we have a better idea of whether the tokens would always be protected, we could ask around the other contributors to see how much interest there is.

**Comment by ruddfawcett** [comment]
I completely agree. The keys would have to be stored properly in order to avoid a breech.  The second project you thinker to is the original one I wrote (not very secure or functional), but the first link is almost an exact copy of the original one I made, just less configurable.  I wonder how they are storing the keys.  I'll do some research and get back to you.  Thanks!

**Comment by ruddfawcett** [comment]
@Alys now that I think about it, I see no reason why tokens couldn't be used as parameters in the webhook URL, such as `?apiToken=xxx-xxx-xxx&secret=xxx-xxx-xxx`, as it would only expose the tokens to the user adding the webhook to their own repository.

It looks like this is what @Kerrick is doing on his site.  @Kerrick -- any interest in possible building this up a bit more as a service, with customizable settings, such as number of commits, public vs. private repo, etc. ?  I agree that Node.js is the way to go.

**Comment by Alys** [comment]
No, tokens should not be put in URLs because it is a security risk. URLs are always transmitted across the net in the clear, even to secure sites, which means that your token would be exposed to anyone reading your browsing history, or sniffing your internet traffic, or viewing logs that contain the URL (which could be on a wide variety of servers that your internet traffic passes through).

@Kerrick can you change your service to prevent tokens being in URLs?

**Comment by Kerrick** [comment]
@ruddfawcett That's why it's best for services like these to never store API keys. That's why GitHabit simply [takes a key](https://github.com/Kerrick/githabit/blob/master/index.js#L15) as a URL parameter and [passes it right on](https://github.com/Kerrick/githabit/blob/master/lib/habit-rpg.js#L12) to ~~HabitRPG~~ Habitica. GitHub is the only one storing your API keys. (And if you're worried about it, you can host your own instance of GitHabit.)

@Alys Tokens in URLs are fine as long as they're transmitted via SSL. Network traffic over SSL does _not_ expose the query parameters to any sniffing, that's part of the encrypted traffic.

That said, I do need to update GitHabit not to be pointed at `beta.habitrpg.com` anymore.

**Comment by Alys** [comment]
@Kerrick Sorry, yes, you're right about sniffing, but HTTPS URL parameters are not secure for the other reasons I listed. There's some details at https://blog.httpwatch.com/2009/02/20/how-secure-are-query-strings-over-https/

Is there some other way that your service can securely pass tokens?

**Comment by Alys** [comment]
@ruddfawcett I'm closing this but you're welcome to create the tool you have in mind. If you'd like to, comment here when it's completed, or if you have questions.
