### ISSUE TITLE
Please get rid of "Fix Character Values"

### ISSUE THREAD

**Issue by evil-ai** [HabitRPG/habitica#6300]
This feature makes HabitRPG totally pointless and removes all of the fun. Games aren't entertaining if there's no danger and if you can just win by changing values in a box. There's a reason many people stop playing a game once they discover a cheat or a way to break it.

I can't imagine how one would stay motivated after finding out this exists.

**Comment by Alys** [comment]
Hi @evil-ai. I understand that you find Fix Character Values (FCV) demotivating and I'm sorry about that! However we won't be removing it because it's a very useful tool for many players. It helps us to recover from accidental damage due to bugs or network outages (e.g., if my internet connection was unavailable for a day and I took a large health loss from not being able to do my Dailies, I would be able to use FCV to repair the unfair damage)

It also allows us to implement our own personal features that aren't built in to Habitica. For example, many players use it to make a gold bank for saving up for a particular purpose - they record their amount of gold in a task or reward, then delete that gold using FCV, and then when they are ready to use the gold, they use FCV to restore it to their account. 

Another use is to make a "beserker mode". A Warrior or Mage can use FCV to convert health to mana to allow them to do more damage to a boss - I enjoy doing that!  A similar idea is implementing a "hard mode" - each time a level up happens, FCV can be used to reduce health to make the next level-up harder, thereby providing more motivation to do tasks and avoid negative Habits.

Some players sometimes use it to reduce their level to more closely match that of their party mates.

You might like to go to Help -> Request a Feature to ask that an optional setting be added to turn off FCV for your own account. However note that if we did implement that setting, it would have to be reversible to allow players to change their minds about using it. But even so, you might find that it would help you avoid the temptation to use FCV when you didn't want to.
