### ISSUE TITLE
Party member not able to join quest.

### ISSUE THREAD

**Issue by IstraLouise** [HabitRPG/habitica#6310]
'circle of friends' has a party member that has tried to join the current quest 4 times and is permanently stuck at pending.

**Comment by Alys** [comment]
We can't identify parties by name because the names are not unique - there could be two or more parties called that. Instead we need the group ID, which is a unique identifier. We also need the User ID of the affected party member. Please see step 6 of Help -> Report a Bug for how to find the IDs (the user will need to tell you their ID, or you can find it in their profile).

**Comment by IstraLouise** [comment]
Ok, the Group ID: 9bbdc1a5-870c-4197-9ac0-527692686f92
The character ID that is affected is: dcf5fa65-bf57-4ebe-a60a-29e1ca87a26f

**Comment by Alys** [comment]
I can't see anything wrong with that player's account or with how the quest is set up in the party.

Please ask the player to comment here with a description of exactly what happens when they try to join the quest. They should also give us details of their browser and operating system, including the version of both (e.g., Chrome version 46), and if they are using Chrome, give us information from the console (see Help -> Report a Bug step 8 for instructions). If they aren't using Chrome, I recommend that they try it in Chrome, if they possibly can.

**Comment by IstraLouise** [comment]
I've passed on the information to the other members of the party.  I kind of suspect one other person might be having issues as well, but can't confirm because they haven't gotten back to me.  I've supplied links to GitHub for creating accounts and a link directly to this issue so its up to them now.  I was trying to handle as much of it as I could because they are new players. 

Thanks for checking it out and letting me know!
Theresa (IstraLouise)

**Comment by IstraLouise** [comment]
The other person was having problems, but unbeknownst to me they were trying to join using the app.. waiting on the person whose ID I gave you to get back to me as to whether they were trying to use the app to join (and hence need to be on a different page than this) Have offered them a 5 gem reward if they figure out how to join or comment on this thread (having provided the direct link to the sign up and this thread individually) by midnight my time today, descending by 1 gem if it is tomorrow, day after, etc

**Comment by IstraLouise** [comment]
Thank you, Alys!  The original member who was having the problem was able to fix it by using Chrome. Thank you for your suggestion. I am closing the case now.
