### ISSUE TITLE
"push task to top" arrow in To Dos randomly changes back and forth to "push to bottom"

### ISSUE THREAD

**Issue by librarianjess** [HabitRPG/habitica#6329]
I can't figure out what triggers it, though it seems to happen mostly if the Tasks pane has been open for awhile. ALL arrows suddenly switch to pointing down rather than up. It can be fixed sometimes just by scrolling up on the page. I've had this happen twice today but can't replicate it now to even screenshot it.

---

_edit by admin:_
#### If this is happening to you, click the Ctrl or Cmd button once. That should cause the icon to go back to the "push to top" orientation.

In future improvements to the task screen, we'll be modifying how the tasks and their icons are displayed. That will give each task more space for icons and then we'll be able to have both a push to top and push to bottom icon, which will resolve this issue.

**Comment by Alys** [comment]
That should only happen when you hold down the Ctrl key (or Cmd) on Mac OS. Is it happening when you're doing copy-paste commands while editing a task or tag, or while performing other Ctrl/Cmd actions (e.g., Cmd-tab to change applications in Mac OS)? If so, you can just ignore the changing arrows - they don't have any effect unless you click on one of them.

The arrows should revert back to the Top position a very short time after the Ctrl/Cmd key is unpressed. Is that not happening?

If the arrows are changing to the Bottom position when you are not clicking Ctrl/Cmd, is it possible that your keyboard has developed a problem and Ctrl/Cmd is being triggered automatically? Have you noticed any other odd behaviour on your PC/laptop that might indicate this is happening?

If none of this seems relevant, can you please try using Habitica on a different browser, and tell us if it still happens there? We'll also need to know information about the browsers you're using and your operating system.

**Comment by librarianjess** [comment]
It's definitely been happening without having pressed the Command or Ctrl key. I have noticed it only while scrolling up and down on the page looking at my To Dos -- so not while editing. Nothing else has been acting up so it's not likely that it's a keyboard issue. 

I'm on a Mac, 10.9.5, using Chrome (version 46.0.2490.86 (64-bit)). I just noticed that Chrome will update on relaunch, so I'll go ahead and do that, and fire up Firefox and see if I can replicate the problem. Thanks!

**Comment by librarianjess** [comment]
Okay, it's happened again in Chrome -- attached is a screenshot. This is with no buttons on the keyboard pressed. I had just typed in a new to do when I noticed it, but unfortunately I'm not certain if that's what prompted it. I just typed in a new one to test it (the first screenshot that's attached) and it didn't change anything. I screenshotted the mouseover text, which still thinks it's pointing up.

![screen shot 2015-12-03 at 3 57 33 pm](https://cloud.githubusercontent.com/assets/16143291/11578033/b40cc7a2-99d6-11e5-9141-94b67d9b8cd7.png)

![screen shot 2015-12-03 at 3 55 31 pm](https://cloud.githubusercontent.com/assets/16143291/11577986/742c21d2-99d6-11e5-9d5b-49581e055889.png)
![screen shot 2015-12-03 at 3 55 45 pm](https://cloud.githubusercontent.com/assets/16143291/11577987/742f4f60-99d6-11e5-9e32-268adadfb60c.png)

**Comment by Alys** [comment]
The mouseover text isn't intended to change when the up/down change is triggered because it already describes both options.

What kind of device are you using for scrolling - mouse, trackpad? Does that device give you the option for mimicking a Cmd click in any way, for example with a mutli-finger tap on a trackpad? If so, is it possible that device is misfiring sometimes - maybe a button is stuck or there's dust on the pad? If you have an alternative device for scrolling and controlling the mouse, can you try using that exclusively for a while to see if the problem still occurs? 

I am sorry that I am seeming to be blaming this on your hardware. :( I have a Mac and I'm not yet able to replicate what you're seeing, so we do need to investigate the possibility that it might be your scrolling device that's causing it, but if it still happens with another device, then it's a much clearer sign that it's not related to your hardware.

**Comment by librarianjess** [comment]
Ah, okay -- I hadn't looked carefully at the mouseover text to see if it changed depending on the arrow direction.

I'm using a regular wired Apple mouse -- [this kind.](http://www.apple.com/shop/product/MB112LL/B/apple-mouse?fnode=c7ca2d8eca34d9a96fbff8b83969f7677a9c2abb025b1f7f40bdf28e5f9455fd3bcc2d66a04300a75165c0d06df46dd3bf57b9fc70ed5eafc98d98d1a26cc9e0f901642273fdfa5e3ff79ef4c9e4b4a14f9d3f6a0fb5a73fca558a673ca9ccbe) As far as I can tell, there's no misfire (nothing else is ever affected). This is my work computer so I don't have an alternative to use (without calling IT :) ). 

I'll update if I still have issues when I use my home computer (a much older Mac laptop). It doesn't really bother me but I figured it was a weird enough bug to warrant flagging it.

**Comment by Alys** [comment]
Yes, absolutely worth reporting! It isn't sounding like it's a hardware problem so it's good that we know about it. Thank you for all the details so far!

**Comment by damemi** [comment]
Just commenting to confirm this issue on Linux Chrome 46.0.2490.86 64-bit. Just left the window open for awhile and when I went back all the arrows were pointing down

**Comment by dbarnett** [comment]
@damemi I kept encountering the same thing and I finally figured out what was causing it: happens when I switch away from the Habitica tab with keyboard shortcuts <kbd>Ctrl</kbd>+<kbd>Tab</kbd> or <kbd>Ctrl</kbd>+<kbd>1-9</kbd> and then switch back some other way. I think Habitica needs an event handler to reset <kbd>Ctrl</kbd> key state when it loses focus, and possibly also to check and re-initialize it when it regains focus.

FWIW, I've noticed similar state quirks in other parts of the app, like the hover text over the pet getting stuck open after feeding the last food item to a pet and triggering the "raised pet" dialog.

**Comment by librarianmage** [comment]
Should this be put on hold until the redesign? It doesn't seem to be game-breaking, and it may be fixed by the new UI update.

**Comment by paglias** [comment]
Can be worked on but yeah it'll be overwritten by the redesign

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Push to top/bottom will be returning soon, but they will not be using these icons, so this issue is no longer relevant.
