### ISSUE TITLE
Cannot delete items from lists

### ISSUE THREAD

**Issue by filblue** [HabitRPG/habitica#6330]
Not from Dailies, nor Tasks

**Comment by Alys** [comment]
Can you give us some more details please? What is preventing the items
being deleted? Is there no trash can icon or do you see an error message
when you click on the icon? Does any other noteworthy behaviour happen?
Does it happen with all tasks or just some? If just some, is it only
challenge tasks? (If so, that's expected; you can't delete challenge tasks
unless you leave the challenge.) Are you using the habitica.com website or
the "Habitica" iOS app, or the old "HabitRPG" iOS app, or the Android
"HabitRPG" app?

**Comment by filblue** [comment]
No response when clicking trash button on website. Happens with all tasks, dailies and habits, no challenges involved. Constantly seeing 'No internet' banner in iOS Habitica app. (Connection is definitely OK)

**Comment by Alys** [comment]
Try reloading the website. If that doesn't help, clear local storage (that's different than clearing cache, so you might need to google for instructions for how to do it in your browser). You could also try using a different browser if you have one installed.

**Comment by filblue** [comment]
Reopening the browser helped, thanks for great support!

**Comment by Thomas0921** [comment]
because we check the "Stop creating additional dialog" after we click the trash icon. So it wont ask us about want to delete it or not anymore. Help

**Comment by Alys** [comment]
@Thomas0921 Close and reopen your browser to reset that setting. 

We actually have a guild within Habitica now for faster reporting of problems and faster fixes or advice. You can get to it from Help > Report a Bug from the website's menu and Guilds > Report a Bug from the mobile app. It's best to post there first for any bug report because you'll get faster answers there. If you need to report a bug in GitHub (rare) a moderator will tell you that.

It's also best to not report the same bug in two places at once because it leads to duplication of effort.
