### ISSUE TITLE
Random effects in Habitica

### ISSUE THREAD

**Issue by ojeytonwilliams** [HabitRPG/habitica#6331]
Hey.  I've been looking into #3048 and #5376 and I think they both stem from how random numbers are generated in Habitica.  So, I thought it would make sense create a new issue to discuss this.  If this would be better off as a comment, let me know and I'll do that.

In order for random numbers in Habitica to work properly they need to:
- Appear to be random from the client's perspective.
- Be the same on the client as on the server.

They don't need to be uniformly random, but subsequent calls should typically give different results.  Client-server synchronization is obviously necessary.
### Problems with the current system

Right now, random numbers are generated by predictableRandom which uses a trig function that's very sensitive to changes in its input value.  The input for this function is typically a sum of the user's stats.  This means:
- The user's stats have to change for predictableRandom to give a different result.
- If the user's stats change unpredictably (e.g. a party member heals them) predictableRandom's value changes.
- The client's predictableRandom value depends on the implementation of Math.sin() which varies between Javascript implementations.

Since the user's stats can vary without the client's knowledge it's always possible that predictableRandom will be called with different seeds on the client and server.  Also, with large seeds the different Javascript implementations give different results for predictableRandom, due to how they implement Math.sin().
### Potential solutions

1) Ensure that predictableRandom gives the same results on both the client and the server.
2) Compute predictableRandom on the client or the server (not both) and transmit the result.

As far as I can see, 1) is very difficult to implement in practice.  The only way to ensure that predictableRandom generates a new number each time it's called is to increment the seed with each call.  This means that the client and the server have to call predictableRandom exactly the same number of times (which is not currently the case).

2) is more robust, but has issues of its own.  If the client generates the number, the user can control their drops (which is currently possible, since they can modify their own stats, but not great).  If the server generates the number, the client has to wait every time they trigger something random i.e. a lot.

Oh, and we should probably use a different algorithm to generate the numbers [like David Bau's seedrandom](https://github.com/davidbau/seedrandom).

By the way, I'm not claiming originality for much of this: it's mostly a distillation of what @Alys and @SabreCat had to say, but I thought it was worth bringing everything together and adding a few thoughts of my own.

**Comment by SabreCat** [comment]
My sense is that option 2 with server-side randomness will be the most thorough and sustainable fix. Doing things client-side provides what looks like a snappy response to user action, but has lots of potential to cause downstream confusion and errors. Suppose, for instance, we sent back the Experience and Gold gain for an action in the server response, and the client waited for that before displaying the outcome of the action. Then we wouldn't get "rollbacks" of Gold and eeps due to sync errors, nor extra notifications when it's discovered that your party Rogue used Tools of the Trade and now you've got 30 more Gold than we expected you to have.

To go ahead with that, we would need to be confident in our round-trip time for server requests so the app doesn't start feeling sluggish. But with all the backend and architecture work we're doing now, I'm confident we'll get to the point where this is a feasible approach.

Additional pings: @crookedneighbor @paglias who are overhauling the API right now; @negue and @vIiRuS who could weigh in on the implications for mobile apps.

**Comment by Alys** [comment]
Our code has changed since this was logged and randomness is handled differently now so I'm closing this.
