### ISSUE TITLE
Armour not showing (lvl 10)

### ISSUE THREAD

**Issue by dblais1** [HabitRPG/habitica#6338]
NVM

**Comment by Alys** [comment]
For the record, this was the original text of this issue, before it was replaced with "NVM":

---

Hello,

I recently turned lvl 10 and chose the warrior class. After midnight hit and I went to change my leather armour to the chain mail and chain coif I had, no armour or weapons showed up on my avatar except for my round wooden shield. Not sure if this is because I lvld up, or because I purchased those chain mail upgrades on my ios app, which I later found I shouldn't have been able to and was a bug.

Unequipping and equipping my items do affect my stats, so I think it's just an aesthetic problem.

Please let me know if you can help, and thanks for your work on this useful program!

Cheers,

DB
