### ISSUE TITLE
Color of a new daily created stay in grey

### ISSUE THREAD

**Issue by Nairolf21** [HabitRPG/habitica#6357]
Hi dear developers, 

I've noticed a strange behaviour. I've just created a new daily task today. And, the color of this task is already grey ! If I complete this task, it's still grey. And if I uncheck the task, the color is still grey. I've watched if the task was created with a special parameters for the field "repeat every", but no, it's for everyday. 

I also think I need to add that I have several dailies (14). Is it caused by that ? 

I hope you can understand what is happening.

**Comment by Alys** [comment]
It will probably be because you have a Custom Day Start time that isn't zero and the Start Date on the Daily is interacting incorrectly with that. If you change the Start Date to yesterday (in the Daily's advanced options), then the Daily will be non-grey. Alternatively, wait until tomorrow and it will be non-grey then (you can still tick the task for today and get full rewards from it).

https://github.com/HabitRPG/habitrpg/issues/5525

I'm closing this because I'm pretty confident that that's the only cause it could be, but if that doesn't fix it, tell us and we'll reopen it!

**Comment by Alys** [comment]
Sorry, just to be clearer: There is nothing wrong with you having a Custom Day Start that isn't zero. It's a known bug that a new Daily can be grey on the first day if the CDS is non-zero, and we do need to fix that.

**Comment by Nairolf21** [comment]
okay, yes you right ! Today, in the morning for me. My daily task is yellow, so it's the usual color. Thank you ;)

**Comment by Alys** [comment]
Thanks for letting us know! :)
