### ISSUE TITLE
Allow disabling popping up notification boxes

### ISSUE THREAD

**Issue by jaywink** [HabitRPG/habitica#6364]
When going through dailies and tasks on a mobile phone, every click pops up 3-4 boxes that together cover most of the screen. This makes going through a list of tasks super slow as one has to wait after each click for them to slowly fade away.

Allow in settings to completely disable these OR disable them automatically on small displays. They could also just be shown as a tiny box with only "amount + icon" instead of the long text they have, on small displays.

**Comment by Alys** [comment]
I'm sorry about this @jaywink! Could you please report it through the feedback option on the appropriate app? If you're using iOS, it's Menu > About > Request a Feature. If you're using Android, it's About > Request a Feature. That will ensure that it's sent to the appropriate devs for the app you're using.

**Comment by Alys** [comment]
Oh, unless you're talking about using the website on a mobile phone's browser? If so, please go to Help -> Request a Feature from the habitica.com website.

**Comment by jaywink** [comment]
I don't have Android or iOS, so web yes. It works beautifully, except for the notifications.

Does this look like a feature or a UX bug to you? :)

![screenshot20151212_101448303](https://cloud.githubusercontent.com/assets/1174866/11761038/4b36fb08-a0bb-11e5-82c3-d304599c2171.png)

**Comment by Alys** [comment]
Ah yes, that's the standard notifications for the website. I like your idea of having an option to replace them with a tiny box with only "amount + icon". We wouldn't want that to be the default because it would be confusing for new users, but it would be a great feature for experienced users - I'd probably use it myself even when I was on a PC. This is probably the best Trello card to add it to: https://trello.com/c/684Dv1py/320-in-game-notifications-quiet-notifications-bell-click-to-view-notifications
