### ISSUE TITLE
Android crashes on Party screen when switching between Portrait and Landscape

### ISSUE THREAD

**Issue by BNicoleSchmidt** [HabitRPG/habitica#6366]
Steps to replicate:
1. Open Habitica app.
2. Select Party from left side menu.
3. Tilt phone to change orientation.

4 See Error: Unfortunately, Habitica has stopped.

This happens on a Droid Turbo running Android 5.1, Lollipop.

**Comment by Alys** [comment]
@BNicoleSchmidt Thank you for reporting this! We have an issue for it at https://github.com/HabitRPG/habitrpg-android/issues/193, so I have copied your information to the top post there. It's possible that this issue is specific to certain phones, so your information about your device will be helpful!

**Comment by Alys** [comment]
Note that you won't be able to see the issue I've just linked to at the moment, but it will become visible when we open-source the Android app (the GitHub repository will then become public).
