### ISSUE TITLE
Nothing works, and I keep receiving errors everytime

### ISSUE THREAD

**Issue by deadpyxel** [HabitRPG/habitica#6370]
Every time I try to do anything, leave the inn, complete a task, I have error message.

Here is the console log:
_[log.txt](https://github.com/HabitRPG/habitrpg/files/62728/log.txt)_

**If helps, I'm using Firefox's lastest update in a linux Ubuntu 14.04LTS. I already tried clear cache, logout and log in, an neither work.**

**Comment by NickRIOM** [comment]
This seems to be a similar problem with me, every time I load up Habitica I get the message attatched. It also doesn't seem to allow me to do anything, if I go to try change my avatar it refuses to actually apply the changes I select.
My User ID is: 1b9fca28-f7de-421b-aea2-45e9bfd705b2
And I'm using Chrome on Windows 7
![habitica error](https://cloud.githubusercontent.com/assets/16308579/11816558/dc40a6e6-a348-11e5-8a4c-ab13cc109620.png)

**Comment by rachteo** [comment]
I think I might have the same problem

![screen shot 2015-12-16 at 9 27 13 pm](https://cloud.githubusercontent.com/assets/1234900/11862171/ac022e24-a43c-11e5-9a34-1066ba574b83.png)

I'm on Mac OSX (10.10.5) running Chrome version 47.0.2526.106
User ID: e1efa364-fcd5-46fb-972e-31bd94a01afa

_edit:_ Tested in Firefox 31.0 and was able to log in and everything was fine. Switched back to Chrome and errors all the way. iOS app informs me that I have a Network Error although nothing else on my phone seems to be having any network issues at all

_edit the second:_ Firefox updated to 40.0.3 and now I'm getting errors there too...
![image](https://cloud.githubusercontent.com/assets/1234900/11862528/d473181a-a440-11e5-9cb0-a69755280ed8.png)

_edit the third:_ for whatever reason Firefox updated again to 43.0 and all seems well there....??

**Comment by foxed-in** [comment]
Same. Losing a lot of inventory, mana, exp and gold due to this. 

Win 7/Firefox 42

<source> element has no "src" attribute. Media resource load failed. habitica.com
All candidate resources failed to load. Media load paused. habitica.com
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] platform.twitter.com
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] d24n15hnbwhuhn.cloudfront.net
"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24apply
d/<@https://habitica.com/app-5073b540.js:4:22855
o@https://habitica.com/app-5073b540.js:7:18157
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16613
y@https://habitica.com/app-5073b540.js:20:4989
o.event.special[a].handle@https://habitica.com/app-5073b540.js:2:9671
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
b.purchase@https://habitica.com/app-5073b540.js:33:21024
g@https://habitica.com/app-5073b540.js:7:3744
h/</e@https://habitica.com/app-5073b540.js:8:11787
wd/this.$get</j.prototype.$eval@https://habitica.com/app-5073b540.js:7:16398
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16632
h/<@https://habitica.com/app-5073b540.js:8:11846
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
" app-5073b540.js:6:24898

"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24apply
d/<@https://habitica.com/app-5073b540.js:4:22855
o@https://habitica.com/app-5073b540.js:7:18157
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16613
y@https://habitica.com/app-5073b540.js:20:4989
o.event.special[a].handle@https://habitica.com/app-5073b540.js:2:9671
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
b.purchase@https://habitica.com/app-5073b540.js:33:21024
g@https://habitica.com/app-5073b540.js:7:3744
h/</e@https://habitica.com/app-5073b540.js:8:11787
wd/this.$get</j.prototype.$eval@https://habitica.com/app-5073b540.js:7:16398
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16632
h/<@https://habitica.com/app-5073b540.js:8:11846
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
" app-5073b540.js:6:24898

"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24apply
d/<@https://habitica.com/app-5073b540.js:4:22855
o@https://habitica.com/app-5073b540.js:7:18157
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16613
y@https://habitica.com/app-5073b540.js:20:4989
o.event.special[a].handle@https://habitica.com/app-5073b540.js:2:9671
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
b.purchase@https://habitica.com/app-5073b540.js:33:21024
g@https://habitica.com/app-5073b540.js:7:3744
h/</e@https://habitica.com/app-5073b540.js:8:11787
wd/this.$get</j.prototype.$eval@https://habitica.com/app-5073b540.js:7:16398
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16632
h/<@https://habitica.com/app-5073b540.js:8:11846
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
" app-5073b540.js:6:24898

"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24apply
d/<@https://habitica.com/app-5073b540.js:4:22855
o@https://habitica.com/app-5073b540.js:7:18157
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16613
y@https://habitica.com/app-5073b540.js:20:4989
o.event.special[a].handle@https://habitica.com/app-5073b540.js:2:9671
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
b.purchase@https://habitica.com/app-5073b540.js:33:21024
g@https://habitica.com/app-5073b540.js:7:3744
h/</e@https://habitica.com/app-5073b540.js:8:11787
wd/this.$get</j.prototype.$eval@https://habitica.com/app-5073b540.js:7:16398
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16632
h/<@https://habitica.com/app-5073b540.js:8:11846
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
" app-5073b540.js:6:24898

"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24apply
d/<@https://habitica.com/app-5073b540.js:4:22855
o@https://habitica.com/app-5073b540.js:7:18157
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16613
y@https://habitica.com/app-5073b540.js:20:4989
o.event.special[a].handle@https://habitica.com/app-5073b540.js:2:9671
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
b.purchase@https://habitica.com/app-5073b540.js:33:21024
g@https://habitica.com/app-5073b540.js:7:3744
h/</e@https://habitica.com/app-5073b540.js:8:11787
wd/this.$get</j.prototype.$eval@https://habitica.com/app-5073b540.js:7:16398
wd/this.$get</j.prototype.$apply@https://habitica.com/app-5073b540.js:7:16632
h/<@https://habitica.com/app-5073b540.js:8:11846
o.event.dispatch@https://habitica.com/app-5073b540.js:2:6057
o.event.add/r.handle@https://habitica.com/app-5073b540.js:2:2867
" app-5073b540.js:6:24898

Object { data: "<!DOCTYPE html>     <html>     <hea…", status: 503, headers: tc/<(), config: Object, statusText: "Service Unavailable" } app-5073b540.js:31:4940

**Comment by IstraLouise** [comment]
I'm having the same Application error.. I've tried reloading the page several times.. going to other pages.. I started out in the most recent Firefox.. and moved to IE 11 or Edge as they are calling it.. and I'm still getting the application errors no matter where I go..

My mana stats seem to be buggy too.. instead of a XX/XX it looks like the following
Mana: {{statCalc.mpDisplay(profile)}}

Due to the Application Error I had to go to the Data Export tool and my API Token was missing from the form as well

UserID: f3d96171-562a-4100-a78e-a3792981d837

**Comment by Alys** [comment]
I've restarted the server, which typically clears up these application errors, at least for a while, when they are server-wide, as they probably are now. However there can also be local corruption that causes problems, so can each of you please log out of Habitica, clear cookies and local storage (clearing local storage is important so please google for how to do that in your browser if you're not already aware), and then log back in. Comment here if the problems are still happening after that. We can reopen this if necessary.
