### ISSUE TITLE
Camouflage headgear on market instead of Umbral

### ISSUE THREAD

**Issue by gdpmesquita** [HabitRPG/habitica#6372]
ID: c7c95a14-c4a0-4538-965b-a03451d627b6
Browser: Chrome

Hi, I already bought the Penumbral Headgear, but after my character died this morning the headgear for sale changed from Umbral to Camouflage, is that correct??

**Comment by Alys** [comment]
When you die, you lose one piece of gear, and it goes back into your Rewards column to be repurchased. If' it's a cheaper piece of gear than was available for purchase previously, you have to buy it back first, just like you had to buy it first before you initially saw the better gear. You can learn more if you wish on the wiki at http://habitica.wikia.com/wiki/Death_Mechanics or if you have questions drop in to Help -> Ask a Question on the website, or ask here (but Help -> Ask a Question is usually faster because there's many more experienced players there).
