### ISSUE TITLE
Progress not being applied

### ISSUE THREAD

**Issue by Arie3** [HabitRPG/habitica#6377]
Hi :)  I joined up to group with a couple coworkers in their party.  I've been doing dailies and tasks, but none my my activity shows up in the party log and I don't appear as a contributor in the battle.

Group ID: 69da2aae-bacb-42e5-8a35-9a0dc4103fb1
User ID: b9328f57-db91-452b-b643-7c47d238aff3

Tried playing in Firefox and Chrome, Win7 machine.

Thanks!

**Comment by Alys** [comment]
@Arie3 You aren't a participant in the quest. Either the quest had started before you joined the party, or when you received the quest invitation, you selected the reject option. You can see quest participants in the quest box on the party page - click on the participants tab. It's not possible to join a quest after it has started, for fairness (e..g., so that a person can't join on the final day and receive the rewards without having done any of the damage). The quest owner can choose to abort the quest, losing all quest progress. The quest scroll will go back into their Quests page and they can restart the quest so that you can join.

If you'd like to learn more, there's information on the wiki's Quests page at http://habitica.wikia.com/wiki/Quests or you can ask at the Newbies guild which you can get to from Help -> Ask a Question. You're also welcome to ask here, but Help -> Ask a Question usually gets you an answer faster because there's many more people there.
