### ISSUE TITLE
Alert showing in multiple tabs will grant XP/Gold for each one

### ISSUE THREAD

**Issue by DesertAlopex** [HabitRPG/habitica#6383]
Yesterday I browsed through the public guild list and opened a tab for ones that looked interesting. Today when I started up my browser again each of those tabs was showing the newest alert (12/18/2015 Winter Wonderland Begins). I just happened to notice that each time I dismiss the alert on a tab a notice is popping up showing XP and gold gained. (I'll switch to Tell Me Later for the remaining browser tabs)

I did a search for alerts and none of the ones that came up in the new issues looked like they were the same issue.

User ID: 61bbf61d-6c47-48ca-8669-91c7dc50fd6b
Browser: Chromium Version 47.0.2526.73 Ubuntu 15.10 (64-bit)
OS: Ubuntu 15.10

**Comment by Alys** [comment]
Thanks for letting us know, but those alerts are just showing you what you've earned since the last time you viewed that particular window or tab. The gold and XP aren't given to you more than once. Feel free to comment again if you have questions!

**Comment by Alys** [comment]
Also, in case you're curious, the Tell Me Later button merely closes the alert, whereas the Dismiss button makes a change to your account to say that you don't want to see the alert again. That change is saved into your account, which means that the browser has to sync with the server to do the saving. When the sync happens, the browser is told about any other changes to your account since the last time you synced on that window/tab, which is why you see those notifications when you Dismiss, but not when you Tell Me Later.

**Comment by DesertAlopex** [comment]
Ah! Thanks for the clarification and thanks for your work!
