### ISSUE TITLE
Health potions can be bought even while health is at maximum.

### ISSUE THREAD

**Issue by SpadesNeil** [HabitRPG/habitica#6384]
It's a minor bug but also a minor fix. Seems like an oversight to me. I misclicked the health potion not realizing it was instant use and it just wasted 25 coins which kinda blows.

**Comment by Alys** [comment]
You can get your gold back from any accidental purchase for any reward from Settings -> Site -> Fix Character Values (website only; not on the apps yet).

**Comment by Alys** [comment]
Can you tell us which app you were using? If it's one of the Habitica official mobile apps, we can get the text changed to say "Instant Use" to match what it already says on the website.

**Comment by SpadesNeil** [comment]
I was using the website, not any app.

**Comment by Alys** [comment]
@SpadesNeil No worries. For future reference, if you hover over the potion, it says that it's instant use.

Devs:

If we were to add a check for full health before allowing purchase of the potion, I believe it should be at the API level and NOT also at the UI level. I.e., even if the website is showing that your health is 50, you should still be able to buy the potion. The server would then read your actual health value and reject the purchase (not take your gold) if your health is at maximum. This would avoid any problems with sync errors or local storage errors causing the website to think you had full health when really you did need to buy a potion (admittedly, it wouldn't be often that a player would want to buy a potion if it looked like they had full health, but a player who is aware of sync errors and is using the DDT or an app might want to). 

API changes are on hold while API v3 is under development, and since this isn't an urgent change, I'm labelling it as "wait".

**Comment by khipkin** [comment]
I think the [wait] label can be removed from this now.

**Comment by Alys** [comment]
@khipkin Ah, yes, thanks! :)
