### ISSUE TITLE
Item disappeared on new item purchase

### ISSUE THREAD

**Issue by nicolethenerd** [HabitRPG/habitica#6386]
I started a Habitica account and purchased the Rainbow Warrior Armor. Later, when I purchased the Leather Armor, my Rainbow Warrior Armor disappeared completely - it is no longer available to equip, or as a costume, or to re-purchase in the item store. As far as I can tell, this is not a duplicate of the bugs where items disappear on user death - I didn't die, my item just disappeared as soon as I bought the next one in the class.

**Comment by Alys** [comment]
@nbieber That's a problem that happens sometimes at the end of the period during which limited edition items, such as the Rainbow gear,  are available. It's because of a timezone difference between your PC and Habitica's server. Your PC thinks it's still okay for you to buy the gear, but the server disagrees.  It was unrelated to buying other gear; it's just coincidental that the Rainbow gear disappeared when you bought the Leather Armor.

We can give the gear to you now however we need to identify your account. Please go to Help -> Report a Bug from the Habitica website's menu bar and see step 6. That tells you how to find your User ID.

**Comment by nicolethenerd** [comment]
Thanks! My user id is 8315c6c0-ca5d-4269-8018-1c2da04e0730

**Comment by nicolethenerd** [comment]
...I bought the Rainbow Warrior Helm at the same time, and that did not disappear, though - seems awfully coincidental that the only item I lost was the one I replaced.

**Comment by Alys** [comment]
Yes, it was a coincidence. Since you bought both together and lost only one, it's more likely that it was caused by a local storage sync error - the purchase of the Armor appeared to occur in your browser but was never sent to the server. Regardless of whether it was that or the time-period problem, losing it was not caused by buying another piece of gear. You have the armor back now.

**Comment by nicolethenerd** [comment]
Makes sense, thank you! :-)

**Comment by wildharu** [comment]
The same thing happened to me just now (only with a golden staff with a green gem. Not sure about the exact name) and I found this thread when looking for answers. Can I please ask for help as well? (My Habitica nick is same as here)
