### ISSUE TITLE
Cannot start or end/cancel my partys quest on both PC and Mobile.

### ISSUE THREAD

**Issue by TheRealChief** [HabitRPG/habitica#6388]
My party has been trying to begin the quest "Attack of the Mundane, Part 2: The Snackless Monster", and one of our party members doesnt play any more and didn't accept. All of my other party members have accepted, yet I cannot begin or even cancel the quest.

**Comment by Alys** [comment]
We'll need to be able to identify your account and your party. Please go to Help -> Report a Bug from the Habitica website and see step 6.

**Comment by TheRealChief** [comment]
6f698f1a-a086-4175-8528-33a592115814  - User ID
0799823a-285a-42b5-b78c-451434e1f6f8  - Group ID

**Comment by Alys** [comment]
The quest that's currently showing in that party is owned by another player. Because they are the ones who own the quest scroll, only they can start it. If you post a message in party chat asking them to start it, they will hopefully do so! They will see a "begin" button in the quest box. You can find out who the quest owner is in the participants list of the quest.
