### ISSUE TITLE
Trying to Create an Account and Getting an Error

### ISSUE THREAD

**Issue by shmiracles** [HabitRPG/habitica#639]
when i try to create an account it says my user name and email address are already in use.
"Email already taken"

but when i request my password to be emailed to my email address it says an account does not exist for my email address. "Email not registered"

i'm not sure what to do next.
Thank you!

**Comment by Frai7ty** [comment]
While I do not know a proper fix, I could help you with a workaround for now. If you use gmail you can add a . somewhere in your email on the signup page. For instance use this.ismyemail@gmail.com instead of thisismyemail.   Any messages sent to you will still show in your inbox, but the server will think it's a unique account. Hopefully this helps you in the meantime.

**Comment by lefnire** [comment]
Some people have experienced this. I'm still not sure what causes it, it's often an issue of the server having been reset due to [the memory leak](https://github.com/lefnire/habitrpg/issues/165) - in which case you just have to wait a few minutes and try again. But for some people, it happens to them no matter what. In those cases, I can register them just fine from my browser (and usually do, then send them a reset password, and they're in - can do that if you want) - which is so strange, makes me think it's a browser issue. You're not using IE are ya?

**Comment by lefnire** [comment]
I hopped into the server just now and it was at it's memory peak, so I think that's actually the problem you were experiencing. I restarted, so give that a shot

**Comment by shmiracles** [comment]
problem solved!
i'm registered thank you!!

**Comment by lefnire** [comment]
gonna close, the problem is #165
