### ISSUE TITLE
Mongo Database is missing

### ISSUE THREAD

**Issue by taldin** [HabitRPG/habitica#6398]
Since we're headed into the holidays, I found a roundtuit, and I decided to test the latest version of the Setting up Habitica Locally instructions to my Windows machine using the non-Vagrant instructions.   I'm on the step that says 'Download Mongo and follow the instructions', except what happens is that I get a self-installing thingy and no instructions.   

But more importantly... no database.  So when I try and run mongo, it doesn't connect to anything.

Fortunately(?) I kept my old database, and I can run Mongo from said database --- so I know it's installed properly, but a brand new user (or someone pretending to be one) has no database to run Mongo from.  

How do I get a fresh database?   (And yeah, if you answer this one, I'll update the Wiki. :))

**Comment by Alys** [comment]
The wiki says, "Download the latest production release of MongoDB. Follow the instructions provided at the MongoDB website for installing and starting MongoDB." The download link takes you to https://www.mongodb.org/downloads and on that page just above the download button is an "installation instructions" link. Do those instructions help? 

If they do, you could make that wiki sentence a bit more explicit about where on the mongodb website the instructions are, but include a note to point out that if the website design changes, you might have to look in a different location for the instructions link.

I don't want to provide full details about installation on the wiki because they'll become wrong as soon as / if the ofificial mongodb process changes.

**Comment by Alys** [comment]
The habitica database itself should be created automatically by the habitica installation process, although it would require that mongodb is set up and running first.

**Comment by taldin** [comment]
Yeah, I -think- I just got it working (used extra hammers) but the last time we did this I had a separate database directory for some unfathomable reason.   I know that you want people to use the Vagrant setup, but if you may recall, Vagrant hangs up on me all the time so I'm testing the windows version.

**Comment by Alys** [comment]
We have no objection to people not using Vagrant!

**Comment by taldin** [comment]
Okay. I got it working, and a part of it might have been that I needed to enable my Github shell to be a super user (not default; there's an error I get where it says I have to run as administrator) and nuke my old copies of the Node caches and stuff.    Also, the mongo instructions are wrong -- 'mongo' and 'mongod' just terminate for me -- I have to use 'mongod -dbpath .'

There are also some kinda scary looking errors as it runs, too, but it seems to run okay (I've got a new character and everything...)

**Comment by taldin** [comment]
('scary looking"  'Cannot find module ../build/Release/bson' code: Module_not_found'  )

**Comment by taldin** [comment]
But yeah. I had to do a bower cache clean and reinstall, so I'm going to clear everything out and start over and follow the instructions from scratch just to be sure I'm not introducing new steps we don't need.

**Comment by taldin** [comment]
All right.  Got it running; will be updating the Wiki.
