### ISSUE TITLE
immediate cancellation of new PayPal subscription shows the user a raw error message

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6401]
If you create a subscription with PayPal and then try to cancel it immediately, the notification that you can't do that yet appears as a raw error message in a page by itself, instead of in a dialog screen with an "ok" button to dismiss it.

```
{"err":"\"The plan hasn't activated yet (due to a PayPal bug). It will begin 2015-12-26T10:00:00Z, after which you can cancel to retain your full benefits\""}
```

![screen shot 2015-12-26 at 12 20 44 pm](https://cloud.githubusercontent.com/assets/1495809/12004915/e8c9c8de-abcc-11e5-9b79-17c4ecbc513d.png)

**Comment by pnrich** [comment]
I've looked at this, and it's pretty clear why this happens. This is from `website/src/controllers/payments/paypal.js`:

`var parseErr = function(res, err){
    //var error = err.response ? err.response.message || err.response.details[0].issue : err;
    var error = JSON.stringify(err);
    return res.json(400,{err:error});
}`

This function returns a json stringified error straight to the browser, bypassing everything else. This also shows up for any other errors which occur with PayPal (in my test environment, the error was simply that the client couldn't be authenticated - not a surprise, since I'm running it on a local environment).

If you're looking for a dialog box, first thing to do would be to change this so that it perhaps invoked a modal or an alert.

**Comment by melarish** [comment]
How could this be tested on a local Habitica? Would it be enough if the "Client Authentication failed\" error was working properly, seeing as the errors all seem to come from the same place?

**Comment by crookedneighbor** [comment]
You'd need to sign up for a paypal sandbox account and put the credentials in the config.json

**Comment by melarish** [comment]
Is it these settings?
"client_id":"client_id",
"client_secret":"client_secret"

Do you need both a buyer and seller or just buyer?

**Comment by crookedneighbor** [comment]
Yes and yes.

**Comment by melarish** [comment]
I tried adding the credentials to config but it still gives me the authentication failed error. Paypal doesn't even let me create a seller account and I wouldn't know where to set it in the config.
