### ISSUE TITLE
Find the Cub says I should already have it but I don't

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#6405]
My party completed Trapper Santa.  I purchased the quest Find the Cub from the Seasonal Shop and received a message that I have already earned Find the Cub by completing Trapper Santa and did I really want to spend the gems.  I went back to my inventory page.  No quest.  Checked Trapper Santa and it does not say you earn the Find the Cub quest scroll.  

I do not need anything from this.  I'm good with purchasing the quest.  Just think you might want to know in case is causes confusion.  

My User ID is 2dc2722b-fdc1-4a36-894f-c22418b67a30

**Comment by crookedneighbor** [comment]
I think the wording is that you've unlocked the quest, which is intended to convey that you are allowed to purchase it and start it, not that it was awarded to you. I agree though, that the phrasing is a little confusing. 

@alys, @lemoness thoughts on changing it? This is not the first time this confusion has come up.

**Comment by Memry** [comment]
It actually said - "You already earned this quest by completing Trapper Santa. Buy this quest with 4 of your gems?"

**Comment by Alys** [comment]
It's treating the Santa quests in the same way that it treats the newer Quest Line quests - i.e., it's behaving as if the first Santa quest gives you a scroll for the second one. The wording is mostly appropriate for the newer Quest Lines because you probably don't want to buy the quest scroll, but wrong for the Santa quest.

Possible solutions are:
- adjust the first Santa quest so that it does give you a free copy of the second one (I'm not in favour of this because the Santa quests are a bit different than Quest Lines - they're meant to be gem-purchasable special items)
-  make an exception in the code for the second Santa quest so that it doesn't use the normal Quest Line wording
- allow the second Santa quest to be purchased and used even if the first one hasn't been done.

I think I like the third solution best. It doesn't make sense from a story perspective to do the second quest when you haven't done the first, but that change would allow more players to take advantage of the limited nature of the scrolls. If you're in the middle of a long-lasting quest when the Santa quests are made available, you can buy the first Santa scroll, but you might not have time to finish your current quest and the first Santa quest in time to buy the second Santa scroll. Someone was asking about that in the Tavern the other day.

However I think the second solution is also reasonable if you definitely want to preserve the story progression of the Santa quests.

We could also allow the second Santa quest to be purchased even if the first one hasn't been done, but not allow it to be used until the first one has been done, but that's more complex coding, and I think some players would find it confusing.

common/locales/en/quests.json line 62:

```
"alreadyEarnedQuestReward": "You already earned this quest by completing <%= priorQuest %>. ",
```

website/public/js/controllers/rootCtrl.js line 241:

```
      if (type === 'quests') {
        if (item.previous) {message = window.env.t('alreadyEarnedQuestReward', {priorQuest: Content.quests[item.previous].text()})}
        else if (item.lvl) {message = window.env.t('alreadyEarnedQuestLevel', {level: item.lvl})}
      }
```

**Comment by Alys** [comment]
@Memry Thank you for taking the time to mention this to us!

**Comment by lemoness** [comment]
I also like the third option best!

**Comment by Alys** [comment]
I'm working on this: "allow the second Santa quest to be purchased and used even if the first one hasn't been done".

@lemoness Do you want any change to the quest text for either Santa quest? The current texts are below.

First quest: "Trapper Santa"

quest description: "You hear moaning roars deep in the icefields. You follow the roars and growls - punctuated by another voice's cackling - to a clearing in the woods where you see a fully-grown polar bear. She's caged and shackled, roaring for life. Dancing atop the cage is a malicious little imp wearing castaway Christmas costumes. Vanquish Trapper Santa, and save the beast!"

quest completion: "Trapper Santa squeals in anger, and bounces off into the night. A grateful she-bear, through roars and growls, tries to tell you something. You take her back to the stables, where Matt Boch the whisperer listens to her tale with a gasp of horror. She has a cub! He ran off into the icefields when mama bear was captured. Help her find her baby!"

Second quest: "Find The Cub",

quest description: "Mama bear's cub had run off into the icefields when she was captured by the trapper. At the edge of the woods, she sniffs the air. You hear twig-snaps and snow crunch through the crystaline sound of the forest. Paw prints! You both start racing to follow the trail. Find all the prints and broken twigs, and retrieve her cub!"

quest completion: "You've found the cub! Mama and baby bear couldn't be more grateful. As a token, they've decided to keep you company till the end of days."

**Comment by lemoness** [comment]
Small tweaks:

"You hear agonized roars deep in the icefields. You follow the growls -
punctuated by the sound of cackling - to a clearing in the woods, where you
see a fully-grown polar bear. She's caged and shackled, fighting for her
life. Dancing atop the cage is a malicious little imp wearing a castaway
costume. Vanquish Trapper Santa, and save the beast!"

"Trapper Santa squeals in anger, and bounces off into the night. The
grateful she-bear, through roars and growls, tries to tell you something.
You take her back to the stables, where Matt Boch the Beast Master listens
to her tale with a gasp of horror. She has a cub! He ran off into the
icefields when mama bear was captured."

```

"When Trapper Santa captured the polar bear mount, her cub ran off into the
icefields. You hear twig-snaps and snow crunch through the crystaline sound
of the forest. Paw prints! You start racing to follow the trail. Find all
the prints and broken twigs, and retrieve the cub!"

 "You've found the cub! It will keep you company forever."

On Sat, Jan 2, 2016 at 8:22 PM, Alys <notifications@github.com> wrote:

> I'm working on this: "allow the second Santa quest to be purchased and
> used even if the first one hasn't been done".
>
> @lemoness <https://github.com/lemoness> Do you want any change to the
> quest text for either Santa quest? The current texts are below.
>
> First quest: "Trapper Santa"
>
> quest description: "You hear moaning roars deep in the icefields. You
> follow the roars and growls - punctuated by another voice's cackling - to a
> clearing in the woods where you see a fully-grown polar bear. She's caged
> and shackled, roaring for life. Dancing atop the cage is a malicious little
> imp wearing castaway Christmas costumes. Vanquish Trapper Santa, and save
> the beast!"
>
> quest completion: "Trapper Santa squeals in anger, and bounces off into
> the night. A grateful she-bear, through roars and growls, tries to tell you
> something. You take her back to the stables, where Matt Boch the whisperer
> listens to her tale with a gasp of horror. She has a cub! He ran off into
> the icefields when mama bear was captured. Help her find her baby!"
>
> Second quest: "Find The Cub",
>
> quest description: "Mama bear's cub had run off into the icefields when
> she was captured by the trapper. At the edge of the woods, she sniffs the
> air. You hear twig-snaps and snow crunch through the crystaline sound of
> the forest. Paw prints! You both start racing to follow the trail. Find all
> the prints and broken twigs, and retrieve her cub!"
>
> quest completion: "You've found the cub! Mama and baby bear couldn't be
> more grateful. As a token, they've decided to keep you company till the end
> of days."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HabitRPG/habitrpg/issues/6405#issuecomment-168457976>.
>
```
