### ISSUE TITLE
Have to Refresh Page to See Changes to Party

### ISSUE THREAD

**Issue by joeywoneill** [HabitRPG/habitica#6406]
I have to refresh the page to see changes to the party and their costumes.

**Comment by Alys** [comment]
Hi @mrcheepers. That's actually deliberate in the current design of the site, rather than a bug. If the normal sync process synced all information about your party mates, it would be much slower, and because syncs happen every time you take an action, the slowness would be a significant problem. You can see a discussion about this at https://github.com/HabitRPG/habitrpg/issues/4235 and you might like to follow the advice there about requesting a party sync feature.
