### ISSUE TITLE
Cannot cancel subscription

### ISSUE THREAD

**Issue by edwardet** [HabitRPG/habitica#6407]
I'm attempting to cancel my HabitRPG subscription, but running into a consistent error. When I click through to cancel, regardless of browser, I'm either taken to a page reading "{"err":"Cannot read property 'current_period_end' of null"}" or the page simply refuses to load. This has happened several times, on Chrome/Edge/Explorer, on two different computers. Only one Javascript error is thrown, and it's a GET (url including ID and API) 500 (Internal Server Error).

Any help would be much appreciated!

User ID: 6f977e39-4d7e-468e-9657-f229d396bf18
OS: Windows 10
Browser: Google Chrome/Microsoft Edge/Microsoft Internet Explorer

**Comment by Alys** [comment]
That's a sign that your subscription has already been cancelled in the past by our payment processor company, Stripe, due to multiple failed payments from your debit card. The cancellation was not sent through to our systems so your subscription continued unpaid. I've deleted your subscription information from your Habitica account to complete the cancellation.
