### ISSUE TITLE
Facebook log in issue on Android app

### ISSUE THREAD

**Issue by alexllg** [HabitRPG/habitica#6411]
When using the android app, I can't login with Facebook, it shows an error saying something closer to this: "This URL is invalid. This app must use a valid URL, I mean, an URL which Facebook permits access to your Facebook account."

**Comment by Alys** [comment]
Please ensure that you're using the new "Habitica" app, which has a purple and white gryphon logo, and not the old "HabitRPG" app (brown chest logo), which is no longer supported.

Also make sure that you're using the latest version of the Habitica app, so check the Play store to see if there's any updates. After you've installed that, if needed, clear the apps data and then try logging in again.

If you're still getting this error, please go to https://github.com/HabitRPG/habitrpg-android/issues (the Android repository) and create a new issue there so it can be tracked by the Android devs. Include a screenshot showing the error message.

I'm going to close this since we don't track Android issues here, however if you have any questions about any of this, you're welcome to reply here and I'll keep helping you.
