### ISSUE TITLE
Able to select locked avatar skins / hairstyles / shirts without purchasing with gems.

### ISSUE THREAD

**Issue by GreyMage** [HabitRPG/habitica#6427]
User ID: f96fd5ef-3a77-4913-8d2f-ec8af90b77b2
Browser: Firefox
OS: Windows 7

I'm a programmer so I prod things. I noticed that one is able to "select" locked avatar styles.

I've also tested shirts and skin colors, so I assume the bug is general to avatar customization in general.

**Comment by Alys** [comment]
@GreyMage Thank you very much for reporting this! That's some great detective work. The details will be very helpful to us, however I've removed them from this issue so that they don't act as hints for others.... :)  All of the admin team has your original, full report in emails that github sent us, and I'm also copying your text to another location where we can access it. If you'd like a copy for yourself, tell us and I'll email it to the address that your Habitica account uses.

Are you interested in working on a fix for this yourself? It's fine if you aren't! I just thought I'd ask. :) If you aren't one of us will.

**Comment by GreyMage** [comment]
@Alys Thanks!

I would love to make a pull request with a fix but I haven't actually spent any time reviewing the Habitica codebase, so I fear that might simply delay a patch.

Maybe next time I can make a pull request but for now I'd rather leave it to someone more familiar with the system. :)

**Comment by Alys** [comment]
No worries. :)

If you'd like to start coding for Habitica at any time in the future, have a look at Guidance for Blacksmiths
 on the wiki at http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths and join us in the Aspiring Coders guild. You'd be most welcome there!
