### ISSUE TITLE
Habit Task Value doesn't increase or decrease in iOS app.

### ISSUE THREAD

**Issue by nobugsplz** [HabitRPG/habitica#6436]
EDIT: It does increase to higher levels but doesn't decrease. On the web app it shows a slightly red bar, on the iOS it shows a yellow bar

I've been using Habitica for a few days and this is getting a bit annoying.

I use my phone for most everything instead of my computer (it's just easier) and this isn't helping when I have to go on my computer to log habits and get credit for it.

Basically, when I complete a habit and select it, it gives me EXP and Gold but the Task Value (i.e. color) doesn't decrease.

A lover of Habitica, ~Bugster

**Comment by Alys** [comment]
Sorry about this @nobugsplz! 

On the app, could you please go to Menu > About > Report a Bug and describe this problem there? That's the best way to report app bugs because it sends details about your device (nothing that should be private) to the app developer. Alternatively, you could email mobile@habitica.com, or post to the [habitrpg-ios GitHub repository](https://github.com/HabitRPG/habitrpg-ios). For future reference, if you want to report a bug but forget these details, you can go to Help -> Report a Bug from the Habitica website, and there you'll see notes about how to report iOS bugs.
