### ISSUE TITLE
Unable to interact with Tasks page

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#6440]
Hey, so I think I finally completely overwhelmed the website at long last and now I am unable to interact with the main page whatsoever. I cannot add tasks, remove tasks, mark tasks as complete, purchase rewards or items*, or cast spells. Can somebody look into this for me?

*And while at it, would it be possible for you to take 12 gems from my account and give me the current collection of seasonal items, as well as the Ridiculous Party Hat? I have tried to buy these through the app (both iOS and Android [both flavours]) and neither is able to load the current list of equipment for me to purchase.

User ID: 4182cdea-64db-4db4-9713-dc587d86c662

**Comment by eiron** [comment]
(I think it time I tidy up my to-do list - all these ideas, and not enough time! I am at least able to add new tasks through Android's Habitica app.)

**Comment by Alys** [comment]
@Eiron I've deleted gems and added the equipment. When you can access your account again, check and let me know if it's not right (even if we're past the time when the gear should be available). 

Please go to https://habitica.com/static/clear-browser-data and click the button (read the information around it first; make sure you know your login details). That might help the site behave better for you.

If you wish, I can delete all of your completed To-Dos for you. That might also help a little.

I think the main problem though is that you have more tasks than the site can handle: 5686 from a count of their IDs. That's lots. :) I recommend not adding more until this is resolved.

If the site keeps on being unresponsive, we'll need to work out how to purge your tasks. One option is to create a second account and move some of them into it (which I can do using my database access).

**Comment by eiron** [comment]
I think deleting the completed tasks would be a good start. Since following the above advice (I clicked the button), it has gotten to the point where I cannot even interact with the pages behind the scenes. Checking into the Tavern, for instance, is no guarantee that I will be in the Tavern. I also cannot reset my character values to what they should be in the Settings pages. Ironically, the only thing I seem able to do is to join challenges, so further adding to my problem.

Probably, I do need to follow some of the more drastic above steps. And get some of the things on my to-do lists done, instead of just collecting them forever, like some kind of taskmaster general.

**Comment by Alys** [comment]
I've deleted your completed To-Dos. If it turns out that you needed anything in them, let me know. If it requires sharing private information (e.g., the name of a To-Do that needs to be kept private), send an email to admin@habitica.com, otherwise just comment here.
For my reference, timestamp in my timezone: Thu Jan  7 09:22:16 EST 2016

You are resting in the inn at the moment.

One thing that might help, as a temporary workaround, is having you create a second account, and then I move all your To-Dos to it. This would at least give you better performance for your Habits, Dailies, Rewards, chat, etc, and would probably give you better performance for your To-Dos too. If you want to do this, tell me the User ID of the new account.

We could also do a more tailored workaround where some To-Dos are in one account and some in the other, but that would be harder to do and so probably not a good first step.

Let me know how we should proceed.

**Comment by eiron** [comment]
I think we are going to have to do this. If we can move all the To-Dos to a second account then I can churn through those and transfer any experience and similar over to my main as it is earned. It may be a little clumsy, but it is less clumsy than the site is at the moment under the load of all that optimism. I will also have to dedicate an off-day to Dr Meta - action what I can and lose what I have no intention of doing.

So yeah, new account set up ready for to-dos (I think I spotted a potential exploit of the Attribute Point system, in the process - because I set it up to match my main's level [least, what it ought to be {I am unable to make the changes I need due to the strain I have put on the site}] I was awarded 180 points to spend [191, less the 10 points I had hitherto unlocked while Auto-Assign was set up {see below}]; I am not saying you would want to, but you **could**, in theory, award yourself unlimited Attribute Points in this fashion [though I think it would only work if you were to use the exploit prior to unlocking the class system organically {I had previously thought I was going to need to get the points one at a time as I had it set up to Auto-Assign by Class and it was only loading points into Perception, which is why I turned off auto-assign and was subsequently given all of these points}]).

Anyhoo, new User ID: 0d6d2c5e-4e9d-44a9-9455-e85ae32627db
And a reminder of the old (now my "main"): 4182cdea-64db-4db4-9713-dc587d86c662

**Comment by eiron** [comment]
~~Probably I should put most of that middle paragraph in a fresh issue...~~

No need, by the looks of things. Seems this [has a fix already](https://github.com/HabitRPG/habitrpg/commit/75f71bc2ca40f21a31795b9438c8dafc10316503)?

**Comment by Alys** [comment]
Yes, that fix was merged a few hours ago and will be in production within a week, probably less. Thanks anyway. :)

I'll work on moving your To-Dos now but it might be a while - I've found that importing a lot of data into an account can be slow. I'll comment here when done.

**Comment by Alys** [comment]
The To-Dos have been imported into your new account. Please check that you can see them (no need to check in detail because I've done my own tests that should be sufficient) and then comment here. I'll then delete them from your main account.

All of your To-Do `id`'s have changed so if you were using any of them in API scripts or third-party tools, you will need to update those scripts.

By the way, you don't use the Beeminder integration do you? If you do, your goal will derail but we can help with that. Ignore this if you don't know what it means. Or read http://habitica.wikia.com/wiki/Beeminder if curious. :)

This is going to play havoc with any challenges you are in. You'll still be in the challenges in your main account, and the Habits, Dailies, and Rewards from them will still work, but challenge owners won't be able to see your progress on any To-Dos.

For future reference for admins: I had to import the tasks in batches. I could use a mongo $set command to import 33,333 lines of config at once, but not 66,666 (I didn't try to find the cut-off point any more accurately than that). I was then able to use $push to add 5,555 lines of config at a time (maybe more would work, but not more than 6,666).

**Comment by eiron** [comment]
We will work on the assumption I was never going to win any challenges the way I was playing!

Seems like all are present and correct. Let us purge! I will probably add new To-Dos to my main account as before, but try not to let things get out of hand as before. This is the aim! One day I will have my life back into order once again.

Thanks for doing all of this for me, by the by. It is appreciated.

**Comment by Alys** [comment]
No worries at all. :)  I've removed the To-Dos from your main account. I'd be interested to know what effect it's had on the usability of that account, and what it's like to use the new one.

Let me know if there's anything else I can do, either in the next few days or later. If you get your To-Dos reduced in your new account, I can move them back to your main one (without overwriting any To-Ds that might already be in the main account).
