### ISSUE TITLE
Not in party anymore and quest invitation keeps popping up

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6441]
Yesterday at half past eleven, I was still in my party (named Heroes and Villains, I cannot post the party ID because I'm not in there anymore) and am no longer in it this morning. I don't know why and haven't gotten a response from a party member yet. I received the items from our last quest and now the invitation to the new quest keeps popping up randomly when I reload the page. The quest is "The Rat King" and when I click on "Accept" I get the message "Group not found or you don't have access.". I'm not sure if it's a bug that I'm not in the party anymore (though nothing happened that indicated that I might got kicked and I'm still listed on the parties wiki page), but the quest that keeps popping up seems like one. 

My user ID is 9d8de273-85e3-4ddc-944a-8ca730a262a7 and I'm using Firefox 43.0.3 on Windows 7.

**Comment by Alys** [comment]
@Liobia The party leader has the ability to remove people from the party so that is most likely to be what happened. They are able to give a reason for it, but that's not mandatory. They would have removed you after the quest invitation was sent, which is why you were seeing the invitation. I have deleted it now. Please reload the site if you see it again.
