### ISSUE TITLE
Can't load challenges page.

### ISSUE THREAD

**Issue by nikhiljha** [HabitRPG/habitica#6442]
When I go to Social > Challenges I get an error and no challenges are listed.

Screenshot of Red Box: https://gyazo.com/8112f33869cbca9bfae19ee26caec33b
Screenshot of Relevant Chrome Console: https://gyazo.com/6a66dda8068eeef600404b412cb19298

I have tried reloading the page, on reload I get the error.

My user ID is f32b16d6-dc03-4122-82bb-373fb145c3ef
and I am on Windows 10/Latest 64bit Chrome Build - [https://gyazo.com/56ac9b1aeffd1c8f2bb9fb2442f28394](screenshot of chrome info page)

**Comment by Alys** [comment]
You're in a couple of popular challenges that are exhibiting bugs because they have too many participants for the site to handle, and that's probably what's causing this error. I've spoken to the challenge owner in the past about them but they hadn't asked me to take action. However now I've deleted one of the challenges ("When You Are Mad Count to 10 1 week challenge") since it didn't have any tasks. I've sent the owner another message about the other challenge, and if they don't reply in three days, I'll close it too. I think that should solve your problem, if deleting the first challenge hasn't already done that.

**Comment by Alys** [comment]
The owner has replied about the other challenge, with a requested winner, so I've assigned the winner and deleted the challenge.

I'm pretty sure this should fix the problem you were having viewing the challenge page, so could you please reload the site using your browser's reload or refresh button, and then after that, go to Social -> Challenges.

Comment here if you still get the error!
