### ISSUE TITLE
Join party notification persists after accepting party invitation

### ISSUE THREAD

**Issue by psyclist** [HabitRPG/habitica#6452]
Browser: Chrome
Machine: Macbook Air; OSX 10.10.5 
Console Errors: "Failed to load resources: the server responded with a status of 503 (service unavailable)"
Group ID: b6d5d44c-636c-46fb-8a7e-5d0433f62f4b
User ID: 76cc0561-b634-410a-b415-f2167a65803c

Reloading the page makes the error bar on the right-hand side disappear but the party notification persists. Clicking join party button produces error.

**Comment by Alys** [comment]
Clicking the join party button will produce an error because you're already in that party. 

I've deleted the invitation from your account and from the party, but they often come back over a few days. I'll keep deleting it twice a day until it disappears for good.

Can you please go to https://habitica.com/static/clear-browser-data and click the button you'll find there (read the information above it first). It is possible that that will make the invitation go away for good immediately. Please post here when you've done that.

**Comment by psyclist** [comment]
Thanks for the response. I have cleared the browser data as you instructed.
I appreciate your help.

**Comment by Alys** [comment]
I'm closing this because we're tracking the bug in https://github.com/HabitRPG/habitrpg/issues/5649

@psyclist Your invitation is currently not showing up in your account or your party, but I'll keep checking for another couple of days until I'm sure it's gone for good.
