### ISSUE TITLE
Way too many attribute points on level

### ISSUE THREAD

**Issue by klink42** [HabitRPG/habitica#6459]
Hi,

When I reached lvl 11 I noticed that I had 11 attribute points to assign. I reached level 12 quickly after using burst of flame to go through all my mana. When I reached level 12 I saw that I had 89 attribute points to assign. This seems crazy-- is it a glitch?

My userid is:
a84e1a98-6139-409d-baf5-419f173557f5

**Comment by Alys** [comment]
Sorry about that! It's a temporary bug that's already been fixed but we haven't yet finished cleaning up everyone's data. I've removed the excess points. Because you'd already assigned them to attributes, I couldn't work out what your previous assignments had been, so I've set all your attributes to zero. You can reallocate points as normal now.

I'm leaving this open for other players to comment on if they need the same fix.

**Comment by miss-peristeronic** [comment]
Yes, I have the same problem! Level 40 but it gave me all 100 points ><

**Comment by Alys** [comment]
@miss-peristeronic I can fix that for you. I can either unassign all your points so that you can assign 40 of them to attributes, or you can tell me which attributes you want them assigned to, so that you don't have to click 40 times. :)  Please also can you tell us how long ago did you reach level 40?

**Comment by miss-peristeronic** [comment]
It's been five days maybe? But you can just unassign all the points, that's fine. Thank you!

**Comment by Alys** [comment]
@miss-peristeronic Done!
