### ISSUE TITLE
Clear cookies in Clear Browser Data page

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#6490]

**Comment by Alys** [comment]
In https://github.com/HabitRPG/habitrpg/issues/6344, we created the https://habitica.com/static/clear-browser-data page to allow players to easily clear local storage for habitica.com.

The same button on that page should also delete all cookies for habitica.com.

**Comment by librarianmage** [comment]
I can work on this!

**Comment by librarianmage** [comment]
Should this wait until the client update?

**Comment by paglias** [comment]
@MathWhiz this can go ahead! Though I think that redirecting to /logout (if it's not already done) should be enough to delete cookies

**Comment by crookedneighbor** [comment]
^ that's what it does

**Comment by Alys** [comment]
clear-browser-data does redirect to /logout, but that doesn't delete all cookies - some remain. They're overwritten when you log in again, but that doesn't rule out the possibility of some site problems being caused by corrupted cookies. I'd like clear-browser-data to completely delete all existing cookies, so that when a player has used it, we can be certain that any remaining problems can't be related to cookies.

**Comment by paglias** [comment]
Which cookies are retained? The only ones we care about or control directly
are for login status in and they should be deleted by /logout

Il 23 set 2016 08:06, "Alys" notifications@github.com ha scritto:

**Comment by Alys** [comment]
I didn't record the cookies that remained but I don't think that's
important. The reason for this feature is so we can be absolutely certain
that any unusual problems a user is having are not from cookies. If the
button deletes ALL cookies from habitica.com, that will include any left
over from an earlier version of the site (for returning users), anything
weird a user has done by editing cookies, and any bad cookies that are
created by future bugs. It might not be something that's useful often, but
we have had cases where problems disappeared after users deleted cookies
(even after they'd already tried logging out and that hadn't helped).

It wouldn't be a difficult feature to add; a contributor could do it, and
it would be relatively easy for an admin to review since the code would
have a specific purpose and be fairly small. It wouldn't affect other parts
of the site because it would be limited to the clear-browser-data function.
It's a harmless feature that will make troubleshooting a bit easier and a
bit more reliable.

**Comment by paglias** [comment]
👍  sounds good to me

**Comment by librarianmage** [comment]
I was looking at the cookies generated by the code, and some of them have the `HttpOnly` tag on them, meaning that it is inaccessible to client-side scripts. Does that mean that I would need to add the code to the server-side?

**Comment by paglias** [comment]
@MathWhiz those are cleaned by visiting /logout that already happens in the Clear browser data page
