### ISSUE TITLE
Non-member friends invited, not showing up in party

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6493]
I'm in a party, I'm not the party leader but I invited three people. They accepted and have started to play, but they are not showing up in the party as members, they're still under invited.
![capture](https://cloud.githubusercontent.com/assets/6742405/12225015/1323ef3c-b7bd-11e5-8a19-f1be6898e83c.PNG)

**Comment by Alys** [comment]
If they're not showing up in the list of members, then they most likely have not accepted their invitations. If they are part of a party now, they might have accepted an invitation to a different party.

If you'd like us to investigate further, please go to Help -> Report a Bug from the Habitica website, and see the instructions there. Step 6 tells you how to report the party's Group ID to us. We'll need that to be able to examine the party's members.

**Comment by seancojr** [comment]
Question for you @Alys, somewhat related to the issue here. If a user was invited and now shows up as a member of the party but their nickname is also still shown on the invited list, what does that indicate? I wondered if it could be that they joined the party voluntarily without using the invitation. Even if so, shouldn't the user now appear only under a single header, not both? Things I've tried: Clearing local storage for Habitica and refreshing the page. I've only just considered booting the user and having them re-join but I'd like some feedback first.

**Comment by Alys** [comment]
@seancojr That sounds like the opposite of this problem. Please see the text in bold at the top of this issue: https://github.com/HabitRPG/habitrpg/issues/5649

It's not possible to join a party without having an invitation.
