### ISSUE TITLE
Error created each time click on a new challenge item. 

### ISSUE THREAD

**Issue by nelle013** [HabitRPG/habitica#6507]
I created the Lessen Screen Time challenge in the Life Hackers Guild, and am now receiving an error message each time I click on any item for that challenge, except rewards. It goes away when I reload the page but I want to make sure that it's not interrupting anyone else's data being collected into the excel sheet for the challenge. The error message I've been receiving the most is "Error Internal Server Error." Does that mean it's a problem with my internet?

**Comment by Alys** [comment]
@nelle013 We were having server problems yesterday and the day before which were probably causing this (it wouldn't have been due to your internet connection). We seem to have got rid of the problems, so I think this should be working for you now, but if it isn't, please do comment here again and we'll keep helping you!

Your actions wouldn't have been affecting anyone else's data, so it's safe for you to try again at any time.
