### ISSUE TITLE
Day restarting several times, with HP loss

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#651]
I've had this since yesterday (I think) - I click a daily, it registers, but a while later I click on the habitrpg tab again and I get deduced (again) the hitpoints for not getting all dailies done yesterday, and today's dailies are unchecked.
Yesterday I kept the gold and XP from the checking, though; but right now I lost the XP (and probably the gold, I don't remember) for doing a very red to-do task, about 16 XP or so.

On a side note, I get 6 XP for completing a daily I do every day without fail, but I received less than 20 XP for said very red task that has been languishing for ages on my list. Is that on purpose? I know you fiddled with the algos, but it feels sort of skewed for me.

**Comment by wc8** [comment]
This may not have to do with your issue, but just in case: I reload habitrpg.com before and **right after** making any changes. The after lets me know if the change was saved on the server: if it wasn't.
In other words, are you clicking the task, refreshing and seeing it registered, but it still deducts on refresh in the morning?

Re: side-note: Did you notice what your HP loss was for that task? 
I'm dying many fast deaths with these higher values (mostly because I'm miss recording completions of end of night tasks).

**Comment by wildcate** [comment]
It had reloaded by itself when that happened... and I think I did a refresh after in one case, and the issue occured. Didn't happen today, though!

HP loss was, I think, about 4 or so for 2 not-done dailies, and today I lost 6.something for 3 missed dailies.

**Comment by wildcate** [comment]
Happened again today - I got deducted the penalty HP twice...

**Comment by rixx** [comment]
#777

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
