### ISSUE TITLE
Add Wheelchair to Avatar Customization Page

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6515]
**UDPATE**: _See the comments below. This won't be done as a back accessory._

Very exciting! We now have the art assets for adding a wheelchair to the avatar customization page. (Thank you, Balduranne!)

This should be a free back accessory available to all avatars, in its own section (since we will probably have other colors eventually).

![icon-wheelchair](https://cloud.githubusercontent.com/assets/3494081/12315220/608470ae-ba2d-11e5-9c7b-e88878cb8b13.png)
![wheelchair](https://cloud.githubusercontent.com/assets/3494081/12315219/6073ffbc-ba2d-11e5-8351-d3f189902031.png)

**Comment by Alys** [comment]
I am wondering if it's worth creating a new avatar layer for this, rather than making it an equipment back accessory.

My thinking is, you'll go to the Avatar page to equip it, and then later you'll go to your Equipment page to change your gear, and whenever you try on another back accessory, the wheelchair will disappear. This will make sense to those players who understand that the chair is a back accessory, but I think many players won't realise that (even if it's labelled as a back accessory on the Avatar page). It will seem odd and perhaps buggy if items on the Equipment page can unequip Avatar customisations.

I think the effort required to create a new layer would be less than the effort needed to answer ongoing questions about.

Admittedly we don't get complaints like this about the gem-purchasable ears, but I think they are more obviously the same kind of thing as the other head accessories.

Also it would be very nice if avatars in wheelchairs could still wear wings and tails and capes. :) It would make the wheelchair more like a skin (something you can have all the time no matter how you dress).

**Comment by deilann** [comment]
Totally agree with alys and am so excited!

**Comment by crookedneighbor** [comment]
I agree that we should make it a new layer.

In fact, I wish we had renamed the flower layer and made the animal ears an avatar customization, not equipment. Mucks with the purchase logic to have them be equipment.

**Comment by lemoness** [comment]
New layer sounds great!! I'd suggested Back Accessory because I wasn't sure
it was possible otherwise but I agree that it's preferable this way :)

**Comment by Alys** [comment]
I've advertised it in Aspiring Coders.

**Comment by MikeFoden** [comment]
@Alys I'd love to give this a try.

**Comment by Alys** [comment]
@MikeFoden   Please do! Thank you!

Post here if you have any questions or run into any problems.

**Comment by tylernotfound** [comment]
How would the wheelchair accessory work when paired with mounts? I'm not sure I see a scenario where a user is mounted, while on a wheelchair. So, would wheelchairs work as a mount section? It would give them room to grow with variations, as well.

I'm also willing to work on this, if @MikeFoden isn't already covering it.

**Comment by Alys** [comment]
@tylerxo Wheelchairs should be able to be used at the same time as mounts. It might look odd with some mounts, or it might look really cool in an interesting way. :) Each player can decide that for themselves. 

I.e., wheelchairs should not be implemented as mounts.

**Comment by MikeFoden** [comment]
I am working on this one at the moment @tylerxo but if I can't figure it out I'll handball it to you. :)

**Comment by tylernotfound** [comment]
Sounds good.

**Comment by giuz09** [comment]
OMG! good job!

**Comment by MikeFoden** [comment]
@tylerxo I've had some family stuff come up so I think I'll have to leave this one to you! Sorry for taking so long to reply!

**Comment by querry43** [comment]
This might be an opportunity for subscriber items.  I'm thinking thrones, tree stumps, park benches, etc...

**Comment by nrbunn** [comment]
![wheelchair](https://cloud.githubusercontent.com/assets/8887847/13515624/9a08858c-e178-11e5-9358-493689cd4f51.PNG)

I'm close just haven't figured out how to get the setting to save the DB yet... a hint would help :0)

**Comment by crookedneighbor** [comment]
You should submit a Pull Request so we can see what code you have so far and help you fill in the missing details.

**Comment by nrbunn** [comment]
So i got it to save to the DB.. but now even though you select it again to remove it comes back after you refresh the page. or now that i think about it.. its always on...

**Comment by nrbunn** [comment]
nope made a new user and its not there until you select the wheelchair. I will keep digging

**Comment by nrbunn** [comment]
got it all working in latest PR. Let me know. I'm still a learning so forgive me if i missed something
