### ISSUE TITLE
Am I there?

### ISSUE THREAD

**Issue by Shipmaster001** [HabitRPG/habitica#6532]
I had completed a habit for the second time that day. I clicked on the button to earn my reward, but then an error message pulled up. I refreshed the page ne less than three times, but the message wouldn't go away. When I went to another page and then back to the "tasks" page, it seemed that all was well. But now none of the buttons I click on do anything. I tried refreshing the page, but that just caused the error message to pull up yet again. What should I do?

**Comment by Alys** [comment]
Sorry about this! Please go to https://habitica.com/static/clear-browser-data and click the button there (read the text above it first).

If that doesn't solve the problem, you'll need to tell us exactly what the error message says. Whenever you're reporting an error (on any system, not just Habitica), it's important to include the full text of the error, or a screenshot, because the error message will often give useful clues about what is wrong. We'll also need to know your User ID - to find out how to report it, please go to Help -> Report a Bug from the Habitica website and see step 6 of the instructions.

**Comment by Alys** [comment]
I'm closing this but comment here if you still need help.

**Comment by Shipmaster001** [comment]
I've switched to using the app full-time since it is less temperamental. After successfully completing a task on my to-do list, I received a notification that I had gotten a Desert HatchingPotion. I headed to my inventory to check it out but, to my surprise I found a piece off meat and a Wolf egg, neither of which I remember receiving. Why is this?

**Comment by Alys** [comment]
@Shipmaster001 If you're seeing items in your inventory that you don't recall getting, it's possible that you didn't see the notification. Do you always watch the app after ticking off a task for as long as it takes for all the notifications to appear? Try doing that for several days for every task, and check your inventory regularly.
