### ISSUE TITLE
Sample tasks on front page are visually outdated

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#6535]
The sample tasks on the front page look very outdated compared to the current UI.

Front page:
![image](https://cloud.githubusercontent.com/assets/9433472/12374776/a34d1fc6-bc9e-11e5-8e74-cc798a6ca769.png)

Current UI:
![image](https://cloud.githubusercontent.com/assets/9433472/12374798/5bba8a80-bc9f-11e5-8f9f-548c26884ebb.png)

**Comment by Alys** [comment]
I think this might be deliberate to give a clean, simple view on the front page. Those examples are intended to draw new users in, so they need to be attractive with no confusing details.

I don't think we'd want to include the icons because without the tooltips they don't all make sense immediately, and they'd add visual clutter.

The +/- positioning is definitely different, but it probably looks better to have the same height for each sample task; if the buttons were one above the other, the Habit with both would be taller than the others. 

The current front page design was created relatively recently, and Habitica's task page design hasn't changed noticeably since then, so it's not so much that it's outdated, just different.

I'll leave this issue open for a day or so to see if there's any contrasting comments from the staff, but if there's not, I'll close it.
