### ISSUE TITLE
Quest abandoned.

### ISSUE THREAD

**Issue by TanveerSehgal** [HabitRPG/habitica#6538]
The quest owner (the name of the party is GrowFast) has not logged in to habitica for a while. I removed him from the party due to inactivity but the quest is still stale. http://habitica.wikia.com/wiki/Quests recommended that I post here.

Kindly reset the quest field so the party can continue with other quests.

Thank you.

**Comment by Alys** [comment]
The wiki actually asks you to comment on a specific issue and to include your User ID and the party's Group ID. We'll work with this issue that you've opened now, but if you need this done again in future, please comment on the issue that the wiki links to.

Kindly go to Help -> Report a Bug and see step 6 in the instructions there. It will tell you how to find your User ID and the party's Group ID, which we need to identify the party. The name isn't enough because multiple parties could have the same name and/or the party leader could change the name at any time.

**Comment by Alys** [comment]
I'm closing this since there was no response but if you still need help, tell us your User ID and Party ID.
