### ISSUE TITLE
Opting out of PMs: Should be impossible for challenge/guild leaders? Give suggestion to opt-in when sending a PM?

### ISSUE THREAD

**Issue by Dewines** [HabitRPG/habitica#6540]
I am one of the pirates of Habitica who do gamified clear up of dead and abandoned guilds and thus I sometimes want to send a PM to a guild leader. I have just had a problem with one such interaction when someone had created a duplicate guild that was subsequently made private. 

 _EDIT by Alys: this has been logged in_ https://github.com/HabitRPG/habitica/issues/9247 <strike>Though still logging in to Habitica, the guild leader wasn't responding to posts in the guild chat. I therefore composed a careful PM, but only discovered on trying to send that they had opted out of the PM system. It would have been really helpful if I'd been told that **before** writing the message! The guild was then made private and now the leader has PM'd me and I'd like to respond but as they have opted out of PM's, I can't! I can't even respond in guild chat because I never actually joined the guild and now it's private, I can't, due to not being able to contact the guild leader! It's not a huge deal, but it does make me look rude and as the guild was concerned with mental health issues, they may have taken my lack of response to heart.</strike>

I think there are two issues here: 
1.  _EDIT by Alys: this has been logged in_ https://github.com/HabitRPG/habitica/issues/9247 <strike>If someone has opted out of PM's, then that should be obvious before people waste time composing messages to them.</strike>
2. if you are a guild leader, you shouldn't be able to opt out of the PM system.

**Comment by Alys** [comment]
In addition:

  3. If you are a challenge owner, you shouldn't be able to opt out of the PM system.

  4. If you have opted out and you send a PM, you should be shown a warning that the person will not be able to reply unless you opt back in to the PM system.

Items 2 and 3 might be controversial, and I'm not certain I'm in favour of them, but you can make a case that if you choose to create a guild or challenge, you're choosing to participate in the community and hence should be contactable.

Item 2 should not apply for parties, and probably not for private guilds. 

Things to consider though:
- When a guild leader leaves a guild, they can choose a new leader (or a leader is chosen automatically) - what happens if that person has previously opted out? We'd probably want to make it impossible for an opted out person to be chosen.
- When an admin changes a guild from private to public, they'd have to remember to check the opt out status and either change it with the person's permission, or change the guild leader, or refuse to make the guild public.

**Comment by Dewines** [comment]
Those are all excellent points, @Alys. My argument for points 2 & 3 is exactly what you said, namely that if you've chosen to lead a public guild or to create a public challenge you should be contactable.

**Comment by SabreCat** [comment]
Client would need to query this to warn the user. Pending for redesign.

**Comment by librarianmage** [comment]
Should this no longer be on hold?

**Comment by Alys** [comment]
I've created a new issue for being told that you can't PM a person **before** you type: https://github.com/HabitRPG/habitica/issues/9247

I'm setting this issue to suggestion-discussion so that we can discuss the other points mentioned above, and I'm adjusting the title accordingly.

**Comment by lemoness** [comment]
I think Challenge leaders and Guild leaders should still be allowed to opt-out of the PM system. Not all Guilds and Challenges require asking the leader questions, and some people may find the PM system very invasive. If they'd like to avoid it, I think that's fine. For that reason, I'm closing this ticket, though people can continue to comment on it if they disagree with me.
