### ISSUE TITLE
Accepting Community Guidelines

### ISSUE THREAD

**Issue by starwarsthx1138** [HabitRPG/habitica#6548]
When attempting to accept the Community Guidelines if you have not clicked on the Community Guidelines link to pull up that page you get an Error saving settings please reload the page to try again message.  At this point the use has no information stating what the root cause is (not clicking on the Community Guideline's link first).  Given that most people do not actually read these types of guide lines (yes I know they should so this should go without saying but), it would be beneficial to state with this error or on this page that you must read the Community Guidelines before accepting them.

The problem does fix itself if you read (click on) the Community Guidelines before attempting to accept them.

User Id : 5ed53cb5-ac4c-484f-b49a-aa8afd5b5598
Browser : Chrome  47.0.2526.111 m
OS : Windows 10 (Version 1511 OS Build 10586.63)

**Comment by Alys** [comment]
That's actually just a coincidental server error, rather than an error created by not clicking on the link. I've just tested with a new account and I was able to accept the guidelines without reading them (which isn't ideal but there's not much we can do about it; even if we did enforce opening the guidelines, people could close them without reading).

Any time you see that error, reloading usually fixes it and allows you to do whatever you were trying to. When the errors keep happening, we typically notice and restart the server to make them stop.

Sorry about the trouble! We are improving the site's backend code and database, which will reduce these errors over time.
