### ISSUE TITLE
Challenge Link broken

### ISSUE THREAD

**Issue by thediceofliars** [HabitRPG/habitica#6551]
When a challenge is removed, the pending tasks for said challenge are still automatically generated for each user who joins. When this challenge is sub-sequentially deleted, the pending tasks are only marked with a "Challenge Link Broken" token. 

How should this be resolved? If a challenge creator deletes a challenge, should the participants in said challenge still get rewarded even for simply removing the tasks by checking them off?
![habitica_brokenchallengelink](https://cloud.githubusercontent.com/assets/15920231/12424387/efe3ce74-be9d-11e5-9a45-7f3f7b3f14b8.JPG)

**Comment by Alys** [comment]
The behaviour you've noticed is correct. When a challenge is deleted or closed the tasks are meant to stay in the participants' task lists so that the participants can keep using them if they wish. If you click on the "broken challenge link" icon, you'll be given an option to keep or remove the tasks. If you choose to keep them, then they'll become just like normal tasks as if you'd created them yourself. If you mark them completed, then you're supposed to be rewarded with Experience and Gold. The idea is that even though the challenge has finished, the tasks might still be useful to people.

For more information, see "Deleting a Challenge Task" in the wiki's Challenges page: http://habitica.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task

If I haven't answered your questions well enough, ask again here or go to Help -> Ask a Question from the Habitica website's menu.

**Comment by thediceofliars** [comment]
Thank you very much for the swift reply!
