### ISSUE TITLE
Show subscription end date on subscription page

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#6559]
From an admin email:

> it would be nice to see somewhere on the subscription page when the current subscription will end, especially for people who are on the yearly plan. It's nice to be able to see when you'll be charged $48 again

We have that information in the user object, so it should be feasible to display it.

**Comment by tylernotfound** [comment]
@SabreCat Is there a shortcut/helper in the local environment to generate fake subscriptions for testing this out?

**Comment by Alys** [comment]
We should be cautious with this. The date shown is not always the start date of the CURRENT subscription. If the user buys a monthly subscription and then upgrades it to, for example, a three monthly subscription, I believe (we should check!) that the start date will NOT change and so it will not tell them when their subscription payment is next due.

**Comment by SabreCat** [comment]
@tylerxo: I think the only helper we've got is the migration `freeMonth.js`, which has two scripts (one commented out) you can use to create a subscription for a user. You can tweak that to the parameters you need for a given scenario, then run it against your local mongo.

**Comment by Alys** [comment]
An update:

If your subscription has been cancelled so that it has a defined termination date stored in your user document, then the end date is displayed on the Subscription page (see screenshot below).

For the case where the subscription has not been cancelled, we still have the problem I described above with the start date (`purchased.plan.dateCreated`) not necessarily being the date of the current subscription, and therefore not being usable to calculate the next payment date. There is currently no reliable way to find the "end date" of a subscription that has not been cancelled.

![image](https://cloud.githubusercontent.com/assets/1495809/23235458/4eb9cae0-f9a1-11e6-8944-1f295d4138d6.png)

**Comment by SabreCat** [comment]
Might have server-side pieces that can be done prior to redesign, but it's largely a matter of information display on the client, so I'm placing this on hold for now.

**Comment by librarianmage** [comment]
This has already been added, so should this issue be closed?

**Comment by Alys** [comment]
Ah yes. The termination date is displayed (when it exists). The next renewal date can't be displayed for the reasons listed above, so I'm closing this. A renewal date is still desirable but needs significantly more work than just adjusting the display. We want to make other improvements to subscriptions so I'll mention this requirement to the staff, and if this isn't done at the same time as the other improvements, we'll create a new issue for it.

**Comment by Alys** [comment]
I won't mention mention this to the staff because the renewal date idea is already well described at https://github.com/HabitRPG/habitica/issues/5556
Thanks for your posts on both, MathWhiz.:)

**Comment by librarianmage** [comment]
No problem! Glad to help :)
