### ISSUE TITLE
Many images on front page have no alt attribute

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#6560]
According to the [HTML spec](https://www.w3.org/html/wg/drafts/html/master/semantics.html#alt), every image must have an alt attribute, but most of the images on the front page don't.

I'm happy to write alt-texts for the images, but presumably they will need translating; is `common/locales/en/front.json` the right place for them?

**Comment by Alys** [comment]
`common/locales/en/front.json` is correct. I suggest that each string's key starts with a particular set of characters so that all alt texts can be clearly identified. `altAttr...` maybe (e.g., altAttrLifehacker), unless there's a different system that's already been applied for any alt attribtues.

Keep in mind this recommendation from the W3C: http://dev.w3.org/html5/alt-techniques/#sec5 -- purely decorative images that don't add any information should have a null alt attribute (alt=""), and that should be coded into the HTML, not provided as an empty string in front.json (so that translators don't incorrectly supply a string in their language). I also suggest putting a brief comment describing that in the first location in the HTML code that has a null alt, so that future contributors don't think it's a mistake.

However Habitica might be a bit of a special case for decorative images. Normally I'd say that many of the images on the home page were purely decorative and should have a null alt, but since the monster and pet images are such an integral part of Habitica's motivational features, maybe that's not the case.

It would be nice if we could get some opinions from visually impaired people who use screen readers or who have images turned off.
