### ISSUE TITLE
Confirm name of user being booted from party

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitica#6578]
When booting the party member, there is a confirmation screen, but no username present. It's hard to tell if you're booting the right person or not. 
![screenshot 2016-01-24 17 48 40](https://cloud.githubusercontent.com/assets/5608909/12563644/2490642c-c360-11e5-8ff6-eeef3f4001e2.png)
I imagine booting activity doesn't happen too often, but fixing it so that the username of the player being booted would be helpful.

**Comment by tylernotfound** [comment]
I'll take a look at this one.

**Comment by tylernotfound** [comment]
@Alys how do you feel about this approach?

![image](https://cloud.githubusercontent.com/assets/977577/12568477/03a5fb80-c37b-11e5-9804-c0f32624937f.png)

This solution simply adds a header element under the action message, with the target's username. It skips the trouble of fussing with the translations. I was originally thinking of a solution like:

"Do you really want to remove **username** from the party?"

But the work involved in identifying how that fits for each translation seems like a lot of work.

**Comment by Alys** [comment]
I like that a lot! It will look better for long names than having them inline would, it also helps when booting multiple people because you can learn to ignore the question and focus on the name, and your point about translations is excellent.

However from a strict HTML standards point of view, it shouldn't be a heading. ;)  Just strong and large.

**Comment by tylernotfound** [comment]
Excellent, PR submitted.
