### ISSUE TITLE
Use Bootstrap CDN?

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#658]
Would it be better to use http://bootstrapcdn.com instead of hosting Bootstrap locally?

**Comment by lefnire** [comment]
I started this branch: https://github.com/lefnire/habitrpg/tree/cdn-scripts. Using cdnjs.com instead of bootstrapcdn.com, there are quite a few other js libs we can pull in from cdnjs including jquery, bootstrap-growl, bootstrap-tour, etc. 

Now, Let's talk about this first - I didn't pull in to `develop` because I'm unsure if this actually saves us anything. Check out [this post](https://groups.google.com/forum/?fromgroups=#!searchin/derbyjs/require/derbyjs/hUKYYoxgaA8/vkx_bG11a3wJ) for why I kept everything locally in the first place, but here's the nutshell. Derby uses Browserify to compile require() statements pre launch, which will minify/concat all required scripts into a single file, and send the whole thing down to the client. TMK, it also uses Express caching mechanisms to then keep that big file on cache, and with caching headers so the client won't request it every time until the server is rebooted. It's like having a big sprite sheet + CSS instead of a ton of little images, even if those images are hosted on a CDN. So in my estimation, our method actually saves resources - but I could be wrong, so let's discuss here.

**Comment by ruddfawcett** [comment]
Gotcha.  Quick question for you... Available on IRC?

**Comment by lefnire** [comment]
merged into develop, will see how that goes

**Comment by caycefischer** [comment]
Point of order: as long as bootstrap loads BEFORE our local css, I don't care which method we use. But I do know that I've had problems overpowering bootstrap styles thus far, so maybe this CDN will solve that problem.

**Comment by lefnire** [comment]
I found the reason for that strongarm btw: `derby.use require('derby-ui-boot'), {styles: ['bootstrap', 'responsive']}`. This places the css in the html, and I believe after stylus does its magic. In a recent `develop` push I emptied the `styles` array and simply @imported all boostrap (& responsive) css inside our `styles/app/index.styl`, so we can specify which order.

**Comment by lefnire** [comment]
We moved to CDN for now, but we can move back. Here are pros & cons:
- CDN Pros: I think that each server restart (which happens quite often, because of our memory leak) causes a cache invalidation, meaning clients have to re-download the giant min/concat single file nearly every time they visit. CDN FTW.
- CDN Cons: (1) multiple and many files to download, (2) if your computer goes offline it borks everything (in a very strange fashion... I'm still looking into it).
