### ISSUE TITLE
Party members have disappeared on my account but are still visible for everyone else

### ISSUE THREAD

**Issue by annamw** [HabitRPG/habitica#6584]
I was added to the party of a friend while they were on a quest. After the quest was done, instead of being able to participate in the next quest, I couldn't see any of my quest members anymore. When I click on "Social -> Party" I show up as the group leader and the party is empty. My friend says she can still see me (she is the group leader). 
In the Newbies Guild I was told to empty the cache of my browser. I have done that and checked an alternative browser, too. The issue is the same on Safari and Chrome, and I've also checked if the problem appears on the IOS app, but it's the same everywhere.

Group ID: 84ea5aef-405e-468c-9db5-0be0f15a34ee
User ID: b35f53d6-739f-478f-810e-1be317d8104d

**Comment by Alys** [comment]
Your b35f53d6-739f-478f-810e-1be317d8104d account (profile name _kleine_anna) is in a party with no one else - probably a party that you created (perhaps inadvertently), rather than your friend's party.

If your friend still sees you in her party, then either she is seeing old information, or you have two Habitica accounts. There is also a small chance that you have one account that is in two parties, which is a bug that can happen but very rarely.

Please ask your friend to click on your avatar in the header of the website. That will show her your profile (it's important that she gets to your profile by clicking on your avatar in the header, NOT by any other method). On the left-hand side of the profile, she'll see a User ID (near the top). If that User ID is not exactly the same as b35f53d6-739f-478f-810e-1be317d8104d, then you have two accounts. If you need help finding your second account, paste that User ID here.

If your friend does see b35f53d6-739f-478f-810e-1be317d8104d on your profile, then she's probably seeing old data. Ask her to go to https://habitica.com/static/clear-browser-data and click the button there (she should read the text above it first). If she's still seeing you in her party, please post her User ID here so that I can look into it further (I won't need to look at her account in detail; I'll just need to extract party information from it). She can find her User ID from Settings -> API (https://habitica.com/#/options/settings/api ).

If any of this is unclear or she has trouble with any of it, just post her User ID here and I'll do all the investigation. :)

**Comment by annamw** [comment]
Dear Alys, thank you for your help! I contacted my friend but sadly she told me she stopped using habitica in the last few weeks, so I just left the party that I was in by myself - maybe I'll be able to convince my friend to come back to habitica and see if we still have the same problem, or I'll find a new party alltogether. Sorry for using up your time!

**Comment by Alys** [comment]
That's okay! Thanks for letting us know. Good luck with finding a party!
