### ISSUE TITLE
Subscribing via Stripe after having subscribed via PayPal gift subscription workaround

### ISSUE THREAD

**Issue by oktayacikalin** [HabitRPG/habitica#6592]
I've subscribed via the PayPal gift subscription workaround, which covers me until the 30th of December. Now I've seen, I could also use Stripe.

What will actually happen, if I subscribe annually via Stripe now? :)

**Comment by Alys** [comment]
When you create a second subscription, it starts at the moment that the old subscription ends. If anything goes wrong with that process, you can log a bug report and we'll fix the problem.

I'm closing this now since it sounds like nothing is wrong yet, but if I'm mistaken, we can reopen this. You can also comment here if you have follow up questions. We'll see them even when this is closed.

In general though, when you have questions, the best place for them is at Help > Ask a Question from the Habitica website's menu. That takes you to a guild where a lot of experienced users can answer almost any question. You'll often get an answer there faster than anywhere else. GitHub is really just for bug reports.
