### ISSUE TITLE
Concern with case-sensitive usernames, given mobile environment

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#6597]
From an admin email:

> A lot of mobile phones capitalise first words. So when I created my account the initial letter was capitialised automatically. Since usernames for logging on Desktop are case sensitive, it took a while to figure out why I couldnt login.

UPDATE: For the method of fixing this, see this comment below from @paglias : https://github.com/HabitRPG/habitrpg/issues/6597#issuecomment-176721894

**Comment by Alys** [comment]
_EDIT: This comment is wrong (see later comments for why)._

@paglias There's no longer any need for logging in to treat the username case-sensitively, is there?

Unless you say otherwise in the next day, I'll advertise this in Aspiring Coders. It should be a fairly simple matter of using `auth.local.lowerCaseUsername` in `api.loginLocal` in `website/src/controllers/api-v2/auth.js`  (and at the same time, changing the error messages to translatable strings).

**Comment by paglias** [comment]
@Alys I don't remember exactly if there are still some duplicates with different casing and so some duplicates is lowerCaseUsername. If there aren't then for me it's :+1:

**Comment by Alys** [comment]
I'll do a final check of usernames and if it's all good, I'll post to Aspiring Coders.

**Comment by Alys** [comment]
Ugh, no, we do still have duplicates. Quite a lot. The lowercase checking is only for creating new accounts; it can't be used for logging in because then a bunch of people would lose access to their accounts.

We were going to fix this in the long term by removing usernames and using just email addresses for logging in. I still think that's the best approach, although we might be able to do some short term changes. 

Perhaps force all new accounts to have a lower-case-only username and tell the user what their username is after their account is created? Could be seen as a bit rude though. It also won't help with accounts created before we make that change.

Perhaps if the user's login fails, then before we report the failure to the user, we do another search that does use the lower-case username, and if only one account is returned, then we do a password comparison. @paglias Do you think that would be doable?

**Comment by paglias** [comment]
@Alys your last suggestion looks reasonable. I hoped we would be able to migrate to lower case only logins at some point: when we have duplicates like uSer1, User2 and usEr3 we could take the most recently used and transform it to the lowercase version and then changing the others two sending them an email with the new username. But I realize that if someone used an invalid email then it would be problematic (even though they chose not to use the right email address)

**Comment by Alys** [comment]
There's no guarantee that duplicates are all owned by the same person and there's very many of them. Trying to remove them would be nightmarish.

**Comment by paglias** [comment]
I didn't meant that they are owned by the same person just that we could keep the most recently used one and force a change on the others using a script

**Comment by Alys** [comment]
Ah, sorry, but even so, I don't think it's manageable. Too many users to contact, too much chance of not being able to reach some and having them locked out of their accounts. Also, some would be annoyed about their names being changed. There's no real reason to keep usernames when people can log in using their email addresses. Getting rid of usernames has the bonus of removing the confusion between usernames and profile / display names.

**Comment by paglias** [comment]
@Alys I get you point especially if we want to drop usernames. 

I'd go this route:

> Perhaps if the user's login fails, then before we report the failure to the user, we do another search that does use the lower-case username, and if only one account is returned, then we do a password comparison.

**Comment by luanmuniz** [comment]
I like this too

> Perhaps if the user's login fails, then before we report the failure to the user, we do another search that does use the lower-case username, and if only one account is returned, then we do a password comparison.

But i think we should do a list and ask the users to change their username of duplicate exist. I know this is not cool but i also thinks this kind o password check should be temporary

**Comment by ineffyble** [comment]
I just ran into this. Tried to make it easier by changing my username to lowercase, but was told already taken (because the check is insensitive).

**Comment by TheHollidayInn** [comment]
This is being fixed by: https://github.com/HabitRPG/habitica/pull/10620 and some migrations we will be posting/running after discussing internally.
