### ISSUE TITLE
Dailies charting like habits, showing progress as negative numbers, making task turn red

### ISSUE THREAD

**Issue by solariaus** [HabitRPG/habitica#6605]
All of my dailies started showing progress like a habit (with a graph charting history), and two of the dailies started counting each check-off alternatively as a negative value, which means my trend streak is negative and turning the daily red as time passes. 

Additionally, the difficulty of all my dailies was reset to Medium overnight, though I've since manually reset all the dailies. 

My user id is: 5029e821-5cfe-4a43-870d-abc8929a47a4

I am using Chrome on a Mac.

**Comment by Alys** [comment]
Could you please show us a screenshot of that? Note that to add a screenshot to a GitHub issue, come to this page (https://github.com/HabitRPG/habitrpg/issues/6605 ) and drag the image into a new comment (attaching it to an email won't work).

If you don't want to have your tasks displayed here, then please email the screenshot to admin@habitica.com and include this URL: https://github.com/HabitRPG/habitrpg/issues/6605

**Comment by Alys** [comment]
Sanitised screenshots that were emailed to us:

![8a649af5f47a3edd745c05b9073ed988cee7ff1e](https://cloud.githubusercontent.com/assets/1495809/12658301/ee57596e-c653-11e5-8185-52d237b2965b.png)
![8a1d9c4c22757166acb4f34509a99b03c46239ca](https://cloud.githubusercontent.com/assets/1495809/12658302/ee59d586-c653-11e5-9f24-bd809e05399c.png)

**Comment by Alys** [comment]
@solariaus Dailies are meant to have those progress graphs, because they have values that change over time. Dailies are also meant to have negative values if they haven't been actioned often enough for them to turn orange.

Is the problem that you think the Dailies shouldn't be orange? Have you been marking them as completed EVERY day? If so, you're being affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313 . In brief, sometimes when you take an action on the site, your browser records it but doesn't send the action to the server for permanent storage. Thus when cron runs, it punishes you for not doing some of your Dailies because it was never told that you did them. Does that sound like what might have been happening? Are you taking a health loss each morning that's larger than you thought it should be or are you noticing streaks on your Dailies dropping to zero when they shouldn't have? If so, then it's that bug. There's an "Advice" section near the top of that issue to help you recover from unfair damage and to notice the bug when it happens.

Let us know if that doesn't seem relevant!

Having the difficulty set to Medium automatically is something we haven't seen before. Had you recently changed the difficulties, before they were reset to Medium? Two of your Dailies are still at Medium now (the third and fourth ones on your list probably; I haven't looked at their texts) - are they supposed to be Medium or have they reset themselves again?

**Comment by Alys** [comment]
@solariaus I'm closing this but if you'd like us to look into it further, please see my questions in my previous comment.
