### ISSUE TITLE
issues posting Challenge in Party - player is in two parties at once

### ISSUE THREAD

**Issue by Olia1** [HabitRPG/habitica#6620]
dear tech support,

I'm trying to create a Challenge in my party (92cc50af-96bb-4b95-9871-71db926f224b) but in the list of options as to where to create the challenge, only my old solo party HardMode shows up. this has occured once before, and Alys had fixed it somehow.. but I don't remember how she did it. :(

**Comment by Alys** [comment]
Can you tell us your User ID please? If you're not sure how to find it, go to Help > Report a Bug and see step 6.

**Comment by Olia1** [comment]
3f6a57c5-9321-408b-8ed6-db58dde1ad5a

**Comment by Alys** [comment]
Thanks! This is very exciting because it's evidence of a rare bug. :) Your account was in two parties at once which is not supposed to be possible. 

I've removed you from your Hard Mode party, which should fix your challenge problem and any other party-related weirdness you might have been experiencing. Comment here if anything is still odd, but I don't think it will be.

For our reference, these were the two parties (sanitised for privacy):

```
{
    "_id": "0852b891-9c46-4950-a229-0e6f73c2a9ec",
    "leader": "3f6a57c5-9321-408b-8ed6-db58dde1ad5a",
    "type": "party",
    "name": "Hard mode",
    "quest": {
        "key": null,
        "leader": null
    },
    "memberCount": 1,
    "privacy": "private",
    "invites": [],
    "members": [
        "3f6a57c5-9321-408b-8ed6-db58dde1ad5a"
    ]
}

{
    "_id": "92cc50af-96bb-4b95-9871-71db926f224b",
    "leader": "{leader ID here}",
    "type": "party",
    "name": "{party name here}",
    "quest": null,
    "memberCount": 53,
    "privacy": "private",
    "members": [
        "3f6a57c5-9321-408b-8ed6-db58dde1ad5a",
        {and 52 other members; Olia was towards the bottom}
    ]
}

```

**Comment by Olia1** [comment]
it works now, thanks Alys! :)
