### ISSUE TITLE
javascript gets stuck when I apply 'burst of flames' to any task/daily etc.

### ISSUE THREAD

**Issue by sundaresvani** [HabitRPG/habitica#6624]
This happens everytime, it hangs I wait, my dailies briefly flash to showing ALL steps & all grey & due dailies & then I get the first window:

<img width="1520" alt="screen shot 2016-01-30 at 12 17 30" src="https://cloud.githubusercontent.com/assets/15809495/12698203/7ce2817a-c74b-11e5-8108-64e9ef063119.png">

& then I usually choose 'stop script' & i can go about my business. This time I chose 'debug' but I don't understand what I saw. Maybe you will.
<img width="520" alt="screen shot 2016-01-30 at 12 16 44" src="https://cloud.githubusercontent.com/assets/15809495/12698202/7ce050e4-c74b-11e5-9628-78614e8f4fd8.png">

**Comment by Alys** [comment]
Could you please log out of Habitica, clear your browser's cookies, then go to https://habitica.com/static/clear-browser-data and click the button there. Does that make the problem go away?

If the problem persists:

Please go to Help > Report a Bug from the Habitica website and tell us the information listed in steps 6 and 7.

Also tell us how many tasks you have. The easiest way to count them is to go to Data -> Data Display Tool and use the "Task Statistics" section. 

Do you have another browser installed on your PC or are you able to install one? Does the same problem happen on it?

If you know how to use the JavaScript Console in Chrome, and if the problem happens in Chrome, please tell us what messages, if any, appear in the console. You can skip this step at least for now if you're not sure how to do it (we can talk you through it later if it seems to be essential).

**Comment by AnnaFromPoland** [comment]
good day!

i have just encountered the same issue - warning about an unresponsive "https://habitica.com/app-3f324ec7.js:5" script.

it cannot possibly be cookies because i have formatted my entire computer yesterday! today was the _first_ time i've even opened up firefox, and the -only- site i use firefox for now is habitica.

it _can_ have to do with a super long list of to-do tasks that i've been reordering. but still, given that firefox is the only single program running right now (no itunes in the background even!) and that i had only one tab open (habitica tasks) it is a bit odd! it went super slow, freezing for a few seconds when i were rearranging the tasks, and finally has given me this error.

i've a looooot of tasks cause i signed up for 3 reading challenges (those yearly ones. i wish they had a 12x1 month form :( it's super unwieldy to juggle a whole year's worth of books tasks :C ) but i was hoping that with only 1 program open and working and only 1 tab habitica will work at normal speed :C tough luck.

is there a way to see this java script console thingy in firefox?

**Comment by sundaresvani** [comment]
I do have a long list of tasks. 34 habits, 30 dailies, 88 todos. Like the other user, I participate in annual challenges that are single tasks for each week rather than checklists. 

I went through the process of 'clear browser data' to no effect prior to posting. 

I cannot replicate the issue on Chrome. I use Firefox 43.0.5 on Macos 10.10.5

Userid:2e9755be-bbd1-4ad3-80fb-3c906f14e5bd

I attached images of js errors to my original post. I am unable to extract txt from the js console on Firefox.

**Comment by AnnaFromPoland** [comment]
new code: unresponsive https://habitica.com/app-027344d3.js:4 when i tried to drag a new daily up.

**Comment by AnnaFromPoland** [comment]
new unresponsive one - https://habitica.com/app-027344d3.js:31 - i'm seriously getting more and more of these, now the computer starts panting with or without merfy's customization on, and it's not only the tasks page that's the problematic one, just now started panting when i tried to send a message to mara, every page reload takes eons. 
i'm on firefox 44 on mac 10.11.1.

**Comment by Alys** [comment]
@sundaresvani The fact that you can't replicate it in Chrome probably means that it's a problem with your Firefox browser, possibly that it contains corrupted data. You said that you already used the clear-browser-data page, but you didn't mention cookies, so can you please perform all of these steps now, including any that you may have already done in the past: 
1. log out of Habitica
2. clear your browser's cookies,
3. go to https://habitica.com/static/clear-browser-data and click the button there. 

If it still happens, tell us and we'll walk you through using the console in Firefox to get more information.

@bakatenko you said that it cannot possibly be cookies, however it could be because Habitica sets its own cookies. Please do the above three steps, and tell us if it still happens.

**Comment by AnnaFromPoland** [comment]
..but.. HOW?
if i have a -clean install- of an operating system, everything is new, this is the -first time- using firefox on a newly set up machine, HOW can there be any habitica cookies on it??? on a freshly installed computer? where i've formatted the whole disk clean prior to installing the os and all the programs?

i'll do this "log out, clear cookies" act _again_, but honestly, i've already done this twice yesterday, and _each time_ i open up the "tasks" page i have the java script problem - the number at the end changes sometimes, but the popup shows without fail.

i suspect this can have to do with the 4th column - rewards - cause after using the orb of rebirth all my gear shows up there, and that's a lot of items. the spells weren't even showing for 2 days after i earned my mana bar back. and why i suspect this is, when the tasks page loads, all the tasks load, then there's the popup, 4th column is empty (everything else loaded already) and it says that the script is unresponsive in this moment.

bah, nevermind, i've done what you said to do and i'll see how it works over a few days :)

**Comment by Alys** [comment]
@bakatenko When you use Habitica, Habitica creates cookies, immediately - that's how they have gotten there. 

You hadn't said that you'd already gone through all three of those steps, and so that's why I asked you to do them just now.

Your information about the Rewards column and having used the Orb of Rebirth is useful. You could be correct that that's what's causing the problem. Please go to Settings -> Site (Settings is the gear-shaped icon) and click on the "Fix Character Values" button. Use that tool to give yourself a very large amount of gold and then buy back all your equipment. Tell us after that if the problem has gone away.

Alternatively, if you wish, I can adjust your account to convert all the equipment to being bought (and I can then adjust it back again later if you wish), but I need to be able to identify your account. Please go to Help -> Report a Bug and see step 6 for how to find your User ID.

Skills aren't meant to show up as soon as you earn your mana bar back. Your mana bar appears at level 10 and your first skill appears at level 11.

**Comment by AnnaFromPoland** [comment]
i didn’t know that the spells appear at level 11 :) thank you. still, at level 13 they were buried way under, and the last time i checked (now) i saw only 3 of 4 spells - that’s what made me think that perhaps there isn’t enough space projected there. 

so far i’ve refreshed several times, and the bug seems gone - the only change from the „clear browser cookies & whole history” routine i’ve made is that "go to https://habitica.com/static/clear-browser-data https://habitica.com/static/clear-browser-data and click the button there” - so if the bug won’t return, this will be the one action that helped (either in combination with clearing the browser cookies & history or alone, but definitely only cleaning the browser cookies & history did not do a thing here).

it will take me just one more wave of checking off my tasks to buy the equipment back cause i’ve a lot to do and thus a lot to check off, so i’ll stick to buying them off using normally available means, but thank you :)

i hope it won’t return, cause this would mean that we already know what works to repel this bug :)

**Comment by Alys** [comment]
@bakatenko That's good news! Thanks for letting us know. It is possible that it will return but the same fix should fix it again. Do please comment here if it doesn't! Or if it does fix it but you have to do it so often that it's a nuisance.

**Comment by AnnaFromPoland** [comment]
i have bad news, alys. 8 hours after the cleanup the bug showed up again, in the very same manner (load the /tasks page, receive the error). wasn't an 1-off thing, so after 3hrs, i cleaned the cache and used the magic cleaning button again. in the morning, for unrelated reasons, i did the cleaning once more past 11, and now it's 1pm and the bug is here _yet again_.

it definitely does not go away for good using that magic button, so whatever causes it, is in the files that are being left on the computer by habitica. they should be cleaned 3x a day approximately to prevent the bug from popping up - i can do that, cause honestly i only have firefox installed on my pc to use habitica (everything else is done @ safari), but that's the nerdy me, normal people use one browser >.> and clearing the cache and history and using the magic button 3x a day to prevent this bug from happening might be a nuisance to such people.

**Comment by Alys** [comment]
@bakatenko Using the "clear browser data" button or logging out of Habitica (they both do the same thing) will remove all local storage that Habitica has saved in your browser. I'm sorry it's being such a nuisance! All I can suggest is that when you get errors that aren't fixed by a simple reload, you log out (or use the button if you aren't able to reach the logout menu option). Clearing the cache isn't likely to make any difference so I wouldn't bother doing that. Clearing cookies might help but I wouldn't advise doing it regularly (because it's extra trouble for you) unless you find that just logging out doesn't make any significant difference.

**Comment by Alys** [comment]
@sundaresvani  and @bakatenko 
I'm closing this but if you're still having troupe, see my most recent post to each of you (a different one for each - search upwards for your name), and let us know how that goes. We'll see your reply and can reopen this if necessary.
