### ISSUE TITLE
Clicking sync doesn't update party members displayed

### ISSUE THREAD

**Issue by dbarnett** [HabitRPG/habitica#6630]
I added a party member yesterday, but when I checked a browser tab I had open she still wasn't shown in the party. I clicked sync and still didn't see her without reloading the page.

**Comment by crookedneighbor** [comment]
This was an intentional decision to reduce load on the server. Looking up the data for every party member in a party (especially for large parties) on every sync would be an expensive operation.

That said, I could see an argument for drawing a distinction between the normal syncing that happens when using the site (making new tasks, purchasing items, checking off tasks, etc) and clicking the sync button itself. 

@Alys @lemoness do you have thoughts on that?

**Comment by Alys** [comment]
We have this issue open here with some discussion in it: https://github.com/HabitRPG/habitrpg/issues/3018
