### ISSUE TITLE
Duplicated Tag bug

### ISSUE THREAD

**Issue by Cartogenic** [HabitRPG/habitica#6635]
Duplicate tags appear if user enters a challenge containing one or more tags already created by the user.
For example, I have the "Health" Tag, but when joining a challenge containing "Health" tag, I got 2 of the same now.

[Screenshot](https://i.imgur.com/9I4xXqp.png)

**Comment by Alys** [comment]
This is deliberate, and the tags are actually two different tags that happen to have the same text. If you use each tag in turn, you'll see that each one shows you a different set of tasks. The tag that you created will show you the tasks that you created. The tag that came from the challenge will show you the challenge's tasks.

Every challenge comes with its own tag so that you can easily find the tasks belonging to that challenge. If you don't want that tag, you can delete or rename it (click the edit button next to the tags on the website). Alternatively, you could delete your own Health tag and use the challenge tag for tagging your own tasks as well as the challenge tasks.

Note that if you leave the challenge, or the challenge ends, the challenge's tag will remain in your tag list until you chose to delete it. This means that it is safe to use the challenge tag for tagging your own tasks.

If you have any questions, ask here, or go to Help > Ask a Question from the website's menu. We'll respond to you in either place. Help > Ask a Question might get you an answer faster because there's more people there to offer assistance.

**Comment by Cartogenic** [comment]
Thank you :+1:
