### ISSUE TITLE
No buff after Tools of the trade

### ISSUE THREAD

**Issue by KGBoo** [HabitRPG/habitica#6638]
Hi! It happened a few times in my party that the perception buff from Tools of the trade don't work for some people. For example, 4 people out of 5 get the buff, the other one gets nothing. 

Here is my User ID: d6208b0e-a7e0-4ddd-ae0b-06a8f5853702

**Comment by Alys** [comment]
There's two possibilities for why this happened.

One is that if the buff was cast while one person is sleeping, it will wear off as soon as they start using Habitica the next day and their cron runs. This is unfortunate but it's how the buffs work currently. It is likely that the behaviour of buffs will be changed in future so that this doesn't happen.

The other possibility is that if the buffs are cast when the site is under heavier load than usual, then the site might not be able to give the buff to all party members. Unfortunately there isn't anything we can do to help with that in the short term, but we are making some large back-end changes to the site that should improve performance in several areas, probably including this one.

We do know that there aren't any bugs in the Tools of the Trade code that would prevent some players from receiving the buff.

You're welcome to reply if you have any questions.
