### ISSUE TITLE
Basi-List quest scroll gone

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6645]
Hi there, I'm Courtney and my user ID is 9654d89f-1d14-49b1-a6df-5aef8638a222.
I invited a friend to Habitica and received the Basi-list quest scroll. I have initiated this quest for my party several times. We completed it today again, but when I went to re-start the quest, the scroll was gone from my available quests! I cleared cache in my browser and refreshed the page, however it is still gone and I am unable to start it. Did we somehow max it out, or did it expire when I hit level 10? Any ideas? Thanks :)

**Comment by Alys** [comment]
A quest scroll can be used once only. It disappears from your Quests page as soon as the quest starts (i.e., after all players accept or reject the quest invitation). 

You get a new copy of the Basi-List scroll each time a person accepts your invitation to your party.

If you have any questions, you're welcome to ask here, or go to Help > Ask a Question from the website's menu. We'll respond to you in either place. Help > Ask a Question might get you an answer faster because there's more people there to offer assistance. :)
