### ISSUE TITLE
+1 to comment caused large error notice to block one third the screen.

### ISSUE THREAD

**Issue by madkingchris01** [HabitRPG/habitica#6650]
using Chrome 
On occasion, when I'm +1ing a comment, one third of the screen is blocked by an error notice. This wouldn't be a problem, if it didn't block half of all the comments I'm trying to read. I can +1 them later, if need be. Also, reloading the page (which takes to long anyway) doesn't do away with the message. I have to close my browser completely. Reloading the page takes long enough, restarting it is just crazy. To top it off, when I do get rid of the offending message, everything is as I left it. No miss labels, no missed +1's... nothing. What is the error bringing my usage to a halt? Considering that I need to totally close the program, I assume that a button to close the message is not an option.
![image](https://cloud.githubusercontent.com/assets/16292855/12784825/6f826d1a-ca57-11e5-9562-1bcc8cd66a62.png)

**Comment by Alys** [comment]
Hi @madkingchris01. That "application error" usually occurs when the server is under heavy load, and generally is not caused by any action you take. It usually disappears by itself.

If it keeps on happening, there might be something temporarily wrong in your browser, so go to https://habitica.com/static/clear-browser-data and click the button there (read the text above it first). If the error keeps happening, comment again here and we'll keep helping you.
