### ISSUE TITLE
Unsure what causes this error...?

### ISSUE THREAD

**Issue by Bootporeon** [HabitRPG/habitica#6653]
I have no idea what is causing this error:

http://i.imgur.com/4jkExoU.png?1

If it helps to know, I'm using a Windows 8.1 laptop, using Chrome for the browser. My user ID is: 5817d4c4-98f3-40ee-9019-41fc12b271c5

**Comment by Alys** [comment]
Hi @Bootporeon. That "application error" usually occurs when the server is under heavy load, and generally is not caused by any action you take. It usually disappears by itself.

If it keeps on happening, there might be something temporarily wrong in your browser, so go to https://habitica.com/static/clear-browser-data and click the button there (read the text above it first). If the error keeps happening, comment again here and we'll keep helping you.
