### ISSUE TITLE
Emojis in challenge titles don't show properly in challenge winner's profile

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#6657]
Emojis in challenge titles don't show properly in the challenge winner's profile. For example, if a challenge is named "This :smile: is a test!", it shows as "This : smile : is a test!" (without the spaces between colons and emoji name) in the challenge winner's profile.

Yes, it's just a tiny low-priority thing. I wouldn't even have reported it, but was told it's an unreported bug that should probably be fixed instead of something that's just supposed to stay that way.

**Comment by Alys** [comment]
Markdown in challenge titles should also be displayed properly in the challenge winner's profile.

**Comment by khipkin** [comment]
@Alys I am interested in working on this.

**Comment by Alys** [comment]
@khipkin Thank you! Please go ahead!

**Comment by khipkin** [comment]
I've encountered a problem that I'm having trouble with.

[Here](https://github.com/HabitRPG/habitrpg/blob/2d862593ae4152e2b3a61c66f71dc203ea2341de/website/views/shared/profiles/achievements.jade#L149) is the line where markdown needs to be applied.

And here's the dilemma.

Applying the `markdown` filter to that binding (like so: `td {{::chal | markdown}}`) yields the correct html, but that html is displayed as a string on the page.  The winner of the challenge titled "This : smile : is a test!", without the spaces, has this on their profile page:
![image](https://cloud.githubusercontent.com/assets/5641207/13582996/32d193a6-e47d-11e5-840f-c8424773290e.png)

However, if I use [`ng-bind-html`](https://docs.angularjs.org/api/ng/directive/ngBindHtml) to treat the result as html instead of just a string (like so: `td(ng-bind-html='::chal | markdown')`), angular passes the html through `$sanitize`, which [removes the inline style attribute](https://github.com/angular/angular.js/issues/10406) from the emoji's span.
![image](https://cloud.githubusercontent.com/assets/5641207/13583130/c59709dc-e47d-11e5-84c7-80c6405be00c.png)
The result is an empty `<span>` where the emoji should be:
![image](https://cloud.githubusercontent.com/assets/5641207/13583114/aed87550-e47d-11e5-8cf2-759409b5cb59.png)

Angular provides a way to bypass sanitization for values we know are safe, using [`$sce.trustAsHtml`](https://docs.angularjs.org/api/ng/service/$sce#trustAsHtml), but I'm not sure if this is wise.  The challenge title is user-entered text, so it may be dangerous to trust it.

Can someone point me in the right direction?

**Comment by Alys** [comment]
@khipkin I'm sorry about the delay. Do you still need help with that? I'm not able to give you advice because I'm hopeless with Angular, but if no one else answers here, maybe ask in the Aspiring Coders guild.

**Comment by crookedneighbor** [comment]
Should be as simple as using the markdown directive:

``` jade
td: markdown(text='::chal')
```

**Comment by khipkin** [comment]
@crookedneighbor Wow that worked.
![image](https://cloud.githubusercontent.com/assets/5641207/13832536/75d719c2-ebb3-11e5-89ef-7c94393a9854.png)
Magic!

However, I also noticed this issue:
![challenge_won_modal_failed_emoji](https://cloud.githubusercontent.com/assets/5641207/13832547/94ac57d6-ebb3-11e5-941b-8fba6b2c1996.PNG)

**Comment by crookedneighbor** [comment]
Does the same solution not work in the modal?

**Comment by khipkin** [comment]
Yeah it worked.  It just was never mentioned in the issue, but I encountered it while testing.

Anyway, here's the fixed modal:
![image](https://cloud.githubusercontent.com/assets/5641207/13832903/d68fbc8a-ebb6-11e5-9956-c3b0fb2fe392.png)

**Comment by crookedneighbor** [comment]
Fixed with #6657
