### ISSUE TITLE
Missing some pets in CSS

### ISSUE THREAD

**Issue by switz** [HabitRPG/habitica#666]
We're missing some pets in the css/sprite, for example Cactus-White – I'll keep updating this with pets as I see them missing.

**Comment by switz** [comment]
Flying Pig Veteran

**Comment by Shaners** [comment]
Where is the pet CSS anyway? Not in img/sprites/ ?

**Comment by lefnire** [comment]
it is, actually - we merged @Pandoro's changes into https://github.com/switz/habitrpg/tree/inventory, but haven't gotten it back to `develop` yet because it was incompatible with some things. You might want to do a PR against that branch maybe? @switz, what do you think? How to best merge these two efforts?

**Comment by lefnire** [comment]
Also, @Shaners don't worry about the missing veterans - we realized late that Wolf is the only pet with Veteran

**Comment by Shaners** [comment]
May even be a good idea to take away the veteran wolf pet as an option since it doesn't really fit with the others. I could revise it into a wolf mount with some tweaking. Also the cactus pet image files were named differently because I was being silly... that may have lead to some confusion with Pandoro making the CSS...

**Comment by switz** [comment]
Woah, missed this thread, sorry. I don't think we should merge into develop yet. We need some beautification + fine tuning first. I've been keeping the branch up to date so the merge should be painless.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
