### ISSUE TITLE
Available crystals disappear from Special in the Market 

### ISSUE THREAD

**Issue by ray4ik** [HabitRPG/habitica#6661]
I was a subscriber and every month I had an opportunity to buy 25 crystals from Special in in the Market. In the end of January I had 8 available crystals in Special in in the Market. Today is February, 4 and I don't see any crystals. I think it's a big bug, I need my crystals which were bought for a real money.

**Comment by Alys** [comment]
We're happy to help you but we need to be able to identify your account. Please go to Help > Report a Bug and see step 6 for how to find your User ID.

**Comment by ray4ik** [comment]
User ID is 3e700caa-f40d-4e8c-80ce-47f6bb46e61f 

browser is chrome (Version 39.0.2171.99 (64-bit))  or Safari (Version 9.0.3 (11601.4.4)) 
OS - OS X el Capitan (10.11.3) 
I use mobile version  as well 

Also I have a feeling that 1 or 2 crystals were disappeared in 2015.

**Comment by Alys** [comment]
Your subscription is marked as terminated on 2016-02-01, which is why gems are no longer available for purchase. I'm guessing the subscription cancellation was an error? If so, I can look into that, but I need to find your subscription record in PayPal and there's nothing there under the email address you use for Habitica. Can you please email admin@habitica.com to tell us which email address you use when you log in to PayPal? Please include the URL of this issue which is github.com/HabitRPG/habitrpg/issues/6661

**Comment by Alys** [comment]
@ray4ik I've closed this but if you still need help, please see my previous comment.
