### ISSUE TITLE
Quest owner abandoned our party

### ISSUE THREAD

**Issue by NicoleNobody** [HabitRPG/habitica#6676]
Hi, our party has a problem with a quest. It’s owner stopped logging in and there are some members resting in the inn, so they didn’t accept/reject it. Now we are stuck with a quest whe can’t start. Could someone please help? Thank you very much. 

My user ID is 96bad0fe-e963-43dd-b6f7-bcb73ddc4ebd
Id of the party is 84f03be9-33d6-4a95-a12e-8623ad2721bd

**Comment by Cartogenic** [comment]
If I were you, I'd leave the party :/

I was in a similar situation, very inactive members, very boring, and decided to create my own. In a day, 20 people PM'd me asking to join in. If you want to join, you have to agree with our rules, specially regarding inactivity: https://i.gyazo.com/1a19506f095bf0d7c85e94edf306ef36.png

Hit me with a PM if you're interested :) We're currently in the middle of a quest but everyone is doing their dailies and talking on the chat to support each other, so we should defeat this boss in 1-2 days.
EDIT: we all defeated a 500HP, 2x strenght boss in less than 12 hours! :)

Invitations are currently closed, since we already have 20 members, and that's quite a lot, but I can open an exception for you if you want :)

**Comment by Alys** [comment]
@NicoleNobody I will remove the quest from your party in a few hours. (I haven't been able to yet because of internet issues.)

**Comment by Alys** [comment]
@NicoleNobody I've deleted the quest from your party.

**Comment by NicoleNobody** [comment]
Alys, thank you so much!

**Comment by Brubrubru** [comment]
Hi, I have the same problem. Our owner is sleeping since 29/8 and we are stuck. This is annoying.
id of the party 9b66352a-f0b2-42fb-81b7-c21a014edafe
my own id b0017bf9-7b7f-414d-8f29-14030773f1fe
can you help us please?
