### ISSUE TITLE
[Android] Cannot access Inventory

### ISSUE THREAD

**Issue by chrisisinclair** [HabitRPG/habitica#6677]
Im level 6 and I can access all functions just fine on my web browser. However on the Android app I cannot click inventory - it is partially grayed out (although not as gray as the coming soon features). Is this a bug or ?

**Comment by crookedneighbor** [comment]
Would you post a screenshot?

**Comment by Cartogenic** [comment]
Both Social and Inventory are grayed out, took a screenshot: http://i.imgur.com/YXjXEye.png

**Comment by Alys** [comment]
Those are both sunheadings for the items under them.

@vIiRuS et al: We see this question reasonably often in the Tavern. Perhaps the subheadings can have a colon after them, or be underlined, or something?

**Comment by chrisisinclair** [comment]
Thats exactly how mine looks

**Comment by Alys** [comment]
Sorry, I've only just noticed that this has been posted in the website's repository. For Android bug reports, you can use About > Report a Bug or send an email to mobile@habitica.com or report them on the Android repository (see Help > Report a Bug from the Habitica website for a list of the methods).

However this particular thing is intentional, not a bug. The Inventory item is a subheading and isn't meant to be clickable. 

@chrisisinclair you might like to make a feature request to have the Inventory item formatted to look more like a subheading, perhaps by adding a colon after it, or some other method. You can make feature requests on the app through About > Request a Feature or by email to mobile@habitica.com
