### ISSUE TITLE
Can't join challenge - "Error request entity too large" - Basic Meditation challenge

### ISSUE THREAD

**Issue by wyantb** [HabitRPG/habitica#6678]
User b9ef1d3f-01a8-4bb8-8430-d37e16a8a197, attempting to join the challenge at https://habitica.com/#/options/groups/challenges/1deb5c06-33a0-4d24-8edb-f911be82964c

When I click join - on Linux, FF and Chrome have the same behavior - server returns a 500 error `{"err":"request entity too large"}`.

Looking at the data:

```
config: Object
  cached: false
  data: v
  headers: Object
  method: "POST"
  transformRequest: Array[1]
  transformResponse: Array[1]
  url: "/api/v2/challenges/1deb5c06-33a0-4d24-8edb-f911be82964c/join"
  __proto__: Object
data: Object
headers: (c)
status: 500
statusText: "Internal Server Error"
__proto__: Object
```

Both `config.data.description` and `config.data.dailys.history` (Array of 5461 objects) are fairly large.

**Comment by keysmashes** [comment]
See #6646. Tl;dr: soft max participant limit is 1800. You may be able to solve this by joining directly from [the list of challenges](https://habitica.com/#/options/groups/challenges) rather than the specific challenge page.

**Comment by Alys** [comment]
@wyantb That error happens when challenges get too popular or too old. I'll talk to the challenge creator about closing that challenge and creating a new version of it, which won't have that error. Check the challenge list in a few days to see if there is a new version (it will have fewer participants and a different string of random characters in the URL).

I'll try to remember to post the new URL here if the creator lets me know when it's been created.

**Comment by Alys** [comment]
I've sent a message to the challenge creator.

**Comment by wyantb** [comment]
Ah, if there's no code changes here (e.g. stripping out # of challengers for the post), no need to keep the issue around.  I'll keep an eye out.  Thanks!

**Comment by keysmashes** [comment]
See #5831 and #1471.
