### ISSUE TITLE
Bottom and right of XP graph is clipped

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#6679]
Adding a few more pixels to the SVG element's height/width fixes it, but also makes it overlap with the tags; this is fixable by increasing the size of the (grand)parent div, but that seems like a nasty solution. Anyone know how the SVGs work? (i.e. how they're generated, why the height gets mangled)

![image](https://cloud.githubusercontent.com/assets/9433472/12893727/bf142b3e-ce8a-11e5-80f0-60acd0413bfc.png)

**Comment by ltorroba** [comment]
Seems like this is a problem to do with the chartArea option on the `toggleChart` function of `website/public/js/controllers/rootCtrl.js`. I'll be doing some tests tomorrow and see what can be done about it.

**Comment by ltorroba** [comment]
So I did some tests and this boils down to the fact that the size of the container object of the SVG, defined through the `width` and `height` parameters, is not sufficiently big enough to contain the chart, the legend and the axes.

The fix to this issue was simply a matter of adjusting the `chartArea` property so that the legend and axes are given a fixed, minimum space to be drawn, and then the chart is drawn in the remaining space.

I've addressed this issue as part of a series of fixes when it came to the problems that came up when drawing charts. Here's a preview of the fix, running on Safari @ Mac OS X:

New alignment, 1000’s (red background for illustration):
![](http://i.imgur.com/3ckQEq7.png)

New alignment, decimals (red background for illustration):
![](http://i.imgur.com/KA1J6wt.png)

**Comment by SabreCat** [comment]
Client issue. Pending for frontend redesign.

**Comment by librarianmage** [comment]
Should this be closed and considered during re-implementation?

**Comment by SabreCat** [comment]
Yes, we don't currently have the graphs at all, so this issue isn't in evidence.
