### ISSUE TITLE
Timing issue when clicking multiple times on a Habit or a skill

### ISSUE THREAD

**Issue by htgiddings** [HabitRPG/habitica#6701]
I often click on my habits or skills multiple times before the last click is synched and the notifications have appeared.  Sometimes, though not often until recently, this results in an Application Error that means I must reload the page.  Also recently, the error appears when the loading bar across the top reaches completion and I must reload the page several times before it disappears and I can use the Task interface again.

Javascript error: app-c14655c7.js:6 POST https://habitica.com/api/v2/groups/undefined/chat/seen 503 (Service Unavailable)
OS: Mac OSX El Capitan 10.11.3
Browser: Google Chrome
User ID: 2bed1856-7922-4e1e-a4a0-e08819c0bfaa

**Comment by kyuuei** [comment]
If you're getting the app error message, I would not try to attempt clicking tasks. If worried, try to 'pause' the game at the tavern and wait for a small amount of time, and then try interacting with the game again, exit and re-enter and see if the stats reset before trying to click multiple tasks as checked. There is a known issue with the app errors that is being worked on, so this might just be a bandaid until this is better fixed server wide.

**Comment by Alys** [comment]
@autopsyblue @kyuuei There's no need to repeatedly start and stop resting in the inn. If you're concerned about taking damage from incomplete Dailies overnight (probably a valid concern at the moment), then rest in the inn now and stay in there all day. You can keep ticking off tasks and Habits, and can keep doing all other functions on the site while you are in the inn. If you get to the end of the day and you've completed all your Dailies, and if they're still marked as completed after logging out of Habitica and logging back in, then you can stop resting in the inn to allow all the normal cron processes to happen overnight.

@autopsyblue  clicking on tasks or skills multiple times before previous clicks have synced is not recommended, even when the site is performing well. It tends to cause sync errors, which aren't necessarily connected to server load problems such as we're having at the moment. See http://habitica.wikia.com/wiki/Sync_Errors for more information.

If you'd like to track our progress in fixing the server errors, see https://github.com/HabitRPG/habitrpg/issues/6700 . You can subscribe to email notifications in the right hand column. 

I'm going to close this issue now since we're using the other one for the server errors, but if you have questions about anything I've written here, comment in this issue.

**Comment by htgiddings** [comment]
@kyuuei That's not what I'm saying.  I'm not clicking off tasks when an app error has already occurred, I'm checking them off quickly and getting an app error.

@Alys Well that's annoying.  :T I break up my habits into small pieces so I can be a little more granular, so often I want to hit them several times in a row.

Thanks for the links, but again I think that's not quite what I'm talking about.  I'm talking about an error that is initially caused by a synch error but persists even after several reloads.

**Comment by Cartogenic** [comment]
@autopsyblue that is what @Alys was referring too.
I had the same problem these last few days, just go check issue #6700, check my screenshots, is that the same issue you're having?
