### ISSUE TITLE
I seem to have gone back in time - lost level, XP, regained eggs & food.

### ISSUE THREAD

**Issue by vg19** [HabitRPG/habitica#6707]
This afternoon, I spent a fair amount of time doing the enchanted armoire about 80 times.  I then took all the accumulated food and fed a bunch of pets, as well as hatched a number of quest eggs.  
I did this using IE on my work computer.  I came home this evening, and refreshed my session that I had been logged in with on chrome on my home laptop.  It appeared that a number of dailies had reverted to being unchecked, all the food that I had fed my pets was back, I had gone down a level (since all those dailies weren't checked), the eggs I hatched had returned to eggness, etc.  I've killed and restarted my browser, refreshed a number of times, etc.  It is though I reverted about 5-6 hours from the current time.

**Comment by Alys** [comment]
Ugh, I'm so sorry about this. That sounds immensely frustrating.

The problem has happened on your work computer, so nothing you do on your home computer can fix it.

What's happened is that, due to the server errors we've been having lately, your browser at work has stopped communicating with Habitica's servers. All of the actions you took that seem to have be reversed were done in the browser alone and were never saved to the server for permanent storage.

It is possible that if you went back to your work computer and reloaded the site, the actions would then become saved to the server and you'd then see them on your home computer as well. However it's also possible that reloading on your work computer would cause the actions to vanish. There's no way we can predict which will happen, or force the actions to be applied.

I'm guessing you won't be back at your work computer for a couple of days, so I think it's probably best that we consider those actions lost.

What we can do is try to make up for it by giving you food or, if you prefer, directly applying the food to your pets so that you don't have to go through feeding them again. We can also cause eggs to turn in to hatched pets. If you had gained equipment from the Armoire, we can ensure that it appears in your account now (if you can't recall what you gained, we can give you a random selection). Alternatively, we could give you gold (or you could use [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to get it yourself) and you could then repeat your clicks on the Armoire, but I'm reluctant to make you click again 80 times!

Let us know what you'd like to have done to minimise the effects of this error on you.

I recommend that you read the "Advice" section near the top of this issue: https://github.com/HabitRPG/habitrpg/issues/4313 (points 1 and 2 especially) because it will help you recover from the unfair damage and losses caused by the Dailies that should have been marked as completed.

**Comment by vg19** [comment]
Alys –

  As best I can tell, the food that I got seems to be there.  And, of course, I realize that this is no fault of yours (or anyone else’s, other than the evil computer gods).  If it isn’t much trouble for you, if there is a way to feed the food I have to the pets I have (who gets what doesn’t really matter – it’ll just stave off the inevitable carpal tunnel syndrome in my mouse hand a bit longer), that would be wonderful.

  I appreciate the speedy response, and the help!  Me, being an old fashioned server-type programmer, completely spaced the fact that it’s all javascript, and the fact that I saw everything get applied didn’t obviously mean that it had to have hit the server.  Life was much simpler in the old green screen days!  ☺

Thanks!

Vic

**Comment by Alys** [comment]
Thanks for understanding! :)  I miss the days when websites were simple HTML and CGI scripts. They just worked. `sigh` :)

I should have asked before: What is you User ID? You can see it at Settings > API (https://habitica.com/#/options/settings/api ). I can use that to find your account and feed your pets.

**Comment by vg19** [comment]
99ab5aa5-ef23-4745-917a-2a8d14b6ea32
Thanks again!

**Comment by Alys** [comment]
I've fed a bunch of your pets, but only to the point where they need just one more food, and I've left the food required to finish feeding them, where possible. This is because I like doing the final step and taking my new pet for a run and I thought you might too. :)

Let me know if anything else needs to be fixed!

When you get back to your work computer, I recommend that before you try to use Habitica in any way, you first go to https://habitica.com/static/clear-browser-data and click the button there. That will clear out any of your previous unsaved actions, which will prevent them being rewritten to the server. You might experience odd results if that isn't done.

**Comment by vg19** [comment]
Danke!  I will clear out the cache as recommended (after I take the new pets out for that run, of course ☺)(in the figurative sense!)

Thanks!

**Comment by ghost** [comment]
psst, @vg19 , when you responded by email it attached your name and work info, with phone number. You probably want to come to the page and edit that out (I can't do it for you).

**Comment by vg19** [comment]
Danke!
