### ISSUE TITLE
Invited to a quest in the Tavern

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#6714]
This one's a new one on me and seems to involve a problem with the way the Tavern is set up to work, so I thought I'd better report it. I just received an email asking me to join in a quest. I'm already both in a party and on a quest, and didn't know the person who apparently sent the invitation. Text of email was the usual "help [user] complete the Attack of the Mundane" etc.

When I went on Habitica, I still saw my own party as usual, but when I went to the Tavern, I saw a quest pane... 

![screencap](http://oi65.tinypic.com/2uszjf6.jpg)

I do know that I am a "member" of the Tavern thanks to once clicking the "join" link when I landed on the Tavern via [this link](https://habitica.com/#/options/groups/guilds/habitrpg). Might be part of the issue. 

Hopefully nothing's broken and this is just an odd glitch caused by an unforeseen way of using the site! Either way, thought I'd best report it.

**Comment by Alys** [comment]
Thanks, @shanaqui! I received the same invitation on both of my Habitica accounts (one much less known), and I've just discovered that I see the quest in the Tavern too.

I'm going to do what I can to end that quest after capturing data about it.

**Comment by rachelkachel** [comment]
I'm seeing this too, same quest, same usernames except for shanaqui's. I didn't get an email or an invitation though. (I do get email notifications of quests normally.)

**Comment by shanaqui** [comment]
I assumed it would be related to being a 'member' of the Tavern which doesn't really have that structure, but maybe not... Glad you're on the case, @Alys!

**Comment by Alys** [comment]
Okay, the quest invitation was sent to everyone who's a member of the "habitrpg" guild (the Tavern). @shanaqui you were right about that.

It's possible to become a member of the Tavern by joining it through its normal guild interface at https://habitica.com/#/options/groups/guilds/habitrpg (i.e., the Tavern is treated as a normal guild in some ways). I'm probably going to delete all the members from that "guild" as part of the fix for this (I can always put them back later if needed).

**Comment by Alys** [comment]
Okay, the quest is deleted from the Tavern and all the members are removed.

@lemoness 110 people were invited to that quest and at least some would have received emails, so we might get questions about that.

The quest invitation was put into all of those user's accounts, so I'm about to start removing it form all of them. This invitation would have wiped out any earlier invitations to real party quests, so I'll also try to put those back in, although that might take a while.

At this stage, I have NO idea how this happened. The person who sent the quest invitation is a new user and I'm quite sure they didn't do it deliberately - they're the unfortunate victim of some bug.

**Comment by shanaqui** [comment]
@Alys I dropped a link and explanation in the Aspiring Socialites guild to help respond to any questions that come up!

**Comment by Alys** [comment]
@crookedneighbor has found the code that allowed this to happen. In brief, if you're not in a party but still manage to send a quest invitation (might be only possibly through the API), then the quest will pick up a guild/Tavern as the place it "belongs". We can push a fix to that quite easily, so we can stop this happening again.

I've removed the quest invitation from all the user accounts, although I can't do anything about the invitations that were sent by email.

I'm starting to work on restoring any quest invitations that should be in the user accounts.

**Comment by Alys** [comment]
All quest invitations that should be present are now restored (7 players affected).

I also have to adjust the account for all users who were in a quest that was already running. The Tavern quest invitation would have removed their participation from their real quest. Since there's about a hundred of them, some might cron before the fix gets to their account. If we get any reports of lack of quest progress over the next day, it could be from this issue. I'm keeping a list of the players affected so I'll be able to tell.

**Comment by Alys** [comment]
38 players were already on real quests, and I've replaced their proper quest information in their accounts. @shanaqui you were one of them - can you please reload your party page and tell me if the quest appears as expected? Also tell me after cron if there's no progress report in party chat for you.

Unfortunately, all of the current day's quest progress has been lost for those users and I have no way to find out what it was. I'm going to send them all a PM to let them know that they can tell me what quest progress they want applied (they won't have to PM me today; I can add it to their account whenever they reply). For some time now, I've been wanting a script that sends PMs semi-automatically, so this is a good excuse to write it. :)

**Comment by Alys** [comment]
PMs sent.

The only remaining tasks are to change the code to prevent this happening again, and then after that I'll search through the guilds for any others that have quest information in them, just in case this bug happened in the past and we didn't notice.

@crookedneighbor's notes about the suggested fix:

---

Here's the problem https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/api-v2/groups.js#L905-L909
the quest code just pulls the group info from `res.locals`
There is zero validation on it
Quick fix would be https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/api-v2/groups.js#L909

```
if (!group || group.type !=== 'party') return res.json(400, {err: "Must be in a party to start quests."});
```

Fairly certain that's it, but would like to check

---

**Comment by cTheDragons** [comment]
@Alys I was one of those users who was affected and in a quest. My quest information stayed. We had just started, and I was the first to cron this morning with small 7.8 (yes very poor performance) and the Boss is reporting that it is still damaged by it. Or am i missing understanding what you mean by Quest information.

**Comment by Alys** [comment]
@cTheDragons That's good! Thank you! That's just the information I was referring to, and it sounds like it's all happening as it should. Although it is possible that you cronned before the bug affected your account, so watch it again tomorrow. No need to report if it all still seems normal.

**Comment by Ks2ndChoice** [comment]
Hi all, I am the "owner" of the quest. I've been using habitica only for a few days and I hope I did'nt do anything wrong. If so, my apologies for any inconvenience.
Here's some information that might be of interest for the bugfixing. I started that quest from the iOs mobile app from my private party page. I had to try twice, before I could see the quest description and the quest seemed to be activated. It is my first experience with quests, so I can't compare to other occasions.

**Comment by Alys** [comment]
@Ks2ndChoice Hello! Thank you very much for commenting! You did not do anything wrong; this is a bug that you fell victim to through no fault of your own.

Those details are VERY useful - thanks! I'll make sure the iOS developers know about it. The fix we have planned (described a few comments up) will stop the same problem occurring, but there might also be other fixes we can put in place for making it easier to start quests on the app.

If you experience any other problems with the quest, do tell us and we'll help.

**Comment by Dewines** [comment]
This is sort of related to the accidental quest invitation, so I thought I'd mention it here. After @Alys removed all the member of the Tavern guild (as it appears in the guild list), it therefore dropped down to the bottom of the list because it had zero members. Looking inside without joining, its owner appeared to be a level 1 player. Curious as to what would happen, I then joined the Tavern guild and therefore it's now made me owner! I have an edit group button and everything! I assume that changing things there wouldn't alter the appearance of the actual Tavern, but I'm worried that it might. I therefore thought I'd better remain as "leader" for the time being and raise the matter here. Should a mod be the leader of this guild? Or (possibly better) can it somehow be hidden from the guild list? To be honest, it was only when the accidental quest invitation happened that I realised that the two Taverns were one and the same. Until then I'd thought that someone, for some reason, had created a guild and called it "Tavern".

**Comment by Alys** [comment]
Ohhh duuuuh that was so foolish of me. I should have left a proper leader in there. 

I've just made the leader Lemoness, and placed her as the only member of the guild. 

Yes, we'll hide it from the guild list - we've been talking about doing that for some time but it hasn't seemed as important as it does now.

Dewines, **thank you**, especially for staying as a leader to protect it. You would have been able to edit the Tavern's description, etc, so I'm very glad it was you who discovered this. :)

**Comment by lemoness** [comment]
Yikes, close call! Thank you so much, Dewines.

**Comment by Alys** [comment]
Fixed with https://github.com/HabitRPG/habitrpg/commit/fb338a00cbfff85857c620c29196b17a34bdfde5
No guilds have quests now.
