### ISSUE TITLE
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by Vicnov** [HabitRPG/habitica#6716]
User id 05aee64a-45f6-4a5d-b0db-c19d756ae6b9

Chrome 48.0.2564.109 m
Windows 10 

Getting an error saying that "application can not be served", "please reload"

after getting this error 3-4 times the app started to work correctly

Console:
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1699863280.1454911651&jid=1708638213&_v=j41&z=324963959 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

https://habitica.com/api/v2/user/batch-update?_v=5258&data=1455502368062 Failed to load resource: the server responded with a status of 503 (Service Unavailable)

app-c14655c7.js:32 Objectconfig: Objectdata: "<!DOCTYPE html>↵    <html>↵    <head>↵      <meta name="viewport" content="width=device-width, initial-scale=1">↵      <style type="text/css">↵        html, body, iframe { margin: 0; padding: 0; height: 100%; }↵        iframe { display: block; width: 100%; border: none; }↵      </style>↵    <title>Application Error</title>↵    </head>↵    <body>↵      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">↵        <p>Application Error</p>↵      </iframe>↵    </body>↵    </html>"headers: (c)status: 503statusText: "Service Unavailable"**proto**: ObjectresponseError @ app-c14655c7.js:32

**Comment by kotylw** [comment]
I am having a similar issue.  My error is persistent and will not stop occuring.  I am getting a red box that says reload page and every now and again I get a page that says the page wouldn't load.  This started a few days ago, but has gotten worse.  I also use Chrome, and use both Windows 7 and Windows 10.  User ID: 0eeeb347-64ca-4321-9b81-a7408de63ad1
![errorhabitica](https://cloud.githubusercontent.com/assets/16230029/13052165/4ef15872-d3cb-11e5-9d4f-e5a0db883bf6.png)

**Comment by SabreCat** [comment]
The application errors were due to server overload trouble we're grappling with, documented in several other tickets. ERR_BLOCKED_BY_CLIENT is something different, though. @Vicnov, do you run any ad blocking software? You'll likely see that error in the console whenever your adblock stops something.

**Comment by Alys** [comment]
@Vicnov and @kotylw We're tracking the server errors in https://github.com/HabitRPG/habitrpg/issues/6700 so I'm closing this one now. This comment in that issue has our latest update: https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-184375608

@Vicnov as @SabreCat says, that ERR_BLOCKED_BY_CLIENT will be from security/privacy software on your PC blocking optional, third-party features on the website. It's not related to the server errors and it's not something you need to worry about. I see it often in my browser because of my blocking tools. However if you have questions about it, you're welcome to comment again here.

**Comment by ChintuKarthi** [comment]
hey can anyone explain me about how to remove "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" without disabling the AdBlock ?
because if i develop a webpage, i don't want my users to get those error because of some AdBlocking softwares.

I am new to web developing, don't mind if there is an easy to to do it and i didn't know about it means i'm sorry, and please help me out!
Thanks :)

**Comment by WiseEagle** [comment]
You can ask your users "please disable AdBlock for this site, for view more..." JS or jQuery can halp you!)

**Comment by LiuJQ** [comment]
> The application errors were due to server overload trouble we're grappling with, documented in several other tickets. ERR_BLOCKED_BY_CLIENT is something different, though. @Vicnov, do you run any ad blocking software? You'll likely see that error in the console whenever your adblock stops something.

Save my time, well done !
