### ISSUE TITLE
Setting tags for multiple items

### ISSUE THREAD

**Issue by wwahammy** [HabitRPG/habitica#6718]
Often I create multiple items and forget to set the tag ahead of time. Right now I don't seem to see a way to edit tags on multiple items at once. This can be really tedious to fix. It'd be nice if there was a way to set the tags on multiple activities at once.

**Comment by Alys** [comment]
There isn't currently a way to edit tags on multiple items at once, however that's by design, rather than from a bug, because our programmers haven't had the time to add the feature yet. It's been requested on our Tags Trello card at https://trello.com/c/HzlNeTQB/274-tags-v-2-tag-ideas-enhancements and it is likely to be something that is added at some time in the future. You can access other features request cards from Help > Request a Feature from the Habitica website's menu bar.
