### ISSUE TITLE
Post-Rebirth Cross-class items bought with gems not appearing for gold purchase

### ISSUE THREAD

**Issue by Aloriellelyn** [HabitRPG/habitica#6724]
At least, not unless you select that class.

Long description:
After I used the orb of rebirth, I expected (by all descriptions) that ALL items I had purchased with gems would be available for purchase with gold. Instead, I have discovered that items that are not my current class (warrior) remain hidden. In fact, I can't even re-purchase them with gems because I have already done so. This means that I will have to spend gems to switch classes, just so that I can get the items I have already purchased with gems.

Instructions to reproduce:
1) Get to level 50+.
2) Buy an item from the seasonal shop that is not from the warrior class.
3) Use orb of rebirth.
4) Note how at level 1 you cannot repurchase any item that isn't a warrior class item (or non-class specific).

At this point, to reacquire all the items I have had, I will have to switch to all 4 of the classes.

Solution:
Allow any previously owned object from any class to be purchased for gold. Items that were not previously owned would remain unavailable unless their respective classes are chosen.

**Comment by Alys** [comment]
This is actually the current expected behaviour of the Orb of Rebirth, rather than a bug, although it will be changed in future. The current intention is that the Orb takes you back to a state very similar to that of a new user, which means that equipment from other classes is not available to you. That's what it's getting at in the Orb's confirmation screen when it says "Limited edition equipment you've purchased can be repurchased, even if its event has ended. To repurchase class-specific equipment, you must first change to the correct class." Please tell us if you have suggestions for making that clearer! I'm sorry it isn't clear already!

Our intention for how the Orb will be changed in future is described in https://github.com/HabitRPG/habitrpg/issues/5750#issuecomment-166851875 so I'm closing this issue now, however you can still comment here and we'll see it. If you tell us which equipment pieces you purchased with gems, we will put them back on your equipment page.
