### ISSUE TITLE
Custom Day Start was set to 11pm -- CRON - Habitica acha que hoje é Quinta, sendo que hoje é Sexta.

### ISSUE THREAD

**Issue by EdisonMatos** [HabitRPG/habitica#6738]
Procurei procurei e não achei nada neste aspecto. A situação é a seguinte:

Já fiz alguns testes lógicos e ficou claro que, para o habitica, é como se hoje fosse QUINTA FEIRA (sendo que hoje é Sexta, dia 19), pois tudo que marco pra QUINTA fica colorido, e o que eu marco pra SEXTA, fica cinza, como se ainda fosse chegar esse dia.

O Habitica está considerando hoje uma Quinta feira, e não uma Sexta feira, que é a realidade.
Já me certifiquei de ajustar o fuso horário, pra certificar que o computador está de acordo com o site, e está sim. Já limpei os dados de navegação, mas nada disso foi efetivo até então.

O que fazer? 
Meu ID: 56a8e801-14ee-4230-9b7e-3e0c7c1d7a63

**Comment by ghost** [comment]
Do you have a "Custom Day Start"?  One cause of this problem is setting your Custom Day Start to 22, 23, etc. It doesn't make the day roll over at 11 or 10, it makes it roll over 22-23 hours _late_, so it is thursday until 10/11p.m friday. 

(google translate) Você tem um "Início do Dia Personalizado"? Uma das causas deste problema é definir o seu Início do Dia Personalizado para 22, 23, etc. Isto não faz a mudança dia 10 ou 11 p.m., torna-se mudar 22-23 horas _tarde,_ por isso é quinta-feira até 10 / 11:00p.m. Sexta-feira.

**Comment by EdisonMatos** [comment]
Então deve ter sido isso. Não entendi direito a explicação. Pode esclarecer mais ainda?
Eu mudei o início de dia personalizado mais cedo, mas já voltei ao normal. O que faço agora? Só esperar? Atualmente o meu está 11:00 PM.
Obrigado!

**Comment by ghost** [comment]
The Custom Day Start does not set a clock for the day, or a time zone. Your time zone comes from your computer. The Custom Day Start tells Habitica to wait before changing the day. For example, I have mine set to 6  because go to sleep very late. If my day changed at midnight, I would miss dailies. So it changes at midnight + 6 = 6 a.m. the next day.   But if you go to bed early, you cannot set it for 22 -- it resets at midnight + 22 = 10 p.m._ the next day_.  So, the soonest  it can change is midnight. I hope that explains it. 

Início do Dia Personalizado não definir um relógio para o dia, ou um fuso horário. O fuso horário vem de seu computador. Início do Dia Personalizado diz Habitica que esperar antes de mudar o dia. Por exemplo, eu tenho a minha definida para 6 porque ir dormir muito tarde. Se o meu dia mudou à meia-noite, eu iria perder diários. Então ele muda à meia-noite + 6 = 06:00 do dia seguinte. Mas se você ir para a cama cedo, você não pode configurá-lo para 22 - ele redefine à meia-noite + 22 = 10 p.m._ a próxima day_. Então, o mais rápido que pode mudar é a meia-noite. Espero que isso explica tudo.

**Comment by EdisonMatos** [comment]
Estou começando a entender...
Agora me tire uma dúvida, pra que o meu dia mude exatamente com a virada do dia do meu fuso horário (que seria às 0:00h), qual o horário que eu devo colocar lá?

**Comment by ghost** [comment]
0 .  :) 

It will actually not change at 0:00, but when you first use the site after that. This is not important to know for setting the Custom Day Start, but it is good to know. 

Ele realmente não vai mudar em 0:00, mas quando você usar o site depois disso. Isso não é importante saber para definir o Início do Dia Personalizado, mas é bom saber.

**Comment by ghost** [comment]
Zero, Zero. Not 1. The formatting changed it. 

 Não 1. A formatação mudou.

**Comment by EdisonMatos** [comment]
Certo então! Vou ajustar desta forma!
Obrigado!

**Comment by EdisonMatos** [comment]
Ah, e no momento atual, meu dia ainda está na Quinta-feira. Tem algo que eu possa fazer pra que, agora se torne Sexta-feira já, e mais tarde às 00h, mude pra sábado?

**Comment by ghost** [comment]
You should try syncing the site. There is a button like turning arrows in the upper right corner of the website. If that does not help, I do not know; you may have to wait. 

 Você deve tentar sincronizar o site. Existe um botão como o giro de setas no canto superior direito do site. Se isso não ajudar, eu não sei; você pode ter que esperar. :/

**Comment by EdisonMatos** [comment]
Consegui! Tudo 100% agora! Muito obrigado pelo tempo e pela paciência!
