### ISSUE TITLE
Can't access my inventory

### ISSUE THREAD

**Issue by Tick308** [HabitRPG/habitica#6753]
I have eggs, food, hatching potions, but can't use any of them.

**Comment by Alys** [comment]
Hi @Tick308! We're going to need some more details before we can help you. 

Are you trying to do this on the iOS app or the Android app or the website?

If you're using a mobile app, is it the app called "HabitRPG" which has a brown chest logo, or the app called "Habitica" which has a purple gryphon logo?

What is it that's preventing you from using the eggs, food, and hatching potions? For example, are you unable to access the Inventory and if so what happens when you try to - do you get an error message or does the site / app freeze up or something else? 

Or are you able to access the inventory but then when you click on an item nothing happens? Or does an error happen at that point?

Or can you click on one item (e.g., one egg) but then when you click on a second item (e.g., a potion), does something go wrong? If so, what is it that goes wrong - an error message or a freeze or...?

Is there anything else you can tell us about the problem that might help us work out what's wrong?

If you see error messages at any point while trying to use your items, please tell us the full, complete message.

What is your User ID? To get it, please go to Help > Report a Bug from the Habitica website and read step 6 carefully - your User ID is not the same as your name. We need to know your User ID to investigate this.

**Comment by Tick308** [comment]
I use the Habitca for Android. When i go to side menu and touch the word
Inventory, it does nothing. The word is in a grayish colour, but not like
the ones that I don't have level for.
My ID: dad4081c-e573-4bf8-8c27-d674693649be
Thank you
Patrick Buchmann
Em 22/02/2016 08:56, "Alys" notifications@github.com escreveu:

**Comment by Alys** [comment]
"Inventory" in the app's menu is a heading for the things under it - it's not meant to do anything when you click on it.

One of the items under it will work when you click on it. The others won't because they're not available yet - they have "Coming soon" written after them. When the "Coming soon" message is no longer there, then they will work.

You can access your Inventory on the website (https://habitica.com). If you have any questions about using it, go to Help > Ask a Question from the website's menu.
