### ISSUE TITLE
"Battle Monsters With Friends" Button should persist 

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6754]
We've discovered that users stay much more accountable to their habits and engaged with each other if they have at least 4 people in their party, so we want to encourage that! An easy way to do this is to edit the "Battle Monsters with Friends" button so that it persists until there are four users in the party, at which point it should disappear as usual.

**Comment by colwem** [comment]
Ok, I'll make this my first first coding quest.

**Comment by colwem** [comment]
So I have a solution but I'm stuck on testing.  First of all I can't seem to get the tests to run in vagrant.  It doesn't seem like I can run karma tests or the e2e tests in vagrant.  Second I don't really know how to write my tests or even if you guys want me to write a test for this.  I'm a novice at writing tests.  What I suspect I need is to write a test that puts 3 users in a party and check that the button is present and then a test that puts 4 users in a party and checks that the button is not present.  How do I do that.  It would also be nice if I could run something and get screenshots of what the page looks like in each of these cases on all the major browsers just to make sure it's displaying properly.

Side note.  Where should I be asking for help.  I post to the Aspiring Coders guild but the only person who seems to know what they're doing and checks in regularly is Alys and that means I have to wait a day to get any answers because Alys and I aren't usually online at the same time.  But it looks like there are a lot more people working on this project than just Alys.  I'd love get feedback a lot more quickly than I am right now.  So do I just post my questions here?  On github issues?  Or should I not do that?

**Comment by Alys** [comment]
@colwen Posting questions like this on github issues is absolutely fine! 

There is a problem with some of the tests in that they don't work in vagrant without some intervention. There's a correct way to fix it, but there's also a quick-and-dirty way, and I can't find notes about the correct way at the moment. I really should have added it to the guidance for blacksmiths page. :(  For a quick fix, edit `.eslintrc` to comment out `"no-empty-pattern": 2,` and `"no-arrow-condition": 2,` and `"func-style": [2, "declaration", { "allowArrowFunctions": true }],`, then edit `tasks/gulp-tests.js` to comment out `'test:e2e:safe',`. That should at least let the tests run. 

I'll try to post more later but it won't be for hours because I'm going to work soon. :(

You might like to submit a PR with your solution so far so that we can have a look at it now. Any commits that you make later to the same branch will be automatically added to the PR.

**Comment by colwem** [comment]
pull request made.  How do I link it to this issue.  Can't figure it out.  Need to leave though so I'll look back in on this tomorrow.

**Comment by Alys** [comment]
You can create an automatic link between issues and pull requests by entering `fixes #6754` in the subject of the pull request. I've edited the subject to add that, and also to add words so that if we're later searching for the PR, we can find it easily.

I should also mention... :) There are several others in Habitica who understand the test framework and architecture _much_ better than I do, but they're really busy at the moment on some large-scale, site-wide improvements. I am sorry you're finding this frustrating! :(

**Comment by colwem** [comment]
Ok so now how do I fix the PR.  How do I remove the .gitignore commit?  Do I do a git rebase then push it to origin?  I'm so bad at git I've really messed up using rebase before.  Also, I haven't fully tested this at all yet.  I've only checked that it looks right in chrome and obviously I haven't added or updated any tests.  I just submitted the PR so you could take a look at it.

**Comment by colwem** [comment]
Ok so made the changes @Alys suggested in order to get the tests to run.  There were still problems but at least it finished.  I'm linking the output so you can check to see if it's what's expected.  The `test:karma:safe` section still errored out.  As did the `test:api-v2:integration`.

https://gist.github.com/colwem/b7697fef4ffc3cefe75c
