### ISSUE TITLE
Subscription renewal

### ISSUE THREAD

**Issue by rachelkachel** [HabitRPG/habitica#6755]
My yearly subscription renewed yesterday, but I didn't get any extra hourglasses and the consecutive months didn't increase. Neither of these actually matter at the moment, since I've already bought everything from the seasonal shop and my gem cap is at maximum, but I'd like the information to be correct (and if this is a bug I wanted to make sure people know about it).

There's also the .36 months of extra subscription credit, but that's been there since I first switched to the annual subscription.

My user ID is 7b9c41d3-6d21-4168-9dfd-e0c2489df8ff (Rachel Ann).

**Comment by Alys** [comment]
Sorry about that! I've given you the extra four Hourglasses. Thanks for letting us know!

The 0.36 months of extra subscription credit is something that happens when an earlier subscription doesn't finish before a new one starts (that doesn't normally happen, but can if a gift subscription is involved, and probably under other circumstances too). If you ever end your yearly subscription and don't start a new one, then the 0.36 months will be added on to the end of the yearly subscription period.

**Comment by joyheron** [comment]
I also have this issue. 
My User ID is 63e151fa-0a95-47c6-9bfd-6824b19ebcfc

And I was really hoping to get a Mantis Shrimp :(

**Comment by Alys** [comment]
@joyclark I've given you the extra Hourglasses and another 5 gems on the gem cap. It looks like the subscription renewal happened last month, so I've also given you the extra 5 gems you should have been able to buy then.
