### ISSUE TITLE
Implement Party Cap

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6756]
We've found that very large parties result in a lot of issues, both for the party (see: Quest rewards bug) and for the site as a whole. Therefore, we should probably implement a party size cap.

The number that we were tentatively thinking about as a cap was 30, but that is open to discussion! Parties that are currently larger than the cap should be grandfathered in, but prevented from adding any additional members. 

There should also definitely be a pop-up warning parties when they are approaching the cap, as well as announcing when they have reached it.

**Comment by Alys** [comment]
EDIT: This was COMPLETELY irrelevant and is now deleted. Thanks @colwem :)

**Comment by colwem** [comment]
@Alys I don't understand.  I just tested this and there doesn't seem to be a limit on the number of members that show up in the party member list and removing members isn't hard at all.  Also, isn't that issue: #1806 referring to guild member lists not party member lists?

Wouldn't implementing this cap be as simple as not displaying the invite button when `group.memberCount >= 30 && group.type === "party"` and then in the api refusing at group.invite if the group.memberCount is greater than 30. That and the warning.  I guess we also have to make sure that members + open invites <= 30.

**Comment by Alys** [comment]
@colwem Oh - I was under the impression that parties showed only 15 members in the list, just as guilds do. If they show all members, even for huge parties, then my comment is irrelevant. I never thought to test that. You're definitely seeing all party members for a large party?

**Comment by colwem** [comment]
@Alys yup definitely seeing it.  Tried it with 200 members, all showed up. 

I've been trying to implement this but I've run into an issue that I think is above my pay grade.  It doesn't look like the group object is being updated after an invite is sent so it's group.invites member never changes making it impossible to hide the button after you've sent your 30th invite.  I don't know how to do that updating and I have no idea what side effects doing so would have.

**Comment by querry43** [comment]
Is a party size limit actually an end-goal or just a means to limiting large party difficulties?  If someone actually has 30 some friends, I hesitate to require some party friend exclusion.  I could see this happen if it was a school or work group.

Could large party problems be addressed bu applying the diminishing returns mechanism on damage to and from a boss relative to party size?

**Comment by Alys** [comment]
@querry43 The issues that Lemoness was talking about are bugs that occur more often when the party is large. Ideally of course we'd change Habitica so that the bugs couldn't occur, and several of our best devs are working on making improvements like that now, but it's possible that even then issues would occur from large parties. Limiting party size is likely to improve performance for various reasons.

This isn't related to the amount of damage to and from a boss; there are no bugs with that as far as we are aware, regardless of party size. If you'd like to make suggestions about that from a game balance point of view, Help > Request a Feature will contain an appropriate Trello card.

**Comment by SabreCat** [comment]
This has been live for a little while now! Closing.
