### ISSUE TITLE
Invite friends (to a new party) modal may need the Invite Later button

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6757]
When a new user wants to create a new Party they have the following options:
1. The Party page -> Start a Party with your friends -> Invite friends modal -> Send invitations -> New party created
2. The Party page -> Invite friends now -> Invite friends modal -> Send invitations -> New party created
3. The Party page -> Invite friends later -> New party created
4. Battle Monsters With Friends button in header -> Invite friends modal -> Send invitations -> New party created

The issue is with the fourth option. The only way to create a party from that modal is by clicking Send Invitations. So it's not evident with that route that a user can actually create a new party now and invite friends later.

Suggestion: add Invite Friends Later button from the Party page also to the Invite friends modal
![Pic](http://snag.gy/3QUgx.jpg)

The only question is if it's been made this way deliberately as a marketing feature in order to make the newbies invite more new users to Habitica?..

**Comment by Alys** [comment]
@lemoness What do you think of this?

**Comment by lemoness** [comment]
So, this was actually a deliberate feature, since the "Battle Monsters with Friends" is not meant to create a 1-person party, but rather to invite people. As you said, its goal is to encourage parties with others!

As a result, I'm closing this ticket, but feel free to comment here if you have any questions or concerns :)
