### ISSUE TITLE
Health won't reset when I level up

### ISSUE THREAD

**Issue by radtastical1** [HabitRPG/habitica#6759]
I've leveled up twice recently, and my health didn't reset to full either of those times. My user ID is 7d0731c9-4be3-4582-9451-422061eeb3b8 and I'm using Chrome.

**Comment by Alys** [comment]
Can you tell us a bit more about the level-up process on both of those times? 

Did your health change at all when you levelled up? How much health did you have immediately after levelling up - if you don't recall exactly, can you tell us if it was very close to full or not?

What date did each of them happen on? Also approximately what time, if you recall that? Please also tell us your timezone so that we can work out what date it was on the server -- specify the timezone as a number (e.g., GMT -7), rather than as a timezone name.

Did they happen first thing in the morning (e.g., when you ticked off your first task of the day) or did they happen later in the day?

Did you notice a quest being completed at the same time?

Are you on a boss quest and do you have party members that often allow the boss to cause damage to the party?

**Comment by radtastical1** [comment]
I'm sorry I completely forgot to respond to this before. But I leveled up
again today and it appears to be fixed?? I finally got my full health back.
