### ISSUE TITLE
MarkDown format on To Do task

### ISSUE THREAD

**Issue by markediez** [HabitRPG/habitica#6771]
Is it intended for the tasks to be formatted through markdown?

**Comment by Alys** [comment]
Yes. If you're seeing a task that the formatting doesn't apply to, please show us a screenshot of it, and also copy the text of the task into a new comment here as plain text, and tell us your User ID (see step 6 of Help > Report a Bug from the Habitica website's menu).

If you're just asking for help with markdown, Help > Ask a Question is the best place because you'll often get an answer faster there.
