### ISSUE TITLE
Armoire equipment lost, found again, but doesn't appear in equipment

### ISSUE THREAD

**Issue by CookieAD** [HabitRPG/habitica#6785]
Hi!
I lost my Shepherd Crook from the Enchanted Armoire due to character death, and it showed up in the rewards column for me to buy back. Later, when I had 100 gold I clicked the armoire button and was told that I had found a Shepherd Crook - but it is still listed in the reward colum, and doesn't appear in my equipment. (It's possible I misremember it being the object I found in the armoire, but I'm 95% sure it was the same crook.)
User ID: 1deeefb5-cd63-4625-84b7-20994acd748b
Using Firefox 44.0.2, Windows 7

**Comment by Alys** [comment]
Please see the bug reported in https://github.com/HabitRPG/habitrpg/issues/5376 ("Enchanted Armoire drops equipment but no gear or the wrong gear appears in Inventory"). Your character death was unrelated to this - it just happened that the Armoire incorrectly reported the item that you'd lost due to death. That issue has a section in bold near the top that explains the issue and gives you advice about getting back your gold, if you wish to (note though that the Armoire did give you something - possibly food or XP).

**Comment by CookieAD** [comment]
Alright, thanks for clarifying!
