### ISSUE TITLE
Wrong invitation to the party.

### ISSUE THREAD

**Issue by BasilYinYang** [HabitRPG/habitica#6795]
---
## ENVIRONMENT

Win8, Ubuntu 14.04, GChrome Version 45.0.2454.93 (64-bit)

Group ID: 89f6a05d-408b-4547-9daf-93bd72e32a48
User ID: 93f4da09-fd0b-419f-ad7b-0ccb1c7ec224

---
## DESCRIPTION

1) I always have invitation to my current  party on the "Party" Tab although I'm in the party from the beginning of my life with Habitica.
2) I've tried to reject and tried to accept it once again but nothing changes. 
3) My name is also in the "Invitation" frame on the "Party" Tab. Our leader also see it, but I afraid to ask him delete my invitation due to we are always in the quest and I don't know will I in the quest after that or not.

---
## ADDITIONAL INFO

I also couldn't invite my friend through email. When I try to do this nothing happens. May be these are linked issues or I need to create new issue?

**Comment by rektascensja** [comment]
I have such an issue too. And each time I accept the invitation, a copy of basi-list scroll is added to my quest scrolls. 
User Id: 3444a638-6491-4380-b52b-3eac3743fd29
Party Id: 87469c87-37c4-4f28-bf91-85b7cdb182b1
Issue appears on the webside, both computer (fedora 19, firefox 43) and mobile (android 5.1.1, chrome 48.0.2564.95)
And I don't have problem with inviting via e-mail.

**Comment by Alys** [comment]
The invitation bug is described in https://github.com/HabitRPG/habitrpg/issues/5649 "Accepted party invite, but Invitation doesn't disappear". Please see the "What to do if this happens to you" section near the top of that issue for a list of steps to follow. Comment in that issue if they don't work for you.

@BasilYinYang Not being able to invite your friend by email is a different problem, but we can handle that in this issue. When you say that nothing happens, do you mean that when you enter their email address into the invitation form and then click the "Send Invitations" button, literally nothing happens -- i.e., the invitation form stays visible and you don't see a notification that the invitation has been sent? If so, please log out of Habitica, clear your browser's cookies, and then try again.

**Comment by BasilYinYang** [comment]
Alys, thank you for #5649 - it helps!:) 
About friends invitation: after I enter data into fields "Name" and "Email" and press "Send" button I see notification that the invitation has been send. Then I close "Invitation" window, but I don't see the name of my friend in the  "Invitations" frame. Although I can see the names of another persons, who were invited by another members of our party. More over, my friend say that she wasn't receive invitation (I understand, that this could be email problem, not Habitica)

**Comment by Alys** [comment]
When you send an invitation by email, it's expected that the invited person won't immediately appear in the invitation list, because Habitica doesn't know which Habitica account is associated with that email address. When the invited person receives the email and clicks on the link in it, then they will appear in the list of invited people. Note that they will also experience the problem described in https://github.com/HabitRPG/habitrpg/issues/5649 so you might want to show that issue to them - sorry about that!

We've tested email invitations very recently for another issue and they were being sent, so I think you're right that the email not being received is an email problem, not a Habitica problem. Have they looked in their junk mail folder?

If the person already has a Habitica account, you can invite them by their User ID, which they can see at Settings > API (https://habitica.com/#/options/settings/api ), or you can see it in their profile by clicking on their name in a chat area (e.g., the Tavern). Inviting them by User ID avoids all problems with email and should also avoid the problem from https://github.com/HabitRPG/habitrpg/issues/5649

**Comment by BasilYinYang** [comment]
"When you send an invitation by email, it's expected that the invited person won't immediately appear in the invitation list, because Habitica doesn't know which Habitica account is associated with that email address. When the invited person receives the email and clicks on the link in it, then they will appear in the list of invited people. " - if it really works in that way let's close this issue. And if my invitation will be in junk folder I'll send one more.

**Comment by colwem** [comment]
Why don't we put a stub in the invites list anyway that says something like
"Invited by {{inviters username}}".  Then when the invited user clicks on
his e-mail link we replace the stub with the real user.  While working on
the "party cap issue" I've been basically ignoring e-mail invites but had
felt that this was a weird issue.  As someone who just started a party and
sent out invites I was very confused by this.  I actually ended up spamming
my brother with 3 e-mails because I was expecting it to show up in the
invites list but it didn't so I assumed there must have been an error.
