### ISSUE TITLE
Lack of damage

### ISSUE THREAD

**Issue by Ultrarobb** [HabitRPG/habitica#6797]
I've been trying to find a solution in older posts and have come to realize I need to ask for help.

Starting yesterday and continuing today I'm not getting the credit towards a boss I used too.  I could get 1000+ damage a day, but yesterday I only got 71.  Today though doing quite a bit, I only have 39.  Something is wrong.  I checked my stats and they are always what they are, so my gear has not changed.  What can be done?  I can't contribute to my party.  Help.

ID:  fab8b52f-3587-4c9b-9f32-2ddf6ac875f6

**Comment by Alys** [comment]
When you do more than 100 damage a day, it's usually from the skills Brutal Smash (Warrior) and Burst of Flames (Mage). If you've been casting them in the past but not yesterday and today, that would explain the difference. Tell us if that's not what's happened.

**Comment by Ultrarobb** [comment]
I've been using Brutal Smash for a long time now.  I've though have been using brutal smash the past few days and it seems not to be working.  The + is showing up an the mana is going down.  So something is starting.  I've nothing different.  I did though leave a party and started a new one.  Could that have messed up my account?

**Comment by Alys** [comment]
You've probably experienced a problem where your browser shows you the results of an action (e.g., casting a skill) but doesn't send that action to the server for permanent storage. Have you been seeing a lot of red application error or server error messages on the screen since yesterday? Do you always reload when you see them? Have you noticed anything else being wrong, such as tasks that you ticked becoming unticked?

If you ever notice an action being taken but the result not being applied permanently, try reloading the site and if that doesn't work, try logging out. You can check the immediate effect of Brutal Smash on your boss damage by going to Data > Data Display Tool and refetching the data each time you cast it (normally you don't need to do that of course, but it will help to trouble-shoot this issue).

**Comment by Ultrarobb** [comment]
OK, I think that fixed it.  I logged out and then back in.  I then did 6 Brutal Smash on Habits, then did a "TEST" to do with some tick off's, and saw the damage go from 39 to 309.  Thanks for the help!

**Comment by Alys** [comment]
No worries! Thanks for letting us know it's working!
