### ISSUE TITLE
Overflow issue with party

### ISSUE THREAD

**Issue by daveflanagan-fi** [HabitRPG/habitica#6801]
I'm not sure if this has already been submitted, but...
When the last person in a party has a mount it makes a horizontal scrollbar appear in Firefox, not a huge problem but it looks bad.

I would recommend adding overflow: hidden to the .herobox-wrap css class as a quick fix

![capture](https://cloud.githubusercontent.com/assets/7560572/13458262/0d7f4e38-e075-11e5-84c9-b55d32e35a7f.PNG)

**Comment by Alys** [comment]
The scroll bar is actually intentional to allow you to see all of your party when there are more members than will fit on the page. For example:

![screen shot 2016-03-02 at 9 18 08 pm](https://cloud.githubusercontent.com/assets/1495809/13459001/6ce2c782-e0bc-11e5-97c3-4ed2a739b554.png)

With only five people in your party, you might find that the scroll bar disappears if you're able to make your browser window slightly larger.
