### ISSUE TITLE
Received eggs are not removed when task is un-done

### ISSUE THREAD

**Issue by Quelklef** [HabitRPG/habitica#6807]
A finished a daily, got an egg from it, and then "un-finished" the task. I did not lose the egg, and by spamming finish / unfinish, I was able to collect an extra 3 eggs.

User ID: fc7a367f-d6f0-4a20-9d4c-b0b82bdb2d83
OS: Windows
Browser: Google Chrome version 48.0.2564.116 m
JS Errors: Unknown (changed pages before looking)

Would love it if a moderator would set my Panda Cub Egg count to 1, instead of 4, but it's not a huge issue.

**Comment by Quelklef** [comment]
Oh, shoot! I didn't add any labels! This is a bug. I'll put that in the title, at least for now.

**Comment by Alys** [comment]
This is intentional, rather than a bug. Please see https://github.com/HabitRPG/habitrpg/issues/4626 for details.

We actually don't use the [BUG] label in the issue titles here. :)  GitHub is used almost exclusively for bugs, so there's no real point in labelling each one.

You can get rid of the drops easily if you want to! Just go to Inventory > Market and sell them for gold, and then get rid of the gold with a custom reward or Settings > Site > Fix Character Values.

**Comment by Quelklef** [comment]
Okay, thank you!
