### ISSUE TITLE
Delete button doesn't work if disable confirmation alert window

### ISSUE THREAD

**Issue by Pteroto** [HabitRPG/habitica#6814]
If you disable the confirmation alert window when delete a task, the delete button doesn't work

**Comment by Alys** [comment]
This is deliberate; we don't let a task be deleted without a confirmation step because there's no way to undelete a task.

We're planning to change the confirmation process to use a custom popup that is impossible to disable.

In the meantime, anyone who disables the popup can get it back by closing all browser windows and reopening them (it's a browser setting, not a Habitica setting).
