### ISSUE TITLE
Finned Coral armor disappeared from inventory

### ISSUE THREAD

**Issue by d-watkins** [HabitRPG/habitica#6826]
Hi,

My group recently completed the Dilatory Distress quest, and all participants received the Finned Coral Armor, however for one group member, the armor has now disappeared.

Group ID: 639450f6-0153-482b-88bb-e081cf92461d
User ID: 33b3ece9-a38f-4847-86f7-03abbe2f6c2d

Thanks,

**Comment by Alys** [comment]
The armor is shown as being available for that player to buy in their Rewards column, which typically happens when the player's health drops to zero from doing too many negative Habits, or missing too many Dailies, or being given damage by a quest boss. The result of health dropping to zero is that you lose a level, all your gold, and one piece of equipment. However you can always buy the equipment back.

If the player feels that their health loss and the resulting other losses were unfair, they can go to Settings -> Site -> Fix Character Values to restore their level and gold, and to give themself enough extra gold to buy back the armor. "Settings" is the gear-shaped icon on the top right of the website.  

You're welcome to reply if you have any questions!
