### ISSUE TITLE
All dropdown menus open upon reload

### ISSUE THREAD

**Issue by Jathay** [HabitRPG/habitica#6827]
Was experiencing errors with the sprite images, so I reloaded the page only to have the task page open with all of the dropdown menus open, my avatar is both a snowman and a sea star, two NPC/mod announcement heads at the top, and none of the links work when I click on them. Reloading the page doesn't help, I've already cleared all browsing data in chrome and the issue is still there, as well as in firefox.

![image](https://cloud.githubusercontent.com/assets/17188442/13547935/5f92e642-e2b1-11e5-8e4a-3686ce91b7b0.png)

**Comment by ltorroba** [comment]
I have encountered that issue a few times, both in production and the local development copy, but it always went away after a page refresh. Seems like the website is not parsing any of the variable fields in `website/views/shared/headers/menu.jade`. 

Quite a few weird bugs have come up due to recent server changes. Could this be one of them, @Alys?

**Comment by yakryder** [comment]
I also got this bug just a minute ago after registering a new account in Chrome. Although as Jathay's experience suggests, the overwhelming majority of the links didn't work, I was able to open at least two in a new window. One of them was the FAQ. Hope that additional information can prove useful - if not, just that I've seen the same bug

**Comment by yakryder** [comment]
and for me it does appear to have gone away after a refresh, at least for the moment

**Comment by colwem** [comment]
This looks like the same issue as #6820.  I've been having this issue too this morning and to me it looks like it's just caused by a lot of **404 Not Found** errors when requesting resources like the spritesheets and js files.

**Comment by ltorroba** [comment]
I just got this error again. Looked at the console and this came up:

`Failed to load resource: the server responded with a status of 503 (Service Unavailable: Back-end server is at capacity)` for the resource `/app-2584cc1c.js`.

Prior to this, I was getting three other problems (all started this morning):
a) I reloaded/accessed the page and was served a blank page;
b) I reloaded/accessed the page and was served only the HTML, with no CSS styles;
c) I reloaded/accessed the page and the page loaded, but upon trying to add a To-Do (and possibly other actions) I got "Yikes!" error modal.

I don't know much about the backend, but perhaps this error is indeed due to the server getting overloaded (I saw some mentions of it before).

**Comment by Alys** [comment]
@zesme We've just restarted the server so that should have fixed it. Please reload the site. If it's still looking wrong, log out of Habitica. If you can't get to the logout button, you can use the button at https://habitica.com/static/clear-browser-data - it will log you out. You can log back in as soon as you've logged out. Let us know if it's still broken after that.

**Comment by ltorroba** [comment]
@Alys Reloaded the page and it's perfectly fine now, without the need to logout and back in. Tried some basic interactions and seems like the server is recording them just fine. I'll let you know if something out of the ordinary jumps out.
