### ISSUE TITLE
Fractional HP Error

### ISSUE THREAD

**Issue by MattALevine** [HabitRPG/habitica#6831]
I clicked on a minus sign for a green habit and a blurb saying I lost .2 HP popped up, and then the website failed to update it, giving me an error message. I've reloaded 2-3 times and it still gives me the same message, and now I can't do anything. Here's a screenshot of my account page:
![q](https://cloud.githubusercontent.com/assets/17689788/13555962/5c96afb4-e39c-11e5-8972-f2f34eefc7f2.PNG)

**Comment by MattALevine** [comment]
Update: my account is now usable again: but the bug most likely still exists. For anyone with this problem, zoom out to 10% or such until you can access the log out button (normally hidden behind the error message). When you log back in everything will be fixed (but I don't know if the change has been undone)

**Comment by Alys** [comment]
@MattALevine This is an example of the bug reported at https://github.com/HabitRPG/habitrpg/issues/6700 and it won't have been specific to losing HP. I'm going to close this issue now since we're tracking the problem in the other one.

However your trick to reach the logout button is very clever! I haven't seen or thought of that before! I've added it to the instructions at the top of that other issue. Thank you for mentioning it!

**Comment by citrusella** [comment]
Am I the only one who can click the error bubble to get it to disappear? 0_o (I remember being able to do this, the same that I can click any of the other status bubbles to shoo them away.)

**Comment by Alys** [comment]
@citrusella Huh. I never realised that either! That's a good way of getting access to the logout button, but if you're not planning to log out, it is highly recommended that you reload the site, even if the message disappears, otherwise your actions after the error appears might not be recorded permanently.

**Comment by citrusella** [comment]
Yeah, I usually reload, I just clicked in the vicinity of the error message one time on accident and realized it worked like other bubbles. (Come to think of it, I don't usually click on the standard bubbles either unless they're covering something I need to use at a given point... which doesn't normally happen.)
