### ISSUE TITLE
Quest Abandoned

### ISSUE THREAD

**Issue by DeweyReadmore** [HabitRPG/habitica#6835]
I realize that this isn't a bug, and I'm sorry to trouble you, but the wiki recommended that I come here for advice. Our party has a player who has sent out invitations for a quest and, despite repeated PMs asking to start the quest, has been nonresponsive. They have been logging in regularly, but have not taken any action or responded to PMs or messages on the party page. We have many players currently resting or inactive, so I don't foresee a way out of this soon. Any assistance you can give would be much appreciated. Thanks!

My user ID: ac2fd2a7-ab57-4fd9-8512-99d526544e40
Our group ID:  c813cbe4-8791-4c6e-8e44-1ece4994a6d8

I realize that these sorts of issues do happen more frequently with larger parties, and I will certainly weed the ranks to prevent future recurrences so that I won't have to trouble you again, but, in this case, we have players resting in the inn and others who simply have been inactive only for a short time and we're still holding out hope that they'll return. Is there anything I can do to solve this?

**Comment by Alys** [comment]
@DeweyReadmore I've changed the quest leader to you so you can now start the quest, or cancel it if you prefer. Reload the party page if you don't see the begin and abort buttons. You'll remain as the quest leader after it's started, so you can abort it later too, if needed.

The original quest leader has not lost their quest scroll. (Also, your account's counter for this quest scroll won't become negative; don't worry about this if you don't know what it means.)

Unrelated to that:

If you want me to, I can remove from your party all players who have not logged in to Habitica before a specific date of your chosing. E.g, everyone who's been inactive for a month or more.

If you'd like that, send me a personal message in Habitica so that I can confirm that it really is the party leader who wants it done. Sorry about that, but it could be a big change for the party so I do need the extra confirmation. :)
