### ISSUE TITLE
Suggestion: Provide 'Full API' access to mark tasks up and down.

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#684]
Currently (at least according to the documentation) the only way to mark tasks as up/down is via the "extensions/scripts" API. This uses a different method of authentication, different path, and different calling method than the 'full' API.  The result is that clients (at least mine) have to implement the basics twice.

Proposed solution:

Add `/api/v1/user/task/:id/up` and `/api/v1/user/task/:id/down`. Since these are changing data, they should probably be POST requests, even though the body of the post is likely to be empty.

Ideally these return HP/XP/GP deltas as well as current HP/XP/GP, so clients can easily update their displays.  Any other info being returned is gravy. :)

(Also, if I _shouldn't_ tag my own tickets with API/suggestion tags, let me know!)

**Comment by switz** [comment]
Yes. I'll handle this tomorrow. Thanks for the suggestion.

**Comment by ruddfawcett** [comment]
:+1:

**Comment by ghost** [comment]
Why have the separate extensions/scripts API anyway, as it pretty much needs the same data as the regular API?

**Comment by ruddfawcett** [comment]
@Xeross

It was used before there was a full API in the Chrome extension.

**Comment by lefnire** [comment]
because it's just up/down scoring - a quick requirement needed by the majority of API consumers (like the chrome extension, pomodoro, Anki, etc). Otherwise you'd have to do the following:
- `GET /user`, `GET /user/tasks/taskId`
- If task doesn't exist, `POST /user/tasks` to create it
- Update user stats & task (the client has to know the algorithms)
- `PUT /user`, `PUT /user/tasks/:taskId`

We definitely want to keep the extension API. When a full application is being developed, like the mobile app or habitrpg-ncurses, the "full API" should be used, and not the extension API (they probably shouldn't both be used by the same app). But for quickies, the "extension API" is preferred.

**Comment by lefnire** [comment]
But @pfenwick is right, we need consistent routes

**Comment by switz** [comment]
Okay, I built this out with specs. We actually already had a similar route in.

`/api/v1/user/tasks/:taskId/:direction` was already in there. I left it in for now, but created
`/api/v1/user/task/:taskId/:direction` to be more consistent with our other routes. If you're using `tasks`, please update your routes to `task`. I'll let you know when it's live.

Here's what the new route returns: `{ gp: 1, exp: 7.5, lvl: 1, hp: 50, delta: 1 }` – Tyler, how can we figure out the health/exp after the delta, since that's all client-side.

**Comment by pjf** [comment]
@switz : Oh! There was already a route in there? I must have missed that!

I'll add it to WebService::HabitRPG and do some testing.  :)

**Comment by pjf** [comment]
@switz: Should I be POSTing or GETting /api/v1/user/task/:taskId/:direction?

**Comment by switz** [comment]
POST to `tasks`. The new route isn't on production yet. But keep in mind it'll be deprecated soon in favor of `task`.  

Soon to be deprecated (but only available route now:)  - `/api/v1/user/tasks/:taskId/:direction`

New, not yet live  - `/api/v1/user/task/:taskId/:direction`

**Comment by pjf** [comment]
Just successfully used the old route, thank you! :)

Updating the API docs now.

**Comment by pjf** [comment]
I've noticed the 'full API' route will _add_ a habit if it does not already exist. I'm happy with that happening in the quick API (it makes writing extensions super-easy), but for the full API it seems to invite the accidental creation of habits.

If it is a feature, can we have an option or alternative route for 'update this task, but said task MUST exist'?

**Comment by pjf** [comment]
There might be a bug in my code that I'm missing, but right now it looks like /up'ing a task using the full API does _not_ mark it as complete if it's a daily.  Can open this as a separate bug if you like.

**Comment by switz** [comment]
That route is for habits only now. I'm going to extend it out so it supports completing a daily. Would you like it to use `up` and `down` or `check` and `uncheck`. I think the latter might be clearer.

**Comment by pjf** [comment]
`up` and `down`, most definitely. From an API consumer's standpoint this means I can mark a task as 'done' and not care if it's a todo, a habit, or a daily.

I'd even extend `up` to meaning 'buy this reward' when used on a reward (and `down` would always be an error).

**Comment by ghost** [comment]
To be honest I'd rather have separate endpoints on the API for habits, dailies, todos and rewards, because
1. they're different resources from a user standpoint, even though they might have some overlap
2. They do have different behaviours and you'd be setting different things for a daily or a habit, etc.

**Comment by pjf** [comment]
If we do end up with different endpoints, then i'd rather them be `/user/habit/:id/up` and /user/todo/:id/done`, etc.  Ie, not lumping them all under`/task`.

**Comment by ghost** [comment]
Probably not even up/down for a habit through the full API, as a habit already has an up/down setting attached to it, so merely `/user/habit/:id/trigger` or something like that.

**Comment by pjf** [comment]
@xeross: Some habits can be both up and down.  Eg: `down` means I drank a soda, and `up` means I had a glass of healthy water.

**Comment by ghost** [comment]
@pjf ah ok good point, and then return a 403 or something for the ones that don't have the up or down you're trying to call?

**Comment by switz** [comment]
For now, we're going to leave each type as one endpoint. In the future (see: `v2`), we may move towards a more specific API with individual routes. I'm implementing `up` and `down` for dailies now.
