### ISSUE TITLE
Streaks Erased Randomly, 'day' won't turn over

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6850]
6ce147e7-03b9-4b29-b343-a3a05dc05b50
I check off dailies in the evening, and overnight the 'day' clock won't reset properly for a new day. The following day all my streaks will have been reset to zero and Habitica treats the dailies checked off the previous day as if they were checked off on the current day, and docks me health as if all of my dailies from the previous day were missed. This has happened several times (at least 5), using a Chrome browser on a chrome OS, a chrome browser on Android OS, and the Android app.

**Comment by Alys** [comment]
I'm sorry about this! You've been affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313

There's an "Advice" section near the top which will help you recover from the unfair damage, reset the streaks, and untick your Dailies without losing XP and GP. It will also give some tips to help avoid the bug. I'm closing this now since we have it recorded there, but you are welcome to comment here if you have any questions.
