### ISSUE TITLE
Can't set Due Date in items in To Do list

### ISSUE THREAD

**Issue by LiuJoyceC** [HabitRPG/habitica#6851]
When I create a new item in my To Do list, I can't set the due date to be anything other than the current date. When I change the due date and save, it's still set to the current date when I go back in to edit it. It's making me not able to track tasks that are longer term than one day. I'm using Android 5.1.1 on a Samsung Galaxy S5.

**Comment by Alys** [comment]
This is a known bug on the Android app and will be fixed in an upcoming release.

BTW, if you notice other bugs, we'd love to hear about them, but they're not recorded in this repostitory. You can report them through the app at About > Report a Bug, or by email to mobile@habitica.com or at the Android repository at https://github.com/HabitRPG/habitrpg-android/issues . There's a summary of these methods at Help > Report a Bug from the Habitica website's menu (habitica.com).

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg-android/issues/417
