### ISSUE TITLE
Didn't receive gems that were purchased

### ISSUE THREAD

**Issue by MarkTangoKilo** [HabitRPG/habitica#6854]
It's in the title, however, I did receive the gifts, just no gems.

**Comment by Alys** [comment]
Because you've said that you did receive gifts, I'm wondering if you purchased a subscription, rather than gems? If so, please see this issue: https://github.com/HabitRPG/habitrpg/issues/5295 "Subscribed but did not receive gems immediately". In brief, subscriptions don't give you gems immediately but you can buy them with gold.

If however you tried to purchase gems rather than a subscription, then please forward your purchase receipt to admin@habitica.com and include your User ID (see step 6 of Help > Report a Bug from the Habitica website's menu if you don't know how to find it).

I'm going to close this now because if any action is necessary, we'll deal with it by email to protect your financial information.

**Comment by si-luetta** [comment]
Hello! I have a problem with gems too. I tried to bought gems (with help of "PayPal") two times (20 March and today). But i didn't receive them though payments were done. What should i do?

**Comment by Alys** [comment]
Hi @si-luetta Please forward your purchase receipt to admin@habitica.com and include
your User ID. To learn how to find your User ID on website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu).

**Comment by si-luetta** [comment]
@Alys , thank you!
