### ISSUE TITLE
Quest drops not showing as notifications

### ISSUE THREAD

**Issue by evae2** [HabitRPG/habitica#6856]
I am on the collection quest "Attack of the Mundane, Part 1: Dish Disaster!"

I've noticed that while the quest and the Official User Data Display Tool will say that I have found (x) bars of soap, I never see the soap appear as a notification when I tick off a habit/daily/to-do (but I do still see normal eggs/potions/food drops). This has happened for two days (including today) for both the users below:

User ID 1 = 8ae9701c-ddb2-4274-ad24-84dfe38efee4
User ID 2 = 5b95af34-7c29-4ba4-a6a3-46288f36432b

**Comment by Alys** [comment]
With the current design of Habitica, quest drops aren't intended to be shown as notifications, so this is expected behaviour rather than a bug. 

If you'd like to make a feature request for quest drop notifications, go to Help > Request a Feature from the Habitica website's menu. That will take you to our Trello board, to the card that gives instructions for how to make feature requests. You'll find a card on the list there about Quests (the name of the card will start with that) and you can write your suggestion on that card.

**Comment by evae2** [comment]
Thanks Alys. This text in the party confused me: "Quest items drop just like normal items; however, you won't see the drops until the next day..." - I guess the drop _mechanism_ is like normal items but just without the notification (which is how I experience drops, so what I expected). 

I will make a feature request but in the meantime a small text adjustment would be almost as good: "Quest items **may** drop just like normal items; however, **you won't see a notification. You can check how many quest drops occured the next day on this page**..."
