### ISSUE TITLE
Damage to boss does not register if party member does not visit party chat screen that day

### ISSUE THREAD

**Issue by azraelblue** [HabitRPG/habitica#6857]
Party ID: d3383e15-8aef-45fb-96f6-009f4fc223ec
My user ID: 4b4f2944-60a5-4a6f-a0cb-f8e4445245ac

Everyone in our group has their cron set around midnight-2 am. However, damage is only applied to the boss (according the party chat screen) at the time the user visit the party chat screen. I'm not sure if this is by design or not. 

But the bigger problem is that if the user does not specifically visit the party chat screen, they do no damage to the boss (and the boss does no damage to us for their undone tasks) at all for that day. 
It almost acts like anyone who does not visit the party chat page is in the inn. 
Note: this occurs when we are NOT in the inn.

**Comment by ltorroba** [comment]
Are you sure the the damage is applied _only_ when the user accesses the party chat? As far as I know, the cron for applying/receiving damage should be triggered the first time the user reloads the page _after_ their set cron time. So if you a member does not access the website for multiple days, damage will not be calculated, although upon reloading the page the cron for all missed days should be triggered.

In order to confirm this behaviour, ask someone to simply reload their tasks page after the cron time, while another user checks the party chat to see if the damage has been dealt accordingly.

[More information about how Habitica's cron works here.](http://habitica.wikia.com/wiki/Cron)

**Comment by azraelblue** [comment]
So would interacting with the mobile app not be sufficient to trigger boss calculations? My current understanding of the behvaior I'm seeing is that just checking off tasks in the mobile app is not causing the boss cron to be triggered.

**Comment by ltorroba** [comment]
Sorry, I thought you were talking about the web app. In that case I'm afraid I am not quite sure, maybe open an issue in the [mobile app repository](https://github.com/HabitRPG/habitrpg-android)?

**Comment by azraelblue** [comment]
I will attempt to trigger the boss calculations from the mobile app(checking off a task), the web app (checking off a task), and then by visiting the party page. If it works from the web app, but not the mobile, I will close this issue and reopen there. 
Since the rest of the Cron activities (habit colors, dailies ungreyed, etc) seemed to be working for people who just use the app, it didn't occur to me that this might be specifically a mobile app issue. I will get back to you.
