### ISSUE TITLE
JerseyEmerald's cron problem

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitica#6862]
_edit by admin:_

**This issue is specifically for discussing problems that JerseyEmerald has been having with cron. If any other players have been having similar problems, please do not comment here but instead create a new issue.**

---

I came online at 12:30 am 
I noticed my dailes didn't reset
I verified cron set for 12 am
I went to data display tool
It showed I had 43 undone dailes (they were still gray in  TASK  menu)
I exited out of  DATA display tool
Going back to my task
A msg flashed on my screen
-4000 coins
-1000 experience 
-2 mana
It disappeared before I could get a screen shot
My dailies  were all reset
I know it's odd, for the past few days, no matter what I was working on in Habitica,  I would get random messages
-3 gold, or -26 mana,  it's random
Issues with using my armoire,  where it would take my coins, but I wouldn't get anything
I was using mobile browser thru Chrome
My id is 29c5340b-d150-4347-862c-fec571a18b8a

**Comment by Alys** [comment]
This is the bug I mentioned earlier : https://github.com/HabitRPG/habitrpg/issues/4313
See the "Advice" section near the top for how to recover from the unfair damage and how to try to avoid the bug.

Whenever the Habitica website shows Dailies marked as completed, but the Data Display Tool says they are not completed, it means that your browser hasn't synced the information from the Habitica website to Habitica's server. Since this is happening to you often, it's probably worth your time to check this each evening just before you stop using Habitica for the day -- see point 4 in the Advice section.

Comment here if you have questions about that.

**Comment by JerseyEmerald** [comment]
I didn't loose any hp, just my gold and experience points...I check my dailes every night since my previous problem,  through the data display tool, it showed zero last night before I left. I make sure I monitor this every day.  That's a big loss of mana and gold  but I do know how to correct it. The past few days I would loose  mana/gold throughout my day which is very odd.

**Comment by Alys** [comment]
When you lose all your gold and some experience points, it means that your health had dropped to zero and your avatar had died.

Last night before midnight, you checked your Dailies on the Data Display Tool and they were all marked as completed? Can you tell me what time you checked them?

**Comment by JerseyEmerald** [comment]
That's the thing, my hp didn't change, I didn't die, I'm still level 74
Yes I checked it at 11pm

**Comment by JerseyEmerald** [comment]
![screenshot_20160311-005659](https://cloud.githubusercontent.com/assets/17463902/13702593/b4879d54-e75d-11e5-872d-41ed912aab1d.png)

**Comment by JerseyEmerald** [comment]
I left the website and preceeded to the mobile app to see if I could capture that message again, but it didn't work but this is how it looked

**Comment by Alys** [comment]
I've been capturing regular data from your account (Dailies completion status, health, etc - nothing private and no task names) however my laptop was offline while this latest problem happened because I had to take it to work. Timing. :-/  

The next time anything like this happens, please describe it again in this issue (don't create a new one - keeping it all in one issue will help us track this problem). I'm about to rename this issue to put your name in the title, because I want to avoid having other people report similar problems here which could confuse the investigation into your bug.

I'm sorry about this - I realise it must be annoying and frustrating for you!

**Comment by JerseyEmerald** [comment]
I truly appreciate your time and effort.
Quite the contrary,  this problem is very interesting and has the wheels in my mind turning as to what could cause a glitch like this.  It's very interesting,  and I'm a big computer geek and have worked for a support Center as a computer  analyst.  So no worries there☺☺

**Comment by Alys** [comment]
Well that's good to know! Thank you for telling us. :)

Regarding these points:
"**for the past few days, no matter what I was working on in Habitica, I would get random messages
-3 gold, or -26 mana, it's random
Issues with using my armoire, where it would take my coins, but I wouldn't get anything**"
What's happening there is similar to the other problems, but on a smaller scale. Your browser is recording small actions such as marking a few tasks as completed and is showing you the gold, mana, etc that you gain from those tasks, but while it's doing that, it's not sending that data to the server for permanent storage. Later, when it does sync with the server, the data that was only in the browser is overwritten by the data that the server has, and so your earnings of gold, mana, etc are reversed. The site shows you this by those messages containing negative values. 

For the Armoire, it's possible that you're receiving nothing, but I think it's more likely that the Armoire is giving you something different than what it tells you you got. E.g., it will tell you that you received a certain piece of equipment but really it gave you food or XP, or a different piece of equipment. That bug is described at https://github.com/HabitRPG/habitrpg/issues/5376. It is expected to happen much more often when syncing errors occur (the bug happens when your browser and the server have different data), so I'm not surprised that it's happening to you.

It should be possible to reduce the frequency of these problems by reloading the website regularly using your browser's refresh or reload button. Even better would be logging out of Habitica often (you could log back in immediately if you wanted to) but that would be a lot more annoying! Reloading would encourage your browser to sync with the server. Logging out would clear any local data that hadn't been synced.

At the very least, before you use the Armoire, it would be worth reloading, because that means you'd be more likely to see the correct notification for the item you have actually been given.

**Comment by JerseyEmerald** [comment]
Ok thank you very much,  I will do just that!!

**Comment by JerseyEmerald** [comment]
Update: I logged out on my mobile device from the app and browser, I waited and hour (it took that long to make toast, my 2 fur babies had a different. Plan lol)
I rebooted my phone ( why not, it couldn't hurt right)
I updated my Chrome browser, again, for 3rd time in 2 weeks  (how many times can Google make changes to their browser in 2 weeks.... seriously)
I logged back in on the mobile Web browser
I decided to see what I could get from the enchanted Armoire 
Started with 1.7 K gold
Tapped it 7 times
Ended with   956 gold. Huh ( is the Armoire charging sales tax??)

**Comment by JerseyEmerald** [comment]
I logged out of my mobile app and will be using the mobile browser.  When I need the mobile app I will log out of the browser so neither one is open at the same time..

**Comment by JerseyEmerald** [comment]
It happened again,  I logged out at after midnight
My mobile app was signed out 
I verified all dailes were completed,  in gray, I Tapped the ALL Button to make sure
I took a screen shot of my points,gold,health 
I logged in around 1:30am, I wanted to create a to do list for things on my mind
Then I got the msgs, you lost your health and life..and other things..
I was too mad to read it all
I saw the data display tool, it showed none of my were completed,  I know I checked them off before bed
Anyway, I reentered All my info and streaks on 52 dailes that I have
I think this time I lost a piece of equipment,  it was 
In my rewards column
So I purchased it back

**Comment by Alys** [comment]
Ah, I'm sorry about that. :(  

You said you logged out after midnight - is that correct, not a typo? Did you take any other actions on the site after midnight? The reason I ask that your day start time is midnight, so if you were using the site or app after midnight, cron should have run then.

When you checked off your Dailies before bed, did you look at the Data Display Tool then to confirm that they were all checked off? Or did you only look at the DDT after you'd seen the health and life loss?

**Comment by JerseyEmerald** [comment]
No I didn't check the DDT,  first time since this all happened 
I just went to my task screen and made sure they were checked off, before midnight then I went to my profile page, then to my party chat room
From there I signed off

**Comment by Alys** [comment]
So you logged off before midnight - is that right?

**Comment by JerseyEmerald** [comment]
No I logged off at 12:19 am, my dailes were still gray, I took a screen shot of the top page so I know what info was there in case I needed it, and I did....

**Comment by JerseyEmerald** [comment]
![screenshot_20160314-001949](https://cloud.githubusercontent.com/assets/17463902/13741770/523ee9ec-e9ae-11e5-9be7-a6e999cca924.png)

**Comment by Alys** [comment]
Okay, there's definitely something odd going on if you were able to use the site after midnight without triggering cron. 

Can you tell me what timezone you are in? Please include both the local name for the timezone and the numerical designation if you know it (e.g., UTC+10 or UTC-7).

Please also look at the "Advice" section in this issue again: https://github.com/HabitRPG/habitrpg/issues/4313
Even if that isn't the bug you're experiencing, point 4 in the Advice section will likely help you. It describes how you can use the Data Display Tool before midnight to check that your Dailies really are completed. Even if the website seems to be showing you that they are completed, they might not be as far as Habitica's server is concerned, and it's the server that controls cron (this can happen when your browser is unable to send data to the server). So what I recommend you do each night before midnight is look on the website to see if all your Dailies are completed and then still BEFORE midnight (that's important!) go to the Data Display Tool and look in the "Dailies Incomplete" section. If that section is showing you something different than that website, it's likely that the Habitica website is wrong.

**Comment by JerseyEmerald** [comment]
On the Web site it shows cron 12am 
HOWEVER, further down it shows  UTC -4
This was always UTC -5
I live in Indiana, East coast time NY
I have a new phone so I'll look into the time zone setting on it as well
I'll do that, check DDT before midnight

**Comment by JerseyEmerald** [comment]
It's eastern GET-04:00 Eastern Daylight time
DST was this weekend

**Comment by Alys** [comment]
We tracked down a problem related to the DST change that can cause two crons in one day if the website hasn't been reloaded or logged out of since the DST change occurred. That bug has probably disappeared for you now, but can you please reload the website to make sure of that?

**Comment by JerseyEmerald** [comment]
I've signed out of it 3 times today, on website 
My app was not logged into at all
But if I go to my mobile app I log out of the Web site

**Comment by Alys** [comment]
@JerseyEmerald Some of the problems you've been having definitely seem to be from your browser not syncing with the server correctly, but you've also been suffering from a bug in the Android app that we've just found and fixed (fix will be on the Google Play Store soon).

This comment explains it and gives a workaround to use until the new app version is available: https://github.com/HabitRPG/habitrpg/issues/6879#issuecomment-197559252

I believe we don't need more information from you about this bug, but you are very welcome to post here again if you have questions, or if anything else seems to be going wrong. I do recommend keeping using the Data Display Tool just before bed to keep on checking that sync problems haven't happened. I'm sorry it's been so annoying for you!

**Comment by JerseyEmerald** [comment]
Ok I've been only using the website except when I need to purchase gems or if I need to post comments in my party .. but I'll stay of the mobile app until the update is out, thank you very much!!
