### ISSUE TITLE
Should not be able to recast Chilling Frost and Stealth skill / spell that gives no additional benefit

### ISSUE THREAD

**Issue by cdouglass** [HabitRPG/habitica#6867]
Casting Chilling Frost (which prevents streaks from resetting on the next cron) costs 40 mana each time, but there is no benefit from doing so twice in one day. There is also no indicator of whether it has already been cast today, so it's easy to forget and cast it extra times, spending mana for no purpose. Proposed solutions: either it should only be possible to cast this spell once per day or there should be some indicator of whether it's already been cast.

My user id: be3421a9-9f57-4ed1-8804-7b1ba8702dd0

---

_edit by Alys, 2018-09-16:_

This is happening again for both Chilling Frost and Stealth. It was originally fixed (and the fix was working) in https://github.com/HabitRPG/habitica/pull/7110 / https://github.com/HabitRPG/habitica/commit/b97d7cc9f989cd8089d3a0883933dbe80faade6a so possibly some of that code has been accidentally removed, or something new has caused it to stop working. Regardless, looking at the previous fix is probably a good way to start investigating this.

**Comment by Alys** [comment]
You can see that it's been cast if you look on the User --> Stats page, where it will say "Streaks Frozen" if you've cast it. The Data > Data Display Tool also tells you in the "Skills and Buffs" section. However both of those are FAR from obvious! 

You're right that it should not be possible to cast it more than once per day. After you've cast it:
- [ ] the skill should be greyed out (or some other visual effect to show it's no longer available)
- [ ] both hovering over it and clicking on it should give you a message saying that you've already cast it, your streaks are already frozen, and there's no need to cast it again.

That could be done on the website's user interface as a purely client-side change. It could also be done separately on the mobile apps, although probably not for some time because the apps have greater priorities. Ideally it should also be done by modifying the API so that it's impossible to cast the skill more than once per day, however that API change cannot be done until version 3 of the API is released some time in the future (there's a change freeze on non-essential API changes until then).

I'm going to leave this issue as is for a couple of days, and then if there's no complaints, I'm going to mark it as "help welcome now" for ONLY the change to the website's user interface. I believe it should be possible to make that client-side change with no API changes. If that goes ahead, we'd also mention this to the app developers as a possible future feature request.

It would also be good to do something similar for the Rogue's Stealth skill. You can see how many Dailies are hidden from User > Stats and the Data Display Tool, but it would be nice to have that visible on hover on the skill itself, and maybe have the skill greyed-out when there's no point casting it again (more complex to work out though). But that can be discussed later when we see how the Chilling Frost proposal is received. :)

**Comment by cdouglass** [comment]
Anyone mind if I try to create a fix for this?

**Comment by Alys** [comment]
Please do! Comment here if you run into trouble or would like advice. If you have partially completed code that you'd like us to look at, you're welcome to submit an incomplete pull request.

**Comment by cdouglass** [comment]
Does anyone have a working process for setting the site up locally on Vagrant? I'm running up against something like #6499.

**Comment by cdouglass** [comment]
Here are partial npm-debug.log files from my first and second times running `npm install` according to the Vagrant instructions in http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally. For some reason Github won't let me upload them even as .txt files.

First run:

```
3345 silly lifecycle npmconf@2.1.1~install: no script for install, continuing

3346 silly install phantomjs@1.9.19 /vagrant/node_modules/.staging/phantomjs-d95424a8

3347 info lifecycle phantomjs@1.9.19~install: phantomjs@1.9.19

3348 verbose lifecycle phantomjs@1.9.19~install: unsafe-perm in lifecycle true

3349 verbose lifecycle phantomjs@1.9.19~install: PATH: /home/vagrant/.nvm/versions/node/v4.3.1/lib/node_modules/npm/bin/node-gyp-bin:/vagrant/node_modules/phantomjs/node_modules/.bin:/vagrant/node_modules/.bin:/home/vagrant/.nvm/versions/node/v4.3.1/bin:/home/vagrant/.nvm/versions/node/v4.3.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/vagrant_ruby/bin

3350 verbose lifecycle phantomjs@1.9.19~install: CWD: /vagrant/node_modules/phantomjs

3351 silly lifecycle phantomjs@1.9.19~install: Args: [ '-c', 'node install.js' ]

3352 silly lifecycle phantomjs@1.9.19~install: Returned: code: 1  signal: null

3353 info lifecycle phantomjs@1.9.19~install: Failed to exec install script

3354 verbose unlock done using /home/vagrant/.npm/_locks/staging-db29c5a769436947.lock for /vagrant/node_modules/.staging

3355 silly rollbackFailedOptional Starting

3356 silly rollbackFailedOptional Finishing

3357 silly runTopLevelLifecycles Starting

3358 silly runTopLevelLifecycles Finishing

3359 silly install printInstalled

3360 warn optional Skipping failed optional dependency /chokidar/fsevents:

3361 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.8

3362 verbose stack Error: phantomjs@1.9.19 install: `node install.js`

3362 verbose stack Exit status 1

3362 verbose stack     at EventEmitter.<anonymous> (/home/vagrant/.nvm/versions/node/v4.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)

3362 verbose stack     at emitTwo (events.js:87:13)

3362 verbose stack     at EventEmitter.emit (events.js:172:7)

3362 verbose stack     at ChildProcess.<anonymous> (/home/vagrant/.nvm/versions/node/v4.3.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)

3362 verbose stack     at emitTwo (events.js:87:13)

3362 verbose stack     at ChildProcess.emit (events.js:172:7)

3362 verbose stack     at maybeClose (internal/child_process.js:821:16)

3362 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

3363 verbose pkgid phantomjs@1.9.19

3364 verbose cwd /vagrant

3365 error Linux 3.2.0-23-generic

3366 error argv "/home/vagrant/.nvm/versions/node/v4.3.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.3.1/bin/npm" "install"

3367 error node v4.3.1

3368 error npm  v3.8.2

3369 error code ELIFECYCLE

3370 error phantomjs@1.9.19 install: `node install.js`

3370 error Exit status 1

3371 error Failed at the phantomjs@1.9.19 install script 'node install.js'.

3371 error Make sure you have the latest version of node.js and npm installed.

3371 error If you do, this is most likely a problem with the phantomjs package,

3371 error not with npm itself.

3371 error Tell the author that this fails on your system:

3371 error     node install.js

3371 error You can get information on how to open an issue for this project with:

3371 error     npm bugs phantomjs

3371 error Or if that isn't available, you can get their info via:

3371 error     npm owner ls phantomjs

3371 error There is likely additional logging output above.

3372 verbose exit [ 1, true ]
```

Second run:

```
2945 silly install npmconf@2.1.1 /vagrant/node_modules/.staging/npmconf-08d028d3

2946 info lifecycle npmconf@2.1.1~install: npmconf@2.1.1

2947 silly lifecycle npmconf@2.1.1~install: no script for install, continuing

2948 silly install phantomjs@1.9.19 /vagrant/node_modules/.staging/phantomjs-d95424a8

2949 info lifecycle phantomjs@1.9.19~install: phantomjs@1.9.19

2950 verbose lifecycle phantomjs@1.9.19~install: unsafe-perm in lifecycle true

2951 verbose lifecycle phantomjs@1.9.19~install: PATH: /home/vagrant/.nvm/versions/node/v4.3.1/lib/node_modules/npm/bin/node-gyp-bin:/vagrant/node_modules/phantomjs/node_modules/.bin:/vagrant/node_modules/.bin:/home/vagrant/.nvm/versions/node/v4.3.1/bin:/home/vagrant/.nvm/versions/node/v4.3.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/vagrant_ruby/bin

2952 verbose lifecycle phantomjs@1.9.19~install: CWD: /vagrant/node_modules/phantomjs

2953 silly lifecycle phantomjs@1.9.19~install: Args: [ '-c', 'node install.js' ]

2954 silly lifecycle phantomjs@1.9.19~install: Returned: code: 1  signal: null

2955 info lifecycle phantomjs@1.9.19~install: Failed to exec install script

2956 verbose unlock done using /home/vagrant/.npm/_locks/staging-db29c5a769436947.lock for /vagrant/node_modules/.staging

2957 silly rollbackFailedOptional Starting

2958 silly rollbackFailedOptional Finishing

2959 silly runTopLevelLifecycles Starting

2960 silly runTopLevelLifecycles Finishing

2961 silly install printInstalled

2962 warn optional Skipping failed optional dependency /chokidar/fsevents:

2963 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.8

2964 verbose stack Error: phantomjs@1.9.19 install: `node install.js`

2964 verbose stack Exit status 1

2964 verbose stack     at EventEmitter.<anonymous> (/home/vagrant/.nvm/versions/node/v4.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)

2964 verbose stack     at emitTwo (events.js:87:13)

2964 verbose stack     at EventEmitter.emit (events.js:172:7)

2964 verbose stack     at ChildProcess.<anonymous> (/home/vagrant/.nvm/versions/node/v4.3.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)

2964 verbose stack     at emitTwo (events.js:87:13)

2964 verbose stack     at ChildProcess.emit (events.js:172:7)

2964 verbose stack     at maybeClose (internal/child_process.js:821:16)

2964 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

2965 verbose pkgid phantomjs@1.9.19

2966 verbose cwd /vagrant

2967 error Linux 3.2.0-23-generic

2968 error argv "/home/vagrant/.nvm/versions/node/v4.3.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.3.1/bin/npm" "install"

2969 error node v4.3.1

2970 error npm  v3.8.2

2971 error code ELIFECYCLE

2972 error phantomjs@1.9.19 install: `node install.js`

2972 error Exit status 1

2973 error Failed at the phantomjs@1.9.19 install script 'node install.js'.

2973 error Make sure you have the latest version of node.js and npm installed.

2973 error If you do, this is most likely a problem with the phantomjs package,

2973 error not with npm itself.

2973 error Tell the author that this fails on your system:

2973 error     node install.js

2973 error You can get information on how to open an issue for this project with:

2973 error     npm bugs phantomjs

2973 error Or if that isn't available, you can get their info via:

2973 error     npm owner ls phantomjs

2973 error There is likely additional logging output above.

2974 verbose exit [ 1, true ]
```

**Comment by keysmashes** [comment]
@cdouglass Are you totally set on using Vagrant to run Habit locally? I couldn't get it to work either, but getting it running on a [Cloud9](https://c9.io) container (following the Unix instructions) was pretty easy, and much of the work (like installing Node and Mongo) is actually done already!

I did have to tweak a few things to get it to work, like starting Mongo with a [specific script](https://docs.c9.io/docs/setting-up-mongodb), but you basically just follow the instructions from the third step 1 (install and set up Git). You'll probably have to run `npm install` more than once – if it errors, run it again.

**Comment by Hus274** [comment]
I noticed that no one has commented on this in a while, is this still being worked on?

**Comment by Hus274** [comment]
I spent some time looking into this as i haven't hear anything back. Would something along these lines work?

The changes here are that the button to cast the spell is disabled ( it's greyed out and it is not clickable), and the hover over text reads something along the lines of what Alys said here. This would probably still require some word crafting and distinguishing between what to say for sneak or chilling frost but the idea is pretty much the same.

What do you think?

![screenshot from 2016-04-19 17-41-25](https://cloud.githubusercontent.com/assets/17734753/14660054/3a93bbfa-0656-11e6-9b56-02894fb6f0c4.png)

**Comment by Alys** [comment]
That looks good to me!

**Comment by cdouglass** [comment]
Looks good to me too.

**Comment by Hus274** [comment]
So here's what stealth would end up looking like then: (Number of dailies is there always, the other part pops up when the number of dailies effected exceeds the users number of dailies)
![stealth](https://cloud.githubusercontent.com/assets/17734753/14694936/173fbaf6-0722-11e6-91d0-0f4437d2fadb.png)

**Comment by Hus274** [comment]
So I do have a couple questions before submitting a pull request though.
1.
In order to make the popover work with both spells and only to pop up under certain circumstances has lead me to pollute the jade file with logic like what follows:

``` javascript
  popover='{{skill.notes()}}{{k=="frost" && user.stats.buffs.streaks ? " You have already cast this today. Your streaks are frozen, and there\'s no need to cast it again." : ""}}}{{k=="stealth" ? " Number of dailies avoided: " + user.stats.buffs.stealth + "." : ""}}{{k=="stealth" && user.stats.buffs.stealth >= user.dailys.length ? " You have already avoided all your dailies, there\'s no need to cast it again." : ""}}')
```

Which is hard to read and not great practice. This makes me feel like it should be a function in the spells.js file that gets called on the spell and then decides the popover based on this logic passing in the skill. 
Do you have any thoughts on this?

2.
I would prefer if someone else could also look over the wording and what not and make sure that what's there looks good.

---

#### Unrelated To the Issue

3.
This isn't so much of a question as an observation but the stealth skill logic is not super straightforward. The description implies a sort of randomness to the number of tasks effected (some of your dailies will not cause damage) but there's no randomness in the number generation, only which daily doesn't cause damage. 

The other thing is that the most significant number in the equation is the current number of dailies. It seems weird to me that I could cast it one day with 5 dailies and cause it to miss two dailies, then add 5 more dailies the next, recast it with no other change and get 4 dailies avoided. 

I understand that it seems to be based on the concept of effecting a percentage of the dailies but it seems like the main distinction should be around the perception attribute. I would think a level 10 rogue with 100 dailies should get less dailies avoided than a level 100 rogue with 10.

Sorry for the long winded question, I was just curious if it had been discussed earlier here or if there was reasoning behind it being that way.

**Comment by Alys** [comment]
1. Not really my area of expertise but I agree with what you've said. However if we're to modify the JavaScript code, this should probably go on hold for a little while. A new version of the API is being written and the backend skills code is part of that.
2. Noted!
3. Interesting points. The current behaviour is an improvement on the previous behaviour from more than a year ago, but that doesn't mean it can't be improved further. We're collection ideas for skill improvements at https://trello.com/c/TjZc6PnC/466-skills-v3-stat-rebalancing and I've made a note there about your comment.

**Comment by Hus274** [comment]
Great, thanks Alys!

As for one, that's what I figured. If that's the case, I think it makes sense to go ahead with the front end change to improve the functionality from a user perspective and the it can be migrated to the backend when the api v3 is released. The only real difference is going to be code cleanliness and it should be pretty minor to switch it to the back end retroactively.

**Comment by Hus274** [comment]
So it doesn't look like it's currently possible to correctly grey out the rogue's skill when the number of UNCOMPLETE dailies is less than the number of dailies avoided. The current behavior is such that the popover will now display the current number of dailies avoided and will become disabled when the number of dailies avoided becomes greater than the total number of dailies. Does this seem reasonable?

**Comment by Alys** [comment]
Yes, that seems fine, at least for now. We can always tweak it later, especially if we adjust Stealth.

**Comment by Alys** [comment]
I'm reopening this because it's happening again for both Chilling Frost and Stealth. It was originally fixed (and the fix was working) in https://github.com/HabitRPG/habitica/pull/7110 / https://github.com/HabitRPG/habitica/commit/b97d7cc9f989cd8089d3a0883933dbe80faade6a so possibly some of that code has been accidentally removed, or something new has caused it to stop working. Regardless, looking at the previous fix is probably a good way to start investigating this. I'm copying this comment to the top post.

**Comment by Alys** [comment]
I'm marking this as in progress because it's looking like it will be fixed by @alexandreabeh in https://github.com/HabitRPG/habitica/pull/12255

**Comment by Alys** [comment]
This issue will be partly fixed by @alexandreabeh in #12255. As @paglias [points out](https://github.com/HabitRPG/habitica/pull/12255#pullrequestreview-421508223), that PR is for a client-side fix and we'll still need an API level fix. When that PR is merged, I'll update this issue and change it back to help wanted.

**Comment by paglias** [comment]
I'm removing the in progress label because #12255 is not going to fix this one, the tooltip will say that casting isn't necessary but it won't prevent you from casting it anyway and the cast button will not be greyed out when the spell should be disabled

**Comment by Alys** [comment]
I'm closing this because I've created two new issues that will cover the remaining items for this issue.

https://github.com/HabitRPG/habitica/issues/12361 (API - disable skill casting)
https://github.com/HabitRPG/habitica/issues/12362 (website - disable buttons)
