### ISSUE TITLE
Recurring invitation to join group without possibility to succesfully join it

### ISSUE THREAD

**Issue by CaptainInVain** [HabitRPG/habitica#6870]
Hi there,

I have been invited to a group and accepted the offer, but I am not getting fully registred as member of the group. On the group page, I keep getting a message that I am invited to the same group I already am (sort of) part of with the options to join the 'new' group (which is thus the same one) or declining the offer. Whatever option I choose, I stay in the group and the message keeps popping up.
Moreover, I am listed as a 'member' and as 'invited' at the same time. I have managed to post a message, but completing my tasks doesn't effect the current Basi-list.
I have tried to refresh the page multiple times, leave the group and then rejoin, being kicked out and then rejoin, but it all doesn't help. If I leave the group I immediately get an invitation to rejoin, whether the group leader has actually invited me or not. If I decline that invitation I get a new one, if I accept it the whole business begins all over again.
Can someone help me to succesfully join the group and get rid of the recurring invitations?

Thanks

User ID: 1b8ff2ad-47fe-40b1-b6ff-472b27649239
Group ID: c02287fb-a094-421c-a2fe-f1c2949e0aaa
Tried it with Internet Explorer and Chrome.

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/5649 . It has a "What to do if this happens to you" section at the top which should help you get rid of that problem. If it doesn't work for you or if the instructions seem incomplete or confusing, please comment on that issue (best to comment there rather than here so we can keep the conversation in one place).
