### ISSUE TITLE
Checked out of Tavern yesterday, got hit

### ISSUE THREAD

**Issue by MrAdventure** [HabitRPG/habitica#6885]
I had been checked in Sunday. I checked out Monday.  I had checked in with pretty high health, because I had used all my mana on healing. Monday, right before bed, I noticed I had been knocked down to 14 health, prior to midnight. 

I should have checked back in to make up for it, but instead was killed. 

I'm outside of the US, not sure if that and daylight savings had anything to do with it.

**Comment by librarianmage** [comment]
Were you in a quest?

**Comment by MrAdventure** [comment]
No, no quests as of yet, ever.

**Comment by librarianmage** [comment]
Hmm. Are you in a party?

**Comment by MrAdventure** [comment]
Nope, never did that either. I saw you had another issue from  daylight
savings time, perhaps that was it?

**Comment by librarianmage** [comment]
It all depends on when you logged in. Since you are outside the US, it shouldn't affect you.

**Comment by MrAdventure** [comment]
Hmmmm, well, somehow my guy died. I had healed him up to full and knew that
if level today, so that was a surprise.  It does that really matter to me,
but I wanted you to know.

**Comment by librarianmage** [comment]
Ok!

**Comment by Alys** [comment]
@MrAdventure If you yourself haven't gone through a daylight savings time change recently, then DST won't be related to this (the server's time zone doesn't ever change).

There is an issue in which that actions you take in your browser aren't always synced to the server (https://github.com/HabitRPG/habitrpg/issues/4313 ), and this can apply to resting in the inn. It can look like you're resting because your browser shows that, but if your browser hasn't told the server you're resting, then when cron runs, it doesn't know that it's not supposed to damage you. One aspect of the bug is that the actions that weren't synced to the server when they should have been can be synced later, so it is possible that your account started resting in the inn immediately after you cronned on Monday. 

That issue has an "Advice" section near the top that will help you recover from the unfair damage. It also talks about the Data Display Tool, and you can use that tool to check that you really are resting in the inn.

For the moment, I'm going to assume that this is what happened, because we see this kind of error fairly often. The next time you rest in the inn, please use the Data Display Tool to check that it worked, and then tell us if the unexpected damage happens again.

**Comment by MrAdventure** [comment]
Ok, thanks for the help.

One thing I thought of that might or might not also have to do with it,
while my phone is out of the US, when I use a browser I'm coming on on a
VPN in the US. I hadn't in a few days, so don't think that was it, but just
FYI.

**Comment by Alys** [comment]
Then yes, it probably is related to time zones. If you use Habitica on two devices that have different time zones, you'll get two or more crons each day. You can go to Settings > Site on the website to see what time zone the device has reported to Habitica (be sure to read all the instructions in the Time Zone section on that page). Please do that on your phone's browser and your PC browser and tell us what the zone is for each one.

**Comment by MrAdventure** [comment]
They both have the same time zone, I just checked, and they are the one on
the website. I think it was the previously mentioned problem.

And I think that is great that you let people fix that, it should keep the
frustration down from the occasional bug.

**Comment by Alys** [comment]
Yes, it probably was https://github.com/HabitRPG/habitrpg/issues/4313. I'm closing this, but do tell us if you have further problems that can't be explained by the information in https://github.com/HabitRPG/habitrpg/issues/4313
