### ISSUE TITLE
Party quest: "The Basi-List" won't suffer damage

### ISSUE THREAD

**Issue by RinMeow** [HabitRPG/habitica#6892]
Hello!
My party has been trying to defeat the first quest "The Basi-List" one. It's been a few days but nothing happened, it didn't recieve any damage. We've been doing everything it told us to do, like "Complete your To-Dos and Dailies to defang the monster". We completed the To-Dos and Dailies, but no damage was dealed.
The instructions also said "Each completed Daily and To-Do and each positive Habit hurts the boss.", but nothing has happened.
Are we doing something wrong?

**_My user ID: de376401-8bce-4c0b-9796-e956efb29c67
Group ID: 9715ea80-1b1c-4d80-9bcf-841d0bb60690
I tried both the Chrome browser and the Android Habitica app. In both, nothing happened either._**

**Comment by librarianmage** [comment]
How did you start the quest?

**Comment by librarianmage** [comment]
Can you also screenshot your party screen and upload it?

**Comment by crookedneighbor** [comment]
I've queried the database and it looks you you are not part of that quest. Only the user with the id `58654135-c92e-4a83-bc23-d3d87f72500e` is. Seems like that user started the quest before you pressed the accept button. 

I assume that user has also not been dealing damage? And they are _not_ resting in the inn, correct?

**Comment by Alys** [comment]
I've just gone into the database and looked for the party to investigate this further, and I've found that the quest owner had aborted the quest and restarted it and now RinMeow is a participant. 

@RinMeow when you log issues, it really helps us if you can tell us if the situation changes, especially if the problem goes away - then we know that we don't need to keep working on it for you. :) I'm closing this now, but if you have other problems with the quest, you're welcome to comment here! You can also ask for advice about using Habitica through Help > Ask a Question from the website's menu, which will often give you a very fast response since there's a lot of helpful players there.
