### ISSUE TITLE
Cron seemed to have happened twice for me?

### ISSUE THREAD

**Issue by carmenning** [HabitRPG/habitica#6899]
My custom day start is 5 am, and I woke up this morning, probably at like 5:15-5:20. Opened up the Habitica Android app, checked out how much damage I did, then went about my day.

But then at work I opened up the app again at 7:40-7:45, and then was notified I died? So I checked my party again and saw that it seemed like cron happened again...

I went through some of the recent issues and found #6885 was similar. I am in the US, though if that helps. Not sure if this was a daylight savings issue...

**Comment by carmenning** [comment]
Oh dang. I just found #6879. Sorry for the double issue!

**Comment by Alys** [comment]
That's okay. :) Sorry about the double cron!!! 

[This recent comment from mandyzhou](https://github.com/HabitRPG/habitrpg/issues/6879#issuecomment-197335721) might be extremely helpful.

Tomorrow, I recommend that you don't use Habitica until after 6am (or today change your Custom Day Start time to 4am and then tomorrow don't use Habitica until after 5am). Whether you do that or not, please tell us if you get a double cron tomorrow.

I'm going to close this issue now but please keep commenting on this one so that we can keep your experiences in one place. If anything needs to be mentioned back on the original issue, I'll copy it across.

**Comment by Alys** [comment]
Please see this new comment from me: https://github.com/HabitRPG/habitrpg/issues/6879#issuecomment-197559252

We've found and fixed the bug that was causing this but the fix isn't released yet. We don't need more information from you about this bug, but you are welcome to post again if you have questions. Please see https://github.com/HabitRPG/habitrpg/issues/6879 for all future updates - you can click the "subscribe" button in the right-hand column to get email notifications from that issue.

**Comment by carmenning** [comment]
Yay, thanks for letting me know!
