### ISSUE TITLE
Daily Cron not being counted towards current quest

### ISSUE THREAD

**Issue by IceManX2X** [HabitRPG/habitica#6906]
I'm currently doing the Golden Knight Part 1 with my group but for the last 2-3 days I have not been listed as contributing.  It is like my daily Chron is stuck.  My habits reset at 11pm each night but it doesn't show me finding any testimonials.  I've finished my dailies plus much more so the amount I should've contributed is a lot.  Please help.
User API is e01dcb6b-6239-40d1-a6e1-f3606d1109ef
Group ID: b2dd018a-078c-4837-9bf1-af48dde0a52a

**Comment by Alys** [comment]
You've already reported this at https://github.com/HabitRPG/habitrpg-android/issues/440 so please see there for the fix.

BTW, cron is spelt without the "h", which is important if you're ever searching for information about it. I've renamed this issue to remove the "h" so that it will appear in any searches we do for cron problems.
