### ISSUE TITLE
Habits tracking

### ISSUE THREAD

**Issue by thecoldest** [HabitRPG/habitica#691]
I have notice that Habits are not being track anymore. I can no longer hit progress and see the history of my progress in the Habit column. Also every day it turn yellow. When I check it it turns to green and restart to yellow the next day. My understand of this was that has you do your Habits dally the color changed to so you progress. A thought can you make it to where when you check off a Habit for 21 to 66 days (to form a Habit) it will tell you to pick another Habit to start.

**Comment by wc8** [comment]
1) _Re: issue: no habit progress visible when you click the progress button_
Is this for "only" habits or for all habits?

("Only" Habits is a nickname to refer to habits that are only either good habits or bad habits.
Example:
- ONLY: - Smoke Cigarette
- ONLY: - brush teeth
- BOTH: alternative good or bad habit: + Take the Stairs; alternatively, - take the elevator.)

2) _Re: Your support question/issue: only habits are returning to yellow the next day, rather than staying green_
[Shading for "Only" habits](https://trello.com/c/YSXfecBt) is a new feature. 
I find on a given day, if I have clicked a good habit, it will turn green. The next day it turns to yellow, but after several days of keeping up the good habit, it retains the green color.
Perhaps @MrConcept or @lefnire could explain further how this is expected to work. 

3) _Your suggestion: suggest new habit after 21-66 days_ Check out the [Mastered Habits](https://trello.com/c/1d1BqCM1) suggestion. I think that might be what you're looking for.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
