### ISSUE TITLE
Invisible Equipment 

### ISSUE THREAD

**Issue by DenisVerkhovsky** [HabitRPG/habitica#6914]
Hi!
Since yesterday all my eqipment became invisible. It's no difference whether i put on armor or helmet or even sword, my avatar stays the same.
It started when i tryed to put off all my equipment using button "Unequip Battle Gear". Than i tryed to put on sword and nothing happend. After a few tries i decided to download app (android).  It helped to pun on equipment, but it wasn't shown up.

My id: 0504765f-35a2-43c1-9a88-51c04b4e528d

P.S. Sorry for possible mistakes in my English.
Thanks!

**Comment by Alys** [comment]
You've turn on the "use costume" option but you haven't put on any costume pieces. On the website, go to Inventory > Equipment and hover over the "Battle Gear" header and the "Costume" header to see an explanation of each. 

You can either untick "Use Costume" or leave it ticked and select costume items from that side of the page.

If you'd like more information, see the wiki's [Equipment](http://habitica.wikia.com/wiki/Equipment) page ("Costumes" section), or ask at Help > Ask a Question.

You can also ask here, but Help > Ask a Question might give you assistance faster because there's many more people there. :)
