### ISSUE TITLE
An incomplete collection quest message fragment appeared during a boss quest

### ISSUE THREAD

**Issue by mgpc3** [HabitRPG/habitica#6916]
My party was doing the snail quest and everything was going fine and then this appeared in party chat:

![snail quest bug](https://cloud.githubusercontent.com/assets/5097204/13877519/1bfda1b8-ed03-11e5-8c83-9ec33f9f193e.jpg)

I think we were still about 70 HP away from defeating the boss (I keep track of our damage on a separate spreadsheet) when the "(user x) found ." message appeared, this user does not usually do that much damage in a single cron so I think it's possible that the bug caused the quest to be viewed as completed when it shouldn't have been, but I have no way to check that.

As you can see from the screeenshot, the snail quest ended and I seem to have received all the quest rewards (I assume othe party members did too). Not sure what happened.

My UUID is 8f21e403-8e3a-4d75-8824-74fe4712b2ce
The group ID for the party is dbfaff12-f77e-4635-9cab-aad256e616a7

**Comment by Alys** [comment]
Sorry about this! I will look into it and also see if similar problems can
occur in other parties.

**Comment by Alys** [comment]
This would have been a side-effect of a bug that happened a day or two ago, which caused one of your party members to have incorrect quest information for a collection quest. Because that quest ended incorrectly, which I realise must have felt very unsatisfactory after your hard work, I've given four gems to each of the players in your party to spend on another quest scroll or on anything else as you each prefer.
