### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by maryanne2001** [HabitRPG/habitica#6917]
Haven't been able to log anything last night or this morning. However, my health and streaks took a hit for the items I couldn't log last night, so that's no fun. Thankfully, my phone app didn't manage to talk to the server at all so I took screenshots of my streaks so that I can restore them later, otherwise, I wouldn't even know where to start on that either. Suggested feature given that issue: show previous streak. I've attached some screenshots of my issue. I'm very concerned that if this keeps going on, my character will die. I've gotten server errors before, several times, but usually it was just a matter of refreshing or waiting a minute or two. This one is going on for a fair bit longer.

![habiticaerror1](https://cloud.githubusercontent.com/assets/17927813/13878320/850fa5f4-ecde-11e5-916f-89da9763925f.JPG)
![healthpanelscreenshot](https://cloud.githubusercontent.com/assets/17927813/13878319/850c4a1c-ecde-11e5-88e3-d20bcc3e6868.JPG)
![screenshot_2016-03-18-07-22-47](https://cloud.githubusercontent.com/assets/17927813/13878372/ddaef78c-ecde-11e5-82e0-cb4b16552e91.png)

**Comment by cmmata** [comment]
It's the same than #6915

**Comment by Alys** [comment]
@maryanne2001 I've seen that you reported the same problem by email and that one of us responded to you there so I'm closing this issue. You don't need to report problems in both locations, and it can lead to duplicate handling (if you do want to report it twice, please explain in each place that you've done so so that we know to look for the other report to see if it's been handled there). GitHub is usually the best place for bug reports because it allows all our devs to see the problems that need to be fixed.
