### ISSUE TITLE
New class (druid)

### ISSUE THREAD

**Issue by Zemisfit** [HabitRPG/habitica#6929]
A new class of a mixture of mage and rogue where the majority of there strengths are in magic (Intelligence and mana) and Perception. I would think that would be a cool combination which could be benificial in parties with cool spells but also sneaky. Armour could have a dark foresty theme.

**Comment by Alys** [comment]
@Zemisfit We usually use GitHub for only bug reports, rather than feature requests. To request a new class or any other feature, you can go to Help > Request a Feature from the website's menu. You are welcome to do that now if you wish!

I'm closing this now and I'm also deleting the image you uploaded because I suspect it might be copyrighted with a licence that doesn't allow it to be used without permission.

If you do log a feature request, please either don't include that image, or if it has been released under a licence that allows you to use it, please provide a link to the location of the licence information.
