### ISSUE TITLE
Clean Up CONTRIBUTING.md

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#6930]
In its current state, [CONTRIBUTING.md](https://github.com/HabitRPG/habitrpg/blob/cbd5626cfdb885107b3777e0c51234e8955837e3/CONTRIBUTING.md) seems to be (imo) a rather unweildly piece of text. It requires multiple clicks to find how to submit an issue, and completely omits how to submit a pull request (found at http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request), which was rather difficult to find. This info is unlikely to change, so it would make sense to just have it in CONTRIBUTING.md. Any thoughts? @Alys

**Comment by Alys** [comment]
We're currently making some large improvements to the documentation on the wiki and when that's finished, we'll update CONTRIBUTING.md to have appropriate links to the wiki pages.

The wiki is preferred because it is easier to update, and can be done so by more people without them needing to create github accounts, and allows better organisation than a single file.

**Comment by librarianmage** [comment]
Ok. Should I add the link to the current pull request info in the meantime?

**Comment by Alys** [comment]
Yes, please do.
