### ISSUE TITLE
Random Items

### ISSUE THREAD

**Issue by Shipmaster001** [HabitRPG/habitica#6935]
I frequently receive items without notification. This has been going on for weeks, and I had begun to assume it was normal. However, just this morning, I went to feed my pets. I had with me some Honey and  Potato. When I fed the Potato to my Golden Tiger Cub, nothing seemed to happen. However, as I went to feed the Potato to my Desert Wolf, I noticed that I had somehow acquired a Pink Cotton Candy when I had no reason at all for earning it. I fed the Potato to my Desert Wolf and did not touch Habitica again for several hours. When I looked again, the only items in my Inventory were the Pink Cotton Candy and a couple of HatchingPotions (Zombie and Cotton Candy Blue) both of which I remember acquiring. Is there something going on here?

**Comment by Shipmaster001** [comment]
Update: I decided to risk getting back to Habitica so that I can register the day's progress. Naturally, I was not informed of acquiring a Panda Cub Egg. The Bear Cub Egg, however, I recieved a notification on.

**Comment by Alys** [comment]
"When I fed the Potato to my Golden Tiger Cub, nothing seemed to happen" -- Literally nothing? No notification on the corner of the website saying that the pet had been fed but did not like the food? And the green highlighting did not disappear from around the pet? Did you receive the popup asking you to confirm the feeding?

"somehow acquired a Pink Cotton Candy when I had no reason at all for earning it" -- The candy would not have been given to you at that moment. Instead, you would have earned it at some time in the past (by completing a task or using the Enchanted Armoire) and it hadn't yet appeared in your food list because the food list hadn't been synced to the server until you used some of the food.

The Enchanted Armoire can be another cause of getting food without notifications, but I'll go into that in more detail in my next message. First I need to know: Do you use the Armoire at all? Roughly how often? Do you ever find that equipment you've received from it seems to have disappeared?

"When I looked again, the only items in my Inventory were the Pink Cotton Candy and a couple of HatchingPotions (Zombie and Cotton Candy Blue) both of which I remember acquiring" -- do you mean that some items had disappeared? Which ones and how many of each?

"Naturally, I was not informed of acquiring a Panda Cub Egg." -- actually that's not natural; you are supposed to receive a notification when you get any kind of egg from a drop. If you're not seeing notifications, it could be because your browser is being slow to sync (I'll say more about that later after I've seen your answers). Another possibility is that you might not have been looking at the time - the drop notifications never appear at the same time as the XP, GP, MP notifications because drops  are assigned by the server and so there is a delay while the server processes your actions and sends information back to your browser. If you look away very soon after ticking off a task (e.g., to leave your computer to do the next task) then you might not see the drop notification. Is it possible that that is happening sometimes? I.e., do you ever mark a task as done, see the XP, etc notifications and then immediately look away to do something else?

"I decided to risk getting back to Habitica" -- this is the point that concerns me most, and I definitely want to help with it! It sounds like you've been having much more serious problems than not getting notifications for food. Can you tell me what other things are happening that are risky? What other bugs have you experienced? Are you taking health losses that you're not expecting? Anything else? To investigate serious bugs, we definitely need to be able to find your account, so please tell us your User ID. If you're not sure how to find it, step 6 from Help > Report a Bug will tell you (for website or app).

**Comment by Shipmaster001** [comment]
1. Actually, I did receive a notification that the feeding had happened. I meant that nothing happened in terms of potential bugs.
2. Well, I HAD just registered a bunch of tasks that I had accomplished the previous night.
3. I use the Armorie every time I get 100 gold. I don't think anything from it disappears, but it does take a while to show up. (Unless its XP, which shows up immediatly)
4. No items have disappeared. I was informing you about the HatchingPotions in case you needed to check my inventory.
5. It's worth noting that I usually receive items without notifications when I use the app, and almost never with the browser.
6. There are no other bugs that I have noticed. I simply do not wish to break the rules by existing.

**Comment by Alys** [comment]
Regarding the Armoire: If there is a sync error when you use it, it can give you one item but report the wrong one to you. It's possible for you to see the wrong item for a short time before the browser syncs to the server and the right item appears. If the right item was food, then it would appear in your inventory without you seeing a notification. This could account for some of the unexpected food that you see. This bug is documented in https://github.com/HabitRPG/habitrpg/issues/5376

For bugs with the app, such as missing notifications, there's three ways you can report them: using the in-app bug report form under About > Report a Bug or by email to mobile@habitica.com or in the [habitrpg-android GitHub repository](https://github.com/HabitRPG/habitrpg-android/issues).  They're summarised on the Help > Report a Bug page from the Habitica website's menu, so you don't need to remember them all. :)

I'm not able to check your inventory without knowing your User ID, but I'm not sure there's much I could tell. If you'd like me to look though, see my comment above about how to find your User ID. I'm happy to look if you want me to.

I'm certain though that all the food you've received has been earned by you, either from actioning your tasks or from using the Enchanted Armoire.

**Comment by crookedneighbor** [comment]
Just pushed a fix for Armoire weirdness that may have made it display the wrong reward for using it. Going to close this now, but please re-open if you're still having issues later this week.

Closed with https://github.com/HabitRPG/habitrpg/commit/0008839996a6879730d72a3fd5aeb5a3829cbcb8
