### ISSUE TITLE
Issues starting locally without Vagrant -- mongoose

### ISSUE THREAD

**Issue by jeffmwells** [HabitRPG/habitica#6936]
Running npm start causes errors not listed on the troubleshooting page:
1. `TypeError: Cannot read property 'ObjectID' of undefined at ...\habitrpg\node_modules\mongoose\lib\drivers\node-mongodb-native\objectid.js:8`  
   I did a simple google search and found a stackoverflow answer [here](http://stackoverflow.com/questions/30370734/cannot-read-property-objectid-of-undefined). Making this change led to...
2. `TypeError: Cannot read property 'Binary' of undefined at ...\habitrpg\node_modules\mongoose\lib\drivers\node-mongodb-native\binary.js:6`  
   I made the same fix from the first error, and everything started working. Seems to be mongoose-specific.

**Comment by Alys** [comment]
Do you still have the full output from `npm start` and `npm install`? Or even part of it if some has scrolled back off the window's buffer? I think that problem would have originated earlier in the process and I'd like to work out where.

**Comment by jeffmwells** [comment]
I did not keep the original logs. Today I tried deleting the node_modules folder and calling npm install again, and had different problems.

[Here ](http://pastebin.com/jmQJrFwn) are clips of erroneous output from npm-debug.log

**Comment by crookedneighbor** [comment]
If you're using npm 3, it will not work with the `develop` branch. You should be using node v4.3.1 which comes packaged with npm 2.

**Comment by Alys** [comment]
@swellingt0n Since you posted this, I've made some changes to [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally). If you're still having trouble, could you please try installing from scratch, working through that page from the top? Don't rely on any of the information you obtained from it previously. Pay particular attention to the "Important Notes" section. The page's history will show you what I changed, and if you create a Wikia account, you can follow the page for email notifications about future changes I'll be making.

Comment here if you have errors with the new instructions. If you do get it all working, please tell us so that we can close this.

**Comment by Alys** [comment]
@swellingt0n I'm closing this now but if you'd like more help, see my previous post. If you comment here we'll still see if even though this is closed. We can reopen if needed.
