### ISSUE TITLE
Unable to change class after using oracle of rebirth 

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitica#6957]
General Info
- UUID: 29c5340b-d150-4347-862c-fec571a18b8a
- Browser: 
- OS: 
### Description

I reached level 100 as a Rouge
I used oracle of rebirth 
I hit level 10 
I went to choose Warrior class
Saved it and went to the  Avatar status 
screen 
I was still a Rouge
I spent 3 gems to change class
It won't let me, my choice was Rouge or Healer
So I opted out 
This was on my Chrome browser
Website
I rebooted 
Cleared cache
Same problem 
My ID number
29c5340b-d150-4347-862c-fec571a18b8a
No error msgs

**Comment by Alys** [comment]
Sorry about this, @JerseyEmerald! Habitica seems to give all its bugs to you. :(

Your account is showing now that you're a Warrior with the class system not disabled, so you should be seeing a mana bar and the four Warrior skills. Please tell me if that's not the case!

I've given you the three gems you spend to change class, as you described in this issue. Tell me if you had to spend more to get yourself to Warrior and I'll refund those as well.

I can't see anything wrong in your account so I think this was a temporary problem that has fixed itself (or been fixed by any actions you might have taken after you logged this issue). I am wondering if it was just a display issue. Possibly after you went back to the stats screen, your browser was showing you a cached version with the old Rogue information in it, and when you tried to change class again, the two Mage and Warrior images might not have been loaded.

**Comment by JerseyEmerald** [comment]
Guess this is what I get for always saying I have to be different  lol
When I went to the Avatar status screen,  I had to click on the name of the class, before it loaded the page to tell me about that class, I hit the back button and was able to choose my class..I know, weird right.
That's how I worked around it, I'll have to wait until I reach level 100 again to try it out!!
Thank you so much for everything ☺
