### ISSUE TITLE
Cron hit me twice? And I died.

### ISSUE THREAD

**Issue by anaincoe** [HabitRPG/habitica#6959]
General Info
- UUID: 
- Browser: 
- OS: 
### Description

[//](#): # (After nearly getting my first 21 perfect days achievements, today I lost my 19 perfect days' streak because I forgot to log in before midnight. I took serious damage, all my party took half of it, and I was really sad because today I worked like crazy thinking about that streak and all the XP i would get. But that's ok. Was my fault. I though I could manually solve things in the settings, but there is no way to do undue party damage and fix the quest progress, nor can I restore perfect days, only each task, and that was a bad thing to notice that was missing.

So, recoving from that news, I changed my custom time again to a couple hours later. This stil today after the first cron.

So I had 2 crons on the same day and I died. Was that supposed to happen? What day is it in my account and how can i see that? Will my dailies with fixed weekdays be affected? I couldnt find other topics related. This seems like a newbie mistake, and I dont usually send tickets, but I was really upset to had had the idea that I could fix my mistakes and actually there are limitations to that that I dont think make sense since it doesnt even involve cancelling gold and new stats and xp that I could use to increase other results unfairly, it is just a matter to allow fixes to the last 12h or so for people who fall asleep or loosr their phones or have no service to check dailies in time. That seems like a major flaw to all the ideia of getting rewarded for good behaviours, since we cant undo the bad stuff even if it is a matter that escapes our grasp.

Anyway. My current day in habitica? Was that supposed to happen? Two crons on the same day? Would I get an extra perfect day if i had checked everything? It doesnt make sense, its not only the bad consequences, i think that doubling the rewards is not something that should happen.

Thank you and sorry forz the rant i ended up doing.
But it that other thing is a big flaw indeed.)

**Comment by Alys** [comment]
I'm sorry about this! You and your party mates can restore lost health, gold, etc by going to Settings > Site > Fix Character Values on the website (http://habitica.wikia.com/wiki/Fix_Character_Values )

When you changed your Custom Day Start time (CDS), was it on the website or on the iOS mobile app?

The website's feature for changing CDS has some protection wrapped around it so that it tells you when cron will next run and lets you back out if you know you can't complete your Dailies by that time. I don't think the iOS app has that protection yet, but certainly will in future. Until then, it's best to change CDS on the website, or if you need to do it on the iOS app, then do it after your Dailies are all done, or while you're resting in the inn.

We'll also be changing cron in future so that you'll see a warning appear before it happens, giving you a chance to protect yourself from incomplete Dailies.

**Comment by anaincoe** [comment]
I did it on the website ^^ . I only use that or the android app, the most recent version.

In the settings > checking out my history, I couldnt find data for before the first reset, I think. I didn't have much time to check it all out before I changed my custom time settings and had to log out, but I'll check it again as soon as I can.

And it would be a great plus to see a log of the previous 20 "things that happened". That way I could see all the dailies that made me lose HP, all the habits I had already check and not... I could see the dailies graphics, but that was the only "history" feature I found. Nothing for habits nor to DOS completed (habits are more of a necessity as they don't disappear, don't change color every time you click on them and is hard to keep track of what you've checked already. In a situation like this, with a crown in between, it gets even worse to know.

Thanks for the fast answer. there is no way to restore lost streaks then?
And even though I did the change to the time settings on the site, was that a bug or an unavoidable consequence I somehow couldt predict because now I think it has to have messed up all the date settings...? XD

Thanks again :)

(I EDITED THE POST because typing walls of text on a mobile phone makes you prone to incoherence and to typing mistakes like crazy xD)

**Comment by Alys** [comment]
When you changed the Custom Day Start time, do you recall if you saw a confirmation screen like this below?

![screen shot 2016-03-25 at 6 31 03 pm](https://cloud.githubusercontent.com/assets/1495809/14040908/c5b1e430-f2b7-11e5-9b61-b038430c5618.png)

If you saw it, do you remember what date and time it displayed for your next cron? It really should have warned you if cron was going to run again the same day so I'd love to know exactly what time it told you if you can recall, so that we can work out if it's buggy.

You can edit each Daily to restore streaks. The Data > Data Display Tool will help you estimate them (see https://habitica.wikia.com/wiki/Streaks for more information about that). That tool will also show you as much history as Habitica keeps for your data.

_"And even though I did the change to the time settings on the site, was that a bug or an unavoidable consequence I somehow couldt predict because now I think it has to have messed up all the date settings...?"_  -- Can you give me more information about which date settings its messed up?

**Comment by Alys** [comment]
@anaincoe I'm closing this now but if you'd like more help, see my questions from my previous post, and let us know if there's any other information you can give us.
