### ISSUE TITLE
Won a Quest - but instead of getting my rewards lost a level

### ISSUE THREAD

**Issue by surrealdog** [HabitRPG/habitica#6970]
General Info
- UUID: d6ad2801-3f77-4201-9e00-b71f9d275d53
- Browser: chrome
- OS: windows
  ### Description

On 3/26,realizing my health was low, I purchased 15 health points with gold coins. When I logged in on 3-27, I got two messages: that I had died and lost a level, and that I had won the Laundromancer 3 quest. Indeed, I died and lost all my gold/xp, and was given none of my rewards for winning the quest, even though it was listed as something that had happened and my new quest was listed as Vice level 1.

**Comment by Alys** [comment]
There's a couple of possibilities for the death: Either the health potion was never actually applied to your account due to a [sync error](http://habitica.wikia.com/wiki/Sync_Errors), or you took enough damage from the quest boss to kill you after the health potion was applied.

When you die at the same time that a quest ends, then you do gain the gold and experience from the quest but lose it immediately afterwards due to the death. Think of it as a real-world battle between a fighter and a monster in which they both kill each other - neither wins. :) However if you feel that the death was at all unfair, on the website, you can use Settings > Site > [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to restore the lost gold, experience, and level. You can see what the quest's rewards should have been from [The Laundromancer](http://habitica.wikia.com/wiki/The_Laundromancer).

I can see that you do own the Nameless Helm that the quest gave you and you have the achievement for completing the quest.  If you're not seeing them, reload the site and tell us if they still don't appear!
