### ISSUE TITLE
Getting more money / gold by un-completing then re-completing tasks

### ISSUE THREAD

**Issue by ansh** [HabitRPG/habitica#6971]
General Info
- UUID: 
- Browser: 
- OS: 
### Description

Suppose I am on the habitica.com main page https://habitica.com/#/tasks and then I have 1 gold coin in my inventory, and I have 2 dailies that I have completed. If i uncheck those dailies I will not go into negative gold but stay at 00, now if I have a total of 5 dailies and i tick them all, I will get a lot more cash than before! This is crazy. I can easily exploit it. Here is a link to a video where I do this:
[here](https://vid.me/7Fke)

**Comment by Alys** [comment]
Thank you for letting us know about this, but "cheating" like that is actually not something we are worried about. :) Any "cheating" that a player might do affects only their own account, and the worst that can happen is that it reduces their motivation to earn gold by completing their real-life tasks.

I believe we don't let the gold go negative because in normal situations, negative gold doesn't make sense. Having negative gold could also be confusing or demotivating to new users, who are the ones most likely to experience this through legitimate experimentation rather than "cheating".

If you've ended up with gold that you feel you haven't earned, you can go to Settings > Site on the website (Settings is the gear-shaped icon) and use [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to remove the gold. You could also use a custom reward to remove it, or feel free to keep it if you'd like to think of it as a legitimate reward for investigating this!

I'm going to close this now since I don't consider it to be a bug but if you have any questions or would like to make more comments about this, you're welcome to reply here! We'll see your comments and respond. Other admins are also welcome to reopen it if they feel it is a bug.
