### ISSUE TITLE
No "Accept the Basi-list Quest"

### ISSUE THREAD

**Issue by fallingallover** [HabitRPG/habitica#6972]
- UUID: 2af051d3-fef4-46fd-825b-1045dcc29656
- Browser: Version 49.0.2623.95 (64-bit) (Chromebook)
- OS: Chrome OS

Also play on iPad mini 3.  Doesn't work there either.
### Description

[//]: # My party leader sent me an invitation to join the Basi-list quest.  I never got it.  All my other party members got the invitation.

**Comment by Alys** [comment]
To fix this now, the party leader can abort the quest. The scroll will go back into their inventory for them to reuse. If they don't click the quest's "begin" button until after every active player in the party has accepted or rejected the invitation, then no one who wants to be in the quest will be left out (and if every party member accepts or rejects, the quest will start automatically - no need to use the "begin" button).

When you say that you didn't receive the invitation, do you mean that you didn't get an email about it, or you didn't see the invitation pop up on the website, or both?

Are you certain that it was a quest invitation that was sent, or just a party invitation? I.e., did you join the party after the quest had already started?

If you did receive emails about joining the quest / party, could you please forward them to admin@habitica.com so that we can investigate this? Please include the URL of this issue in all emails that you forward so that we know to look back here for details. The URL is github.com/HabitRPG/habitrpg/issues/6972
