### ISSUE TITLE
Background clipped in intro tour To-Dos task column

### ISSUE THREAD

**Issue by kimsey0** [HabitRPG/habitica#6982]
General Info
- UUID: f2178945-ef3c-4896-96c0-81fad2f0313f
- Browser: Firefox 45.0.1
- OS: Windows 10
### Description

The background on the To-Dos task column shown during the intro tour is clipped if you add multiple to-dos. The relevant `div` element has classes `task-column todos tour-step-backdrop tour-intro-element tour-intro-1-element`, and has `background: inherit` from the `tour-step-backdrop` class, which applies the clipped background.

![habitrpg background clipped](https://cloud.githubusercontent.com/assets/984760/14119391/3e563be6-f5ee-11e5-8a70-be02549e435c.PNG)

**Comment by ESWAT** [comment]
This breaks if you happen to resize the browser window during the tour also.

This could be fixed by modifying bootstrap-tour by removing the `tour-step-background` element - since it’s not needed and just causes issues when the To-Dos is resized - and modifying the `tour-step-backdrop` styles to match `tour-step-background`. I’d imagine this would affect other parts of the tour tough.

**Comment by SabreCat** [comment]
Placing on hold for frontend redesign.
