### ISSUE TITLE
Quest is not starting even though everyone accepted

### ISSUE THREAD

**Issue by kueb** [HabitRPG/habitica#6983]
General Info
- UUID: 54455f1b-c34e-4d3c-ad08-4b0e80d5a7ab
- Browser: 
- OS:

**Comment by crookedneighbor** [comment]
Please provide your user id. Without that, we can't investigate.

**Comment by ghost** [comment]
You're going to need to fill in some information -- your UUID is under Settings-API on the website and under Settings -> Account details in the app.  They may also want your Party ID (on the website at the bottom of the left-hand column). Also, did anyone leave/join the party?

**Comment by kueb** [comment]
I just did.

**Comment by kueb** [comment]
and here is my party's id 0f1c6d6e-ea28-4c5a-bde5-853da4e756e5
well I even deleted the other invitations just in case but quest isnt starting for hours.

**Comment by Alys** [comment]
One problem is that one user (sw agger) either left the party or was removed before accepting or rejecting the quest invitation - that's why the quest isn't starting automatically. Also it looks like the person who started the quest is no longer in the party, so there's no one who can force-start it. I'm about to delete the quest from the party. Reload the party page in five minutes and you'll see that it's gone. The quest scroll will be kept by the person who owned it.

**Comment by kueb** [comment]
alright. Thank you very much :)

**Comment by MerlinFisher** [comment]
Similar problem in my party: a former party member started a quest, then left the party.  All remaining members have accepted but the quest won't start and we can't abort.  Please fix.

Party ID:  e6e9e187-0d39-4774-8a70-5d5e03d5d3a2

thank you.
