### ISSUE TITLE
cannot "Copy message as To-Do" from the Inbox

### ISSUE THREAD

**Issue by meganstrickland** [HabitRPG/habitica#6994]
General Info
- UUID: 73e5125c-2c87-4004-8ccd-972aeac4f17a
- Browser: Chrome (49.0.2623.110 m) and Firefox (40.0.3)
- OS: Windows 7
### Description

The "Copy message as To-Do" feature does not work from the Inbox. It works in the Tavern (and I assume guilds, etc.), but in the Inbox there is no confirmation dialog. I see the same behavior in both Chrome and Firefox.

**Comment by Alys** [comment]
Confirmed. No javascript console messages. The button does literally nothing (except for the on-hover explanatory text).

**Comment by Redmega** [comment]
If nobody picks this up by tonight I'd like to give it a go

**Comment by Redmega** [comment]
I've got my local environment set up and running, I'm looking into this now.

**Comment by Redmega** [comment]
Still performing root cause analysis but it looks like from a cursory look the copyToDo method is never being hit on click of the inbox "Copy to Todos" button. I don't know enough about angular to fathom why, though.

**Comment by Alys** [comment]
@Redmega Maybe the method is in a scope that isn't being used for the code that does the inbox? 
`throws buzzwords around while trying to look intelligent and knowledgable`

**Comment by nrbunn** [comment]
@Redmega I wanted to see if I could solve this problem as well. I believe i have a fix but i don't want to steal your issue. Give you a hint to **Part** of the problem. There is a missing`ng-controller='ChatCtrl'`

**Comment by Redmega** [comment]
@Sinble Thanks for the tip. Been reading into angular so not having that ChatCtrl controller attached would cause it to not be able to talk with the controller layer, right? So it doesn't even know what the copyToDo function is...

Guessing there's more to it than just adding the ng-controller attribute, though, since you're saying thats only _part_ of the problem. You can go ahead and solve this, I haven't gotten any headway with it and I'm going to be busy with work the next few days.
