### ISSUE TITLE
Skeleton snake mount misaligned with avatar and background

### ISSUE THREAD

**Issue by GrayDays** [HabitRPG/habitica#6997]
As seen here: http://i.imgur.com/A2fdgbr.jpg http://i.imgur.com/ItEiQdI.jpg

The skeleton snake mount appears to be floating above the ground with my avatar floating above it in one screenshot, and in the other it's tangent with the scenery instead of resting in the open space on the ground. I haven't raised any of my other snakes to mounts yet to test if this is also an issue with those that yet bear mortal flesh.

**Comment by Alys** [comment]
Below is one with flesh. The skeleton mounts are placed in the same position as the other mounts of the same breed, but because they have less flesh, they can look as if they're positioned differently. It's not so obvious with most mounts because their legs still reach the ground, but it's more obvious with snakes and snails. Think of it as invisible flesh. :) 

![screen shot 2016-04-02 at 8 33 04 am](https://cloud.githubusercontent.com/assets/1495809/14221875/a4ae56c8-f8ad-11e5-879d-8b3e7cae11f2.png)
