### ISSUE TITLE
Frozen quest status after party member left

### ISSUE THREAD

**Issue by MerlinFisher** [HabitRPG/habitica#6998]
As other members have reported (in closed issues), we had a party member who initiated a quest, but that person then suddenly switched to another party, and now our quest status is frozen.  We've all "Accepted" but the quest will not start and we cannot abort either.  I complained about this in Tavern and was told to report it here on Git.

Party ID:
e6e9e187-0d39-4774-8a70-5d5e03d5d3a2

p.s.  The link for known HRPG issues (meaning this https://github.com/HabitRPG/habitrpg/issues ) is broken, you probably should fix the link or take it off your header.

**Comment by crookedneighbor** [comment]
Can you elaborate what you mean by "broken"? I'm not having any trouble getting to it.

**Comment by Alys** [comment]
@MerlinFisher The quest owner (Lorna) is still in your party. That person will see "begin" and "cancel" buttons at the bottom of the quest box and can use them to start the quest or remove it (the cancel option allows the quest scroll to remain in their inventory). Can you please ask Lorna to click on one of the buttons? If they don't appear, please ask her to put a screenshot of the quest box into this issue so that we can investigate.

**Comment by Alys** [comment]
@MerlinFisher I'm closing this now since we aren't aware of any bugs that would prevent Lorna from starting the quest, but if Lorna does have trouble, you can post here again - see my comments from my previous post if that's necessary.
