### ISSUE TITLE
with the latest update I spontaneously died today... I had enough health... weird

### ISSUE THREAD

**Issue by Daij-Djan** [HabitRPG/habitica#700]
with the latest update I spontaneously died today... I had enough health... weird

**Comment by sh4unz0r** [comment]
The same thing happened to me. I went to be with full health and woke up dead. There is no way I lost that much from one day.

**Comment by lefnire** [comment]
this has only happened since the latest push? We didn't adjust the algorithms - only the design, but I'll look into it

**Comment by sh4unz0r** [comment]
unless somehow the number of hitpoints inflicted by my unfinished tasks doubled overnight. I leveled at the end of the day yesterday so I was full health. The most i have seen HP go down overnight previously is about 18, so jumping to 50 would be more than incremental.

It would be nice if there was some type of log to see what caused the loss of HP.

**Comment by AngeloAdam** [comment]
It would be nice to know how much damage is inflicted from uncompleted tasks on each new day. This has led to me dying without knowing how much damage each task caused.  i currently have no idea how much HP is reduced by each unfinished task on each new day.

**Comment by wc8** [comment]
@come2gether, that's the reason for the suggestion under [Progress/History Views](https://trello.com/c/h0pezwDR) to show HP loss causes, especially in cases of death.

**Comment by lefnire** [comment]
Temporary work around, look at the last history graph entry on each daily -
that's how much it hurt you

**Comment by Pandoro** [comment]
This happened to me as well today. Lately stuff is a bit weird. Actually I became lvl 11 two days ago. But yesterday morning I was back at lvl 10. I figured it didn't transmit my final checks to the server. (I just survived, going from 23 to 3 hp.) I checked those off again and leveled up. I thus had 50 hp yesterday night and pretty much checked everything but one green daily. This morning I died. I restored it, but it is very weird :x 

I cannot say if this has only happened since the last push, but I think similar stuff has happened before, so I doubt it is the latest push.

**Comment by lefnire** [comment]
I have a feeling that many of these issues we're experiencing are due to data not registering, similar to the old bugs we experienced due to the memory leak. Eg, you check-boxed your tasks, but they never went through - next day you refresh, and get hurt by all of them. I have a hunch it's due to the migration to AWS, 2 possible causes: (1) the cron time was upped since we now have more RAM - I just reverted that back in case that's the problem, so let's keep an eye on it. (2) we restart using `chef-client` - which I _think_ might be wiping `/public/gen/*`, killing socket.io connections on restart. I may be wrong on 2, and I'll be investigating that. In any case, rest assured this is being looked into.

**Comment by Pandoro** [comment]
I actually refresh the page after everything I do. I get the idea, that at
least in my case, this is caused due to the custom day restart thing.

**Comment by lefnire** [comment]
I suspect rogue tasks that should have been deleted, and not showing up in the lists - I'll be looking into this very soon

**Comment by lefnire** [comment]
got a duplicate over at https://github.com/lefnire/habitrpg/issues/777#issuecomment-16027991 , let's follow up there since I have some more info there
