### ISSUE TITLE
Subscription not expiring at the end of a 12 month plan

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7014]
### General Info
- UUID: a75eb6f8-5a29-482f-a971-7aff7438da86
- Browser: Firefox 45
- OS: Ubuntu 15.10
### Description

I paid a 12 months subscription, as far as I can remember somewhere around the end of February 2015. It should have been automatically renewed at the end of February this year. Except my credit card informations changed last year, and I didn't changed them on Paypal because I don't use it that much in the first place. So it should have failed. But in fact, my subscription didn't even expired, as far as I can see it.

I was waiting for the renewal to change my card informations. On March 8, I received a notification from Paypal stating that the automatic payment failed (logically, since informations were outdated). I ran to the Subscription page on Habitica, only to see that I now had 13 consecutive months, and that I was still a subscriber. I first thought that this was temporary. But I'm now at 14 consecutive months, still a subscriber. I was able to buy gems, got the subscribers monthly reward; the only thing missing is the hourglass, which were not renewed (maybe I would have got one on the 15th month?)

This is annoying because:
- I feel like I abused the system
- I'm willing to give my money to a project that I really like
- I can't seem to get any hourglass

Also, just to make sure, I checked my bank account and can confirm that I wasn't charged in any way.

I guess this can be solved by cancelling and then pay a new subscription, but maybe doing so wouldn't allow you to get the information you need to look into this issue. I'm waiting for any input on how to make things right.

**Comment by Alys** [comment]
Thank you for asking about this!

This is PayPal's expected behaviour. When an ongoing payment fails, PayPal keeps track of the failures. Later, when it is able to take money from your bank account or credit card again, it will make those payments. Your subscription continues uninterrupted while this happens.

All you need to do is add a new credit card or bank account to PayPal.

Could you please let us know when you've done that? We'll then close this issue and check that PayPal has noticed that it can make the payments now.

**Comment by ghost** [comment]
Okay, so I've updated my card informations on Paypal.

But this seems to me like a strange behaviour, as it looks I could have continued to be considered a subscriber, although not being charged for it. I somehow expected a notification on Habitica stating that something went wrong.

**Comment by Alys** [comment]
Thanks very much @Blablux ! I've noted that on our list of changes to consider for the back-end subscription processing.

**Comment by ghost** [comment]
@Alys one month later, things didn't change much. My subscriber status went up one more month (15 now) thus granting me a mystic hourglass, but nothing close to the 12 months subscription I was expecting, though my credit card has been updated for more than a month now.
So as far as I see it, Paypal didn't try that much to collect my subscription since then.

**Comment by Alys** [comment]
Thank you for telling us! I've instructed PayPal to try to take the payment again. Once that goes through, I'll update your subscription details, including your Hourglasses to give you the extra three you should receive (four in total for another year's payment).

**Comment by Alys** [comment]
PayPal has collected the $48 from you now. 

I've given you the missing three Hourglasses. Your monthly gem cap is already at the maximum, so that's correct. I'll check on your Habitica account's subscription details again this time next month to ensure that the monthly count is ticking over correctly.

Thank you for your support and I'm sorry it's been troublesome for you!

For my reference:

```
    "purchased": {
        "plan": {
            "customerId": "-------",
            "dateCreated": "2015-02-27T22:24:14.220Z",
            "dateTerminated": null,
            "dateUpdated": "2016-05-01T05:41:17.813Z",
            "paymentMethod": "Paypal",
            "planId": "basic_12mo",
            "consecutive": {
                "trinkets": 4,
                "gemCapExtra": 25,
                "offset": 0,
                "count": 15
            },
            "mysteryItems": [],
            "gemsBought": 50,
            "extraMonths": 0
        }
    }
```

edit 11 June: I've set offset to 10 - I forgot that initially. It won't have had any negative effects. All else looked good.
