### ISSUE TITLE
Am a subscriber but not receiving the mystery items

### ISSUE THREAD

**Issue by lonealchemist** [HabitRPG/habitica#7016]
General Info
- UUID: 2c9105c1-bf5e-467c-a97c-386120d9f16d
- Browser: Chrome
- OS: Windows 10
### Description

Hi! I subscribed to Habitica in March but have not seen the mystery item appear in my inventory. I saw a similar issue posted a couple of days ago, but it was closed/resolved (not sure if I should have posted under that one as well).

Thanks for your help!

**Comment by GoblinClan** [comment]
I am having the same issue as well. I also subscribed in March but have not seen the March mystery item appear in my inventory. My UUID is 38c8d533-51c2-471f-bd3b-fada4ad8b6ac. Thanks!

**Comment by lonealchemist** [comment]
I looked at my subscription settings and it does not say that I am a subscriber; however, when I checked my credit card statement, I was charged on March 20th for a 1 month plan (5 / month). It's the same instance with GoblinClan, who is a family member.

**Comment by Alys** [comment]
@lonealchemist There's no indication in your 2c9105c1-bf5e-467c-a97c-386120d9f16d account that you are a subscriber. Please email your subscription receipt to admin@habitica.com and include your User ID. We'll get that sorted out for you!

@GoblinClan Your account also is not showing a subscription. Please email your receipt to admin@habitica.com and include your User ID and this issue's URL: github.com/HabitRPG/habitrpg/issues/7016

I'm closing this now since we'll handle it all by email to keep your financial details private.
