### ISSUE TITLE
Equipment tab doesn't work. Don't show anything. And at the app, there is a "connection err"

### ISSUE THREAD

**Issue by louceiro** [HabitRPG/habitica#7022]
General Info
- UUID: 
- Browser: 
- OS:

**Comment by Alys** [comment]
Hi @louceiro. I'm guessing this was saved in error while you were trying to make a full bug report, so I'm closing it now, but if you're still having trouble seeing anything on the website, try reloading the site using your browser's reload button, and if that doesn't help, log out. If you can't get to the log out menu item for any reason, you can go to https://habitica.com/static/clear-browser-data and click the button you'll see there - that will cause you to log out.

Once you've logged back in, it's likely to be working, but if not let us know the details listed in the comment above and we'll keep helping you.

**Comment by Featherlite2** [comment]
Hi Alys, 

I have just encountered this issue when attempting to access my equipment via android app see screenshot -
![13015151_10153389582995899_7776310544138719477_n](https://cloud.githubusercontent.com/assets/18439563/14489835/fadb8852-01a1-11e6-8157-34506e24e213.jpg)

I thought that it would still keep the item equipped but when I would go out and back in to view the item it showed as not being equipped again.

Via web browser both on my laptop and phone, when i looked at my equipment there was nothing there at all.

I did as you suggested above and logged out of the web browser and out of the app on my phone. 

Now there is no equipment at all available on the app either. Very frustrating!

Is there a solution available at all?

**Comment by Alys** [comment]
@Featherlite2 Could you please tell me your User ID? To find out how to get it from either the website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu).

**Comment by Featherlite2** [comment]
@Alys my apologies for not posting it when I commented above. It is acd8a54c-d5bc-4676-afbf-238a789545a8
I have just rechecked my app and the equipment is there but when I try to equip, the error is still coming up. Also, still nothing showing under equipment in the web browsers.

**Comment by Alys** [comment]
No worries. :)

I've checked your account and you don't own any equipment at all - that's why the equipment screens on the browser and app are shown as empty.

If you had bought some equipment in the past, a sync error might have stopped the purchase being permanently saved to the server. You should see all the item(s) you previously bought still available under Rewards to be bought again. If you didn't get back the gold that you spent on them previously, you can go to Settings > Site > Fix Character Values (on the website only, at the moment) and use that to get back your gold.

**Comment by Featherlite2** [comment]
@Alys - that is true that I hadn't yet purchased any equipment.

Are you able to tell me why I can see items when I access my equipment on app? For example in the screenshot I took above it showed me as having a wooden shield?

Also, as I noted in my previous comment - the items are showing again on the app. I've put them in a list below:
Leather Helm
Chain Coif
Leather Armor
Training Sword
Sword
Axe
Wooden Sheild

I am in a party and we are all the same level and the rest of my party gained what looks to be the same items that show in app for me from the Basi-List quest, and from what I can see from their avatar's they have been able to equip (I am currently waiting for them to reply to my query in the party chat).

I've had no issue with "equipping" or viewing pets.

This one has me boggled...

**Comment by Alys** [comment]
You hadn't mentioned before that you have never purchased any equipment. I thought you were saying that you used to own equipment but that it had disappeared.

Because you haven't bought any equipment yet, it's correct that the equipment page on the website isn't showing anything - it will be empty until you buy some.

You've experienced this bug on the app: https://github.com/HabitRPG/habitrpg-android/issues/493

Normally, app bugs would need to be reported either through the in-app report form or in the Android github repository (see the "To report a bug in the Android Habitica app" section of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions), however since we already know about this bug and already have a fix for it in the works, you don't need to report it. If you install the next Android app update, you'll find it's fixed.
