### ISSUE TITLE
Applicate Error

### ISSUE THREAD

**Issue by imafable** [HabitRPG/habitica#7028]
General Info
- UUID: 5468b1fe-d50a-4180-9b99-14105a1941b4
- Browser: Chrome
- OS: Windows 7
### Description

The site loads well but randomly, often when browsing challenges/guilds/inventory I get this error. It happens on Chrome Android and on Desktop.
![app error](https://cloud.githubusercontent.com/assets/18137110/14321383/913c96e4-fc4b-11e5-8b61-1c8c65b05e98.png)
#### Console Errors

https://habitica.com/api/v2/user/batch-update?_v=1867&data=1459952954823 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-05136417.js:33 ObjectresponseError @ app-05136417.js:33
https://habitica.com/api/v2/groups?type=party,guilds,tavern Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-05136417.js:33 Objectconfig: Objectdata: "<!DOCTYPE html>↵    <html>↵    <head>↵      <meta name="viewport" content="width=device-width, initial-scale=1">↵      <style type="text/css">↵        html, body, iframe { margin: 0; padding: 0; height: 100%; }↵        iframe { display: block; width: 100%; border: none; }↵      </style>↵    <title>Application Error</title>↵    </head>↵    <body>↵      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">↵        <p>Application Error</p>↵      </iframe>↵    </body>↵    </html>"headers: (c)status: 503statusText: "Service Unavailable"**proto**: ObjectresponseError @ app-05136417.js:33
https://habitica.com/common/dist/sprites/spritesmith-main-0-ce258761.png Failed to load resource: the server responded with a status of 503 (Service Unavailable)

**Comment by SparkleSara** [comment]
I am having the same problem on desktop and Android App.

I'm using Chrome and Windows 7.

My Android App tells me that I am not connected to the internet when I can see that I am connected to wifi.

**Comment by Redmega** [comment]
I faced the same problem intermittently with my android application, can't verify the web browser at the moment

**Comment by lemoness** [comment]
We are so sorry about this! Some of our servers went down, which was causing the errors. It should be fixed now. Please let us know ASAP if it isn't! 

 If you lost health, gold, or anything else due to the server outages, you can restore your lost stats on the website under Settings > Site > Fix Character Values. You can also restore lost streaks on the website when you edit a task. Feel free to ask if you have any questions!

The good news is that we've now transferred over the servers, which we're hoping will lead to more stability. Thank you so much for all of your patience!
