### ISSUE TITLE
Unresponsive Script

### ISSUE THREAD

**Issue by Shipmaster001** [HabitRPG/habitica#7048]
General Info
- UUID: Unknown
- Browser: Firefox
- OS: Microsoft
### Description

For the past few weeks, I have keep recieving messages on Habitica that say that the script is unresponsive. I'm usually able to get past them by clicking the "Stop Script" button, but the sheer frequency at which they appear is annoying. It happens every time I log in for the day or when I click on a task for the first time in a at least an hour. It's gotten to the point where I'm scared to use the website and instead use the app, which doesn't have these problems. What can I do to make them stop?

**Comment by Alys** [comment]
Can you please tell us your User ID? You can find out how to get it on either website or app from step 6  of the [Help > Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions.

**Comment by Shipmaster001** [comment]
cfe6f321-92cf-4766-910c-703d11ffb65f

**Comment by Alys** [comment]
You have about 450 tasks, so it's possible that the website just takes a long time to respond because it's displaying a lot of information. 

About half your tasks are completed To-Dos. Most of them won't be having any impact because the website doesn't show them after they've been marked as completed for three or more days, however you might find that deleting your completed To-Dos improves the performance. You can do that from the bottom of the "Done" tab in the website's To-Dos column.

Also if you have any old tasks that you no longer need, it might help to remove them.

Try reloading the site when you notice the problem. 

About how many tabs and windows do you have open in Firefox typically? It's possible that your browser is just generally overloaded.

You could also try using a different browser, such as Chrome, for Habitica.

**Comment by Shipmaster001** [comment]
I'm afraid that might be a problem. Many of my completed To-Do's are from completed challenges. I find that I can't delete anything from challenges. Why is this?

Also, I ususally just have two things open at a time: Habitica and something else. Sometimes, I open a 3rd window, but usually it's just the two.

**Comment by Alys** [comment]
Challenge tasks can't be edited in most ways (including deleting them) because all participants are meant to have the same tasks, for fairness. If you no longer want to be in a challenge and don't care about winning it, you can leave the challenge (from the Challenges list under the Social menu) and select the option to delete challenge tasks. If the challenge has already ended and the tasks remain, mark one of the tasks as completed and that should cause them all to become deletable; if the only tasks are completed To-Dos, mark one as uncompleted then completed. Let us know if you have problems with that.

**Comment by Shipmaster001** [comment]
I'm sorry, but the advice that you gave me didn't work. I checked off a To-Do from a challenge that I had already failed, and it couldn't delete it. I unchecked and re-checked a completed To-Do, and I couldn't delete it. Even when I found a "Delete Completed" button at the bottom of my "Done" To-Do list, I still couldn't delete them. Is there something I'm doing wrong?

**Comment by Alys** [comment]
When you say "a challenge that I had already failed", do you mean that the challenge ended and someone else was awarded as the winner? Or that you left the challenge? Or that you're still in the challenge but can't win it because you haven't met the conditions? Basically, we need to know for certain if the challenge has ended, or if it's still running but you are definitely not in it. 

If you did leave the challenge but kept the challenge tasks and if the challenge still exists, rejoin the challenge and then leave again but this time select the option to remove the tasks.

Tell us what challenge it was and/or the full name of a task from this challenge that you can still see in your tasks lists.

**Comment by Shipmaster001** [comment]
It was a challenge that someone else already won. If I recall, it was the "Clear the Dungeons: March Edition" challenge, which has already ended.

**Comment by Alys** [comment]
That challenge had just a few To-Ds so even if they are never deleted, they won't be causing enough load to add to the problem you're experiencing.

Your total number of tasks and number of completed To-Dos has decreased significantly. I wouldn't worry about the remaining completed challenge To-Dos; they probably also aren't numerous enough to be a significant problem.

Has it been long enough since you deleted completed To-Dos to tell if the unresponsive script error has disappeared or at least is happening less often?

If not, have you noticed if it helps to reload when the error occurs? Does it still happen in another browser?

**Comment by Alys** [comment]
In the Tavern, another user has reported something similar, and the moderator Megan says that she sees it occasionally when she has a lot of other programs running (or a lot of tabs open). Is it possible that something else is using up your system resources, causing Firefox to be less responsive?

**Comment by Shipmaster001** [comment]
Now that you mention it, it started at around the same time that I downloaded BOINCManager. I don't want to delete it, because I really want my computer to contribute to solving the world's problems, so what do I do?

**Comment by Alys** [comment]
The webpage for that program (https://boinc.berkeley.edu/wiki/BOINC_Manager ) says that it doesn't need to run all the time, so you could close it whenever you aren't using it.

Did you download BOINC itself at the same time? If so, BOINC is more likely to be the culprit. I imagine that the manager will let you configure BOINC to use fewer resources. If not, delete BOINC and see if Firefox then starts performing better. You could reinstall BOINC after testing that.

**Comment by Shipmaster001** [comment]
Uninstalling BOINC had no impact on the quality of the website.

**Comment by Alys** [comment]
You might also like to look through other long-running applications and browser extensions.

Did you see my questions from above? These ones:

Has it been long enough since you deleted completed To-Dos to tell if the unresponsive script error has disappeared or at least is happening less often?

If not, have you noticed if it helps to reload when the error occurs? Does it still happen in another browser?

**Comment by Alys** [comment]
I'm closing this now but if you'd like more help, see the questions from my previous post.
