### ISSUE TITLE
Not able to do damage during quest

### ISSUE THREAD

**Issue by thinklb** [HabitRPG/habitica#7061]
I am in a party of 2, completing dailies and to-dos and not doing any damage to The Basi-List. The other party member has been doing damage. I've confirmed that I'm a participant in the party list of participants and am also the quest owner. I used the Habitica User Data Display Tool (https://oldgods.net/habitrpg/habitrpg_user_data_display.html) to see if I crossed off some tasks it would register damage, but it's showing that I will do no damage to the monster even after completing several tasks.

User ID: 51abec71-ba44-4ff9-bc33-f92281806bc7
Group ID: 179df892-c7a3-428f-84f7-73b929b2cc23

**Comment by Alys** [comment]
Sorry about that! The quest information hadn't been correctly saved to your user account when the quest started. I've fixed that now and you should find that tomorrow when your Dailies reset, a quest progress message will appear for you in party chat, and it will contain damage to make up for the two or three days that the quest has been running for.

If it does not, comment again here! I'm closing this now but we'll still see your reply even though this is closed.

**Comment by Mithedhelwen** [comment]
Hi--I have the exact same issue described above:  In a party of two, my other party member is doing a little damage, but I completed all my dailies and loads of to-dos yesterday (and spent lots of mana adding "burst of flames to most of them), and I haven't done any damage at all.  Please advise.  Thanks!

User ID:  ee648396-666e-40cd-af3e-7912ced3a2b8
Group ID:  bf19fe3b-fb18-4b6d-8b5e-c68fd793534d

**Comment by Alys** [comment]
@Mithedhelwen I can see that you joined Habitica only a day ago, and have been through only one cron since then ([cron](http://habitica.wikia.com/wiki/Cron) is the process that resets your Dailies at the start of each day, and also applies your quest progress and does other things). Either the quest started this morning after your cron happened, or it started yesterday and you were [resting in the inn](http://habitica.wikia.com/wiki/Rest_in_the_Inn) overnight, which is designed to prevent your account having any effect on the quest (as well as having other effects). If you have questions that those wiki pages don't help with, you are welcome to ask here or go to the Newbies guild (Help > Ask a Question from the website, or from the top of the list of "Guilds" on the mobile app). The Newbies guild has many experienced players who can help with almost any question and you'll often get an answer faster there because there's many more people there. :)
