### ISSUE TITLE
Sorting dailies does not work [To-Dos sorting bug]

### ISSUE THREAD

**Issue by artemisclyde** [HabitRPG/habitica#7074]
Hi there,

I have a problem sorting my dailies. I usually sort them to know in which order I'll do those tasks. For the past week or so, when I sorted them properly and reloaded the site later on, everything was set back and my sorting was reset. Does anyone know why this is happening?

**Comment by Alys** [comment]
@artemisclyde Sorry about this! I keep my Dailies in a very strict order so I know how frustrating this must be for you!

I think it's likely to be caused by your browser not syncing correctly with Habitica's server. You might have also noticed other problems such as tasks that you though you'd completed appearing as uncompleted later.

Sync errors usually disappear if you log out of Habitica and log back in, although the sync errors can come back a few minutes/hours/days after that.

What I recommend you do is, just before you want to sort your Dailies again, log out and log back in. Then sort a few Dailies, and then stop to check to see if the new order has been saved. One way to check would be to log out and back in again, but that's laborious! Another way would be to reload, but a reload doesn't always remove syncing problems, so it's not completely reliable. A third way is to use the [Data Display Tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) -- look in the "Task Overview" section and filter by "type" (or just scroll down to the Dailies); if it shows the Dailies in the order you've just moved them to, then you can be sure that the new order has been saved to Habitica's server. You can then sort a few more Dailies, and check again (if you're using the Data Display Tool, click the "Re-Fetch Data" button to get fresh data from the server).

Let us know if none of this helps!

**Comment by artemisclyde** [comment]
Manually checking whether it has synched does work for me, but it's weary since I also have a very strict order for my tasks. Is there no way to ensure constant synching between my browser and the habitica server? I'm currently using firefox 45.0.2-1 on Arch Linux.

**Comment by Alys** [comment]
Not really, sorry. :(  Habitica uses your browser's local storage as well as data stored on the server, but sometimes the browser seems to just keep using local storage without any communication to the server. Logging out clears that, but we're not aware of any way to make it stop happening again.

However once you've got your Dailies in the correct order and have confirmed that the order is saved to the server, they won't get out of order again. I believe the only problem is that your actions to sort them weren't being saved to the server, not that the Dailies later unsorted themselves.

If you haven't been noticing frequent sync errors (e.g., completed tasks becoming uncompleted), then the errors probably don't happen often for you. You could probably get away with logging out once, then resorting all your Dailies in a single stage, and then doing one check of them all at the end.

**Comment by artemisclyde** [comment]
Well okay, I'll see how that will work for me. I'm just confused that I didn't have this issue before, maybe something about my browser changed. That I'll have to figure out.

Thanks though for the quick and kind help on this!

**Comment by artemisclyde** [comment]
I just recognized one more thing: Synchronizing may not work for sorting all the time, but adding tasks always works and is synchronized. Even when I sort something first and then add another task, upon synchronizing the sorting is reset, but the task I added afterwards still exists.

**Comment by Alys** [comment]
Are you sorting and adding Dailies through the website alone? 

Or are you sorting on the website and using the mobile app to add Dailies?

Or are you adding Dailies through some other tool, for example a script that uses the API?

If you're sorting your Dailies on the website and then adding Dailies using the mobile app, it might help to ensure that the mobile app is synced first and is displaying all your Dailies in the correct order, before you add a new one. Does that seem to be relevant?

Is the sorting problem just with your Dailies?

**Comment by artemisclyde** [comment]
The problem occurs when I sort my tasks, not my dailies. My dailies pretty much stay the same at the moment.
I use the website alone for both adding and sorting.

**Comment by Alys** [comment]
@artemisclyde "Tasks" is generally used to refer to all of Habits and Dailies and To-Dos (and in some circumstances also Rewards). Your initial post here and your title said that you had trouble sorting Dailies. Can you please clarify which types of tasks you are having trouble sorting?

**Comment by artemisclyde** [comment]
Oooooh sry, didn't realise that before. I'm talking about To-Dos.
I'm currently trying to log out and in again after doing a great lot of sorting. Maybe this way I can at least asure that my changes are being synched.
Sorry for the misunderstanding on my side.

**Comment by Alys** [comment]
Ignore all the advice I gave you previously - it was all based on the assumption you'd be sorting your Dailies once to get them into a good order and then not repeating that often. The process I suggested is too laborious for frequent sorting of To-Dos.

Please see the "Rearranging To-Dos" section in the wiki's [To-Dos](http://habitica.wikia.com/wiki/To-Dos) page. There's some tips there that should help.

**Comment by Alys** [comment]
Also https://github.com/HabitRPG/habitrpg/issues/6040 for the known issue mentioned in that page.
