### ISSUE TITLE
Unable to install phantomjs-prebuilt on fresh Vagrant install

### ISSUE THREAD

**Issue by natfarleydev** [HabitRPG/habitica#7082]
I'm not a nodejs developer (yet!) so apologies if this is the wrong place for this bug report.

I've done a fresh install of a machine with vagrant for the 'api-v3' branch of Habitica but when I do `npm install` it cannot install the `phantomjs-prebuilt` package. Is there a way around this?

Log:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.3.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.3.1/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
vagrant@habitrpg:/vagrant$ npm install phantomjs-prebuilt

> phantomjs-prebuilt@2.1.7 install /vagrant/node_modules/phantomjs-prebuilt
> node install.js

/vagrant/node_modules/fd-slicer/index.js:145
  this.pos = this


SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/yauzl/index.js:3:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by crookedneighbor** [comment]
Hmmm. Phantom v2 just came out. We were using phantom 1 before. I wonder if that is the problem.

**Comment by natfarleydev** [comment]
How would one go about changing it back to phantom 1? I tried changing the `project.json` to have `"phantomjs": "~1.9"` and destroying and recreating the vagrant box but it still tried to install version 2.something

**Comment by lucubro** [comment]
Confirming the problem here on branch `develop`. I am using Vagrant too.

**Comment by Alys** [comment]
I've been getting similar errors today, although with different modules. For example:

```
==> default:   +-- mkdirp@0.5.1 
==> default:   | `-- minimist@0.0.8 
==> default:   `-- supports-color@1.2.0 
==> default: All done! run npm install to install the required node modules and then npm start to start the server
You have new mail in /var/mail/alys
  [idun:/code/habitrpg 510 ]$ vagrant ssh
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '14.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Welcome to your Vagrant-built virtual machine.
Last login: Fri Sep 14 06:23:18 2012 from 10.0.2.2
N/A: version "current" is not yet installed
Found '/vagrant/.nvmrc' with version <4.3.1>
v4.3.1 is already installed.
Now using node v4.3.1 (npm v3.8.6)
vagrant@habitrpg:/vagrant$ npm install
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated pngjs2@1.2.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> kerberos@0.0.3 install /vagrant/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/vagrant/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory `/vagrant/node_modules/kerberos/build'

> bson@0.2.2 install /vagrant/node_modules/mongoskin/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/vagrant/node_modules/mongoskin/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: Leaving directory `/vagrant/node_modules/mongoskin/node_modules/bson/build'

> phantomjs-prebuilt@2.1.7 install /vagrant/node_modules/phantomjs-prebuilt
> node install.js

/vagrant/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:47
mo


SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/fs-extra/lib/index.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
habitrpg@0.0.0-152 /vagrant
+-- amazon-payments@0.0.4 
| +-- qs@0.6.6 
| +-- request@2.34.0 
```

This seems to be the critical part:

```
/vagrant/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:47
mo

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
```

When I look at line 47 of /vagrant/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js, I see that it starts with the letters `mo` and then has a lot of non-ascii characters after that. It's clearly corrupted. Other attempts to run `npm install` produce similar effects but with different files.

This might not be related but graceful-fs.js warns:
`npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

I'm experimenting with making the vagrant installation process go back to using npm v2 instead of v3. I'll report back with findings.

**Comment by Alys** [comment]
I had that problem of corrupted files consistently during multiple attempts to create a new Vagrant install, while using the current `develop` vagrant scripts which specify npm@3. 

As soon as I changed `vagrant_scripts/install_node.sh` back to use npm@2, that problem went away. 

npm@3 was introduced in https://github.com/HabitRPG/habitrpg/pull/6564 but I'm not sure we should keep using it with the current `develop` code base. @crookedneighbor @KristianTashkov do you have any comments?

Possibly related is this issue which might have been from using npm 3: https://github.com/HabitRPG/habitrpg/issues/6936#issuecomment-200448991

If no one objects in a day or so, I'll push a change to specify npm@2 in `vagrant_scripts/install_node.sh`

Note though that even with npm 2, I still can't get a new Vagrant install running because I'm getting errors similar to https://github.com/HabitRPG/habitrpg/issues/7090, but that seems to be an unrelated problem.

**Comment by crookedneighbor** [comment]
If I recall, there was some weird caveat with some versions of Virtualbox that didn't play nice with npm 2. However, the project isn't set up to use npm 3 yet. I've been working on it, but the process has been slow going. 

I say, for now, change it back to npm 2, but I'm hoping to get the project working with npm 3 (what the api-v3 branch is using) soon.

**Comment by Alys** [comment]
I've made a commit to `develop` (https://github.com/HabitRPG/habitrpg/commit/823f51e7270deec80c3c334d34646420df8edf64) to change vagrant_scripts/install_node.sh to use npm 2 instead of npm 3.

**Comment by Alys** [comment]
I believe this is now fixed for those installing the current code base from `develop`.

@nasfarley88 are you still trying to use the `api-v3` branch and are you still having trouble?

**Comment by natfarleydev** [comment]
Yep, same trouble I think.

Log in case it isn't the same trouble. This is npm install from fresh vagrant. 

My Virtualbox version is 5.0.16_RPMFusion r105871 if that helps.

```
npm WARN package.json Dependency 'vinyl-source-stream' exists in both dependencies and devDependencies, using 'vinyl-source-stream@^1.1.0' from dependencies
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

> phantomjs-prebuilt@2.1.7 install /vagrant/node_modules/pageres/node_modules/screenshot-stream/node_modules/phantom-bridge/node_modules/phantomjs-prebuilt
> node install.js

/vagrant/node_modules/fd-slicer/index.js:145
  this.pos = this


SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/yauzl/index.js:3:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.3.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.3.1/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.15.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

**Comment by Alys** [comment]
@nasfarley88 Since you're using the API v3 branch, you'll need to use more recent versions of node an npm. That would probably correct the problem you're having. However that branch isn't really ready for normal use yet, and so you might have more luck with the `develop` branch, following the steps in https://habitica.wikia.com/wiki/Setting_up_Habitica_Locally

I'm closing this now but if you have trouble with installing `develop`, you're welcome to open a new issue.

**Comment by natfarleydev** [comment]
Thanks @Alys. I still need to use the api-v3 branch since I'm trying to test the new api with a python library. How would I go about getting those newer versions (package management? ; from source?). I don't mind doing the heavy lifting just not sure of the best place to start.

Or is there another way to test the v3 api? I don't need to edit the js code, just use a bleeding edge version of the v3 api.

**Comment by crookedneighbor** [comment]
@nasfarley88

You should just need the newer version of npm. `npm install -g npm@3`

**Comment by Alys** [comment]
@nasfarley88 Sorry! You have a good reason for using the api v3 branch. I should have asked before closing this. You're welcome to keep posting here if you have more problems. Let us know if the npm3 install doesn't work. `npm --version` and `node --version` or `nodejs --version` will show you what you have installed.

**Comment by natfarleydev** [comment]
Before upgrade:

```
vagrant@habitrpg:/vagrant$ npm --version && node --version
2.15.4
v4.3.1
```

Then:

```
vagrant@habitrpg:/vagrant$ sudo npm install -g npm@3
/home/vagrant/.nvm/versions/node/v4.3.1/bin/npm -> /home/vagrant/.nvm/versions/node/v4.3.1/lib/node_modules/npm/bin/npm-cli.js
npm@3.8.7 /home/vagrant/.nvm/versions/node/v4.3.1/lib/node_modules/npm
```

resulting in these versions:

```
vagrant@habitrpg:/vagrant$ npm --version && node --version
3.8.7
v4.3.1
```

But still the same issue trying to install `phantomjs-prebuilt@2.1.7`. I'll try a fresh Vagrant box and upgrade straight away (before running `npm install`) to see if that makes a difference.

**Comment by Alys** [comment]
@nasfarley88 Follow the steps listed in [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) BUT when you're in the Vagrant section of those instructions, stop just after doing this step:

```
7. Login to the environment (a Ubuntu Linux virtual machine):
vagrant ssh
```

Then do this:

```
sudo nvm install 5     # note that's nVm, not nPm
nvm use 5
node --version; npm --version
```

Node should then be at version 5.x and npm should be at version 3.x. Note that you don't need to install or upgrade npm separately. If you find that you aren't at versions 5.x and 3.x, show us the full output of those three commands and don't go further.

If you do have versions 5.x and 3.x, continue with the instructions from the wiki page:

```
Install required node modules. This will take many minutes. Due to a bug you may have to run it twice.
npm install
[ and so on ]
```

**Comment by natfarleydev** [comment]
(Not sure if relevant: just `git pull`'d which changed a lot in `migrations/api_v3/users.js`.)

`sudo nvm install 5` came up with function not found, so I had to `sudo su` and then `npm install 5`. After that, I have:

```
vagrant@habitrpg:/vagrant$ node --version; npm --version
v5.11.0
3.8.6
```

But still the same error, 

```
> phantomjs-prebuilt@2.1.7 install /vagrant/node_modules/phantom-bridge/node_modules/phantomjs-prebuilt
> node install.js

/vagrant/node_modules/fd-slicer/index.js:145
  this.pos = this


SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant/node_modules/yauzl/index.js:3:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
habitrpg@3.0.0-alpha /vagrant
`-- (empty)
```

PS: I'm using Virtualbox version  5.0.16_RPMFusion r105871 which _should_ be fine?

**Comment by Alys** [comment]
I'm using Virtualbox version 5.0.18 r106667 (on Mac OS), which is slightly ahead of yours. I'm not sure if upgrading yours will help, but from memory, upgrading it is easy, so it's probably worth your time to try that.

> (Not sure if relevant: just git pull'd which changed a lot in migrations/api_v3/users.js.)

I don't think it will be related to this problem. 
You can expect frequent large changes while it's under development.

Can you please show us the full output of `npm install`? Also show us the full output of the first part of the vagrant installation process if you still have it. [Gist](https://gist.github.com/) is good for uploading large text blocks, if you don't have another preferred site for that.

**Comment by crookedneighbor** [comment]
Just an FYI, v3 is not using Node 5. It's using Node 4.

**Comment by Alys** [comment]
Ah, so sorry about that, @nasfarley88! Your original method of `sudo npm install -g npm@3` was correct. :(

Still show us the full output once you've changed back to node 4 and rerun npm install.

**Comment by natfarleydev** [comment]
No problem, I'll re install properly tonight and post the logs. Anything else useful I should grab?

**Comment by Alys** [comment]
@nasfarley88 If you can get all the output from the entire local install process, that should help. I can't think of anything else.

**Comment by natfarleydev** [comment]
Log files: https://gist.github.com/nasfarley88/87158b0e731fb8bd25923a3ef97d409d

They are all named after their commands so it should be pretty obvious what they are (except `npm-debug.log`, that was just outputted by npm).

**Comment by Alys** [comment]
Links to the specific files, since they're huge:
- [vagrant_up_--provider_virtualbox.log](https://gist.github.com/nasfarley88/87158b0e731fb8bd25923a3ef97d409d#file-vagrant_up_-provider_virtualbox-log)
- [sudo_npm_install_-g_npmAT3.log](https://gist.github.com/nasfarley88/87158b0e731fb8bd25923a3ef97d409d#file-sudo_npm_install_-g_npmat3-log)
- [npm_install.log](https://gist.github.com/nasfarley88/87158b0e731fb8bd25923a3ef97d409d#file-npm_install-log)
- [npm_install_2nd_time.log](https://gist.github.com/nasfarley88/87158b0e731fb8bd25923a3ef97d409d#file-npm_install_2nd_time-log)
- [npm-debug.log](https://gist.github.com/nasfarley88/87158b0e731fb8bd25923a3ef97d409d#file-npm_install_2nd_time-log)

The `vagrant up` output seems normal.

`npm_install.log` is showing this, which is the problem we need to fix:

```
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

> phantomjs-prebuilt@2.1.7 install /vagrant/node_modules/phantom-bridge/node_modules/phantomjs-prebuilt
> node install.js

/vagrant/node_modules/fd-slicer/index.js:145
  this.pos = this

SyntaxError: Unexpected token ILLEGAL
...
```

@nasfarley88 Can you open /vagrant/node_modules/fd-slicer/index.js in an editor and confirm that at line 145 after `this.pos = this` there's a lot of non-ascii characters, as in [my comment above](https://github.com/HabitRPG/habitrpg/issues/7082#issuecomment-211786520)?

Unfortunately, when I fixed that for my own install, it was by using npm 2 instead of 3, but that's not an option for the api v3 branch. :( We'll have to find some other way to fix it.

**Comment by natfarleydev** [comment]
Yep, I can confirm the non-ascii characters. Just renders as lots of `^@^@^@^@^@^@^@` etc. when looking at it with less.

**Comment by Alys** [comment]
@nasfarley88 I've been able to get a local install working with the api-v3 branch on a Ubuntu 14.04 non-virtual machine, although I had to increase my swapfile from 2G to 4G before it would work. I followed the usual process in [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally), using the Unix section, except that before doing the final `npm install` (in the "Install Habitica-Specific Requirements for Unix" subsection), I upgraded npm to version 3.8.9 and I deleted the node_modules directory that had been there from previous installation attempts.

The same process should work on the vagrant virtual machine if it has good enough specs, since it's a Ubuntu 14.04 machine. I had no luck at all with a 2G swapfile, so maybe adding a large swapfile to your VM will help you.
