### ISSUE TITLE
Mobile Website Doesn't Display All Tasks

### ISSUE THREAD

**Issue by CharltonFranklin** [HabitRPG/habitica#7089]
General Info
- UUID:f143cc7e-4a52-42ff-9f23-88864452f6a1
- Browser: Chrome for Android
- OS: Android 6 .0 .1 
### Description

[//](#): # I launch the game by using a bookmark to the mobile site. This issue happens with or without the bookmark. Not all my tasks are displayed including habits, dailies and to do items. This happened after testing in the inn, which I'm unsure if that is related. Due to mobile app feature limits, I prefer the mobile site. I will try finding a way to clear cache to see if that resolves the issue.

This is from the mobile website. Pay attention to the habits.
![screenshot_20160416-074441](https://cloud.githubusercontent.com/assets/6109113/14581670/44bb870e-03a7-11e6-9964-aa047ad95d42.png)

This is from the mobile app. As you can see there are a lot more habits.
![screenshot_20160416-074556](https://cloud.githubusercontent.com/assets/6109113/14581684/98a6bb22-03a7-11e6-8ede-b23ba5ba81ce.png)

**Comment by CharltonFranklin** [comment]
Clearing cache did resolve the issue.

**Comment by crookedneighbor** [comment]
Thanks for reporting it. Going to close this now since there are no actionable items for this.

**Comment by Alys** [comment]
@charltonfranklin Only some of your tasks were displayed because a tag was active. Clearing the cache cleared the tag selection, but you could also do that by clicking on the "clear" button next to the tags, or by clicking on the tag itself to unselect it. You can learn more about tags on the wiki at http://habitica.wikia.com/wiki/Tags
