### ISSUE TITLE
Header Markdown issue

### ISSUE THREAD

**Issue by MidnightsWaltz** [HabitRPG/habitica#7106]
General Info
- UUID: 13bedd29-a7c2-4166-ae06-787c952075e6
- Browser: Chrome
- OS: Windows 8.1

Only one of the header markdowns have worked the last couple days:

![problem with hrpg 2](https://cloud.githubusercontent.com/assets/18617093/14746229/366f0dac-0874-11e6-8472-3500b3437cb6.jpg)

I have tried deleting & creating new ones, but that didn't work.

**Comment by crookedneighbor** [comment]
The markdown parser we were using was susceptible to an xss attack, so I had to switch it out. As a result:

``` mrkdown
#not a valid heading
# a valid heading
```

I'm working to reinstate the old behavior with the new module, but for now, you can just switch your task names to include a space between the `#` and the text.

**Comment by MidnightsWaltz** [comment]
I was 99% sure that I had tried that, apparently I was wrong.

That got it, thank you!

**Comment by ghost** [comment]
/raises hand 
This is more of a suggestion than an otherwise-useful comment, but I'm pro- hashtags-with-spaces. It would take the occasional explanation perhaps, especially since it's been without spaces so long, but I suspect it would reduce to approximately zero the instances of accidentally-huge posts that come from users trying to post a hashtag or wanting to use it as, you know, a number symbol (such as in the Challenge Accepted guild, or people talking about numbers of books read in a challenge, etc.) .

**Comment by crookedneighbor** [comment]
We discussed it internally @Cantras and have decided that is the direction we're going to take. Thanks for chiming in!

**Comment by ghost** [comment]
@crookedneighbor @paglias 
reporting [suggestion from a linguist on Transifex](https://www.transifex.com/habitrpg/habitrpg/translate/#pl/loadingscreentipsjson/88780307) somehow connected to this issue:

[loading screen tip 4](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/loadingScreenTips.json#L6) `Use the # sign before a task name to make it really big!`
might benefit from an example as `#Task` and `# Task` won't work the same while some users think of hashtags-without-spaces by default
