### ISSUE TITLE
Attack 2 times on the boss per day.

### ISSUE THREAD

**Issue by sujunmin** [HabitRPG/habitica#7117]
General Info
- UUID(me): ac6fbe37-b0dc-40d8-ba14-77dde66fbfa8
- UUID(xiamo): 27227345-eb10-4aa8-ba15-3e8e5d4e25e1
- Browser: Firefox 45.0.2
- OS: Ubuntu 16.04 LTS
### Description

We got 2 lines in team chat log for one player who attack the boss.

![2016-04-27 10-55-31](https://cloud.githubusercontent.com/assets/6415168/14840412/a77b9bd2-0c66-11e6-9d4a-811a648dab8b.png)

So once this play online, all the team will lose more hp.

Please help to solve this problem.

**Comment by Alys** [comment]
@sujunmin I've looked into this, and I'm not certain there's a problem, but there might be and I'm going to keep investigating.

Below are the times for all of the attacks that xiamo has done in the current quest, and the final blow xiamo cast in the previous quest. The times will probably be reported in a different time zone than the one you are in, so they might look wrong, but they do accurately show the gaps between xiamo's attacks.

2016-04-27 11:25:28
2016-04-26 10:39:01
2016-04-26 01:01:01
2016-04-24 15:07:05
2016-04-24 01:36:52
# new quest started
2016-04-22 09:43:01

It does look like there's sometimes two attacks in one day, but that might be misleading. The attack messages appear when a player uses Habitica for the first time each day. If xiamo doesn't use Habitica at all until very late in one day, and then uses Habitica very early the next day, then the two attack messages will appear close together, but there is still only one attack per day. So that might be what was happening.

Alternatively, there could be a problem if xiamo uses Habitica on two or more PCs or mobile phones or tablets that have different timezones. There's no signs at the moment that that's a problem, but it might have been happening before today.

Can you please ask xiamo to check all of the PCs and mobile devices that xiamo uses Habitica on, and make sure they all use the same time zone?

For the next couple of days, I'll keep watching xiamo's account to monitor the time zone and daily restart time (the cron time).

For my reference:

```
"preferences": {
    "dayStart": 6,
    "timezoneOffset": -540,
    "timezoneOffsetAtLastCron": -540
},
"lastCron": "2016-04-28T08:14:47.197Z",

Thu Apr 28 19:49:45 AEST 2016
```

**Comment by sujunmin** [comment]
Hi @Alys , I‘ve chatted with xiamo at team chat room, he said he had changed time zone 15 days ago by using only one device, but this problem was happend some days ago, he thought it should be happend when he just changed the time zone, not after some days. By the way, he will use another new device to help test.

**Comment by Alys** [comment]
For the past three days, I've been monitoring xiamo's daily reset (cron) times and the time zone recorded in his Habitica account. 

I can see that his time zone hasn't changed at all in those days, which means that it's very unlikely he's having trouble with cron running at the wrong time.

The times of his daily reset are variable:

2016-04-30 10:19:46
2016-04-29 14:47:30
2016-04-28 08:14:47
2016-04-27 11:25:28
2016-04-26 10:39:01
2016-04-26 01:01:01
2016-04-24 15:07:05
2016-04-24 01:36:52
# new quest started
2016-04-22 09:43:01

Those times won't be in his time zone.

This probably just means that each day he starts using Habitica at a different time. If he uses Habitica late in one day and then earlier in the next, it could look like he's attacked the quest boss twice in one day, when really it is two separate days.

If you're aware of any other information that does indicate that there's a bug, please tell us!

**Comment by sujunmin** [comment]
I chatted with xiamo today, and he said he got right attack time after he changing his device playing habitica, but he still thought that is the services bug XD. I thought there was no evidence or findings for this issue, this issue might be closed, thanks.
