### ISSUE TITLE
Left the Tavern but still not dealing damage

### ISSUE THREAD

**Issue by jlreeve** [HabitRPG/habitica#7121]
General Info
- UUID: 97a88169-776d-4681-9f9f-9f7a9b974eee
- Browser: Chrome
- OS: Windows/Android
### Description

I rested in the Tavern for the weekend (I think on my Android app) and left it on Monday (both web and app show that I could enter the Tavern now), but I haven't dealt damage in party quests for a couple of days now. I did cast spells which were logged in the party chat however. Looking at the data agrees with what I think I did.

**Comment by Alys** [comment]
@jlreeve Your party doesn't have an active quest (it's still pending all the invitations being accepted). 

For any previous quest, you might not have been a participant or it might have ended before you were able to do damage to it. I can't tell from the information remaining in the database, but I can tell that you've accepted the invitation to the current quest, and at the moment there's no signs in your account or in the party of anything that might stop you doing damage.

I'm closing this now, but if it turns out that you don't do damage to the new quest after it's started, please comment here again!
