### ISSUE TITLE
Sticky Posts in Tavern 

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7123]
Often there are messages that are useful to convey to new users who come to the Tavern, such as explanations about common bugs or answers to frequent questions. It would great if moderators and staff members had the ability to pin a sticky post to the top of the Tavern, so that it would be the first message that people saw regardless of when it was posted.

**Comment by Alys** [comment]
It would be great if this could be done in a way that allowed it to work in the mobile apps (and any third-party tools) too. For example, it could be done by resorting the chat array so that the pinned posts were always at the top of the array. An extra attribute on the pinned posts could be added to allow for custom formatting.

Any method of solving this issue would probably require changes to code that's being modified for the API v3 rewrite, so before any coder works on this, comment here to describe what you're thinking of doing, and then wait a day or two to see if our API v3 programmers have any comments.

**Comment by paglias** [comment]
Adding pinned posts at the top of the array is going to be a breaking change and will lead to unexpected consequences. I would lean toward an array of pinned posts ids stored in the group model

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
Should this still be on hold?

**Comment by Alys** [comment]
I'm marking this as suggestion-discussion.

I'd very much like to see this implemented, and for guilds as well as the Tavern. The Report a Bug guild would benefit from a pinned post at the top of the chat right now - it would be more obvious than the description and there's up-to-date information we could put in it.

If we wanted only a single sticky post (rather than an unlimited number of sticky posts  per guild), then it wouldn't need to be implemented as a chat message in the back end, even if it was displayed in a way that made it look like a chat message on the front -end. That would overcome the problems mentioned above about sorting the chat array.

One option is that we could re-use the `leaderMessage` field, now that it's no longer in use on the new website/apps. In fact really this feature would bringing back the leader message, but with different formatting. I think there's still a good case for allowing a custom message pinned at the top of the chat area.

**Comment by lemoness** [comment]
We definitely still want this feature. I'm adding it to the list of things that need a design and updating the label accordingly.

**Comment by Alys** [comment]
I'd like to see this implemented using the old `leaderMessage` field, which could be used exactly as on the old site but formatted so that it looks like a chat post fixed to the top of the chat area. That would be significantly easier to code than trying to display an actual chat message out of its natural order.

**Comment by librarianmage** [comment]
@Alys Perhaps it should be an array? Then multiple messages can be stickied.

**Comment by Alys** [comment]
I'm not opposed to that, although I like the simplicity of one message field that the group leader can customise as they wish with markdown, which also has the benefit of already having support in the database and some of the code. :)

**Comment by TheHollidayInn** [comment]
I'd like if we implemented separating out chat messages into their own model first. Then we can have a "sticked" field or maybe a sticky cache.

**Comment by lemoness** [comment]
FYI @Tressley

**Comment by veeeeeee** [comment]
We're going to explore different ways of accomplishing this that would preserve user experience and allow more users to view critical information (since only a fraction of users will even visit the tavern).
