### ISSUE TITLE
Party member received NaN quest items

### ISSUE THREAD

**Issue by kalmduck** [HabitRPG/habitica#7129]
General Info
- UUID: 9219a210-e771-4a3e-91ac-65914c3a17ec
- Browser: Safari
- OS: El Capitan
- Party ID: bff1392a-f42f-4901-b9f9-f4d522e69858
### Description

When one of my party members did their cron, they received NaN testimonies for the Golden Knight Part 1.  This resulted in finishing the quest immediately, which was a little unexpected because we were around 20/300 testimonies needed.  This just seemed a but buggy, and I thought somebody might want to know about it.

**Comment by Alys** [comment]
Thank you very much for reporting this! We've seen this happen before but only under well-understood circumstances when we know of a specific problem that has caused it. Finding it seemingly randomly like this is new and I'm glad we know about it!

I'm sorry your quest ended prematurely. I know that can feel like a demotivating anticlimax. I've given four gems to you and that party member to buy replacement quests of your choice.

uuid 52225cdf-88a7-4b35-a306-764d16259748

**Comment by Alys** [comment]
Data extracted from user 52225cdf-88a7-4b35-a306-764d16259748, from a backup made before the cron reported here:

```
    "party" : {
        "quest" : {
            "RSVPNeeded" : false,
            "progress" : {
                "collect" : {
                    "testimony" : NaN
                },
                "down" : 0,
                "up" : 44.205781567534316
            },
            "completed" : null,
            "key" : "goldenknight1"
        },
        "orderAscending" : "ascending",
        "order" : "level"
    },
```

This has happened before, also under unknown circumstances: https://github.com/HabitRPG/habitrpg/issues/5882

That's the only other occurrence I can find, excluding those that happened from bugs we understand (e.g., the time when a guild quest was started accidentally and it overwrite the party.quest information for many players; in that case their data wasn't like `"testimony" : NaN` but instead was a finite number of found items where the item type was wrong for the quest that the player was in).

This bug is rare enough that it's not urgent and I'm going to put it on hold until version 3 of Habitica's API is released, which won't be long now. We'll investigate after that because it's possible that the improved code in API v3 will have removed the bug.

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/pull/7570
