### ISSUE TITLE
Cannot Connect to Server Errors

### ISSUE THREAD

**Issue by jtgithub2016** [HabitRPG/habitica#7134]
General Info
- UUID: e44e6069-2e30-49cf-ab49-db41d3134045
- Browser: Vivaldi 
- OS: Windows
### Description

I am getting a lot of "cannot connect to server" errors when I try to click on good habits, check off to-dos or dailies, etc.  This problem has become much more frequent in the last 48-72 hours.  I am located in PR China - I don't know if this is a Great Firewall issue.  Logging off and logging back on does not seem to help.  Logging back on can actually be difficult because there are many long delays after I click on the "Play Habitica" button and I need to refresh several times before the login screen pops up and after clicking login, there are additional delays.

**Comment by Alys** [comment]
@jtgithub2016 There might not be much we can do to help if it is due to the Great Firewall. :(

We have https://github.com/HabitRPG/habitrpg/issues/6700 for tracking the server errors that occur sometimes for many users, but there's been very few of them lately so your issue might not be related to that.

Do you have any other browsers that you can use? If so, do you have the same problem on them?

Vivaldi is a browser that we haven't seen before, so it's possible that it isn't compatible with Habitica. I'm about to start using it myself to look into that  (and because it sounds like an interesting browser and I'm curious about it 😄  ).

**Comment by crookedneighbor** [comment]
Vivaldi is based on Chromium, I believe. So it should be fine.

**Comment by jtgithub2016** [comment]
Thanks much for the quick response.  Things seem better this evening.  I
got one Gateway timed out message, but I think hitting reload fixed it.  I
don't know if the Great Firewall is affecting Habitica, but in case you all
are not familiar with the GFW, it is not a constantt thing.  For instance,
using VPN software at my home is normally ok, but around times of political
sensitivity or instability, it can become radically more difficult.  Or the
same VPN software may not work in a different part of the country.  I know
previously, I had the impression that the GFW was blocking the data page,
but that was about 1.5-2 months ago, and doesn't seem to be a problem
anymore.

Habitica was causing Firefox to crash several times a day, but since I
switched to Chrome and now Vivialdi, I don't have any crash problems.
Habitica seems to load more slowly on Vivaldi, but I've been sticking with
it for IDK what reason.  :P

**Comment by Alys** [comment]
Vivaldi has been very responsive for me so I'm no longer suggesting it might be causing the problem. :) It's a nice browser.

When you get the server errors, could you check in the Console to see if there's any error messages and tell us what they are? Ignore the warning that says "Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779"

**Comment by Alys** [comment]
Oh and thank you for the information about the GFW. That's good for us to know.

**Comment by Alys** [comment]
Have you been getting any errors recently? If so, was there anything in the Console?

**Comment by SabreCat** [comment]
I've been using Vivaldi for Habit myself lately, and it seems to work at least as well as Chrome. There is one issue where running Habitica in one of Vivaldi's "web panes" is missing some functionality because it doesn't display Javascript confirmation or alert boxes--but we intend to clean those out in favor of homegrown modals already.

**Comment by TeresaEllis** [comment]
I don't know if this is the right thread, but I am also getting a "can't connect to server" or "timed out error".  I just started two days ago and the first day was fine.  I can still get HabitRPG Metro to work, but when I go online, nothing finishes refreshing.  I have tried using Firefox and Microsoft Edge and both have problems, where neither did the day before.  I also signed my son up for an account half way through the second day.  The program worked for both of us alright at first, but I started seeing difficulties when I tried to add him to my party for a quest.  I don't know if that could have caused it, but that is when I notice the problem. 504 gateway time out is the error that shows up when I try to refresh.

**Comment by Alys** [comment]
@TeresaEllis Do you have any programs or services on your computer or on network devices in your home that might be blocking access? For example, do you use a proxy server or software like Net Nanny‎ that blocks access to websites that aren't on a child-safe whitelist? By the way, if your son is younger than 13, could you please read the "Legal Requirement" section at the top of [Children Using Habitica](http://habitica.wikia.com/wiki/Children_Using_Habitica) on the wiki?

**Comment by TeresaEllis** [comment]
My son is 13, so that shouldn't be the problem.  I can't find any program or service that would block Habitca and my account isn't refreshing either.  As I say, I can use HabitRPG Metro, which is nice or I wouldn't be able to use the program at all and I really like it.  I am staying on task better than I have with anything else.  It is when I go online or when my son goes online where the 'error 504 gateway timeout' crops up.  I even tried turning my computer off and then on again to see if it was something that needed to be cleared.
*****_New information**_****
I found that Google Chrome works with Habitica and so I will use that to go online to use Habitca.  I tried tinkered with Kapersky private browsing to see if that helped me get through on Microsoft Edge or Firefox, but it didn't change anything in a useful manner.

**Comment by jtgithub2016** [comment]
Lately, I've been having trouble getting my Party's status to update?  For
example, if we finish a quest, I need to log off Habitica, close the
browser, re-launch the browser, and then log back in.  At least that's what
I've been doing.  Simply closing and re-launching the browser doesn't
work.  It's possible logging off and back on might be sufficient, but I
haven't tried that.

Same problem crops up when I issue a quest invite to the party.  It doesn't
show as having been issued, and when I try to re-issue, then I get an error
message showing that my team is already on a quest.

This is with Vivaldi (v 1.2.something something) on a Windows machine.

**Comment by Alys** [comment]
@jtgithub2016 Are you seeing "Cannot connect to server" errors? If not, can you please copy your comment to this issue: https://github.com/HabitRPG/habitrpg/issues/7578 
Please also tell us there if you've tried reloading and if so, what effect that has.
