### ISSUE TITLE
Loss of Gems

### ISSUE THREAD

**Issue by jtgithub2016** [HabitRPG/habitica#7135]
General Info
- UUID: e44e6069-2e30-49cf-ab49-db41d3134045
- Browser: Vivaldi
- OS: Windows
### Description

This morning, I lost about 9 gems.  There may have been a loss of gold, XP, or MP as well, but the gems are what I particularly noticed.  It seemed like I was getting delayed "credit" for failure to complete a task or something, but I wasn't aware this could impact my gem count.

**Comment by Alys** [comment]
It's likely that you experienced the bug https://github.com/HabitRPG/habitrpg/issues/4313 in which your browser holds on to data in local storage instead of sending that data to the server for permanent storage. When your browser later syncs to the server, the data it was holding is often lost - i.e., the unsaved changes that you could see in your browser are reverted (although sometimes they are reapplied after the newest data from the server is received). In this particular case, it looks like some actions to mark tasks as completed might not have been saved (so you saw the rewards from them being taken away when the actions were reverted), and also possibly your recent purchases of gems using gold were reverted. Had you recently bought about 9 gems? I've added them back to your account.

**Comment by jtgithub2016** [comment]
Yep - all set.  Thanks much.
