### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by RichardSkolek** [HabitRPG/habitica#7139]
Hello, I cannot log in to Habitica. The buttons "Play Habitica", "Join for free" and "Gamify your life" don't do anything. When I used it two days ago, everything worked fine.
I tried to clear cookies and local storage and it didn't help.

General Info
- UUID: f37656d7-db29-42b7-9859-1ac8d6ee59aa
- Browser: Firefox
- OS: Windows 10

Any help would be appreciated.

**Comment by Alys** [comment]
Please go to https://habitica.com/static/clear-browser-data and click the button you'll see there, and then clear your cookies again. Are you able to log in after that?

If not, please try incognito / private mode in Firefox, and if that fails too, try another browser - Chrome if at all possible.

If it doesn't work in Chrome, open the JavaScript Console and copy-paste the contents of it for us. Let us know if you need advice about how to do that.

**Comment by RichardSkolek** [comment]
Hello, nothing worked with Firefox, but I was able to log in with Chrome and Internet Explorer. However, that does not really solve my problem - I would like to continue using Firefox.

**Comment by Alys** [comment]
Yes, no worries, we're happy to help troubleshoot Firefox, we just needed to know first where the problem lies. It's unlikely to be with your account since it works in other browsers, so there's probably something wrong with Firefox itself.

Reboot your PC just in case there's something weird going on that a reboot will fix.

Then start Firefox and disable all extensions without exception (you can turn them back on later, but for now we need to have every extension turned off). If you still can't log in, open Firefox's JavaScript console and show us everything that appears in it.

**Comment by RichardSkolek** [comment]
Hello, thank you for your help. I have fiddled with Firefox in the meantime and I am not sure what I did, but all works fine now. Well, everything seems to be in a default setting with most of my information gone, but Habitica works:). Thanks!

**Comment by Alys** [comment]
"Well, everything seems to be in a default setting with most of my information gone"  -- Is it a level 1 character with no personalised tasks? If so, you've created a new account accidentally. You can go to Settings (the gear-shaped icon) then Site to delete it (red delete button at the bottom right of the page).

If it's your same account but some tasks are missing, click the "clear" button next to your tags and delete any text in the search box above the Rewards column.

Tell us if you're still missing information!

**Comment by Alys** [comment]
I'm closing this now but if you'd like more help with missing tasks, see my previous post and comment here. We'll still see your reply and can reopen this if necessary.
