### ISSUE TITLE
Suscription gone after about a week

### ISSUE THREAD

**Issue by Amphara** [HabitRPG/habitica#7140]
General Info
  UUID: 9b520b7f-b3ae-4968-a515-a694ee58f94e
  Browser: Chrome
  OS: Windows 10

Description: After about seven days my subscription has gone. And no I don't how to fix this problem without buying a new one. 
Besides, I'm not sure if I received the correct number of mystic hourglasses. But I am not able to look it up at the moment, for I don't have a subscription at the moment. 
(Sorry for my bad English. I am not a native speaker :)

I hope you guys can help me with my problem(s).

**Comment by Alys** [comment]
I'm so sorry about that! That's very odd. Do you still have the receipt that you were sent by email when you made the subscription, if so, please forward it to admin@habitica.com. We can use that to put your subscription back the way it was.

If you don't have the receipt, can you tell us whether you used PayPal or Amazon or a credit card to make the subscription, and also what email address you use to sign up to that service (or what address you entered when you gave us your credit card details)? Email that information to admin@habitica.com - don't write it here because anyone can see it here!

**Comment by Alys** [comment]
Email received. Will deal with this solely by email now.
