### ISSUE TITLE
"Crazy" page after open Habitrpg webpage

### ISSUE THREAD

**Issue by Rohlik** [HabitRPG/habitica#7152]
General Info
- UUID: abf7a2d4-caf0-4a98-b053-49313e8fc262
- Browser: Chrome, last version
- OS: Win 8.1
### Description

Something when I open Habit web page I get this:
![habbit](https://cloud.githubusercontent.com/assets/2051154/15096937/a3afb228-150c-11e6-88f6-7ef7db5548c9.PNG)

After F5 is everything OK. I can´t reproduce this bug.

**Comment by Alys** [comment]
When that happens, it's because your browser hasn't downloaded all the files it needs from the server, or it has stored incomplete or corrupted data for your profile. It is almost always fixable by reloading the page, or by logging out and logging back in. If you're unable to log out, you can go to https://habitica.com/static/clear-browser-data and click the button that you'll see there, which will log you out.
