### ISSUE TITLE
Update Press kit

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#7174]
Similar to #5906, the press kit should probably updated to include Android screenshots (if other people get the pictures, I wouldn't mind putting them in :wink::wink:)

@lemoness @Alys @crookedneighbor

**Comment by librarianmage** [comment]
It might also make sense to look into a different way of displaying the images. It currently looks rather cluttered, and the page currently has a (deactivated) carousel like thing in it.

**Comment by lemoness** [comment]
I agree!

How about these images? 
![android screenshot2](https://cloud.githubusercontent.com/assets/3494081/15235458/50c2dfd8-1870-11e6-90f1-109b30cc17e2.png)
![android screenshot4](https://cloud.githubusercontent.com/assets/3494081/15235461/50e852a4-1870-11e6-858c-200ca6f36a58.jpg)
![android screenshot6](https://cloud.githubusercontent.com/assets/3494081/15235463/51129ae6-1870-11e6-8f31-74e55647f105.png)
![android screenshot7](https://cloud.githubusercontent.com/assets/3494081/15235460/50d89436-1870-11e6-9b87-3730ba6cf9df.png)
![android screenshot5](https://cloud.githubusercontent.com/assets/3494081/15235459/50c98338-1870-11e6-9965-0cc71ee02776.png)
![android screenshot1](https://cloud.githubusercontent.com/assets/3494081/15235462/50ebb11a-1870-11e6-800f-df211e9439d0.png)

It would also be nice to include the Habitica promotional video.

**Comment by librarianmage** [comment]
@Lemoness where would I find that?

**Comment by lemoness** [comment]
It's here: https://www.youtube.com/watch?v=hgdeJnSili0

**Comment by librarianmage** [comment]
@lemoness The main changes are done, but it still doesn't look great. Some potential things to think about are:
- Change Position of Download Button - It being inline with the download text looks rather jarring and out of place
- Add links to Images?
- Change Image Size - Some of the more important pictures, like the website sample screens, are smaller than, say, the app icons
- Image Presentation - having them in a line on the far left of the screen looks rather unbalanced
- Image Preview - being able to click on an image and have it displayed larger might make looking at the images easier
- Captions / Titles

**Comment by lemoness** [comment]
A very thoughtful list of changes!
1. I agree. It would be nice to have this be larger and more prominent.
2. I don't think we need to add links to images, since these are images for
   journalists to download, but if there are any that you feel would benefit
   in particular from a link, let me know.
3. Another good comment! Do you need separate files from me?
4. I absolutely concur. It would be nice if they were grouped into
   sections. Possibly Logos, Promotional Art, Website Screenshots, iOS
   Screenshots, and Android Screenshots? If individual images could be
   displayed next to each other within their section instead of in a vertical
   line, that would look good, too.
5. I am a fan of image previews!
6. I don't think these are essential, but they'd be a nice touch. Let me
   know if you need titles for any of the images.

**Comment by librarianmage** [comment]
@lemoness I would like the separate files, please.

**Comment by lemoness** [comment]
![challenges sample screen](https://cloud.githubusercontent.com/assets/3494081/15953049/30393d0e-2e7b-11e6-918d-e73308b096d6.png)
![guilds sample screen](https://cloud.githubusercontent.com/assets/3494081/15953050/3046ff34-2e7b-11e6-9269-3fc6bdba99cd.png)
![market sample screen](https://cloud.githubusercontent.com/assets/3494081/15953058/58097632-2e7b-11e6-895a-b91d97f59e11.png)
![equipment sample screen](https://cloud.githubusercontent.com/assets/3494081/15953089/b4c883cc-2e7b-11e6-91ec-28c9de3e1d2e.png)

It will take more time to replace the task page screen, unfortunately, but let me know if those files work better.

**Comment by librarianmage** [comment]
@lemoness Thanks! I will replace the images and see if they will work better

**Comment by librarianmage** [comment]
Actually, the original images look better
