### ISSUE TITLE
Dailies tasks left from previous month challenge

### ISSUE THREAD

**Issue by Elythingol** [HabitRPG/habitica#7185]
General Info
- UUID: dde908b3-dbb7-46ce-9a9b-dcb4d58f1347
- Browser: Google Chrome Version 49.0.2623.112 m
- OS: Windows 8.1
### Description

I have dailies tasks left from previous month challenge.Currently, i don't have active challenges.

![screenshot_14](https://cloud.githubusercontent.com/assets/7562146/15175534/75cad76a-176f-11e6-9c6e-1bae5c81a0a0.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/7562146/15175533/75ca394a-176f-11e6-89c9-99e859577bad.png)

**Comment by Alys** [comment]
@Elythingol Sorry about this! It's an example of this bug: https://github.com/HabitRPG/habitrpg/issues/2763

Please see the information in bold in the first post in that bug report.

I'm closing this now since we already have it reported, but if you need help after following the steps from that bold section, you can comment either here or in that bug report.
