### ISSUE TITLE
Redoing tasks glitch

### ISSUE THREAD

**Issue by Thornclaw9000** [HabitRPG/habitica#7190]
It is possible for you to gain free mana/drops/xp/coins by pulling out undone things and redoing them over and over andover until you hit critical. Also, you gain free mana/ coins because those values cannot benegative. Someone could do this on a highly valuable task and level up really quick. Please fix this.

**Comment by Alys** [comment]
We're aware of this and we don't mind if people do this kind of "cheating" because it doesn't affect anyone except the player who does it. In fact, repeatedly unticking and ticking the same task is recommended as one way of implementing a "Wishing Well" (https://github.com/HabitRPG/habitrpg/issues/4626#issuecomment-72838554 ). Also if people want to level up quickly, they can do so much more easily using [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values).
