### ISSUE TITLE
Recent account loss issues

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#725]
A few people have chimed in today having experienced potential account loss. Similar issues are #459 #268, but those should be fixed by now. Creating this ticket here to gather some follow up information.

Divana

> Hello Tyler~ My HabitRPG chrome extension was just updated recently -which is all find and dandy- however all of my information was _completely_ scrapped. Not a single bit of my data was left over from the update. TT~TT Even my party was disconnected; I can no longer see my party member's avatar. I am very saddened by this as HabitRPG has actually done a lot to improve my lifestyle and I would hate to see all of my progress gone. I was using my Facebook to login to the extension.

Wine Guy

> Same thing happened to me. Using chrome on Windows Vista. Chrome version: Version 25.0.1364.172 m
> HabitRPG doesn't even recognize my username.... and it won't let me apply for a new password.

Questions for both of you: when did you sign up? When did you experience this issue? Do you have your user ids or emails handy that you can [send to me](mailto:tylerrenelle@gmail.com)?

**Comment by lefnire** [comment]
ok, wineguy's was a wrong username. Waiting to hear back from Divana

**Comment by dmagracia** [comment]
Hello~ My name is Divina and I wrote about the Account loss issue before.
I used to sign in with my Facebook account however just the other day my HabitRPG looks like the Beta (I don't remember switching), has a new UserID and API, and all of my stats and progress are gone. My UserID used to start with 8b32be40 but now it starts with 508d2d48. 
I'm particularly worried since tokens are supposed to come in soon and I'm using the wrong account/UserID right now. My friend who was in my party no longer can see me either.

**Comment by dmagracia** [comment]
I also signed up quite a while ago... I don't recall the exact date but it was before the party system was established.

**Comment by lefnire** [comment]
Some of the original players (sounds like you're one) were effected along time ago by [this](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found). It's no longer happening, but some players get hit much later since their login session doesn't get invalidated for 2months or so. Follow [these](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found) instructions and email me something unique to find you by

**Comment by lefnire** [comment]
solved this offline with both
