### ISSUE TITLE
[API v3] When creating a challenge no group is selected by default

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7253]

**Comment by Memry** [comment]
I also noticed that the list of guilds dropdown is not limited to guilds I am a member of.  It won't let me create a challenge in another guild, but it was difficult to find a guild I could create a challenge in.

**Comment by ghost** [comment]
I confirm that a lot of guilds are showing up when creating a challenge, guilds that I'm not part of. But maybe this should be reported as another issue ?

**Comment by TheHollidayInn** [comment]
I will fix this. The multiple guild issue is filed separately. Thanks!

**Comment by crookedneighbor** [comment]
Okay, I've tracked down why this is happening. Steps to reproduce:
1. start a party
2. create a challenge for that party
3. Leave a party
4. Notice that challenge from that party still exists in challenges list
5. create a challenge (get a javascript error since you don't have access to the group object for that challenge)
6. See that dropdown is not populated

Not sure what the correct behavior for this is. I _think_ it should be that if you leave or are kicked from a party or private group, you should automatically leave the challenge but keep the tasks.

**Comment by Alys** [comment]
I think it would be okay to have the kicked player left in challenges. There could be cases where the the group leader doesn't like the player, but the challenge creator has no problems with them. At the least, I don't think it matters if they aren't removed from challenges before go-live.

Perhaps in future we could add a remove-player-from-challenge option for challenge owners (that might be popular for those owners who track obvious cheating).

**Comment by crookedneighbor** [comment]
@Alys then we need to change the client code to handle the null group. It'd be easier to not allow a person that leaves a private guild or party to remain in a challenge, but if you feel strongly, we can write some workaround in the client.

**Comment by Alys** [comment]
Go with what's easiest!

**Comment by paglias** [comment]
Fixed
