### ISSUE TITLE
API v3:  Burst of flames 

### ISSUE THREAD

**Issue by CloJo** [HabitRPG/habitica#7265]
General Info
- UUID: 99463fab-e36e-4f8b-87f6-a6f925850ed8
- Browser:  Safari
- OS:  OSX Yosemite, v 10.10.5
### Description

[//](#): # Mage skill burst of flames appears to work, but returns error message "unable to cast on challenge task"  The mana for casting is returned upon sync.

**Comment by Alys** [comment]
The fact that you can't successfully cast it on a challenge task is actually one of the very few feature changes that this new code introduces. The idea is that skills which adjust a task's value (colour) can't be used on tasks from an active challenge so that it's easier for the challenge creator to judge the challenge using the values of the tasks.

However it sounds like that limitation only takes effect after you've tried to cast the skill on a challenge task. Ideally the user interface shouldn't make it look as if it's possible to cast it on that task. E.g., the task's border shouldn't go green when you hover over it after clicking on the skill. I'd consider this to not be a high priority to fix though.

**Comment by paglias** [comment]
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.

Regarding challenge task @Alys is right, but we should open a different issue for it.
