### ISSUE TITLE
Missing challenge. Can't leave, can't edit. 

### ISSUE THREAD

**Issue by Treegona** [HabitRPG/habitica#7275]
General Info
- UUID: 039fcf70-8eab-4c84-9ccd-8e9bf4d600f9
- Browser: Firefox 46.0.1
- OS: Windows 10
### Description

I joined a challenge about 2 months ago. I never received a notification that the challenge ended and the megaphone doesn't have a red background/doesn't seem broken, but when I look through the challenges page I can't find it -I searched for the challenges I'm participating in and it didn't show up. I can't remove the habits or the dailies, but I can't leave the challenge either.

**Comment by Alys** [comment]
@Treegona That challenge would have ended - sometimes when that happens, the notifications aren't sent to all players because of a timeout. For advice about deleting the tasks, please see the text in bold near the top of this issue: https://github.com/HabitRPG/habitrpg/issues/2763
Comment either here or there if you still have the problem after going through the steps that that links to.

Sorry about the confusion with the "API v3" issue that you originally commented on! We should have adjusted the bug report instructions to say that those issues should be ignored. I'll do that now.

**Comment by Treegona** [comment]
I found the problem, which was apparently my fault. The challenge was still open, but I couldn't find it because it was a newbies challenge and I hadn't realised those were excluded by the filter. Sorry for the trouble.

**Comment by Alys** [comment]
No worries! Thanks for letting us know!
