### ISSUE TITLE
Markdown support on all platforms

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#7335]
A number of issues have come up in some guilds about users wanting or needing to warn others about post content (spoilers, triggers in guilds where that is relevant). 

TWs or other warnings/content notes are less useful when the reader of a post can see all text in the post at once- as in platforms where messages show in their entirety or do not scroll, or in the case that the poster is not able to use markdown for line breaks because of the platform they are using to access the chat.

I have implemented some workarounds for now (asking users to use markdown when possible, asking those who may want to avoid some content to access the chat using platforms that support markdown/scrolling), but more markdown support (or another relevant solution) across platforms would help with this greatly.

**Comment by Alys** [comment]
@beffymaroo Now that markdown is in both the mobile apps, what do you need to improve trigger warnings?

**Comment by Alys** [comment]
We have [this issue](https://github.com/HabitRPG/habitica-markdown/issues/8) now for adding support for a spoiler tag (useful for trigger warnings too). I've also added a note about this in our plans for an upcoming renovation for the website. I'm closing this issue now because those two things should cover it.
