### ISSUE TITLE
Some emojis are missing

### ISSUE THREAD

**Issue by teles** [HabitRPG/habitica#7344]
General Info
- UUID: 616cdbe4-edd9-4cf4-8789-dbf2872ae97b
- Browser: Chrome
- OS: Linux
### Description

Some emojis are missing on habitica.
I'm trying to use some emojis from this [emoji cheatsheet](http://www.emoji-cheat-sheet.com/) but the emoji codes are not being turned into emojis.

It happens with the :octocat: emoji and emojis from doom game, just like :godmode: and :goberserk: .

I didnt take a look at the code yet, but I guess maybe the [emoji library](https://github.com/snicker/js-emoji) is not updated with new emojis.
#### Console Errors

None.

**Comment by Alys** [comment]
Oh great point! Our documentation on the wiki was outdated - we hadn't updated it since we started using that library.

I've just now modified the wiki's [Emoji](http://habitica.wikia.com/wiki/Emoji) page to state that we use the  snicker/js-emoji library, and that it provides many, but not all of the emoji from the Cheat Sheet.

Thank you for pointing that out!

**Comment by crookedneighbor** [comment]
@Alys It doesn't use snicker-js anymore. 

Also, those emojis demonstrated aren't standard emojis. They are Github specific.

**Comment by ghost** [comment]
is it difficult to have a page listing all the emojis (with codes) supported by Habitica?

**Comment by crookedneighbor** [comment]
https://github.com/HabitRPG/habitica-markdown/blob/master/plugins/data/unicode-emoji.js 

😄

**Comment by Alys** [comment]
Oh, sorry!  snicker-js is still listed in bower.json and I had forgotten the details of the emoji change. I'd editing the wiki page again. :)

**Comment by crookedneighbor** [comment]
It's only in bower for making the chat extension not error immediately https://github.com/Horacious/HabitRPG-Chat-Extension/pull/40#issuecomment-214967878

**Comment by teles** [comment]
Thank you guys. @crookedneighbor, according to emoji-cheatsheet all listed emojis are supported in many websites besides github.
Is there an official emojis list which we can use as habitica emojis?

**Comment by Alys** [comment]
@teles The link @crookedneighbor posted contains the full list, and I've copied that link to the wiki's  [Emoji](http://habitica.wikia.com/wiki/Emoji) page.

**Comment by teles** [comment]
Thanks @Alys.

**Comment by ghost** [comment]
It seems like some emojis are really missing after migration. E.g. I'm begging to bring :bomb: back

**Comment by crookedneighbor** [comment]
We decided to remove :bomb: and :gun: from the emojis list after some inappropriate uses of the gun emoji in some guilds. 

Personally, I think we should reinstate them and just flag any chats that use them inappropriately, but I'll let @lemoness and @alys make the call on that as it is a community issue. 

In better news, we added some of Github's non-standard emojis. (Basically just left out the doom game ones)

**Comment by ghost** [comment]
Thank you for clarification! I'm really used to using :bomb: to highlight super strict deadlines or deadly habits I have real troubles fighting with - I tend to associate both cases with explosions, and I will find it difficult to replace the emoji...

**Comment by brightbold** [comment]
Yeah, I'm here too because my tasks with 💣 are now broken. I agree with @crookedneighbor that I'd prefer to see inappropriate use of emoji in chat handled the same way we handle inappropriate language. Habitica doesn't censor curse words in my tasks (and, yeah, sometimes there are curse words in my tasks), but if I use them in the Tavern or a guild where they're prohibited, my post will be reported and deleted. I don't see why emoji should be handled differently.

Also, the link to [Habitica emoji](https://github.com/HabitRPG/habitica-markdown/blob/master/plugins/data/unicode-emoji.js) posted above is now resulting in a 404. Is there a place we can see the currently supported emoji?

**Comment by crookedneighbor** [comment]
I just refactored the emoji stuff into its own module. I plan to put together a cheat sheet specific to Habitica soon.

**Comment by crookedneighbor** [comment]
I think y'all made good points. We've decided to reinstate both emojis. We will look into other options for chat.
