### ISSUE TITLE
Item bought from armoire disappeared overnight

### ISSUE THREAD

**Issue by bdecesare** [HabitRPG/habitica#7358]
Hello,

I received an item bought from the Enchanted Armoire yesterday (a lasso) and I had equipped the item during the day and then logged off around 5pm PST. As of this morning I no longer have that item and my old gear is now equipped.

Can I please get the item restored?

Thank you

General Info
- UUID: e47cf3d2-4b92-40fc-9ffc-b29058788891
- Browser: safari
- OS: Yosemite Max OSX

**Comment by citrusella** [comment]
Had it been awhile since you synced when you used the armoire? You might have gotten something else, including experience or food. (That's a known bug.) You could go into Fix Character Values and add back the gold you spent if you feel it unfair. (It's possible someone might restore the item, but this is the advice I always see being given as well, so I figured I'd give it since I was here.)

**Comment by bdecesare** [comment]
Thank you citrusella. I synced at the beginning and end of my day yesterday and didn't notice anything until this morning. If they are unable to give me back that item I will definitely do what you suggested, thanks for that!

**Comment by Alys** [comment]
@bdecesare Sorry about that! You were hit by this bug: https://github.com/HabitRPG/habitrpg/issues/5376 - the text in bold at the top explains it, but it's as @citrusella says. You were given something else instead of what was reported, but it might have been food or XP. Definitely use Fix Character Values if you feel it was unfair!
