### ISSUE TITLE
Egg Quest,  missing rewards

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitica#7371]
General Info
- UUID: 743aac61-a781-41e1-8017-1610873fcfa4 PARTY ID
- Browser: varies
- OS: 
#### Console Errors

No errors 
All items found! Party has received their rewards. -2 days ago+1

**Comment by JerseyEmerald** [comment]
These are the team members missing  10 plain eggs
Again, second time we did this quest 
Is the problem due to it being out of season 
Afternoon Tea

Group Leader:Lazyez8
Members

Lazyez8 
Smokeflower
Roberto 
SlayerSSavate 
JerseyGirl01 
corilannam 
KarlBear 
Kinsey 
Ak14523 
PhoenixFlorid 
andianiherlina 
Akai Akane 
claritastic 
Bomber1705 
nickdin 
An Na 
Absolute_Zero
mourad244 
Arthur_
Fly 
Inuky 
ColourCarnival 
Dinosaurio 
Guilherme Aglio

**Comment by Alys** [comment]
I've given the achievement and rewards to everyone in your party. Reload if you don't see them. Please tell me if they don't appear after that!

This isn't related to the quest being out of season. Once you own a quest scroll, you can use it at any time. This is just the standard bug that sometimes happens when a medium- to large-sized party finishes any quest. Sorry about the trouble!

**Comment by JerseyEmerald** [comment]
Thank you!!!
