### ISSUE TITLE
Gems are not refunded when deleting a Tavern challenge

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7379]
_edit by Alys 2017-04-07:_

When a Tavern challenge is deleted by either the challenge owner or a moderator, the gem prize must be returned to the challenge owner.

**Comment by Alys** [comment]
Discussion of whether this is desirable or not is here: https://github.com/HabitRPG/habitrpg/pull/5137#issuecomment-98564554 
with the decision being that Tavern challenges shouldn't have the gems refunded, although there seemed to be willingness to reconsider later.

A note about the relevant code is here: https://github.com/HabitRPG/habitrpg/issues/7272#issuecomment-219680193

**Comment by librarianmage** [comment]
What is the status on this?

**Comment by Alys** [comment]
There's compelling arguments from this comment onwards: https://github.com/HabitRPG/habitica/pull/5137#issuecomment-102196106
for making the gems refundable. My feeling about the current state of the community is that the main reasons for deleting a Tavern challenge would be because you'd put it there by mistake or because one of our many challenge bugs had broken the challenge. I'm marking this as help wanted and editing the top post to clarify.
