### ISSUE TITLE
Class, Race and Combat system

### ISSUE THREAD

**Issue by AdrianRWalker** [HabitRPG/habitica#74]
One thing I love about RPGs is Clases and Races. It would ba cool if you could some how incorporate that into this game somehow. 

One idea I had when I first saw this was to have it be a full on RPG where you can travel around and fight monsters and do quests and eventually have boss fights. Maybe as your fighting monsters you can swap your habit EXP into fight time (something like FF7) where you have to complet 10 points of habit inorder to attack. 

Just an initial idea. May need lots of work to flush out how it would all work. But it would help get away from the feeling your raising a tamagotchi RPG character.

**Comment by lefnire** [comment]
Absolutely.

Race might be a digital item you purchase with tokens, we'll see. 

There will definitely be classes. My thoughts might seem strange, but the goal with Habit is to plug into all the services you currently use (eg, pomodoro, anki, myfitnesspal, pivotaltracker, rememberthemilk, etc). So here are my thoughts:
- intelligence is gained from good action on QA sites (stackoverflow, quora, etc) and brain apps (anki, lumosity)
- strength from health sites (fitbit, myfitnesspal), and thoroughness in conquering individual habits
- agility from quickness in task completion (todo lists, project management systems)
- dexterity from keeping abreast all your habits at the same time, or using many services

Your class will automatically be determined from that (warrior, mage, rogue). QA-site frequenters will become clerics automatically ;) Eventually with the Party system, I want users to be able to heal eachother - they get spells when they have enough intelligence. this will encourage accountability and team-focus. strength will increase value gain & decrease HP loss. not sure yet what agility and dexterity will do.

**Comment by lefnire** [comment]
and combat - I'm still not sure if I'm going to include that. I'm going back and forth, maybe die-rolling D&D style (basically only worth it if your'e the same level), because it'll take a whole level of Canvas-coding HTML5-animating ninjary for me to make any serious battle engine. But we'll see. Encouragement first (healing & party-system), dueling later

**Comment by ghost** [comment]
And maybe special sets of weapons for each class and a set of universal weapons?

**Comment by shmumbz** [comment]
What about a FF style level up system and battle system with Mana and Health where you can battle NPCs/Bosses, Creatures, and, most importantly, battling random people online to show off skills and give an incentive to actually keep up with using the website. Maybe leaderboards too? 

The only foreseeable problem is cheaters.

**Comment by ghost** [comment]
@shmumbz brilliant

**Comment by recrm** [comment]
I really like the idea of being able to do something with the character outside of just levelling. The feeling that the points I get for this can actually be used for something really helps with the motivational factor.

That said, I don't think it needs to be that complicated. No real animations are needed if you run it Pokemon style. Two sprites a few shake animations, and turn (or at least action point) based combat.

It would certainly be low priority, the number crunching engine by itself is a lot of work. I've personally been working on a generalized discrete battle engine for a python project for about two years now and it turns out it is a lot more work then one would think it would be. 

As for cheaters, I don't care. The reason I'm personally interested in this project is because of customization, not winning. I'm against leader boards, instead put in options to meet people and have fun. The cheaters will just get bored and go on to do something else.

**Comment by areyn** [comment]
It would be nice if you could change the character's gender and skin colour. I realize most RPG or medieval fantasy involves a white male, but you might attract a wider audience if the character was more of a reflection of the user.

**Comment by wc8** [comment]
@areyn Most RPG might involve a green elf :-) https://github.com/lefnire/habitrpg/issues/107 suggests users could help by submitting some more character variations.

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
Vote for [Character Stats & Attributes](https://trello.com/c/L1H6LiZ3)
Combat-Like Requests: [Battle Creatures](https://trello.com/c/MnfgnOF0) and [Boss Battles](https://trello.com/c/WP3dXij9)
