### ISSUE TITLE
Chat Rolls Back in Party and Tavern(?) -- must click Fetch Recent Messages to see posts and clear notification

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7407]
My messages in the Tavern were up-to-date, but after I went to a Guild and then returned to the Tavern, I  found that the most recently displayed messages were gone. I had to click Fetch Recent Messages to regain them.

Possibly related, noted by Alys: "When you go to the party page, the messages no longer load automatically, and the new-message notification in the guild/party notification icon won't clear automatically. The workaround is to click the "fetch recent messages" button. "  She also noted, "Probably same issue as Tavern because both don't use Groups IDs."

_edit by Alys;_

This also prevents you seeing your own message immediately after you post it, making it look as if your message has not been posted (https://github.com/HabitRPG/habitrpg/issues/7575).
### What to do when this happens to you:

**As soon as you visit your party or Tavern page, click the Fetch Recent Messages button. That will show you all messages and clear the notification icon.**

**When you post a message, also click that button and then you'll see that your message has been saved to the party chat.**

**You do not need to comment on this issue because we know it happens for all players.**

**Comment by citrusella** [comment]
This is the same issue I reported back during testing ( #7229 ). I thought that was fixed since it was closed and referenced elsewhere, but apparently not? 0_o

**Comment by paglias** [comment]
@citrusella it looks like it came back or was never fixed correctly :)

Pinging @TheHollidayInn

**Comment by TheHollidayInn** [comment]
@paglias can you replicate this locally? I cannot.

**Comment by lemoness** [comment]
Another thing I've noticed, possibly unrelated.

Currently, the chat cap in the Tavern has been extremely low (4 hours, instead of 12-16), which I assumed was due to a flood of messages reporting bugs.  However, I've noticed that when my chat rolls back, it sometimes rolls back much further (for example, to seven hours ago). Perhaps it's also artificially messing with the chat cap of 200 messages?

**Comment by citrusella** [comment]
@lemoness For what it's worth, I just manually counted the entire chat and ended up with 200 messages (well, 201, but I probably accidentally counted a message twice somewhere), with the oldest message at 6 hours ago. Unless you meant something else by "chat cap". XP

**Comment by Alys** [comment]
@citrusella That's exactly what we meant. THANK YOU!!! That's good to know. I was intending to do a database script to count them and now I am glad that I don't have to!

**Comment by fbsr** [comment]
Ok thank you for support.

**Comment by khipkin** [comment]
This has been happening to me for the last few days in other guilds as well, not just the Tavern and my party chat.  Specifically, it has been happening in the [Achieve, Accomplish, Aspire guild](https://habitica.com/#/options/groups/guilds/588519bb-5c2e-4a12-a5a7-8c9f73192f9f).

**Comment by Alys** [comment]
This might be still happening. I asked about it in the Tavern and received these responses:

tricksy.fox (90e5c4f2-d5d9-4472-ab2c-19041ee2218d): 
I was experiencing that bug earlier today as well as yesterday (and maybe the day before? My sense of time isn't the best). I was seeing my messages go through fine, but it wasn't updating other people's messages as mine went in, so it would look like I was the only one answering questions for a while, and then when I refresh there's all these other answers I just didn't see, sprinkles in between mine. Not sure about now since I'm on my phone.

citrusella, the serving wench (2d6ef231-50b4-4a22-90e7-45eb97147a2c):
I feel like I've been experiencing it less often perhaps? (Which might be why I'm suddenly forgetting it's been a thing.) But nothing about the way it's happening has changed. (In fact, it's been unchanged enough that I didn't even know that issue had been resolved on Github.) I'll play around to be sure it's definitely still happening and post to that issue by breakfast or lunch tomorrow (I'd do it now, but the chats are pretty slow XP).

**Comment by khipkin** [comment]
@Alys are those two reports talking about the tavern chat or party chat?

**Comment by citrusella** [comment]
@khipkin Mine's fairly localized to the Tavern, mostly because I haven't noticed it elsewhere. My party chat never moves because I'm in a lone party, so I've never noticed anything there, and I think there's something different about guilds that's usually somehow keeping it from happening there.

I'm trying to figure out if there's anything different about the behavior, though the Tavern's moving a little slow, so I'm not sure how long it might take. XP

EDIT: I had thought this morning that there might have been a difference in the behavior now if I posted versus if I didn't, but nope, it's exactly identical to how it was initially reported.

**Comment by SabreCat** [comment]
I've definitely noticed Tavern rolling back to the way it looked on my first visit of the day, and haven't seen similar behavior in Guilds. Just anecdotal, but one more observation anyway.

**Comment by Alys** [comment]
Found in the Tavern by a.study.in.emerald (32d0f48a-b1d2-430a-b67a-3cef54d9e7ad): 
"Wow. Is the Tavern chat being a little glitchy for anyone else? Any time I fetch recent messages, it shows me a slightly different set of the most recent ones. The newest will show but the second-newest won't, then the third most recent will disappear but the second newest will come back, and the one that was first will be replaced by another newest message, etc. It's weird."

EDIT:
Also in the Tavern from  Dracindo (1ee37752-f615-45a2-872e-8bc4eff2255b): 
"Yeah it's also a bit buggy for me. Like I was just answering theletter_k's question (which was 1 minute ago after fetching) and after one minute of writing you answerd that question 2 minutes ago"

**Comment by lemoness** [comment]
This happened again to me this morning, also in the Tavern. Have not
noticed it in Guilds recently, and I have been checking them fairly
regularly.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
I haven't done much testing on this, but I haven't seen it happen recently. Is this still an issue?

**Comment by paglias** [comment]
can reopen if it happens again
