### ISSUE TITLE
Challenge sorting out of order

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7409]
UUID: 28771972-ca6d-4c03-8261-e1734aa7d21d
### Description

Post-maintenance, challenges are out of order, in no order that I can identify. 

For reference, screenshotted are the challenges that I am operating myself. 

The order, as far as I can recall, should be 
(newest)
Organ donor challenges with 15 lines of emoji people
Organ donor challenges with 14 lines of emoji people, if any
May Habitversary challenge
Get Disemboweled 
Make the world better in your computer's spare time 
Become an organ donor 
Cutting down costs
Defeating the terrible crushing debt monster
(oldest)

~~AND in listing those I've just discovered that one of them is missing. Challenge "Crash Course Format" in my private guild should be, I believe, between habitversary and disemboweled.~~ Nevermind, found it, durrr. 

  I am not 100% certain of the order of Get Disemboweled, Make the world better, Become an organ donor relative to eachother. 

Feel free to dig around as needed, including in private guild. 

Top and bottom -- the highlighted one is where they overlap. 
![top](https://cloud.githubusercontent.com/assets/9494342/15452583/39357302-1fba-11e6-8ac5-72f5464f523a.png)
![bottom](https://cloud.githubusercontent.com/assets/9494342/15452585/3c1c1efe-1fba-11e6-91f5-71741ac57cf2.png)

**Comment by eiron** [comment]
They are all now sorted by the random string assigned to them upon creation. This will likely be due to this being the order they were transferred onto the new database. It does make things a little confusing, alas.

**Comment by Dewines** [comment]
Would this be a good place to mention that challenges with more than 30 participants are only displaying 30 names in the participants list, regardless of how many people are actually in the challenge? This actually solves the problem I reported as #7419. My work account was joining the challenge, but because the sorting is no longer based on date of joining, my work account name wasn't in the first 30 whereas my main account and writing account were. DewinesAtWork didn't show in the list whereas my other two accounts apparently pushed @aust out of the challenge.

**Comment by Alys** [comment]
Lemoness has created https://github.com/HabitRPG/habitrpg/issues/7507 to describe the preferred challenge order so I'm closing this one. The 30 participant problem is described in https://github.com/HabitRPG/habitrpg/issues/7422

Thanks, @Cantras, @Eiron, @Dewines for the information!
