### ISSUE TITLE
NPM install errors

### ISSUE THREAD

**Issue by freeman42x** [HabitRPG/habitica#741]
Trying to install locally following https://github.com/lefnire/habitrpg/wiki/Running-Locally on windows but I receive the following errors on `npm install`:

E:\SoftwareDev\habitrpg>npm install
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/Unroll-Me/derby) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/Unroll-Me/derby) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/lefnire/racer) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/lefnire/racer) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/codeparty/derby-ui-boot) undefined

npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/codeparty/derby-ui-boot) undefined

npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/lefnire/racer-db-mongo) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/lefnire/racer-db-mongo) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/lefnire/derby-auth) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/lefnire/derby-auth) undefined
npm http GET https://registry.npmjs.org/connect-mongo
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/passport-facebook
npm http GET https://registry.npmjs.org/stripe
npm http GET https://registry.npmjs.org/gzippo
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/guid
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mongoskin
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/lefnire/node-icalendar) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/lefnire/node-icalendar) undefined
npm http GET https://registry.npmjs.org/browserify/1.17.3
npm http GET https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/nconf
npm http GET https://registry.npmjs.org/superagent
npm ERR! git clone git://github.com/Unroll-Me/derby undefined
npm ERR! git clone git://github.com/Unroll-Me/derby undefined
npm ERR! git clone git://github.com/codeparty/derby-ui-boot undefined
npm ERR! git clone git://github.com/codeparty/derby-ui-boot undefined
npm ERR! git clone git://github.com/lefnire/racer undefined
npm ERR! git clone git://github.com/lefnire/racer undefined
npm ERR! git clone git://github.com/lefnire/derby-auth undefined
npm ERR! git clone git://github.com/lefnire/derby-auth undefined
npm ERR! git clone git://github.com/lefnire/racer-db-mongo undefined
npm ERR! git clone git://github.com/lefnire/racer-db-mongo undefined
npm http GET https://registry.npmjs.org/derby-i18n/0.0.1
npm http GET https://registry.npmjs.org/expect.js
npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:945:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:736:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "E:\SoftwareDev\nodejs\\node.exe" "E:\SoftwareDev\nodejs\node_modules\npm\bin\npm-cli.js" "in
stall"
npm ERR! cwd E:\SoftwareDev\habitrpg
npm ERR! node -v v0.10.1
npm ERR! npm -v 1.2.15
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! git clone git://github.com/lefnire/node-icalendar undefined
npm ERR! git clone git://github.com/lefnire/node-icalendar undefined
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/stripe
npm http 304 https://registry.npmjs.org/gzippo
npm http 304 https://registry.npmjs.org/passport-facebook
npm http 304 https://registry.npmjs.org/connect-mongo
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/guid
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/mongoskin
npm http 304 https://registry.npmjs.org/browserify/1.17.3
npm http 304 https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/nconf
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/derby-i18n/0.0.1
npm http 304 https://registry.npmjs.org/expect.js
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\SoftwareDev\habitrpg\npm-debug.log
npm ERR! not ok code 0

**Comment by AndreCaseyScott** [comment]
Also having an issue installing Habit now. Figured I'd use an open issue instead of opening a new one. My current install was really buggy and thought I'd reinstall it fresh. When I tried this, it kept throwing errors. Tried to clean the cache and things, as was mentioned in #1277, to no avail. 

From what I can tell, it seems that it cannot find the bootstrap repo on github. After a quick search, it looks like twitter moved the repo to https://github.com/twbs/bootstrap, from https://github.com/twitter/bootstrap.git (which `npm install` looks for). Thought I might be able to update the `package.json` and just run `npm install` again, but seems the dependency for bootstrap is located elsewhere.

The main error that is being throw is this:
`2210 verbose lock git://github.com/twitter/bootstrap.git /Users/andre/.npm/8e14791d-github-com-twitter-bootstrap-git.lock
2211 verbose addRemoteGit [ 'git://github.com/twitter/bootstrap.git', 'master' ]
2212 error git clone git://github.com/twitter/bootstrap.git Cloning into bare repository '/Users/andre/.npm/_git-remotes/git-github-com-twitter-bootstrap-git-8e14791d'...
2212 error git clone git://github.com/twitter/bootstrap.git
2212 error git clone git://github.com/twitter/bootstrap.git fatal: remote error:
2212 error git clone git://github.com/twitter/bootstrap.git   Repository not found.
2213 silly lockFile 8e14791d-github-com-twitter-bootstrap-git git://github.com/twitter/bootstrap.git
2214 silly lockFile 8e14791d-github-com-twitter-bootstrap-git git://github.com/twitter/bootstrap.git
2215 verbose about to build /Applications/MAMP/htdocs/habitrpg/node_modules/derby-ui-boot
2216 info /Applications/MAMP/htdocs/habitrpg/node_modules/derby-ui-boot unbuild
2217 verbose from cache /Applications/MAMP/htdocs/habitrpg/node_modules/derby-ui-boot/package.json
2218 info preuninstall derby-ui-boot@0.0.7
2219 info uninstall derby-ui-boot@0.0.7
2220 verbose true,/Applications/MAMP/htdocs/habitrpg/node_modules,/Applications/MAMP/htdocs/habitrpg/node_modules unbuild derby-ui-boot@0.0.7
2221 info postuninstall derby-ui-boot@0.0.7
2222 error Error: Command failed: fatal: remote error:
2222 error   Repository not found.
2222 error
2222 error     at ChildProcess.exithandler (child_process.js:542:15)
2222 error     at ChildProcess.EventEmitter.emit (events.js:99:17)
2222 error     at maybeClose (child_process.js:640:16)
2222 error     at Socket.ChildProcess.spawn.stdin (child_process.js:817:11)
2222 error     at Socket.EventEmitter.emit (events.js:96:17)
2222 error     at Socket._destroy.destroyed (net.js:358:10)
2222 error     at process.startup.processNextTick.process._tickCallback (node.js:245:9)
2223 error If you need help, you may report this log at:
2223 error     <http://github.com/isaacs/npm/issues>
2223 error or email it to:
2223 error     <npm-@googlegroups.com>
2224 error System Darwin 11.4.2
2225 error command "node" "/usr/local/bin/npm" "install"
2226 error cwd /Applications/MAMP/htdocs/habitrpg
2227 error node -v v0.8.24
2228 error npm -v 1.2.24
2229 error code 128
2230 verbose exit [ 1, true ]`

**Comment by SabreCat** [comment]
I grappled with this for far too long today, to no avail. I'd pretty much given up, hoping that when the rewrite comes out it'll be fixed there (or just not need this package). If somebody does figure out how to fix this, that'd be fantastic!

**Comment by AndreCaseyScott** [comment]
@lefnire I wonder if this would be an easy fix for you? :/ new developers will find it hard to join the team if they find a dependency is broken...

**Comment by litenull** [comment]
That's a derby package.json bug. Someone changed his repository name, and
now everything is broken. We cant do anything about this. We could fork the
repo and change the dependency, but that's not a priority right now, since
me and Tyler are working on releasing the rewrite in a few days.

On Sun, Aug 4, 2013 at 5:45 AM, onduhray notifications@github.com wrote:

> @lefnire https://github.com/lefnire I wonder if this would be an easy
> fix for you? :/ new developers will find it hard to join the team if they
> find a dependency is broken...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/741#issuecomment-22066325
> .

## 

LP, Tomaž :)

**Comment by litenull** [comment]
http://registry.npmjs.org/ = down. Cant do anything about it for now.

**Comment by lefnire** [comment]
Sorry, bootstrap changed their repo url from https://github.com/twitter/bootstrap to https://github.com/twbs/bootstrap. With their upcoming 3.0 release, they're shifting some stuff around. We're already using a specific SHA of derby-ui-boot (because codeparty is keeping `master` up with derby 0.5), so I'll just forked at that SHA to create our own `habit0.3` branch & point to the new repo url. Bootstrap 2.3.2 (which we require) is currently on their master branch, but once they release 3.0 they're going to make that the new master, and create a tag like `2.3.2` - we'll need to update our branch when that time comes.

Anyway, it should be fixed now if you give `npm install` another go?

Edit: Looks like npm is still down... that means beta is down too, lol

**Comment by lefnire** [comment]
@onduhray I'm gonna add you as repo admin. You've been a huge help and I don't want to be your bottle neck. Email me tylerrenelle gmail if you have any questions

**Comment by lefnire** [comment]
npm's back, we're good

**Comment by SabreCat** [comment]
I am up and running on local! Y'all have no idea how happy this makes me. Thank you @lefnire !

**Comment by AndreCaseyScott** [comment]
Yup! so great :) had to clear the cache and try `npm install` about 5 times but it works. Thanks @lefnire ^_^
