### ISSUE TITLE
[API v3] Changing password doesn't work

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7423]

**Comment by Nezuko** [comment]
Also experiencing this bug. 
MacOS 10.11.4. 
Chrome Version 50.0.2661.102 (64-bit)

Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
Error
    at q.zone (https://habitica.com/app-00ad4002.js:40:20037)
    at Object.u.authenticate (https://habitica.com/app-00ad4002.js:44:1427)
    at Object.<anonymous> (https://habitica.com/app-00ad4002.js:44:2577)
    at Object.i [as invoke](https://habitica.com/app-00ad4002.js:5:16822)
    at Object.c [as $get](https://habitica.com/app-00ad4002.js:5:15218)
    at Object.i [as invoke](https://habitica.com/app-00ad4002.js:5:16822)
    at https://habitica.com/app-00ad4002.js:5:14868
    at g (https://habitica.com/app-00ad4002.js:5:16455)
    at Object.i [as invoke](https://habitica.com/app-00ad4002.js:5:16789)
    at D.instance (https://habitica.com/app-00ad4002.js:6:8436)

**https://sb.scorecardresearch.com/beacon.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT**

bridge.js:44 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
bridge.js:60 [XKit Bridge] Hello from Bridge 2.1
bridge.js:61 [XKit Bridge] Retrieving storage..
bridge.js:88 [XKit Bridge] Storage loaded, calling XKit.. bye!
xkit.js:664 init_extension: {"standard":false,"ask_frame":false,"blog_frame":false,"peepr":false,"xkit":false}

**https://habitica.com/api/v3/user/auth/update-password?userV=10 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app-00ad4002.js:42 Object**

**Comment by crookedneighbor** [comment]
Porting from another issue:

General Info
- UUID: b8637b91-9d24-4a00-8054-24654a0eae7a
- Browser: Vivaldi and Chrome
- OS: Windows 10 Pro

### Description

When I try to change my password it shows the following message:
![habitica password glitch](https://cloud.githubusercontent.com/assets/2553443/15490319/e2acfdbc-2134-11e6-9a96-d441107cf852.PNG)
This happens in both Chrome and Vivaldi, and I tried different password lengths and character uses, to no avail.

**Comment by lemoness** [comment]
This happens for me as well.

**Comment by HataKare** [comment]
Sorry for the double post, but in the tutorial it says "Ignore anything with [API v3]"

**Comment by HataKare** [comment]
The issue is not resolved by the way.

**Comment by crookedneighbor** [comment]
It's fixed in the code base, but has not been deployed to the site yet. Will happen today.

**Comment by crookedneighbor** [comment]
I'll post here when it does.

**Comment by HataKare** [comment]
Oh okay, thanks

**Comment by crookedneighbor** [comment]
The fix is deployed now.

**Comment by lemoness** [comment]
Just tested, and it works for me!

**Comment by Alys** [comment]
@HataKare Thanks VERY much for the note about the bug instructions being wrong! I'd forgotten that I'd need to remove that and it could have stayed there for months if you hadn't taken the time to tell us! :)

**Comment by HataKare** [comment]
Haha, no problem
