### ISSUE TITLE
[API v3] sellerId being set to undefined

### ISSUE THREAD

**Issue by ltorroba** [HabitRPG/habitica#7427]
General Info
- **UUID:** 8ac1be04-4201-4eed-a2a4-436eada5c0e9
- **Browser:** Chrome
- **OS:** Mac OS X
### Description

Seems like on the rendered HTML of the page, the `sellerId` field of some Amazon payment scripts located on the bottom of the file is being set to _undefined_:

![](http://i.imgur.com/jslKVXo.png)

I attempted to initiate an Amazon Payments purchase of gems and at least until the credit card selection screen, nothing seemed wrong - I didn't venture any further though.
#### Console Errors

None, but I didn't go beyond the [credit card selection screen](http://i.imgur.com/ATadReR.png).

**Comment by quin-jay** [comment]
Alright, I tried this, since I just got an Amazon gift card anyway. I got to a window with a button that said "Click the button to pay using Amazon Payments." I did, then I signed in. I have two-factor authentication, and while it did let me enter a code, perhaps that contributed to this error I got? The notification said "`missing req.body.billingAgreementId`" (I got a pop-up message that said that, and then clicking "OK" created a Habitica notification with the same string). The error in the console was:
`https://habitica.com/amazon/createOrderReferenceId Failed to load resource: the server responded with a status of 400 (Bad Request)`.

Trying again for the purposes of this comment led me to a couple different console errors, presumably because now I was signed in (it didn't make me sign in again), but the pop-up and Habitica notifications didn't change.

```
nrWrapper @ (index):1(anonymous function) @ app-00ad4002.js:6s @ app-00ad4002.js:6f @ app-00ad4002.js:6j @ app-00ad4002.js:7(anonymous function) @ app-00ad4002.js:7j.$eval @ app-00ad4002.js:7j.$digest @ app-00ad4002.js:7(anonymous function) @ app-00ad4002.js:7p @ app-00ad4002.js:5(anonymous function) @ app-00ad4002.js:5nrWrapper @ (index):1
(index):1 POST https://habitica.com/amazon/createOrderReferenceId 400 (Bad Request)
```

EDIT: Alright, according to zesme's link, I ought to be seeing some kind of box under the "click the button to use amazon payments" button, but I don't. I turned off uBlock for Habitica and as far as I can tell I have no cosmetic filters or anything of the kind for the site, so I'm not sure what's blocking me from seeing the credit card box, but it looks like maybe my errors aren't related to zesme's after all.

**Comment by paglias** [comment]
@zesme did you find this problem on v3.habitica.com? In this case it could be because we were running it into dev mode

**Comment by paglias** [comment]
@lynnyliz I've tested buying gems with Amazon and it worked for me, it's possible though that there are problems when using gift cards. The kind of box @zesme is referring to is probably the one that appears when setting up a subscription. Also as far as I know Amazon Gift cards cannot be used to purchase on sites external of Amazon like Habitica

**Comment by quin-jay** [comment]
@paglias it didn't even let me pick whether I wanted to use a credit card, though. Every time I reload the page I get `BLOCKED_BY_CLIENT` console errors which make me think uBlock is still filtering something Amazon-related -- Like, even though habitica.com is on my whitelist, maybe I need to whitelist Amazon too. Or something like that. Either way, separate issue, I'm glad this ticket got sorted out :)

```
payments.amazon.com/gp/cba/uedata/179-7955592-3155051?ld&v=28&id=B2Z8TD3HHB…=0&hob=4&hoe=5&ld=451&t=1464024598662&ctb=1&csmtags=nonredirect|noAmznJQ:1 GET https://payments.amazon.com/gp/cba/uedata/179-7955592-3155051?ld&v=28&id=B2…rc=0&hob=4&hoe=5&ld=451&t=1464024598662&ctb=1&csmtags=nonredirect|noAmznJQ net::ERR_BLOCKED_BY_CLIENT
fls-na.amazon.com/1/batch/1/OP/AGWSWK15IEJJ7:179-7955592-3155051:B2Z8TD3HHB…451%26t%3D1464024598662%26ctb%3D1%26csmtags%3Dnonredirect%7CnoAmznJQ:452:1 GET https://fls-na.amazon.com/1/batch/1/OP/AGWSWK15IEJJ7:179-7955592-3155051:B2…3D451%26t%3D1464024598662%26ctb%3D1%26csmtags%3Dnonredirect%7CnoAmznJQ:452 net::ERR_BLOCKED_BY_CLIENT
```

**Comment by ltorroba** [comment]
@paglias I encountered this on the normal version (https://habitica.com), but I think this really doesn't impact in anything. I tried sifting through the sources to see if there were any 400/404 upon page load but none showed up, so I resorted pasting the URL of the script to google and, alas, first result was [this](https://github.com/HabitRPG/habitrpg/issues/5780) (n.b.: check fifth comment).

Seems like this has being going on for at least a year now, so it's probably low priority, or completely benign. If I have some spare time I will look at it, as maybe it's one of those scripts that links Habitica's referral code to Amazon, so you get some money off purchases redirected from your site, or something along those lines.
