### ISSUE TITLE
Party Boss Still Asleep?

### ISSUE THREAD

**Issue by Lizzikins** [HabitRPG/habitica#7447]
General Info
- UUID: d035f6f3-a18d-44f0-9684-54618e78c51d
- Browser: Chrome
- OS: Windows 7
### Description

The quest boss (Vice, the Shadow Wyrm) is showing as "asleep". 
![image](https://cloud.githubusercontent.com/assets/19531744/15475547/8f94a972-2102-11e6-8070-39c21b58acc1.png)

**Comment by ghost** [comment]
Yes, the special no-damage maintenance mode was planned to be several hours longer than the maintenance window in order to also protect people who didn't sign on until the next evening. You'll start taking damage normally by tomorrow.

**Comment by crookedneighbor** [comment]
We're seeing increased instances of double boss damage after maintenance: https://github.com/HabitRPG/habitrpg/issues/2805

So we're going to implement a temporary measure while we work it out so that dailies work normally, but boss damage still does not affect the user. (message has been updated) https://github.com/HabitRPG/habitrpg/pull/7462

We're doing this so that user's are not unfairly damaged. We're hoping to turn it off soon.
