### ISSUE TITLE
Unable to add party member "an unexpected error has occurred" for days

### ISSUE THREAD

**Issue by MunchkinPaws** [HabitRPG/habitica#7479]
I am trying to add someone to my party but it keeps saying "an unexpected error has occurred" and tells me to reload the page. I have tried to reload the page as well as multiple computers but it continues to happen. It has happened for days with the same person. Does anyone know of a way to fix this? Thanks

my user id is : a0ecb538-3725-48f9-8b09-2a2ea453fcd8

my group id is: 518bd819-42e7-44b4-8526-e84113999792

I have tried in Edge and Chrome

**Comment by Alys** [comment]
Sorry about this! Could you please tell us their user ID?

**Comment by MunchkinPaws** [comment]
theamazingsplit
0c93e1bb-0dde-45cb-b306-8c095b1120dc

**Comment by Alys** [comment]
@MunchkinPaws Could you please try once more now? 

You can ignore the information below if you wish.

---

Technical details for bughunting:

That player's invitations.party attribute contains null instead of an object - I wonder if that's causing it. I have changed it to {}:

```
    "invitations": {
        "party": null,
        "guilds": []
    },
```

Their party object looks normal and does not show an existing party id:

```
    "party": {
        "quest": {
            "key": null,
            "completed": null,
            "RSVPNeeded": false,
            "progress": {
                "collect": {},
                "down": 0,
                "up": 8.194160282162736
            }
        },
        "orderAscending": "ascending",
        "order": "level"
    },
```

They're not already in the party

**Comment by MunchkinPaws** [comment]
It worked! Thank you so much for your help.

**Comment by Alys** [comment]
Fantastic! Thanks for telling us! We'll keep using this issue for sorting out how it happened and for finding and fixing other instances, if any.

---

Looks like the `null` in `invitation.party` was causing it. I'll do a search for any other affected players and fix it.

We should also look into whether this was a once-off data glitch or caused by code.

**Comment by Alys** [comment]
49,954 user accounts had `null` in `invitation.party`. I've changed them all to `{}`

Such a large number makes me think this was incorrect data left over from the old site. I don't think it could be from a new bug in our new code (e.g., can't be due to accepting or rejecting an invitation and having the attribute cleared wrongly) because there hasn't been enough time for that many players to be affected. However I'll look through the code just to make sure there's no `null` in anything setting the invitation object.

**Comment by paglias** [comment]
Definitely a v2 problem
