### ISSUE TITLE
Daily validation failed

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7487]
{ message: [32m'daily validation failed'[39m,
    name: [32m'ValidationError'[39m,
    errors: 
     { [32m'tags.1'[39m: 
        { message: [32m'Invalid uuid.'[39m,
          name: [32m'ValidatorError'[39m,
          properties:

**Comment by Alys** [comment]
Possible related: https://github.com/HabitRPG/habitrpg/issues/7470 ("Since maintanance, damage to boss doesn't work")
".... it said something along the lines of 'Daily verification failed'...."

**Comment by cybercrash** [comment]
I get these errors since the big switchover/update, when I check a box in a checklist (happens with both Dailies and To-Dos) :
- on the website (Chrome or Firefox, Ubuntu 14.04) it says "invalid uuid"
- in the app (Android), it says "daily validation failed"

and then it unchecks the box.

Interestingly, this seems to only happen with old/existing tasks with checklists. I just created a brand new daily and a to-do each with checklists, and those seem to save just fine, and do not trigger errors.

user ID: 9bcd85dc-968d-42d2-91fc-b383c58d5304

Error from console in Chrome (checking a box in an old Daily):
(index):1 PUT https://habitica.com/api/v3/tasks/3e06f6cd-00d4-45a6-a430-9a739abb645f?userV=5044 400 (Bad Request)nrWrapper @ (index):1(anonymous function) @ app-5d6051d5.js:6s @ app-5d6051d5.js:6f @ app-5d6051d5.js:6j @ app-5d6051d5.js:7(anonymous function) @ app-5d6051d5.js:7j.$eval @ app-5d6051d5.js:7j.$digest @ app-5d6051d5.js:7j.$apply @ app-5d6051d5.js:7$$debounceViewValueCommit @ app-5d6051d5.js:8$setViewValue @ app-5d6051d5.js:8Qe.k @ app-5d6051d5.js:8o.event.dispatch @ app-5d6051d5.js:2r.handle @ app-5d6051d5.js:2nrWrapper @ (index):1

**Comment by paglias** [comment]
@cybercrash this should be fixed now, can you reload the site / close the mobile apps and try again? Let me know if it still doesn't work

**Comment by cybercrash** [comment]
fixed!! thank you sooooo much!!
