### ISSUE TITLE
Checklist - item duplicates

### ISSUE THREAD

**Issue by Batchasse** [HabitRPG/habitica#7493]
General Info
- UUID: 022bf9e4-e8fe-43d4-afb2-f367d79cf64b
- Browser: Firefox (up to date)
- OS: W7
### Description

Hello. When adding an item to an old checklist ... Edit the task, cursor on last filled item of the checklist, enter, type in the new item in the blank field, enter. The typed value has disappeared  and the created item is filled with the previous one. No hurry :-) Have a good day.

**Comment by thebat137** [comment]
I am seeing this one too, on both old and newly-created checklists.  For me, it does not seem to occur immediately when creating a new checklist --- as long as I've just created the checklist and keep entering items in order I seem to be okay.  But if I rearrange the items on the newly created checklist, or if I save it and re-open it, then I start having this problem.

I can fix each overwritten item by retyping it after it's been overwritten, and the second time, it stays.  But once I've had the problem once for a particular list, it continues to recur for each new item added to the list.

UUID: dea8a9e8-c084-438a-9a14-7fe96a73fd0a
Browser: Firefox 45.1.0
OS: Debian Linux

I don't see any specific console errors.

**Comment by lemoness** [comment]
Quick note that this happens to me frequently with my longer checklists (last or second-to-last item) even if I have not adjusted the order.

**Comment by camdroid** [comment]
I second what thebat137 said - new checklists work fine, as long as they stay exactly the same after you save them for the first time. As soon as you try to modify the list, it copies the value from the item above it.

Same about the error messages - nothing pops up that looks related.

NB: The first two items I edit seem fine. On the third item, I start getting repeats.

UUID: beb555b6-31ab-4da2-b168-0d02d4c6dda9
Browser: Chrome Version 50.0.2661.102 (64-bit)
OS: Mac (El Cap 10.11.5)

**Comment by MagBag** [comment]
This is happening to me as well.  When editing a previously established checklist, the task typed in reverts to the previously entered subtask after pressing enter.  The duplication does not occur when making a new checklist for a new task (even with multiple subtasks), but if I go back to edit the new checklist, the duplication occurs.  The duplication does not occur in an old task with no previous checklist; if I edit to add a checklist, it allows me to add multiple subtasks with no duplication.  When it happens, It seems to happen with both short and long check lists.

User ID 99e9a8f7-57c5-49a7-870d-f4ff46f2439b
Firefox 46.0.1
OS Windows 7

**Comment by ltorroba** [comment]
I second what @MagBag said. Exact same behaviour seen here. I will be taking a look at the code for the tasks; perhaps its a matter of changing a parameter or two.

User ID: 8ac1be04-4201-4eed-a2a4-436eada5c0e9
Browser: Chrome
OS: Mac OS X

**Comment by lemoness** [comment]
So, I decided to take a close look at this behavior, and I figured out that it isn't just duplicating. The text is getting replaced systematically by whatever you typed before , leading to a checklist lag. 

Took some screenshots to try to illustrate this, because it is a bit tricky to describe:

![checklistissue1](https://cloud.githubusercontent.com/assets/3494081/15584425/6e41b114-232f-11e6-8207-c92db42986d7.png)

Previously entered text: test 2
Current text (cursor still in box): see how this disappears?

![checklistissue2](https://cloud.githubusercontent.com/assets/3494081/15584478/9471d670-232f-11e6-88d9-85b9a7209c76.png)

Upon hitting enter, the current text, "see how this disappears?" is replaced with the previously entered text, "test 2" 

Previously entered text: see how this disappears?
Current text (cursor still in box): this gets replaced

![checklistissue3](https://cloud.githubusercontent.com/assets/3494081/15584541/de20f44a-232f-11e6-8065-9cdf1044ada5.png)

Then, when I hit enter again, the text isn't duplicated, but replaced by the previously typed text that had disappeared.

**Comment by MagBag** [comment]
Yes, that's exactly what's happening.  Not duplicating but getting replaced!

**Comment by ltorroba** [comment]
I've been looking into this for the past hour. Hopefully I should have a PR to fix this within the next hour.

The current of the implementation of the checklist entails that when one presses enter, the current item is **always** added to the checklist and, as an extra precaution/synchronisation measure, the label is changed to reflect the _n_th item of the checklist. 

This works perfectly when you are making a new task from scratch; however, when editing an existing checklist, upon pressing enter for the first edited item, it will be added again, as a duplicate. This then causes conflicts with the synchronisation measures, which synchronise checklist item's by IDs, and thus, due to the duplicate, the ID's are all offset by one.

**Comment by ShulamitLH** [comment]
It's still happening to me as of this afternoon.
User ID cd180aea-f9bf-4bf0-99e6-b62a0f9e6359

**Comment by Maslor** [comment]
This just happened to me too. I create a new checklist item of a daily task and it gets replaced by my previous checklist item. 
Browser: Safari
UID: 84947daf-c445-4bf6-b49c-e62adcd2043d
OS: OS X El Capitan

**Comment by colinwirt** [comment]
This issue is still happening for me. The newly inserted item is always overwritten with the last item in the list. It's not a duplicate.

**Comment by Batchasse** [comment]
Hello,
For me too. It's not blocking, however. Copy (CTRL+C) what I type before hitting the return key, then paste. I might create a specific task for it, for days I'm short of XPs ;-)

**Comment by quin-jay** [comment]
@crookedneighbor has that PR gone live yet? It looks like a number of people (including me) are still seeing this issue.

**Comment by crookedneighbor** [comment]
It has not been deployed yet. Should go out today.

**Comment by Batchasse** [comment]
Works fine now. Thanks a lot
