### ISSUE TITLE
No damage to boss during quest, 6x damage from one party member

### ISSUE THREAD

**Issue by idgiebay** [HabitRPG/habitica#7495]
I think I may be having a similar issue to #7470 but I'm getting different errors. First of all, the general info:

UUID: 821c9559-d2ec-41af-83db-e28a33b3a4e1
Browser: Chrome 50.0.2661.102 m
OS: Windows 7

We started Dilatory Distress, Part 3: Not a Mere Maid on Sunday. I don't know if all the participating party members have logged in since then, but I have and so has one other, yet they are the only one who has dealt any damage. It comes along with this message:

_Eisah Vakohler attacks Adva, the Usurping Mermaid for 6.7 damage. Adva, the Usurping Mermaid does not attack, because it respects the fact that there are some bugs post-maintenance and it doesn't want to hurt anyone unfairly. It will continue its rampage soon!_

That happened six times yesterday, exact same amount of damage. Since then, no other damage has been done. We don't seem to be getting any other errors.

**Comment by Alys** [comment]
The issue of not making any progress on a quest has been fixed in https://github.com/HabitRPG/habitrpg/issues/7470 but please comment on https://github.com/HabitRPG/habitrpg/issues/7470 if you notice it happening again.

The duplicate (sextuplicate!) damage messages are being tracked in https://github.com/HabitRPG/habitrpg/issues/2805 and we have made a fix for that too. If you notice an identical quest message appearing two or more times, please comment on https://github.com/HabitRPG/habitrpg/issues/2805
