### ISSUE TITLE
ads are not showing

### ISSUE THREAD

**Issue by litenull** [HabitRPG/habitica#750]
The ads are not showing, as you see in this pic:

![Screen Shot 2013-03-29 at 10 19 04 PM](https://f.cloud.github.com/assets/2871471/319313/302e16e0-98ba-11e2-9798-05b87132567e.png)

**Comment by lefnire** [comment]
it's a problem where derby redraws very the app shortly after loading the page, and google ads won't allow client-side rendering of ads (or maybe they don't allow multipel loading on the same session or something). It sounds like something's triggering `model.emit('bulkUpdate')` when it wouldn't make sense to, like are there too many `model.set()`s being triggered right after page load?

Solution - (1) fix the above, or (2) find a simple image-based ad provider

**Comment by lefnire** [comment]
so it appears you can't use adsense with derby! pretty big incompatibility, but whatevs (see [the conversation](https://groups.google.com/forum/?fromgroups=#!topic/derbyjs/x8FwdTLEuXo)). switching to amazon affiliate. this is actually cooler, because I ended up linking the books in each column that guided my decision to create those columns in the first place - so it's kinda like "backstory tutorial on this column"
