### ISSUE TITLE
Mount Red Wolf image not loading properly

### ISSUE THREAD

**Issue by fromsaturn** [HabitRPG/habitica#7502]
General Info
- UUID: 746c6c0a-9b87-40c4-98f7-59cf9aab1b88
- Browser: Chrome
- OS: Windows 10

Bug: Mount wolf does not load properly. See screenshot here: http://www.awesomescreenshot.com/image/1278936/057a8be2fe9574f4912dd7e46ae08be2

**Comment by Alys** [comment]
Whenever you see something odd like that or don't see something you're
expecting to see, try reloading the site with the browser's reload/refresh
button. Usually those problems are caused by your browser not having
downloaded all the files it needs and a reload often fixes it. Tell us how
that goes.

**Comment by crookedneighbor** [comment]
Closing this. Re-open if you're still having issues.
