### ISSUE TITLE
Can't start a quest alone

### ISSUE THREAD

**Issue by Hiyaiba** [HabitRPG/habitica#7503]
General Info
- UUID: 6439cbbd-9153-415b-a8ee-ab0659871288
- Browser: Firefox
- OS: Windows 10 (PC)
### Description

I can't start any quest alone. When I push the start button, nothing happens and the quest is still in my inventory. I left my group because nobody plays anymore but I read that I can start the quests alone, it'll only be more difficult. Any idea? Thanks =3

**Comment by Alys** [comment]
First, make sure you're in a party by yourself (if you don't know how to,
go to Help > Ask a Question on the Habitica.com website or Guilds > The
Newbies Guild on the app - they'll be able to help you faster there because
there's more of them!). Then, from your party page, click the button to
start a quest and choose the quest you want. You need to have already
bought or been given the quest - ask again at the same place if you're not
sure how! If after that you still can't start it, post again here and say
what went wrong again.

**Comment by Alys** [comment]
I'm closing this now but if you'd like more help, see the points from my previous post, and let us know if there's any other information you can give us. We'll still see your reply and can reopen this if necessary.
