### ISSUE TITLE
Emoji appearing in URLs

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7515]
General Info
- UUID: 
- Browser: Firefox 46.0.1
- OS: Windows 7 Service Pack 1
### Description

Raw URLs (not those created in Markdown like [this](http://example.com), in all but one instance I've seen) convert basic emoji used in them to the image. The links still work as intended so this is really a display issue more than anything. I've seen at least two instances of http:// converting to http::confused:/, one of which was actually in what appeared to be correct Markdown format (though maybe there was an accidental space in there so perhaps not). The http:// thing doesn't seem to happen reliably, though; I've seen many a time it hasn't happened. A message I posted in the [Wizards of the Wiki](https://habitica.com/#/options/groups/guilds/9a163b28-ebcf-4e52-87de-5c040ed0f8f8) guild contains this problem with a different emoji in a different place in the URL. The URL in the message is http://habitica.wikia.com/wiki/Special:Preferences but it displays as [http://habitica.wikia.com/wiki/Special:stuck_out_tongue:references](http://habitica.wikia.com/wiki/Special:Preferences) ...though it still links to the right place, as I've approximated using Markdown here.
#### Console Errors

Nothing.

**Comment by habitrpguser** [comment]
I'd like to second that! While it's especially weird in URLs, unintentional smileys happen to me all the time (probably because I'm using parentheses and colons a lot). I don't remember how often I typed some combination of letters and punctuation and ended up with an unintentional smiley, and had to repost (usually with an added blank space). Also sometimes I like the look of ASCII smileys better than the picture, and/or have a hard time predicting which picture they will turn into without extensive testing and memorizing. (For instance, when typing : and ), I think of smiling with a closed mouth, and the resulting :smiley: looks too much like laughing, in my opinion, and all the available closed-mouthed ones have an added meaning, for example :blush: :relaxed: :yum: :relieved: :smirk: ). Because of all this, I don't like the automatic smiley processing as it is now, and would like to either turn it back the way it was, or have the possibility to opt out of it, or at least have a way to escape it. (Maybe there are working escapes for that already, but I didn't take the time to test and find them yet). Anyway I think I'm not the only one who finds it more a nuisance than a great new feature, and thought I'd give that feedback here. (If it stays as it is, I can live with it, it's not a big deal - I just liked it better the way it was before that added smiley processing.)

**Comment by crookedneighbor** [comment]
Issue moved to [HabitRPG/habitica-markdown-emoji #4](https://github.com/HabitRPG/habitica-markdown-emoji/issues/4) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by crookedneighbor** [comment]
Thanks for reporting this. That is definitely not the desired behavior.

**Comment by crookedneighbor** [comment]
I've re-opened up an issue in the markdown emoji parser: https://github.com/markdown-it/markdown-it-emoji/issues/4#issuecomment-222130810

For now, I've disabled shortcuts entirely. I haven't heard from a staff member one way or the other what the decision will be when the underlying issue with links is fixed. If you'd like to track the conversation, comment on or press the subscribe button for https://github.com/HabitRPG/habitica-markdown-emoji/issues/4
