### ISSUE TITLE
Unexpected death causes item loss

### ISSUE THREAD

**Issue by AranelS** [HabitRPG/habitica#7528]
General Info
- UUID: 77f27b3d-09fc-4d21-8484-d945d39c198a
- Browser: Firefox
- OS: Windows 7
### Description

[//](#): # Yesterday I could not get the page to load all day (I can't report the errors because they aren't happening anymore, sorry), but I didn't worry about it much because my health was (at least close to) full and I only lose about 5 health if I forget to check my dailies.

Today it was reported that my character had died. I'm not in any quests at all. I was able to restore my gold, level, and experience, no problem. But I can't get back the Boreal Robe that was "broken". I want it back.

**Comment by Alys** [comment]
I'm sorry about the errors! I'm not able to work out what was causing them for you, and we weren't having any site-wide problems yesterday, but if it happens again, try going to https://habitica.com/static/clear-browser-data and clicking on the button there, and then before you log in again, clear your browser's cookies for the habitica.com domain.

Losing an item when you die is actually a standard part of death rather than a bug - if you'd like to know more, you can read about the effects of death on the wiki's [Death Mechanics](http://habitica.wikia.com/wiki/Death_Mechanics) page. The good news is that you can always buy back the item you lost from your Rewards column! If you don't wan to wait until you've earned the gold through doing tasks, you can go to Settings > Site > [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) and use that to give yourself back the gold.

I'm going to close this now, but if you have any more questions, you're welcome to ask them. If the error happens again, comment here with a description of what occurs and we'll reopen this.

**Comment by AranelS** [comment]
I didn't know you could buy back seasonal items, thanks! 

I know that losing an item is a standard part of death--that wasn't the bug, the death was the bug. My character should definitely not have died after missing only one day of dailies.
