### ISSUE TITLE
Repetitive "5/30/16" & Lost Almost Everything.

### ISSUE THREAD

**Issue by ShuLongNu** [HabitRPG/habitica#7551]
General Info
- UUID:  cf9a1419-cef1-47d8-921d-a7d7f38da424
- Browser: Chrome
- OS: Windows 10
### Description

After the fix on habitica today regarding on our inability to check off our tasks, logging in issue and getting some sort of null error, I found that I have lost 2 levels, a shield, all my money, and my dailies streak. 

None of this makes sense, because I finished all my tasks and dailies yesterday and couldn't check them off today due to the bug going on.

I went into the progress graphs of the dailies to check, and I found that 5/30/16 has been repeated several times and there are days missing.

![screenshot 2016-05-30 17 25 20](https://cloud.githubusercontent.com/assets/19656152/15658610/8249551c-268c-11e6-8cd4-8b9ffa028daa.png)

**Comment by librarianmage** [comment]
did they also all turn red?

**Comment by ShuLongNu** [comment]
all except the daily challenge "word of the day"

**Comment by paglias** [comment]
Note for devs: this happens because we're  saving user and tasks separately (while concurrently) so it's possible that a task is saved correctly before the one that errors stop the whole process.

**Comment by crookedneighbor** [comment]
Did cron run multiple times because of the bad value in the challenge object?

**Comment by Alys** [comment]
@ShuLongNu had also made a report of this by email and I was helping them there, so here's some extra information they have just given me there:

"The first time I got on Habitica today was between the time period of 1PM and 2PM EST. It was the same time when I notice I lost everything and having the same problem with most people who are reporting an issue."

@ShuLongNu we'll deal with this in GitHub now rather than by email to avoid duplicate handling but see the information in my email to you about Fix Character Values for restoring your stats.

**Comment by Alys** [comment]
@ShuLongNu had also made a report of this by email and I was helping them there, so here's some extra information they have just given me there:

"The first time I got on Habitica today was between the time period of 1PM and 2PM EST. It was the same time when I notice I lost everything and having the same problem with most people who are reporting an issue."

@ShuLongNu we'll deal with this in GitHub now rather than by email to avoid duplicate handling but see the information in my email to you about Fix Character Values for restoring your stats.

**Comment by Alys** [comment]
@ShuLongNu had also made a report of this by email and I was helping them there, so here's some extra information they have just given me there:

"The first time I got on Habitica today was between the time period of 1PM and 2PM EST. It was the same time when I notice I lost everything and having the same problem with most people who are reporting an issue."

@ShuLongNu we'll deal with this in GitHub now rather than by email to avoid duplicate handling but see the information in my email to you about Fix Character Values for restoring your stats.

**Comment by Alys** [comment]
@ShuLongNu had also made a report of this by email and I was helping them there, so here's some extra information they have just given me there:

"The first time I got on Habitica today was between the time period of 1PM and 2PM EST. It was the same time when I notice I lost everything and having the same problem with most people who are reporting an issue."

@ShuLongNu we'll deal with this in GitHub now rather than by email to avoid duplicate handling but see the information in my email to you about Fix Character Values for restoring your stats.

**Comment by paglias** [comment]
@crookedneighbor yes. because lastCron is set after all task and the user have been saved correctly even if 1 fails it would restart the process from the beginning while having already saved 99% of progress. Ideally this should never happen but when there's a problem saving data it can happen.

**Comment by crookedneighbor** [comment]
Ahh. That makes sense. We should definitely save lastCron at the beginning then. 

@ShuLongNu would you like the history and color for your tasks reset to what they were this morning? We have a db backup from 10 hours ago, which would be before the problem occurred.

**Comment by paglias** [comment]
The problem with setting lastCron at the beginning is that <cronSignature
would be set at the end anyway so it won't change much and could do more
harm than good since cron would not fully run for at least another 24hrs...
we have to find a different solution
Il 31 mag 2016 12:05 AM, "Blade Barringer" <notifications@github.com> ha
scritto:

**Comment by ShuLongNu** [comment]
@crookedneighbor yes, I would appreciate that

**Comment by crookedneighbor** [comment]
@ShuLongNu your task value and histories should be back to normal. Report here if that is not the case.

**Comment by ShuLongNu** [comment]
@crookedneighbor  it seems to be dailies are fixed, but my shield and I'm not sure if it's also the rod that's not back to normal, because the kite shield wasn't broken yesterday and the rewards is still saying 20 coins for acolyte rod

not sure if those are part of history.

**Comment by crookedneighbor** [comment]
It's totally separate. I didn't want to modify your account any more than necessary since you could have made changes since the backup data I have. 

You can just use the "Fix Character Values" button on the settings page to grant yourself enough gold to purchase them back. Let me know if you need additional assistance, happy to look into it.

**Comment by ShuLongNu** [comment]
ok thanks!

**Comment by paglias** [comment]
Closing as it seems resolved
