### ISSUE TITLE
Health points drop dramatically and repeatedly without reason (not in quest)

### ISSUE THREAD

**Issue by rongqingpin** [HabitRPG/habitica#7557]
General Info
- UUID: 217e89b1-62d9-456e-b801-9d22aa6a4b39
- Browser: tried both safari and opera
- OS: 
### Description

My health points have dropped several times with no apparent reason for a few days. I'm not currently in a quest (the quest in my party hasn't started). It happens during the day, after I've logged in for several hours, when I complete a daily or a task. Sometimes it drop by 8~10 points. really frustrating.

**Comment by crookedneighbor** [comment]
Are you receiving any red error messages?

**Comment by rongqingpin** [comment]
What do you mean by error messages? I only have messages noticing me how many health points are dropped. They are in red though...

Thanks.

**Comment by Selantri** [comment]
1c265ce6-ec4a-4aa5-8363-19ffd9fce52d
Browser: Firefox
OS: Apple 10.10

I'm having a problem too where, when I first log on and click something, I lose health for no apparent reason. At first it was just  10 or 17 HP, but the past two days, it's been over 50 HP, causing player death every single time I log in. My undone dailies and quest damage cannot account for it. Super frustrating.

**Comment by paglias** [comment]
@rongqingpin @Selantri can you try logging out of Habitica?

**Comment by rongqingpin** [comment]
I have logged out and logged back in. Still the same thing. After the health points from yesterday's activity are taken off, I rearranged some tasks and checked off a few dailies; then some points are taken off with no apparent reason - not in a quest, didn't click on bad habits, etc. I logged out once more and the points taken off didn't come back either.

**Comment by paglias** [comment]
No errors recorded for @rongqingpin

**Comment by EHLOVader** [comment]
be3ac978-507a-4234-b5c4-d044a3bcc0eb
Browser: Chrome
OS: Apple 10.11

I had an issue over the past few days where it drained all my health after I saw a level up for completing all my dailies the night before.

This follows another issue which wasn't formally reported but after the maintenance I was seeing next days dailies after midnight instead of my remaining dailies. Something I do often with a cron scheduled at 3am instead of midnight.

**Comment by rongqingpin** [comment]
So can you check why the points keep dropping?

**Comment by EHLOVader** [comment]
Would it be possible to expose a ledger of all the scoring in the system? 

Obviously such a log would take lots of space and certainly it shouldn't be used for tallying the live values, but in cases like this it would allow me to audit the scoring myself to identify issues that happened. Might even offer an interface for quickly reversing small items in the scoring without much fuss.

**Comment by quin-jay** [comment]
@EHLOVader If you click the "Data" button in the toolbar, you can use a couple of the options in the Data Display Tool to show you the exact score of every one of your tasks. It's not ideal but it's probably the best place to start if you're trying to find a rogue task.

**Comment by Selantri** [comment]
@paglias  This morning I had no large, unexpected drops in health. After logging out and back in and doing a few more tasks, still no drops. Maybe that fixed it? I also stayed on past the chron turn-over last night, which I have not done since the problem started.

**Comment by paglias** [comment]
@Selantri great news! We deployed a fix that hopefully should fix this problem and it looks like it's worked for you!

**Comment by rongqingpin** [comment]
Could it be I'm listed in two parties by mistake? This morning when I logged in, I lost 10 health points. But yesterday I only had one daily incomplete, which should be 2 or 3 points at most. Also the party I'm currently in haven't started a quest yet. So it makes no sense how the 10 points were lost...

**Comment by crookedneighbor** [comment]
It's impossible to be in two parties at once now (since the party id is defined as a string on the user object).

**Comment by crookedneighbor** [comment]
@rongqingpin do you use only the website? Or do you use one of the mobile apps as well?

**Comment by rongqingpin** [comment]
I just use the website. I downloaded the app (iOS) but rarely open it.

**Comment by rongqingpin** [comment]
I'm pretty sure somehow I'm in two parties at the same time. I just got a notice that a quest is completed, which is not the one I'm currently in with my party!

**Comment by Alys** [comment]
@rongqingpin Your current party ID is bdf39d10-4e04-4c69-8d31-608aa9fb72aa - that's stored in your user account and there's space for only one party ID, so it's not meant to be possible to be in two parties. You can find that same ID on the party page, in the left-hand column near the bottom. If you ever think that you are in a different party, please look for the ID on that page and tell us what it is, if it is different than bdf39d10-4e04-4c69-8d31-608aa9fb72aa.

However it's much more likely that the quest completion notice was cached from earlier - your party completed Snackless Monster quest on 2016-05-31 21:00 UTC - was that the completion notice you saw?

Your party is in the Necromancer quest now, so any sudden health loss could be due to that. When you next see health loss, please immediately go to your party page on the website and click the "fetch recent messages" button and look for quest boss attack messages that match the amount of health lost. If you experience any health loss that does not match an attack message, please tell us how much the health loss was and at what time, as accurately as you can. Please also tell us the time zone.

**Comment by rongqingpin** [comment]
Thanks, I see. I left my old party in the middle of a quest, and I wasn't in a quest with my new party until yesterday. Is it possible that I was still in the old party's quest although I'm in a new party (but haven't started a new quest)? That would explain the quest completion notice I saw and the unexplained lost health points. Now that the old quest is completed and I've started the new one, hopefully I won't see those problems any more.

**Comment by crookedneighbor** [comment]
@rongqingpin Thank you for that information! While leaving a party should clean up any data related to being in that party's quest, it's possible there's a bug some where. We'll investigate that.

**Comment by Alys** [comment]
@rongqingpin I believe I've removed you from your previous party's quest as part of my clean up for https://github.com/HabitRPG/habitrpg/issues/7653

I'm closing this now but if you experience more unexpected health loss, comment here again and we'll reopen this.
