### ISSUE TITLE
Loosing life when doing some tasks 

### ISSUE THREAD

**Issue by Boreale** [HabitRPG/habitica#7560]
I noticed, not long after the update that sometimes I'm loosing points of life when I do some dailies or habits. Sometimes 2 points, sometimes 7 !!! I don't want to loose my game because of that ..
I'm not sure but I also think it happened for mana, my mana bar  fell at less than 100 despite I didn't change anything in my equipment ..

Is it possible to fix this ?

Thanks

**Comment by crookedneighbor** [comment]
What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.   

Did you see any errors that looked something like this?

![null value for challenge](https://cloud.githubusercontent.com/assets/4967571/15656992/8b30a44e-26ca-11e6-8964-632de4f09fe6.JPG)

**Comment by Boreale** [comment]
My ID, like my username is 67ac4995-6cdd-444e-ad1f-3ab2fd23d5ba.
I don't see any of this messages, it's just when I check a task, daily or habit that I see a notification like "-2.6 health" on the topright.

**Comment by Alys** [comment]
@Boreale You're in a large party that is doing a boss quest. It's likely that the health loss you see comes from the boss attacking the party because of another player's incomplete Dailies. The next time you see one of those health loss messages, go to the party page on the website and click the "fetch recent messages" button. If you're on the app, go to the chat section of the party screen. Look in party chat for a message saying that the boss attacked the party, and see if the amount of health loss you noticed matches the attack.

If you  keep seeing health loss that cannot be explained by a boss attack, please tell us.

**Comment by paglias** [comment]
@Boreale I would also try logging out, comment here if it's still happening after that
