### ISSUE TITLE
APIDoc - Create template to allow sending API requests from the APIDoc page

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#7561]
See http://apidocjs.com/#template

**Comment by shervinmathieu** [comment]
The template should include fields to input user ID and the API password, right?

**Comment by Alys** [comment]
@velezsarain Yes.

**Comment by shervinmathieu** [comment]
Would it be ok to leave out the api calls that take complex parameters (ex: createChallenge) and the ones that may be undesirable (like the entirety of the authentication related calls)?

**Comment by crookedneighbor** [comment]
@velezsarain no.

Also, just an FYI, I'm going to be very picky about how this is implemented 😄

**Comment by shervinmathieu** [comment]
This is going to be harder than I thought...

I'm still going to give it a shot because I kinda opened this one

Don't expect this to be finished soon

**Comment by librarianmage** [comment]
@velezsarain You might want to take a peek at the api docs from v2

**Comment by shervinmathieu** [comment]
After trying to do this I'm afraid apidoc isn't quite ready yet to send sample requests that contain arrays... The doc itself can be written but the sample requests are bugged and will not fill the parameters correctly.

In general apidoc does not like arrays

Example:
I want `body: { tagDetails: { name: 'morning2'}}`

But apidoc generates `body: { tagDetails: '', 'tagDetails.name': 'morning2' }`

Unless anyone else wants to pick this one up or go debug apidoc this will have to wait

**Comment by crookedneighbor** [comment]
Could you share a branch or snippet with what you've done?

**Comment by shervinmathieu** [comment]
Sure.

I only modified 1 file : https://gist.github.com/velezsarain/09524b04528eba8bfe9466114e508a2f

So I got getTags working just fine because it's only a pair of headers. But for updateTags, both

```
/**
 * @apiDefine tagDetails Tag data
 * @apiParam (Tag data) {String} tagDetails[].name Tag name
 */
```

and

```
/**
 * @apiDefine tagDetails Tag data
 * @apiParam (Tag data) {Object[]} tagDetails Tag name
 * @apiParam (Tag data) {String} tagDetails.name Tag name
 */
```

Do not work. The first one will produce an incorrect field "tagDetails[]" (not an array), the second one will create a unwanted tagDetails field along the tagDetails.name field, wich will produce the above result (not an array either).

Do note that the second one will print a correct apidoc with name being a field of the tagDetails array. So it's not a syntax issue.

As you can see both [here ](https://github.com/apidoc/apidoc/issues/23)and [here](https://github.com/apidoc/apidoc/issues/260), these issues are known but are not yet fixed.

**Comment by librarianmage** [comment]
Those issues have still not been fixed

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by crookedneighbor** [comment]
I'm going through old issues that I had opened on Github, I assume this issue is low enough priority that it's not really even worth keeping open. Agree?

**Comment by Alys** [comment]
I agree with closing it. I don't think the benefit of the template is worth the time to set it up and maintain it.

We saw only a few posts lamenting the loss of the template feature from the previous API's docs. If we do see any complaints about this being closed, we can work to clarify the wiki's instructions for testing API routes.

I believe there's also third-party websites that can be used to test documented APIs. Contributors could look into that and we could link to them from the wiki if needed.

I'm closing this now but if staff disagree, of course reopen it. :)
