### ISSUE TITLE
No Cron? Dailies not reset

### ISSUE THREAD

**Issue by itsasooz** [HabitRPG/habitica#7562]
General Info
- UUID: 312f9e64-7c17-40dc-b10c-3c03afc948a3
- Browser: Chrome
- OS: Windows 8.1

Logged in at usual time to find Dailies not reset; multiple reloads did not fix this.  Checked off other dailies, which remain checked off after multiple reloads.

**Comment by citrusella** [comment]
Did you lose any health?

**Comment by itsasooz** [comment]
I didn't have any nongrey unchecked dailies, so I don't know whether health would have been lost.

**Comment by citrusella** [comment]
Okay, I just asked because it sounded like it could be this bug: #4313 

That bug often causes damage because what happens when the bug occurs is that the browser doesn't send the checks to the server until the next day, which means any dailies that were due yesterday that haven't reset would have caused damage (and all affected dailies would have reset to 1 on the streak counter).

But there have been a lot of cron bugs lately so it's entirely possible that may not be it. XP

**Comment by itsasooz** [comment]
Ah!  I see.  I had seen that one, but read "dailies unticked" and assumed it was a different problem from mine.  Should I go post there?

**Comment by citrusella** [comment]
I'm not sure (mostly because I don't have much experience with telling people things on Github... though I'm sure it wouldn't hurt if you'd like to comment); at the very least the advice might help you to fix any effects you might have experienced.

(I'm also not sure whether or not you should go there because I'm not sure it's your exact problem? If it is, then that's great, but I feel I attribute too many cron bugs to that one. XD Maybe read through it (if you haven't already?) and decide for yourself? :smile: )

**Comment by Alys** [comment]
@itsasooz I think @citrusella's assessment of this might be correct - it could have been that #4313 bug. Even if it's not, as she says, the Advice section near the top will help you untick your Dailies without losing gold, experience, and mana, and using the Data Display Tool each night will help you notice before cron that the bug has happened (although that might not be worth your time if this bug doesn't happen often for you; for some players it's very rare). If you notice your Dailies not becoming unticked by cron when you're certain that the server did have them recorded as ticked, please do tell us here! You're also welcome to comment on this issue if you have questions.
