### ISSUE TITLE
Cron should pull quest key from party

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#7567]
When cron runs, it pulls the quest key from the user. The key can get out of sync with the group for unknown reasons. Cron already loads the party so it can use the key from the party.

**Comment by crookedneighbor** [comment]
I'm working on this.

One hiccup I discovered is that currently the items for collection quest get determined during the [randomDrop op](https://github.com/HabitRPG/habitrpg/blob/28f2e9c356d7053884107d90d04e28dde75fa81b/common/script/fns/randomDrop.js), which needs the quest key to happen. 
1. Since we never actually display this data, we could instead just log number of drops for collect progress and then have the server make the call at cron for _what_ the items are. This would mess up how the DDT reports the quest progress. CC @Alys 
2. We could pass the party or the quest key as an argument, but I think we'd end up with the same weird inconsistencies if the party data is out of date. 
3. Leave it as is and figure out why the key isn't being set correctly?

**Comment by Alys** [comment]
I'd be fine with logging just the number of drops. I can change the DDT so that it reports only "x drops" rather than "y Fire Coral and z Blue Fins". The types of drops are nice for gamification but not really necessary for motivation.

Although now that I've typed that... 

There could be cases where you know you already have enough Coral but need more Fins and you'd want the DDT to tell you how you were going with that. It's a bit of an edge case though, and the quests that have more than one type of collection item are all short quests, so you wouldn't be in suspense for long.

On the whole, I think more reliable code is more valuable in this case! There have been a few bugs in the past that resulted in the wrong key being set or the wrong collection items being put in the user's account, so working out now what particular bug caused the current problem won't be much help in the long term.

**Comment by Alys** [comment]
Just don't let me forget to modify the DDT as soon as this goes live!

**Comment by Alys** [comment]
Ohh!!! The best party about the idea to just log number of drops, not type of drop:

You can make players accumulate quest drops ALL the time, just as they accumulate boss damage all the time. Then when a collection quest starts late in the day, they've already made some progress towards it (just as they do for a boss quest). This is a nice bonus for the player, and makes the two types of quests behave more consistently compared to each other, and makes the code simpler, and removes potential future bugs! Go go go! :)

**Comment by paglias** [comment]
I may be wrong but since randomDrops are based on the user stats at the moment of the randomDrop call we don't risk producing different results since it'll be called at a different time with (probably) different stats? Also all drops would be determined by the same type of drops instead of different type of drops (at the morning I may have 50HP and 200XP while in the evening 35HP and 300XP)

**Comment by Alys** [comment]
Ah no, the way I see it, there's still going to be the random drop calculation made at exactly the same point as it is now, and the number of random drops will still be stored in the user's party.quest.progress.collect object as now. The only different is that they're stored as simply a number, rather than as a type of drop, and the type of drop is then worked out on cron, using the stored number.

So for example, instead of the current situation:
`user.party.quest.progress.collect: {blueFins: 3, redCoral: 2}`
we'd have:
`user.party.quest.progress.collect: 5`
and then when cron ran, it would do a trivial random thing to break up the 5 drops into blueFins and redCoral (doesn't matter exactly how).
It would be even easier for the collection quests where there's only one kind of drop possible - no need to split up the items found.

**Comment by paglias** [comment]
Hmm but we would not know if the party is on a quest or not.. and on which type of quest. We can probably just calculate the drops anyway and just discard them at cron if the party is not doing a collect quest

**Comment by Alys** [comment]
Yes! Just like for boss quests - more consistent code. :)

**Comment by crookedneighbor** [comment]
^ could have a tavern collection quest boss :)
