### ISSUE TITLE
Lost food, potions and eggs

### ISSUE THREAD

**Issue by Efox917** [HabitRPG/habitica#7576]
General Info
- UUID: c1-----8f
- Browser: Safari 9.1.1
- OS: Mac 10.11.5
### Description

While I was feeding my zombie pet rotten meat, my food supply disappeared.  I had about 21 rotten meats.  I fed 9 to Zombie Wolf, and started feeding Zombie Tiger.  I fed Zombie Tiger about 4 rotten meats, and the rest of the rotten meat supply disappeared.  I tried refreshing, and that didn't help.  I couldn't find a related issue in GitHub.  

In the past, potions and eggs have disappeared as well.  I didn't pay it any mind because I have more than enough of both.  The last time I sold eggs and potions back to the market, I was getting my inventory down to 50 each.  Much to my surprise, my red potions (and maybe one other) disappeared completely (e.g. 0 from over 50).  I haven't tried selling anything since.

**Comment by crookedneighbor** [comment]
FYI, when you edit an issue, we don't get an email alert that changes have been made to the issue. I'm going to copy and paste your text and then delete this comment so that we have a record in email about the issue. 

General Info

UUID: c1e6d23e-aa8c-48a1-83eb-eeb6e41c198f
Browser: Safari 9.1.1
OS: Mac 10.11.5
Description

While I was feeding my zombie pet rotten meat, my food supply disappeared. I had about 21 rotten meats. I fed 9 to Zombie Wolf, and started feeding Zombie Tiger. I fed Zombie Tiger about 4 rotten meats, and the rest of the rotten meat supply disappeared. I tried refreshing, and that didn't help. I couldn't find a related issue in GitHub.

In the past, potions and eggs have disappeared as well. I didn't pay it any mind because I have more than enough of both. The last time I sold eggs and potions back to the market, I was getting my inventory down to 50 each. Much to my surprise, my red potions (and maybe one other) disappeared completely (e.g. 0 from over 50). I haven't tried selling anything since.

**Comment by Alys** [comment]
@Efox917 The ID you provided isn't your User ID (unless you've deleted your account since then). Can you please paste your User ID into a new comment?

I've obscured most of the code you provided in case it's your API token. Once you've provided your User ID, I'll check to see if it was your token, and if so, I'll change your token. This will either log you out of Habitica immediately, or cause the website and app to behave strangely until you do log out, so keep that in mind. 

We can't investigate the past problems since it will be too hard or impossible to find data about them now, but if you provide your user ID we'll look into the most recent problem.

**Comment by Efox917** [comment]
Hi, I just saw this.  Sorry for the tardy response.  I hope this is the user Id you need:  8f9110b4-50d7-446b-a142-0c6ca0cb5029
I’ll put this in Github as well.

**Comment by Alys** [comment]
@Efox917 I'm really sorry I didn't get back to you sooner! I should have been keeping on top of this.

This would be an example of this issue: https://github.com/HabitRPG/habitrpg/issues/7851 so I'm going to close your issue - we'll investigate in the other one and hopefully find a fix!

**Comment by Efox917** [comment]
Yes, this is the problem.  I sold a bunch of eggs recently and did so slowly and didn’t experience the problem.
Thanks for your time and attention!
