### ISSUE TITLE
Unable to purchase rewards if coin amount is exact in gold

### ISSUE THREAD

**Issue by geebru** [HabitRPG/habitica#758]
This has happened twice so I figured I'd put in a bug report. I have 25g 98s and am unable to purchase the Chain Coif. Once I get to 26g I'll be able to purchase it (based on what happened last time, I had to go OVER the price to actually buy it).

I should be able to purchase it because I still have silver left over (negating the fact that this might be a safeguard to avoid letting you go absolutely broke), no?

![Screen Shot 2013-04-01 at 11 58 31 AM](https://f.cloud.github.com/assets/806033/324411/52fc4160-9ae5-11e2-811e-f8edaeb0286b.png)

**Comment by lefnire** [comment]
It's actually a bug. Filed somewhere, but can't find it now. Will fix later

**Comment by paglias** [comment]
The problem is that the GP amount shown in the rewards coins is rounded up, so for example @blackpandemic didn't had 25.98 gold but 24.98.

The hero box instead show the gold amount rounded down using:

`{floor(@profile.stats.gp)}`

![Spazio di lavoro 1_005](https://f.cloud.github.com/assets/589911/413327/eb5a2c9c-abed-11e2-918e-26f9e3061cf4.png)
