### ISSUE TITLE
Lost health (and level) upon using Burst of Flames

### ISSUE THREAD

**Issue by msiwek** [HabitRPG/habitica#7609]
Just used the Burst of Flames after being left with 2HP (my party is fighting a quest boss, others are not performing well :P ) and wanted to boost my health by leveling up, but after using Burst of Flames on a task I lost HP and got killed... It's really bummer, can you look into that? I cannot recreate it, due to obvious reasons, so maybe you can check the log.

User ID: 3963fa54-22e8-4597-b514-26a94898bd80

Best,
Maciej

General Info
- UUID: 
- Browser: 
- OS:

**Comment by SabreCat** [comment]
Given that you were in a boss quest, could it be that a party member's check-in delivered the final 2+ damage sometime between your previous action and when you cast Burst of Flames? You would then see the damage when you BoFed, as that's when your Health next had the chance to sync with the server--it's not that the BoF caused the damage.

**Comment by msiwek** [comment]
Hmm.. I seriously doubt that given the hour (6 pm). Would be really weird
to have such time set for day end, but I'll ask friends.

**Comment by citrusella** [comment]
It doesn't matter when the time was set for the day to end, if the person logged in then. (Some days, I don't log in until almost midnight! :worried: ) Your cron (the actual day rolling over for you) doesn't actually occur until the first time you log on after your day starts. That would mean someone could cause damage to the party if they logged on for the first time of the day at 6pm.

**Comment by Alys** [comment]
@msiwek You don't actually have to ask your friends - you can see when damage from the boss occurred in your party chat. On the website, go to the party page and click the "fetch recent messages" button to load the latest posts.

From looking at your party's quest progress log, there was damage done to the party about 6 or 7 hours ago, so that is likely to be what caused your health loss. I'm closing this, but we can reopen if necessary. You're welcome to comment here if you have questions about any of this.
