### ISSUE TITLE
no clear "login" option on the home page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7634]
The home page contains a "Play Habitica" button and a "Join for free" button but no obvious button for logging in after joining.

Every so often, we see users who've come from the apps (often via email links) being confused about how to get into the website. They don't realise they can use the play/join buttons to log in.

@lemoness how would you prefer this be handled? Adding a new button? Renaming one to "Login"? Or adding "login" to one in addition to the existing text?

**Comment by Hus274** [comment]
From my experience, I was only using the web client and the first time I logged in on a new computer, I wasn't sure where I was supposed to sign in as an existing user. It would definitely be nice to have a login button on the main page that makes it clear where to log in for existing users.

I like the play button text because it's short and sweet so I feel like it would make sense to change the join button to be something like "Join for free / Login". Just my thoughts

**Comment by IstraLouise** [comment]
I am having trouble with the buttons on the homepage.  I recently switched computers and am back to using Windows 8.1 with Firefox 47.0 and when I click "Play for Free" or anything else.. it goes through some web addresses like its loading a page, but it doesn't go anywhere.  Three other people on the Facebook page have stated that they've had the same problem for at least 24 hours.  This is a big deal to me since my preferred way of accessing the site is by computer.  Just easier for using Markdown, making challenges and editing the guild when I have to.

**Comment by Alys** [comment]
@IstraLouise Please try going to https://habitica.com/static/clear-browser-data and clicking the red button there, and then (BEFORE logging in) clear all "habitica.com" cookies from your browser. After that, try to log in. If you still can't log in, please open a new issue and we'll help you further there. This issue is specifically about renaming the buttons on the home page. :)

**Comment by librarianmage** [comment]
How about renaming the small button "Play Habitica (Login)"?

**Comment by lemoness** [comment]
That's a bit awkward.

Maybe we could try "Enter Habitica"? It's also more flavorful.

**Comment by librarianmage** [comment]
That is definitely better.
