### ISSUE TITLE
Displayed name doesn't change

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#764]
Is it possible to change a character's name? The option under "Profile" looks like it's supposed to do that, and when I change it the name displayed in the box on my profiles screen changes. However, the name that's displayed on my main screen and the name party members see for my character don't change. 

Name on profile screen: 
![Name on profile screen ](https://f.cloud.github.com/assets/1575692/330713/c4349b98-9bd5-11e2-9b30-81031d6f299e.png)

Different name on main screen:
![Screen Shot 2013-04-02 at 13 43 41 ](https://f.cloud.github.com/assets/1575692/330722/1d4d7db2-9bd6-11e2-8ad6-4bc30bf154e7.png)

**Comment by wc8** [comment]
Hm... I think the name above the character is the username and the name in the profile is supposed to be your name (although, theoretically, you could enter something else).  
I'm marking this down as a suggestion, since I think it's functioning as designed. Would the [option to change username](https://trello.com/c/4h5W1gMd) meet your needs?

**Comment by octern** [comment]
That is what I'm looking for, thank you.
