### ISSUE TITLE
Validator failed for path `auth.local.email` with value `[my_username]`

### ISSUE THREAD

**Issue by Lelldorian** [HabitRPG/habitica#7641]
General Info
- UUID: a8cf8b58-929d-433a-8fce-2c0ab066722a
  ![habitica_error](https://cloud.githubusercontent.com/assets/19857488/15965373/bbd5621e-2f1d-11e6-8f97-66471aefbfb8.jpg)
- Browser: Firefox 46.0.1, Chrome 51.0, Habitica AndroidAPP
- OS: Windows7
### Description

When I load habitica.com web, I receive this message: Validator failed for path `auth.local.email` with value `[my_username]`

I cant interact with my tasks or any information in my profile. Changes cant be saved.

I have the same problem in different browsers and even in the android app.

**Comment by Alys** [comment]
That has happened because when you created your Habitica account, you didn't enter an email address but instead you put just the name "lelldorian" in the email field (or you might have registered with an email address but then later changed it to your name). We've recently implemented stricter checking for email addresses, which is why you're seeing that warning message now.

I've fixed the immediate problem of you being unable to interact with your tasks by setting your account's email address to "example@example.com".

You can change that to a real email address from Settings > Site on the Habitica.com website. "Settings" is the gear-shaped icon on the top right. I recommend that you do use your own email address because then if you ever forget your password, the website's "forgot password" feature will be able to send a new one to you.

**Comment by Alys** [comment]
That has happened because when you created your Habitica account, you didn't enter an email address but instead you put just the name "lelldorian" in the email field (or you might have registered with an email address but then later changed it to your name). We've recently implemented stricter checking for email addresses, which is why you're seeing that warning message now.

I've fixed the immediate problem of you being unable to interact with your tasks by setting your account's email address to "example@example.com".

You can change that to a real email address from Settings > Site on the Habitica.com website. "Settings" is the gear-shaped icon on the top right. I recommend that you do use your own email address because then if you ever forget your password, the website's "forgot password" feature will be able to send a new one to you.

**Comment by Alys** [comment]
That has happened because when you created your Habitica account, you didn't enter an email address but instead you put just the name "lelldorian" in the email field (or you might have registered with an email address but then later changed it to your name). We've recently implemented stricter checking for email addresses, which is why you're seeing that warning message now.

I've fixed the immediate problem of you being unable to interact with your tasks by setting your account's email address to "example@example.com".

You can change that to a real email address from Settings > Site on the Habitica.com website. "Settings" is the gear-shaped icon on the top right. I recommend that you do use your own email address because then if you ever forget your password, the website's "forgot password" feature will be able to send a new one to you.
