### ISSUE TITLE
Translate Mongoose validation messages

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7643]
Pass the string key as the error message and then in the error handler middleware substitute it with the translated string since we have access to `req.language`

**Comment by khipkin** [comment]
Suggestion: add [translations] label.

**Comment by jerell-mendoza** [comment]
@paglias , I take a look at this one. Do we still need work on it?

**Comment by paglias** [comment]
@jerellmendoodoo it's something we're still interested in but not an high priority right now. But if you want to work on it, that's great, it might just be a while before we can review it since we're in the middle of a website redesign project

**Comment by jerell-mendoza** [comment]
@paglias , hi it's been a while, but I've started looking into this - is this simply adding:
`responseErr = new BadRequest(res.t(err.message));` and translating the mongoose validation error? I'm wondering what happens if we don't have a proper mapping for the the error message thrown?

In the comment in the error handler it says:
`// TODO standard message? translate?`
Do we want to throw in a standard error message instead?

let me know, thanks!

**Comment by paglias** [comment]
@jerellmendoodoo This is a bit old so I might not remember exactly but the idea was to change the Mongoose error messages with a code like "DUPLICATE_KEY_XXX" and when handling the error substitute the error code with `res.t('DUPLICATE_KEY_XXX')`

**Comment by jerell-mendoza** [comment]
@paglias , ah I see, I think this is out of my realm of know-how, I don't think I can tackle this one.

**Comment by paglias** [comment]
@jerellmendoodoo no worries :)

**Comment by lemoness** [comment]
Labels added.

**Comment by Alys** [comment]
We have a new strategy now of not translating error messages that are not shown to the user so I'm closing this.
