### ISSUE TITLE
Dropped item disappeared

### ISSUE THREAD

**Issue by llqt** [HabitRPG/habitica#765]
I'd received a base hatching potion from a random drop, but when I later logged on and checked my inventory it wasn't there and I also lost some experience. I understand it's not possible to reset token items like exp (for obvious reasons), but that was kinda frustrating. Anyway:

Browser: Firefox 17.0 
System: Fedora 17

**Comment by wildcate** [comment]
The same happened to me - due to no internet connection when I clicked the completed list item; this resulted in the completed item reappearing and the potion disappearing, of course, once the connection was re-established. The "offline-reconnect" thingie, unfortunately, only appeared after that. Clicking reconnect, btw, does not do anything for me, I have to reload the page.

**Comment by lefnire** [comment]
I can hook both of you up with your deserved pets if you want - [email me](mailto:tylerrenelle@gmail.com) your user ids and what egg / potion you want. For now, as with almost everything - the real problem is the memory leak, which I devote 30m each day to fixing. Once we get that solve we'll be good.

The long story - memory leak causes restart, y'all are performing actions in-between session re-establishment (the restart takes about 2m), and anything in that slot is lost. Pretty common occurrence, so I need to get it fixed

**Comment by Verie** [comment]
Just had this issue as well. Received a dropped egg, clicked on it, and then all of my daily tasks reset, so no more egg.

**Comment by lefnire** [comment]
@Verie email of (above) offline i'll get you taken care of

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
