### ISSUE TITLE
Orb of Rebirth causes animal ears in 'Customize Avatar' interface to need to be repurchased

### ISSUE THREAD

**Issue by kamni** [HabitRPG/habitica#7662]
General Info
- UUID: fedc44cb-088a-4bc8-8f4f-3e6a1882f042
- Browser: Safari
- OS: OS X 10.11.4
### Description

After using the Orb of Rebirth, the animal ears in the 'Customize Avatar' interface are now locked, even though they previously had been purchased:

<img width="445" alt="screen shot 2016-06-14 at 10 09 36 am" src="https://cloud.githubusercontent.com/assets/101778/16046136/56d81ae2-3219-11e6-9fc5-5418f3d6e247.png">

However, it seems that I can repurchase them using gold:

<img width="360" alt="screen shot 2016-06-14 at 10 09 11 am" src="https://cloud.githubusercontent.com/assets/101778/16046162/6ca6b838-3219-11e6-9e87-7bd04fa5c567.png">

Purchasing them again does unlock them; however, cosmetic non-seasonal items purchased with gems should not be included in the equipment reset when using the Orb of Rebirth.
#### Console Errors

None

**Comment by Alys** [comment]
Ah, it's actually correct behaviour at the moment for all gold-purchasable (non-zero cost) equipment to be removed by the Orb of Rebirth, although we are considering changing that - see https://github.com/HabitRPG/habitrpg/issues/5750 for details.

However you're right that the option to buy them again with gems shouldn't be there because that's misleading. Possibly though the easiest way to resolve that is to include the ears in the list of equipment that  we're considering being left untouched by Rebirth.

**Comment by kamni** [comment]
It seems a bit odd to include them as equipment, because they can be worn with other head gear and they really kind of go with the animal faces (which don't get reset by the Orb of Rebirth). Also, they can be purchased with gold now? I've only ever seen the gem option prior to rebirth -- is this something new?

But anyhow...behavior is unexpected either way. :)

**Comment by crookedneighbor** [comment]
@kamni they're purchased initially on the avatar customization page, but they are technically gear (classified as head accessory). 

They can only be purchased with gold _after_ you have already purchased them once through the avatar customization screen. 

I agree that it's confusing.

**Comment by Alys** [comment]
I'm closing this because it will be resolved when this fix is done:

https://github.com/HabitRPG/habitrpg/issues/7917 "Orb of Rebirth: change to cost 6 gems, not remove any equipment"
