### ISSUE TITLE
Should sorting equipment on an attribute while grouped by type consider the class bonus?

### ISSUE THREAD

**Issue by Gumnos** [HabitRPG/habitica#7701]
As an example, when I group by type and sort by PER, the Jester Hat (PER+15) sorts before the Umbral Hood (PER+12).  But with my Rogue's class bonus, the Umbral Hood actually gives me PER+18 (12 + 6) which is better than the Jester Hat.  When grouped by class, it's not an issue since my class-specific equipment is all together.

Should the sorting take class-bonus into consideration?

**Comment by crookedneighbor** [comment]
I don't think so. If you're concerned about using the class bonus, you can do so by selecting the class.

**Comment by crookedneighbor** [comment]
Though, if the code to do as you suggest is simple, I might chang my mind.

**Comment by Alys** [comment]
I think it should consider the class bonus to make it easy to find your best piece for a stat. Using the class grouping option doesn't really help with that because off-class and non-class gear can have better bonuses in some cases. Using the new type grouping option and selecting an attribute sort order is an excellent way of optimising your battle gear, and ignoring the class bonus feels like a bug for that use case.

**Comment by Gumnos** [comment]
I'm mostly concerned with "I want the best PER bonus from my equipment, so group by location-type, sort by PER, and pick the top item for each item-type".  But with the current sort, the top pick doesn't get me the best resulting stats.  It's not a big deal now that I know about it, but it might throw people who haven't waded through obscure corners of the wiki.

**Comment by Gumnos** [comment]
Just wanted to say thanks for this, @crookedneighbor . Use it **all the time** now.
