### ISSUE TITLE
Winner of challenge sees a notification for a previous challenge that they've won

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7716]
Amazon_Warrior (4273f332-21e2-419a-8a35-e462ce341f5c) reports:
**I just won a Challenge-'Help the Poet'-but the alert that came up was for the very first Challenge I won 'A Weekend Fully Booked: 24-Hour Readathon'. The alert said I'd just won the Readathon Challenge, even though that happened ages ago.**

I've seen one other report of a similar problem and I was able to replicate the bug just now.

However I don't know if it happens always or just sometimes. It's probably the sort of thing that could happen always but few people report it.

_edit by Alys 2017-12-01:_

This bug is back. DCL ( 3bd49b39-283b-4d03-8117-7b87e9547e91 ) wrote in the Report a Bug guild: "when I closed a challenge (in the private guild I use to keep weekly to-do lists as challenges) and listed myself as the winner, the pop-up notification said I had won a different challenge! The challenge I closed was 'Weekly Work Tasks,' and the challenge it told me I won was 'Reflect on the Day...' which I have both in my personal guild and my party (and was the last challenge I won). The problem is just the pop-up, as the proper achievement is listed in my profile, and I got the gems I had associated with the challenge."

The code related to this will be different since the new website was released but the behaviour seems the same and the same style of fix might work, even though the tech is different, so I'm reopening this rather than creating a new issue. If other admins want to close an open a new one, feel free. :)

_edit by Alys 2020-04-14:_

It's back again. https://github.com/HabitRPG/habitica/issues/7716#issuecomment-613309165

**Comment by Alys** [comment]
It's worth noting that Amazon_Warrior has won only two challenges, so the challenge listed in the notification was for the previous one that they had won (it was only incidentally their first one). The challenge listed in my notification was the previous one that I'd won.

It might be that the process to send a notification is sometimes reading the user's `achievements.challenges` array before the newest challenge has been saved into that array. Perhaps this bug only occurs if the winner is active on the site at the exact moment that the challenge is closed.

Possibly relevant code from website/server/models/challenge.js :

```
  // Award prize to winner and notify
  if (winner) {
    winner.achievements.challenges.push(challenge.name);
    winner.balance += challenge.prize / 4;

    winner.addNotification('WON_CHALLENGE');

    let savedWinner = await winner.save();
```

Would changing the order of those last two lines fix this?

**Comment by habitrpguser** [comment]
I just want to confirm that this happened to me, too.
It is very likely that I was active (i.e., logged in) on the site at the moment that the challenge was closed.
I'm using the website, not the app.
This is the only time I won a challenge since the API change. So I can't remember any time when this did NOT happen lately. (So it's actually possible it happens always. If you want to find that out, maybe ask in the [⚔ The Duelling Grounds ⚔](https://habitica.com/#/options/groups/guilds/2f6085fe-5382-46d6-a0ac-c1b16f4f7780) or [Short-Term Goal Accountability](https://habitica.com/#/options/groups/guilds/59f699a3-9d22-4d6d-b34a-8fcdf2ad1dac) guilds? They have rather a lot of challenge winners.)

**Comment by paglias** [comment]
The code in the won-challenge modal is written to show not the last won challenge but the previous one

`::user.achievements.challenges[user.achievements.challenges.length - 1]`

Maybe it was needed before the rewrite but now it seems a bug

**Comment by paglias** [comment]
Ignore my previous comment

**Comment by Dewines** [comment]
I just thought I'd post to say that this just happened to me today. I had created a challenge in my private party and today I completed it so I closed the challenge and made myself the winner. It then announced that I had won a completely different challenge, one that I won some time ago.

**Comment by khipkin** [comment]
This happened to me yesterday.

**Comment by Alys** [comment]
I've added this text to the top post:


_edit by Alys 2017-12-01:_

This bug is back. DCL ( 3bd49b39-283b-4d03-8117-7b87e9547e91 ) wrote in the Report a Bug guild:

"when I closed a challenge (in the private guild I use to keep weekly to-do lists as challenges) and listed myself as the winner, the pop-up notification said I had won a different challenge! The challenge I closed was 'Weekly Work Tasks,' and the challenge it told me I won was 'Reflect on the Day...' which I have both in my personal guild and my party (and was the last challenge I won). The problem is just the pop-up, as the proper achievement is listed in my profile, and I got the gems I had associated with the challenge."

The code related to this will be different since the new website was released but the behaviour seems the same and the same style of fix might work, even though the tech is different, so I'm reopening this rather than creating a new issue. If other admins want to close an open a new one, feel free. :)

**Comment by kawunngg** [comment]
same thing just happened to me. it did not occur for the first time, but last time i thought it was because of my cache or something, but now the title was from a challenge i won weeks ago and i emptied my cache yesterday for sure. 

challenge name: ":tomato: Pom Party 2017-11-28"
in Pomodoro Playground https://habitica.com/groups/guild/36d46844-c04c-4c5b-8a00-7fafb09d2697

User ID: ce935e7f-00e6-44bc-a44a-5280553810f0
Win 7
Firefox 57.0

**Comment by TheHollidayInn** [comment]
Judging from the reports and looking at the old PR, I believe the issue is the same. The user object is not updated before the modal is shown. Looking locally, I can see there is a lag and since we return notifications on each request this lag between updating the user and showing the modal is likely with some requests being pretty slow at times.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
I just did a test, creating two challenges, joining them, then closing them with me as the winner. I received the correct notification in each case, so for that specific situation, this bug no longer exists. Maybe it still exists under other circumstances, but I'm closing this for now and we can reopen it again if the bug does get reported again. Thanks @MathWhiz !

**Comment by Alys** [comment]
I'm reopening this because we've had another report of it: https://github.com/HabitRPG/habitica/issues/12067

Anyone who wants to work on this should look through all the comments above (some contain technical details that _might_ be relevant but don't necessarily rely on that), and the two linked PRs in case they give useful hints for a solution. It's _possible_ that the code has lost the fix for this issue during a refactoring.
