### ISSUE TITLE
Pets Suggestion

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#775]
I was thinking that down the road when people have found more eggs and potions they might want to trade them to get a certain combination.  Maybe we could add a "Swap" tab where players could do a 1 to 1 trade of an egg for egg or potion for potion.  Maybe you could charge 1 token from each user for the swap that way you aren't taking away too much functionality from the "Market" and at the same time add a way to use tokens. This small charge would also discourage most users from making a dozen trades to get from, say, base cactus to golden dragon.

**Comment by lefnire** [comment]
a fine suggestion! will keep in mind

**Comment by lemoness** [comment]
I really like this! A fun inter-party or inter-group feature, and the nominal token charge would probably keep it from breaking the system. Once we'd tested it for balancing, I think it could be enjoyable!

**Comment by rixx** [comment]
I wouldn't charge a token; I'd rather let two eggs be exchanged for one (or make that an alternative option).

**Comment by lemoness** [comment]
If people are sending to friends, though, that doesn't balance out. It
would be nice to have one system that could be used for both the
inter-party trading as well as a possible NPC trade, and the single token
covers that very cleanly. Plus, you'd only be paying 25 cents, which is a
third of what you'd normally pay for an egg, but it could help out Habit a
lot in the long run.

**Comment by storian** [comment]
I would like to suggest an alternate to this idea, specifically for the useless hatching potions the game now generates: trade useless hatching potions back to the game for a useful one.  Context: I currently have all Base, White, and Desert pets.  But I pretty much only receive Base, White, and Desert potions from the game.  At this time these potions are not only useless, they are annoying, because not only can I not use them, I can't get rid of them either.  Meanwhile it seems like the only way to get the other potions is to spend actual money.  It would be nice if the game let me trade, for example, 10 or even 20 Base potions for a Golden.

**Comment by Shaners** [comment]
Vendoring useless items for gold is probably going to be the solution at least as a first step. Also keep in mind when new pets are released you'll have need for those base, white, and desert potions again so you probably don't want to zero out on them completely. Trading common potions for rarer ones begins to eat at the already lack luster monetization, so if added would have to come at a high price.

**Comment by lemoness** [comment]
Yeah, our monetization scheme could use some help.

Maybe pay a gem to trade in potions? But again, potions for gold is most
likely to be the result for the interim. I think there's a Trello card to
debate this...

**Comment by dbueller** [comment]
I have so much gold. Maybe I could pay to get rid of some of these potions?

**Comment by jepler** [comment]
As I mentioned in #1585, in the current system a player will need an average of 979 drops until she gets the 90 eggs + 90 potions needed to fill the stable, which is more than 2.5 years at two drops a day; she will likely have an excess of 57 of one kind of egg and more than 100 of some potion (a total of about 890 extra drops).  So clearly something needs to be done, if only "stacking" the eggs and potions in the inventory so that the list doesn't become insanely long. (by "stack" I mean overlap the count on top of the icon rather than showing the icon multiple times)

Personally I think a crafting system would help for potions (so that you can craft your useless base potions up to that coveted gold potion), and at one point I heard a rumbling that we might be able to feed eggs to certain steeds once the food system is created.

**Comment by gkatsev** [comment]
Like people have said above, trading between users and the game would be great. Between users, it would just need approval of both users and with the game it could be like 3 base options would get you a white, 3 white would get you a desert and so on. Probably should be more balanced but something along those lines.
Also, what exactly is a `token`?

**Comment by derekantrican** [comment]
@gkatsev tokens are the same as gems

@lemoness Saw the weekly update! I'm voting for "Sell them back for gold"!

**Comment by wc8** [comment]
My vote: enable both _sell them back for gold_ and maybe also _gem(s) to trade them_.
Reasons: 
1) Selling them back for gold reduces over-supply of potions and eggs, keeping them valuable
2) Unwanted potions and eggs are most likely rewards for progress, so let them be useful for health potions and rewards
3) It's likely people will keep asking for trade option. So, if they don't want to pay a trade fee, they can exchange the potion for gold. If they want to trade it, they support habit a tiny bit in the transaction.

Should we make an actual poll for voting?

**Comment by lemoness** [comment]
I am with @wc8 100% - I was actually dwelling on this last night and came
to the same conclusion. Due to ease of implementation, the
sell-back-for-gold would probably come first, but I think that the
trade-for-a-gem option, if kept simple, could be very useful and also a
good, creative use of gems. It could maybe even be the first step of the
Crafting system we've bandied about for a bit.

Let's make a poll, with the options "Sell back for gold", "Pay a gem to
trade for other potions" , and "BOTH sell back for gold and/or pay a gem to
trade for other potions." Any other options that should be on there?

Also, I was thinking of a way to try to make the trading most feasible (aka
simple). How about this?

5 common potions = 3 uncommon potions = 1 rare potion.

SO! You could trade one base potion for one white potion, or five base
potions for one gold potion, etc. I imagine that for ease of programming,
they;d all have to be the same, i.e. you can't trade four base potions and
one white potion for one gold potion, but maybe we could work around that.

**Comment by Shaners** [comment]
It'd have to be more like 20 base potions for 1 golden potion or it would never make sense to ever buy a golden (since you could buy base or common for cheaper.)

-Shane

-------- Original message --------

**Comment by Shaners** [comment]
Oops that doesn't really make sense since our gem cost is off or likely rounded up if less than zero. But with a trade up mechanic the cost mechanics would have to change too.

**Comment by lemoness** [comment]
Noted - I was just tossing out numbers. If people want the trade model,
then we need to do some number crunching. One method might be paying more
gems to trade with fewer potions?

Example (with made up numbers)

10 base potions + 1 gem = 1 gold potion
8 base potions + 2 gems = 1 gold potion
6 base potions + 3 gems = 1 gold potion
2 base potions + 4  gems = 1 gold potion

Games like Flutter use that sort of escalation mechanic a lot. Each is
cheaper than just straight-up buying it, and easier than paying nothing and
waiting for it.

**Comment by gkatsev** [comment]
I still think that requiring a gem is not a good thing. Perhaps it should be potions+gold or something.
While I don't think habitrpg will necessarily be affected the same way, I know that some games that do in-app purchases but are still free to play can reach a state where you cannot progress any further without paying.
Though, I guess the other option for is to require gems but also allow trading of potions/eggs for gems.

**Comment by Shaners** [comment]
@gkatsev currently you can get all the pets, except for rare, without spending any gems... you'd just have to be extremely lucky or play Habit for a long time. That part is probably not going to change because Habit needs the 'long game' to keep people interested. Also currently pets don't do anything besides being your faithful companion through all your trails and tribulations to self improvement so it's not pay to win. It will never get to that point because we understand the need to provide as much content to free users because a lot of them cannot pay any money. The more free users that exist the more they will tell their friends and drive in the paying users that subsidize the free users play. This is why Habit needs the long game and cannot make all content immediately available / obtainable unless through monetization.

@lemoness in current state there are 3 ways users can get golden potions, all with very positive outcomes. Possibility 1) new user gets really lucky on their first couple of tasks. User at first probably won't understand but will soon learn how lucky they got either through the tavern or talking with friends they learn that they've gotten a super rare drop and will feel really special. They then become more invested in Habit and continue completing tasks hoping to get another drop.

Possiblity 2) a long time user completes a lot of tasks over a long period of time and gets a rare golden potion drop. They are rewarded for the patience and continued progress of improving their lives. Their interest in Habit is renewed and they continue to use Habit.

Possibility 3) a lucky or unlucky user wants a golden pet very badly but doesn't want to wait so they buy gems and pay for the potion. Habit gets money to continue to run and the user gets a cute new pet for display and they are a little more invested in continued HabitRPG use because they have donated money.

Vendoring for gold is easy to work into this system and actually is ideal. This gives the possibility that people will turn drops they don't need into gold which they will then spend on (ideally) real life rewards reinforcing the primary goal of Habit.

Stacking items that are of the same type also makes sense and I think this with vendoring will alleviate a lot of the  complaints surrounding the system.

A trade-up system though on the surface seems like a simple and good idea introduces a lot of complexity and saps users from possibility 2 and 3. A trade-up system decreases monetization, why pay when I am guaranteed to get what I want after 5 days? As a counter to this point this does not apply in instances where the user would never have used the gem system. A trade-up system diminishes the long game potentially reducing how long people will be using Habit. To combat that we can introduce new pets and new systems but new systems introduce new issues and new pets suffer from the same short life span. Because of this the trade-up system has to come at a higher cost to the user. Possibility 2 and 3 are the primary goals and if we introduce a new avenue to get a golden potion it has to be more expensive or 2 and 3 are destroyed.

The positive side of the trade-up system is that it rewards long time users with stuff they want without having to rely on luck or spending money. They've earned it so why don't they get it?

I'm not trying to say no trade-up system but it's a prickly one and I think one to consider after vendoring and stacking is in to see if people are satisfied with that.

**Comment by wc8** [comment]
Just to make sure I'm following this, the "trading" we're talking about is **between users**, not selling back to the marketplace, correct? 

I did not mean to propose that users be able to trade drops back to the market for gems or other potions (except maybe a health potion). I was referring to these two options:

1) sell drops back for gold 
2) pay exchange fee (gem/gems) to trade drops _between users_.

The Trello card for this: https://trello.com/c/gMeHxtja

**Comment by wc8** [comment]
P.S. re exchange fee:
As @Shaners said, drops are free with patience, for a fee (gems) you can speed up the acquisition.
Since trading is a way of speeding up your collection, an exchange fee seems appropriate.

**Comment by wisteriacs** [comment]
Since I don't see an actual poll, wc8 voiced my feelings exactly way back when. ;-)

I don't worry about exchange rates between players because I don't think there's anyone out there with a dozen spare golden potions to trade off and flood the market. I could be wrong and ill-informed.

**Comment by jepler** [comment]
For this proposed trade economy to work, you not only need people with spare gold potions, but you need them to want more white potions.  There doesn't seem to be any reason that would happen unless HabitRPG ends up with "potion farmers" who are also demanding some real-world money on the side. I think you want to avoid setting up a system which will attract this kind of abuse.

**Comment by Shaners** [comment]
Sorry been sick and in / out of a Nyquil coma. If we are talking a player to player trading marketplace that comes with it's own issues.

You can't make a player market gold based. We have to assume that there are players cheating or abusing the gold rewards. They could even be gifting themselves thousands of gold through the restore function so we have to assume there is an infinite amount of gold out there making it valueless in a p2p marketplace. If you tried to make it gold based prices would quickly skyrocket making it so people who made gold legitimately would be excluded from the system and actually encouraged to cheat so they could participate.

You shouldn't make a player market gem based. A large portion of the user-base can't and won't buy gems so a marketplace based in gems excludes a lot of people from a big feature. It's not really their fault they don't have gems so why punish them? It's possible this could encourage people to buy gems but why wouldn't they just buy the pets directly from the Alex at the market then?

A barter based system requires an imbalance in item distribution. As @jepler touched on no one is going to want to receive 20 base potions for their 1 gold potion. First there are only 9 types of pets so even if they had 0 of the base pets after this trade they have an extra 11 base potions and nothing to do with them. This type of trade just won't happen. You might see some base <-> white <-> desert, red <-> shade <-> skeleton, zombie <-> blue <-> pink, movement but I worry if this will be enough to support constant trading or if people will just be using their high value items. You need some players with excess and others with a demand for that excess which I don't think we have yet. Eggs into that mix makes things more interesting but with the recent egg starvation I worry that we don't have enough items or people with excess items. The mount system with its food items and the quest system start to make this a healthier system though.

As for gem-taxation see the above point about a gem based market. The audience for the market will be limited and requiring a gem per trade limits that even more, so much that I worry no trading at all will happen. So we are brought back to the same issue, how do we balance out the loss of long game that a market introduces? Maybe a limit on the amount of trades a player can do per week?

**Comment by wc8** [comment]
To clarify, I meant
1. User can exchange unwanted drops back to **market** (_not_ other players) for gold.
2. Users can trade drops for drops (eg. egg for egg, potions for egg, etc.) between players... 

If we can trade drops between us without needing an exchange fee, that's fine by me.
_Limited number of trades per week_ sounds like a better plan. Once per day? Once per week?

Also, I suggest it not be a lot of gold/silver received in exchange for a potion/egg. It's mainly a way to clear inventory, without making the drops seem worthless.

**Comment by MercuryChaos** [comment]
My preference would be to sell extra drops to Alexander for a little bit of gold, and I think this option should be available regardless of whatever other drop-related features are introduced (crafting, etc.) People can always use gold to buy their own custom rewards, so even if a user isn't interested in the more RPG-like aspects of the site, the drops will still be useful and motivating for them.

**Comment by lemoness** [comment]
Okay, so it seems like we've come to the following conclusions:
1. Selling unwanted drops for a little bit of gold will be relatively easy
   to implement, will clear unwanted inventory, and will reward players,
   including those for whom the pet system is not motivating.
2. Player-to-player trades are probably not viable for the economy of Habit.
3. Player-to-market trades, even with a gem price, are actually quite hard
   to balance and implement.

That being said, why don't we start with just selling drops for gold. As
@shaners pointed out, this may in and of itself solve the problem,
especially if we implement item stacking. If we've done this for a month or
two and people are still really clamoring for trading, we can always reopen
the issue.

Are people in agreement? If nobody has any strident objections, I will open
up a Trello card so that we can get the Eggs-For-Gold feature moving!

**Comment by wc8** [comment]
Maybe just update the existing Trello card? https://trello.com/c/gMeHxtja

**Comment by Shaners** [comment]
I think I might try my hand at developing the stacking thing this week!

Player to player trades might be more viable in the future but involve a significant development piece / security issues / scam issues / economic and gem impact issues to consider.

**Comment by lemoness** [comment]
Okay, I updated the Trello card!

I think this Github can be marked as closed for now, and then reopened if we decide to revisit the trading issue :) If you guys think there is a reason to keep it open, just let me know!

**Comment by oswinrodrigues** [comment]
Revisiting this, many years later, to check if this is any more feasibile now than before? 

Would really like the ability to trade with (or even just gift) another party member (or friend). It would add to the experience of 'being on this adventure together'.

**Comment by CuriousMagpie** [comment]
Hi @oswinrodrigues! We don't currently have any plans to allow gifting or trading of items between users. Thanks for checking in!
