### ISSUE TITLE
Habitica does not load in Opera browser

### ISSUE THREAD

**Issue by tygryziolek** [HabitRPG/habitica#7754]
General Info
- UUID: 46fbe915-b4a2-4525-b9d5-63bf1b4a4ab3
- Browser: 38.0.2220.31
- OS: OS X 10.9.5
### Description

Opera newly installed, all data imported from FireFox I used previously. First run. 
When going to Habitica page, I get to Tips page, but no further. Instead it keeps switching between tips. The dashboard never loads.

I cleared local storage, deleted cookies and closed and opened browser (just in case). No luck, there, nothing changed.
#### Console Errors

_Sorry, need guidance, my computer literacy ends here_

Thanks
tygryziolek

**Comment by sougat818** [comment]
http://help.opera.com/Mac/12.10/en/errorconsole.html This might help with reporting cosole errors.

**Comment by Alys** [comment]
@sougat818 Thanks, that's useful!

@tygryziolek Can you please open the "Errors panel" using those instructions, then reload the Habitica website, and tell us what (if anything) appears in the Errors panel?

You might also like to try using private mode (File > New Private Window) with no extensions or add-ons enabled. That might get Habitica working straight away, and it would be useful to know if it does or not because it could help us narrow down the problem.

**Comment by tygryziolek** [comment]
Guys, I feel a little bit silly right now - I tried to see the error console and all of the sudden the page loaded! It took a while, but loaded just fine, and as far as I checked - works all right.
Sorry for bothering you. I don't know what happened, but I'm glad it did :)
Thank you for your suppport.

**Comment by paglias** [comment]
@tygryziolek don't worry, we're happy that it worked :)
