### ISSUE TITLE
Leaving the guild removes you from the challenges even though it appears you are still participating

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7764]
### General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 37.0.2178.43
Windows 8.1 32-bit
### Description

Leaving the guild removes you from list of participants of the challenges even though it appears you are still participating. I just checked with [this challenge](https://habitica.com/#/options/groups/challenges/0e44b906-86bf-46ef-9733-b99d4fd6404c). States 2 Participants but only @R@chel states is there and can win the challenge. I have rejoin the guild to no affect. I have not received a broken megaphone to remove the tasks.

_Update:_ @R@chel  has left the challenge but I have asked her to rejoin.
### Desired Affect

You don't want to be automatically removed from challenges when leaving the guild. There are some regular challenges I complete but aren't actually apart of the guild as I have no desire to stay in the chat. At the very least  it should warn you if you will be removed from the challenges.

**Comment by Alys** [comment]
I'm strongly in favour of staying in challenges when you leave a guild. It would work much better with many of the ways that challenges and guilds are used (e.g., we often try to put challenges about a certain topic in a guild of the same topic, but for anyone to join not just current guild members).

**Comment by citrusella** [comment]
> It would work much better with many of the ways that challenges and guilds are used (e.g., we often try to put challenges about a certain topic in a guild of the same topic, but for anyone to join not just current guild members).

Would also be helpful if someone purposely or accidentally joins one of the Tavern's [two](https://habitica.com/#/options/groups/guilds/00000000-0000-4000-A000-000000000000) [links](https://habitica.com/#/options/groups/guilds/habitrpg) (each linked word is a different version of the guild) visible in the guilds list--leaving wouldn't kick them from _all_ Tavern challenges.

**Comment by Hus274** [comment]
I can look at this

**Comment by Hus274** [comment]
I removed the code that deletes the user from the challenge when leaving a group which required an update to the delete user because it was using that functionality to remove the user from any challenges they were participating in. After writing this replacement code, I was trying to write a new test for the delete user functionality and it looks like the challenge model leave method only removes the challenge from the user but not the user from the challenge.

I'm going to try and fix this functionality as part of this change since I'm already working around that code and I'm working on that test.

**Comment by Hus274** [comment]
Looks like to determine the members in a challenge is actually just a database scan to find any users with the given challenge id so it should only need to reduce the member count which is much easier.

**Comment by cTheDragons** [comment]
HI, 

Is it ok to close the challenge? _I would like to get my gems back and the guild owner is asking questions_.

As far as I can tell it fairly reproducible. 

Thanks

**Comment by Alys** [comment]
@cTheDragons Ah heck yes, sorry! Any time you want now.

**Comment by habitrpguser** [comment]
I got thrown out of several challenges in the same way (without notice, without being given the option to keep or remove the challenge tasks, and with the challenge tasks staying in my tasks list). But I'm sure I didn't leave the guilds where the challenges were! (Some of them were Tavern challenges, some were guild challenges.) And I didn't notice being thrown out of the challenges at first because [all challenge tags are also buggy at the moment](https://github.com/HabitRPG/habitrpg/issues/7569) and don't revert to green when a challenge is ended or when the participant leaves a challenge or when the participant is thrown out of a challenge by a bug. (Because of this, I'd suggest giving [github issue 7569](https://github.com/HabitRPG/habitrpg/issues/7569) a higher priority - at least then people notice it much more quickly if they get thrown out of challenges.) Because I didn't notice it at first, I can't say when this happened, but it must have been going on for some time. (I noticed the same thing a few weeks ago but wasn't 100% sure and thought I might have accidentally left a challenge, or at least accidentally left a guild, and therefore didn't report it.)

Some of the challenges I got thrown out of have ended by now, some others are still running. I tried rejoining one of the running ones. Instead of getting a new tag (as usual), I have only one challenge tag for this challenge now, and it tags both the first set of challenge tasks (the one that I got before I was thrown out of the challenge, and which has no megaphone symbol now), and the second set of challenge tasks (the one that I got by rejoining, and which has a megaphone symbol). Maybe this is connected to this bug somehow?

One of the challenges I got thrown out of was the August Take This challenge (which is why I haven't received the Take This armor yet). I definitely did participate in this one, and didn't actively leave it at any point. _(Update: @SabreCat gave me the Take This armor by now.)_

I should probably mention that all this happened on the website, and that I've never used any of the apps.

**Comment by khipkin** [comment]
Suggestion: [help welcome now] --> [in progress]

**Comment by TheHollidayInn** [comment]
https://github.com/HabitRPG/habitica/pull/8517

**Comment by Alys** [comment]
I've had two reports that this bug is still happening so I'm reopening this. I'll test it myself later when I get a chance. Note that it might have stopped for a while (I'm pretty sure I tested the fix for it) but then started up again due to some other code change.

**Comment by TheHollidayInn** [comment]
I can't recreate this on develop.

**Comment by Alys** [comment]
I can't replicate in staging. Looks like it's been fixed.

**Comment by SabreCat** [comment]
Got a report of this in the bug guild:

>The Hopeful Mage (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) tier 7 Legendary Socialite 
>this is a thing I was sure was solved: I left the Tavern guild and was thrown out of all Public Challenges I was in...

Has the issue recurred? Or maybe it wasn't addressed with respect to the Tavern "Guild"?

**Comment by shanaqui** [comment]
The Hopeful Mage has added a comment that possibly further explains the recurrence of this issue:

> And I have solved the mistery! it happens also with regular guilds: I joined the Super Socialite challenge, left the Aspiring Socialite guild, now all the tasks are no challenge tasks anymore and I am not part of the challenge anymore. But it happens only if I leave the guild from the iOS app, if I leave the guild from website I keep being part of the challenge! (I didn't remember what I used to leave the Tavern guild, but now I can say that from website it works as it should, on app it has that behaviour)

**Comment by Alys** [comment]
I've created [this issue for the iOS app](https://github.com/HabitRPG/habitica-ios/issues/673). We already have [this issue for the Android app](https://github.com/HabitRPG/habitica-android/issues/906). The bug and fix are the same for both.

It's likely that any third-party tools that implement leaving guilds or parties will have the same bug, and the same fix can be done for them. 

The Android issue has all the details in its comments. A future version of the API might implement this fix by default for all apps and tools, but that's a long way off, so the fix is needed for now. It's already been done for the website in https://github.com/HabitRPG/habitica/pull/8517 so I'm closing this issue.

@shanaqui  and The Hopeful Mage, thanks for the troubleshooting! I'd forgotten that the Android issue needed to be tested for on iOS.
