### ISSUE TITLE
Lost Points and Health Over Night / Random Death

### ISSUE THREAD

**Issue by BrianFinifter** [HabitRPG/habitica#777]
Checked all of my Dailies over the course of the day, along with a number of To Dos. Woke up this morning having lost points and health and my To Dos reset to earlier yesterday (two items checked off yesterday had returned, and I'm assuming other items I had added and checked after those two were also erased).

Using Chrome Version 26.0.1410.43. I was going back and forth between my laptop and desktop, but they weren't syncing very well, so I've stopped doing that.

**Comment by amirdt22** [comment]
Me too.  I was surprised to see that I died today.  I leveled up last night so that should not have happened.  I'm usually careful to make sure I'm not offline when checking off tasks.

**Comment by lefnire** [comment]
I think this is due to rogue deleted tasks hanging around behind the scenes, i'll be tackling this asap. I think there's a dupe ticket somewhere, I'll find later

**Comment by wc8** [comment]
Maybe #700 is the duplicate

**Comment by lefnire** [comment]
I pushed a possible fix. if my theory is correct, some tasks aren't being deleted properly when the trashcan is clicked (likely because it's clicked on a server crash or peak memleak), leaving a rogue / invisible task that's unfairly docking points. This fix restores the task the next morning if it wasn't properly deleted, so that you can click the trash-can to properly delete it this time. I could have deleted rogue tasks (since they should be deleted anyway), but that's really scary business from past data-loss experiences... so this is the unfortunate current stop-gap until I can get that fixed.

So - my theory, everyone on this thread should have some tasks come back tomorrow morning that they deleted forever ago. If that's the case, we know what happened . If that's not the case, then I need to revisit this.

**Comment by rixx** [comment]
@lefnire: I had this issue, too (and died twice because of it). I make sure to refresh to see if my Dailies are really checked.

This might or might not be of help: I use two PCs, my work PC and my laptop at home. (Both running an up-to-date Linux with Firefox.) They never seemed to be completely in sync: Tasks were all right, but Dailies an XP weren't. So when I marked all Dailies as 'done' at work, they weren't ticked off at home. This might, of course, cause sponaneuous death.

(Please let me know if I can help/provide further information. This issue is kind of turning me away, since I died twice already despite of relatively hard work; and restoring points feels too much like cheating to be gratifying.)

**Comment by lemoness** [comment]
Also been happening to me! I think that mine is related to my dailies not staying checked if they are every-other-daylies or weeklies, ie I complete my exercise on Wednesday and check it off, but then it unchecks it and by the time the reset on Sunday rolls around, I get massively docked :/ 

At least for me, I think this is partially related to the fact that my custom day start is 6am, but the every-other-dailies and weeklies are always restarting at midnight, and it just leads to an unchecked, HP-docking mess.

**Comment by lefnire** [comment]
Is there anyone on this thread _not_ using multiple computers?

**Comment by amirdt22** [comment]
I am using multiple computers.  I didn't notice deleted tasks come back.

**Comment by lefnire** [comment]
It seems multiple computers is the common denominator. I'm going to upgrade nginx a la https://github.com/lefnire/habitrpg/issues/769 and try enabling websockets today and tomorrow, I'll see if that doesn't help with this issue. Will get back to y'all in a few days

**Comment by lemoness** [comment]
Ahh, I am using the same computer every time - but I really do think that
mine is linked to the time disparity, so it might need a separate ticket.

**Comment by lefnire** [comment]
@lemoness can you try custom day at 0 for a couple days to see if it changes it, while I work on my other theories in the background?

**Comment by DevonOrxi** [comment]
I randomly died after several days frozen.

And I am using a single computer.

User: Hariel Cid    (b025b30e-373f-4324-96ff-400a4ecd85be)

**Comment by lemoness** [comment]
@lefnire I'll give it a try for the sake of the team. Let's be real, it's
probably better for me to get more sleep anyway.

On Wed, Apr 10, 2013 at 6:37 AM, TheOneAndTrueAcid <notifications@github.com

**Comment by lefnire** [comment]
@TheOneAndTrueAcid good! That means it's working again :) Sorry about the death though, go to User -> Settings -> Danger Zone -> Restore

**Comment by DevonOrxi** [comment]
Thanks a lot! :D

**Comment by lefnire** [comment]
added tokens for all the woes, sorry 'bout that

**Comment by earthbutterfly** [comment]
Hey, that's ok. I'm here (I'm sure you're all over the place with these things)

Basically, I "died" even though I know I shouldn't have and although I have found the restore button I'm not sure what values to put in some of the fields. Obviously level and HP are easy, but I forgot how many tokens I was on and XP/GP etc - is there any way for you to find a cached copy or something and find out these details for me? Was really doing so well... :/

Also, I don't know what to put in for items. I know I had purchased all that were available and only my own personal rewards and the Potion were left, but I don't know how many this was?

**Comment by lefnire** [comment]
@earthbutterfly looks like yesterday you were at:

armor: 5, head: 5, shield: 5, weapon: 6
exp: 312, gp: 1041, hp: 17, lvl: 47

daaayum, someone's good at this game!

**Comment by earthbutterfly** [comment]
Haha yeah - hence the surprise and sadness at having died...
Thanks for that info :)

**Comment by lemoness** [comment]
If I had those stats and randomly died, I would have hurled my laptop out
of the window. Props to you for finding the restore button instead!

**Comment by McBly** [comment]
I've had the same issue here.
Last night I finally gained access to the rewards menu. I reached level 2 completing all my daylies and some ToDos.
Today I woke up with only 20 HP and being Level1 with 130 pts.
And my Dailies are grey.
Reading this thread I've fixed some numbers with the restore option but I've lost the rewards menu and my Daylies are still grey.

I'm using only one computer and browsing with firefox.
Any advise?

thanks

**Comment by mustbetuesday** [comment]
I bought a potion last night so I wouldn't die, but I still died this morning. I think this could be due to a glitch where the page always loads each morning from a previous state, and then reloads again from the correct state. So I died before it had a chance to reload from the most recent state where I had bought a potion.

I'm using only one computer, Chrome 26.0.1410.65, and my time to restart the day is set to 4am. I can't remember if I bought the potion before or after midnight, if that makes a difference. User mustbetuesday (08590e22-8438-4f5b-bd5f-97f95c176773).

**Comment by StanLindsey** [comment]
@mustbetuesday - Thanks for the bug-report! As a by-pass at the moment go to Settings > Danger Zone > Restore - you can set your character back up to where you should of been.

**Comment by mustbetuesday** [comment]
Thanks!

**Comment by braidedmane** [comment]
I'm having the same issue with dailies--I'll mark them off, receive XP/money, but then have health subtracted in the morning and fewer XP/silver. I _think_ it's also happening with my habits, but it's harder to tell since they don't subtract health. I do use multiple computers, but I generally only notice this happening at home--like I'll mark my dailies at home before I go to bed, then check again in the morning and they didn't "stick." Using the beta version and Firefox 20.0.1 if it helps.

**Comment by nexttin** [comment]
I have the same issue as braid, come midnight, I lose HP even though all my dailies were completed.  Some dailies are green, others are yellow at this point.  I did complete two dailies over the weekend even though they were set up as weekday dailies...could that be a culprit?   I also notice that the dailies that I completed and that turned yellow each have a negative score.

**Comment by lefnire** [comment]
Noted. I'm going to be checking this out soon,everyone effected post your
Uuid please (not your api key)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by phantomprince** [comment]
I'm getting the same problem.  I'm using multiple computers and a phone.

**Comment by LilAmy** [comment]
I'm also having this problem. I deleted a lot of habits and to-dos thinking that was the problem but even after doing that and completing my dailies I am losing a profound amount of health or dying overnight.

**Comment by Alys** [comment]
@LilAmy : Are you in a party that is doing a boss quest? If so, you are probably being damaged by the boss due to your party member's incomplete dailies.

Or have you installed a browser extension that tracks your use of the internet and punishes you for too much time on bad websites? Please carefully check your browser extension list. If so, uninstall the extension.

Or do you use HabitRPG on more than one device, possibly with some of the devices set to different times or timezones? Try using HabitRPG on only one device for a few days, with no exceptions.

**Comment by LilAmy** [comment]
Well, I am in a party and we are doing a boss quest but the damage I'm getting from that is significantly lower than what I've been losing. I will try the other two things and see if that helps.

Date: Sun, 21 Sep 2014 18:37:25 -0700
