### ISSUE TITLE
Would like to transfer leadership of a Guild to another member, but their name is not showing up in members list!

### ISSUE THREAD

**Issue by WillowKB** [HabitRPG/habitica#7776]
Hi there,

I'm trying to transfer leadership of the Guild 'Veggie cooking club' ( 30af590a-74d4-4e68-9e72-558a75c6c64d ) to Para spark ( f8bedd9e-b3be-45f4-a458-91b25726e0fa ), but her name is not listed as a member. She has joined and rejoined, just to make sure, but her name is not given as an option when I'm trying to transfer leadership. 

My ID: 0111e48f-f912-40f7-8126-8c066d8002ae

Could you please help us? 

Thanks!

General Info
- UUID: 
- Browser: 
- OS:

**Comment by ghost** [comment]
@WillowKB unfortunately, it's a known issue: https://github.com/HabitRPG/habitrpg/issues/1806

Based on the previous answers, you may be asked to send a message to a moderator in Habitica

> **`Alys`** I need to be certain that it's the current guild leader who's requesting it and that's most easily done if you request it through Habitica itself, where I can confirm your User ID from your profile. Sorry about that! It's just standard practice we follow whenever we change a group's leader.

I'm just another user like you so please take my advice for what it's worth - it only might save you some time. You could copy your message and paste it in the chat found at [Help > Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac)  (that's where most bugs are reported at first now) mentioning @Alys so that the message would be highlighted for her.

**Comment by WillowKB** [comment]
Will do, thanks so much for letting me know :)

**Comment by Alys** [comment]
@GitHubSphinx Perfect, thank you. <3

Closing this as it's been handled in the Bug guild.
