### ISSUE TITLE
Say "Invitation Sent" instead of "Invitations Sent" if only one invitation was sent

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7789]
We should adjust the notification message for invites to say "Invitation Sent" instead of "Invitations Sent" if only one invitation was sent.

**Comment by Alys** [comment]
Any programmer working on this should keep in mind that the non-English translations will handle plurals in different ways. Possibly in some languages the verb will need to be pluralised too, not just the noun. It's probably best to have a separate string for "Invitation Sent", rather than trying to build pluralisation into the existing string with a variable.

I'm advertising this in Aspring Coders.

**Comment by Ozzystrasza** [comment]
Hello, I'd like to give this one a try.

**Comment by Ozzystrasza** [comment]
@Alys @lemoness When you invite a friend by email, you can add multiple emails at once, but when inviting by UserID you can only invite one at a time, is that correct? If so, should the button on the UserID invite say "Send Invitation" instead of "Send Invitations" as well?

**Comment by lemoness** [comment]
Well, we'd actually like you to be able to invite multiple UUIDs, too.
Should I make that a separate GH ticket, or can it be tackled with this one?

**Comment by Ozzystrasza** [comment]
I'm finished with the first issue, so I will give that a try too. In case I'm not successful I will let you know.

**Comment by Ozzystrasza** [comment]
There is a commented line on the code at the part that enables multiple UUID invites: 
`//- @TODO: Refactor src/controllers/groups api.invite to use promises before implimenting this`
If anyone could give some insight about that message, and how I should proceed.

**Comment by crookedneighbor** [comment]
If I recall correctly, v3 of the API supports this. It's just not done on the front end.

**Comment by khipkin** [comment]
Suggestion: [help welcome now] --> [in progress]
