### ISSUE TITLE
Weird that users can get the Veteran pet(s) without the Veteran achievement

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#7803]
In the aftermath of the APIv3 site migration, I (along with anyone else who "weathered" the storm :stuck_out_tongue_winking_eye:) received the Veteran Wolf pet but not the Veteran achievement.

I think that this was intentional, but in my opinion, either one should be renamed or they should be a package deal.  Until I checked just now, I assumed I had the achievement because I had the pet.  I can't possibly be the only user who thought that.

Relevant string from [maintenance.json](https://github.com/HabitRPG/habitrpg/blob/28f2e9c356d7053884107d90d04e28dde75fa81b/common/locales/en/maintenance.json#L9):

> `"veteranPetAward": "At the end, you will receive a Veteran pet!"`

Relevant strings from [generic.json](https://github.com/HabitRPG/habitrpg/blob/2b30c63448272c9d2792577cf67ec1eef6a8dc9a/common/locales/en/generic.json#L82-L83):

> `"veteran": "Veteran"`,
>     `"veteranText": "Has weathered Habit The Grey (our pre Angular website), and has gained many battle-scars from its bugs."`

**Comment by Alys** [comment]
My opinion on this is strong, highly subjective, and biased, so keep that in mind as you read. This is my personal opinion, not me speaking as a mod or admin.

I don't think they should be a package deal.
It also feels odd to rename the Veteran achievement since it's been around for so long, but that would be a better option than giving the pre-Angular achievement to newer players, if you don't want to just leave things as they are now. My vote would be for leaving things as they are. I haven't seen any other questions about this and I've read almost all the posts in the Tavern and Newbies guild since the v3 upgrade. But maybe a name change makes sense.

The Veteran achievement is special. The original website was **SO** buggy - much more so than anything we've seen recently - but we persisted with it because we loved it. In the very early days, it would lose tasks very regularly. I got into the habit of saving the tasks page as an HTML file several times a day so that I could recreate tasks more easily when I lost them. I even wrote a Perl script that parsed the tasks out of it and compared them to the previous saved version so that I could have an automatic list of what had changed. For any other task list application, I would have abandoned it instantly if it showed that many problems but I persisted with Habitica because the concept was awesome. The Veteran achievement really means something.

**Comment by crookedneighbor** [comment]
I completely agree with Alys.

**Comment by khipkin** [comment]
That makes sense! I just think it's weird that they're named the same thing since they don't go together.

**Comment by ghost** [comment]
@Alys You've been quoted in the [👂 Overheard Somewhere in Habitica](https://habitica.com/#/options/groups/guilds/21559f50-7b2d-4191-a13f-ca6e75b732b9) guild. Please let me know if you want me to delete my post quoting you. Well,.. you can surely just delete my post if you don't like it there =)

**Comment by Alys** [comment]
Ha, thanks @GitHubSphinx, that's cool. :)

**Comment by lynxlynxlynx** [comment]
I have no problems with this either. The report can probably be closed, since there seems to be a consensus.
