### ISSUE TITLE
Habitica Naming Day and Habitica Gryphon Mount and Pet

### ISSUE THREAD

**Issue by Jaquel6744** [HabitRPG/habitica#7864]
Excuse me, I would like to say that on 7/31/15 I had accessed the game but did not receive Melior, but this year I got her sister Meliora has somehow I get Melior?  

//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

General Info
- UUID: 
- Browser: 
- OS:

**Comment by Alys** [comment]
@Jaquel6744 could you please post that to the "Report a Bug" guild in Habitica? You can access it from Help > Report a Bug from the habitica.com website's menu, or from Guilds on the mobile app. Because that's in Habitica, it will let us see some details about your account, including your pets and mounts list and the date you joined Habitica, so we can easily check up on what's happened.
