### ISSUE TITLE
Challenge daily won't delete 

### ISSUE THREAD

**Issue by Lyraca** [HabitRPG/habitica#7866]
I have a stuck daily from a challenge from about a year ago that just refuses to be deleted. It is the "throw out three things". I've tried the usual fixes and tips and it still won't go. I get an error on my cell phone when attempting it from there.

User: b517af19-9d58-43c3-9a49-a80575dedec6

**Comment by khipkin** [comment]
Is it a daily from an ongoing challenge that you're still participating in?

**Comment by Lyraca** [comment]
No the challenge is long since gone

**Comment by Alys** [comment]
@Lyraca I've removed that Daily. Sorry about the delay.

We have a guild now for telling us about bugs, which you might find more convenient, and which often helps us because we can see information about your Habitica account immediately (no need for you to specify your User ID, for example). You can access it from the website's menu at Help > [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac).
