### ISSUE TITLE
Checklists on challenge tasks always expand when site syncs

### ISSUE THREAD

**Issue by Ozzystrasza** [HabitRPG/habitica#7875]
General Info
- UUID: 8389891a-ba52-4580-b08b-2cb706c7e0b4
- Browser: Chrome
- OS: Windows 10
### Description

If you add checklists to a challenge task and click on expand/collapse to keep them hidden, they always expand back when the site syncs.

**Comment by JSchneidler** [comment]
Taking a look at this. New to Habitica, can you clarify what you mean by adding checklists to a challenge task? I don't see the option to add a checklist to a task so nothing is expandable for me.

EDIT: I found what you're talking about, but weirdly it does not give me the option to add a checklist to tasks. Possible bug or was it intentionally removed for some reason?

**Comment by Ozzystrasza** [comment]
Are you trying to add checklists to tasks while creating a challenge? If so I don't think that's ever been possible. But what I meant is adding checklists to tasks from a challenge you joined, so the tasks are on my task list, and I can add checklists by editing them. Sorry if I didn't explain so clearly.

**Comment by JSchneidler** [comment]
When editing or creating. Is that intentional that you cannot add checklists to tasks to a challenge for everyone? Only individual users can add a checklist to a task at the moment. But I see what you mean, when running sync, the checklists become expanded. But no worries, I'm new to Habitica so some of these features I only discover through the issues so I seem confused because I am :p I'll take a look and see what I can do, even if it's just finding a cause.

**Comment by Alys** [comment]
Yes: "When editing or creating. Is that intentional that you cannot add
checklists to tasks in a challenge,"

Only participants can add checklists.

**Comment by Hus274** [comment]
@JSchneidler are you still looking into this?
