### ISSUE TITLE
Exp and mana are out of range.

### ISSUE THREAD

**Issue by dgodovanets** [HabitRPG/habitica#7876]
General Info
- UUID: `6b4563cf-ef71-4508-839e-f553d358dab9`
- Browser: Google Chrome, Version 53.0.2785.8 dev-m
- OS: Windows 7

That happens, when I earn exp and mana for completing quest without completing any task. Problem can be fixed by completing any task, anyway that's bug.
![image](https://cloud.githubusercontent.com/assets/16069332/17457566/441a5888-5c04-11e6-83a8-44213346a302.png)

**Comment by ghost** [comment]
@Eramik while waiting for the mods to comment here, you may want to see the issue #2433 _Failed to Level Up..._ regarding the experience bar. As for the mana exceeding the max value there's been some discussion in https://github.com/HabitRPG/habitrpg/issues/2082#issuecomment-55074039 and https://github.com/HabitRPG/habitrpg/pull/3662

**Comment by Alys** [comment]
@GitHubSphinx Thanks for the links!

@Eramik It's deliberate that your mana can be more than max for a short time because it allows you to use the mana that you've earned.

We have a guild now for telling us about bugs, which you might find more convenient, and which often helps us because we can see information about your Habitica account immediately. You can access it from the website's menu at Help > [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac). It's recommended that bugs be posted there first and if a GitHub issue is needed, we'll let you know.

**Comment by dgodovanets** [comment]
Is it normal? 
![image](https://cloud.githubusercontent.com/assets/16069332/19022353/1aab23da-88df-11e6-8725-9f0a51aef067.png)

**Comment by Alys** [comment]
Yes, that's normal. For the experience, see the first link in GitHubSphinx's reply to you above. For the mana, see GitHubSphinx's other links and my previous answer.
