### ISSUE TITLE
Task Note Tooltips with Links Need Hover Improvements

### ISSUE THREAD

**Issue by ESWAT** [HabitRPG/habitica#7886]
- UUID: ffee6b77-0bf8-422a-a65c-c20de17f2b32
- Browser: Chrome 52.0.2743.116
- OS: OS X & Windows 10
### Description

It normally makes sense for task note tooltips to go away once you’ve stopped hovering over the task. But I have a particular case where I use the note to store the URL. It’s handy that it becomes a link in the tooltip, but not-so-handy that I can’t click on the damn thing…

![ezgif-1339943820](https://cloud.githubusercontent.com/assets/65468/17535176/0a3ddc26-5e5b-11e6-9ffe-1259ccfa525a.gif)

Guess this walls in-between a bug and a feature request. ;)

**Comment by Alys** [comment]
You can click on the Note icon to freeze the note's bubble in place.

We have a guild now for telling us about bugs, which you might find more convenient, and which often helps us because we can see information about your Habitica account immediately (although that's not relevant for this particular question of course, but often is useful for other reports). You can access it from the website's menu at Help > [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac). It's recommended that bugs be posted there first and if a GitHub issue is needed, we'll let you know.

**Comment by Asing1001** [comment]
Not instinct that should click icon to freeze the tooltip, would have better UX to freeze when mouse over the tooltip.
