### ISSUE TITLE
thunderstorm potion problem

### ISSUE THREAD

**Issue by adribe82** [HabitRPG/habitica#7892]
General Info
- UUID: 30c37c4b-3558-40dc-80fd-e60a898fd248
- Browser: Chrome 
- OS: IOS 9.3
### Description

Hello! So this morning I bought around 7 thunderstorm potions and used them on 7 eggs I have. However, none of the pets have appeared on my mount list, which appears as if I hadn't used any potions at all.

**Comment by crookedneighbor** [comment]
They will be in the pets list in the stable, not the mounts list.

**Comment by adribe82** [comment]
Yeah, when I said "pets" I meant mounts. I still see paw prints when the actual mounts are supposed to be, as if I hadn't used any of the magic potions. I'm attaching a screenshot for reference. 
[Habitica_magic mount.pdf](https://github.com/HabitRPG/habitrpg/files/415202/Habitica_magic.mount.pdf)

**Comment by Alys** [comment]
As @crookedneighbor says, your hatched eggs created pets which will be in the Pets page; the screenshot you took is the Mounts page. Our logs show that you bought six of the hatching potions and your account contains six Thunderstorm pets.

We have a guild now for telling us about bugs, which you might find more convenient, and which often helps us because we can see information about your Habitica account immediately. You can access it from the website's menu at Help > [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac). It's recommended that bugs be posted there first and if a GitHub issue is needed, we'll let you know.

If you have questions about pets and mounts, our wiki has a lot of information at http://habitica.wikia.com/wiki/Pets and http://habitica.wikia.com/wiki/Mounts and you can ask questions at Help > Ask a Question from the website or Guilds > The Newbies guild on the mobile app.
