### ISSUE TITLE
Alternate input methods suggestion

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#790]
Personally, I don't like having to use the mouse if I don't have to.  I was wondering if we could get some keyboard shortcuts for habit so that I can arrow around and check off items from the keyboard.  If that is possible, mapping the keyboard inputs to a usb gamepad would be trivial and (in my opinion) quite amazing.

**Comment by wizonesolutions** [comment]
A workaround for this at the moment is to use a Vim-like plugin for your browser.

Vimperator or Pentadactyl for Firefox.

Vimium for Chrome.

There's something for Safari too that isn't really maintained, but I think it still worked last time I tried.

But yeah, native keyboard shortcuts would be cool!

**Comment by crookedneighbor** [comment]
I would love some keyboard shortcuts too. Maybe similar to [Trello's shortcuts](https://trello.com/shortcuts)?

**Comment by Satvik** [comment]
Vimium no longer works for dailies on HabitRPG, because the checkbox can't be selected

**Comment by Alys** [comment]
Vimium now works for ticking off Dailies and To-Dos. https://github.com/HabitRPG/habitrpg/commit/f749d1a

I'm going to close this because the Vimium plugin works very well, better than anything we could create without hours of work, and if we did create our own system, it would conflict with Vimium or similar extensions. I believe that for this kind of feature, using a well-crafted, dedicated third-party tool is the best option.

If you disagree, on the HabitRPG website please go to Help -> Request a Feature to ask that we create our own keyboard shortcut system.

**Comment by crookedneighbor** [comment]
You can also now tab to your desired task to check them off. So you can be mouse free on the tasks page even without vimium. (Thanks to @TheHollidayInn for work on this)

**Comment by Satvik** [comment]
Really awesome. Thanks so much!
