### ISSUE TITLE
Change Drop Calculation To Not Rely on Seeded Stats from User

### ISSUE THREAD

**Issue by dancerinsox** [HabitRPG/habitica#7929]
General Info
- UUID: c1d236c4-cc77-443a-9830-265af88bd7fb
- Browser: Chome
- OS: Windows 7
### Description

I have a grey wishing well task, and I was using it. I got a lion cub egg about 16 times in a row (I overused since I was curious about the behavior :P). I then paused, and tried a different task. I then got recurring shade potions...without a pause, I went to the first task I was using. Still shade potions...didn't seem to be any sync errors, and I wasn't fixing my gold value in between clicks to keep it the same (which Alys tells me would give me the same drop).

**Comment by crookedneighbor** [comment]
This is actually expected behavior right now with the way the random values are generated. That said, we no longer need to seed the random value because all drop logic is now done on the server. I'm going to change the title of this issue to reflect the work that actually needs to be done. Namely, to select the drop without relying on a seed.

Original title: _Same drop ~20 times in row on a wishing well daily_

**Comment by gambtho** [comment]
@crookedneighbor not entirely sure my PR is what you intended --- please validate 🔢

**Comment by khipkin** [comment]
Suggestion: [help welcome now] --> [in progress]
