### ISSUE TITLE
do not remove Battle Gear equipment when changing class

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7958]
When a player changes class, their Battle Gear equipment should NOT be removed (nor their Costume gear of course). 

They should also NOT be directed to the Equipment page, and should NOT see the "Class Gear" popup:
![image](https://cloud.githubusercontent.com/assets/1495809/18145203/034a3614-6f7f-11e6-9129-ab608eb25226.png)
(We might want to put an explanation somewhere  about the class bonus, but that's probably something for the upcoming website improvement project, which will introduce more help tips on the site.)

Staff/mods/admins have talked about this somewhere else and I thought it was on GitHub but I can't find it.

The reason is that unless you're a fairly new user, you are likely to be wearing Legendary equipment, or customised gear from other classes and having it change is annoying. For new-ish users, they'll likely need to buy new gear anyway, and can change their equipment as they do that.

**Comment by cmajames** [comment]
@Alys I'm willing to tackle this issue.

**Comment by Alys** [comment]
@cmajames Thank you! Comment here if you have questions or run into problems.

**Comment by cmajames** [comment]
@Alys sorry for not getting back sooner! I've got a draft solution for the first half of the issue, ie I've managed to stop the server from unequipping all of the user's items during class change. For the second half, I've identified the offending code, but when I go to write a solution (that involves User.set in order to create a flag) I'm getting an HTTP 401. Could you take a look at the following Gist and give me your impressions? https://gist.github.com/cmajames/85a5bcc0d9b9c9391ed4ac5361ae3658

**Comment by crookedneighbor** [comment]
Only certain paths are allowed to be edited via the update user API route. This prevents someone from just updating their class/balance/etc to whatever they want. https://github.com/HabitRPG/habitrpg/blob/589b2aaf3a299dae4727e5b1e94479f579feb8a3/website/server/controllers/api-v3/user.js#L163-L167

Is there a reason you need to set a flag?

**Comment by cmajames** [comment]
@Alys sorry for not getting back sooner. I've solved the first half of this issue, ie I've made it so that armor, etc is no longer unequipped after changing classes. However, I'm running into complications with the second half, namely, the server is responding with the following:
{"success":false,"error":"NotAuthorized","message":"path `flags.shownClassChangeEquipment` was not saved, as it's a protected path."}
I did make sure to update website/server/controllers/api-v3/user.js#updatablePaths to include 'flags.shownClassChangeEquipment'

**Comment by cmajames** [comment]
@crookedneighbor I'm setting the flag so that the message only shows up the first time a user changes class.  Although, if I'm misunderstanding what @Alys is asking the point is mute.

**Comment by Alys** [comment]
The message should never show up at all. :) Class changes should not remove equipment so the message won't be necessary any more.

**Comment by cmajames** [comment]
@Alys when a player chooses their class I assume they should still be awarded the basic weapon for that class. However, for _really_ new players, ie players who've reached level 10 for the first time, do we still want to equip the basic weapon automagically?

**Comment by Alys** [comment]
They should still be awarded the basic weapon, but it shouldn't be equipped automatically because they're likely to already be using a better one.

Also, not equipping it will help them to realise that their existing gear can still be used and they haven't wasted their gold buying it (a common question).
