### ISSUE TITLE
Scrollable Party Menu

### ISSUE THREAD

**Issue by Overflow0xFFFF** [HabitRPG/habitica#798]
Small backstory:

I began actively using your wonderful creation a few weeks ago. About two days ago, one of my friends complained about the difficulty in forming new habits, so I suggested HabitRPG to him. Due to his competitive nature, we thought it would be best to create a party together to track one another's status. Soon, HabitRPG began to spread like wildfire amongst my friends, and we all joined up in the same party. 

Our party is now 9 members in total, and it breaks the UI just a little bit. I suggest a simple scrollbar to horizontally scroll through the entire party when it gets very big in size. In its current state, when your party is at least eight members in size (not including yourself), it obstructs the menu in the top right corner of the page. This can be a problem when trying to add additional members to an already dungeon-raid size party.

**Comment by lefnire** [comment]
We'll add that. I'm marking as minor only because I originally intended to limit the party sizes to 5 - there are some subscription performance issues with large parties, as well as interface problems (which you're experiencing). Having a very large party is sort of living on the edge until I can get some other things squared away, so I'll revisit this when I can. Also tagging @zakkain as we were chatting about party-bar scrolling a while back

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
