### ISSUE TITLE
reversal of level-up from level 1 to level 2 after doing website tutorial

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8014]
From the Report a Bug guild by afino (e6350942-4808-4b1b-8abe-99d646f608d9) six hours ago:

"Hi! Just created a new account, went through tutorial, advanced to level 2 and added a new to-do. Then added a new tag and saved it. Finally edited my to-do and assigned the new tag - unfortunately, that didn't work! Instead it said something about a needed valid id + i got 150 experience points + i went back to level one with "151 of 150" experience points."

From The Tig (366367d9-5e71-4359-83f8-8766452c6f15) in that guild at 2016-09-10 01:46:05 UTC:

"I just started an account, and got to level 2 via tutorial stuff. I just changed my "day start" from default midnight to 5 AM, and immediately it told me "experience +150", but now I'm level 1 with 151/150 experience."

These might be just from the level-up happening in the user's browser and not getting saved to the server, but those reports are odd enough that I wanted to capture them in case we get others.

**Comment by citrusella** [comment]
I think someone reported this in the Tavern today.

Nikowski (c73d76b1-e209-4fe2-81f8-beaeadeca819) posted at 17:12:33 and 17:13:12 UTC (I think; I'm converting because the timestamps appear to be in my own timezone and I'm UTC -4):

"Okey, i just join to game and i broke it. It shows me i have 151/150 experience after i end tutorial."  
"And the game was showing me, i have level two, but after reload i have again level 1."

They didn't mention a "+150 experience" notification, but I thought it sounded similar enough to bring up here!

**Comment by Alys** [comment]
@citrusella yes, thank you! That probably is the same bug, and it's good to hear about another example of it.

**Comment by Alys** [comment]
A new example (BTW, we see this bug often, but this example has interesting details):

marharet (297f6e4f-be87-4c57-9d0c-3e16813deed8) :
I just found strange behaviour of application. I already have tried reopening app and opening in incognito mode. So I just lvled up to 2nd lvl and received new mission. I saw that my lvl number has been incremented and progress bar has been properly refreshed. Then I decided to check this new mission. After clicking 'Invite your guild to join mission' few things heppened. Firstly I received information that I can't do this because my guild is already on a mission. Second message said that i received '+150 experience'. Not sure why and if it has been really added or just message is incorrect. Now when I'm checking my lvl counter says that I'm on 1st lvl and my experience progress is on 177/150 points. Refreshing / reseting doesn't fix it. That's all information that I have abut this bug. Hope it will be enough to fix it.

**Comment by joedragons** [comment]
In case it helps, I noticed this a week or two ago when creating a new account.  I was able to "correct" my level by +ing a habit so I assumed it was minor.
Maybe this bug was on my brain but today my party finished a quest (containing xp rewards) enough to put me over to the next level.  I didn't notice (but had noticed earlier I was close), and then clicked -(minus) on one of my habits and noticed I leveled.  This seemed similar to this, enough to remind me to hunt for the original bug which is this one.  I wonder if certain rewards push you over xp to level but don't level you until you do another action (even a neutral, such as join a guild mission above or a negative one).
This may be slightly different for the tutorial simply because it has that huge popout that says you're level 2 and maybe the tutorial code is slightly different but the same underlying issue?  Or anyway, seems another similar issue lurking if not the same.

**Comment by citrusella** [comment]
That's https://github.com/HabitRPG/habitica/issues/2433, actually, slightly different than this but also kind of the same? The tutorial, *most* times AFAIK, properly levels you up but sometimes (more often recently) "reverts" it? Quests (and the Enchanted Armoire) don't check to see if you've met the XP required to level up, and syncing also usually doesn't (I don't think), but all tasks check for level-up conditions when you click them (even custom rewards (all prices including 0) and negative habits, even though neither of those add to your XP), which is why clicking off a task is a workaround sort of solution for leveling up.

I don't know the super technical code side of it but I'm pretty sure that's an accurate summation of the basic process? TL;DR: When XP is more than max then something hasn't checked to see if you should level up. Tasks always check and will level you up when you click them.

**Comment by joedragons** [comment]
@citrusella Thanks.  I admit I was lazy and stopped hunting after I found this one=)  I subscribed over there.

**Comment by TheHollidayInn** [comment]
I believe this is the same issue: 
```
f.s.zoppo
I've lost a level and i can't figure it out why... I was level 14, and i did the tutorial and i did the tutorial of the game(i hasn't done it before) so i got level 15. Then i opened up a Chest(100 Gold) and i lost 9 hp e got a hood, when i looked at my level i was 14 again... 
```

**Comment by Alys** [comment]
I'm closing this because it's no longer relevant for the new website.
