### ISSUE TITLE
Multiple Damage During Quest?

### ISSUE THREAD

**Issue by jtgithub2016** [HabitRPG/habitica#8017]
General Info
- UUID: 
- Browser: 
- OS: 
### Description

My party is on the Rat King quest, and it looks to me like we took too much damage and now most of us are dead.  I understand that being dead isn't a bug, but I think we got dead in a potentially unfair way?  I don't even really know - can someone look into this and see if it was okay?  If it's okay then I guess this isn't a bug.

![image](https://cloud.githubusercontent.com/assets/18677807/18542730/e6df58e2-7b5e-11e6-8ee5-16e2adf6e1d2.png)

**Comment by Alys** [comment]
Players can easily do 15 to 30 damage (or more) if they leave several of their Dailies undone. You might like to ask the players who did that much damage to try to do more of their Dailies each day. If any of them say that they did complete all their Dailies but still caused damage, please ask them to report what happened in the Report a Bug guild (from Help > Report a Bug in the website's menu or from Guilds on the app).

The only thing that looks unusual there is Shioki's damage reports because there's two at once, although that can happen under some conditions without a bug happening. I want to investigate but I need to be able to find the party so can you please provide your User ID (UUID)? UUID is found in Settings -> API.

**Comment by jtgithub2016** [comment]
No problem.  I'm one of the people doing damage to the party. . . My UUID
is
e44e6069-2e30-49cf-ab49-db41d3134045

Our party ID is: 90d10895-0658-4893-bb3e-ccf7480c200c

Thanks again.

John

**Comment by Alys** [comment]
Yesterday, you left several Dailies incomplete, so 27 damage from you isn't impossible. Did it look to as if you had completed all your Dailies? It is possible for them to appear to be marked completed but without that information being sent to Habitica's server for permanent storage. At the end of each day, click the sync button on the website or mobile app (that's the button containing a circle made of two curved arrows) and then check your Dailies to make sure they are still completed.

For admins who are interested in this, the data for the two attacks from Shioki (4a6e7272-a4c6-46b8-b43b-1e91474f5973) is:

```
        {
            "id": "1041c34a-5d59-4b29-abc6-4379b891706f",
            "text": "`Shioki attacks Rat King for 0.0 damage.` `Rat King attacks party for 24.0 damage.`",
            "timestamp": 1473829790905, //      UTC: 2016-09-14 05:09:50        player's zone (offset -480): 2016-09-14 13:09:50
            "flagCount": 0
        },
        {
            "id": "e6e27231-2bea-431d-8236-61635c4fd116",
            "text": "`Shioki attacks Rat King for 19.6 damage.` `Rat King attacks party for 0.0 damage.`",
            "timestamp": 1473824413727, //      UTC: 2016-09-14 03:40:13        player's zone (offset -480): 2016-09-14 11:40:13
            "flagCount": 0
        },
```

Shioki's Custom Day Start time is 12:00. One of those two attacks happened just before that time, and one just after, so the large amount of damage for the second attack is expected - Shioki had not had time to do any of their Dailies. If Shioki often finds that they're using Habitica both before and after midday, they might want to consider changing their Custom Day Start time to earlier in the day.

@jtgithub2016 I can't see any bugs here, but if you have questions about any of this, or if anything I've written doesn't match what you see, comment again here.

**Comment by jtgithub2016** [comment]
I thought I had checked more dailies than that - I knew I was going to do
damage, but 27 kind of took me by surprise.  I thought it was just 3-4
unchecked: record your mood, read story, enter time, and maybe the 547-15
one.

So how does Shioki's custom day work?  I thought she only got to attack or
be attacked once a day.  So she launches an attack when her day ends and we
get attacked when her day ends (and she's ideally done all her dailies).
If the Rat King gets to attack her right after her custom day starts and
before she has a chance to do anything, how is that fair?  Why wouldn't it
attack me one minute after midnight?

**Comment by jtgithub2016** [comment]
I understand ignorance is no defense, but Shioki's told me (in the past,
shortly after she joined the party) that she put her custom day at noon to
make sure she has time to do her dailies. She also doesn't have a pattern
of bringing death upon us all.  I just assumed you got your day to end once
every 24 hours - mine at midnight and hers at noon, and that you attack and
are attacked just before or just as your day ends, whether at noon or
midnight.

**Comment by Alys** [comment]
I count 11 of your Dailies that weren't completed yesterday. I can put a list of them here if you wish (if the texts aren't something you want to keep private).

>  I thought she only got to attack or be attacked once a day.  

Shioki does attack just once a day (as does any player). However her day starts at midday because that's when her Custom Day Start time is. This means that if she uses Habitica before midday, it's still "yesterday" in Habitica-time. 

> So she launches an attack when her day ends and we get attacked when her day ends

No, that's not exactly what happens. Any player (including Shioki) launches an attack when her next day **starts**. If she's done all her Dailies on the previous day, then she won't cause any damage to the party.

> If the Rat King gets to attack her right after her custom day starts and before she has a chance to do anything, how is that fair?

That's how it works for everyone. The boss attacks at the moment that you first use Habitica every day. It's motivation to complete as many of your Dailies as you can on the previous day.

>  Why wouldn't it attack me one minute after midnight?

Normally it would if the Custom Day Start time had be left at the default setting of midnight and if the player used Habitica one minute after midnight.

What happen specifically  in this case is that she didn't use Habitica at all on 2016-09-14 until 11:40am. Because that was the first time she'd used Habitica that day, her cron ran then, causing the first quest progress message that you see. Her Dailies then became unticked, which is what is supposed to happen at the first time you use Habitica on any day.

She then kept using Habitica until after midday. Because she had set her Custom Day Start time to midday, Habitica treated her first action after midday as happening on a new day - that's the purpose of the Custom Day Start time. Because it was now a new day (with respect to the Custom Day Start time), her cron ran again, causing another quest progress message, which is also what is supposed to happen. The trouble then was that she hadn't marked all her Dailies as complete, so she did a lot of damage.

**Comment by jtgithub2016** [comment]
Ok, that makes sense.  Thanks.

**Comment by Alys** [comment]
If you would like more information about how it works, the wiki's [Custom Day Start](http://habitica.wikia.com/wiki/Custom_Day_Start) page might help.

On the website, you can use Settings > Site > [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to restore lost health (and gold and levels, if needed) if you feel that the damage was unfair.

**Comment by jtgithub2016** [comment]
Ok, thanks much.
