### ISSUE TITLE
Due date calendar and text display for Todos don't agree

### ISSUE THREAD

**Issue by ianjohnsa** [HabitRPG/habitica#805]
When I select a due date using the pop up calendar for a todo task, the actual text date that is inputted into the due date field is one day later than the calendar date I select. So, for example, if I choose my task to be due on 4/12 by clicking on that date with the pop up calendar, the date that is automatically filled into the due date field is 4/13. This is confusing because I don't know whether it is actually recording it incorrectly or just displaying the wrong date. But, either way it looks like its a bug.

**Comment by lefnire** [comment]
See https://github.com/lefnire/habitrpg/blob/master/src/app/browser.coffee#L200 - I actually _deliberately_ set the date a day ahead, because from all my testing it was setting it a day behind. Either there's some client-side inconsistency going on, or datepicker may have fixed the original issue rending the current solution a bug. I'll explore soon. Marking as critical only because it'll be really fast once I can jump in

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
