### ISSUE TITLE
Disallow purchasing Magic and Wacky Hatching Potions beyond usable number or allow selling for Gems

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8056]
### Description

It's only ever possible to use a maximum of 18 of a given Magic Hatching Potion. (Hatch the nine pets, raise them to mounts, and hatch the nine pets again.) However, there are no guard rails preventing a user from buying more than this amount, leaving the unfavorable 2-Gold sell price as the only way to get anything for the 2 Gems spent on each excess potion. We could implement a check during the purchase process of Magic Hatching Potions to error out if the user would buy an unusable potion. (Add up current potions + pets + mounts of that type. If it's already 18, stop.) We could additionally fade out the potion in the Market and change its tooltip to say you've purchased the maximum number.
#### Console Errors

N/A

**Comment by colingm** [comment]
Is it alright if I start working on this one?

**Comment by SabreCat** [comment]
@colingm: Sure! In some offline conversation, it's been pointed out that some folks like to keep a potion around as a collectible in addition to the pets, so a hard stop at 18 may not be the best way to solve this. One suggestion I liked was to change the sale value of Magic Hatching Potions from 2 Gold to 2 Gems (basically, you can get them refunded at will)--that may be a more involved fix, though.

**Comment by crookedneighbor** [comment]
I personally don't think this is ready to be worked on. Too much that needs to be discussed and decided on.

**Comment by colingm** [comment]
Okay it does sound like there is still some discussions that need to be resolved before this gets changed so I don't have to work on it. I can see why some people might want to have more than the limit so it is probably a good idea to decide on how that is handled before anything gets implemented.

**Comment by Joseph67843** [comment]
Changing the sell price from 2 GP to 2 gems would solve both problems (allowing excess purchases to be reversed and allowing collectors to buy extra), but I have no idea how much work that would be. Alternatively, the system could warn users and ask them to confirm when they are buying more hatching potions than they can use.

**Comment by Alys** [comment]
If we want to go with the idea of allowing gem-purchasable potions to be sold for gems, we could add a "sellType" field to the various potion types in `website/common/script/content/hatching-potions.js`
`premium` and `wacky` potions would have it set to `gems`, RoyalPurple potions would have it set to `none` (we do not want people to ever sell them since they can't get them back except by asking for admin help), and all other potions would be `gold`.

**Comment by veeeeeee** [comment]
We've determined that disallowing purchases beyond usable number is not a behavior we want to implement, nor do we want to allow selling for Gems at this time. However, there is a chance that lingering issues with purchasing Magic and Wacky Hatching Potions and eggs might be due to lack of warning implementation on the mobile apps. We will open a new issue to account for that.
