### ISSUE TITLE
Provide Completion Status in Habit History Export

### ISSUE THREAD

**Issue by markwk** [HabitRPG/habitica#8069]
In the habit history export in CSV, I'd like to add a column for completion status. Currently we merely show the Task Name, Task ID, Task Type, Date, and Value. But we don't record or display whether that task was checked off or not. This completion status appears nicely in the User Data Display tool as a checkbox in the table (See: https://github.com/Alys/tools-for-habitrpg/blob/master/habitrpg_user_data_display.html). 

I'd like to look at the data between habitica tasks and other areas that I track in order to explore various coorelations. In order to do this mashup, I need some kind of machine readable data. 

I'm new dev on Habitica and more of a life hacker than a solid coder but what I propose is extending the export code in habitrpg/website/server/controllers/top-level/dataexport.js (see: https://github.com/HabitRPG/habitrpg/blob/5fa76f6aebb9c2f10b68d27fcfebee5b4f05a8ff/website/server/controllers/top-level/dataexport.js). In this code, we can follow what's going in the extrapolation of the user data display tool to diplay a column as "completion status" and show either Completed, Fail, Pass (or something like this). 

That's just an initial braindump of an idea. It seems like this would provide more useful data than what is currently in the export for habit history. 

Love to hear thoughts from the dev team and any contributors.

**Comment by Alys** [comment]
Normally we ask that feature requests are placed in Trello, which you can access through Help > Request a Feature from the habitica.com menu. However since you're a dev, I'm guessing you want to work on this feature yourself, so I think it can stay here while it's discussed, but please be aware that if it turns out to not be possible for it to be implemented in the short term, we might close this and have it moved to Trello.

For the exported CSV file, "completion" status doesn't exist for Habits, but I'm guessing you're referring to whether + or - has been clicked. For Habits and Dailies, completion status or +/- can be extrapolated from whether the value has gone up, down, or remained the same since the previous entry, so I'm not sure how much use it would be. Countering that though, certain skills can modify the value, so if we wanted to give an unambiguous indication of how the task had been changed, perhaps a column for "up"/"down"/"completed" would be useful.

If this feature is not implemented, you can obtain unambiguous completion statuses by never casting those skills on tasks you want to track.

**Comment by markwk** [comment]
Yup, I'm a dev, though this would be a bit outside of type of stuff I normally do. I might be able to sort some parts of it out. 

For now on the question of implementation we'd need to consider the idea of storing the actual event users last took on a daily or habit. I know we can extrapolate completion status but seems a bit odd to not have this stored somewhere, especially if you want to obsess on the tracking part like I'm thinking about. 

Is this within reason?

**Comment by paglias** [comment]
I agree about storing completion date for dailies, not sure about habits honestly

**Comment by Alys** [comment]
@markwk We'll leave https://github.com/HabitRPG/habitrpg/issues/8070 open for a while in case you do want to work on adding completion date-time stamps to Dailies.

I'm going to close this one though since it's not really critical for Habits. The date-time stamp of each click is already stored in their history, and whether it was a plus or minus click can be easily worked out by whether the value went up or down. To avoid any uncertainty about that, you can avoid casting skills that affect the task value (I can advise you which skills if you're not sure). It would be slightly easier to have an exact statement of whether it was + or -, but that would increase storage requirements for the Habit history entries, and I'm not sure the convenience is worth it.

However you're welcome to request this on Trello if you wish (Help > Request a Feature from the Habitica website), and you could include a link to this issue. We'd then be able to consider it again during any future projects to enhance tasks.
