### ISSUE TITLE
Checklist Reordering Bug

### ISSUE THREAD

**Issue by Prutonium** [HabitRPG/habitica#8075]
General Info
- UUID: 7980b927-aabf-4d68-8af1-ae3016e407a5
- Browser: Google Chrome Version 53.0.2785.116 m (up to date as of 9/26/16)
- OS: Window 10 64-bit
### Description

To-Dos Checklist is randomizing after moving a few checklist items (This particular checklist has 15 items.). The Task Adjuster Tool does not say I have the reorder bug. I've been making them weekly for school, and this is the first time I've had an issue (so it's possible it wasn't around even a week ago.).

**Comment by paglias** [comment]
@Prutonium sorry for the delay, do you see any error message when you try to re-order items? Also can you try closing your browser cache and logging out?

If it keep happening, can you open the browser console (Ctrl+Shift+J) and copy any error that appears there?

**Comment by Prutonium** [comment]
@paglias Will do! I've currently got the list in the perfect order, but after my exam Thursday morning I'll make some attempts to replicate the bug on a new list (after closing my browser cache and logging out of course :) ). I'll post here whether or not I can replicate it, and if so I'll copy any errors I find!

**Comment by jepperson2** [comment]
I have had this issue as well on iOS. Here are the details of the situation in which it happened:
- iOS 9.3.5 (and now again with iOS 10.0.2)
- iPhone 5c 
- Habitica Version 1.5.2 (152)

When moving an item in my Dailies from the top to the bottom (by long press and then dragging), it displaces the bottommost item to (in my case) 3 spots higher than it should be. For example, suppose I have items ABCDEFGHIJK, where A is on top and K is on bottom. I tried moving A to the bottom, which should produce BCDEFGHIJKA, but actually produced BCDEFGKHIJA. 

I just tried this again and it gives buggy behaviour, improperly displaying the daily description and repeating one of the tasks twice. Upon "refreshing" the screen by pulling down to get list to refresh, the display error disappeared and item K was restored to it's proper spot. 

Additionally, it does not allow me to drag upwards and have the list scroll so that I can place item A back on top of the list without doing multiple long presses. Dragging it downward allows the screen to scroll and me to get to the bottom of the list. Perhaps this is part of the issue? Not sure. 

Hope this is helpful! 

Edit: Err...sorry! I didn't realize this was specific to the web version of habitica. I'll see my way over to the iOS page now...

**Comment by Alys** [comment]
@jepperson2 It sounds like you're talking about problems with sorting Dailies (i.e., the entire task), not checklist items. If so, please go to Help > Report a Bug from the website's menu or Guilds > Report a Bug in the mobile app. It's likely that at least some of the problems you're having are not specific to the iOS app so I will help you in the Report a Bug guild first. In general, for any bug, that's a good place to start, and we can advise you if you need to report elsewhere after that.

**Comment by Prutonium** [comment]
@paglias @Alys 

Alright So I Logged out, cleared my cached files and cookies, restarted chrome and logged back in and was able to replicate the bug. (Sorry for the delay, this week was crazy!)

Here's what was in the browser console: 

app-480b2bc5.js:35 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at s.zone (https://habitica.com/app-480b2bc5.js:35:7232)
    at Object.authenticate (https://habitica.com/app-480b2bc5.js:47:15070)
    at Object.<anonymous> (https://habitica.com/app-480b2bc5.js:47:16291)
    at Object.i [as invoke](https://habitica.com/app-480b2bc5.js:7:17125)
    at Object.c [as $get](https://habitica.com/app-480b2bc5.js:7:15521)
    at Object.i [as invoke](https://habitica.com/app-480b2bc5.js:7:17125)
    at https://habitica.com/app-480b2bc5.js:7:15171
    at g (https://habitica.com/app-480b2bc5.js:7:16758)
    at Object.i [as invoke](https://habitica.com/app-480b2bc5.js:7:17092)
    at D.instance (https://habitica.com/app-480b2bc5.js:8:8733)
app-480b2bc5.js:47 Connecting to Pusher.

**Comment by spdale** [comment]
Hey guys, I added an issue to the iOS repo: https://github.com/HabitRPG/habitrpg-ios/issues/410
Go ahead and correct me over there is you are experiencing a similar issue on iOS.

Cheers!

**Comment by toddmedema** [comment]
Can confirm, seeing this bug on Chrome 56 on Mac. Driving me crazy. All the other parts of Habitica are nice to haves, if the TODO list is buggy, nothing else matters...

I'd like to add a bounty to this issue. Can someone please add it to BountySource?

**Comment by toddmedema** [comment]
Would it be possible to add this on BountySource? This bug is driving me crazy and making Habitica unfortunately annoying to use, I'd be happy to pay someone $20 to fix this

**Comment by Alys** [comment]
@toddmedema I'll talk to the staff about getting it added to BountySource, but one thing first:

Can you confirm that you experience this bug with **checklist** items inside a single To-Do? I.e., on the website, you find a To-Do that has a checklist, you open that To-Do for editing, then in the edit modal, you drag the checklist items around, and then you find that the checklist reorders itself. Is that what happens?

If it's actually To-Dos themselves that you can't sort, then you have a different, much more common bug: https://github.com/HabitRPG/habitica/issues/7645

**Comment by toddmedema** [comment]
Ah, that's the correct one! Is there a bounty on that one?

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Is this still an issue for people?

**Comment by thebat137** [comment]
I was experiencing it occasionally before and have not experienced it since the update.

**Comment by toddmedema** [comment]
I also have not experienced this since the update, huzzah!

**Comment by Prutonium** [comment]
Haven't seen the issue since either :) great work on the update y'all!
