### ISSUE TITLE
Canceling subscription redirects to Tasks page

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8088]
General Info
- UUID: e8277c2b-d1a0-47f8-9a08-31211ee578c8 (a test user)
- Browser: Chrome
- OS: Windows 10
### Description

When a user completes a subscription, the subscription settings page reloads to show them the new information. (It could maybe use a loading screen, but that's a separate matter.) Upon canceling a subscription, however, the process takes them to a reload of the Tasks page instead. This is a bit disorienting, making it hard to confirm that the unsubscribe action succeeded.

I've seen this happen with Amazon Payments at least; I'll update this when I get a chance to look at the other payment methods.
#### Console Errors

None

**Comment by librarianmage** [comment]
How does this work now, with the client redesign?

**Comment by Alys** [comment]
I just tested with a Stripe subscription. When you cancel, you see a JavaScript alert saying that your subscription was cancelled and then when you click it's ok button, you're redirected to the Tasks page.

A better approach would be to not have the JavaScript alert and instead refresh the data on the Subscription page to show the termination date, and not redirect the user away from that page.

So this issue is still relevant.

I've updated the labels.
