### ISSUE TITLE
Feeding Pets in Vivaldi

### ISSUE THREAD

**Issue by jtgithub2016** [HabitRPG/habitica#8094]
General Info
- UUID: e44e6069-2e30-49cf-ab49-db41d3134045
- Browser: Vivaldi
- OS: Windows 7
### Description

When feeding pets, I usually have to feed the pet twice.  The first time, I get the "likes the food" message in the upper right hand corner of the screen, but the pet's development bar doesn't move, and the food doesn't disappear.  So then I re-click on the food, feed the pet the same piece of food again.  The second time around, the pet's development bar moves, the "likes the food" message reappears, and I also get a pink "can't find" error message.

Not a life-threatening issue, just something that could be smoother.

**Comment by Alys** [comment]
Can you please log out of Habitica then log back in and see if the behaviour persists. Post here if you need to be given food or eggs or potions to test it again.

**Comment by jtgithub2016** [comment]
Looks like that fixed the problem.  Thanks.

**Comment by Alys** [comment]
@jtgithub2016 Habitica has a guild now for telling us about bugs, which you might find more convenient, and which often helps us because we can see information about your Habitica account immediately. You can access it from the website's menu at Help > [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac).
