### ISSUE TITLE
Habits v2 - expected frequency/counter/last time performed (from Trello)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8113]
In the trello card [HABITS v2 (expected Habit Frequency, Onlies, Habit Maximum, Custom
Habit Names)](https://trello.com/c/cwQvDQI9/208-habits-v2-expected-habit-frequency-onlies-habit-maximum-custom-habit-names), @shalottastolat (shalott / astolat) has offered to work on part of it:
"Is anyone actively working on this (the expected frequency/counter/last time performed part)? I am finding that I want this a lot (I keep losing track myself) so would take a shot at it if no one else is on it!"

This issue is for discussing specifics.

**Comment by shalott** [comment]
Hi all, here's my plan for the feature; comments welcome. 

A habit will have a counter period that can be specified (per day, per week, per month (?)) - default is per day.

In tasks view you will see a counter on the habit box (to the left of the "top" icon, same place the streak counter goes on a daily) showing the number of times the habit has been ticked within the period. 

If it is a +/- habit then it will show # positive:# negative. (I am considering whether it makes more sense to have the negative counter BE negative -- ie -1, -2, etc. -- will try it and screenshot for opinions).  

At the end of the counter period, the counter will reset to 0. 

Some more thoughts:

I considered allowing an optional "target" but that adds more numbers to enter and display, and also makes +/- habits more complicated -- either there is one target and you combine the +/- or there are separate habits and you have to enter multiple info. It's also not obvious to me how the reward mechanics should change, so rather than get into this area, I figure I will do the first pass on just the counter.  

(If there was a huge demand for a target, I would probably try having the targets displayed only in the long description and use either background color or bolding on the counter to show whether a target had been met.) 

I will also look into adding more info about the last-checked-on to the "progress" chart.

**Comment by Alys** [comment]
@lemoness what do you think about this?

@shalott I agree with your assessment that it would be best to do just the counter for now and consider the target later. I've seen a LOT of request for counters but fewer for targets.

**Comment by lemoness** [comment]
I think that sticking with the counter is best for now. The proposed idea sounds like it would work well!

**Comment by Alys** [comment]
@shalott You're welcome to go ahead with this whenever you wish! Comment here if you have questions or run into trouble.

**Comment by shalott** [comment]
Tossing these up for opinions. I am inclined to skip the - symbol -- it is more intuitive to have the positive counter go first in keeping with the + appearing above the - boxes, but if you have a negative number after the : then it looks bad, and I haven't found a better separator. (There is "Positive Counter" and "Negative Counter" tooltip text on the +/- counts when both appear.)

no minus symbol, positive counter first:
![screenshot 2016-10-26 12 10 09](https://cloud.githubusercontent.com/assets/415001/19734467/a95b889c-9b75-11e6-8403-cbc2547fb446.png)

minus symbol, negative counter first:
![screenshot 2016-10-26 12 12 50](https://cloud.githubusercontent.com/assets/415001/19734644/5205cf70-9b76-11e6-85b1-d2d9ff658815.png)

minus symbol, positive counter first: 
![screenshot 2016-10-26 12 16 52](https://cloud.githubusercontent.com/assets/415001/19734594/1c366dfa-9b76-11e6-9e69-124f43e63d47.png)

**Comment by Alys** [comment]
I think the minus symbol is necessary for clarity, even with the tooltips (users don't always read them, especially on icons that they might not realise have tool tips). I'd be interested to see what it looks like with a + symbol as well as the minus. That might make the meaning even clearer.

Have you considered using a pipe | as a separator? Perhaps it will look better? `+3|-2`

**Comment by shalott** [comment]
![screenshot 2016-10-27 15 40 03](https://cloud.githubusercontent.com/assets/415001/19782399/afcf6f0e-9c5b-11e6-9fe7-cc1ebbb3419c.png)

IDK, I still don't think it looks great? Better than with the : and the + definitely helps, but it still feels a bit clunky. But I am happy to keep it whichever way you all prefer! I also tried it with badging but I think it looks worse. 

![screenshot 2016-10-27 15 50 49](https://cloud.githubusercontent.com/assets/415001/19782750/33d80d50-9c5d-11e6-90f4-87b8f7018cc8.png)

**Comment by shalott** [comment]
Pullreq submitted: 

https://github.com/HabitRPG/habitica/pull/8175

**Comment by tobek** [comment]
Hey guys, I was musing about a similar feature (and [commented on the trello board](https://trello.com/c/cwQvDQI9/208-habits-v2-expected-habit-frequency-onlies-habit-maximum-custom-habit-names#comment-5836803370bf699b3dea8e5e)) and did a mockup that might work as a UI for the counter:

![image](http://i.imgur.com/Yomb56b.png?1)

Also, not sure exactly how you were going to implement the counter period + resetting, but personally I'd love to have a trailing window, e.g. the counter shows how you did in the previous 7 days, rather than, say, the current week. A fixed window like the current week would sometimes show your progress over the last 1 day, sometimes over the last 7 days, so at a glance you wouldn't have any context for the size of the number.

I'm a developer and though I'm new to Habitica I'm familiar with everything the stack and would love to help out here.

**Comment by tobek** [comment]
@shalott I see you have a PR open for this - if you guys like this UI and/or trailing window (control field could be "Counter shows last X days") I'm happy to submit a PR to your branch.

**Comment by shalott** [comment]
I'm sorry, but for my part, I don't want either of those and prefer the functionality as I've already coded it. I find the dots very hard to "read" and they'd be especially bad for tasks I want to do a large number of times within the counter period. And a trailing window would frustrate me. If I have a weekly target in my head, I want to see myself building up towards it.

**Comment by tobek** [comment]
Fair enough - I look forward to the feature being released!

**Comment by khipkin** [comment]
Also, small red and green dots would be incredibly difficult for visually-impaired users to process, especially colorblind users.
