### ISSUE TITLE
Travis build icon on README.md broken

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica#8124]
General Info
- UUID: 30983c37-52c3-415d-977c-38af6c7db91c
### Description

The travis-ci build status icon on the README.md page points to https://travis-ci.org/HabitRPG/habitrpg which now says _The repository at HabitRPG/habitrpg was not found_ which is true, because the actual travis-ci build is https://travis-ci.org/HabitRPG/habitica.

The code climate and coverage icons still refer to "habitrpg", and https://github.com/HabitRPG/habitrpg still redirects to https://github.com/HabitRPG/habitica, so I'm not sure when this broke.

**Comment by DrStrangepork** [comment]
I'll submit a PR for this.

**Comment by DrStrangepork** [comment]
Incidentally, is there a way I could have created my PR in this issue rather than doing the standard PR which opens another ticket (#8125)?

**Comment by DrStrangepork** [comment]
Looks like #8090 may have caused this breakage.

**Comment by Alys** [comment]
issues and PRs are separate things so you couldn't have put your PR into
this issue but if you find a problem and want to fix it immediately, you
can submit a PR with no issue - just describe the problem and the fix in
the PR. I personally think that reduces clutter (only for immediate fixes
though). However if another admin disgrees, listen to them not me. :)

Note though that there is always a bit of a risk with submitting a PR
before there's an admin-approved iissue because if the fix isn't desired
for some reason, your time to create it might be wasted.
