### ISSUE TITLE
Quest items not showing up

### ISSUE THREAD

**Issue by spdale** [HabitRPG/habitica#8130]
General Info
- UUID: 
- Browser: Chrome
- OS: 
### Description

Hi there. I started a quest and did some tasks. There were multiple pop up dialogues that said that I had found quest items, but then when I go to the party area to check my progress, it shows 0/25 blue fins and 0/25 fire coral. 

I'm a new user, so this could be an error on my end, but I would guess that this is a bug.

<img width="1440" alt="screen shot 2016-10-12 at 12 43 55 pm" src="https://cloud.githubusercontent.com/assets/11237859/19325239/178fd1bc-907a-11e6-98bd-8da74314a507.png">

Cheers!

**Comment by Alys** [comment]
Your quest progress is updated on the party page each morning, so this is
expected behaviour.

When you have questions, Help > Ask a Question from the website's menu is
the best place to go. For bug reports, go to Help > Report a Bug if you're
sure it's a bug (use Ask a Question otherwise). If a GitHub issue is needed
for complex bugs, we'll let you know from there. :)

**Comment by spdale** [comment]
Okay cool. Sorry about that.
