### ISSUE TITLE
Missing Gems

### ISSUE THREAD

**Issue by PhillyMuzik** [HabitRPG/habitica#8157]
[//]: I donated for the first time tonight, but did not receive the 20 gems.

**Comment by crookedneighbor** [comment]
First guess without seeing your user data is that you purchased a subscription instead of a one time purchase of 20 gems. Subscriptions let you purchase gems with your gold in the market.

To confirm that, I'll need your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by PhillyMuzik** [comment]
c630fcee-069f-4cd3-bac2-9f1772bac018

Thank you.

**Comment by crookedneighbor** [comment]
Yep. Looks like you purchased a subscription. Here are the benefits for being a subscriber: http://habitica.wikia.com/wiki/Subscription

If that was not your intention, you can forward admin@habitica.com your receipt and they'll help you sort it out.

**Comment by Alys** [comment]
@PhillyMuzik We actually have a guild within Habitica now for faster reporting of problems and faster fixes or advice. You can get to it from Help > Report a Bug from the website's menu and Guilds > Report a Bug from the mobile app. One advantage of it is that we can see your User ID there and so can often resolve your problem as soon as we've seen your first message. 

I think there might be information somewhere on the internet suggesting that this GitHub repository is the best place to report minor problems, so we'll want to change that. Can you please tell us where you found any advice to create an issue here?
