### ISSUE TITLE
Limited Edition Equipment Lost After Death

### ISSUE THREAD

**Issue by messedupdweeb** [HabitRPG/habitica#8186]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 493ca067-8ede-45c4-b60c-858b55d29693
  * Browser: Safari/Android Web Viewer
  * OS: current

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

I lost all my health earlier today and one of the items that was taken away was a gem bought Autumn 2016 Seasonal Limited Edition Jeweled Shield(?) for healers.  I have died because I was unable to check off my dailies. I have been too busy attending to relatives who visited our ancestral home over the course of All Saints Day and All Souls Day. I also have ADHD which causes this tendency of "out of sight, out of mind." I am unable to purchase this back in the shops, I'm assuming because it is limited edition. Is there any way for any other equipment of mine to be taken away instead? One that can be bought in the rewards section instead of the gem shop one? I badly want my gem bought shield back. Thank you.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
When you lose items due to death, you can always buy them back with gold from your Rewards column. If you don't see it there immediately, please reload the website or sync the app (or log out and log back in if syncing doesn't help).

We actually have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu and Guilds > Report a Bug from the mobile app. For questions about Habitica features, you can go to Help > Ask a Question or Guilds > The Newbies Guild (but it's not just for new users). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.

**Comment by messedupdweeb** [comment]
Hi, the item that was taken away was a gem bought Autumn 2016 Seasonal Limited Edition Jeweled Buckler for healers. It's gone in the shops now since I bought it already. I was wondering if there's a way for a different item to be taken away instead, like my circlet or my armor, since these can be bought in the rewards tab.

Philip Reynald P. Cruz

**Comment by messedupdweeb** [comment]
Oh. Sorry. I get it now. Thank you.

Philip Reynald P. Cruz
