### ISSUE TITLE
Makes local installation independent to the paid and social stuff.

### ISSUE THREAD

**Issue by Cubox** [HabitRPG/habitica#819]
Hi,

I'm posting an issue here for this little problem. I tried creating a local installation today, and I was really disappointed.

Why local installations are (nearly) the **same** as habitrpg.com? I know, you have a lot of work, but I think it's can be good to separate things, and makes local installation independant of the paid things, tokens, ability to buy tokens, facebook login (just make an option, don't let it on by default!) and the home page.

I personnaly think that if people makes it run locally, they want their space, not all this links at the bottom, the share buttons, etc.

Yeah, not a critical issue, but it's have to be done to be a real project where people can have their own instances without stuff they don't care about.

Regards.

**Comment by titilambert** [comment]
Hello !
I started my own server for my team (for my job) last week. 
I set subscriptions for all of us but, we can't buy gems. We get this error:
`:type must be in [hatchingPotions,eggs,food,quests,special]`

Thanks for your answer

**Comment by lefnire** [comment]
Not by a computer computer, but look at habitrpg-shared#index.coffee# user.buy code

**Comment by Alys** [comment]
Confirmed on my local install, with a subscribed account, when trying to buy gems from the Market.
![screen shot 2014-08-24 at 2 50 38 pm](https://cloud.githubusercontent.com/assets/1495809/4022620/70534096-2b4a-11e4-8120-a0807a7ea332.png)
I'l have a poke around and see if I can find anything useful.

**Comment by Alys** [comment]
The error message is coming from here:
https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L619

Things I've read in the past indicate that there is special code for subscription features that is not available publicly in GitHub. I'm wondering if this is such a case. The HTML source of the gem in the Market is the same on the production site and the local install, so the backend code on production must be different than local. If that's true, then this error is expected behaviour, albeit not desirable in this particular case.

@titilambert, if you've installed your local server the same way I've installed mine, then in the page footer you'll have a Debug section, with an option to add 10 Gems. That will work, although if you want your team mates to buy gems with gold they've earned, this Debug option might be undesirable. :)  You could also add gems directly to their account by manipulating the database directly.

@lefnire, I think we need you for this one.

**Comment by titilambert** [comment]
@Alys Thanks for your answer !
I installed and configured my server without debug option (I don't want it)
So I did what you suggest: manipule the database directly.
I just started a small web interface to administrate an HabitRPG server. (Add/remove/edit users, set balance, create challenge, ...)
This interface add some features like buy and sell gems, gold transfer between users.
I will release this interface soon on github.

**Comment by titilambert** [comment]
See here: https://github.com/titilambert/Habit-Black-Market

**Comment by Alys** [comment]
This is old, and the errors discussed here have probably been resolved. If not, someone having trouble with a local installation can ask for help in a new issue or in the Aspiring Coders guild. See also http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths and linked pages.

Regarding the initial request to have the local installs be different than the production site: The primary purpose of a local install is to allow development for HabitRPG and so it should be as similar as possible. The gem-purchasable features can be bought locally without real money being spent by using the gem debug option in the footer. Also, anyone with a local install who wants to use it for their own purposes can modify it in any way they choose.
