### ISSUE TITLE
Rebirth not resetting one of the dailies

### ISSUE THREAD

**Issue by lynxlynxlynx** [HabitRPG/habitica#8196]
I've just been reborn again and all went as expected. All but one thing — one daily has intact value, streak count and history. Even after a forced refresh. It is the only one still part of an active challenge, so that may be a good starting point for investigation.
http://imgur.com/MDoC2LL

I didn't see any console errors. I'll let you know what happens after cron.

UUID: 10c530d0-a796-476b-8a31-6f048c6e8a8c

**Comment by SabreCat** [comment]
This is intentional. Because the Daily is part of an active Challenge, it is excluded from modification by skills, Fortify Potions, and Rebirth. Challenge judging often relies on task value being an indicator of how often the task has been completed, so we try to keep Challenge tasks clear of influence by factors other than completions and misses.

**Comment by lynxlynxlynx** [comment]
So a bit of a corner case, but perhaps it should be mentioned in rebirth docs anyway.

**Comment by Alys** [comment]
@lynxlynxlynx The confirmation screen for Rebirth mentions that challenge tasks aren't affected, but if you'd like the wording to be changed to make it more understandable, please comment here with suggestions. It's brief so it might not be clear enough.

**Comment by lynxlynxlynx** [comment]
Ah, must've missed it, as it's not my first rebirth and it has been ages since I translated that bit.
