### ISSUE TITLE
Habitica thinks it's yesterday

### ISSUE THREAD

**Issue by bek8** [HabitRPG/habitica#8208]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: ee01128e-0514-4ce4-9c97-cf9f78e529a3
  * Browser: Chrome Version 54.0.2840.71 (64-bit)
  * OS: Mac Sierra 10.12.1

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
I opened habitica on a Mac that was in the wrong time zone yesterday (after a new installation of the OS), then corrected my time zone settings. Suddenly all my tasks in habitica were unchecked, as if a new day had started and I lost life for a few unfinished tasks.

Today, everything is already checked off as if I'm stuck in yesterday.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
No errors.

app-3d94859e.js:36 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at s.zone (https://habitica.com/app-3d94859e.js:36:16132)
    at Object.authenticate (https://habitica.com/app-3d94859e.js:48:30294)
    at Object.<anonymous> (https://habitica.com/app-3d94859e.js:48:31515)
    at Object.i [as invoke] (https://habitica.com/app-3d94859e.js:7:17654)
    at Object.c [as $get] (https://habitica.com/app-3d94859e.js:7:16050)
    at Object.i [as invoke] (https://habitica.com/app-3d94859e.js:7:17654)
    at https://habitica.com/app-3d94859e.js:7:15700
    at g (https://habitica.com/app-3d94859e.js:7:17287)
    at Object.i [as invoke] (https://habitica.com/app-3d94859e.js:7:17621)
    at D.instance (https://habitica.com/app-3d94859e.js:8:9255)

**Comment by bek8** [comment]
I saw I should have rested in the inn before changing the time zone, but to be honest, habitica was not really on my mind when I set up my new mac... http://habitica.wikia.com/wiki/Rest_in_the_Inn

**Comment by Alys** [comment]
This is expected behaviour, and correct from a technical point of view, although unfortunate from your point of view. Habitica reads the time zone from your PC or mobile device - it has no other way to find out which time zone you are in - so having the wrong time zone on your PC or making a sudden change to the zone can result in cron happening at a time that seems wrong to you. On the website, you can use Settings > Site > [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to restore your lost health. If your time zone is now set correctly, your Dailies should be back to normal tomorrow. If you want to untick them to use them today, you can use the same tool to restore the XP, GP, and MP that you lose from unticking them.

We actually have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that. However if you have questions about what I've written in this issue, you can comment here now.

**Comment by bek8** [comment]
Thank you! Fixed it :)

Happy regards,
Kate
