### ISSUE TITLE
dailies not reset, due to timezone issue? (gmt+8)

### ISSUE THREAD

**Issue by ahoebeke** [HabitRPG/habitica#822]
Hi,
I'm living in China. I have the "reset dailies" time set at 03:00.
Yesterday evening around 1am (well early this morning..) I checked off a few dailies.
Now I booted up my pc, loaded the page and it's almost 13:00 and I see the dailies are still checked (and no penalties for the ones I didn't finish.. not yet!).

**Comment by Alys** [comment]
I've noticed something similar just in the past day. I'm at GMT+10. I went away for the weekend, so I had all my dailies set to grey for Sunday. On Monday, they were still grey, even though they should have been active. Just before bed on Monday night (9pm GMT+10), I checked again and they were still grey. When I checked the next morning (7am GMT+10), I found I'd suffered a HUGE decrease in Health overnight - exactly what I'd expect if my dailies had not been grey and I'd left them all unticked before going to bed.

Today (Tuesday, 10am GMT:10) if I experiment with a daily by selecting or unselecting the "T" box, it makes no difference to whether the daily is grey or not. However if I select or unselect the "M" box, the daily changes to and from grey. It's as if HabitRPG thinks today is still Monday.

**Comment by wizonesolutions** [comment]
@Alys Did you set _all_ your dailies not to be active on a particular day? Or only some?

**Comment by ahoebeke** [comment]
(little update for me: looks as if it took much more than 24h to update
anything.. as I only today (tuesday) saw a change)

**Comment by wizonesolutions** [comment]
See how it goes today. If it always takes that long.

**Comment by ahoebeke** [comment]
I can tell you what time they get reset, if it's ok for me to change the
time to 1:00am (instead of 4:00am.. because I won't sleep late this
evening).
If you think I shouldn't change this setting for now and just see if things
seem to work fine this evening and then tomorrow, let me know :)

**Comment by wizonesolutions** [comment]
I'd say don't change it unless you get up before 4 AM and want to see them
reset. Mine's at 4 AM too even though I go to bed around 11 PM :)

My suspicion is that changing the custom day start right after cron has run
might make it skip a day like this. Something like that. I noticed some
interesting things when I was testing #587.

**Comment by Alys** [comment]
Kevin:  "Did you set _all_ your dailies not to be active on a particular
day? Or only some?"  --- I had ALL my dailies set to not be active on
Saturday and Sunday. Also, some of them were set to be not active on other
days.

I think that might be a bit of a false lead though. The real problem seems
to be that HabitRPG doesn't know what day it is here. :)  At the moment, my
time is Tuesday 8pm GMT+10. If I go to the edit form for any one of my
dailies, and click on the "M" button, the daily greys-out immediately, then
un-greys if I click it again. If I do the same with the "T" button, there's
no greying. HabitRPG thinks that today is still Monday.

**Comment by edrago** [comment]
I'm having the exact same problem as Alys. HabitRPG thinks that today is still Monday and yesterday dailies that should be active were greyed out too.
My timezone is GMT -3

**Comment by wizonesolutions** [comment]
@Alys @edrago Is it consistent? i.e. is it always one day behind? out of curiosity, and if possible, what happens if you set your custom day start back to midnight?

Habit uses your local time for figuring everything out, so your timezone shouldn't matter.

Also, just to confirm — this is not just a "dailies have wrong color" issue but a "dailies get reset at wrong time" issue, right? In other words, if I understand correctly, the Monday rules will be applied whenever it runs for you; you won't lose HP for unfinished Tuesday dailies. Is this right?

**Comment by edrago** [comment]
@wizonesolutions I already had set custom day start to 00:00 hours as soon as I noticed the problem (About Sunday night or Monday morning, I don't remember exactly), but got no changes apparently.
Concerning the rules consequences, I haven't tested it yet as all the dailies were grayed. I will leave some colored daily today unchecked to see what happens.
But given that the daily change colors when I check/uncheck the Repeat "M" button, the chances are that it isn't resetting accordingly.

**Comment by Alys** [comment]
> Is it consistent? i.e. is it always one day behind?

Yes, although it's only been happening for three to six days (I'm not
certain since i was away for the weekend). Today (Wednesday, 5:30am,
GMT+10) the dailies are acting as if the day is Tuesday.

> what happens if you set your custom day start back to midnight?

My day start is already set to 0 (which I believe is midnight).

> this is not just a "dailies have wrong color" issue but a
> "dailies get reset at wrong time" issue, right? In other words,
> if I understand correctly, the Monday rules will be applied
> whenever it runs for you; you won't lose HP for unfinished
> Tuesday dailies. Is this right?

Forgive me for I'm not sure I understand the question, but:

Last night, just before bed, I had six unactioned Monday dailies and I was
penalised for those overnight, even though the yesterday was Tuesday. The
Monday dailies that I had completed yesterday were also Tuesday dailies
(most of my dailies are active on every day) and as far as I can tell I did
not get penalised for "uncompleted" Tuesday dailies (because they HAD been
completed but as Monday dailies).

And I would say that the dailies ARE the wrong colour because they'll be
grey when they should be not grey (or vice versa). (I'm capitalising for
emphasis, not for shouting. :))

In practice, this isn't actually a major bug for me now that I've
recognised how it works, because I can just toggle the dailies for one day
earlier than I actually want, but I'm concerned that I might die if the bug
gets fixed while I'm asleep. :)

This might be relevant: last week, perhaps Wednesday or Thursday but I'm
not sure, HabitRPG seemed to be frozen for a day or so. I couldn't add or
edit or tick off anything, couldn't change any dailies, and the dailies
didn't get reset overnight. I didn't report it at the time because I was
frantically busy at work last week. I think it fixed itself at some time on
Thursday or Friday. The wrong-day problem started after that, but I'm not
sure if it was immediately after or a day or two after. On Friday, the only
thing I did on HabitRPG was grey-out all my dailies for my weekend away.
Sorry - my memory's a bit vague; last week was kind of nasty at work. :)

**Comment by joe-jordan** [comment]
to restate the problem I have been seeing the last few days, as I described in #826 ,
- I have never changed the time of day to update dailies,
- I have been seeing _yesterdays_ dailies active since Monday (when I saw Sundays again.)
- my timezone is GMT+1 (British Summer Time), although timezone seems to be a misnomer here since people in lots of different ones are seeing a similar issue.

Alys' comment that HRPG froze last week, and then has been wrong since last Friday or something, seems to indicate that this may be a problem of particular accounts getting corrupted, perhaps by a rogue database operation under certain circumstances, and then being wrong from that point onwards.

_NOTE_: upon re-reading Alys' comment, their description is not specific about which day the problem started, so it may still have been a global db event on Sunday or Monday.

In case it helps, here is my list of dailies and their pattern:

1: weekdays
2: Saturdays (new, used to be another 1).
3: Sunday
4: Monday, Wednesday, Friday
5: every day.

In contrast to Alys' workaround, to recalibrate every single daily, I'm just entering what I did yesterday, in case the problem rights itself.

**Comment by wizonesolutions** [comment]
@lefnire, are there any other `lastCron` issues that might play in here? It
doesn't seem like my fix is the culprit; it has perhaps just revealed the
behavior :)

**Comment by ahoebeke** [comment]
No more mistakes here. Didn't get reset until after midnight (and so,
probably around 4:00). In the morning dailies were all correctly reset.
Not sure what the problem could have been... I'll watch out for if it
happens again

**Comment by edrago** [comment]
So, I left a daily unchecked yesterday and got no penalty till now, but habitRPG is showing the wrong colors still and changing them when I press the "T" button in Repeat section. Apparently is the code for the UI that's calculating something wrong, but the logic is working as it should.
I'll leave the same daily unchecked today despite being shown gray and see if my guess is correct.

**Comment by joe-jordan** [comment]
not fixed here either, my dailies for today (Wednesday) are all still the ones from Tuesday. I have checked by enabling number 4 (see above, repeating MWF) for Tuesdays temporarily and it un-greys itself when I do. (same behaviour @edrago is seeing).
I don't know how to check if I was penalised for uncompleted ones that were greyed out; I can't seem to see what caused my health to drop (but it is dropping, in spite of me checking all the dailies enabled for each day.)

**Comment by wizonesolutions** [comment]
That's good to know. Will help narrow it down. Some reports sound like it's
a UI issue, some sound like it's a system issue.

To those who may not know — the daily update currently runs the first time
you load the page (or the page updates) after your day start. It should
take multiple days into account, e.g. if you don't go to it for 2 days then
you lose double the HP.

**Comment by edrago** [comment]
@wizonesolutions I just checked and it's a UI problem. I got the penalty for the daily that I left unchecked yesterday, even though it was grayed out (But it shoudn't be). And the dailies are still showing the wrong colors today, as if were Wednesday.

**Comment by wizonesolutions** [comment]
Curious. Hmm, I'm going to check my own dailies...and they're fine. Strange. The only components in the calculation are the last time the daily reset happened and the repeat schedule itself (and of course the current time).

@lefnire Does lastCron re-set itself declaratively according to the current timestamp or does it imperatively increment itself by 1 day when "cron" runs? Cuz I don't see how this could persist for days for some users...but not me. It's gotta be a `lastCron` thing methinks but not sure where to dig.

**Comment by joe-jordan** [comment]
For more info - I sometimes leave the tab open for a while, but I often kill it and reopen it, especially during the last few days to see if this has gone away yet. The dailies have been consistently one day behind for the last few days - no matter how many times I refresh.

**Comment by edrago** [comment]
If you need more information. I had tested on my work PC (linux) on iceweasel, opera and chrome. As well on my home PC (windows/linux) on firefox and iceweasel and all have the same color problem. Maybe really is some timezone problem. I had tried to clear the cache and cookies too.

**Comment by wizonesolutions** [comment]
Yeah, maybe so actually. _People experiencing this issue: Would you mind
sharing your timezones if you haven't already?_ Also, people who see the
correct colors who might be watching this, can you also post yours?
Relative to GMT. For example mine is GMT+2

**Comment by Alys** [comment]
I have the problem (HabitRPG thinks it's Thursday when really it's Friday)
and my timezone is GMT+10.

**Comment by joe-jordan** [comment]
(I don't know if anyone else has noticed this, but...)

I see my MWF daily in grey today, it being Friday (and the UI showing Thursdays dailies.) However, when I hover I get the mouseover view (that is, I see it in colour), and I can in fact mark it as completed (and get the XP for it.)

Can anyone else who can see the bug do this?

**Comment by ahoebeke** [comment]
Me, timezone GMT+8 (china).
Tonight I worked until 6am, so I got to verify if it reset the dailies at
4:00. Actually, I didn't check untill after 5am or so. They didn't reset. I
refreshed the page, had to wait for half a minute and then they reset. I
couldn't check of some dailies right away, had to wait for a minute or two
and then that worked as well.

But I wasn't able since then to buy armor. I tried again now, still not
working. As I'm writing this, I refreshed the habitrpg page again. still
not possible to buy an item :-(  (oh, wait.. I had a bit more than 30 gold
pieces, but couldn't buy a 30gold armor.. the 25 gold armor worked..
strange..)
Sorry, just woke up after sleeping only a little, i should post some of
this in other bug reports I suppose.

**Comment by wizonesolutions** [comment]
@ahoebeke @Alys Can you confirm or object to @edrago's comment that it's a visual problem? That is, you lose HP correctly according to the days the dailies are set, but the colors make it look like the system has the wrong date. Or is the HP-taking behavior wrong too?

**Comment by ahoebeke** [comment]
The interface doesn't always react smoothly. Having to click several times
on a daily or other task, for example, happens regularly. Not a problem,
but smoothness is a plus.. that's a bit missing.
But no, I didn't notice problems that made me think there's a visual
problem, unlike @edrago

**Comment by wizonesolutions** [comment]
OK, so @ahoebeke (let's just keep it to this particular issue:)) the HP
loss also corresponds to the tasks for the wrong day?

That is, let's say you have a task called Exercise scheduled for Friday
(yesterday). When your tasks reset tomorrow (Sunday), will you lose HP if
you don't check off Exercise? Or did you already lose HP for any unfinished
Friday tasks this morning?

I hope this question makes sense :)

**Comment by ahoebeke** [comment]
I live in small place where every day is like the other (or none are
alike...). So my dailies aren't filtered for any particular day. I just
made a new daily, enabled only on friday. I can see tomorrow if I lost hp
or not.
(but...  i checked it even though it was greyed out, and I still got a new
drop!..  is that cheating?? :p)

**Comment by wizonesolutions** [comment]
@ahoebeke: :)

OK, so your daily was colored or greyed-out? Does it seem like the system
thinks it is Thursday?

Make sure not to check it so that you will lose HP. Maybe note down your HP
before you go to bed so you can use the Restore function to fix it if you
want :)

**Comment by ahoebeke** [comment]
What?? I just unchecked it again (the daily that only works on fridays,
that I made one hour ago) and I lost money and XP !!!  ........
Definitely a problem there. A greyed out daily (as it should be) that
reacts to check/uncheck and gives penalties.. problem!

**Comment by wizonesolutions** [comment]
No, that is normal. If you check it again you will get the gold/XP back. I think it's in any case you accidentally check it.

**Comment by wizonesolutions** [comment]
Dailies work even if it's not their day.

**Comment by Alys** [comment]
The problem is fixed for me. Today is Sunday and if I toggle the Su button,
the daily switches between grey and not grey. Toggling the S button (or any
other button) does not change the greyness. Thanks for the fix!

**Comment by joe-jordan** [comment]
Not fixed for me (still Saturday here, will check again in the morning.)

**Comment by joe-jordan** [comment]
(now that it's Sunday, this bug is fixed for me too.)

**Comment by wizonesolutions** [comment]
I didn't do anything, but glad it's working :)

@ahoebeke how did your testing go?

**Comment by Alys** [comment]
> I didn't do anything, but glad it's working :)

Well, it's broken again today. :)   Summary: On Saturday, HabitRPG thought
it was Friday (I had to use the F button to make a daily go grey or not
grey). On Sunday, HabitRPG knew it was Sunday (the Su button was the only
one that affected the colour of a daily). Today (Monday), I have to use the
Su button to grey/ungrey a daily. I am at GMT+10 but that's unlikely to be
relevant since I was also at GMT+10 yesterday. :)

Is there something special about how Sundays are handled in the code? E.g.,
are the days in a zero-indexed array with Sunday first and does the array
index of 0 get (accidentally) treated differently than the other indexes?
Is there any code that controls which day is considered to be the start of
the week (e.g., for a not-yet-implemented feature that would allow a user
to choose Sunday or Monday as the week start) and does that cause Sunday to
be treated differently? Wild guesses here. :)

To help with testing, I've created a new account, username alystest, email
address lady.alys@gmail.com, userid 3b7d59d1-9c79-4c96-a9ac-6e01664d4251. I
have not adjusted the Custom Day Start (it's set to 0). The account
contains nothing but one daily. The daily exhibits exactly the same problem
as with my real account (the M button doesn't affect its greyness today but
the Su button does). If any admins want to log in to that account to see
how it behaves for you, you are most welcome to do so - email me at that
address if you want me to give you the password, or hack the account any
way you wish to get in. :)

I am going to use the account to do testing for this question from Kevin
Kaland from two days ago:

> @ahoebeke @Alys Can you confirm or object to @edrago's comment that
> it's a visual problem? That is, you lose HP correctly according to the
> days the dailies are set, but the colors make it look like the system
> has the wrong date. Or is the HP-taking behavior wrong too?

I have used the Su button to make the daily grey for today. I will not tick
off the daily today (i.e., it will be unactioned at midnight my time).
Tomorrow morning, I will see whether I have lost HP from it. Kevin, please
tell me if this is not the test you were referring to above!

Alys

**Comment by dfjkla** [comment]
Same issue here. Doubt it's tz-related, but rather due to custom day end. It's after midnight between Su/Mon here, and I have items which are live on Monday lit up, although my custom day ends in a few hours, so they shouldn't be colored.

Possibly related to #587.

**Comment by wizonesolutions** [comment]
Alice: The days are indexed 0-6. We use Moment.js's `day()` function. My
dailies work fine, though; haven't noticed any problems. When I get some
time, I'll look into this, see if I can reproduce it.

**Comment by Alys** [comment]
I've done this test:

"> To help with testing, I've created a new account, username alystest...

> The account contains nothing but one daily...
> I am going to use the account to do testing for this:
> 
> > @ahoebeke @Alys Can you confirm or object to @edrago's comment that
> > it's a visual problem? That is, you lose HP correctly according to the
> > days the dailies are set, but the colors make it look like the system
> > has the wrong date. Or is the HP-taking behavior wrong too?
> > I have used the Su button to make the daily grey for today.
> > I will not tick off the daily today..."

Yes, it IS a visual problem. I lost HP last night for the daily that was
grey and not ticked off.

This makes it a more serious bug. All this time I must have been loosing HP
for dailies that I thought were safe to not action! (I.e., dailies that I
should not have had to action because I'd selected a day box to make them
grey.) I hadn't noticed that I was loosing more HP than I should have
because there were always some non-grey dailies that I hadn't actioned and
each daily takes a varying amount of HP.

I'll do another test tonight on that test account. I'll use the Tu button
to turn off the daily - even though the daily will not turn grey from that.
I'll leave it unticked and see if I loose HP again.

Kevin (or other admins/programmers), have you logged in to my test account
yet? It might be useful to know if you see the same problem that I do -
i.e., if you can tick the Tu button today (Tuesday) and yet not have the
daily turn grey.

**Comment by Alys** [comment]
I did this overnight (follow-up from my message yesterday):

"I'll do another test tonight on that test account. I'll use the Tu button to turn off the daily - even though the daily will not turn grey from that. I'll leave it unticked and see if I loose HP again."

I did NOT loose HP overnight. So, the problem is purely visual (and hence
more dangerous since you don't notice its full extent). I.e., if a daily is
disabled by having the current day's button toggled, then you don't loose
HP from not actioning that daily, but it looks as if you will loose HP (the
daily is not grey). If the daily is turned grey by toggling the previous
day's button, then it looks as if you won't loose HP, but you do loose HP
if you don't action it.

Since I've finished my tests, I don't care what happens to that test
account. The password is qwerty1234 and the username is alystest. I really
think someone else should log in to that account, toggle the daily's
colour, and report back about which day's button they had to use to make
the daily go grey. This should be someone who does not experience this
problem on their own account, and ideally a few people from different
timezones just in case it is timezone-related.

**Comment by wizonesolutions** [comment]
@Alys Thanks for continuing to update us on the issue. I concur that people should try logging into the account and seeing what happens in their timezones.

**Comment by Alys** [comment]
I did thorough testing again yesterday (Sunday). As for last Sunday, the
dailies worked perfectly. Toggling the "Su" button toggles the grey colour
AND toggles the removal of HP for dailies that are not ticked off.

So there's clearly something in the code that allows dailies to work
correctly on Sundays but not on other days.

**Comment by wizonesolutions** [comment]
Any further problems, let's tackle it on https://github.com/lefnire/habitrpg/issues/1057
