### ISSUE TITLE
Basi-List does not get correct damage

### ISSUE THREAD

**Issue by camachoborracho** [HabitRPG/habitica#8229]
Basi-List does not get correct damage for an attack. 

On a group quest, it says I have 4.0 damage, but it shows up as 97.0 health for basi-list. (there have been other times where it shows boss HP seems incorrect but this is the most obvious example I noticed). Doesn't seem to be a rounding error either.

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Inf o
  * UUID: 4d6a708d-3434-468d-bfaf-573dd1b04f7b
  * Browser: Google Chrome
  * OS: Macbook Pro

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
![screen shot 2016-11-21 at 9 25 46 am](https://cloud.githubusercontent.com/assets/15842968/20493729/d1b6bcc2-afce-11e6-9478-1e1f8e66e788.png)

**Comment by Alys** [comment]
This is from rounding. Your damage was 3.9970677369 and the boss's health is 96.002932263. The health is rounded up for display because you might want to know how much damage you'd have to do to defeat the boss. For a health of 96.002 you'd have to do 97 damage in whole numbers, not 96. 

If you'd like to suggest that we show decimals (e.g., on hover as we do for some of your own stats), Help > Request a Feature will take you to our Trello board and then the "QUESTS AND BOSSES v.2 (Collection Quest and Boss Fight Enhancements)" card will be the best place.

We actually have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.
