### ISSUE TITLE
Equipment Page Needs Search Function

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#8241]
Despite the sorting options, the Equipment page still gets quite unwieldy. There should be a way to easily search for a specific piece of equipment.

**Comment by a2lin** [comment]
Mind if I take a whack at this? I'm new to javascript but enthusiasm has got to count for something, right?

**Comment by librarianmage** [comment]
I'm guessing it is search by name?

**Comment by Alys** [comment]
@paglias This feels like it might be very dependent on how the equipment page is created. Would it be best done after the website improvement project is finished? 

@a2lin Sorry, I should have thought to ask that before I added the "help welcome" label. Thanks for asking! We'll comment again here about it soon.

@MathWhiz  Name, yes definitely. My personal opinion is that it would be good if the search also returned matches in the descriptions because sometimes you might remember a word from the description but not the name.

It would have to search using the player's chosen language of course.

**Comment by paglias** [comment]
@Alys If it's just adding an input field where items can be filtered by name, I'd say we can do it now, of it's a complete design change probably not worth it

**Comment by Alys** [comment]
@a2lin If you'd like to proceed as @paglias describes, please go ahead! E.g., you could add an input field into which a player types a word or phrase. That causes the equipment list to show only those items that contain the word or phrase in their name or description. Alternatively, it could keep showing all the equipment but have the ones that match the search highlighted in some way (or have the ones that don't match turned grey). We could consider other ideas too! Feel free to comment here if you'd like to describe how you want to do this.

**Comment by a2lin** [comment]
Sorry for the delay!
@Alys I've opened a PR with an attempt.

Took a few shortcuts:
Filtering by notes turns out to be quite the performance hit (if you own a lot of equipment). Since this feature is mostly targeted at people who own a lot of equipment, I took a shortcut and didn't include searching the description in this attempt (probably gonna need a better data structure unless I overlooked a thing).

Another shortcut here is that typing things like 'at' will match 'bat' in this attempt, since translated strings from certain languages e.g. chinese don't really have a readily made delimiter.

If the solution seems acceptable i'd appreciate a pointer to what tests are needed for something like this.

**Comment by Alys** [comment]
@a2lin Two days doesn't count as a delay! :) I'm impressed that you've made a PR already.

I totally agree about not searching the notes since it's bad for performance. Good call to leave it out. We're  part way through a project to improve the website's front-end code, and it might turn out that after that project is finished, filtering by note is faster, so we can look into it then.

I think it's fine that "at" will match "bat". It means that "bow" will match "crossbow" and "longbow" which is definitely an advantage. I'd call that a feature not a shortcut. :)

We'll comment on tests in your PR.
