### ISSUE TITLE
Move RPG elements to a separate page

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#828]
Discussion point, of interest to @zakkain @lemoness @horusofoz @Shaners:

I'm thinking we should move all RPG stuff (customizations, market, inventory, pets, tavern, etc) into a separate page. Totally up for discussion / brainstorming, nothing official yet (and this coincides with @horusofoz's comps discussion), but here's my reasoning:
- Pets is overwhelming the modal, just as an example - other things may follow suit
- More importantly, we're starting to actually have too many dynamic bindings on a single page. It seems to be causing slowdown (@Shaners experienced that from the "clear completed" todos). @switz what do you think about this particular point?

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/issues/361

**Comment by Shaners** [comment]
I see no issue with this idea as long as it's easy to get back to the main page. Perhaps with a big button on the header?

**Comment by lemoness** [comment]
I'm having a little trouble visualizing what this would look like..? You
mean, instead of clicking on yourself to see all your stats, you click on a
button and open a new page with all the tabs?

Could give us more breathing room. As long as it's obvious to people how to
access it, I guess we can give it a try...

**Comment by lemoness** [comment]
Okay, after thinking a bit, I am in favor of this for one really, really big reason.

I do not like our new Stables layout AT ALL.

I've wanted to bring this up as soon as it changed, but I haven't been sure exactly where to put my sorrowful rant, so I'll stick it here for now, and if you'd rather I make a new ticket or stick it in a different one, just let me know. (I know this system is a stop-gap, but it's been driving me insane, so just bear with me.)

First, the positive: heard good things from people about immediately getting to see a grid option of all the pets. When combined with the auto-egg drop, this is excellent, because people excitedly go find their egg on the grid and promptly decide which breeds they want. (I just got a very cute email from a friend explaining that he had determined that he wanted a "WHITE FOX," all capitals.)

I also really like that the numbers are displayed underneath our names!

Okay. Now my problems:
1. The scrolling. It's not working on some devices, and even when it does work, it's annoying. Having RPG elements on their own page will eliminate this big problem!
2. As soon as you get an actual pet, you are replacing the images in the grid with black pawprints. Okay. I know we talked about this before as an exciting motivation thing, but that's because of the element of surprise. You just showed them all of the pets! It's not a surprise anymore. 
3. And then additionally, it makes it impossible for you to examine the grid and choose what pets you want! So say you just glanced over the dragons, because originally you got a fox egg... well, now you have a dragon egg, and you can't remember which color was your favorite, and you can't see the awesome grid that you liked to browse earlier, but you have more or less an idea of what things look like already.... It just seems pointless.
4. Worse, the fact that your new pet is just dropped into its corresponding area in the grid means that you have to go browsing randomly through a sea of black pawprints to find it at all. With scrolling, it's impossible, and even without scrolling, it's not aesthetically pleasing as our main interface AT ALL. It's so crowded!

So. I stick by the stuff I said alongside my prototypes in the pixel thread. (https://github.com/lefnire/habitrpg/issues/107#issuecomment-16001098) While we definitely don't have to use my specific layouts, I do really feel that the following is CRUCIAL to our eventual system:

A. Main page is CLEAN, displaying only stable space and the pets that you currently have. Frankly, I like them being in the order you got them, but their sorting doesn't really matter yet. Beast Master explains way around page.

B. An obvious link to the grid of species, which can be marked in some creative way to show which ones you have. Maybe fadeout, maybe boxes.... something. But based on feedback from people I've talked to, they really like knowing what the pet options look like, so at the very least that should be on display somewhere obvious!

C. When you click on a pet, it displays their private section, where you can see and edit their details. This is CRUCIAL for the mount system, but it's not quite as important now.

D. Option to display your stable to your friends when they view your profile. Again, lower priority.

SO YES. 100% in favor of RPG elements having their own page. Especially since I foresee similar problems with our eventual armory/inventories.

In the interim, I almost wish that the pet layout would go back to how it was :(

PHEW guys, thanks for reading that! It's just that the pet system has quickly become my favorite part of Habit :)

**Comment by lefnire** [comment]
I'll keep these things in mind @lemoness when I come back for a second stab at the pets UI. I'd love to hear @zakkain's thoughts on the UI going forward. You, me, @zakkain, and @Shaners should have a pets roundtable in our next G+

**Comment by lefnire** [comment]
Alright guys, go check out https://beta.habitrpg.com and click the top-right chest button. It did indeed save us resources - for example, edit profile is fixed as a result (doesn't throw you back to the main tab), so it cleans things up and fixes bugs. Before I push to master I'm going to change the mechanism for toggling Tasks vs Game Options (that chest button is kinda stupid, but needed something temporary - any ideas? Also before pushing to master, I'm going to put our 3 NPCs in

**Comment by Shaners** [comment]
I'm actually <strong>really</strong> liking this new setup a lot. I don't mind the chest toggle so much but agree that it is kind of awkward and that a chest icon doesn't really say to me 'game options'. My suggestion would be to: remove the chest icon / toggle, move that functionality to users clicking on the avatar, add back in settings under user name drop down, and have the settings link in the user drop down function like the chest toggle but default you to the settings tab.

An issue with my suggestions could be users getting stuck in the game settings mode without knowing how to get back to their tasks. I'd like to hope that most people realizing that they clicked on the avatar to get there would click on it again to get back but you could perhaps add a little bar at the bottom of the avatar box that said 'Return to Tasks' and have that whole box's colours muted a bit.

I think how the chest toggle button is working right now in beta would be great in the future for encounter / quest notifications and interface. Maybe the growl would notify you that a monster has attacked you or that a new quest is available but not force you to participate until you were ready by clicking on the 'New Quest', 'New Encounter' toggle icons.

**Comment by switz** [comment]
woo, this is **awesome** tyler!

**Comment by lefnire** [comment]
Man, those NPCs _really_ pop... @Shaners & @lemoness are a serious pixel
artists - real SNES RPG stuff this. I'm gonna need @zakkain's help at some
point re-designing the inventory, it doesn't flow quite well currently. Ok,
couple pros / cons with @Shaners avatar / settings ideas. Pro: it feels
more natural to click the avatar to toggle, I keep accidentally doing it in
my testing. Then again, could be because I'm used to clicking the avatar.
Con: It's not obvious (for someone new) - though the initial "click here"
notification may mitigate that. Con: where to put notification of party
activity? Currently I put a bell next to the chest icon, I could just put
the bell bottom right in avatar box.

**Comment by lefnire** [comment]
@Shaners I just set your newStuff flag to show, and am uploading the Bailey
npc now if you wanna take a peak at that

**Comment by lefnire** [comment]
Modified version of @Shaners suggestion getting pushed now. Called
"options" instead of "settings", and it toggles. When you're in the options
stuff it says "Tasks", when in tasks it says "Options". That way we can put
the bell icon back into the menu for party alerts. Clicking avatar also
toggles.

**Comment by Shaners** [comment]
Also <strong>really</strong> like how Bailey looks functions ++

**Comment by bobbyroberts99** [comment]
Instead of the chest, how about a gear or wrench image? That's what I've 
been trained to look for on sites. I figured out that clicking on the 
avatar took me to the settings but it's not intuitive, not what I would 
guess first. Fun for me to figure out how to play the game but maybe 
frustrating to other players.

And instead of a toggle, once you go to the settings/options page, the 
wrench turns into a home image.

Those are my thoughts.

Tyler Renelle wrote:

**Comment by Shaners** [comment]
@lefnire I think it is perfect now (but just my opinion.) Allows for quicker access for experienced (and legacy) users plus intuitive access for newer users when they click on their user name and go to options. A tour tutorial pop up directing people to the options menu and hint that clicking on the player avatar also goes here should seal things up well.

**Comment by lefnire** [comment]
Awesome, and we're off! I made a not in the "new stuff" dialog for existing users. New users will get introduced to it on first "click your avatar" popover. Thanks guys!

**Comment by Shaners** [comment]
Have we lost the ability to see our character's level on mouse hover, over the avatar or is it just me?

**Comment by lefnire** [comment]
ah yes! oversight on my part, the main-char popover was annoying me (since
you oft click there for game options), but it was the only place level
resides. What do we think, put level back next to user name (in avatar
box), or put popover back in?

**Comment by lefnire** [comment]
as far as pet count, that's in the stable now

**Comment by Shaners** [comment]
And hp exp already in the header so seems silly to bring the popover back just to display level. Guess my vote is for avatar box. Were there issues there with long user names before?

**Comment by Pacerparty** [comment]
I think putting level next to username in herobox would be better. And below level show number of pets.
Or put level somewhere beside or near the XP bar.

And, maybe, put the avatar icon somewhere near the herobox. Maybe

**Comment by lemoness** [comment]
I am really, really loving the new format. It feels so much cleaner. Got
back from a week of spotty internet to a great surprise!

Quick question: did people like my stables prototypes enough for me to
start pixelling the backgrounds? If so, I'll get right on that. If not,
what changes would you suggest?

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/issues/107#issuecomment-16001098 ? What new pixel stuff to design, pray - the cubbies?

**Comment by lemoness** [comment]
Yes, the cubbies ;p And also the background for the close-up when you click
on a pet, so that you can rename it, feed it, and see how close it is to
becoming a mount.
