### ISSUE TITLE
"Path 'type' required" error from incomplete notification

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8282]
We've seen three reports from users who were getting constant errors saying `Path 'type' required`. It prevents them performing any actions on the website or mobile app.

It's caused by an incomplete entry in the user's `notifications` object. Below is an example. The cron notification is included for comparison - the incomplete notification is the one under it with nothing but an `updatedAt` line. In the examples I've seen, the incomplete notification always contains only the updatedAt line, but I don't know whether it's possible for other data to also be included.

    "notifications": [
        {
            "type": "CRON",
            "updatedAt": "2016-12-07T14:08:12.476Z",
            "createdAt": "2016-12-07T14:07:38.276Z",
            "data": {
                "hp": -30.89999999999999,
                "mp": -20.166666666666664
            },
            "id": "ad6dc60e-9e6c-437e-9318-1cafc625a0e9"
        },
        {
            "updatedAt": "2016-12-07T14:08:12.477Z"
        }
    ],

**Comment by Hus274** [comment]
Based on the example above and the fact that the updatedAt timestamps for the two notifications are at the same time and the type of the first one is CRON, I feel like this is likely related to the splice statement [here](https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/cron.js#L374). I'm wondering if there's a bug in Mongoose with this situation that could lead to this. 

What do you think about changing this to update the CRON notification to include the new data instead of removing the old notification and creating an entirely new one? Essentially change this from a delete and create to an alter?

**Comment by paglias** [comment]
@Hus274 my idea was the same, that .splice was to blame but I've asked mongoose's maintainer and there shouldn't be problems with it https://github.com/Automattic/mongoose/issues/4807#issuecomment-267792059. 

So far we've removed the code that added `updatedAt` to every notification and the errors have disappeared but I'm not sure if it solved the problem or if it was already solved and the change to `updatedAt` is totally unrelated, because in the days before the change to `updatedAt` the number of errors had already approached 0

**Comment by Hus274** [comment]
@paglias ahh ok, I would be curious to know if the bug starts reoccurring when the lastUpdatedTimestamp is reintroduced. Is there a reason we do a remove and then add a new notification instead of simply doing an update? It seems like the createdAt and updatedAt timestamps would make the update ideal.

**Comment by paglias** [comment]
This has been fixed since the updatedAt timestamps was removed
