### ISSUE TITLE
Suggestion for improvements to the new favicon

### ISSUE THREAD

**Issue by samking** [HabitRPG/habitica#8298]
The favicon was recently changed to have a white background (https://github.com/HabitRPG/habitica/issues/7720).  This makes it look non-standard since very few websites have a non-transparent background for their favicons, and the same is true for tiles in mobile apps, etc.

A more standard way of achieving good viewability regardless of the background is using an outline.  The two files I could find were `website/client-old/favicon.ico`  and `website/client-old/favicon_192x192.png`.  I made copies of each of them with white outlines and transparent backgrounds.

I put the `png`, `ico` and the original GIMP files up: 
https://samking.org/static/habitica_favicon_192x192_outline.png
https://samking.org/static/habitica_favicon_192x192_outline.xcf
https://samking.org/static/habitica_favicon_outline.ico
https://samking.org/static/habitica_favicon_outline.xcf

If this looks good to folks, let me know, and I can submit a pull request.

Thanks!

**Comment by Alys** [comment]
@samking Thank you for looking into this! I've pinged the staff to look at your suggestions.

**Comment by mcooledge** [comment]
Just to add my two cents: I definitely prefer this option. I didn't catch the reason for the white background change (now that I see it, I have never had the icon on my windows 10 taskbar), and the appearance on my list of pinned tabs has been bothering me since the change.

<img width="141" alt="habitica" src="https://cloud.githubusercontent.com/assets/11431021/21322499/37c15e72-c5ce-11e6-9a75-dea3fc9d5fd5.PNG">

**Comment by MathWhiz** [comment]
What is the status on this?

**Comment by librarianmage** [comment]
@Alys may I work on this?

**Comment by Alys** [comment]
Let me ping some staff about this elsewhere - I don't know the relevant person's id in github.

**Comment by Alys** [comment]
@MathWhiz :

@olson5504 has given me a zip file of official icons which I've uploaded to http://oldgods.net/habitica/favicons.zip
She writes "the one we were going to use for the web is the favicon-32x32 and favicon-16x16 with the purple outline. there were a bunch for the android and ios web browser, as well as some for windows bars too"

**Comment by librarianmage** [comment]
:+1: Does that mean I can change it?

**Comment by Alys** [comment]
@MathWhiz Yes, thanks!

**Comment by librarianmage** [comment]
@Alys Does this mean we are no longer using an `.ico` file?

**Comment by Alys** [comment]
@MathWhiz  Looks like there's support for multiple file formats and sizes: https://en.wikipedia.org/wiki/Favicon#Browser_implementation
I believe an ico file can contain two or more versions of different sizes although I haven't looked into it for ages.
Note that we'd want a solution that works in all modern browsers.

@olson5504 did you have a preference for how the new favicons are implemented?

**Comment by librarianmage** [comment]
@Alys I was wondering because quite a few of the files that reference the favicon use the `.ico` file, and I am unsure if that was required or not.

**Comment by saraolson** [comment]
@Alys @MathWhiz hey there! I believe I included a .ico file in the zip that shares the same design as the 16x16 and 32x32 pngs. When I mentioned those particular files, I was trying to clarify which design we want to implement for web browsers rather than the exact files for implementation (web browser gets the light purple outline style). Use the .ico file where it's best practices! Hope this clarifies any confusion, sorry!

**Comment by librarianmage** [comment]
@olson5504 There is indeed an `.ico` file with a light purple outline. Thanks for clarifying!
