### ISSUE TITLE
users had profile name change to @profile name not found & "BOSS_DAMAGE" notification errors occur

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8338]
### Description
With the last release a number of users names were change to *profile name not found*. It appears users who are affected also removes their blurb and image associated with them.

With current reports it appears not to be device specific or the users interacting with the API in any way.

Reports from Report a Bug Guild:
***From @Erik Angeles UID: 36904466-cfa0-4743-8f6c-201a1f3b5728***
> After purchasing a Coif, my name changed to profile name not found.

> @cTheDragons I purchased it on my android device. Chain Coif to be specific. Thanks for your quick reply! 

***From @tehkittehkat UID: d84a7025-05d9-4ba6-8f88-9cf55e3bc3bd***
> @cTheDragons I'm having the same problem as @Erik Angeles my name is showing as "profile name not found". This happened after I logged in after a couple of hours away. I hadn't performed any particular action, it was there at login. All members of my party are also showing as "profile name not found" so it's not just an issue with my profile.

> @cTheDragons I'm using the website, but it shows up on my Android app too. Thanks :)

> @cTheDragons Our party ID is ffb062fb-b161-4a1e-84c0-9a3f501fb4e3. No one else in my party is online, so I'm guessing they haven't logged in at all since the issue occurred and I'm the only one who's spotted it. 

One other report from the Tavern with no specific detail. (UID eb72f978-9f6f-430a-adf9-c0f8014642c2)

**Comment by etaiklein** [comment]
![](https://i.imgur.com/eRlKGPI.png)

**Comment by etaiklein** [comment]
Coming across this. https://github.com/HabitRPG/habitica/commit/0b8def555b01fc105368e4edb160838c5401803f
it...  explains why we're named this way but not how it became so. I lol'd.
Still digging.

**Comment by cTheDragons** [comment]
OK I just got hit by said bug. Been switching between the Android app and Party app. I cast a skill last before I notice but it could of occurred before that. 
UID : 95640e89-24f5-41c7-86ab-533d4ad41cc7

Party being casting Snowballs but not at me. Usual buffing activity.

**Comment by cTheDragons** [comment]
Appears 14 users of my 54 member party have been hit. All been active since the code release.

**Comment by tehkittehkat** [comment]
The issue has reoccurred for me (after I fixed it by manually changing
profile name under User>Profile). Also, now my avatar has turned into a
snowman?! Very strange. Android app screens hot attached.

**Comment by cTheDragons** [comment]
Snowman is due to your party throwing a snowball at you. (Check your party chat to see who).

Nice to know it not permanent.

Was their snowball throwing occurring before the first time your name changed?

**Comment by tehkittehkat** [comment]
Thanks! No, the snowball throwing occurred after the first time my name changed. Still a mystery!

**Comment by cTheDragons** [comment]
Appears your profile blurb is removed too with this bug.

**Comment by ghost** [comment]
This seems to affect whole parties at once, hitting everyone who's ~signed in recently. ("Recently" probably meaning since last code push.)~ participating in the quest?

**Comment by Alys** [comment]
There's only a limited number of PRs that could have caused this and I'm currently looking at this one: https://github.com/HabitRPG/habitica/pull/8249

**Comment by Alys** [comment]
Profile blurbs being removed is bad. :( Much harder to change back. Once this is fixed, we'll download a database backup from before this happened and either put back blurbs for those who ask or (better, if we can manage it) put them all back, if they haven't already been changed by the players.

**Comment by Alys** [comment]
The bug that caused this has been reverted in #8340 however it will still be affecting people as they log in and discover that their profile name, blurb, and image have been erased. @SabreCat and @TheHollidayInn are working to restore profile information from a recent database backup. Any names, blurbs, or images that have already been replaced will not be overwritten by data from the backup.

There's also a related bug where some players were seeing the error message "BOSS_DAMAGE is not a valid enum value for path type" and it was preventing them from using some parts of the site. That's been fixed for players who've logged in recently (by clearing all notifications to fix it quickly; I still need to put back the non-troublesome notificatiions). It still needs to be fixed for other players, either by deleting only the BOSS_DAMAGE notification or by redeploying the reverted PR so that the website is able to handle those notifications.

We should also fix the site so that notifications that aren't recognised don't cause errors that break the site.

**Comment by Alys** [comment]
All profile names, blurbs, and images have now been restored from a database backup (except for any that had already been added by the player themself).

The BOSS_DAMAGE notification was cleared from all players who'd logged in in the couple of weeks before the bug occurred. I didn't clear older accounts because they'll be handled when we do a proper fix for it. However it's still a problem for those older accounts if the users do log in now.

**Comment by Alys** [comment]
This is more important to fix quickly for ALL players than I originally realised. The "BOSS_DAMAGE is not a valid enum value for path type" error appears when an active player without a BOSS_DAMAGE notification casts a party skill, if any inactive player in the party has that notification (see #8370, and I've tested it myself now). So we need to either remove all BOSS_DAMAGE notifications from all accounts or adjust Habitica to handle the notification gracefully.

I can't do this. I'm travelling and have limited time for Habitica work, most of it going to the Report a Bug guild. Can another admin do this please? @TheHollidayInn @SabreCat @paglias

**Comment by paglias** [comment]
Fixed https://github.com/HabitRPG/habitica/commit/28e8ec2d2c16e8be478be338e21863bafc1e394b

If we have to revert again code that involves a notification we should pay attention not to remove it from the list of valid notifications
