### ISSUE TITLE
Dailies Grey-Out on Wrong Day

### ISSUE THREAD

**Issue by Gragriel** [HabitRPG/habitica#834]
It looks like my Dailies now appear  to not grey out when I have them set to skip today, but they do grey out when I have them set to skip yesterday. I think damage is still done correctly depending on which day you have set to skip.

**Comment by wc8** [comment]
Could this be related to custom day start? For example, if you're day starts at 6 am, and this happens between midnight and 6 am, it might be related to custom day start.

**Comment by wc8** [comment]
#587 seems similar

**Comment by edrago** [comment]
I am having it too. It's the same problem as #822

**Comment by Gragriel** [comment]
It's fixed now, I think. In the interest of full disclosure I had my day start set to the default 12am.

**Comment by psutinrerk** [comment]
I still got this problem, I try set custom day to 10PM and now the date is wrong :( how can I fix this

**Comment by Alys** [comment]
@psutinrerk What you're experiencing isn't this bug, it's because you've said that you want each day in Habitica to start at 10pm (that's what the Custom Day Start time is for). I.e., up until 10pm each real-world day, it's still the previous day in Habitica. For more information, see the wiki's [Custom Day Start](http://habitica.wikia.com/wiki/Custom_Day_Start) page.
