### ISSUE TITLE
translation mistake found 

### ISSUE THREAD

**Issue by jJayyyyyyy** [HabitRPG/habitica#8349]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

1.  filename: `habitica/website/common/locales/zh/gear.json`

    In the ZH-file, where keystring is `"headArmoireVioletFloppyHatNotes"`, its value states

    >... 增加<%= per %>点*感知*，<%= int %>点智力，以及<%= con %>点**感知** ...

2.  While in the EN-file `habitica/website/common/locales/en/gear.json`, it is

    >... Increases Perception by <%= per %>, Intelligence by <%= int %>, and **Constitution** by <%= con %>...

3.  The translation of User-Stats between EN and ZH in `Habitica` is

    | EN | ZH |
    | --- | --- |
    | Strength | 力量 |
    | Intelligence |  智力 |
    | Constitution | 体质 |
    | Perception | 感知 |

    But in `1.` the second **感知** (bold) in the ZH-file is translated from **Constitution** (bold) in the EN-file, which should be translated as **体质**.

<br/><br/>

Hope to help, and btw, happy new year :)

**Comment by Alys** [comment]
@jJayyyyyyy Thank you! I've copied your report to the [Aspiring Linguists of Habitica](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) guild.  If you'd like to help with translations, you'd be most welcome to! Drop in to that guild to see the resources in the guild's description and to chat to other translators.

If you find any other problems, we'd love to hear about them. That guild is the best place since translations are handled in Transifex rather than in GitHub.
