### ISSUE TITLE
Claim Button appearing on all tasks if your subscriber.

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8374]
## General Info

UID :bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 42.0.2393.85
Windows 10 32-bit

## Description

Since the latest release of [3.66.1](https://github.com/HabitRPG/habitica/tree/v3.66.1) claim buttons have appeared on all tasks that are not apart of a group plan. (Including challenge tasks).

If you click the claim button you receive an error only group tasks can be assigned.

Appears to be no other affect when completing/ticking tasks.

**Comment by TheHollidayInn** [comment]
This should be only if you have a subscription.

**Comment by cTheDragons** [comment]
So it meant to occur if you have a subscription?

OR 

It is a bug and is only occurring to users who have a subscription?

**Comment by TheHollidayInn** [comment]
It is a bug and I believe it is only happening when users have a subscription.

**Comment by cTheDragons** [comment]
Confirmed Only happening with users who subscribed.

**Comment by SondaSengupta** [comment]
I am also experiencing the same issue. It started last night and I'm a subscriber as well.
It actually makes it hard to read my tasks because of the way things are pushed onto new lines.

![screen shot 2017-01-06 at 7 19 12 am](https://cloud.githubusercontent.com/assets/7119672/21719088/68c0e9ae-d3e1-11e6-92a8-a4f2a1d08ea7.png)

**Comment by ksmith6** [comment]
@cTheDragons - The title has a spelling error: "your" should be "you're"

**Comment by SondaSengupta** [comment]
looks good!
