### ISSUE TITLE
I have negative gold and XP

### ISSUE THREAD

**Issue by KristenEberts** [HabitRPG/habitica#838]
I refreshed HabitRPG after a period of inactivity, and suddenly I had -20 gold and -172 XP. When I completed a task, my XP just went to -165 instead of resetting to its original level. Help, please!

**Comment by wc8** [comment]
For starters: User menu > Settings > Restore.

**Comment by SyntaxPickax** [comment]
Same here. When I logged in this morning, I saw a whole slew of reward/experience notifications appear on their own, which left me in this state:
![Screen Shot 2013-04-19 at 8 15 37 AM](https://f.cloud.github.com/assets/1245093/402554/e0557898-a903-11e2-9025-e507287eb113.png)

**Comment by wc8** [comment]
Possibly rogue tasks and in that sense, may be related to #777

**Comment by amirdt22** [comment]
Me too, #777 affected me as well so possibly the same issue.

**Comment by steelwolf** [comment]
That happened to me as well. I died soon after so it was resolved, haha.

**Comment by lefnire** [comment]
marking as crit. I'm going to spend the next while exploring a migration to AngularJS, which will fix a slew of bugs. If it turns out to be a beast, I'll revisit these crits in Derby

**Comment by katowulf** [comment]
This just happened to me today when I logged in.  I lost 25 gold and lots, probably around 200, XP.

I tried to catch a screenshot of all the notices but wasn't quite fast enough (sat a little too long in shock).  I had not logged in yesterday and should have lost some HP for my dailies, but the rest is a mystery.

![image](https://f.cloud.github.com/assets/959972/434797/74316f7c-af71-11e2-8f31-c9cad77255e9.png)

**Comment by deiwin** [comment]
Happened to me as well. Seemed to happen right after deleting a task, but I'm not 100% sure (might have happened before but I just didn't notice).

**Comment by lefnire** [comment]
I have limited computer access right now, will do some digging when I'm back to good. In the meantime, here's a thought - mostly @MrConcept or @switz might be able to chime in - The only thing that could be causing this is a negative multiplier in `gpModifier()` and `expModifier`, since Exp/GP are only calculated when up-scoring. Eg: str, weaponStr, priority, etc - one of those multipliers somehow accidentally getting a negative value.

My first thought was that logging into multiple computers is giving an inaccurate timestamp, causing the second login to be **before** the first login (user.lastCron), and making cron wig out. In that case, the `times` parameter passed to the `score()` function from `cron()` would be negative. This made sense, since people were also getting hurt when logging in from multiple computers - maybe lastCron timestamp was all jack. However, looking at the code we're `Math.abs`-ing the day diff calculation, so this wouldn't be the case. Just kinda thought-processes brain-dumping. Along those lines, @switz any thoughts on `new Date()` vs `+new Date()` on accuracy for stored timestamps?

**Comment by switz** [comment]
- new Date()s behave similarly. I just tested it in firefox/chrome and it worked as expected.  

I'll dive into the code later today and see if I can figure out what's going on here.

**Comment by zoebeagle** [comment]
I don't know if this will help or not, but I woke up this morning with Negative Experience and Gold.  The odd thing is that I did not miss a single daily, so I still had full health.  I've restored my EXP and GP, so that's not an issue, just thought maybe this information could be useful for tracking down the bug.  :)

**Comment by PhilipHow** [comment]
I'll look into this tonight. (Mainly as it happened to me!)

**Comment by lefnire** [comment]
of note Phil - if you have to modify any scoring functionality, we've moved
everything into habitrpg-shared and I'm almost done with the
habitrpg/tree/habitrpg-shared branch which uses that repo entirely. I'll be
merging it in hopefully tonight

**Comment by PhilipHow** [comment]
From my tests tonight, having another browser window open is actually unchecking the Tasks. I can see the negative XP and gold notifications on "Emulate next day", but score() or any of its helper functions aren't being called at all. If Daily Tasks pushed you over your level, then the changes to the model don't persist, get rolled back, and you get into negative XP.

@lefnire do you want me to fudge some negative XP protection into scoring? I think this is based on your Racer issues..

**Comment by lefnire** [comment]
almost certainly https://github.com/codeparty/racer/issues/109 . We could fudge scoring to protect against negative values, but there will still almost certainly be data-loss. This would just provide bumper for _just_ the negative gp/exp part of the dataloss, if that makes sense. We may just have to wait for Racer v0.5 to get released, which is pretty soon TMK (hopefully)

**Comment by PhilipHow** [comment]
![](http://img832.imageshack.us/img832/5103/gif4i.gif)

Racer isn't really racing anymore. :(

**Comment by lefnire** [comment]
I was able to duplicate this by having two browsers open when cron is run (start of the day). So one browser was left open from last nigh (Fluid), and I opened Habit in Chrome this morning. Negative GP & Exp, with a whole bunch of notifications as such

**Comment by bernerbits** [comment]
I just got hit with this one again today.

**Comment by lefnire** [comment]
this is fixed int he 0.5 upgrade, due to handling multiple browsers on a single session bug. soon

**Comment by pjfontillas** [comment]
This just happened to me today, but thankfully Restore can be used as a workaround.

**Comment by lefnire** [comment]
0.5 upgrade aborted, we'll have to wait till angular rewrite to fix this. check out No. 2 of http://habitrpg.tumblr.com/post/55792029689/bug-workarounds to avoid

**Comment by HLFH** [comment]
I used the restore function too. Good continuation. Yes, I think I forgot to do this : "only access Habit from one browser at a time"

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by wenkokke** [comment]
![screen shot 2015-04-07 at 08 42 04](https://cloud.githubusercontent.com/assets/3983973/7018233/11791bda-dd02-11e4-8400-d9a143d78da9.png)

[UID d1f641e3-2d6f-4f10-b183-a03217f4e7f6]

This morning, after I loaded up HabitRPG, it showed up with negative experience. I'm not entirely sure how that happened, but I'm sure I had a much more positive number when I went to bed yesterday.

**Comment by Alys** [comment]
It is probably that you levelled up (which meant that your XP dropped back to zero) and then a task that had been completed in your browser became uncompleted due to a sync error (i.e., the browser never told the HabitRPG server that the task was completed so a sync with the server marked the task as uncompleted). Becoming uncompleted caused the removal of the XP you had gained from the task, and so your XP dropped below zero. It will become positive as soon as you tick off another task.
