### ISSUE TITLE
API: dates may be invalid

### ISSUE THREAD

**Issue by madpink** [HabitRPG/habitica#8405]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: b0413351-405f-416f-8787-947ec1c85199
  * Browser: Safari
  * OS: MacOSX 10.11 (el capitain)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
When submitting new tasks through the tasks API, anything can go into many of the date params.

For example if I POST the following task: 
{type":"todo","text":"Practice Task","date":"ABCDE"}

Then the Due Date on the task listed on the Habitica site will be "ABCDE"

The only date that seems to be forced to be correct is "startDate" for "reminders"

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

### Notes
If you want to work on this this PR https://github.com/HabitRPG/habitica/pull/10625 has some useful code but the validation should be moved to the model. A migration to remove existing invalid dates is also going to be needed

**Comment by sprusr** [comment]
Going to have a crack at this, unless anybody else steps in

**Comment by JCiske** [comment]
Changing the type to date changes the look of the popup calendar.  I'm not sure that it would be a desirable look but it does work.

Before:
![before](https://cloud.githubusercontent.com/assets/1137190/22074967/795a6544-dd67-11e6-8962-a60e151e943d.png)

After:
![after](https://cloud.githubusercontent.com/assets/1137190/22074992/868d4484-dd67-11e6-944f-1f046943736d.png)

**Comment by sprusr** [comment]
@JCiske to clarify, this is a modification to the backend, changing how the "Due Date" for a todo is stored in the database. Shouldn't affect how the date picker is displayed on the frontend. The before listed above, also appears to be for a daily task, whereas this change only affects todo tasks.

**Comment by JCiske** [comment]
@sprusr Thanks for responding so quickly.  The images are exactly as you said, I was just trying to give a comparison as to what the "After" looked like before changing the type to "date" rather than "text".  So if I am understanding you clearly, the way the date was being displayed as well as the ability to input text isn't the issue and I am looking in the wrong place?

**Comment by sprusr** [comment]
@JCiske I think this is most likely an unrelated issue.

**Comment by JCiske** [comment]
I made the change and have since changed it back.  I was just trying to assist with the issue.

**Comment by Alys** [comment]
This is still happening. Example:

curl -X POST -H "x-api-user: $HRPG_USER_USERID_HOME" -H "x-api-key: $HRPG_USER_APITOKEN_HOME" https://habitica.com/api/v3/tasks/user
-d "type=todo&text=TST&**date=bob**"

{"success":true,"data":{"userId":"d904bd62-da08-416b-a816-ba797c9ee265","text":"TST",
**"date":"bob",**
"updatedAt":"2017-12-08T03:43:03.486Z","createdAt":"2017-12-08T03:43:03.486Z","_id":"54ac4930-5587-437c-8215-f90ae4be53b6","reminders":[],"group":{"approval":{"requested":false,"approved":false,"required":false},"assignedUsers":[]},"challenge":{},"attribute":"str","priority":1,"value":0,"tags":[],"notes":"","type":"todo","checklist":[],"collapseChecklist":false,"completed":false,"id":"54ac4930-5587-437c-8215-f90ae4be53b6"},"notifications":[],"userV":991,"appVersion":"4.13.2"}

**Comment by Alys** [comment]
I've just deleted some old comments that aren't directly relevant to this issue.

The issue is still happening, as shown by the API command and output below.

We've also had a report of it from @Kirska (64751d54-9d7f-4b38-80b0-c180ab9593d0) who created the [To-Do Overs](https://github.com/Kirska/Habitica_ToDoOvers) third-party too. It currently sets dates using Python's standard date format (e.g., "2020-09-09 09:03:59.374647"), and since Habitica's API doesn't give any error message about that, Kirska understandably thought that it was an acceptable format. Dates entered in that format are saved into the tasks in that format. They are actually handled correctly by the website, but the Android app doesn't recognise them, and so it doesn't treat treat such tasks as being scheduled.

Kirska also points out that the API's documentation doesn't specify the date format. That could be fixed separately from the change to the API's code, and would be immediately useful.

There's been an attempt to adjust the API in the past but it stalled: https://github.com/HabitRPG/habitica/pull/8414.
The approach was to throw an error if the date supplied was in the wrong format. I think that's a good approach (i.e., better than trying to convert a supplied date to the correct format since that could produce unexpected results if the input format is wildly different than expected).

That PR contains some discussion from the staff about how to do the fix and about a migration needed. It also mentions giving the Aspiring Comrades some advanced warning about the change since any tools currently using an incorrect format would stop working completely once the fix was in place.

I'm marking this as suggestion discussion in case Habitica's staff want to make any comments about how to fix this now.

I'm also marking it as "notify helpers" so that we don't forget to tell the Comrades after a fix is merged, although it would be better to tell them before merging to give them more notice.

---

Here's an example that proves that any format will be accepted for a date even something clearly incorrectly like `bob`:

curl -X POST -H "x-api-user: $USERID" -H "x-api-key: $APITOKEN" https://habitica.com/api/v3/tasks/user -d "type=todo&text=TST&**date=bob**"

{"success":true,"data":{"challenge":{},"group":{"approval":{"required":false,"approved":false,"requested":false},"assignedUsers":[],"sharedCompletion":"singleCompletion"},"completed":false,"collapseChecklist":false,"type":"todo","notes":"","tags":[],"value":0,"priority":1,"attribute":"str","byHabitica":false,"text":"TST",
**"date":"bob"**,
"checklist":[],"reminders":[],"_id":"eb7b4f81-829b-424e-aab7-de5ae78eec2d","createdAt":"2020-09-14T03:05:20.851Z","updatedAt":"2020-09-14T03:05:20.851Z","userId":"d904bd62-da08-416b-a816-ba797c9ee265","id":"eb7b4f81-829b-424e-aab7-de5ae78eec2d"}, ... }

Here's that task's details from the database with some of the irrelevant fields removed:
```
{
    "_id": "eb7b4f81-829b-424e-aab7-de5ae78eec2d",
    "completed": false,
    "type": "todo",
    "notes": "",
    "value": 0,
    "text": "TST",
    "date": "bob",
    "createdAt": "2020-09-14T03:05:20.851Z",
    "updatedAt": "2020-09-14T03:05:20.851Z",
    "userId": "d904bd62-da08-416b-a816-ba797c9ee265",
    "__v": 0
}
```

**Comment by veeeeeee** [comment]
We agree that having the API throw an error if an incorrect date format is supplied is the best approach.

**Comment by thewilloftheshadow** [comment]
Is this one available? I’d like to take a look at this

**Comment by paglias** [comment]
@thewilloftheshadow it's! I'm marking it as in progress for you

**Comment by thewilloftheshadow** [comment]
I have the fix working, that's just fine, but I'm not sure how to make a migration script. There doesn't seem to be any consistency to the ones in the repo and nothing on the wiki

**Comment by paglias** [comment]
Hi @thewilloftheshadow , for the migration script I'd take inspiration from a recent one like https://github.com/HabitRPG/habitica/blob/develop/migrations/archive/2020/20201102_fix_habitoween.js, basically in `processUsers` you write a query that targets the users / tasks that you want to change and then in `updateUser` (it's better not to change the name even if you're going to change tasks instead of users) you can modify the document based on what's needed. If you need help just push a wip version and I'll give it a look
