### ISSUE TITLE
Error in site login in Firefox browser

### ISSUE THREAD

**Issue by tassiolucas** [HabitRPG/habitica#8413]
The site does not work the login and popup button in Mozilla Firefox asking which means of login. When clicking it loads and nothing appears. I tested it on Google Chrome and it is working normally.

**Comment by Alys** [comment]
It definitely works in Firefox normally and I've just tested it successfully now. Your Firefox browser probably has cached some corrupted data for your account. Please go to https://habitica.com/static/clear-browser-data in the browser that's failing and click the red "clear data" button there, then try logging in again. If that still doesn't work, disable all Firefox extensions and try again.

If you still can't log in on Firefox, go to Help > Report a Bug using Chrome and briefly describe the problem there. That's a guild within Habitica so we can see your account there and can invesigate it to find out what's wrong.

That's actually the best place to report any bug initially. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub.

I'm closing this issue now but if it turns out that there is a problem with Firefox in general, we can reopen it.
