### ISSUE TITLE
Check-in prize message shouldn't always be plural

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#8428]
The check-in prize message for when the next prize will be awarded is always pluralised, even when there's only one day until the next prize. When there's only one day left, it should be singular, e.g. "Your next prize will unlock in 1 more check-in!"

Apologies if this is already known or if a fix is planned.

![image](https://cloud.githubusercontent.com/assets/9433472/22127441/c9d86df4-de93-11e6-83b5-1d1874d7f8e4.png)

**Comment by khipkin** [comment]
I'm not sure if this can be effectively translated into all languages that Habitica supports, but it might be easier to do something like instead of having separate singular/plural versions of the string:
> Your next prize will unlock in 123 more check-in(s)!

**Comment by Alys** [comment]
@GitHubSphinx Do you have any thoughts about whether workarounds like `check-in(s)` will work in enough languages to make it worth doing?

**Comment by ghost** [comment]
Quick reply: we have some pluralized strings that consider the difference
between '0 to 1' and '2 and above' in English. It's not the best option,
but I personally believe it's better than not having any pluralization at
all. As for the suggested walk-around, it should be noted that I've seen
reports from some translators who find the (-s) practice look not quite
natural both in English and when localized. At the same time having X
different strings (I can't even imagine how many) to fit all the languages
seems impossible to me at the moment. So I'd suggest starting with
singular/plural split-up.

BTW, we have had an issue with a comment suggesting to use a 3rd-party
library, but I can't find it when from mobile.

**Comment by ghost** [comment]
Now as I read the thread carefully, I should say I'm sorry that I haven't considered the context of the discussion. If the task is to make it look better with minimum changes, then I can mention a walk-around used by many translators.

Sometimes instead of having sentence-like string with grammar suitable only for some values of a variable (`Your next prize will unlock in X more check-ins`) it may be better to opt for something not so natural from linguistic point of view, but what will be always correct (`Check-ins till the next prize: X`).

It's not actually a suggestion for this particular issue, but just info about practice used by translators sometimes - please take it for what it's worth.

**Comment by Alys** [comment]
I like that idea! It also puts the number in a position where it's very easy to read when you're in a hurry, which is likely since this is a message you see first thing every day when you want to be getting ready for work/school. If there's no complaints in a couple of days, we'll go with this suggestion:

`Check-ins until your next prize:  <%= numberOfCheckinsLeft %>`

**Comment by deonna** [comment]
Is anyone currently working on this issue? If not, I'd like to pick it up.

**Comment by Alys** [comment]
@deonna Please do, thank you! Post here if you have any questions about it.
