### ISSUE TITLE
Stoïkalm Calamity, Part 1: Earthen Enemies 

### ISSUE THREAD

**Issue by brockmacd** [HabitRPG/habitica#8430]
I completed the quest, Stoïkalm Calamity, Part 1: Earthen Enemies, but was not awarded the prize (Mammoth Rider Armor)

- Sir Breven

**Comment by khipkin** [comment]
@brockmacd The admins will need your User ID (**not your API token**) and/or your party ID in order to view your account details.

Also, this seems to be a (still unconfirmed) case of #4252.

**Comment by brockmacd** [comment]
Hello, 

My ID is 
5722ec15-ceb3-48cd-ba5a-e6ae1bcdcd21
And party ID is
Group ID: a359261d-09ab-41ac-ba32-39f94dac6592

Thank you for your promptness!

Sir Breven

**Comment by Alys** [comment]
@brockmacd You do own the equipment from this quest. You'll find it in your equipment list. On the website, you can use the search form to search for it by name or partial name.

We have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu or Guilds > Report a Bug from the mobile app. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. We can see your User ID there and so can often resolve your problem as soon as we've seen your message. If an issue is needed, a moderator would advise you of that.

**Comment by brockmacd** [comment]
Hello!

First of all, thank you so much for this awesome app! My friends and I are epically more productive! Thank you!!

Secondly, a little bit ago, my credit card payment got messed up, and I lost my gem cap and time travelers progress and drop cap since my subscription started in December? 

Once again, thank you for all your work!

Brock 
AKA Alatar the blue 
5722ec15-ceb3-48cd-ba5a-e6ae1bcdcd21

**Comment by Alys** [comment]
@brockmacd I can't see any problems with your gem cap or Hourglasses or consecutive month count so I'll need more information. Since it involves your personal financial details, please email admin@habitica.com and include your message from here and any other information you might have (it's okay if you don't have more; I can ask specific questions if I need to).

BTW, we have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that. :)

**Comment by Alys** [comment]
Heh, sorry, copy-paste fail on that information about the Bug guild. :) Just read the first two paragraphs from my reply.
