### ISSUE TITLE
Website Client: The Optional message is not sent by email or PM when removing someone from a Guild

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8442]
## General Info

User Id: bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 42.0.2393.137
Windows 10 32-bit

## Description
When removing a member from a guild via the website client (not direct via the API), you have the option of sending an optional message. Despite text being typed into this message, the optional message is not sent either by PM or by email (Though you do receive an email, if attached to the account, stating you been removed from the guild).

There are no new console errors when removing member.

**Comment by lulock** [comment]
Hey!

So, I looked a little bit into this and it seems that the API call that is sent via the web-client always leaves out the message query when removing a member:

![image](https://cloud.githubusercontent.com/assets/8599836/23682302/752d6b18-03ac-11e7-8ce2-6b73a5b2f6ee.png)

The API expects something like `?message=get outta here` tagged at the end.

I just have to find where the web-client constructs this query, and I should be able to fix it ... **I'll take this on if no one else has claimed it yet!**

**Comment by Alys** [comment]
@lulock You're welcome to look into it - thanks! Comment here if you have questions.

I suspect however that the message should be in POST body parameters rather than in the query string. The messages could be long or contain punctuation or non-ascii characters, all of which could be troublesome in a URL query string. But it's entirely possible that the apidocs or the api itself don't describe or do that correctly!

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by cTheDragons** [comment]
I believe it still is, unless someone fixed the API and it is not implemented yet ? Notice the label been removed.

**Comment by lemoness** [comment]
I've updated the labels on this issue.
