### ISSUE TITLE
abstract the code that checks for a task belonging to a challenge or a group plan

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8452]
As described in [this comment from paglias](https://github.com/HabitRPG/habitica/pull/8427#issuecomment-274513364) the challenge and group plans code created in https://github.com/HabitRPG/habitica/pull/8427 should be abstracted to a static method inside the Task model, so that duplication of the code can be removed.

@lynxlynxlynx has offered to work on this (thank you!).

Once it's finished, work can proceed on https://github.com/HabitRPG/habitica/pull/8213, which also needs to check whether tasks belong to a challenge or group plan.

**Comment by librarianmage** [comment]
So once this issue is completed, I can continue working on #8213?

**Comment by Alys** [comment]
@MathWhiz Yes. :)

**Comment by lynxlynxlynx** [comment]
Ok, I'm back. These tests are just properties on the object find() and remove() use to filter. Since there's two of them and few uses, a wrapper doesn't make that much sense. I envision the function to simply append the extra property on call, before the filtering starts. Is that what you had in mind @paglias ?

**Comment by paglias** [comment]
Actually I was thinking to move the mongodb query (https://github.com/HabitRPG/habitica/pull/8427#issuecomment-274513364) to a variable and use it in all the places where it's necessary instead of copying the code around

**Comment by lynxlynxlynx** [comment]
Good idea, even cleaner.
