### ISSUE TITLE
Quest Items Show as Collected When Quest Has Not Started

### ISSUE THREAD

**Issue by AmberShards** [HabitRPG/habitica#8454]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 150f0919-c016-4617-a4c5-901c7fc44d58
  * Browser: Pale Moon 27.0.2 (FF branch)
  * OS: Mac OS X 10.9 (Mavericks)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

Quest items show as collected for a quest that has not started yet! I have accepted, but many others in the party are pending. 

http://www.intaligo.com/Habitica_quest_items.png

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
None seen.

**Comment by Alys** [comment]
That's intentional because if the quest starts before your next cron (i.e., before you start using Habitica tomorrow, in most cases), then those items will be applied to the quest.

By the way, we have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu or Guilds > Report a Bug from the mobile app. When you find a bug, you can start reporting it by putting a brief message there - just enough to explain the problem, optionally with a link to a screenshot from a file sharing or image sharing site if you think that helps. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. If an issue is needed, a moderator would advise you of that.
