### ISSUE TITLE
Model slows down under 500 tasks

### ISSUE THREAD

**Issue by yangit** [HabitRPG/habitica#846]
Run this from the console to add 500 tasks:

for (var i=0;i<500;i++) {
DERBY.app.model.set('_newHabit',Math.random());
$("form[data-task-type='habit'] input[type=submit]").click()
} 

And than try to click around some tasks.

**Comment by lefnire** [comment]
This actually makes sense, since we have so many dynamic bindings in the templates. We just need to cut back on dynamic bindings where possible. For example, if a TODO is in the "completed" list, it's bindings should be static.

**Comment by lefnire** [comment]
I'm thinking ahead towards Angular - which doesn't support static bindings. I wonder how we might cut back there, or if we don't need to (maybe bindings are more efficient than in Derby?). Static / Dynamic bindings is a pretty cool thing about Derby

**Comment by wizonesolutions** [comment]
In Meteor, the key is simply to avoid reacting unless we know we need to. So if you're building Trello in Meteor and someone goes to edit a card, the whole template doesn't need to refresh, only that card.

So I guess in Habit, whether the change occurred because of the API or because of user interaction, the Angular implementation should keep that in mind.
