### ISSUE TITLE
New checklist items are sometimes deleted when you click "Save and Close"

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#8488]
UUID: 7bde7864-ebc5-4ee2-a4b7-1070d464cdb0
Browser: Safari Version 10.0.1

### Description
Sometimes when I enter checklist items on a To-Do, often a new To-Do, they are erased when I click "Save and Close." This behavior has been happening for at least a week or two.  The To-Do itself is always saved.

**Comment by eastwood** [comment]
The only way I've managed to replicate this issue is by creating a TODO item and upon editing the issue (to add checkboxes), had my network connection hindered. Is this issue happening *all* the time or sporadically? Are you behind corporate proxy where DNS can be flaky (I know my work is). Can you replicate this with other browsers?

**Comment by lemoness** [comment]
This happens sporadically but regularly. I'd say roughly 1 in 5 times I add a checklist, this happens. I don't have any corporate proxies or anything like that, and my internet works without issue in other cases.

**Comment by SabreCat** [comment]
Likely Angular client issue. Placing on hold for frontend redesign.

**Comment by librarianmage** [comment]
Should this still be on hold?

**Comment by lemoness** [comment]
I haven't seen this issue since the redesign, so I'm closing this ticket!
