### ISSUE TITLE
Opening Edit modal causes task columns to widen

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitica#8490]
General Info
  * UUID: 8cce502f-a91c-40c2-b782-687759c6da0a
  * Browser: Firefox 51.0.1 (64-bit)
  * OS: Ubuntu 16.10

Posted in Report a Bug guild and directed by @Alys to post here. Every time I edit a task, the Habits column widens, causing the other columns to shift to the right. After I exit the edit modal, the width changes back.

My current screen resolution is 1366x768 and my browser window is maximized, but I've tested this using other window sizes, as well as on Windows through Chrome using both my husband's laptop (higher resolution) and my work computer (even higher), and the same issue occurs. 

Screenshot gif here: http://imgur.com/a/M413Y (note how the Habits column width widens and how the right edge of the Rewards column gets closer to the scrollbar).

EDIT: Now that I take another look, it seems like all the columns are widening since the right edge of the Habits column shifts a lot less than the right edge of the Rewards column (the Habits column was just the most noticeable since the left edge did not move).

**Comment by EYHN** [comment]
If set the ```<body>``` overflow:auto.I can fix it easily.

and set ```.modal``` overflow:auto,it looks good.
![image](https://cloud.githubusercontent.com/assets/13579374/23108311/9c1ec766-f746-11e6-99ad-d7a0a4980c43.png)


But the page height is too short, there will be two scroll bars
![image](https://cloud.githubusercontent.com/assets/13579374/23108296/4de6ae60-f746-11e6-93aa-368149557d16.png)

**Comment by mandyzhou** [comment]
Just as an update, it looks like this is happening for all modals I've encountered, not just the Edit modal.

**Comment by EYHN** [comment]
When a modal is turned on,the body's scroll bar is hidden

**Comment by beejunk** [comment]
This is kind of a tricky one. The body scrollbar is purposefully being hidden when the modal is open in order to avoid the double-scrollbar issue. This is causing the responsive design to widen to the new width.

One option is to permanently remove the body scrollbar and add another one somewhere else in the main app window. This is made a little tricky by the fixed positioning of the navbar and headers. One quick-and-dirty approach is to:

1. Change the body to overflow:hidden.
2. Remove the top padding from the header-wrap div (which is being used to push it under the navbar).
3. Add a top margin to the ng-scope div that is the same as the previous header-wrap padding. Then change the ng-scope height to 100% and add overflow:scroll.

This results in a main window that looks like this, with the scrollbar being positioned just underneath the navbar:

![habitica_8490-1](https://cloud.githubusercontent.com/assets/798619/23343557/17c6ef42-fc33-11e6-9d5c-a202dff1960a.png)

Here's what it looks like with an open modal:

![habitica_8490-2](https://cloud.githubusercontent.com/assets/798619/23343573/4b44f120-fc33-11e6-81c3-3cf21f6bae0c.png)

The columns do not widen because there are still two scrollbars here, but the modal scrollbar is overlapping the main window scrollbar since neither are attached to the body element.

This is just an example done with the Firefox DOM inspector; I'd have to spend some time looking through the code to see how to implement this in a proper way.

**Comment by beejunk** [comment]
I fiddled around with this a bit, and my previous suggestion does not work very well. It causes odd visual artifacts when loading, and requires a few additional fixes to work with smaller screens. It also pushes the footer off the bottom of the screen in a way that's not so straightforward to work around.

EDIT: It also caused the party header to scroll off the window, so definitely a no go.

**Comment by SabreCat** [comment]
Client issue. Putting on hold until after the redesign.

**Comment by librarianmage** [comment]
This doesn't happen anymore, as far as I can tell, so should it be closed?

**Comment by SabreCat** [comment]
Yup! Thanks for doing this old-issue hunting, btw @MathWhiz, much appreciated!

**Comment by librarianmage** [comment]
No problem! With such a large core base being around so long, it's easy for
stuff to sink to the bottom.
