### ISSUE TITLE
API Issue: user/change-class doesn't validate class listed

### ISSUE THREAD

**Issue by madpink** [HabitRPG/habitica#8496]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID:  b0413351-405f-416f-8787-947ec1c85199

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

If the class given as a parameter is invalid in an API call, a success is still returned

for example:
`user/change-class?class=cellist`

will still return:
`{"success":true,"data":{etc...}}`
(although the class will still remain the same as it was)

**Comment by lulock** [comment]
Hey! I'm new here, and would like to contribute to this :)

**Comment by Alys** [comment]
@lulock Thank you! Please go ahead! Comment here if you have questions or run into trouble.

**Comment by lulock** [comment]
Hey, @Alys and @madpink !

So I've spent quite a bit of time navigating the source code for this project and have gotten acquainted with the website itself both locally and deployed. I've managed to recreate the issue here with an API call, but the behaviour I noticed was the following:

- An API call to change to a valid class will return with success and will re-assign the class correctly as well as re-allocate class-attribute points. 
- An API call to change to an INVALID class (like cellist), however, will return with success and the return object will specify that the class is unchanged, but the next check-in will prompt the user to choose a class and re-allocate all their points again. 

Here is a screen shot of the prompt after specifying **_user/change-class?class=cellist_**:

![image](https://cloud.githubusercontent.com/assets/8599836/23457326/df36908c-fe90-11e6-82a6-b57a7362b16a.png)

And the line of code that does this is shown in the conditional on **line 15** and the subsequent else block:
![image](https://cloud.githubusercontent.com/assets/8599836/23457338/e8cb18e8-fe90-11e6-8f04-3c26f437f829.png)

My question is: what is the desired behaviour here? Is it okay for the user to be prompted to choose a class when an invalid class is requested, or should a badRequest be returned, and re-allocation of points be denied?

Thanks in advance!

**Comment by Alys** [comment]
@lulock Thank you for looking into that in detail!

If the user specifies an invalid class, an error should be thrown and no change should be made. 

However it's still okay for the user to specify that they want no class and then be opted out of the class system.
