### ISSUE TITLE
Losing Health Steadily ... for unknown reasons? 

### ISSUE THREAD

**Issue by illuscat** [HabitRPG/habitica#8498]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 45cab1d6-0a6a-453f-8a46-a2a807b803ef 
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
Lately, my avatar health has been steadily decreasing ... despite the fact that I have checked off all my dailies and have had no negative habit action. Also, my party is NOT on a quest (although there's a pending invite). 

Throughout the day, I've lost a good 15 points in health. I'm not sure why? It's possible that this has been happening for a while, as I've been losing health for a while and just assumed that it was my fault. 

It does make the game exciting -- I can say that! 
Thanks in advance for helping think through what might be happening... 

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
This is most likely a local problem with your account (e.g., missing Dailies that are hidden by a tag) or your browser or computer (e.g., an extension or other third party tool that's subtracting health) since we haven't seen other reports of it. I've seen that you've also reported this in the Report a Bug guild, which is the best place for initial reports of bugs, so I'll keep helping you there. The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.

**Comment by illuscat** [comment]
Thanks! I'm sorry for the double-post.
