### ISSUE TITLE
Quest Acceptance Not Updating in Vivaldi

### ISSUE THREAD

**Issue by jtgithub2016** [HabitRPG/habitica#8499]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: e44e6069-2e30-49cf-ab49-db41d3134045
  * Browser: Vivaldi
  * OS: Windows 7

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
I'm using Habitica on Vivaldi, on a Windows 7 PC.  Party members often accept a task, but they still show in the website as "pending," even though they are updated in the Android app, and even though I hit "refresh" and/or complete additional habits/dailies/or Todos.

I generally need to log out and log back in to get the website to refresh in a timely fashion.  I am also located in mainland China - I don't know if the Great Firewall affects this.

![image](https://cloud.githubusercontent.com/assets/18677807/23114225/b778d4de-f778-11e6-8326-70af3db0793a.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
Logging out and logging back in shouldn't be necessary. It should be enough to reload the website using your browser's reload or refresh button. I use Vivaldi and I've just tested and that works for me.

When you said "even though I hit "refresh"" were you talking about your browser's refresh / reload button? Or were you referring to Habitica's sync button on the top right of the website? The sync button isn't meant to sync party details because it's just for your own data (that allows the sync of your data to happen more quickly). Similarly, completing tasks won't cause new party data to be loaded.

A normal firewall won't affect this; it will either block the whole site or none of it. However if China uses other kinds of interference (e.g., slowing down network connectivity intermittently), it's possible that sometimes a reload might not load party data, although in that case I'd expect the party page to not show any party information at all. I doubt that the Firewall is involved.

I'm going to close this because I'm guessing that reloading the party page will work for you since it does for me, however if you're sure it doesn't comment here.

We have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu or Guilds > Report a Bug from the mobile app. When you find a bug, you can start reporting it by putting a brief message there - just enough to explain the problem, optionally with a link to a screenshot from a file sharing or image sharing site if you think that helps. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. If an issue is needed, a moderator would advise you of that.
