### ISSUE TITLE
Split pixels in avatar/mount templates relative to backgrounds

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8501]
General Info
  * UUID: 9fe7183a-4b79-4c15-9629-a1aee3873390
  * Browser: Firefox 51.0.1 (32-bit)
  * OS: Windows 10

### Description

Avatar/mount templates seem to split pixels (due to 3x size where each pixel is upsized to 3x3 pixels for sprites) relative to backgrounds. Backgrounds do not appear to be the cause of the issue, after testing of many backgrounds. Many Gen 1 mounts also appear to have split pixels relative to the avatar template. This does not appear to be an issue with quest mounts.

Pets do not appear to have alignment issues with the backgrounds.

If this is an issue with the sprite files themselves (it appears to be for the flying pig at least? There is only a 2-pixel space where it should be 3 between the right edge of the wing and the edge of the template, as tricksy.fox has pointed out in Pixels in Progress) then Artisans may be able to help!

Example screenshots: 

Avatar alone: 

![split pixels2](https://cloud.githubusercontent.com/assets/9218855/23186718/ed869c54-f83c-11e6-8429-06013a1f66cc.png)

![split pixels3](https://cloud.githubusercontent.com/assets/9218855/23186727/f541e930-f83c-11e6-91a7-fdf1c138dfb4.png)

Gen 1 Mounts: 

Wolf does not split pixels relative to avatar, but does relative to background:
![split pixels4](https://cloud.githubusercontent.com/assets/9218855/23186744/01497f2c-f83d-11e6-889b-7b8d0a291b91.png)

The following mounts do split pixels relative to the avatar AND the background.
![split pixels](https://cloud.githubusercontent.com/assets/9218855/23186760/0ce78c5c-f83d-11e6-9308-5bb330436175.png)

![split pixels6](https://cloud.githubusercontent.com/assets/9218855/23186749/04de3498-f83d-11e6-9993-b830799332a2.png)

Quest Mounts (split pixels relative to background but not to avatar)

![split pixels5](https://cloud.githubusercontent.com/assets/9218855/23186780/1d9a4ca6-f83d-11e6-81bf-dadf041f0674.png)

![split pixels7](https://cloud.githubusercontent.com/assets/9218855/23186781/21635936-f83d-11e6-9fa2-2215d2618c99.png)

**Comment by tricksyfox** [comment]
So I think it's been mentioned somewhere at some point before, but I think some of the backgrounds are splitting not because they are split in regard to their own grid (whereas the flying pig, for example, has splits relative to itself), but because of the "expand to 3x and remove one row of pixels from the side" rule in creating backgrounds. It's not, to my knowledge, clearly specified which single line of pixels should be removed, so if artists are inconsistent, things won't always line up, and can be off by one row, column, neither, or both, depending on which they picked.

**Comment by SabreCat** [comment]
I've noticed this too. If a critter splits pixels relative to the avatar, it's likely a problem with the pet/mount; if the avatar doesn't line up on the background grid, that suggests it's a problem with the background.

**Comment by beffymaroo** [comment]
If there's an issue with background alignment relative to the avatar template, that must be true for every background, since I haven't found one that doesn't have this issue yet after testing 20+ . The splits also seem pretty consistent from one to another, though this is difficult to be precise about.

**Comment by tricksyfox** [comment]
Looks like the backgrounds all need to move one pixel down and to the right, whereas the splitting mounts, as far as I recall, all need to move one pixel up and to the left.

If I recall correctly, the only gen 1 mount that's splitting is the flying pig. At least, that's the only one I remember having to move. I noticed when I was making the glow mounts because of the border, and with the pig I didn't have enough space.

**Comment by khipkin** [comment]
What does "splits pixels" mean?

**Comment by SabreCat** [comment]
@khipkin: Habitica's sprites use a 3x scale. To produce the pixelated look of the images on the site, you take a tiny image
![image](https://cloud.githubusercontent.com/assets/4501321/23372186/3af6e7c6-fce0-11e6-8780-8193f4ac844e.png)
and scale it up to three times its size without any interpolation:
![image](https://cloud.githubusercontent.com/assets/4501321/23372218/51a541fc-fce0-11e6-8bb9-417ba96cc2d9.png)

In order for this effect to look consistent across the site, however, all images need to be lined up such that these 3x pixels (I like to call them "chunky pixels," hehe) perfectly overlap one another when layered. If two sprites are misaligned such that when placed atop one another, there's a one- or two-pixel gap in places instead of the proper 0 or 3, they're said to "split pixels".

Maybe the easiest examples to see above are in the middle series, the avatar riding a cotton candy blue wolf / white flying pig / base tiger / cotton candy blue penguin. Look at the space between the avatar's Horned Helm and the tree on the left, where you can see the pink cherry-blossom background. The gap is only 1 pixel wide. If everything lined up correctly, there would be no gap there leaving the Helm flush with the tree bark, or there would be an amount of cherry blossom visible equivalent in size to the black dot in the avatar's eye.

**Comment by khipkin** [comment]
OH! I see what you mean! Thanks for explaining it. :blush:

**Comment by SabreCat** [comment]
This runs a bit deeper than just needing to scoot the backgrounds around a bit--even the background _template_ is wrong. Backgrounds are currently 140x147, which is evenly divisible by 3 vertically, but not horizontally. I fear they would all need to be updated to a more fitting size (go square, 147x147?) to fix this long-term.

**Comment by tricksyfox** [comment]
Yikes! How complex!

Right now the pixel artists are instructed to do the art on a 47x49 canvas, export at 3x, and then shave off a pixel so it's 140x147. Does anybody know why this came to be? Because 141x147 (while not square) IS divisible by 3.

It also looks like there's an issue with the templates on the pixel art trello -- I just downloaded the bg templates, and the one with the mount and the one with the mount AND pet are both 47x49, but the one with just the avatar is 70x50. So I imagine that could have thrown some of the proportions off at some point or another for a few of them, if somebody used that template and not the other two.

**Comment by lemoness** [comment]
We're internally fixing this bit by bit, so I'm closing this ticket.
