### ISSUE TITLE
API Issue: user/unlock allows purchase of unavailable items

### ISSUE THREAD

**Issue by madpink** [HabitRPG/habitica#8505]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID:  b0413351-405f-416f-8787-947ec1c85199

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

Seasonal items that are unavailable at a certain time can still be purchased using user/unlock. For example, Halloween skins

**Comment by Alys** [comment]
I've marked this as suggestion-discussion so that we can talk about the best way to fix it. We'll always need to have dates manually specified somewhere because the exact start and end dates for each item varies each year, but the API should obey those dates - currently it looks like only the website obeys them (and the mobile apps?). I guess ideally we'd make the API return something useful about whether each item should be available and then the website and apps would automatically show/hide them based on that.

**Comment by Alys** [comment]
I'm closing this in favour of https://github.com/HabitRPG/habitica/issues/9697 which is for a generic fix for a range of similar problems.
