### ISSUE TITLE
Please delete account

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#8568]
Please see email to Alys regarding account issue

**Comment by Alys** [comment]
Can you please log in to the Habitica website using the account you want deleted and go to Help > Report a Bug, and post there something simple like "please delete this account". Even though it's not strictly a bug, that's the best place to post because it needs admin assistance. We'll be able to use your post to find your account and we'll then delete it. Another benefit of posting there is that it gives us proof of ownership of the account, which is essential before we can delete it.

**Comment by ghost** [comment]
Hi,

I have just gone back to habitica on my pc but the account is still there.

**Comment by Alys** [comment]
Yes, I haven't deleted it yet. Please post to that guild that I described in my email to you - the one that you reach by going to Help > Report a Bug. I need you to post there so that I can see which Habitica account is yours and so that I can have proof that the person asking for it to be deleted is the person who owns it - I'm sorry about that, but proof of ownership is our standard practice before deleting accounts to ensure the privacy and security of all our users. There are other ways of telling me which account is yours and proving you own it, but posting to that guild is the easiest.

**Comment by ghost** [comment]
I have posted there and received an email to say the case had been closed,
so i assumed it had been deleted.

On 14 Mar 2017 07:40, "Alys" <notifications@github.com> wrote:

Yes, I haven't deleted it yet. Please post to that guild that I described
in my email to you - the one that you reach by going to Help > Report a
Bug. I need you to post there so that I can see which Habitica account is
yours and so that I can have proof that the person asking for it to be
deleted is the person who owns it - I'm sorry about that, but proof of
ownership is our standard practice before deleting accounts to ensure the
privacy and security of all our users. There are other ways of telling me
which account is yours and proving you own it, but posting to that guild is
the easiest.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HabitRPG/habitica/issues/8568#issuecomment-286344643>,
or mute the thread

**Comment by ghost** [comment]
I have posted another message there now.

Thanks
