### ISSUE TITLE
Subscription popup is too narrow in Japanese

### ISSUE THREAD

**Issue by Yutsuten** [HabitRPG/habitica#8581]
General Info
  * UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a
  * Browser: Chromium 56.0.2924.76
  * OS: Ubuntu 16.04 (64-bit)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
As I changed my user language to Japanese (Settings -> Site -> Language -> 日本語), I noticed that the text of the subscription button popup is near illegible.
Here an image showing how it appears:

![Image of bug](http://i.imgur.com/upJiQvF.jpg)

I would like to try resolving this bug myself, may I? I already have set up habitica locally.
I'm starting now so tips are very welcome.

(I searched on the current issues but didn't find anything about this, sorry if it is a known issue...)

**Comment by Alys** [comment]
We're part way through a process to redesign the website's front-end code but I think this is definitely worth fixing now because the way it behaves is completely unhelpful to anyone considering a subscription! @mateus-etto Thank you for reporting it and yes, please do start working on it!

In case it's relevant and you're not aware yet, we use [Stylus](http://learnboost.github.io/stylus/) for our CSS code.

Comment here if you run into any problems or have any questions.
