### ISSUE TITLE
To-Dos with checked-off checklist items turn red faster

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8590]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

If a To-Do has checklist items marked off, its task value changes faster than To-Dos with no checklist or with checklists that have no accomplished items.

To reproduce in debug mode:

1. Create several To-Dos.
2. Add checklists to some of them.
3. On some of the To-Dos with checklists, check off one or more items.
4. Advance the day using the debug buttons and sync. To-Dos with accomplished checklist items turn orange immediately, while those without stay yellow.

While a relatively innocuous issue, this is strange behavior that doesn't strike me as intentional. Why should partly-done To-Dos be treated differently than any other To-Do when it comes to cron aging?

**Comment by Moniarchy** [comment]
I would like to help with this. :)

**Comment by Alys** [comment]
@Moniarchy Thank you! Comment here if you have questions.

**Comment by librarianmage** [comment]
@Moniarchy Are you still working on this?

**Comment by Moniarchy** [comment]
@MathWhiz Yes, I totally forgot about it. Going to get some work on it today.

**Comment by lemoness** [comment]
@Moniarchy - Hi there! Just checking -- what's the status of this?

**Comment by lemoness** [comment]
This is now open for someone to work on again!

**Comment by asharma0703** [comment]
It looks like it was intentional, although I'm not sure of the reason:

https://github.com/HabitRPG/habitica/blob/e5d834b40aa4407ab8603dc911e94e052d15174a/website/common/script/ops/scoreTask.js#L41-L45

https://github.com/HabitRPG/habitica/blob/e5d834b40aa4407ab8603dc911e94e052d15174a/website/common/script/ops/scoreTask.js#L79-L82

Seems like deleting these snippets would solve this.

**Comment by Alys** [comment]
Ah! Good work on finding that. I'd guess that you're right that that code is causing this bug. However... 

All this is from memory so anyone who acts on it would want to first check the code to make sure I'm right. :)

I believe those snippets are also what causes a To-Do to earn you more XP and Gold when the player completes the To-Do if it contained completed checklist items. We definitely still want that behaviour. We also want those increases to be nearly exactly reversed if the player uncompletes the To-Do (e.g., if they realised that they marked the wrong one as completed).

Cron likely uses the same code to redden incomplete To-Dos, and you're right that we don't want completed checklist items to be considered in that case. Perhaps instead of removing those snippets, we could add to the `if` statement so that that code is executed only when cron is not running (the `cron` variable should help with that).

**Comment by asharma0703** [comment]
Oh, that makes sense. Didn't know the task value was used for anything besides color. I'd be happy to put a PR after I figure out all the local setup.

**Comment by Alys** [comment]
@ashaindlin Cool, thanks! Let us know if you need help with the local install.

**Comment by beffymaroo** [comment]
@asharma0703 Are you still working on this issue? Please check in when you have a moment and let us know. Thank you!

**Comment by asharma0703** [comment]
@beffymaroo Hi! I ran into a roadblock while doing local setup earlier and posted in the Aspiring Blacksmiths group but didn't get an answer. I'm still happy to work on it, but I want to get fully setup locally first and haven't been able to so far.

**Comment by SabreCat** [comment]
@asharma0703: hmm, I'm sorry the Blacksmiths weren't able to help! I'd definitely follow up there and see if anyone can chime in on your issue after a second ping. In the meantime, though, I'll free this issue up.
