### ISSUE TITLE
Orb of Rebirth still visible after rebirth + reload of website

### ISSUE THREAD

**Issue by Lalaitha** [HabitRPG/habitica#8593]
Yesterday when I used the Orb of Rebirth, I noticed it was still visible (and set to cost 6 gems) in the Market - even after reloading the website multiple times.

Just checked again, to be sure - and the Orb is still visible in the Market.

Browser used: Google Chrome (checked using Microsoft Edge as well).
OS: Windows.

**Comment by Yutsuten** [comment]
I have this issue too... May I work on it?

**Comment by Yutsuten** [comment]
I will work on this issue now. When I fix it, I'll create a PR.

**Comment by Alys** [comment]
Ah, I'm sorry, I meant to comment on the weekend. :(

I've realised this is actually intentional because the Orb of Rebirth is set to be unlocked if you reach level 50 OR if you have the Beast Master achievement (http://habitica.wikia.com/wiki/Orb_of_Rebirth ), however that was set up a long time ago when we didn't have other features like the Key to the Kennels for releasing pets.

We often see Socialites telling users that Rebirth becomes available at level 50 without mentioning the Beast Master achievement, and I've never realised/remembered that they were giving incomplete information. I also didn't remember about Beast Master when I asked Lalaitha to log this issue. 

In my admittedly biased opinion, it feels that the link between Beast Master and the Orb of Rebirth no longer makes sense. When you achieve Beast Master, you unlock the Key to the Kennels, and I don't think you need to unlock Rebirth as well.

@lemoness is it okay if we stop making Beast Master a trigger to unlock Rebirth?

**Comment by Yutsuten** [comment]
No problem @Alys .
I'll wait for more informations before continuing.

**Comment by Lalaitha** [comment]
Oh, I wasn't aware of that - strange enough, since I've looked at that wiki page a lot of times. Interesting information.

**Comment by Alys** [comment]
@Lalaitha You and me both. And I've even worked on the code for Rebirth in the past!  :)

**Comment by SabreCat** [comment]
I would be fine with removing the Beast Master unlock. Simplification!

**Comment by Alys** [comment]
@lemoness says she also had forgotten that Beast Master unlocks Rebirth.:) This is clearly a feature we no longer want!

@Yutsuten please go ahead. The change we want is that the Beast Master achievement should no longer unlock the Orb of Rebirth. Thank you!

**Comment by Yutsuten** [comment]
@Alys I found that the Orb of Rebirth is enabled at ``website/common/script/fns/updateStats.js``, lines 97-100:

``` JavaScript
if (!user.flags.rebirthEnabled && (user.stats.lvl >= 50 || user.achievements.beastMaster)) {
  user.addNotification('REBIRTH_ENABLED');
  user.flags.rebirthEnabled = true;
}

```

I removed the ``user.achievements.beastMaster`` verification, so future users that receive the Beat Master achievement won't be allowed to buy the Orb of Rebirth.

But the users which already have the ``rebirthEnabled`` changed to true, the Orb of Rebirth will continue appearing in the market.

Is this solution enough?

**Comment by Alys** [comment]
@Yutsuten Yes, that's fine. We won't worry about the users who already have it enabled. Turning it off would provoke questions and there's no real need. Thank you!

**Comment by Alys** [comment]
This is still happening so I'm reopening it. The problem is that some of the code linking Rebirth to Beastmaster has not been removed - below is a list but there might be more as well.

Whoever works on this should test by getting an account on their local install to have Beastmaster (see the Debug menu for an option to make that easy), then use Rebirth, then ensure that Rebirth is not still enabled.

test/common/ops/rebirth.js
```
  it('does not reset rebirthEnabled if user has beastMaster', () => {
    user.achievements.beastMaster = 1;
    user.flags.rebirthEnabled = true;

    rebirth(user);

    expect(user.flags.rebirthEnabled).to.be.true;
  });
```

website/common/script/ops/rebirth.js
```
  if (!user.achievements.beastMaster) {
    flags.rebirthEnabled = false;
  }
```

**Comment by pineapple-joe** [comment]
Hey, may I work on this one?

**Comment by Alys** [comment]
@borisabramovich86 yes, thank you! Comment here if you have questions.

**Comment by Alys** [comment]
@borisabramovich86 Note though that the [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) instructions and related wiki pages haven't yet been updated for the new website and if you follow them exactly as written, your local install won't work. If you need help with that before we update them, comment here or ask for help in the Aspiring Blacksmiths guild (there's already some posts there that might help).

**Comment by pineapple-joe** [comment]
If you can give me some pointers on setting up the new site, I would appreciate it. It would speed things up :)
Also, I can't find those posts you mentioned, if you can add a link here.
(The Aspiring Blacksmiths link just leads me to the new site)
https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f

Thanks!

**Comment by Alys** [comment]
URLs have changed now that the new website is live. You can find the Aspiring Blacksmiths guild in the guild list. We'll be updating the wiki when we can.

**Comment by pineapple-joe** [comment]
Hey, I finally managed to get my local copy working! :)
I got some questions:

1. I can't see the enable BeastMaster in debug Menu.
Can I manually activate it in the DB? 
or is there additional functionality?

2. Also, the level up in the debug menu is not working for me.
I tried setting my level to 50 in the DB, but I don't see the Orb of Rebirth in Market.

3. I understand the test scenario is:
- Enable Beastmaster
- Set level 50, use orb of rebirth
- See that rebirth is no available afterwards. (Orb is not available?)

is there more?

Thanks!

**Comment by Alys** [comment]
@borisabramovich86 If you give yourself all the pets using the debug menu, you'll get the beastmaster achievement (although you might need to give yourself all but one pet and then hatch the final pet normally to trigger the achievement). It's probably simpler to use a database update command to set the achievement manually - look in the Blacksmiths documents on the wiki for information about doing database updates. This is what you want to set: `achievements.beastMaster` and you give it a `true` value.

You can set level 50 at User Icon > Settings > [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values). Click a Habit or complete a task after that to trigger all the things that normally happen after leveling up.

Your test steps in point 3 seem correct to me.
