### ISSUE TITLE
New Achievement and Badge: Invited a Friend

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8615]
A new achievement and badge are ready to be implemented! This should be received when a player invites a friend to Habitica, and that friend becomes an active user. The badge image and the name/mouseover text for the user achievement page can be found here: 

https://trello.com/c/46zdTjUc/10-invited-a-friend-badge

**Comment by Vampitch** [comment]
So exciting! I'm sorry for bringing this up, will previously referred active accounts somehow count for this? Thank you!

**Comment by Alys** [comment]
We do backdate achievements whenever possible but I think that in this particular case, it will unfortunately not be possible. Once a party invitation has been accepted, there's no trace of it left in Habitica and so no way for us to reliably tell who should get the achievement.

This won't be a problem after this new feature goes live because the code that handles the acceptance can award the achievement.

**Comment by kvsm** [comment]
Can I pick this one up?

**Comment by Alys** [comment]
Yes, thank you!
