### ISSUE TITLE
New Achievements and Badges: Checked in X Days in a Row

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8617]
These new achievements and badges are ready to be implemented! These should be received when a player checks in for the number of days indicated by each badge. The badge images and the names/mouseover text for the user achievement page can be found here: 

https://trello.com/c/uxR0r5R0/5-checked-in-x-days-in-a-row-badges

**Comment by Crizzooo** [comment]
I haven't worked on this project before, but the idea is intriguing and this issue sounds like something I can figure out. 

Can I check this out as a possible first PR?

**Comment by Alys** [comment]
@Crizzooo Sure! Thank you! Commen here if you have questions or run into problems.

**Comment by Crizzooo** [comment]
Hey @Alys, just got started reading through source code and am trying to figure out where to start looking to implementing this Badge and the repeated check in functionality.

Do you have any resources or guidance regarding the architecture and getting started on this PR?

**Comment by Alys** [comment]
@Crizzooo Achievements are defined in `website/common/script/content/achievements.js` and you can also use `git grep` to search through the code base for other code related to them. The Perfect Day achievement would be a great one to look at because it's assigned by cron, which will also be how this new achievement is assigned. Try `git grep -i "perfect day"`

This new achievement is awarded for using Habitica for a certain number of days in a row. From a technical perspective, that means that you're checking to see if cron has run for a certain number of days in a row. So each time cron runs, it could check to see if the user already has the achievement and if not, then it works out how many days in a row the user has cronned. We actually already store data that can be used for that - each time cron runs, it updates the user's `history.todos` and `history.exp` arrays, and they contain the date and time that cron ran (in UTC).

**Comment by librarianmage** [comment]
@Crizzooo Are you still working on this?

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by TNychka** [comment]
Hey! I can take a look at this!

**Comment by saraolson** [comment]
Staff are looking at implementing new user achievements, so we're putting this issue on hold for now.

**Comment by veeeeeee** [comment]
We are now tracking these somewhere else to ensure proper handling.
