### ISSUE TITLE
New Achievements and Badges: Hatched X Pets

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8620]
These new achievements and badges are ready to be implemented! These should be received when a player hatches the number of pets indicated by each badge. The badge images and the names/mouseover text for the user achievement page can be found here: 

https://trello.com/c/bLEQxYax/12-hatched-x-pets-badges

**Comment by corinnaj** [comment]
@beffymaroo If no one is working on this yet, I'd like to give it a try :)

**Comment by Alys** [comment]
@corinnaj Go for it! Thank you!

**Comment by corinnaj** [comment]
@alys Hi again :) I have a question: As far as I understand I need to put the sprites of the badges into one of the sprites maps and then reference them in the according css file, to be able to use them on the website. Where should I put them? All of the other achievements seem to be on "spritesmith-main-0.css" but there isn't really any space left.

**Comment by khipkin** [comment]
@corinnaj From [Guidance For Blacksmiths' "Images" section](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths):

> Most images will need to be copied into suitable subdirectories under `common/img/sprites`.

> After adding new images or new versions of existing images, run `npm run sprites` to recompile the image spritesheets.

> Sometimes, this command will result in a new spritesheet being created, in which case use `git add` to add the new files. You will find them under `common/dist/sprites`. (Look for a *.png and *.css file for each spritesheet.)

**Comment by corinnaj** [comment]
@khipkin Thanks! That worked perfectly

**Comment by guyguy2001** [comment]
Are you still on it? If not, could I continue from where you left? I want to check whether or not bugs that happen in my mount achievement will also happen in yours (and from there why they happen in the first place). But if not, I have some formatting notes I got after working on mine:
- in pets.json you can use <%= count %> to track how many pets you hatched
- in schema.js- it would probably be easier (and safer) to track the achievement as a number and not a boolean.
- instead of multiple simple achievemts, I used a multiIconed plural achievement, which probably fits better. Please copy that section from me or, if you create your own, I will use yours

**Comment by corinnaj** [comment]
I am really sorry, Uni started again and I suddenly had a lot more to do than I thought... Please go ahead, you can use anything I already did, if you like :)

**Comment by guyguy2001** [comment]
Just like I said, I merged this with the mount achievements, and then, as I described in #8619, I quit it, but now all that remains in both is identical (except for tiny differences in calculations, like the fact that every triad bingo is 180 pets and not 90), and solving one will solve the other. So, if you'd like to contribute to this achievement, look at my large comment in #8619 to see what needs to be done and take my repo.

However, I believe this issue should be closed, and the name of #8619 should be changed to "New Achievements and Badges: Hatched X Pets, And Grew X Mounts", because of the fact they are identical and exists together in a single fork.

**Comment by Alys** [comment]
@guyguy2001 Good points, thanks! I'll put this on hold and mention it in  #8619 and we will close this if the PR for that fixes both.

**Comment by librarianmage** [comment]
This doesn't need to be on hold, right?

**Comment by LunarGem** [comment]
Nope, and it's not. I'm working on it! (Mostly from the other issue, where it's easier to implement them both at once..)

**Comment by lemoness** [comment]
I'm updating the labels on this issue. 

@LunarGem Thanks for tackling this!

**Comment by lemoness** [comment]
@LunarGem - Hi there! Just checking in -- what's the status of this?

**Comment by LunarGem** [comment]
I've made enough progress on this that I'd like to keep it, but my dev computer threw a tantrum and I have to do reinstalls on all of my dev software. I'm also a high school senior attempting to graduate, so most of my energy is there (and coping with an LD) but over the break I'll probably make more progress. I've gotten to the part where I actually award the achievement, unfortunately, that's the hard part. 😛

**Comment by Alys** [comment]
@LunarGem No worries, it's still yours. Good luck with your computer and exams! Post here if you have questions about awarding the achievement.

**Comment by beffymaroo** [comment]
@LunarGem Checking in about the status of this issue! Let us know if you're still planning to work with it. Thank you. :)

**Comment by LunarGem** [comment]
Yeah, sorry, still graduating... And my keyboard has developed an issue... But I'm getting a new computer for college so...? I'll try to move forward on this but unfortunately no guarantees. (I feel terrible for not keeping my promises here... ☹️ ).

**Comment by beffymaroo** [comment]
@LunarGem That's OK! If you don't think you'll be able to get to this within the month I can change it back to "Help Wanted" status, and if no one claims it before you have time to work on it, you can certainly claim it again! Let me know.

**Comment by TNychka** [comment]
Hey! I can take a look at this!

**Comment by saraolson** [comment]
Staff are looking at implementing new user achievements, so we're putting this issue on hold for now.

**Comment by veeeeeee** [comment]
We are now tracking these somewhere else to ensure proper handling.
