### ISSUE TITLE
Double cron run in a single day

### ISSUE THREAD

**Issue by LoganBarnett** [HabitRPG/habitica#8665]
General Info
  * UUID: b8edbaae-561a-4e78-a4c2-8d39ff4a777c
  * Browser: Chrome
  * OS: Windows 10, Windows 7, Ubuntu 15.10, Android Oxygen OS 4.0.3

My party-mate has run into an issue where it seems to be triggering multiple crons in a day (which has caused a loss of levels and such - I've repaired the data).

c.rayon is the user with the problem in the screenshot below.

![habitica-double-cron-01](https://cloud.githubusercontent.com/assets/27005/24924391/74d24a90-1ea9-11e7-8206-ac0d37ca7acb.png)

I don't know if this issue is specific to the web or android client - my friend uses Android mostly but not exclusively.

If it helps, she transitioned time zones last month (a return trip - so two time zone transitions). Each time the custom day start was changed. We noticed the cron only runs when she logs on typically, but for me it runs at the custom day start time. For whatever reason today it ran at her custom day time plus the moment she logged in for the first time in the day.

Some (closed) but seemingly related issues: #6959 #6899 #5919 

Thanks for any help, and awesome app!

**Comment by Alys** [comment]
Please ask her to post to the Report a Bug guild from the Habitica website's Help menu (or from Guilds > Public Guilds on the mobile app). We can see her account from there which will make it easy to troubleshoot this and her posting there also makes it clear that she doesn't mind us looking into her account.

I'm closing this issue now because this will almost certainly be something simple like her using Habitica for the first time not long before her Custom Day Start time and then again after, but if it turns out to be a bug I'll reopen this issue and add all the technical details we'll need to resolve it.

Cron is supposed to run when you first use Habitica each day (after your Custom Day Start time). The only time it will run at exactly the CDS time is if you happen to be using Habitica exactly then, or if a third-party tool is using Habitica on your behalf, or if the website happens to reload exactly then.

Just so you know for any future problems, most bugs can be handled quickly the in that guild. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.

**Comment by LoganBarnett** [comment]
Just wanted to follow up with this for posterity: I found out later my friend had changed her custom cron time that day or the day before. The exact time it was set to and when it was set is not something I recall, but definitely seems related. She hasn't seen the issue again (about two weeks since filing the ticket).

**Comment by Alys** [comment]
Thanks @LoganBarnett! That explains it. When you change your Custom Date Start time, it is possible for cron to run again the same day. However the feature that lets you change the time always warns you about the earliest possible time your next cron will run, and if that time doesn't suit you then it lets you cancel the change. If she changes it again, it's important to check the time in the confirmation step. If she goes through with the change and then cron runs earlier than the time she was warned about, she should post to the Report a Bug guild, ideally with a screenshot of the warning message (although of course she'd need to take the screenshot before she knew if there was going to be a problem).
