### ISSUE TITLE
Account suspended/blocked error lacks detail; lead to hanging website on refresh

### ISSUE THREAD

**Issue by rhdsmnd** [HabitRPG/habitica#8672]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 54d0305c-fbc0-4fe8-a941-948204625f08
  * Browser: Firefox 52.0.2
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When a user is logged in and they become blocked (i.e. the "auth.blocked" property becomes set to "true"), a refresh of the page causes the website to hang on the loading screen.  Screenshot is below.

Related to this (I think) is a block of code in website/client-old/js/config.js (line 84-87) that never runs due to the response.data object from the server never having a "code" property (legacy?).  I added a console.log statement which you can see in the screenshot (returned response.data object is in the bottom right pane).  As you can see, there is no way to determine that the error is an account suspended error unless you look at the locale-dependent message.

![githubissue](https://cloud.githubusercontent.com/assets/5566652/25028779/b5029976-206b-11e7-93c4-cd2a0eac9773.PNG)

I think the easiest/concise/maintainable way to fix this would be to extend the "NotAuthorized" class with an "AccountSuspended" class (website/common/script/libs/errors.js).  Editing the "NotAuthorized" class would be relatively difficult because the constructor only accepts a string, and we probably don't want to mess with the constructor or do weird hacky logic with message.  I think it also makes sense from an abstraction standpoint; an AccountSuspended error is an extension of a NotAuthorized error, and there is already logic in config.js that is supposed to handle the specific case of a suspended account.  I.e. something like:

![githubissue2](https://cloud.githubusercontent.com/assets/5566652/25029073/aebba500-206e-11e7-8aa7-92c5d69add41.PNG)

What do you guys think?

**Comment by Alys** [comment]
@rhdsmnd That seems reasonable to me, although if other admins suggest a different approach, listen to them not me. :)

Just as a general note about this issue, I'd like to see it fixed because when a user has been blocked and doesn't initially understand the message they get about that, they might refresh the website to see if that fixes the problem (we often tell people to refresh to fix certain errors).  One of the main reasons we block users is because they are underage and we haven't yet seen permission from their parent/guardian, so in those cases we do want the block to make sense and to have the block message visible even after a refresh.

**Comment by rhdsmnd** [comment]
Awesome!  I'll open a pull request soon for this and #8636

**Comment by FrankieFabuloso** [comment]
Has this issue been completed? If not, I'd love to take a look at it.

**Comment by Alys** [comment]
@FrankieFabuloso I'm sorry, we should have marked this as on hold until the website redesign project is finished. It's likely to either be fixed by that project or would involve new code so any fix made now would be wasted. If it's still necessary after the new website is live, you'd be welcome to work on it then!

**Comment by librarianmage** [comment]
Should this still be on hold? How does it look with the new update?

**Comment by Alys** [comment]
This still happens although the loading screen looks different of course:

![image](http://imgur.com/PgsWhool.png)

I'd still like to see this improved in any way that allows the user to read the message about them being blocked after they've reloaded the site.

**Comment by Alys** [comment]
Labels updated although I'm not sure what section is best, and it might need design work. @lemoness

**Comment by lemoness** [comment]
I think "section: other" is OK for now. I think that perhaps we could just display the persistent and entire error message in a permanent state, so it shouldn't need a separate design. We can always improve it visually later, but if it's the only thing that you can look at on the screen, I think people will read it.
