### ISSUE TITLE
Wording on Weekly Dailies set to Repeat Every 0 weeks confusing on website.

### ISSUE THREAD

**Issue by Lalaitha** [HabitRPG/habitica#8752]
(Though this is strictly speaking not a bug, it has caused a lot of confusion after the implementation of Weeklies, Monthlies and Yearlies, so Alys asked me to make an issue for it here. :) )

I have a.. wording suggestion regarding the weeklies and such. I realized after some questions in the Tavern and some testing myself.
When you create a Weekly task, that is active on e.g. Monday, you still have to set the Repeat Every to something else than 0 for it to ever be active. On the app (at least iOS) it says clearly that if the Repeat Every is set to 0, it will never repeat/be active. On the website, however, it says that it Repeats every 0 weeks on Mondays. Even though it does mean the same thing, I think it's a bit more clear wording in the apps - "Repeats never".

**Comment by Alys** [comment]
Agreed. I think it would be better if the website says "Repeats never" whenever the `everyX` field has a value of 0, regardless of what other repeat settings are in place. So for example, instead of seeing this message in the Summary:
![image](https://cloud.githubusercontent.com/assets/1495809/26450460/eb9b377c-419a-11e7-9f2f-85ce08eeca6c.png)
the Summary would contain only "Repeats never."

Also, not strictly related to that, but could be done at the same time:

I think the drop-down menu that contains Daily, Weekly, etc should have a subheading. I suggest "Repeat Type" (other suggestions welcome).
The subheading should have on-hover text as the other subheadings do. The title for it should be something like "What kind of repeat is this?" and the body should be something vaguely like this:

'Select "Daily" if you want this task to repeat every day or every second day or every third day, etc. Select "Weekly" if you want it to repeat on certain days of the week. If you select "Monthly" or "Yearly", adjust the Start Date to control which day of the month or year the task will be due on.

**Comment by Sylvir9** [comment]
So, I'm new and I was wondering if I could try working on this?

**Comment by Alys** [comment]
@LlamaLad That would be great, thank you! Ask here if you have any questions.

**Comment by TheHollidayInn** [comment]
@LlamaLad Just now seeing your post. Do you need any assistance with understand the flow? I add the code, so feel free to ask me questions.

**Comment by librarianmage** [comment]
Has this been fixed? Is it still in progress?

**Comment by TheHollidayInn** [comment]
We no longer have the summary, so we can close this unless we are adding the summary back.
