### ISSUE TITLE
scheduling corruption / confusion for repeat settings in Dailies

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8763]
I've seen a couple of reports indicating that the repeat options for some existing Dailies aren't correctly used now that monthlies and yearlies exist. I haven't fully investigated yet but I'll dump what I find into this issue.

One report is from @thebat137 at https://github.com/HabitRPG/habitica/issues/8756#issuecomment-304427477 :

"I noticed that one of my tasks that existed before the changeover ended up in kind of an odd state after the changeover (possibly unrelatedly, but I mention it here just in case it helps). Before the changeover, it had been scheduled to happen on three specific days every week. After the changeover, it was scheduled to occur every 3 weeks, but still on the same set of days. It seems that in the translation from the old to new style repeats, something did not get converted correctly. I have a sort of hypothesis for what might have happened, based on the fact that at one point in the past I had had this task on an "every 3 days" schedule, and had only later switched it to an "every Tuesday, Thursday, and Sunday" schedule. I wonder if perhaps the "3" was invisibly retained as the "X" in "every X days", even though "every X days" was not actually active. So when the "every Tuesday, Thursday, Sunday" pattern that was actually active got converted into an "every X weeks on Tuesday, Thursday, and Sunday", the old hidden X=3 value was retained instead of a more appropriate X=1 value being written over it. Anyway, I dunno if this is a useful idea about how the repeat got screwed up, or if there's any possible connection between a screwed-up repeat and slow editing, but I just want to be complete."

**Comment by sswam** [comment]
My dailies that were previously on certain days of the week (e.g. every Monday) are now converted to "Weekly" tasks on the web app, which is fine, but in the Android app they are appearing as daily tasks that repeat every day.  So, I am seeing all my "dailies" every day in the app, rather than on the correct days of the week.  I tried pressing "sync" and "reload content" to no avail.  I tried clearing the app data and logging in again, this did not fix the problem.  It seems to fix up if I edit the task on the web, and change the interval to every two weeks, then "refresh" on the app, then change it back to every one week on the web, then "refresh" on the app again.  Needless to say it would be inconvenient to do this manually for all of my tasks, but I guess that's what I'll be doing.

**Comment by sswam** [comment]
Actually even editing the daily on the web does not fix the problem entirely.  When I edit the task in the app it still appears to be recurring every 1 day instead of every 1 week.  The problem also occurs for newly added tasks that should occur each Monday for example, they appear as "every 1 day" tasks when I edit in the Android app.

Also I added a 1-yearly task starting 29/02/2020, just to be perverse, and the first date listed was 28/02/2018. Which is the wrong date, and the wrong year. Please expand your testing team, if you have one.

As it is, I can't continue using Habitica for my daily tasks, because it no longer works correctly.

**Comment by Alys** [comment]
@sswam Please report those problems in the Report a Bug guild, which you can reach from Help > Report a Bug on the website or from Guilds > Public Guilds on the mobile app. We can't help you without knowing which Habitica account is yours and when you post to the guild, we can see your account straight away. Please also tell us there which of your Dailies have those problems. If we need specific reports in GitHub, we'll either copy the posts there ourselves or ask you to report them - that helps us avoid duplicate reports in GitHub. Most of what you describe looks like they probably are known problems with workarounds that will help you until the associated bugs are fixed but we can confirm that when you've posted to the guild.

**Comment by TheHollidayInn** [comment]
I believe we have addressed what we could here on Slack, @Alys. Should we investigate further?

**Comment by Alys** [comment]
Agreed so I'll close this. I haven't found any other scheduling problems that can't be explained by the issues we already know about.
