### ISSUE TITLE
Normalize Task Links

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#8790]
Currently our group and challenge tasks require a sync and are a copy of the originals. This leads to many syncing issues and performance issues. We should implement something similar to database normalization: https://en.wikipedia.org/wiki/Database_normalization. 

Basically the steps are as follows:

1. Create a ID ref to original task (already done)
2. Whenever the task is queried, populate with the origin task
3. Remove all syncing code
4. Ensure nothing breaks

**Comment by kvsm** [comment]
So, if I understand this right:

- the original tasks are the ones stored against the challenge/group (ie. with `task.userID` not set)
- currently, the user's copy of the task has to be kept in sync with the original
- instead, we would still have a user copy but instead of trying to keep it in sync, we'd just use the `task.challenge.taskId` to pull the original any time we needed it?

**Comment by TheHollidayInn** [comment]
Yea, and the group.taskId. There are certain fields that the user can edit, so those can be copied over. The rest of the fields should come from the population.

**Comment by Alys** [comment]
I've just realised that we'll still need to sync when the user leaves the challenge and chooses to keep the tasks, and also when the challenge is deleted or closed so that all participants keep their copies of the tasks. :(  In the latter cases it will be critical that we don't have sync failures - more critical than syncing is now because there won't be any opportunity for the user to work around failures by rejoining.

**Comment by TheHollidayInn** [comment]
Looks like we decided to:
 - keep the old challenge task instead of delete
 - on getChallengeTask, check if the challenge has ended and sync that task at that point.

**Comment by kvsm** [comment]
Ok... would something like this help for general cases other than closing/deleting a challenge?


- User joins a challenge. A user copy of challenge tasks is made as normal.
- Later, user logs in. User's tasks are fetched. For any task which is a challenge task, the original is also fetched. The original is merged with user copy, with user-editable fields from user copy overwriting original.
- Server returns the merged task.
- The merged task gets saved as the user copy any time it would normally be saved, and also if the user leaves the challenge and keeps the tasks (essentially, keeping it updated with changes without explicitly having to sync it).

I'm not 100% familiar with the codebase yet so I've probably overlooked something major. :)

**Comment by TheHollidayInn** [comment]
Hmm. Yea, I think you have the overall idea. I think we can check performance/logic once the code is coming together. Would you like to be assigned to this issue?

**Comment by kvsm** [comment]
Sure, I'll take a swing at it.

**Comment by lemoness** [comment]
@kvsm - Hi there! Just checking in -- what's the status of this fix?

**Comment by lemoness** [comment]
Is this still an issue?

**Comment by TheHollidayInn** [comment]
I'm closing this because I want to rethink the solution after measuring, refactoring and consulting with mongo best practices.
