### ISSUE TITLE
The time is took from the client, but validated against server time.

### ISSUE THREAD

**Issue by tellezhector** [HabitRPG/habitica#881]
Hello. I discovered this because I logged in from a computer which has wrong its date and time. The date in that computer was "May 31" while the correct date was "May 1". 

I logged in and I died because my dailies and todo's "had" been unattended like one month.

**Comment by lefnire** [comment]
Actually, sounds like it worked correctly. If the last time you logged in was May 1, and the new computer registers the new time your'e logging in as May 31, it docks you 30 days. That's regardless of whether calculation is on client or server. On the client, each time you run cron (the "next day" process), it stores the `user.lastCron` property - set on the client - so it can compare later.

**Comment by tellezhector** [comment]
I think that that should work always based on server time, because it is supposed that the server time doesn't change so radically. I mean, a client-server call at most will take a few seconds, but not 30 days.

The application penalizes you because of bad habits. I got penalized because I logged from a new computer with a bad date. Isn't it saying that to log in from a computer with a "bad date" is a terrible bad habit?

I know that something like that would imply a lot of code. But I would like to put it on the board to be considered.

**Comment by lefnire** [comment]
I've tried putting cron on the server before, and there are simply too many difficulties in that approach. I actually put considerable effort into that approach because I wanted to save the client some CPU cycles, but it just doesn't work and is not something worth revisiting. The difficulties are:
- we then need to store `user.timezone` property on each page load (because the server is on a different timezone than the user), then send up to the server to run cron, then have socket.io send the post-cron changes down to the client.
- There's an issue with derby where multiple sets being run on a client route cause a bundle timeout issue. We hit this when trying to run cron on the server, and I banged me head trying to get around this for a long time.

The thing is, having the clock set to a different date is an edge-case, and a working cron based on the user's timezone on the client is the majority case. In your situation, it would be better we have a warning pop up saying "system thinks you haven't been online for 30 days, click this if it was an error".

**Comment by switz** [comment]
You don't have to put cron on the server, just use a timestamp from the initial server route (or express middleware).  

model.set '_timestamp', +new Date()

**Comment by tellezhector** [comment]
Or merely validate if the client time is more than one day different from server time and warn the user.

I'm agree with you when you say that is not a common case. 

What other sites do is to rely part of this responsibility to the https certificate. If you are using https you could use certificates that expire in a short time, and then the browser itself will warn the user. (Try accessing gmail changing your local date).
