### ISSUE TITLE
checklists on To-Dos and Dailies do not stay collapsed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8829]
In the Report a Bug guild, Voidhawk (39e1503b-2415-45e3-905c-d7684fda0039) wrote:

"Since the recent [website] update, new To-Dos do not stay "collapsed" when you reload the site. Old To-Dos will stay collapsed, but changing the collapsed state (for checklists) does not maintain it's state. I keep all mine lists collapsed to save space, and only expand when I want them expanded."

This is probably the update referred to: [Release v3.96.0 Contributor PRs June 2017](https://github.com/HabitRPG/habitica/releases/tag/v3.96.0)

I've tested and confirmed it. If I collapse a checklist on a To-Do or a Daily and then click the sync button, the checklist becomes uncollapsed.

**Comment by Alys** [comment]
If this is an easy, fast fix, it would be worth doing. If it's not, then it might be best to ignore this since we're part way through a website redesign that will presumably fix this problem since there will be new code for the website.

**Comment by wilhen01** [comment]
I've noticed this happening in the last few days too. It's a minor annoyance, but it'd be nice to fix it 😄

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by joedragons** [comment]
In case relavent, I noticed today that this does not happen for all todos.  The quote above infers since a change but I have 3 todos with subtasks on one account and the middle-aged one auto expands but the younger and older do not.  I noticed this on a new todo on another account so I don't believe fixed but does not seem consistent to me.  I do not recall if I created the tasks different ways but I'll keep in mind when doing so for future ones to see if I notice a pattern.  Though as stated new code may fix all this anyway=)

**Comment by CharityB** [comment]
Any update on when the project might be completed that is going to correct this issue?

**Comment by lemoness** [comment]
We've made many changes to the website, and this doesn't appear to be an issue any more. I'm closing this ticket, but if you feel that it should be reopened for any reason, please feel free to leave a comment!

**Comment by tardis4500** [comment]
Is this a joke? It's not an issue because the functionality was completely removed. Telling me that TODOs will stay collapsed in the new interface and then removing the functionality as the "solution" so that no TODOs are collapsed is not a fix. This issue should not have been closed since the problem remains: TODOs do not stay closed.

**Comment by Alys** [comment]
@tardis4500 You might not have reloaded the website recently - reloads are necessary for the latest changes to take effect so I'd recommend reloading once a day, maybe twice a day while we're pushing out changes rapidly, or at least reloading when you see information in Habitica about more bugs being fixed. Checklists are definitely staying closed for me at the moment. If you reload and still see yours not staying closed, please go to Help > Report a Bug to report the issue and tell us there what browser you're using, including its version number and what operating system. if there is a new bug that needs coding changes, an admin would open a new GitHub issue because it would have a different cause compared to this old bug.

**Comment by wilhen01** [comment]
Nice one, thanks guys!
