### ISSUE TITLE
Cannot use my in app log in to log in on website.

### ISSUE THREAD

**Issue by ForbiddenFig403** [HabitRPG/habitica#8869]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 2b35e3eb-1bb5-48c9-a03a-07b6fe4c320b
  * Browser: Chrome (as far as I know it's the latest version)
  * OS: Windows 10

### Description
[//]: # I cannot post on the Bug Guild on the website without an account, so this is not something I can do. I also have looked through the entire guild list on my phone to find this illusive "Bug Guild" and found nothing. When I finally found a link (using my PC) in the help section, it redirected me to make another account (which I don't want a new account, I just want to use my phone app account on the website. Screen includes the only options available for log in as I see them.

#### Console Errors
[//]: # I am not sure where I would find any relevant errors as I am not familiar enough with coding etc.
![habitica 7-12-17](https://user-images.githubusercontent.com/30127962/28142105-6fc91598-672d-11e7-9549-3d55e2692fb2.PNG)

**Comment by deidyomega** [comment]
+1

My fiancee used signin with google, on her phone, and it worked, however when she tried to login via the desktop app, it gave her an oauth error

**Comment by Alys** [comment]
@ForbiddenFig403 We'll deal with your login problem here since you've logged this issue but if you have any problems in future, the guild is called "Report a Bug" and can be access from Guilds on the mobile app (you'll find it in the Public Guilds section), or from Help on the website. You can also report bugs from About > Report a Bug in the mobile app's menu.

Can you please give us more information about why you can't log in? For example, does the "Sign in with Google" button not respond when you click on it? Or does an error message appear when you click it? Or does it show you an account but not your normal account (in which case the browser you're using is logged in to a different Google account than you use on your mobile device)? Or does something else go wrong?

@deidyomega Can you please ask your fiancee to report the problem to us? We need to hear directly from a person experiencing a bug, especially in the case of login errors. If you're reporting it for her because she doesn't speak English, she can report it to us using her native language. The best way for her to report it would be from About > Report a Bug from the mobile app's menu - I recommend she uses that for a login problem rather than the other options, since it sends an email to us, keeping her login details private.

**Comment by ForbiddenFig403** [comment]
@Alys Thank you for the information for next time. I have resolved the issue on my end after much googling on how to clear out my cache and figuring out definitively which account I was using on my mobile app. Previously the issue was that when I clicked the "login" ("Enter"/"Play") button, it didn't send me anywhere at all. Another user from the help section addressed me in order to get this info, so many thanks to ratzalina! Sorry for the inconvenience on posting out of the help guild, but as previously stated (maybe I am just blind) I couldn't find in the list of public guilds.
