### ISSUE TITLE
gift subscriptions and gift gems can't be purchased through PayPal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8878]
Trying to send a gift subscription results in a "Server currently unreachable" notification as soon as you click on the PayPal button. The PayPal website is available at the same time.  Creating a non-gift subscription for yourself does not produce this error, nor does attempting to buy gems with PayPal.

Thanks to XBZ1337 (ed9bd06a-742b-4a6c-be3e-f06f49a564ba) for reporting this in the Report a Bug guild.

**Comment by Alys** [comment]
Also happens if you try to buy gems through PayPal as a gift by going through a player's profile screen (not if you buy gems using PayPal for yourself from the gem icon in the website's header).

XMLHttpRequest cannot load https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-7U775140EV9373346. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://habitica.com' is therefore not allowed access.

**Comment by Audiotuete** [comment]
Hi the Error is caused in habitica/website/client-old/js/services/paymentServices.js:365 by the `$http.get(url)` method. For some reason angulars `$http` is not attaching the right header to the requests.
The generated URLs are vaild. When you open them from the error in the console or request them via Postman they work just as intended.

My first somewhat hacky try would be to explicitly set a header: (but my dev env isn't set up yet and it's not even a tested PR ;)
```
    var req = {
      method: 'GET',
      url: url,
      headers: {
        'Content-Type': 'text/plain;charset=utf-8'
    }

    $http(req);
```
OR the cleaner way is to add: 

`$httpProvider.defaults.headers.common['Content-Type'] = 'text/plain;charset=utf-8';
`
to the default-config in habitica/website/client-old/js/app.js:413

**Comment by SabreCat** [comment]
@Audiotuete: At the moment, the default config for Content-Type is `application/json;charset=utf=8`; you're suggesting we change that to `text/plain`?

**Comment by Audiotuete** [comment]
Hi, my first guess is not going to fix it, but I found a simple workaround that definitely works. 
Just inject `$window` at the top of habitica/website/client-old/js/services/paymentServices.js:4 and :5 after `$rootScope` like this:
```
['$rootScope', '$window', 'User', '$http', 'Content', 'Notification',
function($rootScope, $window, User, $http, Content, Notification) {
```
and instead of making an `$http` request just call `$window.open(url, '_blank');` like this: 

```
Payments.payPalPayment = function(data){
    if(!Payments.checkGemAmount(data)) return;

    var gift = Payments.encodeGift(data.giftedTo, data.gift);
    var url = '/paypal/checkout?_id=' + User.user._id + '&apiToken=' + User.settings.auth.apiToken + '&gift=' + gift;

    $window.open(url, '_blank');
}
```
Sorry for not PRing myself, but I'm still somewhat overwhelmed by this git-stuff :D

**Comment by lemoness** [comment]
Is this issue still in progress?

**Comment by Audiotuete** [comment]
It's solved as far as I know. But since I didn't make the pull request I really can't tell.


________________________________
Von: lemoness <notifications@github.com>
Gesendet: Donnerstag, 7. Dezember 2017 06:44
An: HabitRPG/habitica
Cc: Jan; Mention
Betreff: Re: [HabitRPG/habitica] gift subscriptions and gift gems can't be purchased through PayPal (#8878)


Is this issue still in progress?

**Comment by Alys** [comment]
The linked PR was merged so this should have autoclosed itself.
