### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by coolandsmartrr** [HabitRPG/habitica#89]
It was working until noon, when I was logged out. When I try to log back in, the "login" button after the username and password fields is greyed out. Is there a way to resolve this? I'd like to get back to the game asap.

**Comment by erreerre** [comment]
Me neither :(

**Comment by racuna** [comment]
Me neither, the login doesn't work with LastPass. Just re-type your login and password and the button reappears. If not, try just press enter.

**Comment by lefnire** [comment]
I'll fix that today guys

**Comment by dmuth** [comment]
Subscribing

**Comment by coolandsmartrr** [comment]
Seems like the website's migrated! It's loading find now. Congratulations. That said, I really look forward to resume using HabitRPG by being able to login again. The button's still greyed out. Any guess when this will be fixed?

**Comment by lefnire** [comment]
Next it on the agenda, but hacky hack try entering your uname, then pass,
then reentering uname again

**Comment by erreerre** [comment]
Still doesn't work... It says "Invalid login"

**Comment by lefnire** [comment]
@erreerre there was a lot of data-persistence problems yesterday due to #91 unfortunately :( :( :( - try to re-register

**Comment by ghost** [comment]
Tried reregistering still getting the grey but when I log back in through facebook everything is fine. Video games don't make people violent buggy code does.

**Comment by lefnire** [comment]
how bout now?

**Comment by coolandsmartrr** [comment]
I previously made an account, but it doesn't seem to work, and instead produces a message that it's an "Invalid Login." I've already listed many of my todos and gained experience points, and feel attached to that account. Could you possibly recover it?

**Comment by lefnire** [comment]
so for everyone's reference, there are two bugs here:
1. The button is greyed out and won't let you click "login". That should be fixed now with https://github.com/lefnire/derby-auth/commit/9167fd3676c530f3673cdb52e5325a5c7700a4d7
2. Users are seeing "username not registered". Unfortunately, due to #91 a lot of data was **not** persisted during the 3-day hulk-smash of Lifehacker/Reddit/Kotaku (roughly 1/16-1/18). Try re-registering, and if that creates a new account I'm _terribly_ sorry - send me your user-id [via email](mailto:tylerrenelle@gmail.com) and I'll hook you up with something when user customizations become available.

**Comment by lefnire** [comment]
Hey Ricky I'm terribly sorry for this - check out
https://github.com/lefnire/habitrpg/issues/89#issuecomment-12459057
