### ISSUE TITLE
Username (both herobox & in tavern) - Bug

### ISSUE THREAD

**Issue by Pacerparty** [HabitRPG/habitica#890]
I can''t see my username in tavern chat and other people can't see it too.
I also can't see it in my herobox.

**Comment by heyimzsa** [comment]
+1 and I can't see what level I am as a well

**Comment by lefnire** [comment]
Fixed (will hit prod on next restart). I removed the main-character stats popover because it was semi-annoying, as a common place to click - but forgot that your level is there. Putting back for now. Should we remove again and put level back into herobox next to username? we originally nixed that because it limited the profile name in characters users could enter

**Comment by Pacerparty** [comment]
Maybe put the level below the yellow experience bar.

**Comment by StanLindsey** [comment]
Personally I like the rollover. Keeps it consistent and allows me to quickly compare myself to people in my party.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
