### ISSUE TITLE
Group task API is documented (an possibly coded) wrong

### ISSUE THREAD

**Issue by asmfreak** [HabitRPG/habitica#8922]
### General Info
  * UUID: 1f740057-8e11-4ca3-a9b2-54886615dca6
  * Browser: any
  * OS: any

### Description
This is the current implementation:
```javascript
/**
 * @api {post} /api/v3/group/:groupId/tasks/:taskId/move/to/:position Move a group task to a specified position
 * @apiDescription Moves a group task to a specified position
 * @apiVersion 3.0.0
 * @apiName GroupMoveTask
 * @apiGroup Task
 *
 * @apiParam (Path) {String} taskId The task _id
 * @apiParam (Path) {Number} position Where to move the task (-1 means push to bottom). First position is 0
 *
 * @apiSuccess {Array} data The new tasks order (group.tasksOrder.{task.type}s)
 */
api.groupMoveTask = {
  method: 'POST',
  url: '/group-tasks/:taskId/move/to/:position',
  middlewares: [authWithHeaders()],
  async handler (req, res) {
    req.checkParams('taskId', res.t('taskIdRequired')).notEmpty();
    req.checkParams('position', res.t('positionRequired')).notEmpty().isNumeric();
```

apiDoc reports `/api/v3/group/:groupId/tasks/:taskId/move/to/:position`,  whereas actual code uses `/group-tasks/:taskId/move/to/:position`. Also `groupId` isn't used in actual function text.

**Comment by librarianmage** [comment]
https://github.com/HabitRPG/habitica/blob/7b9ebc34655320b5df3c1c351897f9b8d4f38c53/website/server/controllers/api-v3/tasks/groups.js#L95-L145

**Comment by Alys** [comment]
I'll look into this.

**Comment by Alys** [comment]
@ASMfreaK Thank you for finding this problem! And thanks @MathWhiz for the handy link to the code. :)

I've tested sorting in group plans and it's broken, so I think @ASMfreaK might be right that the code in this function is wrong, as well as / instead of the docs. I've logged https://github.com/HabitRPG/habitica/issues/9691 to get that fixed and I've written in the issue that the fix must fix the docs too, so I'm closing this issue now.
