### ISSUE TITLE
How to find the challenge page for leaving?

### ISSUE THREAD

**Issue by huiwang159** [HabitRPG/habitica#8943]
Hi everyone. I am just wondering is there a link somewhere to the challenge page so I can leave a challenge? It seems such a chore to scroll through all the guilds...

**Comment by shanaqui** [comment]
There's a challenge section! On the website, click the dropdown beside social and then click challenges. You can filter it by challenges you're a member of, too.

Just a note, this isn't a bug; even if the capability wasn't on Habitica, this would be a suggestion rather than a bug report. As such, you might want to ask questions like this in the Habitica Help guild in future, and direct suggestions to the Trello page.
