### ISSUE TITLE
Leaving Group Plan and starting an individual subscription

### ISSUE THREAD

**Issue by Sethycakes** [HabitRPG/habitica#9053]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 8a1db51b-01f8-4794-8f9b-a0da605b9bcb
  * Browser: Google Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Can I subscribe to Habitica without waiting for my Group Plan free subscription to run out? I don't want to risk losing any perks and my group just unsubscribed from Group Plans.

**Comment by Alys** [comment]
cTheDragons's advice to you in the Habitica Help guild is correct. It's best to not ask the same question in two places because it can lead to duplicate effort to help you. Also we try to keep github issues dedicated to problems that need code fixes so if you run into a bug, you can report it in the "Report a Bug" guild, available from Guilds or from the website's Help menu (if you ever need a reminder, there's notes about that in the template for a new GitHub issue, and you can then cancel the issue after reading them).
