### ISSUE TITLE
allocated stat points appear to go to Strength

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9096]
When a user allocates a stat point, on the server it is allocated correctly every time,  but on the client it looks like the point is always allocated to Strength. As soon as you reload you see the correct allocations.

I've tracked it down to this code:
https://github.com/HabitRPG/habitica/blob/4495539e8c34c16b00b3f3c4bb7721428ae72478/website/client/components/userMenu/profile.vue#L281
https://github.com/HabitRPG/habitica/blob/4495539e8c34c16b00b3f3c4bb7721428ae72478/website/client/components/userMenu/profile.vue#L797-L800
https://github.com/HabitRPG/habitica/blob/4495539e8c34c16b00b3f3c4bb7721428ae72478/website/common/script/ops/allocate.js#L12

Note in that third piece of code, `str` is a default for `query.stat`. If you change it so that `int` is the default, then the same change occurs in this bug: all points appear to be assigned to Intelligence. So that default is definitely indirectly responsible for this bug.

I guess that when the allocation happens on the server, everything works perfectly because the user's chosen stat is correctly passed on to the code that assigns the point, and so the default in that third piece of code is never used.
On the client, it looks like the user's chosen stat is not passed, and so the default IS used for the client-side allocation.

I'm not familiar enough with vue to work out how to make the user's choice be correctly passed client-side.

**Comment by Alys** [comment]
I'm marking this important because it's a highly visible bug - so many reports of it in the Bug guild and Tavern! We need this fixed for the Socialite's sanity if nothing else.

If a contributor wants to take it on, please only do so if you already can see how to fix it and can submit a PR within the next day. Comment here if you can do that. I'm also asking the staff devs for input on this and it's possible that they/me will finish this ourselves.

**Comment by trvrfrd** [comment]
I have a fix running locally that seems to solve the issue. Happy to open a PR if no one has taken care of it yet!

@Alys, you had definitely tracked down the problem. It seems to be a simple matter of the `allocate` function in `website/client/components/userMenu/profile.vue` calling the other `allocate` function in `website/common/script/opts/allocate.js` incorrectly. The latter expects its second argument to be an object of the shape `{ query: { stat: String } }` and is instead receiving a plain String of the stat being allocated, which is why it is defaulting to `'str'`.

I haven't worked with Vue before, so I don't know if I fixed it the "right" way, but the (single-line) change I made in the template doesn't seem to have broken any tests or anything. I'm also new to the codebase and didn't see an obvious place to put a UI test to catch regressions. But, again, happy to open a PR with what I have if that's helpful!

**Comment by TheHollidayInn** [comment]
Feel free to open a PR, and I will review! I believe you have the right concept. I was about to do this fix otherwise.

**Comment by Alys** [comment]
This might be related although a fix for it does NOT have to go live at the same time as the fix for the problem above:

Destan53 (380a5fa2-0938-4cc1-8357-89acf2d7e503): 
"I think that the automatic allocation of attribute points isn't working, previous to the change of the site I had the mode of "Distribute attribute points evenly", but last night after the changes I went up one level, and the attribute point that should've gone to Constitution went to Strength instead, as you have suggested I've refreshed the site (multiple times), but nothing happened and the attribute point is still in Strenght. Any recomendations about this?"

EDIT: Copied to https://github.com/HabitRPG/habitica/issues/9107

**Comment by TheHollidayInn** [comment]
That issue seems to have to with how auto allocation works on the server (maybe cron). We should probably separate the issue. But we can double check after this PR goes live.

**Comment by trvrfrd** [comment]
whoa, I contributed something! :heart_eyes_cat: thanks y'all!

**Comment by Alys** [comment]
@trvrfrd Thank YOU! We love the fast fix for this!

@TheHollidayInn I've made a new issue for the other thing: https://github.com/HabitRPG/habitica/issues/9107  It won't be related to cron. Auto-allocation happens on level-up.
