### ISSUE TITLE
Habit progress graphs disappeared in new interface

### ISSUE THREAD

**Issue by vasyl-shumskyi** [HabitRPG/habitica#9110]
Hello, 

Looks like habit progress graphs disappeared in the new interface.

http://habitica.wikia.com/wiki/Habits#Checking_on_your_Habits

<img width="251" alt="habit_progress_graph" src="https://user-images.githubusercontent.com/2331802/31047253-c727d812-a60f-11e7-9182-a3fd60acb722.png">

**Comment by Alys** [comment]
Bugs are best reported in the Report a Bug guild that you can access from the Help menu on the website or from Guilds on the website or mobile app. There's also a bit more information about that in the template within the new issue form in GitHub. If it's ever necessary for you to report a bug in GitHub, an moderator or staff member would advise you of that in the Report a Bug guild.

However there is no need to report this problem in the guild because we are already aware of it. Thanks for taking the time though!

If you find any other bugs, please see the guild's description for a link to a Known Bugs document and if you don't see your bug there, please post to the guild. The guild's description also contains information about our process for handling the bug reports there.
