### ISSUE TITLE
Edits to Skills (Stealth, Chilling Frost, Brutal Smash)

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9136]
After the redesign, there are several small bugs with skills:

- Chilling Frost should be grayed out after the first time that it is cast, since there is no advantage to casting it multiple times a day. - logged at https://github.com/HabitRPG/habitica/issues/6867
- <strike>Brutal Smash and Burst of Flames no longer have an associated notification saying how much damage it dealt to the Boss.</strike> - logged separately and fixed in https://github.com/HabitRPG/habitica/issues/11828 
- In the tooltip for Stealth, it should tell you how many Dailies you are skipping that day. - logged at https://github.com/HabitRPG/habitica/issues/12220

**Comment by LunarGem** [comment]
Are the docs on local installs updated yet? I could try this (I'm already working on a skills-related server side issue, so if it's not too much different with Vue instead of Angular it's probably within my skill set).

**Comment by Alys** [comment]
@LunarGem Sorry about our delay on answering this! We'd love you to work on it - thank you!

These two docs have been updated:
http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths
http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally

This one has not yet:
http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica's_Website_and_API
but most of it should still be the same as before. The "Restarting the Local Web Server" section will need to change but you can get everything you need from that from the "Run Habitica" section near the bottom of http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Run_Habitica

If you have any questions or problems with the docs, your local install, or this issue, please comment here! If you haven't received a reply in a day, post a reminder.

**Comment by LunarGem** [comment]
I was thinking that there should be a more obvious place for knowing how many dailies you've avoided, like the top of the daily column? Or an overlay on dailies that won't be counted?

**Comment by lemoness** [comment]
I've passed this question along to our designer, @Tressley!

**Comment by Alys** [comment]
I'm marking this as needs designs since there's questions for @Tressley

**Comment by Alys** [comment]
There was a bug report about this today from @sophiadaniels (40e741cd-bdc4-4a79-b932-853ad09e4944):

**"Burst of Flames doesn't display a notification with the damage done to the boss. it just tells me the mana spent, xp gained, and that i cast the spell. but it's not clear that it's actually doing any damage without checking the pending damage before and after using it. even if it's 1:1 int stat:damage dealt.... it would be nice if it gave some indication that it's doing damage when i cast it. i was convinced i had to use it on a task and then do that task to have it do any damage."**

Since it's caused confusion about how the skill should be used, is it possible for this to be changed back from minor to medium priority?

Or can it be split up into different issues? For example, adding the boss damage notification could be done without design work I guess since it would be reusing the notification that's used for tasks.

I'll leave this as it is for a few days then if there's no objections I'll make new issues for the simple parts that I think don't need design work.

**Comment by Tressley** [comment]
@Alys -- I'm hesitant to add another snack notification because of how poor the UX is with them now, but we do have plans to tackle that UX this year. So, in the mean time, I think your solution to show a boss damage notification is a good one.

Here's a Zeplin artboard with how damage should be displayed: https://zpl.io/2p0d882
![image](https://user-images.githubusercontent.com/2686586/72626536-e871ec80-3918-11ea-98f2-5a6de8178183.png)

_EDIT by Alys 2020-05-21: I've created this issue:_ https://github.com/HabitRPG/habitica/issues/12221

**Comment by Alys** [comment]
I'm closing this. One of the items from the top post was fixed recently, another already had its own issue, and I've just created an issue for the third. I've updated the top post to link to the issues.
