### ISSUE TITLE
Ctrl+Enter should send chat message

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9138]
You should be able to hit Ctrl+ enter to send chat messages in ALL chat areas of the new site.

**Comment by aalsehly86** [comment]
Hello @lemoness, anyone currently working on this issue? Because Tavern Chat, Party Page and Messages has been **fixed** and tested on 56.0 (64-bit) Firefox on Ubuntu and it's working fine with Ctrl+enter to send messages. Just don't know if there are more chat boxes to be fixed? 
The first two sections, Groups and Guilds? We're contributing to this as a part of a Computer Science class. Thanks.

**Comment by lemoness** [comment]
@aalsehly86 Thank you for asking! This bug has indeed been recently fixed, but I hope that you and your classmates will contribute to one of the other issues. Check out the "POST-REDESIGN" tag to see some of the most recent issues!
