### ISSUE TITLE
"You bought subscriber gems" when they've all been bought - message formatting needs to be fixed

### ISSUE THREAD

**Issue by madpink** [HabitRPG/habitica#9153]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

<strike>When purchasing subscriber gems, there is no notification when we've purchased all that we can.  I keep clicking the purchase button and i get "You bought subscriber gems" but no more gems are added and no gold is deducted.</strike>

<strike>Using the API I get  the error message: "You've reached the Gold=>Gem conversion cap X for this month. We have this to prevent abuse / farming. The cap resets within the first three days of each month."</strike>

EDIT by Alys 2017-10-17: The above message is now displayed on the website, but the formatting needs to be fixed.

![image](https://user-images.githubusercontent.com/1495809/31654295-f0d80252-b368-11e7-8e71-da385a0561fc.png)

**Comment by pineapple-joe** [comment]
Hey, can I work on this?

**Comment by Alys** [comment]
It looks like this has been fixed by a recent update by the staff - there's a message now telling you when you've bought them all, which appears when you click on the gem icon to open the confirmation screen. However it's sort of mis-formed.... :)

![image](https://user-images.githubusercontent.com/1495809/31654295-f0d80252-b368-11e7-8e71-da385a0561fc.png)

I'm renaming this issue to indicate that the formatting needs to be fixed.

@borisabramovich86 Are you interested in working on that? If not, that's fine! It's a different bug now than when you posted. Let us know either way. We can open this up to someone else if you don't want it.

**Comment by pineapple-joe** [comment]
Yeah sure, i'll take it :)

**Comment by Alys** [comment]
Great! All yours.

**Comment by Alys** [comment]
@borisabramovich86 I'm **really** sorry about this, but we've just in the past few minutes realised that there's other issues with that modal and with other modals too, which will need more of a site-wide change, and that would probably affect any fix that you did for this particular formatting issue. It might be best for you to not work on this. Have you done any work on it yet? If you're very nearly finished then maybe it's worth doing a PR if you can get it out in the next several hours. Sorry again. :(

**Comment by pineapple-joe** [comment]
Hey, no problem. I have nothing substantial yet.

**Comment by negue** [comment]
Closing this, the modal was redesigned and fixed (the bubble is gone and the remaining message is under the amount selection)
