### ISSUE TITLE
new Contributor equipment is not able to be purchased after a contributor tier is awarded

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9179]
When a contributor is given Tier 2, 3, 4, or 5, one of their [Contributor Rewards](http://habitica.wikia.com/wiki/Contributor_Rewards) is a piece of equipment, which they need to buy for gold.

They should be able to buy it by going to Shops > Market and selecting "None" from the 'Class" drop-down list. The equipment should appear there for purchase with gold because of this `canOwn` code:
https://github.com/HabitRPG/habitica/blob/5ced47f590a042e183de2ebf8770be77f730c039/website/common/script/content/gear/sets/special/special-contributor.js#L43
(and of course similar code for the other contributor gear pieces).

However that's broken. There is currently no way that a contributor can buy the contributor gear they've earned.

----

_Any Blacksmith who works on this issue can ignore the paragraph below._

_I believe this has been broken since the new website went live and we've given several players contributor tiers since then so they're all missing their gear. Admins can fix that by doing a database search/repair for all contributors, but until we have time to do that, anyone who's missing equipment they've earned can report it in the Report a Bug guild and we'll fix it for them. That fix will be done by giving them the gear with a `false` value, as if they'd previously bought it and then lost it due to death, so they'll then be able to buy it with gold as normal._

**Comment by pineapple-joe** [comment]
Hey, can I try to work this out?

**Comment by Alys** [comment]
@borisabramovich86 Yes please!! :) Post here if you have questions.

**Comment by borisabramovich86** [comment]
Hey,
I am working on this, and while I understand the flow in general, I can't seem to pinpoint the issue.
If you could provide me with some hints, I would really appreciate it :) 
Mainly, the flow of how the items shown in the market are loaded.
Thanks!

**Comment by pineapple-joe** [comment]
@Alys 
Hey,
I managed to get it working, but I'm not sure if the result is correct.
In order to show the items
<img width="1024" alt="screen shot 2017-10-25 at 5 33 11 pm" src="https://user-images.githubusercontent.com/10450216/32004532-a14a71dc-b9aa-11e7-87b4-b828358f282d.png">
 I changed:

https://github.com/HabitRPG/habitica/blob/5ced47f590a042e183de2ebf8770be77f730c039/website/common/script/libs/shops.js#L174

to:
`return !user.items.gear.owned[gear.key] && gear.klass !== user.stats.class;`

and added:

`shops.checkMarketGearLocked(user, nonClassCategory.items);`

after:
https://github.com/HabitRPG/habitica/blob/9736ef0d25f108cbc7d691defcb84c4fe50d87ae/website/common/script/libs/shops.js#L177-L181

<img width="1033" alt="screen shot 2017-10-25 at 5 24 23 pm" src="https://user-images.githubusercontent.com/10450216/32003982-63e8ae40-b9a9-11e7-934b-d03c9c10a94c.png">

this results in 645 items being shown in the None category, 
with all the options showing (locked, time limited etc.).

Is this what we want?

**Comment by SabreCat** [comment]
Hmm, no, most definitely not! This filter should only show gear that doesn't belong to any specific class, so the seasonal and standard sequence gear don't belong there.

I think what needs to happen is one of the following:

1. Add logic around here https://github.com/HabitRPG/habitica/blob/3503b307b20a5276a12f92084c196a8d6de3b538/website/common/script/libs/shops.js#L176 to find and add eligible contributor and backer gear to the list
2. Change the logic here https://github.com/HabitRPG/habitica/blob/3503b307b20a5276a12f92084c196a8d6de3b538/website/common/script/libs/shops.js#L173-L175 to include eligible contributor and backer gear
3. Generalize the logic so it looks for the `canOwn` property, and filters based on whether a class or "None" is selected

I think # 3 is the best option long-term, but the others would be acceptable for fixing the issue at hand!

**Comment by pineapple-joe** [comment]
@SabreCat @Alys 
ok, thanks.

This is the filter I came up with:

  ```
let falseGear = filter(content.gear.flat, (gear) => {
    return !user.items.gear.owned[gear.key] 
           && content.classes.indexOf(gear.klass) < 0
           && content.classes.indexOf(gear.specialClass) < 0
           && (gear.canOwn && gear.canOwn(user));
  });
```

resulting with showing only the contributor gear: 
(for level 7 contributor, and critical bug solver - 5 items)

<img width="1034" alt="screen shot 2017-10-25 at 9 27 40 pm" src="https://user-images.githubusercontent.com/10450216/32015986-5d5ddbbe-b9cb-11e7-9c12-88d7673a5300.png">

level 3 contributor:

<img width="1027" alt="screen shot 2017-10-25 at 9 32 46 pm" src="https://user-images.githubusercontent.com/10450216/32016256-19ece37e-b9cc-11e7-86e9-efcdf58cedee.png">

**Comment by majestic-owl448** [comment]
at the moment if one loose Seasonal Equipment for death the items are found under Class:None, same for Enchanted Armoire items, would this prevent it?

**Comment by pineapple-joe** [comment]
@Ieahleen  could you give me the flows to reproduce those use cases?
I'll test it out.

**Comment by majestic-owl448** [comment]
I have no idea on that, I know only that when loosing equipment for death
that particular equipment has a `false` value.

2017-10-26 12:04 GMT+02:00 borisabramovich86 <notifications@github.com>:

**Comment by pineapple-joe** [comment]
@Alys @SabreCat 
could you provide me with flows to reproduce what @Ieahleen is talking about?
I want to make sure not to break any existing functionality.

From what I understand, if you had
Seasonal equipment or Enchanted Armoire items
and you died, it will be under 
the Class: None section?

**Comment by Alys** [comment]
@borisabramovich86 When you die, one piece of equipment is chosen randomly and its `true` value is changed to `false` in your items.gear.owned object. So you can mimic the effect of death by using a database command in your local install to adjust the gear values in a test account.

Enchanted Armoire items lost due to death should show up under Class : None.  The same should happen for any non-class-specific gear obtained from quests or any other source.

If you lose class-specific gear from the basic set (the set of several gear pieces that any new player has access to), those pieces should appear under the appropriate Class option.

If you lose seasonal class-specific gear, I don't know if the intention for this new website is that it shows up under Class: None, but I guess if it's doing that now, keep letting it do that, unless one of the staff say otherwise.

Does that answer your questions? Ask again if it doesn't.

@leahleen thanks for mentioning this!

**Comment by pineapple-joe** [comment]
ok, got it.

so the original code handled the non-class-specific gear lost due to death.
It shows any items not of the user class that were owned, and now are false.

class specific isn't shown in this category.

If you lose seasonal class-specific gear - it will show here, because it's class is special.

I'll add non class specific gear that the user can own.

```
let falseGear = filter(content.gear.flat, (gear) => {
    return (user.items.gear.owned[gear.key] === false && gear.klass !== user.stats.class)
           || (content.classes.indexOf(gear.klass) < 0
              && content.classes.indexOf(gear.specialClass) < 0
              && (gear.canOwn && gear.canOwn(user)));
  });
```

Here you can see the contributor gear, a special item, a special seasonal item of the user class (warrior) and a mystery item.

<img width="1031" alt="screen shot 2017-10-26 at 9 23 57 pm" src="https://user-images.githubusercontent.com/10450216/32070142-0995c8ec-ba94-11e7-99fa-9dd1cf7707cc.png">

@Alys @SabreCat  - what do you think? let me know if I can proceed.

**Comment by SabreCat** [comment]
I think that's pretty close, but I'm not convinced that broken class or seasonal gear belongs here. To the end user, there is no `class` and `specialClass`, just "what class is associated with this gear set?" (Also, is that a short sword, second from the right? That's class gear by any rubric.)

The "None" class filter should show gear that

1. is not currently owned,
2. that the user can buy,
3. but which isn't tied to a class, "special" or otherwise.

If the current behavior (i.e., before any changes in this PR) is to show broken seasonal gear here, it's OK to leave it that way, but I'd call that a bug worthy of its own issue ticket.

**Comment by pineapple-joe** [comment]
ok, so not sure how to proceed.

1. what's a broken class?

2. About the short sword. 
The user's class is warrior. I added to his items weapon_rogue_1 = false.
not sure if that's possible in a normal use case.
When we say class specific, we mean the user's class (warrior) or any class (of the basic 4) ?
Because the user's class here is warrior, the weapon's class is rogue, therefore , he can see it 
(that is the current functionality).

```
 let falseGear = filter(content.gear.flat, (gear) => {
    return (user.items.gear.owned[gear.key] === false && gear.klass !== user.stats.class)
           || (!user.items.gear.owned[gear.key]
              && content.classes.indexOf(gear.klass) < 0
              && content.classes.indexOf(gear.specialClass) < 0
              && (gear.canOwn && gear.canOwn(user)));
  });
```

original functionality
`(user.items.gear.owned[gear.key] === false && gear.klass !== user.stats.class)`

not currently owned
`!user.items.gear.owned[gear.key]`

user can buy
`(gear.canOwn && gear.canOwn(user))`

isn't tied to a class
```
content.classes.indexOf(gear.klass) < 0
&& content.classes.indexOf(gear.specialClass) < 0
```

Here we can see backer (tier 300), contributor (level 7) , armoire (crossbow), special, seasonal 
mystery, and a basic rogue sword (since I made that the user used to own it, and his class is a warrior).

<img width="1029" alt="screen shot 2017-10-27 at 1 47 00 pm" src="https://user-images.githubusercontent.com/10450216/32100682-5d699f00-bb1d-11e7-8253-6811435fce45.png">

@Alys @SabreCat 
If we wanna moved all class related items to show in their categories (special and seasonal),
that's another matter I think.

**Comment by SabreCat** [comment]
OK, so it is an existing bug! Thanks for the investigation. Yeah, I think you can PR it like this, then!
