### ISSUE TITLE
Relative due dates should be in days, not hours

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9224]
On the tasks page, we now use relative due dates. However, they are erroneously displaying in hours instead of displaying in days. Because there is no way to select hours, instead of saying something like "due in 5 hours" it should simply say "due today" (or "due tomorrow", depending on the time of day).

**Comment by aquibm** [comment]
Hi, I've just got the project setup locally. Would love to pick this one up if it's not assigned yet.

**Comment by Alys** [comment]
@aquibm Thanks! It's yours. Comment here if you have questions or run into problems.

**Comment by mandyzhou** [comment]
I totally understand that you all are super busy, and I'm so sorry to be a bother, but I was wondering if there's an timeline for reviewing the pull request fixing this bug. The bug has been negatively affecting my workflow, since I have to manage a lot of quick-turnaround tasks, to the point that I've been looking into other to-do managers. The bug is labeled "POST-REDESIGN" and "priority: important", but the pull request is 12 days old and hasn't been reviewed yet.
