### ISSUE TITLE
Quick inventories should be centered

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9263]
The Quick Inventory is not centered, compared to the one in the Market. See http://recordit.co/uHUtzsqSlv for an example. Note that there may be other discrepancies with Quick Inventories across the site.

**Comment by marceltn** [comment]
I could not reproduce it. For me is already centered.

![image](https://user-images.githubusercontent.com/3443711/32102740-6e4a4de0-bafc-11e7-8624-6df428f107e0.png)
![image](https://user-images.githubusercontent.com/3443711/32102743-7162a84c-bafc-11e7-8c44-e334921c7b0a.png)

**Comment by citrusella** [comment]
That might be because of your screen size/resolution? Here's what it looks like at 1280x800 resolution on a 13 inch monitor:

![uncentered2](https://user-images.githubusercontent.com/14182450/32137347-fc9ce996-bbeb-11e7-8666-b958db5b26c9.png)
![uncentered1](https://user-images.githubusercontent.com/14182450/32137348-fcd06618-bbeb-11e7-93c3-9a2eb94fc64f.png)

For what it's worth, your first image doesn't have a centered bar, and I'm not sure your second does either (it's certainly not centered across the whole page but might not be centered inside that part of it either).

**Comment by marceltn** [comment]
@citrusella thanks for the feedback.
I opened in a small resolution and maybe I got it the issue.
The reference to be centered is the entire window itself instead of the container (excluding the bar in the left).
**Intead of this**:
![image](https://user-images.githubusercontent.com/3443711/32172954-8746fbe4-bd64-11e7-9c3b-d12479ffb55a.png)

**Must be like this**:
![image](https://user-images.githubusercontent.com/3443711/32172967-93427e96-bd64-11e7-9853-b527ae579b58.png)

If it's the issue, the Shops:Market, Inventory:Equipment and Inventory:Stable screens are affected. And the fix must apply to all these 3, right?

@lemoness I took the base by Shops:Market screen showed in [http://recordit.co/uHUtzsqSlv](http://recordit.co/uHUtzsqSlv) but as citrusella said, seems that issue affect small resolution.
Can you advise here?

**Comment by trvrfrd** [comment]
Also curious about this issue. Some screens have an offset based on the sidebar width when "centering" the container, some center it relative to the whole screen. Which is the correct behavior? Should be an easy change either way to make them consistent.

**Comment by lemoness** [comment]
The best people to advise here are actually @paglias and @tressley!

**Comment by paglias** [comment]
There doesn't seem to be different css for the drawer in those pages but there's this comment in the market page that indicates we might want to consolidate the code into a shared component

```

**Comment by paglias** [comment]
There doesn't seem to be different css for the drawer in those pages but there's this comment in the market page that indicates we might want to consolidate the code into a shared component

```      
//- @TODO: Create new InventoryDrawer component and re-use in 'inventory/stable' component.
```

For the code itself I think @negue can help

**Comment by paglias** [comment]
I think a cause of this could be that the sidebar in the stable is much larger than in the market. 
<img width="368" alt="schermata 2017-11-02 alle 09 57 08" src="https://user-images.githubusercontent.com/589911/32317538-5bf6742c-bfb4-11e7-8b17-42db65f9470d.png">
<img width="478" alt="schermata 2017-11-02 alle 09 57 20" src="https://user-images.githubusercontent.com/589911/32317539-5c113424-bfb4-11e7-8ed6-ede70c0d0371.png">

For the correct centering maybe @Tressley can help, I think they should be centered in the middle of the container (not page) but I'm not sure

**Comment by Tressley** [comment]
Correct. They should be centered horizontally in the middle of the container (not page) as @paglias outlined above. And yes, it does look like the Stable has a much larger left column than the Market. The Market is actually the correct version, so the Stable should be adjusted accordingly.

**Comment by trvrfrd** [comment]
Alright, I'm diving into it and will hopefully have a PR open later today. I'll let you all know if I have any questions.
