### ISSUE TITLE
When a filter/tag is selected, it should apply to all new tasks

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9266]
When you create a task while a filter/tag is selected, it should automatically apply the filter to that new task. This is currently functioning correctly with the advanced task add (the green plus button), but not with the quick-add above each column.

**Comment by lemoness** [comment]
Matteo is working on this! I've adjusted the labels on this ticket.

**Comment by librarianmage** [comment]
@paglias Are you no longer working on this?

**Comment by paglias** [comment]
@MathWhiz no

**Comment by yomimono** [comment]
This is currently working for me in Firefox as described, and I don't like it -- usually when I have the filter view on it's because I don't want to see distracting reminders of other things I shouldn't be focusing on at the moment, and when I'm adding items it's to get them out of my head so they'll stop distracting me.  I usually want to give them a different tag or leave them untagged so they don't show up in the current filter view.

I think what I really want is a way to specify tag(s) when adding items via the quick-add boxes, rather than having them be inferred from my current view.

**Comment by TheHollidayInn** [comment]
@yomimono I can definitely see your point, but for a quick add, I think we might want to stick with this path of inference and see what others think. Maybe other admins can weigh in. We probably don't want to have many options for quick add.

Also, this is working for me on develop, so I'm closing. Feel free to open if not.
