### ISSUE TITLE
Round task difficulty value

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#9275]
The iOS app currently has an issue where it changes the trivial difficulty (value of 0.1) to a string representation of "0.10000000000005" (or something similar). This causes the api to reject the value, because it is not a valid difficulty. Unfortunately fixing this in the app would be non-trivial, so it would probably be easier to change the validation on the server side to round the task difficulty to one digit after the comma before checking if it is a valid difficulty value.

**Comment by lemoness** [comment]
I've added labels to this issue.

**Comment by zwernberg** [comment]
I'd like to give this one a shot

**Comment by Alys** [comment]
@zwernberg Thank you! However I recommend waiting for a few more hours to see if any of the other admins comment here. This is a bit of an unusual issue since it requires changing the API's correct behaviour to compensate for a flaw in the iOS operating system, so they might have special suggestions related to it. For example, I believe we should add a comment to the new code to explain why the change has been made.

**Comment by phillipthelen** [comment]
I’d like to add that this is not a flaw in iOS. It’s a floating point
error, that can also happen in other systems. Internally in the iOS app,
the value is 0.1. It’s only when converting that float to a string when
serializing it to json that the error occurs. Which is something that can
also happen with other clients. So I wouldn’t consider this making the api
behaviour incorrect, but rather making the validation more robust

-- 
Phillip Thelen
Sent with Airmail

**Comment by Alys** [comment]
From Il Mago Discorato (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) in the Report a Bug guild:

"This Fix was partially effective, it is now possible to create a trivial task, but it is still not possible to edit one, the error "validation error" appears"
