### ISSUE TITLE
"Show Bailey" must be clicked twice

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9278]
In https://habitica.com/user/settings/site , the button "Show Bailey" has to be clicked twice to actually show the Bailey. Bailey's most recent announcement should pop up after a single click.

**Comment by ghost** [comment]
I believe that this issue can be closed, as the "Show Bailey" works for me after being clicked just once. The last comment in [this PR that is referenced above](https://github.com/HabitRPG/habitica/pull/9315) seems to think that this issue was fixed in [this larger PR](https://github.com/HabitRPG/habitica/pull/9716).

**Comment by Alys** [comment]
@asherdale Thanks!
