### ISSUE TITLE
Names of Equipment visible on hover

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9280]
When you view someone else’s profile, you can see thumbnails of their equipment but no names or descriptions, including on hover or click. The names of the equipment pieces should be visible on hover. 

_edit by Alys: see [this comment below](https://github.com/HabitRPG/habitica/issues/9280#issuecomment-368189702) for a description of what needs to be done._

**Comment by EmilyOng** [comment]
I would like to take this

**Comment by Alys** [comment]
@EmilyOng Thanks! Comment here if you have questions or find problems.

**Comment by EmilyOng** [comment]
Sorry i am new to vue.js...is it something like [this](https://github.com/EmilyOng/habitica/blob/issue9280/website/client/components/avatar.vue)?

**Comment by Alys** [comment]
@EmilyOng Would you like to submit a PR for those changes? GitHub will highlight all the differences for us which makes it easier to review. :) We can give you advice then and the PR will be easy for you to update if more changes are needed. Thanks for working on this so quickly!

By the way, it looks like you have a typo: "showqeuipments" instead of "showequipments". Capitalising the second word might  be good too for clarity: "showEquipments".

**Comment by librarianmage** [comment]
Should this no longer be marked as in progress?

**Comment by lemoness** [comment]
I've updated the labels on this issue.

**Comment by Alys** [comment]
This has been fixed for the Battle Gear side of the stats section in a user's profile (when you hover, you see the name and stats of each gear piece). All that should be needed to close this issue is for the same on-hover screen to appear on the Costume side, so I'm marking this as a good first issue.

(It might seem unnecessary to display the stats on the Costume side, but I think it's good to do so for consistency and simpler code, and also it will be of use for anyone who's considering whether they want to add someone else's Costume piece to their own Battle Gear.)

**Comment by Cappycot** [comment]
I'd like to take this issue as a first for me to try out.

**Comment by paglias** [comment]
@Cappycot go ahead!

**Comment by Cappycot** [comment]
Do you guys want the pop up to be on the right or the left? The pop up stats on the equipped items show to the right, but I'm not sure if you agree with putting the costume pop up stats on the left, which is what I'm doing for now.

**Comment by lemoness** [comment]
That is a question for @Tressley!

**Comment by Tressley** [comment]
@Cappycot -- Ideally it opens at the bottom of the item unless there isn't enough space. Then it should open at the top.

**Comment by Cappycot** [comment]
@Tressley I'll go ahead and make the changes for both the equipment icons and the costume icons on the profile stats page then.

Edit: [Done](https://drive.google.com/open?id=1Cdw31lhYDXB2WjK7diD4arnOg7l6rNJZ)
