### ISSUE TITLE
Tier color chart is incorrect

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9289]
The Tier color chart located in the Tavern has many style issues. The tier icons are the wrong color and T5/6 are too big (T5/6 and T7 are supposed to be the same size square, but T7 is rotated). See a quick comparison:

<img width="311" alt="screen shot 2017-10-26 at 5 52 24 pm" src="https://user-images.githubusercontent.com/3494081/32083282-83d4b6ae-ba76-11e7-906c-fcda17efcf2b.png">

Whichever contributor volunteers to work on this issue will need to be added to our Zeplin to get all the information about the designs, so when you post to claim this issue, please also include an email address that we should use to invite you.

**Comment by melarish** [comment]
I could work on this one. Looks like the < path > elements (https://www.w3schools.com/graphics/svg_path.asp) need a little tweaking. Are the exact numbers shown in the Zeplin or do I fiddle with it until it looks right? Email is melarish@gmail.com

**Comment by lemoness** [comment]
@melarish Thank you so much! We've invited you to our Zeplin, which should have all the exact numbers for you. Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by melarish** [comment]
Thanks! I've joined the project. It only shows 3 screens on it though - Navigation/Checked into the Inn, Tasks/Habits, Tasks/Habits/Edit Tags. I can't see one for Tier Chart :|

**Comment by lemoness** [comment]
Sorry about that! @Tressley will be sure to get those screens up for you
very soon.

**Comment by lemoness** [comment]
Sorry about that! @Tressley will be sure to get those screens up for you very soon.

**Comment by Tressley** [comment]
@melarish -- You can find that mock-up in Zeplin now. Here's a link! https://zpl.io/V1yvwQE

**Comment by melarish** [comment]
So I've downloaded all the .svg files from the Zeplin but for some reason they have a `<g fill="none"` in the code which makes them have no color (it overrides `<use fill="#C92B2B"`). I'll remove that part unless anyone's got an idea why it's there?

**Comment by melarish** [comment]
How's this look? The svg's downloaded from Zeplin didn't quite turn out like on the spec so I had to do a little guesswork to get them closer to the right size. For example, the T7 icon looked really tiny with width: 8, since the Zeplin numbers refer to width before rotation.

<img width="546" alt="screen shot 2017-12-17 at 6 08 15 pm" src="https://user-images.githubusercontent.com/5783115/34087014-4e1d6c42-e355-11e7-828f-2c3098c2adbe.png">
<img width="536" alt="screen shot 2017-12-17 at 6 08 21 pm" src="https://user-images.githubusercontent.com/5783115/34087015-4ff0d720-e355-11e7-8808-63a46b53dd11.png">
