### ISSUE TITLE
Have to reload after accepting Party invite

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9296]
When you accept an invitation to a Party, you have to reload before the Party members appear in your header. They should appear instantly.

**Comment by crisryantan** [comment]
can you tell me more about this? which file and route should i look into?

**Comment by bryllej8** [comment]
When i try to click the sign up button , it displays invalid request parameters on top, you should put some validation errors at the bottom of input or make a tooltip on input. It is very important for user interaction.

**Comment by Alys** [comment]
@dscbrylle143 Can you please go to the Report a Bug guild in Habitica to describe that problem in more detail. I'm not sure it's related to this issue (if it is, we can copy your comments from the Bug guild back to here). You can reach that guild from Help > Report a Bug on the website. That's the best place to report bugs.


@xxryan1234 The best way to examine this bug is to create a couple of test accounts in the live website (delete them afterwards) or in your local install. Have one of the accounts create a party and invite the second account to it. When the second account accepts the invitation, you'll see that the website's header doesn't change immediately - it still looks like the second account is not in a party. When you reload the website, then you'll see that the second account is in a party. Let us know if you'd like to work on investigating and fixing this bug!

**Comment by TheHollidayInn** [comment]
I'm unable to replicate this. Can anyone else?

**Comment by TheHollidayInn** [comment]
Feel free to reopen if this is happening
