### ISSUE TITLE
Incorrect Experience Notification on Level-Up

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9339]
We're getting reports that when people level up, they're getting notifications saying that they lost experience. While technically correct (since their experience reset), it's misleading. They shouldn't get the experience lost notification when they level up.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by majestic-owl448** [comment]
Yes, it's still an issue
![immagine](https://user-images.githubusercontent.com/26656284/37116571-f72f3df0-224e-11e8-88ef-57cda87cb5cd.png)

**Comment by ghost** [comment]
Hey @Alys @lemoness, could I tackle this issue?

Just to make I'll do the right fix: the 'You lost some Experience' notification should be removed completely, correct? Or should it be changed to a 'You gained some Experience' notification? I'm assuming that we should just remove the 'You lost some Experience' notification because the 'Level Up!' notification already makes it very clear that the user gained experience, so there is no need for a 'You gained some Experience' notification.

**Comment by ghost** [comment]
@Alys @lemoness just a friendly reminder to see if I can work on this issue and also for my question above :)

**Comment by majestic-owl448** [comment]
My two cents on this (I have received the mail and was thinking on this): right now you can't see how much experience you gained from the task you just clicked that caused level up, maybe it could be shown that so to have the same thing happen as every other time you complete a task? (Showing experience, gold and mana gained from the completed task and the Level up! notification)
I don't even know if it's possible...

**Comment by ghost** [comment]
That make sense, and I think either solution would be good. Like you said, however, I am not sure how easy this would be to implement (I already played around with it a little bit). Maybe I can first just fix the bug that this issue references by removing the 'You lost some Experience' notification (which I have already fixed on my local install), and then we could open another issue (or trello ticket, not sure what the correct procedure is) for adding the experience notification? Let me know your thoughts.

**Comment by ghost** [comment]
@leahleen Any update on this?

**Comment by majestic-owl448** [comment]
@asherdale : I am not someone that can answer you, mine was just an idea that I brought up

**Comment by ghost** [comment]
Ok thanks @Ieahleen! @Alys can I work on this?

**Comment by Alys** [comment]
@asherdale I'm sorry, we should have replied days ago. :(  Yes, please work on this issue, thank you for persisting with it! We do want the "You lost some Experience" notification to be removed completely.

@Ieahleen is right that the best solution would be to show you how much XP you earned from the task but that is likely to be complicated. The way those notifications are created is by comparing your old stats with your new ones, not by analysing the individual events that caused the stats to change. @asherdale I think your suggestion to remove the notification now and then create an issue for a better fix is the best approach.

**Comment by Alys** [comment]
@asherdale Thanks for the fix!

I've logged a new issue as we discussed above: https://github.com/HabitRPG/habitica/issues/10297 "show accurate Experience (XP) gain in notification on level-up"

**Comment by joedragons** [comment]
> We do want the "You lost some Experience" notification to be removed completely.

Thus curious will this fix also fix the "bug" when you see this notification intermittantly when clicking a task as complete (but not leveling) or if those are distinct pieces of code.

**Comment by Alys** [comment]
@joedragons Do you mean that as you're completing tasks, you're sometimes seeing that you're losing Experience, Gold, and Mana? That means that you've had a [sync error](http://habitica.wikia.com/wiki/Sync_Errors), where your actions aren't permanently saved and are later reverted (e.g., a task becomes unticked so you lose the Experience from it). Sync errors can happen if you take several actions on the site or app very quickly, but sometimes can also happen at other times because of server problems. If you wait a second or two between clicks, sync errors are generally much less common. On the website, you can watch the purple line travel across the top of the website - when it disappears, the sync has finished and it's safe to mark another task complete.

**Comment by joedragons** [comment]
@Alys Yeah thanks, I didn't know it was a thing big enough to have a wiki=)  I assume the xp reversion will still be a thing since it's a distinct error.  But thanks for the info, doesn't really matter I suppose, I was just curious=)
