### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by ohyde** [HabitRPG/habitica#934]
Maybe i'm missing the settings option where I can change this, but as a New Zealand resident, my Monday morning tasks are not flagged as needing to be done when I get up as it seems like the server timezone is still on Sunday evening.

Sorry if this is a simple setting change that I just haven't identified.

**Comment by lefnire** [comment]
there's no timezone calculation, it just automatically picks up your own timezone since all cron javascript is run on the client, not the server. "timezone" issues are really just faulty day-diff calculations. That said, I think I fixed this issue https://github.com/lefnire/habitrpg/commit/92b178b4a41eb96e24449f1bef3e379e85590bae - re-open if you encounter this bug again
