### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by dmagracia** [HabitRPG/habitica#935]
After the tags feature got put in, I can no longer see any part of my HabitRPG other than the Tag feature, my avatar, and related health and experience bars. (I can also see my party member).

Attached is a screenshot of my page
![habitrpg](https://f.cloud.github.com/assets/4006608/493679/414c4c10-bb62-11e2-9ae1-18c46143a5a3.png)

**Comment by dmagracia** [comment]
Also, when I click on my avatar I can no longer see the menu for the Market, my Inventory, or other related things. Nothing happens other than the Tags feature goes away and comes back on consecutive clicks of my avatar.

**Comment by zoebeagle** [comment]
I don't mean to insult, but have you tried Refreshing the page already?

If that doesn't work, can you try clicking on the pencil icon, adding a tag, and then saving?

**Comment by dmagracia** [comment]
No insult taken; I'm aware that there are idiots on the internet who do not know how to refresh a page. However, I've accessed the page on different days at different times, and after the fifth time I decided to post about the issue. When clicking the Edit Tags button, it only refreshes the page and everything looks the same.

**Comment by lefnire** [comment]
user id? i've seen this before, but i need to get into the account to fix, and hopefully provide a workaround for anyone else encountering the issue

**Comment by dmagracia** [comment]
8b32be40-9b82-4a26-962d-3a43a661d32d

**Comment by lefnire** [comment]
Got it, you should be fixed now

**Comment by lefnire** [comment]
very strange, what happened was when we migrated to the new pets system, for some reason your `user.items.pets` property remained an object instead of being migrated to an array. Heart skipped a beat when I saw that, "how many users are experiencing this!" and I did a database test - just the one account. Don't know how that happened, but I fixed it and did a simple sanity check in the pets display so it won't show an error again.
