### ISSUE TITLE
Skills should immediately affect player casting the skills in header and profile screen

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9351]
When you cast skills that affect your party and hover over their images to see if it took affect, their info bars don’t change until you’ve refreshed the page. This change should take place immediately.

**Comment by kartikadur** [comment]
I'd like to work on this issue if its still available.

**Comment by TheHollidayInn** [comment]
Go for it :D

**Comment by kartikadur** [comment]
thanks, is there anything I should know before or while working on this issue?

**Comment by TheHollidayInn** [comment]
The main logic is here: https://github.com/HabitRPG/habitica/blob/develop/website/client/mixins/spells.js#L33

So, either the party store is not being updated or the header is not reacting to changes correctly.

**Comment by beffymaroo** [comment]
@kartikadur Are you still working on this? Please let us know. Thank you!

**Comment by kartikadur** [comment]
@beffymaroo - I do want to do this, but I am currently handling a few pressing concerns. Let me know if there is someone else who wants to solve this.

**Comment by beffymaroo** [comment]
@kartikadur Thank you for responding! If you think you will not be able to get to this within the next month, please let me know so I can change the status to "Help Wanted".

**Comment by kartikadur** [comment]
@beffymaroo No worries, I was planning on hopefully getting around to it by the end of this month, but should that seem impossible I'll definitely let you know.

**Comment by kartikadur** [comment]
Nothing yet, I'm dealing with the logistics of shifting to a new job, so I
wont be able to deal with this for a few months at best. If someone else
wants to work on this let them have it. I'll work on something else when I
have time in the near future.

**Comment by beffymaroo** [comment]
@kartikadur OK! I am changing the status to "Help Wanted", but if you find time and it's still available when you come back you're welcome to claim it again. Thanks for the update!

**Comment by Alys** [comment]
I'm just noting here that this problem is still occurring, and that as part of it the Healer's own health will also not be updated immediately, as reported by @Aerilita:
_"On the website, when I use Healer's Blessing skill my HP won't change until I sync."_

That's an expected effect of this bug although it does look like it's a separate bug since the Healer's displayed Mana updates immediately.

The Healer's displayed health is not updated immediately because the Healer is processed along with the rest of the party members in a separate action after the Mana has been subtracted.

Whoever works on this issue should ensure that the Healer's displayed health is updated by their fix; it might need to be handled as a special case since it's displayed by different code than the other party members.


(I'm deleting some older comments to tidy up this issue; they were all discussions about a previous claim on the issue and didn't contain technical details. Hopefully the shorter comment thread will make this issues more attractive to work on. :smile:)

**Comment by Alys** [comment]
I've deleted some older comments to tidy up this issue; they were all discussions about a previous claim on the issue and didn't contain technical details. Hopefully the shorter comment thread will make this issues more attractive to work on. :)

**Comment by veeeeeee** [comment]
Because the solution for this may result in additional server load, staff will be taking another look at the best approach.

**Comment by paglias** [comment]
Going to tackle this one

**Comment by paglias** [comment]
So after some investigation:

1. The API has all the info needed to update the party members but its results are not used
2. That being said I just tried to use the `heal all` spell and the results were applied correctly to the party members without a refresh because the spell is also run on the client https://github.com/HabitRPG/habitica/blob/develop/website/client/src/mixins/spells.js#L117 

The only exception seems to be for cards and for the healer's own HP as noted by @Alys

**Comment by Alys** [comment]
I'm seeing the same as @paglias for several of the party buff skills I've tested. When you view a party member's on-hover stats or profile (not your own stats/profile) you see the correct data immediately. For cards, I am also seeing the party member's achievement count being updated correctly.

The person casting the buff is not updated immediately, either for their stats changed by the buffs or for their card achievement numbers, so yeah, I guess this issue just needs the special case handling I mentioned. 

I'm about to change the title.
