### ISSUE TITLE
Sorting by Stat does not include class bonus

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9356]
On the Equipment page, when you sort your equipment by a stat, like perception or strength, the sorting does not take the class bonus into account of the class, only the raw bonus. This results in an incorrect recommendation. It should include the class bonus.

**Comment by negue** [comment]
@lemoness Should the popover of each equipment item also show the class bonus? 

currently it just lists the gear (raw) bonus

**Comment by Alys** [comment]
My thoughts are that once sorting includes the class bonus, the bonus should be listed in the popover otherwise the sorting will look buggy.
I'd like to see it listed separately from the base stat, so that the base stat can still be seen - that will avoid problems with users getting confused about equipment stats changing when they change class, or confused discussions between users where they disagree about what stats one particular piece gives.

**Comment by lemoness** [comment]
Attn: @tressley
