### ISSUE TITLE
Can't View Check-Ins for other users

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9359]
Currently, when you open a user's profile modal, the area that is supposed to show their number of Check-ins is broken and does not display. This should be fixed.

**Comment by kartikadur** [comment]
I'm working on another issue, but can I claim this as well?

**Comment by lemoness** [comment]
@kartikadur Yes, you can! Just be sure to let us know if you can't finish it. Thank you!

I've updated the labels on this ticket.

**Comment by kartikadur** [comment]
Thanks @lemoness.

Is there anything I should know before beginning work on this? like which files to touch, unit testing, etc.

**Comment by kartikadur** [comment]
@lemoness 
Is `loginIncentives` or `achivements.habitica` from `user.data` responsible for tracking user checkins? or am I completely off in that I will I have to manually calculate this value?

**Comment by Alys** [comment]
@kartikadur  `loginIncentives` is the number of check-ins.

**Comment by kartikadur** [comment]
Thank you.

**Comment by kartikadur** [comment]
Sweet yeti of the serengetti, this is a lovely little rabbit hole of a problem. I might need permission for this one because a parameter to backend api calls might need a slight adjustment.

+ There are about 5-7 pages that use / call the `habitica:show-profile` event to display user profiles.
+ For users other than the loggedIn user an api call to `/api/v3/members/:memberId` is made.
+ This api returns a set of public fields from user models as listed below:
  + `preferences[size, hair, skin, shirt, chair, costume, sleep, background, tasks]`
  + `profile`
  + `stats`
  + `achievements`
  + `party`
  + `backer`
  + `contributor`
  + `auth[timestamps]`
  + `items`
  + `inbox[optOut]`
+ This data is then shown on the profile modal

User checkins were not showing because the data element isn't retrieved. The simple solution would be to add `loginIncentives` to the above data set in the api calls. And since checkins aren't exactly private member data AFAIK it shouldn't cause much of a problem.

**Comment by kartikadur** [comment]
@Alys, @lemoness is there an alternative opinion on how to handle this or could I implement my proposed solution?
