### ISSUE TITLE
Editing Challenges that aren't yours

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9391]
It appears that you can edit tasks from a Challenge that is not yours -- the edits do not actually stick upon refresh, but you shouldn't be able to edit them at all.

_edit by Alys:_

As an example of this problem, when you have joined a challenge and you see a task from the challenge in your own tasks list, you can click on that task to open it for editing (which is correct), but you can then change the title, due date, difficulty, and possibly other fields that you shouldn't be able to edit. Those fields should be greyed out and/or not able to be clicked on.

The list of fields that the challenge participant SHOULD be able to edit is on the wiki at [Challenges > Challenge Participant's Permissions](http://habitica.wikia.com/wiki/Challenges#Challenge_Participant.27s_Permissions)

The list of fields that the challenge participant should NOT be able to edit is at [Running a Challenge > Challenge Creator's Permissions](http://habitica.wikia.com/wiki/Running_a_Challenge#Challenge_Creator.27s_Permissions)

If you come across any field that isn't listed in either of those pages, please comment here!

Note that the API prevents those fields being changed permanently so the only fix needed for this issue is a client-side one - i.e., make it obvious to the challenge participant which fields they can't edit.

**Comment by Alys** [comment]
As an example of this problem, when you have joined a challenge and you see a task from the challenge in your own tasks list, you can click on that task to open it for editing (which is correct), but you can then change the title, due date, difficulty, and possibly other fields that you shouldn't be able to edit. Those fields should be greyed out and/or not able to be clicked on.

The list of fields that the challenge participant SHOULD be able to edit is on the wiki at [Challenges > Challenge Participant's Permissions](http://habitica.wikia.com/wiki/Challenges#Challenge_Participant.27s_Permissions)

The list of fields that the challenge participant should NOT be able to edit is at [Running a Challenge > Challenge Creator's Permissions](http://habitica.wikia.com/wiki/Running_a_Challenge#Challenge_Creator.27s_Permissions)

If you come across any field that isn't listed in either of those pages, please comment here!

Note that the API prevents those fields being changed permanently so the only fix needed for this issue is a client-side one - i.e., make it obvious to the challenge participant which fields they can't edit.

I'm going to copy this to the top post to make it unmissable.
