### ISSUE TITLE
Change Static Page Donation Button to Contribute Button

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9399]
The Donation button on the Static Pages should instead say "Contribute" and should link to the following Wiki page about contributing: http://habitica.wikia.com/wiki/Contributing_to_Habitica

**Comment by rcmbal** [comment]
I'd like to take a look at that.

**Comment by Alys** [comment]
@rcmbal Thank you! Post here or in your pull request if you have questions or run into trouble!

**Comment by rcmbal** [comment]
One or two strings need to be replaced:

- Should `companyDonate` just have the contents changed ("Donate" to "Contribute"), or should the label be changed as well? Both options would work, since `appFooter.vue` is the only instance of `companyDonate`.

- Should the link to the contribution wiki page be hard-coded, or should another string containing the URL be added, since the page itself is multi-language?

**Comment by Alys** [comment]
> Should companyDonate just have the contents changed ("Donate" to "Contribute"), or should the label be changed as well? Both options would work, since appFooter.vue is the only instance of companyDonate.

Normally when text changes, we don't change the label as well, but in this case since it's used in just one place and the meaning of the text is significantly different now, I think it's worth changing the label too. 

However, I think the intention of this issue might actually be for the "donate" button that you see **after** you've logged in to remain as it is now (i.e., still say "Donate" and still point to the subscription / gem screen). I think the button needs to be changed only on the pages you see **before** you've logged in (those are referred to as "static" pages because they don't change based on user information). @lemoness Can you confirm that?  If that's right, then we want to keep the `companyDonate` string and add a new `companyContribute` string.

> Should the link to the contribution wiki page be hard-coded, or should another string containing the URL be added, since the page itself is multi-language?

The wiki URL should appear in a string, not be hard coded.

@rcmbal Thank you, good questions!

**Comment by lemoness** [comment]
Hi @rcmbal, thanks for tackling this! As for whether or not the Donation
button should remain the same before and after you log in, for now just do
whichever version is easiest. So if it's simpler to have it say
"Contribute" in both places, that's okay!

**Comment by librarianmage** [comment]
Should this be closed?

**Comment by TheHollidayInn** [comment]
Yep!
