### ISSUE TITLE
Degree of Hardness

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#94]
_Edited by wc8: See [Importance, Priority](https://trello.com/c/4C8w1z5h)_
Each habit,daily,or task should be assigned a level of difficulty. Whether this be a scale from 1-10 or hard extremly hard etc is up for grabs. I am just putting this out there.

**Comment by Aergonus** [comment]
I noticed a lack of timed options, as in this must be completed by 8:00AM Thursday January 17th 2013 (To-Do feature). It adds in the functionality of a scheduler which is what I thought this essentially was. A level of difficulty would compliment this well. Some projects can gain experience based on the number of hours you put in. As in, big project like coding this one can take time. Working on it for 3 hours instead of 1 should be better rewarded. Maybe add this as an extra feature for habits or daily? For longer projects like a weeklong project include functionality to add to habits/daily for days January 1st to January 8th for example. This could be covered by the input hours for experience. Eventually when the person finishes that task, there can be a bonus experience boost for completing it. Two inputs: One for time spent and then one checkbox to complete that project. (If it's completed early big bonus? Defeat procrastination) The analogy I would make to RPGs would be quests like "Slay x number of Birds." You get small bonuses for working on it and then the reward for finishing it. 

For rewards, if you were able to get companies to "sponsor" you with small free stuff for users to get as prizes, that could benefit everyone. 1. A reason to use the app for users. 2. A source of income and more popularity for you. 3. Advertising for Companies This was kinda inspired by the reward of an hour of Game of Thrones. So the reward would be a real reward, maybe a special clip or a coupon for something?

**Comment by JamPol** [comment]
I disagree. I enjoy the current system, it forces the user not to put off any tasks. It's a lot like Jerry Seinfeld's "don't break the chain" method. As soon as you start adding difficulty, you may put off a simple long overdue task for even longer (prime example for myself is "make dentist appointment"). The other side of this is difficulty could easily be changed by the user for example by rather than saying "Finish writing paper", breaking it down into steps "Finish writing introduction"

For the most part at the end of the day it's the user that's going to have to be honest with himself using HabitRPG.

The reason to use the app is to form habits and get'r done. I think the app will sell just fine already, the loss of HP by avoiding tasks already add's a layer of depth that makes HabitRPG much more enjoyable than all the other app's that attempt to accomplish the same "RPG" aspect. A real reward... this system would get incredibly abused by cheaters.

Any who, maybe I'm just blinded by love of what HabitRPG has already accomplished.

**Comment by ghost** [comment]
@JamPol I am going to have to agree with @Spellchaser I think his idea is likely to succeed in keep people doing their habits.

**Comment by Aergonus** [comment]
The difficulty system should compliment the system. Long overdue tasks have a better experience yield for doing them. Adding in a difficulty specification will help people work on things that are hard. Overdue tasks have an inherent experience gain for being overdue. What's gonna stop you from completing a simple task like brushing your teeth instead of exercising if they both give you the same reward? 

Adding in many steps is almost a time waster. I spent way too much time making to do lists as it is. Adding in the fine details for everything is just too much for me. If anything, I'd ask for the difficulty option to be added for those who want it and will use it.  Different people respond to different incentives. If this project is truly dedicated to helping people then this would be an invaluable feature in my opinion.

Oh, extending the app's functionality to work as a scheduler should be really easy. If it's good, why not make it better? There's so much that can be done. 

Cheaters... If this app was free, then it'd be a waste in a way. It depends on how you look at it. The cheaters will add to the user base and can promote the app. The advertisers get exposure (I was thinking a real reward would be a free clip or coupon?). If the point is to help someone, cheaters (despite being scum) would help it out. With anti-cheat measures like checking for unusual fast clicking, cheaters would have to be invested to cheat for actual rewards. The rewards shouldn't be easy to get. If the max difficulty is 10 and gives you 10 coins, real rewards can be 1000 coins for ex.

If you're creating something that's good, I believe people will appreciate it. This project has a great underlying ethos... or pathos? The goal is honorable and admirable. It's a project that will help others. A focus on marketability or payoff undermines that, at least for me.

**Comment by JamPol** [comment]
Hmm I see your point a bit clearer. I hope this app isn't free though, even if it's only $.99 the developer should see some spoils for his hard effort.

I certainly agree with you now that breaking down tasks would be a huge time sink.

I think I've got the best of both our ideas though. For To-do's have an adjustable difficulty, but for daily/habits have the reward increase. So for instance "brush teeth" could increase in reward value for completing everyday to a certain reward cap, but if the user misses a day, the reward goes back to the starting value.

Issue with the rewards would also be due to app stores usually being worldwide. So I believe legal issues/products not being available in a particular region would be an issue. Great incentives can come in other forms such as achievements, the friend challenging aspect which will be added, and so fourth. I don't think marketing will be a huge issue due to the amount of productivity blogs on the web alone. A great app will easily spread by word of mouth.

Ethos I believe.

-Edit-

Sorry I hadn't watched the Kickstarter video and I see now that the app will be free with possible digital items to buy which is awesome. I think I need to create a reward to "spend time on github".

**Comment by Aergonus** [comment]
OOoooh! I had an idea! What if it was just cool stuff. There's the game that went out that promises to show the person who breaks the last block a message. If people submitted cool stuff (links to pictures. inspirational gifs, etc) and they became implemented as rewards, it's be something interesting. Plus you wouldn't be wasting time going through the junk on social sites like Reddit!

Edit: http://youtu.be/giEykqDoUCQ Curiosity was the game I was referencing. Kinda the same idea except more often?

**Comment by JamPol** [comment]
Cool idea, cool idea.

Another good concept is Valve's Team Fortress 2 where you certainly can buy items off the store, but also you get a limited number of random drops per week as you play. Item's are tiered with common items more likely to drop, and hat's being the hardest to get.

Similar situation might work with a limit of a couple items per week which randomly drop as you earn points during the week. So there's something like a 95% chance you're going to get a common item, but the player still holds hope and occasional get's a 5% chance item for their character.

**Comment by horusofoz** [comment]
To keep things simple, implement a 1-3 priority system for tasks. 

New tasks are automatically assigned lowest priority (3) and user can raise if required. Algorithm already in place for defining urgency/reward of tasks (whether it's green, red, etc) can just have a multiplier added based on priority.

Easy solution for dev to implement. Easy to understand and use system for users.

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
@Spellchaser & @JamPol see #181
