### ISSUE TITLE
Task Error in Group Plans

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9425]
Group plans:  When you are viewing tasks in the guild’s task management page, if you try to complete a task there, you see the error message “task not found”. It should say something along the lines of “you need to claim this task and then complete it in your own task list”.

**Comment by TheHollidayInn** [comment]
This was actually disabled a while back. You can't complete a task there.

**Comment by lemoness** [comment]
Yes, that's why the error message needs to be changed, so that it's more accurately describing what action you need to do.

I'm open to suggested wording, but for now, possibly: "Can't complete a task from the Group Dashboard"?

**Comment by TheHollidayInn** [comment]
By disabled, I mean you can't get the message to show. Clicking shouldn't work at all. Are you able to click? (could be a browser thing)

**Comment by Alys** [comment]
There's a comment that might be related to this in another bug report: https://github.com/HabitRPG/habitica/issues/9515. liandri was reporting a bug with deleting Group Plan tasks and as part of that they said:

"... Open [a Group Plan task], assign to self to avoid "Task not found" error ..."

Based on that, it sounds like you might get the "Task not found" error whenever you try to modify a task in the Group Plan's task list unless that task has already been claimed by you. But that's just a guess. I have not tested it.

**Comment by TheHollidayInn** [comment]
Yea, I did fix some issues with claiming, so that could be what you are referencing.

**Comment by Alys** [comment]
The current situation is that when you are viewing the "Task Board" page (https://habitica.com/group-plans/<group-id-goes-here>/task-information) in a group that has a Group Plan, if you click on the checkbox or plus/minus buttons or Reward coin, literally nothing happens (no error message, no change in the task, no feedback of any kind). This behaviour is technically correct ("The best kind of correct!") because those clicks shouldn't work, but Group Plan members are often confused about how to use the tasks so I think it would be more helpful if they saw a message explaining the problem and solution, such as something like "You can't complete a task from the Group's Task Board page. Please claim the task to add it to your own task list."

I'm throwing this to @lemoness / @Tressley for design or closure as desired.

**Comment by lemoness** [comment]
I think we should have an informative error message, so let's leave this ticket open for now.

**Comment by TheHollidayInn** [comment]
How about a tooltip? Since right now, clicking seems to show the action is disabled.

**Comment by Tressley** [comment]
I think a tooltip on the checkbox zone should be sufficient for now. 👍

**Comment by beffymaroo** [comment]
@Tressley @TheHollidayInn Is this still an issue that might be on hold pending design?

**Comment by Tressley** [comment]
@beffymaroo -- It shouldn't be. I think the solution was just to use a tooltip. We'll probably just want copy for it.

**Comment by beffymaroo** [comment]
@TheHollidayInn @Tressley maybe this should go back to Help Wanted status then?
