### ISSUE TITLE
Firefox - Difficult to edit checklists

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9430]
In Firefox, when editing checklists, the cursor turns into a cross with arrows in all four directions so that you can move the whole item up and down to a different position in the list. However, this makes it impossible click into the text to change it, since the cursor only appears at the very end of the checklist entry. Instead, when hovering over the text entry, you should have a normal mouse cursor.

**Comment by pcvonz** [comment]
Hey, can I take a look at this? 
I'm using Firefox nightly and although the cursor changes it doesn't make it impossible to edit the checklist item. Which version of Firefox should I test with?

**Comment by lemoness** [comment]
@pcvonz Thank you for investigating! I'm not sure which versions of Firefox cause this issue, but it should only be the arrow cursor when it's next to the draggable section. We also have some related reports on Firefox of people not being able to click the (+) to add a new checklist item because of the cursor issue, so it would be helpful if you could look into that, too. Let us know if you have any additional questions!

I've updated the tags on this issue.

**Comment by pcvonz** [comment]
I've come across a couple things. 

1. I've tried in Chrome/Chromium, Firefox Developer, and Firefox 52b and every text input of the checklist item will show the draggable cursor on hover. The reason is this line in the taskModal component https://github.com/HabitRPG/habitica/blob/061968dd1aabe66339422d42b473089ed9c6f128/website/client/components/tasks/taskModal.vue#L463 Changing that from `move` to `text` will fix the issue. [Pull request here](https://github.com/HabitRPG/habitica/pull/9443)
2. The plus button of the checklist item isn't clickable because it's a background image. Should I open up a new issue to change it from a background image to a button?

**Comment by lemoness** [comment]
The second question is something for @Tressley to answer!

**Comment by pcvonz** [comment]
I was adding some checklists to one of my tasks and noticed that the problem is more complicated than I originally assumed. If a checklist item is longer than the input box it's easier to see what @lemoness described originally in Firefox. The reason it appears not editable is that the cursor is placed at the end of the input box. The solution is to pass a handle to the sortable js directive. 

Is there a reason the the Vue variant of SortableJS wasn't used?

**Comment by pcvonz** [comment]
Ok, I was able to fix this issue with `vuedraggable`. If there isn't a strong reason for using the custom `sortablejs` directive, I think this is a better all around solution. Let me know and I'll submit a pull request!

**Comment by paglias** [comment]
@TheHollidayInn might some some inputs about this

**Comment by Tressley** [comment]
@pcvonz - The Plus is not supposed to act as button, but as an icon for the checklist item you are currently adding. The behavior is similar to that of Google Keep.

I understand the confusion in how green is suggesting an action. I think changing the fill color of the Plus SVG to  `#878190` helps.

**Comment by pcvonz** [comment]
@paglias Still waiting to hear back whether we want to replace the custom sortablejs directive with the vuedraggable component. If not, I can continue working on the issue.

**Comment by TheHollidayInn** [comment]
I just wasn't aware of Vue Draggable. Seems fine to me, but we need to ensure the events are triggered and handled correctly. Also there are cases (or maybe just a case) where we don't allow sorting because the tasks are presorted. For example, the todos being sorted by date should not allow for dragging.

**Comment by pcvonz** [comment]
The directive works well but I don't think there is a way to provide arguments to a custom directive. I'll start replacing the sortablejs directive with the Vue Draggable component. 👍
