### ISSUE TITLE
Armoire item seemingly incorrect

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9432]
The Armoire can tell you the right thing in the notification it gives you, but then you see the wrong thing on the website for a while, and then later the wrong thing disappears and the right thing reappears. We’ve seen enough reports like that to be pretty sure it’s happening as I describe.

**Comment by Alys** [comment]
I've done tests to confirm that this is a real bug, not users being mistaken about what they've been given.

In my tests, each time I used the Armoire, a server-side change gave me food or equipment or XP and I saw a notification that I spent gold and another notification of the item that I was given. Examining my user document in the database showed me that the notification was always correct.
After each test, when I viewed my inventory on the website, I would always see the item that I had been given but I would also see a second item (food or a different piece of Armoire gear). That second item was never shown in my user document in the database and when I clicked the sync button, that second item disappeared. I.e., the second item had been added as a purely client-side change.

It's that second item that is causing the users to report bugs (very often).

It's because of this code:

https://github.com/HabitRPG/habitica/blob/d9830950aacc3343d708eccd1a2a33c585e797de/website/client/store/actions/shops.js#L42-L48

The `buyResult` from the `axios.post` code contains the correct item, as you'd expect.
The `buyResult` object from the call to `buyOp` contains the incorrect client-side item. However `buyOp` is currently necessary to give the notification of gold spent.

What's the best way to fix this? For example, get rid of `buyOp` and do another `snackbars:add` for the gp notification?

**Comment by paglias** [comment]
Does the server return the correct gp data? In that case we could get rid at all of the client side code and just rely on the server result

**Comment by Alys** [comment]
The server doesn't return the gold spent or change in gold at all, but we could take the gold price from the Armoire's content data.

**Comment by paglias** [comment]
Yeah using that sounds good to me

Il 11 Nov 2017 12:31, "Alys" <notifications@github.com> ha scritto:

**Comment by Alys** [comment]
This bug is back because https://github.com/HabitRPG/habitica/pull/9474 reintroduced some of the code that I removed in https://github.com/HabitRPG/habitica/pull/9463

In addition, because that old code is back while the rest of my fix is still in place, we now have a new bug where the Armoire gives you two notifications that you spent 100 gp (although only 100gp is actually spent).

The partial reversion of #9463 has fixed https://github.com/HabitRPG/habitica/issues/9527, but this bug (9432) is much more annoying. It leads to repeated reports from users that they have lost equipment because they have been seeing equipment that they were never actually given.

In a couple of days when I have a bit more time, I'll restore my full fix from #9463 (unless someone else restores it first or comes up with a better fix). We can then fix #9527 as a lower priority.

**Comment by Alys** [comment]
This should be fixed by the PR(s) linked above. If not, we'll just reopen the darn thing again. The bug that will not die.
