### ISSUE TITLE
Going directly to /logout doesn't clear the local login status

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9438]
If an user goes directly to /logout without passing from the button on the website they'll be logged out from the server but the client will still think that they're logged in.

The problem is that the /logout link must be reachable on the server, one option could be to rename the logout route on the server to something difficult to type or to require some weird query parameter to be passed that cannot be guessed.

**Comment by Vishesh-Gupta** [comment]
@paglias  & @lemoness - I would like to know if anyone is working on this issue. Also how hard would this be as I do not have much experience working with open source projects

**Comment by paglias** [comment]
@Vishesh-Gupta no one's working on this but if you don't have any experience this is likely not the best issue to tackle

**Comment by pollaro** [comment]
I've started looking at this, and I'm new to Vue. I see that there's a isUserLoggedIn in store and checked in the Vue routes, but I never see where it's changed to true. Couldn't we just have that query the session?

**Comment by TheHollidayInn** [comment]
I believe that is updated in the `Store`. Yea, we could query the cookie in the store the same way we query the local storage. 

But I think what we are wanting with this fix is to change the `/logout` route on the server to something like `/logout-server`. This way, we can just set a request to that route to remove the cookie when a user logs out. And, if the user happens to type `habitica.com/logout` we won't have problems because Vue will now handle that route.

Although, do we even use the cookie session? I'm inclined to remove it as we use tokens and eventually move to a better token auth.

**Comment by pollaro** [comment]
Ok. I'll give this a go and see what I can do with it.

**Comment by TheHollidayInn** [comment]
Thanks!
