### ISSUE TITLE
Updates to the Equipment Page

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9458]
We need to implement some changes to the Equipment page based on feedback from users, as well as to reinstate the Unequip All buttons!
<img width="718" alt="screen shot 2017-11-09 at 7 15 52 pm" src="https://user-images.githubusercontent.com/3494081/32641608-d223d5ac-c583-11e7-8fa3-643a71a629b6.png">
<img width="717" alt="screen shot 2017-11-09 at 7 16 48 pm" src="https://user-images.githubusercontent.com/3494081/32641609-d26ec0b2-c583-11e7-8198-57fd12266e47.png">

Whoever works on this ticket will need to be added to our Zeplin so they can get all the full designs and talk with @Tressley about the details, so we'll need to know which email address to invite.

**Comment by Tressley** [comment]
@lemoness -- In addition to the page-level updates, there are design changes to the Drawer component that are a bit more technical. Would you like to break that out into a separate issue? It specifically touches on Drawers that have tabs (e.g. Quick Inventory.)

**Comment by librarianmage** [comment]
As far as I can tell, the updates include:

* Adding a Battle Gear / Costume switcher at the top of the page
* Adding Unequip Battle Gear / Remove Costume, etc. buttons
* Moving the BG / Costume switcher in the action drawer to the title of said drawer
* Adding an overlay when the costume is disabled

is that correct?

**Comment by Tressley** [comment]
@MathWhiz -- Good eyes! Your list pretty much hit all of the changes. There are a couple more to add.

- "You have disabled your costume" design message has been revised.
- "Auto-equip new" and "Use costume" have been pulled from the drawer and added as page-level controls.
- The tabs being included in the drawer header is only when the drawer is open. Otherwise it'll keep the same closed state design.

**Comment by librarianmage** [comment]
I'd like to try this, but I don't know if I can actually do it.

**Comment by lemoness** [comment]
@MathWhiz I'll assign it to you for now, but let us know if you hit a wall. What email address should we invite to Zeplin?

**Comment by MathWhiz** [comment]
If you're able to get it easily, the one connected to my Habitica account.

**Comment by lemoness** [comment]
I've passed it along to @Tressley, so he will invite you soon!

**Comment by Tressley** [comment]
@MathWhiz -- Zeplin invite sent your way. You can find the Zeplin artboards here:

- **Equipment/Battle Gear:** https://zpl.io/bzw8GYX
- **Equipment/Costume:** https://zpl.io/bAOmXGp
- **Equipment/Drawer Open/Battle Gear:** https://zpl.io/agg8LG0
- **Equipment/Drawer Open/Costume:** https://zpl.io/25NEKgW
- **Equipment/Drawer Open/Costume/Disabled:** https://zpl.io/2jpZXl6
- **Equipment/Drawer Closed:** https://zpl.io/adRxqAl

**Comment by Alys** [comment]
When this issue is resolved, https://github.com/HabitRPG/habitica/issues/8781 should be taken off hold.

**Comment by MathWhiz** [comment]
Uh oh! The invite didn't work for me. Can you please invite me again? @Tressley

**Comment by Alys** [comment]
@Tressley Can you invite me to the project too, as well as MathWhiz? alys@habitica.com

Can we use better wording for "You have disabled your costume"? All players start with the costume off by default, so they will see that message as soon as they go to the Costume tab, which will be confusing and misleading since they themselves haven't disabled anything. Also now that the "Use costume" toggle is in a completely different part of the page, it's going to be hard for them to work out how they can enable the costume. Can the message please explain that? Something like "Your costume is disabled. Enable it by clicking 'Use Costume' at the top of this page." would be more helpful.

**Comment by Tressley** [comment]
@MathWhiz / @Alys -- I believe you are both members now. Please let me know if there's still an issue!

As for the wording, I'm not opposed to clearer wording. I like what you've suggested, but will tag-in @lemoness for copy approval.

**Comment by lemoness** [comment]
I like the wording that Alys has suggested!

**Comment by lemoness** [comment]
@MathWhiz Hi there! How is it going with this ticket?

**Comment by MathWhiz** [comment]
Hi @Lemoness! This has been going along, though I am a bit stuck on how to
get the drawer working properly.

**Comment by lemoness** [comment]
Okay, thanks for letting us know! If you have any specific questions feel free to ping our devs and we'll help as best we can :)

**Comment by MathWhiz** [comment]
Will do!

**Comment by mbiondi17** [comment]
I'd like to help out here if I can, but I also think it'd be useful to have a small reminder on the pop-up bar at the bottom of the equipment management page letting the user know if they're editing their equipped items or their costume.
<img width="1547" alt="current" src="https://user-images.githubusercontent.com/8240725/47182501-9a280500-d2f3-11e8-960c-a9080bea0caf.PNG">

**Comment by paglias** [comment]
what do you think @Tressley ?

**Comment by Tressley** [comment]
This is actually something that's been accounted for in the designs, but was not included in the initial post. When the user has the drawer collapsed, the active tab is displayed in the drawer header.

![image](https://user-images.githubusercontent.com/2686586/47293264-a2c05a00-d5d7-11e8-889b-c46aa6a9dc64.png)

**Comment by Alys** [comment]
The work currently required for this issue is in progress [EDIT: no longer in progress; this issue is open for someone else to take up now], and once it's gone live we'll be able to tell from Tavern/guild posts whether it's helped enough to avoid the Costume vs Battle Gear confusion that players have. If there's still confusion, I'm guessing that more adjustments would be planned so I'm copying here a post that thebat137 (dea8a9e8-c084-438a-9a14-7fe96a73fd0a) made in the Report a Bug guild:

_"By the way, I ran into another small issue just now when clicking on your chat icon to see the components of your lovely costume. The stats modal that displays shows your "Equipment" and your "Costume", and it wasn't immediately clear to me why your "Equipment" was the thing I can actually see you wearing, while your "Costume" was clearly not the thing I could see. I eventually realized that you must have both Equipment and a Costume configured, but with the "Use Costume" selector turned off. It seems like it would be nice if, when a user is doing this, the header and equipment piece labels for the "Costume" section of that modal were maybe grayed out and the header was changed to something like "Costume (Unused)" to make it a little more obvious what's going on."_

**Comment by Alys** [comment]
I've removed some old comments that were just related to claiming this issue and getting access to Zeplin, just to make it easier for us to review the requirements. All technical and design comments are still present.

If anyone wants to claim this issue, post here and say what email address you'd like us to use for inviting you to Zeplin to see the design (if you don't want to make your email address public, you can tell us to use the address that's in your Habitica account and we can read it from there - just tell us your account's Username or User ID).

**Comment by paglias** [comment]
@Tressley is this something that we still want / have to implement?

**Comment by Tressley** [comment]
@paglias -- No. This issue can be closed. The work @negue has been doing on
Inventory and Equipment accounts for the feedback in this issue.
