### ISSUE TITLE
Skills cannot be cast more than once within a 10-second window

### ISSUE THREAD

**Issue by garkbit** [HabitRPG/habitica#9467]
### General Info
  * UUID: f744cbeb-05cf-434b-9388-ff01282e34d1
  * Browser: Chrome v62
  * OS: OSX 10.12

### Description
Casting a skill requires a looong round-trip (~10s) from the server confirming that a cast was completed before casting a second time will be effective. However, the UI happily gives the impression that you have successfully cast, until one of the `POST` requests returns, whereupon your mana for the casts in excess of 1 during the ~10-second window are refunded. Examining stats indicates that a single instance of the skill was applied, regardless of how many times the button was pressed.

Functionally, this makes casting skills a pain, especially in a group where mana is replenished quickly.

#### Console Errors
No console errors, however `POST` requests to the `/cast` endpoint are taking ~10s or so.

Screen capture illustrating the problem:
[cast.mov.zip](https://github.com/HabitRPG/habitica/files/1468227/cast.mov.zip)

Note the following in the screen capture:
- Mana starts at 410
- 'Valorous Presence' is cast 3x
- 60 mana deducted
- ~10s later, one of the `POST` requests returns
- 40 mana is refunded, leaving me with 390 mana, and Valorous Presence applied once

**Comment by Alys** [comment]
This is one example of a more general behaviour across the website where any time you take several actions too quickly, not all actions are recorded permanently. See the wiki's [Sync Errors](http://habitica.wikia.com/wiki/Sync_Errors) page for details. It's recommended that when you have clicked on one task/skill/purchasable item/etc, you wait for the sync bar (a purple line) to travel across the top of the website - when it disappears, the sync has finished and it's safe to cast another skill, or mark another task complete, etc. It's not always 10 seconds. The time depends on the player's internet connection, and possibly how busy the server is.

The staff are working on a solution to sync problems in general, and since this is one case of a well-known problem, I'm closing this but it can be reopened if needed.

@garkbit When you experience bugs, the Report a Bug guild is the best place to report them. Usually you can give a fairly brief description of the problem - a lot of detail is often not needed, but we'd ask you there if we did need more information. You can reach that guild from the Help menu on the website or the Guilds menu item on the mobile app.

**Comment by garkbit** [comment]
It's pretty consistently a 10-second sync for me. I see reading through the code that there are 

> big peformance issues

If I've got task and exp history defined, which I do. However, I can find no reference to that on your Sync Errors page, which seems to be telling "click slower, twitchy". That's a pretty disheartening response when I can only register 1 click every ten seconds. To do a little math, it would take me a full six minutes to burn through all my mana in an effort to drop a boss.

Ain't nobody got time for that.

What I've had to do to cast spells without going mad is [write a darned script](https://gist.github.com/garkbit/7b3c276e8f2c9d2b8d4fe9b9d9438579) (that version harkens back to a pre-redesign time when my sync was only taking ~2.5 seconds). Surely that's not the user experience you're after?

Please, pretty please, take a long hard look at the underlying performance issue, and in the mean time, if the client is in a state where it can know a click will fail, don't let me click.

**Comment by garkbit** [comment]
Also, describing this as a "Sync Issue" is misleading, I think. Sync seems to be working as designed. It's a performance issue, IMO. If the server response time were below, I dunno, 100ms or so, issues would be few and far between.

**Comment by Alys** [comment]
It's definitely not the user experience we want but we are planning to fix the more general problem, which will fix it for skills too. In future there might also be the ability to cast a skill multiple times with one action.
