### ISSUE TITLE
Localize comma vs period

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9470]
We should have a string related to the decimal separator, for example when calculating boss health. Some languages use a comma instead of a period, so numbers such as "977.11 / 1000.00" look very odd.

**Comment by GoldenDrummer730** [comment]
Hey could we tackle this issue?

**Comment by veeeeeee** [comment]
@GoldenDrummer730 Hi there! It's a bit late, but if you're still interested, please let us know so we can put this issue down as claimed!

**Comment by GoldenDrummer730** [comment]
Hello! I do apologize for not replying to this issue after such a long time

Unfortunately our group has moved on and we will not be working on this issue anymore. 

Thank you!

**Comment by hellosurbhi** [comment]
@veeeeeee I would be interested in tackling this issue if it hasn't been claimed yet. Thanks!

**Comment by veeeeeee** [comment]
@hellosurbhi Go right ahead! cc: @shanaqui in case I lose track of this thread somewhere later

**Comment by shanaqui** [comment]
@hellosurbhi Hi! Just a quick check in to make sure you're still interested in working on this issue. If not, or if we don't hear back in a week, I'll mark this issue as help wanted again. Let us know!

**Comment by shanaqui** [comment]
I've changed this back to Help Wanted since we didn't get a reply. Do let us know if you want to pick it up again, though!

**Comment by citrusella** [comment]
I tried looking into this (though I don't know yet if I have the skill to fix it so I'm not necessarily claiming it ~~yet~~ until I can figure out if I have a good chance of actually completing it) and I'm wondering something: Is this the code that dictates what displays as the (current) / (total) count under the health bar? (And the pending damage?) https://github.com/HabitRPG/habitica/blob/5165d491b0e234c266660a339e94119ceb96c8f0/website/client/src/components/groups/questSidebarSection.vue#L150-L168

(I think it is, but I'm just confirming.)

**Comment by Helcostr** [comment]
https://stackoverflow.com/questions/5624173/javascript-number-and-currency-localization

I would like to work on this issue.

**Comment by Helcostr** [comment]
> I tried looking into this (though I don't know yet if I have the skill to fix it so I'm not necessarily claiming it ~yet~ until I can figure out if I have a good chance of actually completing it) and I'm wondering something: Is this the code that dictates what displays as the (current) / (total) count under the health bar? (And the pending damage?)
> 
> https://github.com/HabitRPG/habitica/blob/5165d491b0e234c266660a339e94119ceb96c8f0/website/client/src/components/groups/questSidebarSection.vue#L150-L168
> 
> (I think it is, but I'm just confirming.)

@citrusella that seems to be the place that it is displayed (and really, you only need to make sure everything is looking proper before displaying)

**Comment by Alys** [comment]
@Helcostr Thanks! I've marked it as in progress for you.

---

I've deleted some of the older comments that are not directly related to the bug or its fix.

**Comment by Helcostr** [comment]
I believe I have correctly used the user's current language and spit out the correct localization for the numbers. For example: French

![Lapins de poussière sauvages Participants 100,00 / 100,00  8,4 dégâts en cours](https://i.gyazo.com/d2aa2f87e304ceb6ab7c930776c36a93.png)

will reference this issue in my PR when I am ready to make the PR

**Comment by Helcostr** [comment]
I am explicitly stating my PR is ready to be reviewed (not sure if I should ping someone, or if I have to explicitly state in this issue that the PR is ready to be reviewed).

**Comment by citrusella** [comment]
I know there's currently a "bigger fish to fry" regarding this feature right now (the disappearing boss description issue), but since it came to mind I wanted to share before I forgot: I noticed when testing out if a certain language worked with a certain quest that had rage that the localization only applied to the boss health and not to the rage bar as well. Should it apply to both?

(Tangent: I briefly wondered the same about World Bosses in the future, but it turns out they're already using toLocaleString for both, presumably with no checks to catch for the underscore/@ issue? ([boss HP in Tavern.vue](https://github.com/HabitRPG/habitica/blob/51e8aa341dc2d46aa102b3d9014b22584aa8a756/website/client/src/components/groups/tavern.vue#L119), [boss rage in same file](https://github.com/HabitRPG/habitica/blob/51e8aa341dc2d46aa102b3d9014b22584aa8a756/website/client/src/components/groups/tavern.vue#L141)) ...Does that mean previous World Bosses have been invisible to users using certain languages or am I misunderstanding something ~~because I think that would have generated a report at some point~~?)

**Comment by Helcostr** [comment]
@citrusella localization of numbers should apply to everywhere with a number. It's no issue of slapping the mixin into whever it's needed, now that we have a mixin for such an operation.

However, I am not omnicient, and don't know where every number output to screen exists. You are going to have to tell me :)

The only reason the boss value went invisible is because i passed a bad value into the `toLocaleString` function, causing it to blow up. The other instances of `toLocaleString` are fine (because they are not using the habitica language, only the browser language)

The newer PR is more relevant to this topic.

**Comment by citrusella** [comment]
I only really posted it here because it was *supposed* to be relevant to the original issue and not the fix for the related bug... but then I mentioned that whole world boss thing, which tangent-ed directly into the newer bug. :thinking:

(The rage line is here, I think: https://github.com/HabitRPG/habitica/blob/4dc718fbffc9e593309f48121a5d241ca87be240/website/client/src/components/groups/questSidebarSection.vue#L201 )

**Comment by Helcostr** [comment]
@citrusella fair enough, sneaking the change into #13258 fixing the related bug.
