### ISSUE TITLE
Website Markdown does not currently support quoting with > and >> (blockquotes)

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9476]
Website Markdown does not currently support quoting with > and >>. It should be updated so that it supports this again.

**Comment by librarianmage** [comment]
It appears that instead of the blockquotes not appearing, blockquotes (what happens when > or >> is typed) are simply unstyled. @Tressley, would that be something that you would design?

**Comment by Tressley** [comment]
@MathWhiz -- Thanks for doing the detective work. This is something I'll need to design.

**Comment by librarianmage** [comment]
Glad to help!

![](https://media.giphy.com/media/Yiw4aLjpxldhC/giphy.gif)

**Comment by lemoness** [comment]
I've updated the labels on this issue!

**Comment by Ytrog** [comment]
Any update on this issue?

**Comment by veeeeeee** [comment]
Adding in one level of quoting with > for now. We'll monitor the community social spaces to determine if we need to add the >> level back in to maintain quality of discourse.

**Comment by Tressley** [comment]
![image](https://user-images.githubusercontent.com/2686586/52797443-e6861600-3043-11e9-9a32-c9d040c7592f.png)

Here's the Zeplin design: https://zpl.io/2ZL00K1

**Comment by GiacomoLaw** [comment]
Any update on this? I wouldn't mind looking at it if someone can link me to the markdown render files.

Thanks!

**Comment by Tressley** [comment]
@GiacomoLaw -- Great! You can find the Markdown css here:

`habitica/website/client/assets/scss/markdown.scss`

Are you a member of our Zeplin project? If not, can you share an email to invite? That'll give you access to the artboard that has all of the colors and properties of the design.

**Comment by GiacomoLaw** [comment]
No, I'm not. What is Zeplin?

**Comment by Tressley** [comment]
Zeplin is our hand-off tool between designers and developers. It allows our developers to interact with the design to identify colors, typography, and spacing to ensure 1-to-1 implementation.

**Comment by GiacomoLaw** [comment]
Sorry for the late reply - don't think I have the experience to implement this, sorry!

**Comment by citrusella** [comment]
Is the code in question supposed to be added to `habitica/website/client/src/assets/scss/markdown.scss` to get the blockquote to look right in chat posts? It doesn't appear to work on that front, because chat posts aren't given the markdown class. It seems like it could work if added to `habitica/website/client/src/assets/scss/typography.scss` but I don't actually know because I haven't tested it. (I'm looking at the fact that the typography scss has matching characteristics to the markdown I have in chat posts on my local install.)

(I was testing blockquote visibility out by adding old blockquote styling from a second, pre-redesign fork/mirror I have of Habitica, just because I knew it'd give me a different visual than no styling. Do I need access to Zeplin to be able to see that blockquote link directly for the actual style look thing (instead of vicariously through the screenshot)? @Tressley )

Also, in case it's not obvious, I'd like to claim this. I'm fairly confident I can do it, even though my initial play-around failed to apply the style properly. XP (~~Aaand... my second attempt has also failed. Hmm...~~ Ah, no, the typography file above is definitely the one that needs editing AFAICT, as long as you don't make a foolish mistake when making said edits.)

**Comment by Alys** [comment]
@citrusella Thank you! I've marked it as in progress for you.

**Comment by Tressley** [comment]
@citrusella -- Sorry for my late reply! Yes, you'll want an invite to Zeplin to get design specs. Can you provide me an email I can send the invite to?

**Comment by citrusella** [comment]
@Tressley citrusellaflugpucker@yahoo.com should work, I think. o.o

**Comment by citrusella** [comment]
...It's been a week with no invite. Is everything okay? 0_o

**Comment by Tressley** [comment]
@citrusella -- Hmm... I did send one to citrusellaflugpucker@yahoo.com. However, this wouldn't be the first time an invite has gotten lost. I just sent another. Please let me know if you don't see this one!

**Comment by citrusella** [comment]
This is what I have so far (and maybe all I need to do? gonna go over it with a fine toothed comb):

![Three posts in order--nested blockquotes, blockquotes with not-blockquotes around, and a blockquote in isolation](https://user-images.githubusercontent.com/14182450/82363286-98488b00-99db-11ea-9e61-5747fc79879f.PNG)

But I did want to ask since it occurred to me and the Zeplin example only contains the quote in isolation: Is the standard spacing applied to the p (as present in the "blockquote with other text" and "nested quotes" examples) okay here? I'd imagine it *probably* is, but I wanted to ask to be totally sure.
