### ISSUE TITLE
Can't re-pin lost Grand Gala item

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9479]
If you lose a limited-time Grand Gala item due to running out of health and then unpin it from your Rewards column, the item does not appear in the Market, so you can no longer buy it back from anywhere.

**Comment by majestic-owl448** [comment]
I have all my lost grand gala equipment under Class:None, I can pin it without issue. And it appears in my reward column when pinned, but I obviously can't buy it as it is not the correct class.
Maybe the issue is that the equipment doesn't appear under the expected class?

**Comment by Alys** [comment]
@Ieahleen  Thank you! I've tested and confirmed you're right, and the items can be purchased if you're in the right class. I think this issue was either reported before we added those items to "None" or the user couldn't find them, as you suggest.

I've logged https://github.com/HabitRPG/habitica/issues/9485 for getting the gear moved to the right class drop-down option.
