### ISSUE TITLE
Card purchase should have confirmation notification + Card purchase modal should not reopen itself

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9484]
When casting a card on someone, no confirmation is given ~and gold doesn't decrease until the page is synced or refreshed~. There should be a confirmation notification in the corner, ~and the gold should be subtracted immediately~.

_Edit by Alys 2018-01-13 to summarise the comments below:_

The desired fix for this issue is both of these:
1. When you buy a card, you should see a notification saying "You sent a card to [User Name]". It should be a snack notification (the kind that appears in the top right of the website and then disappears quickly).
2. The buy modal should NOT reopen itself as soon as the first purchase has been finished.

I've crossed out the parts about gold not being subtracted because that bug has now been fixed.

We need a fix for this to be live before Valentine's Day because card purchases will be happening often then, so someone should try to fix this **by the end of January** to give time for testing, review, and deployment.

**Comment by librarianmage** [comment]
It also allows multiples to be purchased, but only sends one before exiting.

**Comment by lemoness** [comment]
Confirming that you should NOT be able to buy more than one card at a time.

**Comment by Alys** [comment]
Multiple purchases are being removed in https://github.com/HabitRPG/habitica/issues/9317 which already has a PR in progress, so whoever works on this issue shouldn't try to remove the multi-purchase code.

**Comment by Alys** [comment]
I'm reopening this because one part of it (no confirmation message) is still happening on the staging website. You do see a notification that gold has been subtracted but there's no notification that a card has been given to the recipient, and since the card buying modal reopens immediately, it looks like it didn't work.

Even if if a snackbar notification is implemented to say that the card was sent, it will be easy to miss that notification if you're focused on the card buying modal - and it's likely that you would be focused on the modal since you'lll be wondering why it's reappeared. I know it's intentional that it reappears (https://github.com/HabitRPG/habitica/issues/9567#issuecomment-352014260) but I'm really not sure that's good for clarity. While it might be slightly annoying to have to click on the card icon again for each New Years card you want to send, having the modal stay closed after the card is sent is a much clearer sign that the card has actually been sent. In addition, for cards like happy birthday and congratulations, you're not likely to want to send more than one at once. @Tressley @lemoness

**Comment by lemoness** [comment]
I am in agreement that the modal should stay closed.

**Comment by Tressley** [comment]
Yes, I think the modal should stay closed as well. I think a snack message could be shown that says, "You sent a card to [User Name]" in addition to subtracted gold.

**Comment by lemoness** [comment]
That wording looks good to me!

**Comment by Alys** [comment]
I've added this to the top post:

When casting a card on someone, no confirmation is given ~and gold doesn't decrease until the page is synced or refreshed~. There should be a confirmation notification in the corner, ~and the gold should be subtracted immediately~.

_Edit by Alys 2018-01-13 to summarise the comments below:_

The desired fix for this issue is both of these:
1. When you buy a card, you should see a notification saying "You sent a card to [User Name]". It should be a snack notification (the kind that appears in the top right of the website and then disappears quickly).
2. The buy modal should NOT reopen itself as soon as the first purchase has been finished.

I've crossed out the parts about gold not being subtracted because that bug has now been fixed.

We need a fix for this to be live before Valentine's Day because card purchases will be happening often then, so someone should try to fix this **by the end of January** to give time for testing, review, and deployment.
