### ISSUE TITLE
Health/Experience/Gold/etc notifications go by too quickly

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9490]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

In an attempt to fix stat-change notifications getting "stuck" in view, we shortened their duration. It's too short, now! It can be hard to take in everything that happens on a click, particularly in a busy event like a critical hit with quest progress and a drop.

**Comment by Alys** [comment]
There's also reports of it being too fast for feeding pets:
"Can the flash message please stay a little bit longer. Especially when feeding pets"
"Hey guys! When I feed my pets, the notifications last about half a second and I have no time to read anything whatsoever. I'm using Firefox, but I think I experienced the same problem with Chrome. Anyway to fix this? // Thanks."

And an older report for the Enchanted Armoire:
"I just use the Enchanted Armory but hardly had enough time to see what I got, the notification disappeared too quickly")

Important error / notification messages with a lot of text also disappear FAR too quickly, as reported in https://github.com/HabitRPG/habitica/issues/9249 for the "incorrect username/password" message and the message you see when you try to post a swear word or slur (in one of the comments in that issue).

I think we have a few related problems / suggested fixes:

- notifications for simple, small things like Health, Gold, Experience should be slowed down slightly
- notifications for slight more complex things like feeding pets (loves/hates the food) and the Armoire should be slowed down more
- notifications for long and/or critical messages should be very slow or presented in a popop (even if it's just a javascript alert as a quick, temporary fix because it's really important that those messages can be read).

**Comment by mandyzhou** [comment]
I really like the way the apps (or maybe just the Android app?) combines notifications for experience, gold, and mana. Those are easier for me to parse a little more quickly and are a little less overwhelming. Would it be difficult to implement those for the website as well? Then those combined notifications could appear at the same speed as the ones for slightly more complex things like feeding pets.

**Comment by joedragons** [comment]
Funny, I would have said this was improved yesterday or the day before.  Seems about the original speed now.  I also figured this changed because of people saying it went by too slow (I initially had feedback that way).  I'm surprised the solution isn't a configurable option, considering speed is probably based on taste.

**Comment by Marrepower** [comment]
I thought it was just something wrong with my chrome, but it seems like everyone has this..
I was looking for a setting to change the speed. They go too fast, even for small notifications like money, and damage to boss.

**Comment by SabreCat** [comment]
We roughly doubled the duration recently--still an issue, @Marrepower @joedragons ?

**Comment by joedragons** [comment]
I've been fine with the speed for a while (since my last comment).  Maybe re-ask @mandyzhou ?

**Comment by mandyzhou** [comment]
I think the duration works well! I still like the idea of consolidating some of the notifications a la the app, since the sheer number of notifications can get overwhelming, but that's more of a wish list item than a necessity.

**Comment by joedragons** [comment]
#agree.  The website is the same.  I need to use the trello more for
requesting things=)

**Comment by Marrepower** [comment]
@SabreCat I still think its too fast, but I'm also pretty new to the game so I never had the overwhelming numbers of notifications.
Also there is an anoying News anouncement Popup every time I check something witch I first need to click away to see the gold gain.

**Comment by joedragons** [comment]
@Marrepower FYI, unless your behavior is different than mine, if you click dismiss (at the bottom of the popout) as opposed to away from the popout, it should no longer appear.  I believe I reported this (either bug or feedback) but I have a feeling it's intentional.

**Comment by lemoness** [comment]
Yes, you need to click the "Dismiss" button, or it assumes that you haven't seen it yet! That's intentional, but we have some improvements planned for the future for that and for notifications being more consolidated. However, those aren't related to this ticket, so I'm closing this now.

**Comment by YavorK** [comment]
Notifications disappear way too fast for me to read them on Android and in Chrome. Is there a way to keep them on screen longer or at least find them in a log page somewhere?

**Comment by YavorK** [comment]
> I've been fine with the speed for a while (since my last comment). Maybe re-ask @mandyzhou ?

I am not sure what doubled time means but in games notification text stays on screen for like 10 seconds or is displayed in a bubble you have to hit the X button to close it or hit Escape.

You can also read logs somewhere.

Habitica is the first product that gives me problems with checing out the immediate history of events. Makes me sad.

**Comment by balboah** [comment]
Also having trouble with notifications, they appear for maybe 2 seconds (safari) and then you can't find a log in "notifications". Same on the iPhone app for stats changes, it's too fast
