### ISSUE TITLE
Username notifying is too broad

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9506]
The purple dot that notifies people when they've been tagged in a post is too widely applied. For example, a user named "The H" sees the purple dot appears every time the word "the" precedes the letter "h", for example in the phrase "the Habiticans."

**Comment by LunarGem** [comment]
Shouldn't the mentions be directly attached to the @ symbol like the dropdown that allows you to select? The H should only be mentioned when "@The H" appears in a post.

**Comment by librarianmage** [comment]
Oops, looks like I accidentally broke it in #9411. I'll setup a fix ASAP

**Comment by paglias** [comment]
@MathWhiz I don't think your PR caused this issue since your PR has not been deployed yet. I'm discussing witth the team whether we only want to allow mentions with the `@` char or if we also want to highlight usernames in the wild, but in that case we might want to require a white space between the username and the next word

**Comment by librarianmage** [comment]
Sorry, just fixing it as @lemoness specified

**Comment by paglias** [comment]
@MathWhiz oh it wasn't a critique, I was just saying that it was not caused by your PR :)
