### ISSUE TITLE
Non-participants still see pending Quest damage

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9508]
If you reject a quest invitation, you still get the notifications about Boss damage when you complete tasks, and you see your pending damage in the Party page. ~(This might only happen while the quest is in the invitation stage.)~ You should never see any pending damage or boss damage notifications once you have rejected a Quest.

**Comment by TheHollidayInn** [comment]
Do we know if this was occurring before the redesign?

**Comment by Alys** [comment]
I'm almost completely certain it was not.  We had the damage/collected-items icon in the header then and iirc it never appeared when it shouldn't.

I've edited the top post to cross out "This might only happen while the quest is in the invitation stage" because it happens while the quest is running too.

**Comment by TheHollidayInn** [comment]
Ah, okay. I was wondering if the server was still sending the notifications to the user, but the old client was just ignoring them.

**Comment by TheHollidayInn** [comment]
I'm unable to recreate this issue when completing tasks, but I am pushing a PR to fix the pending damage display.
