### ISSUE TITLE
Completed To-Dos cannot be cleared

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#9517]
There is not currently a way to clear completed To-Dos. Folks would probably like to have that option again. :) 

Here is text from the wiki detailing the way this feature worked previously: 

"At the bottom of the "Done" tab is a button marked "Delete Completed" that will permanently delete all of your completed To-Dos (including those not visible in the Done tab but not including those that are part of a challenge)."

If this is useful, the wiki also notes that completed To-Do's are automatically removed after 30 days for non-subscribers and 90 days for subscribers.

**Comment by Alys** [comment]
Labels updated. "on hold - needs design" @Tressley 

In addition to not deleting To-Dos that are part of a challenge, it should also not delete To-Dos that are from a Group Plan. Once that goes live, we'll need to update the wiki's text - we'd be grateful if the contributor who fixes this puts a brief reminder of that in their PR so we don't forget! :)

**Comment by lemoness** [comment]
We have the design for this now, so I've updated the labels on this ticket to "help wanted." Note that if you would like to work on this, you'll need to post here with an email address that we should invite to our Zeplin account so that you can get all the design details.

<img width="262" alt="screen shot 2017-12-22 at 10 11 02 am" src="https://user-images.githubusercontent.com/3494081/34308163-bf367e42-e700-11e7-9f10-6175e05b4430.png">
