### ISSUE TITLE
Change Badge Tooltips

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9520]
We need a few text changes to the following achievements!

Costume Contestant
Description should read "Participated in X Habitoween Costume Contests. See some of the awesome entries at blog.habitrpg.com! [Should not be a link]

Contributor Badge
Has contributed to Habitica, whether via code, art, music, writing, or other methods. To learn more, join the Aspiring Legends Guild!

**Comment by Davyd23** [comment]
Hello,

I will work on this if it is still available.

Edit: Made a pull request with the modifications.

**Comment by cassidypignatello** [comment]
Hi @lemoness, I'm a little confused why my build failed in Travis. I also had three tests fail locally, but I checked out the develop branch and they also failed there as well. Here's what I'm seeing in Terminal:
```
  1) shouldDo Monthly - Certain days of the nth Week leaves daily inactive if not day of the month with every x month on weekday:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (test/common/shouldDo.test.js:984:52)

  2) shouldDo Monthly - Certain days of the nth Week activates Daily if on nth weekday of the x month:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/common/shouldDo.test.js:1009:52)

  3) shouldDo Monthly - Certain days of the nth Week activates Daily on start date:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/common/shouldDo.test.js:1033:52)
```
I'll keep trying to figure this one out, but any help you could provide would be greatly appreciated!

**Comment by TheHollidayInn** [comment]
The travis issues are not your fault. I have fixed them in the release branch and they will be merged into develop soon.

**Comment by cassidypignatello** [comment]
Thanks for confirming!

**Comment by negue** [comment]
@cassidypignatello @Davyd23 thank you both for your contributions on this issue, but unfortunately we can choose only one. We'll use @cassidypignatello's because it was first and doesn't make changes to the non-English locales files (@Davyd23 see the `_README_FIRST.md` file in `website/common/locales/en` for why they aren't edited manually).

We hope you'll both make more contributions but please both keep in mind that when you want to work on an issue, it's recommended that you post to the issue first to say you're interested and then wait for a response from an admin before you start. That helps to avoid duplicate work. Please see "Ways to Help" in [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) for more details.

@lemoness I guess the Contributor Badge shouldn’t have the „Badge“ in the Name right?
