### ISSUE TITLE
food drawer sometimes goes blank after hatching

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9533]
From Praxis Arete ( 0ce6d43b-efa2-45a3-acaa-59daad7d658d ) in the Report a Bug guild:

"... occasionally ... the foods menu at the bottom of the Stable page sometimes goes blank after hatching, with all the windows black as though you have no foods left. Re-synching and refreshing did not fix this; I had to navigate to a different Habitica page and then return to the Stable page for it to display properly again."

**Comment by lemoness** [comment]
Question! What happens if they click the sideways arrow within the food
drawer when this happens? I think this might actually be confusion as a
result of the fact that the food drawer doesn't loop correctly (as
described here: https://github.com/HabitRPG/habitica/issues/9366) because
sometimes you end up with a blank "page".

**Comment by Alys** [comment]
I haven't seen other reports of this so I'm closing this. If it comes up again, I'll ask about clicking the arrow.
