### ISSUE TITLE
Language bug - bulgarian

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#956]
Lanugage bug - says bg.app.dailies for example. It would also be nice to have an option to switch languages in the settings menu.

**Comment by StanLindsey** [comment]
Is this on beta.habitrpg.com ? If so its because we haven't moved the languages over yet as it is beta. www.habitrpg.com is only in English at the moment if you prefer that. 

If you're on Chrome you can change the language in settings > advanced > languages > language & input settings. Add and move the language you want to the top. Obviously this is a work around but I assume that most users would want all websites in their language?

**Comment by nikrage** [comment]
I'm on the normal site and don't have the option

 -------- Оригинално писмо --------

От: Stan Lindsey notifications@github.com

Относно: Re: [habitrpg] Language bug - bulgarian (#956)

До: lefnire/habitrpg  

Изпратено на: Вторник, 2013, Май 14 18:55:26 EEST

Is this on beta.habitrpg.com ?  

If you're on Chrome you can change the language in settings > advanced > languages > language &amp; input settings. Add and move the language you want to the top. Obviously this is a work around but I assume that most users would want all websites in their language?

**Comment by scroll** [comment]
Can you explain what exactly is wrong ? I started Bulgarian translation some time ago which got merged, but I don't think languages have been implemented in any way on the live site so it shouldn't even be anything related to this.

**Comment by nikrage** [comment]
http://i.imgur.com/RGwAGEQ.jpg?1

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks! Anyway translations are still missing from the new site!
