### ISSUE TITLE
+ only habit bug

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#957]
History bug - the graph declines when i click +

**Comment by lefnire** [comment]
the graph goes downwards? or it just doesn't show up?

**Comment by nikrage** [comment]
the graph goes downwards

 -------- Оригинално писмо --------

От: Tyler Renelle notifications@github.com

Относно: Re: [habitrpg] + only habit bug (#957)

До: lefnire/habitrpg  

Изпратено на: Вторник, 2013, Май 14 20:30:04 EEST

the graph goes downwards? or it just doesn't show up?

**Comment by AndreCaseyScott** [comment]
Hmm, does anything show up in the javascript console when you click the + on a habit? If you press it multiple times in a row, does it decrease everytime? Is it only the graph that is affected, or do you lose HP too?

**Comment by StanLindsey** [comment]
Do you lose HP, experience or gold when you click plus on a habit? 

related to #1069 ?

**Comment by nikrage** [comment]
Only the graph is moving really random.

**Comment by nikrage** [comment]
And that happens to all of them. It's just really random. I can't really figure out a pattern. Sometime it goes up, sometimes down

**Comment by AndreCaseyScott** [comment]
Ooooooh, I think it is possible you are noticing the "drift" that onlies
have. If you have an only ( + only or - only), the "score" (which is shown
in the graph) goes in one direction when you click it. When you don't click
it though, it drifts back to zero. The idea being that they are with less
the more frequently you do them, but if you don't check it for several
days, will become worth more.

If this is not what you are describing, then try to give us any other
information you can, be it screen shots, errors, etc.

If it is, I would like to say that this should be closed :)

**Comment by nikrage** [comment]
Its another bug. As you can see here http://i.imgur.com/x1xH3sv.jpg?1 I've clicked on this habit everyday for atleast 4-5 days but the graph is just messed up. I also have another bug since a week that it doesn't show me the date sometimes when I click the habit, although it gives me all the stats etc. I clicked it today and it doesn't show 28.05

**Comment by StanLindsey** [comment]
I think you're correct @onduhray. 

To reiterate; the plus or minus only habits will reset to the default value so that they don't become too increasingly damaging/worthless. The graph tracks the "score" of the habit (as opposed to user clicks) so when it resets it pulls the graph towards the middle, the default score.

**Comment by nikrage** [comment]
Sounds dumb if thats the case

**Comment by StanLindsey** [comment]
Aha, it is but its because it solved another issue that was even more dumb. We'll sort this out at some point. Tis rather minor though at the moment compared to other issues.

**Comment by lefnire** [comment]
yes, this is definitely habit drift. We had a trello card on the topic, and way more people preferred drifting an "only" habit back to 0 over time, than forever getting greener-and-greener, permenantly devaluing the habit. As far as a static value=1 (the original implementation, in which case the graph was a straight-line on 1), people preferred task devaluation in order to determine which of their "onlies" need more focusing and which need less.

It's a hotly-debated topic, and discussed ad nauseum - we went with the most popular opinion and don't plan on going back unless popular opinion changes.

**Comment by AndreCaseyScott** [comment]
IMHO, I kinda wish habit drift affected ones with + and -, not just onlies.
It's nice to a) have that reminder, and b) be rewarded more when you
haven't done a habit recently. Sometimes my +- habits get neglected for
days or weeks. Given how vastly different people use Habit, I doubt that
sort of drift will ever be added (which is why I use mainly onlies :P).

**Comment by SabreCat** [comment]
I agree with onduhray - I would love to see bidirectional habits drift back to baseline.
