### ISSUE TITLE
Can't feed special pets

### ISSUE THREAD

**Issue by dseebacher** [HabitRPG/habitica#9580]
### General Info
  * UUID: e86bbc60-a81f-47ed-91b4-2d8928482b05
  * Browser: Firefox 57
  * OS: Linux/Fedora 27

### Description
I can't feed special pets in the browser version. Two different things might happen, always with the same pets:
I grab a random food from the quick bar and click on a pet
1. nothing happens at all, the food is still following the cursor
2. the food disappears, but was not consumed (same amount as before) and i get an error

#### Console Errors
Unhandled promise rejection Object { name: "t", httpCode: 401, message: "Dieses Haustier will und kann nicht gefüttert werden.", stack: "" } es6.promise.js:97
	$/</e< es6.promise.js:97
	t.exports _perform.js:3:12
	$/< es6.promise.js:91
	o setImmediate.js:40
	a setImmediate.js:69
	n setImmediate.js:109

**Comment by Alys** [comment]
Special pets aren't intended to be fed. Matching special mounts are given
out for free periodically. The Habitica Help guild can give you more
information if you like!

For reporting bugs, it's best to put a brief message in the Report a Bug
guild, rather than creating a new issue.

You can reach both guilds through the website's Help menu, or for more
details see the instructions when you click "new issue" here (you can
cancel before creating the issue).

**Comment by dseebacher** [comment]
I thought so, but still:

1. signal somehow , that it is not possible to feed them (feature request)
2. they should at least behave all the same way
