### ISSUE TITLE
Saddles Should Not Be Sellable

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#9596]
**EDIT 2018-12-08 by Alys: For the current behaviour and new fix required, see my comment further down in the isssue. This should be a pretty easy fix since it likely just needs small changes to existing code, based on code that was working in the past (links to both sets of code are in my comment) so I'm marking this as "good first issue" although it might be a little harder than such issues normally are.**

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Currently the UI shows that you can sell Saddles in the Market if they are in your inventory. We should not allow this

from @Tressley "If they try to sell a Saddle, we could prompt them with a "Hey! This is a pretty useful item! Are you familiar with how to use a Saddle with your Pets?"

This is also an alternative solution.

**Comment by matchajune** [comment]
@Alys I can take this if it is ready!

**Comment by TheHollidayInn** [comment]
Go for it :D

**Comment by Alys** [comment]
I'm reopening this because the bug exists again (although now when you click the "sell" button, nothing happens). The fix we want is the same as in the PR that fixed it the first time: https://github.com/HabitRPG/habitica/pull/9663

For reference, this is the commit that removed the desired if-else behaviour: https://github.com/HabitRPG/habitica/commit/92e4d5cd68#diff-02353aaddddf057ac294e2caa2b18c6eL12
We don't want that commit reversed because there's a lot of desirable changes in it, but the if-else behaviour from PR https://github.com/HabitRPG/habitica/pull/9663 needs to be added back in to the changes made in that commit.

**Comment by RushedLegacy** [comment]
@Alys Hey, I'm **new** here. Just trying to help. Would appending ".inner-content" at line 24 in your referenced commit work?

The new line 24 would be:

div **.inner-content** (v-if="item.sellWarningNote")

**Comment by Alys** [comment]
@RushedLegacy Thank you for looking at this, but I don't think that will help. I believe it's more of a problem with the `if` statements in the vue code.

**Comment by andrew-vicencio** [comment]
@Alys I can take this issue if nobody is!

**Comment by Alys** [comment]
@andrew-vicencio Thanks very much! Comment here if you have questions.

**Comment by ChesterSng** [comment]
Hi @Alys It looks like it has been awhile since anyone has contributed to this issue, would like to work on it if it is fine!
