### ISSUE TITLE
price / cost / value of large Rewards is obscured by the gold coin image when edting

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9618]
From citrusella, the serving wench ( 2d6ef231-50b4-4a22-90e7-45eb97147a2c )  in the Report a Bug guild:

"If you make a reward with more than three digits (i.e. 1000 or 22096), the money image that shows up in the box obscures the last two digits [when editing the Reward]."

Here's an example with nine digits to make it clear:

![1](http://i.imgur.com/g2rD3H4.png)

**Comment by kartikadur** [comment]
I'd like to work on this if it is still available.

**Comment by lemoness** [comment]
@kartikadur Thank you very much! Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by kartikadur** [comment]
Is there anything that I should know before starting work on this issue?

**Comment by kartikadur** [comment]
will be making the following changes: 

+ text alignment to right
+ gold coin left margin reduced.

Visual change:

![option-1](https://user-images.githubusercontent.com/1319511/33878109-7efcab9c-df50-11e7-9390-afcdc47dc4a8.jpg)

**Comment by Alys** [comment]
@kartikadur Thanks for the details and screenshot!

@Tressley Can you comment on this proposed fix? It's for the edit form only (not how the Reward is displayed on the tasks page when you aren't editing it).  While this proposed fix might not match the original design of this field in the edit form, it does look to me like a simple way to get around the problem of the gold coin obscuring the value.

**Comment by Tressley** [comment]
@Alys -- Hmm. I'd like to tag in either @paglias or @TheHollidayInn to review the implementation. While this may be a possible workaround, I think there's might be a better solution. We should be able to display the icon as a background and pad the element enough to start the input after the icon.

**Comment by paglias** [comment]
I think Bootstrap's input groups are perfect for this use case https://getbootstrap.com/docs/4.0/components/input-group/

I've used them in this PR if you want to give see an example https://github.com/HabitRPG/habitica/pull/9560

**Comment by kartikadur** [comment]
How does the following line of code in [taskModal.vue on line 25](https://github.com/HabitRPG/habitica/blob/7fccf59f505c89618753a8a60958fcdfa7cd213f/website/client/components/tasks/taskModal.vue#L25) work?

`.svg-icon.gold(v-html="icons.gold")`

as far as I can tell
+  `.svg-icon` and `.gold` are css classes
+ `v-html` is used to render html as (opposed to {{...}} for text output)
+ `icons.gold` is an svg image (imported in the script section)

When I tried to replicate it, it only printed the image url value for `icons.gold`

Is there some background functionality that I am missing?

**Comment by paglias** [comment]
Can you post the code you're trying to use? If everything is imported correctly it should work

**Comment by kartikadur** [comment]
@paglias This is more for my understanding so I don't break anything when I refactor the code. Partly because I've never seen `v-html` used this way and partly because I can't find any explanations on the net.

here are lines in question: https://github.com/HabitRPG/habitica/blob/7fccf59f505c89618753a8a60958fcdfa7cd213f/website/client/components/tasks/taskModal.vue#L21-L25

**Comment by paglias** [comment]
That code works by importing the svg file for the icon into JavaScript.
It's then stored inside the components data object under icons.gold and
then rendered in the template as HTML.

The same technique is used across the entire website. I don't understand
when you say

> When I tried to replicate it, it only printed the image url value for
icons.gold

Can you post the code that results in printing the image url?

Il 18 Dic 2017 06:44, "kartik adur" <notifications@github.com> ha scritto:

@paglias <https://github.com/paglias> This is more for my understanding so
I don't break anything when I refactor the code. Partly because I've never
seen v-html used this way and partly because I can't find any explanations
on the net.

here are lines in question: https://github.com/HabitRPG/habitica/blob/
7fccf59f505c89618753a8a60958fcdfa7cd213f/website/client/
components/tasks/taskModal.vue#L21-L25

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HabitRPG/habitica/issues/9618#issuecomment-352331585>,
or mute the thread

**Comment by kartikadur** [comment]
Import command gets the image/icon as a module. The v-html vuejs command renders it as raw unescaped innerhtml for a parent dom node. I think I have a grasp on that much. What I want to know is why it works the way it works. All my research indicates that it should not work unless the module/img/icon is bound to an `<img>` tag `src` attribute at or before runtime.

I started with the base vue-cli webpack starter in a cloud 9 online workspace. And replicated the code as shown below. Afaik I have abstracted away things that were not necessary. Obviously I may have removed something or failed to add something that was necessary.

Sorry if it sounds obtuse. Since I have never used a similar structure before, I probably don't even know how to frame the correct question. In any case below is the code that I wrote with the output

App.vue
```vue
<template lang='pug'>
  .container
    .svg-icon.gold(v-html="flag")
</template>

<style scoped>
  .gold {
    width: 24px;
    margin-left: 5em;
  }
</style>

<script>
  import flagIcon from './assets/icon-image.png';
  
  export default {
    data() {
      return {
        flag: flagIcon,
      };
    },
  };
</script>
```
HTML output
```html
<body>
  <div data-v-7ba5bd90="" class="container">
    <div data-v-7ba5bd90="" class="svg-icon gold">/static/img/icon-image.364c8ad.png</div>
  </div>
  <!-- built files will be auto injected -->
  <script type="text/javascript" src="/app.js"></script>
</body>
```

**Comment by paglias** [comment]
No worries @kartikadur :)

The reason your code isn't working is that you're loading a PNG image which needs to be added as an <IMG> tag with an SRC attribute. This way of importing icons and rendering them as HTML only works with SVG elements that can be added directly to the HTML of the page

**Comment by kartikadur** [comment]
sweet llama of alabama, I completely glossed over the fact that it was an svg thing.
thanks, you are awesome.

**Comment by kartikadur** [comment]
Current iteration of task modal

![adjusted-cost-reward-input](https://user-images.githubusercontent.com/1319511/34165121-6ce38e10-e501-11e7-95fd-1f56a1c9e42d.jpg)

Since I am already working on this would there be objections to adjusting the other inputs  (viz. tasks, repeats, repeats every, dates, etc.) on the task modal? I'd like to standardize the width/placement and types of the inputs.

**Comment by paglias** [comment]
@kartikadur regarding the other inputs for now it'd be better not to do them as we're already working on a new design that will fix those issues but it's not ready yet

**Comment by kartikadur** [comment]
@paglias In that case should I submit a PR for my update now, or should I wait for the new design changes to redo the code accordingly before submitting a PR?

**Comment by paglias** [comment]
@kartikadur submitting this fix now is okay!

**Comment by kartikadur** [comment]
thanks, will do

**Comment by kartikadur** [comment]
Also let me know if I can help with the redesign stuff. Now that I have a slightly better setup I can contribute more.

**Comment by paglias** [comment]
@kartikadur thanks! You can find a list of issues we need help with here https://github.com/HabitRPG/habitica/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitica/pull/9560
