### ISSUE TITLE
Completing then Re-activating a Daily or To-Do removes different XP/GP than was gained

### ISSUE THREAD

**Issue by Celtis** [HabitRPG/habitica#964]
If I close a hard To Do task I gain  16 xp and around 2 gold 13 silver. If I then go into completed tasks and uncheck the completed box I have 15.5xp and  around 2 gold 7 silver removed for not completing the task. I guess the reward is random, but surely the XP removal should be the same...

![habitrpg](https://f.cloud.github.com/assets/1991686/503000/6160bb1c-bcc0-11e2-939b-817cd23b429d.jpg)

snickeredit:
keywords => gold exploit, experience exploit, cheating, unchecking

**Comment by octern** [comment]
I tried checking and unchecking a daily task. It gave me 77 silver for completing it and took away 78 for unchecking it. I repeated this several times and the quantities were always exactly the same. My hypothesis was that when it was undone, it calculated the unreward based on how much I would have gotten for completing it a second time, including the streak bonus. However, if this also happens for to-do items then that's probably not right.

**Comment by jepler** [comment]
I'm also seeing this on dailies.

An unlikely cause is how (a+b)-b is not always exactly equal to a in floating-point arithmetic.  This is unlikely because the difference is going to be down in the [ULPs](http://en.wikipedia.org/wiki/Unit_in_the_last_place), at billionths or less of a silver point or XP—while it's possible to quickly pick up 5XP or 10SP by exploiting this bug.

A more likely cause is not performing the manipulations in reverse order: For instance, if when you check a daily the step is first to add the XP calculated from difficulty and second to adjust the difficulty, then to reverse it you have to first adjust the difficulty and then second subtract the XP.

**Comment by jepler** [comment]
Hmm, today I saw a net decrease in my money when I toggled a daily repeatedly.
