### ISSUE TITLE
Stops responding to changes after a few requests made (and on first load of site) without hard reload

### ISSUE THREAD

**Issue by motoyugota** [HabitRPG/habitica#967]
In Chrome, I continually have the problem where I have to force a reload to get it to actually take my clicks on items to complete them or when adding tasks. Two examples:

When I first come to the page, it almost never responds to my click on an item to complete it. I have to reload the page and then it works again (for a while).

When I am adding tasks, if I add more than two in a row, it almost invariably stops working after the second until I force a reload of the page, and then I can add two more.

**Comment by Gmk1212** [comment]
I'm getting a similar problem in Firefox. I updated my list by clicking the + sign on several habits, and checked off a TODO, but just now, about 15 minutes later, the page suddenly reloaded on it's own and undid all of the changes I had made.

Earlier, I was clicking plusses and noticed that the rewards amount wasn't being updated at all. I'm using beta.habitrpg.com

**Comment by nchezrony** [comment]
Ditto in Firefox. This also occurs when I access the page on my iPhone.

**Comment by octern** [comment]
Losing progress after reload has been happening for me sporadically since I started using the site several weeks ago. I frequently have to hard-reload (clicking "reconnect" does nothing), and when I do there's a good chance I'll have lost my last few actions. I've also gotten the other behavior described here, where clicking does nothing without a reload.

**Comment by storian** [comment]
I am also seeing this.  Been seeing it all day today, maybe yesterday too.  (Seeing as OP is from yesterday, I'm going to go with: also yesterday.)  IME it might be time-related; the page definitely stops responding after 2 or 3 clicks (the last thing I click shows the check in the box, but the popups showing experience and gold etc. do not appear), but at least once after hard-reload I have clicked nothing, done something else for a short time (a few minutes, maybe 5 or 10), then returned to an unresponsive page.

Using Chrome 26.0.1410.65 on OS X 10.6.8.

**Comment by nextmike** [comment]
Same issue here for last few days, random changes in progress, breaks in streaks after a reload.  SInce streaks are breaking via bug maybe let us manually go in and reinstate our streaks?  Without doing that it's really demoralizing to restart a streak due to a bug.  Latest Firefox here. Usually keep HabitRPG open in a background tab...

**Comment by SabreCat** [comment]
I've particularly noticed this phenomenon when interacting with the progress graphs. Viewing one of those tends to cause the rest of the icons to stop responding to clicks.

**Comment by nextmike** [comment]
Yes, I have experienced same issue as SabreCat, looking at graphs sometimes kills additional click functionality.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
