### ISSUE TITLE
"Tell Me Later" Button not displaying correctly

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitica#9683]
On Chrome:

![image](https://user-images.githubusercontent.com/5608909/33673258-4b5971e2-da7a-11e7-9255-cc628f382f96.png)

**Comment by Tressley** [comment]
It looks like this button is referencing `.btn-default` a class that does not exist. Should be switched to `.btn-secondary`. We may want to do a search for `.btn-default` to cover our bases and ensure it isn't being used anywhere else.

**Comment by cassidypignatello** [comment]
I'm happy to take this one!

**Comment by Alys** [comment]
@cassidypignatello Thanks! Comment here if you have questions.

**Comment by cassidypignatello** [comment]
I went ahead and submitted a pull request at #9704 in case this is all set, but I did want to mention that I saw `.btn-default` being used in quite a few places so I went ahead and replaced them all with `.btn-secondary`. I wasn't able to actually see the `newStuff.vue` screen since that modal doesn't seem to pop up when I sign in on my local install, but it looked good when I changed it on other screens that had buttons that were displaying correctly, like `sendGemsModal.vue`.

Some of the buttons using `.btn-default` weren't displaying incorrectly anyway, and I didn't notice any difference after changing them since I'm guessing other styles might be overriding that one. I also wasn't totally sure if I should change it in places like the debug menu, but let me know if you need anything changed here before approving. Thanks!
