### ISSUE TITLE
Group Plan tasks cannot be sorted in the Group's "Task Board" page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9691]
It's not possible for the leader of a group with a Group Plan to sort the tasks in the group's own "Task Board" page (`https://habitica.com/group-plans/<group-id-goes-here>/task-information`).

You can drag the tasks to a new position and it seems to work (no error messages on the page or in the console) but when you reload the page, the tasks are back in their previous order.

This could be because of an error in the `api.groupMoveTask` function. As described in https://github.com/HabitRPG/habitica/issues/8922, the apidoc comments and the code conflict.
Even if the code in that function turns out to be correct, the PR that fixes this issue should also correct the comments in that function.

**Comment by Alys** [comment]
labels updated

**Comment by TheHollidayInn** [comment]
This is because we don't sort the task after loading them using the group's TasksOrder

**Comment by kirsty-tortoise** [comment]
I thought I'd have a look at this, but got confused about how sorting tasks works normally on the users page (since I was attempting to replicate that) and I feel like maybe it isn't working totally correctly.

It seems like the code attempts to sort them according to tasksOrder twice, once on fetching the tasks and again when filters are being applied.

The first is here:
https://github.com/HabitRPG/habitica/blob/71c0939a1595872096dcb0c12947b048d0b125dc/website/client/store/actions/tasks.js#L6-L20
and seems to work fine.

The second is here:
https://github.com/HabitRPG/habitica/blob/71c0939a1595872096dcb0c12947b048d0b125dc/website/client/store/getters/tasks.js#L126-L161
In particular lines 137-144.
As far as I can tell (from printing the value of `taskOrderForType`), `taskOrderForType` is always undefined as it should be looking up `state.user.data.tasksOrder[${type}s]` instead.

Possibly this is recorded and being fixed somewhere else, but I haven't seen anything obvious. However, as far as I can tell, this hasn't caused any problems with sorting for me.

So then I guess the question is whether group tasks should also be sorted in both places. My feeling is that if the second sort was working then the first would not be necessary, but at the moment the second sort doesn't appear to work.

As a separate bug but still related to this issue, it seems that when you try to sort tasks you've been assigned in a group, it tries to sort them as part of the group rather than as part of your task list, and as a result it doesn't stay in its new place when you refresh, and shows up in the groups `tasksOrder` object.

**Comment by veeeeeee** [comment]
Closing issue because this is accounted for in our roadmap and issue duplication is interfering with current processes.
