### ISSUE TITLE
+ only habit suggestion

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#971]
- only habit are like a bonus habit. Like "organize computer". Don't make them become yellow if I haven't done them for a day.

**Comment by lefnire** [comment]
unfortunately this has been debated long and hard, and we're sticking with
the decision we've come to. It used to be as you outlined, we've migrated
to the new situation. it goes green as you do it more often, and then each
day slowly falls back to 0 (yellow). This because (1) if you haven't done a
habit in a long time, it will devalue, (2) you can still get points for
up-only habits over time (it doesn't stay so blue it's worthless)
