### ISSUE TITLE
Performance issue / unresponsive JavaScript

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#976]
Nota bene : I have many habits and many todos.

Quite often, when I load the page or it reloads itself, it takes a while, Firefox becomes unresponsive and I get a popup message proposing to kill a JS script (Script : https://habitrpg.com/gen/k8kgvmpZFPEv0RNzkZIZhQ.js:8 -- the exact script name change in time).

It has been happening for 2-3 days on both Windows and Ubuntu, and it has made HabitRPG very difficult to use.

**Comment by lefnire** [comment]
Can you check if you have a lot of completed todos? "Completed" tab under
your todos, if so hit "Clear Completed" and see if that increases
performance

**Comment by Eusebius** [comment]
No, I flush them on a regular basis now.

**Comment by mendingwall** [comment]
this is constantly happening for me too. I was keeping my Completeds for my own records/sake, but if it helps to flush them, I'll definitely start doing that.

**Comment by Eusebius** [comment]
The first page load of a day, with the resetting of the dailies, seems to be particularly difficult.

**Comment by lefnire** [comment]
i think it's simply that task computations have gotten so complex. two things, (1) we developers will just need to keep a keen eye out for JS optimizations as often as we can, (2) @yangit has done a refactoring of task calcs out into https://github.com/habitrpg/habitrpg-shared - which, when I retrofit the website to use, will cut back on `model.set()` operations and drastically improve this issue. So this should hopefully get fixed in the next week or two

**Comment by Eusebius** [comment]
Same as #686 ?

**Comment by mutedgrey** [comment]
I'm having so much difficulty with this, it's becoming near impossible to use habitrpg anymore. I almost dread trying to load the page because it becomes a 10-15 minute ordeal. Has there been a suggestion for an option to not log completed todos at all? I personally don't need them at all and would prefer they weren't kept so I don't have to keep deleting them.

If it's at all helpful: I use Firefox. This has been an issue through several Firefox updates including the 22.0 Firefox beta I'm using now. My java is up to date. These are the unresponsive script issues I keep getting: 

A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.
Script: https://habitrpg.com/gen/Tfkd6Fz4QinKC3BcBp0jSQ.js:16
Script: https://habitrpg.com/gen/Tfkd6Fz4QinKC3BcBp0jSQ.js:8

**Comment by Eusebius** [comment]
On FF/Linux, HabitRPG has become unusable for me. Loaded in a tab, it responds only after several minutes and a dozen of "unresponsive script" dialog boxes, and it hampers the performance and usability of the whole system. HabitRPG is definitely not the only entity responsible for the situation (my FF is too CPU-consuming and I can't find out why), but I must now stop using HabitRPG on Linux.

**Comment by wizonesolutions** [comment]
@gpeus Same with https://beta.habitrpg.com?

**Comment by Eusebius** [comment]
Yes, I switched to beta a while ago.

**Comment by Chichirinoda** [comment]
This has been happening to me for approximately a week, as well. I'm also using Firefox and Windows 7.

Sometimes I get the notification of an unresponsive script 5-6 times when I load the website for the first time in a day. If I leave the tab open for more than 10-15 minutes, it'll notify me again, interrupting whatever I'm doing. It helps to tell the script to "stop" rather than "continue", but that sometimes affects the functionality of the site.

I tried switching back to the original non-beta site and it seemed to help, but didn't clear up the problem, just reduced the number of times it would hang before finally loading the entire page.

On the beta site, I just tried clearing out my old to-dos. It didn't solve the problem, as when I was clearing it, and then returning to the "remaining" tab for the to dos, it hung three times. 

Just in the last 15 minutes, the following scripts are the ones that came up:
Script: https://beta.habitrpg.com/gen/PA5bZ9txbucfaaWdvvhlFA.js:4
Script: https://beta.habitrpg.com/gen/PA5bZ9txbucfaaWdvvhlFA.js:8

the js:8 one came up 3 times and the js:4 was once. This wasn't the first time I loaded the site today, though, so it wasn't as bad as earlier.

I hope the new build fixes this or you can find the problem, because it's making the site virtually unusable. I may need to go to the tavern and wait until it's resolved.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by marcelosizer** [comment]
I stumbled across this issue a few days back. I cleared the errors before looking at firefox's web console so now I'm not getting the error and there's probably no relevant information there but I can copy it here if needed. Also the issue will probably return when my completed todos start piling up again.

I'm using Firefox 25 and Linux and my ID is: b4597033-349c-4282-8aa3-1fa56047cf7f

The following are some of the errors that I got:

![habit error](https://f.cloud.github.com/assets/6205335/1768042/dac234a8-675c-11e3-8cbc-5e3f62e478b8.png)
![habit error1](https://f.cloud.github.com/assets/6205335/1768043/dd4fa4d0-675c-11e3-9fd0-1b96823124ca.png)
![habit error2](https://f.cloud.github.com/assets/6205335/1768044/dfcf177c-675c-11e3-8388-9f59004d9010.png)
