### ISSUE TITLE
achievement modals close themselves rapidly (Rebirth, Streak, maybe others)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9770]
When you use an Orb of Rebirth or get a 21-day streak on a Daily, you see an achievement modal, however the modal closes after a couple of seconds, giving you no time to read it.

The desired behaviour is that it stays open until you click the button at the bottom of it.

citrusella, the serving wench reported it, with this suggestion:
"There's a window that pops up right after you rebirth, but it's impossible to read because Habitica immediately refreshes upon rebirth. Not sure if this is a bug or just an oversight, but... (Maybe a solution is to make the close button the modal the part that refreshes the site? Is that even possible?)"

However the reload isn't relevant to the Streak achievement, so there might need to be two aspects of a fix for this issue (one to make all achievement modals stay open and another to prevent the Rebirth reload until you've closed the modal).

I'm marking this suggestion-discussion for a few days for staff to comment on how they'd like it to be fixed.

**Comment by citrusella** [comment]
For what it's worth, the modal never technically closed in my case; rather, the whole page did a full refresh (rather than a sync, it loaded the purple screen with the tip again), so quickly after the action/modal that it wasn't readable.

That is to say, the process was:

+ Click rebirth (which no longer has the information about itself in the purchase modal; is that intended?)  
+ Modal pops up with message that includes "this is your [x (i.e. seventh)] rebirth" (the information at that point said it was my seventh, too, so it might not have been current before the refresh)  
+ Site did a full refresh before the modal had sat around long enough to be read or even touched
  
EDIT: Aah, I've been thinking messages didn't say things they actually did say all week. I think I need a break. DX

**Comment by TheHollidayInn** [comment]
I'm adding tags to this. I think at least for some, we can do the refresh after the confirmation button.

**Comment by TheHollidayInn** [comment]
@negue Can you apply the snackbar UX to the rebirth and streak achievements for this issue as well?

**Comment by Alys** [comment]
This is probably no longer relevant since there's been several changes to modals since it was logged.  The streak achievement modal certainly doesn't close itself.
