### ISSUE TITLE
misaligned count of new Private Messages in Firefox

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9774]
In Firefox 57 (and maybe other browsers), the count of new Inbox messages is misaligned:

![screenshot_2018-01-08_18-34-05](https://user-images.githubusercontent.com/1495809/34663483-d03a6000-f4a2-11e7-8f59-1d22f97cc68b.png)

It should be aligned with the word Messages rather than under it.

**Comment by citrusella** [comment]
It might happen in lower Firefox versions, too; I'm in the latest version for the ESR channel (52.5.3) and also noticed this.

**Comment by tsujin** [comment]
After checking this on multiple browsers (edge, opera, chrome, all latest version) it appears this is unique to Firefox. I think it has something to do with the way that Firefox renders white-space between elements. If you scroll to the bottom of the menu, you'll notice the image of gold Habitica coins by the "Need More Gems?" link is also misaligned. I tinkered around a little bit with it just using element inspector in Firefox, and was able to fix it by overriding the white-space property of `.dropdown-separated` and `.dropdown-menu` to use `normal` instead of `nowrap `.

This solution looked safe and didn't break anything in Chrome from what I could see. The problem is that in the vue code [here](https://github.com/HabitRPG/habitica/blob/develop/website/client/components/ui/customMenuDropdown.vue), the `.dropdown-separated` selector is scoped /deep/, so all of the child components also inherit this css, and being unfamiliar with this code base I'm not really sure what else this would affect or if anything would break from this change.
