### ISSUE TITLE
Daily "un-checked" itself

### ISSUE THREAD

**Issue by demhips** [HabitRPG/habitica#985]
At the midnight turnover, one of the dailies I had checked off un-checked itself, docked me HP for incompletion, and broke my streak.

**Comment by AranelS** [comment]
This happens to me almost every day.  Despite the fact that I have completed (and checked off) ALL of my dailies every day since the streaks started, only the first two of my dailies have any streak remaining.  (One is at 16 and the other at 17. I have no idea why the difference.)  The remaining four are constantly coming un-checked and docking me HP.  (I'm pretty sure that yesterday I had 3 dailies with streaks intact, by the way.)

This has happened pretty consistently for a while now, but I never bothered with it because the HP loss was not nearly enough to be a problem.  However with the streaks I am now noticing it more.  

I ALWAYS reload the page at the end of the session to make sure the action has "stuck".  I have even started checking the later dailies earlier and earlier in the day.  (No improvement.)  "Todos" are updating as expected--I can add a todo at the same time that I check the dailies, and the next day it will be there, but the dailies will still have come unchecked.

**Comment by nextmike** [comment]
Yes, same issue here

**Comment by nextmike** [comment]
Bummer, this time ALL my dailies were reset :(  Related, my gold went UP a bunch at the same time.

**Comment by AranelS** [comment]
Me, too.  All reset except for one which for some reason is checked already (but is also reset to "1").  

I appear to have taken the HP hit as well.  It wasn't a huge problem because they're all well into blue.

I think my gold is about the same but I don't pay that much attention to it because I've already got the best equipment.

**Comment by nextmike** [comment]
if there's any way we can manually update/correct the lost streaks that would really help :)

**Comment by mendingwall** [comment]
yep. it happens every single day at least once for me. I was away from my list for an hour and had five uncheck themselves just now. sometimes when it happens, newly added to-do items vanish for me too.

**Comment by PhilipHow** [comment]
Hey guys, this is due to an annoying bug with the underlying data layer used by HabitRPG (Racer).

In the meantime, are you guys running HabitRPG concurrently in multiple browser windows? Running only 1 instance fixes this issue for me, but its obviously not how we intended for it to work.

**Comment by nextmike** [comment]
I only have it running in one window usually as a background tab.

**Comment by AranelS** [comment]
I run it in one tab on one window, also.  I mostly just leave the tab there open in the background as well.

**Comment by demhips** [comment]
I usually leave it running in one tab at home while I open another one at work, but the problem only ever occurs at night for me when I have one tab open.  Then again I don't usually check off much during the day.

**Comment by lefnire** [comment]
Added "Restore Streak" in Daily > Edit > Advanced Options for the time
being. Obviously that's not sufficient, I'm investigating the Racer issue

**Comment by AranelS** [comment]
The restore option really helps, but otherwise I think this problem has actually gotten worse.  I have to restore almost everything almost every day now--at first it was just one or two that would reset.

**Comment by OkamiNoRei** [comment]
I've been having the same issue.  I left the '45m Reading' option in my dailies, I've been checking it off each night before I got to bed, and it has never stayed checked through morning (two nights in a a row, now).  I'll try the 'refresh and check' fix tonight.

**Comment by nextmike** [comment]
Just thought I'd drop a note that the midnight unchecked dailies and broken streaks bug continues and seems to be getting worse.

**Comment by mendingwall** [comment]
WHOAH YEAH.

my last half-dozen dailies unchecked themselves FOUR TIMES last evening, the last time being just before the reset, and a to-do came back twice after being knocked off.

**Comment by nextmike** [comment]
At this point basically 90% of my dailies are resetting every midnight...

**Comment by Shaners** [comment]
Are you guys using habit on multiple computers or leaving habit open in a tab / window for an extended period of time?

**Comment by nextmike** [comment]
constantly stays open in a background tab on only one computer

**Comment by StanLindsey** [comment]
Do you refresh the page before/after edits? It might not be that its unchecking but that its not checking on the server in the first place.

**Comment by nextmike** [comment]
I absolutely do.  They all "stick" after a refresh....but come midnight, everything goes to hell. :(

**Comment by StanLindsey** [comment]
Alright, thanks for that info.You're not getting any javascript errors in the console are you? (F12 on windows/linux)

**Comment by AranelS** [comment]
Since I've stopped leaving the background tab open as often, this seems to be happening less--but it is still happening.  I frequently refresh. I ALWAYS refresh before clicking dailies. (Otherwise it is fairly pointless to click them as it WILL have lost the connection if I've left the tab open for a while.)  

This morning most of my dailies had streaks reset to zero AND they were all greyed out (already checked).

**Comment by nextmike** [comment]
no javascript errors here.

**Comment by Shaners** [comment]
Yea this isn't a proper solution but you can try to make sure to do a browser refresh (F5 or ctrl+F5 not the reload link) <em>before</em> you check your dailies. That seemed to help me a lot in dealing with this.

**Comment by nextmike** [comment]
related, along with unchecked dailies, my pet reverted back to one from earlier in the day yesterday.  As usual this happens around midnight

**Comment by demhips** [comment]
Worth noting, I have not had this issue since I changed my day turnover to 2AM.

**Comment by hametsunosaturn** [comment]
This same thing happened to me. I have had problems with items unchecking themselves, but if I refresh before checking, then usually they stick. All my dailies stuck just fine and because of streaks I even got items (two eggs) and gold. I hatched the eggs and got pets and did all of this before the day reset (from roughly 10pm to 2am). All night, it was fine. Come the next day, though, when the dailies reset, they all acted as if I hadn't checked them the night before, I lost all my streaks and my HP dropped down from 48 to 17. All my gold stayed and the pets I acquired through checking off the dailies stuck around.

**Comment by nextmike** [comment]
I did 2 things which seem to have made it better. I switched my end of day time to 2AM AND I stay the hell away from doing anything with HabitRPG near midnight.  Not ideal I know but seems to have worked for the last couple of days.

**Comment by hametsunosaturn** [comment]
Except I did this at 10 pm and my end of day was already set to 2 am. I normally check things off later in the day and it always works, so this was actually the first time I checked things off well before midnight! So I don't think that fix is gonna work for me.

**Comment by AndreCaseyScott** [comment]
I don't know if this is related to anything, but I always notice a second page load everyone I refresh. If I try to click anything before the second load happens, nothing ever sticks. Maybe it's how JavaScript is loading? 

Do any console errors appear after midnight when dailies uncheck? The console is a part is the developers tools in chrome.

**Comment by nextmike** [comment]
This continues to happen, less frequently but it's still happening.  No real pattern that I can see either. One day it's one Daily, the next day it's two others.  Moving the end of day to 2AM and staying far away from habitrpg after midnight has seemed to help a bit but still doesn't solve it.

**Comment by lefnire** [comment]
Sorry guys, the Habit bugs due to framework issues are spiraling out of control, and it's getting to the point where there's not much I can do as it's not Habit code. I'm working very hard on the Racer 0.5 migration, i'm going to have to put this ticket on hold until I complete that and we can verify the new framework fixes the issue.

**Comment by nextmike** [comment]
Any update here?  I literally have to do some sort of RESTORE every day at this point.

**Comment by lefnire** [comment]
We had to abandon the Derby upgrade, it was a dead end. We have to rewrite the site on Angular + Express + Mongoose. I'd never suggest something so drastic, but we're on a ticking-timebomb framework and I've already reach it's limits (as per this bug).

Here are [ways to avoid this issue](http://habitrpg.tumblr.com/post/55792029689/bug-workarounds) in the meantime, and here's [more information on the upgrade](http://habitrpg.tumblr.com/post/55655159428/0-5-upgrade-aborted-angularjs-future). Follow [that blog](http://habitrpg.tumblr.com/) for any other sorts of bugs / upgrade news.

Would that I could fix the underlying issue #165` (since it affects so many things), but it's just not something I can fix. I'm focusing on wrapping up the mobile client right now (Android app released, iOS app pending review) so that people can have something with the bare necessities that functions, then I'm going to patch up a few bits on the main site - which should _help mitigate_ this bug, but not fix it. Then this weekend and next week I'm going full-steam on the rewrite

**Comment by nextmike** [comment]
Thanks for the update and tips!   I'll persist since I know there's hope at the end of the tunnel...

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
