### ISSUE TITLE
Quests that cannot be started should have a clear message saying that

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9936]
When you own a Quest scrolll but are currently not allowed to use it to start a Quest (e.g., because you are not high level enough to start it), it should be obvious why you can't use it when you look at the scroll in your Inventory or in the Party page when you have clicked the button to choose a quest.

Currently, there is no indication that you're not allowed to start such a quest. If you try to, the button does not respond, making it look like there's a bug. Here's an example of one of those "bug" reports:

_"Hi, I've been trying to start a quest with my party, but the "Start Quest" button doesn't seem to work. I click on the button, but then everything goes light and just stops there. If I click outside the 'Quests' area, the box disappears, but it still doesn't show up in my party that there is a quest invitation. Could someone please help?"_

@Tressley for a design to make this make more sense to the users

**Comment by leonsilicon** [comment]
I've noticed that if you try to start a quest that you aren't allowed to and immediately click outside the quest pop-up area, you will see a message telling you the requirements for the quest. I think the bug is the fact that the message doesn't appear when the quest screen is active – but rather beneath the screen, obscuring its view from the user.
Screen Recording:
https://drive.google.com/open?id=1GP5FSP2aySpQKFBPL1549RyCQrsiTGvs

**Comment by Alys** [comment]
@leonzalion Thanks very much for reporting that and providing the video! Most useful!

I'm marking this as needs designs for @Tressley

**Comment by Tressley** [comment]
I believe progress has been made on this issue since it was originally opened. Trying to start a level-locked Quest shows a snack notification error.
![image](https://user-images.githubusercontent.com/2686586/52645939-c887ac80-2eaf-11e9-8f36-7c485acea728.png)

In the mean time, for additional clarity, I think we should disable the button with tooltip that states why the quest is locked.

**Comment by veeeeeee** [comment]
After some discussion, we have decided that quest owners should be able to start quests for all scrolls they own regardless of level requirement, since they presumably acquired quest legitimately and are now experienced players. Likely solution is to remove level check for starting quests or inviting people to a quest. @Alys can you confirm and perhaps update initial post and title for clarity?

**Comment by Alys** [comment]
@veeeeeee That's a nice idea! Is this what you had in mind? https://github.com/HabitRPG/habitica/issues/12417 I thought it would be clearer to create a new issue.

**Comment by SabreCat** [comment]
That looks good to me!

**Comment by veeeeeee** [comment]
Great writeup! Thanks, @Alys. Closing this issue now :) 

Also, credit goes to @saraolson for bringing up this solution.
