### ISSUE TITLE
Staying in the Inn doesn't stop you from Dying?

### ISSUE THREAD

**Issue by WhitneyFox** [HabitRPG/habitica#997]
I went on vacation and had no internet access so I put myself in the Inn, but I just came back today and was told I'd died.

**Comment by StanLindsey** [comment]
It should stop you from dying. Unless you use the API to down-vote a habit? @lefnire

**Comment by wc8** [comment]
I experienced the same thing, but thought it was a fluke/related to a separate bug that was resolved.

**Comment by WhitneyFox** [comment]
@SlappyBag, seeing as I don't know what "use the API to down-vote a habit" means, I'm going to assume I didn't do that. I'm still in the Inn, didn't check out, but I'm still able to complete tasks and earn XP and gold. Shouldn't my whole profile be on hold while I'm in the Inn?

**Comment by wildcate** [comment]
I had the same issue with the "rest in tavern" a while back, though I thought it might have been due to my clicking rest, leave tavern, rest again...

**Comment by seajules** [comment]
I just had this same issue.  I checked into the inn Thursday night because I had surgery on Friday, and wasn't able to check in again until today.  The directions for checking into the inn say dailies will no longer impact your HP, so anyone checked in should _not_ be dying.

**Comment by dendrobatid** [comment]
Hey, I'm rather new to GitHub, so I don't know how to make this change, but the problem here seems rather simple.

The 'resting' flag that gets toggled when you enter the inn doesn't get checked anywhere (except for creating the player avatar 'Zzz' :P) 

I have a fix (about two lines of code). How do I go about uploading it?

**Comment by maggick** [comment]
you can just do on the file in the code tree and click on the "edit button"

**Comment by dendrobatid** [comment]
I tried to, but /src/app/scoring.coffee appears to have vanished since I looked at the code earlier this morning.

**Comment by lefnire** [comment]
@allrealelements we would love you forever for a PR! most website logic has been moved to a shared repo so other clients can use the algorithms, sprites, etc. Here's your guy: https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee

**Comment by dendrobatid** [comment]
Thanks lefnire! Looks like you guys merged the files right after I stopped looking at them this morning. I'm a little new to github and coding in general, so I'm not sure I did this correctly, but I sent my pull request. 

Let me know if there's anything I should've done differently, and I hope this helps!

**Comment by powerisall** [comment]
Question: would the fact that the user schema isn't defined with a resting flag cause this sort of issue?

Looking at https://github.com/HabitRPG/habitrpg-shared/blob/master/script/helpers.coffee#L52 I see flags for partyEnabled and itemsEnabled, but not one called rest.  Would setting a default value there fix it?

If not, where is flags.rest initialized?

**Comment by switz** [comment]
No, it would not. By default it doesn't exist, which to javascript is somewhat equivalent to false when checking that flag. Nice idea though.

**Comment by powerisall** [comment]
I'm guessing it assumes a null value?  So then how is a rest flag initialized and associated with a user?  I'm just not seeing where that could be except in the ToggleResting function.

And doesn't setting a null value to !(null) still give you a null? If not, what does it set to?

**Comment by lefnire** [comment]
Pop open chrome console, !null == true. Exactly that - the toggleResting
function does all the grunt work

**Comment by powerisall** [comment]
So then would it be possible to print out the value of flags.rest during the chron event? Just to make sure that it is returning like we think it should?

I'd do this myself, but I have no idea how to make and test a local copy on windows.

**Comment by lefnire** [comment]
You'll have to get it running locally to do any tests unfortunately,
otherwise you'll have to set a chrome debugger break-point and wait for the
next morning to test it just once on production. I've tried various things
on local, and everything works according to plan - rest==true when i'm
checked in, debugger after return statement never reached, etc. So
something funky / non-obvious is happening IMO

**Comment by powerisall** [comment]
Is there a reference page I could look at with instructions to get a local copy running?

**Comment by lefnire** [comment]
there's this: https://github.com/lefnire/habitrpg/wiki/Running-Locally - i
should probably create a video walk through too sometime, tell me if you
get stumped with that bit

**Comment by abea** [comment]
Same problem here. I tried to rest at the inn several days ago because I knew I was going to be away from the computer for a while and I just found that I died! I'm going to try to rest at the inn again, but is there anyway to get my gear restored?

**Comment by Shaners** [comment]
@abea go to Settings ­> Danger Zone: Restore

**Comment by lefnire** [comment]
For those that rest - do a refresh, then make sure you have zzz's above your character. If you don't have zzz's, the rest button-click didn't go through (ye ol' #165). I imagine this is what's wrong, and if so we should close this ticket and follow up on that one.

If, however, you _do_ have zzz's when you load habit up after some days, and you still get hurt - this bug is definitely still an issue. Does anyone recall that was effected by this bug - did you have zzz's when you experienced HP-loss, or alternatively was the tavern button "Check Out" instead of "Check In" (aka, were you definitely checked in?)

Very strange bug if so - I can't replicate it with any test cases locally, and the code is dirt simple: https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L342. It says "if the user is resting, set lastCron to today and return" - so none of the HP-losing code should even be reached.

**Comment by abea** [comment]
It's working now. I probably needed to refresh to see if it was actually
submitted as resting. Someone else mentioned the manual stat reset, which I
used, so I think it's all good now. I was not resting when I came back and
saw the HP disappear. Thanks for the help, man.

**Comment by lefnire** [comment]
Glad to see your'e still playing Alex!!

**Comment by WhitneyFox** [comment]
Hi Tyler,

I had refreshed and made sure the "ZZZ"s were above me and the inn said "Check Out", so I think my issue is still in the mystery bug. I haven't tried again since somone above was playing with the code, so it's possible it's been fixed.

**Comment by fragmental** [comment]
Anyone having a problem with this needs to make sure they have also disabled the chrome extension.  The chrome extension is not affected by staying in the inn.  Not sure about any other extensions.

**Comment by lefnire** [comment]
Yea, chrome extension will still doc you points (equiv of manually clicking `-` on a habit, will still nock you)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by startmyquest** [comment]
wow weird! I thought I was still checked into tavern since Christmas day, but came back today and somehow got "kicked out" of the tavern early? was sitting on 3 HP. That was too close. Not sure if related problem to this one before?

**Comment by SabreCat** [comment]
@AverageJoey: You're probably a victim of the database rollback that happened around Christmas. #2105. Use Fix Character Values in Settings to get yourself straightened out, sorry for the trouble!
