### ISSUE TITLE
User status modal: layout breaks when there are unallocated stats points and language is Japanese

### ISSUE THREAD

**Issue by Yutsuten** [HabitRPG/habitica#9979]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a
  * Browser: Google Chrome 64.0.3282.140 (Official build)
  * OS: Debian

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
A small layout bug but it always annoys me.
The text "points" (ポイント) and the arrow for allocating the point it out of the place when I have unallocated points.

If it is fine I can fix it myself.

![Screenshot](https://i.imgur.com/Uih1Zhm.jpg)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
Not applicable.

**Comment by Alys** [comment]
@Yutsuten Thank you for telling us about that and for offering to fix it! 

@Tressley The problem is that the boxes containing the number of points aren't large enough to hold the "pts" label in languages where the label is longer. The boxes could be adjusted to expand automatically to be the right size (possibly the best option to be sure it works for all possible translations), or could be given a larger fixed size for all languages. They could be expanded sideways or downwards. What options do you feel are best?
For reference, here's the US-English version:

![screenshot_2018-02-11_10-43-56](https://user-images.githubusercontent.com/1495809/36068087-85ca404a-0f18-11e8-9355-0da4a00788e0.png)

**Comment by Tressley** [comment]
@Alys -- The implementation of the original design is incomplete. See https://zpl.io/ad3541V for reference. With that being said, updates to this section are on our radar and we have already have a few designs planned.

**Comment by Yutsuten** [comment]
So, can my PR be accepted at least as a temporary solution, or the new design is about to go into production?
If the latter, I guess the PR can be closed...

**Comment by Alys** [comment]
@Yutsuten I've tested it and it's a good temporary solution to improve the situation for anyone using a language that takes up more space than English. Thank you!
